# Results comparison for MIST filtering of model B

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_B/default_models"

In [3]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 5.379
                             mass_smaller_3  T_eff             3.345 - 5.214
                             mass_smaller_14 T_eff             3.345 - 5.214
                             mass_smaller_30 T_eff             3.345 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.966  0.064
                             mass_smaller_3  T_eff             0.958  0.041
                             mass_smaller_14 T_eff             0.967  0.053
                             mass_smaller_30 T_eff             0.964  0.061

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.017  0.001
                             mass_smaller_3  T_eff             0.015  0.001
                             mass_smaller_14 T_eff             0.014  0.001
                             mass_smaller_30 T_eff             0.015  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.983   0.982
                             mass_smaller_3  T_eff             0.979   1.206
                             mass_smaller_14 T_eff             0.983   1.587
                             mass_smaller_30 T_eff             0.982   1.609

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.00404 / 90 : 0.03266 / 95 : 0.09054 / 99 : 0.32479
                             mass_smaller_3  T_eff              75 : 0.00586 / 90 : 0.04883 / 95 : 0.09348 / 99 : 0.18479
                             mass_smaller_14 T_eff              75 : 0.00391 / 90 : 0.02873 / 95 : 0.07799 / 99 : 0.20813
                             mass_smaller_30 T_eff              75 : 0.00382 / 90 : 0.02957 / 95 : 0.08364 / 99 : 0.28184

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             243.748
                             mass_smaller_3  T_eff             119.180
                             mass_smaller_14 T_eff             228.025
                             mass_smaller_30 T_eff             258.963

Results for the phase category with a value of 0.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 4.903
                             mass_smaller_3  T_eff             3.345 - 4.301
                             mass_smaller_14 T_eff             3.345 - 4.634
                             mass_smaller_30 T_eff             3.345 - 4.898

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.974  0.057
                             mass_smaller_3  T_eff             0.985  0.024
                             mass_smaller_14 T_eff             0.981  0.042
                             mass_smaller_30 T_eff             0.972  0.054

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.010  0.001
                             mass_smaller_3  T_eff             0.005  0.000
                             mass_smaller_14 T_eff             0.006  0.001
                             mass_smaller_30 T_eff             0.009  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.979
                             mass_smaller_3  T_eff             0.993   1.206
                             mass_smaller_14 T_eff             0.990   1.587
                             mass_smaller_30 T_eff             0.986   1.609

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff               75 : 0.00149 / 90 : 0.00507 / 95 : 0.02312 / 99 : 0.3164
                             mass_smaller_3  T_eff               75 : 0.00129 / 90 : 0.00368 / 95 : 0.0103 / 99 : 0.13197
                             mass_smaller_14 T_eff              75 : 0.00129 / 90 : 0.00349 / 95 : 0.00889 / 99 : 0.14038
                             mass_smaller_30 T_eff               75 : 0.00137 / 90 : 0.0042 / 95 : 0.01532 / 99 : 0.25128

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             243.748
                             mass_smaller_3  T_eff             119.180
                             mass_smaller_14 T_eff             228.025
                             mass_smaller_30 T_eff             258.963

Results for the phase category with a value of 2.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.425 - 4.711
                             mass_smaller_3  T_eff             3.425 - 4.277
                             mass_smaller_14 T_eff             3.425 - 4.588
                             mass_smaller_30 T_eff             3.425 - 4.675

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.975  0.050
                             mass_smaller_3  T_eff             0.844  0.057
                             mass_smaller_14 T_eff             0.956  0.052
                             mass_smaller_30 T_eff             0.970  0.050

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.020  0.002
                             mass_smaller_3  T_eff             0.033  0.008
                             mass_smaller_14 T_eff             0.022  0.003
                             mass_smaller_30 T_eff             0.021  0.002

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.704
                             mass_smaller_3  T_eff             0.920   0.300
                             mass_smaller_14 T_eff             0.978   0.697
                             mass_smaller_30 T_eff             0.985   0.713

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.01116 / 90 : 0.06942 / 95 : 0.11179 / 99 : 0.20013
                             mass_smaller_3  T_eff               75 : 0.0495 / 90 : 0.10251 / 95 : 0.13649 / 99 : 0.19511
                             mass_smaller_14 T_eff              75 : 0.01776 / 90 : 0.07706 / 95 : 0.11769 / 99 : 0.19591
                             mass_smaller_30 T_eff               75 : 0.01362 / 90 : 0.0722 / 95 : 0.11353 / 99 : 0.19463

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             243.748
                             mass_smaller_3  T_eff             119.180
                             mass_smaller_14 T_eff             228.025
                             mass_smaller_30 T_eff             258.963

Results for the phase category with a value of 3.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.352 - 5.379
                             mass_smaller_3  T_eff             3.352 - 5.214
                             mass_smaller_14 T_eff             3.352 - 5.214
                             mass_smaller_30 T_eff             3.352 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.923  0.091
                             mass_smaller_3  T_eff             0.954  0.053
                             mass_smaller_14 T_eff             0.917  0.077
                             mass_smaller_30 T_eff             0.916  0.088

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.029  0.003
                             mass_smaller_3  T_eff             0.021  0.003
                             mass_smaller_14 T_eff             0.023  0.003
                             mass_smaller_30 T_eff             0.026  0.003

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.961   0.982
                             mass_smaller_3  T_eff             0.977   1.030
                             mass_smaller_14 T_eff             0.958   0.885
                             mass_smaller_30 T_eff             0.958   0.991

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff               75 : 0.0133 / 90 : 0.06569 / 95 : 0.15397 / 99 : 0.48948
                             mass_smaller_3  T_eff              75 : 0.01446 / 90 : 0.05848 / 95 : 0.10576 / 99 : 0.25125
                             mass_smaller_14 T_eff              75 : 0.01185 / 90 : 0.04991 / 95 : 0.10873 / 99 : 0.40663
                             mass_smaller_30 T_eff              75 : 0.01159 / 90 : 0.05354 / 95 : 0.12828 / 99 : 0.49788

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             243.748
                             mass_smaller_3  T_eff             119.180
                             mass_smaller_14 T_eff             228.025
                             mass_smaller_30 T_eff             258.963

In [4]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff", "radius"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                            value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13
KNN               MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13
linear_regression MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13
mlp               MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13
random_forest     MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13
xgboost           MIST           Base   T_eff             3.345 - 5.379
                                        radius            -1.861 - 3.13

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.949  0.079  0.019
                                        radius            0.811  0.324  0.090
KNN               MIST           Base   T_eff             0.967  0.063  0.019
                                        radius            0.903  0.232  0.078
linear_regression MIST           Base   T_eff             0.697  0.191  0.147
                                        radius            0.193  0.669  0.551
mlp               MIST           Base   T_eff             0.688  0.195  0.132
                                        radius            0.559  0.499  0.327
random_forest     MIST           Base   T_eff             0.966  0.064  0.017
                                        radius            0.875  0.263  0.079
xgboost           MIST           Base   T_eff             0.896  0.112  0.070
                                        radius            0.817  0.318  0.203

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.002  0.974
                                        radius            0.005  0.906
KNN               MIST           Base   T_eff             0.002  0.983
                                        radius            0.004  0.951
linear_regression MIST           Base   T_eff             0.131  0.835
                                        radius            0.476  0.440
mlp               MIST           Base   T_eff             0.086  0.841
                                        radius            0.183  0.760
random_forest     MIST           Base   T_eff             0.001  0.983
                                        radius            0.002  0.936
xgboost           MIST           Base   T_eff             0.035  0.947
                                        radius            0.101  0.904

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              1.376
                                        radius             3.855
KNN               MIST           Base   T_eff              1.625
                                        radius             3.017
linear_regression MIST           Base   T_eff              1.529
                                        radius             2.690
mlp               MIST           Base   T_eff              1.376
                                        radius             2.923
random_forest     MIST           Base   T_eff              0.982
                                        radius             3.415
xgboost           MIST           Base   T_eff              1.173
                                        radius             2.605

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00435 / 90 : 0.02316 / 95 : 0.10232 / 99 : 0.42875
                                        radius             75 : 0.01045 / 90 : 0.11728 / 95 : 0.71138 / 99 : 1.69099
KNN               MIST           Base   T_eff               75 : 0.00637 / 90 : 0.04835 / 95 : 0.10199 / 99 : 0.3147
                                        radius             75 : 0.01818 / 90 : 0.24142 / 95 : 0.52093 / 99 : 1.09247
linear_regression MIST           Base   T_eff              75 : 0.19906 / 90 : 0.26661 / 95 : 0.34604 / 99 : 0.53699
                                        radius              75 : 0.7379 / 90 : 1.10175 / 95 : 1.30845 / 99 : 1.64825
mlp               MIST           Base   T_eff              75 : 0.17675 / 90 : 0.31647 / 95 : 0.41895 / 99 : 0.70821
                                        radius             75 : 0.48375 / 90 : 0.82558 / 95 : 1.09255 / 99 : 1.71275
random_forest     MIST           Base   T_eff              75 : 0.00404 / 90 : 0.03266 / 95 : 0.09054 / 99 : 0.32479
                                        radius              75 : 0.00985 / 90 : 0.17901 / 95 : 0.5942 / 99 : 1.31149
xgboost           MIST           Base   T_eff                 75 : 0.099 / 90 : 0.18668 / 95 : 0.2568 / 99 : 0.38126
                                        radius             75 : 0.30621 / 90 : 0.54646 / 95 : 0.69766 / 99 : 1.03829

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.995
                                        radius             17.995
KNN               MIST           Base   T_eff               6.947
                                        radius              6.947
linear_regression MIST           Base   T_eff               0.609
                                        radius              0.609
mlp               MIST           Base   T_eff             233.286
                                        radius            233.286
random_forest     MIST           Base   T_eff             243.748
                                        radius            243.748
xgboost           MIST           Base   T_eff              15.839
                                        radius             15.839

Results for the phase category with a value of 0.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
KNN               MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
linear_regression MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
mlp               MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
random_forest     MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
xgboost           MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.959  0.072  0.012
                                        radius            0.833  0.235  0.039
KNN               MIST           Base   T_eff             0.968  0.063  0.016
                                        radius            0.896  0.187  0.046
linear_regression MIST           Base   T_eff             0.753  0.177  0.151
                                        radius            0.454  0.621  0.520
mlp               MIST           Base   T_eff             0.828  0.149  0.102
                                        radius            0.678  0.341  0.213
random_forest     MIST           Base   T_eff             0.974  0.057  0.010
                                        radius            0.895  0.187  0.035
xgboost           MIST           Base   T_eff             0.939  0.093  0.051
                                        radius            0.833  0.254  0.142

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.001  0.980
                                        radius            0.003  0.925
KNN               MIST           Base   T_eff             0.001  0.984
                                        radius            0.002  0.954
linear_regression MIST           Base   T_eff             0.150  0.868
                                        radius            0.474  0.680
mlp               MIST           Base   T_eff             0.069  0.914
                                        radius            0.083  0.871
random_forest     MIST           Base   T_eff             0.001  0.987
                                        radius            0.001  0.951
xgboost           MIST           Base   T_eff             0.017  0.969
                                        radius            0.040  0.932

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              1.376
                                        radius             2.836
KNN               MIST           Base   T_eff              1.625
                                        radius             2.792
linear_regression MIST           Base   T_eff              0.710
                                        radius             2.031
mlp               MIST           Base   T_eff              1.084
                                        radius             2.401
random_forest     MIST           Base   T_eff              0.979
                                        radius             2.800
xgboost           MIST           Base   T_eff              1.173
                                        radius             2.412

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00257 / 90 : 0.00478 / 95 : 0.01203 / 99 : 0.41386
                                        radius             75 : 0.00543 / 90 : 0.01107 / 95 : 0.02174 / 99 : 1.57031
KNN               MIST           Base   T_eff                75 : 0.00324 / 90 : 0.019 / 95 : 0.09285 / 99 : 0.32869
                                        radius              75 : 0.00728 / 90 : 0.04989 / 95 : 0.27373 / 99 : 0.9764
linear_regression MIST           Base   T_eff              75 : 0.20784 / 90 : 0.25685 / 95 : 0.30418 / 99 : 0.43603
                                        radius             75 : 0.69838 / 90 : 0.99944 / 95 : 1.19713 / 99 : 1.47881
mlp               MIST           Base   T_eff                 75 : 0.1375 / 90 : 0.2459 / 95 : 0.3275 / 99 : 0.47241
                                        radius             75 : 0.32776 / 90 : 0.62784 / 95 : 0.77605 / 99 : 1.03429
random_forest     MIST           Base   T_eff               75 : 0.00149 / 90 : 0.00507 / 95 : 0.02312 / 99 : 0.3164
                                        radius              75 : 0.00317 / 90 : 0.0108 / 95 : 0.07454 / 99 : 1.10261
xgboost           MIST           Base   T_eff              75 : 0.06304 / 90 : 0.15717 / 95 : 0.22384 / 99 : 0.34881
                                        radius             75 : 0.18485 / 90 : 0.44782 / 95 : 0.59913 / 99 : 0.85795

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.995
                                        radius             17.995
KNN               MIST           Base   T_eff               6.947
                                        radius              6.947
linear_regression MIST           Base   T_eff               0.609
                                        radius              0.609
mlp               MIST           Base   T_eff             233.286
                                        radius            233.286
random_forest     MIST           Base   T_eff             243.748
                                        radius            243.748
xgboost           MIST           Base   T_eff              15.839
                                        radius             15.839

Results for the phase category with a value of 2.0

                                                            value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9
KNN               MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9
linear_regression MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9
mlp               MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9
random_forest     MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9
xgboost           MIST           Base   T_eff             3.425 - 4.711
                                        radius              0.092 - 2.9

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.959  0.064  0.024
                                        radius            0.235  0.430  0.176
KNN               MIST           Base   T_eff             0.983  0.041  0.017
                                        radius            0.648  0.292  0.125
linear_regression MIST           Base   T_eff             0.776  0.150  0.120
                                        radius            0.303  0.589  0.468
mlp               MIST           Base   T_eff             0.595  0.209  0.152
                                        radius           -0.207  0.563  0.424
random_forest     MIST           Base   T_eff             0.975  0.050  0.020
                                        radius            0.472  0.357  0.151
xgboost           MIST           Base   T_eff             0.875  0.114  0.085
                                        radius            0.497  0.352  0.265

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.003  0.980
                                        radius            0.008  0.625
KNN               MIST           Base   T_eff             0.002  0.992
                                        radius            0.005  0.810
linear_regression MIST           Base   T_eff             0.106  0.882
                                        radius            0.367  0.564
mlp               MIST           Base   T_eff             0.110  0.801
                                        radius            0.330  0.425
random_forest     MIST           Base   T_eff             0.002  0.987
                                        radius            0.005  0.721
xgboost           MIST           Base   T_eff             0.064  0.936
                                        radius            0.199  0.706

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.830
                                        radius             2.319
KNN               MIST           Base   T_eff              0.713
                                        radius             2.188
linear_regression MIST           Base   T_eff              0.626
                                        radius             1.812
mlp               MIST           Base   T_eff              1.039
                                        radius             2.549
random_forest     MIST           Base   T_eff              0.704
                                        radius             2.318
xgboost           MIST           Base   T_eff              0.532
                                        radius             1.867

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff               75 : 0.00797 / 90 : 0.08248 / 95 : 0.1382 / 99 : 0.23469
                                        radius              75 : 0.0232 / 90 : 0.75067 / 95 : 1.16694 / 99 : 1.73073
KNN               MIST           Base   T_eff               75 : 0.01092 / 90 : 0.05772 / 95 : 0.09178 / 99 : 0.1655
                                        radius             75 : 0.07762 / 90 : 0.49474 / 95 : 0.73756 / 99 : 1.16748
linear_regression MIST           Base   T_eff              75 : 0.16703 / 90 : 0.22476 / 95 : 0.29004 / 99 : 0.43443
                                        radius             75 : 0.67702 / 90 : 1.02249 / 95 : 1.20553 / 99 : 1.42675
mlp               MIST           Base   T_eff              75 : 0.21287 / 90 : 0.33703 / 95 : 0.43624 / 99 : 0.68052
                                        radius               75 : 0.57451 / 90 : 0.904 / 95 : 1.18896 / 99 : 1.75936
random_forest     MIST           Base   T_eff              75 : 0.01116 / 90 : 0.06942 / 95 : 0.11179 / 99 : 0.20013
                                        radius             75 : 0.07048 / 90 : 0.61921 / 95 : 0.93386 / 99 : 1.43872
xgboost           MIST           Base   T_eff              75 : 0.11812 / 90 : 0.18974 / 95 : 0.24525 / 99 : 0.34372
                                        radius             75 : 0.38576 / 90 : 0.58861 / 95 : 0.72567 / 99 : 1.02161

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.995
                                        radius             17.995
KNN               MIST           Base   T_eff               6.947
                                        radius              6.947
linear_regression MIST           Base   T_eff               0.609
                                        radius              0.609
mlp               MIST           Base   T_eff             233.286
                                        radius            233.286
random_forest     MIST           Base   T_eff             243.748
                                        radius            243.748
xgboost           MIST           Base   T_eff              15.839
                                        radius             15.839

Results for the phase category with a value of 3.0

                                                            value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13
KNN               MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13
linear_regression MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13
mlp               MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13
random_forest     MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13
xgboost           MIST           Base   T_eff             3.352 - 5.379
                                        radius            -1.861 - 3.13

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.888  0.110  0.033
                                        radius            0.696  0.363  0.114
KNN               MIST           Base   T_eff             0.934  0.085  0.030
                                        radius            0.859  0.249  0.098
linear_regression MIST           Base   T_eff             0.383  0.265  0.175
                                        radius            0.287  0.869  0.748
mlp               MIST           Base   T_eff             0.438  0.273  0.186
                                        radius            0.197  0.720  0.509
random_forest     MIST           Base   T_eff             0.923  0.091  0.029
                                        radius            0.808  0.289  0.099
xgboost           MIST           Base   T_eff             0.828  0.150  0.102
                                        radius            0.706  0.413  0.286

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.004  0.945
                                        radius            0.009  0.845
KNN               MIST           Base   T_eff             0.004  0.967
                                        radius            0.013  0.927
linear_regression MIST           Base   T_eff             0.112  0.648
                                        radius            0.597  0.549
mlp               MIST           Base   T_eff             0.109  0.721
                                        radius            0.305  0.536
random_forest     MIST           Base   T_eff             0.003  0.961
                                        radius            0.009  0.899
xgboost           MIST           Base   T_eff             0.065  0.910
                                        radius            0.179  0.848

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              1.225
                                        radius             3.855
KNN               MIST           Base   T_eff              0.930
                                        radius             3.017
linear_regression MIST           Base   T_eff              1.529
                                        radius             2.690
mlp               MIST           Base   T_eff              1.376
                                        radius             2.923
random_forest     MIST           Base   T_eff              0.982
                                        radius             3.415
xgboost           MIST           Base   T_eff              1.056
                                        radius             2.605

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff               75 : 0.01025 / 90 : 0.06525 / 95 : 0.1886 / 99 : 0.62989
                                        radius              75 : 0.02523 / 90 : 0.25806 / 95 : 0.7908 / 99 : 1.86425
KNN               MIST           Base   T_eff              75 : 0.02063 / 90 : 0.07355 / 95 : 0.15065 / 99 : 0.43712
                                        radius              75 : 0.0659 / 90 : 0.29572 / 95 : 0.51634 / 99 : 1.16741
linear_regression MIST           Base   T_eff                75 : 0.227 / 90 : 0.39383 / 95 : 0.51454 / 99 : 1.12928
                                        radius             75 : 0.99598 / 90 : 1.44536 / 95 : 1.61757 / 99 : 1.93729
mlp               MIST           Base   T_eff              75 : 0.26536 / 90 : 0.47416 / 95 : 0.62496 / 99 : 0.88444
                                        radius              75 : 0.7973 / 90 : 1.23862 / 95 : 1.52714 / 99 : 2.15208
random_forest     MIST           Base   T_eff               75 : 0.0133 / 90 : 0.06569 / 95 : 0.15397 / 99 : 0.48948
                                        radius             75 : 0.04011 / 90 : 0.26266 / 95 : 0.60379 / 99 : 1.48071
xgboost           MIST           Base   T_eff               75 : 0.1346 / 90 : 0.25574 / 95 : 0.33606 / 99 : 0.49433
                                        radius             75 : 0.41282 / 90 : 0.69157 / 95 : 0.85686 / 99 : 1.34699

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.995
                                        radius             17.995
KNN               MIST           Base   T_eff               6.947
                                        radius              6.947
linear_regression MIST           Base   T_eff               0.609
                                        radius              0.609
mlp               MIST           Base   T_eff             233.286
                                        radius            233.286
random_forest     MIST           Base   T_eff             243.748
                                        radius            243.748
xgboost           MIST           Base   T_eff              15.839
                                        radius             15.839

## Getting the ranges for the values

In [5]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [7]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3, 4, 5]})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.4794, Median : 8.6

log_Teff  : Range : 3.34 - 5.5871, Mean : 3.8475, Median : 3.6808

log_g  : Range : -1.14 - 8.6121, Mean : 2.1347, Median : 2.0681

Values in phase column : 0.0, 2.0, 3.0, 4.0, 5.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 298.5448, Mean : 7.3915, Median : 2.0304

log_R  : Range : -2.09 - 3.1298, Mean : 1.3543, Median : 1.4604

log_L  : Range : -3.33 - 7.069, Mean : 3.0533, Median : 3.4128

## Base vs Base_old

| Parameter      | Base                                                    | Base_old                                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 5.0 - 10.3, Mean : 8.4794, Median : 8.6        |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 298.5448, Mean : 7.3915, Median : 2.0304 |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.5871, Mean : 3.8475, Median : 3.6808  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.14 - 8.6121, Mean : 2.1347, Median : 2.0681 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -2.09 - 3.1298, Mean : 1.3543, Median : 1.4604 |

### T_eff parameter

In [13]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 5.58714
                                      log_g               -1.1449 - 8.6121
                                      radius            -2.08517 - 3.12975

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.85642  0.14016
                                      log_g             0.54794  1.32716
                                      radius            0.55631  0.66360

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.06697  0.00553
                                      log_g             0.68127  0.04931
                                      radius            0.34072  0.02471

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.92628  1.58571
                                      log_g             0.75158  7.91597
                                      radius            0.75665  3.95800

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.07494 / 90 : 0.23372 / 95 : 0.35136 / 99 : 0.56158
                                      log_g              75 : 0.89708 / 90 : 2.51135 / 95 : 3.38312 / 99 : 4.55568
                                      radius             75 : 0.44863 / 90 : 1.25577 / 95 : 1.69166 / 99 : 2.27713

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

Results for the phase category with a value of 0.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 4.90341
                                      log_g             -0.59731 - 5.43309
                                      radius            -0.99747 - 3.08275

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80304  0.17263
                                      log_g            -4.29496  1.63895
                                      radius           -0.59010  0.81950

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.08037  0.00112
                                      log_g             0.80781  0.00401
                                      radius            0.40420  0.00259

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.91864  1.58571
                                      log_g             0.37716  5.57552
                                      radius            0.54558  2.78953

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.08948 / 90 : 0.31533 / 95 : 0.45813 / 99 : 0.61607
                                      log_g              75 : 1.01317 / 90 : 3.49465 / 95 : 4.15935 / 99 : 4.80819
                                      radius             75 : 0.50708 / 90 : 1.74746 / 95 : 2.07953 / 99 : 2.40365

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

Results for the phase category with a value of 2.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.42453 - 4.70936
                                      log_g             -0.32878 - 4.40791
                                      radius             0.09099 - 2.90038

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.94674  0.07435
                                      log_g             0.01791  0.91349
                                      radius            0.15494  0.45674

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.03287  0.00312
                                      log_g             0.44481  0.01621
                                      radius            0.22241  0.00811

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.97383  0.74220
                                      log_g             0.51086  4.41580
                                      radius            0.56201  2.20794

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.03232 / 90 : 0.10811 / 95 : 0.16437 / 99 : 0.33827
                                      log_g                75 : 0.51838 / 90 : 1.7431 / 95 : 2.3302 / 99 : 3.28588
                                      radius             75 : 0.25918 / 90 : 0.87149 / 95 : 1.16491 / 99 : 1.64297

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

Results for the phase category with a value of 3.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff               3.35268 - 5.3788
                                      log_g              -1.0829 - 7.94051
                                      radius            -1.86107 - 3.12975

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.82481  0.14151
                                      log_g             0.38245  0.95863
                                      radius            0.51441  0.47939

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07242  0.01368
                                      log_g             0.54691  0.11312
                                      radius            0.27352  0.05659

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.91279  1.00208
                                      log_g             0.69035  7.50320
                                      radius            0.74976  3.75159

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09327 / 90 : 0.22966 / 95 : 0.33934 / 99 : 0.55474
                                      log_g              75 : 0.88332 / 90 : 1.79715 / 95 : 2.23395 / 99 : 3.08305
                                      radius             75 : 0.44189 / 90 : 0.89859 / 95 : 1.11736 / 99 : 1.54214

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

Results for the phase category with a value of 4.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.45594 - 5.58714
                                      log_g                -0.862 - 8.6121
                                      radius            -2.08517 - 3.07966

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.72308  0.12439
                                      log_g             0.44189  0.78065
                                      radius            0.61375  0.39029

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.05577  0.01056
                                      log_g             0.42883  0.12655
                                      radius            0.21440  0.06328

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.86655  0.89689
                                      log_g             0.71111  6.20091
                                      radius            0.80118  3.10046

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.04696 / 90 : 0.17431 / 95 : 0.30889 / 99 : 0.55789
                                      log_g               75 : 0.57144 / 90 : 1.3231 / 95 : 1.86109 / 99 : 2.91891
                                      radius             75 : 0.28573 / 90 : 0.66156 / 95 : 0.93056 / 99 : 1.45945

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

Results for the phase category with a value of 5.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34914 - 5.54353
                                      log_g              -1.1449 - 8.52744
                                      radius            -2.05402 - 3.04812

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.79922  0.13439
                                      log_g             0.17281  1.38527
                                      radius            0.28797  0.69264

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07095  0.01224
                                      log_g             0.77492  0.13864
                                      radius            0.38745  0.06932

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.90345  1.46849
                                      log_g             0.64915  7.91597
                                      radius            0.68912  3.95800

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09529 / 90 : 0.23667 / 95 : 0.33059 / 99 : 0.49124
                                      log_g                75 : 1.1798 / 90 : 2.6404 / 95 : 3.29779 / 99 : 4.45991
                                      radius             75 : 0.58971 / 90 : 1.31996 / 95 : 1.64907 / 99 : 2.23045

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             674.38852
                                      log_g             674.38852
                                      radius            674.38852

### log_g parameter

In [ ]:
compare_metrics(path, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                data_filters=["Base", "Base_old"])

### Radius parameter

In [ ]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "Base_old"])

## Base vs mass_filtered

| Parameter      | Base                                                    | mass_filtered_smaller_3                                | mass_filtered_smaller_14                               | mass_filtered_smaller_30                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5        | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289  | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537 | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357 | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### Mass parameter

In [11]:
compare_metrics(path, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9951817784001245
                                 mass_smaller_3  mass              0.9986106418886865
                                 mass_smaller_14 mass              0.9997601454617543
                                 mass_smaller_30 mass              0.9991406839290182
KNN               MIST           Base            mass              0.9895916504979603
                                 mass_smaller_3  mass              0.9984125750212497
                                 mass_smaller_14 mass              0.9993586825300925
                                 mass_smaller_30 mass              0.9987489616665379
linear_regression MIST           Base            mass              0.3028040512725666
                                 mass_smaller_3  mass              0.6829393130134978
                                 mass_smaller_14 mass              0.7182024528881572
                                 mass_smaller_30 mass              0.6353562478865478
mlp               MIST           Base            mass              0.9683844484481047
                                 mass_smaller_3  mass              0.9957994560369564
                                 mass_smaller_14 mass              0.9957429512118042
                                 mass_smaller_30 mass              0.9910387989297911
random_forest     MIST           Base            mass              0.9978054138856324
                                 mass_smaller_3  mass              0.9992541969730512
                                 mass_smaller_14 mass              0.9999027955681157
                                 mass_smaller_30 mass              0.9995751700301283
xgboost           MIST           Base            mass              0.9941191064217958
                                 mass_smaller_3  mass              0.9983728478790728
                                 mass_smaller_14 mass              0.9991338329854763
                                 mass_smaller_30 mass              0.9983246900370549

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                1.8540234102645101
                                 mass_smaller_3  mass              0.026963718784338744
                                 mass_smaller_14 mass               0.05074113157012546
                                 mass_smaller_30 mass                0.1791097504790169
KNN               MIST           Base            mass                 2.725540200848424
                                 mass_smaller_3  mass               0.02882109715471059
                                 mass_smaller_14 mass               0.08303339660200539
                                 mass_smaller_30 mass               0.21618078871368385
linear_regression MIST           Base            mass                22.232672792268552
                                 mass_smaller_3  mass                0.4073173369404139
                                 mass_smaller_14 mass                1.7391984293980214
                                 mass_smaller_30 mass                3.6895778330080313
mlp               MIST           Base            mass                4.7495233310888745
                                 mass_smaller_3  mass              0.046932506904485756
                                 mass_smaller_14 mass               0.22130418374812197
                                 mass_smaller_30 mass                  0.58249479040747
random_forest     MIST           Base            mass                1.2512629515795346
                                 mass_smaller_3  mass               0.01975564332021666
                                 mass_smaller_14 mass              0.032303072499435516
                                 mass_smaller_30 mass                0.1259379652907134
xgboost           MIST           Base            mass                 2.048301547851118
                                 mass_smaller_3  mass               0.02917938905834862
                                 mass_smaller_14 mass               0.09642318552932211
                                 mass_smaller_30 mass                0.2500863536782665

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.2004890397009006
                                 mass_smaller_3  mass              0.007951005822130222
                                 mass_smaller_14 mass               0.01627000483643594
                                 mass_smaller_30 mass               0.02839383501351096
KNN               MIST           Base            mass                0.3284718050123655
                                 mass_smaller_3  mass              0.011522296950541105
                                 mass_smaller_14 mass              0.028871276327017265
                                 mass_smaller_30 mass              0.051584393766063746
linear_regression MIST           Base            mass                11.348863115209971
                                 mass_smaller_3  mass               0.29751414476924204
                                 mass_smaller_14 mass                 1.302487570019859
                                 mass_smaller_30 mass                 2.621585630069494
mlp               MIST           Base            mass                1.2799196546015692
                                 mass_smaller_3  mass               0.03016257064520546
                                 mass_smaller_14 mass               0.13516429917558018
                                 mass_smaller_30 mass                0.2231004807891727
random_forest     MIST           Base            mass                0.1452769419896218
                                 mass_smaller_3  mass              0.006025796628853846
                                 mass_smaller_14 mass              0.011467443313132219
                                 mass_smaller_30 mass               0.02050023057819933
xgboost           MIST           Base            mass                0.5307691028961596
                                 mass_smaller_3  mass               0.01614069138603855
                                 mass_smaller_14 mass               0.05506889824914695
                                 mass_smaller_30 mass               0.11284521671968925

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0034602257578986995
                                 mass_smaller_3  mass               0.002184038421144674
                                 mass_smaller_14 mass               0.002748005091117056
                                 mass_smaller_30 mass              0.0029558698063406053
KNN               MIST           Base            mass               0.008160595183567931
                                 mass_smaller_3  mass               0.004450027263839751
                                 mass_smaller_14 mass                0.00651099038010422
                                 mass_smaller_30 mass               0.006974818415286188
linear_regression MIST           Base            mass                  8.184788827830257
                                 mass_smaller_3  mass                0.23046762251371206
                                 mass_smaller_14 mass                 0.9606817542642885
                                 mass_smaller_30 mass                 2.0032717486215152
mlp               MIST           Base            mass                  0.277050288859769
                                 mass_smaller_3  mass               0.020107033844202427
                                 mass_smaller_14 mass                0.08026400122756361
                                 mass_smaller_30 mass                0.10754459115846882
random_forest     MIST           Base            mass               0.004111252117102282
                                 mass_smaller_3  mass              0.0020703142458058377
                                 mass_smaller_14 mass              0.0032917922223517637
                                 mass_smaller_30 mass               0.003458677388648246
xgboost           MIST           Base            mass                0.09905868717464794
                                 mass_smaller_3  mass               0.009581761178914294
                                 mass_smaller_14 mass               0.029048159770226345
                                 mass_smaller_30 mass                0.04711784331134594

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.997589753636418
                                 mass_smaller_3  mass              0.9993051684300485
                                 mass_smaller_14 mass               0.999880065544744
                                 mass_smaller_30 mass              0.9995704381006548
KNN               MIST           Base            mass              0.9948902170346177
                                 mass_smaller_3  mass              0.9992078031704579
                                 mass_smaller_14 mass              0.9996845742622721
                                 mass_smaller_30 mass              0.9993801074893462
linear_regression MIST           Base            mass              0.5502763411107902
                                 mass_smaller_3  mass              0.8264014246305732
                                 mass_smaller_14 mass              0.8474682607151306
                                 mass_smaller_30 mass              0.7970923710251078
mlp               MIST           Base            mass              0.9841319605524157
                                 mass_smaller_3  mass              0.9978975695374722
                                 mass_smaller_14 mass              0.9978783083372683
                                 mass_smaller_30 mass              0.9955136659238233
random_forest     MIST           Base            mass              0.9989035373674631
                                 mass_smaller_3  mass              0.9996270807690646
                                 mass_smaller_14 mass              0.9999514271472582
                                 mass_smaller_30 mass              0.9997875719753877
xgboost           MIST           Base            mass              0.9970552947594146
                                 mass_smaller_3  mass               0.999186127126375
                                 mass_smaller_14 mass               0.999566862464581
                                 mass_smaller_30 mass              0.9991620166265157

                                                                               MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.65813444621273
                                 mass_smaller_3  mass              2.0171919805222065
                                 mass_smaller_14 mass               4.851878152156933
                                 mass_smaller_30 mass               12.04844243089262
KNN               MIST           Base            mass              144.21389375194437
                                 mass_smaller_3  mass              1.0215474131655333
                                 mass_smaller_14 mass               2.556474999289428
                                 mass_smaller_30 mass               8.318905246830845
linear_regression MIST           Base            mass               257.8052486889697
                                 mass_smaller_3  mass              2.8242406186495193
                                 mass_smaller_14 mass               7.499946999587877
                                 mass_smaller_30 mass              18.822455635855913
mlp               MIST           Base            mass              179.18165022433564
                                 mass_smaller_3  mass              1.1380741028372034
                                 mass_smaller_14 mass              3.8791764112049805
                                 mass_smaller_30 mass              14.269413882997462
random_forest     MIST           Base            mass               95.14828406903314
                                 mass_smaller_3  mass              1.3490965095666518
                                 mass_smaller_14 mass              1.9715440625856822
                                 mass_smaller_30 mass               8.346774873747222
xgboost           MIST           Base            mass               72.95365928611318
                                 mass_smaller_3  mass               1.164764377165806
                                 mass_smaller_14 mass               2.302518392782492
                                 mass_smaller_30 mass               6.026359547816558

                                                                                                                        Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                    75 : 0.01985 / 90 : 0.10435 / 95 : 0.35217 / 99 : 4.54997
                                 mass_smaller_3  mass                     75 : 0.00666 / 90 : 0.0177 / 95 : 0.03052 / 99 : 0.08782
                                 mass_smaller_14 mass                     75 : 0.01184 / 90 : 0.0381 / 95 : 0.07309 / 99 : 0.22189
                                 mass_smaller_30 mass                    75 : 0.01407 / 90 : 0.05157 / 95 : 0.10808 / 99 : 0.37967
KNN               MIST           Base            mass                    75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                 mass_smaller_3  mass                       75 : 0.01148 / 90 : 0.025 / 95 : 0.04245 / 99 : 0.1307
                                 mass_smaller_14 mass                    75 : 0.02367 / 90 : 0.07444 / 95 : 0.12844 / 99 : 0.32046
                                 mass_smaller_30 mass                    75 : 0.02856 / 90 : 0.10287 / 95 : 0.20168 / 99 : 0.74883
linear_regression MIST           Base            mass               75 : 13.64283 / 90 : 17.69162 / 95 : 21.44649 / 99 : 105.07348
                                 mass_smaller_3  mass                     75 : 0.4196 / 90 : 0.64407 / 95 : 0.78036 / 99 : 1.14907
                                 mass_smaller_14 mass                        75 : 1.7626 / 90 : 2.825 / 95 : 3.6225 / 99 : 5.65866
                                 mass_smaller_30 mass                   75 : 3.21003 / 90 : 5.18832 / 95 : 7.54665 / 99 : 14.48924
mlp               MIST           Base            mass                   75 : 0.57742 / 90 : 2.19642 / 95 : 5.39114 / 99 : 21.87825
                                 mass_smaller_3  mass                    75 : 0.03915 / 90 : 0.06589 / 95 : 0.08732 / 99 : 0.16978
                                 mass_smaller_14 mass                    75 : 0.17441 / 90 : 0.32813 / 95 : 0.44328 / 99 : 0.73971
                                 mass_smaller_30 mass                     75 : 0.19279 / 90 : 0.38486 / 95 : 0.71174 / 99 : 2.7018
random_forest     MIST           Base            mass                      75 : 0.0156 / 90 : 0.0791 / 95 : 0.29069 / 99 : 3.22241
                                 mass_smaller_3  mass                    75 : 0.00554 / 90 : 0.01225 / 95 : 0.01942 / 99 : 0.06893
                                 mass_smaller_14 mass                    75 : 0.00982 / 90 : 0.02527 / 95 : 0.04712 / 99 : 0.13786
                                 mass_smaller_30 mass                    75 : 0.01095 / 90 : 0.03264 / 95 : 0.06834 / 99 : 0.27095
xgboost           MIST           Base            mass                     75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                 mass_smaller_3  mass                    75 : 0.01928 / 90 : 0.03504 / 95 : 0.05155 / 99 : 0.10739
                                 mass_smaller_14 mass                    75 : 0.06653 / 90 : 0.13176 / 95 : 0.19244 / 99 : 0.37198
                                 mass_smaller_30 mass                    75 : 0.11815 / 90 : 0.25599 / 95 : 0.41145 / 99 : 1.06755

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808
                                 mass_smaller_14 mass               18.232510805130005

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass               0.099998052173157 - 29.999136881366123

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9935567994940296
                                 mass_smaller_3  mass              0.9998109603044399
                                 mass_smaller_14 mass              0.9997672373377944
                                 mass_smaller_30 mass              0.9989288712610146
KNN               MIST           Base            mass              0.9843387655163102
                                 mass_smaller_3  mass              0.9992443930168096
                                 mass_smaller_14 mass              0.9991555335313982
                                 mass_smaller_30 mass              0.9982834222549964
linear_regression MIST           Base            mass              0.2729320152593433
                                 mass_smaller_3  mass              0.8226816036408051
                                 mass_smaller_14 mass               0.697370236171527
                                 mass_smaller_30 mass              0.5900168063755837
mlp               MIST           Base            mass              0.9649620036835357
                                 mass_smaller_3  mass              0.9982370025646433
                                 mass_smaller_14 mass              0.9962005204185861
                                 mass_smaller_30 mass              0.9892189263562553
random_forest     MIST           Base            mass              0.9973575906750899
                                 mass_smaller_3  mass               0.999947044394285
                                 mass_smaller_14 mass              0.9999272514194347
                                 mass_smaller_30 mass              0.9995217371179236
xgboost           MIST           Base            mass              0.9910072956179956
                                 mass_smaller_3  mass              0.9990403957488978
                                 mass_smaller_14 mass              0.9988060825951395
                                 mass_smaller_30 mass              0.9975490361796097

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 2.111164723262909
                                 mass_smaller_3  mass              0.010370181942051407
                                 mass_smaller_14 mass               0.05036105462129625
                                 mass_smaller_30 mass               0.20479451317293032
KNN               MIST           Base            mass                 3.292362185047644
                                 mass_smaller_3  mass               0.02073170340400842
                                 mass_smaller_14 mass               0.09599350162514116
                                 mass_smaller_30 mass               0.25937800608796263
linear_regression MIST           Base            mass                  22.4488919414279
                                 mass_smaller_3  mass                 0.318923392743888
                                 mass_smaller_14 mass                1.8158852607125213
                                 mass_smaller_30 mass                 4.008290647078625
mlp               MIST           Base            mass                 4.923128306127916
                                 mass_smaller_3  mass                0.0322376724352715
                                 mass_smaller_14 mass               0.20508645874586898
                                 mass_smaller_30 mass                0.6553437928307626
random_forest     MIST           Base            mass                1.3521665845754873
                                 mass_smaller_3  mass              0.005488828615455466
                                 mass_smaller_14 mass                0.0281557728235542
                                 mass_smaller_30 mass               0.13685222105468756
xgboost           MIST           Base            mass                 2.494119573996689
                                 mass_smaller_3  mass              0.023363529700188942
                                 mass_smaller_14 mass                0.1140586552050052
                                 mass_smaller_30 mass                0.3098067234614947

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.26982874335994456
                                 mass_smaller_3  mass              0.005151362084081304
                                 mass_smaller_14 mass              0.017034433210483306
                                 mass_smaller_30 mass                0.0370962150739012
KNN               MIST           Base            mass                0.4317822333077811
                                 mass_smaller_3  mass              0.009679770503752662
                                 mass_smaller_14 mass               0.03094177454160305
                                 mass_smaller_30 mass               0.06437274262130681
linear_regression MIST           Base            mass                13.033422245611522
                                 mass_smaller_3  mass                0.2468843962705581
                                 mass_smaller_14 mass                 1.455151466013522
                                 mass_smaller_30 mass                 3.117793007190051
mlp               MIST           Base            mass                1.3415952237953057
                                 mass_smaller_3  mass              0.021222096159887786
                                 mass_smaller_14 mass               0.10801455864156208
                                 mass_smaller_30 mass               0.24864924690696194
random_forest     MIST           Base            mass               0.16783299547779296
                                 mass_smaller_3  mass              0.002764338682723445
                                 mass_smaller_14 mass              0.008851647808148724
                                 mass_smaller_30 mass               0.02297187959691604
xgboost           MIST           Base            mass                0.6773915424575189
                                 mass_smaller_3  mass               0.01561878702027606
                                 mass_smaller_14 mass               0.06421166827237894
                                 mass_smaller_30 mass               0.14257505112937668

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0059165484966978155
                                 mass_smaller_3  mass               0.002431496292047308
                                 mass_smaller_14 mass              0.0041133571597045115
                                 mass_smaller_30 mass               0.004833033082474181
KNN               MIST           Base            mass               0.010309898110725357
                                 mass_smaller_3  mass               0.004370990974717159
                                 mass_smaller_14 mass               0.007145193322956933
                                 mass_smaller_30 mass               0.008397858904385935
linear_regression MIST           Base            mass                 11.068983544383217
                                 mass_smaller_3  mass                 0.1981865105082724
                                 mass_smaller_14 mass                 1.1925945561032538
                                 mass_smaller_30 mass                 2.6977987874340066
mlp               MIST           Base            mass                0.29043916463582464
                                 mass_smaller_3  mass               0.014953144263897489
                                 mass_smaller_14 mass                0.05104043969616057
                                 mass_smaller_30 mass                0.10388373332624068
random_forest     MIST           Base            mass              0.0035490560629605206
                                 mass_smaller_3  mass              0.0013470803912696283
                                 mass_smaller_14 mass               0.002466730917954685
                                 mass_smaller_30 mass              0.0027996199106907205
xgboost           MIST           Base            mass                0.12578609649357553
                                 mass_smaller_3  mass               0.010246877570266266
                                 mass_smaller_14 mass               0.032417196436711926
                                 mass_smaller_30 mass                0.05550889952113919

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9967888598703755
                                 mass_smaller_3  mass              0.9999054840622302
                                 mass_smaller_14 mass              0.9998836229716056
                                 mass_smaller_30 mass              0.9994644970550393
KNN               MIST           Base            mass              0.9924111983284241
                                 mass_smaller_3  mass              0.9996260930156877
                                 mass_smaller_14 mass              0.9995872073184232
                                 mass_smaller_30 mass              0.9991558637442133
linear_regression MIST           Base            mass              0.5334771169192601
                                 mass_smaller_3  mass              0.9082925664189878
                                 mass_smaller_14 mass              0.8485152328791816
                                 mass_smaller_30 mass              0.7793471254495024
mlp               MIST           Base            mass              0.9826529817996816
                                 mass_smaller_3  mass              0.9991181560916915
                                 mass_smaller_14 mass              0.9981009515325953
                                 mass_smaller_30 mass              0.9946777408096366
random_forest     MIST           Base            mass              0.9986793327165373
                                 mass_smaller_3  mass              0.9999735435321911
                                 mass_smaller_14 mass              0.9999636292504032
                                 mass_smaller_30 mass              0.9997608401017831
xgboost           MIST           Base            mass              0.9955145412428942
                                 mass_smaller_3  mass              0.9995201456664305
                                 mass_smaller_14 mass              0.9994029428086492
                                 mass_smaller_30 mass              0.9987741345996765

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               131.77529017024463
                                 mass_smaller_3  mass              0.34190413977015777
                                 mass_smaller_14 mass                4.851878152156933
                                 mass_smaller_30 mass                12.04844243089262
KNN               MIST           Base            mass               126.67441415982648
                                 mass_smaller_3  mass               0.3698302020229671
                                 mass_smaller_14 mass                2.556474999289428
                                 mass_smaller_30 mass                7.274123107442772
linear_regression MIST           Base            mass                257.8052486889697
                                 mass_smaller_3  mass               1.0632048095338902
                                 mass_smaller_14 mass                7.499946999587877
                                 mass_smaller_30 mass               18.822455635855913
mlp               MIST           Base            mass                127.1406465947268
                                 mass_smaller_3  mass               0.4656359153324776
                                 mass_smaller_14 mass               3.8791764112049805
                                 mass_smaller_30 mass               11.688757569553768
random_forest     MIST           Base            mass                83.61091180145692
                                 mass_smaller_3  mass              0.18157378789633682
                                 mass_smaller_14 mass               1.9715440625856822
                                 mass_smaller_30 mass               6.6550974787690045
xgboost           MIST           Base            mass                72.95365928611318
                                 mass_smaller_3  mass              0.33286654519153314
                                 mass_smaller_14 mass                2.302518392782492
                                 mass_smaller_30 mass                6.026359547816558

                                                                                                                        Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                    75 : 0.03086 / 90 : 0.18472 / 95 : 0.67029 / 99 : 5.91802
                                 mass_smaller_3  mass                    75 : 0.00584 / 90 : 0.01193 / 95 : 0.01927 / 99 : 0.04066
                                 mass_smaller_14 mass                    75 : 0.01359 / 90 : 0.04207 / 95 : 0.07437 / 99 : 0.19679
                                 mass_smaller_30 mass                       75 : 0.0185 / 90 : 0.06886 / 95 : 0.1401 / 99 : 0.5168
KNN               MIST           Base            mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                 mass_smaller_3  mass                    75 : 0.01053 / 90 : 0.02183 / 95 : 0.03434 / 99 : 0.09292
                                 mass_smaller_14 mass                     75 : 0.0245 / 90 : 0.06972 / 95 : 0.12383 / 99 : 0.38366
                                 mass_smaller_30 mass                    75 : 0.03339 / 90 : 0.12123 / 95 : 0.26538 / 99 : 1.01642
linear_regression MIST           Base            mass               75 : 15.13979 / 90 : 18.65289 / 95 : 21.10003 / 99 : 102.90302
                                 mass_smaller_3  mass                    75 : 0.35855 / 90 : 0.55457 / 95 : 0.66376 / 99 : 0.80961
                                 mass_smaller_14 mass                    75 : 2.07305 / 90 : 2.88755 / 95 : 3.41735 / 99 : 5.10881
                                 mass_smaller_30 mass                     75 : 4.0861 / 90 : 5.4692 / 95 : 7.10866 / 99 : 14.14449
mlp               MIST           Base            mass                   75 : 0.64487 / 90 : 2.45842 / 95 : 5.63469 / 99 : 21.93746
                                 mass_smaller_3  mass                    75 : 0.02736 / 90 : 0.04468 / 95 : 0.06067 / 99 : 0.11131
                                 mass_smaller_14 mass                    75 : 0.12905 / 90 : 0.27429 / 95 : 0.38413 / 99 : 0.69121
                                 mass_smaller_30 mass                    75 : 0.19513 / 90 : 0.44854 / 95 : 0.88354 / 99 : 3.43365
random_forest     MIST           Base            mass                     75 : 0.01627 / 90 : 0.10846 / 95 : 0.41678 / 99 : 3.6048
                                 mass_smaller_3  mass                    75 : 0.00319 / 90 : 0.00646 / 95 : 0.00971 / 99 : 0.02179
                                 mass_smaller_14 mass                    75 : 0.00718 / 90 : 0.01964 / 95 : 0.03508 / 99 : 0.10437
                                 mass_smaller_30 mass                    75 : 0.00956 / 90 : 0.03289 / 95 : 0.07556 / 99 : 0.36187
xgboost           MIST           Base            mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                 mass_smaller_3  mass                    75 : 0.02029 / 90 : 0.03559 / 95 : 0.04925 / 99 : 0.08368
                                 mass_smaller_14 mass                     75 : 0.07761 / 90 : 0.1563 / 95 : 0.22953 / 99 : 0.44861
                                 mass_smaller_30 mass                    75 : 0.14442 / 90 : 0.33701 / 95 : 0.56422 / 99 : 1.35897

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485
KNN               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485
linear_regression MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485
mlp               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485
random_forest     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485
xgboost           MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6538581961218565 - 29.67887151062485

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9991682912199935
                                 mass_smaller_3  mass               0.9992078967946935
                                 mass_smaller_14 mass               0.9999461137434603
                                 mass_smaller_30 mass               0.9998856763326173
KNN               MIST           Base            mass               0.9993836364150782
                                 mass_smaller_3  mass               0.9991876883590323
                                 mass_smaller_14 mass               0.9997771557894501
                                 mass_smaller_30 mass               0.9998926681676554
linear_regression MIST           Base            mass              0.31780480327703364
                                 mass_smaller_3  mass               0.6094803842541214
                                 mass_smaller_14 mass                0.762400313993691
                                 mass_smaller_30 mass               0.7140435452800753
mlp               MIST           Base            mass               0.9809873465478306
                                 mass_smaller_3  mass                0.995291571916788
                                 mass_smaller_14 mass                0.996214834842145
                                 mass_smaller_30 mass               0.9967538160059431
random_forest     MIST           Base            mass               0.9997441818803499
                                 mass_smaller_3  mass               0.9996653648909077
                                 mass_smaller_14 mass               0.9999748783427481
                                 mass_smaller_30 mass               0.9999630727520922
xgboost           MIST           Base            mass               0.9988754736593098
                                 mass_smaller_3  mass                0.999225961655845
                                 mass_smaller_14 mass               0.9997590049106206
                                 mass_smaller_30 mass                0.999688666857799

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.8563821878406251
                                 mass_smaller_3  mass              0.017616715482776626
                                 mass_smaller_14 mass               0.02385802713393943
                                 mass_smaller_30 mass               0.06333240179353944
KNN               MIST           Base            mass                0.7372507757129543
                                 mass_smaller_3  mass              0.017863580890469438
                                 mass_smaller_14 mass              0.048526462075921734
                                 mass_smaller_30 mass               0.06142220794191277
linear_regression MIST           Base            mass                24.369214026570532
                                 mass_smaller_3  mass               0.40795181296848076
                                 mass_smaller_14 mass                1.5868637538295014
                                 mass_smaller_30 mass                3.1675557469660958
mlp               MIST           Base            mass                4.1025447018224765
                                 mass_smaller_3  mass               0.04347468113678617
                                 mass_smaller_14 mass               0.22698643493170936
                                 mass_smaller_30 mass               0.35036012195355265
random_forest     MIST           Base            mass               0.47498420224835197
                                 mass_smaller_3  mass               0.01145266644937612
                                 mass_smaller_14 mass              0.016380694948155635
                                 mass_smaller_30 mass               0.03600210348199009
xgboost           MIST           Base            mass                0.9959317895204074
                                 mass_smaller_3  mass              0.017420504143439753
                                 mass_smaller_14 mass              0.052322327024145285
                                 mass_smaller_30 mass                0.1069132310207098

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.06250788141530114
                                 mass_smaller_3  mass              0.007694368270985248
                                 mass_smaller_14 mass              0.007503332091038842
                                 mass_smaller_30 mass              0.007766881524781867
KNN               MIST           Base            mass               0.09538418274204148
                                 mass_smaller_3  mass              0.008954045678879998
                                 mass_smaller_14 mass              0.019909272058525742
                                 mass_smaller_30 mass              0.020408799453852138
linear_regression MIST           Base            mass                 10.19273825964967
                                 mass_smaller_3  mass               0.31283468382588653
                                 mass_smaller_14 mass                 1.069708813947661
                                 mass_smaller_30 mass                1.9786101759927788
mlp               MIST           Base            mass                1.0928917274409464
                                 mass_smaller_3  mass               0.03303430572775442
                                 mass_smaller_14 mass               0.15942483952793438
                                 mass_smaller_30 mass               0.16982858627234326
random_forest     MIST           Base            mass               0.05965777535357753
                                 mass_smaller_3  mass              0.006816718583654214
                                 mass_smaller_14 mass              0.008364516305232947
                                 mass_smaller_30 mass              0.008525994540392908
xgboost           MIST           Base            mass               0.29336744162478817
                                 mass_smaller_3  mass              0.011962832958118098
                                 mass_smaller_14 mass               0.03612506183253485
                                 mass_smaller_30 mass               0.06198712841112408

                                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.00035448824774864107
                                 mass_smaller_3  mass               0.0011683880009409897
                                 mass_smaller_14 mass               0.0003194319201256235
                                 mass_smaller_30 mass              0.00029192157563162624
KNN               MIST           Base            mass                0.003644066674525215
                                 mass_smaller_3  mass               0.0049844695910198356
                                 mass_smaller_14 mass                0.005020707249098422
                                 mass_smaller_30 mass                0.003801213620794275
linear_regression MIST           Base            mass                  5.5255520552792525
                                 mass_smaller_3  mass                 0.25049991044110187
                                 mass_smaller_14 mass                   0.760789110979081
                                 mass_smaller_30 mass                  1.3996305598636667
mlp               MIST           Base            mass                  0.2631247976663317
                                 mass_smaller_3  mass                 0.02614850301189242
                                 mass_smaller_14 mass                 0.11114159758060715
                                 mass_smaller_30 mass                  0.1144261130096238
random_forest     MIST           Base            mass                0.004034495488792533
                                 mass_smaller_3  mass                0.004307804055038389
                                 mass_smaller_14 mass                0.004331240334604747
                                 mass_smaller_30 mass               0.0038726860238362804
xgboost           MIST           Base            mass                 0.07123763131807914
                                 mass_smaller_3  mass                  0.0081628820130073
                                 mass_smaller_14 mass                 0.02403747932798972
                                 mass_smaller_30 mass                 0.03476289684299427

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9995841526922911
                                 mass_smaller_3  mass              0.9996086734847093
                                 mass_smaller_14 mass              0.9999731736722719
                                 mass_smaller_30 mass              0.9999428516541571
KNN               MIST           Base            mass              0.9996927065174758
                                 mass_smaller_3  mass              0.9996103334674206
                                 mass_smaller_14 mass              0.9998885716995248
                                 mass_smaller_30 mass              0.9999463625075689
linear_regression MIST           Base            mass              0.5956484957644704
                                 mass_smaller_3  mass              0.8443908629223283
                                 mass_smaller_14 mass              0.9168080990761227
                                 mass_smaller_30 mass              0.8780360246383192
mlp               MIST           Base            mass              0.9906440264736001
                                 mass_smaller_3  mass              0.9976529594265796
                                 mass_smaller_14 mass              0.9981658283323158
                                 mass_smaller_30 mass              0.9983803120639673
random_forest     MIST           Base            mass              0.9998728077084751
                                 mass_smaller_3  mass              0.9998368427876034
                                 mass_smaller_14 mass               0.999987578431358
                                 mass_smaller_30 mass              0.9999816149877483
xgboost           MIST           Base            mass              0.9994709362034415
                                 mass_smaller_3  mass              0.9996379383407658
                                 mass_smaller_14 mass              0.9998847737638235
                                 mass_smaller_30 mass              0.9998448966574918

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               115.07406668861114
                                 mass_smaller_3  mass               0.4249228172899455
                                 mass_smaller_14 mass               0.6972037055216713
                                 mass_smaller_30 mass                9.179017754221904
KNN               MIST           Base            mass                37.48661252169403
                                 mass_smaller_3  mass              0.25092821324204007
                                 mass_smaller_14 mass                0.855295325429557
                                 mass_smaller_30 mass                2.365722589923628
linear_regression MIST           Base            mass                 247.272892099655
                                 mass_smaller_3  mass                1.286388691281558
                                 mass_smaller_14 mass                6.793720968603239
                                 mass_smaller_30 mass               17.207983690530472
mlp               MIST           Base            mass                92.62233332462321
                                 mass_smaller_3  mass              0.24497779297832079
                                 mass_smaller_14 mass               2.6315811224630377
                                 mass_smaller_30 mass               10.488083669766144
random_forest     MIST           Base            mass               21.388650133880788
                                 mass_smaller_3  mass               0.2152611485477416
                                 mass_smaller_14 mass               0.3876454793620763
                                 mass_smaller_30 mass                5.177953336655193
xgboost           MIST           Base            mass                39.12064222195215
                                 mass_smaller_3  mass              0.17315979871153675
                                 mass_smaller_14 mass               0.5749695953718383
                                 mass_smaller_30 mass                3.802174416275264

                                                                                                                        Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                      75 : 0.0055 / 90 : 0.0255 / 95 : 0.04576 / 99 : 0.76556
                                 mass_smaller_3  mass                    75 : 0.00836 / 90 : 0.02499 / 95 : 0.03441 / 99 : 0.06152
                                 mass_smaller_14 mass                     75 : 0.00561 / 90 : 0.02323 / 95 : 0.0345 / 99 : 0.08297
                                 mass_smaller_30 mass                    75 : 0.00503 / 90 : 0.02193 / 95 : 0.03386 / 99 : 0.08563
KNN               MIST           Base            mass                     75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                 mass_smaller_3  mass                    75 : 0.01135 / 90 : 0.02134 / 95 : 0.03077 / 99 : 0.08437
                                 mass_smaller_14 mass                    75 : 0.01614 / 90 : 0.05658 / 95 : 0.10078 / 99 : 0.20837
                                 mass_smaller_30 mass                    75 : 0.01525 / 90 : 0.05396 / 95 : 0.09877 / 99 : 0.23209
linear_regression MIST           Base            mass               75 : 11.07191 / 90 : 14.15785 / 95 : 22.74117 / 99 : 136.10861
                                 mass_smaller_3  mass                    75 : 0.46818 / 90 : 0.69527 / 95 : 0.84131 / 99 : 1.06546
                                 mass_smaller_14 mass                    75 : 1.15478 / 90 : 2.27848 / 95 : 3.92679 / 99 : 6.05809
                                 mass_smaller_30 mass                   75 : 2.23459 / 90 : 2.96898 / 95 : 6.41136 / 99 : 15.23374
mlp               MIST           Base            mass                   75 : 0.50511 / 90 : 1.67386 / 95 : 4.22263 / 99 : 20.09887
                                 mass_smaller_3  mass                     75 : 0.04673 / 90 : 0.0692 / 95 : 0.08313 / 99 : 0.13242
                                 mass_smaller_14 mass                    75 : 0.20197 / 90 : 0.36173 / 95 : 0.49247 / 99 : 0.72618
                                 mass_smaller_30 mass                    75 : 0.18872 / 90 : 0.30412 / 95 : 0.48392 / 99 : 1.13469
random_forest     MIST           Base            mass                    75 : 0.01064 / 90 : 0.02559 / 95 : 0.07213 / 99 : 1.35752
                                 mass_smaller_3  mass                     75 : 0.00903 / 90 : 0.01523 / 95 : 0.0204 / 99 : 0.03971
                                 mass_smaller_14 mass                    75 : 0.01004 / 90 : 0.01896 / 95 : 0.02804 / 99 : 0.06675
                                 mass_smaller_30 mass                    75 : 0.00918 / 90 : 0.01791 / 95 : 0.02743 / 99 : 0.07008
xgboost           MIST           Base            mass                      75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                 mass_smaller_3  mass                     75 : 0.01588 / 90 : 0.0268 / 95 : 0.03579 / 99 : 0.06169
                                 mass_smaller_14 mass                    75 : 0.04892 / 90 : 0.08319 / 95 : 0.10822 / 99 : 0.17266
                                 mass_smaller_30 mass                    75 : 0.07674 / 90 : 0.13986 / 95 : 0.20466 / 99 : 0.42319

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494
KNN               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494
linear_regression MIST           Base            mass                0.5418086127397849 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494
mlp               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494
random_forest     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494
xgboost           MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass              0.5418086127397849 - 13.996563361499728
                                 mass_smaller_30 mass               0.5418086438439156 - 29.99464069960494

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9918974335576843
                                 mass_smaller_3  mass               0.9925088328108644
                                 mass_smaller_14 mass               0.9994746327197954
                                 mass_smaller_30 mass               0.9987842548516085
KNN               MIST           Base            mass               0.9860770182495742
                                 mass_smaller_3  mass                 0.99350766733889
                                 mass_smaller_14 mass               0.9993531353657983
                                 mass_smaller_30 mass               0.9986346706699237
linear_regression MIST           Base            mass              0.37879056102710573
                                 mass_smaller_3  mass              0.15358248802528074
                                 mass_smaller_14 mass               0.7133552017917841
                                 mass_smaller_30 mass               0.6702956939540852
mlp               MIST           Base            mass               0.9519375404272862
                                 mass_smaller_3  mass               0.9859577609925029
                                 mass_smaller_14 mass               0.9942735662962944
                                 mass_smaller_30 mass               0.9891210209652022
random_forest     MIST           Base            mass               0.9949810881828094
                                 mass_smaller_3  mass               0.9956700597782066
                                 mass_smaller_14 mass               0.9997314968892836
                                 mass_smaller_30 mass               0.9992159321432441
xgboost           MIST           Base            mass               0.9944238807426196
                                 mass_smaller_3  mass               0.9940163365388791
                                 mass_smaller_14 mass               0.9992387279839019
                                 mass_smaller_30 mass               0.9988918661985585

                                                                                  RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                2.086222856008246
                                 mass_smaller_3  mass              0.05549221609398243
                                 mass_smaller_14 mass              0.07355267359445937
                                 mass_smaller_30 mass               0.2070129798976643
KNN               MIST           Base            mass                2.734806056725069
                                 mass_smaller_3  mass              0.05166760544925883
                                 mass_smaller_14 mass              0.08213950769951826
                                 mass_smaller_30 mass              0.21958844048701423
linear_regression MIST           Base            mass                18.20601901201638
                                 mass_smaller_3  mass               0.5936734849308265
                                 mass_smaller_14 mass               1.7236705797241394
                                 mass_smaller_30 mass               3.4197583434140055
mlp               MIST           Base            mass                5.083213797408978
                                 mass_smaller_3  mass              0.07749136063495056
                                 mass_smaller_14 mass               0.2537107369491821
                                 mass_smaller_30 mass               0.6193493404151968
random_forest     MIST           Base            mass                1.642420538512268
                                 mass_smaller_3  mass              0.04218948342523731
                                 mass_smaller_14 mass              0.05275259369402082
                                 mass_smaller_30 mass              0.16625089930600467
xgboost           MIST           Base            mass                 1.73045095147863
                                 mass_smaller_3  mass              0.04960002132995069
                                 mass_smaller_14 mass               0.0900224936880097
                                 mass_smaller_30 mass              0.19885674550037932

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.19876474354848747
                                 mass_smaller_3  mass              0.016451897766401203
                                 mass_smaller_14 mass              0.026121137496956662
                                 mass_smaller_30 mass               0.03230223856499136
KNN               MIST           Base            mass               0.36421728355537797
                                 mass_smaller_3  mass               0.02025881030023404
                                 mass_smaller_14 mass               0.03542587449621387
                                 mass_smaller_30 mass                0.0584947875984932
linear_regression MIST           Base            mass                 8.317562587188547
                                 mass_smaller_3  mass               0.42510847614194097
                                 mass_smaller_14 mass                1.2030142610738188
                                 mass_smaller_30 mass                2.1241945242076876
mlp               MIST           Base            mass                1.3679461988307051
                                 mass_smaller_3  mass               0.05247603784180956
                                 mass_smaller_14 mass               0.17618718012670548
                                 mass_smaller_30 mass                0.2247330992267628
random_forest     MIST           Base            mass               0.20145454791412173
                                 mass_smaller_3  mass              0.014501789192269845
                                 mass_smaller_14 mass              0.022827163298679603
                                 mass_smaller_30 mass              0.029871983394766485
xgboost           MIST           Base            mass                0.4513957644350668
                                 mass_smaller_3  mass               0.02313346360611026
                                 mass_smaller_14 mass               0.05592360290374699
                                 mass_smaller_30 mass               0.09970728869430061

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0038324881287014056
                                 mass_smaller_3  mass              0.0018932641038316156
                                 mass_smaller_14 mass              0.0028455203364146087
                                 mass_smaller_30 mass              0.0030829257528004472
KNN               MIST           Base            mass                0.01014186225597502
                                 mass_smaller_3  mass               0.004109206835448909
                                 mass_smaller_14 mass               0.007502834461763808
                                 mass_smaller_30 mass                0.00809698280461102
linear_regression MIST           Base            mass                  4.967714823268368
                                 mass_smaller_3  mass                0.32287952930253383
                                 mass_smaller_14 mass                 0.7817296109138197
                                 mass_smaller_30 mass                 1.3185505105130721
mlp               MIST           Base            mass                  0.264341278289347
                                 mass_smaller_3  mass                0.03857040177293647
                                 mass_smaller_14 mass                0.12182854839341317
                                 mass_smaller_30 mass                0.10856051244673487
random_forest     MIST           Base            mass               0.006907232098912752
                                 mass_smaller_3  mass               0.003545841487851087
                                 mass_smaller_14 mass               0.005682850267350048
                                 mass_smaller_30 mass                0.00565454251708275
xgboost           MIST           Base            mass                0.09355388928063046
                                 mass_smaller_3  mass               0.009825121353496336
                                 mass_smaller_14 mass               0.029557092791241413
                                 mass_smaller_30 mass                0.04858120706529312

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9959603108250029
                                 mass_smaller_3  mass               0.9962474248572476
                                 mass_smaller_14 mass               0.9997378989826986
                                 mass_smaller_30 mass               0.9993932193079896
KNN               MIST           Base            mass               0.9931315041563596
                                 mass_smaller_3  mass               0.9967899726916828
                                 mass_smaller_14 mass               0.9996882976773386
                                 mass_smaller_30 mass               0.9993186347830078
linear_regression MIST           Base            mass               0.6373077587506739
                                 mass_smaller_3  mass              0.40530355547261254
                                 mass_smaller_14 mass               0.9039729388719477
                                 mass_smaller_30 mass               0.8681042646752453
mlp               MIST           Base            mass               0.9761539783804645
                                 mass_smaller_3  mass               0.9930099112080837
                                 mass_smaller_14 mass               0.9971360356854851
                                 mass_smaller_30 mass               0.9947084198344637
random_forest     MIST           Base            mass               0.9976029233414596
                                 mass_smaller_3  mass               0.9978436498641285
                                 mass_smaller_14 mass               0.9998673316027468
                                 mass_smaller_30 mass               0.9996086557743828
xgboost           MIST           Base            mass               0.9972366154162345
                                 mass_smaller_3  mass               0.9970442373213937
                                 mass_smaller_14 mass               0.9996302287964051
                                 mass_smaller_30 mass               0.9994457920153503

                                                                               MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.65813444621273
                                 mass_smaller_3  mass              2.0171919805222065
                                 mass_smaller_14 mass              2.3792352286813614
                                 mass_smaller_30 mass               10.37678082620074
KNN               MIST           Base            mass              144.21389375194437
                                 mass_smaller_3  mass              1.0215474131655333
                                 mass_smaller_14 mass              1.7054970225033568
                                 mass_smaller_30 mass               8.318905246830845
linear_regression MIST           Base            mass              251.18220676294754
                                 mass_smaller_3  mass              2.8242406186495193
                                 mass_smaller_14 mass               6.829523861202951
                                 mass_smaller_30 mass               18.15045861256205
mlp               MIST           Base            mass              179.18165022433564
                                 mass_smaller_3  mass              1.1380741028372034
                                 mass_smaller_14 mass               2.993144344901003
                                 mass_smaller_30 mass              14.269413882997462
random_forest     MIST           Base            mass               95.14828406903314
                                 mass_smaller_3  mass              1.3490965095666518
                                 mass_smaller_14 mass              1.1986061113342346
                                 mass_smaller_30 mass               8.346774873747222
xgboost           MIST           Base            mass               61.88665111883462
                                 mass_smaller_3  mass               1.164764377165806
                                 mass_smaller_14 mass               1.805634457746697
                                 mass_smaller_30 mass               5.780606956144421

                                                                                                                     Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.0237 / 90 : 0.11118 / 95 : 0.26881 / 99 : 4.59332
                                 mass_smaller_3  mass                 75 : 0.00941 / 90 : 0.03454 / 95 : 0.07581 / 99 : 0.27683
                                 mass_smaller_14 mass                   75 : 0.01578 / 90 : 0.0709 / 95 : 0.14655 / 99 : 0.3477
                                 mass_smaller_30 mass                  75 : 0.01723 / 90 : 0.06999 / 95 : 0.14298 / 99 : 0.3706
KNN               MIST           Base            mass                 75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                 mass_smaller_3  mass                 75 : 0.01678 / 90 : 0.05464 / 95 : 0.10517 / 99 : 0.23112
                                 mass_smaller_14 mass                 75 : 0.03425 / 90 : 0.10695 / 95 : 0.16679 / 99 : 0.34825
                                 mass_smaller_30 mass                 75 : 0.03932 / 90 : 0.13294 / 95 : 0.24316 / 99 : 0.80659
linear_regression MIST           Base            mass               75 : 9.59684 / 90 : 14.29098 / 95 : 22.9859 / 99 : 82.28409
                                 mass_smaller_3  mass                 75 : 0.53852 / 90 : 0.86058 / 95 : 1.12503 / 99 : 2.20922
                                 mass_smaller_14 mass                 75 : 1.31295 / 90 : 2.87077 / 95 : 4.20585 / 99 : 5.96268
                                 mass_smaller_30 mass                75 : 2.43399 / 90 : 4.34488 / 95 : 8.35031 / 99 : 14.66932
mlp               MIST           Base            mass                 75 : 0.53231 / 90 : 2.20664 / 95 : 6.2769 / 99 : 24.01312
                                 mass_smaller_3  mass                 75 : 0.06593 / 90 : 0.10615 / 95 : 0.14643 / 99 : 0.28036
                                 mass_smaller_14 mass                 75 : 0.23751 / 90 : 0.38845 / 95 : 0.51461 / 99 : 0.84376
                                 mass_smaller_30 mass                 75 : 0.19504 / 90 : 0.36711 / 95 : 0.67972 / 99 : 2.70266
random_forest     MIST           Base            mass                  75 : 0.0288 / 90 : 0.10782 / 95 : 0.29875 / 99 : 4.67012
                                 mass_smaller_3  mass                  75 : 0.01061 / 90 : 0.03037 / 95 : 0.06452 / 99 : 0.2086
                                 mass_smaller_14 mass                 75 : 0.02137 / 90 : 0.06326 / 95 : 0.10702 / 99 : 0.24041
                                 mass_smaller_30 mass                  75 : 0.0211 / 90 : 0.06291 / 95 : 0.10884 / 99 : 0.28255
xgboost           MIST           Base            mass                  75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                 mass_smaller_3  mass                  75 : 0.02197 / 90 : 0.05469 / 95 : 0.0944 / 99 : 0.22596
                                 mass_smaller_14 mass                  75 : 0.0704 / 90 : 0.14479 / 95 : 0.19878 / 99 : 0.32004
                                 mass_smaller_30 mass                 75 : 0.12968 / 90 : 0.23506 / 95 : 0.32372 / 99 : 0.58866

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808
                                 mass_smaller_14 mass               18.232510805130005

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, medAE and all percentiles except P99, better results on RMSE and MAX_ER\
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors

Random forest : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE\
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

MLP : 
- mass_smaller_3 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER\
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

#### Conclusions on mass filtering

mass_smaller_3 is always worse than Base.

If reducing worst-case errors is the priority, mass_smaller_14 is preferable; if average accuracy matters more, Base is better.

mass_smaller_30 is a middle ground between Base and mass_smaller_14 but it does not offer enough improvements to be interesting to use.

#### Best models for the mass parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### Radius parameter

In [12]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
KNN               MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
linear_regression MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
mlp               MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
random_forest     MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
xgboost           MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0827540579576227
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997998092796726
                                 mass_smaller_3  radius            0.9998692605707555
                                 mass_smaller_14 radius            0.9998337327080868
                                 mass_smaller_30 radius            0.9998199780100178
KNN               MIST           Base            radius            0.9998995813284512
                                 mass_smaller_3  radius            0.9999075272015158
                                 mass_smaller_14 radius            0.9999258045438245
                                 mass_smaller_30 radius             0.999924357563505
linear_regression MIST           Base            radius            0.9839439743859983
                                 mass_smaller_3  radius            0.9886074464966265
                                 mass_smaller_14 radius            0.9896569006470799
                                 mass_smaller_30 radius            0.9893886961293711
mlp               MIST           Base            radius            0.9825030163796187
                                 mass_smaller_3  radius            0.9995988263392411
                                 mass_smaller_14 radius            0.9989090687362142
                                 mass_smaller_30 radius             0.996559892022478
random_forest     MIST           Base            radius             0.999944256151205
                                 mass_smaller_3  radius            0.9999610185567137
                                 mass_smaller_14 radius            0.9999572001459547
                                 mass_smaller_30 radius            0.9999565270829192
xgboost           MIST           Base            radius             0.999397822638394
                                 mass_smaller_3  radius            0.9995279417367391
                                 mass_smaller_14 radius            0.9993023597328426
                                 mass_smaller_30 radius            0.9993998051508514

                                                                                    RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.010536884601545204
                                 mass_smaller_3  radius             0.008100247484890959
                                 mass_smaller_14 radius             0.009177754108950649
                                 mass_smaller_30 radius              0.00963107082974726
KNN               MIST           Base            radius             0.007462979624898889
                                 mass_smaller_3  radius             0.006812071056119723
                                 mass_smaller_14 radius             0.006130817853685161
                                 mass_smaller_30 radius             0.006243100633039712
linear_regression MIST           Base            radius               0.0943610826492741
                                 mass_smaller_3  radius              0.07560806197635822
                                 mass_smaller_14 radius              0.07238483241180424
                                 mass_smaller_30 radius               0.0739408719453246
mlp               MIST           Base            radius              0.10014365984840665
                                 mass_smaller_3  radius             0.014395691899092448
                                 mass_smaller_14 radius              0.02450118083298934
                                 mass_smaller_30 radius              0.04359440516997864
random_forest     MIST           Base            radius            0.0055601212350915655
                                 mass_smaller_3  radius             0.004423646074963593
                                 mass_smaller_14 radius             0.004656843390213431
                                 mass_smaller_30 radius               0.0047331321295951
xgboost           MIST           Base            radius             0.018274104599001577
                                 mass_smaller_3  radius             0.015390595760964007
                                 mass_smaller_14 radius             0.018799141411202563
                                 mass_smaller_30 radius             0.017585161063589008

                                                                                     MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.005846179154299134
                                 mass_smaller_3  radius             0.004470211632979367
                                 mass_smaller_14 radius             0.005336936873300546
                                 mass_smaller_30 radius            0.0054548596331029904
KNN               MIST           Base            radius             0.004208071841339602
                                 mass_smaller_3  radius             0.004086433831855517
                                 mass_smaller_14 radius             0.003822404702126134
                                 mass_smaller_30 radius            0.0038532707478507564
linear_regression MIST           Base            radius              0.06559059660663957
                                 mass_smaller_3  radius              0.05450504488570346
                                 mass_smaller_14 radius              0.05394599108846469
                                 mass_smaller_30 radius             0.053981275582121055
mlp               MIST           Base            radius              0.06760652949280348
                                 mass_smaller_3  radius               0.0104229983182241
                                 mass_smaller_14 radius             0.018148228948391333
                                 mass_smaller_30 radius             0.030666319131616045
random_forest     MIST           Base            radius            0.0027087858185894653
                                 mass_smaller_3  radius            0.0019739870746720185
                                 mass_smaller_14 radius            0.0024542535480174816
                                 mass_smaller_30 radius             0.002394405508418592
xgboost           MIST           Base            radius             0.011086516891189406
                                 mass_smaller_3  radius             0.006715741379452065
                                 mass_smaller_14 radius             0.008634293269184455
                                 mass_smaller_30 radius              0.00954069303942768

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.0033685841256209034
                                 mass_smaller_3  radius            0.0024833995093103134
                                 mass_smaller_14 radius            0.0031605023246422392
                                 mass_smaller_30 radius            0.0032148812518034697
KNN               MIST           Base            radius            0.0025840512601615906
                                 mass_smaller_3  radius             0.002577244559161862
                                 mass_smaller_14 radius            0.0025115982024946915
                                 mass_smaller_30 radius             0.002511131951570378
linear_regression MIST           Base            radius             0.042886350251173766
                                 mass_smaller_3  radius              0.04289506191232645
                                 mass_smaller_14 radius              0.04342268579643055
                                 mass_smaller_30 radius              0.04292699321951132
mlp               MIST           Base            radius              0.04567693375672416
                                 mass_smaller_3  radius             0.007992764463573283
                                 mass_smaller_14 radius             0.013825175227679454
                                 mass_smaller_30 radius             0.023280891836665013
random_forest     MIST           Base            radius            0.0013210056146442106
                                 mass_smaller_3  radius            0.0009900862753579737
                                 mass_smaller_14 radius            0.0012660848855425288
                                 mass_smaller_30 radius            0.0012281094464122386
xgboost           MIST           Base            radius             0.008207268853469507
                                 mass_smaller_3  radius             0.004535109380137164
                                 mass_smaller_14 radius             0.006236816313569399
                                 mass_smaller_30 radius             0.007087796294413876

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998999334973174
                                 mass_smaller_3  radius            0.9999346377052214
                                 mass_smaller_14 radius            0.9999169168391561
                                 mass_smaller_30 radius            0.9999100431442856
KNN               MIST           Base            radius            0.9999498175049178
                                 mass_smaller_3  radius            0.9999537992410381
                                 mass_smaller_14 radius            0.9999629328408591
                                 mass_smaller_30 radius            0.9999622026147249
linear_regression MIST           Base            radius            0.9919395013742175
                                 mass_smaller_3  radius            0.9942874063866546
                                 mass_smaller_14 radius             0.994815008253875
                                 mass_smaller_30 radius            0.9946801979175901
mlp               MIST           Base            radius            0.9912543915133569
                                 mass_smaller_3  radius            0.9997997180272639
                                 mass_smaller_14 radius            0.9994561331556269
                                 mass_smaller_30 radius            0.9982857302461573
random_forest     MIST           Base            radius            0.9999721283552458
                                 mass_smaller_3  radius             0.999980509131565
                                 mass_smaller_14 radius            0.9999786092505406
                                 mass_smaller_30 radius             0.999978267849351
xgboost           MIST           Base            radius            0.9996988823314146
                                 mass_smaller_3  radius            0.9997639449348299
                                 mass_smaller_14 radius            0.9996511254523321
                                 mass_smaller_30 radius            0.9996998703569016

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.5064401538847425
                                 mass_smaller_3  radius             0.3080413669013684
                                 mass_smaller_14 radius            0.29687093092413097
                                 mass_smaller_30 radius             0.8341740650426792
KNN               MIST           Base            radius            0.27880787293870035
                                 mass_smaller_3  radius            0.17596780530916556
                                 mass_smaller_14 radius            0.16948753721672638
                                 mass_smaller_30 radius            0.21195638156532765
linear_regression MIST           Base            radius             0.6754177015661889
                                 mass_smaller_3  radius              0.613371610834804
                                 mass_smaller_14 radius             0.5976239464782516
                                 mass_smaller_30 radius             0.6240646709658961
mlp               MIST           Base            radius             0.8434788426182683
                                 mass_smaller_3  radius             0.2266966943526767
                                 mass_smaller_14 radius            0.31574903891578354
                                 mass_smaller_30 radius             0.5854697900042987
random_forest     MIST           Base            radius            0.28770974092603363
                                 mass_smaller_3  radius            0.13567376296989764
                                 mass_smaller_14 radius            0.13060962532261078
                                 mass_smaller_30 radius            0.26972546397215036
xgboost           MIST           Base            radius             0.7666851796630024
                                 mass_smaller_3  radius             0.7003157608652608
                                 mass_smaller_14 radius             0.8814602412703633
                                 mass_smaller_30 radius             0.8704838143869863

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.00721 / 90 : 0.01302 / 95 : 0.01822 / 99 : 0.04072
                                 mass_smaller_3  radius             75 : 0.00563 / 90 : 0.01118 / 95 : 0.01404 / 99 : 0.02836
                                 mass_smaller_14 radius              75 : 0.00675 / 90 : 0.01228 / 95 : 0.01625 / 99 : 0.0348
                                 mass_smaller_30 radius             75 : 0.00686 / 90 : 0.01241 / 95 : 0.01672 / 99 : 0.03567
KNN               MIST           Base            radius             75 : 0.00514 / 90 : 0.00922 / 95 : 0.01279 / 99 : 0.02707
                                 mass_smaller_3  radius             75 : 0.00515 / 90 : 0.00907 / 95 : 0.01243 / 99 : 0.02369
                                 mass_smaller_14 radius             75 : 0.00488 / 90 : 0.00854 / 95 : 0.01142 / 99 : 0.02111
                                 mass_smaller_30 radius              75 : 0.00489 / 90 : 0.00864 / 95 : 0.0116 / 99 : 0.02194
linear_regression MIST           Base            radius                75 : 0.09215 / 90 : 0.147 / 95 : 0.1831 / 99 : 0.33364
                                 mass_smaller_3  radius                75 : 0.07096 / 90 : 0.09919 / 95 : 0.129 / 99 : 0.2365
                                 mass_smaller_14 radius             75 : 0.07339 / 90 : 0.10346 / 95 : 0.12671 / 99 : 0.20977
                                 mass_smaller_30 radius             75 : 0.07749 / 90 : 0.11075 / 95 : 0.13267 / 99 : 0.20501
mlp               MIST           Base            radius             75 : 0.08412 / 90 : 0.15226 / 95 : 0.23438 / 99 : 0.33377
                                 mass_smaller_3  radius             75 : 0.01419 / 90 : 0.02208 / 95 : 0.02812 / 99 : 0.04409
                                 mass_smaller_14 radius             75 : 0.02477 / 90 : 0.03994 / 95 : 0.05143 / 99 : 0.07408
                                 mass_smaller_30 radius             75 : 0.04228 / 90 : 0.06435 / 95 : 0.07998 / 99 : 0.12362
random_forest     MIST           Base            radius             75 : 0.00312 / 90 : 0.00626 / 95 : 0.00935 / 99 : 0.02085
                                 mass_smaller_3  radius              75 : 0.00224 / 90 : 0.00437 / 95 : 0.0064 / 99 : 0.01507
                                 mass_smaller_14 radius             75 : 0.00294 / 90 : 0.00583 / 95 : 0.00849 / 99 : 0.01696
                                 mass_smaller_30 radius              75 : 0.00284 / 90 : 0.0056 / 95 : 0.00819 / 99 : 0.01699
xgboost           MIST           Base            radius               75 : 0.01483 / 90 : 0.02304 / 95 : 0.0293 / 99 : 0.0469
                                 mass_smaller_3  radius             75 : 0.00826 / 90 : 0.01322 / 95 : 0.01737 / 99 : 0.03323
                                 mass_smaller_14 radius             75 : 0.01117 / 90 : 0.01719 / 95 : 0.02176 / 99 : 0.03453
                                 mass_smaller_30 radius             75 : 0.01272 / 90 : 0.01954 / 95 : 0.02456 / 99 : 0.03738

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              25.21291995048523
                                 mass_smaller_3  radius             11.799425840377808
                                 mass_smaller_14 radius             18.232510805130005

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227
KNN               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227
linear_regression MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227
mlp               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227
random_forest     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227
xgboost           MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974234436680278 - 0.7629161677552769
                                 mass_smaller_14 radius            -0.9974747647513328 - 3.0827540579576227
                                 mass_smaller_30 radius            -0.9974747647513328 - 3.0827540579576227

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997824748596408
                                 mass_smaller_3  radius            0.9998320816205213
                                 mass_smaller_14 radius            0.9997928510771583
                                 mass_smaller_30 radius            0.9998036006117262
KNN               MIST           Base            radius            0.9998348784628862
                                 mass_smaller_3  radius            0.9996595379770277
                                 mass_smaller_14 radius            0.9998244565962764
                                 mass_smaller_30 radius            0.9998692256870981
linear_regression MIST           Base            radius            0.9755626571141772
                                 mass_smaller_3  radius            0.9597040325540658
                                 mass_smaller_14 radius            0.9781333879983054
                                 mass_smaller_30 radius            0.9833485877286566
mlp               MIST           Base            radius            0.9754861361846096
                                 mass_smaller_3  radius            0.9988881540732915
                                 mass_smaller_14 radius            0.9977087320299743
                                 mass_smaller_30 radius            0.9949918119955709
random_forest     MIST           Base            radius             0.999948388627212
                                 mass_smaller_3  radius            0.9999695283084309
                                 mass_smaller_14 radius             0.999954273279007
                                 mass_smaller_30 radius            0.9999553925604562
xgboost           MIST           Base            radius            0.9994453815539737
                                 mass_smaller_3  radius            0.9995942168068729
                                 mass_smaller_14 radius            0.9995316778942331
                                 mass_smaller_30 radius            0.9995444573828897

                                                                                    RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.00841700495690241
                                 mass_smaller_3  radius            0.0041347289814373175
                                 mass_smaller_14 radius            0.0060687074191572345
                                 mass_smaller_30 radius            0.0070988862741955035
KNN               MIST           Base            radius             0.007333273235377103
                                 mass_smaller_3  radius             0.005885135279400312
                                 mass_smaller_14 radius             0.005584677377398187
                                 mass_smaller_30 radius             0.005790859814080516
linear_regression MIST           Base            radius              0.08920696455595324
                                 mass_smaller_3  radius               0.0640247338850259
                                 mass_smaller_14 radius               0.0624000204365977
                                 mass_smaller_30 radius              0.06536757152819228
mlp               MIST           Base            radius               0.0909881002561968
                                 mass_smaller_3  radius             0.010899915109169623
                                 mass_smaller_14 radius               0.0206816775867941
                                 mass_smaller_30 radius              0.03689426064665967
random_forest     MIST           Base            radius             0.004099759822083538
                                 mass_smaller_3  radius            0.0017647987667890634
                                 mass_smaller_14 radius             0.002853961572747469
                                 mass_smaller_30 radius             0.003383653396609602
xgboost           MIST           Base            radius             0.013439001546194694
                                 mass_smaller_3  radius             0.006423854127584885
                                 mass_smaller_14 radius             0.009122362321712117
                                 mass_smaller_30 radius             0.010808218965673706

                                                                                     MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.004580194333593168
                                 mass_smaller_3  radius             0.002637829554723163
                                 mass_smaller_14 radius              0.00363079841596162
                                 mass_smaller_30 radius            0.0039865789953253085
KNN               MIST           Base            radius             0.004259044240868403
                                 mass_smaller_3  radius            0.0038425086261424522
                                 mass_smaller_14 radius            0.0036625411535374805
                                 mass_smaller_30 radius            0.0037649204541067645
linear_regression MIST           Base            radius              0.06854991503547478
                                 mass_smaller_3  radius              0.04957607165002803
                                 mass_smaller_14 radius              0.05016245389308913
                                 mass_smaller_30 radius              0.05169068132730123
mlp               MIST           Base            radius              0.06376711052819783
                                 mass_smaller_3  radius             0.008418232147510444
                                 mass_smaller_14 radius              0.01582301028435908
                                 mass_smaller_30 radius             0.027875213300297234
random_forest     MIST           Base            radius             0.002070584540408149
                                 mass_smaller_3  radius            0.0011131576219897057
                                 mass_smaller_14 radius             0.001634058112005501
                                 mass_smaller_30 radius            0.0017487397567619652
xgboost           MIST           Base            radius             0.009891559775160166
                                 mass_smaller_3  radius             0.004873807675144647
                                 mass_smaller_14 radius             0.006968426619692465
                                 mass_smaller_30 radius             0.008221535385905357

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.002625897491966067
                                 mass_smaller_3  radius            0.0017520001969897891
                                 mass_smaller_14 radius            0.0022819524497347254
                                 mass_smaller_30 radius            0.0024238304529700383
KNN               MIST           Base            radius            0.0025843900660267316
                                 mass_smaller_3  radius             0.002375727073808065
                                 mass_smaller_14 radius             0.002355228896905426
                                 mass_smaller_30 radius            0.0024308009339409214
linear_regression MIST           Base            radius              0.05406571511091185
                                 mass_smaller_3  radius              0.04014195577677965
                                 mass_smaller_14 radius             0.041666565581859216
                                 mass_smaller_30 radius             0.043826614513058845
mlp               MIST           Base            radius              0.04471249135521488
                                 mass_smaller_3  radius             0.006831431521156811
                                 mass_smaller_14 radius              0.01258163075997879
                                 mass_smaller_30 radius             0.021436196371384435
random_forest     MIST           Base            radius            0.0010098834104920185
                                 mass_smaller_3  radius            0.0006941944452366622
                                 mass_smaller_14 radius            0.0009028285606417635
                                 mass_smaller_30 radius            0.0009183059709119146
xgboost           MIST           Base            radius              0.00747479628313269
                                 mass_smaller_3  radius               0.0038186750928417
                                 mass_smaller_14 radius              0.00549809834231528
                                 mass_smaller_30 radius            0.0064256563159944685

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998912748936138
                                 mass_smaller_3  radius            0.9999160804490097
                                 mass_smaller_14 radius             0.999896420481045
                                 mass_smaller_30 radius            0.9999017978007643
KNN               MIST           Base            radius            0.9999177546784094
                                 mass_smaller_3  radius            0.9998319415121707
                                 mass_smaller_14 radius            0.9999129950192717
                                 mass_smaller_30 radius             0.999934934003084
linear_regression MIST           Base            radius            0.9877168815710867
                                 mass_smaller_3  radius            0.9843634847657234
                                 mass_smaller_14 radius            0.9891143074974718
                                 mass_smaller_30 radius            0.9916980887873753
mlp               MIST           Base            radius            0.9878791368934834
                                 mass_smaller_3  radius            0.9994442842217262
                                 mass_smaller_14 radius            0.9988657455811601
                                 mass_smaller_30 radius            0.9974943819239344
random_forest     MIST           Base            radius            0.9999742397308428
                                 mass_smaller_3  radius            0.9999848661853572
                                 mass_smaller_14 radius            0.9999771484155251
                                 mass_smaller_30 radius            0.9999776965246363
xgboost           MIST           Base            radius            0.9997226713831151
                                 mass_smaller_3  radius            0.9997970884152511
                                 mass_smaller_14 radius            0.9997658125307401
                                 mass_smaller_30 radius            0.9997722073062707

                                                                                 MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.5064401538847425
                                 mass_smaller_3  radius             0.12423453457943151
                                 mass_smaller_14 radius             0.29687093092413097
                                 mass_smaller_30 radius              0.5140943028519352
KNN               MIST           Base            radius              0.1536142657637809
                                 mass_smaller_3  radius             0.09194672527837028
                                 mass_smaller_14 radius             0.07454572919311686
                                 mass_smaller_30 radius             0.08158906393655352
linear_regression MIST           Base            radius             0.45880953343128383
                                 mass_smaller_3  radius               0.267428950963736
                                 mass_smaller_14 radius             0.23967427303293753
                                 mass_smaller_30 radius             0.22198913622387573
mlp               MIST           Base            radius              0.5223335924874889
                                 mass_smaller_3  radius               0.059911188425952
                                 mass_smaller_14 radius             0.12968385135237925
                                 mass_smaller_30 radius              0.2406016257426793
random_forest     MIST           Base            radius              0.1991549603986349
                                 mass_smaller_3  radius            0.033817034806178314
                                 mass_smaller_14 radius             0.11315406053672605
                                 mass_smaller_30 radius             0.26972546397215036
xgboost           MIST           Base            radius             0.12641478753552815
                                 mass_smaller_3  radius             0.14346735662654883
                                 mass_smaller_14 radius             0.06950863651605355
                                 mass_smaller_30 radius              0.0721994507485072

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.00532 / 90 : 0.01022 / 95 : 0.01494 / 99 : 0.0322
                                 mass_smaller_3  radius             75 : 0.00348 / 90 : 0.00565 / 95 : 0.00771 / 99 : 0.01498
                                 mass_smaller_14 radius             75 : 0.00455 / 90 : 0.00802 / 95 : 0.01132 / 99 : 0.02386
                                 mass_smaller_30 radius             75 : 0.00486 / 90 : 0.00882 / 95 : 0.01247 / 99 : 0.02659
KNN               MIST           Base            radius              75 : 0.00517 / 90 : 0.00954 / 95 : 0.01354 / 99 : 0.0264
                                 mass_smaller_3  radius             75 : 0.00485 / 90 : 0.00901 / 95 : 0.01268 / 99 : 0.02172
                                 mass_smaller_14 radius             75 : 0.00458 / 90 : 0.00843 / 95 : 0.01173 / 99 : 0.02095
                                 mass_smaller_30 radius               75 : 0.00472 / 90 : 0.00861 / 95 : 0.01199 / 99 : 0.022
linear_regression MIST           Base            radius             75 : 0.10192 / 90 : 0.14453 / 95 : 0.16854 / 99 : 0.26019
                                 mass_smaller_3  radius             75 : 0.06434 / 90 : 0.09113 / 95 : 0.12587 / 99 : 0.21494
                                 mass_smaller_14 radius             75 : 0.07214 / 90 : 0.10126 / 95 : 0.11797 / 99 : 0.17181
                                 mass_smaller_30 radius             75 : 0.07881 / 90 : 0.10961 / 95 : 0.12646 / 99 : 0.15582
mlp               MIST           Base            radius             75 : 0.08221 / 90 : 0.14167 / 95 : 0.21289 / 99 : 0.31117
                                 mass_smaller_3  radius             75 : 0.01179 / 90 : 0.01762 / 95 : 0.02188 / 99 : 0.03205
                                 mass_smaller_14 radius               75 : 0.0222 / 90 : 0.03321 / 95 : 0.04217 / 99 : 0.0609
                                 mass_smaller_30 radius             75 : 0.03966 / 90 : 0.06007 / 95 : 0.07369 / 99 : 0.10634
random_forest     MIST           Base            radius              75 : 0.00232 / 90 : 0.00482 / 95 : 0.0074 / 99 : 0.01643
                                 mass_smaller_3  radius             75 : 0.00143 / 90 : 0.00254 / 95 : 0.00352 / 99 : 0.00648
                                 mass_smaller_14 radius             75 : 0.00195 / 90 : 0.00381 / 95 : 0.00566 / 99 : 0.01135
                                 mass_smaller_30 radius             75 : 0.00203 / 90 : 0.00404 / 95 : 0.00606 / 99 : 0.01272
xgboost           MIST           Base            radius             75 : 0.01359 / 90 : 0.02135 / 95 : 0.02725 / 99 : 0.04188
                                 mass_smaller_3  radius               75 : 0.0068 / 90 : 0.01039 / 95 : 0.01308 / 99 : 0.0189
                                 mass_smaller_14 radius              75 : 0.00976 / 90 : 0.0149 / 95 : 0.01864 / 99 : 0.02672
                                 mass_smaller_30 radius              75 : 0.01151 / 90 : 0.01768 / 95 : 0.02213 / 99 : 0.0317

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              25.21291995048523
                                 mass_smaller_3  radius             11.799425840377808
                                 mass_smaller_14 radius             18.232510805130005

Results for the phase category with a value of 2.0

                                                                                              value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969
KNN               MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969
linear_regression MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969
mlp               MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969
random_forest     MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969
xgboost           MIST           Base            radius            0.0919862423867022 - 2.900376516729969
                                 mass_smaller_3  radius            0.0909920840275404 - 2.353416446984946
                                 mass_smaller_14 radius            0.0909920840275404 - 2.900376516729969
                                 mass_smaller_30 radius            0.0909920840275404 - 2.900376516729969

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9995892806800809
                                 mass_smaller_3  radius            0.9995587617625535
                                 mass_smaller_14 radius            0.9995197001584081
                                 mass_smaller_30 radius            0.9994948425223688
KNN               MIST           Base            radius            0.9999061973615614
                                 mass_smaller_3  radius            0.9998817172665754
                                 mass_smaller_14 radius            0.9998950136532548
                                 mass_smaller_30 radius             0.999896732789779
linear_regression MIST           Base            radius             0.969243149628593
                                 mass_smaller_3  radius            0.9832984636261459
                                 mass_smaller_14 radius            0.9821218597814573
                                 mass_smaller_30 radius            0.9812242174606677
mlp               MIST           Base            radius            0.9631384053179481
                                 mass_smaller_3  radius            0.9991611174957181
                                 mass_smaller_14 radius            0.9972125568463757
                                 mass_smaller_30 radius             0.993936749882818
random_forest     MIST           Base            radius            0.9999322817533202
                                 mass_smaller_3  radius            0.9999391726462705
                                 mass_smaller_14 radius             0.999915869819619
                                 mass_smaller_30 radius            0.9999326512662202
xgboost           MIST           Base            radius            0.9991837368887836
                                 mass_smaller_3  radius            0.9995453399672748
                                 mass_smaller_14 radius            0.9994170466959919
                                 mass_smaller_30 radius            0.9992688621568159

                                                                                    RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.009965134447302801
                                 mass_smaller_3  radius             0.009659532702665367
                                 mass_smaller_14 radius             0.010208011928967486
                                 mass_smaller_30 radius             0.010237794069864602
KNN               MIST           Base            radius             0.004759543963379831
                                 mass_smaller_3  radius             0.005001276314588465
                                 mass_smaller_14 radius             0.004770990555919763
                                 mass_smaller_30 radius              0.00462708959675789
linear_regression MIST           Base            radius              0.08713114427875067
                                 mass_smaller_3  radius              0.06269077852580816
                                 mass_smaller_14 radius              0.06428848258563957
                                 mass_smaller_30 radius              0.06390623781293282
mlp               MIST           Base            radius              0.09772101567582336
                                 mass_smaller_3  radius             0.014736131799820456
                                 mass_smaller_14 radius             0.027633845101238834
                                 mass_smaller_30 radius              0.04036053124376285
random_forest     MIST           Base            radius            0.0040747771955782575
                                 mass_smaller_3  radius             0.003588105645084922
                                 mass_smaller_14 radius             0.004315554552690224
                                 mass_smaller_30 radius             0.003775367391180045
xgboost           MIST           Base            radius             0.014058380710206752
                                 mass_smaller_3  radius             0.009826801089903366
                                 mass_smaller_14 radius             0.011283144985862152
                                 mass_smaller_30 radius             0.012340207213165378

                                                                                     MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.006760991091182068
                                 mass_smaller_3  radius             0.007179036722301516
                                 mass_smaller_14 radius              0.00733210704153488
                                 mass_smaller_30 radius             0.006976767883415538
KNN               MIST           Base            radius             0.003450214237514526
                                 mass_smaller_3  radius             0.003852158053551234
                                 mass_smaller_14 radius             0.003645181573049165
                                 mass_smaller_30 radius            0.0034746355786746423
linear_regression MIST           Base            radius             0.055659137790087646
                                 mass_smaller_3  radius              0.05305258723034893
                                 mass_smaller_14 radius              0.05206851487961322
                                 mass_smaller_30 radius              0.04911116678442271
mlp               MIST           Base            radius              0.06562476159464888
                                 mass_smaller_3  radius             0.011558274933319979
                                 mass_smaller_14 radius             0.020513073464717875
                                 mass_smaller_30 radius             0.031086217055393335
random_forest     MIST           Base            radius             0.002694836316878708
                                 mass_smaller_3  radius            0.0025324195768070693
                                 mass_smaller_14 radius            0.0029546148610459792
                                 mass_smaller_30 radius              0.00258361744057094
xgboost           MIST           Base            radius             0.010954257700611949
                                 mass_smaller_3  radius             0.007534879406329916
                                 mass_smaller_14 radius             0.008769671104498708
                                 mass_smaller_30 radius             0.009608870603818263

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.005224201914791282
                                 mass_smaller_3  radius             0.005917559811051132
                                 mass_smaller_14 radius             0.006049832233677943
                                 mass_smaller_30 radius             0.005629037287626204
KNN               MIST           Base            radius            0.0025531746141193024
                                 mass_smaller_3  radius            0.0030662762462867477
                                 mass_smaller_14 radius             0.002854713522677965
                                 mass_smaller_30 radius             0.002652679339220587
linear_regression MIST           Base            radius             0.029916386324884747
                                 mass_smaller_3  radius             0.046683992102352134
                                 mass_smaller_14 radius              0.04282191739355906
                                 mass_smaller_30 radius              0.03860285690378118
mlp               MIST           Base            radius              0.04380711242323043
                                 mass_smaller_3  radius             0.009501594815213621
                                 mass_smaller_14 radius             0.015041218647519727
                                 mass_smaller_30 radius             0.024559976126819594
random_forest     MIST           Base            radius            0.0017591556092366734
                                 mass_smaller_3  radius             0.001805420067699126
                                 mass_smaller_14 radius             0.002014089156679444
                                 mass_smaller_30 radius             0.001747377912543091
xgboost           MIST           Base            radius             0.008935811729372745
                                 mass_smaller_3  radius             0.005998065347735615
                                 mass_smaller_14 radius             0.007121132467737323
                                 mass_smaller_30 radius             0.007809194362370486

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997957313689314
                                 mass_smaller_3  radius             0.999779478999035
                                 mass_smaller_14 radius            0.9997619984887515
                                 mass_smaller_30 radius            0.9997492057116859
KNN               MIST           Base            radius            0.9999530987775218
                                 mass_smaller_3  radius            0.9999409608872045
                                 mass_smaller_14 radius            0.9999475475373238
                                 mass_smaller_30 radius            0.9999483907470569
linear_regression MIST           Base            radius            0.9845802131239262
                                 mass_smaller_3  radius            0.9952209519299173
                                 mass_smaller_14 radius             0.992189751850785
                                 mass_smaller_30 radius            0.9917120850902722
mlp               MIST           Base            radius            0.9818963992395894
                                 mass_smaller_3  radius            0.9995808035587692
                                 mass_smaller_14 radius             0.998607588204276
                                 mass_smaller_30 radius            0.9969638655840041
random_forest     MIST           Base            radius            0.9999668230698375
                                 mass_smaller_3  radius            0.9999695861358541
                                 mass_smaller_14 radius            0.9999592448517991
                                 mass_smaller_30 radius            0.9999674805098631
xgboost           MIST           Base            radius            0.9995923346285195
                                 mass_smaller_3  radius            0.9997726819919364
                                 mass_smaller_14 radius            0.9997088032289221
                                 mass_smaller_30 radius            0.9996354916781848

                                                                                 MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.3051654040090013
                                 mass_smaller_3  radius             0.11891552138317962
                                 mass_smaller_14 radius              0.1750836121341881
                                 mass_smaller_30 radius              0.8341740650426792
KNN               MIST           Base            radius             0.07185439050078646
                                 mass_smaller_3  radius             0.06103219438058893
                                 mass_smaller_14 radius            0.050980652738506826
                                 mass_smaller_30 radius             0.05680804827445396
linear_regression MIST           Base            radius             0.44653665980271207
                                 mass_smaller_3  radius              0.1826891264968893
                                 mass_smaller_14 radius             0.24111969566047264
                                 mass_smaller_30 radius             0.25332435335892356
mlp               MIST           Base            radius              0.4684602519572878
                                 mass_smaller_3  radius             0.06752888090148179
                                 mass_smaller_14 radius              0.0963852762935562
                                 mass_smaller_30 radius              0.2723470444962355
random_forest     MIST           Base            radius             0.07107360425912734
                                 mass_smaller_3  radius            0.044718073403115066
                                 mass_smaller_14 radius             0.05590281114078155
                                 mass_smaller_30 radius             0.04996632907326015
xgboost           MIST           Base            radius             0.11285984737620902
                                 mass_smaller_3  radius              0.0587070618717922
                                 mass_smaller_14 radius              0.0678817394138389
                                 mass_smaller_30 radius             0.08310079986036634

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.00908 / 90 : 0.01349 / 95 : 0.01668 / 99 : 0.03209
                                 mass_smaller_3  radius             75 : 0.01099 / 90 : 0.01394 / 95 : 0.01631 / 99 : 0.02894
                                 mass_smaller_14 radius             75 : 0.00984 / 90 : 0.01382 / 95 : 0.01725 / 99 : 0.03197
                                 mass_smaller_30 radius             75 : 0.00949 / 90 : 0.01363 / 95 : 0.01688 / 99 : 0.03151
KNN               MIST           Base            radius             75 : 0.00468 / 90 : 0.00769 / 95 : 0.00973 / 99 : 0.01442
                                 mass_smaller_3  radius               75 : 0.0053 / 90 : 0.0082 / 95 : 0.01005 / 99 : 0.01406
                                 mass_smaller_14 radius              75 : 0.00495 / 90 : 0.0079 / 95 : 0.00978 / 99 : 0.01379
                                 mass_smaller_30 radius             75 : 0.00477 / 90 : 0.00771 / 95 : 0.00962 / 99 : 0.01349
linear_regression MIST           Base            radius             75 : 0.07153 / 90 : 0.14014 / 95 : 0.18774 / 99 : 0.35102
                                 mass_smaller_3  radius             75 : 0.07504 / 90 : 0.10078 / 95 : 0.11591 / 99 : 0.14029
                                 mass_smaller_14 radius             75 : 0.07069 / 90 : 0.10203 / 95 : 0.12513 / 99 : 0.18058
                                 mass_smaller_30 radius             75 : 0.07063 / 90 : 0.10453 / 95 : 0.12773 / 99 : 0.18654
mlp               MIST           Base            radius             75 : 0.07877 / 90 : 0.14746 / 95 : 0.24459 / 99 : 0.34017
                                 mass_smaller_3  radius              75 : 0.01657 / 90 : 0.02466 / 95 : 0.0295 / 99 : 0.03869
                                 mass_smaller_14 radius              75 : 0.0279 / 90 : 0.04877 / 95 : 0.06142 / 99 : 0.07956
                                 mass_smaller_30 radius             75 : 0.04408 / 90 : 0.06762 / 95 : 0.08142 / 99 : 0.11124
random_forest     MIST           Base            radius             75 : 0.00361 / 90 : 0.00618 / 95 : 0.00827 / 99 : 0.01427
                                 mass_smaller_3  radius             75 : 0.00347 / 90 : 0.00567 / 95 : 0.00735 / 99 : 0.01147
                                 mass_smaller_14 radius             75 : 0.00399 / 90 : 0.00671 / 95 : 0.00883 / 99 : 0.01468
                                 mass_smaller_30 radius               75 : 0.0035 / 90 : 0.00593 / 95 : 0.0078 / 99 : 0.01267
xgboost           MIST           Base            radius             75 : 0.01553 / 90 : 0.02291 / 95 : 0.02798 / 99 : 0.03912
                                 mass_smaller_3  radius             75 : 0.01052 / 90 : 0.01598 / 95 : 0.01987 / 99 : 0.02873
                                 mass_smaller_14 radius              75 : 0.01242 / 90 : 0.01842 / 95 : 0.0226 / 99 : 0.03161
                                 mass_smaller_30 radius             75 : 0.01363 / 90 : 0.02025 / 95 : 0.02477 / 99 : 0.03421

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              25.21291995048523
                                 mass_smaller_3  radius             11.799425840377808
                                 mass_smaller_14 radius             18.232510805130005

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
KNN               MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
linear_regression MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
mlp               MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
random_forest     MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007
xgboost           MIST           Base            radius            -1.861069007171269 - 3.1297545143214007
                                 mass_smaller_3  radius             -1.861069007171269 - 2.772287451333455
                                 mass_smaller_14 radius            -1.859644360427887 - 3.0658785857783406
                                 mass_smaller_30 radius            -1.861069007171269 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9994488214856186
                                 mass_smaller_3  radius            0.9995610591594069
                                 mass_smaller_14 radius            0.9995284522938918
                                 mass_smaller_30 radius             0.999518246344412
KNN               MIST           Base            radius            0.9997529203147828
                                 mass_smaller_3  radius            0.9997205248038691
                                 mass_smaller_14 radius            0.9998098020686446
                                 mass_smaller_30 radius            0.9998064077445129
linear_regression MIST           Base            radius            0.9697033500946161
                                 mass_smaller_3  radius            0.9684680555577966
                                 mass_smaller_14 radius            0.9740874504101877
                                 mass_smaller_30 radius            0.9739536976742476
mlp               MIST           Base            radius            0.9641735799831238
                                 mass_smaller_3  radius            0.9988542704773874
                                 mass_smaller_14 radius            0.9979244705141928
                                 mass_smaller_30 radius            0.9907665619790221
random_forest     MIST           Base            radius            0.9997946315480227
                                 mass_smaller_3  radius            0.9998040195317754
                                 mass_smaller_14 radius            0.9998425719102682
                                 mass_smaller_30 radius            0.9998427577175978
xgboost           MIST           Base            radius            0.9978108990711222
                                 mass_smaller_3  radius            0.9974539660563065
                                 mass_smaller_14 radius            0.9964580637116783
                                 mass_smaller_30 radius            0.9973770136540635

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.01539969626666862
                                 mass_smaller_3  radius            0.013070929316932505
                                 mass_smaller_14 radius            0.013650398489648939
                                 mass_smaller_30 radius             0.01389575167202071
KNN               MIST           Base            radius             0.01030577426510625
                                 mass_smaller_3  radius            0.010427840393926212
                                 mass_smaller_14 radius            0.008673149483868709
                                 mass_smaller_30 radius             0.00881407804358179
linear_regression MIST           Base            radius             0.11529542651277243
                                 mass_smaller_3  radius             0.11301697835396873
                                 mass_smaller_14 radius             0.10206394356900259
                                 mass_smaller_30 radius             0.10307110536851516
mlp               MIST           Base            radius              0.1244148588119324
                                 mass_smaller_3  radius            0.021263554580899586
                                 mass_smaller_14 radius             0.02913183010024069
                                 mass_smaller_30 radius              0.0612519318100241
random_forest     MIST           Base            radius            0.009442479596902933
                                 mass_smaller_3  radius            0.008736181243265508
                                 mass_smaller_14 radius            0.007924058335185178
                                 mass_smaller_30 radius            0.007972704741764145
xgboost           MIST           Base            radius            0.030670504199222636
                                 mass_smaller_3  radius            0.031480949238054036
                                 mass_smaller_14 radius             0.03739294260387151
                                 mass_smaller_30 radius             0.03241865668810672

                                                                                     MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.008061327413956659
                                 mass_smaller_3  radius             0.006267070362646512
                                 mass_smaller_14 radius            0.0072741532700235185
                                 mass_smaller_30 radius             0.007440869915578349
KNN               MIST           Base            radius             0.005106399769743342
                                 mass_smaller_3  radius              0.00510458604927592
                                 mass_smaller_14 radius             0.004499751983339302
                                 mass_smaller_30 radius             0.004607975897602932
linear_regression MIST           Base            radius              0.07108589686874936
                                 mass_smaller_3  radius              0.07078174763374796
                                 mass_smaller_14 radius               0.0668223827975775
                                 mass_smaller_30 radius              0.06686584138177167
mlp               MIST           Base            radius              0.08083858107155989
                                 mass_smaller_3  radius             0.014783079030899463
                                 mass_smaller_14 radius             0.021270744522059994
                                 mass_smaller_30 radius             0.037782531209207916
random_forest     MIST           Base            radius             0.004476198636221196
                                 mass_smaller_3  radius            0.0037532571463249915
                                 mass_smaller_14 radius             0.004010186326215918
                                 mass_smaller_30 radius             0.003916211614178716
xgboost           MIST           Base            radius             0.014541160379559225
                                 mass_smaller_3  radius             0.011014907799612018
                                 mass_smaller_14 radius             0.012993853217312109
                                 mass_smaller_30 radius             0.013080012282406125

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.004021745057077419
                                 mass_smaller_3  radius            0.0028890165889379205
                                 mass_smaller_14 radius             0.003552037816514364
                                 mass_smaller_30 radius             0.003847691754808591
KNN               MIST           Base            radius              0.00263932261067068
                                 mass_smaller_3  radius             0.002556972964901094
                                 mass_smaller_14 radius            0.0024743618784415222
                                 mass_smaller_30 radius            0.0025538945300956906
linear_regression MIST           Base            radius              0.04013114351431346
                                 mass_smaller_3  radius              0.04994792649392288
                                 mass_smaller_14 radius             0.049247374755953865
                                 mass_smaller_30 radius               0.0469283268068183
mlp               MIST           Base            radius               0.0518899798581407
                                 mass_smaller_3  radius             0.010675623015242053
                                 mass_smaller_14 radius             0.016322991129258835
                                 mass_smaller_30 radius             0.027006018211822358
random_forest     MIST           Base            radius            0.0019954515767242054
                                 mass_smaller_3  radius            0.0015400653174786338
                                 mass_smaller_14 radius            0.0019082715405427386
                                 mass_smaller_30 radius            0.0018533432546462558
xgboost           MIST           Base            radius              0.00953513376862547
                                 mass_smaller_3  radius             0.005399120814039815
                                 mass_smaller_14 radius            0.0075440368273796965
                                 mass_smaller_30 radius             0.008255161654855181

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997244088360632
                                 mass_smaller_3  radius            0.9997806574982038
                                 mass_smaller_14 radius            0.9997642348388597
                                 mass_smaller_30 radius            0.9997591732890485
KNN               MIST           Base            radius            0.9998764909310184
                                 mass_smaller_3  radius            0.9998604449553452
                                 mass_smaller_14 radius            0.9999049072376036
                                 mass_smaller_30 radius            0.9999032219793856
linear_regression MIST           Base            radius            0.9851943973018029
                                 mass_smaller_3  radius            0.9841081337179995
                                 mass_smaller_14 radius            0.9870183381024721
                                 mass_smaller_30 radius            0.9870195443762908
mlp               MIST           Base            radius            0.9819569607521789
                                 mass_smaller_3  radius             0.999453049422036
                                 mass_smaller_14 radius            0.9989768725476394
                                 mass_smaller_30 radius            0.9955058760229845
random_forest     MIST           Base            radius            0.9998973620949058
                                 mass_smaller_3  radius            0.9999020274058216
                                 mass_smaller_14 radius            0.9999212945610508
                                 mass_smaller_30 radius            0.9999213892438928
xgboost           MIST           Base            radius            0.9989049593667946
                                 mass_smaller_3  radius            0.9987261719297972
                                 mass_smaller_14 radius            0.9982274725794851
                                 mass_smaller_30 radius            0.9986876875293155

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.30821055326246355
                                 mass_smaller_3  radius             0.3080413669013684
                                 mass_smaller_14 radius            0.19169201365028865
                                 mass_smaller_30 radius            0.36744245593030844
KNN               MIST           Base            radius            0.27880787293870035
                                 mass_smaller_3  radius            0.17596780530916556
                                 mass_smaller_14 radius            0.16948753721672638
                                 mass_smaller_30 radius            0.21195638156532765
linear_regression MIST           Base            radius             0.6754177015661889
                                 mass_smaller_3  radius              0.613371610834804
                                 mass_smaller_14 radius             0.5976239464782516
                                 mass_smaller_30 radius             0.6240646709658961
mlp               MIST           Base            radius             0.8434788426182683
                                 mass_smaller_3  radius             0.2266966943526767
                                 mass_smaller_14 radius            0.31574903891578354
                                 mass_smaller_30 radius             0.5854697900042987
random_forest     MIST           Base            radius            0.28770974092603363
                                 mass_smaller_3  radius            0.13567376296989764
                                 mass_smaller_14 radius            0.13060962532261078
                                 mass_smaller_30 radius            0.16484832827769735
xgboost           MIST           Base            radius             0.7666851796630024
                                 mass_smaller_3  radius             0.7003157608652608
                                 mass_smaller_14 radius             0.8814602412703633
                                 mass_smaller_30 radius             0.8704838143869863

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius                75 : 0.0094 / 90 : 0.01853 / 95 : 0.029 / 99 : 0.06667
                                 mass_smaller_3  radius              75 : 0.00714 / 90 : 0.0142 / 95 : 0.02237 / 99 : 0.06347
                                 mass_smaller_14 radius             75 : 0.00863 / 90 : 0.01721 / 95 : 0.02609 / 99 : 0.06032
                                 mass_smaller_30 radius              75 : 0.0089 / 90 : 0.01738 / 95 : 0.02605 / 99 : 0.05962
KNN               MIST           Base            radius             75 : 0.00598 / 90 : 0.01111 / 95 : 0.01646 / 99 : 0.04614
                                 mass_smaller_3  radius             75 : 0.00582 / 90 : 0.01116 / 95 : 0.01695 / 99 : 0.04808
                                 mass_smaller_14 radius             75 : 0.00557 / 90 : 0.00989 / 95 : 0.01391 / 99 : 0.03751
                                 mass_smaller_30 radius             75 : 0.00567 / 90 : 0.01022 / 95 : 0.01433 / 99 : 0.03793
linear_regression MIST           Base            radius             75 : 0.08139 / 90 : 0.17851 / 95 : 0.24939 / 99 : 0.51105
                                 mass_smaller_3  radius             75 : 0.08508 / 90 : 0.12212 / 95 : 0.19321 / 99 : 0.50204
                                 mass_smaller_14 radius             75 : 0.08014 / 90 : 0.12039 / 95 : 0.19118 / 99 : 0.47633
                                 mass_smaller_30 radius             75 : 0.08233 / 90 : 0.12875 / 95 : 0.19209 / 99 : 0.48852
mlp               MIST           Base            radius              75 : 0.09772 / 90 : 0.19511 / 95 : 0.27774 / 99 : 0.4788
                                 mass_smaller_3  radius               75 : 0.01955 / 90 : 0.0314 / 95 : 0.04283 / 99 : 0.0706
                                 mass_smaller_14 radius             75 : 0.02938 / 90 : 0.04551 / 95 : 0.05587 / 99 : 0.09423
                                 mass_smaller_30 radius             75 : 0.04729 / 90 : 0.07313 / 95 : 0.09806 / 99 : 0.25807
random_forest     MIST           Base            radius             75 : 0.00501 / 90 : 0.01038 / 95 : 0.01609 / 99 : 0.04204
                                 mass_smaller_3  radius             75 : 0.00378 / 90 : 0.00805 / 95 : 0.01412 / 99 : 0.04246
                                 mass_smaller_14 radius               75 : 0.00474 / 90 : 0.0096 / 95 : 0.0142 / 99 : 0.03265
                                 mass_smaller_30 radius             75 : 0.00457 / 90 : 0.00923 / 95 : 0.01386 / 99 : 0.03231
xgboost           MIST           Base            radius             75 : 0.01738 / 90 : 0.02808 / 95 : 0.03739 / 99 : 0.08879
                                 mass_smaller_3  radius             75 : 0.01028 / 90 : 0.01881 / 95 : 0.03105 / 99 : 0.11646
                                 mass_smaller_14 radius              75 : 0.01364 / 90 : 0.02195 / 95 : 0.0302 / 99 : 0.10566
                                 mass_smaller_30 radius              75 : 0.01501 / 90 : 0.02373 / 95 : 0.03142 / 99 : 0.0873

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              25.21291995048523
                                 mass_smaller_3  radius             11.799425840377808
                                 mass_smaller_14 radius             18.232510805130005

Linear regression : 
- mass_smaller_3 : better/similar results than Base on every metric except MedAE
- mass_smaller_14 : better results than Base on every metric except for MedAE which is similar
- mass_smaller_30 : better results than Base on every metric except for MedAE which is similar, very similar to mass_smaller_14

Decision tree : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : better or similar results than Base on every metric except MAX_ER, less improvement than mass_smaller_3 and mass_smaller_14

KNN : 
- mass_smaller_3 : similar results than Base except for MAX_ER which is better
- mass_smaller_14 : better results than Base on every metric
- mass_smaller_30 : better results than Base on every metric but less than mass_smaller_14

Random forest : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric, less than mass_smaller_3 except for MAX_ER
- mass_smaller_30 : better results than Base on every metric, less than mass_smaller_3 and mass_smaller_14

XGBoost : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric except on RMSE and MAX_ER
- mass_smaller_30 : better results than Base on every metric except on MAX_ER

MLP : 
- mass_smaller_3 : way better results than Base on every metric
- mass_smaller_14 : way better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : way better results than Base on every metric but less than mass_smaller_3 and mass_smaller_14

#### Conclusions on radius

mass_smaller_3 almost always gives better results than Base.

mass_smaller_14 almost always gives better results than Base but most of the time it improves less than mass_smaller_3. Although it is more consistently better.

mass_smaller_30 almost always gives better results than Base but most of the time it improves less than mass_smaller_3 and mass_smaller_14

#### Best models for the radius parameter

The three best performing models in order for the radius parameter are Random forest, KNN and Decision tree.

### Conclusion on both

It seems that using the filtering mass_smaller_14 gives better results for radius and gives less high errors for the mass.

This filtering might be the best choice as it is also the range of values for PARSEC which would make comparing models between the two easier.