# Results comparison for MIST filtering of model B

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [5]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [6]:
pre_path = "../../../../../../"
path = pre_path + "results/model_B/default_models"

In [7]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 5.379
                             mass_smaller_3  T_eff             3.345 - 4.301
                             mass_smaller_14 T_eff             3.345 - 4.634
                             mass_smaller_30 T_eff             3.345 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.967  0.063
                             mass_smaller_3  T_eff             0.957  0.038
                             mass_smaller_14 T_eff             0.967  0.052
                             mass_smaller_30 T_eff             0.964  0.060

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.016  0.001
                             mass_smaller_3  T_eff             0.014  0.001
                             mass_smaller_14 T_eff             0.013  0.001
                             mass_smaller_30 T_eff             0.015  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.984   0.933
                             mass_smaller_3  T_eff             0.978   0.430
                             mass_smaller_14 T_eff             0.984   0.889
                             mass_smaller_30 T_eff             0.982   0.914

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                             mass_smaller_3  T_eff              75 : 0.00557 / 90 : 0.04726 / 95 : 0.09124 / 99 : 0.17501
                             mass_smaller_14 T_eff               75 : 0.00383 / 90 : 0.02721 / 95 : 0.0747 / 99 : 0.19805
                             mass_smaller_30 T_eff               75 : 0.00376 / 90 : 0.02825 / 95 : 0.0807 / 99 : 0.26673

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 0.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 4.903
                             mass_smaller_3  T_eff             3.345 - 4.301
                             mass_smaller_14 T_eff             3.345 - 4.634
                             mass_smaller_30 T_eff             3.345 - 4.898

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.974  0.057
                             mass_smaller_3  T_eff             0.986  0.023
                             mass_smaller_14 T_eff             0.981  0.041
                             mass_smaller_30 T_eff             0.973  0.053

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.010  0.001
                             mass_smaller_3  T_eff             0.005  0.000
                             mass_smaller_14 T_eff             0.006  0.001
                             mass_smaller_30 T_eff             0.009  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.897
                             mass_smaller_3  T_eff             0.993   0.430
                             mass_smaller_14 T_eff             0.991   0.889
                             mass_smaller_30 T_eff             0.987   0.905

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                             mass_smaller_3  T_eff              75 : 0.00127 / 90 : 0.00358 / 95 : 0.01051 / 99 : 0.13035
                             mass_smaller_14 T_eff               75 : 0.0013 / 90 : 0.00354 / 95 : 0.00867 / 99 : 0.14171
                             mass_smaller_30 T_eff               75 : 0.00138 / 90 : 0.00417 / 95 : 0.01479 / 99 : 0.2421

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 2.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.428 - 4.711
                             mass_smaller_3  T_eff             3.431 - 4.277
                             mass_smaller_14 T_eff             3.425 - 4.588
                             mass_smaller_30 T_eff             3.425 - 4.675

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.975  0.050
                             mass_smaller_3  T_eff             0.844  0.057
                             mass_smaller_14 T_eff             0.956  0.052
                             mass_smaller_30 T_eff             0.969  0.050

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.020  0.002
                             mass_smaller_3  T_eff             0.033  0.008
                             mass_smaller_14 T_eff             0.022  0.003
                             mass_smaller_30 T_eff             0.021  0.002

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.713
                             mass_smaller_3  T_eff             0.920   0.308
                             mass_smaller_14 T_eff             0.978   0.723
                             mass_smaller_30 T_eff             0.985   0.698

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                             mass_smaller_3  T_eff              75 : 0.04972 / 90 : 0.10192 / 95 : 0.13515 / 99 : 0.19473
                             mass_smaller_14 T_eff              75 : 0.01781 / 90 : 0.07692 / 95 : 0.11807 / 99 : 0.19909
                             mass_smaller_30 T_eff              75 : 0.01371 / 90 : 0.07218 / 95 : 0.11434 / 99 : 0.19716

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 3.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.352 - 5.379
                             mass_smaller_3  T_eff             3.352 - 4.208
                             mass_smaller_14 T_eff             3.352 - 4.524
                             mass_smaller_30 T_eff             3.352 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.918  0.089
                             mass_smaller_3  T_eff             0.918  0.043
                             mass_smaller_14 T_eff             0.896  0.073
                             mass_smaller_30 T_eff             0.904  0.085

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.027  0.003
                             mass_smaller_3  T_eff             0.017  0.003
                             mass_smaller_14 T_eff             0.021  0.003
                             mass_smaller_30 T_eff             0.024  0.003

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.959   0.933
                             mass_smaller_3  T_eff             0.958   0.419
                             mass_smaller_14 T_eff             0.947   0.873
                             mass_smaller_30 T_eff             0.952   0.914

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                             mass_smaller_3  T_eff              75 : 0.01337 / 90 : 0.05079 / 95 : 0.08983 / 99 : 0.20541
                             mass_smaller_14 T_eff              75 : 0.01102 / 90 : 0.04317 / 95 : 0.09179 / 99 : 0.40046
                             mass_smaller_30 T_eff              75 : 0.01092 / 90 : 0.04684 / 95 : 0.10789 / 99 : 0.49952

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

In [8]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff", "radius"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129
KNN               MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129
linear_regression MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129
mlp               MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129
random_forest     MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129
xgboost           MIST           Base   T_eff              3.345 - 5.379
                                        radius            -0.997 - 3.129

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.950  0.077  0.019
                                        radius            0.816  0.317  0.088
KNN               MIST           Base   T_eff             0.967  0.063  0.019
                                        radius            0.904  0.228  0.076
linear_regression MIST           Base   T_eff             0.736  0.178  0.144
                                        radius            0.199  0.661  0.546
mlp               MIST           Base   T_eff             0.850  0.135  0.092
                                        radius            0.757  0.366  0.242
random_forest     MIST           Base   T_eff             0.967  0.063  0.016
                                        radius            0.878  0.258  0.076
xgboost           MIST           Base   T_eff             0.901  0.109  0.069
                                        radius            0.825  0.309  0.199

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.002  0.975
                                        radius            0.005  0.908
KNN               MIST           Base   T_eff             0.002  0.984
                                        radius            0.004  0.951
linear_regression MIST           Base   T_eff             0.132  0.858
                                        radius            0.474  0.446
mlp               MIST           Base   T_eff             0.055  0.922
                                        radius            0.126  0.870
random_forest     MIST           Base   T_eff             0.001  0.984
                                        radius            0.002  0.938
xgboost           MIST           Base   T_eff             0.035  0.949
                                        radius            0.100  0.909

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.951
                                        radius             2.835
KNN               MIST           Base   T_eff              0.926
                                        radius             2.837
linear_regression MIST           Base   T_eff              0.982
                                        radius             2.044
mlp               MIST           Base   T_eff              0.977
                                        radius             2.832
random_forest     MIST           Base   T_eff              0.933
                                        radius             2.835
xgboost           MIST           Base   T_eff              0.874
                                        radius             2.580

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00427 / 90 : 0.02166 / 95 : 0.09746 / 99 : 0.42345
                                        radius             75 : 0.01029 / 90 : 0.10613 / 95 : 0.68142 / 99 : 1.67507
KNN               MIST           Base   T_eff              75 : 0.00622 / 90 : 0.04667 / 95 : 0.09982 / 99 : 0.31342
                                        radius             75 : 0.01766 / 90 : 0.23258 / 95 : 0.51127 / 99 : 1.08571
linear_regression MIST           Base   T_eff              75 : 0.19925 / 90 : 0.26261 / 95 : 0.33491 / 99 : 0.49514
                                        radius              75 : 0.7361 / 90 : 1.09566 / 95 : 1.29908 / 99 : 1.60347
mlp               MIST           Base   T_eff              75 : 0.12551 / 90 : 0.23121 / 95 : 0.30635 / 99 : 0.43044
                                        radius              75 : 0.38607 / 90 : 0.65018 / 95 : 0.79762 / 99 : 1.1283
random_forest     MIST           Base   T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                        radius             75 : 0.00955 / 90 : 0.16761 / 95 : 0.57416 / 99 : 1.29851
xgboost           MIST           Base   T_eff              75 : 0.09802 / 90 : 0.18339 / 95 : 0.25166 / 99 : 0.37352
                                        radius             75 : 0.30188 / 90 : 0.53827 / 95 : 0.68623 / 99 : 0.98445

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        radius             17.973

Results for the phase category with a value of 0.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
KNN               MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
linear_regression MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
mlp               MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
random_forest     MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083
xgboost           MIST           Base   T_eff              3.345 - 4.903
                                        radius            -0.997 - 3.083

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.960  0.070  0.012
                                        radius            0.836  0.232  0.038
KNN               MIST           Base   T_eff             0.969  0.063  0.016
                                        radius            0.896  0.187  0.046
linear_regression MIST           Base   T_eff             0.750  0.179  0.153
                                        radius            0.445  0.626  0.524
mlp               MIST           Base   T_eff             0.889  0.126  0.081
                                        radius            0.746  0.328  0.189
random_forest     MIST           Base   T_eff             0.974  0.057  0.010
                                        radius            0.896  0.186  0.034
xgboost           MIST           Base   T_eff             0.941  0.092  0.051
                                        radius            0.833  0.255  0.141

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.001  0.980
                                        radius            0.003  0.927
KNN               MIST           Base   T_eff             0.001  0.984
                                        radius            0.002  0.954
linear_regression MIST           Base   T_eff             0.154  0.866
                                        radius            0.476  0.672
mlp               MIST           Base   T_eff             0.042  0.943
                                        radius            0.042  0.904
random_forest     MIST           Base   T_eff             0.001  0.987
                                        radius            0.001  0.952
xgboost           MIST           Base   T_eff             0.016  0.970
                                        radius            0.039  0.932

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.951
                                        radius             2.834
KNN               MIST           Base   T_eff              0.926
                                        radius             2.788
linear_regression MIST           Base   T_eff              0.716
                                        radius             2.044
mlp               MIST           Base   T_eff              0.800
                                        radius             1.997
random_forest     MIST           Base   T_eff              0.897
                                        radius             2.792
xgboost           MIST           Base   T_eff              0.809
                                        radius             2.580

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00256 / 90 : 0.00472 / 95 : 0.01174 / 99 : 0.40476
                                        radius             75 : 0.00541 / 90 : 0.01099 / 95 : 0.02123 / 99 : 1.55013
KNN               MIST           Base   T_eff               75 : 0.00325 / 90 : 0.01865 / 95 : 0.09229 / 99 : 0.3282
                                        radius             75 : 0.00734 / 90 : 0.04884 / 95 : 0.27305 / 99 : 0.98907
linear_regression MIST           Base   T_eff              75 : 0.21036 / 90 : 0.25684 / 95 : 0.30189 / 99 : 0.43765
                                        radius              75 : 0.70451 / 90 : 1.01007 / 95 : 1.20991 / 99 : 1.4882
mlp               MIST           Base   T_eff              75 : 0.10075 / 90 : 0.22594 / 95 : 0.30755 / 99 : 0.42108
                                        radius              75 : 0.30629 / 90 : 0.62338 / 95 : 0.76159 / 99 : 1.0468
random_forest     MIST           Base   T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                        radius              75 : 0.00317 / 90 : 0.01073 / 95 : 0.0708 / 99 : 1.10175
xgboost           MIST           Base   T_eff              75 : 0.06239 / 90 : 0.15626 / 95 : 0.22213 / 99 : 0.34633
                                        radius             75 : 0.18636 / 90 : 0.44548 / 95 : 0.59782 / 99 : 0.86036

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        radius             17.973

Results for the phase category with a value of 2.0

                                                            value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892
KNN               MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892
linear_regression MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892
mlp               MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892
random_forest     MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892
xgboost           MIST           Base   T_eff             3.428 - 4.711
                                        radius            0.092 - 2.892

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.959  0.064  0.024
                                        radius            0.233  0.430  0.176
KNN               MIST           Base   T_eff             0.984  0.041  0.017
                                        radius            0.651  0.290  0.124
linear_regression MIST           Base   T_eff             0.781  0.148  0.119
                                        radius            0.305  0.583  0.463
mlp               MIST           Base   T_eff             0.842  0.126  0.097
                                        radius            0.421  0.373  0.292
random_forest     MIST           Base   T_eff             0.975  0.050  0.020
                                        radius            0.473  0.357  0.151
xgboost           MIST           Base   T_eff             0.874  0.114  0.085
                                        radius            0.496  0.352  0.264

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.003  0.979
                                        radius            0.008  0.624
KNN               MIST           Base   T_eff             0.002  0.992
                                        radius            0.005  0.812
linear_regression MIST           Base   T_eff             0.106  0.884
                                        radius            0.365  0.567
mlp               MIST           Base   T_eff             0.077  0.918
                                        radius            0.236  0.653
random_forest     MIST           Base   T_eff             0.002  0.987
                                        radius            0.005  0.721
xgboost           MIST           Base   T_eff             0.065  0.936
                                        radius            0.198  0.706

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.847
                                        radius             2.292
KNN               MIST           Base   T_eff              0.713
                                        radius             2.294
linear_regression MIST           Base   T_eff              0.631
                                        radius             1.789
mlp               MIST           Base   T_eff              0.653
                                        radius             1.819
random_forest     MIST           Base   T_eff              0.713
                                        radius             2.273
xgboost           MIST           Base   T_eff              0.510
                                        radius             1.868

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00789 / 90 : 0.08242 / 95 : 0.13794 / 99 : 0.23584
                                        radius             75 : 0.02253 / 90 : 0.75231 / 95 : 1.16764 / 99 : 1.73219
KNN               MIST           Base   T_eff               75 : 0.01087 / 90 : 0.05726 / 95 : 0.0917 / 99 : 0.16337
                                        radius             75 : 0.07659 / 90 : 0.48896 / 95 : 0.73686 / 99 : 1.16087
linear_regression MIST           Base   T_eff              75 : 0.16587 / 90 : 0.22216 / 95 : 0.28347 / 99 : 0.42765
                                        radius             75 : 0.66783 / 90 : 1.01223 / 95 : 1.19363 / 99 : 1.41452
mlp               MIST           Base   T_eff               75 : 0.1347 / 90 : 0.20956 / 95 : 0.26236 / 99 : 0.35663
                                        radius              75 : 0.42069 / 90 : 0.6229 / 95 : 0.75123 / 99 : 1.00833
random_forest     MIST           Base   T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                        radius              75 : 0.06932 / 90 : 0.61818 / 95 : 0.93156 / 99 : 1.4339
xgboost           MIST           Base   T_eff              75 : 0.11863 / 90 : 0.18832 / 95 : 0.24477 / 99 : 0.34599
                                        radius             75 : 0.38554 / 90 : 0.58881 / 95 : 0.72605 / 99 : 1.01489

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        radius             17.973

Results for the phase category with a value of 3.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129
KNN               MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129
linear_regression MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129
mlp               MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129
random_forest     MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129
xgboost           MIST           Base   T_eff              3.352 - 5.379
                                        radius            -0.345 - 3.129

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.881  0.106  0.030
                                        radius            0.659  0.337  0.103
KNN               MIST           Base   T_eff             0.927  0.084  0.029
                                        radius            0.835  0.235  0.091
linear_regression MIST           Base   T_eff             0.605  0.210  0.153
                                        radius            0.398  0.835  0.726
mlp               MIST           Base   T_eff             0.762  0.165  0.115
                                        radius            0.564  0.448  0.319
random_forest     MIST           Base   T_eff             0.918  0.089  0.027
                                        radius            0.782  0.269  0.090
xgboost           MIST           Base   T_eff             0.838  0.140  0.097
                                        radius            0.713  0.375  0.268

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.003  0.941
                                        radius            0.009  0.825
KNN               MIST           Base   T_eff             0.004  0.964
                                        radius            0.012  0.914
linear_regression MIST           Base   T_eff             0.106  0.787
                                        radius            0.585  0.649
mlp               MIST           Base   T_eff             0.075  0.878
                                        radius            0.207  0.767
random_forest     MIST           Base   T_eff             0.003  0.959
                                        radius            0.008  0.885
xgboost           MIST           Base   T_eff             0.063  0.916
                                        radius            0.175  0.851

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.931
                                        radius             2.835
KNN               MIST           Base   T_eff              0.917
                                        radius             2.837
linear_regression MIST           Base   T_eff              0.982
                                        radius             2.005
mlp               MIST           Base   T_eff              0.977
                                        radius             2.832
random_forest     MIST           Base   T_eff              0.933
                                        radius             2.835
xgboost           MIST           Base   T_eff              0.874
                                        radius             2.529

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff               75 : 0.00987 / 90 : 0.05367 / 95 : 0.15861 / 99 : 0.6234
                                        radius             75 : 0.02388 / 90 : 0.21487 / 95 : 0.68696 / 99 : 1.78702
KNN               MIST           Base   T_eff              75 : 0.01918 / 90 : 0.06825 / 95 : 0.14393 / 99 : 0.43934
                                        radius             75 : 0.05998 / 90 : 0.26646 / 95 : 0.48254 / 99 : 1.12352
linear_regression MIST           Base   T_eff              75 : 0.21166 / 90 : 0.36121 / 95 : 0.45759 / 99 : 0.60611
                                        radius              75 : 0.96961 / 90 : 1.4046 / 95 : 1.56771 / 99 : 1.78381
mlp               MIST           Base   T_eff               75 : 0.15645 / 90 : 0.2835 / 95 : 0.35727 / 99 : 0.54147
                                        radius              75 : 0.4601 / 90 : 0.78299 / 95 : 0.97979 / 99 : 1.32053
random_forest     MIST           Base   T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                        radius              75 : 0.03635 / 90 : 0.22815 / 95 : 0.5328 / 99 : 1.43515
xgboost           MIST           Base   T_eff               75 : 0.13011 / 90 : 0.24272 / 95 : 0.3206 / 99 : 0.43713
                                        radius             75 : 0.39342 / 90 : 0.65163 / 95 : 0.80015 / 99 : 1.13247

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        radius             17.973

## Getting the ranges for the values

In [9]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [11]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':('<', 3)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 6.2 - 10.3, Mean : 9.0993, Median : 9.2

log_Teff  : Range : 3.34 - 4.3013, Mean : 3.795, Median : 3.7533

log_g  : Range : -1.08 - 5.4331, Mean : 3.6429, Median : 4.1661

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 3.0, Mean : 1.3237, Median : 1.1896

log_R  : Range : -1.0 - 2.7813, Mean : 0.4164, Median : 0.2391

log_L  : Range : -3.33 - 4.02, Mean : 0.9675, Median : 1.3998

## Base vs Base_old

| Parameter      | Base                                                    | Base_old                                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 5.0 - 10.3, Mean : 8.4794, Median : 8.6        |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 298.5448, Mean : 7.3915, Median : 2.0304 |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.5871, Mean : 3.8475, Median : 3.6808  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.14 - 8.6121, Mean : 2.1347, Median : 2.0681 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -2.09 - 3.1298, Mean : 1.3543, Median : 1.4604 |

In [14]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 5.37868
                                      log_g              -1.1449 - 6.25943
                                      radius            -0.99747 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.84057  0.13893
                                      log_g             0.53144  1.30405
                                      radius            0.52940  0.65205

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.06595  0.00496
                                      log_g             0.66420  0.04437
                                      radius            0.33219  0.02224

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.91784  0.92909
                                      log_g             0.74112  5.61441
                                      radius            0.73982  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.07238 / 90 : 0.23285 / 95 : 0.34978 / 99 : 0.55705
                                      log_g               75 : 0.8517 / 90 : 2.48049 / 95 : 3.35619 / 99 : 4.51164
                                      radius             75 : 0.42592 / 90 : 1.24044 / 95 : 1.67813 / 99 : 2.25528

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 0.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 4.90341
                                      log_g             -0.59731 - 5.43309
                                      radius            -0.99747 - 3.08275

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80756  0.17157
                                      log_g            -4.35760  1.64296
                                      radius           -0.60430  0.82151

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07950  0.00103
                                      log_g             0.80682  0.00363
                                      radius            0.40370  0.00236

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.92091  0.89901
                                      log_g             0.37651  5.53132
                                      radius            0.54466  2.76740

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.08557 / 90 : 0.31563 / 95 : 0.45697 / 99 : 0.61308
                                      log_g              75 : 0.99833 / 90 : 3.51157 / 95 : 4.17142 / 99 : 4.81185
                                      radius             75 : 0.49971 / 90 : 1.75563 / 95 : 2.08579 / 99 : 2.40556

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 2.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.42453 - 4.71147
                                      log_g             -0.32878 - 4.40831
                                      radius             0.09099 - 2.89171

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.94636  0.07473
                                      log_g             0.01356  0.91497
                                      radius            0.15317  0.45748

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.03289  0.00313
                                      log_g             0.44560  0.01634
                                      radius            0.22280  0.00818

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.97366  0.72262
                                      log_g             0.51031  4.42512
                                      radius            0.56223  2.21252

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff               75 : 0.03253 / 90 : 0.10746 / 95 : 0.16429 / 99 : 0.3427
                                      log_g              75 : 0.52112 / 90 : 1.74899 / 95 : 2.32971 / 99 : 3.29739
                                      radius             75 : 0.26054 / 90 : 0.87451 / 95 : 1.16479 / 99 : 1.64861

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 3.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.35162 - 5.37868
                                      log_g             -1.07485 - 6.25943
                                      radius            -0.34459 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80007  0.14211
                                      log_g             0.25851  0.94071
                                      radius            0.39723  0.47044

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07204  0.01308
                                      log_g             0.53570  0.10649
                                      radius            0.26792  0.05325

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.89988  0.92909
                                      log_g             0.62390  5.43249
                                      radius            0.68217  2.71757

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09139 / 90 : 0.22968 / 95 : 0.34287 / 99 : 0.56025
                                      log_g                75 : 0.866 / 90 : 1.76549 / 95 : 2.20904 / 99 : 3.03616
                                      radius             75 : 0.43322 / 90 : 0.88292 / 95 : 1.10456 / 99 : 1.51874

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 4.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             3.45536 - 5.16499
                                      log_g               -0.862 - 5.4397
                                      radius            0.18216 - 3.07966

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.59184  0.12532
                                      log_g             0.25238  0.77030
                                      radius            0.51498  0.38512

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.05624  0.01049
                                      log_g             0.42572  0.12590
                                      radius            0.21285  0.06296

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80964  0.86611
                                      log_g             0.61631  5.23203
                                      radius            0.75184  2.61593

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff               75 : 0.04701 / 90 : 0.1757 / 95 : 0.31484 / 99 : 0.55476
                                      log_g              75 : 0.57838 / 90 : 1.30897 / 95 : 1.84395 / 99 : 2.88357
                                      radius             75 : 0.28916 / 90 : 0.65428 / 95 : 0.92196 / 99 : 1.44147

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             3.34914 - 5.17056
                                      log_g             -1.1449 - 5.46002
                                      radius                0.172 - 3.054

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff            -2.48156  0.13114
                                      log_g            -6.30552  1.32320
                                      radius           -3.88181  0.66162

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.06905  0.01082
                                      log_g             0.73508  0.11967
                                      radius            0.36753  0.05983

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.47116  0.76615
                                      log_g             0.13059  5.61441
                                      radius            0.24499  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09369 / 90 : 0.23484 / 95 : 0.32494 / 99 : 0.47661
                                      log_g               75 : 1.0951 / 90 : 2.57832 / 95 : 3.21253 / 99 : 4.24664
                                      radius               75 : 0.54747 / 90 : 1.289 / 95 : 1.60623 / 99 : 2.12374

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

In [16]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.34467 - 5.3788
                                      log_g              -1.0829 - 6.25943
                                      radius            -0.99746 - 3.12927
                             Base_old T_eff              3.34467 - 5.37868
                                      log_g              -1.1449 - 6.25943
                                      radius            -0.99747 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.96719  0.06264
                                      log_g             0.81983  0.51625
                                      radius            0.87761  0.25822
                             Base_old T_eff             0.84057  0.13893
                                      log_g             0.53144  1.30405
                                      radius            0.52940  0.65205

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01611  0.00101
                                      log_g             0.15238  0.00412
                                      radius            0.07640  0.00233
                             Base_old T_eff             0.06595  0.00496
                                      log_g             0.66420  0.04437
                                      radius            0.33219  0.02224

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98351  0.93308
                                      log_g             0.90761  5.67025
                                      radius            0.93773  2.83521
                             Base_old T_eff             0.91784  0.92909
                                      log_g             0.74112  5.61441
                                      radius            0.73982  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                      log_g               75 : 0.0185 / 90 : 0.33483 / 95 : 1.14725 / 99 : 2.59569
                                      radius             75 : 0.00955 / 90 : 0.16761 / 95 : 0.57416 / 99 : 1.29851
                             Base_old T_eff              75 : 0.07238 / 90 : 0.23285 / 95 : 0.34978 / 99 : 0.55705
                                      log_g               75 : 0.8517 / 90 : 2.48049 / 95 : 3.35619 / 99 : 4.51164
                                      radius             75 : 0.42592 / 90 : 1.24044 / 95 : 1.67813 / 99 : 2.25528

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 0.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.34467 - 4.90341
                                      log_g             -0.59678 - 5.43307
                                      radius            -0.99746 - 3.08275
                             Base_old T_eff              3.34467 - 4.90341
                                      log_g             -0.59731 - 5.43309
                                      radius            -0.99747 - 3.08275

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.97420  0.05672
                                      log_g             0.65564  0.37094
                                      radius            0.89594  0.18567
                             Base_old T_eff             0.80756  0.17157
                                      log_g            -4.35760  1.64296
                                      radius           -0.60430  0.82151

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01024  0.00058
                                      log_g             0.06819  0.00176
                                      radius            0.03446  0.00115
                             Base_old T_eff             0.07950  0.00103
                                      log_g             0.80682  0.00363
                                      radius            0.40370  0.00236

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98713  0.89738
                                      log_g             0.86381  5.58083
                                      radius            0.95156  2.79213
                             Base_old T_eff             0.92091  0.89901
                                      log_g             0.37651  5.53132
                                      radius            0.54466  2.76740

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                      log_g              75 : 0.00525 / 90 : 0.01949 / 95 : 0.14109 / 99 : 2.20116
                                      radius              75 : 0.00317 / 90 : 0.01073 / 95 : 0.0708 / 99 : 1.10175
                             Base_old T_eff              75 : 0.08557 / 90 : 0.31563 / 95 : 0.45697 / 99 : 0.61308
                                      log_g              75 : 0.99833 / 90 : 3.51157 / 95 : 4.17142 / 99 : 4.81185
                                      radius             75 : 0.49971 / 90 : 1.75563 / 95 : 2.08579 / 99 : 2.40556

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 2.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.42786 - 4.71147
                                      log_g             -0.29592 - 4.40831
                                      radius             0.09199 - 2.89171
                             Base_old T_eff              3.42453 - 4.71147
                                      log_g             -0.32878 - 4.40831
                                      radius             0.09099 - 2.89171

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.97488  0.05016
                                      log_g             0.38691  0.71305
                                      radius            0.47265  0.35652
                             Base_old T_eff             0.94636  0.07473
                                      log_g             0.01356  0.91497
                                      radius            0.15317  0.45748

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01991  0.00210
                                      log_g             0.30152  0.01023
                                      radius            0.15076  0.00513
                             Base_old T_eff             0.03289  0.00313
                                      log_g             0.44560  0.01634
                                      radius            0.22280  0.00818

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98736  0.71261
                                      log_g             0.66352  4.54661
                                      radius            0.72091  2.27333
                             Base_old T_eff             0.97366  0.72262
                                      log_g             0.51031  4.42512
                                      radius            0.56223  2.21252

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                      log_g              75 : 0.13861 / 90 : 1.23629 / 95 : 1.86362 / 99 : 2.86772
                                      radius              75 : 0.06932 / 90 : 0.61818 / 95 : 0.93156 / 99 : 1.4339
                             Base_old T_eff               75 : 0.03253 / 90 : 0.10746 / 95 : 0.16429 / 99 : 0.3427
                                      log_g              75 : 0.52112 / 90 : 1.74899 / 95 : 2.32971 / 99 : 3.29739
                                      radius             75 : 0.26054 / 90 : 0.87451 / 95 : 1.16479 / 99 : 1.64861

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 3.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.35162 - 5.3788
                                      log_g              -1.0829 - 6.25943
                                      radius            -0.34459 - 3.12927
                             Base_old T_eff              3.35162 - 5.37868
                                      log_g             -1.07485 - 6.25943
                                      radius            -0.34459 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.91798  0.08865
                                      log_g             0.73284  0.53858
                                      radius            0.78222  0.26940
                             Base_old T_eff             0.80007  0.14211
                                      log_g             0.25851  0.94071
                                      radius            0.39723  0.47044

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.02720  0.00314
                                      log_g             0.18010  0.01689
                                      radius            0.09011  0.00845
                             Base_old T_eff             0.07204  0.01308
                                      log_g             0.53570  0.10649
                                      radius            0.26792  0.05325

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.95873  0.93308
                                      log_g             0.85841  5.67025
                                      radius            0.88536  2.83521
                             Base_old T_eff             0.89988  0.92909
                                      log_g             0.62390  5.43249
                                      radius            0.68217  2.71757

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                      log_g              75 : 0.07269 / 90 : 0.45574 / 95 : 1.06538 / 99 : 2.86521
                                      radius              75 : 0.03635 / 90 : 0.22815 / 95 : 0.5328 / 99 : 1.43515
                             Base_old T_eff              75 : 0.09139 / 90 : 0.22968 / 95 : 0.34287 / 99 : 0.56025
                                      log_g                75 : 0.866 / 90 : 1.76549 / 95 : 2.20904 / 99 : 3.03616
                                      radius             75 : 0.43322 / 90 : 0.88292 / 95 : 1.10456 / 99 : 1.51874

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

In [17]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.344668191350628 - 5.378801600728572
                                      log_g             -1.0828963170617296 - 6.259434356871683
                                      radius            -0.9974628481553472 - 3.129269620812593
                             Base_old T_eff               3.344668191350628 - 5.378675973625695
                                      log_g               -1.14489780699774 - 6.259434356871683
                                      radius            -0.9974747647513328 - 3.129269620812593

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9671910035107978
                                      log_g             0.8198256636371155
                                      radius            0.8776105127019214
                             Base_old T_eff             0.8405722178416324
                                      log_g             0.5314380568631798
                                      radius            0.5294025708949806

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.07936%  0.79178%
                                      log_g              7.03112%  2.07541%
                                      radius             6.25728%  1.85127%
                             Base_old T_eff              6.83041%  3.24253%
                                      log_g             17.61203%  8.97044%
                                      radius            15.80052%  8.04974%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.04971%
                                      log_g             0.05608%
                                      radius            0.05635%
                             Base_old T_eff             0.24375%
                                      log_g              0.5992%
                                      radius            0.53897%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9835135887268114
                                      log_g             0.9076055609149075
                                      radius            0.9377254771026249
                             Base_old T_eff             0.9178359321898323
                                      log_g             0.7411154874957776
                                      radius            0.7398210409174621

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             45.87133%
                                      log_g             77.22678%
                                      radius             68.7036%
                             Base_old T_eff             45.67783%
                                      log_g             75.82596%
                                      radius            68.02711%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.19271% / 90 : 1.52252% / 95 : 4.29814% / 99 : 15.59239%
                                      log_g                75 : 0.25196% / 90 : 4.56027% / 95 : 15.62515% / 99 : 35.3524%
                                      radius              75 : 0.23142% / 90 : 4.06157% / 95 : 13.91319% / 99 : 31.46581%
                             Base_old T_eff              75 : 3.55849% / 90 : 11.44784% / 95 : 17.19659% / 99 : 27.38682%
                                      log_g             75 : 11.50273% / 90 : 33.50052% / 95 : 45.32738% / 99 : 60.93244%
                                      radius            75 : 10.32097% / 90 : 30.05856% / 95 : 40.66474% / 99 : 54.65034%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 0.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                 3.344668191350628 - 4.90340707004253
                                      log_g              -0.5967768342670462 - 5.433070637654307
                                      radius            -0.9974628481553472 - 3.0827540579576227
                             Base_old T_eff                 3.344668191350628 - 4.90340707004253
                                      log_g              -0.5973100835175252 - 5.433094523832443
                                      radius            -0.9974747647513328 - 3.0827540579576227

                                                                        RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              0.9741964262283933
                                      log_g               0.655638939150234
                                      radius              0.895944647709672
                             Base_old T_eff              0.8075611489100274
                                      log_g               -4.35760028643572
                                      radius            -0.6043004559884961

                                                             RMSE        MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.63894%   0.65716%
                                      log_g              6.15166%   1.13095%
                                      radius             4.55042%   0.84445%
                             Base_old T_eff             11.00682%   5.10023%
                                      log_g             27.24468%  13.37923%
                                      radius            20.13395%   9.89413%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.03705%
                                      log_g             0.02924%
                                      radius            0.02822%
                             Base_old T_eff             0.06583%
                                      log_g             0.06012%
                                      radius            0.05774%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9871344752716238
                                      log_g              0.863807624437327
                                      radius            0.9515577145193358
                             Base_old T_eff             0.9209118656585242
                                      log_g             0.3765108921511524
                                      radius            0.5446576008706236

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             57.57081%
                                      log_g             92.55336%
                                      radius            68.43104%
                             Base_old T_eff             57.67556%
                                      log_g             91.72381%
                                      radius             67.8246%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                    75 : 0.09559% / 90 : 0.32398% / 95 : 1.43% / 99 : 19.7647%
                                      log_g                75 : 0.08707% / 90 : 0.32323% / 95 : 2.33986% / 99 : 36.50441%
                                      radius                75 : 0.07769% / 90 : 0.26298% / 95 : 1.7352% / 99 : 27.00224%
                             Base_old T_eff               75 : 5.48969% / 90 : 20.24906% / 95 : 29.31665% / 99 : 39.3318%
                                      log_g             75 : 16.55494% / 90 : 58.23108% / 95 : 69.17314% / 99 : 79.79315%
                                      radius             75 : 12.24711% / 90 : 43.02773% / 95 : 51.11944% / 99 : 58.9565%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 2.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                3.42785685311742 - 4.711472733477716
                                      log_g             -0.2959230723262505 - 4.408311770676233
                                      radius             0.0919862423867022 - 2.891706235288321
                             Base_old T_eff               3.424526073183654 - 4.711472733477716
                                      log_g             -0.3287802371627256 - 4.408311770676233
                                      radius             0.0909920840275404 - 2.891706235288321

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               0.9748807497002827
                                      log_g              0.38691114604182897
                                      radius             0.47265136875136293
                             Base_old T_eff               0.9463609440149476
                                      log_g             0.013557431677446496
                                      radius             0.15317328940586838

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.90772%  1.55124%
                                      log_g             15.15768%  6.40953%
                                      radius            12.73409%   5.3849%
                             Base_old T_eff               5.8064%   2.5557%
                                      log_g             19.31497%  9.40665%
                                      radius            16.33443%  7.95519%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.16334%
                                      log_g             0.21754%
                                      radius            0.18312%
                             Base_old T_eff             0.24331%
                                      log_g             0.34488%
                                      radius            0.29199%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9873643484911543
                                      log_g             0.6635177579267701
                                      radius            0.7209068216276289
                             Base_old T_eff             0.9736585453129091
                                      log_g             0.5103084799376272
                                      radius            0.5622317588684937

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             55.51569%
                                      log_g             96.64932%
                                      radius             81.1983%
                             Base_old T_eff             56.15027%
                                      log_g             93.41425%
                                      radius             78.9986%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.87098% / 90 : 5.38011% / 95 : 8.67783% / 99 : 15.51321%
                                      log_g              75 : 2.94649% / 90 : 26.28036% / 95 : 39.61579% / 99 : 60.96039%
                                      radius             75 : 2.47596% / 90 : 22.08007% / 95 : 33.27333% / 99 : 51.21584%
                             Base_old T_eff                  75 : 2.52769% / 90 : 8.35% / 95 : 12.76587% / 99 : 26.62892%
                                      log_g             75 : 11.00084% / 90 : 36.92117% / 95 : 49.18017% / 99 : 69.60789%
                                      radius             75 : 9.30263% / 90 : 31.22454% / 95 : 41.58904% / 99 : 58.86392%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 3.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.3516171610778134 - 5.378801600728572
                                      log_g             -1.0828963170617296 - 6.259434356871683
                                      radius            -0.3445863859219699 - 3.129269620812593
                             Base_old T_eff              3.3516171610778134 - 5.378675973625695
                                      log_g              -1.074853654540692 - 6.259434356871683
                                      radius            -0.3445863859219699 - 3.129269620812593

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9179849306556465
                                      log_g             0.7328442946232603
                                      radius            0.7822157797380761
                             Base_old T_eff             0.8000731487510342
                                      log_g             0.2585106887735762
                                      radius             0.397229303297262

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              4.37315%  1.34172%
                                      log_g              7.33521%   2.4529%
                                      radius             7.75509%  2.59391%
                             Base_old T_eff              7.01041%  3.55404%
                                      log_g             12.82615%  7.30402%
                                      radius            13.54228%  7.71256%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.15483%
                                      log_g             0.23001%
                                      radius             0.2432%
                             Base_old T_eff             0.64525%
                                      log_g             1.45192%
                                      radius            1.53275%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9587327279611804
                                      log_g             0.8584121763316808
                                      radius            0.8853617266109324
                             Base_old T_eff             0.8998755106353982
                                      log_g              0.623904841285878
                                      radius            0.6821740223416446

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             46.02857%
                                      log_g             77.22678%
                                      radius            81.61575%
                             Base_old T_eff             45.83442%
                                      log_g              74.0698%
                                      radius            78.22922%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.61317% / 90 : 2.86703% / 95 : 6.65998% / 99 : 24.21832%
                                      log_g               75 : 0.99001% / 90 : 6.20702% / 95 : 14.51011% / 99 : 39.02317%
                                      radius              75 : 1.04639% / 90 : 6.56763% / 95 : 15.33742% / 99 : 41.31288%
                             Base_old T_eff                75 : 4.5085% / 90 : 11.3307% / 95 : 16.91465% / 99 : 27.63857%
                                      log_g             75 : 11.80755% / 90 : 24.07173% / 95 : 30.11935% / 99 : 41.39679%
                                      radius            75 : 12.47087% / 90 : 25.41614% / 95 : 31.79637% / 99 : 43.71914%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

### Conclusion

Removing phase 4 and 5 (EAGB and TPAGB) improves the results by a lot. 

Since there are no more superposition possible between phase 0 and 5 (MS and TPAGB), the results for the phase 0 drastically improved (2x to 4x better results for different statistics)

Phase 2 also improved (RGB), although not as much as phase 0.

Same with phase 3 (CHeB).

However, the results are not that good. Even for Random forest, the RMSE is quite high (3, 7 and 6% relative error).

## Base vs mass_filtered

| Parameter      | Base                                                    | mass_filtered_smaller_3                                | mass_filtered_smaller_14                               | mass_filtered_smaller_30                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5        | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289  | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537 | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357 | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### T_eff parameter

In [19]:
compare_metrics(path, value_rounding=5, relative_values=False,
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
KNN               MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
linear_regression MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
mlp               MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
random_forest     MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
xgboost           MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95021
                                 mass_smaller_3  T_eff             0.93383
                                 mass_smaller_14 T_eff             0.95001
                                 mass_smaller_30 T_eff             0.94563
KNN               MIST           Base            T_eff             0.96733
                                 mass_smaller_3  T_eff             0.96945
                                 mass_smaller_14 T_eff             0.97390
                                 mass_smaller_30 T_eff             0.96956
linear_regression MIST           Base            T_eff             0.73552
                                 mass_smaller_3  T_eff             0.64139
                                 mass_smaller_14 T_eff             0.67901
                                 mass_smaller_30 T_eff             0.71899
mlp               MIST           Base            T_eff             0.84981
                                 mass_smaller_3  T_eff             0.73249
                                 mass_smaller_14 T_eff             0.80153
                                 mass_smaller_30 T_eff             0.71904
random_forest     MIST           Base            T_eff             0.96719
                                 mass_smaller_3  T_eff             0.95676
                                 mass_smaller_14 T_eff             0.96741
                                 mass_smaller_30 T_eff             0.96429
xgboost           MIST           Base            T_eff             0.90068
                                 mass_smaller_3  T_eff             0.90393
                                 mass_smaller_14 T_eff             0.86912
                                 mass_smaller_30 T_eff             0.88596

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.07717
                                 mass_smaller_3  T_eff             0.04728
                                 mass_smaller_14 T_eff             0.06387
                                 mass_smaller_30 T_eff             0.07408
KNN               MIST           Base            T_eff             0.06255
                                 mass_smaller_3  T_eff             0.03212
                                 mass_smaller_14 T_eff             0.04616
                                 mass_smaller_30 T_eff             0.05545
linear_regression MIST           Base            T_eff             0.17783
                                 mass_smaller_3  T_eff             0.11005
                                 mass_smaller_14 T_eff             0.16184
                                 mass_smaller_30 T_eff             0.16840
mlp               MIST           Base            T_eff             0.13459
                                 mass_smaller_3  T_eff             0.09696
                                 mass_smaller_14 T_eff             0.12946
                                 mass_smaller_30 T_eff             0.16882
random_forest     MIST           Base            T_eff             0.06264
                                 mass_smaller_3  T_eff             0.03822
                                 mass_smaller_14 T_eff             0.05157
                                 mass_smaller_30 T_eff             0.06004
xgboost           MIST           Base            T_eff             0.10898
                                 mass_smaller_3  T_eff             0.05696
                                 mass_smaller_14 T_eff             0.10334
                                 mass_smaller_30 T_eff             0.10728

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.01857
                                 mass_smaller_3  T_eff             0.01659
                                 mass_smaller_14 T_eff             0.01549
                                 mass_smaller_30 T_eff             0.01736
KNN               MIST           Base            T_eff             0.01861
                                 mass_smaller_3  T_eff             0.01231
                                 mass_smaller_14 T_eff             0.01262
                                 mass_smaller_30 T_eff             0.01521
linear_regression MIST           Base            T_eff             0.14378
                                 mass_smaller_3  T_eff             0.09070
                                 mass_smaller_14 T_eff             0.12885
                                 mass_smaller_30 T_eff             0.13277
mlp               MIST           Base            T_eff             0.09181
                                 mass_smaller_3  T_eff             0.07338
                                 mass_smaller_14 T_eff             0.09084
                                 mass_smaller_30 T_eff             0.11704
random_forest     MIST           Base            T_eff             0.01611
                                 mass_smaller_3  T_eff             0.01413
                                 mass_smaller_14 T_eff             0.01326
                                 mass_smaller_30 T_eff             0.01496
xgboost           MIST           Base            T_eff             0.06890
                                 mass_smaller_3  T_eff             0.03655
                                 mass_smaller_14 T_eff             0.06461
                                 mass_smaller_30 T_eff             0.06693

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00174
                                 mass_smaller_3  T_eff             0.00152
                                 mass_smaller_14 T_eff             0.00171
                                 mass_smaller_30 T_eff             0.00169
KNN               MIST           Base            T_eff             0.00168
                                 mass_smaller_3  T_eff             0.00176
                                 mass_smaller_14 T_eff             0.00155
                                 mass_smaller_30 T_eff             0.00156
linear_regression MIST           Base            T_eff             0.13156
                                 mass_smaller_3  T_eff             0.08197
                                 mass_smaller_14 T_eff             0.11623
                                 mass_smaller_30 T_eff             0.11708
mlp               MIST           Base            T_eff             0.05510
                                 mass_smaller_3  T_eff             0.05296
                                 mass_smaller_14 T_eff             0.05654
                                 mass_smaller_30 T_eff             0.07226
random_forest     MIST           Base            T_eff             0.00101
                                 mass_smaller_3  T_eff             0.00103
                                 mass_smaller_14 T_eff             0.00102
                                 mass_smaller_30 T_eff             0.00099
xgboost           MIST           Base            T_eff             0.03453
                                 mass_smaller_3  T_eff             0.01589
                                 mass_smaller_14 T_eff             0.03081
                                 mass_smaller_30 T_eff             0.03244

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.97513
                                 mass_smaller_3  T_eff             0.96698
                                 mass_smaller_14 T_eff             0.97503
                                 mass_smaller_30 T_eff             0.97284
KNN               MIST           Base            T_eff             0.98353
                                 mass_smaller_3  T_eff             0.98463
                                 mass_smaller_14 T_eff             0.98687
                                 mass_smaller_30 T_eff             0.98467
linear_regression MIST           Base            T_eff             0.85762
                                 mass_smaller_3  T_eff             0.80087
                                 mass_smaller_14 T_eff             0.82402
                                 mass_smaller_30 T_eff             0.84794
mlp               MIST           Base            T_eff             0.92191
                                 mass_smaller_3  T_eff             0.85942
                                 mass_smaller_14 T_eff             0.89530
                                 mass_smaller_30 T_eff             0.85265
random_forest     MIST           Base            T_eff             0.98351
                                 mass_smaller_3  T_eff             0.97824
                                 mass_smaller_14 T_eff             0.98362
                                 mass_smaller_30 T_eff             0.98205
xgboost           MIST           Base            T_eff             0.94909
                                 mass_smaller_3  T_eff             0.95097
                                 mass_smaller_14 T_eff             0.93234
                                 mass_smaller_30 T_eff             0.94131

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95071
                                 mass_smaller_3  T_eff             0.44718
                                 mass_smaller_14 T_eff             0.91705
                                 mass_smaller_30 T_eff             0.95102
KNN               MIST           Base            T_eff             0.92644
                                 mass_smaller_3  T_eff             0.41705
                                 mass_smaller_14 T_eff             0.88595
                                 mass_smaller_30 T_eff             0.91990
linear_regression MIST           Base            T_eff             0.98202
                                 mass_smaller_3  T_eff             0.39655
                                 mass_smaller_14 T_eff             0.76832
                                 mass_smaller_30 T_eff             0.95037
mlp               MIST           Base            T_eff             0.97704
                                 mass_smaller_3  T_eff             0.52459
                                 mass_smaller_14 T_eff             0.64463
                                 mass_smaller_30 T_eff             1.04212
random_forest     MIST           Base            T_eff             0.93308
                                 mass_smaller_3  T_eff             0.43044
                                 mass_smaller_14 T_eff             0.88883
                                 mass_smaller_30 T_eff             0.91376
xgboost           MIST           Base            T_eff             0.87367
                                 mass_smaller_3  T_eff             0.38800
                                 mass_smaller_14 T_eff             0.82046
                                 mass_smaller_30 T_eff             0.85115

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00427 / 90 : 0.02166 / 95 : 0.09746 / 99 : 0.42345
                                 mass_smaller_3  T_eff              75 : 0.00472 / 90 : 0.05086 / 95 : 0.11507 / 99 : 0.22325
                                 mass_smaller_14 T_eff               75 : 0.0043 / 90 : 0.02023 / 95 : 0.08661 / 99 : 0.24334
                                 mass_smaller_30 T_eff               75 : 0.00419 / 90 : 0.01996 / 95 : 0.0916 / 99 : 0.32118
KNN               MIST           Base            T_eff              75 : 0.00622 / 90 : 0.04667 / 95 : 0.09982 / 99 : 0.31342
                                 mass_smaller_3  T_eff              75 : 0.00564 / 90 : 0.04037 / 95 : 0.07343 / 99 : 0.14317
                                 mass_smaller_14 T_eff              75 : 0.00473 / 90 : 0.02803 / 95 : 0.06703 / 99 : 0.17616
                                 mass_smaller_30 T_eff               75 : 0.0051 / 90 : 0.03435 / 95 : 0.07975 / 99 : 0.25305
linear_regression MIST           Base            T_eff              75 : 0.19925 / 90 : 0.26261 / 95 : 0.33491 / 99 : 0.49514
                                 mass_smaller_3  T_eff              75 : 0.13308 / 90 : 0.17305 / 95 : 0.19823 / 99 : 0.27515
                                 mass_smaller_14 T_eff              75 : 0.18093 / 90 : 0.23499 / 95 : 0.28624 / 99 : 0.50201
                                 mass_smaller_30 T_eff               75 : 0.18644 / 90 : 0.24577 / 95 : 0.3075 / 99 : 0.53499
mlp               MIST           Base            T_eff              75 : 0.12551 / 90 : 0.23121 / 95 : 0.30635 / 99 : 0.43044
                                 mass_smaller_3  T_eff              75 : 0.11483 / 90 : 0.16631 / 95 : 0.19743 / 99 : 0.25269
                                 mass_smaller_14 T_eff              75 : 0.12599 / 90 : 0.22804 / 95 : 0.29284 / 99 : 0.40039
                                 mass_smaller_30 T_eff              75 : 0.16288 / 90 : 0.29303 / 95 : 0.37757 / 99 : 0.51242
random_forest     MIST           Base            T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                 mass_smaller_3  T_eff              75 : 0.00557 / 90 : 0.04726 / 95 : 0.09124 / 99 : 0.17501
                                 mass_smaller_14 T_eff               75 : 0.00383 / 90 : 0.02721 / 95 : 0.0747 / 99 : 0.19805
                                 mass_smaller_30 T_eff               75 : 0.00376 / 90 : 0.02825 / 95 : 0.0807 / 99 : 0.26673
xgboost           MIST           Base            T_eff              75 : 0.09802 / 90 : 0.18339 / 95 : 0.25166 / 99 : 0.37352
                                 mass_smaller_3  T_eff               75 : 0.05806 / 90 : 0.10125 / 95 : 0.1285 / 99 : 0.18066
                                 mass_smaller_14 T_eff              75 : 0.09281 / 90 : 0.17298 / 95 : 0.23878 / 99 : 0.36132
                                 mass_smaller_30 T_eff                75 : 0.09515 / 90 : 0.1785 / 95 : 0.2475 / 99 : 0.37369

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 0.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
KNN               MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
linear_regression MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
mlp               MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
random_forest     MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
xgboost           MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.96019
                                 mass_smaller_3  T_eff             0.97740
                                 mass_smaller_14 T_eff             0.97099
                                 mass_smaller_30 T_eff             0.95823
KNN               MIST           Base            T_eff             0.96900
                                 mass_smaller_3  T_eff             0.98948
                                 mass_smaller_14 T_eff             0.98135
                                 mass_smaller_30 T_eff             0.97281
linear_regression MIST           Base            T_eff             0.75037
                                 mass_smaller_3  T_eff             0.79522
                                 mass_smaller_14 T_eff             0.74704
                                 mass_smaller_30 T_eff             0.74064
mlp               MIST           Base            T_eff             0.88942
                                 mass_smaller_3  T_eff             0.84068
                                 mass_smaller_14 T_eff             0.85328
                                 mass_smaller_30 T_eff             0.81285
random_forest     MIST           Base            T_eff             0.97420
                                 mass_smaller_3  T_eff             0.98642
                                 mass_smaller_14 T_eff             0.98125
                                 mass_smaller_30 T_eff             0.97319
xgboost           MIST           Base            T_eff             0.94101
                                 mass_smaller_3  T_eff             0.95885
                                 mass_smaller_14 T_eff             0.93300
                                 mass_smaller_30 T_eff             0.93384

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.07035
                                 mass_smaller_3  T_eff             0.03011
                                 mass_smaller_14 T_eff             0.05092
                                 mass_smaller_30 T_eff             0.06634
KNN               MIST           Base            T_eff             0.06264
                                 mass_smaller_3  T_eff             0.02057
                                 mass_smaller_14 T_eff             0.04099
                                 mass_smaller_30 T_eff             0.05382
linear_regression MIST           Base            T_eff             0.17867
                                 mass_smaller_3  T_eff             0.10012
                                 mass_smaller_14 T_eff             0.15761
                                 mass_smaller_30 T_eff             0.16967
mlp               MIST           Base            T_eff             0.12627
                                 mass_smaller_3  T_eff             0.09428
                                 mass_smaller_14 T_eff             0.13013
                                 mass_smaller_30 T_eff             0.14971
random_forest     MIST           Base            T_eff             0.05672
                                 mass_smaller_3  T_eff             0.02343
                                 mass_smaller_14 T_eff             0.04100
                                 mass_smaller_30 T_eff             0.05322
xgboost           MIST           Base            T_eff             0.09214
                                 mass_smaller_3  T_eff             0.04324
                                 mass_smaller_14 T_eff             0.08433
                                 mass_smaller_30 T_eff             0.09000

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.01167
                                 mass_smaller_3  T_eff             0.00564
                                 mass_smaller_14 T_eff             0.00702
                                 mass_smaller_30 T_eff             0.01014
KNN               MIST           Base            T_eff             0.01575
                                 mass_smaller_3  T_eff             0.00459
                                 mass_smaller_14 T_eff             0.00715
                                 mass_smaller_30 T_eff             0.01125
linear_regression MIST           Base            T_eff             0.15277
                                 mass_smaller_3  T_eff             0.08566
                                 mass_smaller_14 T_eff             0.13580
                                 mass_smaller_30 T_eff             0.14250
mlp               MIST           Base            T_eff             0.08112
                                 mass_smaller_3  T_eff             0.06911
                                 mass_smaller_14 T_eff             0.08671
                                 mass_smaller_30 T_eff             0.09505
random_forest     MIST           Base            T_eff             0.01024
                                 mass_smaller_3  T_eff             0.00475
                                 mass_smaller_14 T_eff             0.00597
                                 mass_smaller_30 T_eff             0.00880
xgboost           MIST           Base            T_eff             0.05084
                                 mass_smaller_3  T_eff             0.02268
                                 mass_smaller_14 T_eff             0.04437
                                 mass_smaller_30 T_eff             0.04853

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00115
                                 mass_smaller_3  T_eff             0.00086
                                 mass_smaller_14 T_eff             0.00102
                                 mass_smaller_30 T_eff             0.00107
KNN               MIST           Base            T_eff             0.00119
                                 mass_smaller_3  T_eff             0.00114
                                 mass_smaller_14 T_eff             0.00098
                                 mass_smaller_30 T_eff             0.00104
linear_regression MIST           Base            T_eff             0.15386
                                 mass_smaller_3  T_eff             0.08274
                                 mass_smaller_14 T_eff             0.13979
                                 mass_smaller_30 T_eff             0.14259
mlp               MIST           Base            T_eff             0.04218
                                 mass_smaller_3  T_eff             0.04259
                                 mass_smaller_14 T_eff             0.04772
                                 mass_smaller_30 T_eff             0.04996
random_forest     MIST           Base            T_eff             0.00058
                                 mass_smaller_3  T_eff             0.00049
                                 mass_smaller_14 T_eff             0.00053
                                 mass_smaller_30 T_eff             0.00055
xgboost           MIST           Base            T_eff             0.01609
                                 mass_smaller_3  T_eff             0.00665
                                 mass_smaller_14 T_eff             0.01270
                                 mass_smaller_30 T_eff             0.01441

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.98031
                                 mass_smaller_3  T_eff             0.98902
                                 mass_smaller_14 T_eff             0.98570
                                 mass_smaller_30 T_eff             0.97937
KNN               MIST           Base            T_eff             0.98438
                                 mass_smaller_3  T_eff             0.99482
                                 mass_smaller_14 T_eff             0.99066
                                 mass_smaller_30 T_eff             0.98633
linear_regression MIST           Base            T_eff             0.86626
                                 mass_smaller_3  T_eff             0.89971
                                 mass_smaller_14 T_eff             0.86536
                                 mass_smaller_30 T_eff             0.86061
mlp               MIST           Base            T_eff             0.94349
                                 mass_smaller_3  T_eff             0.91846
                                 mass_smaller_14 T_eff             0.92401
                                 mass_smaller_30 T_eff             0.90391
random_forest     MIST           Base            T_eff             0.98713
                                 mass_smaller_3  T_eff             0.99335
                                 mass_smaller_14 T_eff             0.99069
                                 mass_smaller_30 T_eff             0.98664
xgboost           MIST           Base            T_eff             0.97034
                                 mass_smaller_3  T_eff             0.97921
                                 mass_smaller_14 T_eff             0.96598
                                 mass_smaller_30 T_eff             0.96652

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95071
                                 mass_smaller_3  T_eff             0.43652
                                 mass_smaller_14 T_eff             0.91705
                                 mass_smaller_30 T_eff             0.95102
KNN               MIST           Base            T_eff             0.92644
                                 mass_smaller_3  T_eff             0.41705
                                 mass_smaller_14 T_eff             0.88582
                                 mass_smaller_30 T_eff             0.91990
linear_regression MIST           Base            T_eff             0.71583
                                 mass_smaller_3  T_eff             0.22314
                                 mass_smaller_14 T_eff             0.76832
                                 mass_smaller_30 T_eff             0.74677
mlp               MIST           Base            T_eff             0.80023
                                 mass_smaller_3  T_eff             0.31988
                                 mass_smaller_14 T_eff             0.59585
                                 mass_smaller_30 T_eff             1.03406
random_forest     MIST           Base            T_eff             0.89738
                                 mass_smaller_3  T_eff             0.43044
                                 mass_smaller_14 T_eff             0.88883
                                 mass_smaller_30 T_eff             0.90517
xgboost           MIST           Base            T_eff             0.80948
                                 mass_smaller_3  T_eff             0.29387
                                 mass_smaller_14 T_eff             0.75278
                                 mass_smaller_30 T_eff             0.81510

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00256 / 90 : 0.00472 / 95 : 0.01174 / 99 : 0.40476
                                 mass_smaller_3  T_eff              75 : 0.00197 / 90 : 0.00419 / 95 : 0.00773 / 99 : 0.19471
                                 mass_smaller_14 T_eff              75 : 0.00223 / 90 : 0.00399 / 95 : 0.00729 / 99 : 0.19457
                                 mass_smaller_30 T_eff              75 : 0.00237 / 90 : 0.00428 / 95 : 0.00946 / 99 : 0.28001
KNN               MIST           Base            T_eff               75 : 0.00325 / 90 : 0.01865 / 95 : 0.09229 / 99 : 0.3282
                                 mass_smaller_3  T_eff               75 : 0.0024 / 90 : 0.00458 / 95 : 0.00705 / 99 : 0.10441
                                 mass_smaller_14 T_eff               75 : 0.00233 / 90 : 0.00531 / 95 : 0.0105 / 99 : 0.15692
                                 mass_smaller_30 T_eff               75 : 0.00263 / 90 : 0.00762 / 95 : 0.04414 / 99 : 0.2751
linear_regression MIST           Base            T_eff              75 : 0.21036 / 90 : 0.25684 / 95 : 0.30189 / 99 : 0.43765
                                 mass_smaller_3  T_eff               75 : 0.12842 / 90 : 0.15487 / 95 : 0.1725 / 99 : 0.19345
                                 mass_smaller_14 T_eff              75 : 0.19274 / 90 : 0.23077 / 95 : 0.24862 / 99 : 0.33349
                                 mass_smaller_30 T_eff              75 : 0.20117 / 90 : 0.24367 / 95 : 0.26761 / 99 : 0.43833
mlp               MIST           Base            T_eff              75 : 0.10075 / 90 : 0.22594 / 95 : 0.30755 / 99 : 0.42108
                                 mass_smaller_3  T_eff              75 : 0.11639 / 90 : 0.16656 / 95 : 0.19535 / 99 : 0.24359
                                 mass_smaller_14 T_eff              75 : 0.11091 / 90 : 0.23916 / 95 : 0.30743 / 99 : 0.41344
                                 mass_smaller_30 T_eff              75 : 0.10867 / 90 : 0.27364 / 95 : 0.37476 / 99 : 0.47961
random_forest     MIST           Base            T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                 mass_smaller_3  T_eff              75 : 0.00127 / 90 : 0.00358 / 95 : 0.01051 / 99 : 0.13035
                                 mass_smaller_14 T_eff               75 : 0.0013 / 90 : 0.00354 / 95 : 0.00867 / 99 : 0.14171
                                 mass_smaller_30 T_eff               75 : 0.00138 / 90 : 0.00417 / 95 : 0.01479 / 99 : 0.2421
xgboost           MIST           Base            T_eff              75 : 0.06239 / 90 : 0.15626 / 95 : 0.22213 / 99 : 0.34633
                                 mass_smaller_3  T_eff              75 : 0.02135 / 90 : 0.07711 / 95 : 0.10589 / 99 : 0.16856
                                 mass_smaller_14 T_eff              75 : 0.04967 / 90 : 0.13734 / 95 : 0.20064 / 99 : 0.33639
                                 mass_smaller_30 T_eff                75 : 0.05789 / 90 : 0.1498 / 95 : 0.2151 / 99 : 0.35203

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 2.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
KNN               MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
linear_regression MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
mlp               MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
random_forest     MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
xgboost           MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95901
                                 mass_smaller_3  T_eff             0.77096
                                 mass_smaller_14 T_eff             0.92890
                                 mass_smaller_30 T_eff             0.95004
KNN               MIST           Base            T_eff             0.98360
                                 mass_smaller_3  T_eff             0.89345
                                 mass_smaller_14 T_eff             0.97242
                                 mass_smaller_30 T_eff             0.98139
linear_regression MIST           Base            T_eff             0.78059
                                 mass_smaller_3  T_eff             0.51209
                                 mass_smaller_14 T_eff             0.67815
                                 mass_smaller_30 T_eff             0.77809
mlp               MIST           Base            T_eff             0.84182
                                 mass_smaller_3  T_eff             0.53268
                                 mass_smaller_14 T_eff             0.73524
                                 mass_smaller_30 T_eff             0.61403
random_forest     MIST           Base            T_eff             0.97488
                                 mass_smaller_3  T_eff             0.84432
                                 mass_smaller_14 T_eff             0.95553
                                 mass_smaller_30 T_eff             0.96945
xgboost           MIST           Base            T_eff             0.87438
                                 mass_smaller_3  T_eff             0.75926
                                 mass_smaller_14 T_eff             0.77876
                                 mass_smaller_30 T_eff             0.84459

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.06407
                                 mass_smaller_3  T_eff             0.06883
                                 mass_smaller_14 T_eff             0.06550
                                 mass_smaller_30 T_eff             0.06445
KNN               MIST           Base            T_eff             0.04053
                                 mass_smaller_3  T_eff             0.04703
                                 mass_smaller_14 T_eff             0.04081
                                 mass_smaller_30 T_eff             0.03934
linear_regression MIST           Base            T_eff             0.14837
                                 mass_smaller_3  T_eff             0.11229
                                 mass_smaller_14 T_eff             0.14258
                                 mass_smaller_30 T_eff             0.13675
mlp               MIST           Base            T_eff             0.12586
                                 mass_smaller_3  T_eff             0.10020
                                 mass_smaller_14 T_eff             0.12643
                                 mass_smaller_30 T_eff             0.17930
random_forest     MIST           Base            T_eff             0.05016
                                 mass_smaller_3  T_eff             0.05684
                                 mass_smaller_14 T_eff             0.05181
                                 mass_smaller_30 T_eff             0.05040
xgboost           MIST           Base            T_eff             0.11425
                                 mass_smaller_3  T_eff             0.07337
                                 mass_smaller_14 T_eff             0.11845
                                 mass_smaller_30 T_eff             0.11604

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.02389
                                 mass_smaller_3  T_eff             0.03871
                                 mass_smaller_14 T_eff             0.02674
                                 mass_smaller_30 T_eff             0.02496
KNN               MIST           Base            T_eff             0.01684
                                 mass_smaller_3  T_eff             0.02689
                                 mass_smaller_14 T_eff             0.01830
                                 mass_smaller_30 T_eff             0.01705
linear_regression MIST           Base            T_eff             0.11891
                                 mass_smaller_3  T_eff             0.09124
                                 mass_smaller_14 T_eff             0.10823
                                 mass_smaller_30 T_eff             0.10625
mlp               MIST           Base            T_eff             0.09677
                                 mass_smaller_3  T_eff             0.08033
                                 mass_smaller_14 T_eff             0.09732
                                 mass_smaller_30 T_eff             0.13958
random_forest     MIST           Base            T_eff             0.01991
                                 mass_smaller_3  T_eff             0.03267
                                 mass_smaller_14 T_eff             0.02226
                                 mass_smaller_30 T_eff             0.02075
xgboost           MIST           Base            T_eff             0.08532
                                 mass_smaller_3  T_eff             0.05884
                                 mass_smaller_14 T_eff             0.08986
                                 mass_smaller_30 T_eff             0.08681

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00323
                                 mass_smaller_3  T_eff             0.00480
                                 mass_smaller_14 T_eff             0.00370
                                 mass_smaller_30 T_eff             0.00341
KNN               MIST           Base            T_eff             0.00216
                                 mass_smaller_3  T_eff             0.00665
                                 mass_smaller_14 T_eff             0.00266
                                 mass_smaller_30 T_eff             0.00229
linear_regression MIST           Base            T_eff             0.10571
                                 mass_smaller_3  T_eff             0.07963
                                 mass_smaller_14 T_eff             0.08911
                                 mass_smaller_30 T_eff             0.08979
mlp               MIST           Base            T_eff             0.07663
                                 mass_smaller_3  T_eff             0.06775
                                 mass_smaller_14 T_eff             0.07779
                                 mass_smaller_30 T_eff             0.11259
random_forest     MIST           Base            T_eff             0.00210
                                 mass_smaller_3  T_eff             0.00784
                                 mass_smaller_14 T_eff             0.00265
                                 mass_smaller_30 T_eff             0.00228
xgboost           MIST           Base            T_eff             0.06484
                                 mass_smaller_3  T_eff             0.05041
                                 mass_smaller_14 T_eff             0.07014
                                 mass_smaller_30 T_eff             0.06588

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.97945
                                 mass_smaller_3  T_eff             0.88476
                                 mass_smaller_14 T_eff             0.96418
                                 mass_smaller_30 T_eff             0.97489
KNN               MIST           Base            T_eff             0.99177
                                 mass_smaller_3  T_eff             0.94532
                                 mass_smaller_14 T_eff             0.98613
                                 mass_smaller_30 T_eff             0.99066
linear_regression MIST           Base            T_eff             0.88380
                                 mass_smaller_3  T_eff             0.73973
                                 mass_smaller_14 T_eff             0.82514
                                 mass_smaller_30 T_eff             0.88241
mlp               MIST           Base            T_eff             0.91766
                                 mass_smaller_3  T_eff             0.75574
                                 mass_smaller_14 T_eff             0.85764
                                 mass_smaller_30 T_eff             0.79799
random_forest     MIST           Base            T_eff             0.98736
                                 mass_smaller_3  T_eff             0.91997
                                 mass_smaller_14 T_eff             0.97752
                                 mass_smaller_30 T_eff             0.98461
xgboost           MIST           Base            T_eff             0.93580
                                 mass_smaller_3  T_eff             0.87167
                                 mass_smaller_14 T_eff             0.88254
                                 mass_smaller_30 T_eff             0.91943

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.84709
                                 mass_smaller_3  T_eff             0.40629
                                 mass_smaller_14 T_eff             0.82977
                                 mass_smaller_30 T_eff             0.86487
KNN               MIST           Base            T_eff             0.71255
                                 mass_smaller_3  T_eff             0.33967
                                 mass_smaller_14 T_eff             0.62606
                                 mass_smaller_30 T_eff             0.69827
linear_regression MIST           Base            T_eff             0.63134
                                 mass_smaller_3  T_eff             0.35365
                                 mass_smaller_14 T_eff             0.72518
                                 mass_smaller_30 T_eff             0.68560
mlp               MIST           Base            T_eff             0.65349
                                 mass_smaller_3  T_eff             0.34468
                                 mass_smaller_14 T_eff             0.54802
                                 mass_smaller_30 T_eff             0.90711
random_forest     MIST           Base            T_eff             0.71261
                                 mass_smaller_3  T_eff             0.30798
                                 mass_smaller_14 T_eff             0.72317
                                 mass_smaller_30 T_eff             0.69815
xgboost           MIST           Base            T_eff             0.50986
                                 mass_smaller_3  T_eff             0.26120
                                 mass_smaller_14 T_eff             0.52165
                                 mass_smaller_30 T_eff             0.48684

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00789 / 90 : 0.08242 / 95 : 0.13794 / 99 : 0.23584
                                 mass_smaller_3  T_eff               75 : 0.05913 / 90 : 0.12783 / 95 : 0.16949 / 99 : 0.2268
                                 mass_smaller_14 T_eff               75 : 0.0145 / 90 : 0.09382 / 95 : 0.14629 / 99 : 0.23065
                                 mass_smaller_30 T_eff              75 : 0.01001 / 90 : 0.08773 / 95 : 0.14107 / 99 : 0.23055
KNN               MIST           Base            T_eff               75 : 0.01087 / 90 : 0.05726 / 95 : 0.0917 / 99 : 0.16337
                                 mass_smaller_3  T_eff              75 : 0.04026 / 90 : 0.08182 / 95 : 0.11058 / 99 : 0.16643
                                 mass_smaller_14 T_eff               75 : 0.0155 / 90 : 0.06208 / 95 : 0.09523 / 99 : 0.16225
                                 mass_smaller_30 T_eff              75 : 0.01193 / 90 : 0.05915 / 95 : 0.09295 / 99 : 0.15869
linear_regression MIST           Base            T_eff              75 : 0.16587 / 90 : 0.22216 / 95 : 0.28347 / 99 : 0.42765
                                 mass_smaller_3  T_eff              75 : 0.13149 / 90 : 0.18251 / 95 : 0.21442 / 99 : 0.28156
                                 mass_smaller_14 T_eff              75 : 0.14466 / 90 : 0.20896 / 95 : 0.28902 / 99 : 0.46973
                                 mass_smaller_30 T_eff              75 : 0.14427 / 90 : 0.20588 / 95 : 0.26343 / 99 : 0.43116
mlp               MIST           Base            T_eff               75 : 0.1347 / 90 : 0.20956 / 95 : 0.26236 / 99 : 0.35663
                                 mass_smaller_3  T_eff               75 : 0.1156 / 90 : 0.16717 / 95 : 0.19789 / 99 : 0.25215
                                 mass_smaller_14 T_eff              75 : 0.13623 / 90 : 0.21043 / 95 : 0.26145 / 99 : 0.35802
                                 mass_smaller_30 T_eff              75 : 0.19898 / 90 : 0.29875 / 95 : 0.35921 / 99 : 0.48333
random_forest     MIST           Base            T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                 mass_smaller_3  T_eff              75 : 0.04972 / 90 : 0.10192 / 95 : 0.13515 / 99 : 0.19473
                                 mass_smaller_14 T_eff              75 : 0.01781 / 90 : 0.07692 / 95 : 0.11807 / 99 : 0.19909
                                 mass_smaller_30 T_eff              75 : 0.01371 / 90 : 0.07218 / 95 : 0.11434 / 99 : 0.19716
xgboost           MIST           Base            T_eff              75 : 0.11863 / 90 : 0.18832 / 95 : 0.24477 / 99 : 0.34599
                                 mass_smaller_3  T_eff               75 : 0.0853 / 90 : 0.12113 / 95 : 0.14299 / 99 : 0.18504
                                 mass_smaller_14 T_eff               75 : 0.12351 / 90 : 0.19578 / 95 : 0.25317 / 99 : 0.3482
                                 mass_smaller_30 T_eff               75 : 0.12091 / 90 : 0.1925 / 95 : 0.24987 / 99 : 0.34624

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 3.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
KNN               MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
linear_regression MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
mlp               MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
random_forest     MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
xgboost           MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.88142
                                 mass_smaller_3  T_eff             0.87065
                                 mass_smaller_14 T_eff             0.84508
                                 mass_smaller_30 T_eff             0.86278
KNN               MIST           Base            T_eff             0.92720
                                 mass_smaller_3  T_eff             0.94238
                                 mass_smaller_14 T_eff             0.92125
                                 mass_smaller_30 T_eff             0.92511
linear_regression MIST           Base            T_eff             0.60534
                                 mass_smaller_3  T_eff             0.38535
                                 mass_smaller_14 T_eff             0.42918
                                 mass_smaller_30 T_eff             0.57042
mlp               MIST           Base            T_eff             0.76217
                                 mass_smaller_3  T_eff             0.56861
                                 mass_smaller_14 T_eff             0.71984
                                 mass_smaller_30 T_eff             0.53400
random_forest     MIST           Base            T_eff             0.91798
                                 mass_smaller_3  T_eff             0.91785
                                 mass_smaller_14 T_eff             0.89558
                                 mass_smaller_30 T_eff             0.90440
xgboost           MIST           Base            T_eff             0.83805
                                 mass_smaller_3  T_eff             0.81282
                                 mass_smaller_14 T_eff             0.75437
                                 mass_smaller_30 T_eff             0.80911

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.10650
                                 mass_smaller_3  T_eff             0.05348
                                 mass_smaller_14 T_eff             0.08919
                                 mass_smaller_30 T_eff             0.10195
KNN               MIST           Base            T_eff             0.08394
                                 mass_smaller_3  T_eff             0.03568
                                 mass_smaller_14 T_eff             0.06361
                                 mass_smaller_30 T_eff             0.07546
linear_regression MIST           Base            T_eff             0.21019
                                 mass_smaller_3  T_eff             0.13340
                                 mass_smaller_14 T_eff             0.19536
                                 mass_smaller_30 T_eff             0.20129
mlp               MIST           Base            T_eff             0.16539
                                 mass_smaller_3  T_eff             0.10045
                                 mass_smaller_14 T_eff             0.13173
                                 mass_smaller_30 T_eff             0.20143
random_forest     MIST           Base            T_eff             0.08865
                                 mass_smaller_3  T_eff             0.04262
                                 mass_smaller_14 T_eff             0.07328
                                 mass_smaller_30 T_eff             0.08516
xgboost           MIST           Base            T_eff             0.14039
                                 mass_smaller_3  T_eff             0.06715
                                 mass_smaller_14 T_eff             0.12652
                                 mass_smaller_30 T_eff             0.13559

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.03049
                                 mass_smaller_3  T_eff             0.01971
                                 mass_smaller_14 T_eff             0.02352
                                 mass_smaller_30 T_eff             0.02718
KNN               MIST           Base            T_eff             0.02906
                                 mass_smaller_3  T_eff             0.01590
                                 mass_smaller_14 T_eff             0.02006
                                 mass_smaller_30 T_eff             0.02378
linear_regression MIST           Base            T_eff             0.15327
                                 mass_smaller_3  T_eff             0.10536
                                 mass_smaller_14 T_eff             0.13812
                                 mass_smaller_30 T_eff             0.14212
mlp               MIST           Base            T_eff             0.11481
                                 mass_smaller_3  T_eff             0.07691
                                 mass_smaller_14 T_eff             0.09337
                                 mass_smaller_30 T_eff             0.14771
random_forest     MIST           Base            T_eff             0.02720
                                 mass_smaller_3  T_eff             0.01738
                                 mass_smaller_14 T_eff             0.02113
                                 mass_smaller_30 T_eff             0.02427
xgboost           MIST           Base            T_eff             0.09651
                                 mass_smaller_3  T_eff             0.04837
                                 mass_smaller_14 T_eff             0.08613
                                 mass_smaller_30 T_eff             0.09117

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00343
                                 mass_smaller_3  T_eff             0.00272
                                 mass_smaller_14 T_eff             0.00328
                                 mass_smaller_30 T_eff             0.00322
KNN               MIST           Base            T_eff             0.00421
                                 mass_smaller_3  T_eff             0.00378
                                 mass_smaller_14 T_eff             0.00368
                                 mass_smaller_30 T_eff             0.00377
linear_regression MIST           Base            T_eff             0.10620
                                 mass_smaller_3  T_eff             0.08282
                                 mass_smaller_14 T_eff             0.09380
                                 mass_smaller_30 T_eff             0.09629
mlp               MIST           Base            T_eff             0.07511
                                 mass_smaller_3  T_eff             0.06081
                                 mass_smaller_14 T_eff             0.06400
                                 mass_smaller_30 T_eff             0.10873
random_forest     MIST           Base            T_eff             0.00314
                                 mass_smaller_3  T_eff             0.00316
                                 mass_smaller_14 T_eff             0.00311
                                 mass_smaller_30 T_eff             0.00298
xgboost           MIST           Base            T_eff             0.06314
                                 mass_smaller_3  T_eff             0.03287
                                 mass_smaller_14 T_eff             0.05556
                                 mass_smaller_30 T_eff             0.05795

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.94126
                                 mass_smaller_3  T_eff             0.93361
                                 mass_smaller_14 T_eff             0.92359
                                 mass_smaller_30 T_eff             0.93213
KNN               MIST           Base            T_eff             0.96403
                                 mass_smaller_3  T_eff             0.97099
                                 mass_smaller_14 T_eff             0.96028
                                 mass_smaller_30 T_eff             0.96248
linear_regression MIST           Base            T_eff             0.78745
                                 mass_smaller_3  T_eff             0.67438
                                 mass_smaller_14 T_eff             0.71182
                                 mass_smaller_30 T_eff             0.77357
mlp               MIST           Base            T_eff             0.87806
                                 mass_smaller_3  T_eff             0.77571
                                 mass_smaller_14 T_eff             0.85260
                                 mass_smaller_30 T_eff             0.77117
random_forest     MIST           Base            T_eff             0.95873
                                 mass_smaller_3  T_eff             0.95810
                                 mass_smaller_14 T_eff             0.94734
                                 mass_smaller_30 T_eff             0.95186
xgboost           MIST           Base            T_eff             0.91556
                                 mass_smaller_3  T_eff             0.90198
                                 mass_smaller_14 T_eff             0.87143
                                 mass_smaller_30 T_eff             0.90015

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.93139
                                 mass_smaller_3  T_eff             0.44718
                                 mass_smaller_14 T_eff             0.91146
                                 mass_smaller_30 T_eff             0.93366
KNN               MIST           Base            T_eff             0.91675
                                 mass_smaller_3  T_eff             0.41430
                                 mass_smaller_14 T_eff             0.88595
                                 mass_smaller_30 T_eff             0.91158
linear_regression MIST           Base            T_eff             0.98202
                                 mass_smaller_3  T_eff             0.39655
                                 mass_smaller_14 T_eff             0.75693
                                 mass_smaller_30 T_eff             0.95037
mlp               MIST           Base            T_eff             0.97704
                                 mass_smaller_3  T_eff             0.52459
                                 mass_smaller_14 T_eff             0.64463
                                 mass_smaller_30 T_eff             1.04212
random_forest     MIST           Base            T_eff             0.93308
                                 mass_smaller_3  T_eff             0.41916
                                 mass_smaller_14 T_eff             0.87264
                                 mass_smaller_30 T_eff             0.91376
xgboost           MIST           Base            T_eff             0.87367
                                 mass_smaller_3  T_eff             0.38800
                                 mass_smaller_14 T_eff             0.82046
                                 mass_smaller_30 T_eff             0.85115

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff               75 : 0.00987 / 90 : 0.05367 / 95 : 0.15861 / 99 : 0.6234
                                 mass_smaller_3  T_eff               75 : 0.01078 / 90 : 0.0549 / 95 : 0.11789 / 99 : 0.28011
                                 mass_smaller_14 T_eff              75 : 0.00931 / 90 : 0.03439 / 95 : 0.11243 / 99 : 0.49627
                                 mass_smaller_30 T_eff               75 : 0.0092 / 90 : 0.03894 / 95 : 0.13073 / 99 : 0.66352
KNN               MIST           Base            T_eff              75 : 0.01918 / 90 : 0.06825 / 95 : 0.14393 / 99 : 0.43934
                                 mass_smaller_3  T_eff              75 : 0.01594 / 90 : 0.04753 / 95 : 0.07039 / 99 : 0.15954
                                 mass_smaller_14 T_eff              75 : 0.01433 / 90 : 0.04415 / 95 : 0.07949 / 99 : 0.31662
                                 mass_smaller_30 T_eff              75 : 0.01578 / 90 : 0.05188 / 95 : 0.10037 / 99 : 0.39911
linear_regression MIST           Base            T_eff              75 : 0.21166 / 90 : 0.36121 / 95 : 0.45759 / 99 : 0.60611
                                 mass_smaller_3  T_eff               75 : 0.1652 / 90 : 0.22101 / 95 : 0.25872 / 99 : 0.32763
                                 mass_smaller_14 T_eff              75 : 0.18089 / 90 : 0.32896 / 95 : 0.45534 / 99 : 0.61901
                                 mass_smaller_30 T_eff               75 : 0.18784 / 90 : 0.3445 / 95 : 0.46674 / 99 : 0.62964
mlp               MIST           Base            T_eff               75 : 0.15645 / 90 : 0.2835 / 95 : 0.35727 / 99 : 0.54147
                                 mass_smaller_3  T_eff               75 : 0.11032 / 90 : 0.1637 / 95 : 0.20588 / 99 : 0.28983
                                 mass_smaller_14 T_eff              75 : 0.13038 / 90 : 0.22651 / 95 : 0.29624 / 99 : 0.40679
                                 mass_smaller_30 T_eff              75 : 0.19535 / 90 : 0.32514 / 95 : 0.42013 / 99 : 0.67228
random_forest     MIST           Base            T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                 mass_smaller_3  T_eff              75 : 0.01337 / 90 : 0.05079 / 95 : 0.08983 / 99 : 0.20541
                                 mass_smaller_14 T_eff              75 : 0.01102 / 90 : 0.04317 / 95 : 0.09179 / 99 : 0.40046
                                 mass_smaller_30 T_eff              75 : 0.01092 / 90 : 0.04684 / 95 : 0.10789 / 99 : 0.49952
xgboost           MIST           Base            T_eff               75 : 0.13011 / 90 : 0.24272 / 95 : 0.3206 / 99 : 0.43713
                                 mass_smaller_3  T_eff              75 : 0.07337 / 90 : 0.11548 / 95 : 0.14339 / 99 : 0.19664
                                 mass_smaller_14 T_eff               75 : 0.11553 / 90 : 0.21641 / 95 : 0.3024 / 99 : 0.39371
                                 mass_smaller_30 T_eff              75 : 0.11964 / 90 : 0.23036 / 95 : 0.31839 / 99 : 0.43258

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better results than Base on every metric except P99

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER and P99
- mass_smaller_14 : worse results than Base on every metric except MAX_ER, P90 and P99
- mass_smaller_30 : better/similar results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric except P99
- mass_smaller_30 : better/similar results than Base on every metric

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and MAX_ER
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : worse results than Base on every metric

#### Conclusions on T_eff

mass_smaller_3 is always worse than Base.

mass_smaller_14 is always worse than Base.

mass_smaller_30 is always better or similar to Base.

But it is important to note that the range does not change a lot and the errors without relativity to the range do not have that much of a difference.

#### Best models for the T_eff parameter

The three best performing models in order for the mass parameter are Random forest, KNN and decision tree.

### Radius parameter

In [22]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
KNN               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
mlp               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.8155741609143345
                                 mass_smaller_3  radius             0.6813803019471154
                                 mass_smaller_14 radius             0.7834989803759971
                                 mass_smaller_30 radius             0.7901160695649663
KNN               MIST           Base            radius             0.9043914862732579
                                 mass_smaller_3  radius             0.8544471075170126
                                 mass_smaller_14 radius              0.897478837024348
                                 mass_smaller_30 radius             0.8975823132234476
linear_regression MIST           Base            radius            0.19856216776938762
                                 mass_smaller_3  radius            0.41944480979620613
                                 mass_smaller_14 radius              0.314088761140893
                                 mass_smaller_30 radius             0.2456438925301918
mlp               MIST           Base            radius             0.7570156135268156
                                 mass_smaller_3  radius             0.6444511414397914
                                 mass_smaller_14 radius             0.7019859105066648
                                 mass_smaller_30 radius             0.5008492082149913
random_forest     MIST           Base            radius             0.8776105127019214
                                 mass_smaller_3  radius             0.7909281628598143
                                 mass_smaller_14 radius             0.8562731444960898
                                 mass_smaller_30 radius             0.8612812279603893
xgboost           MIST           Base            radius             0.8250961607541988
                                 mass_smaller_3  radius             0.8179235085333942
                                 mass_smaller_14 radius              0.805581593834652
                                 mass_smaller_30 radius             0.8085546865245665

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             7.68088%
                                 mass_smaller_3  radius            10.43277%
                                 mass_smaller_14 radius             8.03792%
                                 mass_smaller_30 radius             7.89114%
KNN               MIST           Base            radius              5.5336%
                                 mass_smaller_3  radius             7.05194%
                                 mass_smaller_14 radius              5.5326%
                                 mass_smaller_30 radius              5.5146%
linear_regression MIST           Base            radius            16.01055%
                                 mass_smaller_3  radius            14.08097%
                                 mass_smaller_14 radius            14.30581%
                                 mass_smaller_30 radius            14.95897%
mlp               MIST           Base            radius             8.87463%
                                 mass_smaller_3  radius            11.02065%
                                 mass_smaller_14 radius             9.57033%
                                 mass_smaller_30 radius            12.16998%
random_forest     MIST           Base            radius             6.25728%
                                 mass_smaller_3  radius             8.45121%
                                 mass_smaller_14 radius             6.54927%
                                 mass_smaller_30 radius              6.4155%
xgboost           MIST           Base            radius             7.47947%
                                 mass_smaller_3  radius             7.88566%
                                 mass_smaller_14 radius             7.61635%
                                 mass_smaller_30 radius             7.53591%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             2.12385%
                                 mass_smaller_3  radius             3.44458%
                                 mass_smaller_14 radius             2.23847%
                                 mass_smaller_30 radius             2.18437%
KNN               MIST           Base            radius             1.83831%
                                 mass_smaller_3  radius              2.5208%
                                 mass_smaller_14 radius             1.71757%
                                 mass_smaller_30 radius             1.74531%
linear_regression MIST           Base            radius            13.23913%
                                 mass_smaller_3  radius             11.3089%
                                 mass_smaller_14 radius            11.41533%
                                 mass_smaller_30 radius            11.94486%
mlp               MIST           Base            radius             5.85675%
                                 mass_smaller_3  radius             7.13177%
                                 mass_smaller_14 radius             6.42474%
                                 mass_smaller_30 radius             8.23567%
random_forest     MIST           Base            radius             1.85127%
                                 mass_smaller_3  radius             2.98463%
                                 mass_smaller_14 radius             1.94743%
                                 mass_smaller_30 radius             1.89755%
xgboost           MIST           Base            radius             4.81548%
                                 mass_smaller_3  radius             4.64369%
                                 mass_smaller_14 radius             4.88373%
                                 mass_smaller_30 radius             4.83095%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.11272%
                                 mass_smaller_3  radius             0.11211%
                                 mass_smaller_14 radius             0.11222%
                                 mass_smaller_30 radius             0.11001%
KNN               MIST           Base            radius             0.09215%
                                 mass_smaller_3  radius             0.10623%
                                 mass_smaller_14 radius             0.08603%
                                 mass_smaller_30 radius             0.08522%
linear_regression MIST           Base            radius            11.47659%
                                 mass_smaller_3  radius             9.90535%
                                 mass_smaller_14 radius             9.41273%
                                 mass_smaller_30 radius             9.72037%
mlp               MIST           Base            radius             3.04591%
                                 mass_smaller_3  radius             3.28518%
                                 mass_smaller_14 radius             3.28777%
                                 mass_smaller_30 radius             4.35791%
random_forest     MIST           Base            radius             0.05635%
                                 mass_smaller_3  radius             0.05843%
                                 mass_smaller_14 radius             0.05543%
                                 mass_smaller_30 radius             0.05342%
xgboost           MIST           Base            radius             2.42428%
                                 mass_smaller_3  radius             1.85755%
                                 mass_smaller_14 radius             2.42202%
                                 mass_smaller_30 radius             2.38222%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.908046242988254
                                 mass_smaller_3  radius            0.8419035771879697
                                 mass_smaller_14 radius            0.8922261811712158
                                 mass_smaller_30 radius            0.8955234190221543
KNN               MIST           Base            radius            0.9513432795547301
                                 mass_smaller_3  radius            0.9249854638398343
                                 mass_smaller_14 radius            0.9476753422536481
                                 mass_smaller_30 radius            0.9477664655557928
linear_regression MIST           Base            radius            0.4456031520460739
                                 mass_smaller_3  radius            0.6476455899305139
                                 mass_smaller_14 radius            0.5604362239996286
                                 mass_smaller_30 radius            0.4956247505107052
mlp               MIST           Base            radius             0.870162623980867
                                 mass_smaller_3  radius            0.8037429900849645
                                 mass_smaller_14 radius            0.8380678806130963
                                 mass_smaller_30 radius            0.7344859272641178
random_forest     MIST           Base            radius            0.9377254771026249
                                 mass_smaller_3  radius            0.8923834308438076
                                 mass_smaller_14 radius            0.9266852908075508
                                 mass_smaller_30 radius               0.9292823709225
xgboost           MIST           Base            radius            0.9085430473618937
                                 mass_smaller_3  radius            0.9046341479324373
                                 mass_smaller_14 radius            0.8977703702232838
                                 mass_smaller_30 radius            0.8994303143903841

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            68.70409%
                                 mass_smaller_3  radius             75.0767%
                                 mass_smaller_14 radius            69.78073%
                                 mass_smaller_30 radius            68.61564%
KNN               MIST           Base            radius            68.74998%
                                 mass_smaller_3  radius             75.0386%
                                 mass_smaller_14 radius            69.28761%
                                 mass_smaller_30 radius            68.41746%
linear_regression MIST           Base            radius            49.52014%
                                 mass_smaller_3  radius             67.6647%
                                 mass_smaller_14 radius            52.65001%
                                 mass_smaller_30 radius            48.28021%
mlp               MIST           Base            radius            68.62412%
                                 mass_smaller_3  radius            72.22869%
                                 mass_smaller_14 radius             68.4321%
                                 mass_smaller_30 radius            66.54739%
random_forest     MIST           Base            radius             68.7036%
                                 mass_smaller_3  radius            75.04157%
                                 mass_smaller_14 radius            69.29905%
                                 mass_smaller_30 radius            68.42441%
xgboost           MIST           Base            radius            62.53131%
                                 mass_smaller_3  radius             68.4045%
                                 mass_smaller_14 radius            60.98666%
                                 mass_smaller_30 radius            61.13306%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.24935% / 90 : 2.57177% / 95 : 16.51234% / 99 : 40.59071%
                                 mass_smaller_3  radius             75 : 0.32074% / 90 : 11.84535% / 95 : 26.21321% / 99 : 49.31114%
                                 mass_smaller_14 radius               75 : 0.2466% / 90 : 2.85203% / 95 : 17.62722% / 99 : 41.94464%
                                 mass_smaller_30 radius                75 : 0.24084% / 90 : 2.641% / 95 : 17.27047% / 99 : 41.27769%
KNN               MIST           Base            radius              75 : 0.42794% / 90 : 5.63594% / 95 : 12.38922% / 99 : 26.30919%
                                 mass_smaller_3  radius              75 : 0.49196% / 90 : 9.42129% / 95 : 17.02559% / 99 : 30.58526%
                                 mass_smaller_14 radius              75 : 0.31474% / 90 : 4.73117% / 95 : 12.19597% / 99 : 26.37697%
                                 mass_smaller_30 radius              75 : 0.34139% / 90 : 4.98132% / 95 : 12.12585% / 99 : 26.31216%
linear_regression MIST           Base            radius             75 : 17.83736% / 90 : 26.5503% / 95 : 31.47963% / 99 : 38.85568%
                                 mass_smaller_3  radius            75 : 14.84394% / 90 : 21.04806% / 95 : 27.86639% / 99 : 41.81031%
                                 mass_smaller_14 radius            75 : 16.96562% / 90 : 24.06102% / 95 : 27.97886% / 99 : 35.51353%
                                 mass_smaller_30 radius            75 : 17.33614% / 90 : 25.54166% / 95 : 30.10212% / 99 : 36.98594%
mlp               MIST           Base            radius             75 : 9.35534% / 90 : 15.75532% / 95 : 19.32812% / 99 : 27.34124%
                                 mass_smaller_3  radius            75 : 10.96518% / 90 : 19.62458% / 95 : 25.19357% / 99 : 34.50425%
                                 mass_smaller_14 radius             75 : 10.7713% / 90 : 17.21467% / 95 : 20.23413% / 99 : 27.75139%
                                 mass_smaller_30 radius             75 : 13.1522% / 90 : 22.05651% / 95 : 26.17526% / 99 : 36.22392%
random_forest     MIST           Base            radius              75 : 0.23142% / 90 : 4.06157% / 95 : 13.91319% / 99 : 31.46581%
                                 mass_smaller_3  radius              75 : 0.50307% / 90 : 11.1221% / 95 : 21.17773% / 99 : 38.28536%
                                 mass_smaller_14 radius              75 : 0.23042% / 90 : 4.41986% / 95 : 14.79798% / 99 : 32.85367%
                                 mass_smaller_30 radius              75 : 0.22025% / 90 : 4.21228% / 95 : 14.45744% / 99 : 32.24497%
xgboost           MIST           Base            radius             75 : 7.31523% / 90 : 13.04349% / 95 : 16.62889% / 99 : 23.85544%
                                 mass_smaller_3  radius             75 : 6.52327% / 90 : 13.23337% / 95 : 18.32548% / 99 : 28.25117%
                                 mass_smaller_14 radius              75 : 7.51211% / 90 : 13.2532% / 95 : 16.94381% / 99 : 24.10833%
                                 mass_smaller_30 radius              75 : 7.34345% / 90 : 13.12289% / 95 : 16.81666% / 99 : 23.9607%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511
                                 mass_smaller_3  radius             203.75130891799927

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.8362997592078089
                                 mass_smaller_3  radius              0.3860599348423952
                                 mass_smaller_14 radius              0.7239370774639855
                                 mass_smaller_30 radius              0.7889707604937268
KNN               MIST           Base            radius              0.8957368145865507
                                 mass_smaller_3  radius              0.6964623631952935
                                 mass_smaller_14 radius               0.849444000345548
                                 mass_smaller_30 radius               0.878962963156113
linear_regression MIST           Base            radius              0.4447713018606766
                                 mass_smaller_3  radius            -0.20822089580122594
                                 mass_smaller_14 radius             0.22469211359168928
                                 mass_smaller_30 radius             0.43522613091488316
mlp               MIST           Base            radius              0.7459947947493104
                                 mass_smaller_3  radius             0.19097817221195146
                                 mass_smaller_14 radius             0.48473145728270606
                                 mass_smaller_30 radius             0.44506374825504247
random_forest     MIST           Base            radius               0.895944647709672
                                 mass_smaller_3  radius              0.6267123490082731
                                 mass_smaller_14 radius              0.8274921577145724
                                 mass_smaller_30 radius               0.867058646092464
xgboost           MIST           Base            radius              0.8325938372230868
                                 mass_smaller_3  radius              0.5720666346088736
                                 mass_smaller_14 radius              0.7102589478863934
                                 mass_smaller_30 radius              0.7873612816207101

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              5.6898%
                                 mass_smaller_3  radius            14.30347%
                                 mass_smaller_14 radius             5.46235%
                                 mass_smaller_30 radius             5.73089%
KNN               MIST           Base            radius             4.58944%
                                 mass_smaller_3  radius            10.07942%
                                 mass_smaller_14 radius             4.05337%
                                 mass_smaller_30 radius              4.3704%
linear_regression MIST           Base            radius            15.33939%
                                 mass_smaller_3  radius            25.54716%
                                 mass_smaller_14 radius             13.0895%
                                 mass_smaller_30 radius            13.79434%
mlp               MIST           Base            radius             8.04191%
                                 mass_smaller_3  radius            18.13249%
                                 mass_smaller_14 radius             8.95429%
                                 mass_smaller_30 radius            10.17176%
random_forest     MIST           Base            radius             4.55042%
                                 mass_smaller_3  radius            11.20315%
                                 mass_smaller_14 radius             4.33274%
                                 mass_smaller_30 radius             4.56248%
xgboost           MIST           Base            radius              6.2399%
                                 mass_smaller_3  radius            12.55431%
                                 mass_smaller_14 radius             6.10784%
                                 mass_smaller_30 radius             6.23992%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.93531%
                                 mass_smaller_3  radius             2.06635%
                                 mass_smaller_14 radius             0.74986%
                                 mass_smaller_30 radius             0.88418%
KNN               MIST           Base            radius             1.13459%
                                 mass_smaller_3  radius             1.69932%
                                 mass_smaller_14 radius             0.71117%
                                 mass_smaller_30 radius             0.91376%
linear_regression MIST           Base            radius            12.83078%
                                 mass_smaller_3  radius            22.27107%
                                 mass_smaller_14 radius            10.16758%
                                 mass_smaller_30 radius            10.81206%
mlp               MIST           Base            radius             4.63773%
                                 mass_smaller_3  radius             9.70704%
                                 mass_smaller_14 radius             5.39856%
                                 mass_smaller_30 radius             5.97698%
random_forest     MIST           Base            radius             0.84445%
                                 mass_smaller_3  radius             1.89569%
                                 mass_smaller_14 radius             0.67968%
                                 mass_smaller_30 radius              0.7976%
xgboost           MIST           Base            radius             3.46212%
                                 mass_smaller_3  radius             5.72068%
                                 mass_smaller_14 radius             3.25528%
                                 mass_smaller_30 radius             3.41942%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.07006%
                                 mass_smaller_3  radius             0.11843%
                                 mass_smaller_14 radius             0.06094%
                                 mass_smaller_30 radius             0.06496%
KNN               MIST           Base            radius             0.05836%
                                 mass_smaller_3  radius             0.12615%
                                 mass_smaller_14 radius             0.04726%
                                 mass_smaller_30 radius             0.05102%
linear_regression MIST           Base            radius            11.66998%
                                 mass_smaller_3  radius            21.68166%
                                 mass_smaller_14 radius             7.58202%
                                 mass_smaller_30 radius             8.26743%
mlp               MIST           Base            radius             1.04095%
                                 mass_smaller_3  radius              2.9089%
                                 mass_smaller_14 radius             1.21098%
                                 mass_smaller_30 radius             1.82764%
random_forest     MIST           Base            radius             0.02822%
                                 mass_smaller_3  radius             0.04841%
                                 mass_smaller_14 radius             0.02382%
                                 mass_smaller_30 radius             0.02536%
xgboost           MIST           Base            radius             0.96479%
                                 mass_smaller_3  radius             1.25839%
                                 mass_smaller_14 radius             0.83797%
                                 mass_smaller_30 radius             0.93601%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9266704914779671
                                 mass_smaller_3  radius             0.803251675998881
                                 mass_smaller_14 radius             0.887290831162512
                                 mass_smaller_30 radius             0.908472573531127
KNN               MIST           Base            radius            0.9538577488062183
                                 mass_smaller_3  radius            0.8839207964856702
                                 mass_smaller_14 radius            0.9351653848778183
                                 mass_smaller_30 radius            0.9461368898191871
linear_regression MIST           Base            radius            0.6719624779362757
                                 mass_smaller_3  radius            0.6426645360484811
                                 mass_smaller_14 radius            0.5947013137402104
                                 mass_smaller_30 radius            0.6630070969610159
mlp               MIST           Base            radius            0.9040382509041051
                                 mass_smaller_3  radius            0.8366833440684885
                                 mass_smaller_14 radius            0.8677287985184537
                                 mass_smaller_30 radius            0.8128531007437122
random_forest     MIST           Base            radius            0.9515577145193358
                                 mass_smaller_3  radius            0.8656451900394606
                                 mass_smaller_14 radius            0.9250715450137749
                                 mass_smaller_30 radius            0.9393845002936859
xgboost           MIST           Base            radius            0.9316960163015878
                                 mass_smaller_3  radius             0.887840588032607
                                 mass_smaller_14 radius            0.9153577170512818
                                 mass_smaller_30 radius            0.9205772750607841

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              69.4522%
                                 mass_smaller_3  radius            160.55903%
                                 mass_smaller_14 radius             69.78073%
                                 mass_smaller_30 radius              69.3233%
KNN               MIST           Base            radius             68.33134%
                                 mass_smaller_3  radius            158.22055%
                                 mass_smaller_14 radius             68.00774%
                                 mass_smaller_30 radius             68.21537%
linear_regression MIST           Base            radius             50.08468%
                                 mass_smaller_3  radius             66.47507%
                                 mass_smaller_14 radius             41.14256%
                                 mass_smaller_30 radius             46.67504%
mlp               MIST           Base            radius             48.93262%
                                 mass_smaller_3  radius             92.30827%
                                 mass_smaller_14 radius             42.80368%
                                 mass_smaller_30 radius             55.79403%
random_forest     MIST           Base            radius             68.43104%
                                 mass_smaller_3  radius            157.59275%
                                 mass_smaller_14 radius             68.37084%
                                 mass_smaller_30 radius             67.45209%
xgboost           MIST           Base            radius             63.24418%
                                 mass_smaller_3  radius            146.83423%
                                 mass_smaller_14 radius             60.98666%
                                 mass_smaller_30 radius             61.83726%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius               75 : 0.13259% / 90 : 0.26935% / 95 : 0.52032% / 99 : 37.99136%
                                 mass_smaller_3  radius                75 : 0.22495% / 90 : 0.3823% / 95 : 0.59759% / 99 : 98.44802%
                                 mass_smaller_14 radius                75 : 0.11423% / 90 : 0.1961% / 95 : 0.30101% / 99 : 38.96612%
                                 mass_smaller_30 radius               75 : 0.12156% / 90 : 0.22376% / 95 : 0.38699% / 99 : 39.35477%
KNN               MIST           Base            radius                 75 : 0.17989% / 90 : 1.197% / 95 : 6.69205% / 99 : 24.24062%
                                 mass_smaller_3  radius               75 : 0.27778% / 90 : 0.59021% / 95 : 1.13668% / 99 : 53.59719%
                                 mass_smaller_14 radius               75 : 0.11791% / 90 : 0.33239% / 95 : 0.86113% / 99 : 21.81715%
                                 mass_smaller_30 radius               75 : 0.13749% / 90 : 0.56615% / 95 : 3.20939% / 99 : 23.51591%
linear_regression MIST           Base            radius             75 : 17.26648% / 90 : 24.7553% / 95 : 29.65308% / 99 : 36.47355%
                                 mass_smaller_3  radius             75 : 30.97437% / 90 : 39.4526% / 95 : 43.72551% / 99 : 51.51697%
                                 mass_smaller_14 radius               75 : 15.413% / 90 : 22.7148% / 95 : 26.57332% / 99 : 32.95736%
                                 mass_smaller_30 radius            75 : 16.06385% / 90 : 23.78305% / 95 : 28.30144% / 99 : 34.85207%
mlp               MIST           Base            radius              75 : 7.50671% / 90 : 15.27811% / 95 : 18.66543% / 99 : 25.6555%
                                 mass_smaller_3  radius             75 : 8.67989% / 90 : 32.29226% / 95 : 47.10715% / 99 : 67.37254%
                                 mass_smaller_14 radius             75 : 10.25139% / 90 : 17.37474% / 95 : 19.94145% / 99 : 24.5628%
                                 mass_smaller_30 radius             75 : 7.52068% / 90 : 20.72757% / 95 : 25.23444% / 99 : 29.81067%
random_forest     MIST           Base            radius                75 : 0.07769% / 90 : 0.26298% / 95 : 1.7352% / 99 : 27.00224%
                                 mass_smaller_3  radius                 75 : 0.121% / 90 : 0.33686% / 95 : 2.11828% / 99 : 65.83878%
                                 mass_smaller_14 radius               75 : 0.06104% / 90 : 0.16472% / 95 : 0.56918% / 99 : 26.48164%
                                 mass_smaller_30 radius                75 : 0.06715% / 90 : 0.2022% / 95 : 1.18008% / 99 : 27.51006%
xgboost           MIST           Base            radius              75 : 4.5674% / 90 : 10.91805% / 95 : 14.65167% / 99 : 21.08613%
                                 mass_smaller_3  radius             75 : 4.97674% / 90 : 17.26719% / 95 : 28.54934% / 99 : 48.67385%
                                 mass_smaller_14 radius             75 : 3.92152% / 90 : 10.46416% / 95 : 14.34744% / 99 : 21.12491%
                                 mass_smaller_30 radius              75 : 4.3733% / 90 : 10.81977% / 95 : 14.63452% / 99 : 21.24397%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
KNN               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
linear_regression MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
mlp               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
random_forest     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
xgboost           MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969

                                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.23288301898402786
                                 mass_smaller_3  radius              -0.7458496586144128
                                 mass_smaller_14 radius            -0.028543113399956743
                                 mass_smaller_30 radius             0.008940780881484534
KNN               MIST           Base            radius               0.6509309889395495
                                 mass_smaller_3  radius              0.19179709327537986
                                 mass_smaller_14 radius               0.5333019304174877
                                 mass_smaller_30 radius               0.5517339169333411
linear_regression MIST           Base            radius                0.304632547786987
                                 mass_smaller_3  radius              -0.1896931695325681
                                 mass_smaller_14 radius             0.059961009862141035
                                 mass_smaller_30 radius              0.03933893202957717
mlp               MIST           Base            radius               0.4212087734607134
                                 mass_smaller_3  radius             -0.14009440119764327
                                 mass_smaller_14 radius                0.275176267606035
                                 mass_smaller_30 radius              -0.4927047177897663
random_forest     MIST           Base            radius              0.47265136875136293
                                 mass_smaller_3  radius             -0.19734173176697278
                                 mass_smaller_14 radius              0.29061011162827377
                                 mass_smaller_30 radius               0.3209279815569862
xgboost           MIST           Base            radius               0.4964972804842628
                                 mass_smaller_3  radius              0.23581421719283302
                                 mass_smaller_14 radius              0.36641121794787357
                                 mass_smaller_30 radius               0.3732885641726318

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            15.35342%
                                 mass_smaller_3  radius            27.13726%
                                 mass_smaller_14 radius            16.97989%
                                 mass_smaller_30 radius            16.10045%
KNN               MIST           Base            radius            10.36147%
                                 mass_smaller_3  radius            18.48443%
                                 mass_smaller_14 radius            11.44341%
                                 mass_smaller_30 radius            10.83249%
linear_regression MIST           Base            radius            20.82202%
                                 mass_smaller_3  radius            25.56294%
                                 mass_smaller_14 radius            20.31584%
                                 mass_smaller_30 radius            20.71392%
mlp               MIST           Base            radius            13.33981%
                                 mass_smaller_3  radius            22.63872%
                                 mass_smaller_14 radius            14.25356%
                                 mass_smaller_30 radius            19.96091%
random_forest     MIST           Base            radius            12.73409%
                                 mass_smaller_3  radius            22.49475%
                                 mass_smaller_14 radius            14.10684%
                                 mass_smaller_30 radius            13.33166%
xgboost           MIST           Base            radius            12.55677%
                                 mass_smaller_3  radius            18.14648%
                                 mass_smaller_14 radius            13.49019%
                                 mass_smaller_30 radius            12.93804%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             6.28038%
                                 mass_smaller_3  radius            15.35917%
                                 mass_smaller_14 radius             7.54179%
                                 mass_smaller_30 radius             6.86536%
KNN               MIST           Base            radius             4.43989%
                                 mass_smaller_3  radius            10.82666%
                                 mass_smaller_14 radius             5.28703%
                                 mass_smaller_30 radius             4.80323%
linear_regression MIST           Base            radius            16.55147%
                                 mass_smaller_3  radius            19.86068%
                                 mass_smaller_14 radius            16.39261%
                                 mass_smaller_30 radius            16.61523%
mlp               MIST           Base            radius            10.41918%
                                 mass_smaller_3  radius            17.91902%
                                 mass_smaller_14 radius            11.41301%
                                 mass_smaller_30 radius            15.80096%
random_forest     MIST           Base            radius              5.3849%
                                 mass_smaller_3  radius            13.17627%
                                 mass_smaller_14 radius             6.46988%
                                 mass_smaller_30 radius              5.8732%
xgboost           MIST           Base            radius             9.43325%
                                 mass_smaller_3  radius            13.94354%
                                 mass_smaller_14 radius            10.48008%
                                 mass_smaller_30 radius             9.83277%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.2846%
                                 mass_smaller_3  radius             0.70253%
                                 mass_smaller_14 radius             0.32927%
                                 mass_smaller_30 radius             0.29982%
KNN               MIST           Base            radius             0.18513%
                                 mass_smaller_3  radius             2.05289%
                                 mass_smaller_14 radius             0.23592%
                                 mass_smaller_30 radius             0.20007%
linear_regression MIST           Base            radius            13.03607%
                                 mass_smaller_3  radius            15.08111%
                                 mass_smaller_14 radius            14.07152%
                                 mass_smaller_30 radius            14.03054%
mlp               MIST           Base            radius             8.42984%
                                 mass_smaller_3  radius             14.8346%
                                 mass_smaller_14 radius             9.66816%
                                 mass_smaller_30 radius            13.17423%
random_forest     MIST           Base            radius             0.18312%
                                 mass_smaller_3  radius             2.32554%
                                 mass_smaller_14 radius             0.24346%
                                 mass_smaller_30 radius             0.20321%
xgboost           MIST           Base            radius             7.06592%
                                 mass_smaller_3  radius            10.84642%
                                 mass_smaller_14 radius             8.41358%
                                 mass_smaller_30 radius             7.58819%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.6239292439330856
                                 mass_smaller_3  radius            0.12255294497939681
                                 mass_smaller_14 radius             0.4980870599144762
                                 mass_smaller_30 radius             0.5175122906926821
KNN               MIST           Base            radius             0.8118473473513885
                                 mass_smaller_3  radius            0.49107973054923415
                                 mass_smaller_14 radius             0.7405883337799539
                                 mass_smaller_30 radius             0.7521913415214849
linear_regression MIST           Base            radius             0.5669445250663593
                                 mass_smaller_3  radius            0.05327467345197411
                                 mass_smaller_14 radius             0.4195772079058465
                                 mass_smaller_30 radius             0.3884618763855989
mlp               MIST           Base            radius             0.6527394139165096
                                 mass_smaller_3  radius            0.21330361433506007
                                 mass_smaller_14 radius              0.529277646993492
                                 mass_smaller_30 radius            0.32496572505198623
random_forest     MIST           Base            radius             0.7209068216276289
                                 mass_smaller_3  radius            0.27291659304747523
                                 mass_smaller_14 radius             0.6159875321344142
                                 mass_smaller_30 radius             0.6338808982434485
xgboost           MIST           Base            radius             0.7059467903707194
                                 mass_smaller_3  radius            0.48613388033852417
                                 mass_smaller_14 radius             0.6060964235878444
                                 mass_smaller_30 radius             0.6128252627513893

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             81.87871%
                                 mass_smaller_3  radius            101.62586%
                                 mass_smaller_14 radius              83.4224%
                                 mass_smaller_30 radius             82.54584%
KNN               MIST           Base            radius             81.92638%
                                 mass_smaller_3  radius             95.64678%
                                 mass_smaller_14 radius             77.89833%
                                 mass_smaller_30 radius             80.20268%
linear_regression MIST           Base            radius             63.88906%
                                 mass_smaller_3  radius             67.16073%
                                 mass_smaller_14 radius             50.67361%
                                 mass_smaller_30 radius             57.51105%
mlp               MIST           Base            radius             64.98551%
                                 mass_smaller_3  radius             84.63792%
                                 mass_smaller_14 radius              60.0413%
                                 mass_smaller_30 radius             78.52232%
random_forest     MIST           Base            radius              81.1983%
                                 mass_smaller_3  radius             98.72428%
                                 mass_smaller_14 radius             80.27493%
                                 mass_smaller_30 radius             80.29803%
xgboost           MIST           Base            radius             66.72546%
                                 mass_smaller_3  radius             87.07138%
                                 mass_smaller_14 radius             65.42607%
                                 mass_smaller_30 radius             66.21739%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius               75 : 0.80472% / 90 : 26.8709% / 95 : 41.7056% / 99 : 61.87012%
                                 mass_smaller_3  radius            75 : 26.15504% / 90 : 52.06076% / 95 : 65.62239% / 99 : 83.21725%
                                 mass_smaller_14 radius             75 : 4.42935% / 90 : 31.55729% / 95 : 45.42955% / 99 : 63.69878%
                                 mass_smaller_30 radius             75 : 1.82318% / 90 : 29.33276% / 95 : 43.60635% / 99 : 62.21007%
KNN               MIST           Base            radius              75 : 2.73563% / 90 : 17.4646% / 95 : 26.31906% / 99 : 41.46379%
                                 mass_smaller_3  radius            75 : 17.96257% / 90 : 33.36991% / 95 : 42.42112% / 99 : 60.54767%
                                 mass_smaller_14 radius              75 : 5.62617% / 90 : 20.2589% / 95 : 28.70355% / 99 : 43.32225%
                                 mass_smaller_30 radius             75 : 3.97596% / 90 : 18.81693% / 95 : 27.59039% / 99 : 41.88462%
linear_regression MIST           Base            radius            75 : 23.85346% / 90 : 36.15469% / 95 : 42.63391% / 99 : 50.52362%
                                 mass_smaller_3  radius             75 : 29.17941% / 90 : 46.11524% / 95 : 53.41367% / 99 : 61.1915%
                                 mass_smaller_14 radius             75 : 24.65336% / 90 : 34.17073% / 95 : 39.52782% / 99 : 46.4224%
                                 mass_smaller_30 radius             75 : 24.51071% / 90 : 35.52308% / 95 : 41.2763% / 99 : 47.60901%
mlp               MIST           Base            radius            75 : 15.02615% / 90 : 22.24865% / 95 : 26.83233% / 99 : 36.01539%
                                 mass_smaller_3  radius            75 : 25.97811% / 90 : 37.98309% / 95 : 45.24175% / 99 : 57.77083%
                                 mass_smaller_14 radius            75 : 16.67815% / 90 : 23.67201% / 95 : 27.65314% / 99 : 35.34848%
                                 mass_smaller_30 radius            75 : 22.54515% / 90 : 32.02125% / 95 : 38.59529% / 99 : 56.14148%
random_forest     MIST           Base            radius             75 : 2.47596% / 90 : 22.08007% / 95 : 33.27333% / 99 : 51.21584%
                                 mass_smaller_3  radius            75 : 22.30901% / 90 : 41.45068% / 95 : 52.10991% / 99 : 71.63002%
                                 mass_smaller_14 radius               75 : 6.02044% / 90 : 25.83075% / 95 : 36.255% / 99 : 53.47634%
                                 mass_smaller_30 radius             75 : 4.00301% / 90 : 23.99494% / 95 : 34.47446% / 99 : 51.85086%
xgboost           MIST           Base            radius             75 : 13.77066% / 90 : 21.03103% / 95 : 25.93295% / 99 : 36.2497%
                                 mass_smaller_3  radius            75 : 19.81723% / 90 : 30.45233% / 95 : 37.37813% / 99 : 50.70474%
                                 mass_smaller_14 radius             75 : 15.0421% / 90 : 22.28418% / 95 : 27.10527% / 99 : 37.50758%
                                 mass_smaller_30 radius             75 : 14.31773% / 90 : 21.61933% / 95 : 26.47128% / 99 : 36.5678%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Results for the phase category with a value of 3.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
KNN               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
mlp               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.6590712626454432
                                 mass_smaller_3  radius             0.35081167612718833
                                 mass_smaller_14 radius              0.6160001034824771
                                 mass_smaller_30 radius              0.6206737380792444
KNN               MIST           Base            radius              0.8353242227223191
                                 mass_smaller_3  radius              0.7535060700780324
                                 mass_smaller_14 radius              0.8342892512480198
                                 mass_smaller_30 radius              0.8294303823205751
linear_regression MIST           Base            radius              0.3982384047629932
                                 mass_smaller_3  radius            -0.07494995277205785
                                 mass_smaller_14 radius             0.41936533653757024
                                 mass_smaller_30 radius              0.3267466410515468
mlp               MIST           Base            radius              0.5642957350076949
                                 mass_smaller_3  radius              0.1138444737599047
                                 mass_smaller_14 radius             0.49578211404893224
                                 mass_smaller_30 radius             0.06029965560710715
random_forest     MIST           Base            radius              0.7822157797380761
                                 mass_smaller_3  radius              0.6076236823682659
                                 mass_smaller_14 radius              0.7574501064358165
                                 mass_smaller_30 radius               0.759258384982005
xgboost           MIST           Base            radius              0.7131476322201502
                                 mass_smaller_3  radius              0.6041815289843242
                                 mass_smaller_14 radius              0.6833396854803595
                                 mass_smaller_30 radius              0.6908352593175837

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             9.68915%
                                 mass_smaller_3  radius            14.00059%
                                 mass_smaller_14 radius            11.04287%
                                 mass_smaller_30 radius              9.7228%
KNN               MIST           Base            radius              6.7715%
                                 mass_smaller_3  radius             8.61369%
                                 mass_smaller_14 radius             7.25287%
                                 mass_smaller_30 radius             6.53249%
linear_regression MIST           Base            radius            24.02534%
                                 mass_smaller_3  radius            25.30981%
                                 mass_smaller_14 radius            24.28421%
                                 mass_smaller_30 radius            22.67477%
mlp               MIST           Base            radius             12.8948%
                                 mass_smaller_3  radius            19.46503%
                                 mass_smaller_14 radius            14.94349%
                                 mass_smaller_30 radius            17.99745%
random_forest     MIST           Base            radius             7.75509%
                                 mass_smaller_3  radius            10.88908%
                                 mass_smaller_14 radius             8.78628%
                                 mass_smaller_30 radius             7.75612%
xgboost           MIST           Base            radius            10.80828%
                                 mass_smaller_3  radius            12.04656%
                                 mass_smaller_14 radius            12.14277%
                                 mass_smaller_30 radius            10.66887%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             2.97062%
                                 mass_smaller_3  radius             4.56728%
                                 mass_smaller_14 radius             3.22661%
                                 mass_smaller_30 radius             2.87817%
KNN               MIST           Base            radius             2.62182%
                                 mass_smaller_3  radius             3.43954%
                                 mass_smaller_14 radius             2.60505%
                                 mass_smaller_30 radius             2.37863%
linear_regression MIST           Base            radius            20.89034%
                                 mass_smaller_3  radius            18.89648%
                                 mass_smaller_14 radius             20.8337%
                                 mass_smaller_30 radius            19.42268%
mlp               MIST           Base            radius             9.17557%
                                 mass_smaller_3  radius            14.41522%
                                 mass_smaller_14 radius            10.12429%
                                 mass_smaller_30 radius            13.40789%
random_forest     MIST           Base            radius             2.59391%
                                 mass_smaller_3  radius             3.89808%
                                 mass_smaller_14 radius              2.8212%
                                 mass_smaller_30 radius             2.50425%
xgboost           MIST           Base            radius             7.72471%
                                 mass_smaller_3  radius             7.99654%
                                 mass_smaller_14 radius             8.60054%
                                 mass_smaller_30 radius             7.51952%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.26474%
                                 mass_smaller_3  radius             0.38983%
                                 mass_smaller_14 radius             0.31591%
                                 mass_smaller_30 radius             0.26139%
KNN               MIST           Base            radius             0.35742%
                                 mass_smaller_3  radius             0.56094%
                                 mass_smaller_14 radius             0.38472%
                                 mass_smaller_30 radius             0.33021%
linear_regression MIST           Base            radius            16.85032%
                                 mass_smaller_3  radius            14.12548%
                                 mass_smaller_14 radius            17.59821%
                                 mass_smaller_30 radius            15.68512%
mlp               MIST           Base            radius              5.9726%
                                 mass_smaller_3  radius            10.25658%
                                 mass_smaller_14 radius             5.94211%
                                 mass_smaller_30 radius             9.56729%
random_forest     MIST           Base            radius              0.2432%
                                 mass_smaller_3  radius             0.42526%
                                 mass_smaller_14 radius             0.29197%
                                 mass_smaller_30 radius             0.23619%
xgboost           MIST           Base            radius             5.03794%
                                 mass_smaller_3  radius             4.82432%
                                 mass_smaller_14 radius             5.42161%
                                 mass_smaller_30 radius             4.70475%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.8254828285545792
                                 mass_smaller_3  radius             0.6820236056572688
                                 mass_smaller_14 radius             0.8056024610712359
                                 mass_smaller_30 radius             0.8059452531001631
KNN               MIST           Base            radius             0.9140042384395503
                                 mass_smaller_3  radius             0.8682650878896927
                                 mass_smaller_14 radius             0.9133943688563751
                                 mass_smaller_30 radius             0.9107358889625214
linear_regression MIST           Base            radius             0.6489233026042639
                                 mass_smaller_3  radius             0.1647629145553814
                                 mass_smaller_14 radius             0.6475902703031168
                                 mass_smaller_30 radius             0.5718783607278599
mlp               MIST           Base            radius             0.7668922431326006
                                 mass_smaller_3  radius             0.4297623557407227
                                 mass_smaller_14 radius             0.7255574518107819
                                 mass_smaller_30 radius            0.48398577800524223
random_forest     MIST           Base            radius             0.8853617266109324
                                 mass_smaller_3  radius              0.789798166465493
                                 mass_smaller_14 radius             0.8720719936849396
                                 mass_smaller_30 radius             0.8726345032266805
xgboost           MIST           Base            radius             0.8509390938547726
                                 mass_smaller_3  radius             0.7809057752800133
                                 mass_smaller_14 radius             0.8352348077486584
                                 mass_smaller_30 radius             0.8417490970201137

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             81.61634%
                                 mass_smaller_3  radius            104.79946%
                                 mass_smaller_14 radius             94.78598%
                                 mass_smaller_30 radius             81.47174%
KNN               MIST           Base            radius             81.67085%
                                 mass_smaller_3  radius            104.74628%
                                 mass_smaller_14 radius             94.60865%
                                 mass_smaller_30 radius             81.23643%
linear_regression MIST           Base            radius             57.70486%
                                 mass_smaller_3  radius             94.45306%
                                 mass_smaller_14 radius             71.89087%
                                 mass_smaller_30 radius             57.32618%
mlp               MIST           Base            radius             81.52133%
                                 mass_smaller_3  radius            100.82393%
                                 mass_smaller_14 radius              93.4405%
                                 mass_smaller_30 radius             79.01598%
random_forest     MIST           Base            radius             81.61575%
                                 mass_smaller_3  radius            104.75043%
                                 mass_smaller_14 radius             94.62427%
                                 mass_smaller_30 radius             81.24469%
xgboost           MIST           Base            radius             72.79811%
                                 mass_smaller_3  radius              83.7053%
                                 mass_smaller_14 radius             80.69301%
                                 mass_smaller_30 radius             68.73942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.68742% / 90 : 6.18535% / 95 : 19.77514% / 99 : 51.44197%
                                 mass_smaller_3  radius              75 : 1.48057% / 90 : 11.95688% / 95 : 28.18187% / 99 : 83.2634%
                                 mass_smaller_14 radius              75 : 0.74372% / 90 : 5.58959% / 95 : 20.27583% / 99 : 61.43565%
                                 mass_smaller_30 radius                  75 : 0.624% / 90 : 5.19139% / 95 : 18.80465% / 99 : 53.159%
KNN               MIST           Base            radius              75 : 1.72661% / 90 : 7.67044% / 95 : 13.89062% / 99 : 32.34216%
                                 mass_smaller_3  radius              75 : 2.71549% / 90 : 10.41425% / 95 : 17.33985% / 99 : 38.6301%
                                 mass_smaller_14 radius              75 : 1.43053% / 90 : 7.33442% / 95 : 14.22367% / 99 : 34.67422%
                                 mass_smaller_30 radius              75 : 1.37344% / 90 : 6.64509% / 95 : 12.83333% / 99 : 31.68774%
linear_regression MIST           Base            radius            75 : 27.91163% / 90 : 40.43345% / 95 : 45.12881% / 99 : 51.34957%
                                 mass_smaller_3  radius            75 : 20.18426% / 90 : 49.89731% / 95 : 59.18561% / 99 : 70.86323%
                                 mass_smaller_14 radius            75 : 28.39245% / 90 : 38.23248% / 95 : 46.63394% / 99 : 55.55252%
                                 mass_smaller_30 radius            75 : 26.61201% / 90 : 38.59521% / 95 : 42.95718% / 99 : 48.63506%
mlp               MIST           Base            radius            75 : 13.24465% / 90 : 22.53951% / 95 : 28.20468% / 99 : 38.01338%
                                 mass_smaller_3  radius            75 : 19.20755% / 90 : 33.62319% / 95 : 42.64553% / 99 : 57.26139%
                                 mass_smaller_14 radius            75 : 14.22668% / 90 : 25.92132% / 95 : 33.68817% / 99 : 47.27624%
                                 mass_smaller_30 radius            75 : 20.05208% / 90 : 30.50131% / 95 : 36.46773% / 99 : 52.23177%
random_forest     MIST           Base            radius              75 : 1.04639% / 90 : 6.56763% / 95 : 15.33742% / 99 : 41.31288%
                                 mass_smaller_3  radius             75 : 2.23194% / 90 : 10.84387% / 95 : 20.77494% / 99 : 57.37664%
                                 mass_smaller_14 radius              75 : 1.11658% / 90 : 6.54618% / 95 : 16.02004% / 99 : 47.88373%
                                 mass_smaller_30 radius               75 : 0.9232% / 90 : 5.93852% / 95 : 14.58911% / 99 : 42.18387%
xgboost           MIST           Base            radius             75 : 11.32517% / 90 : 18.75812% / 95 : 23.03348% / 99 : 32.5998%
                                 mass_smaller_3  radius            75 : 10.32338% / 90 : 19.28476% / 95 : 27.14384% / 99 : 42.32636%
                                 mass_smaller_14 radius             75 : 12.5314% / 90 : 21.52863% / 95 : 26.17067% / 99 : 36.20382%
                                 mass_smaller_30 radius             75 : 10.84538% / 90 : 18.72956% / 95 : 23.1016% / 99 : 32.70042%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Linear regression : 
- mass_smaller_3 : better results than Base on every metric except P99 and MAX_ER
- mass_smaller_14 : better results than Base on every metric except MAX_ER
- mass_smaller_30 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : very slightly worse results than Base on every metric
- mass_smaller_30 : similar results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : very slightly better results than Base on every metric
- mass_smaller_30 : very slightly better results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse/similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

XGBoost : 
- mass_smaller_3 : similar results to Base on every metric
- mass_smaller_14 : similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse/similar results to Base on every metric
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

#### Conclusions on radius

mass_smaller_3 almost always gives worse results than Base.

mass_smaller_14 and mass_smaller_30 give very similar results to Base.

All the results are pretty bad, 5% and more RMSE, 1-2% MAE, very high MAX_ER,...

#### Best models for the radius parameter

The three best performing models in order for the radius parameter are KNN, Random forest and Decision tree.

### log_g parameter

In [23]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
KNN               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
linear_regression MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
mlp               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
random_forest     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
xgboost           MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.7285247646204323
                                 mass_smaller_3  log_g              0.6138112143565488
                                 mass_smaller_14 log_g              0.7189069024866426
                                 mass_smaller_30 log_g              0.7181035533852704
KNN               MIST           Base            log_g              0.8593320998569429
                                 mass_smaller_3  log_g              0.8236243833174176
                                 mass_smaller_14 log_g               0.866920583507224
                                 mass_smaller_30 log_g               0.862489109211493
linear_regression MIST           Base            log_g             0.12147458541872769
                                 mass_smaller_3  log_g             0.35434676404367205
                                 mass_smaller_14 log_g              0.2640825025784339
                                 mass_smaller_30 log_g             0.19463139141835717
mlp               MIST           Base            log_g              0.6418730124942693
                                 mass_smaller_3  log_g              0.5771521379759594
                                 mass_smaller_14 log_g              0.6138501240242349
                                 mass_smaller_30 log_g              0.3352960639050495
random_forest     MIST           Base            log_g              0.8198256636371155
                                 mass_smaller_3  log_g              0.7465900159985581
                                 mass_smaller_14 log_g              0.8133904953096501
                                 mass_smaller_30 log_g               0.813686514686689
xgboost           MIST           Base            log_g              0.7433521284066151
                                 mass_smaller_3  log_g              0.7789057456997621
                                 mass_smaller_14 log_g               0.748756654054018
                                 mass_smaller_30 log_g              0.7435212384765314

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              8.63038%
                                 mass_smaller_3  log_g             12.11548%
                                 mass_smaller_14 log_g             10.06455%
                                 mass_smaller_30 log_g              8.89904%
KNN               MIST           Base            log_g              6.21617%
                                 mass_smaller_3  log_g              8.18831%
                                 mass_smaller_14 log_g               6.9268%
                                 mass_smaller_30 log_g              6.21789%
linear_regression MIST           Base            log_g             15.52437%
                                 mass_smaller_3  log_g             15.66347%
                                 mass_smaller_14 log_g             16.28354%
                                 mass_smaller_30 log_g              15.0404%
mlp               MIST           Base            log_g              9.96571%
                                 mass_smaller_3  log_g             12.67641%
                                 mass_smaller_14 log_g             11.98187%
                                 mass_smaller_30 log_g             13.66823%
random_forest     MIST           Base            log_g              7.03112%
                                 mass_smaller_3  log_g              9.81431%
                                 mass_smaller_14 log_g              8.20061%
                                 mass_smaller_30 log_g              7.23491%
xgboost           MIST           Base            log_g              8.39084%
                                 mass_smaller_3  log_g              9.16595%
                                 mass_smaller_14 log_g               9.5144%
                                 mass_smaller_30 log_g              8.48765%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              2.37276%
                                 mass_smaller_3  log_g              3.99059%
                                 mass_smaller_14 log_g              2.79121%
                                 mass_smaller_30 log_g               2.4518%
KNN               MIST           Base            log_g              2.04919%
                                 mass_smaller_3  log_g               2.8999%
                                 mass_smaller_14 log_g              2.13258%
                                 mass_smaller_30 log_g              1.95213%
linear_regression MIST           Base            log_g             12.69875%
                                 mass_smaller_3  log_g             12.54307%
                                 mass_smaller_14 log_g             13.14727%
                                 mass_smaller_30 log_g             12.06362%
mlp               MIST           Base            log_g              6.54401%
                                 mass_smaller_3  log_g              8.26879%
                                 mass_smaller_14 log_g              8.02197%
                                 mass_smaller_30 log_g              9.13665%
random_forest     MIST           Base            log_g              2.07541%
                                 mass_smaller_3  log_g              3.46271%
                                 mass_smaller_14 log_g              2.43474%
                                 mass_smaller_30 log_g              2.13613%
xgboost           MIST           Base            log_g              5.41921%
                                 mass_smaller_3  log_g              5.37573%
                                 mass_smaller_14 log_g              6.08087%
                                 mass_smaller_30 log_g              5.43794%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.10357%
                                 mass_smaller_3  log_g              0.10772%
                                 mass_smaller_14 log_g              0.11584%
                                 mass_smaller_30 log_g              0.10133%
KNN               MIST           Base            log_g              0.08534%
                                 mass_smaller_3  log_g              0.08708%
                                 mass_smaller_14 log_g              0.08481%
                                 mass_smaller_30 log_g              0.07714%
linear_regression MIST           Base            log_g             10.86887%
                                 mass_smaller_3  log_g             11.36309%
                                 mass_smaller_14 log_g             10.84226%
                                 mass_smaller_30 log_g              9.76028%
mlp               MIST           Base            log_g              3.41768%
                                 mass_smaller_3  log_g               3.8299%
                                 mass_smaller_14 log_g               4.0749%
                                 mass_smaller_30 log_g              4.81846%
random_forest     MIST           Base            log_g              0.05608%
                                 mass_smaller_3  log_g              0.05969%
                                 mass_smaller_14 log_g              0.06227%
                                 mass_smaller_30 log_g              0.05374%
xgboost           MIST           Base            log_g              2.76032%
                                 mass_smaller_3  log_g              2.11627%
                                 mass_smaller_14 log_g              3.00412%
                                 mass_smaller_30 log_g              2.68542%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.8650177953048179
                                 mass_smaller_3  log_g              0.8086938972173562
                                 mass_smaller_14 log_g              0.8603439496612715
                                 mass_smaller_30 log_g              0.8600069496777575
KNN               MIST           Base            log_g              0.9276197914525868
                                 mass_smaller_3  log_g              0.9084810991897053
                                 mass_smaller_14 log_g              0.9316142259580836
                                 mass_smaller_30 log_g              0.9292952253806753
linear_regression MIST           Base            log_g              0.3485320446593273
                                 mass_smaller_3  log_g              0.5952703288602817
                                 mass_smaller_14 log_g              0.5138895821344123
                                 mass_smaller_30 log_g             0.44117047957309463
mlp               MIST           Base            log_g              0.8016648757290119
                                 mass_smaller_3  log_g              0.7608965549932789
                                 mass_smaller_14 log_g              0.7843504708309273
                                 mass_smaller_30 log_g              0.6391839561254214
random_forest     MIST           Base            log_g              0.9076055609149075
                                 mass_smaller_3  log_g               0.868711422625732
                                 mass_smaller_14 log_g              0.9042615607050316
                                 mass_smaller_30 log_g              0.9044100379702219
xgboost           MIST           Base            log_g              0.8626939818756764
                                 mass_smaller_3  log_g              0.8829455189300828
                                 mass_smaller_14 log_g              0.8657553618027817
                                 mass_smaller_30 log_g              0.8627864126356243

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             77.21771%
                                 mass_smaller_3  log_g              87.1508%
                                 mass_smaller_14 log_g             87.37434%
                                 mass_smaller_30 log_g             77.36648%
KNN               MIST           Base            log_g             77.24848%
                                 mass_smaller_3  log_g             87.13073%
                                 mass_smaller_14 log_g             86.68154%
                                 mass_smaller_30 log_g             77.14502%
linear_regression MIST           Base            log_g             54.65398%
                                 mass_smaller_3  log_g             77.47297%
                                 mass_smaller_14 log_g             67.30463%
                                 mass_smaller_30 log_g             56.37993%
mlp               MIST           Base            log_g             76.51689%
                                 mass_smaller_3  log_g             84.64705%
                                 mass_smaller_14 log_g             85.07392%
                                 mass_smaller_30 log_g             75.72174%
random_forest     MIST           Base            log_g             77.22678%
                                 mass_smaller_3  log_g             87.13463%
                                 mass_smaller_14 log_g             86.76837%
                                 mass_smaller_30 log_g             77.14587%
xgboost           MIST           Base            log_g             68.08384%
                                 mass_smaller_3  log_g             79.69897%
                                 mass_smaller_14 log_g             74.67886%
                                 mass_smaller_30 log_g             67.92942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               75 : 0.26204% / 90 : 2.88519% / 95 : 18.52967% / 99 : 45.58648%
                                 mass_smaller_3  log_g               75 : 0.3674% / 90 : 13.75779% / 95 : 30.44001% / 99 : 57.26905%
                                 mass_smaller_14 log_g               75 : 0.29819% / 90 : 3.57029% / 95 : 22.07139% / 99 : 52.51772%
                                 mass_smaller_30 log_g                75 : 0.25881% / 90 : 2.9764% / 95 : 19.46809% / 99 : 46.55716%
KNN               MIST           Base            log_g               75 : 0.43297% / 90 : 6.33191% / 95 : 13.92119% / 99 : 29.55642%
                                 mass_smaller_3  log_g              75 : 0.48418% / 90 : 10.94047% / 95 : 19.77167% / 99 : 35.51611%
                                 mass_smaller_14 log_g                75 : 0.35129% / 90 : 5.92419% / 95 : 15.2712% / 99 : 33.02629%
                                 mass_smaller_30 log_g               75 : 0.34257% / 90 : 5.61598% / 95 : 13.67147% / 99 : 29.66892%
linear_regression MIST           Base            log_g             75 : 16.93223% / 90 : 25.24879% / 95 : 30.51061% / 99 : 41.11079%
                                 mass_smaller_3  log_g              75 : 16.26027% / 90 : 22.68349% / 95 : 31.1745% / 99 : 47.60963%
                                 mass_smaller_14 log_g             75 : 18.81341% / 90 : 26.85348% / 95 : 31.57785% / 99 : 41.95248%
                                 mass_smaller_30 log_g             75 : 17.01832% / 90 : 24.92174% / 95 : 29.86118% / 99 : 39.59072%
mlp               MIST           Base            log_g              75 : 10.47774% / 90 : 17.72734% / 95 : 21.68821% / 99 : 30.8161%
                                 mass_smaller_3  log_g                75 : 12.73043% / 90 : 22.52% / 95 : 28.91925% / 99 : 39.67625%
                                 mass_smaller_14 log_g             75 : 13.54652% / 90 : 21.54776% / 95 : 25.34519% / 99 : 34.63326%
                                 mass_smaller_30 log_g             75 : 14.77625% / 90 : 24.69955% / 95 : 29.46122% / 99 : 40.92219%
random_forest     MIST           Base            log_g                75 : 0.25196% / 90 : 4.56027% / 95 : 15.62515% / 99 : 35.3524%
                                 mass_smaller_3  log_g              75 : 0.58283% / 90 : 12.91636% / 95 : 24.59715% / 99 : 44.45871%
                                 mass_smaller_14 log_g               75 : 0.28407% / 90 : 5.53392% / 95 : 18.52995% / 99 : 41.12759%
                                 mass_smaller_30 log_g               75 : 0.24295% / 90 : 4.74896% / 95 : 16.30326% / 99 : 36.36262%
xgboost           MIST           Base            log_g              75 : 8.23921% / 90 : 14.62955% / 95 : 18.60118% / 99 : 26.67164%
                                 mass_smaller_3  log_g               75 : 7.56536% / 90 : 15.3858% / 95 : 21.34221% / 99 : 32.81941%
                                 mass_smaller_14 log_g              75 : 9.35146% / 90 : 16.56141% / 95 : 21.18097% / 99 : 30.22441%
                                 mass_smaller_30 log_g              75 : 8.27618% / 90 : 14.76395% / 95 : 18.96838% / 99 : 27.01924%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511
                                 mass_smaller_3  log_g              203.75130891799927

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
KNN               MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
linear_regression MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
mlp               MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
random_forest     MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
xgboost           MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.45836693468175915
                                 mass_smaller_3  log_g              -1.1300497320341796
                                 mass_smaller_14 log_g              0.05701950107399145
                                 mass_smaller_30 log_g              0.37615329194584457
KNN               MIST           Base            log_g               0.6553166931256764
                                 mass_smaller_3  log_g             -0.05205026633067278
                                 mass_smaller_14 log_g              0.48608619995224744
                                 mass_smaller_30 log_g               0.6424747234239525
linear_regression MIST           Base            log_g              -0.0611340641093332
                                 mass_smaller_3  log_g               -2.521397989651777
                                 mass_smaller_14 log_g               -0.844565358746435
                                 mass_smaller_30 log_g             -0.09979128547079386
mlp               MIST           Base            log_g              0.15799191189495787
                                 mass_smaller_3  log_g              -1.6952020211239422
                                 mass_smaller_14 log_g              -0.7756869751909656
                                 mass_smaller_30 log_g              -0.6183924085775647
random_forest     MIST           Base            log_g                0.655638939150234
                                 mass_smaller_3  log_g              -0.2951054665192323
                                 mass_smaller_14 log_g              0.41070435949489426
                                 mass_smaller_30 log_g                0.606987074468411
xgboost           MIST           Base            log_g               0.4471727368192875
                                 mass_smaller_3  log_g             -0.48240618124680723
                                 mass_smaller_14 log_g             0.022218103719078286
                                 mass_smaller_30 log_g               0.3757175405545202

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              7.69123%
                                 mass_smaller_3  log_g             24.52446%
                                 mass_smaller_14 log_g              7.38958%
                                 mass_smaller_30 log_g              7.74995%
KNN               MIST           Base            log_g              6.20155%
                                 mass_smaller_3  log_g             17.27367%
                                 mass_smaller_14 log_g              5.48163%
                                 mass_smaller_30 log_g              5.90784%
linear_regression MIST           Base            log_g             16.84849%
                                 mass_smaller_3  log_g             41.10698%
                                 mass_smaller_14 log_g             15.39921%
                                 mass_smaller_30 log_g             15.83877%
mlp               MIST           Base            log_g             10.81126%
                                 mass_smaller_3  log_g             31.13279%
                                 mass_smaller_14 log_g              12.1479%
                                 mass_smaller_30 log_g              13.6968%
random_forest     MIST           Base            log_g              6.15166%
                                 mass_smaller_3  log_g             19.20845%
                                 mass_smaller_14 log_g              5.86154%
                                 mass_smaller_30 log_g              6.16991%
xgboost           MIST           Base            log_g              8.43068%
                                 mass_smaller_3  log_g             21.51556%
                                 mass_smaller_14 log_g              8.21256%
                                 mass_smaller_30 log_g               8.4162%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              1.23362%
                                 mass_smaller_3  log_g              3.48977%
                                 mass_smaller_14 log_g               0.9911%
                                 mass_smaller_30 log_g              1.16974%
KNN               MIST           Base            log_g              1.49713%
                                 mass_smaller_3  log_g              2.75962%
                                 mass_smaller_14 log_g              0.92602%
                                 mass_smaller_30 log_g              1.19974%
linear_regression MIST           Base            log_g             14.48558%
                                 mass_smaller_3  log_g              36.1289%
                                 mass_smaller_14 log_g             12.69459%
                                 mass_smaller_30 log_g             13.04051%
mlp               MIST           Base            log_g              6.16017%
                                 mass_smaller_3  log_g              17.1055%
                                 mass_smaller_14 log_g              7.27198%
                                 mass_smaller_30 log_g              7.82195%
random_forest     MIST           Base            log_g              1.13095%
                                 mass_smaller_3  log_g              3.23175%
                                 mass_smaller_14 log_g              0.91205%
                                 mass_smaller_30 log_g               1.0701%
xgboost           MIST           Base            log_g              4.70345%
                                 mass_smaller_3  log_g              9.68735%
                                 mass_smaller_14 log_g               4.3431%
                                 mass_smaller_30 log_g               4.6038%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.06856%
                                 mass_smaller_3  log_g              0.15006%
                                 mass_smaller_14 log_g              0.06005%
                                 mass_smaller_30 log_g              0.06371%
KNN               MIST           Base            log_g              0.05378%
                                 mass_smaller_3  log_g              0.13072%
                                 mass_smaller_14 log_g              0.04206%
                                 mass_smaller_30 log_g              0.04637%
linear_regression MIST           Base            log_g             13.26164%
                                 mass_smaller_3  log_g             37.61934%
                                 mass_smaller_14 log_g             10.62594%
                                 mass_smaller_30 log_g              10.8214%
mlp               MIST           Base            log_g              1.22781%
                                 mass_smaller_3  log_g              5.76802%
                                 mass_smaller_14 log_g              1.48053%
                                 mass_smaller_30 log_g              1.91017%
random_forest     MIST           Base            log_g              0.02924%
                                 mass_smaller_3  log_g              0.06654%
                                 mass_smaller_14 log_g              0.02524%
                                 mass_smaller_30 log_g              0.02659%
xgboost           MIST           Base            log_g              1.38202%
                                 mass_smaller_3  log_g               1.9691%
                                 mass_smaller_14 log_g              1.05678%
                                 mass_smaller_30 log_g              1.28116%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.8064994593089099
                                 mass_smaller_3  log_g              0.6375765894703289
                                 mass_smaller_14 log_g              0.7393021475013991
                                 mass_smaller_30 log_g              0.7877792937070838
KNN               MIST           Base            log_g              0.8672941111598133
                                 mass_smaller_3  log_g              0.7488648874287605
                                 mass_smaller_14 log_g              0.8323450479359569
                                 mass_smaller_30 log_g              0.8636937145353946
linear_regression MIST           Base            log_g             0.29813341758804923
                                 mass_smaller_3  log_g              0.5823745803566858
                                 mass_smaller_14 log_g             0.45563954743444723
                                 mass_smaller_30 log_g              0.4411502617745956
mlp               MIST           Base            log_g              0.7783008265777945
                                 mass_smaller_3  log_g              0.7789827796691844
                                 mass_smaller_14 log_g              0.7872523910284589
                                 mass_smaller_30 log_g              0.6581716551440178
random_forest     MIST           Base            log_g               0.863807624437327
                                 mass_smaller_3  log_g                0.72688968985791
                                 mass_smaller_14 log_g              0.8119698543700286
                                 mass_smaller_30 log_g              0.8497599980063882
xgboost           MIST           Base            log_g              0.8353265916677893
                                 mass_smaller_3  log_g              0.8157995353707765
                                 mass_smaller_14 log_g              0.8401454856816758
                                 mass_smaller_30 log_g              0.8301342889155285

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              93.99281%
                                 mass_smaller_3  log_g             275.29554%
                                 mass_smaller_14 log_g              94.40998%
                                 mass_smaller_30 log_g              93.68956%
KNN               MIST           Base            log_g              92.41866%
                                 mass_smaller_3  log_g             271.35114%
                                 mass_smaller_14 log_g               91.9639%
                                 mass_smaller_30 log_g              92.30022%
linear_regression MIST           Base            log_g              63.17729%
                                 mass_smaller_3  log_g              85.40057%
                                 mass_smaller_14 log_g              51.89466%
                                 mass_smaller_30 log_g              61.99574%
mlp               MIST           Base            log_g              63.37325%
                                 mass_smaller_3  log_g             154.73679%
                                 mass_smaller_14 log_g                55.658%
                                 mass_smaller_30 log_g              76.77598%
random_forest     MIST           Base            log_g              92.55336%
                                 mass_smaller_3  log_g             270.14473%
                                 mass_smaller_14 log_g              92.44992%
                                 mass_smaller_30 log_g              91.23499%
xgboost           MIST           Base            log_g              81.01893%
                                 mass_smaller_3  log_g             252.60134%
                                 mass_smaller_14 log_g              79.89835%
                                 mass_smaller_30 log_g              82.29856%

                                                                                                                          Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g                 75 : 0.13682% / 90 : 0.28458% / 95 : 0.60516% / 99 : 51.33546%
                                 mass_smaller_3  log_g                 75 : 0.30487% / 90 : 0.53133% / 95 : 0.8922% / 99 : 168.86915%
                                 mass_smaller_14 log_g                 75 : 0.11956% / 90 : 0.20861% / 95 : 0.35354% / 99 : 52.72698%
                                 mass_smaller_30 log_g                    75 : 0.12719% / 90 : 0.23829% / 95 : 0.46% / 99 : 53.16911%
KNN               MIST           Base            log_g                  75 : 0.16982% / 90 : 1.49755% / 95 : 9.0402% / 99 : 32.78109%
                                 mass_smaller_3  log_g                 75 : 0.28636% / 90 : 0.59464% / 95 : 1.05146% / 99 : 91.87805%
                                 mass_smaller_14 log_g                 75 : 0.10729% / 90 : 0.30678% / 95 : 1.00822% / 99 : 29.52588%
                                 mass_smaller_30 log_g                 75 : 0.12769% / 90 : 0.59432% / 95 : 4.32676% / 99 : 31.79534%
linear_regression MIST           Base            log_g               75 : 18.6411% / 90 : 26.76038% / 95 : 30.97309% / 99 : 37.56878%
                                 mass_smaller_3  log_g               75 : 50.1188% / 90 : 62.47037% / 95 : 68.58967% / 99 : 77.66707%
                                 mass_smaller_14 log_g              75 : 18.16279% / 90 : 26.06442% / 95 : 29.66816% / 99 : 35.27342%
                                 mass_smaller_30 log_g              75 : 18.44925% / 90 : 26.70296% / 95 : 30.54218% / 99 : 36.55059%
mlp               MIST           Base            log_g              75 : 10.04719% / 90 : 20.67216% / 95 : 25.13447% / 99 : 34.61879%
                                 mass_smaller_3  log_g             75 : 16.39572% / 90 : 55.29621% / 95 : 79.52891% / 99 : 114.71449%
                                 mass_smaller_14 log_g              75 : 14.06937% / 90 : 23.52927% / 95 : 26.98559% / 99 : 33.88429%
                                 mass_smaller_30 log_g              75 : 10.39072% / 90 : 27.74435% / 95 : 34.10349% / 99 : 40.35301%
random_forest     MIST           Base            log_g                 75 : 0.08707% / 90 : 0.32323% / 95 : 2.33986% / 99 : 36.50441%
                                 mass_smaller_3  log_g                75 : 0.17191% / 90 : 0.52987% / 95 : 3.61314% / 99 : 112.90086%
                                 mass_smaller_14 log_g                 75 : 0.06965% / 90 : 0.20363% / 95 : 0.76413% / 99 : 35.83093%
                                 mass_smaller_30 log_g                  75 : 0.07661% / 90 : 0.2504% / 95 : 1.58398% / 99 : 37.13812%
xgboost           MIST           Base            log_g               75 : 6.21973% / 90 : 14.71961% / 95 : 19.68275% / 99 : 28.61465%
                                 mass_smaller_3  log_g               75 : 8.35224% / 90 : 29.52797% / 95 : 48.73569% / 99 : 84.21639%
                                 mass_smaller_14 log_g               75 : 5.24824% / 90 : 14.01896% / 95 : 19.24846% / 99 : 28.67138%
                                 mass_smaller_30 log_g               75 : 5.90162% / 90 : 14.57205% / 95 : 19.79145% / 99 : 28.87745%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Results for the phase category with a value of 2.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
KNN               MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
linear_regression MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
mlp               MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
random_forest     MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
xgboost           MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865

                                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               0.10816902880453338
                                 mass_smaller_3  log_g                -0.600607812095914
                                 mass_smaller_14 log_g              -0.03513855644318564
                                 mass_smaller_30 log_g                0.0377295775830393
KNN               MIST           Base            log_g                 0.594178882501541
                                 mass_smaller_3  log_g                0.2590407279815474
                                 mass_smaller_14 log_g                0.5303123075394265
                                 mass_smaller_30 log_g                0.5647573800180672
linear_regression MIST           Base            log_g                0.2245163409964468
                                 mass_smaller_3  log_g             -0.024985407321623132
                                 mass_smaller_14 log_g               0.11325394232664077
                                 mass_smaller_30 log_g               0.12370500206716573
mlp               MIST           Base            log_g                0.3249124565645656
                                 mass_smaller_3  log_g              -0.02348330102255436
                                 mass_smaller_14 log_g                 0.266375411165814
                                 mass_smaller_30 log_g               -0.4449444547364432
random_forest     MIST           Base            log_g               0.38691114604182897
                                 mass_smaller_3  log_g              -0.09774314204530898
                                 mass_smaller_14 log_g                0.2860576263244211
                                 mass_smaller_30 log_g               0.34065187710603484
xgboost           MIST           Base            log_g               0.41515284669200114
                                 mass_smaller_3  log_g               0.29738900211887476
                                 mass_smaller_14 log_g                0.3627631788126231
                                 mass_smaller_30 log_g               0.39282919468435273

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             18.27543%
                                 mass_smaller_3  log_g             26.03536%
                                 mass_smaller_14 log_g             19.93071%
                                 mass_smaller_30 log_g              19.0992%
KNN               MIST           Base            log_g             12.33347%
                                 mass_smaller_3  log_g             17.73381%
                                 mass_smaller_14 log_g             13.43205%
                                 mass_smaller_30 log_g             12.85004%
linear_regression MIST           Base            log_g             22.30162%
                                 mass_smaller_3  log_g             23.73509%
                                 mass_smaller_14 log_g             22.24743%
                                 mass_smaller_30 log_g             22.55021%
mlp               MIST           Base            log_g             15.90061%
                                 mass_smaller_3  log_g             21.43808%
                                 mass_smaller_14 log_g             16.78211%
                                 mass_smaller_30 log_g             23.59835%
random_forest     MIST           Base            log_g             15.15768%
                                 mass_smaller_3  log_g             21.58147%
                                 mass_smaller_14 log_g             16.55842%
                                 mass_smaller_30 log_g             15.81473%
xgboost           MIST           Base            log_g             14.93954%
                                 mass_smaller_3  log_g             17.43216%
                                 mass_smaller_14 log_g             15.83208%
                                 mass_smaller_30 log_g              15.3332%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              7.47512%
                                 mass_smaller_3  log_g             14.73486%
                                 mass_smaller_14 log_g              8.85195%
                                 mass_smaller_30 log_g               8.1436%
KNN               MIST           Base            log_g               5.2846%
                                 mass_smaller_3  log_g              10.3866%
                                 mass_smaller_14 log_g              6.20551%
                                 mass_smaller_30 log_g              5.69755%
linear_regression MIST           Base            log_g             16.88375%
                                 mass_smaller_3  log_g             18.41003%
                                 mass_smaller_14 log_g             17.54727%
                                 mass_smaller_30 log_g             17.56593%
mlp               MIST           Base            log_g             12.39095%
                                 mass_smaller_3  log_g             17.00405%
                                 mass_smaller_14 log_g              13.4424%
                                 mass_smaller_30 log_g             18.70484%
random_forest     MIST           Base            log_g              6.40953%
                                 mass_smaller_3  log_g             12.64109%
                                 mass_smaller_14 log_g              7.59406%
                                 mass_smaller_30 log_g              6.96691%
xgboost           MIST           Base            log_g             11.23095%
                                 mass_smaller_3  log_g             13.39482%
                                 mass_smaller_14 log_g             12.29373%
                                 mass_smaller_30 log_g             11.65767%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.33801%
                                 mass_smaller_3  log_g              0.67312%
                                 mass_smaller_14 log_g              0.38587%
                                 mass_smaller_30 log_g              0.35496%
KNN               MIST           Base            log_g              0.22004%
                                 mass_smaller_3  log_g              1.96951%
                                 mass_smaller_14 log_g              0.27631%
                                 mass_smaller_30 log_g              0.23695%
linear_regression MIST           Base            log_g             12.23613%
                                 mass_smaller_3  log_g             13.86347%
                                 mass_smaller_14 log_g             14.35389%
                                 mass_smaller_30 log_g             13.93329%
mlp               MIST           Base            log_g              9.94997%
                                 mass_smaller_3  log_g             14.13881%
                                 mass_smaller_14 log_g             11.39814%
                                 mass_smaller_30 log_g             15.55125%
random_forest     MIST           Base            log_g              0.21754%
                                 mass_smaller_3  log_g              2.22946%
                                 mass_smaller_14 log_g              0.28533%
                                 mass_smaller_30 log_g              0.24072%
xgboost           MIST           Base            log_g              8.41823%
                                 mass_smaller_3  log_g             10.43905%
                                 mass_smaller_14 log_g              9.88399%
                                 mass_smaller_30 log_g              9.02535%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.5517614412105366
                                 mass_smaller_3  log_g             0.18202335941849643
                                 mass_smaller_14 log_g             0.47974864175030285
                                 mass_smaller_30 log_g              0.5165791626752562
KNN               MIST           Base            log_g              0.7750442583318956
                                 mass_smaller_3  log_g               0.539920011518819
                                 mass_smaller_14 log_g              0.7349547949015152
                                 mass_smaller_30 log_g              0.7567392250580913
linear_regression MIST           Base            log_g              0.4743260904396181
                                 mass_smaller_3  log_g             0.12286635004626859
                                 mass_smaller_14 log_g             0.36751055359689394
                                 mass_smaller_30 log_g              0.3711145323223116
mlp               MIST           Base            log_g              0.5729121364080281
                                 mass_smaller_3  log_g             0.30576531055074774
                                 mass_smaller_14 log_g               0.518007149747776
                                 mass_smaller_30 log_g             0.28535473759631075
random_forest     MIST           Base            log_g              0.6635177579267701
                                 mass_smaller_3  log_g              0.3341023253485054
                                 mass_smaller_14 log_g              0.6029009914629886
                                 mass_smaller_30 log_g              0.6356216771994637
xgboost           MIST           Base            log_g              0.6444816958330817
                                 mass_smaller_3  log_g              0.5462072880360849
                                 mass_smaller_14 log_g              0.6022982771634144
                                 mass_smaller_30 log_g              0.6267933206065803

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             97.46571%
                                 mass_smaller_3  log_g             97.51643%
                                 mass_smaller_14 log_g              97.9042%
                                 mass_smaller_30 log_g              97.9042%
KNN               MIST           Base            log_g             97.51553%
                                 mass_smaller_3  log_g             91.75768%
                                 mass_smaller_14 log_g             91.42906%
                                 mass_smaller_30 log_g             95.14774%
linear_regression MIST           Base            log_g             71.92701%
                                 mass_smaller_3  log_g             63.49404%
                                 mass_smaller_14 log_g             58.32543%
                                 mass_smaller_30 log_g             66.29245%
mlp               MIST           Base            log_g             77.45604%
                                 mass_smaller_3  log_g             79.59942%
                                 mass_smaller_14 log_g             70.89997%
                                 mass_smaller_30 log_g             93.00004%
random_forest     MIST           Base            log_g             96.64932%
                                 mass_smaller_3  log_g             94.71626%
                                 mass_smaller_14 log_g             94.22698%
                                 mass_smaller_30 log_g             95.24933%
xgboost           MIST           Base            log_g             79.35298%
                                 mass_smaller_3  log_g             81.22272%
                                 mass_smaller_14 log_g             77.44526%
                                 mass_smaller_30 log_g             81.07605%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g                75 : 0.95403% / 90 : 31.99032% / 95 : 49.661% / 99 : 73.63195%
                                 mass_smaller_3  log_g             75 : 25.09455% / 90 : 49.94242% / 95 : 62.96935% / 99 : 79.84058%
                                 mass_smaller_14 log_g               75 : 5.19836% / 90 : 37.0438% / 95 : 53.32691% / 99 : 74.76867%
                                 mass_smaller_30 log_g              75 : 2.15129% / 90 : 34.79498% / 95 : 51.73339% / 99 : 73.79922%
KNN               MIST           Base            log_g              75 : 3.25558% / 90 : 20.78829% / 95 : 31.32773% / 99 : 49.34873%
                                 mass_smaller_3  log_g              75 : 17.2345% / 90 : 32.01566% / 95 : 40.70149% / 99 : 58.08666%
                                 mass_smaller_14 log_g              75 : 6.60313% / 90 : 23.77547% / 95 : 33.68872% / 99 : 50.84458%
                                 mass_smaller_30 log_g                 75 : 4.71701% / 90 : 22.32065% / 95 : 32.7275% / 99 : 49.679%
linear_regression MIST           Base            log_g             75 : 25.11439% / 90 : 39.81179% / 95 : 47.61391% / 99 : 57.14298%
                                 mass_smaller_3  log_g             75 : 26.74976% / 90 : 42.95573% / 95 : 49.94864% / 99 : 57.43105%
                                 mass_smaller_14 log_g             75 : 26.39903% / 90 : 38.12747% / 95 : 44.90013% / 99 : 53.37399%
                                 mass_smaller_30 log_g             75 : 26.09143% / 90 : 39.54977% / 95 : 46.74509% / 99 : 54.72113%
mlp               MIST           Base            log_g             75 : 17.86752% / 90 : 26.52929% / 95 : 32.02242% / 99 : 43.22913%
                                 mass_smaller_3  log_g             75 : 24.56196% / 90 : 35.89017% / 95 : 42.64647% / 99 : 54.72716%
                                 mass_smaller_14 log_g             75 : 19.62784% / 90 : 27.90367% / 95 : 32.52757% / 99 : 41.73653%
                                 mass_smaller_30 log_g               75 : 26.62471% / 90 : 37.826% / 95 : 45.43004% / 99 : 66.45464%
random_forest     MIST           Base            log_g              75 : 2.94649% / 90 : 26.28036% / 95 : 39.61579% / 99 : 60.96039%
                                 mass_smaller_3  log_g                75 : 21.402% / 90 : 39.77326% / 95 : 49.99043% / 99 : 68.7179%
                                 mass_smaller_14 log_g              75 : 7.06569% / 90 : 30.32603% / 95 : 42.55673% / 99 : 62.76894%
                                 mass_smaller_30 log_g              75 : 4.74825% / 90 : 28.46249% / 95 : 40.89544% / 99 : 61.50815%
xgboost           MIST           Base            log_g             75 : 16.39353% / 90 : 25.06295% / 95 : 30.79863% / 99 : 43.07799%
                                 mass_smaller_3  log_g              75 : 19.02666% / 90 : 29.2479% / 95 : 35.87689% / 99 : 48.70343%
                                 mass_smaller_14 log_g             75 : 17.63046% / 90 : 26.19361% / 95 : 31.80238% / 99 : 43.95538%
                                 mass_smaller_30 log_g             75 : 17.00111% / 90 : 25.64597% / 95 : 31.36832% / 99 : 43.42294%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
KNN               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
linear_regression MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
mlp               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
random_forest     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
xgboost           MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               0.5817849716549621
                                 mass_smaller_3  log_g              0.39658754576723376
                                 mass_smaller_14 log_g               0.5649290988435505
                                 mass_smaller_30 log_g               0.5720442209331444
KNN               MIST           Base            log_g               0.7980532314937201
                                 mass_smaller_3  log_g               0.7708923072432344
                                 mass_smaller_14 log_g               0.8122572762330336
                                 mass_smaller_30 log_g               0.8075748852844039
linear_regression MIST           Base            log_g               0.2918925646174637
                                 mass_smaller_3  log_g              0.06115414919245732
                                 mass_smaller_14 log_g               0.3580823886911023
                                 mass_smaller_30 log_g              0.28195119047507056
mlp               MIST           Base            log_g               0.4653238995649285
                                 mass_smaller_3  log_g               0.2008645002962569
                                 mass_smaller_14 log_g               0.4325540283744135
                                 mass_smaller_30 log_g             -0.06588931590939096
random_forest     MIST           Base            log_g               0.7328442946232603
                                 mass_smaller_3  log_g               0.6352925182607598
                                 mass_smaller_14 log_g               0.7251996112862353
                                 mass_smaller_30 log_g               0.7284262896968001
xgboost           MIST           Base            log_g               0.6523316020107637
                                 mass_smaller_3  log_g               0.6309680787988265
                                 mass_smaller_14 log_g               0.6381930706674352
                                 mass_smaller_30 log_g                0.649731958801443

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              9.16454%
                                 mass_smaller_3  log_g             14.63007%
                                 mass_smaller_14 log_g             12.72316%
                                 mass_smaller_30 log_g              9.23587%
KNN               MIST           Base            log_g              6.40396%
                                 mass_smaller_3  log_g              9.00085%
                                 mass_smaller_14 log_g              8.35632%
                                 mass_smaller_30 log_g              6.20516%
linear_regression MIST           Base            log_g             20.75805%
                                 mass_smaller_3  log_g             25.74915%
                                 mass_smaller_14 log_g             26.48153%
                                 mass_smaller_30 log_g             20.04177%
mlp               MIST           Base            log_g             12.26276%
                                 mass_smaller_3  log_g             19.98537%
                                 mass_smaller_14 log_g             17.06044%
                                 mass_smaller_30 log_g             17.02025%
random_forest     MIST           Base            log_g              7.33521%
                                 mass_smaller_3  log_g             11.37864%
                                 mass_smaller_14 log_g             10.12306%
                                 mass_smaller_30 log_g              7.36726%
xgboost           MIST           Base            log_g             10.18322%
                                 mass_smaller_3  log_g             12.61432%
                                 mass_smaller_14 log_g             13.98227%
                                 mass_smaller_30 log_g             10.13779%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               2.8092%
                                 mass_smaller_3  log_g              4.77246%
                                 mass_smaller_14 log_g              3.71793%
                                 mass_smaller_30 log_g              2.73391%
KNN               MIST           Base            log_g              2.47975%
                                 mass_smaller_3  log_g              3.59383%
                                 mass_smaller_14 log_g              3.00148%
                                 mass_smaller_30 log_g              2.25945%
linear_regression MIST           Base            log_g             17.56366%
                                 mass_smaller_3  log_g             19.01309%
                                 mass_smaller_14 log_g             22.13535%
                                 mass_smaller_30 log_g             16.73313%
mlp               MIST           Base            log_g              8.75411%
                                 mass_smaller_3  log_g             14.64573%
                                 mass_smaller_14 log_g             11.56179%
                                 mass_smaller_30 log_g             12.59538%
random_forest     MIST           Base            log_g               2.4529%
                                 mass_smaller_3  log_g              4.07332%
                                 mass_smaller_14 log_g               3.2506%
                                 mass_smaller_30 log_g              2.37865%
xgboost           MIST           Base            log_g              7.29781%
                                 mass_smaller_3  log_g              8.36599%
                                 mass_smaller_14 log_g              9.89411%
                                 mass_smaller_30 log_g               7.1457%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.25027%
                                 mass_smaller_3  log_g               0.4075%
                                 mass_smaller_14 log_g              0.36477%
                                 mass_smaller_30 log_g              0.24852%
KNN               MIST           Base            log_g              0.33808%
                                 mass_smaller_3  log_g              0.58623%
                                 mass_smaller_14 log_g              0.44345%
                                 mass_smaller_30 log_g              0.31397%
linear_regression MIST           Base            log_g              13.7017%
                                 mass_smaller_3  log_g             14.06947%
                                 mass_smaller_14 log_g             18.06905%
                                 mass_smaller_30 log_g             12.97423%
mlp               MIST           Base            log_g              5.72762%
                                 mass_smaller_3  log_g             10.10081%
                                 mass_smaller_14 log_g              6.79746%
                                 mass_smaller_30 log_g               8.7711%
random_forest     MIST           Base            log_g              0.23001%
                                 mass_smaller_3  log_g              0.44471%
                                 mass_smaller_14 log_g              0.33699%
                                 mass_smaller_30 log_g              0.22461%
xgboost           MIST           Base            log_g              4.76833%
                                 mass_smaller_3  log_g              5.06187%
                                 mass_smaller_14 log_g              6.23096%
                                 mass_smaller_30 log_g               4.4703%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.7872344983380405
                                 mass_smaller_3  log_g              0.6995983327084234
                                 mass_smaller_14 log_g              0.7805402170911522
                                 mass_smaller_30 log_g              0.7827031834182294
KNN               MIST           Base            log_g              0.8937310126228201
                                 mass_smaller_3  log_g              0.8780237811999819
                                 mass_smaller_14 log_g              0.9013032085598914
                                 mass_smaller_30 log_g              0.8987875289208588
linear_regression MIST           Base            log_g              0.5655350134948097
                                 mass_smaller_3  log_g              0.2550286481499008
                                 mass_smaller_14 log_g              0.6134692342216399
                                 mass_smaller_30 log_g              0.5386517947860948
mlp               MIST           Base            log_g              0.6888025677453951
                                 mass_smaller_3  log_g             0.48508877527218314
                                 mass_smaller_14 log_g              0.6707943127078274
                                 mass_smaller_30 log_g             0.40828462494586637
random_forest     MIST           Base            log_g              0.8584121763316808
                                 mass_smaller_3  log_g              0.8038675761512467
                                 mass_smaller_14 log_g              0.8543698517419703
                                 mass_smaller_30 log_g              0.8559373653759447
xgboost           MIST           Base            log_g              0.8172568061289313
                                 mass_smaller_3  log_g              0.8005425244811992
                                 mass_smaller_14 log_g              0.8042511867428563
                                 mass_smaller_30 log_g               0.814855291786251

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              77.21771%
                                 mass_smaller_3  log_g             109.46637%
                                 mass_smaller_14 log_g             109.17321%
                                 mass_smaller_30 log_g              77.36648%
KNN               MIST           Base            log_g              77.24848%
                                 mass_smaller_3  log_g             109.44116%
                                 mass_smaller_14 log_g             108.90912%
                                 mass_smaller_30 log_g              77.14502%
linear_regression MIST           Base            log_g              54.65398%
                                 mass_smaller_3  log_g              97.31046%
                                 mass_smaller_14 log_g              84.56343%
                                 mass_smaller_30 log_g              56.37993%
mlp               MIST           Base            log_g              76.51689%
                                 mass_smaller_3  log_g             106.32152%
                                 mass_smaller_14 log_g             106.88926%
                                 mass_smaller_30 log_g              75.72174%
random_forest     MIST           Base            log_g              77.22678%
                                 mass_smaller_3  log_g             109.44606%
                                 mass_smaller_14 log_g             109.01821%
                                 mass_smaller_30 log_g              77.14587%
xgboost           MIST           Base            log_g              68.08384%
                                 mass_smaller_3  log_g              87.22692%
                                 mass_smaller_14 log_g              93.82861%
                                 mass_smaller_30 log_g              67.92942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               75 : 0.65007% / 90 : 5.84978% / 95 : 18.71014% / 99 : 48.68195%
                                 mass_smaller_3  log_g              75 : 1.54731% / 90 : 12.49408% / 95 : 29.44887% / 99 : 86.97434%
                                 mass_smaller_14 log_g                   75 : 0.8569% / 90 : 6.442% / 95 : 23.36157% / 99 : 70.7918%
                                 mass_smaller_30 log_g                75 : 0.5914% / 90 : 4.93494% / 95 : 17.85801% / 99 : 50.51276%
KNN               MIST           Base            log_g                75 : 1.63381% / 90 : 7.2492% / 95 : 13.14337% / 99 : 30.57381%
                                 mass_smaller_3  log_g               75 : 2.83599% / 90 : 10.8825% / 95 : 18.11917% / 99 : 40.36765%
                                 mass_smaller_14 log_g                75 : 1.65094% / 90 : 8.45082% / 95 : 16.38469% / 99 : 39.9358%
                                 mass_smaller_30 log_g               75 : 1.30551% / 90 : 6.31327% / 95 : 12.19598% / 99 : 30.09471%
linear_regression MIST           Base            log_g             75 : 23.90631% / 90 : 35.75704% / 95 : 40.46671% / 99 : 46.57608%
                                 mass_smaller_3  log_g              75 : 19.9253% / 90 : 51.09035% / 95 : 60.69691% / 99 : 73.13676%
                                 mass_smaller_14 log_g              75 : 30.20985% / 90 : 42.9178% / 95 : 52.81286% / 99 : 63.54959%
                                 mass_smaller_30 log_g             75 : 23.03139% / 90 : 34.97512% / 95 : 39.29666% / 99 : 45.66569%
mlp               MIST           Base            log_g             75 : 12.53131% / 90 : 21.34826% / 95 : 26.79204% / 99 : 36.15105%
                                 mass_smaller_3  log_g             75 : 19.69601% / 90 : 35.08553% / 95 : 43.98975% / 99 : 59.25131%
                                 mass_smaller_14 log_g             75 : 16.14057% / 90 : 29.79412% / 95 : 38.51007% / 99 : 54.33847%
                                 mass_smaller_30 log_g             75 : 18.68785% / 90 : 28.90699% / 95 : 34.89286% / 99 : 49.99378%
random_forest     MIST           Base            log_g               75 : 0.99001% / 90 : 6.20702% / 95 : 14.51011% / 99 : 39.02317%
                                 mass_smaller_3  log_g              75 : 2.33225% / 90 : 11.33008% / 95 : 21.70827% / 99 : 59.95828%
                                 mass_smaller_14 log_g               75 : 1.28709% / 90 : 7.54244% / 95 : 18.45425% / 99 : 55.16548%
                                 mass_smaller_30 log_g               75 : 0.87699% / 90 : 5.63934% / 95 : 13.85335% / 99 : 40.05285%
xgboost           MIST           Base            log_g             75 : 10.68135% / 90 : 17.61716% / 95 : 21.69529% / 99 : 30.57667%
                                 mass_smaller_3  log_g               75 : 10.82769% / 90 : 20.2067% / 95 : 28.7444% / 99 : 44.00191%
                                 mass_smaller_14 log_g             75 : 14.45839% / 90 : 24.72078% / 95 : 30.18401% / 99 : 41.86692%
                                 mass_smaller_30 log_g             75 : 10.30003% / 90 : 17.86415% / 95 : 21.94766% / 99 : 31.03032%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Linear regression : 
- mass_smaller_3 : similar results to Base on every metric
- mass_smaller_14 : similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : similar results to Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse results than Base on every metric
- mass_smaller_30 : very slightly better results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : slightly worse results than Base on every metric
- mass_smaller_30 : similar results to Base on every metric

XGBoost : 
- mass_smaller_3 : slightly worse results to Base on every metric
- mass_smaller_14 : slightly worse results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : worse results than Base on every metric

#### Conclusions on log_g

mass_smaller_3 almost always gives worse results than Base.

mass_smaller_14 give slightly worse results than Base.

mass_smaller_30 give worse/similar results to Base.

All the results are pretty bad. Same as above, very high MAX_ER, high RMSE,...

#### Best models for the log_g parameter

The three best performing models in order for the radius parameter are KNN, Random forest and Decision tree.

### Conclusion on both

Using the Base filtering seems to be the best solution for most parameters.

Since mass_smaller_14 is used for model_A_partial, it might still be interesting to use mass_smaller_14; also making it easier to compare with PARSEC

The three models that need to be used are : KNN, Random forest and Decision tree