# Results comparison for MIST filtering of model B

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_B/default_models"

In [7]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 5.379
                             mass_smaller_3  T_eff             3.345 - 4.301
                             mass_smaller_14 T_eff             3.345 - 4.634
                             mass_smaller_30 T_eff             3.345 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.967  0.063
                             mass_smaller_3  T_eff             0.957  0.038
                             mass_smaller_14 T_eff             0.967  0.052
                             mass_smaller_30 T_eff             0.964  0.060

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.016  0.001
                             mass_smaller_3  T_eff             0.014  0.001
                             mass_smaller_14 T_eff             0.013  0.001
                             mass_smaller_30 T_eff             0.015  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.984   0.933
                             mass_smaller_3  T_eff             0.978   0.430
                             mass_smaller_14 T_eff             0.984   0.889
                             mass_smaller_30 T_eff             0.982   0.914

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                             mass_smaller_3  T_eff              75 : 0.00557 / 90 : 0.04726 / 95 : 0.09124 / 99 : 0.17501
                             mass_smaller_14 T_eff               75 : 0.00383 / 90 : 0.02721 / 95 : 0.0747 / 99 : 0.19805
                             mass_smaller_30 T_eff               75 : 0.00376 / 90 : 0.02825 / 95 : 0.0807 / 99 : 0.26673

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 0.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.345 - 4.903
                             mass_smaller_3  T_eff             3.345 - 4.301
                             mass_smaller_14 T_eff             3.345 - 4.634
                             mass_smaller_30 T_eff             3.345 - 4.898

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.974  0.057
                             mass_smaller_3  T_eff             0.986  0.023
                             mass_smaller_14 T_eff             0.981  0.041
                             mass_smaller_30 T_eff             0.973  0.053

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.010  0.001
                             mass_smaller_3  T_eff             0.005  0.000
                             mass_smaller_14 T_eff             0.006  0.001
                             mass_smaller_30 T_eff             0.009  0.001

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.897
                             mass_smaller_3  T_eff             0.993   0.430
                             mass_smaller_14 T_eff             0.991   0.889
                             mass_smaller_30 T_eff             0.987   0.905

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                             mass_smaller_3  T_eff              75 : 0.00127 / 90 : 0.00358 / 95 : 0.01051 / 99 : 0.13035
                             mass_smaller_14 T_eff               75 : 0.0013 / 90 : 0.00354 / 95 : 0.00867 / 99 : 0.14171
                             mass_smaller_30 T_eff               75 : 0.00138 / 90 : 0.00417 / 95 : 0.01479 / 99 : 0.2421

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 2.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.428 - 4.711
                             mass_smaller_3  T_eff             3.431 - 4.277
                             mass_smaller_14 T_eff             3.425 - 4.588
                             mass_smaller_30 T_eff             3.425 - 4.675

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.975  0.050
                             mass_smaller_3  T_eff             0.844  0.057
                             mass_smaller_14 T_eff             0.956  0.052
                             mass_smaller_30 T_eff             0.969  0.050

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.020  0.002
                             mass_smaller_3  T_eff             0.033  0.008
                             mass_smaller_14 T_eff             0.022  0.003
                             mass_smaller_30 T_eff             0.021  0.002

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.987   0.713
                             mass_smaller_3  T_eff             0.920   0.308
                             mass_smaller_14 T_eff             0.978   0.723
                             mass_smaller_30 T_eff             0.985   0.698

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                             mass_smaller_3  T_eff              75 : 0.04972 / 90 : 0.10192 / 95 : 0.13515 / 99 : 0.19473
                             mass_smaller_14 T_eff              75 : 0.01781 / 90 : 0.07692 / 95 : 0.11807 / 99 : 0.19909
                             mass_smaller_30 T_eff              75 : 0.01371 / 90 : 0.07218 / 95 : 0.11434 / 99 : 0.19716

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

Results for the phase category with a value of 3.0

                                                                 value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             3.352 - 5.379
                             mass_smaller_3  T_eff             3.352 - 4.208
                             mass_smaller_14 T_eff             3.352 - 4.524
                             mass_smaller_30 T_eff             3.352 - 5.354

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.918  0.089
                             mass_smaller_3  T_eff             0.918  0.043
                             mass_smaller_14 T_eff             0.896  0.073
                             mass_smaller_30 T_eff             0.904  0.085

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.027  0.003
                             mass_smaller_3  T_eff             0.017  0.003
                             mass_smaller_14 T_eff             0.021  0.003
                             mass_smaller_30 T_eff             0.024  0.003

                                                                CORR  MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             0.959   0.933
                             mass_smaller_3  T_eff             0.958   0.419
                             mass_smaller_14 T_eff             0.947   0.873
                             mass_smaller_30 T_eff             0.952   0.914

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                             mass_smaller_3  T_eff              75 : 0.01337 / 90 : 0.05079 / 95 : 0.08983 / 99 : 0.20541
                             mass_smaller_14 T_eff              75 : 0.01102 / 90 : 0.04317 / 95 : 0.09179 / 99 : 0.40046
                             mass_smaller_30 T_eff              75 : 0.01092 / 90 : 0.04684 / 95 : 0.10789 / 99 : 0.49952

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            T_eff             293.086
                             mass_smaller_3  T_eff             125.782
                             mass_smaller_14 T_eff             223.165
                             mass_smaller_30 T_eff             253.362

In [6]:
compare_metrics(path, value_rounding=3,
                output_parameters=["T_eff", "radius", "log_g"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129
KNN               MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129
linear_regression MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129
mlp               MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129
random_forest     MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129
xgboost           MIST           Base   T_eff              3.345 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.997 - 3.129

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.950  0.077  0.019
                                        log_g             0.729  0.634  0.174
                                        radius            0.816  0.317  0.088
KNN               MIST           Base   T_eff             0.967  0.063  0.019
                                        log_g             0.859  0.456  0.150
                                        radius            0.904  0.228  0.076
linear_regression MIST           Base   T_eff             0.736  0.178  0.144
                                        log_g             0.121  1.140  0.932
                                        radius            0.199  0.661  0.546
mlp               MIST           Base   T_eff             0.850  0.135  0.092
                                        log_g             0.642  0.732  0.480
                                        radius            0.757  0.366  0.242
random_forest     MIST           Base   T_eff             0.967  0.063  0.016
                                        log_g             0.820  0.516  0.152
                                        radius            0.878  0.258  0.076
xgboost           MIST           Base   T_eff             0.901  0.109  0.069
                                        log_g             0.743  0.616  0.398
                                        radius            0.825  0.309  0.199

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.002  0.975
                                        log_g             0.008  0.865
                                        radius            0.005  0.908
KNN               MIST           Base   T_eff             0.002  0.984
                                        log_g             0.006  0.928
                                        radius            0.004  0.951
linear_regression MIST           Base   T_eff             0.132  0.858
                                        log_g             0.798  0.349
                                        radius            0.474  0.446
mlp               MIST           Base   T_eff             0.055  0.922
                                        log_g             0.251  0.802
                                        radius            0.126  0.870
random_forest     MIST           Base   T_eff             0.001  0.984
                                        log_g             0.004  0.908
                                        radius            0.002  0.938
xgboost           MIST           Base   T_eff             0.035  0.949
                                        log_g             0.203  0.863
                                        radius            0.100  0.909

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.951
                                        log_g              5.670
                                        radius             2.835
KNN               MIST           Base   T_eff              0.926
                                        log_g              5.672
                                        radius             2.837
linear_regression MIST           Base   T_eff              0.982
                                        log_g              4.013
                                        radius             2.044
mlp               MIST           Base   T_eff              0.977
                                        log_g              5.618
                                        radius             2.832
random_forest     MIST           Base   T_eff              0.933
                                        log_g              5.670
                                        radius             2.835
xgboost           MIST           Base   T_eff              0.874
                                        log_g              4.999
                                        radius             2.580

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00427 / 90 : 0.02166 / 95 : 0.09746 / 99 : 0.42345
                                        log_g              75 : 0.01924 / 90 : 0.21184 / 95 : 1.36051 / 99 : 3.34711
                                        radius             75 : 0.01029 / 90 : 0.10613 / 95 : 0.68142 / 99 : 1.67507
KNN               MIST           Base   T_eff              75 : 0.00622 / 90 : 0.04667 / 95 : 0.09982 / 99 : 0.31342
                                        log_g              75 : 0.03179 / 90 : 0.46491 / 95 : 1.02214 / 99 : 2.17013
                                        radius             75 : 0.01766 / 90 : 0.23258 / 95 : 0.51127 / 99 : 1.08571
linear_regression MIST           Base   T_eff              75 : 0.19925 / 90 : 0.26261 / 95 : 0.33491 / 99 : 0.49514
                                        log_g              75 : 1.24322 / 90 : 1.85385 / 95 : 2.24019 / 99 : 3.01849
                                        radius              75 : 0.7361 / 90 : 1.09566 / 95 : 1.29908 / 99 : 1.60347
mlp               MIST           Base   T_eff              75 : 0.12551 / 90 : 0.23121 / 95 : 0.30635 / 99 : 0.43044
                                        log_g               75 : 0.76931 / 90 : 1.3016 / 95 : 1.59242 / 99 : 2.26262
                                        radius              75 : 0.38607 / 90 : 0.65018 / 95 : 0.79762 / 99 : 1.1283
random_forest     MIST           Base   T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                        log_g               75 : 0.0185 / 90 : 0.33483 / 95 : 1.14725 / 99 : 2.59569
                                        radius             75 : 0.00955 / 90 : 0.16761 / 95 : 0.57416 / 99 : 1.29851
xgboost           MIST           Base   T_eff              75 : 0.09802 / 90 : 0.18339 / 95 : 0.25166 / 99 : 0.37352
                                        log_g              75 : 0.60495 / 90 : 1.07415 / 95 : 1.36576 / 99 : 1.95832
                                        radius             75 : 0.30188 / 90 : 0.53827 / 95 : 0.68623 / 99 : 0.98445

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        log_g              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        log_g               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        log_g               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        log_g             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        log_g             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        log_g              17.973
                                        radius             17.973

Results for the phase category with a value of 0.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083
KNN               MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083
linear_regression MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083
mlp               MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083
random_forest     MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083
xgboost           MIST           Base   T_eff              3.345 - 4.903
                                        log_g             -0.597 - 5.433
                                        radius            -0.997 - 3.083

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.960  0.070  0.012
                                        log_g             0.458  0.464  0.074
                                        radius            0.836  0.232  0.038
KNN               MIST           Base   T_eff             0.969  0.063  0.016
                                        log_g             0.655  0.374  0.090
                                        radius            0.896  0.187  0.046
linear_regression MIST           Base   T_eff             0.750  0.179  0.153
                                        log_g            -0.061  1.016  0.873
                                        radius            0.445  0.626  0.524
mlp               MIST           Base   T_eff             0.889  0.126  0.081
                                        log_g             0.158  0.652  0.371
                                        radius            0.746  0.328  0.189
random_forest     MIST           Base   T_eff             0.974  0.057  0.010
                                        log_g             0.656  0.371  0.068
                                        radius            0.896  0.186  0.034
xgboost           MIST           Base   T_eff             0.941  0.092  0.051
                                        log_g             0.447  0.508  0.284
                                        radius            0.833  0.255  0.141

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.001  0.980
                                        log_g             0.004  0.806
                                        radius            0.003  0.927
KNN               MIST           Base   T_eff             0.001  0.984
                                        log_g             0.003  0.867
                                        radius            0.002  0.954
linear_regression MIST           Base   T_eff             0.154  0.866
                                        log_g             0.800  0.298
                                        radius            0.476  0.672
mlp               MIST           Base   T_eff             0.042  0.943
                                        log_g             0.074  0.778
                                        radius            0.042  0.904
random_forest     MIST           Base   T_eff             0.001  0.987
                                        log_g             0.002  0.864
                                        radius            0.001  0.952
xgboost           MIST           Base   T_eff             0.016  0.970
                                        log_g             0.083  0.835
                                        radius            0.039  0.932

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.951
                                        log_g              5.668
                                        radius             2.834
KNN               MIST           Base   T_eff              0.926
                                        log_g              5.573
                                        radius             2.788
linear_regression MIST           Base   T_eff              0.716
                                        log_g              3.809
                                        radius             2.044
mlp               MIST           Base   T_eff              0.800
                                        log_g              3.821
                                        radius             1.997
random_forest     MIST           Base   T_eff              0.897
                                        log_g              5.581
                                        radius             2.792
xgboost           MIST           Base   T_eff              0.809
                                        log_g              4.885
                                        radius             2.580

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00256 / 90 : 0.00472 / 95 : 0.01174 / 99 : 0.40476
                                        log_g              75 : 0.00825 / 90 : 0.01716 / 95 : 0.03649 / 99 : 3.09545
                                        radius             75 : 0.00541 / 90 : 0.01099 / 95 : 0.02123 / 99 : 1.55013
KNN               MIST           Base   T_eff               75 : 0.00325 / 90 : 0.01865 / 95 : 0.09229 / 99 : 0.3282
                                        log_g               75 : 0.01024 / 90 : 0.0903 / 95 : 0.54511 / 99 : 1.97665
                                        radius             75 : 0.00734 / 90 : 0.04884 / 95 : 0.27305 / 99 : 0.98907
linear_regression MIST           Base   T_eff              75 : 0.21036 / 90 : 0.25684 / 95 : 0.30189 / 99 : 0.43765
                                        log_g              75 : 1.12403 / 90 : 1.61361 / 95 : 1.86763 / 99 : 2.26534
                                        radius              75 : 0.70451 / 90 : 1.01007 / 95 : 1.20991 / 99 : 1.4882
mlp               MIST           Base   T_eff              75 : 0.10075 / 90 : 0.22594 / 95 : 0.30755 / 99 : 0.42108
                                        log_g               75 : 0.60583 / 90 : 1.2465 / 95 : 1.51557 / 99 : 2.08746
                                        radius              75 : 0.30629 / 90 : 0.62338 / 95 : 0.76159 / 99 : 1.0468
random_forest     MIST           Base   T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                        log_g              75 : 0.00525 / 90 : 0.01949 / 95 : 0.14109 / 99 : 2.20116
                                        radius              75 : 0.00317 / 90 : 0.01073 / 95 : 0.0708 / 99 : 1.10175
xgboost           MIST           Base   T_eff              75 : 0.06239 / 90 : 0.15626 / 95 : 0.22213 / 99 : 0.34633
                                        log_g              75 : 0.37504 / 90 : 0.88757 / 95 : 1.18684 / 99 : 1.72542
                                        radius             75 : 0.18636 / 90 : 0.44548 / 95 : 0.59782 / 99 : 0.86036

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        log_g              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        log_g               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        log_g               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        log_g             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        log_g             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        log_g              17.973
                                        radius             17.973

Results for the phase category with a value of 2.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892
KNN               MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892
linear_regression MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892
mlp               MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892
random_forest     MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892
xgboost           MIST           Base   T_eff              3.428 - 4.711
                                        log_g             -0.296 - 4.408
                                        radius             0.092 - 2.892

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.959  0.064  0.024
                                        log_g             0.108  0.860  0.352
                                        radius            0.233  0.430  0.176
KNN               MIST           Base   T_eff             0.984  0.041  0.017
                                        log_g             0.594  0.580  0.249
                                        radius            0.651  0.290  0.124
linear_regression MIST           Base   T_eff             0.781  0.148  0.119
                                        log_g             0.225  1.049  0.794
                                        radius            0.305  0.583  0.463
mlp               MIST           Base   T_eff             0.842  0.126  0.097
                                        log_g             0.325  0.748  0.583
                                        radius            0.421  0.373  0.292
random_forest     MIST           Base   T_eff             0.975  0.050  0.020
                                        log_g             0.387  0.713  0.302
                                        radius            0.473  0.357  0.151
xgboost           MIST           Base   T_eff             0.874  0.114  0.085
                                        log_g             0.415  0.703  0.528
                                        radius            0.496  0.352  0.264

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.003  0.979
                                        log_g             0.016  0.552
                                        radius            0.008  0.624
KNN               MIST           Base   T_eff             0.002  0.992
                                        log_g             0.010  0.775
                                        radius            0.005  0.812
linear_regression MIST           Base   T_eff             0.106  0.884
                                        log_g             0.576  0.474
                                        radius            0.365  0.567
mlp               MIST           Base   T_eff             0.077  0.918
                                        log_g             0.468  0.573
                                        radius            0.236  0.653
random_forest     MIST           Base   T_eff             0.002  0.987
                                        log_g             0.010  0.664
                                        radius            0.005  0.721
xgboost           MIST           Base   T_eff             0.065  0.936
                                        log_g             0.396  0.644
                                        radius            0.198  0.706

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.847
                                        log_g              4.585
                                        radius             2.292
KNN               MIST           Base   T_eff              0.713
                                        log_g              4.587
                                        radius             2.294
linear_regression MIST           Base   T_eff              0.631
                                        log_g              3.384
                                        radius             1.789
mlp               MIST           Base   T_eff              0.653
                                        log_g              3.644
                                        radius             1.819
random_forest     MIST           Base   T_eff              0.713
                                        log_g              4.547
                                        radius             2.273
xgboost           MIST           Base   T_eff              0.510
                                        log_g              3.733
                                        radius             1.868

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              75 : 0.00789 / 90 : 0.08242 / 95 : 0.13794 / 99 : 0.23584
                                        log_g               75 : 0.04488 / 90 : 1.5049 / 95 : 2.33617 / 99 : 3.46382
                                        radius             75 : 0.02253 / 90 : 0.75231 / 95 : 1.16764 / 99 : 1.73219
KNN               MIST           Base   T_eff               75 : 0.01087 / 90 : 0.05726 / 95 : 0.0917 / 99 : 0.16337
                                        log_g              75 : 0.15315 / 90 : 0.97793 / 95 : 1.47373 / 99 : 2.32148
                                        radius             75 : 0.07659 / 90 : 0.48896 / 95 : 0.73686 / 99 : 1.16087
linear_regression MIST           Base   T_eff              75 : 0.16587 / 90 : 0.22216 / 95 : 0.28347 / 99 : 0.42765
                                        log_g              75 : 1.18144 / 90 : 1.87284 / 95 : 2.23987 / 99 : 2.68814
                                        radius             75 : 0.66783 / 90 : 1.01223 / 95 : 1.19363 / 99 : 1.41452
mlp               MIST           Base   T_eff               75 : 0.1347 / 90 : 0.20956 / 95 : 0.26236 / 99 : 0.35663
                                        log_g                 75 : 0.84053 / 90 : 1.248 / 95 : 1.50641 / 99 : 2.0336
                                        radius              75 : 0.42069 / 90 : 0.6229 / 95 : 0.75123 / 99 : 1.00833
random_forest     MIST           Base   T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                        log_g              75 : 0.13861 / 90 : 1.23629 / 95 : 1.86362 / 99 : 2.86772
                                        radius              75 : 0.06932 / 90 : 0.61818 / 95 : 0.93156 / 99 : 1.4339
xgboost           MIST           Base   T_eff              75 : 0.11863 / 90 : 0.18832 / 95 : 0.24477 / 99 : 0.34599
                                        log_g              75 : 0.77119 / 90 : 1.17902 / 95 : 1.44884 / 99 : 2.02649
                                        radius             75 : 0.38554 / 90 : 0.58881 / 95 : 0.72605 / 99 : 1.01489

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        log_g              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        log_g               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        log_g               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        log_g             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        log_g             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        log_g              17.973
                                        radius             17.973

Results for the phase category with a value of 3.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129
KNN               MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129
linear_regression MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129
mlp               MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129
random_forest     MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129
xgboost           MIST           Base   T_eff              3.352 - 5.379
                                        log_g             -1.083 - 6.259
                                        radius            -0.345 - 3.129

                                                            RVE   RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.881  0.106  0.030
                                        log_g             0.582  0.673  0.206
                                        radius            0.659  0.337  0.103
KNN               MIST           Base   T_eff             0.927  0.084  0.029
                                        log_g             0.798  0.470  0.182
                                        radius            0.835  0.235  0.091
linear_regression MIST           Base   T_eff             0.605  0.210  0.153
                                        log_g             0.292  1.524  1.290
                                        radius            0.398  0.835  0.726
mlp               MIST           Base   T_eff             0.762  0.165  0.115
                                        log_g             0.465  0.900  0.643
                                        radius            0.564  0.448  0.319
random_forest     MIST           Base   T_eff             0.918  0.089  0.027
                                        log_g             0.733  0.539  0.180
                                        radius            0.782  0.269  0.090
xgboost           MIST           Base   T_eff             0.838  0.140  0.097
                                        log_g             0.652  0.748  0.536
                                        radius            0.713  0.375  0.268

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff             0.003  0.941
                                        log_g             0.018  0.787
                                        radius            0.009  0.825
KNN               MIST           Base   T_eff             0.004  0.964
                                        log_g             0.025  0.894
                                        radius            0.012  0.914
linear_regression MIST           Base   T_eff             0.106  0.787
                                        log_g             1.006  0.566
                                        radius            0.585  0.649
mlp               MIST           Base   T_eff             0.075  0.878
                                        log_g             0.421  0.689
                                        radius            0.207  0.767
random_forest     MIST           Base   T_eff             0.003  0.959
                                        log_g             0.017  0.858
                                        radius            0.008  0.885
xgboost           MIST           Base   T_eff             0.063  0.916
                                        log_g             0.350  0.817
                                        radius            0.175  0.851

                                                          MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              0.931
                                        log_g              5.670
                                        radius             2.835
KNN               MIST           Base   T_eff              0.917
                                        log_g              5.672
                                        radius             2.837
linear_regression MIST           Base   T_eff              0.982
                                        log_g              4.013
                                        radius             2.005
mlp               MIST           Base   T_eff              0.977
                                        log_g              5.618
                                        radius             2.832
random_forest     MIST           Base   T_eff              0.933
                                        log_g              5.670
                                        radius             2.835
xgboost           MIST           Base   T_eff              0.874
                                        log_g              4.999
                                        radius             2.529

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff               75 : 0.00987 / 90 : 0.05367 / 95 : 0.15861 / 99 : 0.6234
                                        log_g              75 : 0.04773 / 90 : 0.42951 / 95 : 1.37376 / 99 : 3.57439
                                        radius             75 : 0.02388 / 90 : 0.21487 / 95 : 0.68696 / 99 : 1.78702
KNN               MIST           Base   T_eff              75 : 0.01918 / 90 : 0.06825 / 95 : 0.14393 / 99 : 0.43934
                                        log_g              75 : 0.11996 / 90 : 0.53226 / 95 : 0.96503 / 99 : 2.24483
                                        radius             75 : 0.05998 / 90 : 0.26646 / 95 : 0.48254 / 99 : 1.12352
linear_regression MIST           Base   T_eff              75 : 0.21166 / 90 : 0.36121 / 95 : 0.45759 / 99 : 0.60611
                                        log_g                75 : 1.75528 / 90 : 2.6254 / 95 : 2.9712 / 99 : 3.41977
                                        radius              75 : 0.96961 / 90 : 1.4046 / 95 : 1.56771 / 99 : 1.78381
mlp               MIST           Base   T_eff               75 : 0.15645 / 90 : 0.2835 / 95 : 0.35727 / 99 : 0.54147
                                        log_g              75 : 0.92009 / 90 : 1.56746 / 95 : 1.96716 / 99 : 2.65433
                                        radius              75 : 0.4601 / 90 : 0.78299 / 95 : 0.97979 / 99 : 1.32053
random_forest     MIST           Base   T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                        log_g              75 : 0.07269 / 90 : 0.45574 / 95 : 1.06538 / 99 : 2.86521
                                        radius              75 : 0.03635 / 90 : 0.22815 / 95 : 0.5328 / 99 : 1.43515
xgboost           MIST           Base   T_eff               75 : 0.13011 / 90 : 0.24272 / 95 : 0.3206 / 99 : 0.43713
                                        log_g              75 : 0.78426 / 90 : 1.29351 / 95 : 1.59294 / 99 : 2.24504
                                        radius             75 : 0.39342 / 90 : 0.65163 / 95 : 0.80015 / 99 : 1.13247

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   T_eff              17.940
                                        log_g              17.940
                                        radius             17.940
KNN               MIST           Base   T_eff               6.346
                                        log_g               6.346
                                        radius              6.346
linear_regression MIST           Base   T_eff               1.106
                                        log_g               1.106
                                        radius              1.106
mlp               MIST           Base   T_eff             424.225
                                        log_g             424.225
                                        radius            424.225
random_forest     MIST           Base   T_eff             293.086
                                        log_g             293.086
                                        radius            293.086
xgboost           MIST           Base   T_eff              17.973
                                        log_g              17.973
                                        radius             17.973

## Getting the ranges for the values

In [9]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [11]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':('<', 3)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 6.2 - 10.3, Mean : 9.0993, Median : 9.2

log_Teff  : Range : 3.34 - 4.3013, Mean : 3.795, Median : 3.7533

log_g  : Range : -1.08 - 5.4331, Mean : 3.6429, Median : 4.1661

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 3.0, Mean : 1.3237, Median : 1.1896

log_R  : Range : -1.0 - 2.7813, Mean : 0.4164, Median : 0.2391

log_L  : Range : -3.33 - 4.02, Mean : 0.9675, Median : 1.3998

## Comparing each model's results to keep the best ones with MIST dataset

### Linear regression

#### T_eff parameter

In [4]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                       value range  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             3.345 - 5.379
                                 Base_old          T_eff             3.345 - 5.379
                                 mass_smaller_14   T_eff             3.345 - 4.634
                                 mass_smaller_3    T_eff             3.345 - 4.301
                                 mass_smaller_30   T_eff             3.345 - 5.354
                                 scale_power       T_eff             3.345 - 5.379
                                 scale_power_14    T_eff             3.345 - 4.634
                                 scale_quantile    T_eff             3.345 - 5.379
                                 scale_quantile_14 T_eff             3.345 - 4.634
                                 scale_robust      T_eff             3.345 - 5.379
                                 scale_robust_14   T_eff             3.345 - 4.634
                                 scale_standard    T_eff             3.345 - 5.379
                                 scale_standard_14 T_eff             3.345 - 4.634

                                                                       RVE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             0.736
                                 Base_old          T_eff             0.608
                                 mass_smaller_14   T_eff             0.679
                                 mass_smaller_3    T_eff             0.641
                                 mass_smaller_30   T_eff             0.719
                                 scale_power       T_eff             0.774
                                 scale_power_14    T_eff             0.706
                                 scale_quantile    T_eff             0.766
                                 scale_quantile_14 T_eff             0.697
                                 scale_robust      T_eff             0.736
                                 scale_robust_14   T_eff             0.679
                                 scale_standard    T_eff             0.736
                                 scale_standard_14 T_eff             0.679

                                                                        RMSE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff              8.743%
                                 Base_old          T_eff             10.714%
                                 mass_smaller_14   T_eff             12.547%
                                 mass_smaller_3    T_eff             11.503%
                                 mass_smaller_30   T_eff               8.38%
                                 scale_power       T_eff               8.08%
                                 scale_power_14    T_eff             12.002%
                                 scale_quantile    T_eff              8.216%
                                 scale_quantile_14 T_eff             12.191%
                                 scale_robust      T_eff              8.743%
                                 scale_robust_14   T_eff             12.547%
                                 scale_standard    T_eff              8.743%
                                 scale_standard_14 T_eff             12.547%

                                                                        MAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             7.068%
                                 Base_old          T_eff             8.958%
                                 mass_smaller_14   T_eff             9.989%
                                 mass_smaller_3    T_eff             9.481%
                                 mass_smaller_30   T_eff             6.607%
                                 scale_power       T_eff             6.191%
                                 scale_power_14    T_eff              9.46%
                                 scale_quantile    T_eff             6.306%
                                 scale_quantile_14 T_eff             9.665%
                                 scale_robust      T_eff             7.068%
                                 scale_robust_14   T_eff             9.989%
                                 scale_standard    T_eff             7.068%
                                 scale_standard_14 T_eff             9.989%

                                                                      MedAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             6.468%
                                 Base_old          T_eff              8.51%
                                 mass_smaller_14   T_eff             9.011%
                                 mass_smaller_3    T_eff             8.568%
                                 mass_smaller_30   T_eff             5.826%
                                 scale_power       T_eff             5.401%
                                 scale_power_14    T_eff             8.605%
                                 scale_quantile    T_eff             5.444%
                                 scale_quantile_14 T_eff             8.863%
                                 scale_robust      T_eff             6.468%
                                 scale_robust_14   T_eff             9.011%
                                 scale_standard    T_eff             6.468%
                                 scale_standard_14 T_eff             9.011%

                                                                      CORR  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             0.858
                                 Base_old          T_eff             0.780
                                 mass_smaller_14   T_eff             0.824
                                 mass_smaller_3    T_eff             0.801
                                 mass_smaller_30   T_eff             0.848
                                 scale_power       T_eff             0.880
                                 scale_power_14    T_eff             0.840
                                 scale_quantile    T_eff             0.875
                                 scale_quantile_14 T_eff             0.835
                                 scale_robust      T_eff             0.858
                                 scale_robust_14   T_eff             0.824
                                 scale_standard    T_eff             0.858
                                 scale_standard_14 T_eff             0.824

                                                                      MAX_ER  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff             48.277%
                                 Base_old          T_eff             54.888%
                                 mass_smaller_14   T_eff             59.568%
                                 mass_smaller_3    T_eff             41.451%
                                 mass_smaller_30   T_eff             47.294%
                                 scale_power       T_eff              46.38%
                                 scale_power_14    T_eff             51.315%
                                 scale_quantile    T_eff             45.022%
                                 scale_quantile_14 T_eff             50.712%
                                 scale_robust      T_eff             48.277%
                                 scale_robust_14   T_eff             59.568%
                                 scale_standard    T_eff             48.277%
                                 scale_standard_14 T_eff             59.568%

                                                                                                                   Percentiles  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff               75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 Base_old          T_eff             75 : 13.857% / 90 : 16.661% / 95 : 17.885% / 99 : 22.314%
                                 mass_smaller_14   T_eff             75 : 14.028% / 90 : 18.219% / 95 : 22.192% / 99 : 38.921%
                                 mass_smaller_3    T_eff             75 : 13.911% / 90 : 18.089% / 95 : 20.721% / 99 : 28.761%
                                 mass_smaller_30   T_eff               75 : 9.278% / 90 : 12.23% / 95 : 15.302% / 99 : 26.623%
                                 scale_power       T_eff              75 : 8.004% / 90 : 11.298% / 95 : 16.575% / 99 : 26.884%
                                 scale_power_14    T_eff             75 : 12.492% / 90 : 16.543% / 95 : 22.849% / 99 : 39.471%
                                 scale_quantile    T_eff                75 : 8.102% / 90 : 11.851% / 95 : 16.83% / 99 : 27.13%
                                 scale_quantile_14 T_eff             75 : 12.661% / 90 : 17.013% / 95 : 23.169% / 99 : 39.536%
                                 scale_robust      T_eff               75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 scale_robust_14   T_eff             75 : 14.028% / 90 : 18.219% / 95 : 22.192% / 99 : 38.921%
                                 scale_standard    T_eff               75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 scale_standard_14 T_eff             75 : 14.028% / 90 : 18.219% / 95 : 22.192% / 99 : 38.921%

                                                                       time
model             physical_model filter            output_parameter
linear_regression MIST           Base              T_eff              1.106
                                 Base_old          T_eff              1.301
                                 mass_smaller_14   T_eff              0.530
                                 mass_smaller_3    T_eff              0.314
                                 mass_smaller_30   T_eff              0.574
                                 scale_power       T_eff             10.220
                                 scale_power_14    T_eff              8.118
                                 scale_quantile    T_eff              2.282
                                 scale_quantile_14 T_eff              1.850
                                 scale_robust      T_eff              1.024
                                 scale_robust_14   T_eff              0.912
                                 scale_standard    T_eff              0.924
                                 scale_standard_14 T_eff              0.692

Aucun modèle n'est vraiment très performant. scale_power donne les meilleurs résultats => MAX_ER, RMSE et percentiles dans les plus bas

#### log_g parameter

In [5]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                        value range  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             -1.083 - 6.259
                                 Base_old          log_g             -1.145 - 6.259
                                 mass_smaller_14   log_g             -1.083 - 5.433
                                 mass_smaller_3    log_g             -1.075 - 5.433
                                 mass_smaller_30   log_g             -1.075 - 6.243
                                 scale_power       log_g             -1.083 - 6.259
                                 scale_power_14    log_g             -1.083 - 5.433
                                 scale_quantile    log_g             -1.083 - 6.259
                                 scale_quantile_14 log_g             -1.083 - 5.433
                                 scale_robust      log_g             -1.083 - 6.259
                                 scale_robust_14   log_g             -1.083 - 5.433
                                 scale_standard    log_g             -1.083 - 6.259
                                 scale_standard_14 log_g             -1.083 - 5.433

                                                                       RVE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             0.121
                                 Base_old          log_g             0.124
                                 mass_smaller_14   log_g             0.264
                                 mass_smaller_3    log_g             0.354
                                 mass_smaller_30   log_g             0.195
                                 scale_power       log_g             0.411
                                 scale_power_14    log_g             0.418
                                 scale_quantile    log_g             0.405
                                 scale_quantile_14 log_g             0.399
                                 scale_robust      log_g             0.121
                                 scale_robust_14   log_g             0.264
                                 scale_standard    log_g             0.121
                                 scale_standard_14 log_g             0.264

                                                                        RMSE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             15.524%
                                 Base_old          log_g             24.079%
                                 mass_smaller_14   log_g             16.284%
                                 mass_smaller_3    log_g             15.663%
                                 mass_smaller_30   log_g              15.04%
                                 scale_power       log_g             12.707%
                                 scale_power_14    log_g             14.477%
                                 scale_quantile    log_g             12.773%
                                 scale_quantile_14 log_g             14.712%
                                 scale_robust      log_g             15.524%
                                 scale_robust_14   log_g             16.284%
                                 scale_standard    log_g             15.524%
                                 scale_standard_14 log_g             16.284%

                                                                         MAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             12.699%
                                 Base_old          log_g              20.89%
                                 mass_smaller_14   log_g             13.147%
                                 mass_smaller_3    log_g             12.543%
                                 mass_smaller_30   log_g             12.064%
                                 scale_power       log_g             10.177%
                                 scale_power_14    log_g             11.695%
                                 scale_quantile    log_g             10.215%
                                 scale_quantile_14 log_g              11.89%
                                 scale_robust      log_g             12.699%
                                 scale_robust_14   log_g             13.147%
                                 scale_standard    log_g             12.699%
                                 scale_standard_14 log_g             13.147%

                                                                       MedAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             10.869%
                                 Base_old          log_g             19.454%
                                 mass_smaller_14   log_g             10.842%
                                 mass_smaller_3    log_g             11.363%
                                 mass_smaller_30   log_g               9.76%
                                 scale_power       log_g              9.067%
                                 scale_power_14    log_g             10.814%
                                 scale_quantile    log_g              9.298%
                                 scale_quantile_14 log_g             11.142%
                                 scale_robust      log_g             10.869%
                                 scale_robust_14   log_g             10.842%
                                 scale_standard    log_g             10.869%
                                 scale_standard_14 log_g             10.842%

                                                                      CORR  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             0.349
                                 Base_old          log_g             0.352
                                 mass_smaller_14   log_g             0.514
                                 mass_smaller_3    log_g             0.595
                                 mass_smaller_30   log_g             0.441
                                 scale_power       log_g             0.641
                                 scale_power_14    log_g             0.647
                                 scale_quantile    log_g             0.637
                                 scale_quantile_14 log_g             0.632
                                 scale_robust      log_g             0.349
                                 scale_robust_14   log_g             0.514
                                 scale_standard    log_g             0.349
                                 scale_standard_14 log_g             0.514

                                                                      MAX_ER  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             54.654%
                                 Base_old          log_g             59.258%
                                 mass_smaller_14   log_g             67.305%
                                 mass_smaller_3    log_g             77.473%
                                 mass_smaller_30   log_g              56.38%
                                 scale_power       log_g             63.136%
                                 scale_power_14    log_g             73.891%
                                 scale_quantile    log_g             66.984%
                                 scale_quantile_14 log_g             77.549%
                                 scale_robust      log_g             54.654%
                                 scale_robust_14   log_g             67.305%
                                 scale_standard    log_g             54.654%
                                 scale_standard_14 log_g             67.305%

                                                                                                                   Percentiles  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g             75 : 16.932% / 90 : 25.249% / 95 : 30.511% / 99 : 41.111%
                                 Base_old          log_g             75 : 30.153% / 90 : 36.717% / 95 : 41.184% / 99 : 50.179%
                                 mass_smaller_14   log_g             75 : 18.813% / 90 : 26.853% / 95 : 31.578% / 99 : 41.952%
                                 mass_smaller_3    log_g               75 : 16.26% / 90 : 22.683% / 95 : 31.174% / 99 : 47.61%
                                 mass_smaller_30   log_g             75 : 17.018% / 90 : 24.922% / 95 : 29.861% / 99 : 39.591%
                                 scale_power       log_g              75 : 13.159% / 90 : 20.09% / 95 : 25.591% / 99 : 35.715%
                                 scale_power_14    log_g             75 : 15.387% / 90 : 22.386% / 95 : 28.413% / 99 : 40.029%
                                 scale_quantile    log_g             75 : 13.245% / 90 : 19.779% / 95 : 25.378% / 99 : 36.568%
                                 scale_quantile_14 log_g             75 : 15.095% / 90 : 22.497% / 95 : 28.599% / 99 : 41.841%
                                 scale_robust      log_g             75 : 16.932% / 90 : 25.249% / 95 : 30.511% / 99 : 41.111%
                                 scale_robust_14   log_g             75 : 18.813% / 90 : 26.853% / 95 : 31.578% / 99 : 41.952%
                                 scale_standard    log_g             75 : 16.932% / 90 : 25.249% / 95 : 30.511% / 99 : 41.111%
                                 scale_standard_14 log_g             75 : 18.813% / 90 : 26.853% / 95 : 31.578% / 99 : 41.952%

                                                                       time
model             physical_model filter            output_parameter
linear_regression MIST           Base              log_g              1.106
                                 Base_old          log_g              1.301
                                 mass_smaller_14   log_g              0.530
                                 mass_smaller_3    log_g              0.314
                                 mass_smaller_30   log_g              0.574
                                 scale_power       log_g             10.220
                                 scale_power_14    log_g              8.118
                                 scale_quantile    log_g              2.282
                                 scale_quantile_14 log_g              1.850
                                 scale_robust      log_g              1.024
                                 scale_robust_14   log_g              0.912
                                 scale_standard    log_g              0.924
                                 scale_standard_14 log_g              0.692

Aucun modèle n'est vraiment très performant. scale_power donne les meilleurs résultats => MAX_ER, RMSE et percentiles dans les plus bas

#### Radius parameter

In [6]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                        value range  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            -0.997 - 3.129
                                 Base_old          radius            -0.997 - 3.129
                                 mass_smaller_14   radius            -0.997 - 3.082
                                 mass_smaller_3    radius            -0.997 - 2.781
                                 mass_smaller_30   radius             -0.997 - 3.13
                                 scale_power       radius            -0.997 - 3.129
                                 scale_power_14    radius            -0.997 - 3.082
                                 scale_quantile    radius            -0.997 - 3.129
                                 scale_quantile_14 radius            -0.997 - 3.082
                                 scale_robust      radius            -0.997 - 3.129
                                 scale_robust_14   radius            -0.997 - 3.082
                                 scale_standard    radius            -0.997 - 3.129
                                 scale_standard_14 radius            -0.997 - 3.082

                                                                       RVE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            0.199
                                 Base_old          radius            0.039
                                 mass_smaller_14   radius            0.314
                                 mass_smaller_3    radius            0.419
                                 mass_smaller_30   radius            0.246
                                 scale_power       radius            0.602
                                 scale_power_14    radius            0.543
                                 scale_quantile    radius            0.579
                                 scale_quantile_14 radius            0.520
                                 scale_robust      radius            0.199
                                 scale_robust_14   radius            0.314
                                 scale_standard    radius            0.199
                                 scale_standard_14 radius            0.314

                                                                        RMSE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            16.011%
                                 Base_old          radius            22.584%
                                 mass_smaller_14   radius            14.306%
                                 mass_smaller_3    radius            14.081%
                                 mass_smaller_30   radius            14.959%
                                 scale_power       radius            11.286%
                                 scale_power_14    radius            11.675%
                                 scale_quantile    radius            11.603%
                                 scale_quantile_14 radius            11.974%
                                 scale_robust      radius            16.011%
                                 scale_robust_14   radius            14.306%
                                 scale_standard    radius            16.011%
                                 scale_standard_14 radius            14.306%

                                                                         MAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            13.239%
                                 Base_old          radius            19.362%
                                 mass_smaller_14   radius            11.415%
                                 mass_smaller_3    radius            11.309%
                                 mass_smaller_30   radius            11.945%
                                 scale_power       radius             9.059%
                                 scale_power_14    radius             9.456%
                                 scale_quantile    radius             9.299%
                                 scale_quantile_14 radius             9.666%
                                 scale_robust      radius            13.239%
                                 scale_robust_14   radius            11.415%
                                 scale_standard    radius            13.239%
                                 scale_standard_14 radius            11.415%

                                                                       MedAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            11.477%
                                 Base_old          radius            18.028%
                                 mass_smaller_14   radius             9.413%
                                 mass_smaller_3    radius             9.905%
                                 mass_smaller_30   radius              9.72%
                                 scale_power       radius             8.273%
                                 scale_power_14    radius             8.714%
                                 scale_quantile    radius             8.295%
                                 scale_quantile_14 radius             8.979%
                                 scale_robust      radius            11.477%
                                 scale_robust_14   radius             9.413%
                                 scale_standard    radius            11.477%
                                 scale_standard_14 radius             9.413%

                                                                      CORR  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            0.446
                                 Base_old          radius            0.196
                                 mass_smaller_14   radius            0.560
                                 mass_smaller_3    radius            0.648
                                 mass_smaller_30   radius            0.496
                                 scale_power       radius            0.776
                                 scale_power_14    radius            0.737
                                 scale_quantile    radius            0.761
                                 scale_quantile_14 radius            0.721
                                 scale_robust      radius            0.446
                                 scale_robust_14   radius            0.560
                                 scale_standard    radius            0.446
                                 scale_standard_14 radius            0.560

                                                                      MAX_ER  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius             49.52%
                                 Base_old          radius            62.794%
                                 mass_smaller_14   radius             52.65%
                                 mass_smaller_3    radius            67.665%
                                 mass_smaller_30   radius             48.28%
                                 scale_power       radius            57.275%
                                 scale_power_14    radius            59.504%
                                 scale_quantile    radius            61.943%
                                 scale_quantile_14 radius            63.498%
                                 scale_robust      radius             49.52%
                                 scale_robust_14   radius             52.65%
                                 scale_standard    radius             49.52%
                                 scale_standard_14 radius             52.65%

                                                                                                                   Percentiles  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius              75 : 17.837% / 90 : 26.55% / 95 : 31.48% / 99 : 38.856%
                                 Base_old          radius            75 : 27.967% / 90 : 33.079% / 95 : 39.945% / 99 : 51.635%
                                 mass_smaller_14   radius            75 : 16.966% / 90 : 24.061% / 95 : 27.979% / 99 : 35.514%
                                 mass_smaller_3    radius             75 : 14.844% / 90 : 21.048% / 95 : 27.866% / 99 : 41.81%
                                 mass_smaller_30   radius            75 : 17.336% / 90 : 25.542% / 95 : 30.102% / 99 : 36.986%
                                 scale_power       radius            75 : 11.683% / 90 : 17.719% / 95 : 22.492% / 99 : 31.794%
                                 scale_power_14    radius            75 : 12.504% / 90 : 18.048% / 95 : 22.751% / 99 : 32.211%
                                 scale_quantile    radius            75 : 12.219% / 90 : 17.741% / 95 : 23.004% / 99 : 33.154%
                                 scale_quantile_14 radius            75 : 12.194% / 90 : 18.477% / 95 : 23.458% / 99 : 34.039%
                                 scale_robust      radius              75 : 17.837% / 90 : 26.55% / 95 : 31.48% / 99 : 38.856%
                                 scale_robust_14   radius            75 : 16.966% / 90 : 24.061% / 95 : 27.979% / 99 : 35.514%
                                 scale_standard    radius              75 : 17.837% / 90 : 26.55% / 95 : 31.48% / 99 : 38.856%
                                 scale_standard_14 radius            75 : 16.966% / 90 : 24.061% / 95 : 27.979% / 99 : 35.514%

                                                                       time
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius             1.106
                                 Base_old          radius             1.301
                                 mass_smaller_14   radius             0.530
                                 mass_smaller_3    radius             0.314
                                 mass_smaller_30   radius             0.574
                                 scale_power       radius            10.220
                                 scale_power_14    radius             8.118
                                 scale_quantile    radius             2.282
                                 scale_quantile_14 radius             1.850
                                 scale_robust      radius             1.024
                                 scale_robust_14   radius             0.912
                                 scale_standard    radius             0.924
                                 scale_standard_14 radius             0.692

Aucun modèle n'est vraiment très performant. scale_power donne les meilleurs résultats => MAX_ER, RMSE et percentiles dans les plus bas

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour la masse et est l'un des deux meilleurs filtre pour le rayon.

linear_regression	MIST	scale_power	T_eff	3.345 - 5.379	0.774	8.08%	6.191%	5.401%	0.880	46.38%	75 : 8.004% / 90 : 11.298% / 95 : 16.575% / 99 : 26.884%	10.220

linear_regression	MIST	scale_power	log_g	-1.083 - 6.259	0.411	12.707%	10.177%	9.067%	0.641	63.136%	75 : 13.159% / 90 : 20.09% / 95 : 25.591% / 99 : 35.715%	10.220

linear_regression	MIST	scale_power	radius	-0.997 - 3.129	0.602	11.286%	9.059%	8.273%	0.776	57.275%	75 : 11.683% / 90 : 17.719% / 95 : 22.492% / 99 : 31.794%	10.220

### Decision tree

#### T_eff parameter

In [66]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                   value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             3.345 - 5.379
                             Base_old          T_eff             3.345 - 5.379
                             mass_smaller_14   T_eff             3.345 - 4.634
                             mass_smaller_3    T_eff             3.345 - 4.301
                             mass_smaller_30   T_eff             3.345 - 5.354
                             scale_power       T_eff             3.345 - 5.379
                             scale_power_14    T_eff             3.345 - 4.634
                             scale_quantile    T_eff             3.345 - 5.379
                             scale_quantile_14 T_eff             3.345 - 4.634
                             scale_robust      T_eff             3.345 - 5.379
                             scale_robust_14   T_eff             3.345 - 4.634
                             scale_standard    T_eff             3.345 - 5.379
                             scale_standard_14 T_eff             3.345 - 4.634

                                                                   RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             0.950
                             Base_old          T_eff             0.745
                             mass_smaller_14   T_eff             0.950
                             mass_smaller_3    T_eff             0.934
                             mass_smaller_30   T_eff             0.946
                             scale_power       T_eff             0.950
                             scale_power_14    T_eff             0.950
                             scale_quantile    T_eff             0.950
                             scale_quantile_14 T_eff             0.950
                             scale_robust      T_eff             0.950
                             scale_robust_14   T_eff             0.950
                             scale_standard    T_eff             0.950
                             scale_standard_14 T_eff             0.950

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             3.794%
                             Base_old          T_eff             8.635%
                             mass_smaller_14   T_eff             4.952%
                             mass_smaller_3    T_eff             4.942%
                             mass_smaller_30   T_eff             3.686%
                             scale_power       T_eff             3.794%
                             scale_power_14    T_eff              4.95%
                             scale_quantile    T_eff             3.787%
                             scale_quantile_14 T_eff             4.948%
                             scale_robust      T_eff             3.797%
                             scale_robust_14   T_eff             4.946%
                             scale_standard    T_eff             3.794%
                             scale_standard_14 T_eff             4.944%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             0.913%
                             Base_old          T_eff             3.588%
                             mass_smaller_14   T_eff             1.201%
                             mass_smaller_3    T_eff             1.735%
                             mass_smaller_30   T_eff             0.864%
                             scale_power       T_eff             0.914%
                             scale_power_14    T_eff               1.2%
                             scale_quantile    T_eff             0.912%
                             scale_quantile_14 T_eff             1.199%
                             scale_robust      T_eff             0.915%
                             scale_robust_14   T_eff             1.199%
                             scale_standard    T_eff             0.913%
                             scale_standard_14 T_eff             1.199%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             0.086%
                             Base_old          T_eff              0.11%
                             mass_smaller_14   T_eff             0.133%
                             mass_smaller_3    T_eff             0.159%
                             mass_smaller_30   T_eff             0.084%
                             scale_power       T_eff             0.086%
                             scale_power_14    T_eff             0.133%
                             scale_quantile    T_eff             0.086%
                             scale_quantile_14 T_eff             0.133%
                             scale_robust      T_eff             0.086%
                             scale_robust_14   T_eff             0.132%
                             scale_standard    T_eff             0.086%
                             scale_standard_14 T_eff             0.133%

                                                                  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             0.975
                             Base_old          T_eff             0.873
                             mass_smaller_14   T_eff             0.975
                             mass_smaller_3    T_eff             0.967
                             mass_smaller_30   T_eff             0.973
                             scale_power       T_eff             0.975
                             scale_power_14    T_eff             0.975
                             scale_quantile    T_eff             0.975
                             scale_quantile_14 T_eff             0.975
                             scale_robust      T_eff             0.975
                             scale_robust_14   T_eff             0.975
                             scale_standard    T_eff             0.975
                             scale_standard_14 T_eff             0.975

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             46.738%
                             Base_old          T_eff             47.443%
                             mass_smaller_14   T_eff             71.099%
                             mass_smaller_3    T_eff             46.744%
                             mass_smaller_30   T_eff             47.326%
                             scale_power       T_eff             46.738%
                             scale_power_14    T_eff             71.099%
                             scale_quantile    T_eff             46.738%
                             scale_quantile_14 T_eff             71.099%
                             scale_robust      T_eff             46.738%
                             scale_robust_14   T_eff             71.099%
                             scale_standard    T_eff             46.738%
                             scale_standard_14 T_eff             71.099%

                                                                                                             Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff               75 : 0.21% / 90 : 1.065% / 95 : 4.791% / 99 : 20.817%
                             Base_old          T_eff              75 : 1.0% / 90 : 15.503% / 95 : 24.471% / 99 : 32.345%
                             mass_smaller_14   T_eff              75 : 0.333% / 90 : 1.568% / 95 : 6.715% / 99 : 18.866%
                             mass_smaller_3    T_eff             75 : 0.493% / 90 : 5.316% / 95 : 12.028% / 99 : 23.336%
                             mass_smaller_30   T_eff              75 : 0.209% / 90 : 0.993% / 95 : 4.558% / 99 : 15.983%
                             scale_power       T_eff                75 : 0.21% / 90 : 1.07% / 95 : 4.793% / 99 : 20.817%
                             scale_power_14    T_eff              75 : 0.333% / 90 : 1.568% / 95 : 6.699% / 99 : 18.851%
                             scale_quantile    T_eff               75 : 0.21% / 90 : 1.061% / 95 : 4.781% / 99 : 20.764%
                             scale_quantile_14 T_eff              75 : 0.334% / 90 : 1.565% / 95 : 6.691% / 99 : 18.854%
                             scale_robust      T_eff                 75 : 0.21% / 90 : 1.072% / 95 : 4.8% / 99 : 20.848%
                             scale_robust_14   T_eff              75 : 0.333% / 90 : 1.565% / 95 : 6.691% / 99 : 18.834%
                             scale_standard    T_eff                75 : 0.21% / 90 : 1.065% / 95 : 4.781% / 99 : 20.85%
                             scale_standard_14 T_eff              75 : 0.333% / 90 : 1.567% / 95 : 6.691% / 99 : 18.851%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           Base              T_eff             17.940
                             Base_old          T_eff             37.199
                             mass_smaller_14   T_eff             13.361
                             mass_smaller_3    T_eff              7.840
                             mass_smaller_30   T_eff             16.161
                             scale_power       T_eff             26.015
                             scale_power_14    T_eff             20.366
                             scale_quantile    T_eff             17.085
                             scale_quantile_14 T_eff             14.207
                             scale_robust      T_eff             16.742
                             scale_robust_14   T_eff             14.829
                             scale_standard    T_eff             19.279
                             scale_standard_14 T_eff             12.893

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne les meilleurs résultats absolus

#### log_g parameter

In [67]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             -1.083 - 6.259
                             Base_old          log_g             -1.145 - 6.259
                             mass_smaller_14   log_g             -1.083 - 5.433
                             mass_smaller_3    log_g             -1.075 - 5.433
                             mass_smaller_30   log_g             -1.075 - 6.243
                             scale_power       log_g             -1.083 - 6.259
                             scale_power_14    log_g             -1.083 - 5.433
                             scale_quantile    log_g             -1.083 - 6.259
                             scale_quantile_14 log_g             -1.083 - 5.433
                             scale_robust      log_g             -1.083 - 6.259
                             scale_robust_14   log_g             -1.083 - 5.433
                             scale_standard    log_g             -1.083 - 6.259
                             scale_standard_14 log_g             -1.083 - 5.433

                                                                   RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             0.729
                             Base_old          log_g             0.245
                             mass_smaller_14   log_g             0.719
                             mass_smaller_3    log_g             0.614
                             mass_smaller_30   log_g             0.718
                             scale_power       log_g             0.728
                             scale_power_14    log_g             0.719
                             scale_quantile    log_g             0.729
                             scale_quantile_14 log_g             0.719
                             scale_robust      log_g             0.728
                             scale_robust_14   log_g             0.719
                             scale_standard    log_g             0.729
                             scale_standard_14 log_g             0.719

                                                                    RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g               8.63%
                             Base_old          log_g             22.353%
                             mass_smaller_14   log_g             10.065%
                             mass_smaller_3    log_g             12.115%
                             mass_smaller_30   log_g              8.899%
                             scale_power       log_g              8.634%
                             scale_power_14    log_g             10.066%
                             scale_quantile    log_g              8.621%
                             scale_quantile_14 log_g             10.058%
                             scale_robust      log_g              8.634%
                             scale_robust_14   log_g             10.063%
                             scale_standard    log_g              8.626%
                             scale_standard_14 log_g             10.059%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             2.373%
                             Base_old          log_g             9.848%
                             mass_smaller_14   log_g             2.791%
                             mass_smaller_3    log_g             3.991%
                             mass_smaller_30   log_g             2.452%
                             scale_power       log_g             2.373%
                             scale_power_14    log_g             2.792%
                             scale_quantile    log_g             2.369%
                             scale_quantile_14 log_g             2.789%
                             scale_robust      log_g             2.375%
                             scale_robust_14   log_g              2.79%
                             scale_standard    log_g             2.371%
                             scale_standard_14 log_g              2.79%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             0.104%
                             Base_old          log_g             0.217%
                             mass_smaller_14   log_g             0.116%
                             mass_smaller_3    log_g             0.108%
                             mass_smaller_30   log_g             0.101%
                             scale_power       log_g             0.104%
                             scale_power_14    log_g             0.116%
                             scale_quantile    log_g             0.104%
                             scale_quantile_14 log_g             0.116%
                             scale_robust      log_g             0.104%
                             scale_robust_14   log_g             0.116%
                             scale_standard    log_g             0.104%
                             scale_standard_14 log_g             0.116%

                                                                  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             0.865
                             Base_old          log_g             0.623
                             mass_smaller_14   log_g             0.860
                             mass_smaller_3    log_g             0.809
                             mass_smaller_30   log_g             0.860
                             scale_power       log_g             0.865
                             scale_power_14    log_g             0.860
                             scale_quantile    log_g             0.865
                             scale_quantile_14 log_g             0.861
                             scale_robust      log_g             0.865
                             scale_robust_14   log_g             0.860
                             scale_standard    log_g             0.865
                             scale_standard_14 log_g             0.861

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             77.218%
                             Base_old          log_g             76.579%
                             mass_smaller_14   log_g             87.374%
                             mass_smaller_3    log_g             87.151%
                             mass_smaller_30   log_g             77.366%
                             scale_power       log_g             77.383%
                             scale_power_14    log_g             87.374%
                             scale_quantile    log_g             77.383%
                             scale_quantile_14 log_g             87.374%
                             scale_robust      log_g             77.218%
                             scale_robust_14   log_g             87.374%
                             scale_standard    log_g             77.383%
                             scale_standard_14 log_g             87.374%

                                                                                                             Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g              75 : 0.262% / 90 : 2.885% / 95 : 18.53% / 99 : 45.586%
                             Base_old          log_g               75 : 2.58% / 90 : 51.6% / 95 : 61.969% / 99 : 69.555%
                             mass_smaller_14   log_g              75 : 0.298% / 90 : 3.57% / 95 : 22.071% / 99 : 52.518%
                             mass_smaller_3    log_g             75 : 0.367% / 90 : 13.758% / 95 : 30.44% / 99 : 57.269%
                             mass_smaller_30   log_g             75 : 0.259% / 90 : 2.976% / 95 : 19.468% / 99 : 46.557%
                             scale_power       log_g              75 : 0.262% / 90 : 2.885% / 95 : 18.541% / 99 : 45.59%
                             scale_power_14    log_g               75 : 0.298% / 90 : 3.567% / 95 : 22.1% / 99 : 52.507%
                             scale_quantile    log_g             75 : 0.262% / 90 : 2.858% / 95 : 18.504% / 99 : 45.527%
                             scale_quantile_14 log_g              75 : 0.298% / 90 : 3.551% / 95 : 22.06% / 99 : 52.526%
                             scale_robust      log_g             75 : 0.262% / 90 : 2.896% / 95 : 18.571% / 99 : 45.576%
                             scale_robust_14   log_g             75 : 0.298% / 90 : 3.552% / 95 : 22.071% / 99 : 52.507%
                             scale_standard    log_g              75 : 0.263% / 90 : 2.908% / 95 : 18.489% / 99 : 45.59%
                             scale_standard_14 log_g              75 : 0.298% / 90 : 3.582% / 95 : 22.06% / 99 : 52.507%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           Base              log_g             17.940
                             Base_old          log_g             37.199
                             mass_smaller_14   log_g             13.361
                             mass_smaller_3    log_g              7.840
                             mass_smaller_30   log_g             16.161
                             scale_power       log_g             26.015
                             scale_power_14    log_g             20.366
                             scale_quantile    log_g             17.085
                             scale_quantile_14 log_g             14.207
                             scale_robust      log_g             16.742
                             scale_robust_14   log_g             14.829
                             scale_standard    log_g             19.279
                             scale_standard_14 log_g             12.893

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne des résultats similaires en absolu

#### Radius parameter

In [68]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            -0.997 - 3.129
                             Base_old          radius            -0.997 - 3.129
                             mass_smaller_14   radius            -0.997 - 3.082
                             mass_smaller_3    radius            -0.997 - 2.781
                             mass_smaller_30   radius             -0.997 - 3.13
                             scale_power       radius            -0.997 - 3.129
                             scale_power_14    radius            -0.997 - 3.082
                             scale_quantile    radius            -0.997 - 3.129
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_robust      radius            -0.997 - 3.129
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_standard    radius            -0.997 - 3.129
                             scale_standard_14 radius            -0.997 - 3.082

                                                                   RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            0.816
                             Base_old          radius            0.242
                             mass_smaller_14   radius            0.783
                             mass_smaller_3    radius            0.681
                             mass_smaller_30   radius            0.790
                             scale_power       radius            0.815
                             scale_power_14    radius            0.783
                             scale_quantile    radius            0.816
                             scale_quantile_14 radius            0.784
                             scale_robust      radius            0.815
                             scale_robust_14   radius            0.784
                             scale_standard    radius            0.816
                             scale_standard_14 radius            0.784

                                                                    RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius             7.681%
                             Base_old          radius            20.054%
                             mass_smaller_14   radius             8.038%
                             mass_smaller_3    radius            10.433%
                             mass_smaller_30   radius             7.891%
                             scale_power       radius             7.684%
                             scale_power_14    radius             8.039%
                             scale_quantile    radius             7.672%
                             scale_quantile_14 radius             8.033%
                             scale_robust      radius             7.684%
                             scale_robust_14   radius             8.036%
                             scale_standard    radius             7.677%
                             scale_standard_14 radius             8.033%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            2.124%
                             Base_old          radius            8.841%
                             mass_smaller_14   radius            2.238%
                             mass_smaller_3    radius            3.445%
                             mass_smaller_30   radius            2.184%
                             scale_power       radius            2.124%
                             scale_power_14    radius            2.239%
                             scale_quantile    radius             2.12%
                             scale_quantile_14 radius            2.237%
                             scale_robust      radius            2.126%
                             scale_robust_14   radius            2.237%
                             scale_standard    radius            2.122%
                             scale_standard_14 radius            2.237%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            0.113%
                             Base_old          radius            0.203%
                             mass_smaller_14   radius            0.112%
                             mass_smaller_3    radius            0.112%
                             mass_smaller_30   radius             0.11%
                             scale_power       radius            0.113%
                             scale_power_14    radius            0.112%
                             scale_quantile    radius            0.113%
                             scale_quantile_14 radius            0.112%
                             scale_robust      radius            0.113%
                             scale_robust_14   radius            0.112%
                             scale_standard    radius            0.113%
                             scale_standard_14 radius            0.112%

                                                                  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            0.908
                             Base_old          radius            0.621
                             mass_smaller_14   radius            0.892
                             mass_smaller_3    radius            0.842
                             mass_smaller_30   radius            0.896
                             scale_power       radius            0.908
                             scale_power_14    radius            0.892
                             scale_quantile    radius            0.908
                             scale_quantile_14 radius            0.892
                             scale_robust      radius            0.908
                             scale_robust_14   radius            0.892
                             scale_standard    radius            0.908
                             scale_standard_14 radius            0.892

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            68.704%
                             Base_old          radius            68.688%
                             mass_smaller_14   radius            69.781%
                             mass_smaller_3    radius            75.077%
                             mass_smaller_30   radius            68.616%
                             scale_power       radius            68.844%
                             scale_power_14    radius            69.781%
                             scale_quantile    radius            68.844%
                             scale_quantile_14 radius            69.781%
                             scale_robust      radius            68.704%
                             scale_robust_14   radius            69.781%
                             scale_standard    radius            68.844%
                             scale_standard_14 radius            69.781%

                                                                                                              Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius             75 : 0.249% / 90 : 2.572% / 95 : 16.512% / 99 : 40.591%
                             Base_old          radius             75 : 2.323% / 90 : 46.29% / 95 : 55.563% / 99 : 62.424%
                             mass_smaller_14   radius             75 : 0.247% / 90 : 2.852% / 95 : 17.627% / 99 : 41.945%
                             mass_smaller_3    radius            75 : 0.321% / 90 : 11.845% / 95 : 26.213% / 99 : 49.311%
                             mass_smaller_30   radius              75 : 0.241% / 90 : 2.641% / 95 : 17.27% / 99 : 41.278%
                             scale_power       radius              75 : 0.25% / 90 : 2.574% / 95 : 16.514% / 99 : 40.597%
                             scale_power_14    radius              75 : 0.246% / 90 : 2.849% / 95 : 17.65% / 99 : 41.941%
                             scale_quantile    radius              75 : 0.25% / 90 : 2.545% / 95 : 16.466% / 99 : 40.539%
                             scale_quantile_14 radius             75 : 0.247% / 90 : 2.837% / 95 : 17.618% / 99 : 41.952%
                             scale_robust      radius              75 : 0.25% / 90 : 2.579% / 95 : 16.543% / 99 : 40.584%
                             scale_robust_14   radius             75 : 0.247% / 90 : 2.837% / 95 : 17.629% / 99 : 41.941%
                             scale_standard    radius              75 : 0.25% / 90 : 2.589% / 95 : 16.456% / 99 : 40.599%
                             scale_standard_14 radius             75 : 0.247% / 90 : 2.861% / 95 : 17.619% / 99 : 41.941%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            17.940
                             Base_old          radius            37.199
                             mass_smaller_14   radius            13.361
                             mass_smaller_3    radius             7.840
                             mass_smaller_30   radius            16.161
                             scale_power       radius            26.015
                             scale_power_14    radius            20.366
                             scale_quantile    radius            17.085
                             scale_quantile_14 radius            14.207
                             scale_robust      radius            16.742
                             scale_robust_14   radius            14.829
                             scale_standard    radius            19.279
                             scale_standard_14 radius            12.893

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne des résultats similaires en absolu

#### Filtre choisi

Le filtre Base est choisi parce qu'il donne les meilleurs résultats pour les trois paramètres.

decision_tree	MIST	Base	T_eff	3.345 - 5.379	0.950	3.794%	0.913%	0.086%	0.975	46.738%	75 : 0.21% / 90 : 1.065% / 95 : 4.791% / 99 : 20.817%	17.940

decision_tree	MIST	Base	log_g	-1.083 - 6.259	0.729	8.63%	2.373%	0.104%	0.865	77.218%	75 : 0.262% / 90 : 2.885% / 95 : 18.53% / 99 : 45.586%	17.940

decision_tree	MIST	Base	radius	-0.997 - 3.129	0.816	7.681%	2.124%	0.113%	0.908	68.704%	75 : 0.249% / 90 : 2.572% / 95 : 16.512% / 99 : 40.591%	17.940

### KNN

#### T_eff parameter

In [65]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff             3.345 - 5.379  0.967
                     Base_old          T_eff             3.345 - 5.379  0.869
                     mass_smaller_14   T_eff             3.345 - 4.634  0.974
                     mass_smaller_3    T_eff             3.345 - 4.301  0.969
                     mass_smaller_30   T_eff             3.345 - 5.354  0.970
                     scale_power       T_eff             3.345 - 5.379  0.977
                     scale_power_14    T_eff             3.345 - 4.634  0.977
                     scale_quantile    T_eff             3.345 - 5.379  0.977
                     scale_quantile_14 T_eff             3.345 - 4.634  0.977
                     scale_robust      T_eff             3.345 - 5.379  0.973
                     scale_robust_14   T_eff             3.345 - 4.634  0.976
                     scale_standard    T_eff             3.345 - 5.379  0.976
                     scale_standard_14 T_eff             3.345 - 4.634  0.977

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff             3.075%  0.915%
                     Base_old          T_eff             6.204%  2.922%
                     mass_smaller_14   T_eff             3.579%  0.979%
                     mass_smaller_3    T_eff             3.358%  1.287%
                     mass_smaller_30   T_eff              2.76%  0.757%
                     scale_power       T_eff             2.604%  0.686%
                     scale_power_14    T_eff             3.356%  0.889%
                     scale_quantile    T_eff             2.601%   0.69%
                     scale_quantile_14 T_eff             3.362%  0.898%
                     scale_robust      T_eff             2.796%  0.789%
                     scale_robust_14   T_eff             3.404%   0.92%
                     scale_standard    T_eff             2.641%  0.725%
                     scale_standard_14 T_eff             3.384%  0.914%

                                                          MedAE   CORR  \
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff             0.083%  0.984
                     Base_old          T_eff             0.224%  0.932
                     mass_smaller_14   T_eff              0.12%  0.987
                     mass_smaller_3    T_eff             0.184%  0.985
                     mass_smaller_30   T_eff             0.077%  0.985
                     scale_power       T_eff             0.079%  0.988
                     scale_power_14    T_eff             0.117%  0.988
                     scale_quantile    T_eff             0.083%  0.988
                     scale_quantile_14 T_eff             0.124%  0.988
                     scale_robust      T_eff             0.084%  0.986
                     scale_robust_14   T_eff             0.127%  0.988
                     scale_standard    T_eff              0.09%  0.988
                     scale_standard_14 T_eff              0.13%  0.988

                                                          MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff             45.544%
                     Base_old          T_eff             48.075%
                     mass_smaller_14   T_eff             68.688%
                     mass_smaller_3    T_eff             43.594%
                     mass_smaller_30   T_eff             45.778%
                     scale_power       T_eff             45.037%
                     scale_power_14    T_eff             71.082%
                     scale_quantile    T_eff             45.011%
                     scale_quantile_14 T_eff             71.016%
                     scale_robust      T_eff             45.235%
                     scale_robust_14   T_eff              69.57%
                     scale_standard    T_eff             45.125%
                     scale_standard_14 T_eff             71.016%

                                                                                                     Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff              75 : 0.306% / 90 : 2.294% / 95 : 4.907% / 99 : 15.408%
                     Base_old          T_eff             75 : 3.628% / 90 : 9.181% / 95 : 14.552% / 99 : 27.155%
                     mass_smaller_14   T_eff              75 : 0.367% / 90 : 2.173% / 95 : 5.197% / 99 : 13.658%
                     mass_smaller_3    T_eff                75 : 0.59% / 90 : 4.22% / 95 : 7.676% / 99 : 14.965%
                     mass_smaller_30   T_eff              75 : 0.254% / 90 : 1.709% / 95 : 3.969% / 99 : 12.593%
                     scale_power       T_eff              75 : 0.206% / 90 : 1.377% / 95 : 3.596% / 99 : 12.032%
                     scale_power_14    T_eff              75 : 0.312% / 90 : 1.898% / 95 : 4.769% / 99 : 12.523%
                     scale_quantile    T_eff               75 : 0.216% / 90 : 1.38% / 95 : 3.595% / 99 : 12.027%
                     scale_quantile_14 T_eff              75 : 0.333% / 90 : 1.914% / 95 : 4.769% / 99 : 12.545%
                     scale_robust      T_eff              75 : 0.267% / 90 : 1.795% / 95 : 4.208% / 99 : 13.652%
                     scale_robust_14   T_eff              75 : 0.366% / 90 : 1.951% / 95 : 4.853% / 99 : 12.675%
                     scale_standard    T_eff              75 : 0.257% / 90 : 1.528% / 95 : 3.768% / 99 : 12.235%
                     scale_standard_14 T_eff              75 : 0.367% / 90 : 1.927% / 95 : 4.808% / 99 : 12.609%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           Base              T_eff              6.346
                     Base_old          T_eff             13.920
                     mass_smaller_14   T_eff              4.210
                     mass_smaller_3    T_eff              2.542
                     mass_smaller_30   T_eff              5.295
                     scale_power       T_eff             16.104
                     scale_power_14    T_eff             13.037
                     scale_quantile    T_eff              7.903
                     scale_quantile_14 T_eff              5.660
                     scale_robust      T_eff              6.295
                     scale_robust_14   T_eff              5.874
                     scale_standard    T_eff              7.123
                     scale_standard_14 T_eff              4.679

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne les meilleurs résultats absolus

In [23]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff             3.345 - 4.634  0.974
                     scale_standard_14 T_eff             3.345 - 4.634  0.977
                     scale_robust_14   T_eff             3.345 - 4.634  0.976
                     scale_quantile_14 T_eff             3.345 - 4.634  0.977
                     scale_power_14    T_eff             3.345 - 4.634  0.977

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff             3.579%  0.979%
                     scale_standard_14 T_eff             3.384%  0.914%
                     scale_robust_14   T_eff             3.404%   0.92%
                     scale_quantile_14 T_eff             3.362%  0.898%
                     scale_power_14    T_eff             3.356%  0.889%

                                                          MedAE   CORR  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff              0.12%  0.987
                     scale_standard_14 T_eff              0.13%  0.988
                     scale_robust_14   T_eff             0.127%  0.988
                     scale_quantile_14 T_eff             0.124%  0.988
                     scale_power_14    T_eff             0.117%  0.988

                                                          MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff             68.688%
                     scale_standard_14 T_eff             71.016%
                     scale_robust_14   T_eff              69.57%
                     scale_quantile_14 T_eff             71.016%
                     scale_power_14    T_eff             71.082%

                                                                                                    Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff             75 : 0.367% / 90 : 2.173% / 95 : 5.197% / 99 : 13.658%
                     scale_standard_14 T_eff             75 : 0.367% / 90 : 1.927% / 95 : 4.808% / 99 : 12.609%
                     scale_robust_14   T_eff             75 : 0.366% / 90 : 1.951% / 95 : 4.853% / 99 : 12.675%
                     scale_quantile_14 T_eff             75 : 0.333% / 90 : 1.914% / 95 : 4.769% / 99 : 12.545%
                     scale_power_14    T_eff             75 : 0.312% / 90 : 1.898% / 95 : 4.769% / 99 : 12.523%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   T_eff              4.210
                     scale_standard_14 T_eff              4.679
                     scale_robust_14   T_eff              5.874
                     scale_quantile_14 T_eff              5.660
                     scale_power_14    T_eff             13.037

Le scaling semble améliorer les résultats. Le meilleur scaling est le power scaling

#### log_g parameter

In [24]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
KNN   MIST           Base              log_g             -1.083 - 6.259
                     Base_old          log_g             -1.145 - 6.259
                     mass_smaller_14   log_g             -1.083 - 5.433
                     mass_smaller_3    log_g             -1.075 - 5.433
                     mass_smaller_30   log_g             -1.075 - 6.243
                     scale_power       log_g             -1.083 - 6.259
                     scale_power_14    log_g             -1.083 - 5.433
                     scale_quantile    log_g             -1.083 - 6.259
                     scale_quantile_14 log_g             -1.083 - 5.433
                     scale_robust      log_g             -1.083 - 6.259
                     scale_robust_14   log_g             -1.083 - 5.433
                     scale_standard    log_g             -1.083 - 6.259
                     scale_standard_14 log_g             -1.083 - 5.433

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
KNN   MIST           Base              log_g             0.859  0.456  0.150
                     Base_old          log_g             0.625  1.168  0.581
                     mass_smaller_14   log_g             0.867  0.451  0.139
                     mass_smaller_3    log_g             0.824  0.533  0.189
                     mass_smaller_30   log_g             0.862  0.455  0.143
                     scale_power       log_g             0.875  0.430  0.128
                     scale_power_14    log_g             0.870  0.445  0.133
                     scale_quantile    log_g             0.875  0.430  0.128
                     scale_quantile_14 log_g             0.871  0.445  0.133
                     scale_robust      log_g             0.869  0.440  0.137
                     scale_robust_14   log_g             0.870  0.446  0.134
                     scale_standard    log_g             0.874  0.432  0.130
                     scale_standard_14 log_g             0.870  0.446  0.134

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           Base              log_g             0.006  0.928   5.672
                     Base_old          log_g             0.038  0.794   5.668
                     mass_smaller_14   log_g             0.006  0.932   5.648
                     mass_smaller_3    log_g             0.006  0.908   5.670
                     mass_smaller_30   log_g             0.006  0.929   5.646
                     scale_power       log_g             0.005  0.936   5.672
                     scale_power_14    log_g             0.005  0.933   5.648
                     scale_quantile    log_g             0.005  0.936   5.668
                     scale_quantile_14 log_g             0.005  0.934   5.649
                     scale_robust      log_g             0.006  0.933   5.672
                     scale_robust_14   log_g             0.005  0.933   5.648
                     scale_standard    log_g             0.005  0.935   5.672
                     scale_standard_14 log_g             0.005  0.933   5.648

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           Base              log_g              75 : 0.03179 / 90 : 0.46491 / 95 : 1.02214 / 99 : 2.17013
                     Base_old          log_g              75 : 0.83595 / 90 : 1.91355 / 95 : 2.98864 / 99 : 4.62544
                     mass_smaller_14   log_g              75 : 0.02289 / 90 : 0.38602 / 95 : 0.99507 / 99 : 2.15199
                     mass_smaller_3    log_g                75 : 0.03151 / 90 : 0.712 / 95 : 1.28673 / 99 : 2.31137
                     mass_smaller_30   log_g              75 : 0.02507 / 90 : 0.41099 / 95 : 1.00051 / 99 : 2.17124
                     scale_power       log_g              75 : 0.01781 / 90 : 0.31869 / 95 : 0.91695 / 99 : 2.10641
                     scale_power_14    log_g              75 : 0.01778 / 90 : 0.34524 / 95 : 0.97306 / 99 : 2.13984
                     scale_quantile    log_g              75 : 0.01948 / 90 : 0.31931 / 95 : 0.91859 / 99 : 2.10542
                     scale_quantile_14 log_g              75 : 0.01943 / 90 : 0.34454 / 95 : 0.97233 / 99 : 2.14109
                     scale_robust      log_g               75 : 0.02316 / 90 : 0.38825 / 95 : 0.95651 / 99 : 2.1267
                     scale_robust_14   log_g                 75 : 0.02 / 90 : 0.35202 / 95 : 0.97579 / 99 : 2.14268
                     scale_standard    log_g              75 : 0.01984 / 90 : 0.33842 / 95 : 0.92131 / 99 : 2.10666
                     scale_standard_14 log_g                75 : 0.01934 / 90 : 0.34758 / 95 : 0.9731 / 99 : 2.1414

                                                           time
model physical_model filter            output_parameter
KNN   MIST           Base              log_g              6.346
                     Base_old          log_g             13.920
                     mass_smaller_14   log_g              4.210
                     mass_smaller_3    log_g              2.542
                     mass_smaller_30   log_g              5.295
                     scale_power       log_g             16.104
                     scale_power_14    log_g             13.037
                     scale_quantile    log_g              7.903
                     scale_quantile_14 log_g              5.660
                     scale_robust      log_g              6.295
                     scale_robust_14   log_g              5.874
                     scale_standard    log_g              7.123
                     scale_standard_14 log_g              4.679

Le filtre Base et ses scaling donne les meilleurs résultats, mass_smaller_14 n'est pas loin derrière

In [26]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   MIST           Base           log_g             -1.083 - 6.259  0.859
                     scale_standard log_g             -1.083 - 6.259  0.874
                     scale_robust   log_g             -1.083 - 6.259  0.869
                     scale_quantile log_g             -1.083 - 6.259  0.875
                     scale_power    log_g             -1.083 - 6.259  0.875

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
KNN   MIST           Base           log_g             6.216%  2.049%  0.085%
                     scale_standard log_g             5.884%  1.774%  0.072%
                     scale_robust   log_g             5.998%  1.869%  0.076%
                     scale_quantile log_g             5.861%  1.746%  0.073%
                     scale_power    log_g             5.863%  1.739%  0.066%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
KNN   MIST           Base           log_g             0.928  77.248%
                     scale_standard log_g             0.935  77.248%
                     scale_robust   log_g             0.933  77.248%
                     scale_quantile log_g             0.936  77.199%
                     scale_power    log_g             0.936  77.248%

                                                                                                  Percentiles  \
model physical_model filter         output_parameter
KNN   MIST           Base           log_g             75 : 0.433% / 90 : 6.332% / 95 : 13.921% / 99 : 29.556%
                     scale_standard log_g              75 : 0.27% / 90 : 4.609% / 95 : 12.548% / 99 : 28.692%
                     scale_robust   log_g             75 : 0.315% / 90 : 5.288% / 95 : 13.027% / 99 : 28.965%
                     scale_quantile log_g             75 : 0.265% / 90 : 4.349% / 95 : 12.511% / 99 : 28.675%
                     scale_power    log_g              75 : 0.243% / 90 : 4.34% / 95 : 12.489% / 99 : 28.689%

                                                        time
model physical_model filter         output_parameter
KNN   MIST           Base           log_g              6.346
                     scale_standard log_g              7.123
                     scale_robust   log_g              6.295
                     scale_quantile log_g              7.903
                     scale_power    log_g             16.104

Le filtre scale_quantile donne les meilleurs résultats

#### Radius parameter

In [28]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            -0.997 - 3.129
                     Base_old          radius            -0.997 - 3.129
                     mass_smaller_14   radius            -0.997 - 3.082
                     mass_smaller_3    radius            -0.997 - 2.781
                     mass_smaller_30   radius             -0.997 - 3.13
                     scale_power       radius            -0.997 - 3.129
                     scale_power_14    radius            -0.997 - 3.082
                     scale_quantile    radius            -0.997 - 3.129
                     scale_quantile_14 radius            -0.997 - 3.082
                     scale_robust      radius            -0.997 - 3.129
                     scale_robust_14   radius            -0.997 - 3.082
                     scale_standard    radius            -0.997 - 3.129
                     scale_standard_14 radius            -0.997 - 3.082

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            0.904  0.228  0.076
                     Base_old          radius            0.623  0.584  0.291
                     mass_smaller_14   radius            0.897  0.226  0.070
                     mass_smaller_3    radius            0.854  0.266  0.095
                     mass_smaller_30   radius            0.898  0.228  0.072
                     scale_power       radius            0.915  0.215  0.065
                     scale_power_14    radius            0.900  0.223  0.067
                     scale_quantile    radius            0.915  0.215  0.065
                     scale_quantile_14 radius            0.900  0.222  0.067
                     scale_robust      radius            0.911  0.220  0.069
                     scale_robust_14   radius            0.900  0.223  0.068
                     scale_standard    radius            0.914  0.216  0.066
                     scale_standard_14 radius            0.900  0.223  0.068

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            0.004  0.951   2.837
                     Base_old          radius            0.020  0.793   2.833
                     mass_smaller_14   radius            0.004  0.948   2.827
                     mass_smaller_3    radius            0.004  0.925   2.836
                     mass_smaller_30   radius            0.004  0.948   2.824
                     scale_power       radius            0.003  0.957   2.837
                     scale_power_14    radius            0.003  0.949   2.827
                     scale_quantile    radius            0.004  0.957   2.833
                     scale_quantile_14 radius            0.004  0.949   2.823
                     scale_robust      radius            0.004  0.955   2.837
                     scale_robust_14   radius            0.003  0.949   2.827
                     scale_standard    radius            0.004  0.956   2.837
                     scale_standard_14 radius            0.003  0.949   2.827

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius             75 : 0.01766 / 90 : 0.23258 / 95 : 0.51127 / 99 : 1.08571
                     Base_old          radius             75 : 0.41796 / 90 : 0.95684 / 95 : 1.49404 / 99 : 2.31101
                     mass_smaller_14   radius             75 : 0.01284 / 90 : 0.19301 / 95 : 0.49754 / 99 : 1.07606
                     mass_smaller_3    radius             75 : 0.01859 / 90 : 0.35601 / 95 : 0.64336 / 99 : 1.15575
                     mass_smaller_30   radius             75 : 0.01409 / 90 : 0.20559 / 95 : 0.50046 / 99 : 1.08596
                     scale_power       radius             75 : 0.01028 / 90 : 0.15945 / 95 : 0.45868 / 99 : 1.05358
                     scale_power_14    radius             75 : 0.01009 / 90 : 0.17263 / 95 : 0.48645 / 99 : 1.06995
                     scale_quantile    radius             75 : 0.01165 / 90 : 0.15979 / 95 : 0.45953 / 99 : 1.05296
                     scale_quantile_14 radius             75 : 0.01134 / 90 : 0.17227 / 95 : 0.48608 / 99 : 1.07047
                     scale_robust      radius              75 : 0.0131 / 90 : 0.19433 / 95 : 0.47853 / 99 : 1.06398
                     scale_robust_14   radius             75 : 0.01155 / 90 : 0.17602 / 95 : 0.48794 / 99 : 1.07148
                     scale_standard    radius             75 : 0.01169 / 90 : 0.16928 / 95 : 0.46101 / 99 : 1.05375
                     scale_standard_14 radius              75 : 0.01125 / 90 : 0.17379 / 95 : 0.48647 / 99 : 1.0707

                                                           time
model physical_model filter            output_parameter
KNN   MIST           Base              radius             6.346
                     Base_old          radius            13.920
                     mass_smaller_14   radius             4.210
                     mass_smaller_3    radius             2.542
                     mass_smaller_30   radius             5.295
                     scale_power       radius            16.104
                     scale_power_14    radius            13.037
                     scale_quantile    radius             7.903
                     scale_quantile_14 radius             5.660
                     scale_robust      radius             6.295
                     scale_robust_14   radius             5.874
                     scale_standard    radius             7.123
                     scale_standard_14 radius             4.679

les scaling de Base donne les meilleurs résultats

In [29]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   MIST           Base           radius            -0.997 - 3.129  0.904
                     scale_standard radius            -0.997 - 3.129  0.914
                     scale_robust   radius            -0.997 - 3.129  0.911
                     scale_quantile radius            -0.997 - 3.129  0.915
                     scale_power    radius            -0.997 - 3.129  0.915

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
KNN   MIST           Base           radius            5.534%  1.838%  0.092%
                     scale_standard radius            5.237%    1.6%  0.091%
                     scale_robust   radius            5.339%   1.68%  0.087%
                     scale_quantile radius            5.217%  1.575%   0.09%
                     scale_power    radius            5.218%  1.565%  0.084%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
KNN   MIST           Base           radius            0.951   68.75%
                     scale_standard radius            0.956   68.75%
                     scale_robust   radius            0.955   68.75%
                     scale_quantile radius            0.957  68.651%
                     scale_power    radius            0.957   68.75%

                                                                                                  Percentiles  \
model physical_model filter         output_parameter
KNN   MIST           Base           radius            75 : 0.428% / 90 : 5.636% / 95 : 12.389% / 99 : 26.309%
                     scale_standard radius            75 : 0.283% / 90 : 4.102% / 95 : 11.171% / 99 : 25.535%
                     scale_robust   radius            75 : 0.317% / 90 : 4.709% / 95 : 11.596% / 99 : 25.783%
                     scale_quantile radius            75 : 0.282% / 90 : 3.872% / 95 : 11.135% / 99 : 25.516%
                     scale_power    radius            75 : 0.249% / 90 : 3.864% / 95 : 11.115% / 99 : 25.531%

                                                        time
model physical_model filter         output_parameter
KNN   MIST           Base           radius             6.346
                     scale_standard radius             7.123
                     scale_robust   radius             6.295
                     scale_quantile radius             7.903
                     scale_power    radius            16.104

Le filtre scale_quantile est le meileur scaling

#### Filtre choisi

Le filtre scale_quantile est choisi parce qu'il donne des bons résultats pour la T_eff et les meilleurs résultats pour le log_g et le rayon.

KNN	MIST	scale_quantile	T_eff	3.345 - 5.379	0.977	2.601%	0.69%	0.083%	0.988	45.011%	75 : 0.216% / 90 : 1.38% / 95 : 3.595% / 99 : 12.027%	7.903

KNN	MIST	scale_quantile	log_g	-1.083 - 6.259	0.875	5.861%	1.746%	0.073%	0.936	77.199%	75 : 0.265% / 90 : 4.349% / 95 : 12.511% / 99 : 28.675%	7.903

KNN	MIST	scale_quantile	radius	-0.997 - 3.129	0.915	5.217%	1.575%	0.09%	0.957	68.651%	75 : 0.282% / 90 : 3.872% / 95 : 11.135% / 99 : 25.516%	7.903

### Random forest

#### T_eff parameter

In [32]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                   value range  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff             3.345 - 5.379
                             Base_old          T_eff             3.345 - 5.379
                             mass_smaller_14   T_eff             3.345 - 4.634
                             mass_smaller_3    T_eff             3.345 - 4.301
                             mass_smaller_30   T_eff             3.345 - 5.354
                             scale_power       T_eff             3.345 - 5.379
                             scale_power_14    T_eff             3.345 - 4.634
                             scale_quantile    T_eff             3.345 - 5.379
                             scale_quantile_14 T_eff             3.345 - 4.634
                             scale_robust      T_eff             3.345 - 5.379
                             scale_robust_14   T_eff             3.345 - 4.634
                             scale_standard    T_eff             3.345 - 5.379
                             scale_standard_14 T_eff             3.345 - 4.634

                                                                   RVE   RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff             0.967  0.063
                             Base_old          T_eff             0.841  0.139
                             mass_smaller_14   T_eff             0.967  0.052
                             mass_smaller_3    T_eff             0.957  0.038
                             mass_smaller_30   T_eff             0.964  0.060
                             scale_power       T_eff             0.967  0.063
                             scale_power_14    T_eff             0.967  0.052
                             scale_quantile    T_eff             0.967  0.063
                             scale_quantile_14 T_eff             0.967  0.052
                             scale_robust      T_eff             0.967  0.063
                             scale_robust_14   T_eff             0.967  0.052
                             scale_standard    T_eff             0.967  0.063
                             scale_standard_14 T_eff             0.967  0.052

                                                                   MAE  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff             0.016  0.001
                             Base_old          T_eff             0.066  0.005
                             mass_smaller_14   T_eff             0.013  0.001
                             mass_smaller_3    T_eff             0.014  0.001
                             mass_smaller_30   T_eff             0.015  0.001
                             scale_power       T_eff             0.016  0.001
                             scale_power_14    T_eff             0.013  0.001
                             scale_quantile    T_eff             0.016  0.001
                             scale_quantile_14 T_eff             0.013  0.001
                             scale_robust      T_eff             0.016  0.001
                             scale_robust_14   T_eff             0.013  0.001
                             scale_standard    T_eff             0.016  0.001
                             scale_standard_14 T_eff             0.013  0.001

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff             0.984
                             Base_old          T_eff             0.918
                             mass_smaller_14   T_eff             0.984
                             mass_smaller_3    T_eff             0.978
                             mass_smaller_30   T_eff             0.982
                             scale_power       T_eff             0.984
                             scale_power_14    T_eff             0.984
                             scale_quantile    T_eff             0.984
                             scale_quantile_14 T_eff             0.984
                             scale_robust      T_eff             0.984
                             scale_robust_14   T_eff             0.984
                             scale_standard    T_eff             0.984
                             scale_standard_14 T_eff             0.984

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff              0.933
                             Base_old          T_eff              0.929
                             mass_smaller_14   T_eff              0.889
                             mass_smaller_3    T_eff              0.430
                             mass_smaller_30   T_eff              0.914
                             scale_power       T_eff              0.931
                             scale_power_14    T_eff              0.889
                             scale_quantile    T_eff              0.925
                             scale_quantile_14 T_eff              0.887
                             scale_robust      T_eff              0.925
                             scale_robust_14   T_eff              0.890
                             scale_standard    T_eff              0.927
                             scale_standard_14 T_eff              0.889

                                                                                                                 Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                             Base_old          T_eff              75 : 0.07238 / 90 : 0.23285 / 95 : 0.34978 / 99 : 0.55705
                             mass_smaller_14   T_eff               75 : 0.00383 / 90 : 0.02721 / 95 : 0.0747 / 99 : 0.19805
                             mass_smaller_3    T_eff              75 : 0.00557 / 90 : 0.04726 / 95 : 0.09124 / 99 : 0.17501
                             mass_smaller_30   T_eff               75 : 0.00376 / 90 : 0.02825 / 95 : 0.0807 / 99 : 0.26673
                             scale_power       T_eff               75 : 0.00391 / 90 : 0.03105 / 95 : 0.0876 / 99 : 0.31821
                             scale_power_14    T_eff               75 : 0.00383 / 90 : 0.02732 / 95 : 0.0749 / 99 : 0.19706
                             scale_quantile    T_eff              75 : 0.00392 / 90 : 0.03108 / 95 : 0.08703 / 99 : 0.31605
                             scale_quantile_14 T_eff              75 : 0.00385 / 90 : 0.02734 / 95 : 0.07453 / 99 : 0.19742
                             scale_robust      T_eff              75 : 0.00391 / 90 : 0.03108 / 95 : 0.08743 / 99 : 0.31701
                             scale_robust_14   T_eff               75 : 0.00382 / 90 : 0.0272 / 95 : 0.07477 / 99 : 0.19797
                             scale_standard    T_eff              75 : 0.00393 / 90 : 0.03104 / 95 : 0.08729 / 99 : 0.31801
                             scale_standard_14 T_eff              75 : 0.00383 / 90 : 0.02724 / 95 : 0.07486 / 99 : 0.19733

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           Base              T_eff             293.086
                             Base_old          T_eff             632.958
                             mass_smaller_14   T_eff             223.165
                             mass_smaller_3    T_eff             125.782
                             mass_smaller_30   T_eff             253.362
                             scale_power       T_eff             302.977
                             scale_power_14    T_eff             241.892
                             scale_quantile    T_eff             284.082
                             scale_quantile_14 T_eff             206.138
                             scale_robust      T_eff             279.456
                             scale_robust_14   T_eff             196.903
                             scale_standard    T_eff             237.817
                             scale_standard_14 T_eff             222.574

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne les meilleurs résultats absolus

In [63]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                                value range  \
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             3.345 - 5.379
                             scale_standard T_eff             3.345 - 5.379
                             scale_robust   T_eff             3.345 - 5.379
                             scale_quantile T_eff             3.345 - 5.379
                             scale_power    T_eff             3.345 - 5.379

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             0.967  3.079%
                             scale_standard T_eff             0.967  3.079%
                             scale_robust   T_eff             0.967  3.079%
                             scale_quantile T_eff             0.967  3.074%
                             scale_power    T_eff             0.967   3.08%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             0.792%   0.05%
                             scale_standard T_eff             0.792%   0.05%
                             scale_robust   T_eff             0.792%   0.05%
                             scale_quantile T_eff              0.79%  0.051%
                             scale_power    T_eff             0.791%   0.05%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             0.984  45.871%
                             scale_standard T_eff             0.984  45.583%
                             scale_robust   T_eff             0.984  45.485%
                             scale_quantile T_eff             0.984  45.473%
                             scale_power    T_eff             0.984  45.787%

                                                                                                         Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             75 : 0.193% / 90 : 1.523% / 95 : 4.298% / 99 : 15.592%
                             scale_standard T_eff             75 : 0.193% / 90 : 1.526% / 95 : 4.291% / 99 : 15.634%
                             scale_robust   T_eff             75 : 0.192% / 90 : 1.528% / 95 : 4.298% / 99 : 15.585%
                             scale_quantile T_eff             75 : 0.193% / 90 : 1.528% / 95 : 4.278% / 99 : 15.537%
                             scale_power    T_eff             75 : 0.192% / 90 : 1.526% / 95 : 4.307% / 99 : 15.644%

                                                                 time
model         physical_model filter         output_parameter
random_forest MIST           Base           T_eff             293.086
                             scale_standard T_eff             237.817
                             scale_robust   T_eff             279.456
                             scale_quantile T_eff             284.082
                             scale_power    T_eff             302.977

Tous les filtres sont équivalents

#### log_g parameter

In [34]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             -1.083 - 6.259
                             Base_old          log_g             -1.145 - 6.259
                             mass_smaller_14   log_g             -1.083 - 5.433
                             mass_smaller_3    log_g             -1.075 - 5.433
                             mass_smaller_30   log_g             -1.075 - 6.243
                             scale_power       log_g             -1.083 - 6.259
                             scale_power_14    log_g             -1.083 - 5.433
                             scale_quantile    log_g             -1.083 - 6.259
                             scale_quantile_14 log_g             -1.083 - 5.433
                             scale_robust      log_g             -1.083 - 6.259
                             scale_robust_14   log_g             -1.083 - 5.433
                             scale_standard    log_g             -1.083 - 6.259
                             scale_standard_14 log_g             -1.083 - 5.433

                                                                   RVE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             0.820
                             Base_old          log_g             0.531
                             mass_smaller_14   log_g             0.813
                             mass_smaller_3    log_g             0.747
                             mass_smaller_30   log_g             0.814
                             scale_power       log_g             0.820
                             scale_power_14    log_g             0.814
                             scale_quantile    log_g             0.820
                             scale_quantile_14 log_g             0.814
                             scale_robust      log_g             0.820
                             scale_robust_14   log_g             0.814
                             scale_standard    log_g             0.820
                             scale_standard_14 log_g             0.814

                                                                    RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g              7.031%
                             Base_old          log_g             17.612%
                             mass_smaller_14   log_g              8.201%
                             mass_smaller_3    log_g              9.814%
                             mass_smaller_30   log_g              7.235%
                             scale_power       log_g              7.034%
                             scale_power_14    log_g              8.197%
                             scale_quantile    log_g              7.024%
                             scale_quantile_14 log_g              8.187%
                             scale_robust      log_g              7.031%
                             scale_robust_14   log_g              8.197%
                             scale_standard    log_g              7.031%
                             scale_standard_14 log_g              8.192%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             2.075%
                             Base_old          log_g              8.97%
                             mass_smaller_14   log_g             2.435%
                             mass_smaller_3    log_g             3.463%
                             mass_smaller_30   log_g             2.136%
                             scale_power       log_g             2.076%
                             scale_power_14    log_g             2.434%
                             scale_quantile    log_g             2.072%
                             scale_quantile_14 log_g             2.432%
                             scale_robust      log_g             2.076%
                             scale_robust_14   log_g             2.434%
                             scale_standard    log_g             2.076%
                             scale_standard_14 log_g             2.433%

                                                                  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             0.056%
                             Base_old          log_g             0.599%
                             mass_smaller_14   log_g             0.062%
                             mass_smaller_3    log_g              0.06%
                             mass_smaller_30   log_g             0.054%
                             scale_power       log_g             0.056%
                             scale_power_14    log_g             0.062%
                             scale_quantile    log_g             0.056%
                             scale_quantile_14 log_g             0.062%
                             scale_robust      log_g             0.056%
                             scale_robust_14   log_g             0.062%
                             scale_standard    log_g             0.056%
                             scale_standard_14 log_g             0.063%

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             0.908
                             Base_old          log_g             0.741
                             mass_smaller_14   log_g             0.904
                             mass_smaller_3    log_g             0.869
                             mass_smaller_30   log_g             0.904
                             scale_power       log_g             0.908
                             scale_power_14    log_g             0.904
                             scale_quantile    log_g             0.908
                             scale_quantile_14 log_g             0.905
                             scale_robust      log_g             0.908
                             scale_robust_14   log_g             0.904
                             scale_standard    log_g             0.908
                             scale_standard_14 log_g             0.904

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             77.227%
                             Base_old          log_g             75.826%
                             mass_smaller_14   log_g             86.768%
                             mass_smaller_3    log_g             87.135%
                             mass_smaller_30   log_g             77.146%
                             scale_power       log_g              77.23%
                             scale_power_14    log_g             86.768%
                             scale_quantile    log_g             77.229%
                             scale_quantile_14 log_g              86.76%
                             scale_robust      log_g             77.231%
                             scale_robust_14   log_g             86.769%
                             scale_standard    log_g             77.234%
                             scale_standard_14 log_g             86.769%

                                                                                                               Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g                75 : 0.252% / 90 : 4.56% / 95 : 15.625% / 99 : 35.352%
                             Base_old          log_g             75 : 11.503% / 90 : 33.501% / 95 : 45.327% / 99 : 60.932%
                             mass_smaller_14   log_g                75 : 0.284% / 90 : 5.534% / 95 : 18.53% / 99 : 41.128%
                             mass_smaller_3    log_g              75 : 0.583% / 90 : 12.916% / 95 : 24.597% / 99 : 44.459%
                             mass_smaller_30   log_g               75 : 0.243% / 90 : 4.749% / 95 : 16.303% / 99 : 36.363%
                             scale_power       log_g               75 : 0.252% / 90 : 4.548% / 95 : 15.646% / 99 : 35.376%
                             scale_power_14    log_g               75 : 0.285% / 90 : 5.538% / 95 : 18.521% / 99 : 40.982%
                             scale_quantile    log_g               75 : 0.251% / 90 : 4.517% / 95 : 15.624% / 99 : 35.338%
                             scale_quantile_14 log_g                75 : 0.287% / 90 : 5.545% / 95 : 18.501% / 99 : 41.01%
                             scale_robust      log_g               75 : 0.252% / 90 : 4.566% / 95 : 15.646% / 99 : 35.423%
                             scale_robust_14   log_g               75 : 0.284% / 90 : 5.532% / 95 : 18.516% / 99 : 40.942%
                             scale_standard    log_g                75 : 0.254% / 90 : 4.56% / 95 : 15.647% / 99 : 35.383%
                             scale_standard_14 log_g               75 : 0.284% / 90 : 5.544% / 95 : 18.483% / 99 : 40.939%

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           Base              log_g             293.086
                             Base_old          log_g             632.958
                             mass_smaller_14   log_g             223.165
                             mass_smaller_3    log_g             125.782
                             mass_smaller_30   log_g             253.362
                             scale_power       log_g             302.977
                             scale_power_14    log_g             241.892
                             scale_quantile    log_g             284.082
                             scale_quantile_14 log_g             206.138
                             scale_robust      log_g             279.456
                             scale_robust_14   log_g             196.903
                             scale_standard    log_g             237.817
                             scale_standard_14 log_g             222.574

le filtre Base et ses scaling donne les meilleurs résultats

In [35]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g             -1.083 - 6.259
                             scale_standard log_g             -1.083 - 6.259
                             scale_robust   log_g             -1.083 - 6.259
                             scale_quantile log_g             -1.083 - 6.259
                             scale_power    log_g             -1.083 - 6.259

                                                               RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g             0.82  7.031%
                             scale_standard log_g             0.82  7.031%
                             scale_robust   log_g             0.82  7.031%
                             scale_quantile log_g             0.82  7.024%
                             scale_power    log_g             0.82  7.034%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g             2.075%  0.056%
                             scale_standard log_g             2.076%  0.056%
                             scale_robust   log_g             2.076%  0.056%
                             scale_quantile log_g             2.072%  0.056%
                             scale_power    log_g             2.076%  0.056%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g             0.908  77.227%
                             scale_standard log_g             0.908  77.234%
                             scale_robust   log_g             0.908  77.231%
                             scale_quantile log_g             0.908  77.229%
                             scale_power    log_g             0.908   77.23%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g              75 : 0.252% / 90 : 4.56% / 95 : 15.625% / 99 : 35.352%
                             scale_standard log_g              75 : 0.254% / 90 : 4.56% / 95 : 15.647% / 99 : 35.383%
                             scale_robust   log_g             75 : 0.252% / 90 : 4.566% / 95 : 15.646% / 99 : 35.423%
                             scale_quantile log_g             75 : 0.251% / 90 : 4.517% / 95 : 15.624% / 99 : 35.338%
                             scale_power    log_g             75 : 0.252% / 90 : 4.548% / 95 : 15.646% / 99 : 35.376%

                                                                 time
model         physical_model filter         output_parameter
random_forest MIST           Base           log_g             293.086
                             scale_standard log_g             237.817
                             scale_robust   log_g             279.456
                             scale_quantile log_g             284.082
                             scale_power    log_g             302.977

Tous les filtres sont équivalents

#### Radius parameter

In [39]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            -0.997 - 3.129
                             Base_old          radius            -0.997 - 3.129
                             mass_smaller_14   radius            -0.997 - 3.082
                             mass_smaller_3    radius            -0.997 - 2.781
                             mass_smaller_30   radius             -0.997 - 3.13
                             scale_power       radius            -0.997 - 3.129
                             scale_power_14    radius            -0.997 - 3.082
                             scale_quantile    radius            -0.997 - 3.129
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_robust      radius            -0.997 - 3.129
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_standard    radius            -0.997 - 3.129
                             scale_standard_14 radius            -0.997 - 3.082

                                                                   RVE   RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            0.878  0.258
                             Base_old          radius            0.529  0.652
                             mass_smaller_14   radius            0.856  0.267
                             mass_smaller_3    radius            0.791  0.319
                             mass_smaller_30   radius            0.861  0.265
                             scale_power       radius            0.878  0.258
                             scale_power_14    radius            0.856  0.267
                             scale_quantile    radius            0.878  0.258
                             scale_quantile_14 radius            0.857  0.267
                             scale_robust      radius            0.878  0.258
                             scale_robust_14   radius            0.856  0.267
                             scale_standard    radius            0.878  0.258
                             scale_standard_14 radius            0.857  0.267

                                                                   MAE  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            0.076  0.002
                             Base_old          radius            0.332  0.022
                             mass_smaller_14   radius            0.079  0.002
                             mass_smaller_3    radius            0.113  0.002
                             mass_smaller_30   radius            0.078  0.002
                             scale_power       radius            0.076  0.002
                             scale_power_14    radius            0.079  0.002
                             scale_quantile    radius            0.076  0.002
                             scale_quantile_14 radius            0.079  0.002
                             scale_robust      radius            0.076  0.002
                             scale_robust_14   radius            0.079  0.002
                             scale_standard    radius            0.076  0.002
                             scale_standard_14 radius            0.079  0.002

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            0.938
                             Base_old          radius            0.740
                             mass_smaller_14   radius            0.927
                             mass_smaller_3    radius            0.892
                             mass_smaller_30   radius            0.929
                             scale_power       radius            0.938
                             scale_power_14    radius            0.927
                             scale_quantile    radius            0.938
                             scale_quantile_14 radius            0.927
                             scale_robust      radius            0.938
                             scale_robust_14   radius            0.927
                             scale_standard    radius            0.938
                             scale_standard_14 radius            0.927

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius             2.835
                             Base_old          radius             2.807
                             mass_smaller_14   radius             2.827
                             mass_smaller_3    radius             2.836
                             mass_smaller_30   radius             2.824
                             scale_power       radius             2.835
                             scale_power_14    radius             2.827
                             scale_quantile    radius             2.836
                             scale_quantile_14 radius             2.827
                             scale_robust      radius             2.835
                             scale_robust_14   radius             2.827
                             scale_standard    radius             2.836
                             scale_standard_14 radius             2.827

                                                                                                                 Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius             75 : 0.00955 / 90 : 0.16761 / 95 : 0.57416 / 99 : 1.29851
                             Base_old          radius             75 : 0.42592 / 90 : 1.24044 / 95 : 1.67813 / 99 : 2.25528
                             mass_smaller_14   radius              75 : 0.0094 / 90 : 0.18031 / 95 : 0.60369 / 99 : 1.34028
                             mass_smaller_3    radius             75 : 0.01901 / 90 : 0.42028 / 95 : 0.80026 / 99 : 1.44672
                             mass_smaller_30   radius             75 : 0.00909 / 90 : 0.17385 / 95 : 0.59669 / 99 : 1.33082
                             scale_power       radius             75 : 0.00954 / 90 : 0.16724 / 95 : 0.57476 / 99 : 1.29955
                             scale_power_14    radius             75 : 0.00942 / 90 : 0.18045 / 95 : 0.60343 / 99 : 1.33501
                             scale_quantile    radius             75 : 0.00956 / 90 : 0.16605 / 95 : 0.57375 / 99 : 1.29797
                             scale_quantile_14 radius             75 : 0.00949 / 90 : 0.18062 / 95 : 0.60279 / 99 : 1.33623
                             scale_robust      radius             75 : 0.00955 / 90 : 0.16791 / 95 : 0.57487 / 99 : 1.30065
                             scale_robust_14   radius                75 : 0.0094 / 90 : 0.18023 / 95 : 0.6033 / 99 : 1.3339
                             scale_standard    radius             75 : 0.00963 / 90 : 0.16762 / 95 : 0.57468 / 99 : 1.29952
                             scale_standard_14 radius              75 : 0.0094 / 90 : 0.18066 / 95 : 0.60214 / 99 : 1.33375

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            293.086
                             Base_old          radius            632.958
                             mass_smaller_14   radius            223.165
                             mass_smaller_3    radius            125.782
                             mass_smaller_30   radius            253.362
                             scale_power       radius            302.977
                             scale_power_14    radius            241.892
                             scale_quantile    radius            284.082
                             scale_quantile_14 radius            206.138
                             scale_robust      radius            279.456
                             scale_robust_14   radius            196.903
                             scale_standard    radius            237.817
                             scale_standard_14 radius            222.574

Filtre Base et ses scaling donne les meilleurs résultats

In [40]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            -0.997 - 3.129
                             scale_standard radius            -0.997 - 3.129
                             scale_robust   radius            -0.997 - 3.129
                             scale_quantile radius            -0.997 - 3.129
                             scale_power    radius            -0.997 - 3.129

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            0.878  6.257%
                             scale_standard radius            0.878  6.258%
                             scale_robust   radius            0.878  6.257%
                             scale_quantile radius            0.878  6.251%
                             scale_power    radius            0.878  6.259%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            1.851%  0.056%
                             scale_standard radius            1.852%  0.057%
                             scale_robust   radius            1.852%  0.057%
                             scale_quantile radius            1.849%  0.057%
                             scale_power    radius            1.851%  0.057%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            0.938  68.704%
                             scale_standard radius            0.938  68.715%
                             scale_robust   radius            0.938  68.709%
                             scale_quantile radius            0.938  68.713%
                             scale_power    radius            0.938  68.707%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            75 : 0.231% / 90 : 4.062% / 95 : 13.913% / 99 : 31.466%
                             scale_standard radius             75 : 0.233% / 90 : 4.062% / 95 : 13.926% / 99 : 31.49%
                             scale_robust   radius             75 : 0.231% / 90 : 4.069% / 95 : 13.93% / 99 : 31.518%
                             scale_quantile radius            75 : 0.232% / 90 : 4.024% / 95 : 13.903% / 99 : 31.453%
                             scale_power    radius            75 : 0.231% / 90 : 4.053% / 95 : 13.928% / 99 : 31.491%

                                                                 time
model         physical_model filter         output_parameter
random_forest MIST           Base           radius            293.086
                             scale_standard radius            237.817
                             scale_robust   radius            279.456
                             scale_quantile radius            284.082
                             scale_power    radius            302.977

Tous les filtres sont équivalents

#### Filtre choisi

Le filtre scale_quantile est choisi parce qu'il donne des résultats un peu meilleurs que les autres filtres pour le log_g et le rayon et est donne des bons résultats pour la T_eff.

random_forest	MIST	scale_quantile	T_eff	3.345 - 5.379	0.967	3.074%	0.79%	0.051%	0.984	45.473%	75 : 0.193% / 90 : 1.528% / 95 : 4.278% / 99 : 15.537%	284.082

random_forest	MIST	scale_quantile	log_g	-1.083 - 6.259	0.82	7.024%	2.072%	0.056%	0.908	77.229%	75 : 0.251% / 90 : 4.517% / 95 : 15.624% / 99 : 35.338%	284.082

random_forest	MIST	scale_quantile	radius	-0.997 - 3.129	0.878	6.251%	1.849%	0.057%	0.938	68.713%	75 : 0.232% / 90 : 4.024% / 95 : 13.903% / 99 : 31.453%	284.082

### XGBoost

#### T_eff parameter

In [42]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                             value range  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff             3.345 - 5.379
                       Base_old          T_eff             3.345 - 5.379
                       mass_smaller_14   T_eff             3.345 - 4.634
                       mass_smaller_3    T_eff             3.345 - 4.301
                       mass_smaller_30   T_eff             3.345 - 5.354
                       scale_power       T_eff             3.345 - 5.379
                       scale_power_14    T_eff             3.345 - 4.634
                       scale_quantile    T_eff             3.345 - 5.379
                       scale_quantile_14 T_eff             3.345 - 4.634
                       scale_robust      T_eff             3.345 - 5.379
                       scale_robust_14   T_eff             3.345 - 4.634
                       scale_standard    T_eff             3.345 - 5.379
                       scale_standard_14 T_eff             3.345 - 4.634

                                                             RVE   RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff             0.901  0.109
                       Base_old          T_eff             0.805  0.154
                       mass_smaller_14   T_eff             0.869  0.103
                       mass_smaller_3    T_eff             0.904  0.057
                       mass_smaller_30   T_eff             0.886  0.107
                       scale_power       T_eff             0.901  0.109
                       scale_power_14    T_eff             0.870  0.103
                       scale_quantile    T_eff             0.901  0.109
                       scale_quantile_14 T_eff             0.869  0.103
                       scale_robust      T_eff             0.901  0.109
                       scale_robust_14   T_eff             0.869  0.103
                       scale_standard    T_eff             0.901  0.109
                       scale_standard_14 T_eff             0.869  0.103

                                                             MAE  MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff             0.069  0.035
                       Base_old          T_eff             0.110  0.077
                       mass_smaller_14   T_eff             0.065  0.031
                       mass_smaller_3    T_eff             0.037  0.016
                       mass_smaller_30   T_eff             0.067  0.032
                       scale_power       T_eff             0.069  0.034
                       scale_power_14    T_eff             0.064  0.031
                       scale_quantile    T_eff             0.069  0.034
                       scale_quantile_14 T_eff             0.064  0.030
                       scale_robust      T_eff             0.069  0.034
                       scale_robust_14   T_eff             0.065  0.031
                       scale_standard    T_eff             0.069  0.034
                       scale_standard_14 T_eff             0.065  0.031

                                                            CORR  MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff             0.949   0.874
                       Base_old          T_eff             0.897   0.823
                       mass_smaller_14   T_eff             0.932   0.820
                       mass_smaller_3    T_eff             0.951   0.388
                       mass_smaller_30   T_eff             0.941   0.851
                       scale_power       T_eff             0.949   0.864
                       scale_power_14    T_eff             0.933   0.777
                       scale_quantile    T_eff             0.949   0.843
                       scale_quantile_14 T_eff             0.932   0.786
                       scale_robust      T_eff             0.949   0.877
                       scale_robust_14   T_eff             0.932   0.826
                       scale_standard    T_eff             0.949   0.875
                       scale_standard_14 T_eff             0.932   0.804

                                                                                                           Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff              75 : 0.09802 / 90 : 0.18339 / 95 : 0.25166 / 99 : 0.37352
                       Base_old          T_eff              75 : 0.15376 / 90 : 0.26733 / 95 : 0.33968 / 99 : 0.46983
                       mass_smaller_14   T_eff              75 : 0.09281 / 90 : 0.17298 / 95 : 0.23878 / 99 : 0.36132
                       mass_smaller_3    T_eff               75 : 0.05806 / 90 : 0.10125 / 95 : 0.1285 / 99 : 0.18066
                       mass_smaller_30   T_eff                75 : 0.09515 / 90 : 0.1785 / 95 : 0.2475 / 99 : 0.37369
                       scale_power       T_eff              75 : 0.09763 / 90 : 0.18326 / 95 : 0.25179 / 99 : 0.37411
                       scale_power_14    T_eff              75 : 0.09246 / 90 : 0.17283 / 95 : 0.23815 / 99 : 0.36131
                       scale_quantile    T_eff                 75 : 0.09802 / 90 : 0.1832 / 95 : 0.25153 / 99 : 0.373
                       scale_quantile_14 T_eff              75 : 0.09268 / 90 : 0.17299 / 95 : 0.23873 / 99 : 0.36032
                       scale_robust      T_eff              75 : 0.09797 / 90 : 0.18343 / 95 : 0.25186 / 99 : 0.37378
                       scale_robust_14   T_eff              75 : 0.09273 / 90 : 0.17277 / 95 : 0.23824 / 99 : 0.36002
                       scale_standard    T_eff              75 : 0.09811 / 90 : 0.18303 / 95 : 0.25173 / 99 : 0.37307
                       scale_standard_14 T_eff                 75 : 0.09279 / 90 : 0.17341 / 95 : 0.239 / 99 : 0.3602

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           Base              T_eff             17.973
                       Base_old          T_eff             34.861
                       mass_smaller_14   T_eff             14.965
                       mass_smaller_3    T_eff              9.705
                       mass_smaller_30   T_eff             14.461
                       scale_power       T_eff             27.663
                       scale_power_14    T_eff             23.344
                       scale_quantile    T_eff             19.682
                       scale_quantile_14 T_eff             17.546
                       scale_robust      T_eff             17.767
                       scale_robust_14   T_eff             13.039
                       scale_standard    T_eff             15.017
                       scale_standard_14 T_eff             15.242

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne les meilleurs résultats absolus

In [44]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             3.345 - 5.379  0.901
                       scale_standard T_eff             3.345 - 5.379  0.901
                       scale_robust   T_eff             3.345 - 5.379  0.901
                       scale_quantile T_eff             3.345 - 5.379  0.901
                       scale_power    T_eff             3.345 - 5.379  0.901

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             5.357%  3.387%
                       scale_standard T_eff             5.354%  3.384%
                       scale_robust   T_eff             5.355%  3.382%
                       scale_quantile T_eff             5.354%  3.383%
                       scale_power    T_eff             5.352%  3.376%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             1.698%  0.949
                       scale_standard T_eff              1.69%  0.949
                       scale_robust   T_eff              1.69%  0.949
                       scale_quantile T_eff             1.692%  0.949
                       scale_power    T_eff             1.676%  0.949

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             42.951%
                       scale_standard T_eff             43.032%
                       scale_robust   T_eff             43.099%
                       scale_quantile T_eff             41.433%
                       scale_power    T_eff             42.485%

                                                                                                    Percentiles  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             75 : 4.819% / 90 : 9.016% / 95 : 12.372% / 99 : 18.363%
                       scale_standard T_eff              75 : 4.823% / 90 : 8.998% / 95 : 12.375% / 99 : 18.34%
                       scale_robust   T_eff             75 : 4.816% / 90 : 9.018% / 95 : 12.382% / 99 : 18.375%
                       scale_quantile T_eff             75 : 4.819% / 90 : 9.006% / 95 : 12.365% / 99 : 18.337%
                       scale_power    T_eff               75 : 4.8% / 90 : 9.009% / 95 : 12.378% / 99 : 18.392%

                                                          time
model   physical_model filter         output_parameter
XGBoost MIST           Base           T_eff             17.973
                       scale_standard T_eff             15.017
                       scale_robust   T_eff             17.767
                       scale_quantile T_eff             19.682
                       scale_power    T_eff             27.663

Tous les filtres sont équivalents

#### log_g parameter

In [45]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                              value range  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g             -1.083 - 6.259
                       Base_old          log_g             -1.145 - 6.259
                       mass_smaller_14   log_g             -1.083 - 5.433
                       mass_smaller_3    log_g             -1.075 - 5.433
                       mass_smaller_30   log_g             -1.075 - 6.243
                       scale_power       log_g             -1.083 - 6.259
                       scale_power_14    log_g             -1.083 - 5.433
                       scale_quantile    log_g             -1.083 - 6.259
                       scale_quantile_14 log_g             -1.083 - 5.433
                       scale_robust      log_g             -1.083 - 6.259
                       scale_robust_14   log_g             -1.083 - 5.433
                       scale_standard    log_g             -1.083 - 6.259
                       scale_standard_14 log_g             -1.083 - 5.433

                                                             RVE   RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g             0.743  0.616
                       Base_old          log_g             0.531  1.304
                       mass_smaller_14   log_g             0.749  0.620
                       mass_smaller_3    log_g             0.779  0.597
                       mass_smaller_30   log_g             0.744  0.621
                       scale_power       log_g             0.743  0.617
                       scale_power_14    log_g             0.748  0.620
                       scale_quantile    log_g             0.744  0.616
                       scale_quantile_14 log_g             0.748  0.621
                       scale_robust      log_g             0.742  0.617
                       scale_robust_14   log_g             0.749  0.620
                       scale_standard    log_g             0.743  0.616
                       scale_standard_14 log_g             0.749  0.620

                                                             MAE  MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g             0.398  0.203
                       Base_old          log_g             0.971  0.799
                       mass_smaller_14   log_g             0.396  0.196
                       mass_smaller_3    log_g             0.350  0.138
                       mass_smaller_30   log_g             0.398  0.197
                       scale_power       log_g             0.398  0.203
                       scale_power_14    log_g             0.396  0.194
                       scale_quantile    log_g             0.397  0.201
                       scale_quantile_14 log_g             0.397  0.196
                       scale_robust      log_g             0.399  0.203
                       scale_robust_14   log_g             0.396  0.195
                       scale_standard    log_g             0.398  0.202
                       scale_standard_14 log_g             0.396  0.195

                                                            CORR  MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g             0.863   4.999
                       Base_old          log_g             0.729   5.458
                       mass_smaller_14   log_g             0.866   4.866
                       mass_smaller_3    log_g             0.883   5.187
                       mass_smaller_30   log_g             0.863   4.971
                       scale_power       log_g             0.862   5.051
                       scale_power_14    log_g             0.866   4.778
                       scale_quantile    log_g             0.863   4.797
                       scale_quantile_14 log_g             0.865   4.901
                       scale_robust      log_g             0.862   4.847
                       scale_robust_14   log_g             0.866   5.107
                       scale_standard    log_g             0.863   4.903
                       scale_standard_14 log_g             0.866   4.771

                                                                                                           Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g              75 : 0.60495 / 90 : 1.07415 / 95 : 1.36576 / 99 : 1.95832
                       Base_old          log_g               75 : 1.34081 / 90 : 2.09475 / 95 : 2.85642 / 99 : 3.9318
                       mass_smaller_14   log_g              75 : 0.60934 / 90 : 1.07914 / 95 : 1.38015 / 99 : 1.96942
                       mass_smaller_3    log_g               75 : 0.49235 / 90 : 1.0013 / 95 : 1.38894 / 99 : 2.13587
                       mass_smaller_30   log_g              75 : 0.60567 / 90 : 1.08046 / 95 : 1.38815 / 99 : 1.97733
                       scale_power       log_g               75 : 0.60492 / 90 : 1.07266 / 95 : 1.36845 / 99 : 1.9648
                       scale_power_14    log_g               75 : 0.61059 / 90 : 1.0805 / 95 : 1.38236 / 99 : 1.97228
                       scale_quantile    log_g              75 : 0.60297 / 90 : 1.07131 / 95 : 1.36577 / 99 : 1.96148
                       scale_quantile_14 log_g              75 : 0.61053 / 90 : 1.08208 / 95 : 1.37973 / 99 : 1.97257
                       scale_robust      log_g              75 : 0.60595 / 90 : 1.07507 / 95 : 1.36832 / 99 : 1.96373
                       scale_robust_14   log_g               75 : 0.61008 / 90 : 1.0824 / 95 : 1.37952 / 99 : 1.97065
                       scale_standard    log_g              75 : 0.60255 / 90 : 1.07245 / 95 : 1.36879 / 99 : 1.96226
                       scale_standard_14 log_g               75 : 0.60926 / 90 : 1.0782 / 95 : 1.38079 / 99 : 1.97092

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           Base              log_g             17.973
                       Base_old          log_g             34.861
                       mass_smaller_14   log_g             14.965
                       mass_smaller_3    log_g              9.705
                       mass_smaller_30   log_g             14.461
                       scale_power       log_g             27.663
                       scale_power_14    log_g             23.344
                       scale_quantile    log_g             19.682
                       scale_quantile_14 log_g             17.546
                       scale_robust      log_g             17.767
                       scale_robust_14   log_g             13.039
                       scale_standard    log_g             15.017
                       scale_standard_14 log_g             15.242

Filtre Base donne les meilleurs résultats

In [61]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g             -1.083 - 6.259  0.743
                       scale_standard log_g             -1.083 - 6.259  0.743
                       scale_robust   log_g             -1.083 - 6.259  0.742
                       scale_quantile log_g             -1.083 - 6.259  0.744
                       scale_power    log_g             -1.083 - 6.259  0.743

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g             8.391%  5.419%
                       scale_standard log_g              8.39%  5.415%
                       scale_robust   log_g             8.405%   5.43%
                       scale_quantile log_g             8.385%  5.409%
                       scale_power    log_g             8.397%  5.423%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g              2.76%  0.863
                       scale_standard log_g             2.753%  0.863
                       scale_robust   log_g              2.76%  0.862
                       scale_quantile log_g             2.741%  0.863
                       scale_power    log_g             2.761%  0.862

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g             68.084%
                       scale_standard log_g             66.779%
                       scale_robust   log_g             66.018%
                       scale_quantile log_g             65.332%
                       scale_power    log_g             68.798%

                                                                                                     Percentiles  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g              75 : 8.239% / 90 : 14.63% / 95 : 18.601% / 99 : 26.672%
                       scale_standard log_g             75 : 8.207% / 90 : 14.606% / 95 : 18.642% / 99 : 26.725%
                       scale_robust   log_g             75 : 8.253% / 90 : 14.642% / 95 : 18.636% / 99 : 26.745%
                       scale_quantile log_g             75 : 8.212% / 90 : 14.591% / 95 : 18.601% / 99 : 26.715%
                       scale_power    log_g              75 : 8.239% / 90 : 14.609% / 95 : 18.638% / 99 : 26.76%

                                                          time
model   physical_model filter         output_parameter
XGBoost MIST           Base           log_g             17.973
                       scale_standard log_g             15.017
                       scale_robust   log_g             17.767
                       scale_quantile log_g             19.682
                       scale_power    log_g             27.663

Tous les filtres sont équivalents

#### Radius parameter

In [48]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                              value range  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            -0.997 - 3.129
                       Base_old          radius            -0.997 - 3.129
                       mass_smaller_14   radius            -0.997 - 3.082
                       mass_smaller_3    radius            -0.997 - 2.781
                       mass_smaller_30   radius             -0.997 - 3.13
                       scale_power       radius            -0.997 - 3.129
                       scale_power_14    radius            -0.997 - 3.082
                       scale_quantile    radius            -0.997 - 3.129
                       scale_quantile_14 radius            -0.997 - 3.082
                       scale_robust      radius            -0.997 - 3.129
                       scale_robust_14   radius            -0.997 - 3.082
                       scale_standard    radius            -0.997 - 3.129
                       scale_standard_14 radius            -0.997 - 3.082

                                                             RVE   RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            0.825  0.309
                       Base_old          radius            0.527  0.654
                       mass_smaller_14   radius            0.806  0.311
                       mass_smaller_3    radius            0.818  0.298
                       mass_smaller_30   radius            0.809  0.311
                       scale_power       radius            0.825  0.309
                       scale_power_14    radius            0.806  0.310
                       scale_quantile    radius            0.825  0.308
                       scale_quantile_14 radius            0.805  0.311
                       scale_robust      radius            0.825  0.309
                       scale_robust_14   radius            0.805  0.311
                       scale_standard    radius            0.825  0.309
                       scale_standard_14 radius            0.805  0.311

                                                             MAE  MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            0.199  0.100
                       Base_old          radius            0.488  0.402
                       mass_smaller_14   radius            0.199  0.099
                       mass_smaller_3    radius            0.175  0.070
                       mass_smaller_30   radius            0.199  0.098
                       scale_power       radius            0.199  0.100
                       scale_power_14    radius            0.199  0.099
                       scale_quantile    radius            0.199  0.100
                       scale_quantile_14 radius            0.199  0.099
                       scale_robust      radius            0.199  0.100
                       scale_robust_14   radius            0.199  0.098
                       scale_standard    radius            0.199  0.100
                       scale_standard_14 radius            0.200  0.099

                                                            CORR  MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            0.909   2.580
                       Base_old          radius            0.726   2.723
                       mass_smaller_14   radius            0.898   2.488
                       mass_smaller_3    radius            0.905   2.585
                       mass_smaller_30   radius            0.899   2.523
                       scale_power       radius            0.908   2.550
                       scale_power_14    radius            0.898   2.352
                       scale_quantile    radius            0.909   2.510
                       scale_quantile_14 radius            0.898   2.397
                       scale_robust      radius            0.908   2.518
                       scale_robust_14   radius            0.898   2.512
                       scale_standard    radius            0.909   2.539
                       scale_standard_14 radius            0.898   2.477

                                                                                                           Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius             75 : 0.30188 / 90 : 0.53827 / 95 : 0.68623 / 99 : 0.98445
                       Base_old          radius             75 : 0.67425 / 90 : 1.05149 / 95 : 1.42933 / 99 : 1.96479
                       mass_smaller_14   radius             75 : 0.30646 / 90 : 0.54067 / 95 : 0.69123 / 99 : 0.98351
                       mass_smaller_3    radius              75 : 0.2465 / 90 : 0.50006 / 95 : 0.69248 / 99 : 1.06755
                       mass_smaller_30   radius             75 : 0.30308 / 90 : 0.54161 / 95 : 0.69406 / 99 : 0.98891
                       scale_power       radius              75 : 0.3033 / 90 : 0.53922 / 95 : 0.68807 / 99 : 0.98368
                       scale_power_14    radius             75 : 0.30525 / 90 : 0.54027 / 95 : 0.69113 / 99 : 0.98635
                       scale_quantile    radius             75 : 0.30256 / 90 : 0.53774 / 95 : 0.68639 / 99 : 0.98079
                       scale_quantile_14 radius              75 : 0.3066 / 90 : 0.54047 / 95 : 0.69077 / 99 : 0.99116
                       scale_robust      radius             75 : 0.30384 / 90 : 0.53788 / 95 : 0.68639 / 99 : 0.98102
                       scale_robust_14   radius             75 : 0.30655 / 90 : 0.54245 / 95 : 0.69203 / 99 : 0.98974
                       scale_standard    radius             75 : 0.30324 / 90 : 0.53841 / 95 : 0.68594 / 99 : 0.98333
                       scale_standard_14 radius              75 : 0.30692 / 90 : 0.5415 / 95 : 0.69099 / 99 : 0.98826

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            17.973
                       Base_old          radius            34.861
                       mass_smaller_14   radius            14.965
                       mass_smaller_3    radius             9.705
                       mass_smaller_30   radius            14.461
                       scale_power       radius            27.663
                       scale_power_14    radius            23.344
                       scale_quantile    radius            19.682
                       scale_quantile_14 radius            17.546
                       scale_robust      radius            17.767
                       scale_robust_14   radius            13.039
                       scale_standard    radius            15.017
                       scale_standard_14 radius            15.242

Filtre Base donne les meilleurs résultats

In [62]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            -0.997 - 3.129  0.825
                       scale_standard radius            -0.997 - 3.129  0.825
                       scale_robust   radius            -0.997 - 3.129  0.825
                       scale_quantile radius            -0.997 - 3.129  0.825
                       scale_power    radius            -0.997 - 3.129  0.825

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            7.479%  4.815%
                       scale_standard radius            7.478%   4.82%
                       scale_robust   radius            7.485%  4.825%
                       scale_quantile radius            7.474%  4.814%
                       scale_power    radius            7.489%  4.823%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            2.424%  0.909
                       scale_standard radius            2.434%  0.909
                       scale_robust   radius            2.426%  0.908
                       scale_quantile radius            2.419%  0.909
                       scale_power    radius            2.422%  0.908

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            62.531%
                       scale_standard radius            61.536%
                       scale_robust   radius            61.029%
                       scale_quantile radius             60.82%
                       scale_power    radius            61.786%

                                                                                                     Percentiles  \
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            75 : 7.315% / 90 : 13.043% / 95 : 16.629% / 99 : 23.855%
                       scale_standard radius            75 : 7.348% / 90 : 13.047% / 95 : 16.622% / 99 : 23.828%
                       scale_robust   radius            75 : 7.363% / 90 : 13.034% / 95 : 16.633% / 99 : 23.772%
                       scale_quantile radius            75 : 7.332% / 90 : 13.031% / 95 : 16.633% / 99 : 23.767%
                       scale_power    radius             75 : 7.35% / 90 : 13.067% / 95 : 16.673% / 99 : 23.837%

                                                          time
model   physical_model filter         output_parameter
XGBoost MIST           Base           radius            17.973
                       scale_standard radius            15.017
                       scale_robust   radius            17.767
                       scale_quantile radius            19.682
                       scale_power    radius            27.663

Tous les filtres sont équivalents

#### Filtre choisi

Le filtre Base est choisi parce qu'il donne les meilleurs résultats pour le log_g et la masse et donne des bons résultats pour la T_eff.

XGBoost	MIST	Base	T_eff	3.345 - 5.379	0.901	5.357%	3.387%	1.698%	0.949	42.951%	75 : 4.819% / 90 : 9.016% / 95 : 12.372% / 99 : 18.363%	17.973

XGBoost	MIST	Base	log_g	-1.083 - 6.259	0.743	8.391%	5.419%	2.76%	0.863	68.084%	75 : 8.239% / 90 : 14.63% / 95 : 18.601% / 99 : 26.672%	17.973

XGBoost	MIST	Base	radius	-0.997 - 3.129	0.825	7.479%	4.815%	2.424%	0.909	62.531%	75 : 7.315% / 90 : 13.043% / 95 : 16.629% / 99 : 23.855%	17.973

### MLP

#### T_eff parameter

In [51]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model physical_model filter            output_parameter
mlp   MIST           Base              T_eff             3.345 - 5.379  0.850
                     Base_old          T_eff             3.345 - 5.379  0.761
                     mass_smaller_14   T_eff             3.345 - 4.634  0.802
                     mass_smaller_3    T_eff             3.345 - 4.301  0.732
                     mass_smaller_30   T_eff             3.345 - 5.354  0.719
                     scale_power       T_eff             3.345 - 5.379  0.899
                     scale_power_14    T_eff             3.345 - 4.634  0.868
                     scale_quantile    T_eff             3.345 - 5.379  0.883
                     scale_quantile_14 T_eff             3.345 - 4.634  0.856
                     scale_robust      T_eff             3.345 - 5.379  0.888
                     scale_robust_14   T_eff             3.345 - 4.634  0.870
                     scale_standard    T_eff             3.345 - 5.379  0.864
                     scale_standard_14 T_eff             3.345 - 4.634  0.864

                                                          RMSE    MAE  MedAE  \
model physical_model filter            output_parameter
mlp   MIST           Base              T_eff             0.135  0.092  0.055
                     Base_old          T_eff             0.170  0.122  0.081
                     mass_smaller_14   T_eff             0.129  0.091  0.057
                     mass_smaller_3    T_eff             0.097  0.073  0.053
                     mass_smaller_30   T_eff             0.169  0.117  0.072
                     scale_power       T_eff             0.111  0.075  0.051
                     scale_power_14    T_eff             0.106  0.073  0.051
                     scale_quantile    T_eff             0.118  0.076  0.041
                     scale_quantile_14 T_eff             0.109  0.069  0.036
                     scale_robust      T_eff             0.116  0.075  0.044
                     scale_robust_14   T_eff             0.103  0.067  0.040
                     scale_standard    T_eff             0.129  0.091  0.060
                     scale_standard_14 T_eff             0.107  0.071  0.045

                                                          CORR  MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           Base              T_eff             0.922   0.977
                     Base_old          T_eff             0.874   0.885
                     mass_smaller_14   T_eff             0.895   0.645
                     mass_smaller_3    T_eff             0.859   0.525
                     mass_smaller_30   T_eff             0.853   1.042
                     scale_power       T_eff             0.948   0.935
                     scale_power_14    T_eff             0.932   0.781
                     scale_quantile    T_eff             0.940   0.925
                     scale_quantile_14 T_eff             0.925   0.745
                     scale_robust      T_eff             0.943   1.142
                     scale_robust_14   T_eff             0.933   0.868
                     scale_standard    T_eff             0.930   1.105
                     scale_standard_14 T_eff             0.929   0.783

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           Base              T_eff              75 : 0.12551 / 90 : 0.23121 / 95 : 0.30635 / 99 : 0.43044
                     Base_old          T_eff               75 : 0.17171 / 90 : 0.29035 / 95 : 0.37238 / 99 : 0.5291
                     mass_smaller_14   T_eff              75 : 0.12599 / 90 : 0.22804 / 95 : 0.29284 / 99 : 0.40039
                     mass_smaller_3    T_eff              75 : 0.11483 / 90 : 0.16631 / 95 : 0.19743 / 99 : 0.25269
                     mass_smaller_30   T_eff              75 : 0.16288 / 90 : 0.29303 / 95 : 0.37757 / 99 : 0.51242
                     scale_power       T_eff               75 : 0.09023 / 90 : 0.1684 / 95 : 0.25198 / 99 : 0.39923
                     scale_power_14    T_eff              75 : 0.08742 / 90 : 0.15815 / 95 : 0.23867 / 99 : 0.39261
                     scale_quantile    T_eff               75 : 0.09605 / 90 : 0.19835 / 95 : 0.27634 / 99 : 0.4148
                     scale_quantile_14 T_eff               75 : 0.0886 / 90 : 0.18129 / 95 : 0.25715 / 99 : 0.39261
                     scale_robust      T_eff               75 : 0.0925 / 90 : 0.18791 / 95 : 0.26858 / 99 : 0.41577
                     scale_robust_14   T_eff              75 : 0.08254 / 90 : 0.16159 / 95 : 0.23703 / 99 : 0.38185
                     scale_standard    T_eff                75 : 0.1243 / 90 : 0.21381 / 95 : 0.2819 / 99 : 0.41274
                     scale_standard_14 T_eff              75 : 0.08561 / 90 : 0.17109 / 95 : 0.24289 / 99 : 0.38839

                                                             time
model physical_model filter            output_parameter
mlp   MIST           Base              T_eff              424.225
                     Base_old          T_eff             1908.579
                     mass_smaller_14   T_eff              339.600
                     mass_smaller_3    T_eff              203.751
                     mass_smaller_30   T_eff              214.479
                     scale_power       T_eff              431.956
                     scale_power_14    T_eff              334.375
                     scale_quantile    T_eff              431.271
                     scale_quantile_14 T_eff              337.118
                     scale_robust      T_eff              383.268
                     scale_robust_14   T_eff              196.107
                     scale_standard    T_eff              245.473
                     scale_standard_14 T_eff              335.724

Filtre Base donne les meilleurs résultats relatif, mass_smaller_14 et ses scaling donne les meilleurs résultats absolus

In [52]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                        value range    RVE  \
model physical_model filter         output_parameter
mlp   MIST           Base           T_eff             3.345 - 5.379  0.850
                     scale_standard T_eff             3.345 - 5.379  0.864
                     scale_robust   T_eff             3.345 - 5.379  0.888
                     scale_quantile T_eff             3.345 - 5.379  0.883
                     scale_power    T_eff             3.345 - 5.379  0.899

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
mlp   MIST           Base           T_eff             6.617%  4.513%  2.709%
                     scale_standard T_eff             6.327%  4.459%  2.965%
                     scale_robust   T_eff             5.692%  3.682%  2.148%
                     scale_quantile T_eff             5.822%  3.739%  2.026%
                     scale_power    T_eff             5.441%  3.674%  2.518%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
mlp   MIST           Base           T_eff             0.922  48.032%
                     scale_standard T_eff             0.930  54.314%
                     scale_robust   T_eff             0.943  56.139%
                     scale_quantile T_eff             0.940  45.477%
                     scale_power    T_eff             0.948  45.953%

                                                                                                   Percentiles  \
model physical_model filter         output_parameter
mlp   MIST           Base           T_eff               75 : 6.17% / 90 : 11.367% / 95 : 15.06% / 99 : 21.161%
                     scale_standard T_eff             75 : 6.111% / 90 : 10.511% / 95 : 13.858% / 99 : 20.291%
                     scale_robust   T_eff               75 : 4.547% / 90 : 9.238% / 95 : 13.204% / 99 : 20.44%
                     scale_quantile T_eff              75 : 4.722% / 90 : 9.751% / 95 : 13.585% / 99 : 20.392%
                     scale_power    T_eff              75 : 4.436% / 90 : 8.279% / 95 : 12.388% / 99 : 19.627%

                                                         time
model physical_model filter         output_parameter
mlp   MIST           Base           T_eff             424.225
                     scale_standard T_eff             245.473
                     scale_robust   T_eff             383.268
                     scale_quantile T_eff             431.271
                     scale_power    T_eff             431.956

Le fitre scale_power donne les meilleurs résultats.

#### log_g parameter

In [55]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
mlp   MIST           Base              log_g             -1.083 - 6.259
                     Base_old          log_g             -1.145 - 6.259
                     mass_smaller_14   log_g             -1.083 - 5.433
                     mass_smaller_3    log_g             -1.075 - 5.433
                     mass_smaller_30   log_g             -1.075 - 6.243
                     scale_power       log_g             -1.083 - 6.259
                     scale_power_14    log_g             -1.083 - 5.433
                     scale_quantile    log_g             -1.083 - 6.259
                     scale_quantile_14 log_g             -1.083 - 5.433
                     scale_robust      log_g             -1.083 - 6.259
                     scale_robust_14   log_g             -1.083 - 5.433
                     scale_standard    log_g             -1.083 - 6.259
                     scale_standard_14 log_g             -1.083 - 5.433

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
mlp   MIST           Base              log_g             0.642  0.732  0.480
                     Base_old          log_g             0.492  1.358  1.002
                     mass_smaller_14   log_g             0.614  0.781  0.523
                     mass_smaller_3    log_g             0.577  0.825  0.538
                     mass_smaller_30   log_g             0.335  1.000  0.669
                     scale_power       log_g             0.766  0.588  0.338
                     scale_power_14    log_g             0.765  0.600  0.341
                     scale_quantile    log_g             0.718  0.645  0.387
                     scale_quantile_14 log_g             0.722  0.654  0.396
                     scale_robust      log_g             0.734  0.628  0.371
                     scale_robust_14   log_g             0.754  0.614  0.352
                     scale_standard    log_g             0.683  0.685  0.437
                     scale_standard_14 log_g             0.740  0.631  0.371

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           Base              log_g             0.251  0.802   5.618
                     Base_old          log_g             0.785  0.702   5.612
                     mass_smaller_14   log_g             0.266  0.784   5.543
                     mass_smaller_3    log_g             0.249  0.761   5.509
                     mass_smaller_30   log_g             0.353  0.639   5.541
                     scale_power       log_g             0.116  0.876   5.589
                     scale_power_14    log_g             0.104  0.874   5.564
                     scale_quantile    log_g             0.141  0.848   5.630
                     scale_quantile_14 log_g             0.145  0.850   5.606
                     scale_robust      log_g             0.130  0.857   5.547
                     scale_robust_14   log_g             0.114  0.868   5.627
                     scale_standard    log_g             0.203  0.827   5.328
                     scale_standard_14 log_g             0.119  0.860   5.505

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           Base              log_g               75 : 0.76931 / 90 : 1.3016 / 95 : 1.59242 / 99 : 2.26262
                     Base_old          log_g              75 : 1.39272 / 90 : 2.24514 / 95 : 3.06086 / 99 : 3.99218
                     mass_smaller_14   log_g               75 : 0.88269 / 90 : 1.40405 / 95 : 1.65149 / 99 : 2.2567
                     mass_smaller_3    log_g              75 : 0.82849 / 90 : 1.46559 / 95 : 1.88205 / 99 : 2.58211
                     mass_smaller_30   log_g              75 : 1.08136 / 90 : 1.80757 / 95 : 2.15604 / 99 : 2.99478
                     scale_power       log_g              75 : 0.43553 / 90 : 1.01434 / 95 : 1.39706 / 99 : 2.07462
                     scale_power_14    log_g               75 : 0.44341 / 90 : 1.05268 / 95 : 1.4527 / 99 : 2.09883
                     scale_quantile    log_g              75 : 0.55668 / 90 : 1.13385 / 95 : 1.48811 / 99 : 2.15365
                     scale_quantile_14 log_g              75 : 0.57094 / 90 : 1.15654 / 95 : 1.50152 / 99 : 2.19587
                     scale_robust      log_g              75 : 0.50818 / 90 : 1.10924 / 95 : 1.47975 / 99 : 2.14845
                     scale_robust_14   log_g              75 : 0.47539 / 90 : 1.06644 / 95 : 1.45448 / 99 : 2.14521
                     scale_standard    log_g              75 : 0.65067 / 90 : 1.19763 / 95 : 1.53309 / 99 : 2.26205
                     scale_standard_14 log_g              75 : 0.50879 / 90 : 1.10361 / 95 : 1.46626 / 99 : 2.23395

                                                             time
model physical_model filter            output_parameter
mlp   MIST           Base              log_g              424.225
                     Base_old          log_g             1908.579
                     mass_smaller_14   log_g              339.600
                     mass_smaller_3    log_g              203.751
                     mass_smaller_30   log_g              214.479
                     scale_power       log_g              431.956
                     scale_power_14    log_g              334.375
                     scale_quantile    log_g              431.271
                     scale_quantile_14 log_g              337.118
                     scale_robust      log_g              383.268
                     scale_robust_14   log_g              196.107
                     scale_standard    log_g              245.473
                     scale_standard_14 log_g              335.724

Filtre Base donne les meilleurs résultats

In [60]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
mlp   MIST           Base           log_g             -1.083 - 6.259  0.642
                     scale_standard log_g             -1.083 - 6.259  0.683
                     scale_robust   log_g             -1.083 - 6.259  0.734
                     scale_quantile log_g             -1.083 - 6.259  0.718
                     scale_power    log_g             -1.083 - 6.259  0.766

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
mlp   MIST           Base           log_g             9.966%  6.544%  3.418%
                     scale_standard log_g             9.328%  5.952%  2.765%
                     scale_robust   log_g             8.553%  5.051%  1.777%
                     scale_quantile log_g             8.789%  5.268%  1.919%
                     scale_power    log_g             8.004%   4.61%  1.574%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
mlp   MIST           Base           log_g             0.802  76.517%
                     scale_standard log_g             0.827   72.56%
                     scale_robust   log_g             0.857  75.547%
                     scale_quantile log_g             0.848  76.683%
                     scale_power    log_g             0.876  76.124%

                                                                                                    Percentiles  \
model physical_model filter         output_parameter
mlp   MIST           Base           log_g             75 : 10.478% / 90 : 17.727% / 95 : 21.688% / 99 : 30.816%
                     scale_standard log_g               75 : 8.862% / 90 : 16.311% / 95 : 20.88% / 99 : 30.808%
                     scale_robust   log_g              75 : 6.921% / 90 : 15.107% / 95 : 20.154% / 99 : 29.261%
                     scale_quantile log_g              75 : 7.582% / 90 : 15.443% / 95 : 20.268% / 99 : 29.332%
                     scale_power    log_g              75 : 5.932% / 90 : 13.815% / 95 : 19.027% / 99 : 28.256%

                                                         time
model physical_model filter         output_parameter
mlp   MIST           Base           log_g             424.225
                     scale_standard log_g             245.473
                     scale_robust   log_g             383.268
                     scale_quantile log_g             431.271
                     scale_power    log_g             431.956

Le fitre scale_power donne les meilleurs résultats.

#### Radius parameter

In [58]:
compare_metrics(path, value_rounding=3, relative_values=False, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            -0.997 - 3.129
                     Base_old          radius            -0.997 - 3.129
                     mass_smaller_14   radius            -0.997 - 3.082
                     mass_smaller_3    radius            -0.997 - 2.781
                     mass_smaller_30   radius             -0.997 - 3.13
                     scale_power       radius            -0.997 - 3.129
                     scale_power_14    radius            -0.997 - 3.082
                     scale_quantile    radius            -0.997 - 3.129
                     scale_quantile_14 radius            -0.997 - 3.082
                     scale_robust      radius            -0.997 - 3.129
                     scale_robust_14   radius            -0.997 - 3.082
                     scale_standard    radius            -0.997 - 3.129
                     scale_standard_14 radius            -0.997 - 3.082

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            0.757  0.366  0.242
                     Base_old          radius            0.489  0.680  0.503
                     mass_smaller_14   radius            0.702  0.390  0.262
                     mass_smaller_3    radius            0.644  0.416  0.269
                     mass_smaller_30   radius            0.501  0.502  0.340
                     scale_power       radius            0.841  0.294  0.170
                     scale_power_14    radius            0.818  0.301  0.172
                     scale_quantile    radius            0.808  0.324  0.197
                     scale_quantile_14 radius            0.785  0.327  0.202
                     scale_robust      radius            0.817  0.316  0.192
                     scale_robust_14   radius            0.809  0.309  0.181
                     scale_standard    radius            0.780  0.346  0.226
                     scale_standard_14 radius            0.800  0.316  0.184

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            0.126  0.870   2.832
                     Base_old          radius            0.393  0.699   2.837
                     mass_smaller_14   radius            0.134  0.838   2.792
                     mass_smaller_3    radius            0.124  0.804   2.729
                     mass_smaller_30   radius            0.180  0.734   2.747
                     scale_power       radius            0.061  0.917   2.742
                     scale_power_14    radius            0.057  0.904   2.759
                     scale_quantile    radius            0.079  0.899   2.814
                     scale_quantile_14 radius            0.085  0.886   2.775
                     scale_robust      radius            0.080  0.904   2.826
                     scale_robust_14   radius            0.068  0.899   2.808
                     scale_standard    radius            0.114  0.883   2.750
                     scale_standard_14 radius            0.061  0.894   2.773

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius              75 : 0.38607 / 90 : 0.65018 / 95 : 0.79762 / 99 : 1.1283
                     Base_old          radius             75 : 0.69746 / 90 : 1.12306 / 95 : 1.52935 / 99 : 1.99601
                     mass_smaller_14   radius             75 : 0.43942 / 90 : 0.70228 / 95 : 0.82546 / 99 : 1.13213
                     mass_smaller_3    radius             75 : 0.41435 / 90 : 0.74157 / 95 : 0.95201 / 99 : 1.30384
                     mass_smaller_30   radius             75 : 0.54282 / 90 : 0.91032 / 95 : 1.08031 / 99 : 1.49504
                     scale_power       radius             75 : 0.21849 / 90 : 0.50671 / 95 : 0.69933 / 99 : 1.03305
                     scale_power_14    radius             75 : 0.22287 / 90 : 0.52657 / 95 : 0.72696 / 99 : 1.04587
                     scale_quantile    radius             75 : 0.27986 / 90 : 0.56728 / 95 : 0.74378 / 99 : 1.07582
                     scale_quantile_14 radius             75 : 0.28502 / 90 : 0.57861 / 95 : 0.75004 / 99 : 1.09426
                     scale_robust      radius                 75 : 0.2542 / 90 : 0.5576 / 95 : 0.74329 / 99 : 1.077
                     scale_robust_14   radius             75 : 0.24072 / 90 : 0.53587 / 95 : 0.73037 / 99 : 1.07009
                     scale_standard    radius              75 : 0.32921 / 90 : 0.60124 / 95 : 0.77429 / 99 : 1.1299
                     scale_standard_14 radius               75 : 0.254 / 90 : 0.55241 / 95 : 0.73472 / 99 : 1.11348

                                                             time
model physical_model filter            output_parameter
mlp   MIST           Base              radius             424.225
                     Base_old          radius            1908.579
                     mass_smaller_14   radius             339.600
                     mass_smaller_3    radius             203.751
                     mass_smaller_30   radius             214.479
                     scale_power       radius             431.956
                     scale_power_14    radius             334.375
                     scale_quantile    radius             431.271
                     scale_quantile_14 radius             337.118
                     scale_robust      radius             383.268
                     scale_robust_14   radius             196.107
                     scale_standard    radius             245.473
                     scale_standard_14 radius             335.724

Filtre Base donne les meilleurs résultats

In [64]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_quantile", "scale_power"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
mlp   MIST           Base           radius            -0.997 - 3.129  0.757
                     scale_standard radius            -0.997 - 3.129  0.780
                     scale_robust   radius            -0.997 - 3.129  0.817
                     scale_quantile radius            -0.997 - 3.129  0.808
                     scale_power    radius            -0.997 - 3.129  0.841

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
mlp   MIST           Base           radius            8.875%  5.857%  3.046%
                     scale_standard radius            8.383%  5.465%  2.774%
                     scale_robust   radius            7.652%  4.642%  1.947%
                     scale_quantile radius             7.84%  4.777%  1.906%
                     scale_power    radius            7.126%  4.128%  1.472%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
mlp   MIST           Base           radius            0.870  68.624%
                     scale_standard radius            0.883  66.645%
                     scale_robust   radius            0.904  68.491%
                     scale_quantile radius            0.899  68.185%
                     scale_power    radius            0.917  66.437%

                                                                                                   Percentiles  \
model physical_model filter         output_parameter
mlp   MIST           Base           radius            75 : 9.355% / 90 : 15.755% / 95 : 19.328% / 99 : 27.341%
                     scale_standard radius             75 : 7.977% / 90 : 14.569% / 95 : 18.763% / 99 : 27.38%
                     scale_robust   radius             75 : 6.16% / 90 : 13.512% / 95 : 18.012% / 99 : 26.098%
                     scale_quantile radius             75 : 6.782% / 90 : 13.746% / 95 : 18.023% / 99 : 26.07%
                     scale_power    radius            75 : 5.295% / 90 : 12.279% / 95 : 16.946% / 99 : 25.033%

                                                         time
model physical_model filter         output_parameter
mlp   MIST           Base           radius            424.225
                     scale_standard radius            245.473
                     scale_robust   radius            383.268
                     scale_quantile radius            431.271
                     scale_power    radius            431.956

Le fitre scale_power donne les meilleurs résultats.

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour le log_g et le rayon et donne de bons résultats pour la T_eff.

mlp	MIST	scale_power	T_eff	3.345 - 5.379	0.899	5.441%	3.674%	2.518%	0.948	45.953%	75 : 4.436% / 90 : 8.279% / 95 : 12.388% / 99 : 19.627%	431.956

mlp	MIST	scale_power	log_g	-1.083 - 6.259	0.766	8.004%	4.61%	1.574%	0.876	76.124%	75 : 5.932% / 90 : 13.815% / 95 : 19.027% / 99 : 28.256%	431.956

mlp	MIST	scale_power	radius	-0.997 - 3.129	0.841	7.126%	4.128%	1.472%	0.917	66.437%	75 : 5.295% / 90 : 12.279% / 95 : 16.946% / 99 : 25.033%	431.956

### Compilation des meilleurs modèles

#### T_eff parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | MIST | scale_power | T_eff | 3.345 - 5.379 | 0.774 | 8.08% | 6.191% | 5.401% | 0.880 | 46.38% | 75 : 8.004% / 90 : 11.298% / 95 : 16.575% / 99 : 26.884% | 10.220 |
| decision_tree | MIST | Base | T_eff | 3.345 - 5.379 | 0.950 | 3.794% | 0.913% | 0.086% | 0.975 | 46.738% | 75 : 0.21% / 90 : 1.065% / 95 : 4.791% / 99 : 20.817% | 17.940 |
| KNN | MIST | scale_quantile | T_eff | 3.345 - 5.379 | 0.977 | 2.601% | 0.69% | 0.083% | 0.988 | 45.011% | 75 : 0.216% / 90 : 1.38% / 95 : 3.595% / 99 : 12.027% | 7.903 |
| random_forest | MIST | scale_quantile | T_eff | 3.345 - 5.379 | 0.967 | 3.074% | 0.79% | 0.051% | 0.984 | 45.473% | 75 : 0.193% / 90 : 1.528% / 95 : 4.278% / 99 : 15.537% | 284.082 |
| XGBoost | MIST | Base | T_eff | 3.345 - 5.379 | 0.901 | 5.357% | 3.387% | 1.698% | 0.949 | 42.951% | 75 : 4.819% / 90 : 9.016% / 95 : 12.372% / 99 : 18.363% | 17.973 |
| mlp | MIST | scale_power | T_eff | 3.345 - 5.379 | 0.899 | 5.441% | 3.674% | 2.518% | 0.948 | 45.953% | 75 : 4.436% / 90 : 8.279% / 95 : 12.388% / 99 : 19.627% | 431.956 |

The best models in order for the T_eff from best to worst are:

1. KNN
2. Random forest
3. Decision Tree
4. XGBoost
5. MLP
6. Linear regression (worse results than any other modelon all metrics)

#### log_g parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | MIST | scale_power | log_g | -1.083 - 6.259 | 0.411 | 12.707% | 10.177% | 9.067% | 0.641 | 63.136% | 75 : 13.159% / 90 : 20.09% / 95 : 25.591% / 99 : 35.715% | 10.220 |
| decision_tree | MIST | Base | log_g | -1.083 - 6.259 | 0.729 | 8.63% | 2.373% | 0.104% | 0.865 | 77.218% | 75 : 0.262% / 90 : 2.885% / 95 : 18.53% / 99 : 45.586% | 17.940 |
| KNN | MIST | scale_quantile | log_g | -1.083 - 6.259 | 0.875 | 5.861% | 1.746% | 0.073% | 0.936 | 77.199% | 75 : 0.265% / 90 : 4.349% / 95 : 12.511% / 99 : 28.675% | 7.903 |
| random_forest | MIST | scale_quantile | log_g | -1.083 - 6.259 | 0.82 | 7.024% | 2.072% | 0.056% | 0.908 | 77.229% | 75 : 0.251% / 90 : 4.517% / 95 : 15.624% / 99 : 35.338% | 284.082 |
| XGBoost | MIST | Base | log_g | -1.083 - 6.259 | 0.743 | 8.391% | 5.419% | 2.76% | 0.863 | 68.084% | 75 : 8.239% / 90 : 14.63% / 95 : 18.601% / 99 : 26.672% | 17.973 |
| mlp | MIST | scale_power | log_g | -1.083 - 6.259 | 0.766 | 8.004% | 4.61% | 1.574% | 0.876 | 76.124% | 75 : 5.932% / 90 : 13.815% / 95 : 19.027% / 99 : 28.256% | 431.956 |

The best models in order for the log_g from best to worst are:

1. KNN
2. Random forest
3. Decision Tree
4. XGBoost
5. MLP
6. Linear regression (worse results than any other modelon all metrics)

#### Radius parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | MIST | scale_power | radius | -0.997 - 3.129 | 0.602 | 11.286% | 9.059% | 8.273% | 0.776 | 57.275% | 75 : 11.683% / 90 : 17.719% / 95 : 22.492% / 99 : 31.794% | 10.220 |
| decision_tree | MIST | Base | radius | -0.997 - 3.129 | 0.816 | 7.681% | 2.124% | 0.113% | 0.908 | 68.704% | 75 : 0.249% / 90 : 2.572% / 95 : 16.512% / 99 : 40.591% | 17.940 |
| KNN | MIST | scale_quantile | radius | -0.997 - 3.129 | 0.915 | 5.217% | 1.575% | 0.09% | 0.957 | 68.651% | 75 : 0.282% / 90 : 3.872% / 95 : 11.135% / 99 : 25.516% | 7.903 |
| random_forest | MIST | scale_quantile | radius | -0.997 - 3.129 | 0.878 | 6.251% | 1.849% | 0.057% | 0.938 | 68.713% | 75 : 0.232% / 90 : 4.024% / 95 : 13.903% / 99 : 31.453% | 284.082 |
| XGBoost | MIST | Base | radius | -0.997 - 3.129 | 0.825 | 7.479% | 4.815% | 2.424% | 0.909 | 62.531% | 75 : 7.315% / 90 : 13.043% / 95 : 16.629% / 99 : 23.855% | 17.973 |
| mlp | MIST | scale_power | radius | -0.997 - 3.129 | 0.841 | 7.126% | 4.128% | 1.472% | 0.917 | 66.437% | 75 : 5.295% / 90 : 12.279% / 95 : 16.946% / 99 : 25.033% | 431.956 |

The best models in order for the radius from best to worst are:

1. KNN
2. Random forest
3. Decision Tree
4. XGBoost
5. MLP
6. Linear regression (worse results than any other modelon all metrics)

### Models to be fine-tuned

KNN with scale_quantile and Random forest with scale_quantile

## Base vs scaling

### T_eff parameter

In [ ]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                            value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572
KNN               MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572
linear_regression MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572
mlp               MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572
random_forest     MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572
xgboost           MIST           Base           T_eff             3.344668191350628 - 5.378801600728572
                                 scale_standard T_eff             3.344668191350628 - 5.378801600728572
                                 scale_robust   T_eff             3.344668191350628 - 5.378801600728572
                                 scale_power    T_eff             3.344668191350628 - 5.378801600728572
                                 scale_quantile T_eff             3.344668191350628 - 5.378801600728572

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9502050923349665
                                 scale_standard T_eff             0.9501871697841585
                                 scale_robust   T_eff             0.9501050321070466
                                 scale_power    T_eff             0.9501954581041117
                                 scale_quantile T_eff             0.9503835674334257
KNN               MIST           Base           T_eff              0.967329492642253
                                 scale_standard T_eff             0.9758768509839008
                                 scale_robust   T_eff             0.9729752749533875
                                 scale_power    T_eff             0.9765422592204478
                                 scale_quantile T_eff              0.976590460202308
linear_regression MIST           Base           T_eff             0.7355187564971222
                                 scale_standard T_eff             0.7355187564971222
                                 scale_robust   T_eff             0.7355187564971217
                                 scale_power    T_eff             0.7741024913072201
                                 scale_quantile T_eff             0.7663945780063608
mlp               MIST           Base           T_eff             0.8498091378840883
                                 scale_standard T_eff             0.8635374554309876
                                 scale_robust   T_eff             0.8881714136796509
                                 scale_power    T_eff             0.8987982939954424
                                 scale_quantile T_eff             0.8832443429715168
random_forest     MIST           Base           T_eff             0.9671910035107978
                                 scale_standard T_eff              0.967208635099049
                                 scale_robust   T_eff             0.9672023300391356
                                 scale_power    T_eff             0.9671848961945723
                                 scale_quantile T_eff             0.9673109085611591
xgboost           MIST           Base           T_eff              0.900678314457821
                                 scale_standard T_eff             0.9007913390931858
                                 scale_robust   T_eff              0.900779329097207
                                 scale_power    T_eff             0.9008630145382767
                                 scale_quantile T_eff             0.9008167868156934

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             3.794%
                                 scale_standard T_eff             3.794%
                                 scale_robust   T_eff             3.797%
                                 scale_power    T_eff             3.794%
                                 scale_quantile T_eff             3.787%
KNN               MIST           Base           T_eff             3.075%
                                 scale_standard T_eff             2.641%
                                 scale_robust   T_eff             2.796%
                                 scale_power    T_eff             2.604%
                                 scale_quantile T_eff             2.601%
linear_regression MIST           Base           T_eff             8.743%
                                 scale_standard T_eff             8.743%
                                 scale_robust   T_eff             8.743%
                                 scale_power    T_eff              8.08%
                                 scale_quantile T_eff             8.216%
mlp               MIST           Base           T_eff             6.617%
                                 scale_standard T_eff             6.327%
                                 scale_robust   T_eff             5.692%
                                 scale_power    T_eff             5.441%
                                 scale_quantile T_eff             5.822%
random_forest     MIST           Base           T_eff             3.079%
                                 scale_standard T_eff             3.079%
                                 scale_robust   T_eff             3.079%
                                 scale_power    T_eff              3.08%
                                 scale_quantile T_eff             3.074%
xgboost           MIST           Base           T_eff             5.357%
                                 scale_standard T_eff             5.354%
                                 scale_robust   T_eff             5.355%
                                 scale_power    T_eff             5.352%
                                 scale_quantile T_eff             5.354%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.913%
                                 scale_standard T_eff             0.913%
                                 scale_robust   T_eff             0.915%
                                 scale_power    T_eff             0.914%
                                 scale_quantile T_eff             0.912%
KNN               MIST           Base           T_eff             0.915%
                                 scale_standard T_eff             0.725%
                                 scale_robust   T_eff             0.789%
                                 scale_power    T_eff             0.686%
                                 scale_quantile T_eff              0.69%
linear_regression MIST           Base           T_eff             7.068%
                                 scale_standard T_eff             7.068%
                                 scale_robust   T_eff             7.068%
                                 scale_power    T_eff             6.191%
                                 scale_quantile T_eff             6.306%
mlp               MIST           Base           T_eff             4.513%
                                 scale_standard T_eff             4.459%
                                 scale_robust   T_eff             3.682%
                                 scale_power    T_eff             3.674%
                                 scale_quantile T_eff             3.739%
random_forest     MIST           Base           T_eff             0.792%
                                 scale_standard T_eff             0.792%
                                 scale_robust   T_eff             0.792%
                                 scale_power    T_eff             0.791%
                                 scale_quantile T_eff              0.79%
xgboost           MIST           Base           T_eff             3.387%
                                 scale_standard T_eff             3.384%
                                 scale_robust   T_eff             3.382%
                                 scale_power    T_eff             3.376%
                                 scale_quantile T_eff             3.383%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.086%
                                 scale_standard T_eff             0.086%
                                 scale_robust   T_eff             0.086%
                                 scale_power    T_eff             0.086%
                                 scale_quantile T_eff             0.086%
KNN               MIST           Base           T_eff             0.083%
                                 scale_standard T_eff              0.09%
                                 scale_robust   T_eff             0.084%
                                 scale_power    T_eff             0.079%
                                 scale_quantile T_eff             0.083%
linear_regression MIST           Base           T_eff             6.468%
                                 scale_standard T_eff             6.468%
                                 scale_robust   T_eff             6.468%
                                 scale_power    T_eff             5.401%
                                 scale_quantile T_eff             5.444%
mlp               MIST           Base           T_eff             2.709%
                                 scale_standard T_eff             2.965%
                                 scale_robust   T_eff             2.148%
                                 scale_power    T_eff             2.518%
                                 scale_quantile T_eff             2.026%
random_forest     MIST           Base           T_eff              0.05%
                                 scale_standard T_eff              0.05%
                                 scale_robust   T_eff              0.05%
                                 scale_power    T_eff              0.05%
                                 scale_quantile T_eff             0.051%
xgboost           MIST           Base           T_eff             1.698%
                                 scale_standard T_eff              1.69%
                                 scale_robust   T_eff              1.69%
                                 scale_power    T_eff             1.676%
                                 scale_quantile T_eff             1.692%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9751306779168328
                                 scale_standard T_eff             0.9751227021017657
                                 scale_robust   T_eff              0.975080769304039
                                 scale_power    T_eff             0.9751278582374941
                                 scale_quantile T_eff             0.9752204310675738
KNN               MIST           Base           T_eff             0.9835300833228364
                                 scale_standard T_eff              0.987871516338093
                                 scale_robust   T_eff             0.9863975088206922
                                 scale_power    T_eff             0.9882136179053675
                                 scale_quantile T_eff             0.9882381622051759
linear_regression MIST           Base           T_eff             0.8576239015725322
                                 scale_standard T_eff             0.8576239015725321
                                 scale_robust   T_eff              0.857623901572532
                                 scale_power    T_eff             0.8798309447355699
                                 scale_quantile T_eff             0.8754396484598674
mlp               MIST           Base           T_eff             0.9219059878986472
                                 scale_standard T_eff             0.9299270010011824
                                 scale_robust   T_eff             0.9430132388589794
                                 scale_power    T_eff             0.9482644094626318
                                 scale_quantile T_eff             0.9398882058318869
random_forest     MIST           Base           T_eff             0.9835135887268114
                                 scale_standard T_eff             0.9835227118683182
                                 scale_robust   T_eff              0.983519003579004
                                 scale_power    T_eff             0.9835110145112257
                                 scale_quantile T_eff             0.9835739836275601
xgboost           MIST           Base           T_eff             0.9490879339478984
                                 scale_standard T_eff              0.949147347472418
                                 scale_robust   T_eff             0.9491421054938405
                                 scale_power    T_eff             0.9491859145821268
                                 scale_quantile T_eff             0.9491623037842996

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             46.738%
                                 scale_standard T_eff             46.738%
                                 scale_robust   T_eff             46.738%
                                 scale_power    T_eff             46.738%
                                 scale_quantile T_eff             46.738%
KNN               MIST           Base           T_eff             45.544%
                                 scale_standard T_eff             45.125%
                                 scale_robust   T_eff             45.235%
                                 scale_power    T_eff             45.037%
                                 scale_quantile T_eff             45.011%
linear_regression MIST           Base           T_eff             48.277%
                                 scale_standard T_eff             48.277%
                                 scale_robust   T_eff             48.277%
                                 scale_power    T_eff              46.38%
                                 scale_quantile T_eff             45.022%
mlp               MIST           Base           T_eff             48.032%
                                 scale_standard T_eff             54.314%
                                 scale_robust   T_eff             56.139%
                                 scale_power    T_eff             45.953%
                                 scale_quantile T_eff             45.477%
random_forest     MIST           Base           T_eff             45.871%
                                 scale_standard T_eff             45.583%
                                 scale_robust   T_eff             45.485%
                                 scale_power    T_eff             45.787%
                                 scale_quantile T_eff             45.473%
xgboost           MIST           Base           T_eff             42.951%
                                 scale_standard T_eff             43.032%
                                 scale_robust   T_eff             43.099%
                                 scale_power    T_eff             42.485%
                                 scale_quantile T_eff             41.433%

                                                                                                               Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff                75 : 0.21% / 90 : 1.065% / 95 : 4.791% / 99 : 20.817%
                                 scale_standard T_eff                 75 : 0.21% / 90 : 1.065% / 95 : 4.781% / 99 : 20.85%
                                 scale_robust   T_eff                  75 : 0.21% / 90 : 1.072% / 95 : 4.8% / 99 : 20.848%
                                 scale_power    T_eff                 75 : 0.21% / 90 : 1.07% / 95 : 4.793% / 99 : 20.817%
                                 scale_quantile T_eff                75 : 0.21% / 90 : 1.061% / 95 : 4.781% / 99 : 20.764%
KNN               MIST           Base           T_eff               75 : 0.306% / 90 : 2.294% / 95 : 4.907% / 99 : 15.408%
                                 scale_standard T_eff               75 : 0.257% / 90 : 1.528% / 95 : 3.768% / 99 : 12.235%
                                 scale_robust   T_eff               75 : 0.267% / 90 : 1.795% / 95 : 4.208% / 99 : 13.652%
                                 scale_power    T_eff               75 : 0.206% / 90 : 1.377% / 95 : 3.596% / 99 : 12.032%
                                 scale_quantile T_eff                75 : 0.216% / 90 : 1.38% / 95 : 3.595% / 99 : 12.027%
linear_regression MIST           Base           T_eff              75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 scale_standard T_eff              75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 scale_robust   T_eff              75 : 9.795% / 90 : 12.91% / 95 : 16.465% / 99 : 24.342%
                                 scale_power    T_eff             75 : 8.004% / 90 : 11.298% / 95 : 16.575% / 99 : 26.884%

Results for the phase category with a value of 0.0

                                                                                           value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253
KNN               MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253
linear_regression MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253
mlp               MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253
random_forest     MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253
xgboost           MIST           Base           T_eff             3.344668191350628 - 4.90340707004253
                                 scale_standard T_eff             3.344668191350628 - 4.90340707004253
                                 scale_robust   T_eff             3.344668191350628 - 4.90340707004253
                                 scale_power    T_eff             3.344668191350628 - 4.90340707004253
                                 scale_quantile T_eff             3.344668191350628 - 4.90340707004253

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9601890918163569
                                 scale_standard T_eff             0.9600898418075682
                                 scale_robust   T_eff              0.959976466104702
                                 scale_power    T_eff             0.9601523820454696
                                 scale_quantile T_eff             0.9603800772684251
KNN               MIST           Base           T_eff             0.9690034666098396
                                 scale_standard T_eff             0.9795972895047481
                                 scale_robust   T_eff             0.9758093827265293
                                 scale_power    T_eff             0.9804756634381895
                                 scale_quantile T_eff             0.9805307662414631
linear_regression MIST           Base           T_eff             0.7503697754371101
                                 scale_standard T_eff             0.7503697754371119
                                 scale_robust   T_eff             0.7503697754371128
                                 scale_power    T_eff             0.8842253627890934
                                 scale_quantile T_eff             0.8776469903235318
mlp               MIST           Base           T_eff             0.8894177020501132
                                 scale_standard T_eff              0.891355030967779
                                 scale_robust   T_eff             0.9270646642584757
                                 scale_power    T_eff             0.9301492649805465
                                 scale_quantile T_eff             0.9301163502931963
random_forest     MIST           Base           T_eff             0.9741964262283933
                                 scale_standard T_eff             0.9741732182997672
                                 scale_robust   T_eff             0.9741910192801136
                                 scale_power    T_eff             0.9741790168630927
                                 scale_quantile T_eff              0.974284415249455
xgboost           MIST           Base           T_eff             0.9410078232448617
                                 scale_standard T_eff             0.9411032034414745
                                 scale_robust   T_eff             0.9412845284241762
                                 scale_power    T_eff             0.9411979038677618
                                 scale_quantile T_eff             0.9410809021703103

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff              4.513%
                                 scale_standard T_eff              4.519%
                                 scale_robust   T_eff              4.526%
                                 scale_power    T_eff              4.515%
                                 scale_quantile T_eff              4.503%
KNN               MIST           Base           T_eff              4.019%
                                 scale_standard T_eff              3.237%
                                 scale_robust   T_eff              3.533%
                                 scale_power    T_eff              3.163%
                                 scale_quantile T_eff              3.159%
linear_regression MIST           Base           T_eff             11.462%
                                 scale_standard T_eff             11.462%
                                 scale_robust   T_eff             11.462%
                                 scale_power    T_eff              8.834%
                                 scale_quantile T_eff              9.049%
mlp               MIST           Base           T_eff              8.101%
                                 scale_standard T_eff              7.454%
                                 scale_robust   T_eff              6.179%
                                 scale_power    T_eff              5.967%
                                 scale_quantile T_eff              6.073%
random_forest     MIST           Base           T_eff              3.639%
                                 scale_standard T_eff              3.641%
                                 scale_robust   T_eff              3.639%
                                 scale_power    T_eff               3.64%
                                 scale_quantile T_eff              3.633%
xgboost           MIST           Base           T_eff              5.911%
                                 scale_standard T_eff              5.904%
                                 scale_robust   T_eff              5.896%
                                 scale_power    T_eff              5.896%
                                 scale_quantile T_eff              5.905%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.748%
                                 scale_standard T_eff              0.75%
                                 scale_robust   T_eff             0.751%
                                 scale_power    T_eff              0.75%
                                 scale_quantile T_eff             0.747%
KNN               MIST           Base           T_eff             1.011%
                                 scale_standard T_eff             0.669%
                                 scale_robust   T_eff             0.791%
                                 scale_power    T_eff             0.584%
                                 scale_quantile T_eff             0.592%
linear_regression MIST           Base           T_eff             9.801%
                                 scale_standard T_eff             9.801%
                                 scale_robust   T_eff             9.801%
                                 scale_power    T_eff             7.453%
                                 scale_quantile T_eff             7.612%
mlp               MIST           Base           T_eff             5.204%
                                 scale_standard T_eff             5.118%
                                 scale_robust   T_eff             3.744%
                                 scale_power    T_eff             4.011%
                                 scale_quantile T_eff             3.588%
random_forest     MIST           Base           T_eff             0.657%
                                 scale_standard T_eff             0.657%
                                 scale_robust   T_eff             0.657%
                                 scale_power    T_eff             0.657%
                                 scale_quantile T_eff             0.656%
xgboost           MIST           Base           T_eff             3.262%
                                 scale_standard T_eff             3.251%
                                 scale_robust   T_eff             3.248%
                                 scale_power    T_eff             3.243%
                                 scale_quantile T_eff             3.257%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.074%
                                 scale_standard T_eff             0.074%
                                 scale_robust   T_eff             0.074%
                                 scale_power    T_eff             0.074%
                                 scale_quantile T_eff             0.074%
KNN               MIST           Base           T_eff             0.076%
                                 scale_standard T_eff             0.094%
                                 scale_robust   T_eff             0.082%
                                 scale_power    T_eff             0.079%
                                 scale_quantile T_eff             0.082%
linear_regression MIST           Base           T_eff             9.871%
                                 scale_standard T_eff             9.871%
                                 scale_robust   T_eff             9.871%
                                 scale_power    T_eff             7.665%
                                 scale_quantile T_eff             7.636%
mlp               MIST           Base           T_eff             2.706%
                                 scale_standard T_eff             3.213%
                                 scale_robust   T_eff             2.152%
                                 scale_power    T_eff              2.97%
                                 scale_quantile T_eff             1.893%
random_forest     MIST           Base           T_eff             0.037%
                                 scale_standard T_eff             0.037%
                                 scale_robust   T_eff             0.037%
                                 scale_power    T_eff             0.037%
                                 scale_quantile T_eff             0.039%
xgboost           MIST           Base           T_eff             1.032%
                                 scale_standard T_eff              1.02%
                                 scale_robust   T_eff             1.019%
                                 scale_power    T_eff              1.02%
                                 scale_quantile T_eff             1.027%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff              0.980305799388707
                                 scale_standard T_eff             0.9802579096071886
                                 scale_robust   T_eff             0.9802015626550209
                                 scale_power    T_eff             0.9802905465241833
                                 scale_quantile T_eff              0.980401371100485
KNN               MIST           Base           T_eff             0.9843805681802057
                                 scale_standard T_eff             0.9897827730900279
                                 scale_robust   T_eff             0.9878436525681992
                                 scale_power    T_eff             0.9902447996113808
                                 scale_quantile T_eff              0.990274803695282
linear_regression MIST           Base           T_eff              0.866261429421513
                                 scale_standard T_eff             0.8662614294215141
                                 scale_robust   T_eff              0.866261429421515
                                 scale_power    T_eff             0.9414995523610266
                                 scale_quantile T_eff              0.938506539021327
mlp               MIST           Base           T_eff             0.9434861861259601
                                 scale_standard T_eff             0.9475718500815937
                                 scale_robust   T_eff             0.9640408595762875
                                 scale_power    T_eff             0.9652979820066797
                                 scale_quantile T_eff             0.9648971639094235
random_forest     MIST           Base           T_eff             0.9871344752716238
                                 scale_standard T_eff              0.987123447532878
                                 scale_robust   T_eff             0.9871313567754358
                                 scale_power    T_eff             0.9871268181464751
                                 scale_quantile T_eff             0.9871786907114718
xgboost           MIST           Base           T_eff             0.9703350629066066
                                 scale_standard T_eff              0.970382156964214
                                 scale_robust   T_eff             0.9704570973123287
                                 scale_power    T_eff             0.9704129128295416
                                 scale_quantile T_eff             0.9703614392032379

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             60.992%
                                 scale_standard T_eff             60.992%
                                 scale_robust   T_eff             60.992%
                                 scale_power    T_eff             60.992%
                                 scale_quantile T_eff             60.992%
KNN               MIST           Base           T_eff             59.435%
                                 scale_standard T_eff             58.772%
                                 scale_robust   T_eff             58.539%
                                 scale_power    T_eff             58.772%
                                 scale_quantile T_eff             58.739%
linear_regression MIST           Base           T_eff             45.923%
                                 scale_standard T_eff             45.923%
                                 scale_robust   T_eff             45.923%
                                 scale_power    T_eff             43.908%
                                 scale_quantile T_eff               44.8%
mlp               MIST           Base           T_eff             51.339%
                                 scale_standard T_eff             58.735%
                                 scale_robust   T_eff             53.194%
                                 scale_power    T_eff             52.553%
                                 scale_quantile T_eff             45.393%
random_forest     MIST           Base           T_eff             57.571%
                                 scale_standard T_eff             58.778%
                                 scale_robust   T_eff             57.537%
                                 scale_power    T_eff             58.141%
                                 scale_quantile T_eff             58.699%
xgboost           MIST           Base           T_eff             51.931%
                                 scale_standard T_eff             50.076%
                                 scale_robust   T_eff             51.182%
                                 scale_power    T_eff             49.909%
                                 scale_quantile T_eff             50.415%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff                75 : 0.164% / 90 : 0.303% / 95 : 0.753% / 99 : 25.967%
                                 scale_standard T_eff                75 : 0.166% / 90 : 0.305% / 95 : 0.757% / 99 : 26.155%
                                 scale_robust   T_eff                75 : 0.164% / 90 : 0.304% / 95 : 0.762% / 99 : 26.202%
                                 scale_power    T_eff                75 : 0.165% / 90 : 0.305% / 95 : 0.762% / 99 : 26.051%
                                 scale_quantile T_eff                75 : 0.166% / 90 : 0.305% / 95 : 0.751% / 99 : 25.618%
KNN               MIST           Base           T_eff                75 : 0.209% / 90 : 1.196% / 95 : 5.921% / 99 : 21.055%
                                 scale_standard T_eff                75 : 0.203% / 90 : 0.477% / 95 : 1.816% / 99 : 16.089%
                                 scale_robust   T_eff                75 : 0.195% / 90 : 0.581% / 95 : 3.809% / 99 : 18.726%
                                 scale_power    T_eff                   75 : 0.158% / 90 : 0.3% / 95 : 0.59% / 99 : 15.713%
                                 scale_quantile T_eff                75 : 0.168% / 90 : 0.324% / 95 : 0.715% / 99 : 15.717%
linear_regression MIST           Base           T_eff             75 : 13.496% / 90 : 16.477% / 95 : 19.368% / 99 : 28.077%
                                 scale_standard T_eff             75 : 13.496% / 90 : 16.477% / 95 : 19.368% / 99 : 28.077%
                                 scale_robust   T_eff             75 : 13.496% / 90 : 16.477% / 95 : 19.368% / 99 : 28.077%
                                 scale_power    T_eff               75 : 10.195% / 90 : 12.031% / 95 : 13.58% / 99 : 24.96%

Results for the phase category with a value of 2.0

                                                                                           value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716
KNN               MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716
linear_regression MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716
mlp               MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716
random_forest     MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716
xgboost           MIST           Base           T_eff             3.42785685311742 - 4.711472733477716
                                 scale_standard T_eff             3.42785685311742 - 4.711472733477716
                                 scale_robust   T_eff             3.42785685311742 - 4.711472733477716
                                 scale_power    T_eff             3.42785685311742 - 4.711472733477716
                                 scale_quantile T_eff             3.42785685311742 - 4.711472733477716

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9590063372020218
                                 scale_standard T_eff             0.9589975428692362
                                 scale_robust   T_eff             0.9589530393867527
                                 scale_power    T_eff             0.9589604262887346
                                 scale_quantile T_eff             0.9591785148023877
KNN               MIST           Base           T_eff              0.983601717255791
                                 scale_standard T_eff             0.9843516318801757
                                 scale_robust   T_eff             0.9837144113445745
                                 scale_power    T_eff              0.984616766946925
                                 scale_quantile T_eff             0.9845943556106616
linear_regression MIST           Base           T_eff               0.78058731167709
                                 scale_standard T_eff             0.7805873116770892
                                 scale_robust   T_eff             0.7805873116770906
                                 scale_power    T_eff              0.795925569215073
                                 scale_quantile T_eff             0.7910034425526862
mlp               MIST           Base           T_eff             0.8418208833372822
                                 scale_standard T_eff             0.8348754196827564
                                 scale_robust   T_eff              0.857706280437711
                                 scale_power    T_eff             0.8711307553976656
                                 scale_quantile T_eff             0.8504797312207428
random_forest     MIST           Base           T_eff             0.9748807497002827
                                 scale_standard T_eff             0.9748377659913344
                                 scale_robust   T_eff             0.9747708835322587
                                 scale_power    T_eff             0.9748517740047027
                                 scale_quantile T_eff             0.9749101598261279
xgboost           MIST           Base           T_eff             0.8743753451121083
                                 scale_standard T_eff             0.8743195401885882
                                 scale_robust   T_eff             0.8742383305147967
                                 scale_power    T_eff              0.874489716153028
                                 scale_quantile T_eff             0.8744853198333601

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff              4.992%
                                 scale_standard T_eff              4.992%
                                 scale_robust   T_eff              4.995%
                                 scale_power    T_eff              4.994%
                                 scale_quantile T_eff              4.981%
KNN               MIST           Base           T_eff              3.157%
                                 scale_standard T_eff              3.084%
                                 scale_robust   T_eff              3.147%
                                 scale_power    T_eff              3.058%
                                 scale_quantile T_eff              3.061%
linear_regression MIST           Base           T_eff             11.559%
                                 scale_standard T_eff             11.559%
                                 scale_robust   T_eff             11.559%
                                 scale_power    T_eff             11.735%
                                 scale_quantile T_eff             11.882%
mlp               MIST           Base           T_eff              9.805%
                                 scale_standard T_eff             10.256%
                                 scale_robust   T_eff              9.374%
                                 scale_power    T_eff              8.972%
                                 scale_quantile T_eff              9.673%
random_forest     MIST           Base           T_eff              3.908%
                                 scale_standard T_eff              3.911%
                                 scale_robust   T_eff              3.916%
                                 scale_power    T_eff               3.91%
                                 scale_quantile T_eff              3.906%
xgboost           MIST           Base           T_eff              8.901%
                                 scale_standard T_eff              8.901%
                                 scale_robust   T_eff              8.902%
                                 scale_power    T_eff              8.891%
                                 scale_quantile T_eff              8.893%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             1.861%
                                 scale_standard T_eff             1.861%
                                 scale_robust   T_eff             1.863%
                                 scale_power    T_eff             1.862%
                                 scale_quantile T_eff             1.858%
KNN               MIST           Base           T_eff             1.312%
                                 scale_standard T_eff             1.289%
                                 scale_robust   T_eff             1.305%
                                 scale_power    T_eff              1.28%
                                 scale_quantile T_eff             1.283%
linear_regression MIST           Base           T_eff             9.263%
                                 scale_standard T_eff             9.263%
                                 scale_robust   T_eff             9.263%
                                 scale_power    T_eff             8.774%
                                 scale_quantile T_eff             8.838%
mlp               MIST           Base           T_eff             7.539%
                                 scale_standard T_eff             7.852%
                                 scale_robust   T_eff             6.851%
                                 scale_power    T_eff             6.542%
                                 scale_quantile T_eff             7.197%
random_forest     MIST           Base           T_eff             1.551%
                                 scale_standard T_eff             1.552%
                                 scale_robust   T_eff             1.552%
                                 scale_power    T_eff             1.552%
                                 scale_quantile T_eff             1.549%
xgboost           MIST           Base           T_eff             6.647%
                                 scale_standard T_eff             6.646%
                                 scale_robust   T_eff             6.642%
                                 scale_power    T_eff             6.634%
                                 scale_quantile T_eff             6.634%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.252%
                                 scale_standard T_eff             0.252%
                                 scale_robust   T_eff             0.252%
                                 scale_power    T_eff             0.252%
                                 scale_quantile T_eff             0.252%
KNN               MIST           Base           T_eff             0.168%
                                 scale_standard T_eff             0.167%
                                 scale_robust   T_eff             0.168%
                                 scale_power    T_eff             0.167%
                                 scale_quantile T_eff              0.17%
linear_regression MIST           Base           T_eff             8.235%
                                 scale_standard T_eff             8.235%
                                 scale_robust   T_eff             8.235%
                                 scale_power    T_eff             6.933%
                                 scale_quantile T_eff             6.859%
mlp               MIST           Base           T_eff              5.97%
                                 scale_standard T_eff             6.168%
                                 scale_robust   T_eff             4.961%
                                 scale_power    T_eff             4.755%
                                 scale_quantile T_eff             5.356%
random_forest     MIST           Base           T_eff             0.163%
                                 scale_standard T_eff             0.164%
                                 scale_robust   T_eff             0.164%
                                 scale_power    T_eff             0.163%
                                 scale_quantile T_eff             0.162%
xgboost           MIST           Base           T_eff             5.052%
                                 scale_standard T_eff             5.049%
                                 scale_robust   T_eff              5.04%
                                 scale_power    T_eff             5.027%
                                 scale_quantile T_eff             5.029%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9794490750411232
                                 scale_standard T_eff                0.9794425035529
                                 scale_robust   T_eff              0.979422173806773
                                 scale_power    T_eff             0.9794262869598029
                                 scale_quantile T_eff             0.9795348158649451
KNN               MIST           Base           T_eff             0.9917713327850771
                                 scale_standard T_eff              0.992151361185105
                                 scale_robust   T_eff             0.9918295166875765
                                 scale_power    T_eff              0.992284111315052
                                 scale_quantile T_eff             0.9922729012911393
linear_regression MIST           Base           T_eff             0.8837977866743568
                                 scale_standard T_eff             0.8837977866743556
                                 scale_robust   T_eff             0.8837977866743549
                                 scale_power    T_eff             0.8921924965928406
                                 scale_quantile T_eff             0.8895476708545759
mlp               MIST           Base           T_eff             0.9176580562848249
                                 scale_standard T_eff             0.9139276566221946
                                 scale_robust   T_eff             0.9264405781300954
                                 scale_power    T_eff             0.9333446000486072
                                 scale_quantile T_eff             0.9222263515967575
random_forest     MIST           Base           T_eff             0.9873643484911543
                                 scale_standard T_eff             0.9873426149349664
                                 scale_robust   T_eff             0.9873089061746222
                                 scale_power    T_eff             0.9873497472698224
                                 scale_quantile T_eff             0.9873793086840453
xgboost           MIST           Base           T_eff             0.9357988163202772
                                 scale_standard T_eff             0.9357671319435953
                                 scale_robust   T_eff             0.9356980450899091
                                 scale_power    T_eff             0.9358520653482332
                                 scale_quantile T_eff             0.9358424119856497

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             65.993%
                                 scale_standard T_eff             65.993%
                                 scale_robust   T_eff             65.993%
                                 scale_power    T_eff             65.993%
                                 scale_quantile T_eff             65.993%
KNN               MIST           Base           T_eff             55.511%
                                 scale_standard T_eff             55.511%
                                 scale_robust   T_eff             55.511%
                                 scale_power    T_eff             55.511%
                                 scale_quantile T_eff             55.511%
linear_regression MIST           Base           T_eff             49.184%
                                 scale_standard T_eff             49.184%
                                 scale_robust   T_eff             49.184%
                                 scale_power    T_eff             51.185%
                                 scale_quantile T_eff             50.989%
mlp               MIST           Base           T_eff              50.91%
                                 scale_standard T_eff             51.593%
                                 scale_robust   T_eff             51.963%
                                 scale_power    T_eff             48.269%
                                 scale_quantile T_eff             47.734%
random_forest     MIST           Base           T_eff             55.516%
                                 scale_standard T_eff             56.269%
                                 scale_robust   T_eff             58.042%
                                 scale_power    T_eff             56.238%
                                 scale_quantile T_eff             54.965%
xgboost           MIST           Base           T_eff             39.721%
                                 scale_standard T_eff             39.066%
                                 scale_robust   T_eff             39.017%
                                 scale_power    T_eff             38.357%
                                 scale_quantile T_eff             39.463%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff               75 : 0.615% / 90 : 6.421% / 95 : 10.746% / 99 : 18.373%
                                 scale_standard T_eff               75 : 0.612% / 90 : 6.422% / 95 : 10.742% / 99 : 18.367%
                                 scale_robust   T_eff               75 : 0.618% / 90 : 6.432% / 95 : 10.734% / 99 : 18.376%
                                 scale_power    T_eff                75 : 0.613% / 90 : 6.426% / 95 : 10.738% / 99 : 18.36%
                                 scale_quantile T_eff                75 : 0.615% / 90 : 6.417% / 95 : 10.72% / 99 : 18.314%
KNN               MIST           Base           T_eff                75 : 0.847% / 90 : 4.461% / 95 : 7.144% / 99 : 12.727%
                                 scale_standard T_eff                75 : 0.815% / 90 : 4.408% / 95 : 7.072% / 99 : 12.582%
                                 scale_robust   T_eff                75 : 0.834% / 90 : 4.437% / 95 : 7.117% / 99 : 12.681%
                                 scale_power    T_eff                75 : 0.802% / 90 : 4.389% / 95 : 7.043% / 99 : 12.498%
                                 scale_quantile T_eff                75 : 0.815% / 90 : 4.392% / 95 : 7.026% / 99 : 12.603%
linear_regression MIST           Base           T_eff             75 : 12.922% / 90 : 17.307% / 95 : 22.084% / 99 : 33.316%
                                 scale_standard T_eff             75 : 12.922% / 90 : 17.307% / 95 : 22.084% / 99 : 33.316%
                                 scale_robust   T_eff             75 : 12.922% / 90 : 17.307% / 95 : 22.084% / 99 : 33.316%
                                 scale_power    T_eff             75 : 11.173% / 90 : 18.544% / 95 : 25.698% / 99 : 37.767%

Results for the phase category with a value of 3.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572
KNN               MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572
linear_regression MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572
mlp               MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572
random_forest     MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572
xgboost           MIST           Base           T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_standard T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_robust   T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_power    T_eff             3.3516171610778134 - 5.378801600728572
                                 scale_quantile T_eff             3.3516171610778134 - 5.378801600728572

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.8814227303787838
                                 scale_standard T_eff             0.8816482464870106
                                 scale_robust   T_eff             0.8816203219832035
                                 scale_power    T_eff              0.881543304202185
                                 scale_quantile T_eff             0.8816406725502451
KNN               MIST           Base           T_eff             0.9271998783892499
                                 scale_standard T_eff             0.9405843164789971
                                 scale_robust   T_eff             0.9370295787171915
                                 scale_power    T_eff             0.9411755059078774
                                 scale_quantile T_eff              0.941350205906234
linear_regression MIST           Base           T_eff             0.6053377226384591
                                 scale_standard T_eff             0.6053377226384462
                                 scale_robust   T_eff             0.6053377226384227
                                 scale_power    T_eff             0.5766979656357076
                                 scale_quantile T_eff             0.5655410590031273
mlp               MIST           Base           T_eff             0.7621667936835659
                                 scale_standard T_eff             0.7927917344885378
                                 scale_robust   T_eff             0.7833418602490809
                                 scale_power    T_eff              0.805088032866851
                                 scale_quantile T_eff             0.7638403608095855
random_forest     MIST           Base           T_eff             0.9179849306556465
                                 scale_standard T_eff             0.9182314591893198
                                 scale_robust   T_eff             0.9182330568907016
                                 scale_power    T_eff             0.9180335607248322
                                 scale_quantile T_eff             0.9184073321466956
xgboost           MIST           Base           T_eff             0.8380459351877558
                                 scale_standard T_eff             0.8381668583409654
                                 scale_robust   T_eff             0.8378726776760136
                                 scale_power    T_eff             0.8375235445565777
                                 scale_quantile T_eff             0.8384031927832134

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff              5.253%
                                 scale_standard T_eff              5.248%
                                 scale_robust   T_eff              5.249%
                                 scale_power    T_eff               5.25%
                                 scale_quantile T_eff              5.249%
KNN               MIST           Base           T_eff               4.14%
                                 scale_standard T_eff              3.715%
                                 scale_robust   T_eff              3.831%
                                 scale_power    T_eff              3.696%
                                 scale_quantile T_eff              3.691%
linear_regression MIST           Base           T_eff             10.369%
                                 scale_standard T_eff             10.369%
                                 scale_robust   T_eff             10.369%
                                 scale_power    T_eff             11.626%
                                 scale_quantile T_eff             11.769%
mlp               MIST           Base           T_eff              8.159%
                                 scale_standard T_eff              7.653%
                                 scale_robust   T_eff              7.555%
                                 scale_power    T_eff              7.132%
                                 scale_quantile T_eff              7.992%
random_forest     MIST           Base           T_eff              4.373%
                                 scale_standard T_eff              4.366%
                                 scale_robust   T_eff              4.366%
                                 scale_power    T_eff              4.372%
                                 scale_quantile T_eff              4.362%
xgboost           MIST           Base           T_eff              6.925%
                                 scale_standard T_eff              6.923%
                                 scale_robust   T_eff              6.935%
                                 scale_power    T_eff              6.933%
                                 scale_quantile T_eff              6.924%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             1.504%
                                 scale_standard T_eff             1.502%
                                 scale_robust   T_eff             1.504%
                                 scale_power    T_eff             1.504%
                                 scale_quantile T_eff             1.503%
KNN               MIST           Base           T_eff             1.433%
                                 scale_standard T_eff             1.198%
                                 scale_robust   T_eff             1.258%
                                 scale_power    T_eff             1.188%
                                 scale_quantile T_eff             1.191%
linear_regression MIST           Base           T_eff             7.561%
                                 scale_standard T_eff             7.561%
                                 scale_robust   T_eff             7.561%
                                 scale_power    T_eff             8.472%
                                 scale_quantile T_eff             8.673%
mlp               MIST           Base           T_eff             5.663%
                                 scale_standard T_eff             5.286%
                                 scale_robust   T_eff             5.083%
                                 scale_power    T_eff             4.735%
                                 scale_quantile T_eff             5.407%
random_forest     MIST           Base           T_eff             1.342%
                                 scale_standard T_eff             1.342%
                                 scale_robust   T_eff             1.342%
                                 scale_power    T_eff              1.34%
                                 scale_quantile T_eff             1.339%
xgboost           MIST           Base           T_eff             4.761%
                                 scale_standard T_eff             4.767%
                                 scale_robust   T_eff             4.767%
                                 scale_power    T_eff             4.757%
                                 scale_quantile T_eff             4.762%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.169%
                                 scale_standard T_eff             0.171%
                                 scale_robust   T_eff             0.169%
                                 scale_power    T_eff             0.169%
                                 scale_quantile T_eff             0.169%
KNN               MIST           Base           T_eff             0.208%
                                 scale_standard T_eff             0.181%
                                 scale_robust   T_eff             0.187%
                                 scale_power    T_eff             0.181%
                                 scale_quantile T_eff             0.185%
linear_regression MIST           Base           T_eff             5.239%
                                 scale_standard T_eff             5.239%
                                 scale_robust   T_eff             5.239%
                                 scale_power    T_eff             5.773%
                                 scale_quantile T_eff             6.113%
mlp               MIST           Base           T_eff             3.705%
                                 scale_standard T_eff             3.431%
                                 scale_robust   T_eff             3.139%
                                 scale_power    T_eff             2.914%
                                 scale_quantile T_eff              3.41%
random_forest     MIST           Base           T_eff             0.155%
                                 scale_standard T_eff             0.157%
                                 scale_robust   T_eff             0.155%
                                 scale_power    T_eff             0.154%
                                 scale_quantile T_eff             0.155%
xgboost           MIST           Base           T_eff             3.115%
                                 scale_standard T_eff             3.132%
                                 scale_robust   T_eff             3.125%
                                 scale_power    T_eff             3.104%
                                 scale_quantile T_eff             3.121%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             0.9412624782801967
                                 scale_standard T_eff             0.9413786419235035
                                 scale_robust   T_eff              0.941351804429737
                                 scale_power    T_eff              0.941322177623533
                                 scale_quantile T_eff             0.9413803579511083
KNN               MIST           Base           T_eff              0.964029448214006
                                 scale_standard T_eff             0.9700486769443445
                                 scale_robust   T_eff             0.9684109934757318
                                 scale_power    T_eff             0.9703359333322209
                                 scale_quantile T_eff             0.9704206694353663
linear_regression MIST           Base           T_eff             0.7874495752455607
                                 scale_standard T_eff              0.787449575245557
                                 scale_robust   T_eff              0.787449575245552
                                 scale_power    T_eff             0.7832853901626523
                                 scale_quantile T_eff             0.7791987926618806
mlp               MIST           Base           T_eff             0.8780614786223581
                                 scale_standard T_eff             0.8914003518467677
                                 scale_robust   T_eff             0.8900118801267736
                                 scale_power    T_eff             0.8992646873498357
                                 scale_quantile T_eff             0.8771214789206417
random_forest     MIST           Base           T_eff             0.9587327279611804
                                 scale_standard T_eff              0.958853976206325
                                 scale_robust   T_eff             0.9588525826430497
                                 scale_power    T_eff             0.9587548260408851
                                 scale_quantile T_eff             0.9589433657134631
xgboost           MIST           Base           T_eff             0.9155583216400488
                                 scale_standard T_eff             0.9156290855981143
                                 scale_robust   T_eff             0.9154936735878333
                                 scale_power    T_eff              0.915315553700138
                                 scale_quantile T_eff             0.9157596079105613

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff             45.945%
                                 scale_standard T_eff             45.945%
                                 scale_robust   T_eff             45.945%
                                 scale_power    T_eff             45.945%
                                 scale_quantile T_eff             45.945%
KNN               MIST           Base           T_eff             45.223%
                                 scale_standard T_eff              45.28%
                                 scale_robust   T_eff             45.391%
                                 scale_power    T_eff             45.126%
                                 scale_quantile T_eff             45.145%
linear_regression MIST           Base           T_eff             48.443%
                                 scale_standard T_eff             48.443%
                                 scale_robust   T_eff             48.443%
                                 scale_power    T_eff             46.539%
                                 scale_quantile T_eff             45.177%
mlp               MIST           Base           T_eff             48.197%
                                 scale_standard T_eff               54.5%
                                 scale_robust   T_eff             56.332%
                                 scale_power    T_eff             46.111%
                                 scale_quantile T_eff             45.633%
random_forest     MIST           Base           T_eff             46.029%
                                 scale_standard T_eff             45.739%
                                 scale_robust   T_eff             45.641%
                                 scale_power    T_eff             45.944%
                                 scale_quantile T_eff             45.628%
xgboost           MIST           Base           T_eff             43.098%
                                 scale_standard T_eff             43.179%
                                 scale_robust   T_eff             43.247%
                                 scale_power    T_eff             42.631%
                                 scale_quantile T_eff             41.575%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           T_eff                75 : 0.487% / 90 : 2.648% / 95 : 7.824% / 99 : 30.752%
                                 scale_standard T_eff                75 : 0.489% / 90 : 2.588% / 95 : 7.822% / 99 : 30.673%
                                 scale_robust   T_eff                75 : 0.487% / 90 : 2.649% / 95 : 7.841% / 99 : 30.609%
                                 scale_power    T_eff                75 : 0.487% / 90 : 2.648% / 95 : 7.827% / 99 : 30.781%
                                 scale_quantile T_eff                75 : 0.486% / 90 : 2.646% / 95 : 7.836% / 99 : 30.609%
KNN               MIST           Base           T_eff                  75 : 0.946% / 90 : 3.367% / 95 : 7.1% / 99 : 21.672%
                                 scale_standard T_eff                75 : 0.748% / 90 : 2.681% / 95 : 5.456% / 99 : 18.703%
                                 scale_robust   T_eff                75 : 0.789% / 90 : 2.834% / 95 : 5.888% / 99 : 19.918%
                                 scale_power    T_eff                 75 : 0.743% / 90 : 2.649% / 95 : 5.38% / 99 : 18.488%
                                 scale_quantile T_eff                75 : 0.753% / 90 : 2.647% / 95 : 5.391% / 99 : 18.597%
linear_regression MIST           Base           T_eff             75 : 10.441% / 90 : 17.818% / 95 : 22.573% / 99 : 29.899%
                                 scale_standard T_eff             75 : 10.441% / 90 : 17.818% / 95 : 22.573% / 99 : 29.899%
                                 scale_robust   T_eff             75 : 10.441% / 90 : 17.818% / 95 : 22.573% / 99 : 29.899%

### log_g parameter

In [ ]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["MIST"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
KNN               MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
linear_regression MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
mlp               MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
random_forest     MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
xgboost           MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.7285247646204323
                                 scale_standard log_g              0.7288014971778101
                                 scale_robust   log_g              0.7283032019721216
                                 scale_power    log_g              0.7283013507868066
                                 scale_quantile log_g               0.729119851127697
KNN               MIST           Base           log_g              0.8593320998569429
                                 scale_standard log_g              0.8738619944555549
                                 scale_robust   log_g              0.8689608657672727
                                 scale_power    log_g              0.8747295426852866
                                 scale_quantile log_g              0.8748387136161617
linear_regression MIST           Base           log_g             0.12147458541872769
                                 scale_standard log_g             0.12147458541872769
                                 scale_robust   log_g             0.12147458541872791
                                 scale_power    log_g              0.4114284758608032
                                 scale_quantile log_g             0.40526701327376935
mlp               MIST           Base           log_g              0.6418730124942693
                                 scale_standard log_g              0.6832212244513693
                                 scale_robust   log_g              0.7336255006217894
                                 scale_power    log_g              0.7664677331781704
                                 scale_quantile log_g              0.7184506787861439
random_forest     MIST           Base           log_g              0.8198256636371155
                                 scale_standard log_g              0.8198117652444687
                                 scale_robust   log_g              0.8198205470194437
                                 scale_power    log_g              0.8196999826087166
                                 scale_quantile log_g              0.8201852768123867
xgboost           MIST           Base           log_g              0.7433521284066151
                                 scale_standard log_g              0.7433800226211051
                                 scale_robust   log_g               0.742495966284112
                                 scale_power    log_g              0.7429744137483232
                                 scale_quantile log_g              0.7437394518862814

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g               8.63%
                                 scale_standard log_g              8.626%
                                 scale_robust   log_g              8.634%
                                 scale_power    log_g              8.634%
                                 scale_quantile log_g              8.621%
KNN               MIST           Base           log_g              6.216%
                                 scale_standard log_g              5.884%
                                 scale_robust   log_g              5.998%
                                 scale_power    log_g              5.863%
                                 scale_quantile log_g              5.861%
linear_regression MIST           Base           log_g             15.524%
                                 scale_standard log_g             15.524%
                                 scale_robust   log_g             15.524%
                                 scale_power    log_g             12.707%
                                 scale_quantile log_g             12.773%
mlp               MIST           Base           log_g              9.966%
                                 scale_standard log_g              9.328%
                                 scale_robust   log_g              8.553%
                                 scale_power    log_g              8.004%
                                 scale_quantile log_g              8.789%
random_forest     MIST           Base           log_g              7.031%
                                 scale_standard log_g              7.031%
                                 scale_robust   log_g              7.031%
                                 scale_power    log_g              7.034%
                                 scale_quantile log_g              7.024%
xgboost           MIST           Base           log_g              8.391%
                                 scale_standard log_g               8.39%
                                 scale_robust   log_g              8.405%
                                 scale_power    log_g              8.397%
                                 scale_quantile log_g              8.385%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              2.373%
                                 scale_standard log_g              2.371%
                                 scale_robust   log_g              2.375%
                                 scale_power    log_g              2.373%
                                 scale_quantile log_g              2.369%
KNN               MIST           Base           log_g              2.049%
                                 scale_standard log_g              1.774%
                                 scale_robust   log_g              1.869%
                                 scale_power    log_g              1.739%
                                 scale_quantile log_g              1.746%
linear_regression MIST           Base           log_g             12.699%
                                 scale_standard log_g             12.699%
                                 scale_robust   log_g             12.699%
                                 scale_power    log_g             10.177%
                                 scale_quantile log_g             10.215%
mlp               MIST           Base           log_g              6.544%
                                 scale_standard log_g              5.952%
                                 scale_robust   log_g              5.051%
                                 scale_power    log_g               4.61%
                                 scale_quantile log_g              5.268%
random_forest     MIST           Base           log_g              2.075%
                                 scale_standard log_g              2.076%
                                 scale_robust   log_g              2.076%
                                 scale_power    log_g              2.076%
                                 scale_quantile log_g              2.072%
xgboost           MIST           Base           log_g              5.419%
                                 scale_standard log_g              5.415%
                                 scale_robust   log_g               5.43%
                                 scale_power    log_g              5.423%
                                 scale_quantile log_g              5.409%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.104%
                                 scale_standard log_g              0.104%
                                 scale_robust   log_g              0.104%
                                 scale_power    log_g              0.104%
                                 scale_quantile log_g              0.104%
KNN               MIST           Base           log_g              0.085%
                                 scale_standard log_g              0.072%
                                 scale_robust   log_g              0.076%
                                 scale_power    log_g              0.066%
                                 scale_quantile log_g              0.073%
linear_regression MIST           Base           log_g             10.869%
                                 scale_standard log_g             10.869%
                                 scale_robust   log_g             10.869%
                                 scale_power    log_g              9.067%
                                 scale_quantile log_g              9.298%
mlp               MIST           Base           log_g              3.418%
                                 scale_standard log_g              2.765%
                                 scale_robust   log_g              1.777%
                                 scale_power    log_g              1.574%
                                 scale_quantile log_g              1.919%
random_forest     MIST           Base           log_g              0.056%
                                 scale_standard log_g              0.056%
                                 scale_robust   log_g              0.056%
                                 scale_power    log_g              0.056%
                                 scale_quantile log_g              0.056%
xgboost           MIST           Base           log_g               2.76%
                                 scale_standard log_g              2.753%
                                 scale_robust   log_g               2.76%
                                 scale_power    log_g              2.761%
                                 scale_quantile log_g              2.741%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             0.8650177953048179
                                 scale_standard log_g             0.8651572753701307
                                 scale_robust   log_g             0.8649142835133994
                                 scale_power    log_g             0.8649129887571588
                                 scale_quantile log_g             0.8652780012433271
KNN               MIST           Base           log_g             0.9276197914525868
                                 scale_standard log_g             0.9352664511954977
                                 scale_robust   log_g             0.9327036038349381
                                 scale_power    log_g             0.9357199697755355
                                 scale_quantile log_g             0.9357720434156561
linear_regression MIST           Base           log_g             0.3485320446593273
                                 scale_standard log_g             0.3485320446593274
                                 scale_robust   log_g             0.3485320446593273
                                 scale_power    log_g             0.6414269061329517
                                 scale_quantile log_g             0.6366058539474496
mlp               MIST           Base           log_g             0.8016648757290119
                                 scale_standard log_g             0.8266544320624966
                                 scale_robust   log_g             0.8565734915669443
                                 scale_power    log_g             0.8755205045040888
                                 scale_quantile log_g             0.8476261846195673
random_forest     MIST           Base           log_g             0.9076055609149075
                                 scale_standard log_g             0.9076047903066623
                                 scale_robust   log_g             0.9076050289962412
                                 scale_power    log_g             0.9075455018881825
                                 scale_quantile log_g             0.9077888806404456
xgboost           MIST           Base           log_g             0.8626939818756764
                                 scale_standard log_g             0.8627022847844747
                                 scale_robust   log_g             0.8621997660496006
                                 scale_power    log_g             0.8624796161543846
                                 scale_quantile log_g             0.8629241480992709

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             77.218%
                                 scale_standard log_g             77.383%
                                 scale_robust   log_g             77.218%
                                 scale_power    log_g             77.383%
                                 scale_quantile log_g             77.383%
KNN               MIST           Base           log_g             77.248%
                                 scale_standard log_g             77.248%
                                 scale_robust   log_g             77.248%
                                 scale_power    log_g             77.248%
                                 scale_quantile log_g             77.199%
linear_regression MIST           Base           log_g             54.654%
                                 scale_standard log_g             54.654%
                                 scale_robust   log_g             54.654%
                                 scale_power    log_g             63.136%
                                 scale_quantile log_g             66.984%
mlp               MIST           Base           log_g             76.517%
                                 scale_standard log_g              72.56%
                                 scale_robust   log_g             75.547%
                                 scale_power    log_g             76.124%
                                 scale_quantile log_g             76.683%
random_forest     MIST           Base           log_g             77.227%
                                 scale_standard log_g             77.234%
                                 scale_robust   log_g             77.231%
                                 scale_power    log_g              77.23%
                                 scale_quantile log_g             77.229%
xgboost           MIST           Base           log_g             68.084%
                                 scale_standard log_g             66.779%
                                 scale_robust   log_g             66.018%
                                 scale_power    log_g             68.798%
                                 scale_quantile log_g             65.332%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g                75 : 0.262% / 90 : 2.885% / 95 : 18.53% / 99 : 45.586%
                                 scale_standard log_g                75 : 0.263% / 90 : 2.908% / 95 : 18.489% / 99 : 45.59%
                                 scale_robust   log_g               75 : 0.262% / 90 : 2.896% / 95 : 18.571% / 99 : 45.576%
                                 scale_power    log_g                75 : 0.262% / 90 : 2.885% / 95 : 18.541% / 99 : 45.59%
                                 scale_quantile log_g               75 : 0.262% / 90 : 2.858% / 95 : 18.504% / 99 : 45.527%
KNN               MIST           Base           log_g               75 : 0.433% / 90 : 6.332% / 95 : 13.921% / 99 : 29.556%
                                 scale_standard log_g                75 : 0.27% / 90 : 4.609% / 95 : 12.548% / 99 : 28.692%
                                 scale_robust   log_g               75 : 0.315% / 90 : 5.288% / 95 : 13.027% / 99 : 28.965%
                                 scale_power    log_g                75 : 0.243% / 90 : 4.34% / 95 : 12.489% / 99 : 28.689%
                                 scale_quantile log_g               75 : 0.265% / 90 : 4.349% / 95 : 12.511% / 99 : 28.675%
linear_regression MIST           Base           log_g             75 : 16.932% / 90 : 25.249% / 95 : 30.511% / 99 : 41.111%
                                 scale_standard log_g             75 : 16.932% / 90 : 25.249% / 95 : 30.511% / 99 : 41.111%

Results for the phase category with a value of 0.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307
KNN               MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307
linear_regression MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307
mlp               MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307
random_forest     MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307
xgboost           MIST           Base           log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_standard log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_robust   log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_power    log_g             -0.5967768342670462 - 5.433070637654307
                                 scale_quantile log_g             -0.5967768342670462 - 5.433070637654307

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.45836693468175915
                                 scale_standard log_g              0.45749390103105436
                                 scale_robust   log_g              0.45651979642145146
                                 scale_power    log_g              0.45740611827176303
                                 scale_quantile log_g               0.4611116829745463
KNN               MIST           Base           log_g               0.6553166931256764
                                 scale_standard log_g               0.7240932323440599
                                 scale_robust   log_g               0.6994491226506004
                                 scale_power    log_g               0.7282076009653046
                                 scale_quantile log_g               0.7299559107290954
linear_regression MIST           Base           log_g              -0.0611340641093332
                                 scale_standard log_g             -0.06113406410934452
                                 scale_robust   log_g             -0.06113406410938116
                                 scale_power    log_g             -0.12300587991780687
                                 scale_quantile log_g             -0.17479167445925192
mlp               MIST           Base           log_g              0.15799191189495787
                                 scale_standard log_g              0.36370262337147663
                                 scale_robust   log_g                0.404804456462337
                                 scale_power    log_g              0.49025894409040494
                                 scale_quantile log_g              0.39673337884952586
random_forest     MIST           Base           log_g                0.655638939150234
                                 scale_standard log_g               0.6551770944148279
                                 scale_robust   log_g               0.6553960865834342
                                 scale_power    log_g                0.655578527090177
                                 scale_quantile log_g               0.6563309508568553
xgboost           MIST           Base           log_g               0.4471727368192875
                                 scale_standard log_g              0.44691654666339886
                                 scale_robust   log_g              0.44370923416826025
                                 scale_power    log_g              0.44725040714391595
                                 scale_quantile log_g              0.44645242431657517

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              7.691%
                                 scale_standard log_g              7.697%
                                 scale_robust   log_g              7.704%
                                 scale_power    log_g              7.698%
                                 scale_quantile log_g              7.671%
KNN               MIST           Base           log_g              6.202%
                                 scale_standard log_g              5.504%
                                 scale_robust   log_g              5.761%
                                 scale_power    log_g              5.459%
                                 scale_quantile log_g              5.441%
linear_regression MIST           Base           log_g             16.848%
                                 scale_standard log_g             16.848%
                                 scale_robust   log_g             16.848%
                                 scale_power    log_g             13.554%
                                 scale_quantile log_g             13.693%
mlp               MIST           Base           log_g             10.811%
                                 scale_standard log_g              9.031%
                                 scale_robust   log_g              8.305%
                                 scale_power    log_g               7.71%
                                 scale_quantile log_g              8.542%
random_forest     MIST           Base           log_g              6.152%
                                 scale_standard log_g              6.155%
                                 scale_robust   log_g              6.154%
                                 scale_power    log_g              6.152%
                                 scale_quantile log_g              6.145%
xgboost           MIST           Base           log_g              8.431%
                                 scale_standard log_g              8.429%
                                 scale_robust   log_g              8.461%
                                 scale_power    log_g              8.431%
                                 scale_quantile log_g              8.428%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              1.234%
                                 scale_standard log_g              1.235%
                                 scale_robust   log_g              1.237%
                                 scale_power    log_g              1.235%
                                 scale_quantile log_g              1.228%
KNN               MIST           Base           log_g              1.497%
                                 scale_standard log_g              1.022%
                                 scale_robust   log_g              1.197%
                                 scale_power    log_g              0.953%
                                 scale_quantile log_g              0.963%
linear_regression MIST           Base           log_g             14.486%
                                 scale_standard log_g             14.486%
                                 scale_robust   log_g             14.486%
                                 scale_power    log_g             11.678%
                                 scale_quantile log_g             11.909%
mlp               MIST           Base           log_g               6.16%
                                 scale_standard log_g              4.956%
                                 scale_robust   log_g               3.71%
                                 scale_power    log_g              3.334%
                                 scale_quantile log_g              3.936%
random_forest     MIST           Base           log_g              1.131%
                                 scale_standard log_g               1.13%
                                 scale_robust   log_g              1.132%
                                 scale_power    log_g               1.13%
                                 scale_quantile log_g              1.128%
xgboost           MIST           Base           log_g              4.703%
                                 scale_standard log_g              4.702%
                                 scale_robust   log_g              4.729%
                                 scale_power    log_g               4.71%
                                 scale_quantile log_g              4.699%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.069%
                                 scale_standard log_g              0.068%
                                 scale_robust   log_g              0.068%
                                 scale_power    log_g              0.068%
                                 scale_quantile log_g              0.068%
KNN               MIST           Base           log_g              0.054%
                                 scale_standard log_g              0.048%
                                 scale_robust   log_g              0.049%
                                 scale_power    log_g              0.041%
                                 scale_quantile log_g              0.046%
linear_regression MIST           Base           log_g             13.262%
                                 scale_standard log_g             13.262%
                                 scale_robust   log_g             13.262%
                                 scale_power    log_g             11.581%
                                 scale_quantile log_g             12.308%
mlp               MIST           Base           log_g              1.228%
                                 scale_standard log_g              1.694%
                                 scale_robust   log_g              0.953%
                                 scale_power    log_g              0.989%
                                 scale_quantile log_g              0.896%
random_forest     MIST           Base           log_g              0.029%
                                 scale_standard log_g              0.029%
                                 scale_robust   log_g              0.029%
                                 scale_power    log_g              0.029%
                                 scale_quantile log_g              0.029%
xgboost           MIST           Base           log_g              1.382%
                                 scale_standard log_g              1.381%
                                 scale_robust   log_g              1.392%
                                 scale_power    log_g              1.395%
                                 scale_quantile log_g              1.389%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.8064994593089099
                                 scale_standard log_g              0.8062207393762549
                                 scale_robust   log_g              0.8060527588349902
                                 scale_power    log_g              0.8062874619439341
                                 scale_quantile log_g              0.8070422546237424
KNN               MIST           Base           log_g              0.8672941111598133
                                 scale_standard log_g              0.8867512302011042
                                 scale_robust   log_g              0.8796946959060437
                                 scale_power    log_g              0.8877096449591447
                                 scale_quantile log_g              0.8884189357626322
linear_regression MIST           Base           log_g             0.29813341758804923
                                 scale_standard log_g             0.29813341758803996
                                 scale_robust   log_g              0.2981334175880259
                                 scale_power    log_g              0.6361928696408995
                                 scale_quantile log_g              0.6142673652047831
mlp               MIST           Base           log_g              0.7783008265777945
                                 scale_standard log_g              0.8037987558914559
                                 scale_robust   log_g              0.8055732769696478
                                 scale_power    log_g              0.8200690803715617
                                 scale_quantile log_g               0.807208078815741
random_forest     MIST           Base           log_g               0.863807624437327
                                 scale_standard log_g              0.8636357039072204
                                 scale_robust   log_g              0.8637320950847849
                                 scale_power    log_g              0.8637955961746254
                                 scale_quantile log_g              0.8639749511783242
xgboost           MIST           Base           log_g              0.8353265916677893
                                 scale_standard log_g              0.8354414595009478
                                 scale_robust   log_g               0.834795780639791
                                 scale_power    log_g              0.8355283484911415
                                 scale_quantile log_g              0.8348530960370989

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             93.993%
                                 scale_standard log_g             94.227%
                                 scale_robust   log_g             93.993%
                                 scale_power    log_g             94.227%
                                 scale_quantile log_g             94.227%
KNN               MIST           Base           log_g             92.419%
                                 scale_standard log_g             92.419%
                                 scale_robust   log_g             92.419%
                                 scale_power    log_g             92.419%
                                 scale_quantile log_g             92.419%
linear_regression MIST           Base           log_g             63.177%
                                 scale_standard log_g             63.177%
                                 scale_robust   log_g             63.177%
                                 scale_power    log_g             58.147%
                                 scale_quantile log_g             59.211%
mlp               MIST           Base           log_g             63.373%
                                 scale_standard log_g             64.458%
                                 scale_robust   log_g             68.473%
                                 scale_power    log_g             75.602%
                                 scale_quantile log_g             79.431%
random_forest     MIST           Base           log_g             92.553%
                                 scale_standard log_g             92.535%
                                 scale_robust   log_g             92.573%
                                 scale_power    log_g             92.568%
                                 scale_quantile log_g             92.457%
xgboost           MIST           Base           log_g             81.019%
                                 scale_standard log_g             81.314%
                                 scale_robust   log_g             78.302%
                                 scale_power    log_g             83.037%
                                 scale_quantile log_g             79.553%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g                75 : 0.137% / 90 : 0.285% / 95 : 0.605% / 99 : 51.335%
                                 scale_standard log_g                75 : 0.137% / 90 : 0.285% / 95 : 0.608% / 99 : 51.344%
                                 scale_robust   log_g                75 : 0.137% / 90 : 0.284% / 95 : 0.609% / 99 : 51.439%
                                 scale_power    log_g                75 : 0.137% / 90 : 0.285% / 95 : 0.615% / 99 : 51.344%
                                 scale_quantile log_g                75 : 0.137% / 90 : 0.284% / 95 : 0.606% / 99 : 51.166%
KNN               MIST           Base           log_g                  75 : 0.17% / 90 : 1.498% / 95 : 9.04% / 99 : 32.781%
                                 scale_standard log_g                 75 : 0.115% / 90 : 0.306% / 95 : 2.04% / 99 : 29.824%
                                 scale_robust   log_g                75 : 0.129% / 90 : 0.506% / 95 : 5.218% / 99 : 30.575%
                                 scale_power    log_g                  75 : 0.1% / 90 : 0.229% / 95 : 0.588% / 99 : 29.796%
                                 scale_quantile log_g                  75 : 0.116% / 90 : 0.284% / 95 : 0.7% / 99 : 29.796%
linear_regression MIST           Base           log_g              75 : 18.641% / 90 : 26.76% / 95 : 30.973% / 99 : 37.569%
                                 scale_standard log_g              75 : 18.641% / 90 : 26.76% / 95 : 30.973% / 99 : 37.569%

Results for the phase category with a value of 2.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233
KNN               MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233
linear_regression MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233
mlp               MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233
random_forest     MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233
xgboost           MIST           Base           log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_standard log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_robust   log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_power    log_g             -0.2959230723262505 - 4.408311770676233
                                 scale_quantile log_g             -0.2959230723262505 - 4.408311770676233

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             0.10816902880453338
                                 scale_standard log_g             0.10822677245062406
                                 scale_robust   log_g             0.10829530980978075
                                 scale_power    log_g             0.10768816507489454
                                 scale_quantile log_g             0.11027369794462605
KNN               MIST           Base           log_g               0.594178882501541
                                 scale_standard log_g               0.595896903825001
                                 scale_robust   log_g              0.5944509281907415
                                 scale_power    log_g              0.5965656849446874
                                 scale_quantile log_g              0.5959314274255119
linear_regression MIST           Base           log_g              0.2245163409964468
                                 scale_standard log_g             0.22451634099644813
                                 scale_robust   log_g             0.22451634099645423
                                 scale_power    log_g             0.16932552746124974
                                 scale_quantile log_g               0.156831205485903
mlp               MIST           Base           log_g              0.3249124565645656
                                 scale_standard log_g              0.3086582358414772
                                 scale_robust   log_g             0.41031385054164404
                                 scale_power    log_g              0.4716115591167418
                                 scale_quantile log_g              0.3895086801927977
random_forest     MIST           Base           log_g             0.38691114604182897
                                 scale_standard log_g              0.3865878927575134
                                 scale_robust   log_g             0.38727717423648633
                                 scale_power    log_g              0.3865126783099391
                                 scale_quantile log_g             0.38804695967478287
xgboost           MIST           Base           log_g             0.41515284669200114
                                 scale_standard log_g             0.41669574350629013
                                 scale_robust   log_g              0.4147772819149461
                                 scale_power    log_g              0.4145312350522812
                                 scale_quantile log_g             0.41844544202242595

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             18.275%
                                 scale_standard log_g             18.275%
                                 scale_robust   log_g             18.274%
                                 scale_power    log_g              18.28%
                                 scale_quantile log_g             18.254%
KNN               MIST           Base           log_g             12.333%
                                 scale_standard log_g             12.307%
                                 scale_robust   log_g             12.329%
                                 scale_power    log_g             12.297%
                                 scale_quantile log_g             12.307%
linear_regression MIST           Base           log_g             22.302%
                                 scale_standard log_g             22.302%
                                 scale_robust   log_g             22.302%
                                 scale_power    log_g             18.928%
                                 scale_quantile log_g             18.984%
mlp               MIST           Base           log_g             15.901%
                                 scale_standard log_g             16.452%
                                 scale_robust   log_g             14.921%
                                 scale_power    log_g             14.105%
                                 scale_quantile log_g             15.158%
random_forest     MIST           Base           log_g             15.158%
                                 scale_standard log_g             15.161%
                                 scale_robust   log_g             15.153%
                                 scale_power    log_g             15.163%
                                 scale_quantile log_g             15.144%
xgboost           MIST           Base           log_g              14.94%
                                 scale_standard log_g             14.922%
                                 scale_robust   log_g             14.949%
                                 scale_power    log_g              14.95%
                                 scale_quantile log_g             14.896%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              7.475%
                                 scale_standard log_g              7.474%
                                 scale_robust   log_g              7.477%
                                 scale_power    log_g              7.476%
                                 scale_quantile log_g               7.46%
KNN               MIST           Base           log_g              5.285%
                                 scale_standard log_g              5.255%
                                 scale_robust   log_g              5.275%
                                 scale_power    log_g              5.244%
                                 scale_quantile log_g               5.25%
linear_regression MIST           Base           log_g             16.884%
                                 scale_standard log_g             16.884%
                                 scale_robust   log_g             16.884%
                                 scale_power    log_g             14.466%
                                 scale_quantile log_g             14.315%
mlp               MIST           Base           log_g             12.391%
                                 scale_standard log_g              12.46%
                                 scale_robust   log_g             11.235%
                                 scale_power    log_g             10.379%
                                 scale_quantile log_g             11.548%
random_forest     MIST           Base           log_g               6.41%
                                 scale_standard log_g              6.413%
                                 scale_robust   log_g              6.408%
                                 scale_power    log_g              6.413%
                                 scale_quantile log_g              6.403%
xgboost           MIST           Base           log_g             11.231%
                                 scale_standard log_g             11.215%
                                 scale_robust   log_g             11.237%
                                 scale_power    log_g             11.234%
                                 scale_quantile log_g             11.194%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.338%
                                 scale_standard log_g              0.338%
                                 scale_robust   log_g              0.338%
                                 scale_power    log_g              0.338%
                                 scale_quantile log_g              0.338%
KNN               MIST           Base           log_g               0.22%
                                 scale_standard log_g              0.219%
                                 scale_robust   log_g              0.219%
                                 scale_power    log_g              0.218%
                                 scale_quantile log_g              0.224%
linear_regression MIST           Base           log_g             12.236%
                                 scale_standard log_g             12.236%
                                 scale_robust   log_g             12.236%
                                 scale_power    log_g             10.969%
                                 scale_quantile log_g             10.698%
mlp               MIST           Base           log_g               9.95%
                                 scale_standard log_g              9.493%
                                 scale_robust   log_g              8.378%
                                 scale_power    log_g              7.313%
                                 scale_quantile log_g              8.811%
random_forest     MIST           Base           log_g              0.218%
                                 scale_standard log_g              0.219%
                                 scale_robust   log_g              0.218%
                                 scale_power    log_g              0.218%
                                 scale_quantile log_g              0.216%
xgboost           MIST           Base           log_g              8.418%
                                 scale_standard log_g              8.411%
                                 scale_robust   log_g              8.446%
                                 scale_power    log_g              8.438%
                                 scale_quantile log_g              8.407%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             0.5517614412105366
                                 scale_standard log_g             0.5516616408008641
                                 scale_robust   log_g             0.5517990029869932
                                 scale_power    log_g             0.5514488118229172
                                 scale_quantile log_g             0.5526584178143672
KNN               MIST           Base           log_g             0.7750442583318956
                                 scale_standard log_g             0.7759932574016178
                                 scale_robust   log_g             0.7751750302973626
                                 scale_power    log_g             0.7763917178718475
                                 scale_quantile log_g             0.7760255102457181
linear_regression MIST           Base           log_g             0.4743260904396181
                                 scale_standard log_g             0.4743260904396199
                                 scale_robust   log_g             0.4743260904396259
                                 scale_power    log_g             0.4123851128974287
                                 scale_quantile log_g             0.3960287670926846
mlp               MIST           Base           log_g             0.5729121364080281
                                 scale_standard log_g             0.5674601751037733
                                 scale_robust   log_g             0.6460291461396649
                                 scale_power    log_g              0.686913766818218
                                 scale_quantile log_g              0.627652844506561
random_forest     MIST           Base           log_g             0.6635177579267701
                                 scale_standard log_g             0.6633979629987422
                                 scale_robust   log_g             0.6637357344271062
                                 scale_power    log_g             0.6632740848405663
                                 scale_quantile log_g             0.6641131757934536
xgboost           MIST           Base           log_g             0.6444816958330817
                                 scale_standard log_g             0.6457549730283418
                                 scale_robust   log_g             0.6442449739008681
                                 scale_power    log_g             0.6440115892267994
                                 scale_quantile log_g             0.6471204358980626

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             97.466%
                                 scale_standard log_g             97.466%
                                 scale_robust   log_g             97.466%
                                 scale_power    log_g             97.466%
                                 scale_quantile log_g             97.466%
KNN               MIST           Base           log_g             97.516%
                                 scale_standard log_g             97.516%
                                 scale_robust   log_g             97.516%
                                 scale_power    log_g             97.516%
                                 scale_quantile log_g             97.671%
linear_regression MIST           Base           log_g             71.927%
                                 scale_standard log_g             71.927%
                                 scale_robust   log_g             71.927%
                                 scale_power    log_g              60.19%
                                 scale_quantile log_g             62.524%
mlp               MIST           Base           log_g             77.456%
                                 scale_standard log_g             76.567%
                                 scale_robust   log_g             65.701%
                                 scale_power    log_g             66.931%
                                 scale_quantile log_g             70.519%
random_forest     MIST           Base           log_g             96.649%
                                 scale_standard log_g             97.544%
                                 scale_robust   log_g             96.869%
                                 scale_power    log_g              97.53%
                                 scale_quantile log_g             97.565%
xgboost           MIST           Base           log_g             79.353%
                                 scale_standard log_g             77.594%
                                 scale_robust   log_g             77.802%
                                 scale_power    log_g             79.581%
                                 scale_quantile log_g              79.23%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g               75 : 0.954% / 90 : 31.99% / 95 : 49.661% / 99 : 73.632%
                                 scale_standard log_g              75 : 0.951% / 90 : 31.985% / 95 : 49.643% / 99 : 73.633%
                                 scale_robust   log_g                75 : 0.962% / 90 : 31.998% / 95 : 49.631% / 99 : 73.6%
                                 scale_power    log_g              75 : 0.951% / 90 : 32.032% / 95 : 49.644% / 99 : 73.608%
                                 scale_quantile log_g              75 : 0.961% / 90 : 31.957% / 95 : 49.591% / 99 : 73.547%
KNN               MIST           Base           log_g              75 : 3.256% / 90 : 20.788% / 95 : 31.328% / 99 : 49.349%
                                 scale_standard log_g              75 : 3.038% / 90 : 20.719% / 95 : 31.276% / 99 : 49.312%
                                 scale_robust   log_g              75 : 3.169% / 90 : 20.783% / 95 : 31.329% / 99 : 49.359%
                                 scale_power    log_g               75 : 2.96% / 90 : 20.685% / 95 : 31.262% / 99 : 49.294%
                                 scale_quantile log_g              75 : 2.954% / 90 : 20.699% / 95 : 31.179% / 99 : 49.312%
linear_regression MIST           Base           log_g             75 : 25.114% / 90 : 39.812% / 95 : 47.614% / 99 : 57.143%
                                 scale_standard log_g             75 : 25.114% / 90 : 39.812% / 95 : 47.614% / 99 : 57.143%

Results for the phase category with a value of 3.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
KNN               MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
linear_regression MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
mlp               MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
random_forest     MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683
xgboost           MIST           Base           log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_standard log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_robust   log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_power    log_g             -1.0828963170617296 - 6.259434356871683
                                 scale_quantile log_g             -1.0828963170617296 - 6.259434356871683

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              0.5817849716549621
                                 scale_standard log_g              0.5844426985595641
                                 scale_robust   log_g              0.5820122649768529
                                 scale_power    log_g               0.581697680185388
                                 scale_quantile log_g              0.5809201136610418
KNN               MIST           Base           log_g              0.7980532314937201
                                 scale_standard log_g              0.8208883562022297
                                 scale_robust   log_g              0.8150467085703471
                                 scale_power    log_g              0.8217012382765656
                                 scale_quantile log_g              0.8214157848351649
linear_regression MIST           Base           log_g              0.2918925646174637
                                 scale_standard log_g              0.2918925646174597
                                 scale_robust   log_g              0.2918925646174616
                                 scale_power    log_g              0.2835044071005689
                                 scale_quantile log_g             0.26916115099933835
mlp               MIST           Base           log_g              0.4653238995649285
                                 scale_standard log_g              0.5164587995672794
                                 scale_robust   log_g              0.5235820661685188
                                 scale_power    log_g              0.5511273515163868
                                 scale_quantile log_g             0.47567689262454127
random_forest     MIST           Base           log_g              0.7328442946232603
                                 scale_standard log_g              0.7334926677636304
                                 scale_robust   log_g              0.7326552522390626
                                 scale_power    log_g              0.7323940013874497
                                 scale_quantile log_g              0.7334580764552663
xgboost           MIST           Base           log_g              0.6523316020107637
                                 scale_standard log_g              0.6490719706864312
                                 scale_robust   log_g              0.6517319128029383
                                 scale_power    log_g              0.6506504787544074
                                 scale_quantile log_g              0.6495771230448516

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              9.165%
                                 scale_standard log_g              9.134%
                                 scale_robust   log_g              9.162%
                                 scale_power    log_g              9.165%
                                 scale_quantile log_g              9.174%
KNN               MIST           Base           log_g              6.404%
                                 scale_standard log_g              5.992%
                                 scale_robust   log_g              6.098%
                                 scale_power    log_g              5.977%
                                 scale_quantile log_g              5.982%
linear_regression MIST           Base           log_g             20.758%
                                 scale_standard log_g             20.758%
                                 scale_robust   log_g             20.758%
                                 scale_power    log_g             16.927%
                                 scale_quantile log_g              16.94%
mlp               MIST           Base           log_g             12.263%
                                 scale_standard log_g             11.955%
                                 scale_robust   log_g             11.057%
                                 scale_power    log_g             10.325%
                                 scale_quantile log_g             11.482%
random_forest     MIST           Base           log_g              7.335%
                                 scale_standard log_g              7.326%
                                 scale_robust   log_g              7.338%
                                 scale_power    log_g              7.341%
                                 scale_quantile log_g              7.327%
xgboost           MIST           Base           log_g             10.183%
                                 scale_standard log_g             10.199%
                                 scale_robust   log_g             10.187%
                                 scale_power    log_g               10.2%
                                 scale_quantile log_g             10.197%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g              2.809%
                                 scale_standard log_g              2.797%
                                 scale_robust   log_g               2.81%
                                 scale_power    log_g              2.809%
                                 scale_quantile log_g              2.812%
KNN               MIST           Base           log_g               2.48%
                                 scale_standard log_g              2.169%
                                 scale_robust   log_g              2.244%
                                 scale_power    log_g              2.157%
                                 scale_quantile log_g              2.163%
linear_regression MIST           Base           log_g             17.564%
                                 scale_standard log_g             17.564%
                                 scale_robust   log_g             17.564%
                                 scale_power    log_g             13.085%
                                 scale_quantile log_g             12.886%
mlp               MIST           Base           log_g              8.754%
                                 scale_standard log_g              8.388%
                                 scale_robust   log_g              7.663%
                                 scale_power    log_g              7.002%
                                 scale_quantile log_g              7.994%
random_forest     MIST           Base           log_g              2.453%
                                 scale_standard log_g              2.455%
                                 scale_robust   log_g              2.456%
                                 scale_power    log_g              2.453%
                                 scale_quantile log_g               2.45%
xgboost           MIST           Base           log_g              7.298%
                                 scale_standard log_g              7.296%
                                 scale_robust   log_g              7.291%
                                 scale_power    log_g              7.299%
                                 scale_quantile log_g              7.288%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g               0.25%
                                 scale_standard log_g              0.254%
                                 scale_robust   log_g               0.25%
                                 scale_power    log_g               0.25%
                                 scale_quantile log_g               0.25%
KNN               MIST           Base           log_g              0.338%
                                 scale_standard log_g              0.296%
                                 scale_robust   log_g              0.305%
                                 scale_power    log_g              0.296%
                                 scale_quantile log_g              0.302%
linear_regression MIST           Base           log_g             13.702%
                                 scale_standard log_g             13.702%
                                 scale_robust   log_g             13.702%
                                 scale_power    log_g             10.288%
                                 scale_quantile log_g              10.03%
mlp               MIST           Base           log_g              5.728%
                                 scale_standard log_g              5.431%
                                 scale_robust   log_g              4.838%
                                 scale_power    log_g              4.373%
                                 scale_quantile log_g              5.065%
random_forest     MIST           Base           log_g               0.23%
                                 scale_standard log_g              0.237%
                                 scale_robust   log_g              0.231%
                                 scale_power    log_g              0.229%
                                 scale_quantile log_g              0.231%
xgboost           MIST           Base           log_g              4.768%
                                 scale_standard log_g              4.766%
                                 scale_robust   log_g              4.772%
                                 scale_power    log_g              4.779%
                                 scale_quantile log_g               4.75%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             0.7872344983380405
                                 scale_standard log_g             0.7883832407191782
                                 scale_robust   log_g             0.7873238841724238
                                 scale_power    log_g             0.7871993412931575
                                 scale_quantile log_g              0.786861451108818
KNN               MIST           Base           log_g             0.8937310126228201
                                 scale_standard log_g             0.9060488796991131
                                 scale_robust   log_g             0.9028681553447171
                                 scale_power    log_g             0.9064944263895816
                                 scale_quantile log_g             0.9063360729815944
linear_regression MIST           Base           log_g             0.5655350134948097
                                 scale_standard log_g             0.5655350134948054
                                 scale_robust   log_g              0.565535013494802
                                 scale_power    log_g             0.5626397515302185
                                 scale_quantile log_g             0.5578496107233222
mlp               MIST           Base           log_g             0.6888025677453951
                                 scale_standard log_g             0.7203384812487673
                                 scale_robust   log_g             0.7251278128127923
                                 scale_power    log_g             0.7448347819157957
                                 scale_quantile log_g             0.6911528874279258
random_forest     MIST           Base           log_g             0.8584121763316808
                                 scale_standard log_g             0.8587371440199593
                                 scale_robust   log_g             0.8583093082779081
                                 scale_power    log_g             0.8581824816292007
                                 scale_quantile log_g             0.8587642023823582
xgboost           MIST           Base           log_g             0.8172568061289313
                                 scale_standard log_g             0.8149518521188247
                                 scale_robust   log_g             0.8171260428301962
                                 scale_power    log_g             0.8163156147150368
                                 scale_quantile log_g             0.8157706156557358

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g             77.218%
                                 scale_standard log_g             77.218%
                                 scale_robust   log_g             77.218%
                                 scale_power    log_g             77.218%
                                 scale_quantile log_g             77.218%
KNN               MIST           Base           log_g             77.248%
                                 scale_standard log_g             77.248%
                                 scale_robust   log_g             77.248%
                                 scale_power    log_g             77.248%
                                 scale_quantile log_g             77.199%
linear_regression MIST           Base           log_g             54.654%
                                 scale_standard log_g             54.654%
                                 scale_robust   log_g             54.654%
                                 scale_power    log_g             63.136%
                                 scale_quantile log_g             66.984%
mlp               MIST           Base           log_g             76.517%
                                 scale_standard log_g              72.56%
                                 scale_robust   log_g             75.547%
                                 scale_power    log_g             76.124%
                                 scale_quantile log_g             76.683%
random_forest     MIST           Base           log_g             77.227%
                                 scale_standard log_g             77.234%
                                 scale_robust   log_g             77.231%
                                 scale_power    log_g              77.23%
                                 scale_quantile log_g             77.229%
xgboost           MIST           Base           log_g             68.084%
                                 scale_standard log_g             66.632%
                                 scale_robust   log_g             66.018%
                                 scale_power    log_g             68.798%
                                 scale_quantile log_g             64.789%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           log_g                  75 : 0.65% / 90 : 5.85% / 95 : 18.71% / 99 : 48.682%
                                 scale_standard log_g               75 : 0.657% / 90 : 5.776% / 95 : 18.411% / 99 : 48.682%
                                 scale_robust   log_g                75 : 0.65% / 90 : 5.871% / 95 : 18.713% / 99 : 48.682%
                                 scale_power    log_g               75 : 0.651% / 90 : 5.848% / 95 : 18.694% / 99 : 48.726%
                                 scale_quantile log_g                75 : 0.65% / 90 : 5.849% / 95 : 18.762% / 99 : 48.699%
KNN               MIST           Base           log_g               75 : 1.634% / 90 : 7.249% / 95 : 13.143% / 99 : 30.574%
                                 scale_standard log_g               75 : 1.172% / 90 : 6.128% / 95 : 11.961% / 99 : 28.929%
                                 scale_robust   log_g               75 : 1.259% / 90 : 6.391% / 95 : 12.296% / 99 : 29.355%
                                 scale_power    log_g               75 : 1.163% / 90 : 6.064% / 95 : 11.905% / 99 : 28.922%
                                 scale_quantile log_g               75 : 1.174% / 90 : 6.065% / 95 : 11.912% / 99 : 28.961%
linear_regression MIST           Base           log_g             75 : 23.906% / 90 : 35.757% / 95 : 40.467% / 99 : 46.576%
                                 scale_standard log_g             75 : 23.906% / 90 : 35.757% / 95 : 40.467% / 99 : 46.576%

### Radius parameter

In [ ]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
KNN               MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
linear_regression MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
mlp               MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
random_forest     MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
xgboost           MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.8155741609143345
                                 scale_standard radius             0.8157624813325708
                                 scale_robust   radius             0.8154243467970417
                                 scale_power    radius             0.8154229879237795
                                 scale_quantile radius             0.8159785636939894
KNN               MIST           Base           radius             0.9043914862732579
                                 scale_standard radius             0.9142818269483467
                                 scale_robust   radius             0.9109488591467841
                                 scale_power    radius               0.91488668756761
                                 scale_quantile radius             0.9149477965101658
linear_regression MIST           Base           radius            0.19856216776938762
                                 scale_standard radius             0.1985621677693875
                                 scale_robust   radius             0.1985621677693874
                                 scale_power    radius             0.6017363333629401
                                 scale_quantile radius             0.5791071187333383
mlp               MIST           Base           radius             0.7570156135268156
                                 scale_standard radius             0.7803147269583259
                                 scale_robust   radius             0.8171402799525951
                                 scale_power    radius             0.8413830615282124
                                 scale_quantile radius             0.8078136869323864
random_forest     MIST           Base           radius             0.8776105127019214
                                 scale_standard radius             0.8776009870856252
                                 scale_robust   radius             0.8776056729724643
                                 scale_power    radius             0.8775243375903539
                                 scale_quantile radius             0.8778547070989275
xgboost           MIST           Base           radius             0.8250961607541988
                                 scale_standard radius             0.8251614546888759
                                 scale_robust   radius             0.8248165695604994
                                 scale_power    radius             0.8246419528448673
                                 scale_quantile radius             0.8253728915273966

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             7.681%
                                 scale_standard radius             7.677%
                                 scale_robust   radius             7.684%
                                 scale_power    radius             7.684%
                                 scale_quantile radius             7.672%
KNN               MIST           Base           radius             5.534%
                                 scale_standard radius             5.237%
                                 scale_robust   radius             5.339%
                                 scale_power    radius             5.218%
                                 scale_quantile radius             5.217%
linear_regression MIST           Base           radius            16.011%
                                 scale_standard radius            16.011%
                                 scale_robust   radius            16.011%
                                 scale_power    radius            11.286%
                                 scale_quantile radius            11.603%
mlp               MIST           Base           radius             8.875%
                                 scale_standard radius             8.383%
                                 scale_robust   radius             7.652%
                                 scale_power    radius             7.126%
                                 scale_quantile radius              7.84%
random_forest     MIST           Base           radius             6.257%
                                 scale_standard radius             6.258%
                                 scale_robust   radius             6.257%
                                 scale_power    radius             6.259%
                                 scale_quantile radius             6.251%
xgboost           MIST           Base           radius             7.479%
                                 scale_standard radius             7.478%
                                 scale_robust   radius             7.485%
                                 scale_power    radius             7.489%
                                 scale_quantile radius             7.474%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             2.124%
                                 scale_standard radius             2.122%
                                 scale_robust   radius             2.126%
                                 scale_power    radius             2.124%
                                 scale_quantile radius              2.12%
KNN               MIST           Base           radius             1.838%
                                 scale_standard radius               1.6%
                                 scale_robust   radius              1.68%
                                 scale_power    radius             1.565%
                                 scale_quantile radius             1.575%
linear_regression MIST           Base           radius            13.239%
                                 scale_standard radius            13.239%
                                 scale_robust   radius            13.239%
                                 scale_power    radius             9.059%
                                 scale_quantile radius             9.299%
mlp               MIST           Base           radius             5.857%
                                 scale_standard radius             5.465%
                                 scale_robust   radius             4.642%
                                 scale_power    radius             4.128%
                                 scale_quantile radius             4.777%
random_forest     MIST           Base           radius             1.851%
                                 scale_standard radius             1.852%
                                 scale_robust   radius             1.852%
                                 scale_power    radius             1.851%
                                 scale_quantile radius             1.849%
xgboost           MIST           Base           radius             4.815%
                                 scale_standard radius              4.82%
                                 scale_robust   radius             4.825%
                                 scale_power    radius             4.823%
                                 scale_quantile radius             4.814%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.113%
                                 scale_standard radius             0.113%
                                 scale_robust   radius             0.113%
                                 scale_power    radius             0.113%
                                 scale_quantile radius             0.113%
KNN               MIST           Base           radius             0.092%
                                 scale_standard radius             0.091%
                                 scale_robust   radius             0.087%
                                 scale_power    radius             0.084%
                                 scale_quantile radius              0.09%
linear_regression MIST           Base           radius            11.477%
                                 scale_standard radius            11.477%
                                 scale_robust   radius            11.477%
                                 scale_power    radius             8.273%
                                 scale_quantile radius             8.295%
mlp               MIST           Base           radius             3.046%
                                 scale_standard radius             2.774%
                                 scale_robust   radius             1.947%
                                 scale_power    radius             1.472%
                                 scale_quantile radius             1.906%
random_forest     MIST           Base           radius             0.056%
                                 scale_standard radius             0.057%
                                 scale_robust   radius             0.057%
                                 scale_power    radius             0.057%
                                 scale_quantile radius             0.057%
xgboost           MIST           Base           radius             2.424%
                                 scale_standard radius             2.434%
                                 scale_robust   radius             2.426%
                                 scale_power    radius             2.422%
                                 scale_quantile radius             2.419%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.908046242988254
                                 scale_standard radius            0.9081386357273782
                                 scale_robust   radius            0.9079789450890545
                                 scale_power    radius            0.9079742462640294
                                 scale_quantile radius            0.9082281830658759
KNN               MIST           Base           radius            0.9513432795547301
                                 scale_standard radius            0.9563895118652173
                                 scale_robust   radius            0.9547087872472125
                                 scale_power    radius            0.9566839050796957
                                 scale_quantile radius            0.9567144846803333
linear_regression MIST           Base           radius            0.4456031520460739
                                 scale_standard radius            0.4456031520460738
                                 scale_robust   radius            0.4456031520460738
                                 scale_power    radius            0.7757166579215733
                                 scale_quantile radius             0.760990879710776
mlp               MIST           Base           radius             0.870162623980867
                                 scale_standard radius            0.8833542633550214
                                 scale_robust   radius            0.9039792930363099
                                 scale_power    radius               0.9173247617532
                                 scale_quantile radius            0.8987872724949383
random_forest     MIST           Base           radius            0.9377254771026249
                                 scale_standard radius            0.9377236923690966
                                 scale_robust   radius            0.9377253208910087
                                 scale_power    radius            0.9376846112000989
                                 scale_quantile radius            0.9378488347694381
xgboost           MIST           Base           radius            0.9085430473618937
                                 scale_standard radius              0.90858530850819
                                 scale_robust   radius             0.908393438697702
                                 scale_power    radius            0.9082945489122911
                                 scale_quantile radius            0.9086936712180833

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            68.704%
                                 scale_standard radius            68.844%
                                 scale_robust   radius            68.704%
                                 scale_power    radius            68.844%
                                 scale_quantile radius            68.844%
KNN               MIST           Base           radius             68.75%
                                 scale_standard radius             68.75%
                                 scale_robust   radius             68.75%
                                 scale_power    radius             68.75%
                                 scale_quantile radius            68.651%
linear_regression MIST           Base           radius             49.52%
                                 scale_standard radius             49.52%
                                 scale_robust   radius             49.52%
                                 scale_power    radius            57.275%
                                 scale_quantile radius            61.943%
mlp               MIST           Base           radius            68.624%
                                 scale_standard radius            66.645%
                                 scale_robust   radius            68.491%
                                 scale_power    radius            66.437%
                                 scale_quantile radius            68.185%
random_forest     MIST           Base           radius            68.704%
                                 scale_standard radius            68.715%
                                 scale_robust   radius            68.709%
                                 scale_power    radius            68.707%
                                 scale_quantile radius            68.713%
xgboost           MIST           Base           radius            62.531%
                                 scale_standard radius            61.536%
                                 scale_robust   radius            61.029%
                                 scale_power    radius            61.786%
                                 scale_quantile radius             60.82%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              75 : 0.249% / 90 : 2.572% / 95 : 16.512% / 99 : 40.591%
                                 scale_standard radius               75 : 0.25% / 90 : 2.589% / 95 : 16.456% / 99 : 40.599%
                                 scale_robust   radius               75 : 0.25% / 90 : 2.579% / 95 : 16.543% / 99 : 40.584%
                                 scale_power    radius               75 : 0.25% / 90 : 2.574% / 95 : 16.514% / 99 : 40.597%
                                 scale_quantile radius               75 : 0.25% / 90 : 2.545% / 95 : 16.466% / 99 : 40.539%
KNN               MIST           Base           radius              75 : 0.428% / 90 : 5.636% / 95 : 12.389% / 99 : 26.309%
                                 scale_standard radius              75 : 0.283% / 90 : 4.102% / 95 : 11.171% / 99 : 25.535%
                                 scale_robust   radius              75 : 0.317% / 90 : 4.709% / 95 : 11.596% / 99 : 25.783%
                                 scale_power    radius              75 : 0.249% / 90 : 3.864% / 95 : 11.115% / 99 : 25.531%
                                 scale_quantile radius              75 : 0.282% / 90 : 3.872% / 95 : 11.135% / 99 : 25.516%
linear_regression MIST           Base           radius              75 : 17.837% / 90 : 26.55% / 95 : 31.48% / 99 : 38.856%
                                 scale_standard radius              75 : 17.837% / 90 : 26.55% / 95 : 31.48% / 99 : 38.856%

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.8362997592078089
                                 scale_standard radius             0.8360374886351921
                                 scale_robust   radius             0.8357431647857865
                                 scale_power    radius             0.8360114422390652
                                 scale_quantile radius             0.8371235729987013
KNN               MIST           Base           radius             0.8957368145865507
                                 scale_standard radius              0.916522014528654
                                 scale_robust   radius             0.9090903105399593
                                 scale_power    radius             0.9178264630814648
                                 scale_quantile radius             0.9183151403797886
linear_regression MIST           Base           radius             0.4447713018606766
                                 scale_standard radius             0.4447713018606817
                                 scale_robust   radius            0.44477130186068814
                                 scale_power    radius             0.6550628400035865
                                 scale_quantile radius             0.6213945971705614
mlp               MIST           Base           radius             0.7459947947493104
                                 scale_standard radius             0.8064145112135745
                                 scale_robust   radius             0.8161209159567955
                                 scale_power    radius             0.8499263294366519
                                 scale_quantile radius             0.8154709522675168
random_forest     MIST           Base           radius              0.895944647709672
                                 scale_standard radius             0.8958047717666149
                                 scale_robust   radius             0.8958674569669184
                                 scale_power    radius             0.8959275756314524
                                 scale_quantile radius             0.8961531518373833
xgboost           MIST           Base           radius             0.8325938372230868
                                 scale_standard radius             0.8326137247348038
                                 scale_robust   radius             0.8322859950168372
                                 scale_power    radius             0.8315916300000741
                                 scale_quantile radius             0.8323670112776573

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              5.69%
                                 scale_standard radius             5.694%
                                 scale_robust   radius               5.7%
                                 scale_power    radius             5.695%
                                 scale_quantile radius             5.675%
KNN               MIST           Base           radius             4.589%
                                 scale_standard radius             4.073%
                                 scale_robust   radius             4.263%
                                 scale_power    radius             4.039%
                                 scale_quantile radius             4.027%
linear_regression MIST           Base           radius            15.339%
                                 scale_standard radius            15.339%
                                 scale_robust   radius            15.339%
                                 scale_power    radius            10.029%
                                 scale_quantile radius            10.333%
mlp               MIST           Base           radius             8.042%
                                 scale_standard radius             6.926%
                                 scale_robust   radius             6.206%
                                 scale_power    radius             5.754%
                                 scale_quantile radius             6.353%
random_forest     MIST           Base           radius              4.55%
                                 scale_standard radius             4.553%
                                 scale_robust   radius             4.552%
                                 scale_power    radius             4.551%
                                 scale_quantile radius             4.546%
xgboost           MIST           Base           radius              6.24%
                                 scale_standard radius             6.243%
                                 scale_robust   radius             6.249%
                                 scale_power    radius             6.261%
                                 scale_quantile radius             6.244%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.935%
                                 scale_standard radius             0.936%
                                 scale_robust   radius             0.938%
                                 scale_power    radius             0.936%
                                 scale_quantile radius             0.932%
KNN               MIST           Base           radius             1.135%
                                 scale_standard radius             0.796%
                                 scale_robust   radius             0.916%
                                 scale_power    radius             0.738%
                                 scale_quantile radius             0.753%
linear_regression MIST           Base           radius            12.831%
                                 scale_standard radius            12.831%
                                 scale_robust   radius            12.831%
                                 scale_power    radius             8.675%
                                 scale_quantile radius             8.962%
mlp               MIST           Base           radius             4.638%
                                 scale_standard radius             4.002%
                                 scale_robust   radius             3.004%
                                 scale_power    radius             2.531%
                                 scale_quantile radius             3.063%
random_forest     MIST           Base           radius             0.844%
                                 scale_standard radius             0.844%
                                 scale_robust   radius             0.845%
                                 scale_power    radius             0.844%
                                 scale_quantile radius             0.843%
xgboost           MIST           Base           radius             3.462%
                                 scale_standard radius             3.467%
                                 scale_robust   radius             3.472%
                                 scale_power    radius             3.473%
                                 scale_quantile radius             3.465%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.07%
                                 scale_standard radius             0.07%
                                 scale_robust   radius             0.07%
                                 scale_power    radius             0.07%
                                 scale_quantile radius             0.07%
KNN               MIST           Base           radius            0.058%
                                 scale_standard radius            0.067%
                                 scale_robust   radius             0.06%
                                 scale_power    radius            0.059%
                                 scale_quantile radius            0.064%
linear_regression MIST           Base           radius            11.67%
                                 scale_standard radius            11.67%
                                 scale_robust   radius            11.67%
                                 scale_power    radius            8.869%
                                 scale_quantile radius            9.076%
mlp               MIST           Base           radius            1.041%
                                 scale_standard radius            1.672%
                                 scale_robust   radius            1.086%
                                 scale_power    radius            0.777%
                                 scale_quantile radius            0.871%
random_forest     MIST           Base           radius            0.028%
                                 scale_standard radius            0.028%
                                 scale_robust   radius            0.028%
                                 scale_power    radius            0.028%
                                 scale_quantile radius            0.029%
xgboost           MIST           Base           radius            0.965%
                                 scale_standard radius            0.959%
                                 scale_robust   radius            0.969%
                                 scale_power    radius            0.952%
                                 scale_quantile radius            0.961%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9266704914779671
                                 scale_standard radius             0.926555506289964
                                 scale_robust   radius            0.9264549667525878
                                 scale_power    radius            0.9265557627158635
                                 scale_quantile radius            0.9269582354951056
KNN               MIST           Base           radius            0.9538577488062183
                                 scale_standard radius            0.9608601938239718
                                 scale_robust   radius            0.9583895305216908
                                 scale_power    radius            0.9611875575805502
                                 scale_quantile radius            0.9614204425767404
linear_regression MIST           Base           radius            0.6719624779362757
                                 scale_standard radius            0.6719624779362798
                                 scale_robust   radius            0.6719624779362837
                                 scale_power    radius            0.8498640321814145
                                 scale_quantile radius            0.8325393214118922
mlp               MIST           Base           radius            0.9040382509041051
                                 scale_standard radius            0.9178434334352733
                                 scale_robust   radius            0.9225180050411218
                                 scale_power    radius            0.9337537910429986
                                 scale_quantile radius            0.9212710151731694
random_forest     MIST           Base           radius            0.9515577145193358
                                 scale_standard radius            0.9514927392446253
                                 scale_robust   radius            0.9515257535051763
                                 scale_power    radius            0.9515541860187633
                                 scale_quantile radius            0.9516381646896326
xgboost           MIST           Base           radius            0.9316960163015878
                                 scale_standard radius            0.9319318508795805
                                 scale_robust   radius            0.9316597340427875
                                 scale_power    radius            0.9313568658432774
                                 scale_quantile radius            0.9316678916643752

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            69.452%
                                 scale_standard radius            69.629%
                                 scale_robust   radius            69.452%
                                 scale_power    radius            69.629%
                                 scale_quantile radius            69.629%
KNN               MIST           Base           radius            68.331%
                                 scale_standard radius            68.331%
                                 scale_robust   radius            68.331%
                                 scale_power    radius            68.331%
                                 scale_quantile radius            68.331%
linear_regression MIST           Base           radius            50.085%
                                 scale_standard radius            50.085%
                                 scale_robust   radius            50.085%
                                 scale_power    radius            42.185%
                                 scale_quantile radius            42.651%
mlp               MIST           Base           radius            48.933%
                                 scale_standard radius            50.772%
                                 scale_robust   radius            52.305%
                                 scale_power    radius            57.499%
                                 scale_quantile radius            59.536%
random_forest     MIST           Base           radius            68.431%
                                 scale_standard radius            68.417%
                                 scale_robust   radius            68.447%
                                 scale_power    radius            68.443%
                                 scale_quantile radius            68.361%
xgboost           MIST           Base           radius            63.244%
                                 scale_standard radius            62.237%
                                 scale_robust   radius            61.725%
                                 scale_power    radius             62.49%
                                 scale_quantile radius            60.013%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius                75 : 0.133% / 90 : 0.269% / 95 : 0.52% / 99 : 37.991%
                                 scale_standard radius                75 : 0.133% / 90 : 0.27% / 95 : 0.523% / 99 : 37.994%
                                 scale_robust   radius                75 : 0.133% / 90 : 0.27% / 95 : 0.522% / 99 : 38.034%
                                 scale_power    radius                  75 : 0.133% / 90 : 0.27% / 95 : 0.526% / 99 : 38.0%
                                 scale_quantile radius               75 : 0.133% / 90 : 0.269% / 95 : 0.521% / 99 : 37.834%
KNN               MIST           Base           radius                75 : 0.18% / 90 : 1.197% / 95 : 6.692% / 99 : 24.241%
                                 scale_standard radius               75 : 0.141% / 90 : 0.346% / 95 : 1.595% / 99 : 22.065%
                                 scale_robust   radius                 75 : 0.14% / 90 : 0.525% / 95 : 3.875% / 99 : 22.65%
                                 scale_power    radius                 75 : 0.12% / 90 : 0.251% / 95 : 0.64% / 99 : 22.038%
                                 scale_quantile radius               75 : 0.139% / 90 : 0.323% / 95 : 0.821% / 99 : 22.041%
linear_regression MIST           Base           radius            75 : 17.266% / 90 : 24.755% / 95 : 29.653% / 99 : 36.474%
                                 scale_standard radius            75 : 17.266% / 90 : 24.755% / 95 : 29.653% / 99 : 36.474%

Results for the phase category with a value of 2.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
KNN               MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
linear_regression MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
mlp               MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
random_forest     MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
xgboost           MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.23288301898402786
                                 scale_standard radius            0.23293822663889696
                                 scale_robust   radius            0.23299017968828972
                                 scale_power    radius             0.2324716000482907
                                 scale_quantile radius             0.2346952273274595
KNN               MIST           Base           radius             0.6509309889395495
                                 scale_standard radius             0.6524083606660985
                                 scale_robust   radius             0.6511652612679291
                                 scale_power    radius              0.652982705350065
                                 scale_quantile radius             0.6524352649306052
linear_regression MIST           Base           radius              0.304632547786987
                                 scale_standard radius            0.30463254778698523
                                 scale_robust   radius              0.304632547786984
                                 scale_power    radius            0.28094218366076096
                                 scale_quantile radius            0.21430543200315177
mlp               MIST           Base           radius             0.4212087734607134
                                 scale_standard radius            0.39852014409752545
                                 scale_robust   radius             0.4891862246144547
                                 scale_power    radius             0.5451078196698185
                                 scale_quantile radius            0.47410508002947893
random_forest     MIST           Base           radius            0.47265136875136293
                                 scale_standard radius             0.4723744819110136
                                 scale_robust   radius            0.47296548417447126
                                 scale_power    radius             0.4723079693772537
                                 scale_quantile radius             0.4736281752365703
xgboost           MIST           Base           radius             0.4964972804842628
                                 scale_standard radius             0.4973824682051966
                                 scale_robust   radius             0.4964120735229788
                                 scale_power    radius            0.49662050975293337
                                 scale_quantile radius            0.49632700428706644

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            15.353%
                                 scale_standard radius            15.353%
                                 scale_robust   radius            15.352%
                                 scale_power    radius            15.358%
                                 scale_quantile radius            15.336%
KNN               MIST           Base           radius            10.361%
                                 scale_standard radius            10.339%
                                 scale_robust   radius            10.358%
                                 scale_power    radius            10.331%
                                 scale_quantile radius            10.339%
linear_regression MIST           Base           radius            20.822%
                                 scale_standard radius            20.822%
                                 scale_robust   radius            20.822%
                                 scale_power    radius            15.902%
                                 scale_quantile radius             16.51%
mlp               MIST           Base           radius             13.34%
                                 scale_standard radius            13.831%
                                 scale_robust   radius            12.581%
                                 scale_power    radius            11.841%
                                 scale_quantile radius            12.744%
random_forest     MIST           Base           radius            12.734%
                                 scale_standard radius            12.737%
                                 scale_robust   radius             12.73%
                                 scale_power    radius            12.738%
                                 scale_quantile radius            12.722%
xgboost           MIST           Base           radius            12.557%
                                 scale_standard radius            12.545%
                                 scale_robust   radius            12.557%
                                 scale_power    radius            12.552%
                                 scale_quantile radius            12.557%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              6.28%
                                 scale_standard radius             6.279%
                                 scale_robust   radius             6.282%
                                 scale_power    radius             6.281%
                                 scale_quantile radius             6.268%
KNN               MIST           Base           radius              4.44%
                                 scale_standard radius             4.415%
                                 scale_robust   radius             4.432%
                                 scale_power    radius             4.406%
                                 scale_quantile radius             4.411%
linear_regression MIST           Base           radius            16.551%
                                 scale_standard radius            16.551%
                                 scale_robust   radius            16.551%
                                 scale_power    radius             12.15%
                                 scale_quantile radius            12.597%
mlp               MIST           Base           radius            10.419%
                                 scale_standard radius            10.494%
                                 scale_robust   radius             9.471%
                                 scale_power    radius             8.719%
                                 scale_quantile radius             9.736%
random_forest     MIST           Base           radius             5.385%
                                 scale_standard radius             5.388%
                                 scale_robust   radius             5.384%
                                 scale_power    radius             5.388%
                                 scale_quantile radius             5.379%
xgboost           MIST           Base           radius             9.433%
                                 scale_standard radius             9.432%
                                 scale_robust   radius             9.436%
                                 scale_power    radius             9.436%
                                 scale_quantile radius             9.436%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.285%
                                 scale_standard radius             0.285%
                                 scale_robust   radius             0.285%
                                 scale_power    radius             0.285%
                                 scale_quantile radius             0.285%
KNN               MIST           Base           radius             0.185%
                                 scale_standard radius             0.184%
                                 scale_robust   radius             0.185%
                                 scale_power    radius             0.184%
                                 scale_quantile radius             0.188%
linear_regression MIST           Base           radius            13.036%
                                 scale_standard radius            13.036%
                                 scale_robust   radius            13.036%
                                 scale_power    radius             9.295%
                                 scale_quantile radius             9.764%
mlp               MIST           Base           radius              8.43%
                                 scale_standard radius              8.04%
                                 scale_robust   radius             7.075%
                                 scale_power    radius             6.139%
                                 scale_quantile radius             7.465%
random_forest     MIST           Base           radius             0.183%
                                 scale_standard radius             0.184%
                                 scale_robust   radius             0.183%
                                 scale_power    radius             0.183%
                                 scale_quantile radius             0.182%
xgboost           MIST           Base           radius             7.066%
                                 scale_standard radius             7.076%
                                 scale_robust   radius             7.074%
                                 scale_power    radius             7.085%
                                 scale_quantile radius             7.079%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.6239292439330856
                                 scale_standard radius            0.6239320344796885
                                 scale_robust   radius            0.6240439410766132
                                 scale_power    radius            0.6237079498362755
                                 scale_quantile radius            0.6246854400472203
KNN               MIST           Base           radius            0.8118473473513885
                                 scale_standard radius            0.8126494076260037
                                 scale_robust   radius            0.8119990339473955
                                 scale_power    radius            0.8129360129355288
                                 scale_quantile radius            0.8126475875403749
linear_regression MIST           Base           radius            0.5669445250663593
                                 scale_standard radius            0.5669445250663583
                                 scale_robust   radius            0.5669445250663597
                                 scale_power    radius            0.5635259159397945
                                 scale_quantile radius            0.4988639802509385
mlp               MIST           Base           radius            0.6527394139165096
                                 scale_standard radius            0.6637679151101497
                                 scale_robust   radius            0.7068320704446686
                                 scale_power    radius            0.7404891488944191
                                 scale_quantile radius            0.6930830512506778
random_forest     MIST           Base           radius            0.7209068216276289
                                 scale_standard radius             0.720789350938878
                                 scale_robust   radius            0.7210980009187019
                                 scale_power    radius            0.7207160307733551
                                 scale_quantile radius            0.7213476731217772
xgboost           MIST           Base           radius            0.7059467903707194
                                 scale_standard radius            0.7064712725550806
                                 scale_robust   radius            0.7058451891876052
                                 scale_power    radius            0.7060130202280788
                                 scale_quantile radius            0.7058041407041973

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            81.879%
                                 scale_standard radius            81.879%
                                 scale_robust   radius            81.879%
                                 scale_power    radius            81.879%
                                 scale_quantile radius            81.879%
KNN               MIST           Base           radius            81.926%
                                 scale_standard radius            81.926%
                                 scale_robust   radius            81.926%
                                 scale_power    radius            81.926%
                                 scale_quantile radius            82.073%
linear_regression MIST           Base           radius            63.889%
                                 scale_standard radius            63.889%
                                 scale_robust   radius            63.889%
                                 scale_power    radius             49.45%
                                 scale_quantile radius            55.301%
mlp               MIST           Base           radius            64.986%
                                 scale_standard radius            66.356%
                                 scale_robust   radius            54.864%
                                 scale_power    radius            55.633%
                                 scale_quantile radius            58.894%
random_forest     MIST           Base           radius            81.198%
                                 scale_standard radius            81.953%
                                 scale_robust   radius            81.384%
                                 scale_power    radius             81.94%
                                 scale_quantile radius            81.971%
xgboost           MIST           Base           radius            66.725%
                                 scale_standard radius            65.158%
                                 scale_robust   radius             64.52%
                                 scale_power    radius            68.606%
                                 scale_quantile radius            70.456%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              75 : 0.805% / 90 : 26.871% / 95 : 41.706% / 99 : 61.87%
                                 scale_standard radius             75 : 0.802% / 90 : 26.867% / 95 : 41.699% / 99 : 61.873%
                                 scale_robust   radius             75 : 0.811% / 90 : 26.883% / 95 : 41.691% / 99 : 61.843%
                                 scale_power    radius             75 : 0.803% / 90 : 26.914% / 95 : 41.699% / 99 : 61.853%
                                 scale_quantile radius             75 : 0.809% / 90 : 26.845% / 95 : 41.638% / 99 : 61.792%
KNN               MIST           Base           radius             75 : 2.736% / 90 : 17.465% / 95 : 26.319% / 99 : 41.464%
                                 scale_standard radius              75 : 2.552% / 90 : 17.407% / 95 : 26.273% / 99 : 41.43%
                                 scale_robust   radius              75 : 2.661% / 90 : 17.46% / 95 : 26.324% / 99 : 41.474%
                                 scale_power    radius             75 : 2.487% / 90 : 17.376% / 95 : 26.263% / 99 : 41.414%
                                 scale_quantile radius             75 : 2.481% / 90 : 17.391% / 95 : 26.194% / 99 : 41.431%
linear_regression MIST           Base           radius            75 : 23.853% / 90 : 36.155% / 95 : 42.634% / 99 : 50.524%
                                 scale_standard radius            75 : 23.853% / 90 : 36.155% / 95 : 42.634% / 99 : 50.524%

Results for the phase category with a value of 3.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
KNN               MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
linear_regression MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
mlp               MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
random_forest     MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
xgboost           MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.6590712626454432
                                 scale_standard radius             0.6612322390420797
                                 scale_robust   radius             0.6592629710294696
                                 scale_power    radius             0.6590071335399307
                                 scale_quantile radius             0.6583695290726715
KNN               MIST           Base           radius             0.8353242227223191
                                 scale_standard radius             0.8540143638851233
                                 scale_robust   radius             0.8492323557137158
                                 scale_power    radius             0.8546898250890558
                                 scale_quantile radius             0.8544469439436472
linear_regression MIST           Base           radius             0.3982384047629932
                                 scale_standard radius             0.3982384047629923
                                 scale_robust   radius             0.3982384047629989
                                 scale_power    radius              0.417858047542333
                                 scale_quantile radius            0.37319115017898663
mlp               MIST           Base           radius             0.5642957350076949
                                 scale_standard radius             0.6042718319140452
                                 scale_robust   radius             0.6110663311641139
                                 scale_power    radius             0.6353927539015531
                                 scale_quantile radius             0.5722416145261691
random_forest     MIST           Base           radius             0.7822157797380761
                                 scale_standard radius             0.7827445860622531
                                 scale_robust   radius             0.7820614424055412
                                 scale_power    radius             0.7818495577993042
                                 scale_quantile radius             0.7827135451256646
xgboost           MIST           Base           radius             0.7131476322201502
                                 scale_standard radius             0.7146058736148859
                                 scale_robust   radius              0.714187054272018
                                 scale_power    radius              0.715087496382942
                                 scale_quantile radius             0.7164071813107258

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             9.689%
                                 scale_standard radius             9.657%
                                 scale_robust   radius             9.687%
                                 scale_power    radius              9.69%
                                 scale_quantile radius             9.699%
KNN               MIST           Base           radius             6.771%
                                 scale_standard radius             6.334%
                                 scale_robust   radius             6.447%
                                 scale_power    radius             6.318%
                                 scale_quantile radius             6.324%
linear_regression MIST           Base           radius            24.025%
                                 scale_standard radius            24.025%
                                 scale_robust   radius            24.025%
                                 scale_power    radius            17.779%
                                 scale_quantile radius            18.094%
mlp               MIST           Base           radius            12.895%
                                 scale_standard radius             12.51%
                                 scale_robust   radius            11.708%
                                 scale_power    radius             10.83%
                                 scale_quantile radius            12.146%
random_forest     MIST           Base           radius             7.755%
                                 scale_standard radius             7.745%
                                 scale_robust   radius             7.758%
                                 scale_power    radius             7.761%
                                 scale_quantile radius             7.746%
xgboost           MIST           Base           radius            10.808%
                                 scale_standard radius            10.807%
                                 scale_robust   radius            10.818%
                                 scale_power    radius            10.814%
                                 scale_quantile radius            10.769%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             2.971%
                                 scale_standard radius             2.958%
                                 scale_robust   radius             2.971%
                                 scale_power    radius              2.97%
                                 scale_quantile radius             2.974%
KNN               MIST           Base           radius             2.622%
                                 scale_standard radius             2.293%
                                 scale_robust   radius             2.373%
                                 scale_power    radius             2.281%
                                 scale_quantile radius             2.287%
linear_regression MIST           Base           radius             20.89%
                                 scale_standard radius             20.89%
                                 scale_robust   radius             20.89%
                                 scale_power    radius            13.711%
                                 scale_quantile radius            13.751%
mlp               MIST           Base           radius             9.176%
                                 scale_standard radius             8.765%
                                 scale_robust   radius             8.118%
                                 scale_power    radius             7.346%
                                 scale_quantile radius             8.459%
random_forest     MIST           Base           radius             2.594%
                                 scale_standard radius             2.596%
                                 scale_robust   radius             2.597%
                                 scale_power    radius             2.594%
                                 scale_quantile radius              2.59%
xgboost           MIST           Base           radius             7.725%
                                 scale_standard radius             7.738%
                                 scale_robust   radius             7.746%
                                 scale_power    radius             7.732%
                                 scale_quantile radius             7.701%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.265%
                                 scale_standard radius             0.269%
                                 scale_robust   radius             0.265%
                                 scale_power    radius             0.265%
                                 scale_quantile radius             0.265%
KNN               MIST           Base           radius             0.357%
                                 scale_standard radius             0.313%
                                 scale_robust   radius             0.323%
                                 scale_power    radius             0.313%
                                 scale_quantile radius              0.32%
linear_regression MIST           Base           radius             16.85%
                                 scale_standard radius             16.85%
                                 scale_robust   radius             16.85%
                                 scale_power    radius            10.883%
                                 scale_quantile radius            10.742%
mlp               MIST           Base           radius             5.973%
                                 scale_standard radius              5.66%
                                 scale_robust   radius             5.113%
                                 scale_power    radius             4.603%
                                 scale_quantile radius             5.333%
random_forest     MIST           Base           radius             0.243%
                                 scale_standard radius              0.25%
                                 scale_robust   radius             0.244%
                                 scale_power    radius             0.243%
                                 scale_quantile radius             0.244%
xgboost           MIST           Base           radius             5.038%
                                 scale_standard radius             5.049%
                                 scale_robust   radius              5.07%
                                 scale_power    radius             5.061%
                                 scale_quantile radius             5.035%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.8254828285545792
                                 scale_standard radius            0.8264024022316215
                                 scale_robust   radius            0.8255921838710354
                                 scale_power    radius            0.8254822488714862
                                 scale_quantile radius            0.8251707708622211
KNN               MIST           Base           radius            0.9140042384395503
                                 scale_standard radius            0.9241527852380484
                                 scale_robust   radius            0.9215794975724192
                                 scale_power    radius            0.9245136581575644
                                 scale_quantile radius             0.924381838607613
linear_regression MIST           Base           radius            0.6489233026042639
                                 scale_standard radius            0.6489233026042627
                                 scale_robust   radius            0.6489233026042661
                                 scale_power    radius             0.647503830904176
                                 scale_quantile radius            0.6124916151167963
mlp               MIST           Base           radius            0.7668922431326006
                                 scale_standard radius            0.7775843356595595
                                 scale_robust   radius            0.7849016133304765
                                 scale_power    radius            0.7992554700328265
                                 scale_quantile radius            0.7587068685511273
random_forest     MIST           Base           radius            0.8853617266109324
                                 scale_standard radius            0.8856391607520654
                                 scale_robust   radius             0.885286362453233
                                 scale_power    radius            0.8851799247551463
                                 scale_quantile radius            0.8856486914203981
xgboost           MIST           Base           radius            0.8509390938547726
                                 scale_standard radius             0.852523946176989
                                 scale_robust   radius            0.8518320745504907
                                 scale_power    radius            0.8523838910025588
                                 scale_quantile radius            0.8530289559366896

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            81.616%
                                 scale_standard radius            81.616%
                                 scale_robust   radius            81.616%
                                 scale_power    radius            81.616%
                                 scale_quantile radius            81.616%
KNN               MIST           Base           radius            81.671%
                                 scale_standard radius            81.671%
                                 scale_robust   radius            81.671%
                                 scale_power    radius            81.671%
                                 scale_quantile radius            81.553%
linear_regression MIST           Base           radius            57.705%
                                 scale_standard radius            57.705%
                                 scale_robust   radius            57.705%
                                 scale_power    radius            68.039%
                                 scale_quantile radius            73.584%
mlp               MIST           Base           radius            81.521%
                                 scale_standard radius             79.17%
                                 scale_robust   radius            81.363%
                                 scale_power    radius            78.923%
                                 scale_quantile radius              81.0%
random_forest     MIST           Base           radius            81.616%
                                 scale_standard radius             81.63%
                                 scale_robust   radius            81.622%
                                 scale_power    radius             81.62%
                                 scale_quantile radius            81.627%
xgboost           MIST           Base           radius            72.798%
                                 scale_standard radius            70.862%
                                 scale_robust   radius            66.743%
                                 scale_power    radius            70.074%
                                 scale_quantile radius            72.251%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              75 : 0.687% / 90 : 6.185% / 95 : 19.775% / 99 : 51.442%
                                 scale_standard radius              75 : 0.695% / 90 : 6.101% / 95 : 19.486% / 99 : 51.442%
                                 scale_robust   radius              75 : 0.688% / 90 : 6.205% / 95 : 19.787% / 99 : 51.442%
                                 scale_power    radius               75 : 0.689% / 90 : 6.18% / 95 : 19.764% / 99 : 51.576%
                                 scale_quantile radius                75 : 0.688% / 90 : 6.182% / 95 : 19.85% / 99 : 51.45%
KNN               MIST           Base           radius               75 : 1.727% / 90 : 7.67% / 95 : 13.891% / 99 : 32.342%
                                 scale_standard radius               75 : 1.238% / 90 : 6.483% / 95 : 12.65% / 99 : 30.574%
                                 scale_robust   radius              75 : 1.331% / 90 : 6.761% / 95 : 13.013% / 99 : 31.006%
                                 scale_power    radius              75 : 1.229% / 90 : 6.411% / 95 : 12.593% / 99 : 30.562%
                                 scale_quantile radius              75 : 1.239% / 90 : 6.415% / 95 : 12.598% / 99 : 30.627%
linear_regression MIST           Base           radius             75 : 27.912% / 90 : 40.433% / 95 : 45.129% / 99 : 51.35%
                                 scale_standard radius             75 : 27.912% / 90 : 40.433% / 95 : 45.129% / 99 : 51.35%

les résultats avec du scaling sont très proche de Base, il n'y a pas d'intérêt à utilise le scaling pour ce modèle

## Base vs Base_old

| Parameter      | Base                                                    | Base_old                                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 5.0 - 10.3, Mean : 8.4794, Median : 8.6        |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 298.5448, Mean : 7.3915, Median : 2.0304 |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.5871, Mean : 3.8475, Median : 3.6808  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.14 - 8.6121, Mean : 2.1347, Median : 2.0681 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -2.09 - 3.1298, Mean : 1.3543, Median : 1.4604 |

In [14]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 5.37868
                                      log_g              -1.1449 - 6.25943
                                      radius            -0.99747 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.84057  0.13893
                                      log_g             0.53144  1.30405
                                      radius            0.52940  0.65205

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.06595  0.00496
                                      log_g             0.66420  0.04437
                                      radius            0.33219  0.02224

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.91784  0.92909
                                      log_g             0.74112  5.61441
                                      radius            0.73982  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.07238 / 90 : 0.23285 / 95 : 0.34978 / 99 : 0.55705
                                      log_g               75 : 0.8517 / 90 : 2.48049 / 95 : 3.35619 / 99 : 4.51164
                                      radius             75 : 0.42592 / 90 : 1.24044 / 95 : 1.67813 / 99 : 2.25528

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 0.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.34467 - 4.90341
                                      log_g             -0.59731 - 5.43309
                                      radius            -0.99747 - 3.08275

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80756  0.17157
                                      log_g            -4.35760  1.64296
                                      radius           -0.60430  0.82151

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07950  0.00103
                                      log_g             0.80682  0.00363
                                      radius            0.40370  0.00236

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.92091  0.89901
                                      log_g             0.37651  5.53132
                                      radius            0.54466  2.76740

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.08557 / 90 : 0.31563 / 95 : 0.45697 / 99 : 0.61308
                                      log_g              75 : 0.99833 / 90 : 3.51157 / 95 : 4.17142 / 99 : 4.81185
                                      radius             75 : 0.49971 / 90 : 1.75563 / 95 : 2.08579 / 99 : 2.40556

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 2.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.42453 - 4.71147
                                      log_g             -0.32878 - 4.40831
                                      radius             0.09099 - 2.89171

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.94636  0.07473
                                      log_g             0.01356  0.91497
                                      radius            0.15317  0.45748

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.03289  0.00313
                                      log_g             0.44560  0.01634
                                      radius            0.22280  0.00818

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.97366  0.72262
                                      log_g             0.51031  4.42512
                                      radius            0.56223  2.21252

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff               75 : 0.03253 / 90 : 0.10746 / 95 : 0.16429 / 99 : 0.3427
                                      log_g              75 : 0.52112 / 90 : 1.74899 / 95 : 2.32971 / 99 : 3.29739
                                      radius             75 : 0.26054 / 90 : 0.87451 / 95 : 1.16479 / 99 : 1.64861

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 3.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              3.35162 - 5.37868
                                      log_g             -1.07485 - 6.25943
                                      radius            -0.34459 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80007  0.14211
                                      log_g             0.25851  0.94071
                                      radius            0.39723  0.47044

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.07204  0.01308
                                      log_g             0.53570  0.10649
                                      radius            0.26792  0.05325

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.89988  0.92909
                                      log_g             0.62390  5.43249
                                      radius            0.68217  2.71757

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09139 / 90 : 0.22968 / 95 : 0.34287 / 99 : 0.56025
                                      log_g                75 : 0.866 / 90 : 1.76549 / 95 : 2.20904 / 99 : 3.03616
                                      radius             75 : 0.43322 / 90 : 0.88292 / 95 : 1.10456 / 99 : 1.51874

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 4.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             3.45536 - 5.16499
                                      log_g               -0.862 - 5.4397
                                      radius            0.18216 - 3.07966

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.59184  0.12532
                                      log_g             0.25238  0.77030
                                      radius            0.51498  0.38512

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.05624  0.01049
                                      log_g             0.42572  0.12590
                                      radius            0.21285  0.06296

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.80964  0.86611
                                      log_g             0.61631  5.23203
                                      radius            0.75184  2.61593

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff               75 : 0.04701 / 90 : 0.1757 / 95 : 0.31484 / 99 : 0.55476
                                      log_g              75 : 0.57838 / 90 : 1.30897 / 95 : 1.84395 / 99 : 2.88357
                                      radius             75 : 0.28916 / 90 : 0.65428 / 95 : 0.92196 / 99 : 1.44147

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             3.34914 - 5.17056
                                      log_g             -1.1449 - 5.46002
                                      radius                0.172 - 3.054

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff            -2.48156  0.13114
                                      log_g            -6.30552  1.32320
                                      radius           -3.88181  0.66162

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.06905  0.01082
                                      log_g             0.73508  0.11967
                                      radius            0.36753  0.05983

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             0.47116  0.76615
                                      log_g             0.13059  5.61441
                                      radius            0.24499  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff              75 : 0.09369 / 90 : 0.23484 / 95 : 0.32494 / 99 : 0.47661
                                      log_g               75 : 1.0951 / 90 : 2.57832 / 95 : 3.21253 / 99 : 4.24664
                                      radius               75 : 0.54747 / 90 : 1.289 / 95 : 1.60623 / 99 : 2.12374

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

In [3]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.34467 - 5.3788
                                      log_g              -1.0829 - 6.25943
                                      radius            -0.99746 - 3.12927
                             Base_old T_eff              3.34467 - 5.37868
                                      log_g              -1.1449 - 6.25943
                                      radius            -0.99747 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.96719  0.06264
                                      log_g             0.81983  0.51625
                                      radius            0.87761  0.25822
                             Base_old T_eff             0.84057  0.13893
                                      log_g             0.53144  1.30405
                                      radius            0.52940  0.65205

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01611  0.00101
                                      log_g             0.15238  0.00412
                                      radius            0.07640  0.00233
                             Base_old T_eff             0.06595  0.00496
                                      log_g             0.66420  0.04437
                                      radius            0.33219  0.02224

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98351  0.93308
                                      log_g             0.90761  5.67025
                                      radius            0.93773  2.83521
                             Base_old T_eff             0.91784  0.92909
                                      log_g             0.74112  5.61441
                                      radius            0.73982  2.80731

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                      log_g               75 : 0.0185 / 90 : 0.33483 / 95 : 1.14725 / 99 : 2.59569
                                      radius             75 : 0.00955 / 90 : 0.16761 / 95 : 0.57416 / 99 : 1.29851
                             Base_old T_eff              75 : 0.07238 / 90 : 0.23285 / 95 : 0.34978 / 99 : 0.55705
                                      log_g               75 : 0.8517 / 90 : 2.48049 / 95 : 3.35619 / 99 : 4.51164
                                      radius             75 : 0.42592 / 90 : 1.24044 / 95 : 1.67813 / 99 : 2.25528

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 0.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.34467 - 4.90341
                                      log_g             -0.59678 - 5.43307
                                      radius            -0.99746 - 3.08275
                             Base_old T_eff              3.34467 - 4.90341
                                      log_g             -0.59731 - 5.43309
                                      radius            -0.99747 - 3.08275

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.97420  0.05672
                                      log_g             0.65564  0.37094
                                      radius            0.89594  0.18567
                             Base_old T_eff             0.80756  0.17157
                                      log_g            -4.35760  1.64296
                                      radius           -0.60430  0.82151

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01024  0.00058
                                      log_g             0.06819  0.00176
                                      radius            0.03446  0.00115
                             Base_old T_eff             0.07950  0.00103
                                      log_g             0.80682  0.00363
                                      radius            0.40370  0.00236

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98713  0.89738
                                      log_g             0.86381  5.58083
                                      radius            0.95156  2.79213
                             Base_old T_eff             0.92091  0.89901
                                      log_g             0.37651  5.53132
                                      radius            0.54466  2.76740

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                      log_g              75 : 0.00525 / 90 : 0.01949 / 95 : 0.14109 / 99 : 2.20116
                                      radius              75 : 0.00317 / 90 : 0.01073 / 95 : 0.0708 / 99 : 1.10175
                             Base_old T_eff              75 : 0.08557 / 90 : 0.31563 / 95 : 0.45697 / 99 : 0.61308
                                      log_g              75 : 0.99833 / 90 : 3.51157 / 95 : 4.17142 / 99 : 4.81185
                                      radius             75 : 0.49971 / 90 : 1.75563 / 95 : 2.08579 / 99 : 2.40556

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 2.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.42786 - 4.71147
                                      log_g             -0.29592 - 4.40831
                                      radius             0.09199 - 2.89171
                             Base_old T_eff              3.42453 - 4.71147
                                      log_g             -0.32878 - 4.40831
                                      radius             0.09099 - 2.89171

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.97488  0.05016
                                      log_g             0.38691  0.71305
                                      radius            0.47265  0.35652
                             Base_old T_eff             0.94636  0.07473
                                      log_g             0.01356  0.91497
                                      radius            0.15317  0.45748

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.01991  0.00210
                                      log_g             0.30152  0.01023
                                      radius            0.15076  0.00513
                             Base_old T_eff             0.03289  0.00313
                                      log_g             0.44560  0.01634
                                      radius            0.22280  0.00818

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.98736  0.71261
                                      log_g             0.66352  4.54661
                                      radius            0.72091  2.27333
                             Base_old T_eff             0.97366  0.72262
                                      log_g             0.51031  4.42512
                                      radius            0.56223  2.21252

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                      log_g              75 : 0.13861 / 90 : 1.23629 / 95 : 1.86362 / 99 : 2.86772
                                      radius              75 : 0.06932 / 90 : 0.61818 / 95 : 0.93156 / 99 : 1.4339
                             Base_old T_eff               75 : 0.03253 / 90 : 0.10746 / 95 : 0.16429 / 99 : 0.3427
                                      log_g              75 : 0.52112 / 90 : 1.74899 / 95 : 2.32971 / 99 : 3.29739
                                      radius             75 : 0.26054 / 90 : 0.87451 / 95 : 1.16479 / 99 : 1.64861

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

Results for the phase category with a value of 3.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.35162 - 5.3788
                                      log_g              -1.0829 - 6.25943
                                      radius            -0.34459 - 3.12927
                             Base_old T_eff              3.35162 - 5.37868
                                      log_g             -1.07485 - 6.25943
                                      radius            -0.34459 - 3.12927

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.91798  0.08865
                                      log_g             0.73284  0.53858
                                      radius            0.78222  0.26940
                             Base_old T_eff             0.80007  0.14211
                                      log_g             0.25851  0.94071
                                      radius            0.39723  0.47044

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.02720  0.00314
                                      log_g             0.18010  0.01689
                                      radius            0.09011  0.00845
                             Base_old T_eff             0.07204  0.01308
                                      log_g             0.53570  0.10649
                                      radius            0.26792  0.05325

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.95873  0.93308
                                      log_g             0.85841  5.67025
                                      radius            0.88536  2.83521
                             Base_old T_eff             0.89988  0.92909
                                      log_g             0.62390  5.43249
                                      radius            0.68217  2.71757

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                      log_g              75 : 0.07269 / 90 : 0.45574 / 95 : 1.06538 / 99 : 2.86521
                                      radius              75 : 0.03635 / 90 : 0.22815 / 95 : 0.5328 / 99 : 1.43515
                             Base_old T_eff              75 : 0.09139 / 90 : 0.22968 / 95 : 0.34287 / 99 : 0.56025
                                      log_g                75 : 0.866 / 90 : 1.76549 / 95 : 2.20904 / 99 : 3.03616
                                      radius             75 : 0.43322 / 90 : 0.88292 / 95 : 1.10456 / 99 : 1.51874

                                                             time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.08635
                                      log_g             293.08635
                                      radius            293.08635
                             Base_old T_eff             632.95791
                                      log_g             632.95791
                                      radius            632.95791

In [4]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               3.344668191350628 - 5.378801600728572
                                      log_g             -1.0828963170617296 - 6.259434356871683
                                      radius            -0.9974628481553472 - 3.129269620812593
                             Base_old T_eff               3.344668191350628 - 5.378675973625695
                                      log_g               -1.14489780699774 - 6.259434356871683
                                      radius            -0.9974747647513328 - 3.129269620812593

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9671910035107978
                                      log_g             0.8198256636371155
                                      radius            0.8776105127019214
                             Base_old T_eff             0.8405722178416324
                                      log_g             0.5314380568631798
                                      radius            0.5294025708949806

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.07936%  0.79178%
                                      log_g              7.03112%  2.07541%
                                      radius             6.25728%  1.85127%
                             Base_old T_eff              6.83041%  3.24253%
                                      log_g             17.61203%  8.97044%
                                      radius            15.80052%  8.04974%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.04971%
                                      log_g             0.05608%
                                      radius            0.05635%
                             Base_old T_eff             0.24375%
                                      log_g              0.5992%
                                      radius            0.53897%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9835135887268114
                                      log_g             0.9076055609149075
                                      radius            0.9377254771026249
                             Base_old T_eff             0.9178359321898323
                                      log_g             0.7411154874957776
                                      radius            0.7398210409174621

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             45.87133%
                                      log_g             77.22678%
                                      radius             68.7036%
                             Base_old T_eff             45.67783%
                                      log_g             75.82596%
                                      radius            68.02711%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.19271% / 90 : 1.52252% / 95 : 4.29814% / 99 : 15.59239%
                                      log_g                75 : 0.25196% / 90 : 4.56027% / 95 : 15.62515% / 99 : 35.3524%
                                      radius              75 : 0.23142% / 90 : 4.06157% / 95 : 13.91319% / 99 : 31.46581%
                             Base_old T_eff              75 : 3.55849% / 90 : 11.44784% / 95 : 17.19659% / 99 : 27.38682%
                                      log_g             75 : 11.50273% / 90 : 33.50052% / 95 : 45.32738% / 99 : 60.93244%
                                      radius            75 : 10.32097% / 90 : 30.05856% / 95 : 40.66474% / 99 : 54.65034%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 0.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                 3.344668191350628 - 4.90340707004253
                                      log_g              -0.5967768342670462 - 5.433070637654307
                                      radius            -0.9974628481553472 - 3.0827540579576227
                             Base_old T_eff                 3.344668191350628 - 4.90340707004253
                                      log_g              -0.5973100835175252 - 5.433094523832443
                                      radius            -0.9974747647513328 - 3.0827540579576227

                                                                        RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              0.9741964262283933
                                      log_g               0.655638939150234
                                      radius              0.895944647709672
                             Base_old T_eff              0.8075611489100274
                                      log_g               -4.35760028643572
                                      radius            -0.6043004559884961

                                                             RMSE        MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.63894%   0.65716%
                                      log_g              6.15166%   1.13095%
                                      radius             4.55042%   0.84445%
                             Base_old T_eff             11.00682%   5.10023%
                                      log_g             27.24468%  13.37923%
                                      radius            20.13395%   9.89413%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.03705%
                                      log_g             0.02924%
                                      radius            0.02822%
                             Base_old T_eff             0.06583%
                                      log_g             0.06012%
                                      radius            0.05774%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9871344752716238
                                      log_g              0.863807624437327
                                      radius            0.9515577145193358
                             Base_old T_eff             0.9209118656585242
                                      log_g             0.3765108921511524
                                      radius            0.5446576008706236

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             57.57081%
                                      log_g             92.55336%
                                      radius            68.43104%
                             Base_old T_eff             57.67556%
                                      log_g             91.72381%
                                      radius             67.8246%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                    75 : 0.09559% / 90 : 0.32398% / 95 : 1.43% / 99 : 19.7647%
                                      log_g                75 : 0.08707% / 90 : 0.32323% / 95 : 2.33986% / 99 : 36.50441%
                                      radius                75 : 0.07769% / 90 : 0.26298% / 95 : 1.7352% / 99 : 27.00224%
                             Base_old T_eff               75 : 5.48969% / 90 : 20.24906% / 95 : 29.31665% / 99 : 39.3318%
                                      log_g             75 : 16.55494% / 90 : 58.23108% / 95 : 69.17314% / 99 : 79.79315%
                                      radius             75 : 12.24711% / 90 : 43.02773% / 95 : 51.11944% / 99 : 58.9565%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 2.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                3.42785685311742 - 4.711472733477716
                                      log_g             -0.2959230723262505 - 4.408311770676233
                                      radius             0.0919862423867022 - 2.891706235288321
                             Base_old T_eff               3.424526073183654 - 4.711472733477716
                                      log_g             -0.3287802371627256 - 4.408311770676233
                                      radius             0.0909920840275404 - 2.891706235288321

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff               0.9748807497002827
                                      log_g              0.38691114604182897
                                      radius             0.47265136875136293
                             Base_old T_eff               0.9463609440149476
                                      log_g             0.013557431677446496
                                      radius             0.15317328940586838

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.90772%  1.55124%
                                      log_g             15.15768%  6.40953%
                                      radius            12.73409%   5.3849%
                             Base_old T_eff               5.8064%   2.5557%
                                      log_g             19.31497%  9.40665%
                                      radius            16.33443%  7.95519%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.16334%
                                      log_g             0.21754%
                                      radius            0.18312%
                             Base_old T_eff             0.24331%
                                      log_g             0.34488%
                                      radius            0.29199%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9873643484911543
                                      log_g             0.6635177579267701
                                      radius            0.7209068216276289
                             Base_old T_eff             0.9736585453129091
                                      log_g             0.5103084799376272
                                      radius            0.5622317588684937

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             55.51569%
                                      log_g             96.64932%
                                      radius             81.1983%
                             Base_old T_eff             56.15027%
                                      log_g             93.41425%
                                      radius             78.9986%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.87098% / 90 : 5.38011% / 95 : 8.67783% / 99 : 15.51321%
                                      log_g              75 : 2.94649% / 90 : 26.28036% / 95 : 39.61579% / 99 : 60.96039%
                                      radius             75 : 2.47596% / 90 : 22.08007% / 95 : 33.27333% / 99 : 51.21584%
                             Base_old T_eff                  75 : 2.52769% / 90 : 8.35% / 95 : 12.76587% / 99 : 26.62892%
                                      log_g             75 : 11.00084% / 90 : 36.92117% / 95 : 49.18017% / 99 : 69.60789%
                                      radius             75 : 9.30263% / 90 : 31.22454% / 95 : 41.58904% / 99 : 58.86392%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

Results for the phase category with a value of 3.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              3.3516171610778134 - 5.378801600728572
                                      log_g             -1.0828963170617296 - 6.259434356871683
                                      radius            -0.3445863859219699 - 3.129269620812593
                             Base_old T_eff              3.3516171610778134 - 5.378675973625695
                                      log_g              -1.074853654540692 - 6.259434356871683
                                      radius            -0.3445863859219699 - 3.129269620812593

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9179849306556465
                                      log_g             0.7328442946232603
                                      radius            0.7822157797380761
                             Base_old T_eff             0.8000731487510342
                                      log_g             0.2585106887735762
                                      radius             0.397229303297262

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff              4.37315%  1.34172%
                                      log_g              7.33521%   2.4529%
                                      radius             7.75509%  2.59391%
                             Base_old T_eff              7.01041%  3.55404%
                                      log_g             12.82615%  7.30402%
                                      radius            13.54228%  7.71256%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.15483%
                                      log_g             0.23001%
                                      radius             0.2432%
                             Base_old T_eff             0.64525%
                                      log_g             1.45192%
                                      radius            1.53275%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             0.9587327279611804
                                      log_g             0.8584121763316808
                                      radius            0.8853617266109324
                             Base_old T_eff             0.8998755106353982
                                      log_g              0.623904841285878
                                      radius            0.6821740223416446

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             46.02857%
                                      log_g             77.22678%
                                      radius            81.61575%
                             Base_old T_eff             45.83442%
                                      log_g              74.0698%
                                      radius            78.22922%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff                75 : 0.61317% / 90 : 2.86703% / 95 : 6.65998% / 99 : 24.21832%
                                      log_g               75 : 0.99001% / 90 : 6.20702% / 95 : 14.51011% / 99 : 39.02317%
                                      radius              75 : 1.04639% / 90 : 6.56763% / 95 : 15.33742% / 99 : 41.31288%
                             Base_old T_eff                75 : 4.5085% / 90 : 11.3307% / 95 : 16.91465% / 99 : 27.63857%
                                      log_g             75 : 11.80755% / 90 : 24.07173% / 95 : 30.11935% / 99 : 41.39679%
                                      radius            75 : 12.47087% / 90 : 25.41614% / 95 : 31.79637% / 99 : 43.71914%

                                                                     time
model         physical_model filter   output_parameter
random_forest MIST           Base     T_eff             293.0863494873047
                                      log_g             293.0863494873047
                                      radius            293.0863494873047
                             Base_old T_eff              632.957911491394
                                      log_g              632.957911491394
                                      radius             632.957911491394

### Conclusion

Removing phase 4 and 5 (EAGB and TPAGB) improves the results by a lot. 

Since there are no more superposition possible between phase 0 and 5 (MS and TPAGB), the results for the phase 0 drastically improved (2x to 4x better results for different statistics)

Phase 2 also improved (RGB), although not as much as phase 0.

Same with phase 3 (CHeB).

However, the results are not that good. Even for Random forest, the RMSE is quite high (3, 7 and 6% relative error).

## Base vs mass_filtered

| Parameter      | Base                                                    | mass_filtered_smaller_3                                | mass_filtered_smaller_14                               | mass_filtered_smaller_30                               |
| -------------  | ------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.0 - 10.3, Mean : 8.1222, Median : 8.15        | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5        | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289  | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557   | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557   | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537 | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976  | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357 | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### T_eff parameter

In [19]:
compare_metrics(path, value_rounding=5, relative_values=False,
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
KNN               MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
linear_regression MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
mlp               MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
random_forest     MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417
xgboost           MIST           Base            T_eff              3.34467 - 5.3788
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 5.35417

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95021
                                 mass_smaller_3  T_eff             0.93383
                                 mass_smaller_14 T_eff             0.95001
                                 mass_smaller_30 T_eff             0.94563
KNN               MIST           Base            T_eff             0.96733
                                 mass_smaller_3  T_eff             0.96945
                                 mass_smaller_14 T_eff             0.97390
                                 mass_smaller_30 T_eff             0.96956
linear_regression MIST           Base            T_eff             0.73552
                                 mass_smaller_3  T_eff             0.64139
                                 mass_smaller_14 T_eff             0.67901
                                 mass_smaller_30 T_eff             0.71899
mlp               MIST           Base            T_eff             0.84981
                                 mass_smaller_3  T_eff             0.73249
                                 mass_smaller_14 T_eff             0.80153
                                 mass_smaller_30 T_eff             0.71904
random_forest     MIST           Base            T_eff             0.96719
                                 mass_smaller_3  T_eff             0.95676
                                 mass_smaller_14 T_eff             0.96741
                                 mass_smaller_30 T_eff             0.96429
xgboost           MIST           Base            T_eff             0.90068
                                 mass_smaller_3  T_eff             0.90393
                                 mass_smaller_14 T_eff             0.86912
                                 mass_smaller_30 T_eff             0.88596

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.07717
                                 mass_smaller_3  T_eff             0.04728
                                 mass_smaller_14 T_eff             0.06387
                                 mass_smaller_30 T_eff             0.07408
KNN               MIST           Base            T_eff             0.06255
                                 mass_smaller_3  T_eff             0.03212
                                 mass_smaller_14 T_eff             0.04616
                                 mass_smaller_30 T_eff             0.05545
linear_regression MIST           Base            T_eff             0.17783
                                 mass_smaller_3  T_eff             0.11005
                                 mass_smaller_14 T_eff             0.16184
                                 mass_smaller_30 T_eff             0.16840
mlp               MIST           Base            T_eff             0.13459
                                 mass_smaller_3  T_eff             0.09696
                                 mass_smaller_14 T_eff             0.12946
                                 mass_smaller_30 T_eff             0.16882
random_forest     MIST           Base            T_eff             0.06264
                                 mass_smaller_3  T_eff             0.03822
                                 mass_smaller_14 T_eff             0.05157
                                 mass_smaller_30 T_eff             0.06004
xgboost           MIST           Base            T_eff             0.10898
                                 mass_smaller_3  T_eff             0.05696
                                 mass_smaller_14 T_eff             0.10334
                                 mass_smaller_30 T_eff             0.10728

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.01857
                                 mass_smaller_3  T_eff             0.01659
                                 mass_smaller_14 T_eff             0.01549
                                 mass_smaller_30 T_eff             0.01736
KNN               MIST           Base            T_eff             0.01861
                                 mass_smaller_3  T_eff             0.01231
                                 mass_smaller_14 T_eff             0.01262
                                 mass_smaller_30 T_eff             0.01521
linear_regression MIST           Base            T_eff             0.14378
                                 mass_smaller_3  T_eff             0.09070
                                 mass_smaller_14 T_eff             0.12885
                                 mass_smaller_30 T_eff             0.13277
mlp               MIST           Base            T_eff             0.09181
                                 mass_smaller_3  T_eff             0.07338
                                 mass_smaller_14 T_eff             0.09084
                                 mass_smaller_30 T_eff             0.11704
random_forest     MIST           Base            T_eff             0.01611
                                 mass_smaller_3  T_eff             0.01413
                                 mass_smaller_14 T_eff             0.01326
                                 mass_smaller_30 T_eff             0.01496
xgboost           MIST           Base            T_eff             0.06890
                                 mass_smaller_3  T_eff             0.03655
                                 mass_smaller_14 T_eff             0.06461
                                 mass_smaller_30 T_eff             0.06693

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00174
                                 mass_smaller_3  T_eff             0.00152
                                 mass_smaller_14 T_eff             0.00171
                                 mass_smaller_30 T_eff             0.00169
KNN               MIST           Base            T_eff             0.00168
                                 mass_smaller_3  T_eff             0.00176
                                 mass_smaller_14 T_eff             0.00155
                                 mass_smaller_30 T_eff             0.00156
linear_regression MIST           Base            T_eff             0.13156
                                 mass_smaller_3  T_eff             0.08197
                                 mass_smaller_14 T_eff             0.11623
                                 mass_smaller_30 T_eff             0.11708
mlp               MIST           Base            T_eff             0.05510
                                 mass_smaller_3  T_eff             0.05296
                                 mass_smaller_14 T_eff             0.05654
                                 mass_smaller_30 T_eff             0.07226
random_forest     MIST           Base            T_eff             0.00101
                                 mass_smaller_3  T_eff             0.00103
                                 mass_smaller_14 T_eff             0.00102
                                 mass_smaller_30 T_eff             0.00099
xgboost           MIST           Base            T_eff             0.03453
                                 mass_smaller_3  T_eff             0.01589
                                 mass_smaller_14 T_eff             0.03081
                                 mass_smaller_30 T_eff             0.03244

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.97513
                                 mass_smaller_3  T_eff             0.96698
                                 mass_smaller_14 T_eff             0.97503
                                 mass_smaller_30 T_eff             0.97284
KNN               MIST           Base            T_eff             0.98353
                                 mass_smaller_3  T_eff             0.98463
                                 mass_smaller_14 T_eff             0.98687
                                 mass_smaller_30 T_eff             0.98467
linear_regression MIST           Base            T_eff             0.85762
                                 mass_smaller_3  T_eff             0.80087
                                 mass_smaller_14 T_eff             0.82402
                                 mass_smaller_30 T_eff             0.84794
mlp               MIST           Base            T_eff             0.92191
                                 mass_smaller_3  T_eff             0.85942
                                 mass_smaller_14 T_eff             0.89530
                                 mass_smaller_30 T_eff             0.85265
random_forest     MIST           Base            T_eff             0.98351
                                 mass_smaller_3  T_eff             0.97824
                                 mass_smaller_14 T_eff             0.98362
                                 mass_smaller_30 T_eff             0.98205
xgboost           MIST           Base            T_eff             0.94909
                                 mass_smaller_3  T_eff             0.95097
                                 mass_smaller_14 T_eff             0.93234
                                 mass_smaller_30 T_eff             0.94131

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95071
                                 mass_smaller_3  T_eff             0.44718
                                 mass_smaller_14 T_eff             0.91705
                                 mass_smaller_30 T_eff             0.95102
KNN               MIST           Base            T_eff             0.92644
                                 mass_smaller_3  T_eff             0.41705
                                 mass_smaller_14 T_eff             0.88595
                                 mass_smaller_30 T_eff             0.91990
linear_regression MIST           Base            T_eff             0.98202
                                 mass_smaller_3  T_eff             0.39655
                                 mass_smaller_14 T_eff             0.76832
                                 mass_smaller_30 T_eff             0.95037
mlp               MIST           Base            T_eff             0.97704
                                 mass_smaller_3  T_eff             0.52459
                                 mass_smaller_14 T_eff             0.64463
                                 mass_smaller_30 T_eff             1.04212
random_forest     MIST           Base            T_eff             0.93308
                                 mass_smaller_3  T_eff             0.43044
                                 mass_smaller_14 T_eff             0.88883
                                 mass_smaller_30 T_eff             0.91376
xgboost           MIST           Base            T_eff             0.87367
                                 mass_smaller_3  T_eff             0.38800
                                 mass_smaller_14 T_eff             0.82046
                                 mass_smaller_30 T_eff             0.85115

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00427 / 90 : 0.02166 / 95 : 0.09746 / 99 : 0.42345
                                 mass_smaller_3  T_eff              75 : 0.00472 / 90 : 0.05086 / 95 : 0.11507 / 99 : 0.22325
                                 mass_smaller_14 T_eff               75 : 0.0043 / 90 : 0.02023 / 95 : 0.08661 / 99 : 0.24334
                                 mass_smaller_30 T_eff               75 : 0.00419 / 90 : 0.01996 / 95 : 0.0916 / 99 : 0.32118
KNN               MIST           Base            T_eff              75 : 0.00622 / 90 : 0.04667 / 95 : 0.09982 / 99 : 0.31342
                                 mass_smaller_3  T_eff              75 : 0.00564 / 90 : 0.04037 / 95 : 0.07343 / 99 : 0.14317
                                 mass_smaller_14 T_eff              75 : 0.00473 / 90 : 0.02803 / 95 : 0.06703 / 99 : 0.17616
                                 mass_smaller_30 T_eff               75 : 0.0051 / 90 : 0.03435 / 95 : 0.07975 / 99 : 0.25305
linear_regression MIST           Base            T_eff              75 : 0.19925 / 90 : 0.26261 / 95 : 0.33491 / 99 : 0.49514
                                 mass_smaller_3  T_eff              75 : 0.13308 / 90 : 0.17305 / 95 : 0.19823 / 99 : 0.27515
                                 mass_smaller_14 T_eff              75 : 0.18093 / 90 : 0.23499 / 95 : 0.28624 / 99 : 0.50201
                                 mass_smaller_30 T_eff               75 : 0.18644 / 90 : 0.24577 / 95 : 0.3075 / 99 : 0.53499
mlp               MIST           Base            T_eff              75 : 0.12551 / 90 : 0.23121 / 95 : 0.30635 / 99 : 0.43044
                                 mass_smaller_3  T_eff              75 : 0.11483 / 90 : 0.16631 / 95 : 0.19743 / 99 : 0.25269
                                 mass_smaller_14 T_eff              75 : 0.12599 / 90 : 0.22804 / 95 : 0.29284 / 99 : 0.40039
                                 mass_smaller_30 T_eff              75 : 0.16288 / 90 : 0.29303 / 95 : 0.37757 / 99 : 0.51242
random_forest     MIST           Base            T_eff              75 : 0.00392 / 90 : 0.03097 / 95 : 0.08743 / 99 : 0.31717
                                 mass_smaller_3  T_eff              75 : 0.00557 / 90 : 0.04726 / 95 : 0.09124 / 99 : 0.17501
                                 mass_smaller_14 T_eff               75 : 0.00383 / 90 : 0.02721 / 95 : 0.0747 / 99 : 0.19805
                                 mass_smaller_30 T_eff               75 : 0.00376 / 90 : 0.02825 / 95 : 0.0807 / 99 : 0.26673
xgboost           MIST           Base            T_eff              75 : 0.09802 / 90 : 0.18339 / 95 : 0.25166 / 99 : 0.37352
                                 mass_smaller_3  T_eff               75 : 0.05806 / 90 : 0.10125 / 95 : 0.1285 / 99 : 0.18066
                                 mass_smaller_14 T_eff              75 : 0.09281 / 90 : 0.17298 / 95 : 0.23878 / 99 : 0.36132
                                 mass_smaller_30 T_eff                75 : 0.09515 / 90 : 0.1785 / 95 : 0.2475 / 99 : 0.37369

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 0.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
KNN               MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
linear_regression MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
mlp               MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
random_forest     MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817
xgboost           MIST           Base            T_eff             3.34467 - 4.90341
                                 mass_smaller_3  T_eff             3.34467 - 4.30134
                                 mass_smaller_14 T_eff             3.34467 - 4.63449
                                 mass_smaller_30 T_eff             3.34467 - 4.89817

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.96019
                                 mass_smaller_3  T_eff             0.97740
                                 mass_smaller_14 T_eff             0.97099
                                 mass_smaller_30 T_eff             0.95823
KNN               MIST           Base            T_eff             0.96900
                                 mass_smaller_3  T_eff             0.98948
                                 mass_smaller_14 T_eff             0.98135
                                 mass_smaller_30 T_eff             0.97281
linear_regression MIST           Base            T_eff             0.75037
                                 mass_smaller_3  T_eff             0.79522
                                 mass_smaller_14 T_eff             0.74704
                                 mass_smaller_30 T_eff             0.74064
mlp               MIST           Base            T_eff             0.88942
                                 mass_smaller_3  T_eff             0.84068
                                 mass_smaller_14 T_eff             0.85328
                                 mass_smaller_30 T_eff             0.81285
random_forest     MIST           Base            T_eff             0.97420
                                 mass_smaller_3  T_eff             0.98642
                                 mass_smaller_14 T_eff             0.98125
                                 mass_smaller_30 T_eff             0.97319
xgboost           MIST           Base            T_eff             0.94101
                                 mass_smaller_3  T_eff             0.95885
                                 mass_smaller_14 T_eff             0.93300
                                 mass_smaller_30 T_eff             0.93384

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.07035
                                 mass_smaller_3  T_eff             0.03011
                                 mass_smaller_14 T_eff             0.05092
                                 mass_smaller_30 T_eff             0.06634
KNN               MIST           Base            T_eff             0.06264
                                 mass_smaller_3  T_eff             0.02057
                                 mass_smaller_14 T_eff             0.04099
                                 mass_smaller_30 T_eff             0.05382
linear_regression MIST           Base            T_eff             0.17867
                                 mass_smaller_3  T_eff             0.10012
                                 mass_smaller_14 T_eff             0.15761
                                 mass_smaller_30 T_eff             0.16967
mlp               MIST           Base            T_eff             0.12627
                                 mass_smaller_3  T_eff             0.09428
                                 mass_smaller_14 T_eff             0.13013
                                 mass_smaller_30 T_eff             0.14971
random_forest     MIST           Base            T_eff             0.05672
                                 mass_smaller_3  T_eff             0.02343
                                 mass_smaller_14 T_eff             0.04100
                                 mass_smaller_30 T_eff             0.05322
xgboost           MIST           Base            T_eff             0.09214
                                 mass_smaller_3  T_eff             0.04324
                                 mass_smaller_14 T_eff             0.08433
                                 mass_smaller_30 T_eff             0.09000

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.01167
                                 mass_smaller_3  T_eff             0.00564
                                 mass_smaller_14 T_eff             0.00702
                                 mass_smaller_30 T_eff             0.01014
KNN               MIST           Base            T_eff             0.01575
                                 mass_smaller_3  T_eff             0.00459
                                 mass_smaller_14 T_eff             0.00715
                                 mass_smaller_30 T_eff             0.01125
linear_regression MIST           Base            T_eff             0.15277
                                 mass_smaller_3  T_eff             0.08566
                                 mass_smaller_14 T_eff             0.13580
                                 mass_smaller_30 T_eff             0.14250
mlp               MIST           Base            T_eff             0.08112
                                 mass_smaller_3  T_eff             0.06911
                                 mass_smaller_14 T_eff             0.08671
                                 mass_smaller_30 T_eff             0.09505
random_forest     MIST           Base            T_eff             0.01024
                                 mass_smaller_3  T_eff             0.00475
                                 mass_smaller_14 T_eff             0.00597
                                 mass_smaller_30 T_eff             0.00880
xgboost           MIST           Base            T_eff             0.05084
                                 mass_smaller_3  T_eff             0.02268
                                 mass_smaller_14 T_eff             0.04437
                                 mass_smaller_30 T_eff             0.04853

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00115
                                 mass_smaller_3  T_eff             0.00086
                                 mass_smaller_14 T_eff             0.00102
                                 mass_smaller_30 T_eff             0.00107
KNN               MIST           Base            T_eff             0.00119
                                 mass_smaller_3  T_eff             0.00114
                                 mass_smaller_14 T_eff             0.00098
                                 mass_smaller_30 T_eff             0.00104
linear_regression MIST           Base            T_eff             0.15386
                                 mass_smaller_3  T_eff             0.08274
                                 mass_smaller_14 T_eff             0.13979
                                 mass_smaller_30 T_eff             0.14259
mlp               MIST           Base            T_eff             0.04218
                                 mass_smaller_3  T_eff             0.04259
                                 mass_smaller_14 T_eff             0.04772
                                 mass_smaller_30 T_eff             0.04996
random_forest     MIST           Base            T_eff             0.00058
                                 mass_smaller_3  T_eff             0.00049
                                 mass_smaller_14 T_eff             0.00053
                                 mass_smaller_30 T_eff             0.00055
xgboost           MIST           Base            T_eff             0.01609
                                 mass_smaller_3  T_eff             0.00665
                                 mass_smaller_14 T_eff             0.01270
                                 mass_smaller_30 T_eff             0.01441

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.98031
                                 mass_smaller_3  T_eff             0.98902
                                 mass_smaller_14 T_eff             0.98570
                                 mass_smaller_30 T_eff             0.97937
KNN               MIST           Base            T_eff             0.98438
                                 mass_smaller_3  T_eff             0.99482
                                 mass_smaller_14 T_eff             0.99066
                                 mass_smaller_30 T_eff             0.98633
linear_regression MIST           Base            T_eff             0.86626
                                 mass_smaller_3  T_eff             0.89971
                                 mass_smaller_14 T_eff             0.86536
                                 mass_smaller_30 T_eff             0.86061
mlp               MIST           Base            T_eff             0.94349
                                 mass_smaller_3  T_eff             0.91846
                                 mass_smaller_14 T_eff             0.92401
                                 mass_smaller_30 T_eff             0.90391
random_forest     MIST           Base            T_eff             0.98713
                                 mass_smaller_3  T_eff             0.99335
                                 mass_smaller_14 T_eff             0.99069
                                 mass_smaller_30 T_eff             0.98664
xgboost           MIST           Base            T_eff             0.97034
                                 mass_smaller_3  T_eff             0.97921
                                 mass_smaller_14 T_eff             0.96598
                                 mass_smaller_30 T_eff             0.96652

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95071
                                 mass_smaller_3  T_eff             0.43652
                                 mass_smaller_14 T_eff             0.91705
                                 mass_smaller_30 T_eff             0.95102
KNN               MIST           Base            T_eff             0.92644
                                 mass_smaller_3  T_eff             0.41705
                                 mass_smaller_14 T_eff             0.88582
                                 mass_smaller_30 T_eff             0.91990
linear_regression MIST           Base            T_eff             0.71583
                                 mass_smaller_3  T_eff             0.22314
                                 mass_smaller_14 T_eff             0.76832
                                 mass_smaller_30 T_eff             0.74677
mlp               MIST           Base            T_eff             0.80023
                                 mass_smaller_3  T_eff             0.31988
                                 mass_smaller_14 T_eff             0.59585
                                 mass_smaller_30 T_eff             1.03406
random_forest     MIST           Base            T_eff             0.89738
                                 mass_smaller_3  T_eff             0.43044
                                 mass_smaller_14 T_eff             0.88883
                                 mass_smaller_30 T_eff             0.90517
xgboost           MIST           Base            T_eff             0.80948
                                 mass_smaller_3  T_eff             0.29387
                                 mass_smaller_14 T_eff             0.75278
                                 mass_smaller_30 T_eff             0.81510

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00256 / 90 : 0.00472 / 95 : 0.01174 / 99 : 0.40476
                                 mass_smaller_3  T_eff              75 : 0.00197 / 90 : 0.00419 / 95 : 0.00773 / 99 : 0.19471
                                 mass_smaller_14 T_eff              75 : 0.00223 / 90 : 0.00399 / 95 : 0.00729 / 99 : 0.19457
                                 mass_smaller_30 T_eff              75 : 0.00237 / 90 : 0.00428 / 95 : 0.00946 / 99 : 0.28001
KNN               MIST           Base            T_eff               75 : 0.00325 / 90 : 0.01865 / 95 : 0.09229 / 99 : 0.3282
                                 mass_smaller_3  T_eff               75 : 0.0024 / 90 : 0.00458 / 95 : 0.00705 / 99 : 0.10441
                                 mass_smaller_14 T_eff               75 : 0.00233 / 90 : 0.00531 / 95 : 0.0105 / 99 : 0.15692
                                 mass_smaller_30 T_eff               75 : 0.00263 / 90 : 0.00762 / 95 : 0.04414 / 99 : 0.2751
linear_regression MIST           Base            T_eff              75 : 0.21036 / 90 : 0.25684 / 95 : 0.30189 / 99 : 0.43765
                                 mass_smaller_3  T_eff               75 : 0.12842 / 90 : 0.15487 / 95 : 0.1725 / 99 : 0.19345
                                 mass_smaller_14 T_eff              75 : 0.19274 / 90 : 0.23077 / 95 : 0.24862 / 99 : 0.33349
                                 mass_smaller_30 T_eff              75 : 0.20117 / 90 : 0.24367 / 95 : 0.26761 / 99 : 0.43833
mlp               MIST           Base            T_eff              75 : 0.10075 / 90 : 0.22594 / 95 : 0.30755 / 99 : 0.42108
                                 mass_smaller_3  T_eff              75 : 0.11639 / 90 : 0.16656 / 95 : 0.19535 / 99 : 0.24359
                                 mass_smaller_14 T_eff              75 : 0.11091 / 90 : 0.23916 / 95 : 0.30743 / 99 : 0.41344
                                 mass_smaller_30 T_eff              75 : 0.10867 / 90 : 0.27364 / 95 : 0.37476 / 99 : 0.47961
random_forest     MIST           Base            T_eff              75 : 0.00149 / 90 : 0.00505 / 95 : 0.02229 / 99 : 0.30808
                                 mass_smaller_3  T_eff              75 : 0.00127 / 90 : 0.00358 / 95 : 0.01051 / 99 : 0.13035
                                 mass_smaller_14 T_eff               75 : 0.0013 / 90 : 0.00354 / 95 : 0.00867 / 99 : 0.14171
                                 mass_smaller_30 T_eff               75 : 0.00138 / 90 : 0.00417 / 95 : 0.01479 / 99 : 0.2421
xgboost           MIST           Base            T_eff              75 : 0.06239 / 90 : 0.15626 / 95 : 0.22213 / 99 : 0.34633
                                 mass_smaller_3  T_eff              75 : 0.02135 / 90 : 0.07711 / 95 : 0.10589 / 99 : 0.16856
                                 mass_smaller_14 T_eff              75 : 0.04967 / 90 : 0.13734 / 95 : 0.20064 / 99 : 0.33639
                                 mass_smaller_30 T_eff                75 : 0.05789 / 90 : 0.1498 / 95 : 0.2151 / 99 : 0.35203

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 2.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
KNN               MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
linear_regression MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
mlp               MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
random_forest     MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498
xgboost           MIST           Base            T_eff             3.42786 - 4.71147
                                 mass_smaller_3  T_eff             3.43131 - 4.27651
                                 mass_smaller_14 T_eff             3.42453 - 4.58766
                                 mass_smaller_30 T_eff             3.42453 - 4.67498

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.95901
                                 mass_smaller_3  T_eff             0.77096
                                 mass_smaller_14 T_eff             0.92890
                                 mass_smaller_30 T_eff             0.95004
KNN               MIST           Base            T_eff             0.98360
                                 mass_smaller_3  T_eff             0.89345
                                 mass_smaller_14 T_eff             0.97242
                                 mass_smaller_30 T_eff             0.98139
linear_regression MIST           Base            T_eff             0.78059
                                 mass_smaller_3  T_eff             0.51209
                                 mass_smaller_14 T_eff             0.67815
                                 mass_smaller_30 T_eff             0.77809
mlp               MIST           Base            T_eff             0.84182
                                 mass_smaller_3  T_eff             0.53268
                                 mass_smaller_14 T_eff             0.73524
                                 mass_smaller_30 T_eff             0.61403
random_forest     MIST           Base            T_eff             0.97488
                                 mass_smaller_3  T_eff             0.84432
                                 mass_smaller_14 T_eff             0.95553
                                 mass_smaller_30 T_eff             0.96945
xgboost           MIST           Base            T_eff             0.87438
                                 mass_smaller_3  T_eff             0.75926
                                 mass_smaller_14 T_eff             0.77876
                                 mass_smaller_30 T_eff             0.84459

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.06407
                                 mass_smaller_3  T_eff             0.06883
                                 mass_smaller_14 T_eff             0.06550
                                 mass_smaller_30 T_eff             0.06445
KNN               MIST           Base            T_eff             0.04053
                                 mass_smaller_3  T_eff             0.04703
                                 mass_smaller_14 T_eff             0.04081
                                 mass_smaller_30 T_eff             0.03934
linear_regression MIST           Base            T_eff             0.14837
                                 mass_smaller_3  T_eff             0.11229
                                 mass_smaller_14 T_eff             0.14258
                                 mass_smaller_30 T_eff             0.13675
mlp               MIST           Base            T_eff             0.12586
                                 mass_smaller_3  T_eff             0.10020
                                 mass_smaller_14 T_eff             0.12643
                                 mass_smaller_30 T_eff             0.17930
random_forest     MIST           Base            T_eff             0.05016
                                 mass_smaller_3  T_eff             0.05684
                                 mass_smaller_14 T_eff             0.05181
                                 mass_smaller_30 T_eff             0.05040
xgboost           MIST           Base            T_eff             0.11425
                                 mass_smaller_3  T_eff             0.07337
                                 mass_smaller_14 T_eff             0.11845
                                 mass_smaller_30 T_eff             0.11604

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.02389
                                 mass_smaller_3  T_eff             0.03871
                                 mass_smaller_14 T_eff             0.02674
                                 mass_smaller_30 T_eff             0.02496
KNN               MIST           Base            T_eff             0.01684
                                 mass_smaller_3  T_eff             0.02689
                                 mass_smaller_14 T_eff             0.01830
                                 mass_smaller_30 T_eff             0.01705
linear_regression MIST           Base            T_eff             0.11891
                                 mass_smaller_3  T_eff             0.09124
                                 mass_smaller_14 T_eff             0.10823
                                 mass_smaller_30 T_eff             0.10625
mlp               MIST           Base            T_eff             0.09677
                                 mass_smaller_3  T_eff             0.08033
                                 mass_smaller_14 T_eff             0.09732
                                 mass_smaller_30 T_eff             0.13958
random_forest     MIST           Base            T_eff             0.01991
                                 mass_smaller_3  T_eff             0.03267
                                 mass_smaller_14 T_eff             0.02226
                                 mass_smaller_30 T_eff             0.02075
xgboost           MIST           Base            T_eff             0.08532
                                 mass_smaller_3  T_eff             0.05884
                                 mass_smaller_14 T_eff             0.08986
                                 mass_smaller_30 T_eff             0.08681

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00323
                                 mass_smaller_3  T_eff             0.00480
                                 mass_smaller_14 T_eff             0.00370
                                 mass_smaller_30 T_eff             0.00341
KNN               MIST           Base            T_eff             0.00216
                                 mass_smaller_3  T_eff             0.00665
                                 mass_smaller_14 T_eff             0.00266
                                 mass_smaller_30 T_eff             0.00229
linear_regression MIST           Base            T_eff             0.10571
                                 mass_smaller_3  T_eff             0.07963
                                 mass_smaller_14 T_eff             0.08911
                                 mass_smaller_30 T_eff             0.08979
mlp               MIST           Base            T_eff             0.07663
                                 mass_smaller_3  T_eff             0.06775
                                 mass_smaller_14 T_eff             0.07779
                                 mass_smaller_30 T_eff             0.11259
random_forest     MIST           Base            T_eff             0.00210
                                 mass_smaller_3  T_eff             0.00784
                                 mass_smaller_14 T_eff             0.00265
                                 mass_smaller_30 T_eff             0.00228
xgboost           MIST           Base            T_eff             0.06484
                                 mass_smaller_3  T_eff             0.05041
                                 mass_smaller_14 T_eff             0.07014
                                 mass_smaller_30 T_eff             0.06588

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.97945
                                 mass_smaller_3  T_eff             0.88476
                                 mass_smaller_14 T_eff             0.96418
                                 mass_smaller_30 T_eff             0.97489
KNN               MIST           Base            T_eff             0.99177
                                 mass_smaller_3  T_eff             0.94532
                                 mass_smaller_14 T_eff             0.98613
                                 mass_smaller_30 T_eff             0.99066
linear_regression MIST           Base            T_eff             0.88380
                                 mass_smaller_3  T_eff             0.73973
                                 mass_smaller_14 T_eff             0.82514
                                 mass_smaller_30 T_eff             0.88241
mlp               MIST           Base            T_eff             0.91766
                                 mass_smaller_3  T_eff             0.75574
                                 mass_smaller_14 T_eff             0.85764
                                 mass_smaller_30 T_eff             0.79799
random_forest     MIST           Base            T_eff             0.98736
                                 mass_smaller_3  T_eff             0.91997
                                 mass_smaller_14 T_eff             0.97752
                                 mass_smaller_30 T_eff             0.98461
xgboost           MIST           Base            T_eff             0.93580
                                 mass_smaller_3  T_eff             0.87167
                                 mass_smaller_14 T_eff             0.88254
                                 mass_smaller_30 T_eff             0.91943

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.84709
                                 mass_smaller_3  T_eff             0.40629
                                 mass_smaller_14 T_eff             0.82977
                                 mass_smaller_30 T_eff             0.86487
KNN               MIST           Base            T_eff             0.71255
                                 mass_smaller_3  T_eff             0.33967
                                 mass_smaller_14 T_eff             0.62606
                                 mass_smaller_30 T_eff             0.69827
linear_regression MIST           Base            T_eff             0.63134
                                 mass_smaller_3  T_eff             0.35365
                                 mass_smaller_14 T_eff             0.72518
                                 mass_smaller_30 T_eff             0.68560
mlp               MIST           Base            T_eff             0.65349
                                 mass_smaller_3  T_eff             0.34468
                                 mass_smaller_14 T_eff             0.54802
                                 mass_smaller_30 T_eff             0.90711
random_forest     MIST           Base            T_eff             0.71261
                                 mass_smaller_3  T_eff             0.30798
                                 mass_smaller_14 T_eff             0.72317
                                 mass_smaller_30 T_eff             0.69815
xgboost           MIST           Base            T_eff             0.50986
                                 mass_smaller_3  T_eff             0.26120
                                 mass_smaller_14 T_eff             0.52165
                                 mass_smaller_30 T_eff             0.48684

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              75 : 0.00789 / 90 : 0.08242 / 95 : 0.13794 / 99 : 0.23584
                                 mass_smaller_3  T_eff               75 : 0.05913 / 90 : 0.12783 / 95 : 0.16949 / 99 : 0.2268
                                 mass_smaller_14 T_eff               75 : 0.0145 / 90 : 0.09382 / 95 : 0.14629 / 99 : 0.23065
                                 mass_smaller_30 T_eff              75 : 0.01001 / 90 : 0.08773 / 95 : 0.14107 / 99 : 0.23055
KNN               MIST           Base            T_eff               75 : 0.01087 / 90 : 0.05726 / 95 : 0.0917 / 99 : 0.16337
                                 mass_smaller_3  T_eff              75 : 0.04026 / 90 : 0.08182 / 95 : 0.11058 / 99 : 0.16643
                                 mass_smaller_14 T_eff               75 : 0.0155 / 90 : 0.06208 / 95 : 0.09523 / 99 : 0.16225
                                 mass_smaller_30 T_eff              75 : 0.01193 / 90 : 0.05915 / 95 : 0.09295 / 99 : 0.15869
linear_regression MIST           Base            T_eff              75 : 0.16587 / 90 : 0.22216 / 95 : 0.28347 / 99 : 0.42765
                                 mass_smaller_3  T_eff              75 : 0.13149 / 90 : 0.18251 / 95 : 0.21442 / 99 : 0.28156
                                 mass_smaller_14 T_eff              75 : 0.14466 / 90 : 0.20896 / 95 : 0.28902 / 99 : 0.46973
                                 mass_smaller_30 T_eff              75 : 0.14427 / 90 : 0.20588 / 95 : 0.26343 / 99 : 0.43116
mlp               MIST           Base            T_eff               75 : 0.1347 / 90 : 0.20956 / 95 : 0.26236 / 99 : 0.35663
                                 mass_smaller_3  T_eff               75 : 0.1156 / 90 : 0.16717 / 95 : 0.19789 / 99 : 0.25215
                                 mass_smaller_14 T_eff              75 : 0.13623 / 90 : 0.21043 / 95 : 0.26145 / 99 : 0.35802
                                 mass_smaller_30 T_eff              75 : 0.19898 / 90 : 0.29875 / 95 : 0.35921 / 99 : 0.48333
random_forest     MIST           Base            T_eff              75 : 0.01118 / 90 : 0.06906 / 95 : 0.11139 / 99 : 0.19913
                                 mass_smaller_3  T_eff              75 : 0.04972 / 90 : 0.10192 / 95 : 0.13515 / 99 : 0.19473
                                 mass_smaller_14 T_eff              75 : 0.01781 / 90 : 0.07692 / 95 : 0.11807 / 99 : 0.19909
                                 mass_smaller_30 T_eff              75 : 0.01371 / 90 : 0.07218 / 95 : 0.11434 / 99 : 0.19716
xgboost           MIST           Base            T_eff              75 : 0.11863 / 90 : 0.18832 / 95 : 0.24477 / 99 : 0.34599
                                 mass_smaller_3  T_eff               75 : 0.0853 / 90 : 0.12113 / 95 : 0.14299 / 99 : 0.18504
                                 mass_smaller_14 T_eff               75 : 0.12351 / 90 : 0.19578 / 95 : 0.25317 / 99 : 0.3482
                                 mass_smaller_30 T_eff               75 : 0.12091 / 90 : 0.1925 / 95 : 0.24987 / 99 : 0.34624

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Results for the phase category with a value of 3.0

                                                                         value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
KNN               MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
linear_regression MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
mlp               MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
random_forest     MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417
xgboost           MIST           Base            T_eff              3.35162 - 5.3788
                                 mass_smaller_3  T_eff             3.35162 - 4.20753
                                 mass_smaller_14 T_eff             3.35162 - 4.52417
                                 mass_smaller_30 T_eff             3.35162 - 5.35417

                                                                       RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.88142
                                 mass_smaller_3  T_eff             0.87065
                                 mass_smaller_14 T_eff             0.84508
                                 mass_smaller_30 T_eff             0.86278
KNN               MIST           Base            T_eff             0.92720
                                 mass_smaller_3  T_eff             0.94238
                                 mass_smaller_14 T_eff             0.92125
                                 mass_smaller_30 T_eff             0.92511
linear_regression MIST           Base            T_eff             0.60534
                                 mass_smaller_3  T_eff             0.38535
                                 mass_smaller_14 T_eff             0.42918
                                 mass_smaller_30 T_eff             0.57042
mlp               MIST           Base            T_eff             0.76217
                                 mass_smaller_3  T_eff             0.56861
                                 mass_smaller_14 T_eff             0.71984
                                 mass_smaller_30 T_eff             0.53400
random_forest     MIST           Base            T_eff             0.91798
                                 mass_smaller_3  T_eff             0.91785
                                 mass_smaller_14 T_eff             0.89558
                                 mass_smaller_30 T_eff             0.90440
xgboost           MIST           Base            T_eff             0.83805
                                 mass_smaller_3  T_eff             0.81282
                                 mass_smaller_14 T_eff             0.75437
                                 mass_smaller_30 T_eff             0.80911

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.10650
                                 mass_smaller_3  T_eff             0.05348
                                 mass_smaller_14 T_eff             0.08919
                                 mass_smaller_30 T_eff             0.10195
KNN               MIST           Base            T_eff             0.08394
                                 mass_smaller_3  T_eff             0.03568
                                 mass_smaller_14 T_eff             0.06361
                                 mass_smaller_30 T_eff             0.07546
linear_regression MIST           Base            T_eff             0.21019
                                 mass_smaller_3  T_eff             0.13340
                                 mass_smaller_14 T_eff             0.19536
                                 mass_smaller_30 T_eff             0.20129
mlp               MIST           Base            T_eff             0.16539
                                 mass_smaller_3  T_eff             0.10045
                                 mass_smaller_14 T_eff             0.13173
                                 mass_smaller_30 T_eff             0.20143
random_forest     MIST           Base            T_eff             0.08865
                                 mass_smaller_3  T_eff             0.04262
                                 mass_smaller_14 T_eff             0.07328
                                 mass_smaller_30 T_eff             0.08516
xgboost           MIST           Base            T_eff             0.14039
                                 mass_smaller_3  T_eff             0.06715
                                 mass_smaller_14 T_eff             0.12652
                                 mass_smaller_30 T_eff             0.13559

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.03049
                                 mass_smaller_3  T_eff             0.01971
                                 mass_smaller_14 T_eff             0.02352
                                 mass_smaller_30 T_eff             0.02718
KNN               MIST           Base            T_eff             0.02906
                                 mass_smaller_3  T_eff             0.01590
                                 mass_smaller_14 T_eff             0.02006
                                 mass_smaller_30 T_eff             0.02378
linear_regression MIST           Base            T_eff             0.15327
                                 mass_smaller_3  T_eff             0.10536
                                 mass_smaller_14 T_eff             0.13812
                                 mass_smaller_30 T_eff             0.14212
mlp               MIST           Base            T_eff             0.11481
                                 mass_smaller_3  T_eff             0.07691
                                 mass_smaller_14 T_eff             0.09337
                                 mass_smaller_30 T_eff             0.14771
random_forest     MIST           Base            T_eff             0.02720
                                 mass_smaller_3  T_eff             0.01738
                                 mass_smaller_14 T_eff             0.02113
                                 mass_smaller_30 T_eff             0.02427
xgboost           MIST           Base            T_eff             0.09651
                                 mass_smaller_3  T_eff             0.04837
                                 mass_smaller_14 T_eff             0.08613
                                 mass_smaller_30 T_eff             0.09117

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.00343
                                 mass_smaller_3  T_eff             0.00272
                                 mass_smaller_14 T_eff             0.00328
                                 mass_smaller_30 T_eff             0.00322
KNN               MIST           Base            T_eff             0.00421
                                 mass_smaller_3  T_eff             0.00378
                                 mass_smaller_14 T_eff             0.00368
                                 mass_smaller_30 T_eff             0.00377
linear_regression MIST           Base            T_eff             0.10620
                                 mass_smaller_3  T_eff             0.08282
                                 mass_smaller_14 T_eff             0.09380
                                 mass_smaller_30 T_eff             0.09629
mlp               MIST           Base            T_eff             0.07511
                                 mass_smaller_3  T_eff             0.06081
                                 mass_smaller_14 T_eff             0.06400
                                 mass_smaller_30 T_eff             0.10873
random_forest     MIST           Base            T_eff             0.00314
                                 mass_smaller_3  T_eff             0.00316
                                 mass_smaller_14 T_eff             0.00311
                                 mass_smaller_30 T_eff             0.00298
xgboost           MIST           Base            T_eff             0.06314
                                 mass_smaller_3  T_eff             0.03287
                                 mass_smaller_14 T_eff             0.05556
                                 mass_smaller_30 T_eff             0.05795

                                                                      CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.94126
                                 mass_smaller_3  T_eff             0.93361
                                 mass_smaller_14 T_eff             0.92359
                                 mass_smaller_30 T_eff             0.93213
KNN               MIST           Base            T_eff             0.96403
                                 mass_smaller_3  T_eff             0.97099
                                 mass_smaller_14 T_eff             0.96028
                                 mass_smaller_30 T_eff             0.96248
linear_regression MIST           Base            T_eff             0.78745
                                 mass_smaller_3  T_eff             0.67438
                                 mass_smaller_14 T_eff             0.71182
                                 mass_smaller_30 T_eff             0.77357
mlp               MIST           Base            T_eff             0.87806
                                 mass_smaller_3  T_eff             0.77571
                                 mass_smaller_14 T_eff             0.85260
                                 mass_smaller_30 T_eff             0.77117
random_forest     MIST           Base            T_eff             0.95873
                                 mass_smaller_3  T_eff             0.95810
                                 mass_smaller_14 T_eff             0.94734
                                 mass_smaller_30 T_eff             0.95186
xgboost           MIST           Base            T_eff             0.91556
                                 mass_smaller_3  T_eff             0.90198
                                 mass_smaller_14 T_eff             0.87143
                                 mass_smaller_30 T_eff             0.90015

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff             0.93139
                                 mass_smaller_3  T_eff             0.44718
                                 mass_smaller_14 T_eff             0.91146
                                 mass_smaller_30 T_eff             0.93366
KNN               MIST           Base            T_eff             0.91675
                                 mass_smaller_3  T_eff             0.41430
                                 mass_smaller_14 T_eff             0.88595
                                 mass_smaller_30 T_eff             0.91158
linear_regression MIST           Base            T_eff             0.98202
                                 mass_smaller_3  T_eff             0.39655
                                 mass_smaller_14 T_eff             0.75693
                                 mass_smaller_30 T_eff             0.95037
mlp               MIST           Base            T_eff             0.97704
                                 mass_smaller_3  T_eff             0.52459
                                 mass_smaller_14 T_eff             0.64463
                                 mass_smaller_30 T_eff             1.04212
random_forest     MIST           Base            T_eff             0.93308
                                 mass_smaller_3  T_eff             0.41916
                                 mass_smaller_14 T_eff             0.87264
                                 mass_smaller_30 T_eff             0.91376
xgboost           MIST           Base            T_eff             0.87367
                                 mass_smaller_3  T_eff             0.38800
                                 mass_smaller_14 T_eff             0.82046
                                 mass_smaller_30 T_eff             0.85115

                                                                                                                   Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff               75 : 0.00987 / 90 : 0.05367 / 95 : 0.15861 / 99 : 0.6234
                                 mass_smaller_3  T_eff               75 : 0.01078 / 90 : 0.0549 / 95 : 0.11789 / 99 : 0.28011
                                 mass_smaller_14 T_eff              75 : 0.00931 / 90 : 0.03439 / 95 : 0.11243 / 99 : 0.49627
                                 mass_smaller_30 T_eff               75 : 0.0092 / 90 : 0.03894 / 95 : 0.13073 / 99 : 0.66352
KNN               MIST           Base            T_eff              75 : 0.01918 / 90 : 0.06825 / 95 : 0.14393 / 99 : 0.43934
                                 mass_smaller_3  T_eff              75 : 0.01594 / 90 : 0.04753 / 95 : 0.07039 / 99 : 0.15954
                                 mass_smaller_14 T_eff              75 : 0.01433 / 90 : 0.04415 / 95 : 0.07949 / 99 : 0.31662
                                 mass_smaller_30 T_eff              75 : 0.01578 / 90 : 0.05188 / 95 : 0.10037 / 99 : 0.39911
linear_regression MIST           Base            T_eff              75 : 0.21166 / 90 : 0.36121 / 95 : 0.45759 / 99 : 0.60611
                                 mass_smaller_3  T_eff               75 : 0.1652 / 90 : 0.22101 / 95 : 0.25872 / 99 : 0.32763
                                 mass_smaller_14 T_eff              75 : 0.18089 / 90 : 0.32896 / 95 : 0.45534 / 99 : 0.61901
                                 mass_smaller_30 T_eff               75 : 0.18784 / 90 : 0.3445 / 95 : 0.46674 / 99 : 0.62964
mlp               MIST           Base            T_eff               75 : 0.15645 / 90 : 0.2835 / 95 : 0.35727 / 99 : 0.54147
                                 mass_smaller_3  T_eff               75 : 0.11032 / 90 : 0.1637 / 95 : 0.20588 / 99 : 0.28983
                                 mass_smaller_14 T_eff              75 : 0.13038 / 90 : 0.22651 / 95 : 0.29624 / 99 : 0.40679
                                 mass_smaller_30 T_eff              75 : 0.19535 / 90 : 0.32514 / 95 : 0.42013 / 99 : 0.67228
random_forest     MIST           Base            T_eff              75 : 0.01243 / 90 : 0.05812 / 95 : 0.13501 / 99 : 0.49095
                                 mass_smaller_3  T_eff              75 : 0.01337 / 90 : 0.05079 / 95 : 0.08983 / 99 : 0.20541
                                 mass_smaller_14 T_eff              75 : 0.01102 / 90 : 0.04317 / 95 : 0.09179 / 99 : 0.40046
                                 mass_smaller_30 T_eff              75 : 0.01092 / 90 : 0.04684 / 95 : 0.10789 / 99 : 0.49952
xgboost           MIST           Base            T_eff               75 : 0.13011 / 90 : 0.24272 / 95 : 0.3206 / 99 : 0.43713
                                 mass_smaller_3  T_eff              75 : 0.07337 / 90 : 0.11548 / 95 : 0.14339 / 99 : 0.19664
                                 mass_smaller_14 T_eff               75 : 0.11553 / 90 : 0.21641 / 95 : 0.3024 / 99 : 0.39371
                                 mass_smaller_30 T_eff              75 : 0.11964 / 90 : 0.23036 / 95 : 0.31839 / 99 : 0.43258

                                                                        time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            T_eff              17.94015
                                 mass_smaller_3  T_eff               7.84036
                                 mass_smaller_14 T_eff              13.36124
                                 mass_smaller_30 T_eff              16.16098
KNN               MIST           Base            T_eff               6.34613
                                 mass_smaller_3  T_eff               2.54189
                                 mass_smaller_14 T_eff               4.20966
                                 mass_smaller_30 T_eff               5.29456
linear_regression MIST           Base            T_eff               1.10554
                                 mass_smaller_3  T_eff               0.31400
                                 mass_smaller_14 T_eff               0.53023
                                 mass_smaller_30 T_eff               0.57358
mlp               MIST           Base            T_eff             424.22548
                                 mass_smaller_3  T_eff             203.75131
                                 mass_smaller_14 T_eff             339.60009
                                 mass_smaller_30 T_eff             214.47888
random_forest     MIST           Base            T_eff             293.08635
                                 mass_smaller_3  T_eff             125.78221
                                 mass_smaller_14 T_eff             223.16509
                                 mass_smaller_30 T_eff             253.36178
xgboost           MIST           Base            T_eff              17.97334
                                 mass_smaller_3  T_eff               9.70526
                                 mass_smaller_14 T_eff              14.96473
                                 mass_smaller_30 T_eff              14.46076

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better results than Base on every metric except P99

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER and P99
- mass_smaller_14 : worse results than Base on every metric except MAX_ER, P90 and P99
- mass_smaller_30 : better/similar results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric except P99
- mass_smaller_30 : better/similar results than Base on every metric

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and MAX_ER
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : worse results than Base on every metric

#### Conclusions on T_eff

mass_smaller_3 is always worse than Base.

mass_smaller_14 is always worse than Base.

mass_smaller_30 is always better or similar to Base.

But it is important to note that the range does not change a lot and the errors without relativity to the range do not have that much of a difference.

#### Best models for the T_eff parameter

The three best performing models in order for the mass parameter are Random forest, KNN and decision tree.

### Radius parameter

In [22]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
KNN               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
mlp               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.8155741609143345
                                 mass_smaller_3  radius             0.6813803019471154
                                 mass_smaller_14 radius             0.7834989803759971
                                 mass_smaller_30 radius             0.7901160695649663
KNN               MIST           Base            radius             0.9043914862732579
                                 mass_smaller_3  radius             0.8544471075170126
                                 mass_smaller_14 radius              0.897478837024348
                                 mass_smaller_30 radius             0.8975823132234476
linear_regression MIST           Base            radius            0.19856216776938762
                                 mass_smaller_3  radius            0.41944480979620613
                                 mass_smaller_14 radius              0.314088761140893
                                 mass_smaller_30 radius             0.2456438925301918
mlp               MIST           Base            radius             0.7570156135268156
                                 mass_smaller_3  radius             0.6444511414397914
                                 mass_smaller_14 radius             0.7019859105066648
                                 mass_smaller_30 radius             0.5008492082149913
random_forest     MIST           Base            radius             0.8776105127019214
                                 mass_smaller_3  radius             0.7909281628598143
                                 mass_smaller_14 radius             0.8562731444960898
                                 mass_smaller_30 radius             0.8612812279603893
xgboost           MIST           Base            radius             0.8250961607541988
                                 mass_smaller_3  radius             0.8179235085333942
                                 mass_smaller_14 radius              0.805581593834652
                                 mass_smaller_30 radius             0.8085546865245665

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             7.68088%
                                 mass_smaller_3  radius            10.43277%
                                 mass_smaller_14 radius             8.03792%
                                 mass_smaller_30 radius             7.89114%
KNN               MIST           Base            radius              5.5336%
                                 mass_smaller_3  radius             7.05194%
                                 mass_smaller_14 radius              5.5326%
                                 mass_smaller_30 radius              5.5146%
linear_regression MIST           Base            radius            16.01055%
                                 mass_smaller_3  radius            14.08097%
                                 mass_smaller_14 radius            14.30581%
                                 mass_smaller_30 radius            14.95897%
mlp               MIST           Base            radius             8.87463%
                                 mass_smaller_3  radius            11.02065%
                                 mass_smaller_14 radius             9.57033%
                                 mass_smaller_30 radius            12.16998%
random_forest     MIST           Base            radius             6.25728%
                                 mass_smaller_3  radius             8.45121%
                                 mass_smaller_14 radius             6.54927%
                                 mass_smaller_30 radius              6.4155%
xgboost           MIST           Base            radius             7.47947%
                                 mass_smaller_3  radius             7.88566%
                                 mass_smaller_14 radius             7.61635%
                                 mass_smaller_30 radius             7.53591%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             2.12385%
                                 mass_smaller_3  radius             3.44458%
                                 mass_smaller_14 radius             2.23847%
                                 mass_smaller_30 radius             2.18437%
KNN               MIST           Base            radius             1.83831%
                                 mass_smaller_3  radius              2.5208%
                                 mass_smaller_14 radius             1.71757%
                                 mass_smaller_30 radius             1.74531%
linear_regression MIST           Base            radius            13.23913%
                                 mass_smaller_3  radius             11.3089%
                                 mass_smaller_14 radius            11.41533%
                                 mass_smaller_30 radius            11.94486%
mlp               MIST           Base            radius             5.85675%
                                 mass_smaller_3  radius             7.13177%
                                 mass_smaller_14 radius             6.42474%
                                 mass_smaller_30 radius             8.23567%
random_forest     MIST           Base            radius             1.85127%
                                 mass_smaller_3  radius             2.98463%
                                 mass_smaller_14 radius             1.94743%
                                 mass_smaller_30 radius             1.89755%
xgboost           MIST           Base            radius             4.81548%
                                 mass_smaller_3  radius             4.64369%
                                 mass_smaller_14 radius             4.88373%
                                 mass_smaller_30 radius             4.83095%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.11272%
                                 mass_smaller_3  radius             0.11211%
                                 mass_smaller_14 radius             0.11222%
                                 mass_smaller_30 radius             0.11001%
KNN               MIST           Base            radius             0.09215%
                                 mass_smaller_3  radius             0.10623%
                                 mass_smaller_14 radius             0.08603%
                                 mass_smaller_30 radius             0.08522%
linear_regression MIST           Base            radius            11.47659%
                                 mass_smaller_3  radius             9.90535%
                                 mass_smaller_14 radius             9.41273%
                                 mass_smaller_30 radius             9.72037%
mlp               MIST           Base            radius             3.04591%
                                 mass_smaller_3  radius             3.28518%
                                 mass_smaller_14 radius             3.28777%
                                 mass_smaller_30 radius             4.35791%
random_forest     MIST           Base            radius             0.05635%
                                 mass_smaller_3  radius             0.05843%
                                 mass_smaller_14 radius             0.05543%
                                 mass_smaller_30 radius             0.05342%
xgboost           MIST           Base            radius             2.42428%
                                 mass_smaller_3  radius             1.85755%
                                 mass_smaller_14 radius             2.42202%
                                 mass_smaller_30 radius             2.38222%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.908046242988254
                                 mass_smaller_3  radius            0.8419035771879697
                                 mass_smaller_14 radius            0.8922261811712158
                                 mass_smaller_30 radius            0.8955234190221543
KNN               MIST           Base            radius            0.9513432795547301
                                 mass_smaller_3  radius            0.9249854638398343
                                 mass_smaller_14 radius            0.9476753422536481
                                 mass_smaller_30 radius            0.9477664655557928
linear_regression MIST           Base            radius            0.4456031520460739
                                 mass_smaller_3  radius            0.6476455899305139
                                 mass_smaller_14 radius            0.5604362239996286
                                 mass_smaller_30 radius            0.4956247505107052
mlp               MIST           Base            radius             0.870162623980867
                                 mass_smaller_3  radius            0.8037429900849645
                                 mass_smaller_14 radius            0.8380678806130963
                                 mass_smaller_30 radius            0.7344859272641178
random_forest     MIST           Base            radius            0.9377254771026249
                                 mass_smaller_3  radius            0.8923834308438076
                                 mass_smaller_14 radius            0.9266852908075508
                                 mass_smaller_30 radius               0.9292823709225
xgboost           MIST           Base            radius            0.9085430473618937
                                 mass_smaller_3  radius            0.9046341479324373
                                 mass_smaller_14 radius            0.8977703702232838
                                 mass_smaller_30 radius            0.8994303143903841

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            68.70409%
                                 mass_smaller_3  radius             75.0767%
                                 mass_smaller_14 radius            69.78073%
                                 mass_smaller_30 radius            68.61564%
KNN               MIST           Base            radius            68.74998%
                                 mass_smaller_3  radius             75.0386%
                                 mass_smaller_14 radius            69.28761%
                                 mass_smaller_30 radius            68.41746%
linear_regression MIST           Base            radius            49.52014%
                                 mass_smaller_3  radius             67.6647%
                                 mass_smaller_14 radius            52.65001%
                                 mass_smaller_30 radius            48.28021%
mlp               MIST           Base            radius            68.62412%
                                 mass_smaller_3  radius            72.22869%
                                 mass_smaller_14 radius             68.4321%
                                 mass_smaller_30 radius            66.54739%
random_forest     MIST           Base            radius             68.7036%
                                 mass_smaller_3  radius            75.04157%
                                 mass_smaller_14 radius            69.29905%
                                 mass_smaller_30 radius            68.42441%
xgboost           MIST           Base            radius            62.53131%
                                 mass_smaller_3  radius             68.4045%
                                 mass_smaller_14 radius            60.98666%
                                 mass_smaller_30 radius            61.13306%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.24935% / 90 : 2.57177% / 95 : 16.51234% / 99 : 40.59071%
                                 mass_smaller_3  radius             75 : 0.32074% / 90 : 11.84535% / 95 : 26.21321% / 99 : 49.31114%
                                 mass_smaller_14 radius               75 : 0.2466% / 90 : 2.85203% / 95 : 17.62722% / 99 : 41.94464%
                                 mass_smaller_30 radius                75 : 0.24084% / 90 : 2.641% / 95 : 17.27047% / 99 : 41.27769%
KNN               MIST           Base            radius              75 : 0.42794% / 90 : 5.63594% / 95 : 12.38922% / 99 : 26.30919%
                                 mass_smaller_3  radius              75 : 0.49196% / 90 : 9.42129% / 95 : 17.02559% / 99 : 30.58526%
                                 mass_smaller_14 radius              75 : 0.31474% / 90 : 4.73117% / 95 : 12.19597% / 99 : 26.37697%
                                 mass_smaller_30 radius              75 : 0.34139% / 90 : 4.98132% / 95 : 12.12585% / 99 : 26.31216%
linear_regression MIST           Base            radius             75 : 17.83736% / 90 : 26.5503% / 95 : 31.47963% / 99 : 38.85568%
                                 mass_smaller_3  radius            75 : 14.84394% / 90 : 21.04806% / 95 : 27.86639% / 99 : 41.81031%
                                 mass_smaller_14 radius            75 : 16.96562% / 90 : 24.06102% / 95 : 27.97886% / 99 : 35.51353%
                                 mass_smaller_30 radius            75 : 17.33614% / 90 : 25.54166% / 95 : 30.10212% / 99 : 36.98594%
mlp               MIST           Base            radius             75 : 9.35534% / 90 : 15.75532% / 95 : 19.32812% / 99 : 27.34124%
                                 mass_smaller_3  radius            75 : 10.96518% / 90 : 19.62458% / 95 : 25.19357% / 99 : 34.50425%
                                 mass_smaller_14 radius             75 : 10.7713% / 90 : 17.21467% / 95 : 20.23413% / 99 : 27.75139%
                                 mass_smaller_30 radius             75 : 13.1522% / 90 : 22.05651% / 95 : 26.17526% / 99 : 36.22392%
random_forest     MIST           Base            radius              75 : 0.23142% / 90 : 4.06157% / 95 : 13.91319% / 99 : 31.46581%
                                 mass_smaller_3  radius              75 : 0.50307% / 90 : 11.1221% / 95 : 21.17773% / 99 : 38.28536%
                                 mass_smaller_14 radius              75 : 0.23042% / 90 : 4.41986% / 95 : 14.79798% / 99 : 32.85367%
                                 mass_smaller_30 radius              75 : 0.22025% / 90 : 4.21228% / 95 : 14.45744% / 99 : 32.24497%
xgboost           MIST           Base            radius             75 : 7.31523% / 90 : 13.04349% / 95 : 16.62889% / 99 : 23.85544%
                                 mass_smaller_3  radius             75 : 6.52327% / 90 : 13.23337% / 95 : 18.32548% / 99 : 28.25117%
                                 mass_smaller_14 radius              75 : 7.51211% / 90 : 13.2532% / 95 : 16.94381% / 99 : 24.10833%
                                 mass_smaller_30 radius              75 : 7.34345% / 90 : 13.12289% / 95 : 16.81666% / 99 : 23.9607%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511
                                 mass_smaller_3  radius             203.75130891799927

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.8362997592078089
                                 mass_smaller_3  radius              0.3860599348423952
                                 mass_smaller_14 radius              0.7239370774639855
                                 mass_smaller_30 radius              0.7889707604937268
KNN               MIST           Base            radius              0.8957368145865507
                                 mass_smaller_3  radius              0.6964623631952935
                                 mass_smaller_14 radius               0.849444000345548
                                 mass_smaller_30 radius               0.878962963156113
linear_regression MIST           Base            radius              0.4447713018606766
                                 mass_smaller_3  radius            -0.20822089580122594
                                 mass_smaller_14 radius             0.22469211359168928
                                 mass_smaller_30 radius             0.43522613091488316
mlp               MIST           Base            radius              0.7459947947493104
                                 mass_smaller_3  radius             0.19097817221195146
                                 mass_smaller_14 radius             0.48473145728270606
                                 mass_smaller_30 radius             0.44506374825504247
random_forest     MIST           Base            radius               0.895944647709672
                                 mass_smaller_3  radius              0.6267123490082731
                                 mass_smaller_14 radius              0.8274921577145724
                                 mass_smaller_30 radius               0.867058646092464
xgboost           MIST           Base            radius              0.8325938372230868
                                 mass_smaller_3  radius              0.5720666346088736
                                 mass_smaller_14 radius              0.7102589478863934
                                 mass_smaller_30 radius              0.7873612816207101

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              5.6898%
                                 mass_smaller_3  radius            14.30347%
                                 mass_smaller_14 radius             5.46235%
                                 mass_smaller_30 radius             5.73089%
KNN               MIST           Base            radius             4.58944%
                                 mass_smaller_3  radius            10.07942%
                                 mass_smaller_14 radius             4.05337%
                                 mass_smaller_30 radius              4.3704%
linear_regression MIST           Base            radius            15.33939%
                                 mass_smaller_3  radius            25.54716%
                                 mass_smaller_14 radius             13.0895%
                                 mass_smaller_30 radius            13.79434%
mlp               MIST           Base            radius             8.04191%
                                 mass_smaller_3  radius            18.13249%
                                 mass_smaller_14 radius             8.95429%
                                 mass_smaller_30 radius            10.17176%
random_forest     MIST           Base            radius             4.55042%
                                 mass_smaller_3  radius            11.20315%
                                 mass_smaller_14 radius             4.33274%
                                 mass_smaller_30 radius             4.56248%
xgboost           MIST           Base            radius              6.2399%
                                 mass_smaller_3  radius            12.55431%
                                 mass_smaller_14 radius             6.10784%
                                 mass_smaller_30 radius             6.23992%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.93531%
                                 mass_smaller_3  radius             2.06635%
                                 mass_smaller_14 radius             0.74986%
                                 mass_smaller_30 radius             0.88418%
KNN               MIST           Base            radius             1.13459%
                                 mass_smaller_3  radius             1.69932%
                                 mass_smaller_14 radius             0.71117%
                                 mass_smaller_30 radius             0.91376%
linear_regression MIST           Base            radius            12.83078%
                                 mass_smaller_3  radius            22.27107%
                                 mass_smaller_14 radius            10.16758%
                                 mass_smaller_30 radius            10.81206%
mlp               MIST           Base            radius             4.63773%
                                 mass_smaller_3  radius             9.70704%
                                 mass_smaller_14 radius             5.39856%
                                 mass_smaller_30 radius             5.97698%
random_forest     MIST           Base            radius             0.84445%
                                 mass_smaller_3  radius             1.89569%
                                 mass_smaller_14 radius             0.67968%
                                 mass_smaller_30 radius              0.7976%
xgboost           MIST           Base            radius             3.46212%
                                 mass_smaller_3  radius             5.72068%
                                 mass_smaller_14 radius             3.25528%
                                 mass_smaller_30 radius             3.41942%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.07006%
                                 mass_smaller_3  radius             0.11843%
                                 mass_smaller_14 radius             0.06094%
                                 mass_smaller_30 radius             0.06496%
KNN               MIST           Base            radius             0.05836%
                                 mass_smaller_3  radius             0.12615%
                                 mass_smaller_14 radius             0.04726%
                                 mass_smaller_30 radius             0.05102%
linear_regression MIST           Base            radius            11.66998%
                                 mass_smaller_3  radius            21.68166%
                                 mass_smaller_14 radius             7.58202%
                                 mass_smaller_30 radius             8.26743%
mlp               MIST           Base            radius             1.04095%
                                 mass_smaller_3  radius              2.9089%
                                 mass_smaller_14 radius             1.21098%
                                 mass_smaller_30 radius             1.82764%
random_forest     MIST           Base            radius             0.02822%
                                 mass_smaller_3  radius             0.04841%
                                 mass_smaller_14 radius             0.02382%
                                 mass_smaller_30 radius             0.02536%
xgboost           MIST           Base            radius             0.96479%
                                 mass_smaller_3  radius             1.25839%
                                 mass_smaller_14 radius             0.83797%
                                 mass_smaller_30 radius             0.93601%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9266704914779671
                                 mass_smaller_3  radius             0.803251675998881
                                 mass_smaller_14 radius             0.887290831162512
                                 mass_smaller_30 radius             0.908472573531127
KNN               MIST           Base            radius            0.9538577488062183
                                 mass_smaller_3  radius            0.8839207964856702
                                 mass_smaller_14 radius            0.9351653848778183
                                 mass_smaller_30 radius            0.9461368898191871
linear_regression MIST           Base            radius            0.6719624779362757
                                 mass_smaller_3  radius            0.6426645360484811
                                 mass_smaller_14 radius            0.5947013137402104
                                 mass_smaller_30 radius            0.6630070969610159
mlp               MIST           Base            radius            0.9040382509041051
                                 mass_smaller_3  radius            0.8366833440684885
                                 mass_smaller_14 radius            0.8677287985184537
                                 mass_smaller_30 radius            0.8128531007437122
random_forest     MIST           Base            radius            0.9515577145193358
                                 mass_smaller_3  radius            0.8656451900394606
                                 mass_smaller_14 radius            0.9250715450137749
                                 mass_smaller_30 radius            0.9393845002936859
xgboost           MIST           Base            radius            0.9316960163015878
                                 mass_smaller_3  radius             0.887840588032607
                                 mass_smaller_14 radius            0.9153577170512818
                                 mass_smaller_30 radius            0.9205772750607841

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              69.4522%
                                 mass_smaller_3  radius            160.55903%
                                 mass_smaller_14 radius             69.78073%
                                 mass_smaller_30 radius              69.3233%
KNN               MIST           Base            radius             68.33134%
                                 mass_smaller_3  radius            158.22055%
                                 mass_smaller_14 radius             68.00774%
                                 mass_smaller_30 radius             68.21537%
linear_regression MIST           Base            radius             50.08468%
                                 mass_smaller_3  radius             66.47507%
                                 mass_smaller_14 radius             41.14256%
                                 mass_smaller_30 radius             46.67504%
mlp               MIST           Base            radius             48.93262%
                                 mass_smaller_3  radius             92.30827%
                                 mass_smaller_14 radius             42.80368%
                                 mass_smaller_30 radius             55.79403%
random_forest     MIST           Base            radius             68.43104%
                                 mass_smaller_3  radius            157.59275%
                                 mass_smaller_14 radius             68.37084%
                                 mass_smaller_30 radius             67.45209%
xgboost           MIST           Base            radius             63.24418%
                                 mass_smaller_3  radius            146.83423%
                                 mass_smaller_14 radius             60.98666%
                                 mass_smaller_30 radius             61.83726%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius               75 : 0.13259% / 90 : 0.26935% / 95 : 0.52032% / 99 : 37.99136%
                                 mass_smaller_3  radius                75 : 0.22495% / 90 : 0.3823% / 95 : 0.59759% / 99 : 98.44802%
                                 mass_smaller_14 radius                75 : 0.11423% / 90 : 0.1961% / 95 : 0.30101% / 99 : 38.96612%
                                 mass_smaller_30 radius               75 : 0.12156% / 90 : 0.22376% / 95 : 0.38699% / 99 : 39.35477%
KNN               MIST           Base            radius                 75 : 0.17989% / 90 : 1.197% / 95 : 6.69205% / 99 : 24.24062%
                                 mass_smaller_3  radius               75 : 0.27778% / 90 : 0.59021% / 95 : 1.13668% / 99 : 53.59719%
                                 mass_smaller_14 radius               75 : 0.11791% / 90 : 0.33239% / 95 : 0.86113% / 99 : 21.81715%
                                 mass_smaller_30 radius               75 : 0.13749% / 90 : 0.56615% / 95 : 3.20939% / 99 : 23.51591%
linear_regression MIST           Base            radius             75 : 17.26648% / 90 : 24.7553% / 95 : 29.65308% / 99 : 36.47355%
                                 mass_smaller_3  radius             75 : 30.97437% / 90 : 39.4526% / 95 : 43.72551% / 99 : 51.51697%
                                 mass_smaller_14 radius               75 : 15.413% / 90 : 22.7148% / 95 : 26.57332% / 99 : 32.95736%
                                 mass_smaller_30 radius            75 : 16.06385% / 90 : 23.78305% / 95 : 28.30144% / 99 : 34.85207%
mlp               MIST           Base            radius              75 : 7.50671% / 90 : 15.27811% / 95 : 18.66543% / 99 : 25.6555%
                                 mass_smaller_3  radius             75 : 8.67989% / 90 : 32.29226% / 95 : 47.10715% / 99 : 67.37254%
                                 mass_smaller_14 radius             75 : 10.25139% / 90 : 17.37474% / 95 : 19.94145% / 99 : 24.5628%
                                 mass_smaller_30 radius             75 : 7.52068% / 90 : 20.72757% / 95 : 25.23444% / 99 : 29.81067%
random_forest     MIST           Base            radius                75 : 0.07769% / 90 : 0.26298% / 95 : 1.7352% / 99 : 27.00224%
                                 mass_smaller_3  radius                 75 : 0.121% / 90 : 0.33686% / 95 : 2.11828% / 99 : 65.83878%
                                 mass_smaller_14 radius               75 : 0.06104% / 90 : 0.16472% / 95 : 0.56918% / 99 : 26.48164%
                                 mass_smaller_30 radius                75 : 0.06715% / 90 : 0.2022% / 95 : 1.18008% / 99 : 27.51006%
xgboost           MIST           Base            radius              75 : 4.5674% / 90 : 10.91805% / 95 : 14.65167% / 99 : 21.08613%
                                 mass_smaller_3  radius             75 : 4.97674% / 90 : 17.26719% / 95 : 28.54934% / 99 : 48.67385%
                                 mass_smaller_14 radius             75 : 3.92152% / 90 : 10.46416% / 95 : 14.34744% / 99 : 21.12491%
                                 mass_smaller_30 radius              75 : 4.3733% / 90 : 10.81977% / 95 : 14.63452% / 99 : 21.24397%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
KNN               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
linear_regression MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
mlp               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
random_forest     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
xgboost           MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969

                                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.23288301898402786
                                 mass_smaller_3  radius              -0.7458496586144128
                                 mass_smaller_14 radius            -0.028543113399956743
                                 mass_smaller_30 radius             0.008940780881484534
KNN               MIST           Base            radius               0.6509309889395495
                                 mass_smaller_3  radius              0.19179709327537986
                                 mass_smaller_14 radius               0.5333019304174877
                                 mass_smaller_30 radius               0.5517339169333411
linear_regression MIST           Base            radius                0.304632547786987
                                 mass_smaller_3  radius              -0.1896931695325681
                                 mass_smaller_14 radius             0.059961009862141035
                                 mass_smaller_30 radius              0.03933893202957717
mlp               MIST           Base            radius               0.4212087734607134
                                 mass_smaller_3  radius             -0.14009440119764327
                                 mass_smaller_14 radius                0.275176267606035
                                 mass_smaller_30 radius              -0.4927047177897663
random_forest     MIST           Base            radius              0.47265136875136293
                                 mass_smaller_3  radius             -0.19734173176697278
                                 mass_smaller_14 radius              0.29061011162827377
                                 mass_smaller_30 radius               0.3209279815569862
xgboost           MIST           Base            radius               0.4964972804842628
                                 mass_smaller_3  radius              0.23581421719283302
                                 mass_smaller_14 radius              0.36641121794787357
                                 mass_smaller_30 radius               0.3732885641726318

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            15.35342%
                                 mass_smaller_3  radius            27.13726%
                                 mass_smaller_14 radius            16.97989%
                                 mass_smaller_30 radius            16.10045%
KNN               MIST           Base            radius            10.36147%
                                 mass_smaller_3  radius            18.48443%
                                 mass_smaller_14 radius            11.44341%
                                 mass_smaller_30 radius            10.83249%
linear_regression MIST           Base            radius            20.82202%
                                 mass_smaller_3  radius            25.56294%
                                 mass_smaller_14 radius            20.31584%
                                 mass_smaller_30 radius            20.71392%
mlp               MIST           Base            radius            13.33981%
                                 mass_smaller_3  radius            22.63872%
                                 mass_smaller_14 radius            14.25356%
                                 mass_smaller_30 radius            19.96091%
random_forest     MIST           Base            radius            12.73409%
                                 mass_smaller_3  radius            22.49475%
                                 mass_smaller_14 radius            14.10684%
                                 mass_smaller_30 radius            13.33166%
xgboost           MIST           Base            radius            12.55677%
                                 mass_smaller_3  radius            18.14648%
                                 mass_smaller_14 radius            13.49019%
                                 mass_smaller_30 radius            12.93804%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             6.28038%
                                 mass_smaller_3  radius            15.35917%
                                 mass_smaller_14 radius             7.54179%
                                 mass_smaller_30 radius             6.86536%
KNN               MIST           Base            radius             4.43989%
                                 mass_smaller_3  radius            10.82666%
                                 mass_smaller_14 radius             5.28703%
                                 mass_smaller_30 radius             4.80323%
linear_regression MIST           Base            radius            16.55147%
                                 mass_smaller_3  radius            19.86068%
                                 mass_smaller_14 radius            16.39261%
                                 mass_smaller_30 radius            16.61523%
mlp               MIST           Base            radius            10.41918%
                                 mass_smaller_3  radius            17.91902%
                                 mass_smaller_14 radius            11.41301%
                                 mass_smaller_30 radius            15.80096%
random_forest     MIST           Base            radius              5.3849%
                                 mass_smaller_3  radius            13.17627%
                                 mass_smaller_14 radius             6.46988%
                                 mass_smaller_30 radius              5.8732%
xgboost           MIST           Base            radius             9.43325%
                                 mass_smaller_3  radius            13.94354%
                                 mass_smaller_14 radius            10.48008%
                                 mass_smaller_30 radius             9.83277%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.2846%
                                 mass_smaller_3  radius             0.70253%
                                 mass_smaller_14 radius             0.32927%
                                 mass_smaller_30 radius             0.29982%
KNN               MIST           Base            radius             0.18513%
                                 mass_smaller_3  radius             2.05289%
                                 mass_smaller_14 radius             0.23592%
                                 mass_smaller_30 radius             0.20007%
linear_regression MIST           Base            radius            13.03607%
                                 mass_smaller_3  radius            15.08111%
                                 mass_smaller_14 radius            14.07152%
                                 mass_smaller_30 radius            14.03054%
mlp               MIST           Base            radius             8.42984%
                                 mass_smaller_3  radius             14.8346%
                                 mass_smaller_14 radius             9.66816%
                                 mass_smaller_30 radius            13.17423%
random_forest     MIST           Base            radius             0.18312%
                                 mass_smaller_3  radius             2.32554%
                                 mass_smaller_14 radius             0.24346%
                                 mass_smaller_30 radius             0.20321%
xgboost           MIST           Base            radius             7.06592%
                                 mass_smaller_3  radius            10.84642%
                                 mass_smaller_14 radius             8.41358%
                                 mass_smaller_30 radius             7.58819%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.6239292439330856
                                 mass_smaller_3  radius            0.12255294497939681
                                 mass_smaller_14 radius             0.4980870599144762
                                 mass_smaller_30 radius             0.5175122906926821
KNN               MIST           Base            radius             0.8118473473513885
                                 mass_smaller_3  radius            0.49107973054923415
                                 mass_smaller_14 radius             0.7405883337799539
                                 mass_smaller_30 radius             0.7521913415214849
linear_regression MIST           Base            radius             0.5669445250663593
                                 mass_smaller_3  radius            0.05327467345197411
                                 mass_smaller_14 radius             0.4195772079058465
                                 mass_smaller_30 radius             0.3884618763855989
mlp               MIST           Base            radius             0.6527394139165096
                                 mass_smaller_3  radius            0.21330361433506007
                                 mass_smaller_14 radius              0.529277646993492
                                 mass_smaller_30 radius            0.32496572505198623
random_forest     MIST           Base            radius             0.7209068216276289
                                 mass_smaller_3  radius            0.27291659304747523
                                 mass_smaller_14 radius             0.6159875321344142
                                 mass_smaller_30 radius             0.6338808982434485
xgboost           MIST           Base            radius             0.7059467903707194
                                 mass_smaller_3  radius            0.48613388033852417
                                 mass_smaller_14 radius             0.6060964235878444
                                 mass_smaller_30 radius             0.6128252627513893

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             81.87871%
                                 mass_smaller_3  radius            101.62586%
                                 mass_smaller_14 radius              83.4224%
                                 mass_smaller_30 radius             82.54584%
KNN               MIST           Base            radius             81.92638%
                                 mass_smaller_3  radius             95.64678%
                                 mass_smaller_14 radius             77.89833%
                                 mass_smaller_30 radius             80.20268%
linear_regression MIST           Base            radius             63.88906%
                                 mass_smaller_3  radius             67.16073%
                                 mass_smaller_14 radius             50.67361%
                                 mass_smaller_30 radius             57.51105%
mlp               MIST           Base            radius             64.98551%
                                 mass_smaller_3  radius             84.63792%
                                 mass_smaller_14 radius              60.0413%
                                 mass_smaller_30 radius             78.52232%
random_forest     MIST           Base            radius              81.1983%
                                 mass_smaller_3  radius             98.72428%
                                 mass_smaller_14 radius             80.27493%
                                 mass_smaller_30 radius             80.29803%
xgboost           MIST           Base            radius             66.72546%
                                 mass_smaller_3  radius             87.07138%
                                 mass_smaller_14 radius             65.42607%
                                 mass_smaller_30 radius             66.21739%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius               75 : 0.80472% / 90 : 26.8709% / 95 : 41.7056% / 99 : 61.87012%
                                 mass_smaller_3  radius            75 : 26.15504% / 90 : 52.06076% / 95 : 65.62239% / 99 : 83.21725%
                                 mass_smaller_14 radius             75 : 4.42935% / 90 : 31.55729% / 95 : 45.42955% / 99 : 63.69878%
                                 mass_smaller_30 radius             75 : 1.82318% / 90 : 29.33276% / 95 : 43.60635% / 99 : 62.21007%
KNN               MIST           Base            radius              75 : 2.73563% / 90 : 17.4646% / 95 : 26.31906% / 99 : 41.46379%
                                 mass_smaller_3  radius            75 : 17.96257% / 90 : 33.36991% / 95 : 42.42112% / 99 : 60.54767%
                                 mass_smaller_14 radius              75 : 5.62617% / 90 : 20.2589% / 95 : 28.70355% / 99 : 43.32225%
                                 mass_smaller_30 radius             75 : 3.97596% / 90 : 18.81693% / 95 : 27.59039% / 99 : 41.88462%
linear_regression MIST           Base            radius            75 : 23.85346% / 90 : 36.15469% / 95 : 42.63391% / 99 : 50.52362%
                                 mass_smaller_3  radius             75 : 29.17941% / 90 : 46.11524% / 95 : 53.41367% / 99 : 61.1915%
                                 mass_smaller_14 radius             75 : 24.65336% / 90 : 34.17073% / 95 : 39.52782% / 99 : 46.4224%
                                 mass_smaller_30 radius             75 : 24.51071% / 90 : 35.52308% / 95 : 41.2763% / 99 : 47.60901%
mlp               MIST           Base            radius            75 : 15.02615% / 90 : 22.24865% / 95 : 26.83233% / 99 : 36.01539%
                                 mass_smaller_3  radius            75 : 25.97811% / 90 : 37.98309% / 95 : 45.24175% / 99 : 57.77083%
                                 mass_smaller_14 radius            75 : 16.67815% / 90 : 23.67201% / 95 : 27.65314% / 99 : 35.34848%
                                 mass_smaller_30 radius            75 : 22.54515% / 90 : 32.02125% / 95 : 38.59529% / 99 : 56.14148%
random_forest     MIST           Base            radius             75 : 2.47596% / 90 : 22.08007% / 95 : 33.27333% / 99 : 51.21584%
                                 mass_smaller_3  radius            75 : 22.30901% / 90 : 41.45068% / 95 : 52.10991% / 99 : 71.63002%
                                 mass_smaller_14 radius               75 : 6.02044% / 90 : 25.83075% / 95 : 36.255% / 99 : 53.47634%
                                 mass_smaller_30 radius             75 : 4.00301% / 90 : 23.99494% / 95 : 34.47446% / 99 : 51.85086%
xgboost           MIST           Base            radius             75 : 13.77066% / 90 : 21.03103% / 95 : 25.93295% / 99 : 36.2497%
                                 mass_smaller_3  radius            75 : 19.81723% / 90 : 30.45233% / 95 : 37.37813% / 99 : 50.70474%
                                 mass_smaller_14 radius             75 : 15.0421% / 90 : 22.28418% / 95 : 27.10527% / 99 : 37.50758%
                                 mass_smaller_30 radius             75 : 14.31773% / 90 : 21.61933% / 95 : 26.47128% / 99 : 36.5678%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Results for the phase category with a value of 3.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
KNN               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
mlp               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              0.6590712626454432
                                 mass_smaller_3  radius             0.35081167612718833
                                 mass_smaller_14 radius              0.6160001034824771
                                 mass_smaller_30 radius              0.6206737380792444
KNN               MIST           Base            radius              0.8353242227223191
                                 mass_smaller_3  radius              0.7535060700780324
                                 mass_smaller_14 radius              0.8342892512480198
                                 mass_smaller_30 radius              0.8294303823205751
linear_regression MIST           Base            radius              0.3982384047629932
                                 mass_smaller_3  radius            -0.07494995277205785
                                 mass_smaller_14 radius             0.41936533653757024
                                 mass_smaller_30 radius              0.3267466410515468
mlp               MIST           Base            radius              0.5642957350076949
                                 mass_smaller_3  radius              0.1138444737599047
                                 mass_smaller_14 radius             0.49578211404893224
                                 mass_smaller_30 radius             0.06029965560710715
random_forest     MIST           Base            radius              0.7822157797380761
                                 mass_smaller_3  radius              0.6076236823682659
                                 mass_smaller_14 radius              0.7574501064358165
                                 mass_smaller_30 radius               0.759258384982005
xgboost           MIST           Base            radius              0.7131476322201502
                                 mass_smaller_3  radius              0.6041815289843242
                                 mass_smaller_14 radius              0.6833396854803595
                                 mass_smaller_30 radius              0.6908352593175837

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             9.68915%
                                 mass_smaller_3  radius            14.00059%
                                 mass_smaller_14 radius            11.04287%
                                 mass_smaller_30 radius              9.7228%
KNN               MIST           Base            radius              6.7715%
                                 mass_smaller_3  radius             8.61369%
                                 mass_smaller_14 radius             7.25287%
                                 mass_smaller_30 radius             6.53249%
linear_regression MIST           Base            radius            24.02534%
                                 mass_smaller_3  radius            25.30981%
                                 mass_smaller_14 radius            24.28421%
                                 mass_smaller_30 radius            22.67477%
mlp               MIST           Base            radius             12.8948%
                                 mass_smaller_3  radius            19.46503%
                                 mass_smaller_14 radius            14.94349%
                                 mass_smaller_30 radius            17.99745%
random_forest     MIST           Base            radius             7.75509%
                                 mass_smaller_3  radius            10.88908%
                                 mass_smaller_14 radius             8.78628%
                                 mass_smaller_30 radius             7.75612%
xgboost           MIST           Base            radius            10.80828%
                                 mass_smaller_3  radius            12.04656%
                                 mass_smaller_14 radius            12.14277%
                                 mass_smaller_30 radius            10.66887%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             2.97062%
                                 mass_smaller_3  radius             4.56728%
                                 mass_smaller_14 radius             3.22661%
                                 mass_smaller_30 radius             2.87817%
KNN               MIST           Base            radius             2.62182%
                                 mass_smaller_3  radius             3.43954%
                                 mass_smaller_14 radius             2.60505%
                                 mass_smaller_30 radius             2.37863%
linear_regression MIST           Base            radius            20.89034%
                                 mass_smaller_3  radius            18.89648%
                                 mass_smaller_14 radius             20.8337%
                                 mass_smaller_30 radius            19.42268%
mlp               MIST           Base            radius             9.17557%
                                 mass_smaller_3  radius            14.41522%
                                 mass_smaller_14 radius            10.12429%
                                 mass_smaller_30 radius            13.40789%
random_forest     MIST           Base            radius             2.59391%
                                 mass_smaller_3  radius             3.89808%
                                 mass_smaller_14 radius              2.8212%
                                 mass_smaller_30 radius             2.50425%
xgboost           MIST           Base            radius             7.72471%
                                 mass_smaller_3  radius             7.99654%
                                 mass_smaller_14 radius             8.60054%
                                 mass_smaller_30 radius             7.51952%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.26474%
                                 mass_smaller_3  radius             0.38983%
                                 mass_smaller_14 radius             0.31591%
                                 mass_smaller_30 radius             0.26139%
KNN               MIST           Base            radius             0.35742%
                                 mass_smaller_3  radius             0.56094%
                                 mass_smaller_14 radius             0.38472%
                                 mass_smaller_30 radius             0.33021%
linear_regression MIST           Base            radius            16.85032%
                                 mass_smaller_3  radius            14.12548%
                                 mass_smaller_14 radius            17.59821%
                                 mass_smaller_30 radius            15.68512%
mlp               MIST           Base            radius              5.9726%
                                 mass_smaller_3  radius            10.25658%
                                 mass_smaller_14 radius             5.94211%
                                 mass_smaller_30 radius             9.56729%
random_forest     MIST           Base            radius              0.2432%
                                 mass_smaller_3  radius             0.42526%
                                 mass_smaller_14 radius             0.29197%
                                 mass_smaller_30 radius             0.23619%
xgboost           MIST           Base            radius             5.03794%
                                 mass_smaller_3  radius             4.82432%
                                 mass_smaller_14 radius             5.42161%
                                 mass_smaller_30 radius             4.70475%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.8254828285545792
                                 mass_smaller_3  radius             0.6820236056572688
                                 mass_smaller_14 radius             0.8056024610712359
                                 mass_smaller_30 radius             0.8059452531001631
KNN               MIST           Base            radius             0.9140042384395503
                                 mass_smaller_3  radius             0.8682650878896927
                                 mass_smaller_14 radius             0.9133943688563751
                                 mass_smaller_30 radius             0.9107358889625214
linear_regression MIST           Base            radius             0.6489233026042639
                                 mass_smaller_3  radius             0.1647629145553814
                                 mass_smaller_14 radius             0.6475902703031168
                                 mass_smaller_30 radius             0.5718783607278599
mlp               MIST           Base            radius             0.7668922431326006
                                 mass_smaller_3  radius             0.4297623557407227
                                 mass_smaller_14 radius             0.7255574518107819
                                 mass_smaller_30 radius            0.48398577800524223
random_forest     MIST           Base            radius             0.8853617266109324
                                 mass_smaller_3  radius              0.789798166465493
                                 mass_smaller_14 radius             0.8720719936849396
                                 mass_smaller_30 radius             0.8726345032266805
xgboost           MIST           Base            radius             0.8509390938547726
                                 mass_smaller_3  radius             0.7809057752800133
                                 mass_smaller_14 radius             0.8352348077486584
                                 mass_smaller_30 radius             0.8417490970201137

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             81.61634%
                                 mass_smaller_3  radius            104.79946%
                                 mass_smaller_14 radius             94.78598%
                                 mass_smaller_30 radius             81.47174%
KNN               MIST           Base            radius             81.67085%
                                 mass_smaller_3  radius            104.74628%
                                 mass_smaller_14 radius             94.60865%
                                 mass_smaller_30 radius             81.23643%
linear_regression MIST           Base            radius             57.70486%
                                 mass_smaller_3  radius             94.45306%
                                 mass_smaller_14 radius             71.89087%
                                 mass_smaller_30 radius             57.32618%
mlp               MIST           Base            radius             81.52133%
                                 mass_smaller_3  radius            100.82393%
                                 mass_smaller_14 radius              93.4405%
                                 mass_smaller_30 radius             79.01598%
random_forest     MIST           Base            radius             81.61575%
                                 mass_smaller_3  radius            104.75043%
                                 mass_smaller_14 radius             94.62427%
                                 mass_smaller_30 radius             81.24469%
xgboost           MIST           Base            radius             72.79811%
                                 mass_smaller_3  radius              83.7053%
                                 mass_smaller_14 radius             80.69301%
                                 mass_smaller_30 radius             68.73942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.68742% / 90 : 6.18535% / 95 : 19.77514% / 99 : 51.44197%
                                 mass_smaller_3  radius              75 : 1.48057% / 90 : 11.95688% / 95 : 28.18187% / 99 : 83.2634%
                                 mass_smaller_14 radius              75 : 0.74372% / 90 : 5.58959% / 95 : 20.27583% / 99 : 61.43565%
                                 mass_smaller_30 radius                  75 : 0.624% / 90 : 5.19139% / 95 : 18.80465% / 99 : 53.159%
KNN               MIST           Base            radius              75 : 1.72661% / 90 : 7.67044% / 95 : 13.89062% / 99 : 32.34216%
                                 mass_smaller_3  radius              75 : 2.71549% / 90 : 10.41425% / 95 : 17.33985% / 99 : 38.6301%
                                 mass_smaller_14 radius              75 : 1.43053% / 90 : 7.33442% / 95 : 14.22367% / 99 : 34.67422%
                                 mass_smaller_30 radius              75 : 1.37344% / 90 : 6.64509% / 95 : 12.83333% / 99 : 31.68774%
linear_regression MIST           Base            radius            75 : 27.91163% / 90 : 40.43345% / 95 : 45.12881% / 99 : 51.34957%
                                 mass_smaller_3  radius            75 : 20.18426% / 90 : 49.89731% / 95 : 59.18561% / 99 : 70.86323%
                                 mass_smaller_14 radius            75 : 28.39245% / 90 : 38.23248% / 95 : 46.63394% / 99 : 55.55252%
                                 mass_smaller_30 radius            75 : 26.61201% / 90 : 38.59521% / 95 : 42.95718% / 99 : 48.63506%
mlp               MIST           Base            radius            75 : 13.24465% / 90 : 22.53951% / 95 : 28.20468% / 99 : 38.01338%
                                 mass_smaller_3  radius            75 : 19.20755% / 90 : 33.62319% / 95 : 42.64553% / 99 : 57.26139%
                                 mass_smaller_14 radius            75 : 14.22668% / 90 : 25.92132% / 95 : 33.68817% / 99 : 47.27624%
                                 mass_smaller_30 radius            75 : 20.05208% / 90 : 30.50131% / 95 : 36.46773% / 99 : 52.23177%
random_forest     MIST           Base            radius              75 : 1.04639% / 90 : 6.56763% / 95 : 15.33742% / 99 : 41.31288%
                                 mass_smaller_3  radius             75 : 2.23194% / 90 : 10.84387% / 95 : 20.77494% / 99 : 57.37664%
                                 mass_smaller_14 radius              75 : 1.11658% / 90 : 6.54618% / 95 : 16.02004% / 99 : 47.88373%
                                 mass_smaller_30 radius               75 : 0.9232% / 90 : 5.93852% / 95 : 14.58911% / 99 : 42.18387%
xgboost           MIST           Base            radius             75 : 11.32517% / 90 : 18.75812% / 95 : 23.03348% / 99 : 32.5998%
                                 mass_smaller_3  radius            75 : 10.32338% / 90 : 19.28476% / 95 : 27.14384% / 99 : 42.32636%
                                 mass_smaller_14 radius             75 : 12.5314% / 90 : 21.52863% / 95 : 26.17067% / 99 : 36.20382%
                                 mass_smaller_30 radius             75 : 10.84538% / 90 : 18.72956% / 95 : 23.1016% / 99 : 32.70042%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              17.94014596939087
                                 mass_smaller_3  radius              7.840359210968018
                                 mass_smaller_14 radius             13.361238241195679
                                 mass_smaller_30 radius              16.16098117828369
KNN               MIST           Base            radius              6.346128702163696
                                 mass_smaller_3  radius              2.541893482208252
                                 mass_smaller_14 radius             4.2096593379974365
                                 mass_smaller_30 radius              5.294558763504028
linear_regression MIST           Base            radius             1.1055355072021484
                                 mass_smaller_3  radius            0.31400299072265625
                                 mass_smaller_14 radius             0.5302321910858154
                                 mass_smaller_30 radius             0.5735788345336914
mlp               MIST           Base            radius               424.225483417511

Linear regression : 
- mass_smaller_3 : better results than Base on every metric except P99 and MAX_ER
- mass_smaller_14 : better results than Base on every metric except MAX_ER
- mass_smaller_30 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : very slightly worse results than Base on every metric
- mass_smaller_30 : similar results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : very slightly better results than Base on every metric
- mass_smaller_30 : very slightly better results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse/similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

XGBoost : 
- mass_smaller_3 : similar results to Base on every metric
- mass_smaller_14 : similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse/similar results to Base on every metric
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

#### Conclusions on radius

mass_smaller_3 almost always gives worse results than Base.

mass_smaller_14 and mass_smaller_30 give very similar results to Base.

All the results are pretty bad, 5% and more RMSE, 1-2% MAE, very high MAX_ER,...

#### Best models for the radius parameter

The three best performing models in order for the radius parameter are KNN, Random forest and Decision tree.

### log_g parameter

In [23]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
KNN               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
linear_regression MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
mlp               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
random_forest     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
xgboost           MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 5.433094523832443
                                 mass_smaller_14 log_g             -1.0828963170617296 - 5.433094523832443
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.7285247646204323
                                 mass_smaller_3  log_g              0.6138112143565488
                                 mass_smaller_14 log_g              0.7189069024866426
                                 mass_smaller_30 log_g              0.7181035533852704
KNN               MIST           Base            log_g              0.8593320998569429
                                 mass_smaller_3  log_g              0.8236243833174176
                                 mass_smaller_14 log_g               0.866920583507224
                                 mass_smaller_30 log_g               0.862489109211493
linear_regression MIST           Base            log_g             0.12147458541872769
                                 mass_smaller_3  log_g             0.35434676404367205
                                 mass_smaller_14 log_g              0.2640825025784339
                                 mass_smaller_30 log_g             0.19463139141835717
mlp               MIST           Base            log_g              0.6418730124942693
                                 mass_smaller_3  log_g              0.5771521379759594
                                 mass_smaller_14 log_g              0.6138501240242349
                                 mass_smaller_30 log_g              0.3352960639050495
random_forest     MIST           Base            log_g              0.8198256636371155
                                 mass_smaller_3  log_g              0.7465900159985581
                                 mass_smaller_14 log_g              0.8133904953096501
                                 mass_smaller_30 log_g               0.813686514686689
xgboost           MIST           Base            log_g              0.7433521284066151
                                 mass_smaller_3  log_g              0.7789057456997621
                                 mass_smaller_14 log_g               0.748756654054018
                                 mass_smaller_30 log_g              0.7435212384765314

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              8.63038%
                                 mass_smaller_3  log_g             12.11548%
                                 mass_smaller_14 log_g             10.06455%
                                 mass_smaller_30 log_g              8.89904%
KNN               MIST           Base            log_g              6.21617%
                                 mass_smaller_3  log_g              8.18831%
                                 mass_smaller_14 log_g               6.9268%
                                 mass_smaller_30 log_g              6.21789%
linear_regression MIST           Base            log_g             15.52437%
                                 mass_smaller_3  log_g             15.66347%
                                 mass_smaller_14 log_g             16.28354%
                                 mass_smaller_30 log_g              15.0404%
mlp               MIST           Base            log_g              9.96571%
                                 mass_smaller_3  log_g             12.67641%
                                 mass_smaller_14 log_g             11.98187%
                                 mass_smaller_30 log_g             13.66823%
random_forest     MIST           Base            log_g              7.03112%
                                 mass_smaller_3  log_g              9.81431%
                                 mass_smaller_14 log_g              8.20061%
                                 mass_smaller_30 log_g              7.23491%
xgboost           MIST           Base            log_g              8.39084%
                                 mass_smaller_3  log_g              9.16595%
                                 mass_smaller_14 log_g               9.5144%
                                 mass_smaller_30 log_g              8.48765%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              2.37276%
                                 mass_smaller_3  log_g              3.99059%
                                 mass_smaller_14 log_g              2.79121%
                                 mass_smaller_30 log_g               2.4518%
KNN               MIST           Base            log_g              2.04919%
                                 mass_smaller_3  log_g               2.8999%
                                 mass_smaller_14 log_g              2.13258%
                                 mass_smaller_30 log_g              1.95213%
linear_regression MIST           Base            log_g             12.69875%
                                 mass_smaller_3  log_g             12.54307%
                                 mass_smaller_14 log_g             13.14727%
                                 mass_smaller_30 log_g             12.06362%
mlp               MIST           Base            log_g              6.54401%
                                 mass_smaller_3  log_g              8.26879%
                                 mass_smaller_14 log_g              8.02197%
                                 mass_smaller_30 log_g              9.13665%
random_forest     MIST           Base            log_g              2.07541%
                                 mass_smaller_3  log_g              3.46271%
                                 mass_smaller_14 log_g              2.43474%
                                 mass_smaller_30 log_g              2.13613%
xgboost           MIST           Base            log_g              5.41921%
                                 mass_smaller_3  log_g              5.37573%
                                 mass_smaller_14 log_g              6.08087%
                                 mass_smaller_30 log_g              5.43794%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.10357%
                                 mass_smaller_3  log_g              0.10772%
                                 mass_smaller_14 log_g              0.11584%
                                 mass_smaller_30 log_g              0.10133%
KNN               MIST           Base            log_g              0.08534%
                                 mass_smaller_3  log_g              0.08708%
                                 mass_smaller_14 log_g              0.08481%
                                 mass_smaller_30 log_g              0.07714%
linear_regression MIST           Base            log_g             10.86887%
                                 mass_smaller_3  log_g             11.36309%
                                 mass_smaller_14 log_g             10.84226%
                                 mass_smaller_30 log_g              9.76028%
mlp               MIST           Base            log_g              3.41768%
                                 mass_smaller_3  log_g               3.8299%
                                 mass_smaller_14 log_g               4.0749%
                                 mass_smaller_30 log_g              4.81846%
random_forest     MIST           Base            log_g              0.05608%
                                 mass_smaller_3  log_g              0.05969%
                                 mass_smaller_14 log_g              0.06227%
                                 mass_smaller_30 log_g              0.05374%
xgboost           MIST           Base            log_g              2.76032%
                                 mass_smaller_3  log_g              2.11627%
                                 mass_smaller_14 log_g              3.00412%
                                 mass_smaller_30 log_g              2.68542%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.8650177953048179
                                 mass_smaller_3  log_g              0.8086938972173562
                                 mass_smaller_14 log_g              0.8603439496612715
                                 mass_smaller_30 log_g              0.8600069496777575
KNN               MIST           Base            log_g              0.9276197914525868
                                 mass_smaller_3  log_g              0.9084810991897053
                                 mass_smaller_14 log_g              0.9316142259580836
                                 mass_smaller_30 log_g              0.9292952253806753
linear_regression MIST           Base            log_g              0.3485320446593273
                                 mass_smaller_3  log_g              0.5952703288602817
                                 mass_smaller_14 log_g              0.5138895821344123
                                 mass_smaller_30 log_g             0.44117047957309463
mlp               MIST           Base            log_g              0.8016648757290119
                                 mass_smaller_3  log_g              0.7608965549932789
                                 mass_smaller_14 log_g              0.7843504708309273
                                 mass_smaller_30 log_g              0.6391839561254214
random_forest     MIST           Base            log_g              0.9076055609149075
                                 mass_smaller_3  log_g               0.868711422625732
                                 mass_smaller_14 log_g              0.9042615607050316
                                 mass_smaller_30 log_g              0.9044100379702219
xgboost           MIST           Base            log_g              0.8626939818756764
                                 mass_smaller_3  log_g              0.8829455189300828
                                 mass_smaller_14 log_g              0.8657553618027817
                                 mass_smaller_30 log_g              0.8627864126356243

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             77.21771%
                                 mass_smaller_3  log_g              87.1508%
                                 mass_smaller_14 log_g             87.37434%
                                 mass_smaller_30 log_g             77.36648%
KNN               MIST           Base            log_g             77.24848%
                                 mass_smaller_3  log_g             87.13073%
                                 mass_smaller_14 log_g             86.68154%
                                 mass_smaller_30 log_g             77.14502%
linear_regression MIST           Base            log_g             54.65398%
                                 mass_smaller_3  log_g             77.47297%
                                 mass_smaller_14 log_g             67.30463%
                                 mass_smaller_30 log_g             56.37993%
mlp               MIST           Base            log_g             76.51689%
                                 mass_smaller_3  log_g             84.64705%
                                 mass_smaller_14 log_g             85.07392%
                                 mass_smaller_30 log_g             75.72174%
random_forest     MIST           Base            log_g             77.22678%
                                 mass_smaller_3  log_g             87.13463%
                                 mass_smaller_14 log_g             86.76837%
                                 mass_smaller_30 log_g             77.14587%
xgboost           MIST           Base            log_g             68.08384%
                                 mass_smaller_3  log_g             79.69897%
                                 mass_smaller_14 log_g             74.67886%
                                 mass_smaller_30 log_g             67.92942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               75 : 0.26204% / 90 : 2.88519% / 95 : 18.52967% / 99 : 45.58648%
                                 mass_smaller_3  log_g               75 : 0.3674% / 90 : 13.75779% / 95 : 30.44001% / 99 : 57.26905%
                                 mass_smaller_14 log_g               75 : 0.29819% / 90 : 3.57029% / 95 : 22.07139% / 99 : 52.51772%
                                 mass_smaller_30 log_g                75 : 0.25881% / 90 : 2.9764% / 95 : 19.46809% / 99 : 46.55716%
KNN               MIST           Base            log_g               75 : 0.43297% / 90 : 6.33191% / 95 : 13.92119% / 99 : 29.55642%
                                 mass_smaller_3  log_g              75 : 0.48418% / 90 : 10.94047% / 95 : 19.77167% / 99 : 35.51611%
                                 mass_smaller_14 log_g                75 : 0.35129% / 90 : 5.92419% / 95 : 15.2712% / 99 : 33.02629%
                                 mass_smaller_30 log_g               75 : 0.34257% / 90 : 5.61598% / 95 : 13.67147% / 99 : 29.66892%
linear_regression MIST           Base            log_g             75 : 16.93223% / 90 : 25.24879% / 95 : 30.51061% / 99 : 41.11079%
                                 mass_smaller_3  log_g              75 : 16.26027% / 90 : 22.68349% / 95 : 31.1745% / 99 : 47.60963%
                                 mass_smaller_14 log_g             75 : 18.81341% / 90 : 26.85348% / 95 : 31.57785% / 99 : 41.95248%
                                 mass_smaller_30 log_g             75 : 17.01832% / 90 : 24.92174% / 95 : 29.86118% / 99 : 39.59072%
mlp               MIST           Base            log_g              75 : 10.47774% / 90 : 17.72734% / 95 : 21.68821% / 99 : 30.8161%
                                 mass_smaller_3  log_g                75 : 12.73043% / 90 : 22.52% / 95 : 28.91925% / 99 : 39.67625%
                                 mass_smaller_14 log_g             75 : 13.54652% / 90 : 21.54776% / 95 : 25.34519% / 99 : 34.63326%
                                 mass_smaller_30 log_g             75 : 14.77625% / 90 : 24.69955% / 95 : 29.46122% / 99 : 40.92219%
random_forest     MIST           Base            log_g                75 : 0.25196% / 90 : 4.56027% / 95 : 15.62515% / 99 : 35.3524%
                                 mass_smaller_3  log_g              75 : 0.58283% / 90 : 12.91636% / 95 : 24.59715% / 99 : 44.45871%
                                 mass_smaller_14 log_g               75 : 0.28407% / 90 : 5.53392% / 95 : 18.52995% / 99 : 41.12759%
                                 mass_smaller_30 log_g               75 : 0.24295% / 90 : 4.74896% / 95 : 16.30326% / 99 : 36.36262%
xgboost           MIST           Base            log_g              75 : 8.23921% / 90 : 14.62955% / 95 : 18.60118% / 99 : 26.67164%
                                 mass_smaller_3  log_g               75 : 7.56536% / 90 : 15.3858% / 95 : 21.34221% / 99 : 32.81941%
                                 mass_smaller_14 log_g              75 : 9.35146% / 90 : 16.56141% / 95 : 21.18097% / 99 : 30.22441%
                                 mass_smaller_30 log_g              75 : 8.27618% / 90 : 14.76395% / 95 : 18.96838% / 99 : 27.01924%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511
                                 mass_smaller_3  log_g              203.75130891799927

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
KNN               MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
linear_regression MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
mlp               MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
random_forest     MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307
xgboost           MIST           Base            log_g             -0.5967768342670462 - 5.433070637654307
                                 mass_smaller_3  log_g               3.379753170845917 - 5.433094523832443
                                 mass_smaller_14 log_g             -0.5973100835175252 - 5.433094523832443
                                 mass_smaller_30 log_g             -0.5973100835175252 - 5.433070637654307

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.45836693468175915
                                 mass_smaller_3  log_g              -1.1300497320341796
                                 mass_smaller_14 log_g              0.05701950107399145
                                 mass_smaller_30 log_g              0.37615329194584457
KNN               MIST           Base            log_g               0.6553166931256764
                                 mass_smaller_3  log_g             -0.05205026633067278
                                 mass_smaller_14 log_g              0.48608619995224744
                                 mass_smaller_30 log_g               0.6424747234239525
linear_regression MIST           Base            log_g              -0.0611340641093332
                                 mass_smaller_3  log_g               -2.521397989651777
                                 mass_smaller_14 log_g               -0.844565358746435
                                 mass_smaller_30 log_g             -0.09979128547079386
mlp               MIST           Base            log_g              0.15799191189495787
                                 mass_smaller_3  log_g              -1.6952020211239422
                                 mass_smaller_14 log_g              -0.7756869751909656
                                 mass_smaller_30 log_g              -0.6183924085775647
random_forest     MIST           Base            log_g                0.655638939150234
                                 mass_smaller_3  log_g              -0.2951054665192323
                                 mass_smaller_14 log_g              0.41070435949489426
                                 mass_smaller_30 log_g                0.606987074468411
xgboost           MIST           Base            log_g               0.4471727368192875
                                 mass_smaller_3  log_g             -0.48240618124680723
                                 mass_smaller_14 log_g             0.022218103719078286
                                 mass_smaller_30 log_g               0.3757175405545202

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              7.69123%
                                 mass_smaller_3  log_g             24.52446%
                                 mass_smaller_14 log_g              7.38958%
                                 mass_smaller_30 log_g              7.74995%
KNN               MIST           Base            log_g              6.20155%
                                 mass_smaller_3  log_g             17.27367%
                                 mass_smaller_14 log_g              5.48163%
                                 mass_smaller_30 log_g              5.90784%
linear_regression MIST           Base            log_g             16.84849%
                                 mass_smaller_3  log_g             41.10698%
                                 mass_smaller_14 log_g             15.39921%
                                 mass_smaller_30 log_g             15.83877%
mlp               MIST           Base            log_g             10.81126%
                                 mass_smaller_3  log_g             31.13279%
                                 mass_smaller_14 log_g              12.1479%
                                 mass_smaller_30 log_g              13.6968%
random_forest     MIST           Base            log_g              6.15166%
                                 mass_smaller_3  log_g             19.20845%
                                 mass_smaller_14 log_g              5.86154%
                                 mass_smaller_30 log_g              6.16991%
xgboost           MIST           Base            log_g              8.43068%
                                 mass_smaller_3  log_g             21.51556%
                                 mass_smaller_14 log_g              8.21256%
                                 mass_smaller_30 log_g               8.4162%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              1.23362%
                                 mass_smaller_3  log_g              3.48977%
                                 mass_smaller_14 log_g               0.9911%
                                 mass_smaller_30 log_g              1.16974%
KNN               MIST           Base            log_g              1.49713%
                                 mass_smaller_3  log_g              2.75962%
                                 mass_smaller_14 log_g              0.92602%
                                 mass_smaller_30 log_g              1.19974%
linear_regression MIST           Base            log_g             14.48558%
                                 mass_smaller_3  log_g              36.1289%
                                 mass_smaller_14 log_g             12.69459%
                                 mass_smaller_30 log_g             13.04051%
mlp               MIST           Base            log_g              6.16017%
                                 mass_smaller_3  log_g              17.1055%
                                 mass_smaller_14 log_g              7.27198%
                                 mass_smaller_30 log_g              7.82195%
random_forest     MIST           Base            log_g              1.13095%
                                 mass_smaller_3  log_g              3.23175%
                                 mass_smaller_14 log_g              0.91205%
                                 mass_smaller_30 log_g               1.0701%
xgboost           MIST           Base            log_g              4.70345%
                                 mass_smaller_3  log_g              9.68735%
                                 mass_smaller_14 log_g               4.3431%
                                 mass_smaller_30 log_g               4.6038%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.06856%
                                 mass_smaller_3  log_g              0.15006%
                                 mass_smaller_14 log_g              0.06005%
                                 mass_smaller_30 log_g              0.06371%
KNN               MIST           Base            log_g              0.05378%
                                 mass_smaller_3  log_g              0.13072%
                                 mass_smaller_14 log_g              0.04206%
                                 mass_smaller_30 log_g              0.04637%
linear_regression MIST           Base            log_g             13.26164%
                                 mass_smaller_3  log_g             37.61934%
                                 mass_smaller_14 log_g             10.62594%
                                 mass_smaller_30 log_g              10.8214%
mlp               MIST           Base            log_g              1.22781%
                                 mass_smaller_3  log_g              5.76802%
                                 mass_smaller_14 log_g              1.48053%
                                 mass_smaller_30 log_g              1.91017%
random_forest     MIST           Base            log_g              0.02924%
                                 mass_smaller_3  log_g              0.06654%
                                 mass_smaller_14 log_g              0.02524%
                                 mass_smaller_30 log_g              0.02659%
xgboost           MIST           Base            log_g              1.38202%
                                 mass_smaller_3  log_g               1.9691%
                                 mass_smaller_14 log_g              1.05678%
                                 mass_smaller_30 log_g              1.28116%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.8064994593089099
                                 mass_smaller_3  log_g              0.6375765894703289
                                 mass_smaller_14 log_g              0.7393021475013991
                                 mass_smaller_30 log_g              0.7877792937070838
KNN               MIST           Base            log_g              0.8672941111598133
                                 mass_smaller_3  log_g              0.7488648874287605
                                 mass_smaller_14 log_g              0.8323450479359569
                                 mass_smaller_30 log_g              0.8636937145353946
linear_regression MIST           Base            log_g             0.29813341758804923
                                 mass_smaller_3  log_g              0.5823745803566858
                                 mass_smaller_14 log_g             0.45563954743444723
                                 mass_smaller_30 log_g              0.4411502617745956
mlp               MIST           Base            log_g              0.7783008265777945
                                 mass_smaller_3  log_g              0.7789827796691844
                                 mass_smaller_14 log_g              0.7872523910284589
                                 mass_smaller_30 log_g              0.6581716551440178
random_forest     MIST           Base            log_g               0.863807624437327
                                 mass_smaller_3  log_g                0.72688968985791
                                 mass_smaller_14 log_g              0.8119698543700286
                                 mass_smaller_30 log_g              0.8497599980063882
xgboost           MIST           Base            log_g              0.8353265916677893
                                 mass_smaller_3  log_g              0.8157995353707765
                                 mass_smaller_14 log_g              0.8401454856816758
                                 mass_smaller_30 log_g              0.8301342889155285

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              93.99281%
                                 mass_smaller_3  log_g             275.29554%
                                 mass_smaller_14 log_g              94.40998%
                                 mass_smaller_30 log_g              93.68956%
KNN               MIST           Base            log_g              92.41866%
                                 mass_smaller_3  log_g             271.35114%
                                 mass_smaller_14 log_g               91.9639%
                                 mass_smaller_30 log_g              92.30022%
linear_regression MIST           Base            log_g              63.17729%
                                 mass_smaller_3  log_g              85.40057%
                                 mass_smaller_14 log_g              51.89466%
                                 mass_smaller_30 log_g              61.99574%
mlp               MIST           Base            log_g              63.37325%
                                 mass_smaller_3  log_g             154.73679%
                                 mass_smaller_14 log_g                55.658%
                                 mass_smaller_30 log_g              76.77598%
random_forest     MIST           Base            log_g              92.55336%
                                 mass_smaller_3  log_g             270.14473%
                                 mass_smaller_14 log_g              92.44992%
                                 mass_smaller_30 log_g              91.23499%
xgboost           MIST           Base            log_g              81.01893%
                                 mass_smaller_3  log_g             252.60134%
                                 mass_smaller_14 log_g              79.89835%
                                 mass_smaller_30 log_g              82.29856%

                                                                                                                          Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g                 75 : 0.13682% / 90 : 0.28458% / 95 : 0.60516% / 99 : 51.33546%
                                 mass_smaller_3  log_g                 75 : 0.30487% / 90 : 0.53133% / 95 : 0.8922% / 99 : 168.86915%
                                 mass_smaller_14 log_g                 75 : 0.11956% / 90 : 0.20861% / 95 : 0.35354% / 99 : 52.72698%
                                 mass_smaller_30 log_g                    75 : 0.12719% / 90 : 0.23829% / 95 : 0.46% / 99 : 53.16911%
KNN               MIST           Base            log_g                  75 : 0.16982% / 90 : 1.49755% / 95 : 9.0402% / 99 : 32.78109%
                                 mass_smaller_3  log_g                 75 : 0.28636% / 90 : 0.59464% / 95 : 1.05146% / 99 : 91.87805%
                                 mass_smaller_14 log_g                 75 : 0.10729% / 90 : 0.30678% / 95 : 1.00822% / 99 : 29.52588%
                                 mass_smaller_30 log_g                 75 : 0.12769% / 90 : 0.59432% / 95 : 4.32676% / 99 : 31.79534%
linear_regression MIST           Base            log_g               75 : 18.6411% / 90 : 26.76038% / 95 : 30.97309% / 99 : 37.56878%
                                 mass_smaller_3  log_g               75 : 50.1188% / 90 : 62.47037% / 95 : 68.58967% / 99 : 77.66707%
                                 mass_smaller_14 log_g              75 : 18.16279% / 90 : 26.06442% / 95 : 29.66816% / 99 : 35.27342%
                                 mass_smaller_30 log_g              75 : 18.44925% / 90 : 26.70296% / 95 : 30.54218% / 99 : 36.55059%
mlp               MIST           Base            log_g              75 : 10.04719% / 90 : 20.67216% / 95 : 25.13447% / 99 : 34.61879%
                                 mass_smaller_3  log_g             75 : 16.39572% / 90 : 55.29621% / 95 : 79.52891% / 99 : 114.71449%
                                 mass_smaller_14 log_g              75 : 14.06937% / 90 : 23.52927% / 95 : 26.98559% / 99 : 33.88429%
                                 mass_smaller_30 log_g              75 : 10.39072% / 90 : 27.74435% / 95 : 34.10349% / 99 : 40.35301%
random_forest     MIST           Base            log_g                 75 : 0.08707% / 90 : 0.32323% / 95 : 2.33986% / 99 : 36.50441%
                                 mass_smaller_3  log_g                75 : 0.17191% / 90 : 0.52987% / 95 : 3.61314% / 99 : 112.90086%
                                 mass_smaller_14 log_g                 75 : 0.06965% / 90 : 0.20363% / 95 : 0.76413% / 99 : 35.83093%
                                 mass_smaller_30 log_g                  75 : 0.07661% / 90 : 0.2504% / 95 : 1.58398% / 99 : 37.13812%
xgboost           MIST           Base            log_g               75 : 6.21973% / 90 : 14.71961% / 95 : 19.68275% / 99 : 28.61465%
                                 mass_smaller_3  log_g               75 : 8.35224% / 90 : 29.52797% / 95 : 48.73569% / 99 : 84.21639%
                                 mass_smaller_14 log_g               75 : 5.24824% / 90 : 14.01896% / 95 : 19.24846% / 99 : 28.67138%
                                 mass_smaller_30 log_g               75 : 5.90162% / 90 : 14.57205% / 95 : 19.79145% / 99 : 28.87745%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Results for the phase category with a value of 2.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
KNN               MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
linear_regression MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
mlp               MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
random_forest     MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865
xgboost           MIST           Base            log_g              -0.2959230723262505 - 4.408311770676233
                                 mass_smaller_3  log_g              -0.2597443254273661 - 4.406128730397165
                                 mass_smaller_14 log_g             -0.3287802371627256 - 4.4079093481651865
                                 mass_smaller_30 log_g             -0.3287802371627256 - 4.4079093481651865

                                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               0.10816902880453338
                                 mass_smaller_3  log_g                -0.600607812095914
                                 mass_smaller_14 log_g              -0.03513855644318564
                                 mass_smaller_30 log_g                0.0377295775830393
KNN               MIST           Base            log_g                 0.594178882501541
                                 mass_smaller_3  log_g                0.2590407279815474
                                 mass_smaller_14 log_g                0.5303123075394265
                                 mass_smaller_30 log_g                0.5647573800180672
linear_regression MIST           Base            log_g                0.2245163409964468
                                 mass_smaller_3  log_g             -0.024985407321623132
                                 mass_smaller_14 log_g               0.11325394232664077
                                 mass_smaller_30 log_g               0.12370500206716573
mlp               MIST           Base            log_g                0.3249124565645656
                                 mass_smaller_3  log_g              -0.02348330102255436
                                 mass_smaller_14 log_g                 0.266375411165814
                                 mass_smaller_30 log_g               -0.4449444547364432
random_forest     MIST           Base            log_g               0.38691114604182897
                                 mass_smaller_3  log_g              -0.09774314204530898
                                 mass_smaller_14 log_g                0.2860576263244211
                                 mass_smaller_30 log_g               0.34065187710603484
xgboost           MIST           Base            log_g               0.41515284669200114
                                 mass_smaller_3  log_g               0.29738900211887476
                                 mass_smaller_14 log_g                0.3627631788126231
                                 mass_smaller_30 log_g               0.39282919468435273

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             18.27543%
                                 mass_smaller_3  log_g             26.03536%
                                 mass_smaller_14 log_g             19.93071%
                                 mass_smaller_30 log_g              19.0992%
KNN               MIST           Base            log_g             12.33347%
                                 mass_smaller_3  log_g             17.73381%
                                 mass_smaller_14 log_g             13.43205%
                                 mass_smaller_30 log_g             12.85004%
linear_regression MIST           Base            log_g             22.30162%
                                 mass_smaller_3  log_g             23.73509%
                                 mass_smaller_14 log_g             22.24743%
                                 mass_smaller_30 log_g             22.55021%
mlp               MIST           Base            log_g             15.90061%
                                 mass_smaller_3  log_g             21.43808%
                                 mass_smaller_14 log_g             16.78211%
                                 mass_smaller_30 log_g             23.59835%
random_forest     MIST           Base            log_g             15.15768%
                                 mass_smaller_3  log_g             21.58147%
                                 mass_smaller_14 log_g             16.55842%
                                 mass_smaller_30 log_g             15.81473%
xgboost           MIST           Base            log_g             14.93954%
                                 mass_smaller_3  log_g             17.43216%
                                 mass_smaller_14 log_g             15.83208%
                                 mass_smaller_30 log_g              15.3332%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              7.47512%
                                 mass_smaller_3  log_g             14.73486%
                                 mass_smaller_14 log_g              8.85195%
                                 mass_smaller_30 log_g               8.1436%
KNN               MIST           Base            log_g               5.2846%
                                 mass_smaller_3  log_g              10.3866%
                                 mass_smaller_14 log_g              6.20551%
                                 mass_smaller_30 log_g              5.69755%
linear_regression MIST           Base            log_g             16.88375%
                                 mass_smaller_3  log_g             18.41003%
                                 mass_smaller_14 log_g             17.54727%
                                 mass_smaller_30 log_g             17.56593%
mlp               MIST           Base            log_g             12.39095%
                                 mass_smaller_3  log_g             17.00405%
                                 mass_smaller_14 log_g              13.4424%
                                 mass_smaller_30 log_g             18.70484%
random_forest     MIST           Base            log_g              6.40953%
                                 mass_smaller_3  log_g             12.64109%
                                 mass_smaller_14 log_g              7.59406%
                                 mass_smaller_30 log_g              6.96691%
xgboost           MIST           Base            log_g             11.23095%
                                 mass_smaller_3  log_g             13.39482%
                                 mass_smaller_14 log_g             12.29373%
                                 mass_smaller_30 log_g             11.65767%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.33801%
                                 mass_smaller_3  log_g              0.67312%
                                 mass_smaller_14 log_g              0.38587%
                                 mass_smaller_30 log_g              0.35496%
KNN               MIST           Base            log_g              0.22004%
                                 mass_smaller_3  log_g              1.96951%
                                 mass_smaller_14 log_g              0.27631%
                                 mass_smaller_30 log_g              0.23695%
linear_regression MIST           Base            log_g             12.23613%
                                 mass_smaller_3  log_g             13.86347%
                                 mass_smaller_14 log_g             14.35389%
                                 mass_smaller_30 log_g             13.93329%
mlp               MIST           Base            log_g              9.94997%
                                 mass_smaller_3  log_g             14.13881%
                                 mass_smaller_14 log_g             11.39814%
                                 mass_smaller_30 log_g             15.55125%
random_forest     MIST           Base            log_g              0.21754%
                                 mass_smaller_3  log_g              2.22946%
                                 mass_smaller_14 log_g              0.28533%
                                 mass_smaller_30 log_g              0.24072%
xgboost           MIST           Base            log_g              8.41823%
                                 mass_smaller_3  log_g             10.43905%
                                 mass_smaller_14 log_g              9.88399%
                                 mass_smaller_30 log_g              9.02535%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.5517614412105366
                                 mass_smaller_3  log_g             0.18202335941849643
                                 mass_smaller_14 log_g             0.47974864175030285
                                 mass_smaller_30 log_g              0.5165791626752562
KNN               MIST           Base            log_g              0.7750442583318956
                                 mass_smaller_3  log_g               0.539920011518819
                                 mass_smaller_14 log_g              0.7349547949015152
                                 mass_smaller_30 log_g              0.7567392250580913
linear_regression MIST           Base            log_g              0.4743260904396181
                                 mass_smaller_3  log_g             0.12286635004626859
                                 mass_smaller_14 log_g             0.36751055359689394
                                 mass_smaller_30 log_g              0.3711145323223116
mlp               MIST           Base            log_g              0.5729121364080281
                                 mass_smaller_3  log_g             0.30576531055074774
                                 mass_smaller_14 log_g               0.518007149747776
                                 mass_smaller_30 log_g             0.28535473759631075
random_forest     MIST           Base            log_g              0.6635177579267701
                                 mass_smaller_3  log_g              0.3341023253485054
                                 mass_smaller_14 log_g              0.6029009914629886
                                 mass_smaller_30 log_g              0.6356216771994637
xgboost           MIST           Base            log_g              0.6444816958330817
                                 mass_smaller_3  log_g              0.5462072880360849
                                 mass_smaller_14 log_g              0.6022982771634144
                                 mass_smaller_30 log_g              0.6267933206065803

                                                                      MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             97.46571%
                                 mass_smaller_3  log_g             97.51643%
                                 mass_smaller_14 log_g              97.9042%
                                 mass_smaller_30 log_g              97.9042%
KNN               MIST           Base            log_g             97.51553%
                                 mass_smaller_3  log_g             91.75768%
                                 mass_smaller_14 log_g             91.42906%
                                 mass_smaller_30 log_g             95.14774%
linear_regression MIST           Base            log_g             71.92701%
                                 mass_smaller_3  log_g             63.49404%
                                 mass_smaller_14 log_g             58.32543%
                                 mass_smaller_30 log_g             66.29245%
mlp               MIST           Base            log_g             77.45604%
                                 mass_smaller_3  log_g             79.59942%
                                 mass_smaller_14 log_g             70.89997%
                                 mass_smaller_30 log_g             93.00004%
random_forest     MIST           Base            log_g             96.64932%
                                 mass_smaller_3  log_g             94.71626%
                                 mass_smaller_14 log_g             94.22698%
                                 mass_smaller_30 log_g             95.24933%
xgboost           MIST           Base            log_g             79.35298%
                                 mass_smaller_3  log_g             81.22272%
                                 mass_smaller_14 log_g             77.44526%
                                 mass_smaller_30 log_g             81.07605%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g                75 : 0.95403% / 90 : 31.99032% / 95 : 49.661% / 99 : 73.63195%
                                 mass_smaller_3  log_g             75 : 25.09455% / 90 : 49.94242% / 95 : 62.96935% / 99 : 79.84058%
                                 mass_smaller_14 log_g               75 : 5.19836% / 90 : 37.0438% / 95 : 53.32691% / 99 : 74.76867%
                                 mass_smaller_30 log_g              75 : 2.15129% / 90 : 34.79498% / 95 : 51.73339% / 99 : 73.79922%
KNN               MIST           Base            log_g              75 : 3.25558% / 90 : 20.78829% / 95 : 31.32773% / 99 : 49.34873%
                                 mass_smaller_3  log_g              75 : 17.2345% / 90 : 32.01566% / 95 : 40.70149% / 99 : 58.08666%
                                 mass_smaller_14 log_g              75 : 6.60313% / 90 : 23.77547% / 95 : 33.68872% / 99 : 50.84458%
                                 mass_smaller_30 log_g                 75 : 4.71701% / 90 : 22.32065% / 95 : 32.7275% / 99 : 49.679%
linear_regression MIST           Base            log_g             75 : 25.11439% / 90 : 39.81179% / 95 : 47.61391% / 99 : 57.14298%
                                 mass_smaller_3  log_g             75 : 26.74976% / 90 : 42.95573% / 95 : 49.94864% / 99 : 57.43105%
                                 mass_smaller_14 log_g             75 : 26.39903% / 90 : 38.12747% / 95 : 44.90013% / 99 : 53.37399%
                                 mass_smaller_30 log_g             75 : 26.09143% / 90 : 39.54977% / 95 : 46.74509% / 99 : 54.72113%
mlp               MIST           Base            log_g             75 : 17.86752% / 90 : 26.52929% / 95 : 32.02242% / 99 : 43.22913%
                                 mass_smaller_3  log_g             75 : 24.56196% / 90 : 35.89017% / 95 : 42.64647% / 99 : 54.72716%
                                 mass_smaller_14 log_g             75 : 19.62784% / 90 : 27.90367% / 95 : 32.52757% / 99 : 41.73653%
                                 mass_smaller_30 log_g               75 : 26.62471% / 90 : 37.826% / 95 : 45.43004% / 99 : 66.45464%
random_forest     MIST           Base            log_g              75 : 2.94649% / 90 : 26.28036% / 95 : 39.61579% / 99 : 60.96039%
                                 mass_smaller_3  log_g                75 : 21.402% / 90 : 39.77326% / 95 : 49.99043% / 99 : 68.7179%
                                 mass_smaller_14 log_g              75 : 7.06569% / 90 : 30.32603% / 95 : 42.55673% / 99 : 62.76894%
                                 mass_smaller_30 log_g              75 : 4.74825% / 90 : 28.46249% / 95 : 40.89544% / 99 : 61.50815%
xgboost           MIST           Base            log_g             75 : 16.39353% / 90 : 25.06295% / 95 : 30.79863% / 99 : 43.07799%
                                 mass_smaller_3  log_g              75 : 19.02666% / 90 : 29.2479% / 95 : 35.87689% / 99 : 48.70343%
                                 mass_smaller_14 log_g             75 : 17.63046% / 90 : 26.19361% / 95 : 31.80238% / 99 : 43.95538%
                                 mass_smaller_30 log_g             75 : 17.00111% / 90 : 25.64597% / 95 : 31.36832% / 99 : 43.42294%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
KNN               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
linear_regression MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
mlp               MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
random_forest     MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263
xgboost           MIST           Base            log_g             -1.0828963170617296 - 6.259434356871683
                                 mass_smaller_3  log_g              -1.074853654540692 - 4.106398633491216
                                 mass_smaller_14 log_g             -1.0828963170617296 - 4.103227073714471
                                 mass_smaller_30 log_g               -1.074853654540692 - 6.24337664072263

                                                                                    RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               0.5817849716549621
                                 mass_smaller_3  log_g              0.39658754576723376
                                 mass_smaller_14 log_g               0.5649290988435505
                                 mass_smaller_30 log_g               0.5720442209331444
KNN               MIST           Base            log_g               0.7980532314937201
                                 mass_smaller_3  log_g               0.7708923072432344
                                 mass_smaller_14 log_g               0.8122572762330336
                                 mass_smaller_30 log_g               0.8075748852844039
linear_regression MIST           Base            log_g               0.2918925646174637
                                 mass_smaller_3  log_g              0.06115414919245732
                                 mass_smaller_14 log_g               0.3580823886911023
                                 mass_smaller_30 log_g              0.28195119047507056
mlp               MIST           Base            log_g               0.4653238995649285
                                 mass_smaller_3  log_g               0.2008645002962569
                                 mass_smaller_14 log_g               0.4325540283744135
                                 mass_smaller_30 log_g             -0.06588931590939096
random_forest     MIST           Base            log_g               0.7328442946232603
                                 mass_smaller_3  log_g               0.6352925182607598
                                 mass_smaller_14 log_g               0.7251996112862353
                                 mass_smaller_30 log_g               0.7284262896968001
xgboost           MIST           Base            log_g               0.6523316020107637
                                 mass_smaller_3  log_g               0.6309680787988265
                                 mass_smaller_14 log_g               0.6381930706674352
                                 mass_smaller_30 log_g                0.649731958801443

                                                                        RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              9.16454%
                                 mass_smaller_3  log_g             14.63007%
                                 mass_smaller_14 log_g             12.72316%
                                 mass_smaller_30 log_g              9.23587%
KNN               MIST           Base            log_g              6.40396%
                                 mass_smaller_3  log_g              9.00085%
                                 mass_smaller_14 log_g              8.35632%
                                 mass_smaller_30 log_g              6.20516%
linear_regression MIST           Base            log_g             20.75805%
                                 mass_smaller_3  log_g             25.74915%
                                 mass_smaller_14 log_g             26.48153%
                                 mass_smaller_30 log_g             20.04177%
mlp               MIST           Base            log_g             12.26276%
                                 mass_smaller_3  log_g             19.98537%
                                 mass_smaller_14 log_g             17.06044%
                                 mass_smaller_30 log_g             17.02025%
random_forest     MIST           Base            log_g              7.33521%
                                 mass_smaller_3  log_g             11.37864%
                                 mass_smaller_14 log_g             10.12306%
                                 mass_smaller_30 log_g              7.36726%
xgboost           MIST           Base            log_g             10.18322%
                                 mass_smaller_3  log_g             12.61432%
                                 mass_smaller_14 log_g             13.98227%
                                 mass_smaller_30 log_g             10.13779%

                                                                         MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               2.8092%
                                 mass_smaller_3  log_g              4.77246%
                                 mass_smaller_14 log_g              3.71793%
                                 mass_smaller_30 log_g              2.73391%
KNN               MIST           Base            log_g              2.47975%
                                 mass_smaller_3  log_g              3.59383%
                                 mass_smaller_14 log_g              3.00148%
                                 mass_smaller_30 log_g              2.25945%
linear_regression MIST           Base            log_g             17.56366%
                                 mass_smaller_3  log_g             19.01309%
                                 mass_smaller_14 log_g             22.13535%
                                 mass_smaller_30 log_g             16.73313%
mlp               MIST           Base            log_g              8.75411%
                                 mass_smaller_3  log_g             14.64573%
                                 mass_smaller_14 log_g             11.56179%
                                 mass_smaller_30 log_g             12.59538%
random_forest     MIST           Base            log_g               2.4529%
                                 mass_smaller_3  log_g              4.07332%
                                 mass_smaller_14 log_g               3.2506%
                                 mass_smaller_30 log_g              2.37865%
xgboost           MIST           Base            log_g              7.29781%
                                 mass_smaller_3  log_g              8.36599%
                                 mass_smaller_14 log_g              9.89411%
                                 mass_smaller_30 log_g               7.1457%

                                                                       MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.25027%
                                 mass_smaller_3  log_g               0.4075%
                                 mass_smaller_14 log_g              0.36477%
                                 mass_smaller_30 log_g              0.24852%
KNN               MIST           Base            log_g              0.33808%
                                 mass_smaller_3  log_g              0.58623%
                                 mass_smaller_14 log_g              0.44345%
                                 mass_smaller_30 log_g              0.31397%
linear_regression MIST           Base            log_g              13.7017%
                                 mass_smaller_3  log_g             14.06947%
                                 mass_smaller_14 log_g             18.06905%
                                 mass_smaller_30 log_g             12.97423%
mlp               MIST           Base            log_g              5.72762%
                                 mass_smaller_3  log_g             10.10081%
                                 mass_smaller_14 log_g              6.79746%
                                 mass_smaller_30 log_g               8.7711%
random_forest     MIST           Base            log_g              0.23001%
                                 mass_smaller_3  log_g              0.44471%
                                 mass_smaller_14 log_g              0.33699%
                                 mass_smaller_30 log_g              0.22461%
xgboost           MIST           Base            log_g              4.76833%
                                 mass_smaller_3  log_g              5.06187%
                                 mass_smaller_14 log_g              6.23096%
                                 mass_smaller_30 log_g               4.4703%

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              0.7872344983380405
                                 mass_smaller_3  log_g              0.6995983327084234
                                 mass_smaller_14 log_g              0.7805402170911522
                                 mass_smaller_30 log_g              0.7827031834182294
KNN               MIST           Base            log_g              0.8937310126228201
                                 mass_smaller_3  log_g              0.8780237811999819
                                 mass_smaller_14 log_g              0.9013032085598914
                                 mass_smaller_30 log_g              0.8987875289208588
linear_regression MIST           Base            log_g              0.5655350134948097
                                 mass_smaller_3  log_g              0.2550286481499008
                                 mass_smaller_14 log_g              0.6134692342216399
                                 mass_smaller_30 log_g              0.5386517947860948
mlp               MIST           Base            log_g              0.6888025677453951
                                 mass_smaller_3  log_g             0.48508877527218314
                                 mass_smaller_14 log_g              0.6707943127078274
                                 mass_smaller_30 log_g             0.40828462494586637
random_forest     MIST           Base            log_g              0.8584121763316808
                                 mass_smaller_3  log_g              0.8038675761512467
                                 mass_smaller_14 log_g              0.8543698517419703
                                 mass_smaller_30 log_g              0.8559373653759447
xgboost           MIST           Base            log_g              0.8172568061289313
                                 mass_smaller_3  log_g              0.8005425244811992
                                 mass_smaller_14 log_g              0.8042511867428563
                                 mass_smaller_30 log_g               0.814855291786251

                                                                       MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g              77.21771%
                                 mass_smaller_3  log_g             109.46637%
                                 mass_smaller_14 log_g             109.17321%
                                 mass_smaller_30 log_g              77.36648%
KNN               MIST           Base            log_g              77.24848%
                                 mass_smaller_3  log_g             109.44116%
                                 mass_smaller_14 log_g             108.90912%
                                 mass_smaller_30 log_g              77.14502%
linear_regression MIST           Base            log_g              54.65398%
                                 mass_smaller_3  log_g              97.31046%
                                 mass_smaller_14 log_g              84.56343%
                                 mass_smaller_30 log_g              56.37993%
mlp               MIST           Base            log_g              76.51689%
                                 mass_smaller_3  log_g             106.32152%
                                 mass_smaller_14 log_g             106.88926%
                                 mass_smaller_30 log_g              75.72174%
random_forest     MIST           Base            log_g              77.22678%
                                 mass_smaller_3  log_g             109.44606%
                                 mass_smaller_14 log_g             109.01821%
                                 mass_smaller_30 log_g              77.14587%
xgboost           MIST           Base            log_g              68.08384%
                                 mass_smaller_3  log_g              87.22692%
                                 mass_smaller_14 log_g              93.82861%
                                 mass_smaller_30 log_g              67.92942%

                                                                                                                         Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               75 : 0.65007% / 90 : 5.84978% / 95 : 18.71014% / 99 : 48.68195%
                                 mass_smaller_3  log_g              75 : 1.54731% / 90 : 12.49408% / 95 : 29.44887% / 99 : 86.97434%
                                 mass_smaller_14 log_g                   75 : 0.8569% / 90 : 6.442% / 95 : 23.36157% / 99 : 70.7918%
                                 mass_smaller_30 log_g                75 : 0.5914% / 90 : 4.93494% / 95 : 17.85801% / 99 : 50.51276%
KNN               MIST           Base            log_g                75 : 1.63381% / 90 : 7.2492% / 95 : 13.14337% / 99 : 30.57381%
                                 mass_smaller_3  log_g               75 : 2.83599% / 90 : 10.8825% / 95 : 18.11917% / 99 : 40.36765%
                                 mass_smaller_14 log_g                75 : 1.65094% / 90 : 8.45082% / 95 : 16.38469% / 99 : 39.9358%
                                 mass_smaller_30 log_g               75 : 1.30551% / 90 : 6.31327% / 95 : 12.19598% / 99 : 30.09471%
linear_regression MIST           Base            log_g             75 : 23.90631% / 90 : 35.75704% / 95 : 40.46671% / 99 : 46.57608%
                                 mass_smaller_3  log_g              75 : 19.9253% / 90 : 51.09035% / 95 : 60.69691% / 99 : 73.13676%
                                 mass_smaller_14 log_g              75 : 30.20985% / 90 : 42.9178% / 95 : 52.81286% / 99 : 63.54959%
                                 mass_smaller_30 log_g             75 : 23.03139% / 90 : 34.97512% / 95 : 39.29666% / 99 : 45.66569%
mlp               MIST           Base            log_g             75 : 12.53131% / 90 : 21.34826% / 95 : 26.79204% / 99 : 36.15105%
                                 mass_smaller_3  log_g             75 : 19.69601% / 90 : 35.08553% / 95 : 43.98975% / 99 : 59.25131%
                                 mass_smaller_14 log_g             75 : 16.14057% / 90 : 29.79412% / 95 : 38.51007% / 99 : 54.33847%
                                 mass_smaller_30 log_g             75 : 18.68785% / 90 : 28.90699% / 95 : 34.89286% / 99 : 49.99378%
random_forest     MIST           Base            log_g               75 : 0.99001% / 90 : 6.20702% / 95 : 14.51011% / 99 : 39.02317%
                                 mass_smaller_3  log_g              75 : 2.33225% / 90 : 11.33008% / 95 : 21.70827% / 99 : 59.95828%
                                 mass_smaller_14 log_g               75 : 1.28709% / 90 : 7.54244% / 95 : 18.45425% / 99 : 55.16548%
                                 mass_smaller_30 log_g               75 : 0.87699% / 90 : 5.63934% / 95 : 13.85335% / 99 : 40.05285%
xgboost           MIST           Base            log_g             75 : 10.68135% / 90 : 17.61716% / 95 : 21.69529% / 99 : 30.57667%
                                 mass_smaller_3  log_g               75 : 10.82769% / 90 : 20.2067% / 95 : 28.7444% / 99 : 44.00191%
                                 mass_smaller_14 log_g             75 : 14.45839% / 90 : 24.72078% / 95 : 30.18401% / 99 : 41.86692%
                                 mass_smaller_30 log_g             75 : 10.30003% / 90 : 17.86415% / 95 : 21.94766% / 99 : 31.03032%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            log_g               17.94014596939087
                                 mass_smaller_3  log_g               7.840359210968018
                                 mass_smaller_14 log_g              13.361238241195679
                                 mass_smaller_30 log_g               16.16098117828369
KNN               MIST           Base            log_g               6.346128702163696
                                 mass_smaller_3  log_g               2.541893482208252
                                 mass_smaller_14 log_g              4.2096593379974365
                                 mass_smaller_30 log_g               5.294558763504028
linear_regression MIST           Base            log_g              1.1055355072021484
                                 mass_smaller_3  log_g             0.31400299072265625
                                 mass_smaller_14 log_g              0.5302321910858154
                                 mass_smaller_30 log_g              0.5735788345336914
mlp               MIST           Base            log_g                424.225483417511

Linear regression : 
- mass_smaller_3 : similar results to Base on every metric
- mass_smaller_14 : similar results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : similar results to Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : slightly worse results than Base on every metric
- mass_smaller_30 : very slightly better results than Base on every metric

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : slightly worse results than Base on every metric
- mass_smaller_30 : similar results to Base on every metric

XGBoost : 
- mass_smaller_3 : slightly worse results to Base on every metric
- mass_smaller_14 : slightly worse results to Base on every metric
- mass_smaller_30 : similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on every metric
- mass_smaller_30 : worse results than Base on every metric

#### Conclusions on log_g

mass_smaller_3 almost always gives worse results than Base.

mass_smaller_14 give slightly worse results than Base.

mass_smaller_30 give worse/similar results to Base.

All the results are pretty bad. Same as above, very high MAX_ER, high RMSE,...

#### Best models for the log_g parameter

The three best performing models in order for the radius parameter are KNN, Random forest and Decision tree.

### Conclusion on both

Using the Base filtering seems to be the best solution for most parameters.

Since mass_smaller_14 is used for model_A_partial, it might still be interesting to use mass_smaller_14; also making it easier to compare with PARSEC

The three models that need to be used are : KNN, Random forest and Decision tree