# Results comparison for MIST with final models of model A partial

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_A_partial/default_models"
path_fine_tuned = pre_path + "results/model_A_partial/fine_tuned_models"
path_final = pre_path + "results/model_A_partial/final_models"

## Final model results

In [4]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_standard_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                            value range  RVE  \
model physical_model filter            output_parameter
KNN   MIST           scale_standard_14 mass                0.1 - 13.999  1.0
                                       radius            -0.997 - 3.083  1.0

                                                          RMSE    MAE  MedAE  \
model physical_model filter            output_parameter
KNN   MIST           scale_standard_14 mass              0.044  0.015  0.003
                                       radius            0.005  0.003  0.002

                                                         CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           scale_standard_14 mass               1.0   1.945
                                       radius             1.0   0.130

                                                                                               Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           scale_standard_14 mass               75 : 0.011 / 90 : 0.039 / 95 : 0.07 / 99 : 0.184
                                       radius            75 : 0.003 / 90 : 0.006 / 95 : 0.009 / 99 : 0.017

                                                          time
model physical_model filter            output_parameter
KNN   MIST           scale_standard_14 mass              1.717
                                       radius            1.717

In [3]:
compare_metrics(path_final, value_rounding=3, relative_values=True,
                output_parameters=["mass", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_standard_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass                0.1 - 13.999
                                               radius            -0.997 - 3.083

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              1.0  0.219%
                                               radius            1.0  0.099%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              0.076%
                                               radius            0.047%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              0.022%   1.0
                                               radius            0.021%   1.0

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              12.24%
                                               radius            3.081%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              75 : 0.064% / 90 : 0.166% / 95 : 0.309% / 99 : 0.921%
                                               radius            75 : 0.054% / 90 : 0.112% / 95 : 0.171% / 99 : 0.354%

                                                                   time
model         physical_model filter            output_parameter
random_forest MIST           scale_standard_14 mass              82.816
                                               radius            82.816