# Results comparison for MIST filtering

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_A_partial/default_models"

In [3]:
compare_metrics(path, 
                output_parameters=["mass"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9978054138856324
                             mass_smaller_3  mass              0.9992541969730512
                             mass_smaller_14 mass              0.9978246279671578
                             mass_smaller_30 mass              0.9978090814796585

                                                                              RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               1.2512629515795346
                             mass_smaller_3  mass              0.01975564332021666
                             mass_smaller_14 mass               1.2457736076457506
                             mass_smaller_30 mass               1.2502174142307747

                                                                                MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                0.1452769419896218
                             mass_smaller_3  mass              0.006025796628853846
                             mass_smaller_14 mass                0.1450974561041155
                             mass_smaller_30 mass               0.14544775978054023

                                                                               MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.004111252117102282
                             mass_smaller_3  mass              0.0020703142458058377
                             mass_smaller_14 mass               0.004128173546273484
                             mass_smaller_30 mass               0.004125628598466324

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9989035373674631
                             mass_smaller_3  mass              0.9996270807690646
                             mass_smaller_14 mass              0.9989131374040815
                             mass_smaller_30 mass              0.9989052645073933

                                                                           MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               95.14828406903314
                             mass_smaller_3  mass              1.3490965095666518
                             mass_smaller_14 mass                99.1425528233774
                             mass_smaller_30 mass              103.44266579660032

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                 75 : 0.0156 / 90 : 0.0791 / 95 : 0.29069 / 99 : 3.22241
                             mass_smaller_3  mass               75 : 0.00554 / 90 : 0.01225 / 95 : 0.01942 / 99 : 0.06893
                             mass_smaller_14 mass                75 : 0.01563 / 90 : 0.07924 / 95 : 0.29345 / 99 : 3.2338
                             mass_smaller_30 mass               75 : 0.01559 / 90 : 0.07901 / 95 : 0.29267 / 99 : 3.24571

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               386.4703776836395
                             mass_smaller_3  mass              151.83639550209045
                             mass_smaller_14 mass              368.00555777549744
                             mass_smaller_30 mass               398.6265916824341

Results for the phase category with a value of 0.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9973575906750899
                             mass_smaller_3  mass               0.999947044394285
                             mass_smaller_14 mass               0.997413901088023
                             mass_smaller_30 mass               0.997368944119941

                                                                               RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                1.3521665845754873
                             mass_smaller_3  mass              0.005488828615455466
                             mass_smaller_14 mass                1.3376914087667897
                             mass_smaller_30 mass                1.3492653913806696

                                                                                MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.16783299547779296
                             mass_smaller_3  mass              0.002764338682723445
                             mass_smaller_14 mass               0.16765041145105403
                             mass_smaller_30 mass               0.16841881212380835

                                                                               MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.0035490560629605206
                             mass_smaller_3  mass              0.0013470803912696283
                             mass_smaller_14 mass              0.0035453418124899994
                             mass_smaller_30 mass              0.0035401103163561487

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9986793327165373
                             mass_smaller_3  mass              0.9999735435321911
                             mass_smaller_14 mass              0.9987075486293543
                             mass_smaller_30 mass               0.998685112002334

                                                                            MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                83.61091180145692
                             mass_smaller_3  mass              0.18157378789633682
                             mass_smaller_14 mass                83.57250382102333
                             mass_smaller_30 mass                82.85120835326344

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                75 : 0.01627 / 90 : 0.10846 / 95 : 0.41678 / 99 : 3.6048
                             mass_smaller_3  mass               75 : 0.00319 / 90 : 0.00646 / 95 : 0.00971 / 99 : 0.02179
                             mass_smaller_14 mass               75 : 0.01643 / 90 : 0.10813 / 95 : 0.42046 / 99 : 3.63991
                             mass_smaller_30 mass                 75 : 0.01637 / 90 : 0.108 / 95 : 0.41909 / 99 : 3.63658

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               386.4703776836395
                             mass_smaller_3  mass              151.83639550209045
                             mass_smaller_14 mass              368.00555777549744
                             mass_smaller_30 mass               398.6265916824341

Results for the phase category with a value of 2.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                             mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                             mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                             mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9997441818803499
                             mass_smaller_3  mass              0.9996653648909077
                             mass_smaller_14 mass               0.999743214302835
                             mass_smaller_30 mass              0.9997429524189717

                                                                              RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.47498420224835197
                             mass_smaller_3  mass              0.01145266644937612
                             mass_smaller_14 mass               0.4758809844765971
                             mass_smaller_30 mass              0.47612846312273854

                                                                                MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.05965777535357753
                             mass_smaller_3  mass              0.006816718583654214
                             mass_smaller_14 mass               0.05943118368961476
                             mass_smaller_30 mass              0.059361707757584606

                                                                              MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.004034495488792533
                             mass_smaller_3  mass              0.004307804055038389
                             mass_smaller_14 mass              0.004050206037180315
                             mass_smaller_30 mass              0.004060477925214023

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9998728077084751
                             mass_smaller_3  mass              0.9998368427876034
                             mass_smaller_14 mass              0.9998723208690561
                             mass_smaller_30 mass              0.9998722085378534

                                                                           MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              21.388650133880788
                             mass_smaller_3  mass              0.2152611485477416
                             mass_smaller_14 mass              23.113277495647964
                             mass_smaller_30 mass               18.59308616784716

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01064 / 90 : 0.02559 / 95 : 0.07213 / 99 : 1.35752
                             mass_smaller_3  mass                75 : 0.00903 / 90 : 0.01523 / 95 : 0.0204 / 99 : 0.03971
                             mass_smaller_14 mass               75 : 0.01054 / 90 : 0.02552 / 95 : 0.07329 / 99 : 1.33501
                             mass_smaller_30 mass                75 : 0.0106 / 90 : 0.02556 / 95 : 0.07221 / 99 : 1.36785

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               386.4703776836395
                             mass_smaller_3  mass              151.83639550209045
                             mass_smaller_14 mass              368.00555777549744
                             mass_smaller_30 mass               398.6265916824341

Results for the phase category with a value of 3.0

                                                                                          value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.5484495344916944 - 288.814589557117
                             mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                             mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                             mass_smaller_30 mass               0.5484495344916944 - 288.814589557117

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9949810881828094
                             mass_smaller_3  mass              0.9956700597782066
                             mass_smaller_14 mass              0.9949130093083712
                             mass_smaller_30 mass              0.9949681865732133

                                                                              RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                1.642420538512268
                             mass_smaller_3  mass              0.04218948342523731
                             mass_smaller_14 mass               1.6535157402838208
                             mass_smaller_30 mass               1.6444983811441365

                                                                                MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.20145454791412173
                             mass_smaller_3  mass              0.014501789192269845
                             mass_smaller_14 mass                0.2013493398604617
                             mass_smaller_30 mass               0.20111508890417903

                                                                              MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.006907232098912752
                             mass_smaller_3  mass              0.003545841487851087
                             mass_smaller_14 mass              0.006905876154084667
                             mass_smaller_30 mass              0.006940862869302067

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9976029233414596
                             mass_smaller_3  mass              0.9978436498641285
                             mass_smaller_14 mass              0.9975685820026399
                             mass_smaller_30 mass              0.9975920917628096

                                                                           MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               95.14828406903314
                             mass_smaller_3  mass              1.3490965095666518
                             mass_smaller_14 mass                99.1425528233774
                             mass_smaller_30 mass              103.44266579660032

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                75 : 0.0288 / 90 : 0.10782 / 95 : 0.29875 / 99 : 4.67012
                             mass_smaller_3  mass                75 : 0.01061 / 90 : 0.03037 / 95 : 0.06452 / 99 : 0.2086
                             mass_smaller_14 mass               75 : 0.02869 / 90 : 0.10814 / 95 : 0.29792 / 99 : 4.66353
                             mass_smaller_30 mass               75 : 0.02886 / 90 : 0.10712 / 95 : 0.29747 / 99 : 4.72241

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               386.4703776836395
                             mass_smaller_3  mass              151.83639550209045
                             mass_smaller_14 mass              368.00555777549744
                             mass_smaller_30 mass               398.6265916824341

In [4]:
compare_metrics(path, value_rounding=3,
                output_parameters=["mass", "radius"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -298.445  0.995
                                        radius                 -4.127  1.000
KNN               MIST           Base   mass                 -298.445  0.990
                                        radius                 -4.127  1.000
linear_regression MIST           Base   mass                 -298.445  0.304
                                        radius                 -4.127  0.985
mlp               MIST           Base   mass                 -298.445  0.968
                                        radius                 -4.127  0.989
random_forest     MIST           Base   mass                 -298.445  0.998
                                        radius                 -4.127  1.000
xgboost           MIST           Base   mass                 -298.445  0.994
                                        radius                 -4.127  1.000

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               1.854   0.200
                                        radius             0.011   0.006
KNN               MIST           Base   mass               2.726   0.328
                                        radius             0.007   0.004
linear_regression MIST           Base   mass              22.280  11.345
                                        radius             0.089   0.065
mlp               MIST           Base   mass               4.750   1.280
                                        radius             0.077   0.056
random_forest     MIST           Base   mass               1.251   0.145
                                        radius             0.006   0.003
xgboost           MIST           Base   mass               2.048   0.531
                                        radius             0.015   0.011

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.003  0.998
                                        radius            0.003  1.000
KNN               MIST           Base   mass              0.008  0.995
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              8.154  0.552
                                        radius            0.046  0.993
mlp               MIST           Base   mass              0.277  0.984
                                        radius            0.042  0.995
random_forest     MIST           Base   mass              0.004  0.999
                                        radius            0.001  1.000
xgboost           MIST           Base   mass              0.099  0.997
                                        radius            0.008  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              151.658
                                        radius              0.488
KNN               MIST           Base   mass              144.214
                                        radius              0.307
linear_regression MIST           Base   mass              257.508
                                        radius              0.525
mlp               MIST           Base   mass              179.182
                                        radius              0.692
random_forest     MIST           Base   mass               95.148
                                        radius              0.358
xgboost           MIST           Base   mass               72.954
                                        radius              0.490

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.01985 / 90 : 0.10435 / 95 : 0.35217 / 99 : 4.54997
                                        radius                 75 : 0.00723 / 90 : 0.01301 / 95 : 0.01833 / 99 : 0.04032
KNN               MIST           Base   mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                        radius                 75 : 0.00513 / 90 : 0.00921 / 95 : 0.01275 / 99 : 0.02703
linear_regression MIST           Base   mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                        radius                 75 : 0.08959 / 90 : 0.13937 / 95 : 0.17556 / 99 : 0.30046
mlp               MIST           Base   mass                  75 : 0.57742 / 90 : 2.19642 / 95 : 5.39114 / 99 : 21.87825
                                        radius                 75 : 0.07619 / 90 : 0.12016 / 95 : 0.15389 / 99 : 0.24989
random_forest     MIST           Base   mass                     75 : 0.0156 / 90 : 0.0791 / 95 : 0.29069 / 99 : 3.22241
                                        radius                 75 : 0.00311 / 90 : 0.00627 / 95 : 0.00938 / 99 : 0.02069
xgboost           MIST           Base   mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                        radius                  75 : 0.0146 / 90 : 0.02253 / 95 : 0.02856 / 99 : 0.04454

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 0.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -298.445  0.994
                                        radius                 -4.080  1.000
KNN               MIST           Base   mass                 -298.445  0.984
                                        radius                 -4.080  1.000
linear_regression MIST           Base   mass                 -298.445  0.273
                                        radius                 -4.080  0.978
mlp               MIST           Base   mass                 -298.445  0.965
                                        radius                 -4.080  0.981
random_forest     MIST           Base   mass                 -298.445  0.997
                                        radius                 -4.080  1.000
xgboost           MIST           Base   mass                 -298.445  0.991
                                        radius                 -4.080  0.999

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               2.111   0.270
                                        radius             0.008   0.005
KNN               MIST           Base   mass               3.292   0.432
                                        radius             0.007   0.004
linear_regression MIST           Base   mass              22.430  13.108
                                        radius             0.085   0.066
mlp               MIST           Base   mass               4.923   1.342
                                        radius             0.079   0.057
random_forest     MIST           Base   mass               1.352   0.168
                                        radius             0.004   0.002
xgboost           MIST           Base   mass               2.494   0.677
                                        radius             0.014   0.010

                                                           MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.006  0.997
                                        radius             0.003  1.000
KNN               MIST           Base   mass               0.010  0.992
                                        radius             0.003  1.000
linear_regression MIST           Base   mass              11.253  0.534
                                        radius             0.052  0.989
mlp               MIST           Base   mass               0.290  0.983
                                        radius             0.043  0.990
random_forest     MIST           Base   mass               0.004  0.999
                                        radius             0.001  1.000
xgboost           MIST           Base   mass               0.126  0.996
                                        radius             0.007  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              131.775
                                        radius              0.488
KNN               MIST           Base   mass              126.674
                                        radius              0.154
linear_regression MIST           Base   mass              257.508
                                        radius              0.458
mlp               MIST           Base   mass              127.141
                                        radius              0.692
random_forest     MIST           Base   mass               83.611
                                        radius              0.358
xgboost           MIST           Base   mass               72.954
                                        radius              0.136

                                                                                                               Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                    75 : 0.03086 / 90 : 0.18472 / 95 : 0.67029 / 99 : 5.91802
                                        radius                  75 : 0.00535 / 90 : 0.01031 / 95 : 0.01517 / 99 : 0.03231
KNN               MIST           Base   mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                        radius                   75 : 0.00518 / 90 : 0.00955 / 95 : 0.01355 / 99 : 0.0264
linear_regression MIST           Base   mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                        radius                    75 : 0.0962 / 90 : 0.1347 / 95 : 0.15728 / 99 : 0.25052
mlp               MIST           Base   mass                   75 : 0.64487 / 90 : 2.45842 / 95 : 5.63469 / 99 : 21.93746
                                        radius                  75 : 0.07677 / 90 : 0.12234 / 95 : 0.15977 / 99 : 0.26868
random_forest     MIST           Base   mass                     75 : 0.01627 / 90 : 0.10846 / 95 : 0.41678 / 99 : 3.6048
                                        radius                   75 : 0.00233 / 90 : 0.00485 / 95 : 0.0075 / 99 : 0.01647
xgboost           MIST           Base   mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                        radius                  75 : 0.01364 / 90 : 0.02151 / 95 : 0.02755 / 99 : 0.04225

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 2.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  1.000
KNN               MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  1.000
linear_regression MIST           Base   mass                 -283.067  0.317
                                        radius                 -2.800  0.968
mlp               MIST           Base   mass                 -283.067  0.981
                                        radius                 -2.800  0.981
random_forest     MIST           Base   mass                 -283.067  1.000
                                        radius                 -2.800  1.000
xgboost           MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  0.999

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.856   0.063
                                        radius             0.010   0.007
KNN               MIST           Base   mass               0.737   0.095
                                        radius             0.005   0.003
linear_regression MIST           Base   mass              24.543  10.236
                                        radius             0.088   0.058
mlp               MIST           Base   mass               4.103   1.093
                                        radius             0.068   0.050
random_forest     MIST           Base   mass               0.475   0.060
                                        radius             0.004   0.003
xgboost           MIST           Base   mass               0.996   0.293
                                        radius             0.014   0.011

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.000  1.000
                                        radius            0.005  1.000
KNN               MIST           Base   mass              0.004  1.000
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              5.268  0.596
                                        radius            0.034  0.984
mlp               MIST           Base   mass              0.263  0.991
                                        radius            0.039  0.991
random_forest     MIST           Base   mass              0.004  1.000
                                        radius            0.002  1.000
xgboost           MIST           Base   mass              0.071  0.999
                                        radius            0.009  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              115.074
                                        radius              0.262
KNN               MIST           Base   mass               37.487
                                        radius              0.077
linear_regression MIST           Base   mass              247.133
                                        radius              0.453
mlp               MIST           Base   mass               92.622
                                        radius              0.403
random_forest     MIST           Base   mass               21.389
                                        radius              0.101
xgboost           MIST           Base   mass               39.121
                                        radius              0.074

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                     75 : 0.0055 / 90 : 0.0255 / 95 : 0.04576 / 99 : 0.76556
                                        radius                 75 : 0.00907 / 90 : 0.01348 / 95 : 0.01669 / 99 : 0.03212
KNN               MIST           Base   mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                        radius                 75 : 0.00469 / 90 : 0.00772 / 95 : 0.00978 / 99 : 0.01453
linear_regression MIST           Base   mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                        radius                   75 : 0.0735 / 90 : 0.1413 / 95 : 0.19408 / 99 : 0.35002
mlp               MIST           Base   mass                  75 : 0.50511 / 90 : 1.67386 / 95 : 4.22263 / 99 : 20.09887
                                        radius                 75 : 0.06979 / 90 : 0.10692 / 95 : 0.13792 / 99 : 0.21054
random_forest     MIST           Base   mass                   75 : 0.01064 / 90 : 0.02559 / 95 : 0.07213 / 99 : 1.35752
                                        radius                 75 : 0.00359 / 90 : 0.00619 / 95 : 0.00829 / 99 : 0.01418
xgboost           MIST           Base   mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                        radius                 75 : 0.01514 / 90 : 0.02219 / 95 : 0.02704 / 99 : 0.03759

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 3.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -288.266  0.992
                                        radius                 -3.474  0.999
KNN               MIST           Base   mass                 -288.266  0.986
                                        radius                 -3.474  1.000
linear_regression MIST           Base   mass                 -288.266  0.388
                                        radius                 -3.474  0.970
mlp               MIST           Base   mass                 -288.266  0.952
                                        radius                 -3.474  0.980
random_forest     MIST           Base   mass                 -288.266  0.995
                                        radius                 -3.474  1.000
xgboost           MIST           Base   mass                 -288.266  0.994
                                        radius                 -3.474  0.999

                                                            RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               2.086  0.199
                                        radius             0.016  0.008
KNN               MIST           Base   mass               2.735  0.364
                                        radius             0.010  0.005
linear_regression MIST           Base   mass              18.164  7.961
                                        radius             0.100  0.070
mlp               MIST           Base   mass               5.083  1.368
                                        radius             0.082  0.060
random_forest     MIST           Base   mass               1.642  0.201
                                        radius             0.009  0.004
xgboost           MIST           Base   mass               1.730  0.451
                                        radius             0.019  0.013

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.004  0.996
                                        radius            0.004  1.000
KNN               MIST           Base   mass              0.010  0.993
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              4.599  0.650
                                        radius            0.046  0.985
mlp               MIST           Base   mass              0.264  0.976
                                        radius            0.046  0.990
random_forest     MIST           Base   mass              0.007  0.998
                                        radius            0.002  1.000
xgboost           MIST           Base   mass              0.094  0.997
                                        radius            0.009  0.999

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              151.658
                                        radius              0.351
KNN               MIST           Base   mass              144.214
                                        radius              0.307
linear_regression MIST           Base   mass              250.918
                                        radius              0.525
mlp               MIST           Base   mass              179.182
                                        radius              0.636
random_forest     MIST           Base   mass               95.148
                                        radius              0.292
xgboost           MIST           Base   mass               61.887
                                        radius              0.490

                                                                                                             Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.0237 / 90 : 0.11118 / 95 : 0.26881 / 99 : 4.59332
                                        radius                75 : 0.00937 / 90 : 0.01848 / 95 : 0.02886 / 99 : 0.06747
KNN               MIST           Base   mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                        radius                75 : 0.00589 / 90 : 0.01098 / 95 : 0.01632 / 99 : 0.04576
linear_regression MIST           Base   mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                        radius                75 : 0.08613 / 90 : 0.16865 / 95 : 0.22602 / 99 : 0.32909
mlp               MIST           Base   mass                  75 : 0.53231 / 90 : 2.20664 / 95 : 6.2769 / 99 : 24.01312
                                        radius                75 : 0.08503 / 90 : 0.12883 / 95 : 0.15888 / 99 : 0.25425
random_forest     MIST           Base   mass                   75 : 0.0288 / 90 : 0.10782 / 95 : 0.29875 / 99 : 4.67012
                                        radius                  75 : 0.005 / 90 : 0.01041 / 95 : 0.01596 / 99 : 0.04151
xgboost           MIST           Base   mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                        radius                75 : 0.01645 / 90 : 0.02595 / 95 : 0.03406 / 99 : 0.06632

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

## Getting the ranges for the values

In [10]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [17]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2978, Median : 8.35

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191

log_g  : Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047

log_R  : Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118

log_L  : Range : -3.33 - 5.9763, Mean : 2.2, Median : 2.3306

## Base vs mass_filtered

| Parameter      | Base                                                       | mass_filtered_smaller_3                                | mass_filtered_smaller_14                                           | mass_filtered_smaller_30                               |
| -------------  | ---------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : Range : 5.0 - 10.3 , Mean : 8.1222, Median : 8.15  | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5                    | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1000 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | star_mass  : Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289 | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557      | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | log_Teff  : Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557      | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | log_g  : Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537    | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976     | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | log_R  : Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357    | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### Mass parameter

In [5]:
compare_metrics(path, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9951817784001245
                                 mass_smaller_3  mass              0.9986106418886865
                                 mass_smaller_14 mass              0.9952844938510328
                                 mass_smaller_30 mass              0.9951639894597079
KNN               MIST           Base            mass              0.9895916504979603
                                 mass_smaller_3  mass              0.9984125750212497
                                 mass_smaller_14 mass              0.9895916504979603
                                 mass_smaller_30 mass              0.9895916504979603
linear_regression MIST           Base            mass              0.3042271481418729
                                 mass_smaller_3  mass              0.6829393130134978
                                 mass_smaller_14 mass              0.3042271481418729
                                 mass_smaller_30 mass              0.3042271481418729
mlp               MIST           Base            mass              0.9683844484481047
                                 mass_smaller_3  mass              0.9957994560369564
                                 mass_smaller_14 mass              0.9478895797513055
                                 mass_smaller_30 mass              0.9828362074027303
random_forest     MIST           Base            mass              0.9978054138856324
                                 mass_smaller_3  mass              0.9992541969730512
                                 mass_smaller_14 mass              0.9978246279671578
                                 mass_smaller_30 mass              0.9978090814796585
xgboost           MIST           Base            mass              0.9941191064217958
                                 mass_smaller_3  mass              0.9983728478790728
                                 mass_smaller_14 mass              0.9941191064217958
                                 mass_smaller_30 mass              0.9941191064217958

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                1.8540234102645101
                                 mass_smaller_3  mass              0.026963718784338744
                                 mass_smaller_14 mass                1.8341551482667755
                                 mass_smaller_30 mass                 1.857442794608431
KNN               MIST           Base            mass                 2.725540200848424
                                 mass_smaller_3  mass               0.02882109715471059
                                 mass_smaller_14 mass                 2.725540200848424
                                 mass_smaller_30 mass                 2.725540200848424
linear_regression MIST           Base            mass                22.279505512776158
                                 mass_smaller_3  mass                0.4073173369404139
                                 mass_smaller_14 mass                22.279505512776158
                                 mass_smaller_30 mass                22.279505512776158
mlp               MIST           Base            mass                4.7495233310888745
                                 mass_smaller_3  mass              0.046932506904485756
                                 mass_smaller_14 mass                 6.256866604527516
                                 mass_smaller_30 mass                 3.506272371699963
random_forest     MIST           Base            mass                1.2512629515795346
                                 mass_smaller_3  mass               0.01975564332021666
                                 mass_smaller_14 mass                1.2457736076457506
                                 mass_smaller_30 mass                1.2502174142307747
xgboost           MIST           Base            mass                 2.048301547851118
                                 mass_smaller_3  mass               0.02917938905834862
                                 mass_smaller_14 mass                 2.048301547851118
                                 mass_smaller_30 mass                 2.048301547851118

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.2004890397009006
                                 mass_smaller_3  mass              0.007951005822130222
                                 mass_smaller_14 mass               0.19932482758152828
                                 mass_smaller_30 mass               0.20013489021626832
KNN               MIST           Base            mass                0.3284718050123655
                                 mass_smaller_3  mass              0.011522296950541105
                                 mass_smaller_14 mass                0.3284718050123655
                                 mass_smaller_30 mass                0.3284718050123655
linear_regression MIST           Base            mass                11.345261481543792
                                 mass_smaller_3  mass               0.29751414476924204
                                 mass_smaller_14 mass                11.345261481543792
                                 mass_smaller_30 mass                11.345261481543792
mlp               MIST           Base            mass                1.2799196546015692
                                 mass_smaller_3  mass               0.03016257064520546
                                 mass_smaller_14 mass                1.9314990026978784
                                 mass_smaller_30 mass                 1.111056417247757
random_forest     MIST           Base            mass                0.1452769419896218
                                 mass_smaller_3  mass              0.006025796628853846
                                 mass_smaller_14 mass                0.1450974561041155
                                 mass_smaller_30 mass               0.14544775978054023
xgboost           MIST           Base            mass                0.5307691028961596
                                 mass_smaller_3  mass               0.01614069138603855
                                 mass_smaller_14 mass                0.5307691028961596
                                 mass_smaller_30 mass                0.5307691028961596

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0034602257578986995
                                 mass_smaller_3  mass               0.002184038421144674
                                 mass_smaller_14 mass              0.0034614777435916233
                                 mass_smaller_30 mass              0.0034658274986483217
KNN               MIST           Base            mass               0.008160595183567931
                                 mass_smaller_3  mass               0.004450027263839751
                                 mass_smaller_14 mass               0.008160595183567931
                                 mass_smaller_30 mass               0.008160595183567931
linear_regression MIST           Base            mass                   8.15379784782397
                                 mass_smaller_3  mass                0.23046762251371206
                                 mass_smaller_14 mass                   8.15379784782397
                                 mass_smaller_30 mass                   8.15379784782397
mlp               MIST           Base            mass                  0.277050288859769
                                 mass_smaller_3  mass               0.020107033844202427
                                 mass_smaller_14 mass                0.33978715156903316
                                 mass_smaller_30 mass                0.37168399460501333
random_forest     MIST           Base            mass               0.004111252117102282
                                 mass_smaller_3  mass              0.0020703142458058377
                                 mass_smaller_14 mass               0.004128173546273484
                                 mass_smaller_30 mass               0.004125628598466324
xgboost           MIST           Base            mass                0.09905868717464794
                                 mass_smaller_3  mass               0.009581761178914294
                                 mass_smaller_14 mass                0.09905868717464794
                                 mass_smaller_30 mass                0.09905868717464794

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.997589753636418
                                 mass_smaller_3  mass              0.9993051684300485
                                 mass_smaller_14 mass              0.9976408894322037
                                 mass_smaller_30 mass              0.9975807435432114
KNN               MIST           Base            mass              0.9948902170346177
                                 mass_smaller_3  mass              0.9992078031704579
                                 mass_smaller_14 mass              0.9948902170346177
                                 mass_smaller_30 mass              0.9948902170346177
linear_regression MIST           Base            mass              0.5515679007842895
                                 mass_smaller_3  mass              0.8264014246305732
                                 mass_smaller_14 mass              0.5515679007842895
                                 mass_smaller_30 mass              0.5515679007842895
mlp               MIST           Base            mass              0.9841319605524157
                                 mass_smaller_3  mass              0.9978975695374722
                                 mass_smaller_14 mass              0.9765758035050944
                                 mass_smaller_30 mass              0.9914207154585798
random_forest     MIST           Base            mass              0.9989035373674631
                                 mass_smaller_3  mass              0.9996270807690646
                                 mass_smaller_14 mass              0.9989131374040815
                                 mass_smaller_30 mass              0.9989052645073933
xgboost           MIST           Base            mass              0.9970552947594146
                                 mass_smaller_3  mass               0.999186127126375
                                 mass_smaller_14 mass              0.9970552947594146
                                 mass_smaller_30 mass              0.9970552947594146

                                                                               MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.65813444621273
                                 mass_smaller_3  mass              2.0171919805222065
                                 mass_smaller_14 mass              151.65813444621273
                                 mass_smaller_30 mass              151.65813444621273
KNN               MIST           Base            mass              144.21389375194437
                                 mass_smaller_3  mass              1.0215474131655333
                                 mass_smaller_14 mass              144.21389375194437
                                 mass_smaller_30 mass              144.21389375194437
linear_regression MIST           Base            mass              257.50847847048124
                                 mass_smaller_3  mass              2.8242406186495193
                                 mass_smaller_14 mass              257.50847847048124
                                 mass_smaller_30 mass              257.50847847048124
mlp               MIST           Base            mass              179.18165022433564
                                 mass_smaller_3  mass              1.1380741028372034
                                 mass_smaller_14 mass               183.8555248652169
                                 mass_smaller_30 mass              166.65541720985124
random_forest     MIST           Base            mass               95.14828406903314
                                 mass_smaller_3  mass              1.3490965095666518
                                 mass_smaller_14 mass                99.1425528233774
                                 mass_smaller_30 mass              103.44266579660032
xgboost           MIST           Base            mass               72.95365928611318
                                 mass_smaller_3  mass               1.164764377165806
                                 mass_smaller_14 mass               72.95365928611318
                                 mass_smaller_30 mass               72.95365928611318

                                                                                                                       Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.01985 / 90 : 0.10435 / 95 : 0.35217 / 99 : 4.54997
                                 mass_smaller_3  mass                    75 : 0.00666 / 90 : 0.0177 / 95 : 0.03052 / 99 : 0.08782
                                 mass_smaller_14 mass                    75 : 0.01984 / 90 : 0.10426 / 95 : 0.3525 / 99 : 4.53632
                                 mass_smaller_30 mass                   75 : 0.01984 / 90 : 0.10427 / 95 : 0.35202 / 99 : 4.45943
KNN               MIST           Base            mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                 mass_smaller_3  mass                      75 : 0.01148 / 90 : 0.025 / 95 : 0.04245 / 99 : 0.1307
                                 mass_smaller_14 mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                 mass_smaller_30 mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
linear_regression MIST           Base            mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                 mass_smaller_3  mass                    75 : 0.4196 / 90 : 0.64407 / 95 : 0.78036 / 99 : 1.14907
                                 mass_smaller_14 mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                 mass_smaller_30 mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
mlp               MIST           Base            mass                  75 : 0.57742 / 90 : 2.19642 / 95 : 5.39114 / 99 : 21.87825
                                 mass_smaller_3  mass                   75 : 0.03915 / 90 : 0.06589 / 95 : 0.08732 / 99 : 0.16978
                                 mass_smaller_14 mass                  75 : 2.23649 / 90 : 4.52151 / 95 : 5.67852 / 99 : 20.62222
                                 mass_smaller_30 mass                  75 : 0.72213 / 90 : 1.90839 / 95 : 4.44249 / 99 : 16.14246
random_forest     MIST           Base            mass                     75 : 0.0156 / 90 : 0.0791 / 95 : 0.29069 / 99 : 3.22241
                                 mass_smaller_3  mass                   75 : 0.00554 / 90 : 0.01225 / 95 : 0.01942 / 99 : 0.06893
                                 mass_smaller_14 mass                    75 : 0.01563 / 90 : 0.07924 / 95 : 0.29345 / 99 : 3.2338
                                 mass_smaller_30 mass                   75 : 0.01559 / 90 : 0.07901 / 95 : 0.29267 / 99 : 3.24571
xgboost           MIST           Base            mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                 mass_smaller_3  mass                   75 : 0.01928 / 90 : 0.03504 / 95 : 0.05155 / 99 : 0.10739
                                 mass_smaller_14 mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                 mass_smaller_30 mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808
                                 mass_smaller_14 mass               24.452606439590454

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_30 mass               0.0999979840073621 - 298.5447575808816

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9935567994940296
                                 mass_smaller_3  mass              0.9998109603044399
                                 mass_smaller_14 mass              0.9936483630983785
                                 mass_smaller_30 mass              0.9935794089969434
KNN               MIST           Base            mass              0.9843387655163102
                                 mass_smaller_3  mass              0.9992443930168096
                                 mass_smaller_14 mass              0.9843387655163102
                                 mass_smaller_30 mass              0.9843387655163102
linear_regression MIST           Base            mass              0.2728709030098654
                                 mass_smaller_3  mass              0.8226816036408051
                                 mass_smaller_14 mass              0.2728709030098654
                                 mass_smaller_30 mass              0.2728709030098654
mlp               MIST           Base            mass              0.9649620036835357
                                 mass_smaller_3  mass              0.9982370025646433
                                 mass_smaller_14 mass              0.9478473916947574
                                 mass_smaller_30 mass               0.984580263621212
random_forest     MIST           Base            mass              0.9973575906750899
                                 mass_smaller_3  mass               0.999947044394285
                                 mass_smaller_14 mass               0.997413901088023
                                 mass_smaller_30 mass               0.997368944119941
xgboost           MIST           Base            mass              0.9910072956179956
                                 mass_smaller_3  mass              0.9990403957488978
                                 mass_smaller_14 mass              0.9910072956179956
                                 mass_smaller_30 mass              0.9910072956179956

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 2.111164723262909
                                 mass_smaller_3  mass              0.010370181942051407
                                 mass_smaller_14 mass                 2.096103081128173
                                 mass_smaller_30 mass                 2.107454704641201
KNN               MIST           Base            mass                 3.292362185047644
                                 mass_smaller_3  mass               0.02073170340400842
                                 mass_smaller_14 mass                 3.292362185047644
                                 mass_smaller_30 mass                 3.292362185047644
linear_regression MIST           Base            mass                22.429900129172562
                                 mass_smaller_3  mass                 0.318923392743888
                                 mass_smaller_14 mass                22.429900129172562
                                 mass_smaller_30 mass                22.429900129172562
mlp               MIST           Base            mass                 4.923128306127916
                                 mass_smaller_3  mass                0.0322376724352715
                                 mass_smaller_14 mass                 6.181927412813075
                                 mass_smaller_30 mass                3.2730462646147935
random_forest     MIST           Base            mass                1.3521665845754873
                                 mass_smaller_3  mass              0.005488828615455466
                                 mass_smaller_14 mass                1.3376914087667897
                                 mass_smaller_30 mass                1.3492653913806696
xgboost           MIST           Base            mass                 2.494119573996689
                                 mass_smaller_3  mass              0.023363529700188942
                                 mass_smaller_14 mass                 2.494119573996689
                                 mass_smaller_30 mass                 2.494119573996689

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.26982874335994456
                                 mass_smaller_3  mass              0.005151362084081304
                                 mass_smaller_14 mass                0.2684220808637102
                                 mass_smaller_30 mass               0.26893625809081145
KNN               MIST           Base            mass                0.4317822333077811
                                 mass_smaller_3  mass              0.009679770503752662
                                 mass_smaller_14 mass                0.4317822333077811
                                 mass_smaller_30 mass                0.4317822333077811
linear_regression MIST           Base            mass                13.107804483635931
                                 mass_smaller_3  mass                0.2468843962705581
                                 mass_smaller_14 mass                13.107804483635931
                                 mass_smaller_30 mass                13.107804483635931
mlp               MIST           Base            mass                1.3415952237953057
                                 mass_smaller_3  mass              0.021222096159887786
                                 mass_smaller_14 mass                1.9827753395518333
                                 mass_smaller_30 mass                1.0859487065923914
random_forest     MIST           Base            mass               0.16783299547779296
                                 mass_smaller_3  mass              0.002764338682723445
                                 mass_smaller_14 mass               0.16765041145105403
                                 mass_smaller_30 mass               0.16841881212380835
xgboost           MIST           Base            mass                0.6773915424575189
                                 mass_smaller_3  mass               0.01561878702027606
                                 mass_smaller_14 mass                0.6773915424575189
                                 mass_smaller_30 mass                0.6773915424575189

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0059165484966978155
                                 mass_smaller_3  mass               0.002431496292047308
                                 mass_smaller_14 mass               0.005923601568046832
                                 mass_smaller_30 mass               0.005931907312450746
KNN               MIST           Base            mass               0.010309898110725357
                                 mass_smaller_3  mass               0.004370990974717159
                                 mass_smaller_14 mass               0.010309898110725357
                                 mass_smaller_30 mass               0.010309898110725357
linear_regression MIST           Base            mass                 11.253017830833237
                                 mass_smaller_3  mass                 0.1981865105082724
                                 mass_smaller_14 mass                 11.253017830833237
                                 mass_smaller_30 mass                 11.253017830833237
mlp               MIST           Base            mass                0.29043916463582464
                                 mass_smaller_3  mass               0.014953144263897489
                                 mass_smaller_14 mass                0.37322687497852314
                                 mass_smaller_30 mass                 0.3488324965019458
random_forest     MIST           Base            mass              0.0035490560629605206
                                 mass_smaller_3  mass              0.0013470803912696283
                                 mass_smaller_14 mass              0.0035453418124899994
                                 mass_smaller_30 mass              0.0035401103163561487
xgboost           MIST           Base            mass                0.12578609649357553
                                 mass_smaller_3  mass               0.010246877570266266
                                 mass_smaller_14 mass                0.12578609649357553
                                 mass_smaller_30 mass                0.12578609649357553

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9967888598703755
                                 mass_smaller_3  mass              0.9999054840622302
                                 mass_smaller_14 mass               0.996833021287733
                                 mass_smaller_30 mass              0.9967993978686069
KNN               MIST           Base            mass              0.9924111983284241
                                 mass_smaller_3  mass              0.9996260930156877
                                 mass_smaller_14 mass              0.9924111983284241
                                 mass_smaller_30 mass              0.9924111983284241
linear_regression MIST           Base            mass              0.5343027371731521
                                 mass_smaller_3  mass              0.9082925664189878
                                 mass_smaller_14 mass              0.5343027371731521
                                 mass_smaller_30 mass              0.5343027371731521
mlp               MIST           Base            mass              0.9826529817996816
                                 mass_smaller_3  mass              0.9991181560916915
                                 mass_smaller_14 mass              0.9773841955901896
                                 mass_smaller_30 mass              0.9924885323136697
random_forest     MIST           Base            mass              0.9986793327165373
                                 mass_smaller_3  mass              0.9999735435321911
                                 mass_smaller_14 mass              0.9987075486293543
                                 mass_smaller_30 mass               0.998685112002334
xgboost           MIST           Base            mass              0.9955145412428942
                                 mass_smaller_3  mass              0.9995201456664305
                                 mass_smaller_14 mass              0.9955145412428942
                                 mass_smaller_30 mass              0.9955145412428942

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               131.77529017024463
                                 mass_smaller_3  mass              0.34190413977015777
                                 mass_smaller_14 mass               131.77529017024463
                                 mass_smaller_30 mass               124.36083645636259
KNN               MIST           Base            mass               126.67441415982648
                                 mass_smaller_3  mass               0.3698302020229671
                                 mass_smaller_14 mass               126.67441415982648
                                 mass_smaller_30 mass               126.67441415982648
linear_regression MIST           Base            mass               257.50847847048124
                                 mass_smaller_3  mass               1.0632048095338902
                                 mass_smaller_14 mass               257.50847847048124
                                 mass_smaller_30 mass               257.50847847048124
mlp               MIST           Base            mass                127.1406465947268
                                 mass_smaller_3  mass               0.4656359153324776
                                 mass_smaller_14 mass               169.00486473342426
                                 mass_smaller_30 mass                96.04478201183304
random_forest     MIST           Base            mass                83.61091180145692
                                 mass_smaller_3  mass              0.18157378789633682
                                 mass_smaller_14 mass                83.57250382102333
                                 mass_smaller_30 mass                82.85120835326344
xgboost           MIST           Base            mass                72.95365928611318
                                 mass_smaller_3  mass              0.33286654519153314
                                 mass_smaller_14 mass                72.95365928611318
                                 mass_smaller_30 mass                72.95365928611318

                                                                                                                        Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                    75 : 0.03086 / 90 : 0.18472 / 95 : 0.67029 / 99 : 5.91802
                                 mass_smaller_3  mass                    75 : 0.00584 / 90 : 0.01193 / 95 : 0.01927 / 99 : 0.04066
                                 mass_smaller_14 mass                    75 : 0.03085 / 90 : 0.18449 / 95 : 0.67009 / 99 : 5.87355
                                 mass_smaller_30 mass                     75 : 0.03083 / 90 : 0.18447 / 95 : 0.66893 / 99 : 5.8341
KNN               MIST           Base            mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                 mass_smaller_3  mass                    75 : 0.01053 / 90 : 0.02183 / 95 : 0.03434 / 99 : 0.09292
                                 mass_smaller_14 mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                 mass_smaller_30 mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
linear_regression MIST           Base            mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                 mass_smaller_3  mass                    75 : 0.35855 / 90 : 0.55457 / 95 : 0.66376 / 99 : 0.80961
                                 mass_smaller_14 mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                 mass_smaller_30 mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
mlp               MIST           Base            mass                   75 : 0.64487 / 90 : 2.45842 / 95 : 5.63469 / 99 : 21.93746
                                 mass_smaller_3  mass                    75 : 0.02736 / 90 : 0.04468 / 95 : 0.06067 / 99 : 0.11131
                                 mass_smaller_14 mass                   75 : 2.28865 / 90 : 4.74405 / 95 : 6.00295 / 99 : 20.23021
                                 mass_smaller_30 mass                   75 : 0.69276 / 90 : 2.06135 / 95 : 4.82804 / 99 : 14.03415
random_forest     MIST           Base            mass                     75 : 0.01627 / 90 : 0.10846 / 95 : 0.41678 / 99 : 3.6048
                                 mass_smaller_3  mass                    75 : 0.00319 / 90 : 0.00646 / 95 : 0.00971 / 99 : 0.02179
                                 mass_smaller_14 mass                    75 : 0.01643 / 90 : 0.10813 / 95 : 0.42046 / 99 : 3.63991
                                 mass_smaller_30 mass                      75 : 0.01637 / 90 : 0.108 / 95 : 0.41909 / 99 : 3.63658
xgboost           MIST           Base            mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                 mass_smaller_3  mass                    75 : 0.02029 / 90 : 0.03559 / 95 : 0.04925 / 99 : 0.08368
                                 mass_smaller_14 mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                 mass_smaller_30 mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483
KNN               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483
linear_regression MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483
mlp               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483
random_forest     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483
xgboost           MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_30 mass              0.6538581961218565 - 283.72102985530483

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9991682912199935
                                 mass_smaller_3  mass              0.9992078967946935
                                 mass_smaller_14 mass              0.9992190516533151
                                 mass_smaller_30 mass              0.9992529638955677
KNN               MIST           Base            mass              0.9993836364150782
                                 mass_smaller_3  mass              0.9991876883590323
                                 mass_smaller_14 mass              0.9993836364150782
                                 mass_smaller_30 mass              0.9993836364150782
linear_regression MIST           Base            mass              0.3168817813892185
                                 mass_smaller_3  mass              0.6094803842541214
                                 mass_smaller_14 mass              0.3168817813892185
                                 mass_smaller_30 mass              0.3168817813892185
mlp               MIST           Base            mass              0.9809873465478306
                                 mass_smaller_3  mass               0.995291571916788
                                 mass_smaller_14 mass              0.9533325992045314
                                 mass_smaller_30 mass              0.9903834253738333
random_forest     MIST           Base            mass              0.9997441818803499
                                 mass_smaller_3  mass              0.9996653648909077
                                 mass_smaller_14 mass               0.999743214302835
                                 mass_smaller_30 mass              0.9997429524189717
xgboost           MIST           Base            mass              0.9988754736593098
                                 mass_smaller_3  mass               0.999225961655845
                                 mass_smaller_14 mass              0.9988754736593098
                                 mass_smaller_30 mass              0.9988754736593098

                                                                                   RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.8563821878406251
                                 mass_smaller_3  mass              0.017616715482776626
                                 mass_smaller_14 mass                0.8298425834788763
                                 mass_smaller_30 mass                  0.81162566029371
KNN               MIST           Base            mass                0.7372507757129543
                                 mass_smaller_3  mass              0.017863580890469438
                                 mass_smaller_14 mass                0.7372507757129543
                                 mass_smaller_30 mass                0.7372507757129543
linear_regression MIST           Base            mass                24.543023748412015
                                 mass_smaller_3  mass               0.40795181296848076
                                 mass_smaller_14 mass                24.543023748412015
                                 mass_smaller_30 mass                24.543023748412015
mlp               MIST           Base            mass                4.1025447018224765
                                 mass_smaller_3  mass               0.04347468113678617
                                 mass_smaller_14 mass                 6.612246427503836
                                 mass_smaller_30 mass                 2.912335719667227
random_forest     MIST           Base            mass               0.47498420224835197
                                 mass_smaller_3  mass               0.01145266644937612
                                 mass_smaller_14 mass                0.4758809844765971
                                 mass_smaller_30 mass               0.47612846312273854
xgboost           MIST           Base            mass                0.9959317895204074
                                 mass_smaller_3  mass              0.017420504143439753
                                 mass_smaller_14 mass                0.9959317895204074
                                 mass_smaller_30 mass                0.9959317895204074

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.06250788141530114
                                 mass_smaller_3  mass              0.007694368270985248
                                 mass_smaller_14 mass                0.0609448448948592
                                 mass_smaller_30 mass               0.06116911029908313
KNN               MIST           Base            mass               0.09538418274204148
                                 mass_smaller_3  mass              0.008954045678879998
                                 mass_smaller_14 mass               0.09538418274204148
                                 mass_smaller_30 mass               0.09538418274204148
linear_regression MIST           Base            mass                 10.23576274299457
                                 mass_smaller_3  mass               0.31283468382588653
                                 mass_smaller_14 mass                 10.23576274299457
                                 mass_smaller_30 mass                 10.23576274299457
mlp               MIST           Base            mass                1.0928917274409464
                                 mass_smaller_3  mass               0.03303430572775442
                                 mass_smaller_14 mass                 1.830588639273006
                                 mass_smaller_30 mass                0.9397350987175546
random_forest     MIST           Base            mass               0.05965777535357753
                                 mass_smaller_3  mass              0.006816718583654214
                                 mass_smaller_14 mass               0.05943118368961476
                                 mass_smaller_30 mass              0.059361707757584606
xgboost           MIST           Base            mass               0.29336744162478817
                                 mass_smaller_3  mass              0.011962832958118098
                                 mass_smaller_14 mass               0.29336744162478817
                                 mass_smaller_30 mass               0.29336744162478817

                                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.00035448824774864107
                                 mass_smaller_3  mass               0.0011683880009409897
                                 mass_smaller_14 mass               0.0003537166020919358
                                 mass_smaller_30 mass              0.00035495616004110886
KNN               MIST           Base            mass                0.003644066674525215
                                 mass_smaller_3  mass               0.0049844695910198356
                                 mass_smaller_14 mass                0.003644066674525215
                                 mass_smaller_30 mass                0.003644066674525215
linear_regression MIST           Base            mass                   5.268355111684988
                                 mass_smaller_3  mass                 0.25049991044110187
                                 mass_smaller_14 mass                   5.268355111684988
                                 mass_smaller_30 mass                   5.268355111684988
mlp               MIST           Base            mass                  0.2631247976663317
                                 mass_smaller_3  mass                 0.02614850301189242
                                 mass_smaller_14 mass                  0.2932128930842761
                                 mass_smaller_30 mass                  0.3606439870680642
random_forest     MIST           Base            mass                0.004034495488792533
                                 mass_smaller_3  mass                0.004307804055038389
                                 mass_smaller_14 mass                0.004050206037180315
                                 mass_smaller_30 mass                0.004060477925214023
xgboost           MIST           Base            mass                 0.07123763131807914
                                 mass_smaller_3  mass                  0.0081628820130073
                                 mass_smaller_14 mass                 0.07123763131807914
                                 mass_smaller_30 mass                 0.07123763131807914

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9995841526922911
                                 mass_smaller_3  mass              0.9996086734847093
                                 mass_smaller_14 mass              0.9996095611037669
                                 mass_smaller_30 mass              0.9996265338349888
KNN               MIST           Base            mass              0.9996927065174758
                                 mass_smaller_3  mass              0.9996103334674206
                                 mass_smaller_14 mass              0.9996927065174758
                                 mass_smaller_30 mass              0.9996927065174758
linear_regression MIST           Base            mass              0.5956286032810738
                                 mass_smaller_3  mass              0.8443908629223283
                                 mass_smaller_14 mass              0.5956286032810738
                                 mass_smaller_30 mass              0.5956286032810738
mlp               MIST           Base            mass              0.9906440264736001
                                 mass_smaller_3  mass              0.9976529594265796
                                 mass_smaller_14 mass              0.9800643534553883
                                 mass_smaller_30 mass              0.9954005023987678
random_forest     MIST           Base            mass              0.9998728077084751
                                 mass_smaller_3  mass              0.9998368427876034
                                 mass_smaller_14 mass              0.9998723208690561
                                 mass_smaller_30 mass              0.9998722085378534
xgboost           MIST           Base            mass              0.9994709362034415
                                 mass_smaller_3  mass              0.9996379383407658
                                 mass_smaller_14 mass              0.9994709362034415
                                 mass_smaller_30 mass              0.9994709362034415

                                                                                MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               115.07406668861114
                                 mass_smaller_3  mass               0.4249228172899455
                                 mass_smaller_14 mass                100.3675054235268
                                 mass_smaller_30 mass                 113.357727561799
KNN               MIST           Base            mass                37.48661252169403
                                 mass_smaller_3  mass              0.25092821324204007
                                 mass_smaller_14 mass                37.48661252169403
                                 mass_smaller_30 mass                37.48661252169403
linear_regression MIST           Base            mass                247.1328209413902
                                 mass_smaller_3  mass                1.286388691281558
                                 mass_smaller_14 mass                247.1328209413902
                                 mass_smaller_30 mass                247.1328209413902
mlp               MIST           Base            mass                92.62233332462321
                                 mass_smaller_3  mass              0.24497779297832079
                                 mass_smaller_14 mass               150.50027756851617
                                 mass_smaller_30 mass                70.50425133982313
random_forest     MIST           Base            mass               21.388650133880788
                                 mass_smaller_3  mass               0.2152611485477416
                                 mass_smaller_14 mass               23.113277495647964
                                 mass_smaller_30 mass                18.59308616784716
xgboost           MIST           Base            mass                39.12064222195215
                                 mass_smaller_3  mass              0.17315979871153675
                                 mass_smaller_14 mass                39.12064222195215
                                 mass_smaller_30 mass                39.12064222195215

                                                                                                                       Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                     75 : 0.0055 / 90 : 0.0255 / 95 : 0.04576 / 99 : 0.76556
                                 mass_smaller_3  mass                   75 : 0.00836 / 90 : 0.02499 / 95 : 0.03441 / 99 : 0.06152
                                 mass_smaller_14 mass                   75 : 0.00547 / 90 : 0.02538 / 95 : 0.04514 / 99 : 0.73043
                                 mass_smaller_30 mass                   75 : 0.00551 / 90 : 0.02554 / 95 : 0.04552 / 99 : 0.75332
KNN               MIST           Base            mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                 mass_smaller_3  mass                   75 : 0.01135 / 90 : 0.02134 / 95 : 0.03077 / 99 : 0.08437
                                 mass_smaller_14 mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                 mass_smaller_30 mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
linear_regression MIST           Base            mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                 mass_smaller_3  mass                   75 : 0.46818 / 90 : 0.69527 / 95 : 0.84131 / 99 : 1.06546
                                 mass_smaller_14 mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                 mass_smaller_30 mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
mlp               MIST           Base            mass                  75 : 0.50511 / 90 : 1.67386 / 95 : 4.22263 / 99 : 20.09887
                                 mass_smaller_3  mass                    75 : 0.04673 / 90 : 0.0692 / 95 : 0.08313 / 99 : 0.13242
                                 mass_smaller_14 mass                  75 : 1.97102 / 90 : 4.38429 / 95 : 4.88624 / 99 : 20.02265
                                 mass_smaller_30 mass                  75 : 0.68182 / 90 : 1.53376 / 95 : 3.14288 / 99 : 12.91915
random_forest     MIST           Base            mass                   75 : 0.01064 / 90 : 0.02559 / 95 : 0.07213 / 99 : 1.35752
                                 mass_smaller_3  mass                    75 : 0.00903 / 90 : 0.01523 / 95 : 0.0204 / 99 : 0.03971
                                 mass_smaller_14 mass                   75 : 0.01054 / 90 : 0.02552 / 95 : 0.07329 / 99 : 1.33501
                                 mass_smaller_30 mass                    75 : 0.0106 / 90 : 0.02556 / 95 : 0.07221 / 99 : 1.36785
xgboost           MIST           Base            mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                 mass_smaller_3  mass                    75 : 0.01588 / 90 : 0.0268 / 95 : 0.03579 / 99 : 0.06169
                                 mass_smaller_14 mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                 mass_smaller_30 mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808

Results for the phase category with a value of 3.0

                                                                                              value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117
KNN               MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117
linear_regression MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117
mlp               MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117
random_forest     MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117
xgboost           MIST           Base            mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass              0.5418086127397849 - 2.999885115629765
                                 mass_smaller_14 mass               0.5484495344916944 - 288.814589557117
                                 mass_smaller_30 mass               0.5484495344916944 - 288.814589557117

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9918974335576843
                                 mass_smaller_3  mass               0.9925088328108644
                                 mass_smaller_14 mass               0.9921593929956303
                                 mass_smaller_30 mass               0.9914993723370994
KNN               MIST           Base            mass               0.9860770182495742
                                 mass_smaller_3  mass                 0.99350766733889
                                 mass_smaller_14 mass               0.9860770182495742
                                 mass_smaller_30 mass               0.9860770182495742
linear_regression MIST           Base            mass              0.38830292902171926
                                 mass_smaller_3  mass              0.15358248802528074
                                 mass_smaller_14 mass              0.38830292902171926
                                 mass_smaller_30 mass              0.38830292902171926
mlp               MIST           Base            mass               0.9519375404272862
                                 mass_smaller_3  mass               0.9859577609925029
                                 mass_smaller_14 mass               0.9358246774327645
                                 mass_smaller_30 mass               0.9594092979858375
random_forest     MIST           Base            mass               0.9949810881828094
                                 mass_smaller_3  mass               0.9956700597782066
                                 mass_smaller_14 mass               0.9949130093083712
                                 mass_smaller_30 mass               0.9949681865732133
xgboost           MIST           Base            mass               0.9944238807426196
                                 mass_smaller_3  mass               0.9940163365388791
                                 mass_smaller_14 mass               0.9944238807426196
                                 mass_smaller_30 mass               0.9944238807426196

                                                                                  RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                2.086222856008246
                                 mass_smaller_3  mass              0.05549221609398243
                                 mass_smaller_14 mass               2.0522187068955087
                                 mass_smaller_30 mass               2.1368064791967014
KNN               MIST           Base            mass                2.734806056725069
                                 mass_smaller_3  mass              0.05166760544925883
                                 mass_smaller_14 mass                2.734806056725069
                                 mass_smaller_30 mass                2.734806056725069
linear_regression MIST           Base            mass               18.164454718433227
                                 mass_smaller_3  mass               0.5936734849308265
                                 mass_smaller_14 mass               18.164454718433227
                                 mass_smaller_30 mass               18.164454718433227
mlp               MIST           Base            mass                5.083213797408978
                                 mass_smaller_3  mass              0.07749136063495056
                                 mass_smaller_14 mass                5.948526398443184
                                 mass_smaller_30 mass                4.693165994475431
random_forest     MIST           Base            mass                1.642420538512268
                                 mass_smaller_3  mass              0.04218948342523731
                                 mass_smaller_14 mass               1.6535157402838208
                                 mass_smaller_30 mass               1.6444983811441365
xgboost           MIST           Base            mass                 1.73045095147863
                                 mass_smaller_3  mass              0.04960002132995069
                                 mass_smaller_14 mass                 1.73045095147863
                                 mass_smaller_30 mass                 1.73045095147863

                                                                                    MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.19876474354848747
                                 mass_smaller_3  mass              0.016451897766401203
                                 mass_smaller_14 mass               0.19883409734486018
                                 mass_smaller_30 mass               0.20128759786605474
KNN               MIST           Base            mass               0.36421728355537797
                                 mass_smaller_3  mass               0.02025881030023404
                                 mass_smaller_14 mass               0.36421728355537797
                                 mass_smaller_30 mass               0.36421728355537797
linear_regression MIST           Base            mass                 7.961491217898485
                                 mass_smaller_3  mass               0.42510847614194097
                                 mass_smaller_14 mass                 7.961491217898485
                                 mass_smaller_30 mass                 7.961491217898485
mlp               MIST           Base            mass                1.3679461988307051
                                 mass_smaller_3  mass               0.05247603784180956
                                 mass_smaller_14 mass                 1.928655550987563
                                 mass_smaller_30 mass                 1.419906320510521
random_forest     MIST           Base            mass               0.20145454791412173
                                 mass_smaller_3  mass              0.014501789192269845
                                 mass_smaller_14 mass                0.2013493398604617
                                 mass_smaller_30 mass               0.20111508890417903
xgboost           MIST           Base            mass                0.4513957644350668
                                 mass_smaller_3  mass               0.02313346360611026
                                 mass_smaller_14 mass                0.4513957644350668
                                 mass_smaller_30 mass                0.4513957644350668

                                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.0038324881287014056
                                 mass_smaller_3  mass              0.0018932641038316156
                                 mass_smaller_14 mass              0.0038757572663593587
                                 mass_smaller_30 mass              0.0038434600866712465
KNN               MIST           Base            mass                0.01014186225597502
                                 mass_smaller_3  mass               0.004109206835448909
                                 mass_smaller_14 mass                0.01014186225597502
                                 mass_smaller_30 mass                0.01014186225597502
linear_regression MIST           Base            mass                  4.598725686177184
                                 mass_smaller_3  mass                0.32287952930253383
                                 mass_smaller_14 mass                  4.598725686177184
                                 mass_smaller_30 mass                  4.598725686177184
mlp               MIST           Base            mass                  0.264341278289347
                                 mass_smaller_3  mass                0.03857040177293647
                                 mass_smaller_14 mass                 0.3253481568090255
                                 mass_smaller_30 mass                 0.4636321758817188
random_forest     MIST           Base            mass               0.006907232098912752
                                 mass_smaller_3  mass               0.003545841487851087
                                 mass_smaller_14 mass               0.006905876154084667
                                 mass_smaller_30 mass               0.006940862869302067
xgboost           MIST           Base            mass                0.09355388928063046
                                 mass_smaller_3  mass               0.009825121353496336
                                 mass_smaller_14 mass                0.09355388928063046
                                 mass_smaller_30 mass                0.09355388928063046

                                                                                  CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9959603108250029
                                 mass_smaller_3  mass               0.9962474248572476
                                 mass_smaller_14 mass               0.9960922020037272
                                 mass_smaller_30 mass               0.9957584645267742
KNN               MIST           Base            mass               0.9931315041563596
                                 mass_smaller_3  mass               0.9967899726916828
                                 mass_smaller_14 mass               0.9931315041563596
                                 mass_smaller_30 mass               0.9931315041563596
linear_regression MIST           Base            mass               0.6497333100274104
                                 mass_smaller_3  mass              0.40530355547261254
                                 mass_smaller_14 mass               0.6497333100274104
                                 mass_smaller_30 mass               0.6497333100274104
mlp               MIST           Base            mass               0.9761539783804645
                                 mass_smaller_3  mass               0.9930099112080837
                                 mass_smaller_14 mass               0.9676697520152883
                                 mass_smaller_30 mass               0.9799662843326516
random_forest     MIST           Base            mass               0.9976029233414596
                                 mass_smaller_3  mass               0.9978436498641285
                                 mass_smaller_14 mass               0.9975685820026399
                                 mass_smaller_30 mass               0.9975920917628096
xgboost           MIST           Base            mass               0.9972366154162345
                                 mass_smaller_3  mass               0.9970442373213937
                                 mass_smaller_14 mass               0.9972366154162345
                                 mass_smaller_30 mass               0.9972366154162345

                                                                               MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.65813444621273
                                 mass_smaller_3  mass              2.0171919805222065
                                 mass_smaller_14 mass              151.65813444621273
                                 mass_smaller_30 mass              151.65813444621273
KNN               MIST           Base            mass              144.21389375194437
                                 mass_smaller_3  mass              1.0215474131655333
                                 mass_smaller_14 mass              144.21389375194437
                                 mass_smaller_30 mass              144.21389375194437
linear_regression MIST           Base            mass              250.91823890694823
                                 mass_smaller_3  mass              2.8242406186495193
                                 mass_smaller_14 mass              250.91823890694823
                                 mass_smaller_30 mass              250.91823890694823
mlp               MIST           Base            mass              179.18165022433564
                                 mass_smaller_3  mass              1.1380741028372034
                                 mass_smaller_14 mass               183.8555248652169
                                 mass_smaller_30 mass              166.65541720985124
random_forest     MIST           Base            mass               95.14828406903314
                                 mass_smaller_3  mass              1.3490965095666518
                                 mass_smaller_14 mass                99.1425528233774
                                 mass_smaller_30 mass              103.44266579660032
xgboost           MIST           Base            mass               61.88665111883462
                                 mass_smaller_3  mass               1.164764377165806
                                 mass_smaller_14 mass               61.88665111883462
                                 mass_smaller_30 mass               61.88665111883462

                                                                                                                      Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.0237 / 90 : 0.11118 / 95 : 0.26881 / 99 : 4.59332
                                 mass_smaller_3  mass                  75 : 0.00941 / 90 : 0.03454 / 95 : 0.07581 / 99 : 0.27683
                                 mass_smaller_14 mass                  75 : 0.02373 / 90 : 0.11124 / 95 : 0.27005 / 99 : 4.62067
                                 mass_smaller_30 mass                  75 : 0.02369 / 90 : 0.11103 / 95 : 0.26515 / 99 : 4.58418
KNN               MIST           Base            mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                 mass_smaller_3  mass                  75 : 0.01678 / 90 : 0.05464 / 95 : 0.10517 / 99 : 0.23112
                                 mass_smaller_14 mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                 mass_smaller_30 mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
linear_regression MIST           Base            mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                 mass_smaller_3  mass                  75 : 0.53852 / 90 : 0.86058 / 95 : 1.12503 / 99 : 2.20922
                                 mass_smaller_14 mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                 mass_smaller_30 mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
mlp               MIST           Base            mass                  75 : 0.53231 / 90 : 2.20664 / 95 : 6.2769 / 99 : 24.01312
                                 mass_smaller_3  mass                  75 : 0.06593 / 90 : 0.10615 / 95 : 0.14643 / 99 : 0.28036
                                 mass_smaller_14 mass                 75 : 2.35105 / 90 : 4.42484 / 95 : 5.76761 / 99 : 22.32439
                                 mass_smaller_30 mass                  75 : 0.82514 / 90 : 2.11616 / 95 : 5.5643 / 99 : 22.16383
random_forest     MIST           Base            mass                   75 : 0.0288 / 90 : 0.10782 / 95 : 0.29875 / 99 : 4.67012
                                 mass_smaller_3  mass                   75 : 0.01061 / 90 : 0.03037 / 95 : 0.06452 / 99 : 0.2086
                                 mass_smaller_14 mass                  75 : 0.02869 / 90 : 0.10814 / 95 : 0.29792 / 99 : 4.66353
                                 mass_smaller_30 mass                  75 : 0.02886 / 90 : 0.10712 / 95 : 0.29747 / 99 : 4.72241
xgboost           MIST           Base            mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                 mass_smaller_3  mass                   75 : 0.02197 / 90 : 0.05469 / 95 : 0.0944 / 99 : 0.22596
                                 mass_smaller_14 mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                 mass_smaller_30 mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                33.71577191352844
                                 mass_smaller_3  mass               11.799425840377808
                                 mass_smaller_14 mass               24.452606439590454

Linear regression : 
- mass_filtered_smaller_30 : similar results as Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : similar results as Base (proportionnaly to the mass)

Decision tree : 
- mass_filtered_smaller_30 : worse results than Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : worse results than Base (proportionnaly to the mass)

KNN : 
- mass_filtered_smaller_30 : slightly better results than Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : slightly worse results than Base (proportionnaly to the mass)

Random forest : 
- mass_filtered_smaller_30 : similar results as Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : slightly worse results than Base (proportionnaly to the mass)

XGBoost : 
- mass_filtered_smaller_30 : slightly worse results than Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : slightly worse results than Base (proportionnaly to the mass)

MLP : 
- mass_filtered_smaller_30 : similar results as Base (proportionnaly to the mass)
- mass_filtered_smaller_3 : similar results as Base (proportionnaly to the mass)

Linear regression : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

Decision tree : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

KNN : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

Random forest : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

XGBoost : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

MLP : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 :

#### Conclusions on mass

Proportionnaly to the mass, both filtering give similar (sometimes slightly worse or better) results than Base

&emsp; => not interesting to use as it also restricts what kind of stars the model can predict

### Radius parameter

In [ ]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_filtered_smaller_30", "mass_filtered_smaller_3"])

                                                                                           RVE  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius            0.9997899702074513
                                 mass_filtered_smaller_30 radius            0.9998061270554189
                                 mass_filtered_smaller_3  radius            0.9997980449596693
KNN               MIST           Base                     radius             0.999833901666557
                                 mass_filtered_smaller_30 radius             0.999845742270286
                                 mass_filtered_smaller_3  radius            0.9998124002057707
linear_regression MIST           Base                     radius            0.9897611137480969
                                 mass_filtered_smaller_30 radius            0.9925428351690286
                                 mass_filtered_smaller_3  radius            0.9958055391259805
mlp               MIST           Base                     radius            0.9960419184441298
                                 mass_filtered_smaller_30 radius            0.9987759834874893
                                 mass_filtered_smaller_3  radius            0.9994078667866224
random_forest     MIST           Base                     radius             0.999904453912182
                                 mass_filtered_smaller_30 radius             0.999911027099752
                                 mass_filtered_smaller_3  radius            0.9998952156558059
xgboost           MIST           Base                     radius            0.9996009897646162
                                 mass_filtered_smaller_30 radius             0.999676980016293
                                 mass_filtered_smaller_3  radius            0.9997374331207423

                                                                                            RMSE  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius            0.013774959488591745
                                 mass_filtered_smaller_30 radius            0.013462255965888063
                                 mass_filtered_smaller_3  radius            0.014543308792759283
KNN               MIST           Base                     radius            0.012250269140419087
                                 mass_filtered_smaller_30 radius               0.012009180907773
                                 mass_filtered_smaller_3  radius            0.014019621430573385
linear_regression MIST           Base                     radius             0.09617751115675367
                                 mass_filtered_smaller_30 radius              0.0834915224254678
                                 mass_filtered_smaller_3  radius               0.066277386089521
mlp               MIST           Base                     radius            0.060330025886507314
                                 mass_filtered_smaller_30 radius            0.034357031439120785
                                 mass_filtered_smaller_3  radius             0.02789966474335524
random_forest     MIST           Base                     radius            0.009291129066072832
                                 mass_filtered_smaller_30 radius            0.009120128374631557
                                 mass_filtered_smaller_3  radius            0.010476065091138284
xgboost           MIST           Base                     radius            0.018986255054897025
                                 mass_filtered_smaller_30 radius             0.01737682271670121
                                 mass_filtered_smaller_3  radius             0.01658239941408444

                                                                                              MAE  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius             0.007206933620411441
                                 mass_filtered_smaller_30 radius             0.007048781647942495
                                 mass_filtered_smaller_3  radius             0.007228490272178777
KNN               MIST           Base                     radius             0.006476490638448258
                                 mass_filtered_smaller_30 radius              0.00638546155915349
                                 mass_filtered_smaller_3  radius             0.007597533419531711
linear_regression MIST           Base                     radius              0.07195174148370423
                                 mass_filtered_smaller_30 radius              0.06504086122918111
                                 mass_filtered_smaller_3  radius             0.053263145810978754
mlp               MIST           Base                     radius              0.04294508972270472
                                 mass_filtered_smaller_30 radius             0.025551826662590912
                                 mass_filtered_smaller_3  radius              0.02020179317089933
random_forest     MIST           Base                     radius             0.004568449003201065
                                 mass_filtered_smaller_30 radius            0.0045068366219739465
                                 mass_filtered_smaller_3  radius             0.005087489633142531
xgboost           MIST           Base                     radius             0.013929692953203763
                                 mass_filtered_smaller_30 radius             0.012737733218130255
                                 mass_filtered_smaller_3  radius             0.011554286239594626

                                                                                            MedAE  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius             0.003567480407395074
                                 mass_filtered_smaller_30 radius             0.003480084550178786
                                 mass_filtered_smaller_3  radius             0.003128295879770482
KNN               MIST           Base                     radius              0.00309317203967141
                                 mass_filtered_smaller_30 radius              0.00305341283356797
                                 mass_filtered_smaller_3  radius            0.0034485702594244105
linear_regression MIST           Base                     radius              0.05483596363024501
                                 mass_filtered_smaller_30 radius              0.05338786997733952
                                 mass_filtered_smaller_3  radius              0.04637850962108053
mlp               MIST           Base                     radius              0.03203826639540808
                                 mass_filtered_smaller_30 radius             0.020208523360502495
                                 mass_filtered_smaller_3  radius             0.015852780427029645
random_forest     MIST           Base                     radius            0.0018879824602930917
                                 mass_filtered_smaller_30 radius            0.0018526338286604105
                                 mass_filtered_smaller_3  radius            0.0018548895212230708
xgboost           MIST           Base                     radius             0.010587901199418243
                                 mass_filtered_smaller_30 radius             0.009657425748406778
                                 mass_filtered_smaller_3  radius             0.008178448361610302

                                                                                          CORR  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius            0.9998950176828767
                                 mass_filtered_smaller_30 radius             0.999903104021297
                                 mass_filtered_smaller_3  radius            0.9998990515205088
KNN               MIST           Base                     radius            0.9999169586890249
                                 mass_filtered_smaller_30 radius            0.9999228811195526
                                 mass_filtered_smaller_3  radius             0.999906207529898
linear_regression MIST           Base                     radius            0.9948673850057176
                                 mass_filtered_smaller_30 radius            0.9962644403816882
                                 mass_filtered_smaller_3  radius            0.9979005657509382
mlp               MIST           Base                     radius            0.9982798599860538
                                 mass_filtered_smaller_30 radius            0.9993881726160077
                                 mass_filtered_smaller_3  radius             0.999703950192692
random_forest     MIST           Base                     radius            0.9999522318952349
                                 mass_filtered_smaller_30 radius            0.9999555233337166
                                 mass_filtered_smaller_3  radius            0.9999476181402057
xgboost           MIST           Base                     radius            0.9998004807859229
                                 mass_filtered_smaller_30 radius             0.999838479954102
                                 mass_filtered_smaller_3  radius            0.9998687083705904

                                                                                         MAX_ER  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius             0.4543867202727765
                                 mass_filtered_smaller_30 radius             0.8387471477688041
                                 mass_filtered_smaller_3  radius             0.2671235002295904
KNN               MIST           Base                     radius             0.2990175210027979
                                 mass_filtered_smaller_30 radius            0.25265660257402534
                                 mass_filtered_smaller_3  radius            0.26087605719507456
linear_regression MIST           Base                     radius            0.48899646293087007
                                 mass_filtered_smaller_30 radius             0.3742776903813434
                                 mass_filtered_smaller_3  radius            0.33904326041960253
mlp               MIST           Base                     radius             0.5378201622329044
                                 mass_filtered_smaller_30 radius            0.49841860154233464
                                 mass_filtered_smaller_3  radius             0.4480227615076733
random_forest     MIST           Base                     radius              0.366220162043867
                                 mass_filtered_smaller_30 radius            0.23453191984237343
                                 mass_filtered_smaller_3  radius             0.2375985416469213
xgboost           MIST           Base                     radius             0.4316527938038922
                                 mass_filtered_smaller_30 radius             0.2759740654684639
                                 mass_filtered_smaller_3  radius            0.17234105618015816

                                                                                                                            Percentiles  \
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius             75 : 0.00829 / 90 : 0.01642 / 95 : 0.02615 / 99 : 0.05977
                                 mass_filtered_smaller_30 radius              75 : 0.00815 / 90 : 0.01613 / 95 : 0.0255 / 99 : 0.05853
                                 mass_filtered_smaller_3  radius               75 : 0.00774 / 90 : 0.01687 / 95 : 0.02835 / 99 : 0.066
KNN               MIST           Base                     radius             75 : 0.00723 / 90 : 0.01546 / 95 : 0.02468 / 99 : 0.05304
                                 mass_filtered_smaller_30 radius             75 : 0.00711 / 90 : 0.01531 / 95 : 0.02451 / 99 : 0.05167
                                 mass_filtered_smaller_3  radius             75 : 0.00859 / 90 : 0.01935 / 95 : 0.03017 / 99 : 0.05843
linear_regression MIST           Base                     radius             75 : 0.10009 / 90 : 0.15489 / 95 : 0.20131 / 99 : 0.28426
                                 mass_filtered_smaller_30 radius             75 : 0.09236 / 90 : 0.13749 / 95 : 0.17088 / 99 : 0.22807
                                 mass_filtered_smaller_3  radius             75 : 0.07577 / 90 : 0.10584 / 95 : 0.12563 / 99 : 0.17663
mlp               MIST           Base                     radius             75 : 0.05684 / 90 : 0.08955 / 95 : 0.12341 / 99 : 0.21087
                                 mass_filtered_smaller_30 radius             75 : 0.03488 / 90 : 0.05297 / 95 : 0.06685 / 99 : 0.10411
                                 mass_filtered_smaller_3  radius             75 : 0.02721 / 90 : 0.04163 / 95 : 0.05322 / 99 : 0.08472
random_forest     MIST           Base                     radius             75 : 0.00501 / 90 : 0.01124 / 95 : 0.01784 / 99 : 0.04031
                                 mass_filtered_smaller_30 radius             75 : 0.00495 / 90 : 0.01112 / 95 : 0.01766 / 99 : 0.03956
                                 mass_filtered_smaller_3  radius             75 : 0.00537 / 90 : 0.01318 / 95 : 0.02126 / 99 : 0.04618
xgboost           MIST           Base                     radius             75 : 0.01903 / 90 : 0.02976 / 95 : 0.03817 / 99 : 0.06037
                                 mass_filtered_smaller_30 radius             75 : 0.01737 / 90 : 0.02716 / 95 : 0.03491 / 99 : 0.05602
                                 mass_filtered_smaller_3  radius              75 : 0.0152 / 90 : 0.02523 / 95 : 0.03413 / 99 : 0.05842

                                                                                  time
model             physical_model filter                   output_parameter
decision_tree     MIST           Base                     radius              49.37920
                                 mass_filtered_smaller_30 radius              37.68671
                                 mass_filtered_smaller_3  radius              28.99948
KNN               MIST           Base                     radius              15.33600
                                 mass_filtered_smaller_30 radius              12.08859
                                 mass_filtered_smaller_3  radius              10.05766
linear_regression MIST           Base                     radius               1.00008
                                 mass_filtered_smaller_30 radius               1.19423
                                 mass_filtered_smaller_3  radius               0.61593
mlp               MIST           Base                     radius             232.75999
                                 mass_filtered_smaller_30 radius            3039.23496
                                 mass_filtered_smaller_3  radius             377.59402
random_forest     MIST           Base                     radius             942.58339
                                 mass_filtered_smaller_30 radius             875.75894
                                 mass_filtered_smaller_3  radius             387.80599
xgboost           MIST           Base                     radius              21.18033
                                 mass_filtered_smaller_30 radius              19.93498
                                 mass_filtered_smaller_3  radius              13.38120

Linear regression : 
- mass_filtered_smaller_30 : slightly better results than Base
- mass_filtered_smaller_3 : slightly better results than Base

Decision tree : 
- mass_filtered_smaller_30 : similar results as Base but worse MAX_ER
- mass_filtered_smaller_3 : slightly better results than Base

KNN : 
- mass_filtered_smaller_30 : slightly better results than Base
- mass_filtered_smaller_3 : similar results as Base

Random forest : 
- mass_filtered_smaller_30 : slightly better results than Base
- mass_filtered_smaller_3 : similar results as Base

XGBoost : 
- mass_filtered_smaller_30 : slightly better results than Base
- mass_filtered_smaller_3 : better results than Base

MLP : 
- mass_filtered_smaller_30 : better results than Base
- mass_filtered_smaller_3 : better results than Base

Linear regression : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

Decision tree : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

KNN : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

Random forest : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

XGBoost : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 : 

MLP : 
- mass_smaller_3 : 
- mass_smaller_14 : 
- mass_smaller_30 :

#### Conclusions on radius

The results of both filtering yielded are similar to Base.

&emsp; => not useful to use these filtering instead of Base

### Conclusion on both

Both parameter give similar results as Base while having the restriction on the mass that the model will be able to predict.

&emsp; => It is not useful to use this filtering instead of Base

## Final conclusion on the filters

Filtering on the log_g => not useful as the results of the two parameters go in opposite directions (when one improves, the other worsens)

Filtering on the age => age_filtered_bigger_7 improves the results of both parameters compared to Base and might be useful to use if we are fine with losing the possibility to predict for stars below 10.000.000 years

Filtering on the mass => not useful to use this filtering as it gives similar results as Base while being restricted in the kind of stars it can predict

Filtering on the phase => not useful to use this filtering as it gives similar results as Base while being restricted in the kind of stars it can predict

Filtering on the radius => not useful to use this filtering as it gives worse results than Base overall

Filtering on the Teff => not useful as the results of the two parameters go in opposite directions (when one improves, the other worsens)