# Results comparison for MIST filtering of model A partial

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_A_partial/default_models"

In [3]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                             mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9978063351241271
                             mass_smaller_3  mass              0.9992738264822424
                             mass_smaller_14 mass              0.9999006268975099
                             mass_smaller_30 mass              0.9995874506793025

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.419%  0.049%
                             mass_smaller_3  mass              0.672%  0.207%
                             mass_smaller_14 mass              0.235%  0.082%
                             mass_smaller_30 mass              0.415%  0.069%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass               0.07%
                             mass_smaller_14 mass              0.024%
                             mass_smaller_30 mass              0.012%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9989037560824912
                             mass_smaller_3  mass               0.999636894028306
                             mass_smaller_14 mass              0.9999503530371973
                             mass_smaller_30 mass              0.9997937276626583

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              32.158%
                             mass_smaller_3  mass              51.551%
                             mass_smaller_14 mass              16.749%
                             mass_smaller_30 mass              25.504%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                             mass_smaller_3  mass              75 : 0.192% / 90 : 0.427% / 95 : 0.681% / 99 : 2.322%
                             mass_smaller_14 mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
                             mass_smaller_30 mass               75 : 0.037% / 90 : 0.11% / 95 : 0.231% / 99 : 0.933%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 0.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                             mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9973661987481759
                             mass_smaller_3  mass              0.9999474983734866
                             mass_smaller_14 mass              0.9999235468255409
                             mass_smaller_30 mass               0.999521993790828

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.452%  0.056%
                             mass_smaller_3  mass              0.188%  0.094%
                             mass_smaller_14 mass              0.207%  0.063%
                             mass_smaller_30 mass              0.458%  0.077%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass              0.045%
                             mass_smaller_14 mass              0.018%
                             mass_smaller_30 mass              0.009%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9986840004415223
                             mass_smaller_3  mass              0.9999737782832668
                             mass_smaller_14 mass              0.9999617835917853
                             mass_smaller_30 mass              0.9997609878413475

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              27.991%
                             mass_smaller_3  mass               8.032%
                             mass_smaller_14 mass              16.749%
                             mass_smaller_30 mass              25.504%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              75 : 0.005% / 90 : 0.036% / 95 : 0.139% / 99 : 1.207%
                             mass_smaller_3  mass              75 : 0.107% / 90 : 0.219% / 95 : 0.331% / 99 : 0.749%
                             mass_smaller_14 mass              75 : 0.051% / 90 : 0.141% / 95 : 0.251% / 99 : 0.728%
                             mass_smaller_30 mass              75 : 0.032% / 90 : 0.112% / 95 : 0.253% / 99 : 1.248%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 2.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                             mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                             mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                             mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9997496322236138
                             mass_smaller_3  mass              0.9996443438393721
                             mass_smaller_14 mass              0.9999737930935538
                             mass_smaller_30 mass              0.9999690893306589

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.166%  0.021%
                             mass_smaller_3  mass              0.503%  0.298%
                             mass_smaller_14 mass              0.126%  0.063%
                             mass_smaller_30 mass              0.114%  0.029%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass              0.188%
                             mass_smaller_14 mass              0.033%
                             mass_smaller_30 mass              0.013%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9998754804643019
                             mass_smaller_3  mass              0.9998265900407789
                             mass_smaller_14 mass               0.999987052162877
                             mass_smaller_30 mass               0.999984609078679

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               8.119%
                             mass_smaller_3  mass               9.114%
                             mass_smaller_14 mass               3.642%
                             mass_smaller_30 mass              13.669%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.004% / 90 : 0.009% / 95 : 0.026% / 99 : 0.48%
                             mass_smaller_3  mass              75 : 0.393% / 90 : 0.672% / 95 : 0.904% / 99 : 1.705%
                             mass_smaller_14 mass              75 : 0.076% / 90 : 0.143% / 95 : 0.211% / 99 : 0.515%
                             mass_smaller_30 mass              75 : 0.032% / 90 : 0.061% / 95 : 0.093% / 99 : 0.235%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 3.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                0.5484495344916944 - 288.814589557117
                             mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                             mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                             mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9949439900825313
                             mass_smaller_3  mass              0.9954521777596107
                             mass_smaller_14 mass              0.9997284223560081
                             mass_smaller_30 mass              0.9992635983495934

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.572%   0.07%
                             mass_smaller_3  mass              1.718%  0.602%
                             mass_smaller_14 mass              0.395%  0.173%
                             mass_smaller_30 mass              0.548%  0.103%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.002%
                             mass_smaller_3  mass              0.151%
                             mass_smaller_14 mass              0.044%
                             mass_smaller_30 mass               0.02%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9975811556691733
                             mass_smaller_3  mass              0.9977358261257694
                             mass_smaller_14 mass              0.9998659386279564
                             mass_smaller_30 mass              0.9996323346107105

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              33.293%
                             mass_smaller_3  mass              60.907%
                             mass_smaller_14 mass               9.617%
                             mass_smaller_30 mass              25.403%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01% / 90 : 0.037% / 95 : 0.102% / 99 : 1.625%
                             mass_smaller_3  mass              75 : 0.457% / 90 : 1.258% / 95 : 2.669% / 99 : 8.475%
                             mass_smaller_14 mass              75 : 0.163% / 90 : 0.478% / 95 : 0.808% / 99 : 1.802%
                             mass_smaller_30 mass               75 : 0.073% / 90 : 0.22% / 95 : 0.382% / 99 : 0.985%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

In [8]:
compare_metrics(path, value_rounding=3,
                output_parameters=["mass", "radius"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129
KNN               MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129
linear_regression MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129
mlp               MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129
random_forest     MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129
xgboost           MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.129

                                                            RVE    RMSE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.995   1.837
                                        radius            1.000   0.011
KNN               MIST           Base   mass              0.990   2.726
                                        radius            1.000   0.007
linear_regression MIST           Base   mass              0.304  22.280
                                        radius            0.985   0.089
mlp               MIST           Base   mass              0.976   4.121
                                        radius            0.992   0.066
random_forest     MIST           Base   mass              0.998   1.251
                                        radius            1.000   0.006
xgboost           MIST           Base   mass              0.994   2.048
                                        radius            1.000   0.015

                                                             MAE  MedAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.200  0.003
                                        radius             0.006  0.003
KNN               MIST           Base   mass               0.328  0.008
                                        radius             0.004  0.003
linear_regression MIST           Base   mass              11.345  8.154
                                        radius             0.065  0.046
mlp               MIST           Base   mass               1.261  0.343
                                        radius             0.050  0.040
random_forest     MIST           Base   mass               0.145  0.004
                                        radius             0.003  0.001
xgboost           MIST           Base   mass               0.531  0.099
                                        radius             0.011  0.008

                                                           CORR   MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.998  151.658
                                        radius            1.000    0.478
KNN               MIST           Base   mass              0.995  144.214
                                        radius            1.000    0.307
linear_regression MIST           Base   mass              0.552  257.508
                                        radius            0.993    0.525
mlp               MIST           Base   mass              0.988  174.796
                                        radius            0.996    0.581
random_forest     MIST           Base   mass              0.999   95.973
                                        radius            1.000    0.358
xgboost           MIST           Base   mass              0.997   72.954
                                        radius            1.000    0.490

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.01985 / 90 : 0.10454 / 95 : 0.35331 / 99 : 4.56376
                                        radius                   75 : 0.00721 / 90 : 0.013 / 95 : 0.01829 / 99 : 0.04024
KNN               MIST           Base   mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                        radius                 75 : 0.00513 / 90 : 0.00921 / 95 : 0.01275 / 99 : 0.02703
linear_regression MIST           Base   mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                        radius                 75 : 0.08959 / 90 : 0.13937 / 95 : 0.17556 / 99 : 0.30046
mlp               MIST           Base   mass                  75 : 0.72117 / 90 : 2.44631 / 95 : 5.24067 / 99 : 18.77727
                                        radius                  75 : 0.0702 / 90 : 0.10653 / 95 : 0.13126 / 99 : 0.19313
random_forest     MIST           Base   mass                   75 : 0.01557 / 90 : 0.07872 / 95 : 0.29091 / 99 : 3.19321
                                        radius                 75 : 0.00311 / 90 : 0.00627 / 95 : 0.00939 / 99 : 0.02061
xgboost           MIST           Base   mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                        radius                  75 : 0.0146 / 90 : 0.02253 / 95 : 0.02856 / 99 : 0.04454

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               24.898
                                        radius             24.898
KNN               MIST           Base   mass                8.372
                                        radius              8.372
linear_regression MIST           Base   mass                0.634
                                        radius              0.634
mlp               MIST           Base   mass              259.791
                                        radius            259.791
random_forest     MIST           Base   mass              343.663
                                        radius            343.663
xgboost           MIST           Base   mass               11.712
                                        radius             11.712

Results for the phase category with a value of 0.0

                                                             value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083
KNN               MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083
linear_regression MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083
mlp               MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083
random_forest     MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083
xgboost           MIST           Base   mass               0.1 - 298.545
                                        radius            -0.997 - 3.083

                                                            RVE    RMSE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.994   2.098
                                        radius            1.000   0.008
KNN               MIST           Base   mass              0.984   3.292
                                        radius            1.000   0.007
linear_regression MIST           Base   mass              0.273  22.430
                                        radius            0.978   0.085
mlp               MIST           Base   mass              0.972   4.430
                                        radius            0.987   0.065
random_forest     MIST           Base   mass              0.997   1.350
                                        radius            1.000   0.004
xgboost           MIST           Base   mass              0.991   2.494
                                        radius            0.999   0.014

                                                             MAE   MedAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.270   0.006
                                        radius             0.005   0.003
KNN               MIST           Base   mass               0.432   0.010
                                        radius             0.004   0.003
linear_regression MIST           Base   mass              13.108  11.253
                                        radius             0.066   0.052
mlp               MIST           Base   mass               1.394   0.369
                                        radius             0.050   0.039
random_forest     MIST           Base   mass               0.168   0.004
                                        radius             0.002   0.001
xgboost           MIST           Base   mass               0.677   0.126
                                        radius             0.010   0.007

                                                           CORR   MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.997  131.775
                                        radius            1.000    0.478
KNN               MIST           Base   mass              0.992  126.674
                                        radius            1.000    0.154
linear_regression MIST           Base   mass              0.534  257.508
                                        radius            0.989    0.458
mlp               MIST           Base   mass              0.986  109.716
                                        radius            0.994    0.409
random_forest     MIST           Base   mass              0.999   83.538
                                        radius            1.000    0.358
xgboost           MIST           Base   mass              0.996   72.954
                                        radius            1.000    0.136

                                                                                                               Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                    75 : 0.03086 / 90 : 0.18595 / 95 : 0.67453 / 99 : 5.94846
                                        radius                  75 : 0.00534 / 90 : 0.01028 / 95 : 0.01519 / 99 : 0.03251
KNN               MIST           Base   mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                        radius                   75 : 0.00518 / 90 : 0.00955 / 95 : 0.01355 / 99 : 0.0264
linear_regression MIST           Base   mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                        radius                    75 : 0.0962 / 90 : 0.1347 / 95 : 0.15728 / 99 : 0.25052
mlp               MIST           Base   mass                    75 : 0.83625 / 90 : 2.8714 / 95 : 5.89846 / 99 : 19.76113
                                        radius                  75 : 0.06805 / 90 : 0.10506 / 95 : 0.13268 / 99 : 0.19638
random_forest     MIST           Base   mass                    75 : 0.01628 / 90 : 0.10798 / 95 : 0.41573 / 99 : 3.60316
                                        radius                    75 : 0.00232 / 90 : 0.00485 / 95 : 0.0075 / 99 : 0.0165
xgboost           MIST           Base   mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                        radius                  75 : 0.01364 / 90 : 0.02151 / 95 : 0.02755 / 99 : 0.04225

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               24.898
                                        radius             24.898
KNN               MIST           Base   mass                8.372
                                        radius              8.372
linear_regression MIST           Base   mass                0.634
                                        radius              0.634
mlp               MIST           Base   mass              259.791
                                        radius            259.791
random_forest     MIST           Base   mass              343.663
                                        radius            343.663
xgboost           MIST           Base   mass               11.712
                                        radius             11.712

Results for the phase category with a value of 2.0

                                                              value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892
KNN               MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892
linear_regression MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892
mlp               MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892
random_forest     MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892
xgboost           MIST           Base   mass              0.654 - 283.721
                                        radius              0.092 - 2.892

                                                            RVE    RMSE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.999   0.795
                                        radius            1.000   0.010
KNN               MIST           Base   mass              0.999   0.737
                                        radius            1.000   0.005
linear_regression MIST           Base   mass              0.317  24.543
                                        radius            0.968   0.088
mlp               MIST           Base   mass              0.991   2.831
                                        radius            0.985   0.063
random_forest     MIST           Base   mass              1.000   0.470
                                        radius            1.000   0.004
xgboost           MIST           Base   mass              0.999   0.996
                                        radius            0.999   0.014

                                                             MAE  MedAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.060  0.000
                                        radius             0.007  0.005
KNN               MIST           Base   mass               0.095  0.004
                                        radius             0.003  0.003
linear_regression MIST           Base   mass              10.236  5.268
                                        radius             0.058  0.034
mlp               MIST           Base   mass               0.916  0.301
                                        radius             0.049  0.040
random_forest     MIST           Base   mass               0.059  0.004
                                        radius             0.003  0.002
xgboost           MIST           Base   mass               0.293  0.071
                                        radius             0.011  0.009

                                                           CORR   MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              1.000  105.861
                                        radius            1.000    0.184
KNN               MIST           Base   mass              1.000   37.487
                                        radius            1.000    0.077
linear_regression MIST           Base   mass              0.596  247.133
                                        radius            0.984    0.453
mlp               MIST           Base   mass              0.996   64.984
                                        radius            0.993    0.369
random_forest     MIST           Base   mass              1.000   22.981
                                        radius            1.000    0.091
xgboost           MIST           Base   mass              0.999   39.121
                                        radius            1.000    0.074

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.00549 / 90 : 0.02551 / 95 : 0.04546 / 99 : 0.75464
                                        radius                  75 : 0.00908 / 90 : 0.01345 / 95 : 0.01659 / 99 : 0.0315
KNN               MIST           Base   mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                        radius                 75 : 0.00469 / 90 : 0.00772 / 95 : 0.00978 / 99 : 0.01453
linear_regression MIST           Base   mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                        radius                   75 : 0.0735 / 90 : 0.1413 / 95 : 0.19408 / 99 : 0.35002
mlp               MIST           Base   mass                  75 : 0.57683 / 90 : 1.68666 / 95 : 3.72863 / 99 : 12.95924
                                        radius                 75 : 0.07103 / 90 : 0.10402 / 95 : 0.12406 / 99 : 0.17082
random_forest     MIST           Base   mass                    75 : 0.01059 / 90 : 0.02554 / 95 : 0.07295 / 99 : 1.3585
                                        radius                 75 : 0.00359 / 90 : 0.00617 / 95 : 0.00828 / 99 : 0.01406
xgboost           MIST           Base   mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                        radius                 75 : 0.01514 / 90 : 0.02219 / 95 : 0.02704 / 99 : 0.03759

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               24.898
                                        radius             24.898
KNN               MIST           Base   mass                8.372
                                        radius              8.372
linear_regression MIST           Base   mass                0.634
                                        radius              0.634
mlp               MIST           Base   mass              259.791
                                        radius            259.791
random_forest     MIST           Base   mass              343.663
                                        radius            343.663
xgboost           MIST           Base   mass               11.712
                                        radius             11.712

Results for the phase category with a value of 3.0

                                                              value range  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129
KNN               MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129
linear_regression MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129
mlp               MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129
random_forest     MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129
xgboost           MIST           Base   mass              0.548 - 288.815
                                        radius             -0.345 - 3.129

                                                            RVE    RMSE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.992   2.077
                                        radius            0.999   0.016
KNN               MIST           Base   mass              0.986   2.735
                                        radius            1.000   0.010
linear_regression MIST           Base   mass              0.388  18.164
                                        radius            0.970   0.100
mlp               MIST           Base   mass              0.959   4.701
                                        radius            0.985   0.071
random_forest     MIST           Base   mass              0.995   1.648
                                        radius            1.000   0.009
xgboost           MIST           Base   mass              0.994   1.730
                                        radius            0.999   0.019

                                                            MAE  MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.200  0.004  0.996
                                        radius            0.008  0.004  1.000
KNN               MIST           Base   mass              0.364  0.010  0.993
                                        radius            0.005  0.003  1.000
linear_regression MIST           Base   mass              7.961  4.599  0.650
                                        radius            0.070  0.046  0.985
mlp               MIST           Base   mass              1.368  0.332  0.980
                                        radius            0.054  0.042  0.992
random_forest     MIST           Base   mass              0.201  0.007  0.998
                                        radius            0.004  0.002  1.000
xgboost           MIST           Base   mass              0.451  0.094  0.997
                                        radius            0.013  0.009  0.999

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              151.658
                                        radius              0.385
KNN               MIST           Base   mass              144.214
                                        radius              0.307
linear_regression MIST           Base   mass              250.918
                                        radius              0.525
mlp               MIST           Base   mass              174.796
                                        radius              0.581
random_forest     MIST           Base   mass               95.973
                                        radius              0.301
xgboost           MIST           Base   mass               61.887
                                        radius              0.490

                                                                                                             Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                  75 : 0.02357 / 90 : 0.11188 / 95 : 0.26917 / 99 : 4.64103
                                        radius                75 : 0.00936 / 90 : 0.01845 / 95 : 0.02898 / 99 : 0.06739
KNN               MIST           Base   mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                        radius                75 : 0.00589 / 90 : 0.01098 / 95 : 0.01632 / 99 : 0.04576
linear_regression MIST           Base   mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                        radius                75 : 0.08613 / 90 : 0.16865 / 95 : 0.22602 / 99 : 0.32909
mlp               MIST           Base   mass                  75 : 0.6942 / 90 : 2.40557 / 95 : 5.75475 / 99 : 22.29219
                                        radius                    75 : 0.0756 / 90 : 0.11352 / 95 : 0.13849 / 99 : 0.21
random_forest     MIST           Base   mass                     75 : 0.02891 / 90 : 0.1076 / 95 : 0.29511 / 99 : 4.683
                                        radius                75 : 0.00501 / 90 : 0.01036 / 95 : 0.01595 / 99 : 0.04157
xgboost           MIST           Base   mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                        radius                75 : 0.01645 / 90 : 0.02595 / 95 : 0.03406 / 99 : 0.06632

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               24.898
                                        radius             24.898
KNN               MIST           Base   mass                8.372
                                        radius              8.372
linear_regression MIST           Base   mass                0.634
                                        radius              0.634
mlp               MIST           Base   mass              259.791
                                        radius            259.791
random_forest     MIST           Base   mass              343.663
                                        radius            343.663
xgboost           MIST           Base   mass               11.712
                                        radius             11.712

## Getting the ranges for the values

In [3]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Comparing each model's results to keep the best ones with MIST dataset

### Linear regression

#### Mass parameter

In [5]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                       value range  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass              0.1 - 298.545
                                 mass_smaller_14   mass               0.1 - 13.999
                                 mass_smaller_3    mass                  0.1 - 3.0
                                 mass_smaller_30   mass               0.1 - 29.998
                                 scale_power       mass              0.1 - 298.545
                                 scale_power_14    mass               0.1 - 13.999
                                 scale_quantile    mass              0.1 - 298.545
                                 scale_quantile_14 mass               0.1 - 13.999
                                 scale_robust      mass              0.1 - 298.545
                                 scale_robust_14   mass               0.1 - 13.999
                                 scale_standard    mass              0.1 - 298.545
                                 scale_standard_14 mass               0.1 - 13.999

                                                                       RVE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass              0.304
                                 mass_smaller_14   mass              0.725
                                 mass_smaller_3    mass              0.767
                                 mass_smaller_30   mass              0.642
                                 scale_power       mass              0.277
                                 scale_power_14    mass              0.683
                                 scale_quantile    mass              0.273
                                 scale_quantile_14 mass              0.683
                                 scale_robust      mass              0.304
                                 scale_robust_14   mass              0.725
                                 scale_standard    mass              0.304
                                 scale_standard_14 mass              0.725

                                                                        RMSE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass               7.465%
                                 mass_smaller_14   mass              12.351%
                                 mass_smaller_3    mass              12.023%
                                 mass_smaller_30   mass              12.239%
                                 scale_power       mass                7.61%
                                 scale_power_14    mass              13.269%
                                 scale_quantile    mass                7.63%
                                 scale_quantile_14 mass               13.26%
                                 scale_robust      mass               7.465%
                                 scale_robust_14   mass              12.351%
                                 scale_standard    mass               7.465%
                                 scale_standard_14 mass              12.351%

                                                                         MAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass               3.801%
                                 mass_smaller_14   mass               9.338%
                                 mass_smaller_3    mass               9.153%
                                 mass_smaller_30   mass               8.741%
                                 scale_power       mass               3.899%
                                 scale_power_14    mass              10.002%
                                 scale_quantile    mass               3.917%
                                 scale_quantile_14 mass               9.818%
                                 scale_robust      mass               3.801%
                                 scale_robust_14   mass               9.338%
                                 scale_standard    mass               3.801%
                                 scale_standard_14 mass               9.338%

                                                                      MedAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass              2.732%
                                 mass_smaller_14   mass              7.035%
                                 mass_smaller_3    mass              7.177%
                                 mass_smaller_30   mass              6.762%
                                 scale_power       mass              2.901%
                                 scale_power_14    mass              7.702%
                                 scale_quantile    mass              2.916%
                                 scale_quantile_14 mass              7.305%
                                 scale_robust      mass              2.732%
                                 scale_robust_14   mass              7.035%
                                 scale_standard    mass              2.732%
                                 scale_standard_14 mass              7.035%

                                                                      CORR  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass              0.552
                                 mass_smaller_14   mass              0.852
                                 mass_smaller_3    mass              0.876
                                 mass_smaller_30   mass              0.801
                                 scale_power       mass              0.526
                                 scale_power_14    mass              0.826
                                 scale_quantile    mass              0.523
                                 scale_quantile_14 mass              0.827
                                 scale_robust      mass              0.552
                                 scale_robust_14   mass              0.852
                                 scale_standard    mass              0.552
                                 scale_standard_14 mass              0.852

                                                                      MAX_ER  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass              86.283%
                                 mass_smaller_14   mass              55.541%
                                 mass_smaller_3    mass              62.539%
                                 mass_smaller_30   mass              63.958%
                                 scale_power       mass              88.276%
                                 scale_power_14    mass              55.996%
                                 scale_quantile    mass              89.019%
                                 scale_quantile_14 mass              55.134%
                                 scale_robust      mass              86.283%
                                 scale_robust_14   mass              55.541%
                                 scale_standard    mass              86.283%
                                 scale_standard_14 mass              55.541%

                                                                                                                   Percentiles  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass                 75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 mass_smaller_14   mass               75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%
                                 mass_smaller_3    mass              75 : 12.857% / 90 : 19.584% / 95 : 24.212% / 99 : 36.792%
                                 mass_smaller_30   mass                75 : 10.98% / 90 : 16.99% / 95 : 23.919% / 99 : 48.156%
                                 scale_power       mass                  75 : 4.491% / 90 : 5.962% / 95 : 7.33% / 99 : 36.261%
                                 scale_power_14    mass              75 : 12.765% / 90 : 21.633% / 95 : 27.077% / 99 : 43.312%
                                 scale_quantile    mass                 75 : 4.442% / 90 : 6.007% / 95 : 6.993% / 99 : 36.339%
                                 scale_quantile_14 mass                75 : 12.81% / 90 : 22.21% / 95 : 27.928% / 99 : 42.876%
                                 scale_robust      mass                 75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 scale_robust_14   mass               75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%
                                 scale_standard    mass                 75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 scale_standard_14 mass               75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%

                                                                       time
model             physical_model filter            output_parameter
linear_regression MIST           Base              mass               0.634
                                 mass_smaller_14   mass               0.461
                                 mass_smaller_3    mass               0.285
                                 mass_smaller_30   mass               0.524
                                 scale_power       mass              13.065
                                 scale_power_14    mass              11.723
                                 scale_quantile    mass               2.775
                                 scale_quantile_14 mass               2.143
                                 scale_robust      mass               1.277
                                 scale_robust_14   mass               1.132
                                 scale_standard    mass               0.856
                                 scale_standard_14 mass               0.712

Aucun modèle n'est vraiment très performant. mass_smaller_14 donne les meilleurs résultats => MAX_ER, RMSE et percentiles dans les plus bas

#### Radius parameter

In [22]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                        value range  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            -0.997 - 3.129
                                 mass_smaller_14   radius            -0.997 - 3.082
                                 mass_smaller_3    radius            -0.997 - 2.781
                                 mass_smaller_30   radius             -0.997 - 3.13
                                 scale_power       radius            -0.997 - 3.129
                                 scale_power_14    radius            -0.997 - 3.082
                                 scale_quantile    radius            -0.997 - 3.129
                                 scale_quantile_14 radius            -0.997 - 3.082
                                 scale_robust      radius            -0.997 - 3.129
                                 scale_robust_14   radius            -0.997 - 3.082
                                 scale_standard    radius            -0.997 - 3.129
                                 scale_standard_14 radius            -0.997 - 3.082

                                                                       RVE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            0.985
                                 mass_smaller_14   radius            0.992
                                 mass_smaller_3    radius            0.993
                                 mass_smaller_30   radius            0.991
                                 scale_power       radius            0.965
                                 scale_power_14    radius            0.972
                                 scale_quantile    radius            0.942
                                 scale_quantile_14 radius            0.948
                                 scale_robust      radius            0.985
                                 scale_robust_14   radius            0.992
                                 scale_standard    radius            0.985
                                 scale_standard_14 radius            0.992

                                                                       RMSE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            2.154%
                                 mass_smaller_14   radius            1.586%
                                 mass_smaller_3    radius            1.558%
                                 mass_smaller_30   radius            1.617%
                                 scale_power       radius            3.329%
                                 scale_power_14    radius            2.867%
                                 scale_quantile    radius             4.29%
                                 scale_quantile_14 radius            3.954%
                                 scale_robust      radius            2.154%
                                 scale_robust_14   radius            1.586%
                                 scale_standard    radius            2.154%
                                 scale_standard_14 radius            1.586%

                                                                        MAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            1.569%
                                 mass_smaller_14   radius            1.206%
                                 mass_smaller_3    radius             1.17%
                                 mass_smaller_30   radius            1.231%
                                 scale_power       radius            2.546%
                                 scale_power_14    radius            2.132%
                                 scale_quantile    radius            3.259%
                                 scale_quantile_14 radius            2.831%
                                 scale_robust      radius            1.569%
                                 scale_robust_14   radius            1.206%
                                 scale_standard    radius            1.569%
                                 scale_standard_14 radius            1.206%

                                                                      MedAE  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            1.113%
                                 mass_smaller_14   radius            0.976%
                                 mass_smaller_3    radius            0.887%
                                 mass_smaller_30   radius            0.983%
                                 scale_power       radius             2.18%
                                 scale_power_14    radius            1.878%
                                 scale_quantile    radius              2.7%
                                 scale_quantile_14 radius            2.168%
                                 scale_robust      radius            1.113%
                                 scale_robust_14   radius            0.976%
                                 scale_standard    radius            1.113%
                                 scale_standard_14 radius            0.976%

                                                                      CORR  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            0.993
                                 mass_smaller_14   radius            0.996
                                 mass_smaller_3    radius            0.996
                                 mass_smaller_30   radius            0.996
                                 scale_power       radius            0.983
                                 scale_power_14    radius            0.986
                                 scale_quantile    radius            0.971
                                 scale_quantile_14 radius            0.973
                                 scale_robust      radius            0.993
                                 scale_robust_14   radius            0.996
                                 scale_standard    radius            0.993
                                 scale_standard_14 radius            0.996

                                                                      MAX_ER  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius            12.724%
                                 mass_smaller_14   radius            11.805%
                                 mass_smaller_3    radius            10.931%
                                 mass_smaller_30   radius            12.019%
                                 scale_power       radius            24.305%
                                 scale_power_14    radius            20.728%
                                 scale_quantile    radius            27.221%
                                 scale_quantile_14 radius            27.413%
                                 scale_robust      radius            12.724%
                                 scale_robust_14   radius            11.805%
                                 scale_standard    radius            12.724%
                                 scale_standard_14 radius            11.805%

                                                                                                                Percentiles  \
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 mass_smaller_14   radius              75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
                                 mass_smaller_3    radius              75 : 1.64% / 90 : 2.621% / 95 : 3.242% / 99 : 4.505%
                                 mass_smaller_30   radius             75 : 1.822% / 90 : 2.598% / 95 : 3.113% / 99 : 4.567%
                                 scale_power       radius            75 : 3.351% / 90 : 4.771% / 95 : 6.172% / 99 : 11.163%
                                 scale_power_14    radius            75 : 2.858% / 90 : 3.592% / 95 : 4.568% / 99 : 11.401%
                                 scale_quantile    radius            75 : 4.205% / 90 : 6.382% / 95 : 8.174% / 99 : 14.668%
                                 scale_quantile_14 radius            75 : 3.562% / 90 : 5.729% / 95 : 7.721% / 99 : 15.507%
                                 scale_robust      radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 scale_robust_14   radius              75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
                                 scale_standard    radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 scale_standard_14 radius              75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%

                                                                       time
model             physical_model filter            output_parameter
linear_regression MIST           Base              radius             0.634
                                 mass_smaller_14   radius             0.461
                                 mass_smaller_3    radius             0.285
                                 mass_smaller_30   radius             0.524
                                 scale_power       radius            13.065
                                 scale_power_14    radius            11.723
                                 scale_quantile    radius             2.775
                                 scale_quantile_14 radius             2.143
                                 scale_robust      radius             1.277
                                 scale_robust_14   radius             1.132
                                 scale_standard    radius             0.856
                                 scale_standard_14 radius             0.712

Aucun modèle n'est vraiment très performant. mass_smaller_14 et mass_smaller_3 donne les meilleurs résultats

#### Filtre choisi

Le filtre mass_smaller_14 est choisi parce qu'il donne les meilleurs résultats pour la masse et est l'un des deux meilleurs filtre pour le rayon.

linear_regression	MIST	mass_smaller_14	mass	0.1 - 13.999	0.725	12.351%	9.338%	7.035%	0.852	55.541%	75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%	0.461

linear_regression	MIST	mass_smaller_14	radius	-0.997 - 3.082	0.992	1.586%	1.206%	0.976%	0.996	11.805%	75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%	0.461

### Decision tree

#### Mass parameter

In [7]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                   value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.1 - 298.545
                             mass_smaller_14   mass               0.1 - 13.999
                             mass_smaller_3    mass                  0.1 - 3.0
                             mass_smaller_30   mass               0.1 - 29.998
                             scale_power       mass              0.1 - 298.545
                             scale_power_14    mass               0.1 - 13.999
                             scale_quantile    mass              0.1 - 298.545
                             scale_quantile_14 mass               0.1 - 13.999
                             scale_robust      mass              0.1 - 298.545
                             scale_robust_14   mass               0.1 - 13.999
                             scale_standard    mass              0.1 - 298.545
                             scale_standard_14 mass               0.1 - 13.999

                                                                   RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.995
                             mass_smaller_14   mass              1.000
                             mass_smaller_3    mass              0.999
                             mass_smaller_30   mass              0.999
                             scale_power       mass              0.995
                             scale_power_14    mass              1.000
                             scale_quantile    mass              0.995
                             scale_quantile_14 mass              1.000
                             scale_robust      mass              0.995
                             scale_robust_14   mass              1.000
                             scale_standard    mass              0.995
                             scale_standard_14 mass              1.000

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.615%
                             mass_smaller_14   mass               0.37%
                             mass_smaller_3    mass              0.916%
                             mass_smaller_30   mass              0.614%
                             scale_power       mass              0.614%
                             scale_power_14    mass              0.371%
                             scale_quantile    mass              0.614%
                             scale_quantile_14 mass              0.371%
                             scale_robust      mass              0.617%
                             scale_robust_14   mass              0.372%
                             scale_standard    mass              0.619%
                             scale_standard_14 mass              0.372%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.067%
                             mass_smaller_14   mass              0.117%
                             mass_smaller_3    mass              0.274%
                             mass_smaller_30   mass              0.096%
                             scale_power       mass              0.067%
                             scale_power_14    mass              0.118%
                             scale_quantile    mass              0.067%
                             scale_quantile_14 mass              0.118%
                             scale_robust      mass              0.067%
                             scale_robust_14   mass              0.117%
                             scale_standard    mass              0.067%
                             scale_standard_14 mass              0.118%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.001%
                             mass_smaller_14   mass               0.02%
                             mass_smaller_3    mass              0.075%
                             mass_smaller_30   mass               0.01%
                             scale_power       mass              0.001%
                             scale_power_14    mass               0.02%
                             scale_quantile    mass              0.001%
                             scale_quantile_14 mass               0.02%
                             scale_robust      mass              0.001%
                             scale_robust_14   mass               0.02%
                             scale_standard    mass              0.001%
                             scale_standard_14 mass               0.02%

                                                                  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.998
                             mass_smaller_14   mass              1.000
                             mass_smaller_3    mass              0.999
                             mass_smaller_30   mass              1.000
                             scale_power       mass              0.998
                             scale_power_14    mass              1.000
                             scale_quantile    mass              0.998
                             scale_quantile_14 mass              1.000
                             scale_robust      mass              0.998
                             scale_robust_14   mass              1.000
                             scale_standard    mass              0.998
                             scale_standard_14 mass              1.000

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              50.816%
                             mass_smaller_14   mass              36.812%
                             mass_smaller_3    mass              59.391%
                             mass_smaller_30   mass              51.978%
                             scale_power       mass              50.816%
                             scale_power_14    mass              36.365%
                             scale_quantile    mass              50.816%
                             scale_quantile_14 mass              36.812%
                             scale_robust      mass              49.742%
                             scale_robust_14   mass              36.812%
                             scale_standard    mass              50.816%
                             scale_standard_14 mass              36.365%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                             mass_smaller_14   mass              75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
                             mass_smaller_3    mass              75 : 0.232% / 90 : 0.611% / 95 : 1.042% / 99 : 2.973%
                             mass_smaller_30   mass              75 : 0.048% / 90 : 0.172% / 95 : 0.365% / 99 : 1.264%
                             scale_power       mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.512%
                             scale_power_14    mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.606%
                             scale_quantile    mass               75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.52%
                             scale_quantile_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.601%
                             scale_robust      mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.524%
                             scale_robust_14   mass              75 : 0.087% / 90 : 0.275% / 95 : 0.527% / 99 : 1.595%
                             scale_standard    mass              75 : 0.007% / 90 : 0.035% / 95 : 0.119% / 99 : 1.525%
                             scale_standard_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.529% / 99 : 1.597%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              24.898
                             mass_smaller_14   mass              18.880
                             mass_smaller_3    mass              11.537
                             mass_smaller_30   mass              21.883
                             scale_power       mass              35.473
                             scale_power_14    mass              27.995
                             scale_quantile    mass              26.211
                             scale_quantile_14 mass              20.181
                             scale_robust      mass              28.477
                             scale_robust_14   mass              20.087
                             scale_standard    mass              22.573
                             scale_standard_14 mass              18.010

Filtre mass_smaller_14 donne les meilleurs résultats

In [12]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              0.1 - 13.999
                             scale_standard_14 mass              0.1 - 13.999
                             scale_robust_14   mass              0.1 - 13.999
                             scale_quantile_14 mass              0.1 - 13.999
                             scale_power_14    mass              0.1 - 13.999

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              1.0   0.37%
                             scale_standard_14 mass              1.0  0.372%
                             scale_robust_14   mass              1.0  0.372%
                             scale_quantile_14 mass              1.0  0.371%
                             scale_power_14    mass              1.0  0.371%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              0.117%
                             scale_standard_14 mass              0.118%
                             scale_robust_14   mass              0.117%
                             scale_quantile_14 mass              0.118%
                             scale_power_14    mass              0.118%

                                                                 MedAE  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              0.02%   1.0
                             scale_standard_14 mass              0.02%   1.0
                             scale_robust_14   mass              0.02%   1.0
                             scale_quantile_14 mass              0.02%   1.0
                             scale_power_14    mass              0.02%   1.0

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              36.812%
                             scale_standard_14 mass              36.365%
                             scale_robust_14   mass              36.812%
                             scale_quantile_14 mass              36.812%
                             scale_power_14    mass              36.365%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
                             scale_standard_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.529% / 99 : 1.597%
                             scale_robust_14   mass              75 : 0.087% / 90 : 0.275% / 95 : 0.527% / 99 : 1.595%
                             scale_quantile_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.601%
                             scale_power_14    mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.606%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   mass              18.880
                             scale_standard_14 mass              18.010
                             scale_robust_14   mass              20.087
                             scale_quantile_14 mass              20.181
                             scale_power_14    mass              27.995

Le scaling n'améliore pas significativement les résultats, tous les scaling peuvent être utilisé si besoin.

#### Radius parameter

In [6]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            -0.997 - 3.129
                             mass_smaller_14   radius            -0.997 - 3.082
                             mass_smaller_3    radius            -0.997 - 2.781
                             mass_smaller_30   radius             -0.997 - 3.13
                             scale_power       radius            -0.997 - 3.129
                             scale_power_14    radius            -0.997 - 3.082
                             scale_quantile    radius            -0.997 - 3.129
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_robust      radius            -0.997 - 3.129
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_standard    radius            -0.997 - 3.129
                             scale_standard_14 radius            -0.997 - 3.082

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            1.0  0.255%
                             mass_smaller_14   radius            1.0  0.226%
                             mass_smaller_3    radius            1.0  0.213%
                             mass_smaller_30   radius            1.0  0.232%
                             scale_power       radius            1.0  0.256%
                             scale_power_14    radius            1.0  0.227%
                             scale_quantile    radius            1.0  0.253%
                             scale_quantile_14 radius            1.0  0.228%
                             scale_robust      radius            1.0  0.255%
                             scale_robust_14   radius            1.0  0.226%
                             scale_standard    radius            1.0  0.255%
                             scale_standard_14 radius            1.0  0.226%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            0.142%
                             mass_smaller_14   radius            0.131%
                             mass_smaller_3    radius            0.118%
                             mass_smaller_30   radius            0.132%
                             scale_power       radius            0.141%
                             scale_power_14    radius            0.131%
                             scale_quantile    radius            0.141%
                             scale_quantile_14 radius            0.131%
                             scale_robust      radius            0.142%
                             scale_robust_14   radius             0.13%
                             scale_standard    radius            0.142%
                             scale_standard_14 radius            0.131%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            0.082%   1.0
                             mass_smaller_14   radius            0.077%   1.0
                             mass_smaller_3    radius            0.066%   1.0
                             mass_smaller_30   radius            0.078%   1.0
                             scale_power       radius            0.082%   1.0
                             scale_power_14    radius            0.077%   1.0
                             scale_quantile    radius            0.082%   1.0
                             scale_quantile_14 radius            0.078%   1.0
                             scale_robust      radius            0.082%   1.0
                             scale_robust_14   radius            0.077%   1.0
                             scale_standard    radius            0.082%   1.0
                             scale_standard_14 radius            0.077%   1.0

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            11.591%
                             mass_smaller_14   radius            10.289%
                             mass_smaller_3    radius             4.519%
                             mass_smaller_30   radius            17.115%
                             scale_power       radius            11.824%
                             scale_power_14    radius             9.234%
                             scale_quantile    radius            11.591%
                             scale_quantile_14 radius            10.924%
                             scale_robust      radius            11.591%
                             scale_robust_14   radius             9.234%
                             scale_standard    radius            11.591%
                             scale_standard_14 radius            10.924%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            75 : 0.175% / 90 : 0.315% / 95 : 0.443% / 99 : 0.975%
                             mass_smaller_14   radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
                             mass_smaller_3    radius            75 : 0.149% / 90 : 0.294% / 95 : 0.373% / 99 : 0.762%
                             mass_smaller_30   radius            75 : 0.166% / 90 : 0.301% / 95 : 0.404% / 99 : 0.866%
                             scale_power       radius            75 : 0.175% / 90 : 0.315% / 95 : 0.442% / 99 : 0.973%
                             scale_power_14    radius              75 : 0.165% / 90 : 0.3% / 95 : 0.396% / 99 : 0.853%
                             scale_quantile    radius            75 : 0.175% / 90 : 0.315% / 95 : 0.442% / 99 : 0.972%
                             scale_quantile_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.857%
                             scale_robust      radius            75 : 0.175% / 90 : 0.315% / 95 : 0.444% / 99 : 0.974%
                             scale_robust_14   radius              75 : 0.165% / 90 : 0.3% / 95 : 0.395% / 99 : 0.854%
                             scale_standard    radius            75 : 0.175% / 90 : 0.315% / 95 : 0.444% / 99 : 0.973%
                             scale_standard_14 radius              75 : 0.165% / 90 : 0.3% / 95 : 0.397% / 99 : 0.854%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           Base              radius            24.898
                             mass_smaller_14   radius            18.880
                             mass_smaller_3    radius            11.537
                             mass_smaller_30   radius            21.883
                             scale_power       radius            35.473
                             scale_power_14    radius            27.995
                             scale_quantile    radius            26.211
                             scale_quantile_14 radius            20.181
                             scale_robust      radius            28.477
                             scale_robust_14   radius            20.087
                             scale_standard    radius            22.573
                             scale_standard_14 radius            18.010

Le meilleur filtre est mass_smaller_3 mais le résultat pour la masse n'est pas bon avec celui-là, il faut comparer les différents scaling avec mass_smaller_14.

In [7]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            -0.997 - 3.082
                             scale_standard_14 radius            -0.997 - 3.082
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_power_14    radius            -0.997 - 3.082

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            1.0  0.226%
                             scale_standard_14 radius            1.0  0.226%
                             scale_robust_14   radius            1.0  0.226%
                             scale_quantile_14 radius            1.0  0.228%
                             scale_power_14    radius            1.0  0.227%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            0.131%
                             scale_standard_14 radius            0.131%
                             scale_robust_14   radius             0.13%
                             scale_quantile_14 radius            0.131%
                             scale_power_14    radius            0.131%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            0.077%   1.0
                             scale_standard_14 radius            0.077%   1.0
                             scale_robust_14   radius            0.077%   1.0
                             scale_quantile_14 radius            0.078%   1.0
                             scale_power_14    radius            0.077%   1.0

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            10.289%
                             scale_standard_14 radius            10.924%
                             scale_robust_14   radius             9.234%
                             scale_quantile_14 radius            10.924%
                             scale_power_14    radius             9.234%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
                             scale_standard_14 radius              75 : 0.165% / 90 : 0.3% / 95 : 0.397% / 99 : 0.854%
                             scale_robust_14   radius              75 : 0.165% / 90 : 0.3% / 95 : 0.395% / 99 : 0.854%
                             scale_quantile_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.857%
                             scale_power_14    radius              75 : 0.165% / 90 : 0.3% / 95 : 0.396% / 99 : 0.853%

                                                                   time
model         physical_model filter            output_parameter
decision_tree MIST           mass_smaller_14   radius            18.880
                             scale_standard_14 radius            18.010
                             scale_robust_14   radius            20.087
                             scale_quantile_14 radius            20.181
                             scale_power_14    radius            27.995

scale_robust et scale_power donne des meilleurs MAX_ER et des résultats égaux sur les autres métriques.

#### Filtre choisi

Le filtre scale_power_14 est choisi parce que les résultats pour tous les scaling pour prédire la masse sont a peu près égaux (un peu meilleur MAX_ER pour power) et est l'un des deux meilleurs filtre pour le rayon.

decision_tree	MIST	scale_power_14	mass	0.1 - 13.999	1.0	0.371%	0.118%	0.02%	1.0	36.365%	75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.606%	27.995

decision_tree	MIST	scale_power_14	radius	-0.997 - 3.082	1.0	0.227%	0.131%	0.077%	1.0	9.234%	75 : 0.165% / 90 : 0.3% / 95 : 0.396% / 99 : 0.853%	27.995

### KNN

#### Mass parameter

In [11]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model physical_model filter            output_parameter
KNN   MIST           Base              mass              0.1 - 298.545  0.990
                     mass_smaller_14   mass               0.1 - 13.999  0.999
                     mass_smaller_3    mass                  0.1 - 3.0  0.998
                     mass_smaller_30   mass               0.1 - 29.998  0.999
                     scale_power       mass              0.1 - 298.545  0.993
                     scale_power_14    mass               0.1 - 13.999  1.000
                     scale_quantile    mass              0.1 - 298.545  0.992
                     scale_quantile_14 mass               0.1 - 13.999  1.000
                     scale_robust      mass              0.1 - 298.545  0.994
                     scale_robust_14   mass               0.1 - 13.999  1.000
                     scale_standard    mass              0.1 - 298.545  0.994
                     scale_standard_14 mass               0.1 - 13.999  1.000

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           Base              mass              0.913%   0.11%
                     mass_smaller_14   mass              0.597%  0.209%
                     mass_smaller_3    mass              1.002%    0.4%
                     mass_smaller_30   mass              0.712%  0.172%
                     scale_power       mass               0.74%  0.093%
                     scale_power_14    mass              0.432%  0.159%
                     scale_quantile    mass               0.79%  0.094%
                     scale_quantile_14 mass              0.417%  0.146%
                     scale_robust      mass              0.718%  0.091%
                     scale_robust_14   mass              0.414%  0.159%
                     scale_standard    mass              0.709%  0.089%
                     scale_standard_14 mass              0.409%  0.155%

                                                          MedAE   CORR  \
model physical_model filter            output_parameter
KNN   MIST           Base              mass              0.003%  0.995
                     mass_smaller_14   mass              0.048%  1.000
                     mass_smaller_3    mass              0.156%  0.999
                     mass_smaller_30   mass              0.023%  0.999
                     scale_power       mass              0.002%  0.997
                     scale_power_14    mass              0.031%  1.000
                     scale_quantile    mass              0.002%  0.996
                     scale_quantile_14 mass              0.032%  1.000
                     scale_robust      mass              0.002%  0.997
                     scale_robust_14   mass              0.036%  1.000
                     scale_standard    mass              0.002%  0.997
                     scale_standard_14 mass              0.035%  1.000

                                                          MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           Base              mass              48.322%
                     mass_smaller_14   mass              18.732%
                     mass_smaller_3    mass              46.267%
                     mass_smaller_30   mass              25.561%
                     scale_power       mass              67.984%
                     scale_power_14    mass              18.465%
                     scale_quantile    mass              62.067%
                     scale_quantile_14 mass              15.284%
                     scale_robust      mass              45.135%
                     scale_robust_14   mass              18.778%
                     scale_standard    mass              42.759%
                     scale_standard_14 mass              18.803%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           Base              mass               75 : 0.013% / 90 : 0.07% / 95 : 0.236% / 99 : 2.302%
                     mass_smaller_14   mass              75 : 0.171% / 90 : 0.535% / 95 : 0.925% / 99 : 2.329%
                     mass_smaller_3    mass              75 : 0.399% / 90 : 0.862% / 95 : 1.462% / 99 : 4.535%
                     mass_smaller_30   mass              75 : 0.096% / 90 : 0.347% / 95 : 0.679% / 99 : 2.469%
                     scale_power       mass                75 : 0.011% / 90 : 0.06% / 95 : 0.205% / 99 : 2.09%
                     scale_power_14    mass              75 : 0.123% / 90 : 0.434% / 95 : 0.779% / 99 : 1.844%
                     scale_quantile    mass                75 : 0.01% / 90 : 0.05% / 95 : 0.184% / 99 : 2.084%
                     scale_quantile_14 mass              75 : 0.116% / 90 : 0.358% / 95 : 0.653% / 99 : 1.722%
                     scale_robust      mass              75 : 0.011% / 90 : 0.058% / 95 : 0.193% / 99 : 2.036%
                     scale_robust_14   mass               75 : 0.128% / 90 : 0.432% / 95 : 0.77% / 99 : 1.761%
                     scale_standard    mass              75 : 0.011% / 90 : 0.056% / 95 : 0.183% / 99 : 1.983%
                     scale_standard_14 mass              75 : 0.125% / 90 : 0.421% / 95 : 0.749% / 99 : 1.717%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           Base              mass               8.372
                     mass_smaller_14   mass               5.274
                     mass_smaller_3    mass               2.726
                     mass_smaller_30   mass               6.282
                     scale_power       mass              19.530
                     scale_power_14    mass              16.752
                     scale_quantile    mass               9.047
                     scale_quantile_14 mass               6.832
                     scale_robust      mass               9.668
                     scale_robust_14   mass               6.423
                     scale_standard    mass               9.078
                     scale_standard_14 mass               7.222

Filtre mass_smaller_14 donne les meilleurs résultats

In [13]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass              0.1 - 13.999  0.999
                     scale_standard_14 mass              0.1 - 13.999  1.000
                     scale_robust_14   mass              0.1 - 13.999  1.000
                     scale_quantile_14 mass              0.1 - 13.999  1.000
                     scale_power_14    mass              0.1 - 13.999  1.000

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass              0.597%  0.209%
                     scale_standard_14 mass              0.409%  0.155%
                     scale_robust_14   mass              0.414%  0.159%
                     scale_quantile_14 mass              0.417%  0.146%
                     scale_power_14    mass              0.432%  0.159%

                                                          MedAE  CORR  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass              0.048%   1.0
                     scale_standard_14 mass              0.035%   1.0
                     scale_robust_14   mass              0.036%   1.0
                     scale_quantile_14 mass              0.032%   1.0
                     scale_power_14    mass              0.031%   1.0

                                                          MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass              18.732%
                     scale_standard_14 mass              18.803%
                     scale_robust_14   mass              18.778%
                     scale_quantile_14 mass              15.284%
                     scale_power_14    mass              18.465%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass              75 : 0.171% / 90 : 0.535% / 95 : 0.925% / 99 : 2.329%
                     scale_standard_14 mass              75 : 0.125% / 90 : 0.421% / 95 : 0.749% / 99 : 1.717%
                     scale_robust_14   mass               75 : 0.128% / 90 : 0.432% / 95 : 0.77% / 99 : 1.761%
                     scale_quantile_14 mass              75 : 0.116% / 90 : 0.358% / 95 : 0.653% / 99 : 1.722%
                     scale_power_14    mass              75 : 0.123% / 90 : 0.434% / 95 : 0.779% / 99 : 1.844%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   mass               5.274
                     scale_standard_14 mass               7.222
                     scale_robust_14   mass               6.423
                     scale_quantile_14 mass               6.832
                     scale_power_14    mass              16.752

Le scaling semble améliorer les résultats. Le meilleur scaling est le quantile scaling, les 3 autres scaling sont assez égaux

#### Radius parameter

In [8]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  RVE  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            -0.997 - 3.129  1.0
                     mass_smaller_14   radius            -0.997 - 3.082  1.0
                     mass_smaller_3    radius            -0.997 - 2.781  1.0
                     mass_smaller_30   radius             -0.997 - 3.13  1.0
                     scale_power       radius            -0.997 - 3.129  1.0
                     scale_power_14    radius            -0.997 - 3.082  1.0
                     scale_quantile    radius            -0.997 - 3.129  1.0
                     scale_quantile_14 radius            -0.997 - 3.082  1.0
                     scale_robust      radius            -0.997 - 3.129  1.0
                     scale_robust_14   radius            -0.997 - 3.082  1.0
                     scale_standard    radius            -0.997 - 3.129  1.0
                     scale_standard_14 radius            -0.997 - 3.082  1.0

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            0.181%  0.102%
                     mass_smaller_14   radius            0.151%  0.093%
                     mass_smaller_3    radius            0.181%  0.108%
                     mass_smaller_30   radius            0.151%  0.093%
                     scale_power       radius            0.174%  0.099%
                     scale_power_14    radius            0.159%  0.097%
                     scale_quantile    radius            0.211%  0.114%
                     scale_quantile_14 radius            0.208%  0.115%
                     scale_robust      radius            0.165%  0.094%
                     scale_robust_14   radius            0.142%  0.091%
                     scale_standard    radius            0.167%  0.095%
                     scale_standard_14 radius            0.142%   0.09%

                                                          MedAE  CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            0.063%   1.0  7.445%
                     mass_smaller_14   radius            0.062%   1.0  5.056%
                     mass_smaller_3    radius            0.068%   1.0  5.987%
                     mass_smaller_30   radius            0.061%   1.0  6.014%
                     scale_power       radius             0.06%   1.0  9.692%
                     scale_power_14    radius            0.061%   1.0  6.452%
                     scale_quantile    radius             0.06%   1.0  8.869%
                     scale_quantile_14 radius            0.061%   1.0  7.367%
                     scale_robust      radius             0.06%   1.0  7.445%
                     scale_robust_14   radius            0.061%   1.0  3.102%
                     scale_standard    radius             0.06%   1.0  7.445%
                     scale_standard_14 radius             0.06%   1.0  3.102%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           Base              radius            75 : 0.124% / 90 : 0.223% / 95 : 0.309% / 99 : 0.655%
                     mass_smaller_14   radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
                     mass_smaller_3    radius             75 : 0.135% / 90 : 0.24% / 95 : 0.327% / 99 : 0.629%
                     mass_smaller_30   radius            75 : 0.118% / 90 : 0.208% / 95 : 0.278% / 99 : 0.526%
                     scale_power       radius             75 : 0.122% / 90 : 0.22% / 95 : 0.309% / 99 : 0.626%
                     scale_power_14    radius            75 : 0.125% / 90 : 0.222% / 95 : 0.308% / 99 : 0.546%
                     scale_quantile    radius            75 : 0.133% / 90 : 0.264% / 95 : 0.396% / 99 : 0.842%
                     scale_quantile_14 radius            75 : 0.138% / 90 : 0.274% / 95 : 0.404% / 99 : 0.822%
                     scale_robust      radius            75 : 0.115% / 90 : 0.203% / 95 : 0.282% / 99 : 0.588%
                     scale_robust_14   radius            75 : 0.118% / 90 : 0.202% / 95 : 0.273% / 99 : 0.472%
                     scale_standard    radius             75 : 0.117% / 90 : 0.208% / 95 : 0.29% / 99 : 0.597%
                     scale_standard_14 radius            75 : 0.117% / 90 : 0.202% / 95 : 0.275% / 99 : 0.475%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           Base              radius             8.372
                     mass_smaller_14   radius             5.274
                     mass_smaller_3    radius             2.726
                     mass_smaller_30   radius             6.282
                     scale_power       radius            19.530
                     scale_power_14    radius            16.752
                     scale_quantile    radius             9.047
                     scale_quantile_14 radius             6.832
                     scale_robust      radius             9.668
                     scale_robust_14   radius             6.423
                     scale_standard    radius             9.078
                     scale_standard_14 radius             7.222

mass_smaller_14 et les scaling donne les meilleurs résultats

In [9]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                            value range  RVE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   radius            -0.997 - 3.082  1.0
                     scale_standard_14 radius            -0.997 - 3.082  1.0
                     scale_robust_14   radius            -0.997 - 3.082  1.0
                     scale_quantile_14 radius            -0.997 - 3.082  1.0
                     scale_power_14    radius            -0.997 - 3.082  1.0

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   radius            0.151%  0.093%
                     scale_standard_14 radius            0.142%   0.09%
                     scale_robust_14   radius            0.142%  0.091%
                     scale_quantile_14 radius            0.208%  0.115%
                     scale_power_14    radius            0.159%  0.097%

                                                          MedAE  CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   radius            0.062%   1.0  5.056%
                     scale_standard_14 radius             0.06%   1.0  3.102%
                     scale_robust_14   radius            0.061%   1.0  3.102%
                     scale_quantile_14 radius            0.061%   1.0  7.367%
                     scale_power_14    radius            0.061%   1.0  6.452%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
                     scale_standard_14 radius            75 : 0.117% / 90 : 0.202% / 95 : 0.275% / 99 : 0.475%
                     scale_robust_14   radius            75 : 0.118% / 90 : 0.202% / 95 : 0.273% / 99 : 0.472%
                     scale_quantile_14 radius            75 : 0.138% / 90 : 0.274% / 95 : 0.404% / 99 : 0.822%
                     scale_power_14    radius            75 : 0.125% / 90 : 0.222% / 95 : 0.308% / 99 : 0.546%

                                                           time
model physical_model filter            output_parameter
KNN   MIST           mass_smaller_14   radius             5.274
                     scale_standard_14 radius             7.222
                     scale_robust_14   radius             6.423
                     scale_quantile_14 radius             6.832
                     scale_power_14    radius            16.752

Les scaling standard et robust sont les meilleurs scaling

#### Filtre choisi

Le filtre scale_standard_14 est choisi parce qu'il donne des bons résultats pour la masse et est l'un des deux meilleurs filtre pour le rayon.
le filtre scale_quantile_14 donne de meilleurs résultats sur la masse mais de vraiment moins bons résultats sur le rayon.

KNN	MIST	scale_standard_14	mass	0.1 - 13.999	1.000	0.409%	0.155%	0.035%	1.0	18.803%	75 : 0.125% / 90 : 0.421% / 95 : 0.749% / 99 : 1.717%	7.222

KNN	MIST	scale_standard_14	radius	-0.997 - 3.082	1.0	0.142%	0.09%	0.06%	1.0	3.102%	75 : 0.117% / 90 : 0.202% / 95 : 0.275% / 99 : 0.475%	7.222

### Random forest

#### Mass parameter

In [14]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                   value range  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.1 - 298.545
                             mass_smaller_14   mass               0.1 - 13.999
                             mass_smaller_3    mass                  0.1 - 3.0
                             mass_smaller_30   mass               0.1 - 29.998
                             scale_power       mass              0.1 - 298.545
                             scale_power_14    mass               0.1 - 13.999
                             scale_quantile    mass              0.1 - 298.545
                             scale_quantile_14 mass               0.1 - 13.999
                             scale_robust      mass              0.1 - 298.545
                             scale_robust_14   mass               0.1 - 13.999
                             scale_standard    mass              0.1 - 298.545
                             scale_standard_14 mass               0.1 - 13.999

                                                                   RVE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.998
                             mass_smaller_14   mass              1.000
                             mass_smaller_3    mass              0.999
                             mass_smaller_30   mass              1.000
                             scale_power       mass              0.998
                             scale_power_14    mass              1.000
                             scale_quantile    mass              0.998
                             scale_quantile_14 mass              1.000
                             scale_robust      mass              0.998
                             scale_robust_14   mass              1.000
                             scale_standard    mass              0.998
                             scale_standard_14 mass              1.000

                                                                   RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.419%
                             mass_smaller_14   mass              0.235%
                             mass_smaller_3    mass              0.672%
                             mass_smaller_30   mass              0.415%
                             scale_power       mass              0.418%
                             scale_power_14    mass              0.236%
                             scale_quantile    mass              0.418%
                             scale_quantile_14 mass              0.237%
                             scale_robust      mass              0.417%
                             scale_robust_14   mass              0.236%
                             scale_standard    mass              0.418%
                             scale_standard_14 mass              0.236%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.049%
                             mass_smaller_14   mass              0.082%
                             mass_smaller_3    mass              0.207%
                             mass_smaller_30   mass              0.069%
                             scale_power       mass              0.049%
                             scale_power_14    mass              0.083%
                             scale_quantile    mass              0.049%
                             scale_quantile_14 mass              0.083%
                             scale_robust      mass              0.049%
                             scale_robust_14   mass              0.083%
                             scale_standard    mass              0.049%
                             scale_standard_14 mass              0.083%

                                                                  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.001%
                             mass_smaller_14   mass              0.024%
                             mass_smaller_3    mass               0.07%
                             mass_smaller_30   mass              0.012%
                             scale_power       mass              0.001%
                             scale_power_14    mass              0.024%
                             scale_quantile    mass              0.001%
                             scale_quantile_14 mass              0.024%
                             scale_robust      mass              0.001%
                             scale_robust_14   mass              0.024%
                             scale_standard    mass              0.001%
                             scale_standard_14 mass              0.024%

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              0.999
                             mass_smaller_14   mass              1.000
                             mass_smaller_3    mass              1.000
                             mass_smaller_30   mass              1.000
                             scale_power       mass              0.999
                             scale_power_14    mass              1.000
                             scale_quantile    mass              0.999
                             scale_quantile_14 mass              1.000
                             scale_robust      mass              0.999
                             scale_robust_14   mass              1.000
                             scale_standard    mass              0.999
                             scale_standard_14 mass              1.000

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              32.158%
                             mass_smaller_14   mass              16.749%
                             mass_smaller_3    mass              51.551%
                             mass_smaller_30   mass              25.504%
                             scale_power       mass              32.608%
                             scale_power_14    mass              16.747%
                             scale_quantile    mass              32.421%
                             scale_quantile_14 mass              16.678%
                             scale_robust      mass              33.006%
                             scale_robust_14   mass               17.22%
                             scale_standard    mass               32.26%
                             scale_standard_14 mass               16.71%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           Base              mass               75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                             mass_smaller_14   mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
                             mass_smaller_3    mass              75 : 0.192% / 90 : 0.427% / 95 : 0.681% / 99 : 2.322%
                             mass_smaller_30   mass               75 : 0.037% / 90 : 0.11% / 95 : 0.231% / 99 : 0.933%
                             scale_power       mass              75 : 0.005% / 90 : 0.027% / 95 : 0.098% / 99 : 1.082%
                             scale_power_14    mass              75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 0.999%
                             scale_quantile    mass              75 : 0.005% / 90 : 0.027% / 95 : 0.098% / 99 : 1.067%
                             scale_quantile_14 mass               75 : 0.071% / 90 : 0.182% / 95 : 0.34% / 99 : 1.003%
                             scale_robust      mass              75 : 0.005% / 90 : 0.027% / 95 : 0.098% / 99 : 1.073%
                             scale_robust_14   mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.999%
                             scale_standard    mass              75 : 0.005% / 90 : 0.026% / 95 : 0.098% / 99 : 1.077%
                             scale_standard_14 mass              75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 1.006%

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           Base              mass              343.663
                             mass_smaller_14   mass              248.729
                             mass_smaller_3    mass              142.993
                             mass_smaller_30   mass              327.888
                             scale_power       mass              406.737
                             scale_power_14    mass              303.832
                             scale_quantile    mass              392.487
                             scale_quantile_14 mass              281.774
                             scale_robust      mass              327.375
                             scale_robust_14   mass              292.136
                             scale_standard    mass              380.062
                             scale_standard_14 mass              288.308

Filtre mass_smaller_14 et les scaling avec moins de 14 masse donne les meilleurs résultats

In [17]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              0.1 - 13.999
                             scale_standard_14 mass              0.1 - 13.999
                             scale_robust_14   mass              0.1 - 13.999
                             scale_quantile_14 mass              0.1 - 13.999
                             scale_power_14    mass              0.1 - 13.999

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              1.0  0.235%
                             scale_standard_14 mass              1.0  0.236%
                             scale_robust_14   mass              1.0  0.236%
                             scale_quantile_14 mass              1.0  0.237%
                             scale_power_14    mass              1.0  0.236%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              0.082%
                             scale_standard_14 mass              0.083%
                             scale_robust_14   mass              0.083%
                             scale_quantile_14 mass              0.083%
                             scale_power_14    mass              0.083%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              0.024%   1.0
                             scale_standard_14 mass              0.024%   1.0
                             scale_robust_14   mass              0.024%   1.0
                             scale_quantile_14 mass              0.024%   1.0
                             scale_power_14    mass              0.024%   1.0

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              16.749%
                             scale_standard_14 mass               16.71%
                             scale_robust_14   mass               17.22%
                             scale_quantile_14 mass              16.678%
                             scale_power_14    mass              16.747%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
                             scale_standard_14 mass              75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 1.006%
                             scale_robust_14   mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.999%
                             scale_quantile_14 mass               75 : 0.071% / 90 : 0.182% / 95 : 0.34% / 99 : 1.003%
                             scale_power_14    mass              75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 0.999%

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   mass              248.729
                             scale_standard_14 mass              288.308
                             scale_robust_14   mass              292.136
                             scale_quantile_14 mass              281.774
                             scale_power_14    mass              303.832

Le scaling n'améliore pas les résultats mais ne les rend pas pire. Il n'est pas utile d'utilise les données scaled

#### Radius parameter

In [12]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            -0.997 - 3.129
                             mass_smaller_14   radius            -0.997 - 3.082
                             mass_smaller_3    radius            -0.997 - 2.781
                             mass_smaller_30   radius             -0.997 - 3.13
                             scale_power       radius            -0.997 - 3.129
                             scale_power_14    radius            -0.997 - 3.082
                             scale_quantile    radius            -0.997 - 3.129
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_robust      radius            -0.997 - 3.129
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_standard    radius            -0.997 - 3.129
                             scale_standard_14 radius            -0.997 - 3.082

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            1.0  0.134%
                             mass_smaller_14   radius            1.0  0.114%
                             mass_smaller_3    radius            1.0  0.117%
                             mass_smaller_30   radius            1.0  0.114%
                             scale_power       radius            1.0  0.134%
                             scale_power_14    radius            1.0  0.114%
                             scale_quantile    radius            1.0  0.135%
                             scale_quantile_14 radius            1.0  0.114%
                             scale_robust      radius            1.0  0.135%
                             scale_robust_14   radius            1.0  0.114%
                             scale_standard    radius            1.0  0.135%
                             scale_standard_14 radius            1.0  0.114%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            0.065%
                             mass_smaller_14   radius             0.06%
                             mass_smaller_3    radius            0.053%
                             mass_smaller_30   radius            0.058%
                             scale_power       radius            0.065%
                             scale_power_14    radius            0.059%
                             scale_quantile    radius            0.066%
                             scale_quantile_14 radius             0.06%
                             scale_robust      radius            0.065%
                             scale_robust_14   radius             0.06%
                             scale_standard    radius            0.065%
                             scale_standard_14 radius             0.06%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            0.032%   1.0
                             mass_smaller_14   radius            0.031%   1.0
                             mass_smaller_3    radius            0.026%   1.0
                             mass_smaller_30   radius             0.03%   1.0
                             scale_power       radius            0.032%   1.0
                             scale_power_14    radius             0.03%   1.0
                             scale_quantile    radius            0.032%   1.0
                             scale_quantile_14 radius            0.031%   1.0
                             scale_robust      radius            0.032%   1.0
                             scale_robust_14   radius            0.031%   1.0
                             scale_standard    radius            0.032%   1.0
                             scale_standard_14 radius            0.031%   1.0

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            8.676%
                             mass_smaller_14   radius            3.502%
                             mass_smaller_3    radius            3.915%
                             mass_smaller_30   radius            9.954%
                             scale_power       radius            8.608%
                             scale_power_14    radius             3.28%
                             scale_quantile    radius            9.019%
                             scale_quantile_14 radius            3.531%
                             scale_robust      radius            9.163%
                             scale_robust_14   radius            3.671%
                             scale_standard    radius            9.742%
                             scale_standard_14 radius            3.194%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            75 : 0.075% / 90 : 0.152% / 95 : 0.228% / 99 : 0.499%
                             mass_smaller_14   radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
                             mass_smaller_3    radius             75 : 0.06% / 90 : 0.119% / 95 : 0.175% / 99 : 0.395%
                             mass_smaller_30   radius            75 : 0.069% / 90 : 0.136% / 95 : 0.199% / 99 : 0.412%
                             scale_power       radius              75 : 0.074% / 90 : 0.151% / 95 : 0.225% / 99 : 0.5%
                             scale_power_14    radius             75 : 0.071% / 90 : 0.14% / 95 : 0.205% / 99 : 0.412%
                             scale_quantile    radius            75 : 0.076% / 90 : 0.152% / 95 : 0.228% / 99 : 0.502%
                             scale_quantile_14 radius            75 : 0.072% / 90 : 0.142% / 95 : 0.206% / 99 : 0.413%
                             scale_robust      radius            75 : 0.076% / 90 : 0.152% / 95 : 0.226% / 99 : 0.501%
                             scale_robust_14   radius            75 : 0.071% / 90 : 0.142% / 95 : 0.206% / 99 : 0.415%
                             scale_standard    radius            75 : 0.075% / 90 : 0.152% / 95 : 0.227% / 99 : 0.502%
                             scale_standard_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.206% / 99 : 0.412%

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           Base              radius            343.663
                             mass_smaller_14   radius            248.729
                             mass_smaller_3    radius            142.993
                             mass_smaller_30   radius            327.888
                             scale_power       radius            406.737
                             scale_power_14    radius            303.832
                             scale_quantile    radius            392.487
                             scale_quantile_14 radius            281.774
                             scale_robust      radius            327.375
                             scale_robust_14   radius            292.136
                             scale_standard    radius            380.062
                             scale_standard_14 radius            288.308

Filtre mass_smaller_14 et les scaling avec moins de 14 masse donne les meilleurs résultats

In [13]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            -0.997 - 3.082
                             scale_standard_14 radius            -0.997 - 3.082
                             scale_robust_14   radius            -0.997 - 3.082
                             scale_quantile_14 radius            -0.997 - 3.082
                             scale_power_14    radius            -0.997 - 3.082

                                                                 RVE    RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            1.0  0.114%
                             scale_standard_14 radius            1.0  0.114%
                             scale_robust_14   radius            1.0  0.114%
                             scale_quantile_14 radius            1.0  0.114%
                             scale_power_14    radius            1.0  0.114%

                                                                    MAE  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius             0.06%
                             scale_standard_14 radius             0.06%
                             scale_robust_14   radius             0.06%
                             scale_quantile_14 radius             0.06%
                             scale_power_14    radius            0.059%

                                                                  MedAE  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            0.031%   1.0
                             scale_standard_14 radius            0.031%   1.0
                             scale_robust_14   radius            0.031%   1.0
                             scale_quantile_14 radius            0.031%   1.0
                             scale_power_14    radius             0.03%   1.0

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            3.502%
                             scale_standard_14 radius            3.194%
                             scale_robust_14   radius            3.671%
                             scale_quantile_14 radius            3.531%
                             scale_power_14    radius             3.28%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
                             scale_standard_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.206% / 99 : 0.412%
                             scale_robust_14   radius            75 : 0.071% / 90 : 0.142% / 95 : 0.206% / 99 : 0.415%
                             scale_quantile_14 radius            75 : 0.072% / 90 : 0.142% / 95 : 0.206% / 99 : 0.413%
                             scale_power_14    radius             75 : 0.071% / 90 : 0.14% / 95 : 0.205% / 99 : 0.412%

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           mass_smaller_14   radius            248.729
                             scale_standard_14 radius            288.308
                             scale_robust_14   radius            292.136
                             scale_quantile_14 radius            281.774
                             scale_power_14    radius            303.832

scale_standard_14 et scale_power_14 améliore la MAX_ER avec des résultats similaire pour les autres métriques.

#### Filtre choisi

Le filtre scale_standard_14 est choisi parce qu'il donne des résultats un peu meilleurs que les autres filtres pour la masse et est l'un des deux meilleurs filtre pour le rayon.

random_forest	MIST	scale_standard_14	mass	0.1 - 13.999	1.000	0.236%	0.083%	0.024%	1.000	16.71%	75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 1.006%	288.308

random_forest	MIST	scale_standard_14	radius	-0.997 - 3.082	1.0	0.114%	0.06%	0.031%	1.0	3.194%	75 : 0.071% / 90 : 0.141% / 95 : 0.206% / 99 : 0.412%	288.308

### XGBoost

#### Mass parameter

In [16]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                             value range  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass              0.1 - 298.545
                       mass_smaller_14   mass               0.1 - 13.999
                       mass_smaller_3    mass                  0.1 - 3.0
                       mass_smaller_30   mass               0.1 - 29.998
                       scale_power       mass              0.1 - 298.545
                       scale_power_14    mass               0.1 - 13.999
                       scale_quantile    mass              0.1 - 298.545
                       scale_quantile_14 mass               0.1 - 13.999
                       scale_robust      mass              0.1 - 298.545
                       scale_robust_14   mass               0.1 - 13.999
                       scale_standard    mass              0.1 - 298.545
                       scale_standard_14 mass               0.1 - 13.999

                                                             RVE    RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass              0.994  0.686%
                       mass_smaller_14   mass              0.999  0.696%
                       mass_smaller_3    mass              0.998  1.018%
                       mass_smaller_30   mass              0.998   0.83%
                       scale_power       mass              0.994  0.684%
                       scale_power_14    mass              0.999    0.7%
                       scale_quantile    mass              0.994  0.684%
                       scale_quantile_14 mass              0.999  0.699%
                       scale_robust      mass              0.994  0.682%
                       scale_robust_14   mass              0.999    0.7%
                       scale_standard    mass              0.994  0.684%
                       scale_standard_14 mass              0.999  0.699%

                                                              MAE   MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass              0.178%  0.033%
                       mass_smaller_14   mass              0.395%  0.206%
                       mass_smaller_3    mass              0.565%  0.337%
                       mass_smaller_30   mass              0.374%  0.155%
                       scale_power       mass              0.178%  0.033%
                       scale_power_14    mass              0.397%  0.205%
                       scale_quantile    mass              0.179%  0.034%
                       scale_quantile_14 mass              0.396%  0.206%
                       scale_robust      mass              0.178%  0.034%
                       scale_robust_14   mass              0.397%  0.206%
                       scale_standard    mass              0.178%  0.033%
                       scale_standard_14 mass              0.397%  0.206%

                                                            CORR   MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass              0.997  24.445%
                       mass_smaller_14   mass              1.000  18.006%
                       mass_smaller_3    mass              0.999   41.48%
                       mass_smaller_30   mass              0.999  23.433%
                       scale_power       mass              0.997  25.293%
                       scale_power_14    mass              1.000  18.123%
                       scale_quantile    mass              0.997   30.23%
                       scale_quantile_14 mass              1.000  14.508%
                       scale_robust      mass              0.997  25.293%
                       scale_robust_14   mass              1.000  18.123%
                       scale_standard    mass              0.997  25.293%
                       scale_standard_14 mass              1.000  18.123%

                                                                                                     Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass               75 : 0.091% / 90 : 0.33% / 95 : 0.726% / 99 : 2.844%
                       mass_smaller_14   mass              75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%
                       mass_smaller_3    mass               75 : 0.68% / 90 : 1.221% / 95 : 1.767% / 99 : 3.786%
                       mass_smaller_30   mass                75 : 0.39% / 90 : 0.854% / 95 : 1.37% / 99 : 3.591%
                       scale_power       mass              75 : 0.092% / 90 : 0.332% / 95 : 0.732% / 99 : 2.827%
                       scale_power_14    mass              75 : 0.479% / 90 : 0.956% / 95 : 1.392% / 99 : 2.702%
                       scale_quantile    mass               75 : 0.092% / 90 : 0.331% / 95 : 0.74% / 99 : 2.836%
                       scale_quantile_14 mass               75 : 0.477% / 90 : 0.95% / 95 : 1.386% / 99 : 2.705%
                       scale_robust      mass              75 : 0.092% / 90 : 0.331% / 95 : 0.731% / 99 : 2.808%
                       scale_robust_14   mass               75 : 0.48% / 90 : 0.959% / 95 : 1.396% / 99 : 2.704%
                       scale_standard    mass              75 : 0.092% / 90 : 0.331% / 95 : 0.732% / 99 : 2.825%
                       scale_standard_14 mass               75 : 0.48% / 90 : 0.959% / 95 : 1.394% / 99 : 2.701%

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           Base              mass              11.712
                       mass_smaller_14   mass               8.434
                       mass_smaller_3    mass               5.586
                       mass_smaller_30   mass              10.954
                       scale_power       mass              23.362
                       scale_power_14    mass              20.946
                       scale_quantile    mass              13.555
                       scale_quantile_14 mass              11.715
                       scale_robust      mass              10.018
                       scale_robust_14   mass              10.741
                       scale_standard    mass              11.907
                       scale_standard_14 mass              10.327

Filtre mass_smaller_14 donne les meilleurs résultats

In [18]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass              0.1 - 13.999
                       scale_standard_14 mass              0.1 - 13.999
                       scale_robust_14   mass              0.1 - 13.999
                       scale_quantile_14 mass              0.1 - 13.999
                       scale_power_14    mass              0.1 - 13.999

                                                             RVE    RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass              0.999  0.696%
                       scale_standard_14 mass              0.999  0.699%
                       scale_robust_14   mass              0.999    0.7%
                       scale_quantile_14 mass              0.999  0.699%
                       scale_power_14    mass              0.999    0.7%

                                                              MAE   MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass              0.395%  0.206%
                       scale_standard_14 mass              0.397%  0.206%
                       scale_robust_14   mass              0.397%  0.206%
                       scale_quantile_14 mass              0.396%  0.206%
                       scale_power_14    mass              0.397%  0.205%

                                                           CORR   MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass               1.0  18.006%
                       scale_standard_14 mass               1.0  18.123%
                       scale_robust_14   mass               1.0  18.123%
                       scale_quantile_14 mass               1.0  14.508%
                       scale_power_14    mass               1.0  18.123%

                                                                                                     Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass              75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%
                       scale_standard_14 mass               75 : 0.48% / 90 : 0.959% / 95 : 1.394% / 99 : 2.701%
                       scale_robust_14   mass               75 : 0.48% / 90 : 0.959% / 95 : 1.396% / 99 : 2.704%
                       scale_quantile_14 mass               75 : 0.477% / 90 : 0.95% / 95 : 1.386% / 99 : 2.705%
                       scale_power_14    mass              75 : 0.479% / 90 : 0.956% / 95 : 1.392% / 99 : 2.702%

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   mass               8.434
                       scale_standard_14 mass              10.327
                       scale_robust_14   mass              10.741
                       scale_quantile_14 mass              11.715
                       scale_power_14    mass              20.946

Le scaling quantile semble avoir une meilleur MAX_ER que les autres scaling et les données sans scaling

#### Radius parameter

In [14]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                              value range  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            -0.997 - 3.129
                       mass_smaller_14   radius            -0.997 - 3.082
                       mass_smaller_3    radius            -0.997 - 2.781
                       mass_smaller_30   radius             -0.997 - 3.13
                       scale_power       radius            -0.997 - 3.129
                       scale_power_14    radius            -0.997 - 3.082
                       scale_quantile    radius            -0.997 - 3.129
                       scale_quantile_14 radius            -0.997 - 3.082
                       scale_robust      radius            -0.997 - 3.129
                       scale_robust_14   radius            -0.997 - 3.082
                       scale_standard    radius            -0.997 - 3.129
                       scale_standard_14 radius            -0.997 - 3.082

                                                           RVE    RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            1.0  0.357%
                       mass_smaller_14   radius            1.0  0.275%
                       mass_smaller_3    radius            1.0  0.238%
                       mass_smaller_30   radius            1.0    0.3%
                       scale_power       radius            1.0  0.358%
                       scale_power_14    radius            1.0  0.276%
                       scale_quantile    radius            1.0   0.36%
                       scale_quantile_14 radius            1.0  0.276%
                       scale_robust      radius            1.0  0.358%
                       scale_robust_14   radius            1.0  0.275%
                       scale_standard    radius            1.0  0.358%
                       scale_standard_14 radius            1.0  0.275%

                                                              MAE   MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            0.258%  0.197%
                       mass_smaller_14   radius            0.199%  0.153%
                       mass_smaller_3    radius            0.161%  0.118%
                       mass_smaller_30   radius            0.219%  0.169%
                       scale_power       radius            0.259%  0.197%
                       scale_power_14    radius            0.199%  0.153%
                       scale_quantile    radius             0.26%  0.198%
                       scale_quantile_14 radius            0.199%  0.153%
                       scale_robust      radius            0.258%  0.197%
                       scale_robust_14   radius            0.199%  0.153%
                       scale_standard    radius            0.258%  0.197%
                       scale_standard_14 radius            0.199%  0.153%

                                                           CORR   MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius             1.0  11.866%
                       mass_smaller_14   radius             1.0   5.546%
                       mass_smaller_3    radius             1.0   5.076%
                       mass_smaller_30   radius             1.0   6.672%
                       scale_power       radius             1.0  12.382%
                       scale_power_14    radius             1.0   5.589%
                       scale_quantile    radius             1.0  10.022%
                       scale_quantile_14 radius             1.0   5.588%
                       scale_robust      radius             1.0  12.376%
                       scale_robust_14   radius             1.0   5.589%
                       scale_standard    radius             1.0  11.243%
                       scale_standard_14 radius             1.0   5.589%

                                                                                                     Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            75 : 0.354% / 90 : 0.546% / 95 : 0.692% / 99 : 1.079%
                       mass_smaller_14   radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%
                       mass_smaller_3    radius             75 : 0.214% / 90 : 0.34% / 95 : 0.441% / 99 : 0.747%
                       mass_smaller_30   radius            75 : 0.304% / 90 : 0.467% / 95 : 0.583% / 99 : 0.854%
                       scale_power       radius              75 : 0.355% / 90 : 0.55% / 95 : 0.695% / 99 : 1.08%
                       scale_power_14    radius            75 : 0.274% / 90 : 0.422% / 95 : 0.531% / 99 : 0.806%
                       scale_quantile    radius            75 : 0.357% / 90 : 0.552% / 95 : 0.698% / 99 : 1.085%
                       scale_quantile_14 radius             75 : 0.274% / 90 : 0.422% / 95 : 0.53% / 99 : 0.805%
                       scale_robust      radius            75 : 0.354% / 90 : 0.549% / 95 : 0.694% / 99 : 1.081%
                       scale_robust_14   radius             75 : 0.274% / 90 : 0.421% / 95 : 0.53% / 99 : 0.804%
                       scale_standard    radius             75 : 0.354% / 90 : 0.55% / 95 : 0.695% / 99 : 1.079%
                       scale_standard_14 radius            75 : 0.274% / 90 : 0.422% / 95 : 0.531% / 99 : 0.804%

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           Base              radius            11.712
                       mass_smaller_14   radius             8.434
                       mass_smaller_3    radius             5.586
                       mass_smaller_30   radius            10.954
                       scale_power       radius            23.362
                       scale_power_14    radius            20.946
                       scale_quantile    radius            13.555
                       scale_quantile_14 radius            11.715
                       scale_robust      radius            10.018
                       scale_robust_14   radius            10.741
                       scale_standard    radius            11.907
                       scale_standard_14 radius            10.327

le filtre mass_smaller_3 est le meilleur avec les filtre mass_smaller_14 qui sont un peu moins bon.

In [15]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["XGBoost"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                              value range  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius            -0.997 - 3.082
                       scale_standard_14 radius            -0.997 - 3.082
                       scale_robust_14   radius            -0.997 - 3.082
                       scale_quantile_14 radius            -0.997 - 3.082
                       scale_power_14    radius            -0.997 - 3.082

                                                           RVE    RMSE  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius            1.0  0.275%
                       scale_standard_14 radius            1.0  0.275%
                       scale_robust_14   radius            1.0  0.275%
                       scale_quantile_14 radius            1.0  0.276%
                       scale_power_14    radius            1.0  0.276%

                                                              MAE   MedAE  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius            0.199%  0.153%
                       scale_standard_14 radius            0.199%  0.153%
                       scale_robust_14   radius            0.199%  0.153%
                       scale_quantile_14 radius            0.199%  0.153%
                       scale_power_14    radius            0.199%  0.153%

                                                           CORR  MAX_ER  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius             1.0  5.546%
                       scale_standard_14 radius             1.0  5.589%
                       scale_robust_14   radius             1.0  5.589%
                       scale_quantile_14 radius             1.0  5.588%
                       scale_power_14    radius             1.0  5.589%

                                                                                                     Percentiles  \
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%
                       scale_standard_14 radius            75 : 0.274% / 90 : 0.422% / 95 : 0.531% / 99 : 0.804%
                       scale_robust_14   radius             75 : 0.274% / 90 : 0.421% / 95 : 0.53% / 99 : 0.804%
                       scale_quantile_14 radius             75 : 0.274% / 90 : 0.422% / 95 : 0.53% / 99 : 0.805%
                       scale_power_14    radius            75 : 0.274% / 90 : 0.422% / 95 : 0.531% / 99 : 0.806%

                                                             time
model   physical_model filter            output_parameter
XGBoost MIST           mass_smaller_14   radius             8.434
                       scale_standard_14 radius            10.327
                       scale_robust_14   radius            10.741
                       scale_quantile_14 radius            11.715
                       scale_power_14    radius            20.946

les scaling n'améliore pas les résultats. Les deux meilleurs filtres sont mass_smaller_3 et mass_smaller_14

#### Filtre choisi

Le filtre mass_smaller_14 est choisi parce qu'il donne les meilleurs résultats pour la masse et est l'un des deux meilleurs filtre pour le rayon.

XGBoost	MIST	mass_smaller_14	mass	0.1 - 13.999	0.999	0.696%	0.395%	0.206%	1.0	18.006%	75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%	8.434

XGBoost	MIST	mass_smaller_14	radius	-0.997 - 3.082	1.0	0.275%	0.199%	0.153%	1.0	5.546%	75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%	8.434

### MLP

#### Mass parameter

In [15]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model physical_model filter            output_parameter
mlp   MIST           Base              mass              0.1 - 298.545  0.976
                     mass_smaller_14   mass               0.1 - 13.999  0.998
                     mass_smaller_3    mass                  0.1 - 3.0  0.994
                     mass_smaller_30   mass               0.1 - 29.998  0.963
                     scale_power       mass              0.1 - 298.545  0.992
                     scale_power_14    mass               0.1 - 13.999  1.000
                     scale_quantile    mass              0.1 - 298.545  0.986
                     scale_quantile_14 mass               0.1 - 13.999  0.998
                     scale_robust      mass              0.1 - 298.545  0.993
                     scale_robust_14   mass               0.1 - 13.999  1.000
                     scale_standard    mass              0.1 - 298.545  0.988
                     scale_standard_14 mass               0.1 - 13.999  1.000

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
mlp   MIST           Base              mass              1.381%  0.422%
                     mass_smaller_14   mass              1.064%  0.564%
                     mass_smaller_3    mass              2.037%   1.26%
                     mass_smaller_30   mass              4.065%  1.561%
                     scale_power       mass              0.808%  0.212%
                     scale_power_14    mass              0.482%  0.241%
                     scale_quantile    mass              1.044%  0.289%
                     scale_quantile_14 mass              1.042%  0.524%
                     scale_robust      mass              0.737%  0.214%
                     scale_robust_14   mass              0.435%  0.226%
                     scale_standard    mass              0.986%  0.254%
                     scale_standard_14 mass              0.445%  0.228%

                                                          MedAE   CORR  \
model physical_model filter            output_parameter
mlp   MIST           Base              mass              0.115%  0.988
                     mass_smaller_14   mass              0.323%  0.999
                     mass_smaller_3    mass              0.823%  0.997
                     mass_smaller_30   mass              0.513%  0.982
                     scale_power       mass              0.055%  0.996
                     scale_power_14    mass              0.129%  1.000
                     scale_quantile    mass              0.077%  0.993
                     scale_quantile_14 mass              0.257%  0.999
                     scale_robust      mass              0.051%  0.997
                     scale_robust_14   mass              0.126%  1.000
                     scale_standard    mass               0.05%  0.994
                     scale_standard_14 mass              0.127%  1.000

                                                          MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           Base              mass              58.569%
                     mass_smaller_14   mass              25.383%
                     mass_smaller_3    mass              65.604%
                     mass_smaller_30   mass              65.438%
                     scale_power       mass              42.041%
                     scale_power_14    mass              20.326%
                     scale_quantile    mass              70.769%
                     scale_quantile_14 mass              23.276%
                     scale_robust      mass              24.197%
                     scale_robust_14   mass              16.914%
                     scale_standard    mass              38.412%
                     scale_standard_14 mass              14.543%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           Base              mass               75 : 0.242% / 90 : 0.82% / 95 : 1.756% / 99 : 6.292%
                     mass_smaller_14   mass              75 : 0.666% / 90 : 1.262% / 95 : 1.857% / 99 : 3.598%
                     mass_smaller_3    mass               75 : 1.661% / 90 : 2.828% / 95 : 3.79% / 99 : 6.481%
                     mass_smaller_30   mass              75 : 1.118% / 90 : 3.273% / 95 : 6.509% / 99 : 20.27%
                     scale_power       mass               75 : 0.124% / 90 : 0.333% / 95 : 0.865% / 99 : 2.96%
                     scale_power_14    mass              75 : 0.271% / 90 : 0.531% / 95 : 0.793% / 99 : 1.769%
                     scale_quantile    mass              75 : 0.161% / 90 : 0.571% / 95 : 1.245% / 99 : 3.937%
                     scale_quantile_14 mass              75 : 0.558% / 90 : 1.187% / 95 : 1.885% / 99 : 4.422%
                     scale_robust      mass               75 : 0.11% / 90 : 0.366% / 95 : 0.992% / 99 : 3.241%
                     scale_robust_14   mass              75 : 0.253% / 90 : 0.503% / 95 : 0.758% / 99 : 1.619%
                     scale_standard    mass              75 : 0.134% / 90 : 0.463% / 95 : 1.099% / 99 : 3.883%
                     scale_standard_14 mass              75 : 0.254% / 90 : 0.486% / 95 : 0.752% / 99 : 1.741%

                                                            time
model physical_model filter            output_parameter
mlp   MIST           Base              mass              259.791
                     mass_smaller_14   mass              189.019
                     mass_smaller_3    mass              116.375
                     mass_smaller_30   mass              349.929
                     scale_power       mass              406.952
                     scale_power_14    mass              344.522
                     scale_quantile    mass              414.491
                     scale_quantile_14 mass              304.379
                     scale_robust      mass              351.910
                     scale_robust_14   mass              347.146
                     scale_standard    mass              365.071
                     scale_standard_14 mass              341.886

Filtre mass_smaller_14 donne les meilleurs résultats

In [19]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"],
                data_filters=["mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              0.1 - 13.999  0.998
                     scale_standard_14 mass              0.1 - 13.999  1.000
                     scale_robust_14   mass              0.1 - 13.999  1.000
                     scale_quantile_14 mass              0.1 - 13.999  0.998
                     scale_power_14    mass              0.1 - 13.999  1.000

                                                           RMSE     MAE  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              1.064%  0.564%
                     scale_standard_14 mass              0.445%  0.228%
                     scale_robust_14   mass              0.435%  0.226%
                     scale_quantile_14 mass              1.042%  0.524%
                     scale_power_14    mass              0.482%  0.241%

                                                          MedAE   CORR  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              0.323%  0.999
                     scale_standard_14 mass              0.127%  1.000
                     scale_robust_14   mass              0.126%  1.000
                     scale_quantile_14 mass              0.257%  0.999
                     scale_power_14    mass              0.129%  1.000

                                                          MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              25.383%
                     scale_standard_14 mass              14.543%
                     scale_robust_14   mass              16.914%
                     scale_quantile_14 mass              23.276%
                     scale_power_14    mass              20.326%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              75 : 0.666% / 90 : 1.262% / 95 : 1.857% / 99 : 3.598%
                     scale_standard_14 mass              75 : 0.254% / 90 : 0.486% / 95 : 0.752% / 99 : 1.741%
                     scale_robust_14   mass              75 : 0.253% / 90 : 0.503% / 95 : 0.758% / 99 : 1.619%
                     scale_quantile_14 mass              75 : 0.558% / 90 : 1.187% / 95 : 1.885% / 99 : 4.422%
                     scale_power_14    mass              75 : 0.271% / 90 : 0.531% / 95 : 0.793% / 99 : 1.769%

                                                            time
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_14   mass              189.019
                     scale_standard_14 mass              341.886
                     scale_robust_14   mass              347.146
                     scale_quantile_14 mass              304.379
                     scale_power_14    mass              344.522

le scaling améliore les résultats. Le meilleur scaling est le standard scaler avec le robust scaling en deuxième

#### Radius parameter

In [16]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            -0.997 - 3.129
                     mass_smaller_14   radius            -0.997 - 3.082
                     mass_smaller_3    radius            -0.997 - 2.781
                     mass_smaller_30   radius             -0.997 - 3.13
                     scale_power       radius            -0.997 - 3.129
                     scale_power_14    radius            -0.997 - 3.082
                     scale_quantile    radius            -0.997 - 3.129
                     scale_quantile_14 radius            -0.997 - 3.082
                     scale_robust      radius            -0.997 - 3.129
                     scale_robust_14   radius            -0.997 - 3.082
                     scale_standard    radius            -0.997 - 3.129
                     scale_standard_14 radius            -0.997 - 3.082

                                                           RVE    RMSE  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            0.992  1.593%
                     mass_smaller_14   radius            0.999  0.537%
                     mass_smaller_3    radius            0.999  0.588%
                     mass_smaller_30   radius            0.995  1.476%
                     scale_power       radius            0.988  1.986%
                     scale_power_14    radius            1.000   0.33%
                     scale_quantile    radius            0.978  2.678%
                     scale_quantile_14 radius            0.999  0.657%
                     scale_robust      radius            0.993  1.458%
                     scale_robust_14   radius            1.000  0.313%
                     scale_standard    radius            0.993  1.511%
                     scale_standard_14 radius            1.000  0.274%

                                                            MAE   MedAE  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            1.218%  0.968%
                     mass_smaller_14   radius            0.384%  0.306%
                     mass_smaller_3    radius            0.404%  0.273%
                     mass_smaller_30   radius             1.13%   0.86%
                     scale_power       radius            1.471%   1.13%
                     scale_power_14    radius            0.245%  0.192%
                     scale_quantile    radius            1.961%  1.495%
                     scale_quantile_14 radius            0.467%  0.328%
                     scale_robust      radius            1.055%  0.817%
                     scale_robust_14   radius            0.237%  0.189%
                     scale_standard    radius            1.142%  0.902%
                     scale_standard_14 radius            0.208%  0.169%

                                                          CORR   MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius            0.996  14.074%
                     mass_smaller_14   radius            1.000   11.26%
                     mass_smaller_3    radius            1.000  10.377%
                     mass_smaller_30   radius            0.998  12.688%
                     scale_power       radius            0.994  19.295%
                     scale_power_14    radius            1.000   4.333%
                     scale_quantile    radius            0.989  21.929%
                     scale_quantile_14 radius            0.999   9.179%
                     scale_robust      radius            0.997  21.564%
                     scale_robust_14   radius            1.000   3.348%
                     scale_standard    radius            0.997  17.457%
                     scale_standard_14 radius            1.000   3.244%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           Base              radius             75 : 1.701% / 90 : 2.581% / 95 : 3.181% / 99 : 4.68%
                     mass_smaller_14   radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
                     mass_smaller_3    radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                     mass_smaller_30   radius            75 : 1.604% / 90 : 2.511% / 95 : 3.019% / 99 : 4.046%
                     scale_power       radius            75 : 2.017% / 90 : 3.166% / 95 : 3.972% / 99 : 5.964%
                     scale_power_14    radius            75 : 0.336% / 90 : 0.514% / 95 : 0.646% / 99 : 0.997%
                     scale_quantile    radius              75 : 2.652% / 90 : 4.2% / 95 : 5.405% / 99 : 8.778%
                     scale_quantile_14 radius            75 : 0.635% / 90 : 1.066% / 95 : 1.367% / 99 : 2.073%
                     scale_robust      radius             75 : 1.431% / 90 : 2.19% / 95 : 2.776% / 99 : 4.702%
                     scale_robust_14   radius            75 : 0.331% / 90 : 0.501% / 95 : 0.623% / 99 : 0.901%
                     scale_standard    radius              75 : 1.599% / 90 : 2.39% / 95 : 2.988% / 99 : 4.49%
                     scale_standard_14 radius             75 : 0.29% / 90 : 0.428% / 95 : 0.526% / 99 : 0.782%

                                                            time
model physical_model filter            output_parameter
mlp   MIST           Base              radius            259.791
                     mass_smaller_14   radius            189.019
                     mass_smaller_3    radius            116.375
                     mass_smaller_30   radius            349.929
                     scale_power       radius            406.952
                     scale_power_14    radius            344.522
                     scale_quantile    radius            414.491
                     scale_quantile_14 radius            304.379
                     scale_robust      radius            351.910
                     scale_robust_14   radius            347.146
                     scale_standard    radius            365.071
                     scale_standard_14 radius            341.886

les meilleurs filtres sont mass_smaller_14 avec du scaling et mass_smaller_3

In [18]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["MIST"],
                model_names=["mlp"],
                categories=["Global"],
                data_filters=["mass_smaller_3", "mass_smaller_14", "scale_standard_14", "scale_robust_14", "scale_quantile_14", "scale_power_14"]
                )

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius            -0.997 - 2.781
                     mass_smaller_14   radius            -0.997 - 3.082
                     scale_standard_14 radius            -0.997 - 3.082
                     scale_robust_14   radius            -0.997 - 3.082
                     scale_quantile_14 radius            -0.997 - 3.082
                     scale_power_14    radius            -0.997 - 3.082

                                                           RVE    RMSE  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius            0.999  0.588%
                     mass_smaller_14   radius            0.999  0.537%
                     scale_standard_14 radius            1.000  0.274%
                     scale_robust_14   radius            1.000  0.313%
                     scale_quantile_14 radius            0.999  0.657%
                     scale_power_14    radius            1.000   0.33%

                                                            MAE   MedAE  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius            0.404%  0.273%
                     mass_smaller_14   radius            0.384%  0.306%
                     scale_standard_14 radius            0.208%  0.169%
                     scale_robust_14   radius            0.237%  0.189%
                     scale_quantile_14 radius            0.467%  0.328%
                     scale_power_14    radius            0.245%  0.192%

                                                          CORR   MAX_ER  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius            1.000  10.377%
                     mass_smaller_14   radius            1.000   11.26%
                     scale_standard_14 radius            1.000   3.244%
                     scale_robust_14   radius            1.000   3.348%
                     scale_quantile_14 radius            0.999   9.179%
                     scale_power_14    radius            1.000   4.333%

                                                                                                   Percentiles  \
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                     mass_smaller_14   radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
                     scale_standard_14 radius             75 : 0.29% / 90 : 0.428% / 95 : 0.526% / 99 : 0.782%
                     scale_robust_14   radius            75 : 0.331% / 90 : 0.501% / 95 : 0.623% / 99 : 0.901%
                     scale_quantile_14 radius            75 : 0.635% / 90 : 1.066% / 95 : 1.367% / 99 : 2.073%
                     scale_power_14    radius            75 : 0.336% / 90 : 0.514% / 95 : 0.646% / 99 : 0.997%

                                                            time
model physical_model filter            output_parameter
mlp   MIST           mass_smaller_3    radius            116.375
                     mass_smaller_14   radius            189.019
                     scale_standard_14 radius            341.886
                     scale_robust_14   radius            347.146
                     scale_quantile_14 radius            304.379
                     scale_power_14    radius            344.522

scale_standard_14 donne les meilleurs résultats

#### Filtre choisi

Le filtre scale_standard_14 est choisi parce qu'il donne les meilleurs résultats pour la masse et pour le rayon.

mlp	MIST	scale_standard_14	mass	0.1 - 13.999	1.000	0.445%	0.228%	0.127%	1.000	14.543%	75 : 0.254% / 90 : 0.486% / 95 : 0.752% / 99 : 1.741%	341.886

mlp	MIST	scale_standard_14	radius	-0.997 - 3.082	1.000	0.274%	0.208%	0.169%	1.000	3.244%	75 : 0.29% / 90 : 0.428% / 95 : 0.526% / 99 : 0.782%	341.886

### Compilation des meilleurs modèles

#### Mass parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | MIST | mass_smaller_14 | mass | 0.1 - 13.999 | 0.725 | 12.351% | 9.338% | 7.035% | 0.852 | 55.541% | 75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338% | 0.461 |
| decision_tree | MIST | scale_power_14 | mass | 0.1 - 13.999 | 1.0 | 0.371% | 0.118% | 0.02% | 1.0 | 36.365% | 75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.606% | 27.995 |
| KNN | MIST | scale_standard_14 | mass | 0.1 - 13.999 | 1.000 | 0.409% | 0.155% | 0.035% | 1.0 | 18.803% | 75 : 0.125% / 90 : 0.421% / 95 : 0.749% / 99 : 1.717% | 7.222 |
| random_forest | MIST | scale_standard_14 | mass | 0.1 - 13.999 | 1.000 | 0.236% | 0.083% | 0.024% | 1.000 | 16.71% | 75 : 0.071% / 90 : 0.182% / 95 : 0.337% / 99 : 1.006% | 288.308 |
| XGBoost | MIST | mass_smaller_14 | mass | 0.1 - 13.999 | 0.999 | 0.696% | 0.395% | 0.206% | 1.0 | 18.006% | 75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702% | 8.434 |
| mlp | MIST | scale_standard_14 | mass | 0.1 - 13.999 | 1.000 | 0.445% | 0.228% | 0.127% | 1.000 | 14.543% | 75 : 0.254% / 90 : 0.486% / 95 : 0.752% / 99 : 1.741% | 341.886 |

The best models in order for the mass from best to worst are:

1. Random forest (better results almost all models on almost all metrics)
2. KNN (overall better results than other models)
3. MLP and DT (MLP has slightly worse results than MLP but way better MAX_ER and the other way around for DT)
5. XGBoost
6. Linear regression (worse results than any other modelon all metrics)

#### Radius parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | MIST | mass_smaller_14 | radius | -0.997 - 3.082 | 0.992 | 1.586% | 1.206% | 0.976% | 0.996 | 11.805% | 75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566% | 0.461 |
| decision_tree | MIST | scale_power_14 | radius | -0.997 - 3.082 | 1.0 | 0.227% | 0.131% | 0.077% | 1.0 | 9.234% | 75 : 0.165% / 90 : 0.3% / 95 : 0.396% / 99 : 0.853% | 27.995 |
| KNN | MIST | scale_standard_14 | radius | -0.997 - 3.082 | 1.0 | 0.142% | 0.09% | 0.06% | 1.0 | 3.102% | 75 : 0.117% / 90 : 0.202% / 95 : 0.275% / 99 : 0.475% | 7.222 |
| random_forest | MIST | scale_standard_14 | radius | -0.997 - 3.082 | 1.0 | 0.114% | 0.06% | 0.031% | 1.0 | 3.194% | 75 : 0.071% / 90 : 0.141% / 95 : 0.206% / 99 : 0.412% | 288.308 |
| XGBoost | MIST | mass_smaller_14 | radius | -0.997 - 3.082 | 1.0 | 0.275% | 0.199% | 0.153% | 1.0 | 5.546% | 75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802% | 8.434 |
| mlp | MIST | scale_standard_14 | radius | -0.997 - 3.082 | 1.000 | 0.274% | 0.208% | 0.169% | 1.000 | 3.244% | 75 : 0.29% / 90 : 0.428% / 95 : 0.526% / 99 : 0.782% | 341.886 |

The best models in order for the mass from best to worst are:

1. Random forest (better results almost all models on almost all metrics)
2. KNN (overall better results than other models)
3. MLP and DT (MLP has slightly worse results than MLP but way better MAX_ER and the other way around for DT)
5. XGBoost
6. Linear regression (worse results than any other modelon all metrics)

### Models to be fine-tuned

Random forest with scale_standard_14 and KNN with scale_standard_14

## Scaling vs scaling mass smaller 14

### Mass parameter

In [ ]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["mass"],
                physical_models=["MIST"],
                model_names=["decision_tree"],
                data_filters=["Base", "mass_smaller_14", "scale_standard", "scale_standard_14", "scale_robust", "scale_robust_14", "scale_power", "scale_power_14",  "scale_quantile", "scale_quantile_14"]
                )

Results for the Global category with a value of 1.0

                                                                                             value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_14   mass              0.0999979840073621 - 13.998624815474695
                             scale_standard    mass               0.0999979840073621 - 298.5447575808816
                             scale_standard_14 mass              0.0999979840073621 - 13.998624815474695
                             scale_robust      mass               0.0999979840073621 - 298.5447575808816
                             scale_robust_14   mass              0.0999979840073621 - 13.998624815474695
                             scale_power       mass               0.0999979840073621 - 298.5447575808816
                             scale_power_14    mass              0.0999979840073621 - 13.998624815474695
                             scale_quantile    mass               0.0999979840073621 - 298.5447575808816
                             scale_quantile_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9952703219364649
                             mass_smaller_14   mass              0.9997535427935771
                             scale_standard    mass              0.9952101903329457
                             scale_standard_14 mass              0.9997504112982422
                             scale_robust      mass              0.9952433722990285
                             scale_robust_14   mass              0.9997510626965542
                             scale_power       mass              0.9952936910032032
                             scale_power_14    mass              0.9997524402475794
                             scale_quantile    mass              0.9952909967064102
                             scale_quantile_14 mass              0.9997523470164404

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.615%
                             mass_smaller_14   mass               0.37%
                             scale_standard    mass              0.619%
                             scale_standard_14 mass              0.372%
                             scale_robust      mass              0.617%
                             scale_robust_14   mass              0.372%
                             scale_power       mass              0.614%
                             scale_power_14    mass              0.371%
                             scale_quantile    mass              0.614%
                             scale_quantile_14 mass              0.371%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.067%
                             mass_smaller_14   mass              0.117%
                             scale_standard    mass              0.067%
                             scale_standard_14 mass              0.118%
                             scale_robust      mass              0.067%
                             scale_robust_14   mass              0.117%
                             scale_power       mass              0.067%
                             scale_power_14    mass              0.118%
                             scale_quantile    mass              0.067%
                             scale_quantile_14 mass              0.118%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.001%
                             mass_smaller_14   mass               0.02%
                             scale_standard    mass              0.001%
                             scale_standard_14 mass               0.02%
                             scale_robust      mass              0.001%
                             scale_robust_14   mass               0.02%
                             scale_power       mass              0.001%
                             scale_power_14    mass               0.02%
                             scale_quantile    mass              0.001%
                             scale_quantile_14 mass               0.02%

                                                                               CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9976339781841599
                             mass_smaller_14   mass              0.9998767781112852
                             scale_standard    mass              0.9976039706275885
                             scale_standard_14 mass              0.9998752116775352
                             scale_robust      mass              0.9976203894889993
                             scale_robust_14   mass              0.9998755344691379
                             scale_power       mass              0.9976460939925359
                             scale_power_14    mass              0.9998762296057959
                             scale_quantile    mass              0.9976454672833274
                             scale_quantile_14 mass              0.9998761679412451

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              50.816%
                             mass_smaller_14   mass              36.812%
                             scale_standard    mass              50.816%
                             scale_standard_14 mass              36.365%
                             scale_robust      mass              49.742%
                             scale_robust_14   mass              36.812%
                             scale_power       mass              50.816%
                             scale_power_14    mass              36.365%
                             scale_quantile    mass              50.816%
                             scale_quantile_14 mass              36.812%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                             mass_smaller_14   mass              75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
                             scale_standard    mass              75 : 0.007% / 90 : 0.035% / 95 : 0.119% / 99 : 1.525%
                             scale_standard_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.529% / 99 : 1.597%
                             scale_robust      mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.524%
                             scale_robust_14   mass              75 : 0.087% / 90 : 0.275% / 95 : 0.527% / 99 : 1.595%
                             scale_power       mass              75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.512%
                             scale_power_14    mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.606%
                             scale_quantile    mass               75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.52%
                             scale_quantile_14 mass              75 : 0.087% / 90 : 0.276% / 95 : 0.528% / 99 : 1.601%

                                                                               time
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              24.898207902908325
                             mass_smaller_14   mass              18.880497217178345
                             scale_standard    mass              22.573050260543823
                             scale_standard_14 mass               18.01037335395813
                             scale_robust      mass              28.476685762405396
                             scale_robust_14   mass                20.0865695476532
                             scale_power       mass               35.47294616699219
                             scale_power_14    mass              27.994585514068604
                             scale_quantile    mass              26.211433172225952
                             scale_quantile_14 mass              20.181453704833984

Results for the phase category with a value of 0.0

                                                                                             value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_14   mass              0.0999979840073621 - 13.998624815474695
                             scale_standard    mass               0.0999979840073621 - 298.5447575808816
                             scale_standard_14 mass              0.0999979840073621 - 13.998624815474695
                             scale_robust      mass               0.0999979840073621 - 298.5447575808816
                             scale_robust_14   mass              0.0999979840073621 - 13.998624815474695
                             scale_power       mass               0.0999979840073621 - 298.5447575808816
                             scale_power_14    mass              0.0999979840073621 - 13.998624815474695
                             scale_quantile    mass               0.0999979840073621 - 298.5447575808816
                             scale_quantile_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9936340302001091
                             mass_smaller_14   mass              0.9997590738023714
                             scale_standard    mass              0.9935933952260151
                             scale_standard_14 mass              0.9997530617047778
                             scale_robust      mass              0.9936721398671367
                             scale_robust_14   mass              0.9997543696077013
                             scale_power       mass              0.9937584584493031
                             scale_power_14    mass              0.9997556093085673
                             scale_quantile    mass              0.9936853423995572
                             scale_quantile_14 mass              0.9997583045951958

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.703%
                             mass_smaller_14   mass              0.368%
                             scale_standard    mass              0.705%
                             scale_standard_14 mass              0.373%
                             scale_robust      mass              0.701%
                             scale_robust_14   mass              0.372%
                             scale_power       mass              0.696%
                             scale_power_14    mass              0.371%
                             scale_quantile    mass                0.7%
                             scale_quantile_14 mass              0.369%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               0.09%
                             mass_smaller_14   mass              0.122%
                             scale_standard    mass               0.09%
                             scale_standard_14 mass              0.122%
                             scale_robust      mass               0.09%
                             scale_robust_14   mass              0.122%
                             scale_power       mass               0.09%
                             scale_power_14    mass              0.122%
                             scale_quantile    mass               0.09%
                             scale_quantile_14 mass              0.122%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.002%
                             mass_smaller_14   mass               0.03%
                             scale_standard    mass              0.002%
                             scale_standard_14 mass               0.03%
                             scale_robust      mass              0.002%
                             scale_robust_14   mass               0.03%
                             scale_power       mass              0.002%
                             scale_power_14    mass               0.03%
                             scale_quantile    mass              0.002%
                             scale_quantile_14 mass               0.03%

                                                                               CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9968269721840094
                             mass_smaller_14   mass              0.9998795329372157
                             scale_standard    mass              0.9968085002700635
                             scale_standard_14 mass              0.9998765259740009
                             scale_robust      mass              0.9968467350115852
                             scale_robust_14   mass              0.9998771813410589
                             scale_power       mass              0.9968912616444416
                             scale_power_14    mass              0.9998778036514527
                             scale_quantile    mass              0.9968582092538901
                             scale_quantile_14 mass               0.999879147253342

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              44.154%
                             mass_smaller_14   mass              36.812%
                             scale_standard    mass              44.154%
                             scale_standard_14 mass              36.365%
                             scale_robust      mass              41.604%
                             scale_robust_14   mass              36.812%
                             scale_power       mass              44.154%
                             scale_power_14    mass              36.365%
                             scale_quantile    mass              44.154%
                             scale_quantile_14 mass              36.812%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.993%
                             mass_smaller_14   mass              75 : 0.098% / 90 : 0.303% / 95 : 0.532% / 99 : 1.395%
                             scale_standard    mass               75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.981%
                             scale_standard_14 mass              75 : 0.098% / 90 : 0.303% / 95 : 0.533% / 99 : 1.405%
                             scale_robust      mass               75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.966%
                             scale_robust_14   mass              75 : 0.098% / 90 : 0.302% / 95 : 0.532% / 99 : 1.405%
                             scale_power       mass               75 : 0.01% / 90 : 0.062% / 95 : 0.225% / 99 : 1.963%
                             scale_power_14    mass               75 : 0.098% / 90 : 0.304% / 95 : 0.533% / 99 : 1.41%
                             scale_quantile    mass               75 : 0.01% / 90 : 0.062% / 95 : 0.224% / 99 : 1.966%
                             scale_quantile_14 mass              75 : 0.098% / 90 : 0.302% / 95 : 0.532% / 99 : 1.405%

                                                                               time
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              24.898207902908325
                             mass_smaller_14   mass              18.880497217178345
                             scale_standard    mass              22.573050260543823
                             scale_standard_14 mass               18.01037335395813
                             scale_robust      mass              28.476685762405396
                             scale_robust_14   mass                20.0865695476532
                             scale_power       mass               35.47294616699219
                             scale_power_14    mass              27.994585514068604
                             scale_quantile    mass              26.211433172225952
                             scale_quantile_14 mass              20.181453704833984

Results for the phase category with a value of 2.0

                                                                                             value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.6538581961218565 - 283.72102985530483
                             mass_smaller_14   mass              0.6542770535966311 - 13.927740111688449
                             scale_standard    mass              0.6538581961218565 - 283.72102985530483
                             scale_standard_14 mass              0.6542770535966311 - 13.927740111688449
                             scale_robust      mass              0.6538581961218565 - 283.72102985530483
                             scale_robust_14   mass              0.6542770535966311 - 13.927740111688449
                             scale_power       mass              0.6538581961218565 - 283.72102985530483
                             scale_power_14    mass              0.6542770535966311 - 13.927740111688449
                             scale_quantile    mass              0.6538581961218565 - 283.72102985530483
                             scale_quantile_14 mass              0.6542770535966311 - 13.927740111688449

                                                                                RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9992828062113351
                             mass_smaller_14   mass              0.9999398039293963
                             scale_standard    mass              0.9991249538679495
                             scale_standard_14 mass              0.9999405593642136
                             scale_robust      mass              0.9991330923578028
                             scale_robust_14   mass              0.9999399369641745
                             scale_power       mass              0.9992314927358148
                             scale_power_14    mass              0.9999408009998965
                             scale_quantile    mass              0.9992015439276027
                             scale_quantile_14 mass              0.9999397327291966

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.281%
                             mass_smaller_14   mass               0.19%
                             scale_standard    mass               0.31%
                             scale_standard_14 mass              0.189%
                             scale_robust      mass              0.309%
                             scale_robust_14   mass               0.19%
                             scale_power       mass              0.291%
                             scale_power_14    mass              0.188%
                             scale_quantile    mass              0.296%
                             scale_quantile_14 mass               0.19%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.021%
                             mass_smaller_14   mass              0.058%
                             scale_standard    mass              0.022%
                             scale_standard_14 mass              0.058%
                             scale_robust      mass              0.022%
                             scale_robust_14   mass              0.058%
                             scale_power       mass              0.021%
                             scale_power_14    mass              0.058%
                             scale_quantile    mass              0.022%
                             scale_quantile_14 mass              0.058%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass                0.0%
                             mass_smaller_14   mass              0.002%
                             scale_standard    mass                0.0%
                             scale_standard_14 mass              0.002%
                             scale_robust      mass                0.0%
                             scale_robust_14   mass              0.002%
                             scale_power       mass                0.0%
                             scale_power_14    mass              0.002%
                             scale_quantile    mass                0.0%
                             scale_quantile_14 mass              0.002%

                                                                               CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9996414671007774
                             mass_smaller_14   mass              0.9999700313729203
                             scale_standard    mass              0.9995625272622929
                             scale_standard_14 mass              0.9999704066139526
                             scale_robust      mass              0.9995666476840903
                             scale_robust_14   mass              0.9999701104569542
                             scale_power       mass              0.9996158058322198
                             scale_power_14    mass              0.9999705306146504
                             scale_quantile    mass              0.9996008600501027
                             scale_quantile_14 mass              0.9999700030723048

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              37.398%
                             mass_smaller_14   mass              10.632%
                             scale_standard    mass              40.046%
                             scale_standard_14 mass              10.632%
                             scale_robust      mass              40.653%
                             scale_robust_14   mass              10.626%
                             scale_power       mass              36.887%
                             scale_power_14    mass              10.626%
                             scale_quantile    mass              39.062%
                             scale_quantile_14 mass              10.626%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                             mass_smaller_14   mass              75 : 0.043% / 90 : 0.176% / 95 : 0.262% / 99 : 0.659%
                             scale_standard    mass              75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                             scale_standard_14 mass              75 : 0.044% / 90 : 0.177% / 95 : 0.263% / 99 : 0.645%
                             scale_robust      mass              75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.265%
                             scale_robust_14   mass               75 : 0.044% / 90 : 0.175% / 95 : 0.26% / 99 : 0.644%
                             scale_power       mass              75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.263%
                             scale_power_14    mass                75 : 0.044% / 90 : 0.177% / 95 : 0.26% / 99 : 0.64%
                             scale_quantile    mass               75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.27%
                             scale_quantile_14 mass              75 : 0.044% / 90 : 0.178% / 95 : 0.262% / 99 : 0.645%

                                                                               time
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              24.898207902908325
                             mass_smaller_14   mass              18.880497217178345
                             scale_standard    mass              22.573050260543823
                             scale_standard_14 mass               18.01037335395813
                             scale_robust      mass              28.476685762405396
                             scale_robust_14   mass                20.0865695476532
                             scale_power       mass               35.47294616699219
                             scale_power_14    mass              27.994585514068604
                             scale_quantile    mass              26.211433172225952
                             scale_quantile_14 mass              20.181453704833984

Results for the phase category with a value of 3.0

                                                                                             value range  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass                0.5484495344916944 - 288.814589557117
                             mass_smaller_14   mass              0.5453736573627747 - 13.994428587385377
                             scale_standard    mass                0.5484495344916944 - 288.814589557117
                             scale_standard_14 mass              0.5453736573627747 - 13.994428587385377
                             scale_robust      mass                0.5484495344916944 - 288.814589557117
                             scale_robust_14   mass              0.5453736573627747 - 13.994428587385377
                             scale_power       mass                0.5484495344916944 - 288.814589557117
                             scale_power_14    mass              0.5453736573627747 - 13.994428587385377
                             scale_quantile    mass                0.5484495344916944 - 288.814589557117
                             scale_quantile_14 mass              0.5453736573627747 - 13.994428587385377

                                                                                RVE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9919676920924657
                             mass_smaller_14   mass              0.9994652103837574
                             scale_standard    mass              0.9920611009262763
                             scale_standard_14 mass              0.9994649887554127
                             scale_robust      mass              0.9919873011582692
                             scale_robust_14   mass              0.9994654263554836
                             scale_power       mass               0.991797859522694
                             scale_power_14    mass              0.9994680975436787
                             scale_quantile    mass              0.9921117147204533
                             scale_quantile_14 mass              0.9994610748746898

                                                                   RMSE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.721%
                             mass_smaller_14   mass              0.553%
                             scale_standard    mass              0.716%
                             scale_standard_14 mass              0.553%
                             scale_robust      mass               0.72%
                             scale_robust_14   mass              0.553%
                             scale_power       mass              0.728%
                             scale_power_14    mass              0.551%
                             scale_quantile    mass              0.714%
                             scale_quantile_14 mass              0.555%

                                                                    MAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.069%
                             mass_smaller_14   mass              0.198%
                             scale_standard    mass              0.069%
                             scale_standard_14 mass              0.198%
                             scale_robust      mass              0.069%
                             scale_robust_14   mass              0.198%
                             scale_power       mass               0.07%
                             scale_power_14    mass              0.198%
                             scale_quantile    mass              0.069%
                             scale_quantile_14 mass              0.199%

                                                                  MedAE  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.001%
                             mass_smaller_14   mass              0.022%
                             scale_standard    mass              0.001%
                             scale_standard_14 mass              0.022%
                             scale_robust      mass              0.001%
                             scale_robust_14   mass              0.022%
                             scale_power       mass              0.001%
                             scale_power_14    mass              0.022%
                             scale_quantile    mass              0.001%
                             scale_quantile_14 mass              0.022%

                                                                               CORR  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              0.9959955403728619
                             mass_smaller_14   mass               0.999733532743571
                             scale_standard    mass              0.9960468761786188
                             scale_standard_14 mass              0.9997334211813516
                             scale_robust      mass               0.996008518316001
                             scale_robust_14   mass              0.9997335008920833
                             scale_power       mass              0.9959085120345141
                             scale_power_14    mass              0.9997349701182686
                             scale_quantile    mass               0.996064307450966
                             scale_quantile_14 mass              0.9997313086708921

                                                                  MAX_ER  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               52.61%
                             mass_smaller_14   mass              17.875%
                             scale_standard    mass               52.61%
                             scale_standard_14 mass              18.965%
                             scale_robust      mass              51.498%
                             scale_robust_14   mass               18.73%
                             scale_power       mass               52.61%
                             scale_power_14    mass              18.184%
                             scale_quantile    mass               52.61%
                             scale_quantile_14 mass              18.965%

                                                                                                           Percentiles  \
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass               75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.61%
                             mass_smaller_14   mass              75 : 0.123% / 90 : 0.542% / 95 : 1.113% / 99 : 2.593%
                             scale_standard    mass              75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.609%
                             scale_standard_14 mass              75 : 0.123% / 90 : 0.544% / 95 : 1.124% / 99 : 2.593%
                             scale_robust      mass              75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.608%
                             scale_robust_14   mass               75 : 0.123% / 90 : 0.54% / 95 : 1.114% / 99 : 2.593%
                             scale_power       mass              75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.614%
                             scale_power_14    mass              75 : 0.123% / 90 : 0.543% / 95 : 1.121% / 99 : 2.593%
                             scale_quantile    mass              75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.581%
                             scale_quantile_14 mass              75 : 0.124% / 90 : 0.544% / 95 : 1.118% / 99 : 2.614%

                                                                               time
model         physical_model filter            output_parameter
decision_tree MIST           Base              mass              24.898207902908325
                             mass_smaller_14   mass              18.880497217178345
                             scale_standard    mass              22.573050260543823
                             scale_standard_14 mass               18.01037335395813
                             scale_robust      mass              28.476685762405396
                             scale_robust_14   mass                20.0865695476532
                             scale_power       mass               35.47294616699219
                             scale_power_14    mass              27.994585514068604
                             scale_quantile    mass              26.211433172225952
                             scale_quantile_14 mass              20.181453704833984

### Radius parameter

## Base vs scaling

### Mass parameter

In [8]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
KNN               MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
linear_regression MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
mlp               MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
random_forest     MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
xgboost           MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.9952703219364649
                                 scale_standard mass               0.9952101903329457
                                 scale_robust   mass               0.9952433722990285
                                 scale_power    mass               0.9952936910032032
                                 scale_quantile mass               0.9952909967064102
KNN               MIST           Base           mass               0.9895916504979603
                                 scale_standard mass               0.9937233908251109
                                 scale_robust   mass               0.9935602903980474
                                 scale_power    mass                0.993161017442078
                                 scale_quantile mass               0.9922127893374949
linear_regression MIST           Base           mass               0.3042271481418729
                                 scale_standard mass                0.304227148141873
                                 scale_robust   mass              0.30422714814187324
                                 scale_power    mass               0.2770155793065654
                                 scale_quantile mass               0.2730952731502987
mlp               MIST           Base           mass               0.9762913286039826
                                 scale_standard mass                0.987899524962762
                                 scale_robust   mass               0.9932245130635506
                                 scale_power    mass               0.9918853282774659
                                 scale_quantile mass               0.9864489738826718
random_forest     MIST           Base           mass               0.9978063351241271
                                 scale_standard mass               0.9978189830727664
                                 scale_robust   mass                0.997826601004703
                                 scale_power    mass               0.9978229070988179
                                 scale_quantile mass               0.9978166997821767
xgboost           MIST           Base           mass               0.9941191064217958
                                 scale_standard mass                 0.99415843402732
                                 scale_robust   mass               0.9941860418058858
                                 scale_power    mass               0.9941587684455183
                                 scale_quantile mass               0.9941560974933636

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.615%
                                 scale_standard mass              0.619%
                                 scale_robust   mass              0.617%
                                 scale_power    mass              0.614%
                                 scale_quantile mass              0.614%
KNN               MIST           Base           mass              0.913%
                                 scale_standard mass              0.709%
                                 scale_robust   mass              0.718%
                                 scale_power    mass               0.74%
                                 scale_quantile mass               0.79%
linear_regression MIST           Base           mass              7.465%
                                 scale_standard mass              7.465%
                                 scale_robust   mass              7.465%
                                 scale_power    mass               7.61%
                                 scale_quantile mass               7.63%
mlp               MIST           Base           mass              1.381%
                                 scale_standard mass              0.986%
                                 scale_robust   mass              0.737%
                                 scale_power    mass              0.808%
                                 scale_quantile mass              1.044%
random_forest     MIST           Base           mass              0.419%
                                 scale_standard mass              0.418%
                                 scale_robust   mass              0.417%
                                 scale_power    mass              0.418%
                                 scale_quantile mass              0.418%
xgboost           MIST           Base           mass              0.686%
                                 scale_standard mass              0.684%
                                 scale_robust   mass              0.682%
                                 scale_power    mass              0.684%
                                 scale_quantile mass              0.684%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.067%
                                 scale_standard mass              0.067%
                                 scale_robust   mass              0.067%
                                 scale_power    mass              0.067%
                                 scale_quantile mass              0.067%
KNN               MIST           Base           mass               0.11%
                                 scale_standard mass              0.089%
                                 scale_robust   mass              0.091%
                                 scale_power    mass              0.093%
                                 scale_quantile mass              0.094%
linear_regression MIST           Base           mass              3.801%
                                 scale_standard mass              3.801%
                                 scale_robust   mass              3.801%
                                 scale_power    mass              3.899%
                                 scale_quantile mass              3.917%
mlp               MIST           Base           mass              0.422%
                                 scale_standard mass              0.254%
                                 scale_robust   mass              0.214%
                                 scale_power    mass              0.212%
                                 scale_quantile mass              0.289%
random_forest     MIST           Base           mass              0.049%
                                 scale_standard mass              0.049%
                                 scale_robust   mass              0.049%
                                 scale_power    mass              0.049%
                                 scale_quantile mass              0.049%
xgboost           MIST           Base           mass              0.178%
                                 scale_standard mass              0.178%
                                 scale_robust   mass              0.178%
                                 scale_power    mass              0.178%
                                 scale_quantile mass              0.179%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.001%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
KNN               MIST           Base           mass              0.003%
                                 scale_standard mass              0.002%
                                 scale_robust   mass              0.002%
                                 scale_power    mass              0.002%
                                 scale_quantile mass              0.002%
linear_regression MIST           Base           mass              2.732%
                                 scale_standard mass              2.732%
                                 scale_robust   mass              2.732%
                                 scale_power    mass              2.901%
                                 scale_quantile mass              2.916%
mlp               MIST           Base           mass              0.115%
                                 scale_standard mass               0.05%
                                 scale_robust   mass              0.051%
                                 scale_power    mass              0.055%
                                 scale_quantile mass              0.077%
random_forest     MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.001%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
xgboost           MIST           Base           mass              0.033%
                                 scale_standard mass              0.033%
                                 scale_robust   mass              0.034%
                                 scale_power    mass              0.033%
                                 scale_quantile mass              0.034%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.9976339781841599
                                 scale_standard mass              0.9976039706275885
                                 scale_robust   mass              0.9976203894889993
                                 scale_power    mass              0.9976460939925359
                                 scale_quantile mass              0.9976454672833274
KNN               MIST           Base           mass              0.9948902170346177
                                 scale_standard mass              0.9968709231328967
                                 scale_robust   mass              0.9967907455954607
                                 scale_power    mass              0.9965938064385522
                                 scale_quantile mass              0.9961056281021186
linear_regression MIST           Base           mass              0.5515679007842895
                                 scale_standard mass              0.5515679007842897
                                 scale_robust   mass                0.55156790078429
                                 scale_power    mass              0.5263226960526849
                                 scale_quantile mass              0.5225851838844543
mlp               MIST           Base           mass              0.9881581645347787
                                 scale_standard mass              0.9940372912097557
                                 scale_robust   mass              0.9966356560442742
                                 scale_power    mass              0.9960685056655125
                                 scale_quantile mass              0.9932364455315007
random_forest     MIST           Base           mass              0.9989037560824912
                                 scale_standard mass              0.9989101118878894
                                 scale_robust   mass              0.9989139230116659
                                 scale_power    mass              0.9989119423942042
                                 scale_quantile mass              0.9989089577098539
xgboost           MIST           Base           mass              0.9970552947594146
                                 scale_standard mass              0.9970750949520054
                                 scale_robust   mass              0.9970889681523262
                                 scale_power    mass              0.9970752776914871
                                 scale_quantile mass              0.9970745111500644

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              50.816%
                                 scale_standard mass              50.816%
                                 scale_robust   mass              49.742%
                                 scale_power    mass              50.816%
                                 scale_quantile mass              50.816%
KNN               MIST           Base           mass              48.322%
                                 scale_standard mass              42.759%
                                 scale_robust   mass              45.135%
                                 scale_power    mass              67.984%
                                 scale_quantile mass              62.067%
linear_regression MIST           Base           mass              86.283%
                                 scale_standard mass              86.283%
                                 scale_robust   mass              86.283%
                                 scale_power    mass              88.276%
                                 scale_quantile mass              89.019%
mlp               MIST           Base           mass              58.569%
                                 scale_standard mass              38.412%
                                 scale_robust   mass              24.197%
                                 scale_power    mass              42.041%
                                 scale_quantile mass              70.769%
random_forest     MIST           Base           mass              32.158%
                                 scale_standard mass               32.26%
                                 scale_robust   mass              33.006%
                                 scale_power    mass              32.608%
                                 scale_quantile mass              32.421%
xgboost           MIST           Base           mass              24.445%
                                 scale_standard mass              25.293%
                                 scale_robust   mass              25.293%
                                 scale_power    mass              25.293%
                                 scale_quantile mass               30.23%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                                 scale_standard mass               75 : 0.007% / 90 : 0.035% / 95 : 0.119% / 99 : 1.525%
                                 scale_robust   mass               75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.524%
                                 scale_power    mass               75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.512%
                                 scale_quantile mass                75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.52%
KNN               MIST           Base           mass                75 : 0.013% / 90 : 0.07% / 95 : 0.236% / 99 : 2.302%
                                 scale_standard mass               75 : 0.011% / 90 : 0.056% / 95 : 0.183% / 99 : 1.983%
                                 scale_robust   mass               75 : 0.011% / 90 : 0.058% / 95 : 0.193% / 99 : 2.036%
                                 scale_power    mass                 75 : 0.011% / 90 : 0.06% / 95 : 0.205% / 99 : 2.09%
                                 scale_quantile mass                 75 : 0.01% / 90 : 0.05% / 95 : 0.184% / 99 : 2.084%
linear_regression MIST           Base           mass              75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 scale_standard mass              75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 scale_robust   mass              75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%

Results for the phase category with a value of 0.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
KNN               MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
linear_regression MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
mlp               MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
random_forest     MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816
xgboost           MIST           Base           mass              0.0999979840073621 - 298.5447575808816
                                 scale_standard mass              0.0999979840073621 - 298.5447575808816
                                 scale_robust   mass              0.0999979840073621 - 298.5447575808816
                                 scale_power    mass              0.0999979840073621 - 298.5447575808816
                                 scale_quantile mass              0.0999979840073621 - 298.5447575808816

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.9936340302001091
                                 scale_standard mass               0.9935933952260151
                                 scale_robust   mass               0.9936721398671367
                                 scale_power    mass               0.9937584584493031
                                 scale_quantile mass               0.9936853423995572
KNN               MIST           Base           mass               0.9843387655163102
                                 scale_standard mass               0.9933992332597192
                                 scale_robust   mass               0.9932932634026369
                                 scale_power    mass                0.992509635629161
                                 scale_quantile mass               0.9905000104675683
linear_regression MIST           Base           mass               0.2728709030098654
                                 scale_standard mass              0.27287090300986383
                                 scale_robust   mass               0.2728709030098607
                                 scale_power    mass              0.23962151037570645
                                 scale_quantile mass              0.22915297336788532
mlp               MIST           Base           mass               0.9717157238872854
                                 scale_standard mass               0.9838312171208503
                                 scale_robust   mass               0.9928618261439448
                                 scale_power    mass               0.9928570663963947
                                 scale_quantile mass               0.9866960390309141
random_forest     MIST           Base           mass               0.9973661987481759
                                 scale_standard mass               0.9973594767416726
                                 scale_robust   mass               0.9973939454997334
                                 scale_power    mass               0.9973698735789078
                                 scale_quantile mass               0.9973643192236208
xgboost           MIST           Base           mass               0.9910072956179956
                                 scale_standard mass               0.9911151824412604
                                 scale_robust   mass               0.9911465172719105
                                 scale_power    mass               0.9910987312588692
                                 scale_quantile mass               0.9911413312819737

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.703%
                                 scale_standard mass              0.705%
                                 scale_robust   mass              0.701%
                                 scale_power    mass              0.696%
                                 scale_quantile mass                0.7%
KNN               MIST           Base           mass              1.103%
                                 scale_standard mass              0.716%
                                 scale_robust   mass              0.722%
                                 scale_power    mass              0.763%
                                 scale_quantile mass              0.859%
linear_regression MIST           Base           mass              7.516%
                                 scale_standard mass              7.516%
                                 scale_robust   mass              7.516%
                                 scale_power    mass              7.686%
                                 scale_quantile mass              7.739%
mlp               MIST           Base           mass              1.484%
                                 scale_standard mass              1.121%
                                 scale_robust   mass              0.749%
                                 scale_power    mass              0.747%
                                 scale_quantile mass              1.019%
random_forest     MIST           Base           mass              0.452%
                                 scale_standard mass              0.453%
                                 scale_robust   mass               0.45%
                                 scale_power    mass              0.452%
                                 scale_quantile mass              0.453%
xgboost           MIST           Base           mass              0.836%
                                 scale_standard mass              0.831%
                                 scale_robust   mass              0.829%
                                 scale_power    mass              0.831%
                                 scale_quantile mass              0.829%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.09%
                                 scale_standard mass               0.09%
                                 scale_robust   mass               0.09%
                                 scale_power    mass               0.09%
                                 scale_quantile mass               0.09%
KNN               MIST           Base           mass              0.145%
                                 scale_standard mass                0.1%
                                 scale_robust   mass              0.103%
                                 scale_power    mass              0.111%
                                 scale_quantile mass              0.115%
linear_regression MIST           Base           mass              4.392%
                                 scale_standard mass              4.392%
                                 scale_robust   mass              4.392%
                                 scale_power    mass              4.387%
                                 scale_quantile mass              4.356%
mlp               MIST           Base           mass              0.467%
                                 scale_standard mass              0.264%
                                 scale_robust   mass              0.218%
                                 scale_power    mass              0.208%
                                 scale_quantile mass              0.312%
random_forest     MIST           Base           mass              0.056%
                                 scale_standard mass              0.056%
                                 scale_robust   mass              0.056%
                                 scale_power    mass              0.056%
                                 scale_quantile mass              0.056%
xgboost           MIST           Base           mass              0.227%
                                 scale_standard mass              0.227%
                                 scale_robust   mass              0.227%
                                 scale_power    mass              0.227%
                                 scale_quantile mass              0.227%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.002%
                                 scale_standard mass              0.002%
                                 scale_robust   mass              0.002%
                                 scale_power    mass              0.002%
                                 scale_quantile mass              0.002%
KNN               MIST           Base           mass              0.003%
                                 scale_standard mass              0.002%
                                 scale_robust   mass              0.002%
                                 scale_power    mass              0.002%
                                 scale_quantile mass              0.003%
linear_regression MIST           Base           mass              3.771%
                                 scale_standard mass              3.771%
                                 scale_robust   mass              3.771%
                                 scale_power    mass              3.651%
                                 scale_quantile mass              3.579%
mlp               MIST           Base           mass              0.124%
                                 scale_standard mass              0.045%
                                 scale_robust   mass              0.051%
                                 scale_power    mass              0.049%
                                 scale_quantile mass              0.081%
random_forest     MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.001%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
xgboost           MIST           Base           mass              0.042%
                                 scale_standard mass              0.042%
                                 scale_robust   mass              0.043%
                                 scale_power    mass              0.042%
                                 scale_quantile mass              0.043%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.9968269721840094
                                 scale_standard mass               0.9968085002700635
                                 scale_robust   mass               0.9968467350115852
                                 scale_power    mass               0.9968912616444416
                                 scale_quantile mass               0.9968582092538901
KNN               MIST           Base           mass               0.9924111983284241
                                 scale_standard mass                0.996789698408736
                                 scale_robust   mass               0.9967472328950062
                                 scale_power    mass               0.9963578989313132
                                 scale_quantile mass               0.9952928819657935
linear_regression MIST           Base           mass               0.5343027371731521
                                 scale_standard mass               0.5343027371731519
                                 scale_robust   mass               0.5343027371731518
                                 scale_power    mass               0.5007752690272543
                                 scale_quantile mass              0.48939493352978375
mlp               MIST           Base           mass               0.9860617427522443
                                 scale_standard mass               0.9919889807862203
                                 scale_robust   mass                0.996656567169858
                                 scale_power    mass               0.9964366880967247
                                 scale_quantile mass               0.9934505200261949
random_forest     MIST           Base           mass               0.9986840004415223
                                 scale_standard mass                0.998680579716905
                                 scale_robust   mass               0.9986977751621089
                                 scale_power    mass               0.9986859998912465
                                 scale_quantile mass               0.9986828641899517
xgboost           MIST           Base           mass               0.9955145412428942
                                 scale_standard mass               0.9955691053693145
                                 scale_robust   mass               0.9955836103839013
                                 scale_power    mass               0.9955610707335958
                                 scale_quantile mass               0.9955746789627763

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              44.154%
                                 scale_standard mass              44.154%
                                 scale_robust   mass              41.604%
                                 scale_power    mass              44.154%
                                 scale_quantile mass              44.154%
KNN               MIST           Base           mass              42.445%
                                 scale_standard mass              33.317%
                                 scale_robust   mass              33.317%
                                 scale_power    mass              33.317%
                                 scale_quantile mass              36.336%
linear_regression MIST           Base           mass              86.283%
                                 scale_standard mass              86.283%
                                 scale_robust   mass              86.283%
                                 scale_power    mass              88.276%
                                 scale_quantile mass              89.019%
mlp               MIST           Base           mass              36.763%
                                 scale_standard mass              38.412%
                                 scale_robust   mass              20.301%
                                 scale_power    mass              19.004%
                                 scale_quantile mass              42.247%
random_forest     MIST           Base           mass              27.991%
                                 scale_standard mass              28.027%
                                 scale_robust   mass              27.746%
                                 scale_power    mass              27.716%
                                 scale_quantile mass              27.984%
xgboost           MIST           Base           mass              24.445%
                                 scale_standard mass              25.293%
                                 scale_robust   mass              25.293%
                                 scale_power    mass              25.293%
                                 scale_quantile mass              29.751%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass                75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.993%
                                 scale_standard mass                75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.981%
                                 scale_robust   mass                75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.966%
                                 scale_power    mass                75 : 0.01% / 90 : 0.062% / 95 : 0.225% / 99 : 1.963%
                                 scale_quantile mass                75 : 0.01% / 90 : 0.062% / 95 : 0.224% / 99 : 1.966%
KNN               MIST           Base           mass               75 : 0.017% / 90 : 0.112% / 95 : 0.345% / 99 : 2.996%
                                 scale_standard mass               75 : 0.012% / 90 : 0.073% / 95 : 0.228% / 99 : 2.321%
                                 scale_robust   mass               75 : 0.013% / 90 : 0.078% / 95 : 0.242% / 99 : 2.373%
                                 scale_power    mass               75 : 0.013% / 90 : 0.089% / 95 : 0.284% / 99 : 2.541%
                                 scale_quantile mass               75 : 0.012% / 90 : 0.067% / 95 : 0.272% / 99 : 2.635%
linear_regression MIST           Base           mass              75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%
                                 scale_standard mass              75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%
                                 scale_robust   mass              75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%

Results for the phase category with a value of 2.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483
KNN               MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483
linear_regression MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483
mlp               MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483
random_forest     MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483
xgboost           MIST           Base           mass              0.6538581961218565 - 283.72102985530483
                                 scale_standard mass              0.6538581961218565 - 283.72102985530483
                                 scale_robust   mass              0.6538581961218565 - 283.72102985530483
                                 scale_power    mass              0.6538581961218565 - 283.72102985530483
                                 scale_quantile mass              0.6538581961218565 - 283.72102985530483

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.9992828062113351
                                 scale_standard mass               0.9991249538679495
                                 scale_robust   mass               0.9991330923578028
                                 scale_power    mass               0.9992314927358148
                                 scale_quantile mass               0.9992015439276027
KNN               MIST           Base           mass               0.9993836364150782
                                 scale_standard mass               0.9994093879705608
                                 scale_robust   mass               0.9993692632118909
                                 scale_power    mass               0.9994525162907033
                                 scale_quantile mass               0.9993816647987996
linear_regression MIST           Base           mass               0.3168817813892185
                                 scale_standard mass               0.3168817813892202
                                 scale_robust   mass              0.31688178138922396
                                 scale_power    mass               0.2966175810286509
                                 scale_quantile mass              0.30075995262325006
mlp               MIST           Base           mass                0.990929974425174
                                 scale_standard mass               0.9953629704832989
                                 scale_robust   mass               0.9960907814097686
                                 scale_power    mass               0.9930856960543955
                                 scale_quantile mass               0.9965522145956819
random_forest     MIST           Base           mass               0.9997496322236138
                                 scale_standard mass               0.9997458334941093
                                 scale_robust   mass               0.9997472754685565
                                 scale_power    mass               0.9997462583266511
                                 scale_quantile mass               0.9997423050066863
xgboost           MIST           Base           mass               0.9988754736593098
                                 scale_standard mass               0.9988446771989671
                                 scale_robust   mass               0.9988551789361841
                                 scale_power    mass               0.9988417935213513
                                 scale_quantile mass               0.9987895823412088

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.281%
                                 scale_standard mass               0.31%
                                 scale_robust   mass              0.309%
                                 scale_power    mass              0.291%
                                 scale_quantile mass              0.296%
KNN               MIST           Base           mass               0.26%
                                 scale_standard mass              0.255%
                                 scale_robust   mass              0.263%
                                 scale_power    mass              0.245%
                                 scale_quantile mass              0.261%
linear_regression MIST           Base           mass               8.67%
                                 scale_standard mass               8.67%
                                 scale_robust   mass               8.67%
                                 scale_power    mass              8.798%
                                 scale_quantile mass              8.772%
mlp               MIST           Base           mass                1.0%
                                 scale_standard mass              0.717%
                                 scale_robust   mass              0.656%
                                 scale_power    mass              0.877%
                                 scale_quantile mass              0.617%
random_forest     MIST           Base           mass              0.166%
                                 scale_standard mass              0.167%
                                 scale_robust   mass              0.167%
                                 scale_power    mass              0.167%
                                 scale_quantile mass              0.168%
xgboost           MIST           Base           mass              0.352%
                                 scale_standard mass              0.357%
                                 scale_robust   mass              0.355%
                                 scale_power    mass              0.357%
                                 scale_quantile mass              0.365%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.021%
                                 scale_standard mass              0.022%
                                 scale_robust   mass              0.022%
                                 scale_power    mass              0.021%
                                 scale_quantile mass              0.022%
KNN               MIST           Base           mass              0.034%
                                 scale_standard mass              0.031%
                                 scale_robust   mass              0.033%
                                 scale_power    mass              0.029%
                                 scale_quantile mass              0.029%
linear_regression MIST           Base           mass              3.616%
                                 scale_standard mass              3.616%
                                 scale_robust   mass              3.616%
                                 scale_power    mass              3.829%
                                 scale_quantile mass              3.895%
mlp               MIST           Base           mass              0.324%
                                 scale_standard mass              0.229%
                                 scale_robust   mass              0.195%
                                 scale_power    mass              0.206%
                                 scale_quantile mass               0.21%
random_forest     MIST           Base           mass              0.021%
                                 scale_standard mass              0.021%
                                 scale_robust   mass              0.021%
                                 scale_power    mass              0.021%
                                 scale_quantile mass              0.021%
xgboost           MIST           Base           mass              0.104%
                                 scale_standard mass              0.105%
                                 scale_robust   mass              0.105%
                                 scale_power    mass              0.105%
                                 scale_quantile mass              0.107%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass                0.0%
                                 scale_standard mass                0.0%
                                 scale_robust   mass                0.0%
                                 scale_power    mass                0.0%
                                 scale_quantile mass                0.0%
KNN               MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.002%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
linear_regression MIST           Base           mass              1.861%
                                 scale_standard mass              1.861%
                                 scale_robust   mass              1.861%
                                 scale_power    mass              2.339%
                                 scale_quantile mass              2.455%
mlp               MIST           Base           mass              0.106%
                                 scale_standard mass              0.059%
                                 scale_robust   mass              0.051%
                                 scale_power    mass              0.061%
                                 scale_quantile mass              0.074%
random_forest     MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.001%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
xgboost           MIST           Base           mass              0.025%
                                 scale_standard mass              0.025%
                                 scale_robust   mass              0.025%
                                 scale_power    mass              0.025%
                                 scale_quantile mass              0.026%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.9996414671007774
                                 scale_standard mass              0.9995625272622929
                                 scale_robust   mass              0.9995666476840903
                                 scale_power    mass              0.9996158058322198
                                 scale_quantile mass              0.9996008600501027
KNN               MIST           Base           mass              0.9996927065174758
                                 scale_standard mass              0.9997046504657136
                                 scale_robust   mass              0.9996845845047237
                                 scale_power    mass              0.9997262206887632
                                 scale_quantile mass              0.9996910307263401
linear_regression MIST           Base           mass              0.5956286032810738
                                 scale_standard mass              0.5956286032810738
                                 scale_robust   mass              0.5956286032810741
                                 scale_power    mass              0.5748569584004691
                                 scale_quantile mass               0.574908463952895
mlp               MIST           Base           mass              0.9955996860365472
                                 scale_standard mass              0.9977086617208759
                                 scale_robust   mass               0.998043640605636
                                 scale_power    mass              0.9972029218783641
                                 scale_quantile mass               0.998291554520482
random_forest     MIST           Base           mass              0.9998754804643019
                                 scale_standard mass              0.9998736309325185
                                 scale_robust   mass              0.9998742090282583
                                 scale_power    mass              0.9998737882353769
                                 scale_quantile mass              0.9998717674733442
xgboost           MIST           Base           mass              0.9994709362034415
                                 scale_standard mass              0.9994589461087611
                                 scale_robust   mass               0.999462981882696
                                 scale_power    mass              0.9994585536328132
                                 scale_quantile mass              0.9994306690250524

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              37.398%
                                 scale_standard mass              40.046%
                                 scale_robust   mass              40.653%
                                 scale_power    mass              36.887%
                                 scale_quantile mass              39.062%
KNN               MIST           Base           mass              13.243%
                                 scale_standard mass              13.243%
                                 scale_robust   mass              13.243%
                                 scale_power    mass              13.243%
                                 scale_quantile mass                15.4%
linear_regression MIST           Base           mass              87.305%
                                 scale_standard mass              87.305%
                                 scale_robust   mass              87.305%
                                 scale_power    mass              87.882%
                                 scale_quantile mass              87.744%
mlp               MIST           Base           mass              22.957%
                                 scale_standard mass              19.386%
                                 scale_robust   mass              13.259%
                                 scale_power    mass              28.809%
                                 scale_quantile mass              17.498%
random_forest     MIST           Base           mass               8.119%
                                 scale_standard mass               6.227%
                                 scale_robust   mass               6.314%
                                 scale_power    mass               8.491%
                                 scale_quantile mass               8.282%
xgboost           MIST           Base           mass               13.82%
                                 scale_standard mass              14.746%
                                 scale_robust   mass              14.746%
                                 scale_power    mass              14.746%
                                 scale_quantile mass              19.699%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                                 scale_standard mass               75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                                 scale_robust   mass               75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.265%
                                 scale_power    mass               75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.263%
                                 scale_quantile mass                75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.27%
KNN               MIST           Base           mass               75 : 0.006% / 90 : 0.028% / 95 : 0.057% / 99 : 0.751%
                                 scale_standard mass               75 : 0.006% / 90 : 0.028% / 95 : 0.058% / 99 : 0.713%
                                 scale_robust   mass               75 : 0.006% / 90 : 0.028% / 95 : 0.059% / 99 : 0.753%
                                 scale_power    mass               75 : 0.006% / 90 : 0.027% / 95 : 0.056% / 99 : 0.602%
                                 scale_quantile mass               75 : 0.006% / 90 : 0.027% / 95 : 0.056% / 99 : 0.569%
linear_regression MIST           Base           mass                 75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%
                                 scale_standard mass                 75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%
                                 scale_robust   mass                 75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%

Results for the phase category with a value of 3.0

                                                                                            value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117
KNN               MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117
linear_regression MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117
mlp               MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117
random_forest     MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117
xgboost           MIST           Base           mass              0.5484495344916944 - 288.814589557117
                                 scale_standard mass              0.5484495344916944 - 288.814589557117
                                 scale_robust   mass              0.5484495344916944 - 288.814589557117
                                 scale_power    mass              0.5484495344916944 - 288.814589557117
                                 scale_quantile mass              0.5484495344916944 - 288.814589557117

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               0.9919676920924657
                                 scale_standard mass               0.9920611009262763
                                 scale_robust   mass               0.9919873011582692
                                 scale_power    mass                0.991797859522694
                                 scale_quantile mass               0.9921117147204533
KNN               MIST           Base           mass               0.9860770182495742
                                 scale_standard mass               0.9818702932254654
                                 scale_robust   mass               0.9812203995560788
                                 scale_power    mass               0.9810949015482093
                                 scale_quantile mass               0.9819508320223167
linear_regression MIST           Base           mass              0.38830292902171926
                                 scale_standard mass               0.3883029290217215
                                 scale_robust   mass              0.38830292902172525
                                 scale_power    mass               0.3676919774521994
                                 scale_quantile mass              0.36864768231042655
mlp               MIST           Base           mass               0.9593548446204826
                                 scale_standard mass               0.9854792558357883
                                 scale_robust   mass               0.9883293561541393
                                 scale_power    mass               0.9856480906108916
                                 scale_quantile mass               0.9623985090953352
random_forest     MIST           Base           mass               0.9949439900825313
                                 scale_standard mass               0.9950640492557127
                                 scale_robust   mass               0.9949891698671909
                                 scale_power    mass               0.9950529454549064
                                 scale_quantile mass               0.9950389515233471
xgboost           MIST           Base           mass               0.9944238807426196
                                 scale_standard mass               0.9943770439147128
                                 scale_robust   mass               0.9944302446836073
                                 scale_power    mass               0.9944453594997158
                                 scale_quantile mass               0.9943922336613822

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.721%
                                 scale_standard mass              0.716%
                                 scale_robust   mass               0.72%
                                 scale_power    mass              0.728%
                                 scale_quantile mass              0.714%
KNN               MIST           Base           mass              0.949%
                                 scale_standard mass              1.083%
                                 scale_robust   mass              1.102%
                                 scale_power    mass              1.105%
                                 scale_quantile mass               1.08%
linear_regression MIST           Base           mass              6.301%
                                 scale_standard mass              6.301%
                                 scale_robust   mass              6.301%
                                 scale_power    mass              6.408%
                                 scale_quantile mass              6.402%
mlp               MIST           Base           mass              1.631%
                                 scale_standard mass              0.973%
                                 scale_robust   mass              0.872%
                                 scale_power    mass              0.963%
                                 scale_quantile mass               1.56%
random_forest     MIST           Base           mass              0.572%
                                 scale_standard mass              0.565%
                                 scale_robust   mass              0.569%
                                 scale_power    mass              0.566%
                                 scale_quantile mass              0.566%
xgboost           MIST           Base           mass                0.6%
                                 scale_standard mass              0.603%
                                 scale_robust   mass                0.6%
                                 scale_power    mass              0.599%
                                 scale_quantile mass              0.602%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.069%
                                 scale_standard mass              0.069%
                                 scale_robust   mass              0.069%
                                 scale_power    mass               0.07%
                                 scale_quantile mass              0.069%
KNN               MIST           Base           mass              0.126%
                                 scale_standard mass              0.146%
                                 scale_robust   mass              0.148%
                                 scale_power    mass              0.139%
                                 scale_quantile mass               0.13%
linear_regression MIST           Base           mass              2.762%
                                 scale_standard mass              2.762%
                                 scale_robust   mass              2.762%
                                 scale_power    mass              3.011%
                                 scale_quantile mass              3.103%
mlp               MIST           Base           mass              0.475%
                                 scale_standard mass              0.287%
                                 scale_robust   mass              0.252%
                                 scale_power    mass              0.254%
                                 scale_quantile mass              0.363%
random_forest     MIST           Base           mass               0.07%
                                 scale_standard mass               0.07%
                                 scale_robust   mass               0.07%
                                 scale_power    mass               0.07%
                                 scale_quantile mass               0.07%
xgboost           MIST           Base           mass              0.157%
                                 scale_standard mass              0.157%
                                 scale_robust   mass              0.157%
                                 scale_power    mass              0.156%
                                 scale_quantile mass              0.156%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.001%
                                 scale_standard mass              0.001%
                                 scale_robust   mass              0.001%
                                 scale_power    mass              0.001%
                                 scale_quantile mass              0.001%
KNN               MIST           Base           mass              0.004%
                                 scale_standard mass              0.003%
                                 scale_robust   mass              0.003%
                                 scale_power    mass              0.002%
                                 scale_quantile mass              0.002%
linear_regression MIST           Base           mass              1.595%
                                 scale_standard mass              1.595%
                                 scale_robust   mass              1.595%
                                 scale_power    mass              1.817%
                                 scale_quantile mass              1.949%
mlp               MIST           Base           mass              0.115%
                                 scale_standard mass              0.061%
                                 scale_robust   mass              0.054%
                                 scale_power    mass              0.068%
                                 scale_quantile mass               0.08%
random_forest     MIST           Base           mass              0.002%
                                 scale_standard mass              0.002%
                                 scale_robust   mass              0.002%
                                 scale_power    mass              0.002%
                                 scale_quantile mass              0.002%
xgboost           MIST           Base           mass              0.032%
                                 scale_standard mass              0.033%
                                 scale_robust   mass              0.033%
                                 scale_power    mass              0.033%
                                 scale_quantile mass              0.033%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass              0.9959955403728619
                                 scale_standard mass              0.9960468761786188
                                 scale_robust   mass               0.996008518316001
                                 scale_power    mass              0.9959085120345141
                                 scale_quantile mass               0.996064307450966
KNN               MIST           Base           mass              0.9931315041563596
                                 scale_standard mass              0.9909727541870841
                                 scale_robust   mass              0.9906498316389118
                                 scale_power    mass              0.9905544079568468
                                 scale_quantile mass              0.9909846611048783
linear_regression MIST           Base           mass              0.6497333100274104
                                 scale_standard mass              0.6497333100274102
                                 scale_robust   mass              0.6497333100274099
                                 scale_power    mass              0.6242879898653226
                                 scale_quantile mass              0.6200196410823045
mlp               MIST           Base           mass              0.9801734298207664
                                 scale_standard mass              0.9931554770688498
                                 scale_robust   mass               0.994425862467256
                                 scale_power    mass              0.9928582985660525
                                 scale_quantile mass              0.9811176086131866
random_forest     MIST           Base           mass              0.9975811556691733
                                 scale_standard mass              0.9976398742682272
                                 scale_robust   mass              0.9976048143594032
                                 scale_power    mass              0.9976328829291768
                                 scale_quantile mass              0.9976252374440928
xgboost           MIST           Base           mass              0.9972366154162345
                                 scale_standard mass              0.9972164501895486
                                 scale_robust   mass              0.9972429184075343
                                 scale_power    mass              0.9972509540484696
                                 scale_quantile mass              0.9972248477030711

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass               52.61%
                                 scale_standard mass               52.61%
                                 scale_robust   mass              51.498%
                                 scale_power    mass               52.61%
                                 scale_quantile mass               52.61%
KNN               MIST           Base           mass              50.028%
                                 scale_standard mass              44.269%
                                 scale_robust   mass              46.728%
                                 scale_power    mass              70.384%
                                 scale_quantile mass              64.259%
linear_regression MIST           Base           mass              87.044%
                                 scale_standard mass              87.044%
                                 scale_robust   mass              87.044%
                                 scale_power    mass              88.171%
                                 scale_quantile mass                88.2%
mlp               MIST           Base           mass              60.637%
                                 scale_standard mass              31.913%
                                 scale_robust   mass              25.051%
                                 scale_power    mass              43.525%
                                 scale_quantile mass              73.268%
random_forest     MIST           Base           mass              33.293%
                                 scale_standard mass              33.399%
                                 scale_robust   mass              34.171%
                                 scale_power    mass              33.759%
                                 scale_quantile mass              33.565%
xgboost           MIST           Base           mass              21.469%
                                 scale_standard mass              22.923%
                                 scale_robust   mass              22.923%
                                 scale_power    mass              22.923%
                                 scale_quantile mass              31.297%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           mass                75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.61%
                                 scale_standard mass               75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.609%
                                 scale_robust   mass               75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.608%
                                 scale_power    mass               75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.614%
                                 scale_quantile mass               75 : 0.008% / 90 : 0.039% / 95 : 0.094% / 99 : 1.581%
KNN               MIST           Base           mass                 75 : 0.02% / 90 : 0.085% / 95 : 0.29% / 99 : 2.888%
                                 scale_standard mass                75 : 0.018% / 90 : 0.086% / 95 : 0.312% / 99 : 3.58%
                                 scale_robust   mass                75 : 0.019% / 90 : 0.09% / 95 : 0.317% / 99 : 3.586%
                                 scale_power    mass               75 : 0.016% / 90 : 0.084% / 95 : 0.297% / 99 : 3.163%
                                 scale_quantile mass               75 : 0.014% / 90 : 0.073% / 95 : 0.269% / 99 : 2.948%
linear_regression MIST           Base           mass               75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 scale_standard mass               75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 scale_robust   mass               75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 scale_power    mass              75 : 3.672% / 90 : 5.039% / 95 : 6.543% / 99 : 28.399%

### Radius parameter

In [4]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
KNN               MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
linear_regression MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
mlp               MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
random_forest     MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593
xgboost           MIST           Base           radius            -0.9974628481553472 - 3.129269620812593
                                 scale_standard radius            -0.9974628481553472 - 3.129269620812593
                                 scale_robust   radius            -0.9974628481553472 - 3.129269620812593
                                 scale_power    radius            -0.9974628481553472 - 3.129269620812593
                                 scale_quantile radius            -0.9974628481553472 - 3.129269620812593

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9997963432259059
                                 scale_standard radius            0.9997970778998158
                                 scale_robust   radius            0.9997967216755778
                                 scale_power    radius             0.999795901919137
                                 scale_quantile radius             0.999800198997274
KNN               MIST           Base           radius            0.9998970891526346
                                 scale_standard radius            0.9999126166900904
                                 scale_robust   radius             0.999914617395041
                                 scale_power    radius            0.9999050940243499
                                 scale_quantile radius            0.9998603666103043
linear_regression MIST           Base           radius            0.9854956623390955
                                 scale_standard radius            0.9854956623390955
                                 scale_robust   radius            0.9854956623390956
                                 scale_power    radius             0.965347382496725
                                 scale_quantile radius             0.942449647484239
mlp               MIST           Base           radius            0.9923727221026404
                                 scale_standard radius            0.9928827073789572
                                 scale_robust   radius            0.9934046470298077
                                 scale_power    radius             0.987767167996969
                                 scale_quantile radius            0.9778907542833467
random_forest     MIST           Base           radius            0.9999434532448489
                                 scale_standard radius            0.9999432902372344
                                 scale_robust   radius            0.9999433234624143
                                 scale_power    radius            0.9999436998773278
                                 scale_quantile radius            0.9999429272954269
xgboost           MIST           Base           radius            0.9996020484794627
                                 scale_standard radius            0.9996003371877072
                                 scale_robust   radius            0.9995997102153606
                                 scale_power    radius            0.9995989953037001
                                 scale_quantile radius            0.9995956901351262

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.255%
                                 scale_standard radius            0.255%
                                 scale_robust   radius            0.255%
                                 scale_power    radius            0.256%
                                 scale_quantile radius            0.253%
KNN               MIST           Base           radius            0.181%
                                 scale_standard radius            0.167%
                                 scale_robust   radius            0.165%
                                 scale_power    radius            0.174%
                                 scale_quantile radius            0.211%
linear_regression MIST           Base           radius            2.154%
                                 scale_standard radius            2.154%
                                 scale_robust   radius            2.154%
                                 scale_power    radius            3.329%
                                 scale_quantile radius             4.29%
mlp               MIST           Base           radius            1.593%
                                 scale_standard radius            1.511%
                                 scale_robust   radius            1.458%
                                 scale_power    radius            1.986%
                                 scale_quantile radius            2.678%
random_forest     MIST           Base           radius            0.134%
                                 scale_standard radius            0.135%
                                 scale_robust   radius            0.135%
                                 scale_power    radius            0.134%
                                 scale_quantile radius            0.135%
xgboost           MIST           Base           radius            0.357%
                                 scale_standard radius            0.358%
                                 scale_robust   radius            0.358%
                                 scale_power    radius            0.358%
                                 scale_quantile radius             0.36%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.142%
                                 scale_standard radius            0.142%
                                 scale_robust   radius            0.142%
                                 scale_power    radius            0.141%
                                 scale_quantile radius            0.141%
KNN               MIST           Base           radius            0.102%
                                 scale_standard radius            0.095%
                                 scale_robust   radius            0.094%
                                 scale_power    radius            0.099%
                                 scale_quantile radius            0.114%
linear_regression MIST           Base           radius            1.569%
                                 scale_standard radius            1.569%
                                 scale_robust   radius            1.569%
                                 scale_power    radius            2.546%
                                 scale_quantile radius            3.259%
mlp               MIST           Base           radius            1.218%
                                 scale_standard radius            1.142%
                                 scale_robust   radius            1.055%
                                 scale_power    radius            1.471%
                                 scale_quantile radius            1.961%
random_forest     MIST           Base           radius            0.065%
                                 scale_standard radius            0.065%
                                 scale_robust   radius            0.065%
                                 scale_power    radius            0.065%
                                 scale_quantile radius            0.066%
xgboost           MIST           Base           radius            0.258%
                                 scale_standard radius            0.258%
                                 scale_robust   radius            0.258%
                                 scale_power    radius            0.259%
                                 scale_quantile radius             0.26%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.082%
                                 scale_standard radius            0.082%
                                 scale_robust   radius            0.082%
                                 scale_power    radius            0.082%
                                 scale_quantile radius            0.082%
KNN               MIST           Base           radius            0.063%
                                 scale_standard radius             0.06%
                                 scale_robust   radius             0.06%
                                 scale_power    radius             0.06%
                                 scale_quantile radius             0.06%
linear_regression MIST           Base           radius            1.113%
                                 scale_standard radius            1.113%
                                 scale_robust   radius            1.113%
                                 scale_power    radius             2.18%
                                 scale_quantile radius              2.7%
mlp               MIST           Base           radius            0.968%
                                 scale_standard radius            0.902%
                                 scale_robust   radius            0.817%
                                 scale_power    radius             1.13%
                                 scale_quantile radius            1.495%
random_forest     MIST           Base           radius            0.032%
                                 scale_standard radius            0.032%
                                 scale_robust   radius            0.032%
                                 scale_power    radius            0.032%
                                 scale_quantile radius            0.032%
xgboost           MIST           Base           radius            0.197%
                                 scale_standard radius            0.197%
                                 scale_robust   radius            0.197%
                                 scale_power    radius            0.197%
                                 scale_quantile radius            0.198%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9998982041053214
                                 scale_standard radius            0.9998985783346532
                                 scale_robust   radius             0.999898394191467
                                 scale_power    radius             0.999897988280451
                                 scale_quantile radius            0.9999001106650659
KNN               MIST           Base           radius            0.9999485752530637
                                 scale_standard radius            0.9999563190265183
                                 scale_robust   radius            0.9999573158676766
                                 scale_power    radius            0.9999525458863895
                                 scale_quantile radius            0.9999301857671464
linear_regression MIST           Base           radius            0.9927213417365519
                                 scale_standard radius            0.9927213417365518
                                 scale_robust   radius            0.9927213417365518
                                 scale_power    radius            0.9825209323453429
                                 scale_quantile radius            0.9707984587539031
mlp               MIST           Base           radius            0.9961795022934663
                                 scale_standard radius            0.9965016132439974
                                 scale_robust   radius            0.9967095739335421
                                 scale_power    radius            0.9939133656313248
                                 scale_quantile radius            0.9888974979242546
random_forest     MIST           Base           radius            0.9999717265543759
                                 scale_standard radius            0.9999716447815729
                                 scale_robust   radius            0.9999716614757965
                                 scale_power    radius             0.999971849730217
                                 scale_quantile radius            0.9999714633062002
xgboost           MIST           Base           radius            0.9998010225765576
                                 scale_standard radius            0.9998001667421064
                                 scale_robust   radius            0.9997998509505435
                                 scale_power    radius            0.9997994940056831
                                 scale_quantile radius            0.9997978434809209

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            11.591%
                                 scale_standard radius            11.591%
                                 scale_robust   radius            11.591%
                                 scale_power    radius            11.824%
                                 scale_quantile radius            11.591%
KNN               MIST           Base           radius             7.445%
                                 scale_standard radius             7.445%
                                 scale_robust   radius             7.445%
                                 scale_power    radius             9.692%
                                 scale_quantile radius             8.869%
linear_regression MIST           Base           radius            12.724%
                                 scale_standard radius            12.724%
                                 scale_robust   radius            12.724%
                                 scale_power    radius            24.305%
                                 scale_quantile radius            27.221%
mlp               MIST           Base           radius            14.074%
                                 scale_standard radius            17.457%
                                 scale_robust   radius            21.564%
                                 scale_power    radius            19.295%
                                 scale_quantile radius            21.929%
random_forest     MIST           Base           radius             8.676%
                                 scale_standard radius             9.742%
                                 scale_robust   radius             9.163%
                                 scale_power    radius             8.608%
                                 scale_quantile radius             9.019%
xgboost           MIST           Base           radius            11.866%
                                 scale_standard radius            11.243%
                                 scale_robust   radius            12.376%
                                 scale_power    radius            12.382%
                                 scale_quantile radius            10.022%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             75 : 0.175% / 90 : 0.315% / 95 : 0.443% / 99 : 0.975%
                                 scale_standard radius             75 : 0.175% / 90 : 0.315% / 95 : 0.444% / 99 : 0.973%
                                 scale_robust   radius             75 : 0.175% / 90 : 0.315% / 95 : 0.444% / 99 : 0.974%
                                 scale_power    radius             75 : 0.175% / 90 : 0.315% / 95 : 0.442% / 99 : 0.973%
                                 scale_quantile radius             75 : 0.175% / 90 : 0.315% / 95 : 0.442% / 99 : 0.972%
KNN               MIST           Base           radius             75 : 0.124% / 90 : 0.223% / 95 : 0.309% / 99 : 0.655%
                                 scale_standard radius              75 : 0.117% / 90 : 0.208% / 95 : 0.29% / 99 : 0.597%
                                 scale_robust   radius             75 : 0.115% / 90 : 0.203% / 95 : 0.282% / 99 : 0.588%
                                 scale_power    radius              75 : 0.122% / 90 : 0.22% / 95 : 0.309% / 99 : 0.626%
                                 scale_quantile radius             75 : 0.133% / 90 : 0.264% / 95 : 0.396% / 99 : 0.842%
linear_regression MIST           Base           radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 scale_standard radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 scale_robust   radius             75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base           radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_standard radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_robust   radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_power    radius            -0.9974628481553472 - 3.0827540579576227
                                 scale_quantile radius            -0.9974628481553472 - 3.0827540579576227

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9997790154053315
                                 scale_standard radius            0.9997812436032391
                                 scale_robust   radius            0.9997812953170327
                                 scale_power    radius            0.9997836068122534
                                 scale_quantile radius            0.9997847542449331
KNN               MIST           Base           radius            0.9998333563537635
                                 scale_standard radius            0.9999041966145369
                                 scale_robust   radius            0.9999061433404434
                                 scale_power    radius            0.9999123068864648
                                 scale_quantile radius            0.9998577763461787
linear_regression MIST           Base           radius            0.9778146729622458
                                 scale_standard radius            0.9778146729622449
                                 scale_robust   radius            0.9778146729622429
                                 scale_power    radius            0.9544928392458343
                                 scale_quantile radius            0.9177461475823924
mlp               MIST           Base           radius            0.9874097628400822
                                 scale_standard radius            0.9878229223304492
                                 scale_robust   radius            0.9880178458443394
                                 scale_power    radius             0.980163499329707
                                 scale_quantile radius              0.97026570882368
random_forest     MIST           Base           radius            0.9999465508573717
                                 scale_standard radius            0.9999459020923055
                                 scale_robust   radius            0.9999463946435571
                                 scale_power    radius            0.9999461523890759
                                 scale_quantile radius            0.9999457010003017
xgboost           MIST           Base           radius            0.9994380170169319
                                 scale_standard radius            0.9994418047471755
                                 scale_robust   radius            0.9994435589406726
                                 scale_power    radius            0.9994434633557444
                                 scale_quantile radius            0.9994280715440016

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.208%
                                 scale_standard radius            0.207%
                                 scale_robust   radius            0.207%
                                 scale_power    radius            0.206%
                                 scale_quantile radius            0.205%
KNN               MIST           Base           radius             0.18%
                                 scale_standard radius            0.137%
                                 scale_robust   radius            0.135%
                                 scale_power    radius            0.131%
                                 scale_quantile radius            0.167%
linear_regression MIST           Base           radius            2.083%
                                 scale_standard radius            2.083%
                                 scale_robust   radius            2.083%
                                 scale_power    radius            3.018%
                                 scale_quantile radius            4.041%
mlp               MIST           Base           radius            1.594%
                                 scale_standard radius            1.551%
                                 scale_robust   radius            1.537%
                                 scale_power    radius            1.978%
                                 scale_quantile radius            2.436%
random_forest     MIST           Base           radius            0.102%
                                 scale_standard radius            0.103%
                                 scale_robust   radius            0.102%
                                 scale_power    radius            0.103%
                                 scale_quantile radius            0.103%
xgboost           MIST           Base           radius            0.331%
                                 scale_standard radius             0.33%
                                 scale_robust   radius             0.33%
                                 scale_power    radius             0.33%
                                 scale_quantile radius            0.334%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.113%
                                 scale_standard radius            0.113%
                                 scale_robust   radius            0.113%
                                 scale_power    radius            0.113%
                                 scale_quantile radius            0.113%
KNN               MIST           Base           radius            0.105%
                                 scale_standard radius            0.085%
                                 scale_robust   radius            0.085%
                                 scale_power    radius             0.08%
                                 scale_quantile radius            0.087%
linear_regression MIST           Base           radius            1.628%
                                 scale_standard radius            1.628%
                                 scale_robust   radius            1.628%
                                 scale_power    radius            2.326%
                                 scale_quantile radius            3.149%
mlp               MIST           Base           radius            1.213%
                                 scale_standard radius            1.179%
                                 scale_robust   radius            1.135%
                                 scale_power    radius            1.472%
                                 scale_quantile radius              1.8%
random_forest     MIST           Base           radius            0.051%
                                 scale_standard radius            0.051%
                                 scale_robust   radius            0.051%
                                 scale_power    radius            0.051%
                                 scale_quantile radius            0.051%
xgboost           MIST           Base           radius            0.244%
                                 scale_standard radius            0.243%
                                 scale_robust   radius            0.243%
                                 scale_power    radius            0.242%
                                 scale_quantile radius            0.247%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.064%
                                 scale_standard radius            0.064%
                                 scale_robust   radius            0.064%
                                 scale_power    radius            0.064%
                                 scale_quantile radius            0.064%
KNN               MIST           Base           radius            0.063%
                                 scale_standard radius            0.055%
                                 scale_robust   radius            0.055%
                                 scale_power    radius            0.051%
                                 scale_quantile radius            0.048%
linear_regression MIST           Base           radius            1.286%
                                 scale_standard radius            1.286%
                                 scale_robust   radius            1.286%
                                 scale_power    radius            1.845%
                                 scale_quantile radius            2.441%
mlp               MIST           Base           radius            0.964%
                                 scale_standard radius            0.925%
                                 scale_robust   radius            0.877%
                                 scale_power    radius            1.123%
                                 scale_quantile radius            1.384%
random_forest     MIST           Base           radius            0.025%
                                 scale_standard radius            0.025%
                                 scale_robust   radius            0.025%
                                 scale_power    radius            0.025%
                                 scale_quantile radius            0.025%
xgboost           MIST           Base           radius            0.184%
                                 scale_standard radius            0.183%
                                 scale_robust   radius            0.183%
                                 scale_power    radius            0.183%
                                 scale_quantile radius            0.187%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9998895445736318
                                 scale_standard radius            0.9998906664946047
                                 scale_robust   radius            0.9998906872539167
                                 scale_power    radius            0.9998918428007688
                                 scale_quantile radius            0.9998924306860204
KNN               MIST           Base           radius            0.9999169942116342
                                 scale_standard radius            0.9999522108609485
                                 scale_robust   radius            0.9999531781246771
                                 scale_power    radius            0.9999561789209133
                                 scale_quantile radius            0.9999288857513364
linear_regression MIST           Base           radius            0.9888944199376599
                                 scale_standard radius            0.9888944199376595
                                 scale_robust   radius            0.9888944199376586
                                 scale_power    radius            0.9771381293337085
                                 scale_quantile radius            0.9585022400038563
mlp               MIST           Base           radius            0.9936897796640443
                                 scale_standard radius            0.9942533582095376
                                 scale_robust   radius            0.9940987020643219
                                 scale_power    radius            0.9901030410939038
                                 scale_quantile radius            0.9851832117844048
random_forest     MIST           Base           radius            0.9999733173582267
                                 scale_standard radius            0.9999729881935343
                                 scale_robust   radius             0.999973241438616
                                 scale_power    radius            0.9999731174889579
                                 scale_quantile radius            0.9999729107113497
xgboost           MIST           Base           radius            0.9997190014385369
                                 scale_standard radius            0.9997209009793395
                                 scale_robust   radius            0.9997217737068496
                                 scale_power    radius            0.9997217276059344
                                 scale_quantile radius            0.9997140491652976

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            11.724%
                                 scale_standard radius            11.724%
                                 scale_robust   radius            11.724%
                                 scale_power    radius            11.958%
                                 scale_quantile radius            11.724%
KNN               MIST           Base           radius             3.779%
                                 scale_standard radius             2.852%
                                 scale_robust   radius             2.852%
                                 scale_power    radius             3.547%
                                 scale_quantile radius             3.537%
linear_regression MIST           Base           radius            11.227%
                                 scale_standard radius            11.227%
                                 scale_robust   radius            11.227%
                                 scale_power    radius            17.148%
                                 scale_quantile radius            18.892%
mlp               MIST           Base           radius            10.023%
                                 scale_standard radius            13.581%
                                 scale_robust   radius            14.953%
                                 scale_power    radius            19.515%
                                 scale_quantile radius            17.258%
random_forest     MIST           Base           radius             8.775%
                                 scale_standard radius             9.853%
                                 scale_robust   radius             9.268%
                                 scale_power    radius             8.706%
                                 scale_quantile radius             9.122%
xgboost           MIST           Base           radius              3.33%
                                 scale_standard radius             3.193%
                                 scale_robust   radius             3.017%
                                 scale_power    radius             3.675%
                                 scale_quantile radius             3.455%

                                                                                                            Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            75 : 0.131% / 90 : 0.252% / 95 : 0.372% / 99 : 0.797%
                                 scale_standard radius             75 : 0.131% / 90 : 0.252% / 95 : 0.372% / 99 : 0.79%
                                 scale_robust   radius            75 : 0.131% / 90 : 0.253% / 95 : 0.373% / 99 : 0.792%
                                 scale_power    radius            75 : 0.131% / 90 : 0.252% / 95 : 0.371% / 99 : 0.794%
                                 scale_quantile radius            75 : 0.131% / 90 : 0.251% / 95 : 0.371% / 99 : 0.788%
KNN               MIST           Base           radius            75 : 0.127% / 90 : 0.234% / 95 : 0.332% / 99 : 0.647%
                                 scale_standard radius            75 : 0.104% / 90 : 0.185% / 95 : 0.262% / 99 : 0.515%
                                 scale_robust   radius            75 : 0.105% / 90 : 0.185% / 95 : 0.257% / 99 : 0.503%
                                 scale_power    radius              75 : 0.1% / 90 : 0.175% / 95 : 0.243% / 99 : 0.487%
                                 scale_quantile radius            75 : 0.095% / 90 : 0.186% / 95 : 0.289% / 99 : 0.722%
linear_regression MIST           Base           radius             75 : 2.358% / 90 : 3.301% / 95 : 3.855% / 99 : 6.14%
                                 scale_standard radius             75 : 2.358% / 90 : 3.301% / 95 : 3.855% / 99 : 6.14%
                                 scale_robust   radius             75 : 2.358% / 90 : 3.301% / 95 : 3.855% / 99 : 6.14%

Results for the phase category with a value of 2.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
KNN               MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
linear_regression MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
mlp               MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
random_forest     MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321
xgboost           MIST           Base           radius            0.0919862423867022 - 2.891706235288321
                                 scale_standard radius            0.0919862423867022 - 2.891706235288321
                                 scale_robust   radius            0.0919862423867022 - 2.891706235288321
                                 scale_power    radius            0.0919862423867022 - 2.891706235288321
                                 scale_quantile radius            0.0919862423867022 - 2.891706235288321

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9996013815341348
                                 scale_standard radius            0.9995938384041673
                                 scale_robust   radius            0.9995913251417556
                                 scale_power    radius            0.9995960147556129
                                 scale_quantile radius             0.999596811370535
KNN               MIST           Base           radius            0.9999055166815642
                                 scale_standard radius            0.9998902843052527
                                 scale_robust   radius              0.99989736807755
                                 scale_power    radius             0.999862459528918
                                 scale_quantile radius            0.9997790095960687
linear_regression MIST           Base           radius            0.9679744997103377
                                 scale_standard radius            0.9679744997103389
                                 scale_robust   radius            0.9679744997103417
                                 scale_power    radius            0.9470109780254621
                                 scale_quantile radius            0.9144048268257878
mlp               MIST           Base           radius             0.984995693437375
                                 scale_standard radius            0.9870578755187476
                                 scale_robust   radius            0.9884643866996614
                                 scale_power    radius            0.9739959193110057
                                 scale_quantile radius            0.9604660236115659
random_forest     MIST           Base           radius            0.9999326234217092
                                 scale_standard radius            0.9999328206795431
                                 scale_robust   radius            0.9999325593577166
                                 scale_power    radius            0.9999346689729685
                                 scale_quantile radius            0.9999328241081014
xgboost           MIST           Base           radius            0.9992306813494213
                                 scale_standard radius            0.9992137759915166
                                 scale_robust   radius            0.9992114671557197
                                 scale_power    radius             0.999205779158902
                                 scale_quantile radius            0.9992200945545977

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.35%
                                 scale_standard radius            0.353%
                                 scale_robust   radius            0.355%
                                 scale_power    radius            0.353%
                                 scale_quantile radius            0.352%
KNN               MIST           Base           radius             0.17%
                                 scale_standard radius            0.184%
                                 scale_robust   radius            0.178%
                                 scale_power    radius            0.208%
                                 scale_quantile radius            0.263%
linear_regression MIST           Base           radius            3.158%
                                 scale_standard radius            3.158%
                                 scale_robust   radius            3.158%
                                 scale_power    radius            4.237%
                                 scale_quantile radius            5.429%
mlp               MIST           Base           radius            2.256%
                                 scale_standard radius            2.001%
                                 scale_robust   radius            1.884%
                                 scale_power    radius            2.839%
                                 scale_quantile radius            3.541%
random_forest     MIST           Base           radius            0.145%
                                 scale_standard radius            0.145%
                                 scale_robust   radius            0.145%
                                 scale_power    radius            0.143%
                                 scale_quantile radius            0.145%
xgboost           MIST           Base           radius            0.487%
                                 scale_standard radius            0.492%
                                 scale_robust   radius            0.493%
                                 scale_power    radius            0.494%
                                 scale_quantile radius             0.49%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.241%
                                 scale_standard radius            0.241%
                                 scale_robust   radius            0.241%
                                 scale_power    radius            0.241%
                                 scale_quantile radius            0.241%
KNN               MIST           Base           radius            0.123%
                                 scale_standard radius            0.132%
                                 scale_robust   radius            0.128%
                                 scale_power    radius            0.148%
                                 scale_quantile radius             0.18%
linear_regression MIST           Base           radius            2.062%
                                 scale_standard radius            2.062%
                                 scale_robust   radius            2.062%
                                 scale_power    radius             3.52%
                                 scale_quantile radius            4.498%
mlp               MIST           Base           radius            1.756%
                                 scale_standard radius             1.54%
                                 scale_robust   radius            1.409%
                                 scale_power    radius            2.121%
                                 scale_quantile radius            2.703%
random_forest     MIST           Base           radius            0.096%
                                 scale_standard radius            0.096%
                                 scale_robust   radius            0.096%
                                 scale_power    radius            0.094%
                                 scale_quantile radius            0.096%
xgboost           MIST           Base           radius            0.381%
                                 scale_standard radius            0.384%
                                 scale_robust   radius            0.384%
                                 scale_power    radius            0.386%
                                 scale_quantile radius            0.382%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.186%
                                 scale_standard radius            0.187%
                                 scale_robust   radius            0.186%
                                 scale_power    radius            0.187%
                                 scale_quantile radius            0.187%
KNN               MIST           Base           radius            0.091%
                                 scale_standard radius            0.098%
                                 scale_robust   radius            0.095%
                                 scale_power    radius            0.106%
                                 scale_quantile radius            0.123%
linear_regression MIST           Base           radius            1.212%
                                 scale_standard radius            1.212%
                                 scale_robust   radius            1.212%
                                 scale_power    radius            3.418%
                                 scale_quantile radius            4.253%
mlp               MIST           Base           radius            1.419%
                                 scale_standard radius            1.253%
                                 scale_robust   radius            1.151%
                                 scale_power    radius            1.676%
                                 scale_quantile radius            2.153%
random_forest     MIST           Base           radius            0.063%
                                 scale_standard radius            0.063%
                                 scale_robust   radius            0.063%
                                 scale_power    radius             0.06%
                                 scale_quantile radius            0.064%
xgboost           MIST           Base           radius            0.313%
                                 scale_standard radius            0.315%
                                 scale_robust   radius            0.315%
                                 scale_power    radius            0.317%
                                 scale_quantile radius            0.313%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9998018770327872
                                 scale_standard radius            0.9997981813678157
                                 scale_robust   radius            0.9997969141293508
                                 scale_power    radius            0.9997989654044362
                                 scale_quantile radius            0.9997991043978084
KNN               MIST           Base           radius            0.9999527572442021
                                 scale_standard radius            0.9999451411322162
                                 scale_robust   radius            0.9999486833289599
                                 scale_power    radius            0.9999316286397391
                                 scale_quantile radius             0.999891804306905
linear_regression MIST           Base           radius            0.9838665758685889
                                 scale_standard radius            0.9838665758685898
                                 scale_robust   radius            0.9838665758685912
                                 scale_power    radius            0.9754424635731059
                                 scale_quantile radius            0.9631141916458649
mlp               MIST           Base           radius             0.992574201430493
                                 scale_standard radius            0.9939664670939565
                                 scale_robust   radius            0.9942391838997061
                                 scale_power    radius            0.9875459308173362
                                 scale_quantile radius             0.980407942139034
random_forest     MIST           Base           radius             0.999966988493253
                                 scale_standard radius            0.9999670582449236
                                 scale_robust   radius            0.9999669250325012
                                 scale_power    radius            0.9999678785983874
                                 scale_quantile radius            0.9999668909119557
xgboost           MIST           Base           radius            0.9996159124585666
                                 scale_standard radius            0.9996073362568038
                                 scale_robust   radius            0.9996062681034856
                                 scale_power    radius            0.9996033393483618
                                 scale_quantile radius            0.9996105096187203

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             6.585%
                                 scale_standard radius             8.854%
                                 scale_robust   radius             9.371%
                                 scale_power    radius             6.161%
                                 scale_quantile radius             8.027%
KNN               MIST           Base           radius             2.759%
                                 scale_standard radius             2.759%
                                 scale_robust   radius             2.759%
                                 scale_power    radius             2.759%
                                 scale_quantile radius             4.834%
linear_regression MIST           Base           radius            16.177%
                                 scale_standard radius            16.177%
                                 scale_robust   radius            16.177%
                                 scale_power    radius            21.198%
                                 scale_quantile radius            31.295%
mlp               MIST           Base           radius            13.166%
                                 scale_standard radius            13.222%
                                 scale_robust   radius            18.331%
                                 scale_power    radius             21.19%
                                 scale_quantile radius            21.482%
random_forest     MIST           Base           radius             3.256%
                                 scale_standard radius             3.094%
                                 scale_robust   radius             3.669%
                                 scale_power    radius             2.714%
                                 scale_quantile radius             3.551%
xgboost           MIST           Base           radius              2.63%
                                 scale_standard radius               3.0%
                                 scale_robust   radius             3.015%
                                 scale_power    radius             2.922%
                                 scale_quantile radius             2.754%

                                                                                                             Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius              75 : 0.324% / 90 : 0.48% / 95 : 0.593% / 99 : 1.125%
                                 scale_standard radius             75 : 0.324% / 90 : 0.481% / 95 : 0.594% / 99 : 1.136%
                                 scale_robust   radius               75 : 0.324% / 90 : 0.48% / 95 : 0.594% / 99 : 1.14%
                                 scale_power    radius             75 : 0.324% / 90 : 0.481% / 95 : 0.594% / 99 : 1.127%
                                 scale_quantile radius               75 : 0.324% / 90 : 0.48% / 95 : 0.593% / 99 : 1.13%
KNN               MIST           Base           radius             75 : 0.168% / 90 : 0.276% / 95 : 0.349% / 99 : 0.519%
                                 scale_standard radius             75 : 0.177% / 90 : 0.291% / 95 : 0.374% / 99 : 0.577%
                                 scale_robust   radius              75 : 0.17% / 90 : 0.279% / 95 : 0.361% / 99 : 0.558%
                                 scale_power    radius             75 : 0.201% / 90 : 0.333% / 95 : 0.431% / 99 : 0.665%
                                 scale_quantile radius              75 : 0.243% / 90 : 0.408% / 95 : 0.54% / 99 : 0.888%
linear_regression MIST           Base           radius            75 : 2.625% / 90 : 5.047% / 95 : 6.932% / 99 : 12.502%
                                 scale_standard radius            75 : 2.625% / 90 : 5.047% / 95 : 6.932% / 99 : 12.502%
                                 scale_robust   radius            75 : 2.625% / 90 : 5.047% / 95 : 6.932% / 99 : 12.502%
                                 scale_power    radius            75 : 4.647% / 90 : 5.525% / 95 : 7.424% / 99 : 13.263%

Results for the phase category with a value of 3.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
KNN               MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
linear_regression MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
mlp               MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
random_forest     MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593
xgboost           MIST           Base           radius            -0.3445863859219699 - 3.129269620812593
                                 scale_standard radius            -0.3445863859219699 - 3.129269620812593
                                 scale_robust   radius            -0.3445863859219699 - 3.129269620812593
                                 scale_power    radius            -0.3445863859219699 - 3.129269620812593
                                 scale_quantile radius            -0.3445863859219699 - 3.129269620812593

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius             0.999266684393612
                                 scale_standard radius            0.9992745362709283
                                 scale_robust   radius            0.9992740485359346
                                 scale_power    radius             0.999256197641749
                                 scale_quantile radius            0.9992890357995023
KNN               MIST           Base           radius            0.9996720394056582
                                 scale_standard radius            0.9996244944940947
                                 scale_robust   radius            0.9996290427475479
                                 scale_power    radius            0.9995694141134034
                                 scale_quantile radius            0.9994275605683296
linear_regression MIST           Base           radius              0.96988742831239
                                 scale_standard radius            0.9698874283123914
                                 scale_robust   radius            0.9698874283123944
                                 scale_power    radius            0.8903599794151772
                                 scale_quantile radius             0.834151129048188
mlp               MIST           Base           radius            0.9847763915139012
                                 scale_standard radius            0.9860393999666626
                                 scale_robust   radius            0.9882443736041263
                                 scale_power    radius             0.976159916928418
                                 scale_quantile radius            0.9326645667589165
random_forest     MIST           Base           radius            0.9997339847238751
                                 scale_standard radius            0.9997341014585059
                                 scale_robust   radius            0.9997333271349389
                                 scale_power    radius            0.9997354476932981
                                 scale_quantile radius            0.9997320043983635
xgboost           MIST           Base           radius            0.9989178719473903
                                 scale_standard radius            0.9989105830442501
                                 scale_robust   radius            0.9989023217445784
                                 scale_power    radius            0.9989025700340648
                                 scale_quantile radius            0.9989020263810727

                                                                    RMSE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.447%
                                 scale_standard radius            0.444%
                                 scale_robust   radius            0.444%
                                 scale_power    radius             0.45%
                                 scale_quantile radius             0.44%
KNN               MIST           Base           radius            0.299%
                                 scale_standard radius            0.319%
                                 scale_robust   radius            0.317%
                                 scale_power    radius            0.342%
                                 scale_quantile radius            0.397%
linear_regression MIST           Base           radius            2.866%
                                 scale_standard radius            2.866%
                                 scale_robust   radius            2.866%
                                 scale_power    radius            5.457%
                                 scale_quantile radius            6.718%
mlp               MIST           Base           radius            2.046%
                                 scale_standard radius            1.954%
                                 scale_robust   radius            1.803%
                                 scale_power    radius             2.55%
                                 scale_quantile radius            4.277%
random_forest     MIST           Base           radius             0.27%
                                 scale_standard radius             0.27%
                                 scale_robust   radius            0.271%
                                 scale_power    radius             0.27%
                                 scale_quantile radius            0.272%
xgboost           MIST           Base           radius            0.543%
                                 scale_standard radius            0.544%
                                 scale_robust   radius            0.546%
                                 scale_power    radius            0.546%
                                 scale_quantile radius            0.547%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.232%
                                 scale_standard radius            0.231%
                                 scale_robust   radius            0.231%
                                 scale_power    radius            0.232%
                                 scale_quantile radius            0.231%
KNN               MIST           Base           radius            0.146%
                                 scale_standard radius            0.161%
                                 scale_robust   radius            0.157%
                                 scale_power    radius             0.18%
                                 scale_quantile radius            0.217%
linear_regression MIST           Base           radius            2.006%
                                 scale_standard radius            2.006%
                                 scale_robust   radius            2.006%
                                 scale_power    radius            4.108%
                                 scale_quantile radius            4.696%
mlp               MIST           Base           radius            1.548%
                                 scale_standard radius            1.437%
                                 scale_robust   radius            1.193%
                                 scale_power    radius             1.85%
                                 scale_quantile radius            3.142%
random_forest     MIST           Base           radius            0.128%
                                 scale_standard radius            0.128%
                                 scale_robust   radius            0.128%
                                 scale_power    radius            0.127%
                                 scale_quantile radius            0.129%
xgboost           MIST           Base           radius            0.361%
                                 scale_standard radius            0.361%
                                 scale_robust   radius            0.363%
                                 scale_power    radius            0.364%
                                 scale_quantile radius            0.364%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.116%
                                 scale_standard radius            0.116%
                                 scale_robust   radius            0.116%
                                 scale_power    radius            0.116%
                                 scale_quantile radius            0.116%
KNN               MIST           Base           radius            0.076%
                                 scale_standard radius            0.086%
                                 scale_robust   radius            0.083%
                                 scale_power    radius            0.096%
                                 scale_quantile radius            0.112%
linear_regression MIST           Base           radius            1.329%
                                 scale_standard radius            1.329%
                                 scale_robust   radius            1.329%
                                 scale_power    radius            3.422%
                                 scale_quantile radius            3.604%
mlp               MIST           Base           radius             1.21%
                                 scale_standard radius            1.125%
                                 scale_robust   radius            0.883%
                                 scale_power    radius            1.393%
                                 scale_quantile radius            2.417%
random_forest     MIST           Base           radius            0.057%
                                 scale_standard radius            0.058%
                                 scale_robust   radius            0.057%
                                 scale_power    radius            0.057%
                                 scale_quantile radius            0.058%
xgboost           MIST           Base           radius            0.262%
                                 scale_standard radius             0.26%
                                 scale_robust   radius            0.263%
                                 scale_power    radius            0.264%
                                 scale_quantile radius            0.264%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            0.9996333392274228
                                 scale_standard radius            0.9996372794149946
                                 scale_robust   radius             0.999637018115921
                                 scale_power    radius            0.9996280916668067
                                 scale_quantile radius            0.9996444892370784
KNN               MIST           Base           radius            0.9998360691463095
                                 scale_standard radius            0.9998122948055108
                                 scale_robust   radius            0.9998145655464045
                                 scale_power    radius            0.9997847708432359
                                 scale_quantile radius            0.9997141243781028
linear_regression MIST           Base           radius            0.9849992743688404
                                 scale_standard radius            0.9849992743688406
                                 scale_robust   radius            0.9849992743688423
                                 scale_power    radius            0.9591641307452844
                                 scale_quantile radius            0.9330061414448872
mlp               MIST           Base           radius             0.992384420506142
                                 scale_standard radius            0.9930816370845573
                                 scale_robust   radius            0.9941116108791167
                                 scale_power    radius            0.9880559253315677
                                 scale_quantile radius            0.9674006029567951
random_forest     MIST           Base           radius            0.9998670249575315
                                 scale_standard radius            0.9998670908331497
                                 scale_robust   radius            0.9998667007473334
                                 scale_power    radius            0.9998677667547676
                                 scale_quantile radius             0.999866031801925
xgboost           MIST           Base           radius            0.9994588839474633
                                 scale_standard radius            0.9994552272677016
                                 scale_robust   radius            0.9994510910452163
                                 scale_power    radius            0.9994512267880744
                                 scale_quantile radius            0.9994509548446154

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius            11.071%
                                 scale_standard radius            10.128%
                                 scale_robust   radius            10.128%
                                 scale_power    radius            11.071%
                                 scale_quantile radius             10.09%
KNN               MIST           Base           radius             8.844%
                                 scale_standard radius             8.844%
                                 scale_robust   radius             8.844%
                                 scale_power    radius            11.514%
                                 scale_quantile radius            10.535%
linear_regression MIST           Base           radius            15.116%
                                 scale_standard radius            15.116%
                                 scale_robust   radius            15.116%
                                 scale_power    radius            28.872%
                                 scale_quantile radius            32.337%
mlp               MIST           Base           radius             16.72%
                                 scale_standard radius            20.737%
                                 scale_robust   radius            25.617%
                                 scale_power    radius            22.771%
                                 scale_quantile radius            26.051%
random_forest     MIST           Base           radius             8.677%
                                 scale_standard radius             8.593%
                                 scale_robust   radius             8.364%
                                 scale_power    radius             8.389%
                                 scale_quantile radius             8.464%
xgboost           MIST           Base           radius            14.096%
                                 scale_standard radius            13.356%
                                 scale_robust   radius            14.702%
                                 scale_power    radius            14.709%
                                 scale_quantile radius            11.905%

                                                                                                              Percentiles  \
model             physical_model filter         output_parameter
decision_tree     MIST           Base           radius               75 : 0.269% / 90 : 0.531% / 95 : 0.834% / 99 : 1.94%
                                 scale_standard radius                75 : 0.27% / 90 : 0.532% / 95 : 0.83% / 99 : 1.922%
                                 scale_robust   radius              75 : 0.269% / 90 : 0.532% / 95 : 0.827% / 99 : 1.932%
                                 scale_power    radius              75 : 0.269% / 90 : 0.531% / 95 : 0.826% / 99 : 1.949%
                                 scale_quantile radius               75 : 0.27% / 90 : 0.532% / 95 : 0.831% / 99 : 1.915%
KNN               MIST           Base           radius                75 : 0.17% / 90 : 0.316% / 95 : 0.47% / 99 : 1.317%
                                 scale_standard radius                75 : 0.19% / 90 : 0.353% / 95 : 0.53% / 99 : 1.342%
                                 scale_robust   radius              75 : 0.182% / 90 : 0.341% / 95 : 0.517% / 99 : 1.354%
                                 scale_power    radius                75 : 0.22% / 90 : 0.418% / 95 : 0.61% / 99 : 1.382%
                                 scale_quantile radius              75 : 0.268% / 90 : 0.524% / 95 : 0.762% / 99 : 1.543%
linear_regression MIST           Base           radius              75 : 2.479% / 90 : 4.855% / 95 : 6.506% / 99 : 9.473%
                                 scale_standard radius              75 : 2.479% / 90 : 4.855% / 95 : 6.506% / 99 : 9.473%
                                 scale_robust   radius              75 : 2.479% / 90 : 4.855% / 95 : 6.506% / 99 : 9.473%

les résultats avec du scaling sont très proche de Base, il n'y a pas d'intérêt à utilise le scaling pour ce modèle

## Base vs mass_filtered

| Parameter      | Base                                                       | mass_filtered_smaller_3                                | mass_filtered_smaller_14                                           | mass_filtered_smaller_30                               |
| -------------  | ---------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : Range : 5.0 - 10.3 , Mean : 8.1222, Median : 8.15  | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5                    | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1000 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | star_mass  : Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289 | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557      | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | log_Teff  : Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557      | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | log_g  : Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537    | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976     | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | log_R  : Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357    | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### Mass parameter

In [3]:
compare_metrics(path, value_rounding=3, relative_values=False,
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
KNN               MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
linear_regression MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
mlp               MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
random_forest     MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
xgboost           MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998

                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.995
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
KNN               MIST           Base            mass              0.990
                                 mass_smaller_3  mass              0.998
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.999
linear_regression MIST           Base            mass              0.304
                                 mass_smaller_3  mass              0.767
                                 mass_smaller_14 mass              0.725
                                 mass_smaller_30 mass              0.642
mlp               MIST           Base            mass              0.976
                                 mass_smaller_3  mass              0.994
                                 mass_smaller_14 mass              0.998
                                 mass_smaller_30 mass              0.963
random_forest     MIST           Base            mass              0.998
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.994
                                 mass_smaller_3  mass              0.998
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.998

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               1.837
                                 mass_smaller_3  mass               0.027
                                 mass_smaller_14 mass               0.051
                                 mass_smaller_30 mass               0.184
KNN               MIST           Base            mass               2.726
                                 mass_smaller_3  mass               0.029
                                 mass_smaller_14 mass               0.083
                                 mass_smaller_30 mass               0.213
linear_regression MIST           Base            mass              22.280
                                 mass_smaller_3  mass               0.349
                                 mass_smaller_14 mass               1.717
                                 mass_smaller_30 mass               3.659
mlp               MIST           Base            mass               4.121
                                 mass_smaller_3  mass               0.059
                                 mass_smaller_14 mass               0.148
                                 mass_smaller_30 mass               1.215
random_forest     MIST           Base            mass               1.251
                                 mass_smaller_3  mass               0.019
                                 mass_smaller_14 mass               0.033
                                 mass_smaller_30 mass               0.124
xgboost           MIST           Base            mass               2.048
                                 mass_smaller_3  mass               0.030
                                 mass_smaller_14 mass               0.097
                                 mass_smaller_30 mass               0.248

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.200
                                 mass_smaller_3  mass               0.008
                                 mass_smaller_14 mass               0.016
                                 mass_smaller_30 mass               0.029
KNN               MIST           Base            mass               0.328
                                 mass_smaller_3  mass               0.012
                                 mass_smaller_14 mass               0.029
                                 mass_smaller_30 mass               0.051
linear_regression MIST           Base            mass              11.345
                                 mass_smaller_3  mass               0.265
                                 mass_smaller_14 mass               1.298
                                 mass_smaller_30 mass               2.613
mlp               MIST           Base            mass               1.261
                                 mass_smaller_3  mass               0.037
                                 mass_smaller_14 mass               0.078
                                 mass_smaller_30 mass               0.467
random_forest     MIST           Base            mass               0.145
                                 mass_smaller_3  mass               0.006
                                 mass_smaller_14 mass               0.011
                                 mass_smaller_30 mass               0.021
xgboost           MIST           Base            mass               0.531
                                 mass_smaller_3  mass               0.016
                                 mass_smaller_14 mass               0.055
                                 mass_smaller_30 mass               0.112

                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.003
                                 mass_smaller_3  mass              0.002
                                 mass_smaller_14 mass              0.003
                                 mass_smaller_30 mass              0.003
KNN               MIST           Base            mass              0.008
                                 mass_smaller_3  mass              0.005
                                 mass_smaller_14 mass              0.007
                                 mass_smaller_30 mass              0.007
linear_regression MIST           Base            mass              8.154
                                 mass_smaller_3  mass              0.208
                                 mass_smaller_14 mass              0.978
                                 mass_smaller_30 mass              2.022
mlp               MIST           Base            mass              0.343
                                 mass_smaller_3  mass              0.024
                                 mass_smaller_14 mass              0.045
                                 mass_smaller_30 mass              0.153
random_forest     MIST           Base            mass              0.004
                                 mass_smaller_3  mass              0.002
                                 mass_smaller_14 mass              0.003
                                 mass_smaller_30 mass              0.003
xgboost           MIST           Base            mass              0.099
                                 mass_smaller_3  mass              0.010
                                 mass_smaller_14 mass              0.029
                                 mass_smaller_30 mass              0.046

                                                                    CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.998
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
KNN               MIST           Base            mass              0.995
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
linear_regression MIST           Base            mass              0.552
                                 mass_smaller_3  mass              0.876
                                 mass_smaller_14 mass              0.852
                                 mass_smaller_30 mass              0.801
mlp               MIST           Base            mass              0.988
                                 mass_smaller_3  mass              0.997
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.982
random_forest     MIST           Base            mass              0.999
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.997
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.658
                                 mass_smaller_3  mass                1.722
                                 mass_smaller_14 mass                5.116
                                 mass_smaller_30 mass               15.540
KNN               MIST           Base            mass              144.214
                                 mass_smaller_3  mass                1.342
                                 mass_smaller_14 mass                2.604
                                 mass_smaller_30 mass                7.642
linear_regression MIST           Base            mass              257.508
                                 mass_smaller_3  mass                1.814
                                 mass_smaller_14 mass                7.719
                                 mass_smaller_30 mass               19.122
mlp               MIST           Base            mass              174.796
                                 mass_smaller_3  mass                1.903
                                 mass_smaller_14 mass                3.528
                                 mass_smaller_30 mass               19.564
random_forest     MIST           Base            mass               95.973
                                 mass_smaller_3  mass                1.495
                                 mass_smaller_14 mass                2.328
                                 mass_smaller_30 mass                7.625
xgboost           MIST           Base            mass               72.954
                                 mass_smaller_3  mass                1.203
                                 mass_smaller_14 mass                2.503
                                 mass_smaller_30 mass                7.006

                                                                                                                       Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.01985 / 90 : 0.10454 / 95 : 0.35331 / 99 : 4.56376
                                 mass_smaller_3  mass                   75 : 0.00674 / 90 : 0.01771 / 95 : 0.03022 / 99 : 0.08622
                                 mass_smaller_14 mass                   75 : 0.01198 / 90 : 0.03828 / 95 : 0.07324 / 99 : 0.22077
                                 mass_smaller_30 mass                   75 : 0.01421 / 90 : 0.05152 / 95 : 0.10906 / 99 : 0.37792
KNN               MIST           Base            mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                 mass_smaller_3  mass                      75 : 0.01156 / 90 : 0.025 / 95 : 0.04241 / 99 : 0.1315
                                 mass_smaller_14 mass                    75 : 0.02377 / 90 : 0.07441 / 95 : 0.12857 / 99 : 0.3237
                                 mass_smaller_30 mass                   75 : 0.02864 / 90 : 0.10366 / 95 : 0.20303 / 99 : 0.73807
linear_regression MIST           Base            mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                 mass_smaller_3  mass                   75 : 0.37286 / 90 : 0.56792 / 95 : 0.70214 / 99 : 1.06695
                                 mass_smaller_14 mass                   75 : 1.74444 / 90 : 2.76087 / 95 : 3.49416 / 99 : 5.60649
                                 mass_smaller_30 mass                    75 : 3.28283 / 90 : 5.07965 / 95 : 7.1512 / 99 : 14.3976
mlp               MIST           Base            mass                  75 : 0.72117 / 90 : 2.44631 / 95 : 5.24067 / 99 : 18.77727
                                 mass_smaller_3  mass                      75 : 0.04817 / 90 : 0.082 / 95 : 0.1099 / 99 : 0.18796
                                 mass_smaller_14 mass                   75 : 0.09259 / 90 : 0.17542 / 95 : 0.25806 / 99 : 0.50014
                                 mass_smaller_30 mass                    75 : 0.3343 / 90 : 0.97859 / 95 : 1.94599 / 99 : 6.06023
random_forest     MIST           Base            mass                   75 : 0.01557 / 90 : 0.07872 / 95 : 0.29091 / 99 : 3.19321
                                 mass_smaller_3  mass                   75 : 0.00557 / 90 : 0.01238 / 95 : 0.01974 / 99 : 0.06733
                                 mass_smaller_14 mass                    75 : 0.00986 / 90 : 0.02522 / 95 : 0.0469 / 99 : 0.13865
                                 mass_smaller_30 mass                     75 : 0.011 / 90 : 0.03291 / 95 : 0.06904 / 99 : 0.27884
xgboost           MIST           Base            mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                 mass_smaller_3  mass                   75 : 0.01972 / 90 : 0.03542 / 95 : 0.05123 / 99 : 0.10978
                                 mass_smaller_14 mass                     75 : 0.0661 / 90 : 0.1317 / 95 : 0.19286 / 99 : 0.37551
                                 mass_smaller_30 mass                   75 : 0.11661 / 90 : 0.25518 / 95 : 0.40973 / 99 : 1.07358

                                                                      time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898
                                 mass_smaller_3  mass               11.537
                                 mass_smaller_14 mass               18.880
                                 mass_smaller_30 mass               21.883
KNN               MIST           Base            mass                8.372
                                 mass_smaller_3  mass                2.726
                                 mass_smaller_14 mass                5.274
                                 mass_smaller_30 mass                6.282
linear_regression MIST           Base            mass                0.634
                                 mass_smaller_3  mass                0.285
                                 mass_smaller_14 mass                0.461
                                 mass_smaller_30 mass                0.524
mlp               MIST           Base            mass              259.791
                                 mass_smaller_3  mass              116.375
                                 mass_smaller_14 mass              189.019
                                 mass_smaller_30 mass              349.929
random_forest     MIST           Base            mass              343.663
                                 mass_smaller_3  mass              142.993
                                 mass_smaller_14 mass              248.729
                                 mass_smaller_30 mass              327.888
xgboost           MIST           Base            mass               11.712
                                 mass_smaller_3  mass                5.586
                                 mass_smaller_14 mass                8.434
                                 mass_smaller_30 mass               10.954

Results for the phase category with a value of 0.0

                                                                     value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
KNN               MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
linear_regression MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
mlp               MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
random_forest     MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998
xgboost           MIST           Base            mass              0.1 - 298.545
                                 mass_smaller_3  mass                  0.1 - 3.0
                                 mass_smaller_14 mass               0.1 - 13.999
                                 mass_smaller_30 mass               0.1 - 29.998

                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.994
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
KNN               MIST           Base            mass              0.984
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.998
linear_regression MIST           Base            mass              0.273
                                 mass_smaller_3  mass              0.884
                                 mass_smaller_14 mass              0.704
                                 mass_smaller_30 mass              0.591
mlp               MIST           Base            mass              0.972
                                 mass_smaller_3  mass              0.998
                                 mass_smaller_14 mass              0.998
                                 mass_smaller_30 mass              0.949
random_forest     MIST           Base            mass              0.997
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.991
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.998

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               2.098
                                 mass_smaller_3  mass               0.011
                                 mass_smaller_14 mass               0.051
                                 mass_smaller_30 mass               0.210
KNN               MIST           Base            mass               3.292
                                 mass_smaller_3  mass               0.021
                                 mass_smaller_14 mass               0.095
                                 mass_smaller_30 mass               0.256
linear_regression MIST           Base            mass              22.430
                                 mass_smaller_3  mass               0.263
                                 mass_smaller_14 mass               1.794
                                 mass_smaller_30 mass               4.003
mlp               MIST           Base            mass               4.430
                                 mass_smaller_3  mass               0.040
                                 mass_smaller_14 mass               0.149
                                 mass_smaller_30 mass               1.451
random_forest     MIST           Base            mass               1.350
                                 mass_smaller_3  mass               0.005
                                 mass_smaller_14 mass               0.029
                                 mass_smaller_30 mass               0.137
xgboost           MIST           Base            mass               2.494
                                 mass_smaller_3  mass               0.023
                                 mass_smaller_14 mass               0.114
                                 mass_smaller_30 mass               0.306

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.270
                                 mass_smaller_3  mass               0.005
                                 mass_smaller_14 mass               0.017
                                 mass_smaller_30 mass               0.037
KNN               MIST           Base            mass               0.432
                                 mass_smaller_3  mass               0.010
                                 mass_smaller_14 mass               0.031
                                 mass_smaller_30 mass               0.064
linear_regression MIST           Base            mass              13.108
                                 mass_smaller_3  mass               0.209
                                 mass_smaller_14 mass               1.453
                                 mass_smaller_30 mass               3.137
mlp               MIST           Base            mass               1.394
                                 mass_smaller_3  mass               0.027
                                 mass_smaller_14 mass               0.067
                                 mass_smaller_30 mass               0.563
random_forest     MIST           Base            mass               0.168
                                 mass_smaller_3  mass               0.003
                                 mass_smaller_14 mass               0.009
                                 mass_smaller_30 mass               0.023
xgboost           MIST           Base            mass               0.677
                                 mass_smaller_3  mass               0.016
                                 mass_smaller_14 mass               0.064
                                 mass_smaller_30 mass               0.141

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.006
                                 mass_smaller_3  mass               0.002
                                 mass_smaller_14 mass               0.004
                                 mass_smaller_30 mass               0.005
KNN               MIST           Base            mass               0.010
                                 mass_smaller_3  mass               0.004
                                 mass_smaller_14 mass               0.007
                                 mass_smaller_30 mass               0.008
linear_regression MIST           Base            mass              11.253
                                 mass_smaller_3  mass               0.175
                                 mass_smaller_14 mass               1.239
                                 mass_smaller_30 mass               2.806
mlp               MIST           Base            mass               0.369
                                 mass_smaller_3  mass               0.018
                                 mass_smaller_14 mass               0.035
                                 mass_smaller_30 mass               0.149
random_forest     MIST           Base            mass               0.004
                                 mass_smaller_3  mass               0.001
                                 mass_smaller_14 mass               0.002
                                 mass_smaller_30 mass               0.003
xgboost           MIST           Base            mass               0.126
                                 mass_smaller_3  mass               0.010
                                 mass_smaller_14 mass               0.032
                                 mass_smaller_30 mass               0.054

                                                                    CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.997
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
KNN               MIST           Base            mass              0.992
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
linear_regression MIST           Base            mass              0.534
                                 mass_smaller_3  mass              0.946
                                 mass_smaller_14 mass              0.853
                                 mass_smaller_30 mass              0.781
mlp               MIST           Base            mass              0.986
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.975
random_forest     MIST           Base            mass              0.999
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.996
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.999

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              131.775
                                 mass_smaller_3  mass                0.302
                                 mass_smaller_14 mass                5.116
                                 mass_smaller_30 mass               15.540
KNN               MIST           Base            mass              126.674
                                 mass_smaller_3  mass                0.337
                                 mass_smaller_14 mass                2.604
                                 mass_smaller_30 mass                6.561
linear_regression MIST           Base            mass              257.508
                                 mass_smaller_3  mass                0.885
                                 mass_smaller_14 mass                7.719
                                 mass_smaller_30 mass               19.122
mlp               MIST           Base            mass              109.716
                                 mass_smaller_3  mass                0.440
                                 mass_smaller_14 mass                3.528
                                 mass_smaller_30 mass               19.564
random_forest     MIST           Base            mass               83.538
                                 mass_smaller_3  mass                0.233
                                 mass_smaller_14 mass                2.328
                                 mass_smaller_30 mass                7.625
xgboost           MIST           Base            mass               72.954
                                 mass_smaller_3  mass                0.267
                                 mass_smaller_14 mass                2.503
                                 mass_smaller_30 mass                5.656

                                                                                                                        Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                    75 : 0.03086 / 90 : 0.18595 / 95 : 0.67453 / 99 : 5.94846
                                 mass_smaller_3  mass                    75 : 0.00587 / 90 : 0.01198 / 95 : 0.01939 / 99 : 0.04078
                                 mass_smaller_14 mass                    75 : 0.01359 / 90 : 0.04207 / 95 : 0.07392 / 99 : 0.19384
                                 mass_smaller_30 mass                     75 : 0.0186 / 90 : 0.06849 / 95 : 0.14082 / 99 : 0.52226
KNN               MIST           Base            mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                 mass_smaller_3  mass                      75 : 0.01062 / 90 : 0.0218 / 95 : 0.0341 / 99 : 0.09181
                                 mass_smaller_14 mass                     75 : 0.02433 / 90 : 0.0695 / 95 : 0.12413 / 99 : 0.38274
                                 mass_smaller_30 mass                    75 : 0.03345 / 90 : 0.12227 / 95 : 0.26473 / 99 : 1.00264
linear_regression MIST           Base            mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                 mass_smaller_3  mass                    75 : 0.29173 / 90 : 0.44228 / 95 : 0.53342 / 99 : 0.67958
                                 mass_smaller_14 mass                     75 : 2.05906 / 90 : 2.8256 / 95 : 3.31589 / 99 : 4.98312
                                 mass_smaller_30 mass                   75 : 4.09268 / 90 : 5.38416 / 95 : 6.99855 / 99 : 14.06331
mlp               MIST           Base            mass                    75 : 0.83625 / 90 : 2.8714 / 95 : 5.89846 / 99 : 19.76113
                                 mass_smaller_3  mass                    75 : 0.03715 / 90 : 0.06318 / 95 : 0.08361 / 99 : 0.13527
                                 mass_smaller_14 mass                    75 : 0.07428 / 90 : 0.14201 / 95 : 0.22398 / 99 : 0.46232
                                 mass_smaller_30 mass                     75 : 0.40733 / 90 : 1.27804 / 95 : 2.6148 / 99 : 7.17375
random_forest     MIST           Base            mass                    75 : 0.01628 / 90 : 0.10798 / 95 : 0.41573 / 99 : 3.60316
                                 mass_smaller_3  mass                     75 : 0.00311 / 90 : 0.00634 / 95 : 0.0096 / 99 : 0.02171
                                 mass_smaller_14 mass                    75 : 0.00713 / 90 : 0.01962 / 95 : 0.03484 / 99 : 0.10114
                                 mass_smaller_30 mass                      75 : 0.00963 / 90 : 0.03336 / 95 : 0.07567 / 99 : 0.373
xgboost           MIST           Base            mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                 mass_smaller_3  mass                     75 : 0.02055 / 90 : 0.03539 / 95 : 0.04828 / 99 : 0.0828
                                 mass_smaller_14 mass                    75 : 0.07716 / 90 : 0.15608 / 95 : 0.23067 / 99 : 0.45525
                                 mass_smaller_30 mass                    75 : 0.14307 / 90 : 0.33746 / 95 : 0.56366 / 99 : 1.36516

                                                                      time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898
                                 mass_smaller_3  mass               11.537
                                 mass_smaller_14 mass               18.880
                                 mass_smaller_30 mass               21.883
KNN               MIST           Base            mass                8.372
                                 mass_smaller_3  mass                2.726
                                 mass_smaller_14 mass                5.274
                                 mass_smaller_30 mass                6.282
linear_regression MIST           Base            mass                0.634
                                 mass_smaller_3  mass                0.285
                                 mass_smaller_14 mass                0.461
                                 mass_smaller_30 mass                0.524
mlp               MIST           Base            mass              259.791
                                 mass_smaller_3  mass              116.375
                                 mass_smaller_14 mass              189.019
                                 mass_smaller_30 mass              349.929
random_forest     MIST           Base            mass              343.663
                                 mass_smaller_3  mass              142.993
                                 mass_smaller_14 mass              248.729
                                 mass_smaller_30 mass              327.888
xgboost           MIST           Base            mass               11.712
                                 mass_smaller_3  mass                5.586
                                 mass_smaller_14 mass                8.434
                                 mass_smaller_30 mass               10.954

Results for the phase category with a value of 2.0

                                                                       value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679
KNN               MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679
linear_regression MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679
mlp               MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679
random_forest     MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679
xgboost           MIST           Base            mass              0.654 - 283.721
                                 mass_smaller_3  mass                  0.654 - 3.0
                                 mass_smaller_14 mass               0.654 - 13.928
                                 mass_smaller_30 mass               0.654 - 29.679

                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.999
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
KNN               MIST           Base            mass              0.999
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
linear_regression MIST           Base            mass              0.317
                                 mass_smaller_3  mass              0.615
                                 mass_smaller_14 mass              0.763
                                 mass_smaller_30 mass              0.719
mlp               MIST           Base            mass              0.991
                                 mass_smaller_3  mass              0.994
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.984
random_forest     MIST           Base            mass              1.000
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.999
                                 mass_smaller_3  mass              0.999
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.795
                                 mass_smaller_3  mass               0.018
                                 mass_smaller_14 mass               0.025
                                 mass_smaller_30 mass               0.061
KNN               MIST           Base            mass               0.737
                                 mass_smaller_3  mass               0.018
                                 mass_smaller_14 mass               0.049
                                 mass_smaller_30 mass               0.061
linear_regression MIST           Base            mass              24.543
                                 mass_smaller_3  mass               0.404
                                 mass_smaller_14 mass               1.584
                                 mass_smaller_30 mass               3.144
mlp               MIST           Base            mass               2.831
                                 mass_smaller_3  mass               0.058
                                 mass_smaller_14 mass               0.119
                                 mass_smaller_30 mass               0.791
random_forest     MIST           Base            mass               0.470
                                 mass_smaller_3  mass               0.012
                                 mass_smaller_14 mass               0.017
                                 mass_smaller_30 mass               0.033
xgboost           MIST           Base            mass               0.996
                                 mass_smaller_3  mass               0.018
                                 mass_smaller_14 mass               0.052
                                 mass_smaller_30 mass               0.109

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.060
                                 mass_smaller_3  mass               0.008
                                 mass_smaller_14 mass               0.008
                                 mass_smaller_30 mass               0.008
KNN               MIST           Base            mass               0.095
                                 mass_smaller_3  mass               0.009
                                 mass_smaller_14 mass               0.020
                                 mass_smaller_30 mass               0.020
linear_regression MIST           Base            mass              10.236
                                 mass_smaller_3  mass               0.307
                                 mass_smaller_14 mass               1.072
                                 mass_smaller_30 mass               1.965
mlp               MIST           Base            mass               0.916
                                 mass_smaller_3  mass               0.042
                                 mass_smaller_14 mass               0.077
                                 mass_smaller_30 mass               0.339
random_forest     MIST           Base            mass               0.059
                                 mass_smaller_3  mass               0.007
                                 mass_smaller_14 mass               0.008
                                 mass_smaller_30 mass               0.008
xgboost           MIST           Base            mass               0.293
                                 mass_smaller_3  mass               0.012
                                 mass_smaller_14 mass               0.036
                                 mass_smaller_30 mass               0.062

                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.000
                                 mass_smaller_3  mass              0.001
                                 mass_smaller_14 mass              0.000
                                 mass_smaller_30 mass              0.000
KNN               MIST           Base            mass              0.004
                                 mass_smaller_3  mass              0.005
                                 mass_smaller_14 mass              0.005
                                 mass_smaller_30 mass              0.004
linear_regression MIST           Base            mass              5.268
                                 mass_smaller_3  mass              0.233
                                 mass_smaller_14 mass              0.750
                                 mass_smaller_30 mass              1.363
mlp               MIST           Base            mass              0.301
                                 mass_smaller_3  mass              0.030
                                 mass_smaller_14 mass              0.053
                                 mass_smaller_30 mass              0.158
random_forest     MIST           Base            mass              0.004
                                 mass_smaller_3  mass              0.004
                                 mass_smaller_14 mass              0.004
                                 mass_smaller_30 mass              0.004
xgboost           MIST           Base            mass              0.071
                                 mass_smaller_3  mass              0.008
                                 mass_smaller_14 mass              0.024
                                 mass_smaller_30 mass              0.035

                                                                    CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              1.000
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
KNN               MIST           Base            mass              1.000
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
linear_regression MIST           Base            mass              0.596
                                 mass_smaller_3  mass              0.846
                                 mass_smaller_14 mass              0.918
                                 mass_smaller_30 mass              0.882
mlp               MIST           Base            mass              0.996
                                 mass_smaller_3  mass              0.997
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.992
random_forest     MIST           Base            mass              1.000
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.999
                                 mass_smaller_3  mass              1.000
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              105.861
                                 mass_smaller_3  mass                0.425
                                 mass_smaller_14 mass                1.411
                                 mass_smaller_30 mass                9.238
KNN               MIST           Base            mass               37.487
                                 mass_smaller_3  mass                0.300
                                 mass_smaller_14 mass                0.926
                                 mass_smaller_30 mass                2.368
linear_regression MIST           Base            mass              247.133
                                 mass_smaller_3  mass                1.333
                                 mass_smaller_14 mass                7.092
                                 mass_smaller_30 mass               17.296
mlp               MIST           Base            mass               64.984
                                 mass_smaller_3  mass                0.295
                                 mass_smaller_14 mass                1.594
                                 mass_smaller_30 mass               10.058
random_forest     MIST           Base            mass               22.981
                                 mass_smaller_3  mass                0.214
                                 mass_smaller_14 mass                0.483
                                 mass_smaller_30 mass                3.967
xgboost           MIST           Base            mass               39.121
                                 mass_smaller_3  mass                0.179
                                 mass_smaller_14 mass                0.561
                                 mass_smaller_30 mass                3.277

                                                                                                                       Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.00549 / 90 : 0.02551 / 95 : 0.04546 / 99 : 0.75464
                                 mass_smaller_3  mass                   75 : 0.00831 / 90 : 0.02499 / 95 : 0.03376 / 99 : 0.06114
                                 mass_smaller_14 mass                    75 : 0.0057 / 90 : 0.02333 / 95 : 0.03482 / 99 : 0.08753
                                 mass_smaller_30 mass                     75 : 0.00501 / 90 : 0.022 / 95 : 0.03362 / 99 : 0.08338
KNN               MIST           Base            mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                 mass_smaller_3  mass                    75 : 0.0112 / 90 : 0.02127 / 95 : 0.03065 / 99 : 0.08417
                                 mass_smaller_14 mass                   75 : 0.01612 / 90 : 0.05506 / 95 : 0.10024 / 99 : 0.20841
                                 mass_smaller_30 mass                   75 : 0.01504 / 90 : 0.05275 / 95 : 0.09842 / 99 : 0.22917
linear_regression MIST           Base            mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                 mass_smaller_3  mass                   75 : 0.44357 / 90 : 0.67347 / 95 : 0.85401 / 99 : 1.14038
                                 mass_smaller_14 mass                   75 : 1.19379 / 90 : 2.32195 / 95 : 4.01996 / 99 : 5.92949
                                 mass_smaller_30 mass                  75 : 2.26446 / 90 : 3.12681 / 95 : 6.43411 / 99 : 15.06876
mlp               MIST           Base            mass                  75 : 0.57683 / 90 : 1.68666 / 95 : 3.72863 / 99 : 12.95924
                                 mass_smaller_3  mass                   75 : 0.05721 / 90 : 0.09413 / 95 : 0.12217 / 99 : 0.18414
                                 mass_smaller_14 mass                   75 : 0.09435 / 90 : 0.16082 / 95 : 0.23323 / 99 : 0.44523
                                 mass_smaller_30 mass                   75 : 0.29009 / 90 : 0.66751 / 95 : 1.21718 / 99 : 3.90842
random_forest     MIST           Base            mass                    75 : 0.01059 / 90 : 0.02554 / 95 : 0.07295 / 99 : 1.3585
                                 mass_smaller_3  mass                      75 : 0.00921 / 90 : 0.01576 / 95 : 0.02122 / 99 : 0.04
                                 mass_smaller_14 mass                   75 : 0.01007 / 90 : 0.01901 / 95 : 0.02804 / 99 : 0.06834
                                 mass_smaller_30 mass                   75 : 0.00919 / 90 : 0.01764 / 95 : 0.02708 / 99 : 0.06832
xgboost           MIST           Base            mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                 mass_smaller_3  mass                   75 : 0.01637 / 90 : 0.02833 / 95 : 0.03801 / 99 : 0.06428
                                 mass_smaller_14 mass                   75 : 0.04834 / 90 : 0.08246 / 95 : 0.10878 / 99 : 0.17425
                                 mass_smaller_30 mass                    75 : 0.07639 / 90 : 0.14104 / 95 : 0.2055 / 99 : 0.41893

                                                                      time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898
                                 mass_smaller_3  mass               11.537
                                 mass_smaller_14 mass               18.880
                                 mass_smaller_30 mass               21.883
KNN               MIST           Base            mass                8.372
                                 mass_smaller_3  mass                2.726
                                 mass_smaller_14 mass                5.274
                                 mass_smaller_30 mass                6.282
linear_regression MIST           Base            mass                0.634
                                 mass_smaller_3  mass                0.285
                                 mass_smaller_14 mass                0.461
                                 mass_smaller_30 mass                0.524
mlp               MIST           Base            mass              259.791
                                 mass_smaller_3  mass              116.375
                                 mass_smaller_14 mass              189.019
                                 mass_smaller_30 mass              349.929
random_forest     MIST           Base            mass              343.663
                                 mass_smaller_3  mass              142.993
                                 mass_smaller_14 mass              248.729
                                 mass_smaller_30 mass              327.888
xgboost           MIST           Base            mass               11.712
                                 mass_smaller_3  mass                5.586
                                 mass_smaller_14 mass                8.434
                                 mass_smaller_30 mass               10.954

Results for the phase category with a value of 3.0

                                                                       value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995
KNN               MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995
linear_regression MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995
mlp               MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995
random_forest     MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995
xgboost           MIST           Base            mass              0.548 - 288.815
                                 mass_smaller_3  mass                  0.545 - 3.0
                                 mass_smaller_14 mass               0.545 - 13.994
                                 mass_smaller_30 mass               0.545 - 29.995

                                                                     RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.992
                                 mass_smaller_3  mass              0.992
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.999
KNN               MIST           Base            mass              0.986
                                 mass_smaller_3  mass              0.993
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.999
linear_regression MIST           Base            mass              0.388
                                 mass_smaller_3  mass              0.426
                                 mass_smaller_14 mass              0.729
                                 mass_smaller_30 mass              0.694
mlp               MIST           Base            mass              0.959
                                 mass_smaller_3  mass              0.976
                                 mass_smaller_14 mass              0.997
                                 mass_smaller_30 mass              0.976
random_forest     MIST           Base            mass              0.995
                                 mass_smaller_3  mass              0.995
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
xgboost           MIST           Base            mass              0.994
                                 mass_smaller_3  mass              0.993
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.999

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               2.077
                                 mass_smaller_3  mass               0.055
                                 mass_smaller_14 mass               0.074
                                 mass_smaller_30 mass               0.214
KNN               MIST           Base            mass               2.735
                                 mass_smaller_3  mass               0.053
                                 mass_smaller_14 mass               0.084
                                 mass_smaller_30 mass               0.214
linear_regression MIST           Base            mass              18.164
                                 mass_smaller_3  mass               0.474
                                 mass_smaller_14 mass               1.671
                                 mass_smaller_30 mass               3.291
mlp               MIST           Base            mass               4.701
                                 mass_smaller_3  mass               0.097
                                 mass_smaller_14 mass               0.179
                                 mass_smaller_30 mass               0.942
random_forest     MIST           Base            mass               1.648
                                 mass_smaller_3  mass               0.042
                                 mass_smaller_14 mass               0.053
                                 mass_smaller_30 mass               0.161
xgboost           MIST           Base            mass               1.730
                                 mass_smaller_3  mass               0.051
                                 mass_smaller_14 mass               0.090
                                 mass_smaller_30 mass               0.199

                                                                     MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.200
                                 mass_smaller_3  mass              0.017
                                 mass_smaller_14 mass              0.027
                                 mass_smaller_30 mass              0.033
KNN               MIST           Base            mass              0.364
                                 mass_smaller_3  mass              0.021
                                 mass_smaller_14 mass              0.037
                                 mass_smaller_30 mass              0.059
linear_regression MIST           Base            mass              7.961
                                 mass_smaller_3  mass              0.381
                                 mass_smaller_14 mass              1.178
                                 mass_smaller_30 mass              2.040
mlp               MIST           Base            mass              1.368
                                 mass_smaller_3  mass              0.057
                                 mass_smaller_14 mass              0.113
                                 mass_smaller_30 mass              0.372
random_forest     MIST           Base            mass              0.201
                                 mass_smaller_3  mass              0.015
                                 mass_smaller_14 mass              0.023
                                 mass_smaller_30 mass              0.030
xgboost           MIST           Base            mass              0.451
                                 mass_smaller_3  mass              0.024
                                 mass_smaller_14 mass              0.056
                                 mass_smaller_30 mass              0.098

                                                                   MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.004
                                 mass_smaller_3  mass              0.002
                                 mass_smaller_14 mass              0.003
                                 mass_smaller_30 mass              0.003
KNN               MIST           Base            mass              0.010
                                 mass_smaller_3  mass              0.005
                                 mass_smaller_14 mass              0.008
                                 mass_smaller_30 mass              0.009
linear_regression MIST           Base            mass              4.599
                                 mass_smaller_3  mass              0.325
                                 mass_smaller_14 mass              0.773
                                 mass_smaller_30 mass              1.208
mlp               MIST           Base            mass              0.332
                                 mass_smaller_3  mass              0.039
                                 mass_smaller_14 mass              0.073
                                 mass_smaller_30 mass              0.157
random_forest     MIST           Base            mass              0.007
                                 mass_smaller_3  mass              0.004
                                 mass_smaller_14 mass              0.006
                                 mass_smaller_30 mass              0.006
xgboost           MIST           Base            mass              0.094
                                 mass_smaller_3  mass              0.010
                                 mass_smaller_14 mass              0.030
                                 mass_smaller_30 mass              0.047

                                                                    CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.996
                                 mass_smaller_3  mass              0.996
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
KNN               MIST           Base            mass              0.993
                                 mass_smaller_3  mass              0.996
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999
linear_regression MIST           Base            mass              0.650
                                 mass_smaller_3  mass              0.769
                                 mass_smaller_14 mass              0.929
                                 mass_smaller_30 mass              0.893
mlp               MIST           Base            mass              0.980
                                 mass_smaller_3  mass              0.988
                                 mass_smaller_14 mass              0.999
                                 mass_smaller_30 mass              0.988
random_forest     MIST           Base            mass              0.998
                                 mass_smaller_3  mass              0.998
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              1.000
xgboost           MIST           Base            mass              0.997
                                 mass_smaller_3  mass              0.997
                                 mass_smaller_14 mass              1.000
                                 mass_smaller_30 mass              0.999

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              151.658
                                 mass_smaller_3  mass                1.722
                                 mass_smaller_14 mass                2.404
                                 mass_smaller_30 mass                9.359
KNN               MIST           Base            mass              144.214
                                 mass_smaller_3  mass                1.342
                                 mass_smaller_14 mass                1.645
                                 mass_smaller_30 mass                7.642
linear_regression MIST           Base            mass              250.918
                                 mass_smaller_3  mass                1.814
                                 mass_smaller_14 mass                7.148
                                 mass_smaller_30 mass               18.580
mlp               MIST           Base            mass              174.796
                                 mass_smaller_3  mass                1.903
                                 mass_smaller_14 mass                3.408
                                 mass_smaller_30 mass               18.332
random_forest     MIST           Base            mass               95.973
                                 mass_smaller_3  mass                1.495
                                 mass_smaller_14 mass                1.293
                                 mass_smaller_30 mass                7.481
xgboost           MIST           Base            mass               61.887
                                 mass_smaller_3  mass                1.203
                                 mass_smaller_14 mass                1.609
                                 mass_smaller_30 mass                7.006

                                                                                                                      Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.02357 / 90 : 0.11188 / 95 : 0.26917 / 99 : 4.64103
                                 mass_smaller_3  mass                   75 : 0.01012 / 90 : 0.03454 / 95 : 0.0757 / 99 : 0.28474
                                 mass_smaller_14 mass                   75 : 0.01657 / 90 : 0.0729 / 95 : 0.14969 / 99 : 0.34879
                                 mass_smaller_30 mass                  75 : 0.01774 / 90 : 0.07272 / 95 : 0.15071 / 99 : 0.36592
KNN               MIST           Base            mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                 mass_smaller_3  mass                  75 : 0.01788 / 90 : 0.05778 / 95 : 0.10901 / 99 : 0.24067
                                 mass_smaller_14 mass                  75 : 0.03551 / 90 : 0.10934 / 95 : 0.17097 / 99 : 0.34974
                                 mass_smaller_30 mass                  75 : 0.04059 / 90 : 0.13487 / 95 : 0.24905 / 99 : 0.81109
linear_regression MIST           Base            mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                 mass_smaller_3  mass                  75 : 0.53013 / 90 : 0.77211 / 95 : 0.95296 / 99 : 1.22612
                                 mass_smaller_14 mass                  75 : 1.29983 / 90 : 2.59792 / 95 : 3.96941 / 99 : 6.00044
                                 mass_smaller_30 mass                  75 : 2.37964 / 90 : 3.51507 / 95 : 7.81741 / 99 : 14.5941
mlp               MIST           Base            mass                  75 : 0.6942 / 90 : 2.40557 / 95 : 5.75475 / 99 : 22.29219
                                 mass_smaller_3  mass                   75 : 0.0702 / 90 : 0.11925 / 95 : 0.15933 / 99 : 0.32936
                                 mass_smaller_14 mass                  75 : 0.14858 / 90 : 0.25197 / 95 : 0.33805 / 99 : 0.64026
                                 mass_smaller_30 mass                   75 : 0.28935 / 90 : 0.6915 / 95 : 1.29296 / 99 : 5.13652
random_forest     MIST           Base            mass                     75 : 0.02891 / 90 : 0.1076 / 95 : 0.29511 / 99 : 4.683
                                 mass_smaller_3  mass                  75 : 0.01122 / 90 : 0.03088 / 95 : 0.06552 / 99 : 0.20801
                                 mass_smaller_14 mass                   75 : 0.02188 / 90 : 0.0643 / 95 : 0.10864 / 99 : 0.24241
                                 mass_smaller_30 mass                  75 : 0.02152 / 90 : 0.06486 / 95 : 0.11264 / 99 : 0.29002
xgboost           MIST           Base            mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                 mass_smaller_3  mass                   75 : 0.02245 / 90 : 0.05713 / 95 : 0.10052 / 99 : 0.2311
                                 mass_smaller_14 mass                  75 : 0.07123 / 90 : 0.14504 / 95 : 0.19759 / 99 : 0.32362
                                 mass_smaller_30 mass                  75 : 0.12685 / 90 : 0.23177 / 95 : 0.31687 / 99 : 0.58639

                                                                      time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898
                                 mass_smaller_3  mass               11.537
                                 mass_smaller_14 mass               18.880
                                 mass_smaller_30 mass               21.883
KNN               MIST           Base            mass                8.372
                                 mass_smaller_3  mass                2.726
                                 mass_smaller_14 mass                5.274
                                 mass_smaller_30 mass                6.282
linear_regression MIST           Base            mass                0.634
                                 mass_smaller_3  mass                0.285
                                 mass_smaller_14 mass                0.461
                                 mass_smaller_30 mass                0.524
mlp               MIST           Base            mass              259.791
                                 mass_smaller_3  mass              116.375
                                 mass_smaller_14 mass              189.019
                                 mass_smaller_30 mass              349.929
random_forest     MIST           Base            mass              343.663
                                 mass_smaller_3  mass              142.993
                                 mass_smaller_14 mass              248.729
                                 mass_smaller_30 mass              327.888
xgboost           MIST           Base            mass               11.712
                                 mass_smaller_3  mass                5.586
                                 mass_smaller_14 mass                8.434
                                 mass_smaller_30 mass               10.954

In [6]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9952703219364649
                                 mass_smaller_14 mass              0.9997535427935771
KNN               MIST           Base            mass              0.9895916504979603
                                 mass_smaller_14 mass              0.9993589218740458
linear_regression MIST           Base            mass              0.3042271481418729
                                 mass_smaller_14 mass              0.7253140443717881
mlp               MIST           Base            mass              0.9762913286039826
                                 mass_smaller_14 mass              0.9979690330276763
random_forest     MIST           Base            mass              0.9978063351241271
                                 mass_smaller_14 mass              0.9999006268975099
xgboost           MIST           Base            mass              0.9941191064217958
                                 mass_smaller_14 mass              0.9991287201758143

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.615%
                                 mass_smaller_14 mass                0.37%
KNN               MIST           Base            mass               0.913%
                                 mass_smaller_14 mass               0.597%
linear_regression MIST           Base            mass               7.465%
                                 mass_smaller_14 mass              12.351%
mlp               MIST           Base            mass               1.381%
                                 mass_smaller_14 mass               1.064%
random_forest     MIST           Base            mass               0.419%
                                 mass_smaller_14 mass               0.235%
xgboost           MIST           Base            mass               0.686%
                                 mass_smaller_14 mass               0.696%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.067%
                                 mass_smaller_14 mass              0.117%
KNN               MIST           Base            mass               0.11%
                                 mass_smaller_14 mass              0.209%
linear_regression MIST           Base            mass              3.801%
                                 mass_smaller_14 mass              9.338%
mlp               MIST           Base            mass              0.422%
                                 mass_smaller_14 mass              0.564%
random_forest     MIST           Base            mass              0.049%
                                 mass_smaller_14 mass              0.082%
xgboost           MIST           Base            mass              0.178%
                                 mass_smaller_14 mass              0.395%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass               0.02%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_14 mass              0.048%
linear_regression MIST           Base            mass              2.732%
                                 mass_smaller_14 mass              7.035%
mlp               MIST           Base            mass              0.115%
                                 mass_smaller_14 mass              0.323%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.024%
xgboost           MIST           Base            mass              0.033%
                                 mass_smaller_14 mass              0.206%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9976339781841599
                                 mass_smaller_14 mass              0.9998767781112852
KNN               MIST           Base            mass              0.9948902170346177
                                 mass_smaller_14 mass              0.9996846963987984
linear_regression MIST           Base            mass              0.5515679007842895
                                 mass_smaller_14 mass              0.8516537115536522
mlp               MIST           Base            mass              0.9881581645347787
                                 mass_smaller_14 mass              0.9989848962075332
random_forest     MIST           Base            mass              0.9989037560824912
                                 mass_smaller_14 mass              0.9999503530371973
xgboost           MIST           Base            mass              0.9970552947594146
                                 mass_smaller_14 mass              0.9995643018981833

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              50.816%
                                 mass_smaller_14 mass              36.812%
KNN               MIST           Base            mass              48.322%
                                 mass_smaller_14 mass              18.732%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_14 mass              55.541%
mlp               MIST           Base            mass              58.569%
                                 mass_smaller_14 mass              25.383%
random_forest     MIST           Base            mass              32.158%
                                 mass_smaller_14 mass              16.749%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_14 mass              18.006%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                                 mass_smaller_14 mass                 75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
KNN               MIST           Base            mass                  75 : 0.013% / 90 : 0.07% / 95 : 0.236% / 99 : 2.302%
                                 mass_smaller_14 mass                 75 : 0.171% / 90 : 0.535% / 95 : 0.925% / 99 : 2.329%
linear_regression MIST           Base            mass                75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 mass_smaller_14 mass              75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%
mlp               MIST           Base            mass                  75 : 0.242% / 90 : 0.82% / 95 : 1.756% / 99 : 6.292%
                                 mass_smaller_14 mass                 75 : 0.666% / 90 : 1.262% / 95 : 1.857% / 99 : 3.598%
random_forest     MIST           Base            mass                  75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                                 mass_smaller_14 mass                 75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
xgboost           MIST           Base            mass                  75 : 0.091% / 90 : 0.33% / 95 : 0.726% / 99 : 2.844%
                                 mass_smaller_14 mass                 75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9936340302001091
                                 mass_smaller_14 mass              0.9997590738023714
KNN               MIST           Base            mass              0.9843387655163102
                                 mass_smaller_14 mass              0.9991667805594964
linear_regression MIST           Base            mass              0.2728709030098654
                                 mass_smaller_14 mass               0.703580703577132
mlp               MIST           Base            mass              0.9717157238872854
                                 mass_smaller_14 mass               0.997967880087404
random_forest     MIST           Base            mass              0.9973661987481759
                                 mass_smaller_14 mass              0.9999235468255409
xgboost           MIST           Base            mass              0.9910072956179956
                                 mass_smaller_14 mass              0.9987960913520983

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.703%
                                 mass_smaller_14 mass               0.368%
KNN               MIST           Base            mass               1.103%
                                 mass_smaller_14 mass               0.685%
linear_regression MIST           Base            mass               7.516%
                                 mass_smaller_14 mass              12.911%
mlp               MIST           Base            mass               1.484%
                                 mass_smaller_14 mass               1.069%
random_forest     MIST           Base            mass               0.452%
                                 mass_smaller_14 mass               0.207%
xgboost           MIST           Base            mass               0.836%
                                 mass_smaller_14 mass               0.823%

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.09%
                                 mass_smaller_14 mass               0.122%
KNN               MIST           Base            mass               0.145%
                                 mass_smaller_14 mass               0.222%
linear_regression MIST           Base            mass               4.392%
                                 mass_smaller_14 mass              10.456%
mlp               MIST           Base            mass               0.467%
                                 mass_smaller_14 mass               0.483%
random_forest     MIST           Base            mass               0.056%
                                 mass_smaller_14 mass               0.063%
xgboost           MIST           Base            mass               0.227%
                                 mass_smaller_14 mass                0.46%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.002%
                                 mass_smaller_14 mass               0.03%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_14 mass              0.051%
linear_regression MIST           Base            mass              3.771%
                                 mass_smaller_14 mass              8.915%
mlp               MIST           Base            mass              0.124%
                                 mass_smaller_14 mass              0.251%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.018%
xgboost           MIST           Base            mass              0.042%
                                 mass_smaller_14 mass              0.228%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9968269721840094
                                 mass_smaller_14 mass              0.9998795329372157
KNN               MIST           Base            mass              0.9924111983284241
                                 mass_smaller_14 mass              0.9995923399848191
linear_regression MIST           Base            mass              0.5343027371731521
                                 mass_smaller_14 mass              0.8532020075802779
mlp               MIST           Base            mass              0.9860617427522443
                                 mass_smaller_14 mass              0.9989847800218492
random_forest     MIST           Base            mass              0.9986840004415223
                                 mass_smaller_14 mass              0.9999617835917853
xgboost           MIST           Base            mass              0.9955145412428942
                                 mass_smaller_14 mass              0.9993979214189108

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              44.154%
                                 mass_smaller_14 mass              36.812%
KNN               MIST           Base            mass              42.445%
                                 mass_smaller_14 mass              18.732%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_14 mass              55.541%
mlp               MIST           Base            mass              36.763%
                                 mass_smaller_14 mass              25.383%
random_forest     MIST           Base            mass              27.991%
                                 mass_smaller_14 mass              16.749%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_14 mass              18.006%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.993%
                                 mass_smaller_14 mass                 75 : 0.098% / 90 : 0.303% / 95 : 0.532% / 99 : 1.395%
KNN               MIST           Base            mass                 75 : 0.017% / 90 : 0.112% / 95 : 0.345% / 99 : 2.996%
                                 mass_smaller_14 mass                   75 : 0.175% / 90 : 0.5% / 95 : 0.893% / 99 : 2.754%
linear_regression MIST           Base            mass                75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%
                                 mass_smaller_14 mass              75 : 14.815% / 90 : 20.33% / 95 : 23.858% / 99 : 35.853%
mlp               MIST           Base            mass                  75 : 0.28% / 90 : 0.962% / 95 : 1.976% / 99 : 6.621%
                                 mass_smaller_14 mass                 75 : 0.534% / 90 : 1.022% / 95 : 1.612% / 99 : 3.326%
random_forest     MIST           Base            mass                 75 : 0.005% / 90 : 0.036% / 95 : 0.139% / 99 : 1.207%
                                 mass_smaller_14 mass                 75 : 0.051% / 90 : 0.141% / 95 : 0.251% / 99 : 0.728%
xgboost           MIST           Base            mass                 75 : 0.129% / 90 : 0.432% / 95 : 0.904% / 99 : 3.697%
                                 mass_smaller_14 mass                  75 : 0.555% / 90 : 1.123% / 95 : 1.66% / 99 : 3.276%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
KNN               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
linear_regression MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
mlp               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
random_forest     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
xgboost           MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9992828062113351
                                 mass_smaller_14 mass              0.9999398039293963
KNN               MIST           Base            mass              0.9993836364150782
                                 mass_smaller_14 mass              0.9997767455983123
linear_regression MIST           Base            mass              0.3168817813892185
                                 mass_smaller_14 mass              0.7627584839179414
mlp               MIST           Base            mass               0.990929974425174
                                 mass_smaller_14 mass              0.9986994416645744
random_forest     MIST           Base            mass              0.9997496322236138
                                 mass_smaller_14 mass              0.9999737930935538
xgboost           MIST           Base            mass              0.9988754736593098
                                 mass_smaller_14 mass              0.9997624928648234

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.281%
                                 mass_smaller_14 mass                0.19%
KNN               MIST           Base            mass                0.26%
                                 mass_smaller_14 mass               0.366%
linear_regression MIST           Base            mass                8.67%
                                 mass_smaller_14 mass              11.933%
mlp               MIST           Base            mass                 1.0%
                                 mass_smaller_14 mass               0.896%
random_forest     MIST           Base            mass               0.166%
                                 mass_smaller_14 mass               0.126%
xgboost           MIST           Base            mass               0.352%
                                 mass_smaller_14 mass               0.391%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.021%
                                 mass_smaller_14 mass              0.058%
KNN               MIST           Base            mass              0.034%
                                 mass_smaller_14 mass              0.149%
linear_regression MIST           Base            mass              3.616%
                                 mass_smaller_14 mass              8.073%
mlp               MIST           Base            mass              0.324%
                                 mass_smaller_14 mass              0.578%
random_forest     MIST           Base            mass              0.021%
                                 mass_smaller_14 mass              0.063%
xgboost           MIST           Base            mass              0.104%
                                 mass_smaller_14 mass              0.269%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.0%
                                 mass_smaller_14 mass              0.002%
KNN               MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.038%
linear_regression MIST           Base            mass              1.861%
                                 mass_smaller_14 mass              5.653%
mlp               MIST           Base            mass              0.106%
                                 mass_smaller_14 mass              0.402%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.033%
xgboost           MIST           Base            mass              0.025%
                                 mass_smaller_14 mass              0.179%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9996414671007774
                                 mass_smaller_14 mass              0.9999700313729203
KNN               MIST           Base            mass              0.9996927065174758
                                 mass_smaller_14 mass              0.9998883692148779
linear_regression MIST           Base            mass              0.5956286032810738
                                 mass_smaller_14 mass              0.9184081581407212
mlp               MIST           Base            mass              0.9955996860365472
                                 mass_smaller_14 mass              0.9993909030531274
random_forest     MIST           Base            mass              0.9998754804643019
                                 mass_smaller_14 mass               0.999987052162877
xgboost           MIST           Base            mass              0.9994709362034415
                                 mass_smaller_14 mass              0.9998867034593512

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              37.398%
                                 mass_smaller_14 mass              10.632%
KNN               MIST           Base            mass              13.243%
                                 mass_smaller_14 mass               6.976%
linear_regression MIST           Base            mass              87.305%
                                 mass_smaller_14 mass              53.433%
mlp               MIST           Base            mass              22.957%
                                 mass_smaller_14 mass              12.011%
random_forest     MIST           Base            mass               8.119%
                                 mass_smaller_14 mass               3.642%
xgboost           MIST           Base            mass               13.82%
                                 mass_smaller_14 mass               4.227%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                                 mass_smaller_14 mass                 75 : 0.043% / 90 : 0.176% / 95 : 0.262% / 99 : 0.659%
KNN               MIST           Base            mass                 75 : 0.006% / 90 : 0.028% / 95 : 0.057% / 99 : 0.751%
                                 mass_smaller_14 mass                  75 : 0.121% / 90 : 0.415% / 95 : 0.755% / 99 : 1.57%
linear_regression MIST           Base            mass                   75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%
                                 mass_smaller_14 mass              75 : 8.994% / 90 : 17.493% / 95 : 30.286% / 99 : 44.672%
mlp               MIST           Base            mass                 75 : 0.204% / 90 : 0.596% / 95 : 1.317% / 99 : 4.578%
                                 mass_smaller_14 mass                 75 : 0.711% / 90 : 1.212% / 95 : 1.757% / 99 : 3.354%
random_forest     MIST           Base            mass                  75 : 0.004% / 90 : 0.009% / 95 : 0.026% / 99 : 0.48%
                                 mass_smaller_14 mass                 75 : 0.076% / 90 : 0.143% / 95 : 0.211% / 99 : 0.515%
xgboost           MIST           Base            mass                 75 : 0.055% / 90 : 0.194% / 95 : 0.467% / 99 : 1.559%
                                 mass_smaller_14 mass                  75 : 0.364% / 90 : 0.621% / 95 : 0.82% / 99 : 1.313%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
KNN               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
linear_regression MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
mlp               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
random_forest     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
xgboost           MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9919676920924657
                                 mass_smaller_14 mass               0.9994652103837574
KNN               MIST           Base            mass               0.9860770182495742
                                 mass_smaller_14 mass               0.9993197080056749
linear_regression MIST           Base            mass              0.38830292902171926
                                 mass_smaller_14 mass               0.7294304975319248
mlp               MIST           Base            mass               0.9593548446204826
                                 mass_smaller_14 mass               0.9973619756891468
random_forest     MIST           Base            mass               0.9949439900825313
                                 mass_smaller_14 mass               0.9997284223560081
xgboost           MIST           Base            mass               0.9944238807426196
                                 mass_smaller_14 mass               0.9992349115882041

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.721%
                                 mass_smaller_14 mass               0.553%
KNN               MIST           Base            mass               0.949%
                                 mass_smaller_14 mass               0.627%
linear_regression MIST           Base            mass               6.301%
                                 mass_smaller_14 mass              12.426%
mlp               MIST           Base            mass               1.631%
                                 mass_smaller_14 mass               1.333%
random_forest     MIST           Base            mass               0.572%
                                 mass_smaller_14 mass               0.395%
xgboost           MIST           Base            mass                 0.6%
                                 mass_smaller_14 mass               0.672%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.069%
                                 mass_smaller_14 mass              0.198%
KNN               MIST           Base            mass              0.126%
                                 mass_smaller_14 mass              0.272%
linear_regression MIST           Base            mass              2.762%
                                 mass_smaller_14 mass              8.758%
mlp               MIST           Base            mass              0.475%
                                 mass_smaller_14 mass              0.839%
random_forest     MIST           Base            mass               0.07%
                                 mass_smaller_14 mass              0.173%
xgboost           MIST           Base            mass              0.157%
                                 mass_smaller_14 mass              0.419%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.022%
KNN               MIST           Base            mass              0.004%
                                 mass_smaller_14 mass              0.061%
linear_regression MIST           Base            mass              1.595%
                                 mass_smaller_14 mass              5.749%
mlp               MIST           Base            mass              0.115%
                                 mass_smaller_14 mass              0.545%
random_forest     MIST           Base            mass              0.002%
                                 mass_smaller_14 mass              0.044%
xgboost           MIST           Base            mass              0.032%
                                 mass_smaller_14 mass               0.22%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9959955403728619
                                 mass_smaller_14 mass               0.999733532743571
KNN               MIST           Base            mass              0.9931315041563596
                                 mass_smaller_14 mass              0.9996726034047599
linear_regression MIST           Base            mass              0.6497333100274104
                                 mass_smaller_14 mass              0.9286874399666551
mlp               MIST           Base            mass              0.9801734298207664
                                 mass_smaller_14 mass              0.9987250717515364
random_forest     MIST           Base            mass              0.9975811556691733
                                 mass_smaller_14 mass              0.9998659386279564
xgboost           MIST           Base            mass              0.9972366154162345
                                 mass_smaller_14 mass              0.9996279750905939

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               52.61%
                                 mass_smaller_14 mass              17.875%
KNN               MIST           Base            mass              50.028%
                                 mass_smaller_14 mass              12.229%
linear_regression MIST           Base            mass              87.044%
                                 mass_smaller_14 mass              53.149%
mlp               MIST           Base            mass              60.637%
                                 mass_smaller_14 mass              25.342%
random_forest     MIST           Base            mass              33.293%
                                 mass_smaller_14 mass               9.617%
xgboost           MIST           Base            mass              21.469%
                                 mass_smaller_14 mass              11.967%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.61%
                                 mass_smaller_14 mass                 75 : 0.123% / 90 : 0.542% / 95 : 1.113% / 99 : 2.593%
KNN               MIST           Base            mass                   75 : 0.02% / 90 : 0.085% / 95 : 0.29% / 99 : 2.888%
                                 mass_smaller_14 mass                   75 : 0.264% / 90 : 0.813% / 95 : 1.271% / 99 : 2.6%
linear_regression MIST           Base            mass                 75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 mass_smaller_14 mass              75 : 9.665% / 90 : 19.317% / 95 : 29.514% / 99 : 44.616%
mlp               MIST           Base            mass                 75 : 0.241% / 90 : 0.834% / 95 : 1.996% / 99 : 7.733%
                                 mass_smaller_14 mass                 75 : 1.105% / 90 : 1.874% / 95 : 2.514% / 99 : 4.761%
random_forest     MIST           Base            mass                  75 : 0.01% / 90 : 0.037% / 95 : 0.102% / 99 : 1.625%
                                 mass_smaller_14 mass                 75 : 0.163% / 90 : 0.478% / 95 : 0.808% / 99 : 1.802%
xgboost           MIST           Base            mass                 75 : 0.079% / 90 : 0.248% / 95 : 0.643% / 99 : 2.595%
                                 mass_smaller_14 mass                  75 : 0.53% / 90 : 1.078% / 95 : 1.469% / 99 : 2.406%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric except MAX_ER
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except P99

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors

Random forest : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER\
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

#### Conclusions on mass filtering

mass_smaller_3 is always worse than Base.

If reducing worst-case errors is the priority, mass_smaller_14 is preferable; if average accuracy matters more, Base is better.

mass_smaller_30 is a middle ground between Base and mass_smaller_14 but it does not offer enough improvements to be interesting to use.

#### Best models for the mass parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### Radius parameter

In [7]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
KNN               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
mlp               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997963432259059
                                 mass_smaller_3  radius             0.999866660211663
                                 mass_smaller_14 radius            0.9998290497642414
                                 mass_smaller_30 radius            0.9998192497710287
KNN               MIST           Base            radius            0.9998970891526346
                                 mass_smaller_3  radius            0.9999040702564876
                                 mass_smaller_14 radius            0.9999238365249355
                                 mass_smaller_30 radius            0.9999227649971846
linear_regression MIST           Base            radius            0.9854956623390955
                                 mass_smaller_3  radius            0.9928968443499933
                                 mass_smaller_14 radius            0.9915723548914062
                                 mass_smaller_30 radius            0.9911838669288024
mlp               MIST           Base            radius            0.9923727221026404
                                 mass_smaller_3  radius            0.9991367039903855
                                 mass_smaller_14 radius             0.999136672646969
                                 mass_smaller_30 radius            0.9950540236132825
random_forest     MIST           Base            radius            0.9999434532448489
                                 mass_smaller_3  radius             0.999960084444697
                                 mass_smaller_14 radius            0.9999564181903926
                                 mass_smaller_30 radius            0.9999562627341628
xgboost           MIST           Base            radius            0.9996020484794627
                                 mass_smaller_3  radius            0.9998348191009966
                                 mass_smaller_14 radius            0.9997464415773465
                                 mass_smaller_30 radius            0.9996970259826488

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.255%
                                 mass_smaller_3  radius            0.213%
                                 mass_smaller_14 radius            0.226%
                                 mass_smaller_30 radius            0.232%
KNN               MIST           Base            radius            0.181%
                                 mass_smaller_3  radius            0.181%
                                 mass_smaller_14 radius            0.151%
                                 mass_smaller_30 radius            0.151%
linear_regression MIST           Base            radius            2.154%
                                 mass_smaller_3  radius            1.558%
                                 mass_smaller_14 radius            1.586%
                                 mass_smaller_30 radius            1.617%
mlp               MIST           Base            radius            1.593%
                                 mass_smaller_3  radius            0.588%
                                 mass_smaller_14 radius            0.537%
                                 mass_smaller_30 radius            1.476%
random_forest     MIST           Base            radius            0.134%
                                 mass_smaller_3  radius            0.117%
                                 mass_smaller_14 radius            0.114%
                                 mass_smaller_30 radius            0.114%
xgboost           MIST           Base            radius            0.357%
                                 mass_smaller_3  radius            0.238%
                                 mass_smaller_14 radius            0.275%
                                 mass_smaller_30 radius              0.3%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.142%
                                 mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.131%
                                 mass_smaller_30 radius            0.132%
KNN               MIST           Base            radius            0.102%
                                 mass_smaller_3  radius            0.108%
                                 mass_smaller_14 radius            0.093%
                                 mass_smaller_30 radius            0.093%
linear_regression MIST           Base            radius            1.569%
                                 mass_smaller_3  radius             1.17%
                                 mass_smaller_14 radius            1.206%
                                 mass_smaller_30 radius            1.231%
mlp               MIST           Base            radius            1.218%
                                 mass_smaller_3  radius            0.404%
                                 mass_smaller_14 radius            0.384%
                                 mass_smaller_30 radius             1.13%
random_forest     MIST           Base            radius            0.065%
                                 mass_smaller_3  radius            0.053%
                                 mass_smaller_14 radius             0.06%
                                 mass_smaller_30 radius            0.058%
xgboost           MIST           Base            radius            0.258%
                                 mass_smaller_3  radius            0.161%
                                 mass_smaller_14 radius            0.199%
                                 mass_smaller_30 radius            0.219%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.082%
                                 mass_smaller_3  radius            0.066%
                                 mass_smaller_14 radius            0.077%
                                 mass_smaller_30 radius            0.078%
KNN               MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.068%
                                 mass_smaller_14 radius            0.062%
                                 mass_smaller_30 radius            0.061%
linear_regression MIST           Base            radius            1.113%
                                 mass_smaller_3  radius            0.887%
                                 mass_smaller_14 radius            0.976%
                                 mass_smaller_30 radius            0.983%
mlp               MIST           Base            radius            0.968%
                                 mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.306%
                                 mass_smaller_30 radius             0.86%
random_forest     MIST           Base            radius            0.032%
                                 mass_smaller_3  radius            0.026%
                                 mass_smaller_14 radius            0.031%
                                 mass_smaller_30 radius             0.03%
xgboost           MIST           Base            radius            0.197%
                                 mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.153%
                                 mass_smaller_30 radius            0.169%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998982041053214
                                 mass_smaller_3  radius            0.9999333298626585
                                 mass_smaller_14 radius            0.9999145940186054
                                 mass_smaller_30 radius            0.9999096635705038
KNN               MIST           Base            radius            0.9999485752530637
                                 mass_smaller_3  radius            0.9999520800077348
                                 mass_smaller_14 radius            0.9999619536912048
                                 mass_smaller_30 radius            0.9999614086282542
linear_regression MIST           Base            radius            0.9927213417365519
                                 mass_smaller_3  radius            0.9964420928232931
                                 mass_smaller_14 radius            0.9957772616862719
                                 mass_smaller_30 radius            0.9955821748750935
mlp               MIST           Base            radius            0.9961795022934663
                                 mass_smaller_3  radius            0.9995738143553161
                                 mass_smaller_14 radius            0.9995714386703022
                                 mass_smaller_30 radius            0.9975589823528184
random_forest     MIST           Base            radius            0.9999717265543759
                                 mass_smaller_3  radius            0.9999800420415123
                                 mass_smaller_14 radius            0.9999782166433258
                                 mass_smaller_30 radius            0.9999781350071537
xgboost           MIST           Base            radius            0.9998010225765576
                                 mass_smaller_3  radius             0.999917407540224
                                 mass_smaller_14 radius            0.9998732248486286
                                 mass_smaller_30 radius            0.9998485109640335

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.591%
                                 mass_smaller_3  radius             4.519%
                                 mass_smaller_14 radius            10.289%
                                 mass_smaller_30 radius            17.115%
KNN               MIST           Base            radius             7.445%
                                 mass_smaller_3  radius             5.987%
                                 mass_smaller_14 radius             5.056%
                                 mass_smaller_30 radius             6.014%
linear_regression MIST           Base            radius            12.724%
                                 mass_smaller_3  radius            10.931%
                                 mass_smaller_14 radius            11.805%
                                 mass_smaller_30 radius            12.019%
mlp               MIST           Base            radius            14.074%
                                 mass_smaller_3  radius            10.377%
                                 mass_smaller_14 radius             11.26%
                                 mass_smaller_30 radius            12.688%
random_forest     MIST           Base            radius             8.676%
                                 mass_smaller_3  radius             3.915%
                                 mass_smaller_14 radius             3.502%
                                 mass_smaller_30 radius             9.954%
xgboost           MIST           Base            radius            11.866%
                                 mass_smaller_3  radius             5.076%
                                 mass_smaller_14 radius             5.546%
                                 mass_smaller_30 radius             6.672%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            75 : 0.175% / 90 : 0.315% / 95 : 0.443% / 99 : 0.975%
                                 mass_smaller_3  radius            75 : 0.149% / 90 : 0.294% / 95 : 0.373% / 99 : 0.762%
                                 mass_smaller_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
                                 mass_smaller_30 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.404% / 99 : 0.866%
KNN               MIST           Base            radius            75 : 0.124% / 90 : 0.223% / 95 : 0.309% / 99 : 0.655%
                                 mass_smaller_3  radius             75 : 0.135% / 90 : 0.24% / 95 : 0.327% / 99 : 0.629%
                                 mass_smaller_14 radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
                                 mass_smaller_30 radius            75 : 0.118% / 90 : 0.208% / 95 : 0.278% / 99 : 0.526%
linear_regression MIST           Base            radius            75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 mass_smaller_3  radius             75 : 1.64% / 90 : 2.621% / 95 : 3.242% / 99 : 4.505%
                                 mass_smaller_14 radius             75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
                                 mass_smaller_30 radius            75 : 1.822% / 90 : 2.598% / 95 : 3.113% / 99 : 4.567%
mlp               MIST           Base            radius             75 : 1.701% / 90 : 2.581% / 95 : 3.181% / 99 : 4.68%
                                 mass_smaller_3  radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                                 mass_smaller_14 radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
                                 mass_smaller_30 radius            75 : 1.604% / 90 : 2.511% / 95 : 3.019% / 99 : 4.046%
random_forest     MIST           Base            radius            75 : 0.075% / 90 : 0.152% / 95 : 0.228% / 99 : 0.499%
                                 mass_smaller_3  radius             75 : 0.06% / 90 : 0.119% / 95 : 0.175% / 99 : 0.395%
                                 mass_smaller_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
                                 mass_smaller_30 radius            75 : 0.069% / 90 : 0.136% / 95 : 0.199% / 99 : 0.412%
xgboost           MIST           Base            radius            75 : 0.354% / 90 : 0.546% / 95 : 0.692% / 99 : 1.079%
                                 mass_smaller_3  radius             75 : 0.214% / 90 : 0.34% / 95 : 0.441% / 99 : 0.747%
                                 mass_smaller_14 radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%
                                 mass_smaller_30 radius            75 : 0.304% / 90 : 0.467% / 95 : 0.583% / 99 : 0.854%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997790154053315
                                 mass_smaller_3  radius            0.9998249631057525
                                 mass_smaller_14 radius            0.9997880404019214
                                 mass_smaller_30 radius            0.9997969300603281
KNN               MIST           Base            radius            0.9998333563537635
                                 mass_smaller_3  radius            0.9996571642468787
                                 mass_smaller_14 radius            0.9998255884455621
                                 mass_smaller_30 radius            0.9998699911918713
linear_regression MIST           Base            radius            0.9778146729622458
                                 mass_smaller_3  radius            0.9753521021495244
                                 mass_smaller_14 radius            0.9830496323087852
                                 mass_smaller_30 radius            0.9862122881365466
mlp               MIST           Base            radius            0.9874097628400822
                                 mass_smaller_3  radius            0.9983513710056814
                                 mass_smaller_14 radius            0.9983627542851781
                                 mass_smaller_30 radius            0.9901288111552154
random_forest     MIST           Base            radius            0.9999465508573717
                                 mass_smaller_3  radius            0.9999678953910232
                                 mass_smaller_14 radius            0.9999534137978472
                                 mass_smaller_30 radius            0.9999559178590984
xgboost           MIST           Base            radius            0.9994380170169319
                                 mass_smaller_3  radius            0.9996075937684589
                                 mass_smaller_14 radius            0.9995117695213523
                                 mass_smaller_30 radius            0.9995381873053741

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.208%
                                 mass_smaller_3  radius            0.239%
                                 mass_smaller_14 radius             0.15%
                                 mass_smaller_30 radius            0.177%
KNN               MIST           Base            radius             0.18%
                                 mass_smaller_3  radius            0.335%
                                 mass_smaller_14 radius            0.136%
                                 mass_smaller_30 radius            0.141%
linear_regression MIST           Base            radius            2.083%
                                 mass_smaller_3  radius             2.87%
                                 mass_smaller_14 radius            1.353%
                                 mass_smaller_30 radius             1.46%
mlp               MIST           Base            radius            1.594%
                                 mass_smaller_3  radius             0.92%
                                 mass_smaller_14 radius            0.441%
                                 mass_smaller_30 radius            1.528%
random_forest     MIST           Base            radius            0.102%
                                 mass_smaller_3  radius            0.103%
                                 mass_smaller_14 radius            0.071%
                                 mass_smaller_30 radius            0.082%
xgboost           MIST           Base            radius            0.331%
                                 mass_smaller_3  radius            0.358%
                                 mass_smaller_14 radius            0.228%
                                 mass_smaller_30 radius            0.266%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.113%
                                 mass_smaller_3  radius            0.152%
                                 mass_smaller_14 radius            0.089%
                                 mass_smaller_30 radius            0.098%
KNN               MIST           Base            radius            0.105%
                                 mass_smaller_3  radius            0.219%
                                 mass_smaller_14 radius             0.09%
                                 mass_smaller_30 radius            0.092%
linear_regression MIST           Base            radius            1.628%
                                 mass_smaller_3  radius            2.086%
                                 mass_smaller_14 radius            1.037%
                                 mass_smaller_30 radius            1.138%
mlp               MIST           Base            radius            1.213%
                                 mass_smaller_3  radius            0.672%
                                 mass_smaller_14 radius            0.346%
                                 mass_smaller_30 radius            1.163%
random_forest     MIST           Base            radius            0.051%
                                 mass_smaller_3  radius            0.063%
                                 mass_smaller_14 radius             0.04%
                                 mass_smaller_30 radius            0.043%
xgboost           MIST           Base            radius            0.244%
                                 mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.174%
                                 mass_smaller_30 radius            0.202%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.064%
                                 mass_smaller_3  radius            0.101%
                                 mass_smaller_14 radius            0.056%
                                 mass_smaller_30 radius            0.059%
KNN               MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.136%
                                 mass_smaller_14 radius            0.058%
                                 mass_smaller_30 radius             0.06%
linear_regression MIST           Base            radius            1.286%
                                 mass_smaller_3  radius            1.579%
                                 mass_smaller_14 radius            0.829%
                                 mass_smaller_30 radius            0.922%
mlp               MIST           Base            radius            0.964%
                                 mass_smaller_3  radius            0.467%
                                 mass_smaller_14 radius            0.292%
                                 mass_smaller_30 radius            0.874%
random_forest     MIST           Base            radius            0.025%
                                 mass_smaller_3  radius            0.039%
                                 mass_smaller_14 radius            0.022%
                                 mass_smaller_30 radius            0.023%
xgboost           MIST           Base            radius            0.184%
                                 mass_smaller_3  radius            0.214%
                                 mass_smaller_14 radius            0.136%
                                 mass_smaller_30 radius            0.156%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998895445736318
                                 mass_smaller_3  radius            0.9999125211077539
                                 mass_smaller_14 radius            0.9998940164221873
                                 mass_smaller_30 radius             0.999898462338922
KNN               MIST           Base            radius            0.9999169942116342
                                 mass_smaller_3  radius             0.999830888291084
                                 mass_smaller_14 radius            0.9999135578590763
                                 mass_smaller_30 radius            0.9999353240819183
linear_regression MIST           Base            radius            0.9888944199376599
                                 mass_smaller_3  radius            0.9879836947112961
                                 mass_smaller_14 radius            0.9914885941715924
                                 mass_smaller_30 radius            0.9930892072248287
mlp               MIST           Base            radius            0.9936897796640443
                                 mass_smaller_3  radius            0.9992197462781777
                                 mass_smaller_14 radius            0.9991810430555029
                                 mass_smaller_30 radius             0.995207168464403
random_forest     MIST           Base            radius            0.9999733173582267
                                 mass_smaller_3  radius            0.9999840579307431
                                 mass_smaller_14 radius            0.9999767231025315
                                 mass_smaller_30 radius            0.9999779588394017
xgboost           MIST           Base            radius            0.9997190014385369
                                 mass_smaller_3  radius            0.9998037782605148
                                 mass_smaller_14 radius            0.9997558778235092
                                 mass_smaller_30 radius            0.9997690783741953

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.724%
                                 mass_smaller_3  radius             4.663%
                                 mass_smaller_14 radius             7.812%
                                 mass_smaller_30 radius            17.312%
KNN               MIST           Base            radius             3.779%
                                 mass_smaller_3  radius             5.368%
                                 mass_smaller_14 radius             1.439%
                                 mass_smaller_30 radius             1.762%
linear_regression MIST           Base            radius            11.227%
                                 mass_smaller_3  radius            12.801%
                                 mass_smaller_14 radius             5.381%
                                 mass_smaller_30 radius             5.029%
mlp               MIST           Base            radius            10.023%
                                 mass_smaller_3  radius             3.953%
                                 mass_smaller_14 radius             4.054%
                                 mass_smaller_30 radius             6.651%
random_forest     MIST           Base            radius             8.775%
                                 mass_smaller_3  radius             2.464%
                                 mass_smaller_14 radius             3.502%
                                 mass_smaller_30 radius            10.068%
xgboost           MIST           Base            radius              3.33%
                                 mass_smaller_3  radius             6.229%
                                 mass_smaller_14 radius             1.596%
                                 mass_smaller_30 radius             2.296%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.131% / 90 : 0.252% / 95 : 0.372% / 99 : 0.797%
                                 mass_smaller_3  radius              75 : 0.199% / 90 : 0.324% / 95 : 0.448% / 99 : 0.89%
                                 mass_smaller_14 radius             75 : 0.112% / 90 : 0.197% / 95 : 0.278% / 99 : 0.584%
                                 mass_smaller_30 radius             75 : 0.119% / 90 : 0.218% / 95 : 0.307% / 99 : 0.658%
KNN               MIST           Base            radius             75 : 0.127% / 90 : 0.234% / 95 : 0.332% / 99 : 0.647%
                                 mass_smaller_3  radius             75 : 0.275% / 90 : 0.515% / 95 : 0.723% / 99 : 1.238%
                                 mass_smaller_14 radius             75 : 0.113% / 90 : 0.205% / 95 : 0.285% / 99 : 0.514%
                                 mass_smaller_30 radius             75 : 0.116% / 90 : 0.211% / 95 : 0.291% / 99 : 0.531%
linear_regression MIST           Base            radius              75 : 2.358% / 90 : 3.301% / 95 : 3.855% / 99 : 6.14%
                                 mass_smaller_3  radius            75 : 2.801% / 90 : 4.245% / 95 : 5.738% / 99 : 10.075%
                                 mass_smaller_14 radius             75 : 1.559% / 90 : 2.251% / 95 : 2.664% / 99 : 3.814%
                                 mass_smaller_30 radius              75 : 1.74% / 90 : 2.487% / 95 : 2.896% / 99 : 3.595%
mlp               MIST           Base            radius             75 : 1.668% / 90 : 2.575% / 95 : 3.252% / 99 : 4.813%
                                 mass_smaller_3  radius               75 : 0.963% / 90 : 1.592% / 95 : 1.971% / 99 : 2.7%
                                 mass_smaller_14 radius             75 : 0.488% / 90 : 0.697% / 95 : 0.836% / 99 : 1.194%
                                 mass_smaller_30 radius             75 : 1.671% / 90 : 2.569% / 95 : 3.191% / 99 : 4.273%
random_forest     MIST           Base            radius             75 : 0.057% / 90 : 0.119% / 95 : 0.184% / 99 : 0.404%
                                 mass_smaller_3  radius             75 : 0.081% / 90 : 0.145% / 95 : 0.202% / 99 : 0.373%
                                 mass_smaller_14 radius             75 : 0.047% / 90 : 0.092% / 95 : 0.136% / 99 : 0.278%
                                 mass_smaller_30 radius              75 : 0.05% / 90 : 0.099% / 95 : 0.149% / 99 : 0.314%
xgboost           MIST           Base            radius             75 : 0.334% / 90 : 0.527% / 95 : 0.675% / 99 : 1.035%
                                 mass_smaller_3  radius             75 : 0.382% / 90 : 0.581% / 95 : 0.732% / 99 : 1.059%
                                 mass_smaller_14 radius             75 : 0.243% / 90 : 0.373% / 95 : 0.467% / 99 : 0.669%
                                 mass_smaller_30 radius              75 : 0.283% / 90 : 0.438% / 95 : 0.549% / 99 : 0.78%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
KNN               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
linear_regression MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
mlp               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
random_forest     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
xgboost           MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9996013815341348
                                 mass_smaller_3  radius            0.9995465768676972
                                 mass_smaller_14 radius            0.9995039197290129
                                 mass_smaller_30 radius            0.9995266839683316
KNN               MIST           Base            radius            0.9999055166815642
                                 mass_smaller_3  radius            0.9998807428184813
                                 mass_smaller_14 radius            0.9998943160073213
                                 mass_smaller_30 radius            0.9998962596584994
linear_regression MIST           Base            radius            0.9679744997103377
                                 mass_smaller_3  radius            0.9833773452801731
                                 mass_smaller_14 radius            0.9806856109752665
                                 mass_smaller_30 radius            0.9801561070378554
mlp               MIST           Base            radius             0.984995693437375
                                 mass_smaller_3  radius            0.9978060724763279
                                 mass_smaller_14 radius             0.998723350903017
                                 mass_smaller_30 radius            0.9906433853956087
random_forest     MIST           Base            radius            0.9999326234217092
                                 mass_smaller_3  radius            0.9999301508060892
                                 mass_smaller_14 radius            0.9999185082513201
                                 mass_smaller_30 radius            0.9999308463547795
xgboost           MIST           Base            radius            0.9992306813494213
                                 mass_smaller_3  radius            0.9995508512748904
                                 mass_smaller_14 radius            0.9994208286577492
                                 mass_smaller_30 radius            0.9992951333672936

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.35%
                                 mass_smaller_3  radius            0.437%
                                 mass_smaller_14 radius            0.373%
                                 mass_smaller_30 radius            0.352%
KNN               MIST           Base            radius             0.17%
                                 mass_smaller_3  radius            0.224%
                                 mass_smaller_14 radius            0.172%
                                 mass_smaller_30 radius            0.165%
linear_regression MIST           Base            radius            3.158%
                                 mass_smaller_3  radius            2.771%
                                 mass_smaller_14 radius            2.381%
                                 mass_smaller_30 radius            2.313%
mlp               MIST           Base            radius            2.256%
                                 mass_smaller_3  radius            1.108%
                                 mass_smaller_14 radius            0.599%
                                 mass_smaller_30 radius            2.159%
random_forest     MIST           Base            radius            0.145%
                                 mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.153%
                                 mass_smaller_30 radius            0.136%
xgboost           MIST           Base            radius            0.487%
                                 mass_smaller_3  radius            0.435%
                                 mass_smaller_14 radius            0.404%
                                 mass_smaller_30 radius             0.43%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.241%
                                 mass_smaller_3  radius            0.322%
                                 mass_smaller_14 radius            0.264%
                                 mass_smaller_30 radius            0.247%
KNN               MIST           Base            radius            0.123%
                                 mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.131%
                                 mass_smaller_30 radius            0.124%
linear_regression MIST           Base            radius            2.062%
                                 mass_smaller_3  radius            2.218%
                                 mass_smaller_14 radius            1.855%
                                 mass_smaller_30 radius            1.748%
mlp               MIST           Base            radius            1.756%
                                 mass_smaller_3  radius            0.799%
                                 mass_smaller_14 radius            0.473%
                                 mass_smaller_30 radius             1.71%
random_forest     MIST           Base            radius            0.096%
                                 mass_smaller_3  radius             0.12%
                                 mass_smaller_14 radius            0.105%
                                 mass_smaller_30 radius            0.093%
xgboost           MIST           Base            radius            0.381%
                                 mass_smaller_3  radius            0.333%
                                 mass_smaller_14 radius            0.314%
                                 mass_smaller_30 radius            0.336%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.186%
                                 mass_smaller_3  radius            0.263%
                                 mass_smaller_14 radius            0.217%
                                 mass_smaller_30 radius            0.199%
KNN               MIST           Base            radius            0.091%
                                 mass_smaller_3  radius            0.137%
                                 mass_smaller_14 radius            0.103%
                                 mass_smaller_30 radius            0.094%
linear_regression MIST           Base            radius            1.212%
                                 mass_smaller_3  radius            1.872%
                                 mass_smaller_14 radius            1.509%
                                 mass_smaller_30 radius            1.347%
mlp               MIST           Base            radius            1.419%
                                 mass_smaller_3  radius            0.527%
                                 mass_smaller_14 radius            0.389%
                                 mass_smaller_30 radius            1.365%
random_forest     MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.083%
                                 mass_smaller_14 radius            0.072%
                                 mass_smaller_30 radius            0.063%
xgboost           MIST           Base            radius            0.313%
                                 mass_smaller_3  radius            0.266%
                                 mass_smaller_14 radius            0.255%
                                 mass_smaller_30 radius            0.276%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998018770327872
                                 mass_smaller_3  radius            0.9997733155946078
                                 mass_smaller_14 radius            0.9997540306645297
                                 mass_smaller_30 radius            0.9997651809159842
KNN               MIST           Base            radius            0.9999527572442021
                                 mass_smaller_3  radius            0.9999404528865401
                                 mass_smaller_14 radius            0.9999471831409968
                                 mass_smaller_30 radius            0.9999481574096413
linear_regression MIST           Base            radius            0.9838665758685889
                                 mass_smaller_3  radius             0.993268227885979
                                 mass_smaller_14 radius            0.9909797904600514
                                 mass_smaller_30 radius            0.9907926454524565
mlp               MIST           Base            radius             0.992574201430493
                                 mass_smaller_3  radius            0.9989117384154471
                                 mass_smaller_14 radius            0.9993643661222952
                                 mass_smaller_30 radius            0.9953134588767328
random_forest     MIST           Base            radius             0.999966988493253
                                 mass_smaller_3  radius            0.9999650748236046
                                 mass_smaller_14 radius            0.9999605620655518
                                 mass_smaller_30 radius            0.9999665535016122
xgboost           MIST           Base            radius            0.9996159124585666
                                 mass_smaller_3  radius            0.9997754108047239
                                 mass_smaller_14 radius            0.9997106655945553
                                 mass_smaller_30 radius            0.9996484433732039

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             6.585%
                                 mass_smaller_3  radius             5.347%
                                 mass_smaller_14 radius              15.1%
                                 mass_smaller_30 radius             7.242%
KNN               MIST           Base            radius             2.759%
                                 mass_smaller_3  radius             3.109%
                                 mass_smaller_14 radius             2.265%
                                 mass_smaller_30 radius             1.941%
linear_regression MIST           Base            radius            16.177%
                                 mass_smaller_3  radius             7.833%
                                 mass_smaller_14 radius             8.961%
                                 mass_smaller_30 radius             9.351%
mlp               MIST           Base            radius            13.166%
                                 mass_smaller_3  radius             4.322%
                                 mass_smaller_14 radius              4.45%
                                 mass_smaller_30 radius             8.692%
random_forest     MIST           Base            radius             3.256%
                                 mass_smaller_3  radius             2.008%
                                 mass_smaller_14 radius             2.388%
                                 mass_smaller_30 radius             1.795%
xgboost           MIST           Base            radius              2.63%
                                 mass_smaller_3  radius             2.523%
                                 mass_smaller_14 radius             2.615%
                                 mass_smaller_30 radius             2.329%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.324% / 90 : 0.48% / 95 : 0.593% / 99 : 1.125%
                                 mass_smaller_3  radius             75 : 0.491% / 90 : 0.627% / 95 : 0.747% / 99 : 1.318%
                                 mass_smaller_14 radius             75 : 0.354% / 90 : 0.499% / 95 : 0.622% / 99 : 1.155%
                                 mass_smaller_30 radius             75 : 0.335% / 90 : 0.484% / 95 : 0.594% / 99 : 1.105%
KNN               MIST           Base            radius             75 : 0.168% / 90 : 0.276% / 95 : 0.349% / 99 : 0.519%
                                 mass_smaller_3  radius              75 : 0.236% / 90 : 0.368% / 95 : 0.449% / 99 : 0.63%
                                 mass_smaller_14 radius             75 : 0.178% / 90 : 0.285% / 95 : 0.354% / 99 : 0.494%
                                 mass_smaller_30 radius             75 : 0.169% / 90 : 0.274% / 95 : 0.342% / 99 : 0.482%
linear_regression MIST           Base            radius            75 : 2.625% / 90 : 5.047% / 95 : 6.932% / 99 : 12.502%
                                 mass_smaller_3  radius             75 : 3.379% / 90 : 4.724% / 95 : 5.395% / 99 : 6.276%
                                 mass_smaller_14 radius             75 : 2.614% / 90 : 3.907% / 95 : 4.838% / 99 : 6.671%
                                 mass_smaller_30 radius              75 : 2.553% / 90 : 3.763% / 95 : 4.72% / 99 : 6.837%
mlp               MIST           Base            radius             75 : 2.537% / 90 : 3.715% / 95 : 4.431% / 99 : 6.101%
                                 mass_smaller_3  radius              75 : 1.086% / 90 : 2.065% / 95 : 2.465% / 99 : 3.16%
                                 mass_smaller_14 radius             75 : 0.684% / 90 : 0.991% / 95 : 1.184% / 99 : 1.535%
                                 mass_smaller_30 radius             75 : 2.439% / 90 : 3.767% / 95 : 4.396% / 99 : 5.328%
random_forest     MIST           Base            radius              75 : 0.128% / 90 : 0.22% / 95 : 0.296% / 99 : 0.502%
                                 mass_smaller_3  radius             75 : 0.164% / 90 : 0.272% / 95 : 0.354% / 99 : 0.554%
                                 mass_smaller_14 radius             75 : 0.142% / 90 : 0.239% / 95 : 0.315% / 99 : 0.514%
                                 mass_smaller_30 radius              75 : 0.125% / 90 : 0.212% / 95 : 0.28% / 99 : 0.459%
xgboost           MIST           Base            radius             75 : 0.541% / 90 : 0.793% / 95 : 0.966% / 99 : 1.343%
                                 mass_smaller_3  radius              75 : 0.463% / 90 : 0.706% / 95 : 0.879% / 99 : 1.28%
                                 mass_smaller_14 radius              75 : 0.448% / 90 : 0.66% / 95 : 0.808% / 99 : 1.134%
                                 mass_smaller_30 radius             75 : 0.478% / 90 : 0.705% / 95 : 0.861% / 99 : 1.184%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

Results for the phase category with a value of 3.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
KNN               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
mlp               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.999266684393612
                                 mass_smaller_3  radius            0.9992381885703833
                                 mass_smaller_14 radius            0.9993395139862439
                                 mass_smaller_30 radius            0.9993527873099591
KNN               MIST           Base            radius            0.9996720394056582
                                 mass_smaller_3  radius            0.9994853264493573
                                 mass_smaller_14 radius            0.9997229263417253
                                 mass_smaller_30 radius            0.9997331093747082
linear_regression MIST           Base            radius              0.96988742831239
                                 mass_smaller_3  radius            0.9740128136920825
                                 mass_smaller_14 radius            0.9746821269484942
                                 mass_smaller_30 radius             0.975405297113159
mlp               MIST           Base            radius            0.9847763915139012
                                 mass_smaller_3  radius            0.9952899598276022
                                 mass_smaller_14 radius            0.9970644512745905
                                 mass_smaller_30 radius            0.9902981482812612
random_forest     MIST           Base            radius            0.9997339847238751
                                 mass_smaller_3  radius            0.9996570039158864
                                 mass_smaller_14 radius             0.999774074221781
                                 mass_smaller_30 radius            0.9997907782006465
xgboost           MIST           Base            radius            0.9989178719473903
                                 mass_smaller_3  radius            0.9991584798800517
                                 mass_smaller_14 radius            0.9991636868686137
                                 mass_smaller_30 radius            0.9991259310343945

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.447%
                                 mass_smaller_3  radius            0.478%
                                 mass_smaller_14 radius            0.456%
                                 mass_smaller_30 radius              0.4%
KNN               MIST           Base            radius            0.299%
                                 mass_smaller_3  radius            0.393%
                                 mass_smaller_14 radius            0.295%
                                 mass_smaller_30 radius            0.257%
linear_regression MIST           Base            radius            2.866%
                                 mass_smaller_3  radius            2.794%
                                 mass_smaller_14 radius            2.821%
                                 mass_smaller_30 radius            2.462%
mlp               MIST           Base            radius            2.046%
                                 mass_smaller_3  radius            1.188%
                                 mass_smaller_14 radius            1.158%
                                 mass_smaller_30 radius            1.641%
random_forest     MIST           Base            radius             0.27%
                                 mass_smaller_3  radius            0.321%
                                 mass_smaller_14 radius            0.268%
                                 mass_smaller_30 radius            0.228%
xgboost           MIST           Base            radius            0.543%
                                 mass_smaller_3  radius            0.503%
                                 mass_smaller_14 radius            0.514%
                                 mass_smaller_30 radius            0.465%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.232%
                                 mass_smaller_3  radius             0.23%
                                 mass_smaller_14 radius            0.243%
                                 mass_smaller_30 radius            0.215%
KNN               MIST           Base            radius            0.146%
                                 mass_smaller_3  radius            0.188%
                                 mass_smaller_14 radius             0.15%
                                 mass_smaller_30 radius            0.131%
linear_regression MIST           Base            radius            2.006%
                                 mass_smaller_3  radius            2.203%
                                 mass_smaller_14 radius            2.185%
                                 mass_smaller_30 radius            1.883%
mlp               MIST           Base            radius            1.548%
                                 mass_smaller_3  radius            0.821%
                                 mass_smaller_14 radius            0.789%
                                 mass_smaller_30 radius            1.216%
random_forest     MIST           Base            radius            0.128%
                                 mass_smaller_3  radius            0.138%
                                 mass_smaller_14 radius            0.134%
                                 mass_smaller_30 radius            0.113%
xgboost           MIST           Base            radius            0.361%
                                 mass_smaller_3  radius              0.3%
                                 mass_smaller_14 radius             0.34%
                                 mass_smaller_30 radius             0.31%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.116%
                                 mass_smaller_3  radius            0.106%
                                 mass_smaller_14 radius             0.12%
                                 mass_smaller_30 radius             0.11%
KNN               MIST           Base            radius            0.076%
                                 mass_smaller_3  radius            0.093%
                                 mass_smaller_14 radius            0.082%
                                 mass_smaller_30 radius            0.072%
linear_regression MIST           Base            radius            1.329%
                                 mass_smaller_3  radius            1.885%
                                 mass_smaller_14 radius            1.865%
                                 mass_smaller_30 radius            1.541%
mlp               MIST           Base            radius             1.21%
                                 mass_smaller_3  radius             0.61%
                                 mass_smaller_14 radius            0.609%
                                 mass_smaller_30 radius            0.911%
random_forest     MIST           Base            radius            0.057%
                                 mass_smaller_3  radius            0.057%
                                 mass_smaller_14 radius            0.064%
                                 mass_smaller_30 radius            0.054%
xgboost           MIST           Base            radius            0.262%
                                 mass_smaller_3  radius            0.193%
                                 mass_smaller_14 radius            0.245%
                                 mass_smaller_30 radius            0.227%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9996333392274228
                                 mass_smaller_3  radius            0.9996192777071335
                                 mass_smaller_14 radius            0.9996699530747309
                                 mass_smaller_30 radius            0.9996764243680272
KNN               MIST           Base            radius            0.9998360691463095
                                 mass_smaller_3  radius            0.9997430849980539
                                 mass_smaller_14 radius            0.9998615008366036
                                 mass_smaller_30 radius              0.99986658819855
linear_regression MIST           Base            radius            0.9849992743688404
                                 mass_smaller_3  radius            0.9886235406128182
                                 mass_smaller_14 radius            0.9873693027486672
                                 mass_smaller_30 radius            0.9876332691760843
mlp               MIST           Base            radius             0.992384420506142
                                 mass_smaller_3  radius            0.9976629398298685
                                 mass_smaller_14 radius            0.9985438860810399
                                 mass_smaller_30 radius            0.9951504215106092
random_forest     MIST           Base            radius            0.9998670249575315
                                 mass_smaller_3  radius            0.9998285901743722
                                 mass_smaller_14 radius            0.9998870342476956
                                 mass_smaller_30 radius            0.9998953876885145
xgboost           MIST           Base            radius            0.9994588839474633
                                 mass_smaller_3  radius             0.999579231894782
                                 mass_smaller_14 radius            0.9995818580147785
                                 mass_smaller_30 radius            0.9995630100375634

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.071%
                                 mass_smaller_3  radius             6.307%
                                 mass_smaller_14 radius             5.599%
                                 mass_smaller_30 radius             5.599%
KNN               MIST           Base            radius             8.844%
                                 mass_smaller_3  radius             8.357%
                                 mass_smaller_14 radius             6.904%
                                 mass_smaller_30 radius             7.141%
linear_regression MIST           Base            radius            15.116%
                                 mass_smaller_3  radius            15.259%
                                 mass_smaller_14 radius            16.119%
                                 mass_smaller_30 radius            14.271%
mlp               MIST           Base            radius             16.72%
                                 mass_smaller_3  radius            14.485%
                                 mass_smaller_14 radius            15.375%
                                 mass_smaller_30 radius            15.065%
random_forest     MIST           Base            radius             8.677%
                                 mass_smaller_3  radius             5.464%
                                 mass_smaller_14 radius             4.315%
                                 mass_smaller_30 radius             3.923%
xgboost           MIST           Base            radius            14.096%
                                 mass_smaller_3  radius             7.085%
                                 mass_smaller_14 radius             7.573%
                                 mass_smaller_30 radius             7.922%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.269% / 90 : 0.531% / 95 : 0.834% / 99 : 1.94%
                                 mass_smaller_3  radius            75 : 0.264% / 90 : 0.512% / 95 : 0.827% / 99 : 2.382%
                                 mass_smaller_14 radius             75 : 0.29% / 90 : 0.571% / 95 : 0.873% / 99 : 2.009%
                                 mass_smaller_30 radius            75 : 0.258% / 90 : 0.502% / 95 : 0.764% / 99 : 1.747%
KNN               MIST           Base            radius              75 : 0.17% / 90 : 0.316% / 95 : 0.47% / 99 : 1.317%
                                 mass_smaller_3  radius             75 : 0.212% / 90 : 0.405% / 95 : 0.626% / 99 : 1.88%
                                 mass_smaller_14 radius             75 : 0.185% / 90 : 0.328% / 95 : 0.46% / 99 : 1.275%
                                 mass_smaller_30 radius            75 : 0.161% / 90 : 0.289% / 95 : 0.402% / 99 : 1.089%
linear_regression MIST           Base            radius            75 : 2.479% / 90 : 4.855% / 95 : 6.506% / 99 : 9.473%
                                 mass_smaller_3  radius             75 : 3.38% / 90 : 4.458% / 95 : 5.013% / 99 : 6.569%
                                 mass_smaller_14 radius            75 : 3.015% / 90 : 4.239% / 95 : 5.318% / 99 : 8.521%
                                 mass_smaller_30 radius            75 : 2.615% / 90 : 3.721% / 95 : 4.855% / 99 : 7.622%
mlp               MIST           Base            radius            75 : 2.176% / 90 : 3.268% / 95 : 3.987% / 99 : 6.045%
                                 mass_smaller_3  radius             75 : 1.14% / 90 : 1.655% / 95 : 2.022% / 99 : 3.697%
                                 mass_smaller_14 radius            75 : 1.049% / 90 : 1.573% / 95 : 1.949% / 99 : 3.761%
                                 mass_smaller_30 radius            75 : 1.652% / 90 : 2.764% / 95 : 3.312% / 99 : 4.502%
random_forest     MIST           Base            radius            75 : 0.144% / 90 : 0.298% / 95 : 0.459% / 99 : 1.197%
                                 mass_smaller_3  radius              75 : 0.14% / 90 : 0.298% / 95 : 0.511% / 99 : 1.54%
                                 mass_smaller_14 radius            75 : 0.158% / 90 : 0.318% / 95 : 0.472% / 99 : 1.088%
                                 mass_smaller_30 radius              75 : 0.132% / 90 : 0.267% / 95 : 0.4% / 99 : 0.955%
xgboost           MIST           Base            radius             75 : 0.474% / 90 : 0.747% / 95 : 0.98% / 99 : 1.909%
                                 mass_smaller_3  radius              75 : 0.36% / 90 : 0.61% / 95 : 0.891% / 99 : 2.138%
                                 mass_smaller_14 radius            75 : 0.444% / 90 : 0.691% / 95 : 0.915% / 99 : 1.895%
                                 mass_smaller_30 radius            75 : 0.408% / 90 : 0.639% / 95 : 0.823% / 99 : 1.666%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

In [8]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["mass_smaller_3", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
KNN               MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
linear_regression MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
mlp               MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
random_forest     MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
xgboost           MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             0.999866660211663
                                 mass_smaller_14 radius            0.9998290497642414
KNN               MIST           mass_smaller_3  radius            0.9999040702564876
                                 mass_smaller_14 radius            0.9999238365249355
linear_regression MIST           mass_smaller_3  radius            0.9928968443499933
                                 mass_smaller_14 radius            0.9915723548914062
mlp               MIST           mass_smaller_3  radius            0.9991367039903855
                                 mass_smaller_14 radius             0.999136672646969
random_forest     MIST           mass_smaller_3  radius             0.999960084444697
                                 mass_smaller_14 radius            0.9999564181903926
xgboost           MIST           mass_smaller_3  radius            0.9998348191009966
                                 mass_smaller_14 radius            0.9997464415773465

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.213%
                                 mass_smaller_14 radius            0.226%
KNN               MIST           mass_smaller_3  radius            0.181%
                                 mass_smaller_14 radius            0.151%
linear_regression MIST           mass_smaller_3  radius            1.558%
                                 mass_smaller_14 radius            1.586%
mlp               MIST           mass_smaller_3  radius            0.588%
                                 mass_smaller_14 radius            0.537%
random_forest     MIST           mass_smaller_3  radius            0.117%
                                 mass_smaller_14 radius            0.114%
xgboost           MIST           mass_smaller_3  radius            0.238%
                                 mass_smaller_14 radius            0.275%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.131%
KNN               MIST           mass_smaller_3  radius            0.108%
                                 mass_smaller_14 radius            0.093%
linear_regression MIST           mass_smaller_3  radius             1.17%
                                 mass_smaller_14 radius            1.206%
mlp               MIST           mass_smaller_3  radius            0.404%
                                 mass_smaller_14 radius            0.384%
random_forest     MIST           mass_smaller_3  radius            0.053%
                                 mass_smaller_14 radius             0.06%
xgboost           MIST           mass_smaller_3  radius            0.161%
                                 mass_smaller_14 radius            0.199%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.066%
                                 mass_smaller_14 radius            0.077%
KNN               MIST           mass_smaller_3  radius            0.068%
                                 mass_smaller_14 radius            0.062%
linear_regression MIST           mass_smaller_3  radius            0.887%
                                 mass_smaller_14 radius            0.976%
mlp               MIST           mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.306%
random_forest     MIST           mass_smaller_3  radius            0.026%
                                 mass_smaller_14 radius            0.031%
xgboost           MIST           mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.153%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9999333298626585
                                 mass_smaller_14 radius            0.9999145940186054
KNN               MIST           mass_smaller_3  radius            0.9999520800077348
                                 mass_smaller_14 radius            0.9999619536912048
linear_regression MIST           mass_smaller_3  radius            0.9964420928232931
                                 mass_smaller_14 radius            0.9957772616862719
mlp               MIST           mass_smaller_3  radius            0.9995738143553161
                                 mass_smaller_14 radius            0.9995714386703022
random_forest     MIST           mass_smaller_3  radius            0.9999800420415123
                                 mass_smaller_14 radius            0.9999782166433258
xgboost           MIST           mass_smaller_3  radius             0.999917407540224
                                 mass_smaller_14 radius            0.9998732248486286

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             4.519%
                                 mass_smaller_14 radius            10.289%
KNN               MIST           mass_smaller_3  radius             5.987%
                                 mass_smaller_14 radius             5.056%
linear_regression MIST           mass_smaller_3  radius            10.931%
                                 mass_smaller_14 radius            11.805%
mlp               MIST           mass_smaller_3  radius            10.377%
                                 mass_smaller_14 radius             11.26%
random_forest     MIST           mass_smaller_3  radius             3.915%
                                 mass_smaller_14 radius             3.502%
xgboost           MIST           mass_smaller_3  radius             5.076%
                                 mass_smaller_14 radius             5.546%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.149% / 90 : 0.294% / 95 : 0.373% / 99 : 0.762%
                                 mass_smaller_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
KNN               MIST           mass_smaller_3  radius             75 : 0.135% / 90 : 0.24% / 95 : 0.327% / 99 : 0.629%
                                 mass_smaller_14 radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
linear_regression MIST           mass_smaller_3  radius             75 : 1.64% / 90 : 2.621% / 95 : 3.242% / 99 : 4.505%
                                 mass_smaller_14 radius             75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
mlp               MIST           mass_smaller_3  radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                                 mass_smaller_14 radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
random_forest     MIST           mass_smaller_3  radius             75 : 0.06% / 90 : 0.119% / 95 : 0.175% / 99 : 0.395%
                                 mass_smaller_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
xgboost           MIST           mass_smaller_3  radius             75 : 0.214% / 90 : 0.34% / 95 : 0.441% / 99 : 0.747%
                                 mass_smaller_14 radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
KNN               MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
linear_regression MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
mlp               MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
random_forest     MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
xgboost           MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9998249631057525
                                 mass_smaller_14 radius            0.9997880404019214
KNN               MIST           mass_smaller_3  radius            0.9996571642468787
                                 mass_smaller_14 radius            0.9998255884455621
linear_regression MIST           mass_smaller_3  radius            0.9753521021495244
                                 mass_smaller_14 radius            0.9830496323087852
mlp               MIST           mass_smaller_3  radius            0.9983513710056814
                                 mass_smaller_14 radius            0.9983627542851781
random_forest     MIST           mass_smaller_3  radius            0.9999678953910232
                                 mass_smaller_14 radius            0.9999534137978472
xgboost           MIST           mass_smaller_3  radius            0.9996075937684589
                                 mass_smaller_14 radius            0.9995117695213523

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.239%
                                 mass_smaller_14 radius             0.15%
KNN               MIST           mass_smaller_3  radius            0.335%
                                 mass_smaller_14 radius            0.136%
linear_regression MIST           mass_smaller_3  radius             2.87%
                                 mass_smaller_14 radius            1.353%
mlp               MIST           mass_smaller_3  radius             0.92%
                                 mass_smaller_14 radius            0.441%
random_forest     MIST           mass_smaller_3  radius            0.103%
                                 mass_smaller_14 radius            0.071%
xgboost           MIST           mass_smaller_3  radius            0.358%
                                 mass_smaller_14 radius            0.228%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.152%
                                 mass_smaller_14 radius            0.089%
KNN               MIST           mass_smaller_3  radius            0.219%
                                 mass_smaller_14 radius             0.09%
linear_regression MIST           mass_smaller_3  radius            2.086%
                                 mass_smaller_14 radius            1.037%
mlp               MIST           mass_smaller_3  radius            0.672%
                                 mass_smaller_14 radius            0.346%
random_forest     MIST           mass_smaller_3  radius            0.063%
                                 mass_smaller_14 radius             0.04%
xgboost           MIST           mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.174%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.101%
                                 mass_smaller_14 radius            0.056%
KNN               MIST           mass_smaller_3  radius            0.136%
                                 mass_smaller_14 radius            0.058%
linear_regression MIST           mass_smaller_3  radius            1.579%
                                 mass_smaller_14 radius            0.829%
mlp               MIST           mass_smaller_3  radius            0.467%
                                 mass_smaller_14 radius            0.292%
random_forest     MIST           mass_smaller_3  radius            0.039%
                                 mass_smaller_14 radius            0.022%
xgboost           MIST           mass_smaller_3  radius            0.214%
                                 mass_smaller_14 radius            0.136%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9999125211077539
                                 mass_smaller_14 radius            0.9998940164221873
KNN               MIST           mass_smaller_3  radius             0.999830888291084
                                 mass_smaller_14 radius            0.9999135578590763
linear_regression MIST           mass_smaller_3  radius            0.9879836947112961
                                 mass_smaller_14 radius            0.9914885941715924
mlp               MIST           mass_smaller_3  radius            0.9992197462781777
                                 mass_smaller_14 radius            0.9991810430555029
random_forest     MIST           mass_smaller_3  radius            0.9999840579307431
                                 mass_smaller_14 radius            0.9999767231025315
xgboost           MIST           mass_smaller_3  radius            0.9998037782605148
                                 mass_smaller_14 radius            0.9997558778235092

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             4.663%
                                 mass_smaller_14 radius             7.812%
KNN               MIST           mass_smaller_3  radius             5.368%
                                 mass_smaller_14 radius             1.439%
linear_regression MIST           mass_smaller_3  radius            12.801%
                                 mass_smaller_14 radius             5.381%
mlp               MIST           mass_smaller_3  radius             3.953%
                                 mass_smaller_14 radius             4.054%
random_forest     MIST           mass_smaller_3  radius             2.464%
                                 mass_smaller_14 radius             3.502%
xgboost           MIST           mass_smaller_3  radius             6.229%
                                 mass_smaller_14 radius             1.596%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius              75 : 0.199% / 90 : 0.324% / 95 : 0.448% / 99 : 0.89%
                                 mass_smaller_14 radius             75 : 0.112% / 90 : 0.197% / 95 : 0.278% / 99 : 0.584%
KNN               MIST           mass_smaller_3  radius             75 : 0.275% / 90 : 0.515% / 95 : 0.723% / 99 : 1.238%
                                 mass_smaller_14 radius             75 : 0.113% / 90 : 0.205% / 95 : 0.285% / 99 : 0.514%
linear_regression MIST           mass_smaller_3  radius            75 : 2.801% / 90 : 4.245% / 95 : 5.738% / 99 : 10.075%
                                 mass_smaller_14 radius             75 : 1.559% / 90 : 2.251% / 95 : 2.664% / 99 : 3.814%
mlp               MIST           mass_smaller_3  radius               75 : 0.963% / 90 : 1.592% / 95 : 1.971% / 99 : 2.7%
                                 mass_smaller_14 radius             75 : 0.488% / 90 : 0.697% / 95 : 0.836% / 99 : 1.194%
random_forest     MIST           mass_smaller_3  radius             75 : 0.081% / 90 : 0.145% / 95 : 0.202% / 99 : 0.373%
                                 mass_smaller_14 radius             75 : 0.047% / 90 : 0.092% / 95 : 0.136% / 99 : 0.278%
xgboost           MIST           mass_smaller_3  radius             75 : 0.382% / 90 : 0.581% / 95 : 0.732% / 99 : 1.059%
                                 mass_smaller_14 radius             75 : 0.243% / 90 : 0.373% / 95 : 0.467% / 99 : 0.669%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
KNN               MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
linear_regression MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
mlp               MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
random_forest     MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
xgboost           MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9995465768676972
                                 mass_smaller_14 radius            0.9995039197290129
KNN               MIST           mass_smaller_3  radius            0.9998807428184813
                                 mass_smaller_14 radius            0.9998943160073213
linear_regression MIST           mass_smaller_3  radius            0.9833773452801731
                                 mass_smaller_14 radius            0.9806856109752665
mlp               MIST           mass_smaller_3  radius            0.9978060724763279
                                 mass_smaller_14 radius             0.998723350903017
random_forest     MIST           mass_smaller_3  radius            0.9999301508060892
                                 mass_smaller_14 radius            0.9999185082513201
xgboost           MIST           mass_smaller_3  radius            0.9995508512748904
                                 mass_smaller_14 radius            0.9994208286577492

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.437%
                                 mass_smaller_14 radius            0.373%
KNN               MIST           mass_smaller_3  radius            0.224%
                                 mass_smaller_14 radius            0.172%
linear_regression MIST           mass_smaller_3  radius            2.771%
                                 mass_smaller_14 radius            2.381%
mlp               MIST           mass_smaller_3  radius            1.108%
                                 mass_smaller_14 radius            0.599%
random_forest     MIST           mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.153%
xgboost           MIST           mass_smaller_3  radius            0.435%
                                 mass_smaller_14 radius            0.404%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.322%
                                 mass_smaller_14 radius            0.264%
KNN               MIST           mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.131%
linear_regression MIST           mass_smaller_3  radius            2.218%
                                 mass_smaller_14 radius            1.855%
mlp               MIST           mass_smaller_3  radius            0.799%
                                 mass_smaller_14 radius            0.473%
random_forest     MIST           mass_smaller_3  radius             0.12%
                                 mass_smaller_14 radius            0.105%
xgboost           MIST           mass_smaller_3  radius            0.333%
                                 mass_smaller_14 radius            0.314%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.263%
                                 mass_smaller_14 radius            0.217%
KNN               MIST           mass_smaller_3  radius            0.137%
                                 mass_smaller_14 radius            0.103%
linear_regression MIST           mass_smaller_3  radius            1.872%
                                 mass_smaller_14 radius            1.509%
mlp               MIST           mass_smaller_3  radius            0.527%
                                 mass_smaller_14 radius            0.389%
random_forest     MIST           mass_smaller_3  radius            0.083%
                                 mass_smaller_14 radius            0.072%
xgboost           MIST           mass_smaller_3  radius            0.266%
                                 mass_smaller_14 radius            0.255%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9997733155946078
                                 mass_smaller_14 radius            0.9997540306645297
KNN               MIST           mass_smaller_3  radius            0.9999404528865401
                                 mass_smaller_14 radius            0.9999471831409968
linear_regression MIST           mass_smaller_3  radius             0.993268227885979
                                 mass_smaller_14 radius            0.9909797904600514
mlp               MIST           mass_smaller_3  radius            0.9989117384154471
                                 mass_smaller_14 radius            0.9993643661222952
random_forest     MIST           mass_smaller_3  radius            0.9999650748236046
                                 mass_smaller_14 radius            0.9999605620655518
xgboost           MIST           mass_smaller_3  radius            0.9997754108047239
                                 mass_smaller_14 radius            0.9997106655945553

                                                                   MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            5.347%
                                 mass_smaller_14 radius             15.1%
KNN               MIST           mass_smaller_3  radius            3.109%
                                 mass_smaller_14 radius            2.265%
linear_regression MIST           mass_smaller_3  radius            7.833%
                                 mass_smaller_14 radius            8.961%
mlp               MIST           mass_smaller_3  radius            4.322%
                                 mass_smaller_14 radius             4.45%
random_forest     MIST           mass_smaller_3  radius            2.008%
                                 mass_smaller_14 radius            2.388%
xgboost           MIST           mass_smaller_3  radius            2.523%
                                 mass_smaller_14 radius            2.615%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.491% / 90 : 0.627% / 95 : 0.747% / 99 : 1.318%
                                 mass_smaller_14 radius            75 : 0.354% / 90 : 0.499% / 95 : 0.622% / 99 : 1.155%
KNN               MIST           mass_smaller_3  radius             75 : 0.236% / 90 : 0.368% / 95 : 0.449% / 99 : 0.63%
                                 mass_smaller_14 radius            75 : 0.178% / 90 : 0.285% / 95 : 0.354% / 99 : 0.494%
linear_regression MIST           mass_smaller_3  radius            75 : 3.379% / 90 : 4.724% / 95 : 5.395% / 99 : 6.276%
                                 mass_smaller_14 radius            75 : 2.614% / 90 : 3.907% / 95 : 4.838% / 99 : 6.671%
mlp               MIST           mass_smaller_3  radius             75 : 1.086% / 90 : 2.065% / 95 : 2.465% / 99 : 3.16%
                                 mass_smaller_14 radius            75 : 0.684% / 90 : 0.991% / 95 : 1.184% / 99 : 1.535%
random_forest     MIST           mass_smaller_3  radius            75 : 0.164% / 90 : 0.272% / 95 : 0.354% / 99 : 0.554%
                                 mass_smaller_14 radius            75 : 0.142% / 90 : 0.239% / 95 : 0.315% / 99 : 0.514%
xgboost           MIST           mass_smaller_3  radius             75 : 0.463% / 90 : 0.706% / 95 : 0.879% / 99 : 1.28%
                                 mass_smaller_14 radius             75 : 0.448% / 90 : 0.66% / 95 : 0.808% / 99 : 1.134%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
KNN               MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
linear_regression MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
mlp               MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
random_forest     MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
xgboost           MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9992381885703833
                                 mass_smaller_14 radius            0.9993395139862439
KNN               MIST           mass_smaller_3  radius            0.9994853264493573
                                 mass_smaller_14 radius            0.9997229263417253
linear_regression MIST           mass_smaller_3  radius            0.9740128136920825
                                 mass_smaller_14 radius            0.9746821269484942
mlp               MIST           mass_smaller_3  radius            0.9952899598276022
                                 mass_smaller_14 radius            0.9970644512745905
random_forest     MIST           mass_smaller_3  radius            0.9996570039158864
                                 mass_smaller_14 radius             0.999774074221781
xgboost           MIST           mass_smaller_3  radius            0.9991584798800517
                                 mass_smaller_14 radius            0.9991636868686137

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.478%
                                 mass_smaller_14 radius            0.456%
KNN               MIST           mass_smaller_3  radius            0.393%
                                 mass_smaller_14 radius            0.295%
linear_regression MIST           mass_smaller_3  radius            2.794%
                                 mass_smaller_14 radius            2.821%
mlp               MIST           mass_smaller_3  radius            1.188%
                                 mass_smaller_14 radius            1.158%
random_forest     MIST           mass_smaller_3  radius            0.321%
                                 mass_smaller_14 radius            0.268%
xgboost           MIST           mass_smaller_3  radius            0.503%
                                 mass_smaller_14 radius            0.514%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             0.23%
                                 mass_smaller_14 radius            0.243%
KNN               MIST           mass_smaller_3  radius            0.188%
                                 mass_smaller_14 radius             0.15%
linear_regression MIST           mass_smaller_3  radius            2.203%
                                 mass_smaller_14 radius            2.185%
mlp               MIST           mass_smaller_3  radius            0.821%
                                 mass_smaller_14 radius            0.789%
random_forest     MIST           mass_smaller_3  radius            0.138%
                                 mass_smaller_14 radius            0.134%
xgboost           MIST           mass_smaller_3  radius              0.3%
                                 mass_smaller_14 radius             0.34%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.106%
                                 mass_smaller_14 radius             0.12%
KNN               MIST           mass_smaller_3  radius            0.093%
                                 mass_smaller_14 radius            0.082%
linear_regression MIST           mass_smaller_3  radius            1.885%
                                 mass_smaller_14 radius            1.865%
mlp               MIST           mass_smaller_3  radius             0.61%
                                 mass_smaller_14 radius            0.609%
random_forest     MIST           mass_smaller_3  radius            0.057%
                                 mass_smaller_14 radius            0.064%
xgboost           MIST           mass_smaller_3  radius            0.193%
                                 mass_smaller_14 radius            0.245%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9996192777071335
                                 mass_smaller_14 radius            0.9996699530747309
KNN               MIST           mass_smaller_3  radius            0.9997430849980539
                                 mass_smaller_14 radius            0.9998615008366036
linear_regression MIST           mass_smaller_3  radius            0.9886235406128182
                                 mass_smaller_14 radius            0.9873693027486672
mlp               MIST           mass_smaller_3  radius            0.9976629398298685
                                 mass_smaller_14 radius            0.9985438860810399
random_forest     MIST           mass_smaller_3  radius            0.9998285901743722
                                 mass_smaller_14 radius            0.9998870342476956
xgboost           MIST           mass_smaller_3  radius             0.999579231894782
                                 mass_smaller_14 radius            0.9995818580147785

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             6.307%
                                 mass_smaller_14 radius             5.599%
KNN               MIST           mass_smaller_3  radius             8.357%
                                 mass_smaller_14 radius             6.904%
linear_regression MIST           mass_smaller_3  radius            15.259%
                                 mass_smaller_14 radius            16.119%
mlp               MIST           mass_smaller_3  radius            14.485%
                                 mass_smaller_14 radius            15.375%
random_forest     MIST           mass_smaller_3  radius             5.464%
                                 mass_smaller_14 radius             4.315%
xgboost           MIST           mass_smaller_3  radius             7.085%
                                 mass_smaller_14 radius             7.573%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.264% / 90 : 0.512% / 95 : 0.827% / 99 : 2.382%
                                 mass_smaller_14 radius             75 : 0.29% / 90 : 0.571% / 95 : 0.873% / 99 : 2.009%
KNN               MIST           mass_smaller_3  radius             75 : 0.212% / 90 : 0.405% / 95 : 0.626% / 99 : 1.88%
                                 mass_smaller_14 radius             75 : 0.185% / 90 : 0.328% / 95 : 0.46% / 99 : 1.275%
linear_regression MIST           mass_smaller_3  radius             75 : 3.38% / 90 : 4.458% / 95 : 5.013% / 99 : 6.569%
                                 mass_smaller_14 radius            75 : 3.015% / 90 : 4.239% / 95 : 5.318% / 99 : 8.521%
mlp               MIST           mass_smaller_3  radius             75 : 1.14% / 90 : 1.655% / 95 : 2.022% / 99 : 3.697%
                                 mass_smaller_14 radius            75 : 1.049% / 90 : 1.573% / 95 : 1.949% / 99 : 3.761%
random_forest     MIST           mass_smaller_3  radius              75 : 0.14% / 90 : 0.298% / 95 : 0.511% / 99 : 1.54%
                                 mass_smaller_14 radius            75 : 0.158% / 90 : 0.318% / 95 : 0.472% / 99 : 1.088%
xgboost           MIST           mass_smaller_3  radius              75 : 0.36% / 90 : 0.61% / 95 : 0.891% / 99 : 2.138%
                                 mass_smaller_14 radius            75 : 0.444% / 90 : 0.691% / 95 : 0.915% / 99 : 1.895%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Linear regression : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : better results than Base on every metric but less than mass_smaller_3 and mass_smaller_14

Decision tree : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : better or similar results than Base on every metric except MAX_ER, less than mass_smaller_3 and mass_smaller_14

KNN : 
- mass_smaller_3 : similar results than Base except for MAX_ER which is better
- mass_smaller_14 : better/similar results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric but less than mass_smaller_14

Random forest : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric, less than mass_smaller_3 except for MAX_ER
- mass_smaller_30 : better results than Base on every metric, less than mass_smaller_3 and similar to mass_smaller_14 except MAX_ER which is worse

XGBoost : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric, less than mass_smaller_3
- mass_smaller_30 : better results than Base on every metric, less than mass_smaller_3 and mass_smaller_14

MLP : 
- mass_smaller_3 : way better results than Base on every metric
- mass_smaller_14 : way better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : way better results than Base on every metric but less than mass_smaller_3 and mass_smaller_14

#### Conclusions on radius

mass_smaller_3 almost always gives better results than Base.

mass_smaller_14 almost always gives better results than Base but most of the time it improves less than mass_smaller_3.

mass_smaller_30 almost always gives better results than Base but most of the time it improves less than mass_smaller_3 and mass_smaller_14

#### Best models for the radius parameter

The three best performing models in order for the radius parameter are Random forest, KNN and Decision tree.

### Conclusion for every filtering

In [10]:
compare_metrics(path, value_rounding=3, relative_values=False,
                model_names=["random_forest", "KNN", "decision_tree"],
                output_parameters=["mass", "radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
KNN           MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
decision_tree MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.998  1.251
                                             radius            1.000  0.006
                             mass_smaller_14 mass              1.000  0.033
                                             radius            1.000  0.005
KNN           MIST           Base            mass              0.990  2.726
                                             radius            1.000  0.007
                             mass_smaller_14 mass              0.999  0.083
                                             radius            1.000  0.006
decision_tree MIST           Base            mass              0.995  1.837
                                             radius            1.000  0.011
                             mass_smaller_14 mass              1.000  0.051
                                             radius            1.000  0.009

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.145  0.004
                                             radius            0.003  0.001
                             mass_smaller_14 mass              0.011  0.003
                                             radius            0.002  0.001
KNN           MIST           Base            mass              0.328  0.008
                                             radius            0.004  0.003
                             mass_smaller_14 mass              0.029  0.007
                                             radius            0.004  0.003
decision_tree MIST           Base            mass              0.200  0.003
                                             radius            0.006  0.003
                             mass_smaller_14 mass              0.016  0.003
                                             radius            0.005  0.003

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.999   95.973
                                             radius            1.000    0.358
                             mass_smaller_14 mass              1.000    2.328
                                             radius            1.000    0.143
KNN           MIST           Base            mass              0.995  144.214
                                             radius            1.000    0.307
                             mass_smaller_14 mass              1.000    2.604
                                             radius            1.000    0.206
decision_tree MIST           Base            mass              0.998  151.658
                                             radius            1.000    0.478
                             mass_smaller_14 mass              1.000    5.116
                                             radius            1.000    0.420

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01557 / 90 : 0.07872 / 95 : 0.29091 / 99 : 3.19321
                                             radius             75 : 0.00311 / 90 : 0.00627 / 95 : 0.00939 / 99 : 0.02061
                             mass_smaller_14 mass                75 : 0.00986 / 90 : 0.02522 / 95 : 0.0469 / 99 : 0.13865
                                             radius             75 : 0.00291 / 90 : 0.00575 / 95 : 0.00837 / 99 : 0.01677
KNN           MIST           Base            mass               75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                             radius             75 : 0.00513 / 90 : 0.00921 / 95 : 0.01275 / 99 : 0.02703
                             mass_smaller_14 mass                75 : 0.02377 / 90 : 0.07441 / 95 : 0.12857 / 99 : 0.3237
                                             radius             75 : 0.00487 / 90 : 0.00851 / 95 : 0.01134 / 99 : 0.02103
decision_tree MIST           Base            mass               75 : 0.01985 / 90 : 0.10454 / 95 : 0.35331 / 99 : 4.56376
                                             radius               75 : 0.00721 / 90 : 0.013 / 95 : 0.01829 / 99 : 0.04024
                             mass_smaller_14 mass               75 : 0.01198 / 90 : 0.03828 / 95 : 0.07324 / 99 : 0.22077
                                             radius              75 : 0.00676 / 90 : 0.01226 / 95 : 0.01617 / 99 : 0.0346

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 0.0

                                                                  value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
KNN           MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
decision_tree MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.997  1.350
                                             radius            1.000  0.004
                             mass_smaller_14 mass              1.000  0.029
                                             radius            1.000  0.003
KNN           MIST           Base            mass              0.984  3.292
                                             radius            1.000  0.007
                             mass_smaller_14 mass              0.999  0.095
                                             radius            1.000  0.006
decision_tree MIST           Base            mass              0.994  2.098
                                             radius            1.000  0.008
                             mass_smaller_14 mass              1.000  0.051
                                             radius            1.000  0.006

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.168  0.004
                                             radius            0.002  0.001
                             mass_smaller_14 mass              0.009  0.002
                                             radius            0.002  0.001
KNN           MIST           Base            mass              0.432  0.010
                                             radius            0.004  0.003
                             mass_smaller_14 mass              0.031  0.007
                                             radius            0.004  0.002
decision_tree MIST           Base            mass              0.270  0.006
                                             radius            0.005  0.003
                             mass_smaller_14 mass              0.017  0.004
                                             radius            0.004  0.002

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.999   83.538
                                             radius            1.000    0.358
                             mass_smaller_14 mass              1.000    2.328
                                             radius            1.000    0.143
KNN           MIST           Base            mass              0.992  126.674
                                             radius            1.000    0.154
                             mass_smaller_14 mass              1.000    2.604
                                             radius            1.000    0.059
decision_tree MIST           Base            mass              0.997  131.775
                                             radius            1.000    0.478
                             mass_smaller_14 mass              1.000    5.116
                                             radius            1.000    0.319

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01628 / 90 : 0.10798 / 95 : 0.41573 / 99 : 3.60316
                                             radius               75 : 0.00232 / 90 : 0.00485 / 95 : 0.0075 / 99 : 0.0165
                             mass_smaller_14 mass               75 : 0.00713 / 90 : 0.01962 / 95 : 0.03484 / 99 : 0.10114
                                             radius             75 : 0.00193 / 90 : 0.00375 / 95 : 0.00556 / 99 : 0.01133
KNN           MIST           Base            mass               75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                             radius              75 : 0.00518 / 90 : 0.00955 / 95 : 0.01355 / 99 : 0.0264
                             mass_smaller_14 mass                75 : 0.02433 / 90 : 0.0695 / 95 : 0.12413 / 99 : 0.38274
                                             radius             75 : 0.00459 / 90 : 0.00838 / 95 : 0.01164 / 99 : 0.02096
decision_tree MIST           Base            mass               75 : 0.03086 / 90 : 0.18595 / 95 : 0.67453 / 99 : 5.94846
                                             radius             75 : 0.00534 / 90 : 0.01028 / 95 : 0.01519 / 99 : 0.03251
                             mass_smaller_14 mass               75 : 0.01359 / 90 : 0.04207 / 95 : 0.07392 / 99 : 0.19384
                                             radius             75 : 0.00455 / 90 : 0.00804 / 95 : 0.01134 / 99 : 0.02382

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 2.0

                                                                   value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871
KNN           MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871
decision_tree MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              1.000  0.470
                                             radius            1.000  0.004
                             mass_smaller_14 mass              1.000  0.017
                                             radius            1.000  0.004
KNN           MIST           Base            mass              0.999  0.737
                                             radius            1.000  0.005
                             mass_smaller_14 mass              1.000  0.049
                                             radius            1.000  0.005
decision_tree MIST           Base            mass              0.999  0.795
                                             radius            1.000  0.010
                             mass_smaller_14 mass              1.000  0.025
                                             radius            1.000  0.010

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.059  0.004
                                             radius            0.003  0.002
                             mass_smaller_14 mass              0.008  0.004
                                             radius            0.003  0.002
KNN           MIST           Base            mass              0.095  0.004
                                             radius            0.003  0.003
                             mass_smaller_14 mass              0.020  0.005
                                             radius            0.004  0.003
decision_tree MIST           Base            mass              0.060  0.000
                                             radius            0.007  0.005
                             mass_smaller_14 mass              0.008  0.000
                                             radius            0.007  0.006

                                                               CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               1.0   22.981
                                             radius             1.0    0.091
                             mass_smaller_14 mass               1.0    0.483
                                             radius             1.0    0.066
KNN           MIST           Base            mass               1.0   37.487
                                             radius             1.0    0.077
                             mass_smaller_14 mass               1.0    0.926
                                             radius             1.0    0.063
decision_tree MIST           Base            mass               1.0  105.861
                                             radius             1.0    0.184
                             mass_smaller_14 mass               1.0    1.411
                                             radius             1.0    0.420

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                75 : 0.01059 / 90 : 0.02554 / 95 : 0.07295 / 99 : 1.3585
                                             radius             75 : 0.00359 / 90 : 0.00617 / 95 : 0.00828 / 99 : 0.01406
                             mass_smaller_14 mass               75 : 0.01007 / 90 : 0.01901 / 95 : 0.02804 / 99 : 0.06834
                                             radius             75 : 0.00394 / 90 : 0.00663 / 95 : 0.00876 / 99 : 0.01428
KNN           MIST           Base            mass                75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                             radius             75 : 0.00469 / 90 : 0.00772 / 95 : 0.00978 / 99 : 0.01453
                             mass_smaller_14 mass               75 : 0.01612 / 90 : 0.05506 / 95 : 0.10024 / 99 : 0.20841
                                             radius             75 : 0.00496 / 90 : 0.00793 / 95 : 0.00984 / 99 : 0.01372
decision_tree MIST           Base            mass               75 : 0.00549 / 90 : 0.02551 / 95 : 0.04546 / 99 : 0.75464
                                             radius              75 : 0.00908 / 90 : 0.01345 / 95 : 0.01659 / 99 : 0.0315
                             mass_smaller_14 mass                75 : 0.0057 / 90 : 0.02333 / 95 : 0.03482 / 99 : 0.08753
                                             radius             75 : 0.00984 / 90 : 0.01386 / 95 : 0.01729 / 99 : 0.03211

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 3.0

                                                                   value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064
KNN           MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064
decision_tree MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.995  1.648
                                             radius            1.000  0.009
                             mass_smaller_14 mass              1.000  0.053
                                             radius            1.000  0.008
KNN           MIST           Base            mass              0.986  2.735
                                             radius            1.000  0.010
                             mass_smaller_14 mass              0.999  0.084
                                             radius            1.000  0.009
decision_tree MIST           Base            mass              0.992  2.077
                                             radius            0.999  0.016
                             mass_smaller_14 mass              0.999  0.074
                                             radius            0.999  0.014

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.201  0.007
                                             radius            0.004  0.002
                             mass_smaller_14 mass              0.023  0.006
                                             radius            0.004  0.002
KNN           MIST           Base            mass              0.364  0.010
                                             radius            0.005  0.003
                             mass_smaller_14 mass              0.037  0.008
                                             radius            0.004  0.002
decision_tree MIST           Base            mass              0.200  0.004
                                             radius            0.008  0.004
                             mass_smaller_14 mass              0.027  0.003
                                             radius            0.007  0.004

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.998   95.973
                                             radius            1.000    0.301
                             mass_smaller_14 mass              1.000    1.293
                                             radius            1.000    0.129
KNN           MIST           Base            mass              0.993  144.214
                                             radius            1.000    0.307
                             mass_smaller_14 mass              1.000    1.645
                                             radius            1.000    0.206
decision_tree MIST           Base            mass              0.996  151.658
                                             radius            1.000    0.385
                             mass_smaller_14 mass              1.000    2.404
                                             radius            1.000    0.167

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                  75 : 0.02891 / 90 : 0.1076 / 95 : 0.29511 / 99 : 4.683
                                             radius             75 : 0.00501 / 90 : 0.01036 / 95 : 0.01595 / 99 : 0.04157
                             mass_smaller_14 mass                75 : 0.02188 / 90 : 0.0643 / 95 : 0.10864 / 99 : 0.24241
                                             radius              75 : 0.00471 / 90 : 0.0095 / 95 : 0.01409 / 99 : 0.03252
KNN           MIST           Base            mass               75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                             radius             75 : 0.00589 / 90 : 0.01098 / 95 : 0.01632 / 99 : 0.04576
                             mass_smaller_14 mass               75 : 0.03551 / 90 : 0.10934 / 95 : 0.17097 / 99 : 0.34974
                                             radius             75 : 0.00553 / 90 : 0.00981 / 95 : 0.01374 / 99 : 0.03808
decision_tree MIST           Base            mass               75 : 0.02357 / 90 : 0.11188 / 95 : 0.26917 / 99 : 4.64103
                                             radius             75 : 0.00936 / 90 : 0.01845 / 95 : 0.02898 / 99 : 0.06739
                             mass_smaller_14 mass                75 : 0.01657 / 90 : 0.0729 / 95 : 0.14969 / 99 : 0.34879
                                             radius             75 : 0.00866 / 90 : 0.01705 / 95 : 0.02607 / 99 : 0.06002

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

It seems that using the filtering mass_smaller_14 gives better results for radius and gives less high errors for the mass.

This filtering might be the best choice as it is also the range of values for PARSEC which would make comparing models between the two easier.