# Results comparison for MIST filtering of model A partial

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the MIST dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_A_partial/default_models"

In [3]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"], # output_parameters=["radius"],
                model_names=["random_forest"],
                physical_models=["MIST"],
                data_filters = ["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                             mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9978063351241271
                             mass_smaller_3  mass              0.9992738264822424
                             mass_smaller_14 mass              0.9999006268975099
                             mass_smaller_30 mass              0.9995874506793025

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.419%  0.049%
                             mass_smaller_3  mass              0.672%  0.207%
                             mass_smaller_14 mass              0.235%  0.082%
                             mass_smaller_30 mass              0.415%  0.069%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass               0.07%
                             mass_smaller_14 mass              0.024%
                             mass_smaller_30 mass              0.012%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9989037560824912
                             mass_smaller_3  mass               0.999636894028306
                             mass_smaller_14 mass              0.9999503530371973
                             mass_smaller_30 mass              0.9997937276626583

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              32.158%
                             mass_smaller_3  mass              51.551%
                             mass_smaller_14 mass              16.749%
                             mass_smaller_30 mass              25.504%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                             mass_smaller_3  mass              75 : 0.192% / 90 : 0.427% / 95 : 0.681% / 99 : 2.322%
                             mass_smaller_14 mass              75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
                             mass_smaller_30 mass               75 : 0.037% / 90 : 0.11% / 95 : 0.231% / 99 : 0.933%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 0.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                             mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                             mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                             mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9973661987481759
                             mass_smaller_3  mass              0.9999474983734866
                             mass_smaller_14 mass              0.9999235468255409
                             mass_smaller_30 mass               0.999521993790828

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.452%  0.056%
                             mass_smaller_3  mass              0.188%  0.094%
                             mass_smaller_14 mass              0.207%  0.063%
                             mass_smaller_30 mass              0.458%  0.077%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass              0.045%
                             mass_smaller_14 mass              0.018%
                             mass_smaller_30 mass              0.009%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9986840004415223
                             mass_smaller_3  mass              0.9999737782832668
                             mass_smaller_14 mass              0.9999617835917853
                             mass_smaller_30 mass              0.9997609878413475

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              27.991%
                             mass_smaller_3  mass               8.032%
                             mass_smaller_14 mass              16.749%
                             mass_smaller_30 mass              25.504%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              75 : 0.005% / 90 : 0.036% / 95 : 0.139% / 99 : 1.207%
                             mass_smaller_3  mass              75 : 0.107% / 90 : 0.219% / 95 : 0.331% / 99 : 0.749%
                             mass_smaller_14 mass              75 : 0.051% / 90 : 0.141% / 95 : 0.251% / 99 : 0.728%
                             mass_smaller_30 mass              75 : 0.032% / 90 : 0.112% / 95 : 0.253% / 99 : 1.248%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 2.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                             mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                             mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                             mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9997496322236138
                             mass_smaller_3  mass              0.9996443438393721
                             mass_smaller_14 mass              0.9999737930935538
                             mass_smaller_30 mass              0.9999690893306589

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.166%  0.021%
                             mass_smaller_3  mass              0.503%  0.298%
                             mass_smaller_14 mass              0.126%  0.063%
                             mass_smaller_30 mass              0.114%  0.029%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.001%
                             mass_smaller_3  mass              0.188%
                             mass_smaller_14 mass              0.033%
                             mass_smaller_30 mass              0.013%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9998754804643019
                             mass_smaller_3  mass              0.9998265900407789
                             mass_smaller_14 mass               0.999987052162877
                             mass_smaller_30 mass               0.999984609078679

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               8.119%
                             mass_smaller_3  mass               9.114%
                             mass_smaller_14 mass               3.642%
                             mass_smaller_30 mass              13.669%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.004% / 90 : 0.009% / 95 : 0.026% / 99 : 0.48%
                             mass_smaller_3  mass              75 : 0.393% / 90 : 0.672% / 95 : 0.904% / 99 : 1.705%
                             mass_smaller_14 mass              75 : 0.076% / 90 : 0.143% / 95 : 0.211% / 99 : 0.515%
                             mass_smaller_30 mass              75 : 0.032% / 90 : 0.061% / 95 : 0.093% / 99 : 0.235%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

Results for the phase category with a value of 3.0

                                                                                           value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                0.5484495344916944 - 288.814589557117
                             mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                             mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                             mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494

                                                                              RVE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9949439900825313
                             mass_smaller_3  mass              0.9954521777596107
                             mass_smaller_14 mass              0.9997284223560081
                             mass_smaller_30 mass              0.9992635983495934

                                                                 RMSE     MAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.572%   0.07%
                             mass_smaller_3  mass              1.718%  0.602%
                             mass_smaller_14 mass              0.395%  0.173%
                             mass_smaller_30 mass              0.548%  0.103%

                                                                MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.002%
                             mass_smaller_3  mass              0.151%
                             mass_smaller_14 mass              0.044%
                             mass_smaller_30 mass               0.02%

                                                                             CORR  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.9975811556691733
                             mass_smaller_3  mass              0.9977358261257694
                             mass_smaller_14 mass              0.9998659386279564
                             mass_smaller_30 mass              0.9996323346107105

                                                                MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              33.293%
                             mass_smaller_3  mass              60.907%
                             mass_smaller_14 mass               9.617%
                             mass_smaller_30 mass              25.403%

                                                                                                         Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01% / 90 : 0.037% / 95 : 0.102% / 99 : 1.625%
                             mass_smaller_3  mass              75 : 0.457% / 90 : 1.258% / 95 : 2.669% / 99 : 8.475%
                             mass_smaller_14 mass              75 : 0.163% / 90 : 0.478% / 95 : 0.808% / 99 : 1.802%
                             mass_smaller_30 mass               75 : 0.073% / 90 : 0.22% / 95 : 0.382% / 99 : 0.985%

                                                                             time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               343.6629173755646
                             mass_smaller_3  mass               142.9930453300476
                             mass_smaller_14 mass              248.72876453399658
                             mass_smaller_30 mass              327.88787055015564

In [4]:
compare_metrics(path, value_rounding=3,
                output_parameters=["mass", "radius"], # output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -298.445  0.995
                                        radius                 -4.127  1.000
KNN               MIST           Base   mass                 -298.445  0.990
                                        radius                 -4.127  1.000
linear_regression MIST           Base   mass                 -298.445  0.304
                                        radius                 -4.127  0.985
mlp               MIST           Base   mass                 -298.445  0.968
                                        radius                 -4.127  0.989
random_forest     MIST           Base   mass                 -298.445  0.998
                                        radius                 -4.127  1.000
xgboost           MIST           Base   mass                 -298.445  0.994
                                        radius                 -4.127  1.000

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               1.854   0.200
                                        radius             0.011   0.006
KNN               MIST           Base   mass               2.726   0.328
                                        radius             0.007   0.004
linear_regression MIST           Base   mass              22.280  11.345
                                        radius             0.089   0.065
mlp               MIST           Base   mass               4.750   1.280
                                        radius             0.077   0.056
random_forest     MIST           Base   mass               1.251   0.145
                                        radius             0.006   0.003
xgboost           MIST           Base   mass               2.048   0.531
                                        radius             0.015   0.011

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.003  0.998
                                        radius            0.003  1.000
KNN               MIST           Base   mass              0.008  0.995
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              8.154  0.552
                                        radius            0.046  0.993
mlp               MIST           Base   mass              0.277  0.984
                                        radius            0.042  0.995
random_forest     MIST           Base   mass              0.004  0.999
                                        radius            0.001  1.000
xgboost           MIST           Base   mass              0.099  0.997
                                        radius            0.008  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              151.658
                                        radius              0.488
KNN               MIST           Base   mass              144.214
                                        radius              0.307
linear_regression MIST           Base   mass              257.508
                                        radius              0.525
mlp               MIST           Base   mass              179.182
                                        radius              0.692
random_forest     MIST           Base   mass               95.148
                                        radius              0.358
xgboost           MIST           Base   mass               72.954
                                        radius              0.490

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.01985 / 90 : 0.10435 / 95 : 0.35217 / 99 : 4.54997
                                        radius                 75 : 0.00723 / 90 : 0.01301 / 95 : 0.01833 / 99 : 0.04032
KNN               MIST           Base   mass                   75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                        radius                 75 : 0.00513 / 90 : 0.00921 / 95 : 0.01275 / 99 : 0.02703
linear_regression MIST           Base   mass               75 : 13.88885 / 90 : 17.56944 / 95 : 20.95889 / 99 : 105.1692
                                        radius                 75 : 0.08959 / 90 : 0.13937 / 95 : 0.17556 / 99 : 0.30046
mlp               MIST           Base   mass                  75 : 0.57742 / 90 : 2.19642 / 95 : 5.39114 / 99 : 21.87825
                                        radius                 75 : 0.07619 / 90 : 0.12016 / 95 : 0.15389 / 99 : 0.24989
random_forest     MIST           Base   mass                     75 : 0.0156 / 90 : 0.0791 / 95 : 0.29069 / 99 : 3.22241
                                        radius                 75 : 0.00311 / 90 : 0.00627 / 95 : 0.00938 / 99 : 0.02069
xgboost           MIST           Base   mass                    75 : 0.27216 / 90 : 0.98406 / 95 : 2.1671 / 99 : 8.48746
                                        radius                  75 : 0.0146 / 90 : 0.02253 / 95 : 0.02856 / 99 : 0.04454

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 0.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -298.445  0.994
                                        radius                 -4.080  1.000
KNN               MIST           Base   mass                 -298.445  0.984
                                        radius                 -4.080  1.000
linear_regression MIST           Base   mass                 -298.445  0.273
                                        radius                 -4.080  0.978
mlp               MIST           Base   mass                 -298.445  0.965
                                        radius                 -4.080  0.981
random_forest     MIST           Base   mass                 -298.445  0.997
                                        radius                 -4.080  1.000
xgboost           MIST           Base   mass                 -298.445  0.991
                                        radius                 -4.080  0.999

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               2.111   0.270
                                        radius             0.008   0.005
KNN               MIST           Base   mass               3.292   0.432
                                        radius             0.007   0.004
linear_regression MIST           Base   mass              22.430  13.108
                                        radius             0.085   0.066
mlp               MIST           Base   mass               4.923   1.342
                                        radius             0.079   0.057
random_forest     MIST           Base   mass               1.352   0.168
                                        radius             0.004   0.002
xgboost           MIST           Base   mass               2.494   0.677
                                        radius             0.014   0.010

                                                           MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.006  0.997
                                        radius             0.003  1.000
KNN               MIST           Base   mass               0.010  0.992
                                        radius             0.003  1.000
linear_regression MIST           Base   mass              11.253  0.534
                                        radius             0.052  0.989
mlp               MIST           Base   mass               0.290  0.983
                                        radius             0.043  0.990
random_forest     MIST           Base   mass               0.004  0.999
                                        radius             0.001  1.000
xgboost           MIST           Base   mass               0.126  0.996
                                        radius             0.007  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              131.775
                                        radius              0.488
KNN               MIST           Base   mass              126.674
                                        radius              0.154
linear_regression MIST           Base   mass              257.508
                                        radius              0.458
mlp               MIST           Base   mass              127.141
                                        radius              0.692
random_forest     MIST           Base   mass               83.611
                                        radius              0.358
xgboost           MIST           Base   mass               72.954
                                        radius              0.136

                                                                                                               Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                    75 : 0.03086 / 90 : 0.18472 / 95 : 0.67029 / 99 : 5.91802
                                        radius                  75 : 0.00535 / 90 : 0.01031 / 95 : 0.01517 / 99 : 0.03231
KNN               MIST           Base   mass                    75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                        radius                   75 : 0.00518 / 90 : 0.00955 / 95 : 0.01355 / 99 : 0.0264
linear_regression MIST           Base   mass               75 : 15.42379 / 90 : 18.51741 / 95 : 20.73405 / 99 : 102.34282
                                        radius                    75 : 0.0962 / 90 : 0.1347 / 95 : 0.15728 / 99 : 0.25052
mlp               MIST           Base   mass                   75 : 0.64487 / 90 : 2.45842 / 95 : 5.63469 / 99 : 21.93746
                                        radius                  75 : 0.07677 / 90 : 0.12234 / 95 : 0.15977 / 99 : 0.26868
random_forest     MIST           Base   mass                     75 : 0.01627 / 90 : 0.10846 / 95 : 0.41678 / 99 : 3.6048
                                        radius                   75 : 0.00233 / 90 : 0.00485 / 95 : 0.0075 / 99 : 0.01647
xgboost           MIST           Base   mass                   75 : 0.38484 / 90 : 1.28956 / 95 : 2.69837 / 99 : 11.03449
                                        radius                  75 : 0.01364 / 90 : 0.02151 / 95 : 0.02755 / 99 : 0.04225

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 2.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  1.000
KNN               MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  1.000
linear_regression MIST           Base   mass                 -283.067  0.317
                                        radius                 -2.800  0.968
mlp               MIST           Base   mass                 -283.067  0.981
                                        radius                 -2.800  0.981
random_forest     MIST           Base   mass                 -283.067  1.000
                                        radius                 -2.800  1.000
xgboost           MIST           Base   mass                 -283.067  0.999
                                        radius                 -2.800  0.999

                                                            RMSE     MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               0.856   0.063
                                        radius             0.010   0.007
KNN               MIST           Base   mass               0.737   0.095
                                        radius             0.005   0.003
linear_regression MIST           Base   mass              24.543  10.236
                                        radius             0.088   0.058
mlp               MIST           Base   mass               4.103   1.093
                                        radius             0.068   0.050
random_forest     MIST           Base   mass               0.475   0.060
                                        radius             0.004   0.003
xgboost           MIST           Base   mass               0.996   0.293
                                        radius             0.014   0.011

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.000  1.000
                                        radius            0.005  1.000
KNN               MIST           Base   mass              0.004  1.000
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              5.268  0.596
                                        radius            0.034  0.984
mlp               MIST           Base   mass              0.263  0.991
                                        radius            0.039  0.991
random_forest     MIST           Base   mass              0.004  1.000
                                        radius            0.002  1.000
xgboost           MIST           Base   mass              0.071  0.999
                                        radius            0.009  1.000

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              115.074
                                        radius              0.262
KNN               MIST           Base   mass               37.487
                                        radius              0.077
linear_regression MIST           Base   mass              247.133
                                        radius              0.453
mlp               MIST           Base   mass               92.622
                                        radius              0.403
random_forest     MIST           Base   mass               21.389
                                        radius              0.101
xgboost           MIST           Base   mass               39.121
                                        radius              0.074

                                                                                                              Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                     75 : 0.0055 / 90 : 0.0255 / 95 : 0.04576 / 99 : 0.76556
                                        radius                 75 : 0.00907 / 90 : 0.01348 / 95 : 0.01669 / 99 : 0.03212
KNN               MIST           Base   mass                    75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                        radius                 75 : 0.00469 / 90 : 0.00772 / 95 : 0.00978 / 99 : 0.01453
linear_regression MIST           Base   mass               75 : 11.23711 / 90 : 14.43748 / 95 : 23.0162 / 99 : 137.76066
                                        radius                   75 : 0.0735 / 90 : 0.1413 / 95 : 0.19408 / 99 : 0.35002
mlp               MIST           Base   mass                  75 : 0.50511 / 90 : 1.67386 / 95 : 4.22263 / 99 : 20.09887
                                        radius                 75 : 0.06979 / 90 : 0.10692 / 95 : 0.13792 / 99 : 0.21054
random_forest     MIST           Base   mass                   75 : 0.01064 / 90 : 0.02559 / 95 : 0.07213 / 99 : 1.35752
                                        radius                 75 : 0.00359 / 90 : 0.00619 / 95 : 0.00829 / 99 : 0.01418
xgboost           MIST           Base   mass                     75 : 0.15627 / 90 : 0.548 / 95 : 1.32151 / 99 : 4.41441
                                        radius                 75 : 0.01514 / 90 : 0.02219 / 95 : 0.02704 / 99 : 0.03759

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

Results for the phase category with a value of 3.0

                                                          value range    RVE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                 -288.266  0.992
                                        radius                 -3.474  0.999
KNN               MIST           Base   mass                 -288.266  0.986
                                        radius                 -3.474  1.000
linear_regression MIST           Base   mass                 -288.266  0.388
                                        radius                 -3.474  0.970
mlp               MIST           Base   mass                 -288.266  0.952
                                        radius                 -3.474  0.980
random_forest     MIST           Base   mass                 -288.266  0.995
                                        radius                 -3.474  1.000
xgboost           MIST           Base   mass                 -288.266  0.994
                                        radius                 -3.474  0.999

                                                            RMSE    MAE  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               2.086  0.199
                                        radius             0.016  0.008
KNN               MIST           Base   mass               2.735  0.364
                                        radius             0.010  0.005
linear_regression MIST           Base   mass              18.164  7.961
                                        radius             0.100  0.070
mlp               MIST           Base   mass               5.083  1.368
                                        radius             0.082  0.060
random_forest     MIST           Base   mass               1.642  0.201
                                        radius             0.009  0.004
xgboost           MIST           Base   mass               1.730  0.451
                                        radius             0.019  0.013

                                                          MedAE   CORR  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              0.004  0.996
                                        radius            0.004  1.000
KNN               MIST           Base   mass              0.010  0.993
                                        radius            0.003  1.000
linear_regression MIST           Base   mass              4.599  0.650
                                        radius            0.046  0.985
mlp               MIST           Base   mass              0.264  0.976
                                        radius            0.046  0.990
random_forest     MIST           Base   mass              0.007  0.998
                                        radius            0.002  1.000
xgboost           MIST           Base   mass              0.094  0.997
                                        radius            0.009  0.999

                                                           MAX_ER  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass              151.658
                                        radius              0.351
KNN               MIST           Base   mass              144.214
                                        radius              0.307
linear_regression MIST           Base   mass              250.918
                                        radius              0.525
mlp               MIST           Base   mass              179.182
                                        radius              0.636
random_forest     MIST           Base   mass               95.148
                                        radius              0.292
xgboost           MIST           Base   mass               61.887
                                        radius              0.490

                                                                                                             Percentiles  \
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass                   75 : 0.0237 / 90 : 0.11118 / 95 : 0.26881 / 99 : 4.59332
                                        radius                75 : 0.00937 / 90 : 0.01848 / 95 : 0.02886 / 99 : 0.06747
KNN               MIST           Base   mass                  75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                        radius                75 : 0.00589 / 90 : 0.01098 / 95 : 0.01632 / 99 : 0.04576
linear_regression MIST           Base   mass               75 : 9.08941 / 90 : 13.95243 / 95 : 22.14803 / 99 : 82.27943
                                        radius                75 : 0.08613 / 90 : 0.16865 / 95 : 0.22602 / 99 : 0.32909
mlp               MIST           Base   mass                  75 : 0.53231 / 90 : 2.20664 / 95 : 6.2769 / 99 : 24.01312
                                        radius                75 : 0.08503 / 90 : 0.12883 / 95 : 0.15888 / 99 : 0.25425
random_forest     MIST           Base   mass                   75 : 0.0288 / 90 : 0.10782 / 95 : 0.29875 / 99 : 4.67012
                                        radius                  75 : 0.005 / 90 : 0.01041 / 95 : 0.01596 / 99 : 0.04151
xgboost           MIST           Base   mass                   75 : 0.2286 / 90 : 0.71565 / 95 : 1.85374 / 99 : 7.47915
                                        radius                75 : 0.01645 / 90 : 0.02595 / 95 : 0.03406 / 99 : 0.06632

                                                             time
model             physical_model filter output_parameter
decision_tree     MIST           Base   mass               33.716
                                        radius             33.716
KNN               MIST           Base   mass                7.029
                                        radius              7.029
linear_regression MIST           Base   mass                0.597
                                        radius              0.597
mlp               MIST           Base   mass              683.282
                                        radius            683.282
random_forest     MIST           Base   mass              386.470
                                        radius            386.470
xgboost           MIST           Base   mass               11.765
                                        radius             11.765

## Getting the ranges for the values

In [5]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [6]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2978, Median : 8.35

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191

log_g  : Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047

log_R  : Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118

log_L  : Range : -3.33 - 5.9763, Mean : 2.2, Median : 2.3306

## Base vs mass_filtered

| Parameter      | Base                                                       | mass_filtered_smaller_3                                | mass_filtered_smaller_14                                           | mass_filtered_smaller_30                               |
| -------------  | ---------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : Range : 5.0 - 10.3 , Mean : 8.1222, Median : 8.15  | Range : 6.2 - 10.3, Mean : 9.1366, Median : 9.2        | Range : 5.0 - 10.3, Mean : 8.4693, Median : 8.5                    | Range : 0.1 - 29.9991, Mean : 5.0208, Median : 2.4047  |
| mass           | Range : 0.1000 - 298.5448, Mean : 11.3677, Median : 2.8697 | Range : 0.1 - 3.0, Mean : 1.3172, Median : 1.1821      | star_mass  : Range : 0.1 - 13.9995, Mean : 3.3831, Median : 2.0289 | Range : 0.1 - 3.0, Mean : 1.4429, Median : 1.3194      |
| log_teff       | Range : 3.34 - 5.3788, Mean : 4.0309, Median : 3.8557      | Range : 3.34 - 5.2138, Mean : 3.8022, Median : 3.7554  | log_Teff  : Range : 3.34 - 5.2138, Mean : 3.9383, Median : 3.867   | Range : 3.34 - 5.3542, Mean : 3.9845, Median : 3.9191  |
| log_g          | Range : -1.08 - 7.9405, Mean : 3.515, Median : 3.8557      | Range : -1.08 - 7.9405, Mean : 3.6564, Median : 4.1712 | log_g  : Range : -1.08 - 7.9405, Mean : 3.5574, Median : 3.9537    | Range : -1.08 - 7.9405, Mean : 3.5437, Median : 3.9117 |
| log_R          | Range : -1.86 - 3.1298, Mean : 0.7296, Median : 0.6976     | Range : -1.86 - 2.7813, Mean : 0.4084, Median : 0.2349 | log_R  : Range : -1.86 - 3.0828, Mean : 0.6007, Median : 0.5357    | Range : -1.86 - 3.1298, Mean : 0.6537, Median : 0.6118 |

### Mass parameter

In [ ]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9952703219364649
                                 mass_smaller_3  mass              0.9986499500890793
                                 mass_smaller_14 mass              0.9997535427935771
                                 mass_smaller_30 mass              0.9990976959093945
KNN               MIST           Base            mass              0.9895916504979603
                                 mass_smaller_3  mass              0.9983852760579003
                                 mass_smaller_14 mass              0.9993589218740458
                                 mass_smaller_30 mass              0.9987875623700606
linear_regression MIST           Base            mass              0.3042271481418729
                                 mass_smaller_3  mass              0.7674592941650149
                                 mass_smaller_14 mass              0.7253140443717881
                                 mass_smaller_30 mass               0.641754773914881
mlp               MIST           Base            mass              0.9762913286039826
                                 mass_smaller_3  mass               0.993895065017829
                                 mass_smaller_14 mass              0.9979690330276763
                                 mass_smaller_30 mass              0.9627090545375778
random_forest     MIST           Base            mass              0.9978063351241271
                                 mass_smaller_3  mass              0.9992738264822424
                                 mass_smaller_14 mass              0.9999006268975099
                                 mass_smaller_30 mass              0.9995874506793025
xgboost           MIST           Base            mass              0.9941191064217958
                                 mass_smaller_3  mass              0.9983314923113084
                                 mass_smaller_14 mass              0.9991287201758143
                                 mass_smaller_30 mass              0.9983542808698319

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.615%
                                 mass_smaller_3  mass               0.916%
                                 mass_smaller_14 mass                0.37%
                                 mass_smaller_30 mass               0.614%
KNN               MIST           Base            mass               0.913%
                                 mass_smaller_3  mass               1.002%
                                 mass_smaller_14 mass               0.597%
                                 mass_smaller_30 mass               0.712%
linear_regression MIST           Base            mass               7.465%
                                 mass_smaller_3  mass              12.023%
                                 mass_smaller_14 mass              12.351%
                                 mass_smaller_30 mass              12.239%
mlp               MIST           Base            mass               1.381%
                                 mass_smaller_3  mass               2.037%
                                 mass_smaller_14 mass               1.064%
                                 mass_smaller_30 mass               4.065%
random_forest     MIST           Base            mass               0.419%
                                 mass_smaller_3  mass               0.672%
                                 mass_smaller_14 mass               0.235%
                                 mass_smaller_30 mass               0.415%
xgboost           MIST           Base            mass               0.686%
                                 mass_smaller_3  mass               1.018%
                                 mass_smaller_14 mass               0.696%
                                 mass_smaller_30 mass                0.83%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.067%
                                 mass_smaller_3  mass              0.274%
                                 mass_smaller_14 mass              0.117%
                                 mass_smaller_30 mass              0.096%
KNN               MIST           Base            mass               0.11%
                                 mass_smaller_3  mass                0.4%
                                 mass_smaller_14 mass              0.209%
                                 mass_smaller_30 mass              0.172%
linear_regression MIST           Base            mass              3.801%
                                 mass_smaller_3  mass              9.153%
                                 mass_smaller_14 mass              9.338%
                                 mass_smaller_30 mass              8.741%
mlp               MIST           Base            mass              0.422%
                                 mass_smaller_3  mass               1.26%
                                 mass_smaller_14 mass              0.564%
                                 mass_smaller_30 mass              1.561%
random_forest     MIST           Base            mass              0.049%
                                 mass_smaller_3  mass              0.207%
                                 mass_smaller_14 mass              0.082%
                                 mass_smaller_30 mass              0.069%
xgboost           MIST           Base            mass              0.178%
                                 mass_smaller_3  mass              0.565%
                                 mass_smaller_14 mass              0.395%
                                 mass_smaller_30 mass              0.374%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.001%
                                 mass_smaller_3  mass              0.075%
                                 mass_smaller_14 mass               0.02%
                                 mass_smaller_30 mass               0.01%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_3  mass              0.156%
                                 mass_smaller_14 mass              0.048%
                                 mass_smaller_30 mass              0.023%
linear_regression MIST           Base            mass              2.732%
                                 mass_smaller_3  mass              7.177%
                                 mass_smaller_14 mass              7.035%
                                 mass_smaller_30 mass              6.762%
mlp               MIST           Base            mass              0.115%
                                 mass_smaller_3  mass              0.823%
                                 mass_smaller_14 mass              0.323%
                                 mass_smaller_30 mass              0.513%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_3  mass               0.07%
                                 mass_smaller_14 mass              0.024%
                                 mass_smaller_30 mass              0.012%
xgboost           MIST           Base            mass              0.033%
                                 mass_smaller_3  mass              0.337%
                                 mass_smaller_14 mass              0.206%
                                 mass_smaller_30 mass              0.155%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9976339781841599
                                 mass_smaller_3  mass               0.999324893917221
                                 mass_smaller_14 mass              0.9998767781112852
                                 mass_smaller_30 mass              0.9995491609932478
KNN               MIST           Base            mass              0.9948902170346177
                                 mass_smaller_3  mass               0.999194248387294
                                 mass_smaller_14 mass              0.9996846963987984
                                 mass_smaller_30 mass              0.9993993715544016
linear_regression MIST           Base            mass              0.5515679007842895
                                 mass_smaller_3  mass              0.8760475410802473
                                 mass_smaller_14 mass              0.8516537115536522
                                 mass_smaller_30 mass              0.8010959830005807
mlp               MIST           Base            mass              0.9881581645347787
                                 mass_smaller_3  mass              0.9969894975829324
                                 mass_smaller_14 mass              0.9989848962075332
                                 mass_smaller_30 mass              0.9815799476771778
random_forest     MIST           Base            mass              0.9989037560824912
                                 mass_smaller_3  mass               0.999636894028306
                                 mass_smaller_14 mass              0.9999503530371973
                                 mass_smaller_30 mass              0.9997937276626583
xgboost           MIST           Base            mass              0.9970552947594146
                                 mass_smaller_3  mass              0.9991654568285904
                                 mass_smaller_14 mass              0.9995643018981833
                                 mass_smaller_30 mass              0.9991768202519469

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              50.816%
                                 mass_smaller_3  mass              59.391%
                                 mass_smaller_14 mass              36.812%
                                 mass_smaller_30 mass              51.978%
KNN               MIST           Base            mass              48.322%
                                 mass_smaller_3  mass              46.267%
                                 mass_smaller_14 mass              18.732%
                                 mass_smaller_30 mass              25.561%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_3  mass              62.539%
                                 mass_smaller_14 mass              55.541%
                                 mass_smaller_30 mass              63.958%
mlp               MIST           Base            mass              58.569%
                                 mass_smaller_3  mass              65.604%
                                 mass_smaller_14 mass              25.383%
                                 mass_smaller_30 mass              65.438%
random_forest     MIST           Base            mass              32.158%
                                 mass_smaller_3  mass              51.551%
                                 mass_smaller_14 mass              16.749%
                                 mass_smaller_30 mass              25.504%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_3  mass               41.48%
                                 mass_smaller_14 mass              18.006%
                                 mass_smaller_30 mass              23.433%

                                                                                                                 Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                                 mass_smaller_3  mass                  75 : 0.232% / 90 : 0.611% / 95 : 1.042% / 99 : 2.973%
                                 mass_smaller_14 mass                  75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
                                 mass_smaller_30 mass                  75 : 0.048% / 90 : 0.172% / 95 : 0.365% / 99 : 1.264%
KNN               MIST           Base            mass                   75 : 0.013% / 90 : 0.07% / 95 : 0.236% / 99 : 2.302%
                                 mass_smaller_3  mass                  75 : 0.399% / 90 : 0.862% / 95 : 1.462% / 99 : 4.535%
                                 mass_smaller_14 mass                  75 : 0.171% / 90 : 0.535% / 95 : 0.925% / 99 : 2.329%
                                 mass_smaller_30 mass                  75 : 0.096% / 90 : 0.347% / 95 : 0.679% / 99 : 2.469%
linear_regression MIST           Base            mass                 75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 mass_smaller_3  mass              75 : 12.857% / 90 : 19.584% / 95 : 24.212% / 99 : 36.792%
                                 mass_smaller_14 mass               75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%
                                 mass_smaller_30 mass                75 : 10.98% / 90 : 16.99% / 95 : 23.919% / 99 : 48.156%
mlp               MIST           Base            mass                   75 : 0.242% / 90 : 0.82% / 95 : 1.756% / 99 : 6.292%
                                 mass_smaller_3  mass                   75 : 1.661% / 90 : 2.828% / 95 : 3.79% / 99 : 6.481%
                                 mass_smaller_14 mass                  75 : 0.666% / 90 : 1.262% / 95 : 1.857% / 99 : 3.598%
                                 mass_smaller_30 mass                  75 : 1.118% / 90 : 3.273% / 95 : 6.509% / 99 : 20.27%
random_forest     MIST           Base            mass                   75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                                 mass_smaller_3  mass                  75 : 0.192% / 90 : 0.427% / 95 : 0.681% / 99 : 2.322%
                                 mass_smaller_14 mass                  75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
                                 mass_smaller_30 mass                   75 : 0.037% / 90 : 0.11% / 95 : 0.231% / 99 : 0.933%
xgboost           MIST           Base            mass                   75 : 0.091% / 90 : 0.33% / 95 : 0.726% / 99 : 2.844%
                                 mass_smaller_3  mass                   75 : 0.68% / 90 : 1.221% / 95 : 1.767% / 99 : 3.786%
                                 mass_smaller_14 mass                  75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%
                                 mass_smaller_30 mass                    75 : 0.39% / 90 : 0.854% / 95 : 1.37% / 99 : 3.591%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_3  mass               11.536891222000122
                                 mass_smaller_14 mass               18.880497217178345
                                 mass_smaller_30 mass               21.883111715316772
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_3  mass               2.7264862060546875
                                 mass_smaller_14 mass                 5.27383017539978
                                 mass_smaller_30 mass               6.2819530963897705
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_3  mass              0.28507542610168457
                                 mass_smaller_14 mass              0.46092677116394043
                                 mass_smaller_30 mass               0.5243825912475586
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_3  mass               116.37484526634216
                                 mass_smaller_14 mass                 189.019047498703
                                 mass_smaller_30 mass               349.92928099632263
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_3  mass                142.9930453300476
                                 mass_smaller_14 mass               248.72876453399658

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_3  mass              0.0999979840073621 - 2.9999868374941867
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
                                 mass_smaller_30 mass              0.0999979840073621 - 29.997679694990666

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9936340302001091
                                 mass_smaller_3  mass              0.9998026181186485
                                 mass_smaller_14 mass              0.9997590738023714
                                 mass_smaller_30 mass              0.9988722561008796
KNN               MIST           Base            mass              0.9843387655163102
                                 mass_smaller_3  mass              0.9992523919405951
                                 mass_smaller_14 mass              0.9991667805594964
                                 mass_smaller_30 mass              0.9983227260594209
linear_regression MIST           Base            mass              0.2728709030098654
                                 mass_smaller_3  mass              0.8838520137942808
                                 mass_smaller_14 mass               0.703580703577132
                                 mass_smaller_30 mass              0.5907578263387271
mlp               MIST           Base            mass              0.9717157238872854
                                 mass_smaller_3  mass              0.9977746446628951
                                 mass_smaller_14 mass               0.997967880087404
                                 mass_smaller_30 mass               0.949307847125218
random_forest     MIST           Base            mass              0.9973661987481759
                                 mass_smaller_3  mass              0.9999474983734866
                                 mass_smaller_14 mass              0.9999235468255409
                                 mass_smaller_30 mass               0.999521993790828
xgboost           MIST           Base            mass              0.9910072956179956
                                 mass_smaller_3  mass              0.9990479465037205
                                 mass_smaller_14 mass              0.9987960913520983
                                 mass_smaller_30 mass               0.997607113775301

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.703%
                                 mass_smaller_3  mass               0.365%
                                 mass_smaller_14 mass               0.368%
                                 mass_smaller_30 mass               0.703%
KNN               MIST           Base            mass               1.103%
                                 mass_smaller_3  mass               0.711%
                                 mass_smaller_14 mass               0.685%
                                 mass_smaller_30 mass               0.857%
linear_regression MIST           Base            mass               7.516%
                                 mass_smaller_3  mass                9.07%
                                 mass_smaller_14 mass              12.911%
                                 mass_smaller_30 mass               13.39%
mlp               MIST           Base            mass               1.484%
                                 mass_smaller_3  mass                1.38%
                                 mass_smaller_14 mass               1.069%
                                 mass_smaller_30 mass               4.854%
random_forest     MIST           Base            mass               0.452%
                                 mass_smaller_3  mass               0.188%
                                 mass_smaller_14 mass               0.207%
                                 mass_smaller_30 mass               0.458%
xgboost           MIST           Base            mass               0.836%
                                 mass_smaller_3  mass               0.802%
                                 mass_smaller_14 mass               0.823%
                                 mass_smaller_30 mass               1.024%

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.09%
                                 mass_smaller_3  mass               0.179%
                                 mass_smaller_14 mass               0.122%
                                 mass_smaller_30 mass               0.125%
KNN               MIST           Base            mass               0.145%
                                 mass_smaller_3  mass               0.333%
                                 mass_smaller_14 mass               0.222%
                                 mass_smaller_30 mass               0.214%
linear_regression MIST           Base            mass               4.392%
                                 mass_smaller_3  mass               7.205%
                                 mass_smaller_14 mass              10.456%
                                 mass_smaller_30 mass              10.491%
mlp               MIST           Base            mass               0.467%
                                 mass_smaller_3  mass               0.947%
                                 mass_smaller_14 mass               0.483%
                                 mass_smaller_30 mass               1.883%
random_forest     MIST           Base            mass               0.056%
                                 mass_smaller_3  mass               0.094%
                                 mass_smaller_14 mass               0.063%
                                 mass_smaller_30 mass               0.077%
xgboost           MIST           Base            mass               0.227%
                                 mass_smaller_3  mass                0.54%
                                 mass_smaller_14 mass                0.46%
                                 mass_smaller_30 mass               0.472%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.002%
                                 mass_smaller_3  mass              0.084%
                                 mass_smaller_14 mass               0.03%
                                 mass_smaller_30 mass              0.016%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_3  mass              0.152%
                                 mass_smaller_14 mass              0.051%
                                 mass_smaller_30 mass              0.028%
linear_regression MIST           Base            mass              3.771%
                                 mass_smaller_3  mass              6.025%
                                 mass_smaller_14 mass              8.915%
                                 mass_smaller_30 mass              9.385%
mlp               MIST           Base            mass              0.124%
                                 mass_smaller_3  mass              0.633%
                                 mass_smaller_14 mass              0.251%
                                 mass_smaller_30 mass                0.5%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_3  mass              0.045%
                                 mass_smaller_14 mass              0.018%
                                 mass_smaller_30 mass              0.009%
xgboost           MIST           Base            mass              0.042%
                                 mass_smaller_3  mass              0.361%
                                 mass_smaller_14 mass              0.228%
                                 mass_smaller_30 mass              0.182%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9968269721840094
                                 mass_smaller_3  mass              0.9999013049827169
                                 mass_smaller_14 mass              0.9998795329372157
                                 mass_smaller_30 mass              0.9994366029183054
KNN               MIST           Base            mass              0.9924111983284241
                                 mass_smaller_3  mass              0.9996303324370441
                                 mass_smaller_14 mass              0.9995923399848191
                                 mass_smaller_30 mass              0.9991751174974345
linear_regression MIST           Base            mass              0.5343027371731521
                                 mass_smaller_3  mass              0.9456040197306378
                                 mass_smaller_14 mass              0.8532020075802779
                                 mass_smaller_30 mass              0.7808862484728856
mlp               MIST           Base            mass              0.9860617427522443
                                 mass_smaller_3  mass              0.9989678754731477
                                 mass_smaller_14 mass              0.9989847800218492
                                 mass_smaller_30 mass              0.9748944519439862
random_forest     MIST           Base            mass              0.9986840004415223
                                 mass_smaller_3  mass              0.9999737782832668
                                 mass_smaller_14 mass              0.9999617835917853
                                 mass_smaller_30 mass              0.9997609878413475
xgboost           MIST           Base            mass              0.9955145412428942
                                 mass_smaller_3  mass              0.9995239924982884
                                 mass_smaller_14 mass              0.9993979214189108
                                 mass_smaller_30 mass              0.9988031364064863

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              44.154%
                                 mass_smaller_3  mass              10.411%
                                 mass_smaller_14 mass              36.812%
                                 mass_smaller_30 mass              51.978%
KNN               MIST           Base            mass              42.445%
                                 mass_smaller_3  mass              11.605%
                                 mass_smaller_14 mass              18.732%
                                 mass_smaller_30 mass              21.946%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_3  mass              30.516%
                                 mass_smaller_14 mass              55.541%
                                 mass_smaller_30 mass              63.958%
mlp               MIST           Base            mass              36.763%
                                 mass_smaller_3  mass              15.181%
                                 mass_smaller_14 mass              25.383%
                                 mass_smaller_30 mass              65.438%
random_forest     MIST           Base            mass              27.991%
                                 mass_smaller_3  mass               8.032%
                                 mass_smaller_14 mass              16.749%
                                 mass_smaller_30 mass              25.504%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_3  mass               9.206%
                                 mass_smaller_14 mass              18.006%
                                 mass_smaller_30 mass              18.918%

                                                                                                                 Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.993%
                                 mass_smaller_3  mass                  75 : 0.202% / 90 : 0.413% / 95 : 0.669% / 99 : 1.406%
                                 mass_smaller_14 mass                  75 : 0.098% / 90 : 0.303% / 95 : 0.532% / 99 : 1.395%
                                 mass_smaller_30 mass                  75 : 0.062% / 90 : 0.229% / 95 : 0.471% / 99 : 1.747%
KNN               MIST           Base            mass                  75 : 0.017% / 90 : 0.112% / 95 : 0.345% / 99 : 2.996%
                                 mass_smaller_3  mass                  75 : 0.366% / 90 : 0.752% / 95 : 1.176% / 99 : 3.166%
                                 mass_smaller_14 mass                    75 : 0.175% / 90 : 0.5% / 95 : 0.893% / 99 : 2.754%
                                 mass_smaller_30 mass                  75 : 0.112% / 90 : 0.409% / 95 : 0.885% / 99 : 3.354%
linear_regression MIST           Base            mass                 75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%
                                 mass_smaller_3  mass               75 : 10.06% / 90 : 15.251% / 95 : 18.394% / 99 : 23.434%
                                 mass_smaller_14 mass               75 : 14.815% / 90 : 20.33% / 95 : 23.858% / 99 : 35.853%
                                 mass_smaller_30 mass              75 : 13.689% / 90 : 18.009% / 95 : 23.408% / 99 : 47.038%
mlp               MIST           Base            mass                   75 : 0.28% / 90 : 0.962% / 95 : 1.976% / 99 : 6.621%
                                 mass_smaller_3  mass                  75 : 1.281% / 90 : 2.179% / 95 : 2.883% / 99 : 4.665%
                                 mass_smaller_14 mass                  75 : 0.534% / 90 : 1.022% / 95 : 1.612% / 99 : 3.326%
                                 mass_smaller_30 mass                 75 : 1.362% / 90 : 4.275% / 95 : 8.746% / 99 : 23.994%
random_forest     MIST           Base            mass                  75 : 0.005% / 90 : 0.036% / 95 : 0.139% / 99 : 1.207%
                                 mass_smaller_3  mass                  75 : 0.107% / 90 : 0.219% / 95 : 0.331% / 99 : 0.749%
                                 mass_smaller_14 mass                  75 : 0.051% / 90 : 0.141% / 95 : 0.251% / 99 : 0.728%
                                 mass_smaller_30 mass                  75 : 0.032% / 90 : 0.112% / 95 : 0.253% / 99 : 1.248%
xgboost           MIST           Base            mass                  75 : 0.129% / 90 : 0.432% / 95 : 0.904% / 99 : 3.697%
                                 mass_smaller_3  mass                   75 : 0.709% / 90 : 1.22% / 95 : 1.665% / 99 : 2.855%
                                 mass_smaller_14 mass                   75 : 0.555% / 90 : 1.123% / 95 : 1.66% / 99 : 3.276%
                                 mass_smaller_30 mass                  75 : 0.479% / 90 : 1.129% / 95 : 1.885% / 99 : 4.566%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_3  mass               11.536891222000122
                                 mass_smaller_14 mass               18.880497217178345
                                 mass_smaller_30 mass               21.883111715316772
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_3  mass               2.7264862060546875
                                 mass_smaller_14 mass                 5.27383017539978
                                 mass_smaller_30 mass               6.2819530963897705
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_3  mass              0.28507542610168457
                                 mass_smaller_14 mass              0.46092677116394043
                                 mass_smaller_30 mass               0.5243825912475586
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_3  mass               116.37484526634216
                                 mass_smaller_14 mass                 189.019047498703
                                 mass_smaller_30 mass               349.92928099632263
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_3  mass                142.9930453300476
                                 mass_smaller_14 mass               248.72876453399658

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485
KNN               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485
linear_regression MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485
mlp               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485
random_forest     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485
xgboost           MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_3  mass               0.6538581961218565 - 2.999977935638737
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
                                 mass_smaller_30 mass               0.6542770535966311 - 29.67887151062485

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9992828062113351
                                 mass_smaller_3  mass               0.999184122352797
                                 mass_smaller_14 mass              0.9999398039293963
                                 mass_smaller_30 mass              0.9998927127269793
KNN               MIST           Base            mass              0.9993836364150782
                                 mass_smaller_3  mass              0.9991895200338567
                                 mass_smaller_14 mass              0.9997767455983123
                                 mass_smaller_30 mass              0.9998957487907331
linear_regression MIST           Base            mass              0.3168817813892185
                                 mass_smaller_3  mass              0.6152163506955306
                                 mass_smaller_14 mass              0.7627584839179414
                                 mass_smaller_30 mass               0.719201451727792
mlp               MIST           Base            mass               0.990929974425174
                                 mass_smaller_3  mass              0.9935432284280881
                                 mass_smaller_14 mass              0.9986994416645744
                                 mass_smaller_30 mass              0.9841625316617302
random_forest     MIST           Base            mass              0.9997496322236138
                                 mass_smaller_3  mass              0.9996443438393721
                                 mass_smaller_14 mass              0.9999737930935538
                                 mass_smaller_30 mass              0.9999690893306589
xgboost           MIST           Base            mass              0.9988754736593098
                                 mass_smaller_3  mass              0.9991669639635611
                                 mass_smaller_14 mass              0.9997624928648234
                                 mass_smaller_30 mass              0.9996770428541898

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.281%
                                 mass_smaller_3  mass               0.762%
                                 mass_smaller_14 mass                0.19%
                                 mass_smaller_30 mass               0.212%
KNN               MIST           Base            mass                0.26%
                                 mass_smaller_3  mass               0.761%
                                 mass_smaller_14 mass               0.366%
                                 mass_smaller_30 mass               0.209%
linear_regression MIST           Base            mass                8.67%
                                 mass_smaller_3  mass              17.207%
                                 mass_smaller_14 mass              11.933%
                                 mass_smaller_30 mass              10.833%
mlp               MIST           Base            mass                 1.0%
                                 mass_smaller_3  mass               2.461%
                                 mass_smaller_14 mass               0.896%
                                 mass_smaller_30 mass               2.726%
random_forest     MIST           Base            mass               0.166%
                                 mass_smaller_3  mass               0.503%
                                 mass_smaller_14 mass               0.126%
                                 mass_smaller_30 mass               0.114%
xgboost           MIST           Base            mass               0.352%
                                 mass_smaller_3  mass                0.77%
                                 mass_smaller_14 mass               0.391%
                                 mass_smaller_30 mass               0.375%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.021%
                                 mass_smaller_3  mass              0.327%
                                 mass_smaller_14 mass              0.058%
                                 mass_smaller_30 mass              0.026%
KNN               MIST           Base            mass              0.034%
                                 mass_smaller_3  mass              0.378%
                                 mass_smaller_14 mass              0.149%
                                 mass_smaller_30 mass               0.07%
linear_regression MIST           Base            mass              3.616%
                                 mass_smaller_3  mass              13.08%
                                 mass_smaller_14 mass              8.073%
                                 mass_smaller_30 mass              6.771%
mlp               MIST           Base            mass              0.324%
                                 mass_smaller_3  mass              1.781%
                                 mass_smaller_14 mass              0.578%
                                 mass_smaller_30 mass              1.169%
random_forest     MIST           Base            mass              0.021%
                                 mass_smaller_3  mass              0.298%
                                 mass_smaller_14 mass              0.063%
                                 mass_smaller_30 mass              0.029%
xgboost           MIST           Base            mass              0.104%
                                 mass_smaller_3  mass              0.526%
                                 mass_smaller_14 mass              0.269%
                                 mass_smaller_30 mass              0.214%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.0%
                                 mass_smaller_3  mass              0.051%
                                 mass_smaller_14 mass              0.002%
                                 mass_smaller_30 mass              0.001%
KNN               MIST           Base            mass              0.001%
                                 mass_smaller_3  mass              0.208%
                                 mass_smaller_14 mass              0.038%
                                 mass_smaller_30 mass              0.013%
linear_regression MIST           Base            mass              1.861%
                                 mass_smaller_3  mass               9.93%
                                 mass_smaller_14 mass              5.653%
                                 mass_smaller_30 mass              4.696%
mlp               MIST           Base            mass              0.106%
                                 mass_smaller_3  mass              1.294%
                                 mass_smaller_14 mass              0.402%
                                 mass_smaller_30 mass              0.545%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_3  mass              0.188%
                                 mass_smaller_14 mass              0.033%
                                 mass_smaller_30 mass              0.013%
xgboost           MIST           Base            mass              0.025%
                                 mass_smaller_3  mass               0.35%
                                 mass_smaller_14 mass              0.179%
                                 mass_smaller_30 mass               0.12%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9996414671007774
                                 mass_smaller_3  mass              0.9995972004854448
                                 mass_smaller_14 mass              0.9999700313729203
                                 mass_smaller_30 mass              0.9999463636889504
KNN               MIST           Base            mass              0.9996927065174758
                                 mass_smaller_3  mass              0.9996113621195056
                                 mass_smaller_14 mass              0.9998883692148779
                                 mass_smaller_30 mass              0.9999479221527767
linear_regression MIST           Base            mass              0.5956286032810738
                                 mass_smaller_3  mass              0.8455102812660852
                                 mass_smaller_14 mass              0.9184081581407212
                                 mass_smaller_30 mass              0.8818533174049262
mlp               MIST           Base            mass              0.9955996860365472
                                 mass_smaller_3  mass              0.9967722337850292
                                 mass_smaller_14 mass              0.9993909030531274
                                 mass_smaller_30 mass               0.992485884060122
random_forest     MIST           Base            mass              0.9998754804643019
                                 mass_smaller_3  mass              0.9998265900407789
                                 mass_smaller_14 mass               0.999987052162877
                                 mass_smaller_30 mass               0.999984609078679
xgboost           MIST           Base            mass              0.9994709362034415
                                 mass_smaller_3  mass              0.9996131778577277
                                 mass_smaller_14 mass              0.9998867034593512
                                 mass_smaller_30 mass              0.9998391744806859

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              37.398%
                                 mass_smaller_3  mass              18.112%
                                 mass_smaller_14 mass              10.632%
                                 mass_smaller_30 mass              31.828%
KNN               MIST           Base            mass              13.243%
                                 mass_smaller_3  mass              12.805%
                                 mass_smaller_14 mass               6.976%
                                 mass_smaller_30 mass               8.159%
linear_regression MIST           Base            mass              87.305%
                                 mass_smaller_3  mass              56.821%
                                 mass_smaller_14 mass              53.433%
                                 mass_smaller_30 mass              59.592%
mlp               MIST           Base            mass              22.957%
                                 mass_smaller_3  mass              12.591%
                                 mass_smaller_14 mass              12.011%
                                 mass_smaller_30 mass              34.654%
random_forest     MIST           Base            mass               8.119%
                                 mass_smaller_3  mass               9.114%
                                 mass_smaller_14 mass               3.642%
                                 mass_smaller_30 mass              13.669%
xgboost           MIST           Base            mass               13.82%
                                 mass_smaller_3  mass               7.615%
                                 mass_smaller_14 mass               4.227%
                                 mass_smaller_30 mass              11.292%

                                                                                                                 Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                                 mass_smaller_3  mass                  75 : 0.354% / 90 : 1.065% / 95 : 1.439% / 99 : 2.606%
                                 mass_smaller_14 mass                  75 : 0.043% / 90 : 0.176% / 95 : 0.262% / 99 : 0.659%
                                 mass_smaller_30 mass                  75 : 0.017% / 90 : 0.076% / 95 : 0.116% / 99 : 0.287%
KNN               MIST           Base            mass                  75 : 0.006% / 90 : 0.028% / 95 : 0.057% / 99 : 0.751%
                                 mass_smaller_3  mass                  75 : 0.477% / 90 : 0.907% / 95 : 1.306% / 99 : 3.588%
                                 mass_smaller_14 mass                   75 : 0.121% / 90 : 0.415% / 95 : 0.755% / 99 : 1.57%
                                 mass_smaller_30 mass                   75 : 0.052% / 90 : 0.182% / 95 : 0.339% / 99 : 0.79%
linear_regression MIST           Base            mass                    75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%
                                 mass_smaller_3  mass              75 : 18.907% / 90 : 28.706% / 95 : 36.401% / 99 : 48.607%
                                 mass_smaller_14 mass               75 : 8.994% / 90 : 17.493% / 95 : 30.286% / 99 : 44.672%
                                 mass_smaller_30 mass               75 : 7.802% / 90 : 10.773% / 95 : 22.168% / 99 : 51.917%
mlp               MIST           Base            mass                  75 : 0.204% / 90 : 0.596% / 95 : 1.317% / 99 : 4.578%
                                 mass_smaller_3  mass                  75 : 2.438% / 90 : 4.012% / 95 : 5.207% / 99 : 7.849%
                                 mass_smaller_14 mass                  75 : 0.711% / 90 : 1.212% / 95 : 1.757% / 99 : 3.354%
                                 mass_smaller_30 mass                   75 : 0.999% / 90 : 2.3% / 95 : 4.194% / 99 : 13.466%
random_forest     MIST           Base            mass                   75 : 0.004% / 90 : 0.009% / 95 : 0.026% / 99 : 0.48%
                                 mass_smaller_3  mass                  75 : 0.393% / 90 : 0.672% / 95 : 0.904% / 99 : 1.705%
                                 mass_smaller_14 mass                  75 : 0.076% / 90 : 0.143% / 95 : 0.211% / 99 : 0.515%
                                 mass_smaller_30 mass                  75 : 0.032% / 90 : 0.061% / 95 : 0.093% / 99 : 0.235%
xgboost           MIST           Base            mass                  75 : 0.055% / 90 : 0.194% / 95 : 0.467% / 99 : 1.559%
                                 mass_smaller_3  mass                    75 : 0.698% / 90 : 1.208% / 95 : 1.62% / 99 : 2.74%
                                 mass_smaller_14 mass                   75 : 0.364% / 90 : 0.621% / 95 : 0.82% / 99 : 1.313%
                                 mass_smaller_30 mass                  75 : 0.263% / 90 : 0.486% / 95 : 0.708% / 99 : 1.443%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_3  mass               11.536891222000122
                                 mass_smaller_14 mass               18.880497217178345
                                 mass_smaller_30 mass               21.883111715316772
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_3  mass               2.7264862060546875
                                 mass_smaller_14 mass                 5.27383017539978
                                 mass_smaller_30 mass               6.2819530963897705
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_3  mass              0.28507542610168457
                                 mass_smaller_14 mass              0.46092677116394043
                                 mass_smaller_30 mass               0.5243825912475586
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_3  mass               116.37484526634216
                                 mass_smaller_14 mass                 189.019047498703
                                 mass_smaller_30 mass               349.92928099632263
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_3  mass                142.9930453300476
                                 mass_smaller_14 mass               248.72876453399658

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494
KNN               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494
linear_regression MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494
mlp               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494
random_forest     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494
xgboost           MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_3  mass               0.5453736573627747 - 2.999885115629765
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
                                 mass_smaller_30 mass               0.5453736573627747 - 29.99464069960494

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9919676920924657
                                 mass_smaller_3  mass               0.9922005887222858
                                 mass_smaller_14 mass               0.9994652103837574
                                 mass_smaller_30 mass               0.9987003952016552
KNN               MIST           Base            mass               0.9860770182495742
                                 mass_smaller_3  mass               0.9927200597567128
                                 mass_smaller_14 mass               0.9993197080056749
                                 mass_smaller_30 mass               0.9987071760845542
linear_regression MIST           Base            mass              0.38830292902171926
                                 mass_smaller_3  mass              0.42605261782269743
                                 mass_smaller_14 mass               0.7294304975319248
                                 mass_smaller_30 mass               0.6935074816161797
mlp               MIST           Base            mass               0.9593548446204826
                                 mass_smaller_3  mass                0.975771969308888
                                 mass_smaller_14 mass               0.9973619756891468
                                 mass_smaller_30 mass               0.9755567760581224
random_forest     MIST           Base            mass               0.9949439900825313
                                 mass_smaller_3  mass               0.9954521777596107
                                 mass_smaller_14 mass               0.9997284223560081
                                 mass_smaller_30 mass               0.9992635983495934
xgboost           MIST           Base            mass               0.9944238807426196
                                 mass_smaller_3  mass               0.9932636988080545
                                 mass_smaller_14 mass               0.9992349115882041
                                 mass_smaller_30 mass               0.9988892465563328

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.721%
                                 mass_smaller_3  mass               2.249%
                                 mass_smaller_14 mass               0.553%
                                 mass_smaller_30 mass               0.727%
KNN               MIST           Base            mass               0.949%
                                 mass_smaller_3  mass               2.174%
                                 mass_smaller_14 mass               0.627%
                                 mass_smaller_30 mass               0.726%
linear_regression MIST           Base            mass               6.301%
                                 mass_smaller_3  mass              19.317%
                                 mass_smaller_14 mass              12.426%
                                 mass_smaller_30 mass              11.174%
mlp               MIST           Base            mass               1.631%
                                 mass_smaller_3  mass               3.965%
                                 mass_smaller_14 mass               1.333%
                                 mass_smaller_30 mass                 3.2%
random_forest     MIST           Base            mass               0.572%
                                 mass_smaller_3  mass               1.718%
                                 mass_smaller_14 mass               0.395%
                                 mass_smaller_30 mass               0.548%
xgboost           MIST           Base            mass                 0.6%
                                 mass_smaller_3  mass               2.091%
                                 mass_smaller_14 mass               0.672%
                                 mass_smaller_30 mass               0.677%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.069%
                                 mass_smaller_3  mass              0.681%
                                 mass_smaller_14 mass              0.198%
                                 mass_smaller_30 mass              0.113%
KNN               MIST           Base            mass              0.126%
                                 mass_smaller_3  mass              0.866%
                                 mass_smaller_14 mass              0.272%
                                 mass_smaller_30 mass              0.201%
linear_regression MIST           Base            mass              2.762%
                                 mass_smaller_3  mass              15.53%
                                 mass_smaller_14 mass              8.758%
                                 mass_smaller_30 mass              6.926%
mlp               MIST           Base            mass              0.475%
                                 mass_smaller_3  mass              2.327%
                                 mass_smaller_14 mass              0.839%
                                 mass_smaller_30 mass              1.263%
random_forest     MIST           Base            mass               0.07%
                                 mass_smaller_3  mass              0.602%
                                 mass_smaller_14 mass              0.173%
                                 mass_smaller_30 mass              0.103%
xgboost           MIST           Base            mass              0.157%
                                 mass_smaller_3  mass              0.983%
                                 mass_smaller_14 mass              0.419%
                                 mass_smaller_30 mass              0.334%

                                                                     MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.001%
                                 mass_smaller_3  mass               0.076%
                                 mass_smaller_14 mass               0.022%
                                 mass_smaller_30 mass               0.011%
KNN               MIST           Base            mass               0.004%
                                 mass_smaller_3  mass               0.197%
                                 mass_smaller_14 mass               0.061%
                                 mass_smaller_30 mass               0.029%
linear_regression MIST           Base            mass               1.595%
                                 mass_smaller_3  mass              13.246%
                                 mass_smaller_14 mass               5.749%
                                 mass_smaller_30 mass               4.102%
mlp               MIST           Base            mass               0.115%
                                 mass_smaller_3  mass               1.571%
                                 mass_smaller_14 mass               0.545%
                                 mass_smaller_30 mass               0.534%
random_forest     MIST           Base            mass               0.002%
                                 mass_smaller_3  mass               0.151%
                                 mass_smaller_14 mass               0.044%
                                 mass_smaller_30 mass                0.02%
xgboost           MIST           Base            mass               0.032%
                                 mass_smaller_3  mass               0.418%
                                 mass_smaller_14 mass                0.22%
                                 mass_smaller_30 mass               0.161%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9959955403728619
                                 mass_smaller_3  mass              0.9960926617954065
                                 mass_smaller_14 mass               0.999733532743571
                                 mass_smaller_30 mass              0.9993514303248708
KNN               MIST           Base            mass              0.9931315041563596
                                 mass_smaller_3  mass              0.9964017663413025
                                 mass_smaller_14 mass              0.9996726034047599
                                 mass_smaller_30 mass              0.9993550007458655
linear_regression MIST           Base            mass              0.6497333100274104
                                 mass_smaller_3  mass              0.7694085923484659
                                 mass_smaller_14 mass              0.9286874399666551
                                 mass_smaller_30 mass              0.8934975727418435
mlp               MIST           Base            mass              0.9801734298207664
                                 mass_smaller_3  mass              0.9878862358028604
                                 mass_smaller_14 mass              0.9987250717515364
                                 mass_smaller_30 mass              0.9877896115191739
random_forest     MIST           Base            mass              0.9975811556691733
                                 mass_smaller_3  mass              0.9977358261257694
                                 mass_smaller_14 mass              0.9998659386279564
                                 mass_smaller_30 mass              0.9996323346107105
xgboost           MIST           Base            mass              0.9972366154162345
                                 mass_smaller_3  mass              0.9966834604580608
                                 mass_smaller_14 mass              0.9996279750905939
                                 mass_smaller_30 mass              0.9994445412527682

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               52.61%
                                 mass_smaller_3  mass               70.17%
                                 mass_smaller_14 mass              17.875%
                                 mass_smaller_30 mass              31.779%
KNN               MIST           Base            mass              50.028%
                                 mass_smaller_3  mass              54.665%
                                 mass_smaller_14 mass              12.229%
                                 mass_smaller_30 mass               25.95%
linear_regression MIST           Base            mass              87.044%
                                 mass_smaller_3  mass               73.89%
                                 mass_smaller_14 mass              53.149%
                                 mass_smaller_30 mass              63.091%
mlp               MIST           Base            mass              60.637%
                                 mass_smaller_3  mass               77.51%
                                 mass_smaller_14 mass              25.342%
                                 mass_smaller_30 mass               62.25%
random_forest     MIST           Base            mass              33.293%
                                 mass_smaller_3  mass              60.907%
                                 mass_smaller_14 mass               9.617%
                                 mass_smaller_30 mass              25.403%
xgboost           MIST           Base            mass              21.469%
                                 mass_smaller_3  mass              49.008%
                                 mass_smaller_14 mass              11.967%
                                 mass_smaller_30 mass               23.79%

                                                                                                                 Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                   75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.61%
                                 mass_smaller_3  mass                 75 : 0.412% / 90 : 1.407% / 95 : 3.084% / 99 : 11.601%
                                 mass_smaller_14 mass                  75 : 0.123% / 90 : 0.542% / 95 : 1.113% / 99 : 2.593%
                                 mass_smaller_30 mass                   75 : 0.06% / 90 : 0.247% / 95 : 0.512% / 99 : 1.243%
KNN               MIST           Base            mass                    75 : 0.02% / 90 : 0.085% / 95 : 0.29% / 99 : 2.888%
                                 mass_smaller_3  mass                  75 : 0.728% / 90 : 2.354% / 95 : 4.441% / 99 : 9.805%
                                 mass_smaller_14 mass                    75 : 0.264% / 90 : 0.813% / 95 : 1.271% / 99 : 2.6%
                                 mass_smaller_30 mass                  75 : 0.138% / 90 : 0.458% / 95 : 0.846% / 99 : 2.754%
linear_regression MIST           Base            mass                  75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 mass_smaller_3  mass              75 : 21.598% / 90 : 31.457% / 95 : 38.825% / 99 : 49.954%
                                 mass_smaller_14 mass               75 : 9.665% / 90 : 19.317% / 95 : 29.514% / 99 : 44.616%
                                 mass_smaller_30 mass                75 : 8.08% / 90 : 11.936% / 95 : 26.545% / 99 : 49.557%
mlp               MIST           Base            mass                  75 : 0.241% / 90 : 0.834% / 95 : 1.996% / 99 : 7.733%
                                 mass_smaller_3  mass                  75 : 2.86% / 90 : 4.858% / 95 : 6.491% / 99 : 13.419%
                                 mass_smaller_14 mass                  75 : 1.105% / 90 : 1.874% / 95 : 2.514% / 99 : 4.761%
                                 mass_smaller_30 mass                  75 : 0.983% / 90 : 2.348% / 95 : 4.39% / 99 : 17.442%
random_forest     MIST           Base            mass                   75 : 0.01% / 90 : 0.037% / 95 : 0.102% / 99 : 1.625%
                                 mass_smaller_3  mass                  75 : 0.457% / 90 : 1.258% / 95 : 2.669% / 99 : 8.475%
                                 mass_smaller_14 mass                  75 : 0.163% / 90 : 0.478% / 95 : 0.808% / 99 : 1.802%
                                 mass_smaller_30 mass                   75 : 0.073% / 90 : 0.22% / 95 : 0.382% / 99 : 0.985%
xgboost           MIST           Base            mass                  75 : 0.079% / 90 : 0.248% / 95 : 0.643% / 99 : 2.595%
                                 mass_smaller_3  mass                  75 : 0.915% / 90 : 2.328% / 95 : 4.095% / 99 : 9.415%
                                 mass_smaller_14 mass                   75 : 0.53% / 90 : 1.078% / 95 : 1.469% / 99 : 2.406%
                                 mass_smaller_30 mass                  75 : 0.431% / 90 : 0.787% / 95 : 1.076% / 99 : 1.991%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_3  mass               11.536891222000122
                                 mass_smaller_14 mass               18.880497217178345
                                 mass_smaller_30 mass               21.883111715316772
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_3  mass               2.7264862060546875
                                 mass_smaller_14 mass                 5.27383017539978
                                 mass_smaller_30 mass               6.2819530963897705
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_3  mass              0.28507542610168457
                                 mass_smaller_14 mass              0.46092677116394043
                                 mass_smaller_30 mass               0.5243825912475586
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_3  mass               116.37484526634216
                                 mass_smaller_14 mass                 189.019047498703
                                 mass_smaller_30 mass               349.92928099632263
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_3  mass                142.9930453300476
                                 mass_smaller_14 mass               248.72876453399658

In [6]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9952703219364649
                                 mass_smaller_14 mass              0.9997535427935771
KNN               MIST           Base            mass              0.9895916504979603
                                 mass_smaller_14 mass              0.9993589218740458
linear_regression MIST           Base            mass              0.3042271481418729
                                 mass_smaller_14 mass              0.7253140443717881
mlp               MIST           Base            mass              0.9762913286039826
                                 mass_smaller_14 mass              0.9979690330276763
random_forest     MIST           Base            mass              0.9978063351241271
                                 mass_smaller_14 mass              0.9999006268975099
xgboost           MIST           Base            mass              0.9941191064217958
                                 mass_smaller_14 mass              0.9991287201758143

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.615%
                                 mass_smaller_14 mass                0.37%
KNN               MIST           Base            mass               0.913%
                                 mass_smaller_14 mass               0.597%
linear_regression MIST           Base            mass               7.465%
                                 mass_smaller_14 mass              12.351%
mlp               MIST           Base            mass               1.381%
                                 mass_smaller_14 mass               1.064%
random_forest     MIST           Base            mass               0.419%
                                 mass_smaller_14 mass               0.235%
xgboost           MIST           Base            mass               0.686%
                                 mass_smaller_14 mass               0.696%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.067%
                                 mass_smaller_14 mass              0.117%
KNN               MIST           Base            mass               0.11%
                                 mass_smaller_14 mass              0.209%
linear_regression MIST           Base            mass              3.801%
                                 mass_smaller_14 mass              9.338%
mlp               MIST           Base            mass              0.422%
                                 mass_smaller_14 mass              0.564%
random_forest     MIST           Base            mass              0.049%
                                 mass_smaller_14 mass              0.082%
xgboost           MIST           Base            mass              0.178%
                                 mass_smaller_14 mass              0.395%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass               0.02%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_14 mass              0.048%
linear_regression MIST           Base            mass              2.732%
                                 mass_smaller_14 mass              7.035%
mlp               MIST           Base            mass              0.115%
                                 mass_smaller_14 mass              0.323%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.024%
xgboost           MIST           Base            mass              0.033%
                                 mass_smaller_14 mass              0.206%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9976339781841599
                                 mass_smaller_14 mass              0.9998767781112852
KNN               MIST           Base            mass              0.9948902170346177
                                 mass_smaller_14 mass              0.9996846963987984
linear_regression MIST           Base            mass              0.5515679007842895
                                 mass_smaller_14 mass              0.8516537115536522
mlp               MIST           Base            mass              0.9881581645347787
                                 mass_smaller_14 mass              0.9989848962075332
random_forest     MIST           Base            mass              0.9989037560824912
                                 mass_smaller_14 mass              0.9999503530371973
xgboost           MIST           Base            mass              0.9970552947594146
                                 mass_smaller_14 mass              0.9995643018981833

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              50.816%
                                 mass_smaller_14 mass              36.812%
KNN               MIST           Base            mass              48.322%
                                 mass_smaller_14 mass              18.732%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_14 mass              55.541%
mlp               MIST           Base            mass              58.569%
                                 mass_smaller_14 mass              25.383%
random_forest     MIST           Base            mass              32.158%
                                 mass_smaller_14 mass              16.749%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_14 mass              18.006%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 75 : 0.007% / 90 : 0.035% / 95 : 0.118% / 99 : 1.529%
                                 mass_smaller_14 mass                 75 : 0.086% / 90 : 0.275% / 95 : 0.527% / 99 : 1.588%
KNN               MIST           Base            mass                  75 : 0.013% / 90 : 0.07% / 95 : 0.236% / 99 : 2.302%
                                 mass_smaller_14 mass                 75 : 0.171% / 90 : 0.535% / 95 : 0.925% / 99 : 2.329%
linear_regression MIST           Base            mass                75 : 4.654% / 90 : 5.887% / 95 : 7.023% / 99 : 35.239%
                                 mass_smaller_14 mass              75 : 12.551% / 90 : 19.864% / 95 : 25.14% / 99 : 40.338%
mlp               MIST           Base            mass                  75 : 0.242% / 90 : 0.82% / 95 : 1.756% / 99 : 6.292%
                                 mass_smaller_14 mass                 75 : 0.666% / 90 : 1.262% / 95 : 1.857% / 99 : 3.598%
random_forest     MIST           Base            mass                  75 : 0.005% / 90 : 0.026% / 95 : 0.097% / 99 : 1.07%
                                 mass_smaller_14 mass                 75 : 0.071% / 90 : 0.181% / 95 : 0.337% / 99 : 0.998%
xgboost           MIST           Base            mass                  75 : 0.091% / 90 : 0.33% / 95 : 0.726% / 99 : 2.844%
                                 mass_smaller_14 mass                 75 : 0.476% / 90 : 0.948% / 95 : 1.388% / 99 : 2.702%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 0.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
KNN               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
linear_regression MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
mlp               MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
random_forest     MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695
xgboost           MIST           Base            mass               0.0999979840073621 - 298.5447575808816
                                 mass_smaller_14 mass              0.0999979840073621 - 13.998624815474695

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9936340302001091
                                 mass_smaller_14 mass              0.9997590738023714
KNN               MIST           Base            mass              0.9843387655163102
                                 mass_smaller_14 mass              0.9991667805594964
linear_regression MIST           Base            mass              0.2728709030098654
                                 mass_smaller_14 mass               0.703580703577132
mlp               MIST           Base            mass              0.9717157238872854
                                 mass_smaller_14 mass               0.997967880087404
random_forest     MIST           Base            mass              0.9973661987481759
                                 mass_smaller_14 mass              0.9999235468255409
xgboost           MIST           Base            mass              0.9910072956179956
                                 mass_smaller_14 mass              0.9987960913520983

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.703%
                                 mass_smaller_14 mass               0.368%
KNN               MIST           Base            mass               1.103%
                                 mass_smaller_14 mass               0.685%
linear_regression MIST           Base            mass               7.516%
                                 mass_smaller_14 mass              12.911%
mlp               MIST           Base            mass               1.484%
                                 mass_smaller_14 mass               1.069%
random_forest     MIST           Base            mass               0.452%
                                 mass_smaller_14 mass               0.207%
xgboost           MIST           Base            mass               0.836%
                                 mass_smaller_14 mass               0.823%

                                                                       MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.09%
                                 mass_smaller_14 mass               0.122%
KNN               MIST           Base            mass               0.145%
                                 mass_smaller_14 mass               0.222%
linear_regression MIST           Base            mass               4.392%
                                 mass_smaller_14 mass              10.456%
mlp               MIST           Base            mass               0.467%
                                 mass_smaller_14 mass               0.483%
random_forest     MIST           Base            mass               0.056%
                                 mass_smaller_14 mass               0.063%
xgboost           MIST           Base            mass               0.227%
                                 mass_smaller_14 mass                0.46%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.002%
                                 mass_smaller_14 mass               0.03%
KNN               MIST           Base            mass              0.003%
                                 mass_smaller_14 mass              0.051%
linear_regression MIST           Base            mass              3.771%
                                 mass_smaller_14 mass              8.915%
mlp               MIST           Base            mass              0.124%
                                 mass_smaller_14 mass              0.251%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.018%
xgboost           MIST           Base            mass              0.042%
                                 mass_smaller_14 mass              0.228%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9968269721840094
                                 mass_smaller_14 mass              0.9998795329372157
KNN               MIST           Base            mass              0.9924111983284241
                                 mass_smaller_14 mass              0.9995923399848191
linear_regression MIST           Base            mass              0.5343027371731521
                                 mass_smaller_14 mass              0.8532020075802779
mlp               MIST           Base            mass              0.9860617427522443
                                 mass_smaller_14 mass              0.9989847800218492
random_forest     MIST           Base            mass              0.9986840004415223
                                 mass_smaller_14 mass              0.9999617835917853
xgboost           MIST           Base            mass              0.9955145412428942
                                 mass_smaller_14 mass              0.9993979214189108

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              44.154%
                                 mass_smaller_14 mass              36.812%
KNN               MIST           Base            mass              42.445%
                                 mass_smaller_14 mass              18.732%
linear_regression MIST           Base            mass              86.283%
                                 mass_smaller_14 mass              55.541%
mlp               MIST           Base            mass              36.763%
                                 mass_smaller_14 mass              25.383%
random_forest     MIST           Base            mass              27.991%
                                 mass_smaller_14 mass              16.749%
xgboost           MIST           Base            mass              24.445%
                                 mass_smaller_14 mass              18.006%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.01% / 90 : 0.062% / 95 : 0.226% / 99 : 1.993%
                                 mass_smaller_14 mass                 75 : 0.098% / 90 : 0.303% / 95 : 0.532% / 99 : 1.395%
KNN               MIST           Base            mass                 75 : 0.017% / 90 : 0.112% / 95 : 0.345% / 99 : 2.996%
                                 mass_smaller_14 mass                   75 : 0.175% / 90 : 0.5% / 95 : 0.893% / 99 : 2.754%
linear_regression MIST           Base            mass                75 : 5.168% / 90 : 6.205% / 95 : 6.947% / 99 : 34.292%
                                 mass_smaller_14 mass              75 : 14.815% / 90 : 20.33% / 95 : 23.858% / 99 : 35.853%
mlp               MIST           Base            mass                  75 : 0.28% / 90 : 0.962% / 95 : 1.976% / 99 : 6.621%
                                 mass_smaller_14 mass                 75 : 0.534% / 90 : 1.022% / 95 : 1.612% / 99 : 3.326%
random_forest     MIST           Base            mass                 75 : 0.005% / 90 : 0.036% / 95 : 0.139% / 99 : 1.207%
                                 mass_smaller_14 mass                 75 : 0.051% / 90 : 0.141% / 95 : 0.251% / 99 : 0.728%
xgboost           MIST           Base            mass                 75 : 0.129% / 90 : 0.432% / 95 : 0.904% / 99 : 3.697%
                                 mass_smaller_14 mass                  75 : 0.555% / 90 : 1.123% / 95 : 1.66% / 99 : 3.276%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
KNN               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
linear_regression MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
mlp               MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
random_forest     MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449
xgboost           MIST           Base            mass              0.6538581961218565 - 283.72102985530483
                                 mass_smaller_14 mass              0.6542770535966311 - 13.927740111688449

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9992828062113351
                                 mass_smaller_14 mass              0.9999398039293963
KNN               MIST           Base            mass              0.9993836364150782
                                 mass_smaller_14 mass              0.9997767455983123
linear_regression MIST           Base            mass              0.3168817813892185
                                 mass_smaller_14 mass              0.7627584839179414
mlp               MIST           Base            mass               0.990929974425174
                                 mass_smaller_14 mass              0.9986994416645744
random_forest     MIST           Base            mass              0.9997496322236138
                                 mass_smaller_14 mass              0.9999737930935538
xgboost           MIST           Base            mass              0.9988754736593098
                                 mass_smaller_14 mass              0.9997624928648234

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.281%
                                 mass_smaller_14 mass                0.19%
KNN               MIST           Base            mass                0.26%
                                 mass_smaller_14 mass               0.366%
linear_regression MIST           Base            mass                8.67%
                                 mass_smaller_14 mass              11.933%
mlp               MIST           Base            mass                 1.0%
                                 mass_smaller_14 mass               0.896%
random_forest     MIST           Base            mass               0.166%
                                 mass_smaller_14 mass               0.126%
xgboost           MIST           Base            mass               0.352%
                                 mass_smaller_14 mass               0.391%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.021%
                                 mass_smaller_14 mass              0.058%
KNN               MIST           Base            mass              0.034%
                                 mass_smaller_14 mass              0.149%
linear_regression MIST           Base            mass              3.616%
                                 mass_smaller_14 mass              8.073%
mlp               MIST           Base            mass              0.324%
                                 mass_smaller_14 mass              0.578%
random_forest     MIST           Base            mass              0.021%
                                 mass_smaller_14 mass              0.063%
xgboost           MIST           Base            mass              0.104%
                                 mass_smaller_14 mass              0.269%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.0%
                                 mass_smaller_14 mass              0.002%
KNN               MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.038%
linear_regression MIST           Base            mass              1.861%
                                 mass_smaller_14 mass              5.653%
mlp               MIST           Base            mass              0.106%
                                 mass_smaller_14 mass              0.402%
random_forest     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.033%
xgboost           MIST           Base            mass              0.025%
                                 mass_smaller_14 mass              0.179%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9996414671007774
                                 mass_smaller_14 mass              0.9999700313729203
KNN               MIST           Base            mass              0.9996927065174758
                                 mass_smaller_14 mass              0.9998883692148779
linear_regression MIST           Base            mass              0.5956286032810738
                                 mass_smaller_14 mass              0.9184081581407212
mlp               MIST           Base            mass              0.9955996860365472
                                 mass_smaller_14 mass              0.9993909030531274
random_forest     MIST           Base            mass              0.9998754804643019
                                 mass_smaller_14 mass               0.999987052162877
xgboost           MIST           Base            mass              0.9994709362034415
                                 mass_smaller_14 mass              0.9998867034593512

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              37.398%
                                 mass_smaller_14 mass              10.632%
KNN               MIST           Base            mass              13.243%
                                 mass_smaller_14 mass               6.976%
linear_regression MIST           Base            mass              87.305%
                                 mass_smaller_14 mass              53.433%
mlp               MIST           Base            mass              22.957%
                                 mass_smaller_14 mass              12.011%
random_forest     MIST           Base            mass               8.119%
                                 mass_smaller_14 mass               3.642%
xgboost           MIST           Base            mass               13.82%
                                 mass_smaller_14 mass               4.227%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                 75 : 0.002% / 90 : 0.009% / 95 : 0.016% / 99 : 0.267%
                                 mass_smaller_14 mass                 75 : 0.043% / 90 : 0.176% / 95 : 0.262% / 99 : 0.659%
KNN               MIST           Base            mass                 75 : 0.006% / 90 : 0.028% / 95 : 0.057% / 99 : 0.751%
                                 mass_smaller_14 mass                  75 : 0.121% / 90 : 0.415% / 95 : 0.755% / 99 : 1.57%
linear_regression MIST           Base            mass                   75 : 3.97% / 90 : 5.1% / 95 : 8.131% / 99 : 48.667%
                                 mass_smaller_14 mass              75 : 8.994% / 90 : 17.493% / 95 : 30.286% / 99 : 44.672%
mlp               MIST           Base            mass                 75 : 0.204% / 90 : 0.596% / 95 : 1.317% / 99 : 4.578%
                                 mass_smaller_14 mass                 75 : 0.711% / 90 : 1.212% / 95 : 1.757% / 99 : 3.354%
random_forest     MIST           Base            mass                  75 : 0.004% / 90 : 0.009% / 95 : 0.026% / 99 : 0.48%
                                 mass_smaller_14 mass                 75 : 0.076% / 90 : 0.143% / 95 : 0.211% / 99 : 0.515%
xgboost           MIST           Base            mass                 75 : 0.055% / 90 : 0.194% / 95 : 0.467% / 99 : 1.559%
                                 mass_smaller_14 mass                  75 : 0.364% / 90 : 0.621% / 95 : 0.82% / 99 : 1.313%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
KNN               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
linear_regression MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
mlp               MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
random_forest     MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377
xgboost           MIST           Base            mass                0.5484495344916944 - 288.814589557117
                                 mass_smaller_14 mass              0.5453736573627747 - 13.994428587385377

                                                                                   RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.9919676920924657
                                 mass_smaller_14 mass               0.9994652103837574
KNN               MIST           Base            mass               0.9860770182495742
                                 mass_smaller_14 mass               0.9993197080056749
linear_regression MIST           Base            mass              0.38830292902171926
                                 mass_smaller_14 mass               0.7294304975319248
mlp               MIST           Base            mass               0.9593548446204826
                                 mass_smaller_14 mass               0.9973619756891468
random_forest     MIST           Base            mass               0.9949439900825313
                                 mass_smaller_14 mass               0.9997284223560081
xgboost           MIST           Base            mass               0.9944238807426196
                                 mass_smaller_14 mass               0.9992349115882041

                                                                      RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               0.721%
                                 mass_smaller_14 mass               0.553%
KNN               MIST           Base            mass               0.949%
                                 mass_smaller_14 mass               0.627%
linear_regression MIST           Base            mass               6.301%
                                 mass_smaller_14 mass              12.426%
mlp               MIST           Base            mass               1.631%
                                 mass_smaller_14 mass               1.333%
random_forest     MIST           Base            mass               0.572%
                                 mass_smaller_14 mass               0.395%
xgboost           MIST           Base            mass                 0.6%
                                 mass_smaller_14 mass               0.672%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.069%
                                 mass_smaller_14 mass              0.198%
KNN               MIST           Base            mass              0.126%
                                 mass_smaller_14 mass              0.272%
linear_regression MIST           Base            mass              2.762%
                                 mass_smaller_14 mass              8.758%
mlp               MIST           Base            mass              0.475%
                                 mass_smaller_14 mass              0.839%
random_forest     MIST           Base            mass               0.07%
                                 mass_smaller_14 mass              0.173%
xgboost           MIST           Base            mass              0.157%
                                 mass_smaller_14 mass              0.419%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.001%
                                 mass_smaller_14 mass              0.022%
KNN               MIST           Base            mass              0.004%
                                 mass_smaller_14 mass              0.061%
linear_regression MIST           Base            mass              1.595%
                                 mass_smaller_14 mass              5.749%
mlp               MIST           Base            mass              0.115%
                                 mass_smaller_14 mass              0.545%
random_forest     MIST           Base            mass              0.002%
                                 mass_smaller_14 mass              0.044%
xgboost           MIST           Base            mass              0.032%
                                 mass_smaller_14 mass               0.22%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass              0.9959955403728619
                                 mass_smaller_14 mass               0.999733532743571
KNN               MIST           Base            mass              0.9931315041563596
                                 mass_smaller_14 mass              0.9996726034047599
linear_regression MIST           Base            mass              0.6497333100274104
                                 mass_smaller_14 mass              0.9286874399666551
mlp               MIST           Base            mass              0.9801734298207664
                                 mass_smaller_14 mass              0.9987250717515364
random_forest     MIST           Base            mass              0.9975811556691733
                                 mass_smaller_14 mass              0.9998659386279564
xgboost           MIST           Base            mass              0.9972366154162345
                                 mass_smaller_14 mass              0.9996279750905939

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               52.61%
                                 mass_smaller_14 mass              17.875%
KNN               MIST           Base            mass              50.028%
                                 mass_smaller_14 mass              12.229%
linear_regression MIST           Base            mass              87.044%
                                 mass_smaller_14 mass              53.149%
mlp               MIST           Base            mass              60.637%
                                 mass_smaller_14 mass              25.342%
random_forest     MIST           Base            mass              33.293%
                                 mass_smaller_14 mass               9.617%
xgboost           MIST           Base            mass              21.469%
                                 mass_smaller_14 mass              11.967%

                                                                                                                Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass                  75 : 0.008% / 90 : 0.039% / 95 : 0.093% / 99 : 1.61%
                                 mass_smaller_14 mass                 75 : 0.123% / 90 : 0.542% / 95 : 1.113% / 99 : 2.593%
KNN               MIST           Base            mass                   75 : 0.02% / 90 : 0.085% / 95 : 0.29% / 99 : 2.888%
                                 mass_smaller_14 mass                   75 : 0.264% / 90 : 0.813% / 95 : 1.271% / 99 : 2.6%
linear_regression MIST           Base            mass                 75 : 3.153% / 90 : 4.84% / 95 : 7.683% / 99 : 28.543%
                                 mass_smaller_14 mass              75 : 9.665% / 90 : 19.317% / 95 : 29.514% / 99 : 44.616%
mlp               MIST           Base            mass                 75 : 0.241% / 90 : 0.834% / 95 : 1.996% / 99 : 7.733%
                                 mass_smaller_14 mass                 75 : 1.105% / 90 : 1.874% / 95 : 2.514% / 99 : 4.761%
random_forest     MIST           Base            mass                  75 : 0.01% / 90 : 0.037% / 95 : 0.102% / 99 : 1.625%
                                 mass_smaller_14 mass                 75 : 0.163% / 90 : 0.478% / 95 : 0.808% / 99 : 1.802%
xgboost           MIST           Base            mass                 75 : 0.079% / 90 : 0.248% / 95 : 0.643% / 99 : 2.595%
                                 mass_smaller_14 mass                  75 : 0.53% / 90 : 1.078% / 95 : 1.469% / 99 : 2.406%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            mass               24.898207902908325
                                 mass_smaller_14 mass               18.880497217178345
KNN               MIST           Base            mass                 8.37163758277893
                                 mass_smaller_14 mass                 5.27383017539978
linear_regression MIST           Base            mass               0.6336760520935059
                                 mass_smaller_14 mass              0.46092677116394043
mlp               MIST           Base            mass               259.79061460494995
                                 mass_smaller_14 mass                 189.019047498703
random_forest     MIST           Base            mass                343.6629173755646
                                 mass_smaller_14 mass               248.72876453399658
xgboost           MIST           Base            mass               11.712000608444214
                                 mass_smaller_14 mass                8.433841943740845

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on every metric except MAX_ER
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except P99

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors

Random forest : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on MAX_ER and similar on RMSE \
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

MLP : 
- mass_smaller_3 : worse results than Base on every metric
- mass_smaller_14 : worse results than Base on MAE, MedAE and all percentiles except P99, better results on RMSE and MAX_ER\
&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; => worse results for typical predictions but better at predictions with large errors
- mass_smaller_30 : worse results than Base on every metric except MAX_ER

#### Conclusions on mass filtering

mass_smaller_3 is always worse than Base.

If reducing worst-case errors is the priority, mass_smaller_14 is preferable; if average accuracy matters more, Base is better.

mass_smaller_30 is a middle ground between Base and mass_smaller_14 but it does not offer enough improvements to be interesting to use.

#### Best models for the mass parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### Radius parameter

In [7]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_3", "mass_smaller_14", "mass_smaller_30"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
KNN               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
mlp               MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.9974628481553472 - 3.129269620812593
                                 mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997963432259059
                                 mass_smaller_3  radius             0.999866660211663
                                 mass_smaller_14 radius            0.9998290497642414
                                 mass_smaller_30 radius            0.9998192497710287
KNN               MIST           Base            radius            0.9998970891526346
                                 mass_smaller_3  radius            0.9999040702564876
                                 mass_smaller_14 radius            0.9999238365249355
                                 mass_smaller_30 radius            0.9999227649971846
linear_regression MIST           Base            radius            0.9854956623390955
                                 mass_smaller_3  radius            0.9928968443499933
                                 mass_smaller_14 radius            0.9915723548914062
                                 mass_smaller_30 radius            0.9911838669288024
mlp               MIST           Base            radius            0.9923727221026404
                                 mass_smaller_3  radius            0.9991367039903855
                                 mass_smaller_14 radius             0.999136672646969
                                 mass_smaller_30 radius            0.9950540236132825
random_forest     MIST           Base            radius            0.9999434532448489
                                 mass_smaller_3  radius             0.999960084444697
                                 mass_smaller_14 radius            0.9999564181903926
                                 mass_smaller_30 radius            0.9999562627341628
xgboost           MIST           Base            radius            0.9996020484794627
                                 mass_smaller_3  radius            0.9998348191009966
                                 mass_smaller_14 radius            0.9997464415773465
                                 mass_smaller_30 radius            0.9996970259826488

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.255%
                                 mass_smaller_3  radius            0.213%
                                 mass_smaller_14 radius            0.226%
                                 mass_smaller_30 radius            0.232%
KNN               MIST           Base            radius            0.181%
                                 mass_smaller_3  radius            0.181%
                                 mass_smaller_14 radius            0.151%
                                 mass_smaller_30 radius            0.151%
linear_regression MIST           Base            radius            2.154%
                                 mass_smaller_3  radius            1.558%
                                 mass_smaller_14 radius            1.586%
                                 mass_smaller_30 radius            1.617%
mlp               MIST           Base            radius            1.593%
                                 mass_smaller_3  radius            0.588%
                                 mass_smaller_14 radius            0.537%
                                 mass_smaller_30 radius            1.476%
random_forest     MIST           Base            radius            0.134%
                                 mass_smaller_3  radius            0.117%
                                 mass_smaller_14 radius            0.114%
                                 mass_smaller_30 radius            0.114%
xgboost           MIST           Base            radius            0.357%
                                 mass_smaller_3  radius            0.238%
                                 mass_smaller_14 radius            0.275%
                                 mass_smaller_30 radius              0.3%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.142%
                                 mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.131%
                                 mass_smaller_30 radius            0.132%
KNN               MIST           Base            radius            0.102%
                                 mass_smaller_3  radius            0.108%
                                 mass_smaller_14 radius            0.093%
                                 mass_smaller_30 radius            0.093%
linear_regression MIST           Base            radius            1.569%
                                 mass_smaller_3  radius             1.17%
                                 mass_smaller_14 radius            1.206%
                                 mass_smaller_30 radius            1.231%
mlp               MIST           Base            radius            1.218%
                                 mass_smaller_3  radius            0.404%
                                 mass_smaller_14 radius            0.384%
                                 mass_smaller_30 radius             1.13%
random_forest     MIST           Base            radius            0.065%
                                 mass_smaller_3  radius            0.053%
                                 mass_smaller_14 radius             0.06%
                                 mass_smaller_30 radius            0.058%
xgboost           MIST           Base            radius            0.258%
                                 mass_smaller_3  radius            0.161%
                                 mass_smaller_14 radius            0.199%
                                 mass_smaller_30 radius            0.219%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.082%
                                 mass_smaller_3  radius            0.066%
                                 mass_smaller_14 radius            0.077%
                                 mass_smaller_30 radius            0.078%
KNN               MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.068%
                                 mass_smaller_14 radius            0.062%
                                 mass_smaller_30 radius            0.061%
linear_regression MIST           Base            radius            1.113%
                                 mass_smaller_3  radius            0.887%
                                 mass_smaller_14 radius            0.976%
                                 mass_smaller_30 radius            0.983%
mlp               MIST           Base            radius            0.968%
                                 mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.306%
                                 mass_smaller_30 radius             0.86%
random_forest     MIST           Base            radius            0.032%
                                 mass_smaller_3  radius            0.026%
                                 mass_smaller_14 radius            0.031%
                                 mass_smaller_30 radius             0.03%
xgboost           MIST           Base            radius            0.197%
                                 mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.153%
                                 mass_smaller_30 radius            0.169%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998982041053214
                                 mass_smaller_3  radius            0.9999333298626585
                                 mass_smaller_14 radius            0.9999145940186054
                                 mass_smaller_30 radius            0.9999096635705038
KNN               MIST           Base            radius            0.9999485752530637
                                 mass_smaller_3  radius            0.9999520800077348
                                 mass_smaller_14 radius            0.9999619536912048
                                 mass_smaller_30 radius            0.9999614086282542
linear_regression MIST           Base            radius            0.9927213417365519
                                 mass_smaller_3  radius            0.9964420928232931
                                 mass_smaller_14 radius            0.9957772616862719
                                 mass_smaller_30 radius            0.9955821748750935
mlp               MIST           Base            radius            0.9961795022934663
                                 mass_smaller_3  radius            0.9995738143553161
                                 mass_smaller_14 radius            0.9995714386703022
                                 mass_smaller_30 radius            0.9975589823528184
random_forest     MIST           Base            radius            0.9999717265543759
                                 mass_smaller_3  radius            0.9999800420415123
                                 mass_smaller_14 radius            0.9999782166433258
                                 mass_smaller_30 radius            0.9999781350071537
xgboost           MIST           Base            radius            0.9998010225765576
                                 mass_smaller_3  radius             0.999917407540224
                                 mass_smaller_14 radius            0.9998732248486286
                                 mass_smaller_30 radius            0.9998485109640335

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.591%
                                 mass_smaller_3  radius             4.519%
                                 mass_smaller_14 radius            10.289%
                                 mass_smaller_30 radius            17.115%
KNN               MIST           Base            radius             7.445%
                                 mass_smaller_3  radius             5.987%
                                 mass_smaller_14 radius             5.056%
                                 mass_smaller_30 radius             6.014%
linear_regression MIST           Base            radius            12.724%
                                 mass_smaller_3  radius            10.931%
                                 mass_smaller_14 radius            11.805%
                                 mass_smaller_30 radius            12.019%
mlp               MIST           Base            radius            14.074%
                                 mass_smaller_3  radius            10.377%
                                 mass_smaller_14 radius             11.26%
                                 mass_smaller_30 radius            12.688%
random_forest     MIST           Base            radius             8.676%
                                 mass_smaller_3  radius             3.915%
                                 mass_smaller_14 radius             3.502%
                                 mass_smaller_30 radius             9.954%
xgboost           MIST           Base            radius            11.866%
                                 mass_smaller_3  radius             5.076%
                                 mass_smaller_14 radius             5.546%
                                 mass_smaller_30 radius             6.672%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            75 : 0.175% / 90 : 0.315% / 95 : 0.443% / 99 : 0.975%
                                 mass_smaller_3  radius            75 : 0.149% / 90 : 0.294% / 95 : 0.373% / 99 : 0.762%
                                 mass_smaller_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
                                 mass_smaller_30 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.404% / 99 : 0.866%
KNN               MIST           Base            radius            75 : 0.124% / 90 : 0.223% / 95 : 0.309% / 99 : 0.655%
                                 mass_smaller_3  radius             75 : 0.135% / 90 : 0.24% / 95 : 0.327% / 99 : 0.629%
                                 mass_smaller_14 radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
                                 mass_smaller_30 radius            75 : 0.118% / 90 : 0.208% / 95 : 0.278% / 99 : 0.526%
linear_regression MIST           Base            radius            75 : 2.171% / 90 : 3.377% / 95 : 4.254% / 99 : 7.281%
                                 mass_smaller_3  radius             75 : 1.64% / 90 : 2.621% / 95 : 3.242% / 99 : 4.505%
                                 mass_smaller_14 radius             75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
                                 mass_smaller_30 radius            75 : 1.822% / 90 : 2.598% / 95 : 3.113% / 99 : 4.567%
mlp               MIST           Base            radius             75 : 1.701% / 90 : 2.581% / 95 : 3.181% / 99 : 4.68%
                                 mass_smaller_3  radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                                 mass_smaller_14 radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
                                 mass_smaller_30 radius            75 : 1.604% / 90 : 2.511% / 95 : 3.019% / 99 : 4.046%
random_forest     MIST           Base            radius            75 : 0.075% / 90 : 0.152% / 95 : 0.228% / 99 : 0.499%
                                 mass_smaller_3  radius             75 : 0.06% / 90 : 0.119% / 95 : 0.175% / 99 : 0.395%
                                 mass_smaller_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
                                 mass_smaller_30 radius            75 : 0.069% / 90 : 0.136% / 95 : 0.199% / 99 : 0.412%
xgboost           MIST           Base            radius            75 : 0.354% / 90 : 0.546% / 95 : 0.692% / 99 : 1.079%
                                 mass_smaller_3  radius             75 : 0.214% / 90 : 0.34% / 95 : 0.441% / 99 : 0.747%
                                 mass_smaller_14 radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%
                                 mass_smaller_30 radius            75 : 0.304% / 90 : 0.467% / 95 : 0.583% / 99 : 0.854%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
KNN               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
linear_regression MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
mlp               MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
random_forest     MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227
xgboost           MIST           Base            radius            -0.9974628481553472 - 3.0827540579576227
                                 mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
                                 mass_smaller_30 radius            -0.9974628481553472 - 3.0827540579576227

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9997790154053315
                                 mass_smaller_3  radius            0.9998249631057525
                                 mass_smaller_14 radius            0.9997880404019214
                                 mass_smaller_30 radius            0.9997969300603281
KNN               MIST           Base            radius            0.9998333563537635
                                 mass_smaller_3  radius            0.9996571642468787
                                 mass_smaller_14 radius            0.9998255884455621
                                 mass_smaller_30 radius            0.9998699911918713
linear_regression MIST           Base            radius            0.9778146729622458
                                 mass_smaller_3  radius            0.9753521021495244
                                 mass_smaller_14 radius            0.9830496323087852
                                 mass_smaller_30 radius            0.9862122881365466
mlp               MIST           Base            radius            0.9874097628400822
                                 mass_smaller_3  radius            0.9983513710056814
                                 mass_smaller_14 radius            0.9983627542851781
                                 mass_smaller_30 radius            0.9901288111552154
random_forest     MIST           Base            radius            0.9999465508573717
                                 mass_smaller_3  radius            0.9999678953910232
                                 mass_smaller_14 radius            0.9999534137978472
                                 mass_smaller_30 radius            0.9999559178590984
xgboost           MIST           Base            radius            0.9994380170169319
                                 mass_smaller_3  radius            0.9996075937684589
                                 mass_smaller_14 radius            0.9995117695213523
                                 mass_smaller_30 radius            0.9995381873053741

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.208%
                                 mass_smaller_3  radius            0.239%
                                 mass_smaller_14 radius             0.15%
                                 mass_smaller_30 radius            0.177%
KNN               MIST           Base            radius             0.18%
                                 mass_smaller_3  radius            0.335%
                                 mass_smaller_14 radius            0.136%
                                 mass_smaller_30 radius            0.141%
linear_regression MIST           Base            radius            2.083%
                                 mass_smaller_3  radius             2.87%
                                 mass_smaller_14 radius            1.353%
                                 mass_smaller_30 radius             1.46%
mlp               MIST           Base            radius            1.594%
                                 mass_smaller_3  radius             0.92%
                                 mass_smaller_14 radius            0.441%
                                 mass_smaller_30 radius            1.528%
random_forest     MIST           Base            radius            0.102%
                                 mass_smaller_3  radius            0.103%
                                 mass_smaller_14 radius            0.071%
                                 mass_smaller_30 radius            0.082%
xgboost           MIST           Base            radius            0.331%
                                 mass_smaller_3  radius            0.358%
                                 mass_smaller_14 radius            0.228%
                                 mass_smaller_30 radius            0.266%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.113%
                                 mass_smaller_3  radius            0.152%
                                 mass_smaller_14 radius            0.089%
                                 mass_smaller_30 radius            0.098%
KNN               MIST           Base            radius            0.105%
                                 mass_smaller_3  radius            0.219%
                                 mass_smaller_14 radius             0.09%
                                 mass_smaller_30 radius            0.092%
linear_regression MIST           Base            radius            1.628%
                                 mass_smaller_3  radius            2.086%
                                 mass_smaller_14 radius            1.037%
                                 mass_smaller_30 radius            1.138%
mlp               MIST           Base            radius            1.213%
                                 mass_smaller_3  radius            0.672%
                                 mass_smaller_14 radius            0.346%
                                 mass_smaller_30 radius            1.163%
random_forest     MIST           Base            radius            0.051%
                                 mass_smaller_3  radius            0.063%
                                 mass_smaller_14 radius             0.04%
                                 mass_smaller_30 radius            0.043%
xgboost           MIST           Base            radius            0.244%
                                 mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.174%
                                 mass_smaller_30 radius            0.202%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.064%
                                 mass_smaller_3  radius            0.101%
                                 mass_smaller_14 radius            0.056%
                                 mass_smaller_30 radius            0.059%
KNN               MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.136%
                                 mass_smaller_14 radius            0.058%
                                 mass_smaller_30 radius             0.06%
linear_regression MIST           Base            radius            1.286%
                                 mass_smaller_3  radius            1.579%
                                 mass_smaller_14 radius            0.829%
                                 mass_smaller_30 radius            0.922%
mlp               MIST           Base            radius            0.964%
                                 mass_smaller_3  radius            0.467%
                                 mass_smaller_14 radius            0.292%
                                 mass_smaller_30 radius            0.874%
random_forest     MIST           Base            radius            0.025%
                                 mass_smaller_3  radius            0.039%
                                 mass_smaller_14 radius            0.022%
                                 mass_smaller_30 radius            0.023%
xgboost           MIST           Base            radius            0.184%
                                 mass_smaller_3  radius            0.214%
                                 mass_smaller_14 radius            0.136%
                                 mass_smaller_30 radius            0.156%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998895445736318
                                 mass_smaller_3  radius            0.9999125211077539
                                 mass_smaller_14 radius            0.9998940164221873
                                 mass_smaller_30 radius             0.999898462338922
KNN               MIST           Base            radius            0.9999169942116342
                                 mass_smaller_3  radius             0.999830888291084
                                 mass_smaller_14 radius            0.9999135578590763
                                 mass_smaller_30 radius            0.9999353240819183
linear_regression MIST           Base            radius            0.9888944199376599
                                 mass_smaller_3  radius            0.9879836947112961
                                 mass_smaller_14 radius            0.9914885941715924
                                 mass_smaller_30 radius            0.9930892072248287
mlp               MIST           Base            radius            0.9936897796640443
                                 mass_smaller_3  radius            0.9992197462781777
                                 mass_smaller_14 radius            0.9991810430555029
                                 mass_smaller_30 radius             0.995207168464403
random_forest     MIST           Base            radius            0.9999733173582267
                                 mass_smaller_3  radius            0.9999840579307431
                                 mass_smaller_14 radius            0.9999767231025315
                                 mass_smaller_30 radius            0.9999779588394017
xgboost           MIST           Base            radius            0.9997190014385369
                                 mass_smaller_3  radius            0.9998037782605148
                                 mass_smaller_14 radius            0.9997558778235092
                                 mass_smaller_30 radius            0.9997690783741953

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.724%
                                 mass_smaller_3  radius             4.663%
                                 mass_smaller_14 radius             7.812%
                                 mass_smaller_30 radius            17.312%
KNN               MIST           Base            radius             3.779%
                                 mass_smaller_3  radius             5.368%
                                 mass_smaller_14 radius             1.439%
                                 mass_smaller_30 radius             1.762%
linear_regression MIST           Base            radius            11.227%
                                 mass_smaller_3  radius            12.801%
                                 mass_smaller_14 radius             5.381%
                                 mass_smaller_30 radius             5.029%
mlp               MIST           Base            radius            10.023%
                                 mass_smaller_3  radius             3.953%
                                 mass_smaller_14 radius             4.054%
                                 mass_smaller_30 radius             6.651%
random_forest     MIST           Base            radius             8.775%
                                 mass_smaller_3  radius             2.464%
                                 mass_smaller_14 radius             3.502%
                                 mass_smaller_30 radius            10.068%
xgboost           MIST           Base            radius              3.33%
                                 mass_smaller_3  radius             6.229%
                                 mass_smaller_14 radius             1.596%
                                 mass_smaller_30 radius             2.296%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.131% / 90 : 0.252% / 95 : 0.372% / 99 : 0.797%
                                 mass_smaller_3  radius              75 : 0.199% / 90 : 0.324% / 95 : 0.448% / 99 : 0.89%
                                 mass_smaller_14 radius             75 : 0.112% / 90 : 0.197% / 95 : 0.278% / 99 : 0.584%
                                 mass_smaller_30 radius             75 : 0.119% / 90 : 0.218% / 95 : 0.307% / 99 : 0.658%
KNN               MIST           Base            radius             75 : 0.127% / 90 : 0.234% / 95 : 0.332% / 99 : 0.647%
                                 mass_smaller_3  radius             75 : 0.275% / 90 : 0.515% / 95 : 0.723% / 99 : 1.238%
                                 mass_smaller_14 radius             75 : 0.113% / 90 : 0.205% / 95 : 0.285% / 99 : 0.514%
                                 mass_smaller_30 radius             75 : 0.116% / 90 : 0.211% / 95 : 0.291% / 99 : 0.531%
linear_regression MIST           Base            radius              75 : 2.358% / 90 : 3.301% / 95 : 3.855% / 99 : 6.14%
                                 mass_smaller_3  radius            75 : 2.801% / 90 : 4.245% / 95 : 5.738% / 99 : 10.075%
                                 mass_smaller_14 radius             75 : 1.559% / 90 : 2.251% / 95 : 2.664% / 99 : 3.814%
                                 mass_smaller_30 radius              75 : 1.74% / 90 : 2.487% / 95 : 2.896% / 99 : 3.595%
mlp               MIST           Base            radius             75 : 1.668% / 90 : 2.575% / 95 : 3.252% / 99 : 4.813%
                                 mass_smaller_3  radius               75 : 0.963% / 90 : 1.592% / 95 : 1.971% / 99 : 2.7%
                                 mass_smaller_14 radius             75 : 0.488% / 90 : 0.697% / 95 : 0.836% / 99 : 1.194%
                                 mass_smaller_30 radius             75 : 1.671% / 90 : 2.569% / 95 : 3.191% / 99 : 4.273%
random_forest     MIST           Base            radius             75 : 0.057% / 90 : 0.119% / 95 : 0.184% / 99 : 0.404%
                                 mass_smaller_3  radius             75 : 0.081% / 90 : 0.145% / 95 : 0.202% / 99 : 0.373%
                                 mass_smaller_14 radius             75 : 0.047% / 90 : 0.092% / 95 : 0.136% / 99 : 0.278%
                                 mass_smaller_30 radius              75 : 0.05% / 90 : 0.099% / 95 : 0.149% / 99 : 0.314%
xgboost           MIST           Base            radius             75 : 0.334% / 90 : 0.527% / 95 : 0.675% / 99 : 1.035%
                                 mass_smaller_3  radius             75 : 0.382% / 90 : 0.581% / 95 : 0.732% / 99 : 1.059%
                                 mass_smaller_14 radius             75 : 0.243% / 90 : 0.373% / 95 : 0.467% / 99 : 0.669%
                                 mass_smaller_30 radius              75 : 0.283% / 90 : 0.438% / 95 : 0.549% / 99 : 0.78%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
KNN               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
linear_regression MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
mlp               MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
random_forest     MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969
xgboost           MIST           Base            radius             0.0919862423867022 - 2.891706235288321
                                 mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
                                 mass_smaller_30 radius             0.0909920840275404 - 2.900376516729969

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9996013815341348
                                 mass_smaller_3  radius            0.9995465768676972
                                 mass_smaller_14 radius            0.9995039197290129
                                 mass_smaller_30 radius            0.9995266839683316
KNN               MIST           Base            radius            0.9999055166815642
                                 mass_smaller_3  radius            0.9998807428184813
                                 mass_smaller_14 radius            0.9998943160073213
                                 mass_smaller_30 radius            0.9998962596584994
linear_regression MIST           Base            radius            0.9679744997103377
                                 mass_smaller_3  radius            0.9833773452801731
                                 mass_smaller_14 radius            0.9806856109752665
                                 mass_smaller_30 radius            0.9801561070378554
mlp               MIST           Base            radius             0.984995693437375
                                 mass_smaller_3  radius            0.9978060724763279
                                 mass_smaller_14 radius             0.998723350903017
                                 mass_smaller_30 radius            0.9906433853956087
random_forest     MIST           Base            radius            0.9999326234217092
                                 mass_smaller_3  radius            0.9999301508060892
                                 mass_smaller_14 radius            0.9999185082513201
                                 mass_smaller_30 radius            0.9999308463547795
xgboost           MIST           Base            radius            0.9992306813494213
                                 mass_smaller_3  radius            0.9995508512748904
                                 mass_smaller_14 radius            0.9994208286577492
                                 mass_smaller_30 radius            0.9992951333672936

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.35%
                                 mass_smaller_3  radius            0.437%
                                 mass_smaller_14 radius            0.373%
                                 mass_smaller_30 radius            0.352%
KNN               MIST           Base            radius             0.17%
                                 mass_smaller_3  radius            0.224%
                                 mass_smaller_14 radius            0.172%
                                 mass_smaller_30 radius            0.165%
linear_regression MIST           Base            radius            3.158%
                                 mass_smaller_3  radius            2.771%
                                 mass_smaller_14 radius            2.381%
                                 mass_smaller_30 radius            2.313%
mlp               MIST           Base            radius            2.256%
                                 mass_smaller_3  radius            1.108%
                                 mass_smaller_14 radius            0.599%
                                 mass_smaller_30 radius            2.159%
random_forest     MIST           Base            radius            0.145%
                                 mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.153%
                                 mass_smaller_30 radius            0.136%
xgboost           MIST           Base            radius            0.487%
                                 mass_smaller_3  radius            0.435%
                                 mass_smaller_14 radius            0.404%
                                 mass_smaller_30 radius             0.43%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.241%
                                 mass_smaller_3  radius            0.322%
                                 mass_smaller_14 radius            0.264%
                                 mass_smaller_30 radius            0.247%
KNN               MIST           Base            radius            0.123%
                                 mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.131%
                                 mass_smaller_30 radius            0.124%
linear_regression MIST           Base            radius            2.062%
                                 mass_smaller_3  radius            2.218%
                                 mass_smaller_14 radius            1.855%
                                 mass_smaller_30 radius            1.748%
mlp               MIST           Base            radius            1.756%
                                 mass_smaller_3  radius            0.799%
                                 mass_smaller_14 radius            0.473%
                                 mass_smaller_30 radius             1.71%
random_forest     MIST           Base            radius            0.096%
                                 mass_smaller_3  radius             0.12%
                                 mass_smaller_14 radius            0.105%
                                 mass_smaller_30 radius            0.093%
xgboost           MIST           Base            radius            0.381%
                                 mass_smaller_3  radius            0.333%
                                 mass_smaller_14 radius            0.314%
                                 mass_smaller_30 radius            0.336%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.186%
                                 mass_smaller_3  radius            0.263%
                                 mass_smaller_14 radius            0.217%
                                 mass_smaller_30 radius            0.199%
KNN               MIST           Base            radius            0.091%
                                 mass_smaller_3  radius            0.137%
                                 mass_smaller_14 radius            0.103%
                                 mass_smaller_30 radius            0.094%
linear_regression MIST           Base            radius            1.212%
                                 mass_smaller_3  radius            1.872%
                                 mass_smaller_14 radius            1.509%
                                 mass_smaller_30 radius            1.347%
mlp               MIST           Base            radius            1.419%
                                 mass_smaller_3  radius            0.527%
                                 mass_smaller_14 radius            0.389%
                                 mass_smaller_30 radius            1.365%
random_forest     MIST           Base            radius            0.063%
                                 mass_smaller_3  radius            0.083%
                                 mass_smaller_14 radius            0.072%
                                 mass_smaller_30 radius            0.063%
xgboost           MIST           Base            radius            0.313%
                                 mass_smaller_3  radius            0.266%
                                 mass_smaller_14 radius            0.255%
                                 mass_smaller_30 radius            0.276%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9998018770327872
                                 mass_smaller_3  radius            0.9997733155946078
                                 mass_smaller_14 radius            0.9997540306645297
                                 mass_smaller_30 radius            0.9997651809159842
KNN               MIST           Base            radius            0.9999527572442021
                                 mass_smaller_3  radius            0.9999404528865401
                                 mass_smaller_14 radius            0.9999471831409968
                                 mass_smaller_30 radius            0.9999481574096413
linear_regression MIST           Base            radius            0.9838665758685889
                                 mass_smaller_3  radius             0.993268227885979
                                 mass_smaller_14 radius            0.9909797904600514
                                 mass_smaller_30 radius            0.9907926454524565
mlp               MIST           Base            radius             0.992574201430493
                                 mass_smaller_3  radius            0.9989117384154471
                                 mass_smaller_14 radius            0.9993643661222952
                                 mass_smaller_30 radius            0.9953134588767328
random_forest     MIST           Base            radius             0.999966988493253
                                 mass_smaller_3  radius            0.9999650748236046
                                 mass_smaller_14 radius            0.9999605620655518
                                 mass_smaller_30 radius            0.9999665535016122
xgboost           MIST           Base            radius            0.9996159124585666
                                 mass_smaller_3  radius            0.9997754108047239
                                 mass_smaller_14 radius            0.9997106655945553
                                 mass_smaller_30 radius            0.9996484433732039

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             6.585%
                                 mass_smaller_3  radius             5.347%
                                 mass_smaller_14 radius              15.1%
                                 mass_smaller_30 radius             7.242%
KNN               MIST           Base            radius             2.759%
                                 mass_smaller_3  radius             3.109%
                                 mass_smaller_14 radius             2.265%
                                 mass_smaller_30 radius             1.941%
linear_regression MIST           Base            radius            16.177%
                                 mass_smaller_3  radius             7.833%
                                 mass_smaller_14 radius             8.961%
                                 mass_smaller_30 radius             9.351%
mlp               MIST           Base            radius            13.166%
                                 mass_smaller_3  radius             4.322%
                                 mass_smaller_14 radius              4.45%
                                 mass_smaller_30 radius             8.692%
random_forest     MIST           Base            radius             3.256%
                                 mass_smaller_3  radius             2.008%
                                 mass_smaller_14 radius             2.388%
                                 mass_smaller_30 radius             1.795%
xgboost           MIST           Base            radius              2.63%
                                 mass_smaller_3  radius             2.523%
                                 mass_smaller_14 radius             2.615%
                                 mass_smaller_30 radius             2.329%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius              75 : 0.324% / 90 : 0.48% / 95 : 0.593% / 99 : 1.125%
                                 mass_smaller_3  radius             75 : 0.491% / 90 : 0.627% / 95 : 0.747% / 99 : 1.318%
                                 mass_smaller_14 radius             75 : 0.354% / 90 : 0.499% / 95 : 0.622% / 99 : 1.155%
                                 mass_smaller_30 radius             75 : 0.335% / 90 : 0.484% / 95 : 0.594% / 99 : 1.105%
KNN               MIST           Base            radius             75 : 0.168% / 90 : 0.276% / 95 : 0.349% / 99 : 0.519%
                                 mass_smaller_3  radius              75 : 0.236% / 90 : 0.368% / 95 : 0.449% / 99 : 0.63%
                                 mass_smaller_14 radius             75 : 0.178% / 90 : 0.285% / 95 : 0.354% / 99 : 0.494%
                                 mass_smaller_30 radius             75 : 0.169% / 90 : 0.274% / 95 : 0.342% / 99 : 0.482%
linear_regression MIST           Base            radius            75 : 2.625% / 90 : 5.047% / 95 : 6.932% / 99 : 12.502%
                                 mass_smaller_3  radius             75 : 3.379% / 90 : 4.724% / 95 : 5.395% / 99 : 6.276%
                                 mass_smaller_14 radius             75 : 2.614% / 90 : 3.907% / 95 : 4.838% / 99 : 6.671%
                                 mass_smaller_30 radius              75 : 2.553% / 90 : 3.763% / 95 : 4.72% / 99 : 6.837%
mlp               MIST           Base            radius             75 : 2.537% / 90 : 3.715% / 95 : 4.431% / 99 : 6.101%
                                 mass_smaller_3  radius              75 : 1.086% / 90 : 2.065% / 95 : 2.465% / 99 : 3.16%
                                 mass_smaller_14 radius             75 : 0.684% / 90 : 0.991% / 95 : 1.184% / 99 : 1.535%
                                 mass_smaller_30 radius             75 : 2.439% / 90 : 3.767% / 95 : 4.396% / 99 : 5.328%
random_forest     MIST           Base            radius              75 : 0.128% / 90 : 0.22% / 95 : 0.296% / 99 : 0.502%
                                 mass_smaller_3  radius             75 : 0.164% / 90 : 0.272% / 95 : 0.354% / 99 : 0.554%
                                 mass_smaller_14 radius             75 : 0.142% / 90 : 0.239% / 95 : 0.315% / 99 : 0.514%
                                 mass_smaller_30 radius              75 : 0.125% / 90 : 0.212% / 95 : 0.28% / 99 : 0.459%
xgboost           MIST           Base            radius             75 : 0.541% / 90 : 0.793% / 95 : 0.966% / 99 : 1.343%
                                 mass_smaller_3  radius              75 : 0.463% / 90 : 0.706% / 95 : 0.879% / 99 : 1.28%
                                 mass_smaller_14 radius              75 : 0.448% / 90 : 0.66% / 95 : 0.808% / 99 : 1.134%
                                 mass_smaller_30 radius             75 : 0.478% / 90 : 0.705% / 95 : 0.861% / 99 : 1.184%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

Results for the phase category with a value of 3.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
KNN               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
linear_regression MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
mlp               MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
random_forest     MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007
xgboost           MIST           Base            radius             -0.3445863859219699 - 3.129269620812593
                                 mass_smaller_3  radius             0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius              0.0758282047744788 - 3.063523621241276
                                 mass_smaller_30 radius            -0.3461949526594047 - 3.1297545143214007

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             0.999266684393612
                                 mass_smaller_3  radius            0.9992381885703833
                                 mass_smaller_14 radius            0.9993395139862439
                                 mass_smaller_30 radius            0.9993527873099591
KNN               MIST           Base            radius            0.9996720394056582
                                 mass_smaller_3  radius            0.9994853264493573
                                 mass_smaller_14 radius            0.9997229263417253
                                 mass_smaller_30 radius            0.9997331093747082
linear_regression MIST           Base            radius              0.96988742831239
                                 mass_smaller_3  radius            0.9740128136920825
                                 mass_smaller_14 radius            0.9746821269484942
                                 mass_smaller_30 radius             0.975405297113159
mlp               MIST           Base            radius            0.9847763915139012
                                 mass_smaller_3  radius            0.9952899598276022
                                 mass_smaller_14 radius            0.9970644512745905
                                 mass_smaller_30 radius            0.9902981482812612
random_forest     MIST           Base            radius            0.9997339847238751
                                 mass_smaller_3  radius            0.9996570039158864
                                 mass_smaller_14 radius             0.999774074221781
                                 mass_smaller_30 radius            0.9997907782006465
xgboost           MIST           Base            radius            0.9989178719473903
                                 mass_smaller_3  radius            0.9991584798800517
                                 mass_smaller_14 radius            0.9991636868686137
                                 mass_smaller_30 radius            0.9991259310343945

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.447%
                                 mass_smaller_3  radius            0.478%
                                 mass_smaller_14 radius            0.456%
                                 mass_smaller_30 radius              0.4%
KNN               MIST           Base            radius            0.299%
                                 mass_smaller_3  radius            0.393%
                                 mass_smaller_14 radius            0.295%
                                 mass_smaller_30 radius            0.257%
linear_regression MIST           Base            radius            2.866%
                                 mass_smaller_3  radius            2.794%
                                 mass_smaller_14 radius            2.821%
                                 mass_smaller_30 radius            2.462%
mlp               MIST           Base            radius            2.046%
                                 mass_smaller_3  radius            1.188%
                                 mass_smaller_14 radius            1.158%
                                 mass_smaller_30 radius            1.641%
random_forest     MIST           Base            radius             0.27%
                                 mass_smaller_3  radius            0.321%
                                 mass_smaller_14 radius            0.268%
                                 mass_smaller_30 radius            0.228%
xgboost           MIST           Base            radius            0.543%
                                 mass_smaller_3  radius            0.503%
                                 mass_smaller_14 radius            0.514%
                                 mass_smaller_30 radius            0.465%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.232%
                                 mass_smaller_3  radius             0.23%
                                 mass_smaller_14 radius            0.243%
                                 mass_smaller_30 radius            0.215%
KNN               MIST           Base            radius            0.146%
                                 mass_smaller_3  radius            0.188%
                                 mass_smaller_14 radius             0.15%
                                 mass_smaller_30 radius            0.131%
linear_regression MIST           Base            radius            2.006%
                                 mass_smaller_3  radius            2.203%
                                 mass_smaller_14 radius            2.185%
                                 mass_smaller_30 radius            1.883%
mlp               MIST           Base            radius            1.548%
                                 mass_smaller_3  radius            0.821%
                                 mass_smaller_14 radius            0.789%
                                 mass_smaller_30 radius            1.216%
random_forest     MIST           Base            radius            0.128%
                                 mass_smaller_3  radius            0.138%
                                 mass_smaller_14 radius            0.134%
                                 mass_smaller_30 radius            0.113%
xgboost           MIST           Base            radius            0.361%
                                 mass_smaller_3  radius              0.3%
                                 mass_smaller_14 radius             0.34%
                                 mass_smaller_30 radius             0.31%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.116%
                                 mass_smaller_3  radius            0.106%
                                 mass_smaller_14 radius             0.12%
                                 mass_smaller_30 radius             0.11%
KNN               MIST           Base            radius            0.076%
                                 mass_smaller_3  radius            0.093%
                                 mass_smaller_14 radius            0.082%
                                 mass_smaller_30 radius            0.072%
linear_regression MIST           Base            radius            1.329%
                                 mass_smaller_3  radius            1.885%
                                 mass_smaller_14 radius            1.865%
                                 mass_smaller_30 radius            1.541%
mlp               MIST           Base            radius             1.21%
                                 mass_smaller_3  radius             0.61%
                                 mass_smaller_14 radius            0.609%
                                 mass_smaller_30 radius            0.911%
random_forest     MIST           Base            radius            0.057%
                                 mass_smaller_3  radius            0.057%
                                 mass_smaller_14 radius            0.064%
                                 mass_smaller_30 radius            0.054%
xgboost           MIST           Base            radius            0.262%
                                 mass_smaller_3  radius            0.193%
                                 mass_smaller_14 radius            0.245%
                                 mass_smaller_30 radius            0.227%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            0.9996333392274228
                                 mass_smaller_3  radius            0.9996192777071335
                                 mass_smaller_14 radius            0.9996699530747309
                                 mass_smaller_30 radius            0.9996764243680272
KNN               MIST           Base            radius            0.9998360691463095
                                 mass_smaller_3  radius            0.9997430849980539
                                 mass_smaller_14 radius            0.9998615008366036
                                 mass_smaller_30 radius              0.99986658819855
linear_regression MIST           Base            radius            0.9849992743688404
                                 mass_smaller_3  radius            0.9886235406128182
                                 mass_smaller_14 radius            0.9873693027486672
                                 mass_smaller_30 radius            0.9876332691760843
mlp               MIST           Base            radius             0.992384420506142
                                 mass_smaller_3  radius            0.9976629398298685
                                 mass_smaller_14 radius            0.9985438860810399
                                 mass_smaller_30 radius            0.9951504215106092
random_forest     MIST           Base            radius            0.9998670249575315
                                 mass_smaller_3  radius            0.9998285901743722
                                 mass_smaller_14 radius            0.9998870342476956
                                 mass_smaller_30 radius            0.9998953876885145
xgboost           MIST           Base            radius            0.9994588839474633
                                 mass_smaller_3  radius             0.999579231894782
                                 mass_smaller_14 radius            0.9995818580147785
                                 mass_smaller_30 radius            0.9995630100375634

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius            11.071%
                                 mass_smaller_3  radius             6.307%
                                 mass_smaller_14 radius             5.599%
                                 mass_smaller_30 radius             5.599%
KNN               MIST           Base            radius             8.844%
                                 mass_smaller_3  radius             8.357%
                                 mass_smaller_14 radius             6.904%
                                 mass_smaller_30 radius             7.141%
linear_regression MIST           Base            radius            15.116%
                                 mass_smaller_3  radius            15.259%
                                 mass_smaller_14 radius            16.119%
                                 mass_smaller_30 radius            14.271%
mlp               MIST           Base            radius             16.72%
                                 mass_smaller_3  radius            14.485%
                                 mass_smaller_14 radius            15.375%
                                 mass_smaller_30 radius            15.065%
random_forest     MIST           Base            radius             8.677%
                                 mass_smaller_3  radius             5.464%
                                 mass_smaller_14 radius             4.315%
                                 mass_smaller_30 radius             3.923%
xgboost           MIST           Base            radius            14.096%
                                 mass_smaller_3  radius             7.085%
                                 mass_smaller_14 radius             7.573%
                                 mass_smaller_30 radius             7.922%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             75 : 0.269% / 90 : 0.531% / 95 : 0.834% / 99 : 1.94%
                                 mass_smaller_3  radius            75 : 0.264% / 90 : 0.512% / 95 : 0.827% / 99 : 2.382%
                                 mass_smaller_14 radius             75 : 0.29% / 90 : 0.571% / 95 : 0.873% / 99 : 2.009%
                                 mass_smaller_30 radius            75 : 0.258% / 90 : 0.502% / 95 : 0.764% / 99 : 1.747%
KNN               MIST           Base            radius              75 : 0.17% / 90 : 0.316% / 95 : 0.47% / 99 : 1.317%
                                 mass_smaller_3  radius             75 : 0.212% / 90 : 0.405% / 95 : 0.626% / 99 : 1.88%
                                 mass_smaller_14 radius             75 : 0.185% / 90 : 0.328% / 95 : 0.46% / 99 : 1.275%
                                 mass_smaller_30 radius            75 : 0.161% / 90 : 0.289% / 95 : 0.402% / 99 : 1.089%
linear_regression MIST           Base            radius            75 : 2.479% / 90 : 4.855% / 95 : 6.506% / 99 : 9.473%
                                 mass_smaller_3  radius             75 : 3.38% / 90 : 4.458% / 95 : 5.013% / 99 : 6.569%
                                 mass_smaller_14 radius            75 : 3.015% / 90 : 4.239% / 95 : 5.318% / 99 : 8.521%
                                 mass_smaller_30 radius            75 : 2.615% / 90 : 3.721% / 95 : 4.855% / 99 : 7.622%
mlp               MIST           Base            radius            75 : 2.176% / 90 : 3.268% / 95 : 3.987% / 99 : 6.045%
                                 mass_smaller_3  radius             75 : 1.14% / 90 : 1.655% / 95 : 2.022% / 99 : 3.697%
                                 mass_smaller_14 radius            75 : 1.049% / 90 : 1.573% / 95 : 1.949% / 99 : 3.761%
                                 mass_smaller_30 radius            75 : 1.652% / 90 : 2.764% / 95 : 3.312% / 99 : 4.502%
random_forest     MIST           Base            radius            75 : 0.144% / 90 : 0.298% / 95 : 0.459% / 99 : 1.197%
                                 mass_smaller_3  radius              75 : 0.14% / 90 : 0.298% / 95 : 0.511% / 99 : 1.54%
                                 mass_smaller_14 radius            75 : 0.158% / 90 : 0.318% / 95 : 0.472% / 99 : 1.088%
                                 mass_smaller_30 radius              75 : 0.132% / 90 : 0.267% / 95 : 0.4% / 99 : 0.955%
xgboost           MIST           Base            radius             75 : 0.474% / 90 : 0.747% / 95 : 0.98% / 99 : 1.909%
                                 mass_smaller_3  radius              75 : 0.36% / 90 : 0.61% / 95 : 0.891% / 99 : 2.138%
                                 mass_smaller_14 radius            75 : 0.444% / 90 : 0.691% / 95 : 0.915% / 99 : 1.895%
                                 mass_smaller_30 radius            75 : 0.408% / 90 : 0.639% / 95 : 0.823% / 99 : 1.666%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           Base            radius             24.898207902908325
                                 mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
                                 mass_smaller_30 radius             21.883111715316772
KNN               MIST           Base            radius               8.37163758277893
                                 mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
                                 mass_smaller_30 radius             6.2819530963897705
linear_regression MIST           Base            radius             0.6336760520935059
                                 mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
                                 mass_smaller_30 radius             0.5243825912475586
mlp               MIST           Base            radius             259.79061460494995
                                 mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
                                 mass_smaller_30 radius             349.92928099632263
random_forest     MIST           Base            radius              343.6629173755646
                                 mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
                                 mass_smaller_30 radius             327.88787055015564
xgboost           MIST           Base            radius             11.712000608444214

In [8]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["mass_smaller_3", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
KNN               MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
linear_regression MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
mlp               MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
random_forest     MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
xgboost           MIST           mass_smaller_3  radius            -0.9974747647513328 - 2.7813065611193197
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             0.999866660211663
                                 mass_smaller_14 radius            0.9998290497642414
KNN               MIST           mass_smaller_3  radius            0.9999040702564876
                                 mass_smaller_14 radius            0.9999238365249355
linear_regression MIST           mass_smaller_3  radius            0.9928968443499933
                                 mass_smaller_14 radius            0.9915723548914062
mlp               MIST           mass_smaller_3  radius            0.9991367039903855
                                 mass_smaller_14 radius             0.999136672646969
random_forest     MIST           mass_smaller_3  radius             0.999960084444697
                                 mass_smaller_14 radius            0.9999564181903926
xgboost           MIST           mass_smaller_3  radius            0.9998348191009966
                                 mass_smaller_14 radius            0.9997464415773465

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.213%
                                 mass_smaller_14 radius            0.226%
KNN               MIST           mass_smaller_3  radius            0.181%
                                 mass_smaller_14 radius            0.151%
linear_regression MIST           mass_smaller_3  radius            1.558%
                                 mass_smaller_14 radius            1.586%
mlp               MIST           mass_smaller_3  radius            0.588%
                                 mass_smaller_14 radius            0.537%
random_forest     MIST           mass_smaller_3  radius            0.117%
                                 mass_smaller_14 radius            0.114%
xgboost           MIST           mass_smaller_3  radius            0.238%
                                 mass_smaller_14 radius            0.275%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.131%
KNN               MIST           mass_smaller_3  radius            0.108%
                                 mass_smaller_14 radius            0.093%
linear_regression MIST           mass_smaller_3  radius             1.17%
                                 mass_smaller_14 radius            1.206%
mlp               MIST           mass_smaller_3  radius            0.404%
                                 mass_smaller_14 radius            0.384%
random_forest     MIST           mass_smaller_3  radius            0.053%
                                 mass_smaller_14 radius             0.06%
xgboost           MIST           mass_smaller_3  radius            0.161%
                                 mass_smaller_14 radius            0.199%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.066%
                                 mass_smaller_14 radius            0.077%
KNN               MIST           mass_smaller_3  radius            0.068%
                                 mass_smaller_14 radius            0.062%
linear_regression MIST           mass_smaller_3  radius            0.887%
                                 mass_smaller_14 radius            0.976%
mlp               MIST           mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.306%
random_forest     MIST           mass_smaller_3  radius            0.026%
                                 mass_smaller_14 radius            0.031%
xgboost           MIST           mass_smaller_3  radius            0.118%
                                 mass_smaller_14 radius            0.153%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9999333298626585
                                 mass_smaller_14 radius            0.9999145940186054
KNN               MIST           mass_smaller_3  radius            0.9999520800077348
                                 mass_smaller_14 radius            0.9999619536912048
linear_regression MIST           mass_smaller_3  radius            0.9964420928232931
                                 mass_smaller_14 radius            0.9957772616862719
mlp               MIST           mass_smaller_3  radius            0.9995738143553161
                                 mass_smaller_14 radius            0.9995714386703022
random_forest     MIST           mass_smaller_3  radius            0.9999800420415123
                                 mass_smaller_14 radius            0.9999782166433258
xgboost           MIST           mass_smaller_3  radius             0.999917407540224
                                 mass_smaller_14 radius            0.9998732248486286

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             4.519%
                                 mass_smaller_14 radius            10.289%
KNN               MIST           mass_smaller_3  radius             5.987%
                                 mass_smaller_14 radius             5.056%
linear_regression MIST           mass_smaller_3  radius            10.931%
                                 mass_smaller_14 radius            11.805%
mlp               MIST           mass_smaller_3  radius            10.377%
                                 mass_smaller_14 radius             11.26%
random_forest     MIST           mass_smaller_3  radius             3.915%
                                 mass_smaller_14 radius             3.502%
xgboost           MIST           mass_smaller_3  radius             5.076%
                                 mass_smaller_14 radius             5.546%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.149% / 90 : 0.294% / 95 : 0.373% / 99 : 0.762%
                                 mass_smaller_14 radius            75 : 0.166% / 90 : 0.301% / 95 : 0.396% / 99 : 0.848%
KNN               MIST           mass_smaller_3  radius             75 : 0.135% / 90 : 0.24% / 95 : 0.327% / 99 : 0.629%
                                 mass_smaller_14 radius            75 : 0.119% / 90 : 0.209% / 95 : 0.278% / 99 : 0.515%
linear_regression MIST           mass_smaller_3  radius             75 : 1.64% / 90 : 2.621% / 95 : 3.242% / 99 : 4.505%
                                 mass_smaller_14 radius             75 : 1.747% / 90 : 2.54% / 95 : 3.068% / 99 : 4.566%
mlp               MIST           mass_smaller_3  radius             75 : 0.56% / 90 : 0.953% / 95 : 1.212% / 99 : 1.733%
                                 mass_smaller_14 radius            75 : 0.527% / 90 : 0.775% / 95 : 0.965% / 99 : 1.541%
random_forest     MIST           mass_smaller_3  radius             75 : 0.06% / 90 : 0.119% / 95 : 0.175% / 99 : 0.395%
                                 mass_smaller_14 radius            75 : 0.071% / 90 : 0.141% / 95 : 0.205% / 99 : 0.411%
xgboost           MIST           mass_smaller_3  radius             75 : 0.214% / 90 : 0.34% / 95 : 0.441% / 99 : 0.747%
                                 mass_smaller_14 radius            75 : 0.274% / 90 : 0.421% / 95 : 0.528% / 99 : 0.802%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 0.0

                                                                                                value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
KNN               MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
linear_regression MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
mlp               MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
random_forest     MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837
xgboost           MIST           mass_smaller_3  radius            -0.9974747647513328 - 0.7629161677552769
                                 mass_smaller_14 radius             -0.9974747647513328 - 3.082068881511837

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9998249631057525
                                 mass_smaller_14 radius            0.9997880404019214
KNN               MIST           mass_smaller_3  radius            0.9996571642468787
                                 mass_smaller_14 radius            0.9998255884455621
linear_regression MIST           mass_smaller_3  radius            0.9753521021495244
                                 mass_smaller_14 radius            0.9830496323087852
mlp               MIST           mass_smaller_3  radius            0.9983513710056814
                                 mass_smaller_14 radius            0.9983627542851781
random_forest     MIST           mass_smaller_3  radius            0.9999678953910232
                                 mass_smaller_14 radius            0.9999534137978472
xgboost           MIST           mass_smaller_3  radius            0.9996075937684589
                                 mass_smaller_14 radius            0.9995117695213523

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.239%
                                 mass_smaller_14 radius             0.15%
KNN               MIST           mass_smaller_3  radius            0.335%
                                 mass_smaller_14 radius            0.136%
linear_regression MIST           mass_smaller_3  radius             2.87%
                                 mass_smaller_14 radius            1.353%
mlp               MIST           mass_smaller_3  radius             0.92%
                                 mass_smaller_14 radius            0.441%
random_forest     MIST           mass_smaller_3  radius            0.103%
                                 mass_smaller_14 radius            0.071%
xgboost           MIST           mass_smaller_3  radius            0.358%
                                 mass_smaller_14 radius            0.228%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.152%
                                 mass_smaller_14 radius            0.089%
KNN               MIST           mass_smaller_3  radius            0.219%
                                 mass_smaller_14 radius             0.09%
linear_regression MIST           mass_smaller_3  radius            2.086%
                                 mass_smaller_14 radius            1.037%
mlp               MIST           mass_smaller_3  radius            0.672%
                                 mass_smaller_14 radius            0.346%
random_forest     MIST           mass_smaller_3  radius            0.063%
                                 mass_smaller_14 radius             0.04%
xgboost           MIST           mass_smaller_3  radius            0.273%
                                 mass_smaller_14 radius            0.174%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.101%
                                 mass_smaller_14 radius            0.056%
KNN               MIST           mass_smaller_3  radius            0.136%
                                 mass_smaller_14 radius            0.058%
linear_regression MIST           mass_smaller_3  radius            1.579%
                                 mass_smaller_14 radius            0.829%
mlp               MIST           mass_smaller_3  radius            0.467%
                                 mass_smaller_14 radius            0.292%
random_forest     MIST           mass_smaller_3  radius            0.039%
                                 mass_smaller_14 radius            0.022%
xgboost           MIST           mass_smaller_3  radius            0.214%
                                 mass_smaller_14 radius            0.136%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9999125211077539
                                 mass_smaller_14 radius            0.9998940164221873
KNN               MIST           mass_smaller_3  radius             0.999830888291084
                                 mass_smaller_14 radius            0.9999135578590763
linear_regression MIST           mass_smaller_3  radius            0.9879836947112961
                                 mass_smaller_14 radius            0.9914885941715924
mlp               MIST           mass_smaller_3  radius            0.9992197462781777
                                 mass_smaller_14 radius            0.9991810430555029
random_forest     MIST           mass_smaller_3  radius            0.9999840579307431
                                 mass_smaller_14 radius            0.9999767231025315
xgboost           MIST           mass_smaller_3  radius            0.9998037782605148
                                 mass_smaller_14 radius            0.9997558778235092

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             4.663%
                                 mass_smaller_14 radius             7.812%
KNN               MIST           mass_smaller_3  radius             5.368%
                                 mass_smaller_14 radius             1.439%
linear_regression MIST           mass_smaller_3  radius            12.801%
                                 mass_smaller_14 radius             5.381%
mlp               MIST           mass_smaller_3  radius             3.953%
                                 mass_smaller_14 radius             4.054%
random_forest     MIST           mass_smaller_3  radius             2.464%
                                 mass_smaller_14 radius             3.502%
xgboost           MIST           mass_smaller_3  radius             6.229%
                                 mass_smaller_14 radius             1.596%

                                                                                                              Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius              75 : 0.199% / 90 : 0.324% / 95 : 0.448% / 99 : 0.89%
                                 mass_smaller_14 radius             75 : 0.112% / 90 : 0.197% / 95 : 0.278% / 99 : 0.584%
KNN               MIST           mass_smaller_3  radius             75 : 0.275% / 90 : 0.515% / 95 : 0.723% / 99 : 1.238%
                                 mass_smaller_14 radius             75 : 0.113% / 90 : 0.205% / 95 : 0.285% / 99 : 0.514%
linear_regression MIST           mass_smaller_3  radius            75 : 2.801% / 90 : 4.245% / 95 : 5.738% / 99 : 10.075%
                                 mass_smaller_14 radius             75 : 1.559% / 90 : 2.251% / 95 : 2.664% / 99 : 3.814%
mlp               MIST           mass_smaller_3  radius               75 : 0.963% / 90 : 1.592% / 95 : 1.971% / 99 : 2.7%
                                 mass_smaller_14 radius             75 : 0.488% / 90 : 0.697% / 95 : 0.836% / 99 : 1.194%
random_forest     MIST           mass_smaller_3  radius             75 : 0.081% / 90 : 0.145% / 95 : 0.202% / 99 : 0.373%
                                 mass_smaller_14 radius             75 : 0.047% / 90 : 0.092% / 95 : 0.136% / 99 : 0.278%
xgboost           MIST           mass_smaller_3  radius             75 : 0.382% / 90 : 0.581% / 95 : 0.732% / 99 : 1.059%
                                 mass_smaller_14 radius             75 : 0.243% / 90 : 0.373% / 95 : 0.467% / 99 : 0.669%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 2.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
KNN               MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
linear_regression MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
mlp               MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
random_forest     MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256
xgboost           MIST           mass_smaller_3  radius            0.0909920840275404 - 2.3291459066926827
                                 mass_smaller_14 radius            0.0909920840275404 - 2.8708569524681256

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9995465768676972
                                 mass_smaller_14 radius            0.9995039197290129
KNN               MIST           mass_smaller_3  radius            0.9998807428184813
                                 mass_smaller_14 radius            0.9998943160073213
linear_regression MIST           mass_smaller_3  radius            0.9833773452801731
                                 mass_smaller_14 radius            0.9806856109752665
mlp               MIST           mass_smaller_3  radius            0.9978060724763279
                                 mass_smaller_14 radius             0.998723350903017
random_forest     MIST           mass_smaller_3  radius            0.9999301508060892
                                 mass_smaller_14 radius            0.9999185082513201
xgboost           MIST           mass_smaller_3  radius            0.9995508512748904
                                 mass_smaller_14 radius            0.9994208286577492

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.437%
                                 mass_smaller_14 radius            0.373%
KNN               MIST           mass_smaller_3  radius            0.224%
                                 mass_smaller_14 radius            0.172%
linear_regression MIST           mass_smaller_3  radius            2.771%
                                 mass_smaller_14 radius            2.381%
mlp               MIST           mass_smaller_3  radius            1.108%
                                 mass_smaller_14 radius            0.599%
random_forest     MIST           mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.153%
xgboost           MIST           mass_smaller_3  radius            0.435%
                                 mass_smaller_14 radius            0.404%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.322%
                                 mass_smaller_14 radius            0.264%
KNN               MIST           mass_smaller_3  radius            0.172%
                                 mass_smaller_14 radius            0.131%
linear_regression MIST           mass_smaller_3  radius            2.218%
                                 mass_smaller_14 radius            1.855%
mlp               MIST           mass_smaller_3  radius            0.799%
                                 mass_smaller_14 radius            0.473%
random_forest     MIST           mass_smaller_3  radius             0.12%
                                 mass_smaller_14 radius            0.105%
xgboost           MIST           mass_smaller_3  radius            0.333%
                                 mass_smaller_14 radius            0.314%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.263%
                                 mass_smaller_14 radius            0.217%
KNN               MIST           mass_smaller_3  radius            0.137%
                                 mass_smaller_14 radius            0.103%
linear_regression MIST           mass_smaller_3  radius            1.872%
                                 mass_smaller_14 radius            1.509%
mlp               MIST           mass_smaller_3  radius            0.527%
                                 mass_smaller_14 radius            0.389%
random_forest     MIST           mass_smaller_3  radius            0.083%
                                 mass_smaller_14 radius            0.072%
xgboost           MIST           mass_smaller_3  radius            0.266%
                                 mass_smaller_14 radius            0.255%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9997733155946078
                                 mass_smaller_14 radius            0.9997540306645297
KNN               MIST           mass_smaller_3  radius            0.9999404528865401
                                 mass_smaller_14 radius            0.9999471831409968
linear_regression MIST           mass_smaller_3  radius             0.993268227885979
                                 mass_smaller_14 radius            0.9909797904600514
mlp               MIST           mass_smaller_3  radius            0.9989117384154471
                                 mass_smaller_14 radius            0.9993643661222952
random_forest     MIST           mass_smaller_3  radius            0.9999650748236046
                                 mass_smaller_14 radius            0.9999605620655518
xgboost           MIST           mass_smaller_3  radius            0.9997754108047239
                                 mass_smaller_14 radius            0.9997106655945553

                                                                   MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            5.347%
                                 mass_smaller_14 radius             15.1%
KNN               MIST           mass_smaller_3  radius            3.109%
                                 mass_smaller_14 radius            2.265%
linear_regression MIST           mass_smaller_3  radius            7.833%
                                 mass_smaller_14 radius            8.961%
mlp               MIST           mass_smaller_3  radius            4.322%
                                 mass_smaller_14 radius             4.45%
random_forest     MIST           mass_smaller_3  radius            2.008%
                                 mass_smaller_14 radius            2.388%
xgboost           MIST           mass_smaller_3  radius            2.523%
                                 mass_smaller_14 radius            2.615%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.491% / 90 : 0.627% / 95 : 0.747% / 99 : 1.318%
                                 mass_smaller_14 radius            75 : 0.354% / 90 : 0.499% / 95 : 0.622% / 99 : 1.155%
KNN               MIST           mass_smaller_3  radius             75 : 0.236% / 90 : 0.368% / 95 : 0.449% / 99 : 0.63%
                                 mass_smaller_14 radius            75 : 0.178% / 90 : 0.285% / 95 : 0.354% / 99 : 0.494%
linear_regression MIST           mass_smaller_3  radius            75 : 3.379% / 90 : 4.724% / 95 : 5.395% / 99 : 6.276%
                                 mass_smaller_14 radius            75 : 2.614% / 90 : 3.907% / 95 : 4.838% / 99 : 6.671%
mlp               MIST           mass_smaller_3  radius             75 : 1.086% / 90 : 2.065% / 95 : 2.465% / 99 : 3.16%
                                 mass_smaller_14 radius            75 : 0.684% / 90 : 0.991% / 95 : 1.184% / 99 : 1.535%
random_forest     MIST           mass_smaller_3  radius            75 : 0.164% / 90 : 0.272% / 95 : 0.354% / 99 : 0.554%
                                 mass_smaller_14 radius            75 : 0.142% / 90 : 0.239% / 95 : 0.315% / 99 : 0.514%
xgboost           MIST           mass_smaller_3  radius             75 : 0.463% / 90 : 0.706% / 95 : 0.879% / 99 : 1.28%
                                 mass_smaller_14 radius             75 : 0.448% / 90 : 0.66% / 95 : 0.808% / 99 : 1.134%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Results for the phase category with a value of 3.0

                                                                                               value range  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
KNN               MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
linear_regression MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
mlp               MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
random_forest     MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276
xgboost           MIST           mass_smaller_3  radius            0.0742466933732667 - 2.7813065611193197
                                 mass_smaller_14 radius             0.0758282047744788 - 3.063523621241276

                                                                                  RVE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9992381885703833
                                 mass_smaller_14 radius            0.9993395139862439
KNN               MIST           mass_smaller_3  radius            0.9994853264493573
                                 mass_smaller_14 radius            0.9997229263417253
linear_regression MIST           mass_smaller_3  radius            0.9740128136920825
                                 mass_smaller_14 radius            0.9746821269484942
mlp               MIST           mass_smaller_3  radius            0.9952899598276022
                                 mass_smaller_14 radius            0.9970644512745905
random_forest     MIST           mass_smaller_3  radius            0.9996570039158864
                                 mass_smaller_14 radius             0.999774074221781
xgboost           MIST           mass_smaller_3  radius            0.9991584798800517
                                 mass_smaller_14 radius            0.9991636868686137

                                                                     RMSE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.478%
                                 mass_smaller_14 radius            0.456%
KNN               MIST           mass_smaller_3  radius            0.393%
                                 mass_smaller_14 radius            0.295%
linear_regression MIST           mass_smaller_3  radius            2.794%
                                 mass_smaller_14 radius            2.821%
mlp               MIST           mass_smaller_3  radius            1.188%
                                 mass_smaller_14 radius            1.158%
random_forest     MIST           mass_smaller_3  radius            0.321%
                                 mass_smaller_14 radius            0.268%
xgboost           MIST           mass_smaller_3  radius            0.503%
                                 mass_smaller_14 radius            0.514%

                                                                      MAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             0.23%
                                 mass_smaller_14 radius            0.243%
KNN               MIST           mass_smaller_3  radius            0.188%
                                 mass_smaller_14 radius             0.15%
linear_regression MIST           mass_smaller_3  radius            2.203%
                                 mass_smaller_14 radius            2.185%
mlp               MIST           mass_smaller_3  radius            0.821%
                                 mass_smaller_14 radius            0.789%
random_forest     MIST           mass_smaller_3  radius            0.138%
                                 mass_smaller_14 radius            0.134%
xgboost           MIST           mass_smaller_3  radius              0.3%
                                 mass_smaller_14 radius             0.34%

                                                                    MedAE  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.106%
                                 mass_smaller_14 radius             0.12%
KNN               MIST           mass_smaller_3  radius            0.093%
                                 mass_smaller_14 radius            0.082%
linear_regression MIST           mass_smaller_3  radius            1.885%
                                 mass_smaller_14 radius            1.865%
mlp               MIST           mass_smaller_3  radius             0.61%
                                 mass_smaller_14 radius            0.609%
random_forest     MIST           mass_smaller_3  radius            0.057%
                                 mass_smaller_14 radius            0.064%
xgboost           MIST           mass_smaller_3  radius            0.193%
                                 mass_smaller_14 radius            0.245%

                                                                                 CORR  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            0.9996192777071335
                                 mass_smaller_14 radius            0.9996699530747309
KNN               MIST           mass_smaller_3  radius            0.9997430849980539
                                 mass_smaller_14 radius            0.9998615008366036
linear_regression MIST           mass_smaller_3  radius            0.9886235406128182
                                 mass_smaller_14 radius            0.9873693027486672
mlp               MIST           mass_smaller_3  radius            0.9976629398298685
                                 mass_smaller_14 radius            0.9985438860810399
random_forest     MIST           mass_smaller_3  radius            0.9998285901743722
                                 mass_smaller_14 radius            0.9998870342476956
xgboost           MIST           mass_smaller_3  radius             0.999579231894782
                                 mass_smaller_14 radius            0.9995818580147785

                                                                    MAX_ER  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             6.307%
                                 mass_smaller_14 radius             5.599%
KNN               MIST           mass_smaller_3  radius             8.357%
                                 mass_smaller_14 radius             6.904%
linear_regression MIST           mass_smaller_3  radius            15.259%
                                 mass_smaller_14 radius            16.119%
mlp               MIST           mass_smaller_3  radius            14.485%
                                 mass_smaller_14 radius            15.375%
random_forest     MIST           mass_smaller_3  radius             5.464%
                                 mass_smaller_14 radius             4.315%
xgboost           MIST           mass_smaller_3  radius             7.085%
                                 mass_smaller_14 radius             7.573%

                                                                                                             Percentiles  \
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius            75 : 0.264% / 90 : 0.512% / 95 : 0.827% / 99 : 2.382%
                                 mass_smaller_14 radius             75 : 0.29% / 90 : 0.571% / 95 : 0.873% / 99 : 2.009%
KNN               MIST           mass_smaller_3  radius             75 : 0.212% / 90 : 0.405% / 95 : 0.626% / 99 : 1.88%
                                 mass_smaller_14 radius             75 : 0.185% / 90 : 0.328% / 95 : 0.46% / 99 : 1.275%
linear_regression MIST           mass_smaller_3  radius             75 : 3.38% / 90 : 4.458% / 95 : 5.013% / 99 : 6.569%
                                 mass_smaller_14 radius            75 : 3.015% / 90 : 4.239% / 95 : 5.318% / 99 : 8.521%
mlp               MIST           mass_smaller_3  radius             75 : 1.14% / 90 : 1.655% / 95 : 2.022% / 99 : 3.697%
                                 mass_smaller_14 radius            75 : 1.049% / 90 : 1.573% / 95 : 1.949% / 99 : 3.761%
random_forest     MIST           mass_smaller_3  radius              75 : 0.14% / 90 : 0.298% / 95 : 0.511% / 99 : 1.54%
                                 mass_smaller_14 radius            75 : 0.158% / 90 : 0.318% / 95 : 0.472% / 99 : 1.088%
xgboost           MIST           mass_smaller_3  radius              75 : 0.36% / 90 : 0.61% / 95 : 0.891% / 99 : 2.138%
                                 mass_smaller_14 radius            75 : 0.444% / 90 : 0.691% / 95 : 0.915% / 99 : 1.895%

                                                                                  time
model             physical_model filter          output_parameter
decision_tree     MIST           mass_smaller_3  radius             11.536891222000122
                                 mass_smaller_14 radius             18.880497217178345
KNN               MIST           mass_smaller_3  radius             2.7264862060546875
                                 mass_smaller_14 radius               5.27383017539978
linear_regression MIST           mass_smaller_3  radius            0.28507542610168457
                                 mass_smaller_14 radius            0.46092677116394043
mlp               MIST           mass_smaller_3  radius             116.37484526634216
                                 mass_smaller_14 radius               189.019047498703
random_forest     MIST           mass_smaller_3  radius              142.9930453300476
                                 mass_smaller_14 radius             248.72876453399658
xgboost           MIST           mass_smaller_3  radius              5.586430311203003
                                 mass_smaller_14 radius              8.433841943740845

Linear regression : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : better results than Base on every metric but less than mass_smaller_3 and mass_smaller_14

Decision tree : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : better or similar results than Base on every metric except MAX_ER, less than mass_smaller_3 and mass_smaller_14

KNN : 
- mass_smaller_3 : similar results than Base except for MAX_ER which is better
- mass_smaller_14 : better/similar results than Base on every metric
- mass_smaller_30 : better/similar results than Base on every metric but less than mass_smaller_14

Random forest : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric, less than mass_smaller_3 except for MAX_ER
- mass_smaller_30 : better results than Base on every metric, less than mass_smaller_3 and similar to mass_smaller_14 except MAX_ER which is worse

XGBoost : 
- mass_smaller_3 : better results than Base on every metric
- mass_smaller_14 : better results than Base on every metric, less than mass_smaller_3
- mass_smaller_30 : better results than Base on every metric, less than mass_smaller_3 and mass_smaller_14

MLP : 
- mass_smaller_3 : way better results than Base on every metric
- mass_smaller_14 : way better results than Base on every metric but less than mass_smaller_3
- mass_smaller_30 : way better results than Base on every metric but less than mass_smaller_3 and mass_smaller_14

#### Conclusions on radius

mass_smaller_3 almost always gives better results than Base.

mass_smaller_14 almost always gives better results than Base but most of the time it improves less than mass_smaller_3.

mass_smaller_30 almost always gives better results than Base but most of the time it improves less than mass_smaller_3 and mass_smaller_14

#### Best models for the radius parameter

The three best performing models in order for the radius parameter are Random forest, KNN and Decision tree.

### Conclusion for every filtering

In [10]:
compare_metrics(path, value_rounding=3, relative_values=False,
                model_names=["random_forest", "KNN", "decision_tree"],
                output_parameters=["mass", "radius"],
                physical_models=["MIST"],
                data_filters=["Base", "mass_smaller_14"])

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
KNN           MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
decision_tree MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.129
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.998  1.251
                                             radius            1.000  0.006
                             mass_smaller_14 mass              1.000  0.033
                                             radius            1.000  0.005
KNN           MIST           Base            mass              0.990  2.726
                                             radius            1.000  0.007
                             mass_smaller_14 mass              0.999  0.083
                                             radius            1.000  0.006
decision_tree MIST           Base            mass              0.995  1.837
                                             radius            1.000  0.011
                             mass_smaller_14 mass              1.000  0.051
                                             radius            1.000  0.009

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.145  0.004
                                             radius            0.003  0.001
                             mass_smaller_14 mass              0.011  0.003
                                             radius            0.002  0.001
KNN           MIST           Base            mass              0.328  0.008
                                             radius            0.004  0.003
                             mass_smaller_14 mass              0.029  0.007
                                             radius            0.004  0.003
decision_tree MIST           Base            mass              0.200  0.003
                                             radius            0.006  0.003
                             mass_smaller_14 mass              0.016  0.003
                                             radius            0.005  0.003

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.999   95.973
                                             radius            1.000    0.358
                             mass_smaller_14 mass              1.000    2.328
                                             radius            1.000    0.143
KNN           MIST           Base            mass              0.995  144.214
                                             radius            1.000    0.307
                             mass_smaller_14 mass              1.000    2.604
                                             radius            1.000    0.206
decision_tree MIST           Base            mass              0.998  151.658
                                             radius            1.000    0.478
                             mass_smaller_14 mass              1.000    5.116
                                             radius            1.000    0.420

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01557 / 90 : 0.07872 / 95 : 0.29091 / 99 : 3.19321
                                             radius             75 : 0.00311 / 90 : 0.00627 / 95 : 0.00939 / 99 : 0.02061
                             mass_smaller_14 mass                75 : 0.00986 / 90 : 0.02522 / 95 : 0.0469 / 99 : 0.13865
                                             radius             75 : 0.00291 / 90 : 0.00575 / 95 : 0.00837 / 99 : 0.01677
KNN           MIST           Base            mass               75 : 0.04002 / 90 : 0.20998 / 95 : 0.70302 / 99 : 6.87041
                                             radius             75 : 0.00513 / 90 : 0.00921 / 95 : 0.01275 / 99 : 0.02703
                             mass_smaller_14 mass                75 : 0.02377 / 90 : 0.07441 / 95 : 0.12857 / 99 : 0.3237
                                             radius             75 : 0.00487 / 90 : 0.00851 / 95 : 0.01134 / 99 : 0.02103
decision_tree MIST           Base            mass               75 : 0.01985 / 90 : 0.10454 / 95 : 0.35331 / 99 : 4.56376
                                             radius               75 : 0.00721 / 90 : 0.013 / 95 : 0.01829 / 99 : 0.04024
                             mass_smaller_14 mass               75 : 0.01198 / 90 : 0.03828 / 95 : 0.07324 / 99 : 0.22077
                                             radius              75 : 0.00676 / 90 : 0.01226 / 95 : 0.01617 / 99 : 0.0346

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 0.0

                                                                  value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
KNN           MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082
decision_tree MIST           Base            mass               0.1 - 298.545
                                             radius            -0.997 - 3.083
                             mass_smaller_14 mass                0.1 - 13.999
                                             radius            -0.997 - 3.082

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.997  1.350
                                             radius            1.000  0.004
                             mass_smaller_14 mass              1.000  0.029
                                             radius            1.000  0.003
KNN           MIST           Base            mass              0.984  3.292
                                             radius            1.000  0.007
                             mass_smaller_14 mass              0.999  0.095
                                             radius            1.000  0.006
decision_tree MIST           Base            mass              0.994  2.098
                                             radius            1.000  0.008
                             mass_smaller_14 mass              1.000  0.051
                                             radius            1.000  0.006

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.168  0.004
                                             radius            0.002  0.001
                             mass_smaller_14 mass              0.009  0.002
                                             radius            0.002  0.001
KNN           MIST           Base            mass              0.432  0.010
                                             radius            0.004  0.003
                             mass_smaller_14 mass              0.031  0.007
                                             radius            0.004  0.002
decision_tree MIST           Base            mass              0.270  0.006
                                             radius            0.005  0.003
                             mass_smaller_14 mass              0.017  0.004
                                             radius            0.004  0.002

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.999   83.538
                                             radius            1.000    0.358
                             mass_smaller_14 mass              1.000    2.328
                                             radius            1.000    0.143
KNN           MIST           Base            mass              0.992  126.674
                                             radius            1.000    0.154
                             mass_smaller_14 mass              1.000    2.604
                                             radius            1.000    0.059
decision_tree MIST           Base            mass              0.997  131.775
                                             radius            1.000    0.478
                             mass_smaller_14 mass              1.000    5.116
                                             radius            1.000    0.319

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               75 : 0.01628 / 90 : 0.10798 / 95 : 0.41573 / 99 : 3.60316
                                             radius               75 : 0.00232 / 90 : 0.00485 / 95 : 0.0075 / 99 : 0.0165
                             mass_smaller_14 mass               75 : 0.00713 / 90 : 0.01962 / 95 : 0.03484 / 99 : 0.10114
                                             radius             75 : 0.00193 / 90 : 0.00375 / 95 : 0.00556 / 99 : 0.01133
KNN           MIST           Base            mass               75 : 0.05187 / 90 : 0.33456 / 95 : 1.03023 / 99 : 8.94265
                                             radius              75 : 0.00518 / 90 : 0.00955 / 95 : 0.01355 / 99 : 0.0264
                             mass_smaller_14 mass                75 : 0.02433 / 90 : 0.0695 / 95 : 0.12413 / 99 : 0.38274
                                             radius             75 : 0.00459 / 90 : 0.00838 / 95 : 0.01164 / 99 : 0.02096
decision_tree MIST           Base            mass               75 : 0.03086 / 90 : 0.18595 / 95 : 0.67453 / 99 : 5.94846
                                             radius             75 : 0.00534 / 90 : 0.01028 / 95 : 0.01519 / 99 : 0.03251
                             mass_smaller_14 mass               75 : 0.01359 / 90 : 0.04207 / 95 : 0.07392 / 99 : 0.19384
                                             radius             75 : 0.00455 / 90 : 0.00804 / 95 : 0.01134 / 99 : 0.02382

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 2.0

                                                                   value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871
KNN           MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871
decision_tree MIST           Base            mass              0.654 - 283.721
                                             radius              0.092 - 2.892
                             mass_smaller_14 mass               0.654 - 13.928
                                             radius              0.091 - 2.871

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              1.000  0.470
                                             radius            1.000  0.004
                             mass_smaller_14 mass              1.000  0.017
                                             radius            1.000  0.004
KNN           MIST           Base            mass              0.999  0.737
                                             radius            1.000  0.005
                             mass_smaller_14 mass              1.000  0.049
                                             radius            1.000  0.005
decision_tree MIST           Base            mass              0.999  0.795
                                             radius            1.000  0.010
                             mass_smaller_14 mass              1.000  0.025
                                             radius            1.000  0.010

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.059  0.004
                                             radius            0.003  0.002
                             mass_smaller_14 mass              0.008  0.004
                                             radius            0.003  0.002
KNN           MIST           Base            mass              0.095  0.004
                                             radius            0.003  0.003
                             mass_smaller_14 mass              0.020  0.005
                                             radius            0.004  0.003
decision_tree MIST           Base            mass              0.060  0.000
                                             radius            0.007  0.005
                             mass_smaller_14 mass              0.008  0.000
                                             radius            0.007  0.006

                                                               CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass               1.0   22.981
                                             radius             1.0    0.091
                             mass_smaller_14 mass               1.0    0.483
                                             radius             1.0    0.066
KNN           MIST           Base            mass               1.0   37.487
                                             radius             1.0    0.077
                             mass_smaller_14 mass               1.0    0.926
                                             radius             1.0    0.063
decision_tree MIST           Base            mass               1.0  105.861
                                             radius             1.0    0.184
                             mass_smaller_14 mass               1.0    1.411
                                             radius             1.0    0.420

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                75 : 0.01059 / 90 : 0.02554 / 95 : 0.07295 / 99 : 1.3585
                                             radius             75 : 0.00359 / 90 : 0.00617 / 95 : 0.00828 / 99 : 0.01406
                             mass_smaller_14 mass               75 : 0.01007 / 90 : 0.01901 / 95 : 0.02804 / 99 : 0.06834
                                             radius             75 : 0.00394 / 90 : 0.00663 / 95 : 0.00876 / 99 : 0.01428
KNN           MIST           Base            mass                75 : 0.01708 / 90 : 0.07858 / 95 : 0.16183 / 99 : 2.1265
                                             radius             75 : 0.00469 / 90 : 0.00772 / 95 : 0.00978 / 99 : 0.01453
                             mass_smaller_14 mass               75 : 0.01612 / 90 : 0.05506 / 95 : 0.10024 / 99 : 0.20841
                                             radius             75 : 0.00496 / 90 : 0.00793 / 95 : 0.00984 / 99 : 0.01372
decision_tree MIST           Base            mass               75 : 0.00549 / 90 : 0.02551 / 95 : 0.04546 / 99 : 0.75464
                                             radius              75 : 0.00908 / 90 : 0.01345 / 95 : 0.01659 / 99 : 0.0315
                             mass_smaller_14 mass                75 : 0.0057 / 90 : 0.02333 / 95 : 0.03482 / 99 : 0.08753
                                             radius             75 : 0.00984 / 90 : 0.01386 / 95 : 0.01729 / 99 : 0.03211

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

Results for the phase category with a value of 3.0

                                                                   value range  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064
KNN           MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064
decision_tree MIST           Base            mass              0.548 - 288.815
                                             radius             -0.345 - 3.129
                             mass_smaller_14 mass               0.545 - 13.994
                                             radius              0.076 - 3.064

                                                                 RVE   RMSE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.995  1.648
                                             radius            1.000  0.009
                             mass_smaller_14 mass              1.000  0.053
                                             radius            1.000  0.008
KNN           MIST           Base            mass              0.986  2.735
                                             radius            1.000  0.010
                             mass_smaller_14 mass              0.999  0.084
                                             radius            1.000  0.009
decision_tree MIST           Base            mass              0.992  2.077
                                             radius            0.999  0.016
                             mass_smaller_14 mass              0.999  0.074
                                             radius            0.999  0.014

                                                                 MAE  MedAE  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.201  0.007
                                             radius            0.004  0.002
                             mass_smaller_14 mass              0.023  0.006
                                             radius            0.004  0.002
KNN           MIST           Base            mass              0.364  0.010
                                             radius            0.005  0.003
                             mass_smaller_14 mass              0.037  0.008
                                             radius            0.004  0.002
decision_tree MIST           Base            mass              0.200  0.004
                                             radius            0.008  0.004
                             mass_smaller_14 mass              0.027  0.003
                                             radius            0.007  0.004

                                                                CORR   MAX_ER  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              0.998   95.973
                                             radius            1.000    0.301
                             mass_smaller_14 mass              1.000    1.293
                                             radius            1.000    0.129
KNN           MIST           Base            mass              0.993  144.214
                                             radius            1.000    0.307
                             mass_smaller_14 mass              1.000    1.645
                                             radius            1.000    0.206
decision_tree MIST           Base            mass              0.996  151.658
                                             radius            1.000    0.385
                             mass_smaller_14 mass              1.000    2.404
                                             radius            1.000    0.167

                                                                                                               Percentiles  \
model         physical_model filter          output_parameter
random_forest MIST           Base            mass                  75 : 0.02891 / 90 : 0.1076 / 95 : 0.29511 / 99 : 4.683
                                             radius             75 : 0.00501 / 90 : 0.01036 / 95 : 0.01595 / 99 : 0.04157
                             mass_smaller_14 mass                75 : 0.02188 / 90 : 0.0643 / 95 : 0.10864 / 99 : 0.24241
                                             radius              75 : 0.00471 / 90 : 0.0095 / 95 : 0.01409 / 99 : 0.03252
KNN           MIST           Base            mass               75 : 0.05746 / 90 : 0.24528 / 95 : 0.83709 / 99 : 8.32629
                                             radius             75 : 0.00589 / 90 : 0.01098 / 95 : 0.01632 / 99 : 0.04576
                             mass_smaller_14 mass               75 : 0.03551 / 90 : 0.10934 / 95 : 0.17097 / 99 : 0.34974
                                             radius             75 : 0.00553 / 90 : 0.00981 / 95 : 0.01374 / 99 : 0.03808
decision_tree MIST           Base            mass               75 : 0.02357 / 90 : 0.11188 / 95 : 0.26917 / 99 : 4.64103
                                             radius             75 : 0.00936 / 90 : 0.01845 / 95 : 0.02898 / 99 : 0.06739
                             mass_smaller_14 mass                75 : 0.01657 / 90 : 0.0729 / 95 : 0.14969 / 99 : 0.34879
                                             radius             75 : 0.00866 / 90 : 0.01705 / 95 : 0.02607 / 99 : 0.06002

                                                                  time
model         physical_model filter          output_parameter
random_forest MIST           Base            mass              343.663
                                             radius            343.663
                             mass_smaller_14 mass              248.729
                                             radius            248.729
KNN           MIST           Base            mass                8.372
                                             radius              8.372
                             mass_smaller_14 mass                5.274
                                             radius              5.274
decision_tree MIST           Base            mass               24.898
                                             radius             24.898
                             mass_smaller_14 mass               18.880
                                             radius             18.880

It seems that using the filtering mass_smaller_14 gives better results for radius and gives less high errors for the mass.

This filtering might be the best choice as it is also the range of values for PARSEC which would make comparing models between the two easier.