# Results comparison for MIST with fine-tuned models of model A partial

In this notebook, I will compare the results of the different fine tuned models (only the MIST dataset).

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_B/default_models"
path_fine_tuned = pre_path + "results/model_B/fine_tuned_models"

## Getting the ranges for the values

In [3]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Default vs fine-tuned

### KNN

In [3]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff              3.345 - 5.379  0.977
                                    log_g             -1.083 - 6.259  0.875
                                    radius            -0.997 - 3.129  0.915

                                                       RMSE    MAE  MedAE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.053  0.014  0.002
                                    log_g             0.430  0.128  0.005
                                    radius            0.215  0.065  0.004

                                                       CORR  MAX_ER  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.988   0.916
                                    log_g             0.936   5.668
                                    radius            0.957   2.833

                                                                                                      Percentiles  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff               75 : 0.0044 / 90 : 0.02808 / 95 : 0.07313 / 99 : 0.24465
                                    log_g              75 : 0.01948 / 90 : 0.31931 / 95 : 0.91859 / 99 : 2.10542
                                    radius             75 : 0.01165 / 90 : 0.15979 / 95 : 0.45953 / 99 : 1.05296

                                                       time
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             7.903
                                    log_g             7.903
                                    radius            7.903

In [4]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff              3.345 - 5.379  0.978
                                    log_g             -1.083 - 6.259  0.885
                                    radius            -0.997 - 3.129  0.921

                                                       RMSE    MAE  MedAE  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.051  0.015  0.002
                                    log_g             0.413  0.134  0.008
                                    radius            0.207  0.068  0.005

                                                       CORR  MAX_ER  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             0.989   0.907
                                    log_g             0.941   5.672
                                    radius            0.960   2.837

                                                                                                      Percentiles  \
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff              75 : 0.00734 / 90 : 0.03665 / 95 : 0.07439 / 99 : 0.24062
                                    log_g              75 : 0.03636 / 90 : 0.35539 / 95 : 0.92146 / 99 : 1.97399
                                    radius             75 : 0.02066 / 90 : 0.17776 / 95 : 0.46096 / 99 : 0.98696

                                                       time
model physical_model filter         output_parameter
KNN   MIST           scale_quantile T_eff             8.193
                                    log_g             8.193
                                    radius            8.193

the fine-tuning improved the results for the extremes but worsened the results for the middle errors

### Random forest

In [5]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              3.345 - 5.379
                                            log_g             -1.083 - 6.259
                                            radius            -0.997 - 3.129

                                                                RVE   RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.967  0.063
                                            log_g             0.820  0.516
                                            radius            0.878  0.258

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.016  0.001
                                            log_g             0.152  0.004
                                            radius            0.076  0.002

                                                               CORR  MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.984   0.925
                                            log_g             0.908   5.670
                                            radius            0.938   2.836

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              75 : 0.00392 / 90 : 0.03108 / 95 : 0.08703 / 99 : 0.31605
                                            log_g              75 : 0.01846 / 90 : 0.33168 / 95 : 1.14717 / 99 : 2.59461
                                            radius             75 : 0.00956 / 90 : 0.16605 / 95 : 0.57375 / 99 : 1.29797

                                                                 time
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             284.082
                                            log_g             284.082
                                            radius            284.082

In [6]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              3.345 - 5.379
                                            log_g             -1.083 - 6.259
                                            radius            -0.997 - 3.129

                                                                RVE   RMSE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.978  0.052
                                            log_g             0.880  0.421
                                            radius            0.919  0.210

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.016  0.003
                                            log_g             0.140  0.015
                                            radius            0.071  0.008

                                                               CORR  MAX_ER  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             0.989   0.909
                                            log_g             0.938   5.629
                                            radius            0.959   2.814

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff              75 : 0.01023 / 90 : 0.03603 / 95 : 0.07488 / 99 : 0.23682
                                            log_g              75 : 0.05422 / 90 : 0.33735 / 95 : 0.92082 / 99 : 2.04706
                                            radius             75 : 0.02774 / 90 : 0.16883 / 95 : 0.46068 / 99 : 1.02427

                                                                 time
model         physical_model filter         output_parameter
random_forest MIST           scale_quantile T_eff             634.727
                                            log_g             634.727
                                            radius            634.727

Improved the results of the extremes but not the middle values

## Comparison between fine tuned models

### T_eff parameter

In [12]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                data_filters=["scale_quantile"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile,T_eff,3.345 - 5.379,0.978,0.051,0.015,0.002,0.989,0.907,75 : 0.00734 / 90 : 0.03665 / 95 : 0.07439 / 99 : 0.24062,8.193
random_forest,MIST,scale_quantile,T_eff,3.345 - 5.379,0.978,0.052,0.016,0.003,0.989,0.909,75 : 0.01023 / 90 : 0.03603 / 95 : 0.07488 / 99 : 0.23682,634.727

### log_g parameter

In [13]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["log_g"],
                physical_models=["MIST"],
                data_filters=["scale_quantile"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile,log_g,-1.083 - 6.259,0.885,0.413,0.134,0.008,0.941,5.672,75 : 0.03636 / 90 : 0.35539 / 95 : 0.92146 / 99 : 1.97399,8.193
random_forest,MIST,scale_quantile,log_g,-1.083 - 6.259,0.880,0.421,0.140,0.015,0.938,5.629,75 : 0.05422 / 90 : 0.33735 / 95 : 0.92082 / 99 : 2.04706,634.727

### Radius parameter

In [14]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["radius"],
                physical_models=["MIST"],
                data_filters=["scale_quantile"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile,radius,-0.997 - 3.129,0.921,0.207,0.068,0.005,0.960,2.837,75 : 0.02066 / 90 : 0.17776 / 95 : 0.46096 / 99 : 0.98696,8.193
random_forest,MIST,scale_quantile,radius,-0.997 - 3.129,0.919,0.210,0.071,0.008,0.959,2.814,75 : 0.02774 / 90 : 0.16883 / 95 : 0.46068 / 99 : 1.02427,634.727

The KNN model gives the best results.