# Results comparison for MIST with fine-tuned models of model A partial

In this notebook, I will compare the results of the different fine tuned models (only the MIST dataset).

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_B/default_models"
path_fine_tuned = pre_path + "results/model_B/fine_tuned_models"

## Getting the ranges for the values

In [3]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Default vs fine-tuned

### KNN

In [3]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_quantile_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff              3.345 - 4.634
                                       log_g             -1.083 - 5.433
                                       radius            -0.997 - 3.082

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             0.977  0.043  0.012
                                       log_g             0.871  0.445  0.133
                                       radius            0.900  0.222  0.067

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             0.002  0.988   0.916
                                       log_g             0.005  0.934   5.649
                                       radius            0.004  0.949   2.823

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff              75 : 0.00429 / 90 : 0.02469 / 95 : 0.06151 / 99 : 0.16181
                                       log_g              75 : 0.01943 / 90 : 0.34454 / 95 : 0.97233 / 99 : 2.14109
                                       radius             75 : 0.01134 / 90 : 0.17227 / 95 : 0.48608 / 99 : 1.07047

                                                         time
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             5.66
                                       log_g             5.66
                                       radius            5.66

In [4]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["KNN"],
                data_filters=["scale_quantile_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                            value range  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff              3.345 - 4.634
                                       log_g             -1.083 - 5.433
                                       radius            -0.997 - 3.082

                                                           RVE   RMSE    MAE  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             0.978  0.042  0.013
                                       log_g             0.881  0.426  0.139
                                       radius            0.908  0.213  0.070

                                                         MedAE   CORR  MAX_ER  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             0.002  0.989   0.885
                                       log_g             0.008  0.939   5.650
                                       radius            0.005  0.953   2.823

                                                                                                         Percentiles  \
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff                75 : 0.00715 / 90 : 0.03237 / 95 : 0.065 / 99 : 0.15842
                                       log_g              75 : 0.03588 / 90 : 0.38478 / 95 : 0.96989 / 99 : 1.99355
                                       radius             75 : 0.02031 / 90 : 0.19239 / 95 : 0.48496 / 99 : 0.99672

                                                           time
model physical_model filter            output_parameter
KNN   MIST           scale_quantile_14 T_eff             14.547
                                       log_g             14.547
                                       radius            14.547

the fine-tuning improved the results for the extremes but worsened the results for the middle errors

### Random forest

In [5]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_quantile_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              3.345 - 4.634
                                               log_g             -1.083 - 5.433
                                               radius            -0.997 - 3.082

                                                                   RVE   RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.967  0.052
                                               log_g             0.814  0.533
                                               radius            0.857  0.267

                                                                   MAE  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.013  0.001
                                               log_g             0.158  0.004
                                               radius            0.079  0.002

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.984
                                               log_g             0.905
                                               radius            0.927

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              0.887
                                               log_g              5.653
                                               radius             2.827

                                                                                                                 Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              75 : 0.00385 / 90 : 0.02734 / 95 : 0.07453 / 99 : 0.19742
                                               log_g              75 : 0.01869 / 90 : 0.36128 / 95 : 1.20554 / 99 : 2.67219
                                               radius             75 : 0.00949 / 90 : 0.18062 / 95 : 0.60279 / 99 : 1.33623

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             206.138
                                               log_g             206.138
                                               radius            206.138

In [6]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["MIST"],
                model_names=["random_forest"],
                data_filters=["scale_quantile_14"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                    value range  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              3.345 - 4.634
                                               log_g             -1.083 - 5.433
                                               radius            -0.997 - 3.082

                                                                   RVE   RMSE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.978  0.042
                                               log_g             0.877  0.435
                                               radius            0.905  0.217

                                                                   MAE  MedAE  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.014  0.004
                                               log_g             0.146  0.015
                                               radius            0.073  0.008

                                                                  CORR  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             0.989
                                               log_g             0.936
                                               radius            0.951

                                                                 MAX_ER  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              0.827
                                               log_g              5.633
                                               radius             2.817

                                                                                                                 Percentiles  \
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff              75 : 0.01014 / 90 : 0.03145 / 95 : 0.06372 / 99 : 0.15964
                                               log_g               75 : 0.05516 / 90 : 0.3615 / 95 : 0.97279 / 99 : 2.09432
                                               radius             75 : 0.02801 / 90 : 0.18074 / 95 : 0.48635 / 99 : 1.04709

                                                                    time
model         physical_model filter            output_parameter
random_forest MIST           scale_quantile_14 T_eff             151.876
                                               log_g             151.876
                                               radius            151.876

Improved the results of the extremes but not the middle values

## Comparison between fine tuned models

### T_eff parameter

In [7]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["T_eff"],
                physical_models=["MIST"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile_14,T_eff,3.345 - 4.634,0.978,3.256%,0.999%,0.166%,0.989,68.638%,75 : 0.554% / 90 : 2.51% / 95 : 5.039% / 99 : 12.282%,14.547
random_forest,MIST,scale_quantile_14,T_eff,3.345 - 4.634,0.978,3.266%,1.087%,0.274%,0.989,64.15%,75 : 0.786% / 90 : 2.438% / 95 : 4.94% / 99 : 12.377%,151.876

### log_g parameter

In [8]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["MIST"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile_14,log_g,-1.083 - 5.433,0.881,6.545%,2.126%,0.13%,0.939,86.704%,75 : 0.551% / 90 : 5.905% / 95 : 14.885% / 99 : 30.595%,14.547
random_forest,MIST,scale_quantile_14,log_g,-1.083 - 5.433,0.877,6.671%,2.239%,0.235%,0.936,86.45%,75 : 0.847% / 90 : 5.548% / 95 : 14.929% / 99 : 32.141%,151.876

### Radius parameter

In [9]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["MIST"],
                categories=["Global"],
                model_names=["KNN", "random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,MIST,scale_quantile_14,radius,-0.997 - 3.082,0.908,5.23%,1.722%,0.131%,0.953,69.197%,75 : 0.498% / 90 : 4.716% / 95 : 11.888% / 99 : 24.432%,14.547
random_forest,MIST,scale_quantile_14,radius,-0.997 - 3.082,0.905,5.328%,1.799%,0.207%,0.951,69.046%,75 : 0.687% / 90 : 4.43% / 95 : 11.922% / 99 : 25.667%,151.876

The KNN model gives the best results.