# Results comparison for MIST with fine-tuned models of model A partial

In this notebook, I will compare the results of the different fine tuned models (only the MIST dataset).

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_B/default_models"
path_fine_tuned = pre_path + "results/model_B/fine_tuned_models"

## Getting the ranges for the values

In [3]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/MIST_v1.2_vvcrit0.0_basic_isos/", 
                                    ['log10_isochrone_age_yr', 'log_Teff', 'log_g', 'phase', 'metallicity', 'star_mass', 'log_R', 'log_L'], 
                                    "MIST", reclassify=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Default vs fine-tuned

### KNN

In [6]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                      value range    RVE  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              3.362 - 4.518  0.957
                                 log_g             -0.384 - 5.345  0.814
                                 radius            -0.976 - 2.837  0.863

                                                    RMSE    MAE  MedAE   CORR  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             0.038  0.014  0.002  0.978
                                 log_g             0.451  0.158  0.012  0.903
                                 radius            0.226  0.079  0.007  0.929

                                                   MAX_ER  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              0.813
                                 log_g              4.635
                                 radius             2.317

                                                                                                   Percentiles  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff                75 : 0.012 / 90 : 0.03806 / 95 : 0.06792 / 99 : 0.16104
                                 log_g                75 : 0.0814 / 90 : 0.4088 / 95 : 0.94449 / 99 : 2.17266
                                 radius             75 : 0.04068 / 90 : 0.20393 / 95 : 0.47224 / 99 : 1.08633

                                                    time
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             7.433
                                 log_g             7.433
                                 radius            7.433

In [7]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                      value range    RVE  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              3.362 - 4.518  0.950
                                 log_g             -0.384 - 5.345  0.823
                                 radius            -0.976 - 2.837  0.869

                                                    RMSE    MAE  MedAE   CORR  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             0.041  0.016  0.003  0.975
                                 log_g             0.441  0.167  0.018  0.907
                                 radius            0.220  0.084  0.010  0.933

                                                   MAX_ER  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              0.772
                                 log_g              4.579
                                 radius             2.289

                                                                                                   Percentiles  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              75 : 0.01522 / 90 : 0.04751 / 95 : 0.07984 / 99 : 0.16633
                                 log_g                  75 : 0.132 / 90 : 0.4052 / 95 : 0.95394 / 99 : 2.0776
                                 radius              75 : 0.0659 / 90 : 0.20251 / 95 : 0.47753 / 99 : 1.03974

                                                     time
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             20.404
                                 log_g             20.404
                                 radius            20.404

the fine-tuning improved the results for the extremes but worsened the results for the middle errors

### Random forest

In [8]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              3.362 - 4.518
                                            log_g             -0.384 - 5.345
                                            radius            -0.976 - 2.837

                                                                RVE   RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.957  0.038
                                            log_g             0.808  0.458
                                            radius            0.859  0.229

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.012  0.002
                                            log_g             0.146  0.013
                                            radius            0.073  0.006

                                                               CORR  MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.978   0.823
                                            log_g             0.900   4.610
                                            radius            0.927   2.305

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              75 : 0.00727 / 90 : 0.02909 / 95 : 0.06485 / 99 : 0.16948
                                            log_g              75 : 0.06489 / 90 : 0.28349 / 95 : 0.91433 / 99 : 2.37645
                                            radius             75 : 0.03233 / 90 : 0.14109 / 95 : 0.45622 / 99 : 1.18823

                                                                time
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             82.528
                                            log_g             82.528
                                            radius            82.528

In [9]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              3.362 - 4.518
                                            log_g             -0.384 - 5.345
                                            radius            -0.976 - 2.837

                                                                RVE   RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.960  0.036
                                            log_g             0.845  0.412
                                            radius            0.886  0.206

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.013  0.002
                                            log_g             0.144  0.018
                                            radius            0.072  0.010

                                                               CORR  MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.980   0.757
                                            log_g             0.919   4.548
                                            radius            0.941   2.274

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              75 : 0.00926 / 90 : 0.03408 / 95 : 0.06385 / 99 : 0.15221
                                            log_g              75 : 0.07648 / 90 : 0.33588 / 95 : 0.87895 / 99 : 2.00465
                                            radius             75 : 0.03871 / 90 : 0.16724 / 95 : 0.43928 / 99 : 1.00265

                                                                 time
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             130.496
                                            log_g             130.496
                                            radius            130.496

Improved the results of the extremes but not the middle values

### Decision tree

In [11]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                              value range  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff              3.362 - 4.518
                                         log_g             -0.384 - 5.345
                                         radius            -0.976 - 2.837

                                                             RVE   RMSE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.945  0.042
                                         log_g             0.755  0.518
                                         radius            0.820  0.259

                                                             MAE  MedAE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.013  0.001
                                         log_g             0.150  0.011
                                         radius            0.075  0.006

                                                            CORR  MAX_ER  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.973   0.841
                                         log_g             0.874   4.780
                                         radius            0.908   2.391

                                                                                                          Percentiles  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.1971
                                         log_g               75 : 0.05771 / 90 : 0.22267 / 95 : 0.89572 / 99 : 2.896
                                         radius             75 : 0.02875 / 90 : 0.1113 / 95 : 0.44651 / 99 : 1.44791

                                                            time
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             9.373
                                         log_g             9.373
                                         radius            9.373

In [12]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                              value range  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff              3.362 - 4.518
                                         log_g             -0.384 - 5.345
                                         radius            -0.976 - 2.837

                                                             RVE   RMSE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.953  0.039
                                         log_g             0.830  0.431
                                         radius            0.875  0.216

                                                             MAE  MedAE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.013  0.002
                                         log_g             0.146  0.018
                                         radius            0.073  0.010

                                                            CORR  MAX_ER  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.976   0.831
                                         log_g             0.912   4.668
                                         radius            0.936   2.338

                                                                                                           Percentiles  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff              75 : 0.00927 / 90 : 0.03484 / 95 : 0.06715 / 99 : 0.16304
                                         log_g                75 : 0.07533 / 90 : 0.32033 / 95 : 0.889 / 99 : 2.11669
                                         radius              75 : 0.03816 / 90 : 0.15936 / 95 : 0.44443 / 99 : 1.0593

                                                            time
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             9.327
                                         log_g             9.327
                                         radius            9.327

Improved the results of the extremes but not the middle values

## Comparison between fine tuned models

### T_eff parameter

In [14]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["KNN", "decision_tree"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,PARSEC,scale_power,T_eff,3.362 - 4.518,0.950,3.528%,1.426%,0.226%,0.975,66.834%,75 : 1.317% / 90 : 4.111% / 95 : 6.909% / 99 : 14.393%,20.404
decision_tree,PARSEC,scale_power,T_eff,3.362 - 4.518,0.953,3.402%,1.161%,0.186%,0.976,71.95%,75 : 0.802% / 90 : 3.015% / 95 : 5.811% / 99 : 14.109%,9.327

In [15]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
random_forest,PARSEC,scale_quantile,T_eff,3.362 - 4.518,0.96,3.132%,1.112%,0.19%,0.98,65.527%,75 : 0.801% / 90 : 2.949% / 95 : 5.525% / 99 : 13.172%,130.496

### log_g parameter

In [16]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["KNN", "decision_tree"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,PARSEC,scale_power,log_g,-0.384 - 5.345,0.823,7.691%,2.921%,0.323%,0.907,79.93%,75 : 2.304% / 90 : 7.073% / 95 : 16.651% / 99 : 36.265%,20.404
decision_tree,PARSEC,scale_power,log_g,-0.384 - 5.345,0.830,7.526%,2.556%,0.314%,0.912,81.48%,75 : 1.315% / 90 : 5.591% / 95 : 15.518% / 99 : 36.947%,9.327

In [17]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
random_forest,PARSEC,scale_quantile,log_g,-0.384 - 5.345,0.845,7.185%,2.517%,0.32%,0.919,79.38%,75 : 1.335% / 90 : 5.863% / 95 : 15.342% / 99 : 34.991%,130.496

### Radius parameter

In [18]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["KNN", "decision_tree"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,PARSEC,scale_power,radius,-0.976 - 2.837,0.869,5.78%,2.204%,0.273%,0.933,60.029%,75 : 1.728% / 90 : 5.31% / 95 : 12.522% / 99 : 27.264%,20.404
decision_tree,PARSEC,scale_power,radius,-0.976 - 2.837,0.875,5.654%,1.927%,0.25%,0.936,61.301%,75 : 1.001% / 90 : 4.179% / 95 : 11.654% / 99 : 27.777%,9.327

In [19]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                categories=["Global"],
                model_names=["random_forest"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
random_forest,PARSEC,scale_quantile,radius,-0.976 - 2.837,0.886,5.397%,1.895%,0.252%,0.941,59.636%,75 : 1.015% / 90 : 4.385% / 95 : 11.519% / 99 : 26.291%,130.496

The random forest model gives the best results but the other two models are not far.