# Results comparison for PARSEC with final models of model B

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_B/default_models"
path_fine_tuned = pre_path + "results/model_B/fine_tuned_models"
path_final = pre_path + "results/model_B/final_models"

## Final model results

In [3]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                              value range  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff              3.362 - 4.518
                                         log_g             -0.347 - 5.345
                                         radius            -0.976 - 2.832

                                                             RVE   RMSE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.953  0.039
                                         log_g             0.829  0.432
                                         radius            0.874  0.216

                                                             MAE  MedAE  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.013  0.002
                                         log_g             0.147  0.018
                                         radius            0.074  0.009

                                                            CORR  MAX_ER  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.976   0.810
                                         log_g             0.911   4.770
                                         radius            0.935   2.386

                                                                                                 Percentiles  \
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             75 : 0.009 / 90 : 0.035 / 95 : 0.067 / 99 : 0.164
                                         log_g             75 : 0.073 / 90 : 0.328 / 95 : 0.925 / 99 : 2.093
                                         radius            75 : 0.037 / 90 : 0.164 / 95 : 0.462 / 99 : 1.047

                                                            time
model         physical_model filter      output_parameter
decision_tree PARSEC         scale_power T_eff             0.413
                                         log_g             0.413
                                         radius            0.413

In [ ]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_power"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                      value range    RVE  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              3.362 - 4.518  0.950
                                 log_g             -0.347 - 5.345  0.818
                                 radius            -0.976 - 2.832  0.866

                                                    RMSE    MAE  MedAE   CORR  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             0.041  0.016  0.003  0.975
                                 log_g             0.446  0.169  0.018  0.905
                                 radius            0.223  0.085  0.010  0.931

                                                   MAX_ER  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff              0.785
                                 log_g              4.412
                                 radius             2.206

                                                                                         Percentiles  \
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             75 : 0.015 / 90 : 0.046 / 95 : 0.077 / 99 : 0.168
                                 log_g              75 : 0.127 / 90 : 0.412 / 95 : 0.993 / 99 : 2.09
                                 radius            75 : 0.063 / 90 : 0.206 / 95 : 0.497 / 99 : 1.046

                                                    time
model physical_model filter      output_parameter
KNN   PARSEC         scale_power T_eff             5.096
                                 log_g             5.096
                                 radius            5.096

In [3]:
compare_metrics(path_final, value_rounding=3, relative_values=True,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              3.362 - 4.518
                                            log_g             -0.347 - 5.345
                                            radius            -0.976 - 2.832

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.958  3.214%
                                            log_g             0.841  7.332%
                                            radius            0.882  5.481%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             1.119%  0.188%
                                            log_g             2.576%  0.331%
                                            radius             1.93%  0.258%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             0.979  68.662%
                                            log_g             0.917  76.691%
                                            radius            0.939  57.315%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff              75 : 0.793% / 90 : 2.965% / 95 : 5.536% / 99 : 13.431%
                                            log_g             75 : 1.323% / 90 : 6.133% / 95 : 15.965% / 99 : 35.179%
                                            radius            75 : 1.003% / 90 : 4.561% / 95 : 11.923% / 99 : 26.297%

                                                                time
model         physical_model filter         output_parameter
random_forest PARSEC         scale_quantile T_eff             17.427
                                            log_g             17.427
                                            radius            17.427