# Results comparison for MIST with final models of model A partial

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_A_partial/default_models"
path_fine_tuned = pre_path + "results/model_A_partial/fine_tuned_models"
path_final = pre_path + "results/model_A_partial/final_models"

## Final model results

In [3]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               0.09 - 13.952
                                            radius            -0.976 - 2.832

                                                              RVE   RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              1.0  0.032
                                            radius            1.0  0.008

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              0.006    0.0
                                            radius            0.002    0.0

                                                              CORR  MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               1.0   1.113
                                            radius             1.0   0.315

                                                                                                    Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass                75 : 0.0 / 90 : 0.007 / 95 : 0.032 / 99 : 0.147
                                            radius            75 : 0.001 / 90 : 0.007 / 95 : 0.016 / 99 : 0.031

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              0.691
                                            radius            0.691

In [4]:
compare_metrics(path_final, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range  RVE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               0.09 - 13.952  1.0
                                    radius            -0.976 - 2.832  1.0

                                                       RMSE    MAE  MedAE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              0.018  0.005    0.0
                                    radius            0.004  0.001    0.0

                                                      CORR  MAX_ER  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               1.0   0.817
                                    radius             1.0   0.143

                                                                                            Percentiles  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              75 : 0.002 / 90 : 0.011 / 95 : 0.025 / 99 : 0.078
                                    radius            75 : 0.001 / 90 : 0.003 / 95 : 0.006 / 99 : 0.016

                                                        time
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              17.091
                                    radius            17.091