# Results comparison for PARSEC filtering of model B

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the PARSEC dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

This part was done after the one on MIST so I will only try the filtering which made a positive difference.

In [2]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [3]:
pre_path = "../../../../../../"
path = pre_path + "results/model_B/default_models"

In [4]:
compare_metrics(path, 
                output_parameters=["T_eff"],
                model_names=["decision_tree"],
                physical_models=["PARSEC"])

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.3621 - 4.5177
                             Base_old       T_eff             3.3621 - 4.5177
                             mass_smaller_3 T_eff             3.3621 - 4.1907
                             scale_power    T_eff             3.3621 - 4.5177
                             scale_quantile T_eff             3.3621 - 4.5177
                             scale_robust   T_eff             3.3621 - 4.5177
                             scale_standard T_eff             3.3621 - 4.5177

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9451742472012191
                             Base_old       T_eff             0.9266408296408541
                             mass_smaller_3 T_eff             0.8871586813443988
                             scale_power    T_eff             0.9453531983567844
                             scale_quantile T_eff             0.9454924425303036
                             scale_robust   T_eff             0.9449862108106163
                             scale_standard T_eff             0.9454400175053367

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.042554292673794465
                             Base_old       T_eff             0.042708232796530986
                             mass_smaller_3 T_eff              0.03328590494814946
                             scale_power    T_eff              0.04248474179428776
                             scale_quantile T_eff              0.04243062529498305
                             scale_robust   T_eff              0.04262723673009435
                             scale_standard T_eff              0.04245092382862449

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.012520623599939452
                             Base_old       T_eff             0.015061017757280377
                             mass_smaller_3 T_eff             0.010588167800465901
                             scale_power    T_eff             0.012505704513152338
                             scale_quantile T_eff             0.012510921967176875
                             scale_robust   T_eff             0.012530991134810753
                             scale_standard T_eff             0.012500310903844314

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.001191428571428066
                             Base_old       T_eff             0.0030093023255806095
                             mass_smaller_3 T_eff               0.00101575187969849
                             scale_power    T_eff               0.00118918058185713
                             scale_quantile T_eff             0.0011999999999998678
                             scale_robust   T_eff             0.0011891512046540154
                             scale_standard T_eff             0.0011973684210524471

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9724235183367057
                             Base_old       T_eff             0.9629323431134735
                             mass_smaller_3 T_eff             0.9429494041263922
                             scale_power    T_eff              0.972511433737684
                             scale_quantile T_eff             0.9725796596239012
                             scale_robust   T_eff              0.972325957435005
                             scale_standard T_eff             0.9725590222382688

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                         0.8407
                             Base_old       T_eff             0.8385666666666673
                             mass_smaller_3 T_eff             0.3836999999999997
                             scale_power    T_eff                         0.8407
                             scale_quantile T_eff                         0.8407
                             scale_robust   T_eff                         0.8407
                             scale_standard T_eff                         0.8407

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                             Base_old       T_eff              75 : 0.01239 / 90 : 0.03341 / 95 : 0.07812 / 99 : 0.18114
                             mass_smaller_3 T_eff                75 : 0.00482 / 90 : 0.02104 / 95 : 0.0629 / 99 : 0.1844
                             scale_power    T_eff                  75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.1971
                             scale_quantile T_eff                75 : 0.00664 / 90 : 0.0262 / 95 : 0.06467 / 99 : 0.1974
                             scale_robust   T_eff                75 : 0.0066 / 90 : 0.0262 / 95 : 0.06474 / 99 : 0.19805
                             scale_standard T_eff               75 : 0.0066 / 90 : 0.02611 / 95 : 0.06454 / 99 : 0.19722

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 1.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.3621 - 4.5177
                             Base_old       T_eff             3.3621 - 4.5177
                             mass_smaller_3 T_eff             3.3621 - 4.1907
                             scale_power    T_eff             3.3621 - 4.5177
                             scale_quantile T_eff             3.3621 - 4.5177
                             scale_robust   T_eff             3.3621 - 4.5177
                             scale_standard T_eff             3.3621 - 4.5177

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9748322909531495
                             Base_old       T_eff             0.9646985208110654
                             mass_smaller_3 T_eff              0.975213198122586
                             scale_power    T_eff             0.9753031698008416
                             scale_quantile T_eff             0.9752795584861008
                             scale_robust   T_eff             0.9749175674559253
                             scale_standard T_eff             0.9757503045153407

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.0423812576414891
                             Base_old       T_eff               0.0504197511354913
                             mass_smaller_3 T_eff             0.025525608230402626
                             scale_power    T_eff              0.04197936426549016
                             scale_quantile T_eff              0.04201112413254124
                             scale_robust   T_eff             0.042317808029750464
                             scale_standard T_eff             0.041604061549778415

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.007449396025994484
                             Base_old       T_eff             0.008843633573122251
                             mass_smaller_3 T_eff             0.005852321173799819
                             scale_power    T_eff             0.007407100692190342
                             scale_quantile T_eff             0.007402127563169193
                             scale_robust   T_eff             0.007419384184002267
                             scale_standard T_eff             0.007341559446734046

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             4.999999999988347e-05
                             Base_old       T_eff             4.999999999988347e-05
                             mass_smaller_3 T_eff             6.666666666665932e-05
                             scale_power    T_eff             4.999999999988347e-05
                             scale_quantile T_eff             5.000000000032756e-05
                             scale_robust   T_eff             4.999999999988347e-05
                             scale_standard T_eff             5.000000000032756e-05

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9876003989251159
                             Base_old       T_eff             0.9826770838721797
                             mass_smaller_3 T_eff             0.9879085497518846
                             scale_power    T_eff             0.9878284091690117
                             scale_quantile T_eff             0.9878143829255721
                             scale_robust   T_eff             0.9876376203354993
                             scale_standard T_eff             0.9880496146989258

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8311642857142854
                             Base_old       T_eff             0.8181000000000003
                             mass_smaller_3 T_eff             0.3836999999999997
                             scale_power    T_eff             0.8311642857142854
                             scale_quantile T_eff             0.8342529411764716
                             scale_robust   T_eff             0.8311642857142858
                             scale_standard T_eff             0.8311642857142858

                                                                                                           Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                             Base_old       T_eff               75 : 0.0011 / 90 : 0.0103 / 95 : 0.02628 / 99 : 0.201
                             mass_smaller_3 T_eff              75 : 0.0006 / 90 : 0.0085 / 95 : 0.0246 / 99 : 0.12535
                             scale_power    T_eff              75 : 0.0011 / 90 : 0.0098 / 95 : 0.0247 / 99 : 0.14102
                             scale_quantile T_eff                75 : 0.0012 / 90 : 0.01 / 95 : 0.02459 / 99 : 0.1365
                             scale_robust   T_eff              75 : 0.0011 / 90 : 0.0098 / 95 : 0.0245 / 99 : 0.14125
                             scale_standard T_eff                75 : 0.0011 / 90 : 0.0098 / 95 : 0.0245 / 99 : 0.138

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 2.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              3.6053 - 4.446
                             Base_old       T_eff               3.602 - 4.446
                             mass_smaller_3 T_eff             3.6813 - 4.1397
                             scale_power    T_eff              3.6053 - 4.446
                             scale_quantile T_eff              3.6053 - 4.446
                             scale_robust   T_eff              3.6053 - 4.446
                             scale_standard T_eff              3.6053 - 4.446

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.872460228127739
                             Base_old       T_eff             0.8653488782920009
                             mass_smaller_3 T_eff             0.6049838323957871
                             scale_power    T_eff             0.8744415256893818
                             scale_quantile T_eff             0.8736829102350739
                             scale_robust   T_eff             0.8732613574498688
                             scale_standard T_eff             0.8733647988385779

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.06255115396094892
                             Base_old       T_eff                0.064121708121317
                             mass_smaller_3 T_eff              0.06317765357377349
                             scale_power    T_eff             0.062129597377047284
                             scale_quantile T_eff              0.06226274295500187
                             scale_robust   T_eff               0.0623778883257484
                             scale_standard T_eff              0.06231538504154123

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.03380714142468827
                             Base_old       T_eff             0.034932939805899156
                             mass_smaller_3 T_eff              0.03278852938657706
                             scale_power    T_eff              0.03367641467681891
                             scale_quantile T_eff              0.03377404384220726
                             scale_robust   T_eff              0.03379379673404681
                             scale_standard T_eff               0.0337417893933271

                                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.015225000000000044
                             Base_old       T_eff             0.015500000000000291
                             mass_smaller_3 T_eff             0.009400000000000297
                             scale_power    T_eff             0.015225000000000266
                             scale_quantile T_eff             0.015224999999999822
                             scale_robust   T_eff             0.015200000000000324
                             scale_standard T_eff             0.015200000000000102

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9441691057521153
                             Base_old       T_eff             0.9411344598039713
                             mass_smaller_3 T_eff             0.8925416933006906
                             scale_power    T_eff             0.9449869914976895
                             scale_quantile T_eff             0.9447496545349412
                             scale_robust   T_eff              0.944561942380967
                             scale_standard T_eff             0.9446074534375856

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8240999999999996
                             Base_old       T_eff             0.8071999999999999
                             mass_smaller_3 T_eff             0.2875000000000001
                             scale_power    T_eff             0.8240999999999996
                             scale_quantile T_eff             0.8240999999999996
                             scale_robust   T_eff             0.8240999999999996
                             scale_standard T_eff             0.8240999999999996

                                                                                                             Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                             Base_old       T_eff              75 : 0.0391 / 90 : 0.09034 / 95 : 0.14529 / 99 : 0.24239
                             mass_smaller_3 T_eff              75 : 0.02955 / 90 : 0.11347 / 95 : 0.16941 / 99 : 0.2382
                             scale_power    T_eff                75 : 0.0372 / 90 : 0.08589 / 95 : 0.1409 / 99 : 0.2391
                             scale_quantile T_eff              75 : 0.03721 / 90 : 0.08642 / 95 : 0.14203 / 99 : 0.2392
                             scale_robust   T_eff              75 : 0.03722 / 90 : 0.08631 / 95 : 0.1428 / 99 : 0.23957
                             scale_standard T_eff              75 : 0.03719 / 90 : 0.08584 / 95 : 0.14233 / 99 : 0.2391

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 3.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.4342 - 3.7459
                             Base_old       T_eff             3.4342 - 3.7459
                             mass_smaller_3 T_eff             3.4342 - 3.7459
                             scale_power    T_eff             3.4342 - 3.7459
                             scale_quantile T_eff             3.4342 - 3.7459
                             scale_robust   T_eff             3.4342 - 3.7459
                             scale_standard T_eff             3.4342 - 3.7459

                                                                              RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             -0.7632012932187855
                             Base_old       T_eff             -0.7446428496459467
                             mass_smaller_3 T_eff             -0.5234705113818034
                             scale_power    T_eff             -0.7596825040201673
                             scale_quantile T_eff              -0.759553384754228
                             scale_robust   T_eff             -0.7618045724566715
                             scale_standard T_eff              -0.765712135862846

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.062014552223464726
                             Base_old       T_eff              0.06199437972179435
                             mass_smaller_3 T_eff              0.05848860953001508
                             scale_power    T_eff              0.06194870480825839
                             scale_quantile T_eff             0.061964446949296106
                             scale_robust   T_eff             0.061992688715608396
                             scale_standard T_eff               0.0620593780875414

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.027219918269213918
                             Base_old       T_eff             0.027880328284992886
                             mass_smaller_3 T_eff             0.028422840214358244
                             scale_power    T_eff             0.027203063486938215
                             scale_quantile T_eff             0.027212503851392386
                             scale_robust   T_eff              0.02724340379308805
                             scale_standard T_eff             0.027232969450512973

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0037571428571430143
                             Base_old       T_eff              0.004349999999999632
                             mass_smaller_3 T_eff              0.003509999999999014
                             scale_power    T_eff             0.0037579159212879354
                             scale_quantile T_eff             0.0037599999999999856
                             scale_robust   T_eff              0.003756538461537895
                             scale_standard T_eff             0.0037610810810808637

                                                                             CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.124189042946256
                             Base_old       T_eff             0.12999551271619822
                             mass_smaller_3 T_eff             0.11942462598385166
                             scale_power    T_eff             0.12450767903155473
                             scale_quantile T_eff             0.12500378804352452
                             scale_robust   T_eff             0.12379439602130168
                             scale_standard T_eff             0.12322660736756483

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8298000000000001
                             Base_old       T_eff             0.8385666666666673
                             mass_smaller_3 T_eff             0.2891999999999997
                             scale_power    T_eff             0.8298000000000001
                             scale_quantile T_eff             0.8298000000000001
                             scale_robust   T_eff             0.8298000000000001
                             scale_standard T_eff             0.8298000000000001

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                             Base_old       T_eff              75 : 0.02405 / 90 : 0.09619 / 95 : 0.14095 / 99 : 0.23488
                             mass_smaller_3 T_eff              75 : 0.02726 / 90 : 0.10436 / 95 : 0.14774 / 99 : 0.22839
                             scale_power    T_eff                75 : 0.022 / 90 : 0.09585 / 95 : 0.14382 / 99 : 0.23645
                             scale_quantile T_eff                75 : 0.02192 / 90 : 0.0962 / 95 : 0.14422 / 99 : 0.2366
                             scale_robust   T_eff              75 : 0.02197 / 90 : 0.09647 / 95 : 0.14432 / 99 : 0.23693
                             scale_standard T_eff                75 : 0.0219 / 90 : 0.09647 / 95 : 0.1443 / 99 : 0.23645

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 4.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.5328 - 3.786
                             Base_old       T_eff             3.5301 - 3.786
                             mass_smaller_3 T_eff             3.6191 - 3.786
                             scale_power    T_eff             3.5328 - 3.786
                             scale_quantile T_eff             3.5328 - 3.786
                             scale_robust   T_eff             3.5328 - 3.786
                             scale_standard T_eff             3.5328 - 3.786

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.5441135519545068
                             Base_old       T_eff             0.4919354858527928
                             mass_smaller_3 T_eff             0.9242961999199967
                             scale_power    T_eff             0.5351324084733762
                             scale_quantile T_eff             0.5507394226764424
                             scale_robust   T_eff             0.5270607090720028
                             scale_standard T_eff             0.5280927951335781

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.020721238317739282
                             Base_old       T_eff             0.022068366528774426
                             mass_smaller_3 T_eff             0.007156302955568765
                             scale_power    T_eff              0.02092435136642098
                             scale_quantile T_eff                0.020570109742884
                             scale_robust   T_eff              0.02110522778155409
                             scale_standard T_eff             0.021082189338980886

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0038289243446757216
                             Base_old       T_eff              0.005905391575893141
                             mass_smaller_3 T_eff             0.0030461141057490874
                             scale_power    T_eff              0.003833482378760664
                             scale_quantile T_eff             0.0038218529356632033
                             scale_robust   T_eff             0.0038422804955559648
                             scale_standard T_eff             0.0038492563218812214

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0007587628865994844
                             Base_old       T_eff             0.0016611628857552407
                             mass_smaller_3 T_eff             0.0008441558441583119
                             scale_power    T_eff             0.0007586956521747901
                             scale_quantile T_eff             0.0007589928057547546
                             scale_robust   T_eff             0.0007587301587297368
                             scale_standard T_eff             0.0007587301587301809

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.7961889196467123
                             Base_old       T_eff             0.7769222769874299
                             mass_smaller_3 T_eff             0.9626419908201415
                             scale_power    T_eff             0.7925872052261775
                             scale_quantile T_eff             0.7988385196849132
                             scale_robust   T_eff             0.7900331363309497
                             scale_standard T_eff              0.790574363196574

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                          0.8407
                             Base_old       T_eff              0.8258000000000001
                             mass_smaller_3 T_eff             0.24480000000000013
                             scale_power    T_eff                          0.8407
                             scale_quantile T_eff                          0.8407
                             scale_robust   T_eff                          0.8407
                             scale_standard T_eff                          0.8407

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                             Base_old       T_eff              75 : 0.00662 / 90 : 0.01444 / 95 : 0.02037 / 99 : 0.04379
                             mass_smaller_3 T_eff               75 : 0.00318 / 90 : 0.00748 / 95 : 0.01282 / 99 : 0.0312
                             scale_power    T_eff              75 : 0.00315 / 90 : 0.00744 / 95 : 0.01302 / 99 : 0.03654
                             scale_quantile T_eff              75 : 0.00315 / 90 : 0.00745 / 95 : 0.01303 / 99 : 0.03688
                             scale_robust   T_eff               75 : 0.00315 / 90 : 0.00744 / 95 : 0.01299 / 99 : 0.0365
                             scale_standard T_eff              75 : 0.00315 / 90 : 0.00745 / 95 : 0.01304 / 99 : 0.03653

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 5.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              3.5642 - 4.272
                             Base_old       T_eff              3.5644 - 4.272
                             mass_smaller_3 T_eff             3.6805 - 3.8635
                             scale_power    T_eff              3.5642 - 4.272
                             scale_quantile T_eff              3.5642 - 4.272
                             scale_robust   T_eff              3.5642 - 4.272
                             scale_standard T_eff              3.5642 - 4.272

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.875456632791973
                             Base_old       T_eff             0.8420309857438173
                             mass_smaller_3 T_eff              0.867553551301494
                             scale_power    T_eff             0.8718856861813428
                             scale_quantile T_eff              0.872901526456852
                             scale_robust   T_eff             0.8759638416807798
                             scale_standard T_eff             0.8753790213593057

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.0404003814429823
                             Base_old       T_eff              0.04552491349501501
                             mass_smaller_3 T_eff             0.013122882060035538
                             scale_power    T_eff             0.040980890371482344
                             scale_quantile T_eff              0.04081356629000664
                             scale_robust   T_eff              0.04031796340221164
                             scale_standard T_eff               0.0404132368445149

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.009523709897636998
                             Base_old       T_eff              0.012801870846465514
                             mass_smaller_3 T_eff             0.0015745356602996682
                             scale_power    T_eff                 0.009569231163593
                             scale_quantile T_eff              0.009579287217081574
                             scale_robust   T_eff               0.00948631266370027
                             scale_standard T_eff               0.00949295469255584

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             4.440892098500626e-16
                             Base_old       T_eff             4.440892098500626e-16
                             mass_smaller_3 T_eff                               0.0
                             scale_power    T_eff             4.440892098500626e-16
                             scale_quantile T_eff             4.440892098500626e-16
                             scale_robust   T_eff             4.440892098500626e-16
                             scale_standard T_eff             4.440892098500626e-16

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9382230012465637
                             Base_old       T_eff             0.9245126669295642
                             mass_smaller_3 T_eff             0.9400210765627829
                             scale_power    T_eff             0.9365445651005092
                             scale_quantile T_eff             0.9370107967865656
                             scale_robust   T_eff             0.9384350097349261
                             scale_standard T_eff             0.9381838713498403

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.7346999999999997
                             Base_old       T_eff              0.5848999999999998
                             mass_smaller_3 T_eff             0.31820000000000004
                             scale_power    T_eff              0.7346999999999997
                             scale_quantile T_eff              0.7346999999999997
                             scale_robust   T_eff              0.7346999999999997
                             scale_standard T_eff              0.7346999999999997

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                 75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                             Base_old       T_eff               75 : 0.0034 / 90 : 0.02434 / 95 : 0.08046 / 99 : 0.21703
                             mass_smaller_3 T_eff                   75 : 5e-05 / 90 : 0.0001 / 95 : 0.0021 / 99 : 0.0425
                             scale_power    T_eff               75 : 0.0018 / 90 : 0.01565 / 95 : 0.04047 / 99 : 0.21893
                             scale_quantile T_eff              75 : 0.00175 / 90 : 0.01599 / 95 : 0.04077 / 99 : 0.22361
                             scale_robust   T_eff                 75 : 0.0018 / 90 : 0.0158 / 95 : 0.0404 / 99 : 0.21364
                             scale_standard T_eff               75 : 0.00176 / 90 : 0.0157 / 95 : 0.04042 / 99 : 0.21364

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

Results for the label category with a value of 6.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.5416 - 4.2601
                             Base_old       T_eff             3.5437 - 4.2601
                             mass_smaller_3 T_eff             3.6516 - 3.8551
                             scale_power    T_eff             3.5416 - 4.2601
                             scale_quantile T_eff             3.5416 - 4.2601
                             scale_robust   T_eff             3.5416 - 4.2601
                             scale_standard T_eff             3.5416 - 4.2601

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9361134687179025
                             Base_old       T_eff             0.8509271515153556
                             mass_smaller_3 T_eff             0.9344208412339422
                             scale_power    T_eff             0.9335271417804964
                             scale_quantile T_eff             0.9341691024450434
                             scale_robust   T_eff             0.9313804625450004
                             scale_standard T_eff             0.9343331922797743

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.038817942968688686
                             Base_old       T_eff             0.060310058384806735
                             mass_smaller_3 T_eff             0.009947309738953879
                             scale_power    T_eff              0.03958689424028262
                             scale_quantile T_eff              0.03939935103992178
                             scale_robust   T_eff              0.04022850879357127
                             scale_standard T_eff               0.0393516246296966

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.010905352896371222
                             Base_old       T_eff              0.02210327067054398
                             mass_smaller_3 T_eff             0.003275683015649687
                             scale_power    T_eff             0.011083440367978955
                             scale_quantile T_eff              0.01103665181290483
                             scale_robust   T_eff             0.011206948515997303
                             scale_standard T_eff             0.010951768457800964

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0035000000000007248
                             Base_old       T_eff             0.0040000000000000036
                             mass_smaller_3 T_eff              0.001966666666666672
                             scale_power    T_eff             0.0035000000000007248
                             scale_quantile T_eff             0.0035000000000002807
                             scale_robust   T_eff             0.0035000000000005027
                             scale_standard T_eff             0.0035000000000002807

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9682850567668624
                             Base_old       T_eff             0.9331089743270826
                             mass_smaller_3 T_eff             0.9679753590180824
                             scale_power    T_eff             0.9670225527037652
                             scale_quantile T_eff             0.9673093167946908
                             scale_robust   T_eff              0.965932565824477
                             scale_standard T_eff             0.9674263717777054

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.7282999999999995
                             Base_old       T_eff             0.7282999999999995
                             mass_smaller_3 T_eff                         0.2946
                             scale_power    T_eff             0.7282999999999995
                             scale_quantile T_eff             0.7282999999999995
                             scale_robust   T_eff             0.7282999999999995
                             scale_standard T_eff             0.7282999999999995

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                             Base_old       T_eff                 75 : 0.012 / 90 : 0.05822 / 95 : 0.1444 / 99 : 0.26733
                             mass_smaller_3 T_eff              75 : 0.00418 / 90 : 0.00735 / 95 : 0.00924 / 99 : 0.01914
                             scale_power    T_eff                  75 : 0.0094 / 90 : 0.0183 / 95 : 0.0315 / 99 : 0.1909
                             scale_quantile T_eff                 75 : 0.0093 / 90 : 0.0183 / 95 : 0.0315 / 99 : 0.19653
                             scale_robust   T_eff               75 : 0.00933 / 90 : 0.0183 / 95 : 0.03173 / 99 : 0.19868
                             scale_standard T_eff               75 : 0.0094 / 90 : 0.01814 / 95 : 0.03146 / 99 : 0.18655

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814
                             scale_power    T_eff               9.37336254119873
                             scale_quantile T_eff             5.3814921379089355
                             scale_robust   T_eff              5.470540761947632
                             scale_standard T_eff              4.587049961090088

In [5]:
compare_metrics(path, value_rounding=6,
                output_parameters=["T_eff", "radius", "log_g"],
                physical_models=["PARSEC"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                                   value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
KNN               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
linear_regression PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
mlp               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
random_forest     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
xgboost           PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.945174  0.042554
                                        log_g             0.753657  0.519054
                                        radius            0.818880  0.259482
KNN               PARSEC         Base   T_eff             0.928991  0.048511
                                        log_g             0.796923  0.471456
                                        radius            0.850453  0.235877
linear_regression PARSEC         Base   T_eff             0.344458  0.147146
                                        log_g             0.174017  0.950443
                                        radius            0.306153  0.507872
mlp               PARSEC         Base   T_eff             0.456675  0.134103
                                        log_g             0.507586  0.734551
                                        radius            0.622855  0.374986
random_forest     PARSEC         Base   T_eff             0.956661  0.037835
                                        log_g             0.807427  0.458925
                                        radius            0.858417  0.229420
xgboost           PARSEC         Base   T_eff             0.772632  0.086659
                                        log_g             0.720714  0.552669
                                        radius            0.794523  0.276379

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.012521  0.001191
                                        log_g             0.150609  0.011000
                                        radius            0.075279  0.005673
KNN               PARSEC         Base   T_eff             0.016210  0.001880
                                        log_g             0.168647  0.013200
                                        radius            0.084686  0.007273
linear_regression PARSEC         Base   T_eff             0.108064  0.075052
                                        log_g             0.750716  0.505290
                                        radius            0.397538  0.274545
mlp               PARSEC         Base   T_eff             0.093483  0.064096
                                        log_g             0.501094  0.259584
                                        radius            0.253643  0.133197
random_forest     PARSEC         Base   T_eff             0.012196  0.001501
                                        log_g             0.146241  0.012717
                                        radius            0.073068  0.006440
xgboost           PARSEC         Base   T_eff             0.044921  0.012216
                                        log_g             0.313614  0.107134
                                        radius            0.156982  0.054236

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.972424  0.840700
                                        log_g             0.873827  4.780000
                                        radius            0.907855  2.390815
KNN               PARSEC         Base   T_eff             0.963858  0.829140
                                        log_g             0.893518  4.635400
                                        radius            0.922797  2.317238
linear_regression PARSEC         Base   T_eff             0.586906  0.545711
                                        log_g             0.417154  3.354960
                                        radius            0.553311  1.781259
mlp               PARSEC         Base   T_eff             0.687641  0.832390
                                        log_g             0.712461  3.893786
                                        radius            0.789215  1.990677
random_forest     PARSEC         Base   T_eff             0.978124  0.828999
                                        log_g             0.899847  4.620864
                                        radius            0.927173  2.310296
xgboost           PARSEC         Base   T_eff             0.879159  0.686212
                                        log_g             0.849413  4.357621
                                        radius            0.891569  2.261232

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                                        log_g                75 : 0.05772 / 90 : 0.22267 / 95 : 0.89533 / 99 : 2.907
                                        radius              75 : 0.02877 / 90 : 0.11129 / 95 : 0.4465 / 99 : 1.45363
KNN               PARSEC         Base   T_eff                75 : 0.0133 / 90 : 0.0398 / 95 : 0.07538 / 99 : 0.20009
                                        log_g                 75 : 0.0886 / 90 : 0.4462 / 95 : 1.0346 / 99 : 2.24206
                                        radius             75 : 0.04507 / 90 : 0.22252 / 95 : 0.51756 / 99 : 1.12183
linear_regression PARSEC         Base   T_eff              75 : 0.14234 / 90 : 0.27293 / 95 : 0.32016 / 99 : 0.42868
                                        log_g              75 : 1.13119 / 90 : 1.62211 / 95 : 1.88341 / 99 : 2.41107
                                        radius             75 : 0.58813 / 90 : 0.83923 / 95 : 1.02037 / 99 : 1.42151
mlp               PARSEC         Base   T_eff                75 : 0.11522 / 90 : 0.20538 / 95 : 0.285 / 99 : 0.50069
                                        log_g              75 : 0.73311 / 90 : 1.41779 / 95 : 1.65723 / 99 : 2.18019
                                        radius             75 : 0.37949 / 90 : 0.71574 / 95 : 0.85022 / 99 : 1.08968
random_forest     PARSEC         Base   T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                        log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                        radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
xgboost           PARSEC         Base   T_eff              75 : 0.05362 / 90 : 0.13639 / 95 : 0.20195 / 99 : 0.34634
                                        log_g               75 : 0.40285 / 90 : 0.95171 / 95 : 1.2855 / 99 : 2.01364
                                        radius             75 : 0.19952 / 90 : 0.47689 / 95 : 0.64069 / 99 : 1.00851

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 1.0

                                                                   value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
KNN               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
linear_regression PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
mlp               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
random_forest     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
xgboost           PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.974832  0.042381
                                        log_g            -0.223663  0.380474
                                        radius            0.736372  0.190422
KNN               PARSEC         Base   T_eff             0.925539  0.074090
                                        log_g            -0.568551  0.443320
                                        radius            0.660043  0.222548
linear_regression PARSEC         Base   T_eff             0.597294  0.215205
                                        log_g            -1.225249  1.473679
                                        radius            0.291126  0.808124
mlp               PARSEC         Base   T_eff             0.590721  0.176664
                                        log_g            -4.371544  1.063488
                                        radius           -0.176376  0.543708
random_forest     PARSEC         Base   T_eff             0.982664  0.035351
                                        log_g             0.172115  0.315988
                                        radius            0.821605  0.158164
xgboost           PARSEC         Base   T_eff             0.903544  0.089629
                                        log_g            -1.012488  0.553560
                                        radius            0.566261  0.276740

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.007449  0.000050
                                        log_g             0.067495  0.000750
                                        radius            0.034093  0.000399
KNN               PARSEC         Base   T_eff             0.019715  0.002020
                                        log_g             0.134608  0.007000
                                        radius            0.069347  0.004956
linear_regression PARSEC         Base   T_eff             0.180860  0.137110
                                        log_g             1.383983  1.318829
                                        radius            0.747075  0.675373
mlp               PARSEC         Base   T_eff             0.125399  0.092680
                                        log_g             0.779041  0.578822
                                        radius            0.401638  0.286798
random_forest     PARSEC         Base   T_eff             0.007342  0.000192
                                        log_g             0.070260  0.000980
                                        radius            0.035333  0.000566
xgboost           PARSEC         Base   T_eff             0.043701  0.016440
                                        log_g             0.319178  0.090964
                                        radius            0.160672  0.051169

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.987600  0.831164
                                        log_g             0.705340  4.780000
                                        radius            0.891072  2.390815
KNN               PARSEC         Base   T_eff             0.962302  0.826320
                                        log_g             0.726834  4.513000
                                        radius            0.885902  2.256155
linear_regression PARSEC         Base   T_eff             0.853645  0.545711
                                        log_g             0.337036  3.354960
                                        radius            0.633163  1.781259
mlp               PARSEC         Base   T_eff             0.777345  0.832390
                                        log_g             0.779206  2.711008
                                        radius            0.783845  1.383009
random_forest     PARSEC         Base   T_eff             0.991400  0.769496
                                        log_g             0.775979  4.226316
                                        radius            0.922800  2.112811
xgboost           PARSEC         Base   T_eff             0.951354  0.686212
                                        log_g             0.809582  3.585431
                                        radius            0.882597  1.706742

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                                        log_g                     75 : 0.006 / 90 : 0.026 / 95 : 0.064 / 99 : 1.9685
                                        radius             75 : 0.00335 / 90 : 0.01452 / 95 : 0.03433 / 99 : 0.98432
KNN               PARSEC         Base   T_eff               75 : 0.0082 / 90 : 0.03622 / 95 : 0.06993 / 99 : 0.43359
                                        log_g                  75 : 0.0274 / 90 : 0.2318 / 95 : 0.848 / 99 : 2.22856
                                        radius             75 : 0.01813 / 90 : 0.11851 / 95 : 0.42461 / 99 : 1.12036
linear_regression PARSEC         Base   T_eff              75 : 0.25535 / 90 : 0.36302 / 95 : 0.41855 / 99 : 0.48298
                                        log_g               75 : 1.74379 / 90 : 2.02828 / 95 : 2.27583 / 99 : 2.7985
                                        radius              75 : 0.91055 / 90 : 1.1884 / 95 : 1.39367 / 99 : 1.62448
mlp               PARSEC         Base   T_eff                75 : 0.1533 / 90 : 0.27528 / 95 : 0.39784 / 99 : 0.6293
                                        log_g              75 : 1.51463 / 90 : 1.68943 / 95 : 1.85061 / 99 : 2.26065
                                        radius              75 : 0.76117 / 90 : 0.89535 / 95 : 0.96146 / 99 : 1.1454
random_forest     PARSEC         Base   T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                        log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                        radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
xgboost           PARSEC         Base   T_eff              75 : 0.04522 / 90 : 0.09853 / 95 : 0.19258 / 99 : 0.44504
                                        log_g              75 : 0.43347 / 90 : 1.03051 / 95 : 1.34273 / 99 : 1.90141
                                        radius             75 : 0.21204 / 90 : 0.51508 / 95 : 0.66892 / 99 : 0.95761

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 2.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
KNN               PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
linear_regression PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
mlp               PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
random_forest     PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
xgboost           PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.872460  0.062551
                                        log_g             0.201081  0.756121
                                        radius            0.564531  0.378084
KNN               PARSEC         Base   T_eff             0.901921  0.056525
                                        log_g             0.551332  0.592130
                                        radius            0.755423  0.296099
linear_regression PARSEC         Base   T_eff             0.245804  0.157645
                                        log_g             0.207291  0.804882
                                        radius            0.538604  0.404651
mlp               PARSEC         Base   T_eff            -0.060497  0.201686
                                        log_g             0.420183  0.948966
                                        radius            0.658256  0.477307
random_forest     PARSEC         Base   T_eff             0.899761  0.055911
                                        log_g             0.462614  0.632273
                                        radius            0.707102  0.316149
xgboost           PARSEC         Base   T_eff             0.242135  0.163469
                                        log_g             0.350010  0.832163
                                        radius            0.644051  0.417444

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.033807  0.015225
                                        log_g             0.302998  0.060000
                                        radius            0.151568  0.030172
KNN               PARSEC         Base   T_eff             0.036253  0.022300
                                        log_g             0.307196  0.091600
                                        radius            0.153682  0.045965
linear_regression PARSEC         Base   T_eff             0.125799  0.104393
                                        log_g             0.664043  0.612538
                                        radius            0.330807  0.299524
mlp               PARSEC         Base   T_eff             0.150167  0.111460
                                        log_g             0.809776  0.832247
                                        radius            0.407418  0.413264
random_forest     PARSEC         Base   T_eff             0.032529  0.016365
                                        log_g             0.289372  0.068061
                                        radius            0.144739  0.034069
xgboost           PARSEC         Base   T_eff             0.123031  0.089585
                                        log_g             0.671362  0.584957
                                        radius            0.336568  0.292945

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.944169  0.824100
                                        log_g             0.654394  4.171000
                                        radius            0.780179  2.086107
KNN               PARSEC         Base   T_eff             0.954199  0.636320
                                        log_g             0.769385  3.967000
                                        radius            0.869666  1.983172
linear_regression PARSEC         Base   T_eff             0.498101  0.511006
                                        log_g             0.493105  2.888378
                                        radius            0.736236  1.543650
mlp               PARSEC         Base   T_eff             0.269180  0.771006
                                        log_g             0.652164  2.375106
                                        radius            0.819324  1.263273
random_forest     PARSEC         Base   T_eff             0.954951  0.765904
                                        log_g             0.737427  3.682990
                                        radius            0.845059  1.841073
xgboost           PARSEC         Base   T_eff             0.507815  0.675210
                                        log_g             0.612090  2.695528
                                        radius            0.802798  1.372651

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                                        log_g              75 : 0.15628 / 90 : 1.01729 / 95 : 1.81952 / 99 : 3.37886
                                        radius             75 : 0.07811 / 90 : 0.50835 / 95 : 0.91068 / 99 : 1.68888
KNN               PARSEC         Base   T_eff              75 : 0.04752 / 90 : 0.08675 / 95 : 0.11641 / 99 : 0.19029
                                        log_g                 75 : 0.2642 / 90 : 1.089 / 95 : 1.41552 / 99 : 2.27112
                                        radius              75 : 0.13204 / 90 : 0.54463 / 95 : 0.7077 / 99 : 1.13544
linear_regression PARSEC         Base   T_eff               75 : 0.17836 / 90 : 0.26213 / 95 : 0.3129 / 99 : 0.41535
                                        log_g              75 : 0.93956 / 90 : 1.24051 / 95 : 1.47758 / 99 : 2.09846
                                        radius               75 : 0.4692 / 90 : 0.6187 / 95 : 0.74639 / 99 : 1.09896
mlp               PARSEC         Base   T_eff              75 : 0.20893 / 90 : 0.34079 / 95 : 0.43468 / 99 : 0.60504
                                        log_g              75 : 1.17152 / 90 : 1.42053 / 95 : 1.61857 / 99 : 2.05238
                                        radius             75 : 0.58918 / 90 : 0.71959 / 95 : 0.80987 / 99 : 1.03145
random_forest     PARSEC         Base   T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                        log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                        radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
xgboost           PARSEC         Base   T_eff              75 : 0.17025 / 90 : 0.27651 / 95 : 0.35297 / 99 : 0.48104
                                        log_g               75 : 1.02779 / 90 : 1.3463 / 95 : 1.53656 / 99 : 1.99333
                                        radius              75 : 0.51575 / 90 : 0.67511 / 95 : 0.7715 / 99 : 1.00317

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 3.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
KNN               PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
linear_regression PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
mlp               PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
random_forest     PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
xgboost           PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff            -0.763201  0.062015
                                        log_g            -0.434244  0.980673
                                        radius           -0.029463  0.490364
KNN               PARSEC         Base   T_eff            -0.419654  0.056569
                                        log_g            -0.096894  0.871944
                                        radius            0.212646  0.436015
linear_regression PARSEC         Base   T_eff            -3.483451  0.128916
                                        log_g             0.168726  1.037678
                                        radius            0.402397  0.533016
mlp               PARSEC         Base   T_eff            -3.062654  0.116005
                                        log_g             0.201798  0.878777
                                        radius            0.414377  0.442644
random_forest     PARSEC         Base   T_eff            -0.502332  0.057579
                                        log_g            -0.172120  0.891969
                                        radius            0.158655  0.446023
xgboost           PARSEC         Base   T_eff            -1.921797  0.096128
                                        log_g             0.063088  0.883823
                                        radius            0.328160  0.441498

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.027220  0.003757
                                        log_g             0.470673  0.066188
                                        radius            0.235384  0.033231
KNN               PARSEC         Base   T_eff             0.027020  0.006720
                                        log_g             0.462166  0.109500
                                        radius            0.231142  0.054727
linear_regression PARSEC         Base   T_eff             0.097209  0.074184
                                        log_g             0.824557  0.648371
                                        radius            0.427083  0.344557
mlp               PARSEC         Base   T_eff             0.087439  0.064049
                                        log_g             0.633527  0.384099
                                        radius            0.319721  0.195172
random_forest     PARSEC         Base   T_eff             0.026189  0.004677
                                        log_g             0.451075  0.077399
                                        radius            0.225588  0.038764
xgboost           PARSEC         Base   T_eff             0.061889  0.025207
                                        log_g             0.596223  0.360110
                                        radius            0.297539  0.180217

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.124189  0.829800
                                        log_g             0.240076  4.770000
                                        radius            0.484329  2.385359
KNN               PARSEC         Base   T_eff             0.165105  0.813280
                                        log_g             0.304296  4.635400
                                        radius            0.558678  2.317238
linear_regression PARSEC         Base   T_eff             0.101690  0.380102
                                        log_g             0.410993  2.857540
                                        radius            0.638608  1.423368
mlp               PARSEC         Base   T_eff             0.075250  0.615613
                                        log_g             0.457470  3.893786
                                        radius            0.647683  1.990677
random_forest     PARSEC         Base   T_eff             0.167062  0.806513
                                        log_g             0.306816  4.620864
                                        radius            0.545958  2.310296
xgboost           PARSEC         Base   T_eff             0.050497  0.386060
                                        log_g             0.299175  4.357621
                                        radius            0.574539  2.261232

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                                        log_g                75 : 0.42077 / 90 : 1.80427 / 95 : 2.529 / 99 : 3.83062
                                        radius              75 : 0.21021 / 90 : 0.9022 / 95 : 1.26428 / 99 : 1.91484
KNN               PARSEC         Base   T_eff              75 : 0.02926 / 90 : 0.08358 / 95 : 0.12637 / 99 : 0.21296
                                        log_g                 75 : 0.6006 / 90 : 1.5316 / 95 : 2.08425 / 99 : 3.6946
                                        radius              75 : 0.3004 / 90 : 0.76603 / 95 : 1.04217 / 99 : 1.84744
linear_regression PARSEC         Base   T_eff               75 : 0.13101 / 90 : 0.2356 / 95 : 0.29718 / 99 : 0.33842
                                        log_g              75 : 1.22793 / 90 : 1.78372 / 95 : 2.15088 / 99 : 2.44176
                                        radius             75 : 0.63518 / 90 : 0.90864 / 95 : 1.08583 / 99 : 1.23233
mlp               PARSEC         Base   T_eff              75 : 0.12108 / 90 : 0.18899 / 95 : 0.22475 / 99 : 0.37096
                                        log_g              75 : 0.85527 / 90 : 1.63268 / 95 : 2.02307 / 99 : 2.49201
                                        radius              75 : 0.44388 / 90 : 0.81582 / 95 : 1.00769 / 99 : 1.2349
random_forest     PARSEC         Base   T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                        log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                        radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
xgboost           PARSEC         Base   T_eff              75 : 0.09793 / 90 : 0.17076 / 95 : 0.22502 / 99 : 0.30108
                                        log_g               75 : 0.87508 / 90 : 1.49202 / 95 : 1.96052 / 99 : 2.9245
                                        radius             75 : 0.43744 / 90 : 0.74514 / 95 : 0.97449 / 99 : 1.46297

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 4.0

                                                                 value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
KNN               PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
linear_regression PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
mlp               PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
random_forest     PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
xgboost           PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.544114  0.020721
                                        log_g             0.899619  0.126899
                                        radius            0.955620  0.063414
KNN               PARSEC         Base   T_eff             0.690416  0.017076
                                        log_g             0.888276  0.133877
                                        radius            0.950486  0.066981
linear_regression PARSEC         Base   T_eff            -7.161325  0.090873
                                        log_g             0.418097  0.496098
                                        radius            0.708437  0.261443
mlp               PARSEC         Base   T_eff            -4.487443  0.078045
                                        log_g             0.708946  0.320924
                                        radius            0.821596  0.165257
random_forest     PARSEC         Base   T_eff             0.659119  0.017918
                                        log_g             0.914544  0.117086
                                        radius            0.962170  0.058548
xgboost           PARSEC         Base   T_eff            -0.301430  0.036494
                                        log_g             0.787074  0.200925
                                        radius            0.906795  0.099651

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.003829  0.000759
                                        log_g             0.043147  0.008836
                                        radius            0.021592  0.004420
KNN               PARSEC         Base   T_eff             0.004156  0.000400
                                        log_g             0.048033  0.004200
                                        radius            0.024017  0.002118
linear_regression PARSEC         Base   T_eff             0.060694  0.043600
                                        log_g             0.396976  0.344840
                                        radius            0.209695  0.188876
mlp               PARSEC         Base   T_eff             0.059086  0.049751
                                        log_g             0.246660  0.205930
                                        radius            0.116761  0.080204
random_forest     PARSEC         Base   T_eff             0.003897  0.000786
                                        log_g             0.042945  0.009043
                                        radius            0.021492  0.004535
xgboost           PARSEC         Base   T_eff             0.013120  0.003837
                                        log_g             0.107666  0.046317
                                        radius            0.053422  0.023086

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.796189  0.840700
                                        log_g             0.949517  3.528500
                                        radius            0.977688  1.765034
KNN               PARSEC         Base   T_eff             0.850168  0.829140
                                        log_g             0.944124  3.500000
                                        radius            0.975185  1.750620
linear_regression PARSEC         Base   T_eff            -0.214811  0.373937
                                        log_g             0.648387  1.892872
                                        radius            0.887672  0.961278
mlp               PARSEC         Base   T_eff             0.023312  0.617142
                                        log_g             0.874021  2.014782
                                        radius            0.919896  1.173495
random_forest     PARSEC         Base   T_eff             0.836128  0.828999
                                        log_g             0.956704  3.485594
                                        radius            0.980933  1.743523
xgboost           PARSEC         Base   T_eff             0.377211  0.401789
                                        log_g             0.893052  1.619970
                                        radius            0.957776  0.789785

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                                        log_g               75 : 0.04239 / 90 : 0.10199 / 95 : 0.1735 / 99 : 0.49256
                                        radius             75 : 0.02116 / 90 : 0.05107 / 95 : 0.08715 / 99 : 0.24579
KNN               PARSEC         Base   T_eff               75 : 0.00184 / 90 : 0.0122 / 95 : 0.02378 / 99 : 0.04028
                                        log_g                 75 : 0.0172 / 90 : 0.1798 / 95 : 0.3366 / 99 : 0.50174
                                        radius             75 : 0.00859 / 90 : 0.08998 / 95 : 0.16848 / 99 : 0.25098
linear_regression PARSEC         Base   T_eff                75 : 0.06806 / 90 : 0.11643 / 95 : 0.26577 / 99 : 0.323
                                        log_g              75 : 0.43839 / 90 : 0.51863 / 95 : 1.25134 / 99 : 1.52105
                                        radius             75 : 0.23824 / 90 : 0.28693 / 95 : 0.64321 / 99 : 0.78988
mlp               PARSEC         Base   T_eff              75 : 0.07231 / 90 : 0.10066 / 95 : 0.15498 / 99 : 0.27496
                                        log_g               75 : 0.29286 / 90 : 0.4783 / 95 : 0.73003 / 99 : 0.95422
                                        radius             75 : 0.15069 / 90 : 0.24565 / 95 : 0.36761 / 99 : 0.57346
random_forest     PARSEC         Base   T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                        log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                        radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
xgboost           PARSEC         Base   T_eff              75 : 0.00977 / 90 : 0.01972 / 95 : 0.05406 / 99 : 0.19767
                                        log_g              75 : 0.11966 / 90 : 0.26802 / 95 : 0.40739 / 99 : 0.93169
                                        radius             75 : 0.05941 / 90 : 0.13327 / 95 : 0.19754 / 99 : 0.46263

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 5.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
KNN               PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
linear_regression PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
mlp               PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
random_forest     PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
xgboost           PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.875457  0.040400
                                        log_g             0.953366  0.157175
                                        radius            0.976161  0.074551
KNN               PARSEC         Base   T_eff             0.895290  0.037110
                                        log_g             0.963847  0.138793
                                        radius            0.981003  0.066772
linear_regression PARSEC         Base   T_eff             0.135462  0.161486
                                        log_g             0.467854  0.775188
                                        radius            0.693621  0.412488
mlp               PARSEC         Base   T_eff            -0.292731  0.137099
                                        log_g             0.698659  0.426937
                                        radius            0.790557  0.245640
random_forest     PARSEC         Base   T_eff             0.907909  0.034739
                                        log_g             0.966655  0.132915
                                        radius            0.983322  0.062359
xgboost           PARSEC         Base   T_eff             0.464624  0.085826
                                        log_g             0.805141  0.329745
                                        radius            0.890970  0.164608

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.009524  0.000000
                                        log_g             0.037557  0.001000
                                        radius            0.017089  0.000572
KNN               PARSEC         Base   T_eff             0.014543  0.001100
                                        log_g             0.054556  0.004000
                                        radius            0.025789  0.001905
linear_regression PARSEC         Base   T_eff             0.137198  0.113176
                                        log_g             0.660304  0.612615
                                        radius            0.361341  0.342135
mlp               PARSEC         Base   T_eff             0.106358  0.081960
                                        log_g             0.320239  0.220317
                                        radius            0.183394  0.131973
random_forest     PARSEC         Base   T_eff             0.009529  0.000437
                                        log_g             0.038265  0.001490
                                        radius            0.017504  0.000767
xgboost           PARSEC         Base   T_eff             0.059022  0.034366
                                        log_g             0.225442  0.129193
                                        radius            0.112802  0.066267

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.938223  0.734700
                                        log_g             0.976862  3.008000
                                        radius            0.988134  1.505778
KNN               PARSEC         Base   T_eff             0.946298  0.540500
                                        log_g             0.981920  2.025000
                                        radius            0.990546  1.024449
linear_regression PARSEC         Base   T_eff             0.403575  0.345670
                                        log_g             0.700818  2.042203
                                        radius            0.840505  1.087498
mlp               PARSEC         Base   T_eff             0.342565  0.547152
                                        log_g             0.861605  1.689766
                                        radius            0.904402  1.072072
random_forest     PARSEC         Base   T_eff             0.953477  0.502608
                                        log_g             0.983314  2.000681
                                        radius            0.991657  1.017307
xgboost           PARSEC         Base   T_eff             0.682035  0.553807
                                        log_g             0.899644  2.021328
                                        radius            0.945786  0.991914

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                                        log_g                  75 : 0.005 / 90 : 0.061 / 95 : 0.16786 / 99 : 0.82728
                                        radius             75 : 0.00213 / 90 : 0.02711 / 95 : 0.07076 / 99 : 0.37473
KNN               PARSEC         Base   T_eff               75 : 0.0147 / 90 : 0.03722 / 95 : 0.06555 / 99 : 0.18111
                                        log_g                  75 : 0.0546 / 90 : 0.142 / 95 : 0.2453 / 99 : 0.67312
                                        radius             75 : 0.02562 / 90 : 0.06674 / 95 : 0.11563 / 99 : 0.32208
linear_regression PARSEC         Base   T_eff               75 : 0.1915 / 90 : 0.28075 / 95 : 0.30894 / 99 : 0.33665
                                        log_g                75 : 1.0052 / 90 : 1.23247 / 95 : 1.3198 / 99 : 1.42503
                                        radius                75 : 0.52905 / 90 : 0.63795 / 95 : 0.68 / 99 : 0.75724
mlp               PARSEC         Base   T_eff                75 : 0.13316 / 90 : 0.2293 / 95 : 0.2998 / 99 : 0.40241
                                        log_g              75 : 0.49825 / 90 : 0.75493 / 95 : 0.87557 / 99 : 1.11006
                                        radius              75 : 0.26965 / 90 : 0.42654 / 95 : 0.50947 / 99 : 0.6911
random_forest     PARSEC         Base   T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                        log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                        radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
xgboost           PARSEC         Base   T_eff              75 : 0.08836 / 90 : 0.14542 / 95 : 0.18122 / 99 : 0.26898
                                        log_g              75 : 0.33553 / 90 : 0.56962 / 95 : 0.69518 / 99 : 1.03312
                                        radius             75 : 0.17244 / 90 : 0.27989 / 95 : 0.34668 / 99 : 0.52946

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 6.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
KNN               PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
linear_regression PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
mlp               PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
random_forest     PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
xgboost           PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.936113  0.038818
                                        log_g             0.931182  0.156010
                                        radius            0.959084  0.077104
KNN               PARSEC         Base   T_eff             0.941800  0.037079
                                        log_g             0.937685  0.148530
                                        radius            0.962970  0.073369
linear_regression PARSEC         Base   T_eff             0.207644  0.167819
                                        log_g            -0.725237  0.977894
                                        radius           -0.178027  0.522385
mlp               PARSEC         Base   T_eff             0.032534  0.151943
                                        log_g             0.459459  0.482814
                                        radius            0.618041  0.272027
random_forest     PARSEC         Base   T_eff             0.951628  0.033786
                                        log_g             0.948539  0.134992
                                        radius            0.969767  0.066327
xgboost           PARSEC         Base   T_eff             0.665456  0.089052
                                        log_g             0.629975  0.375169
                                        radius            0.769793  0.190582

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.010905  0.003500
                                        log_g             0.046622  0.018000
                                        radius            0.022777  0.008704
KNN               PARSEC         Base   T_eff             0.020029  0.011480
                                        log_g             0.083939  0.052700
                                        radius            0.041668  0.026158
linear_regression PARSEC         Base   T_eff             0.142558  0.127134
                                        log_g             0.895162  0.873074
                                        radius            0.481581  0.476142
mlp               PARSEC         Base   T_eff             0.120788  0.098131
                                        log_g             0.401809  0.355319
                                        radius            0.224031  0.198615
random_forest     PARSEC         Base   T_eff             0.010590  0.003122
                                        log_g             0.045004  0.015024
                                        radius            0.021995  0.007358
xgboost           PARSEC         Base   T_eff             0.067525  0.051502
                                        log_g             0.294228  0.240937
                                        radius            0.149886  0.123946

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.968285  0.728300
                                        log_g             0.965900  3.018000
                                        radius            0.979618  1.533441
KNN               PARSEC         Base   T_eff             0.970561  0.508160
                                        log_g             0.968447  2.108800
                                        radius            0.981376  1.089249
linear_regression PARSEC         Base   T_eff             0.478529  0.367166
                                        log_g             0.274212  2.013739
                                        radius            0.586775  1.075930
mlp               PARSEC         Base   T_eff             0.418413  0.508366
                                        log_g             0.680063  1.551814
                                        radius            0.790952  0.940885
random_forest     PARSEC         Base   T_eff             0.975645  0.549174
                                        log_g             0.974096  2.152537
                                        radius            0.984808  1.111063
xgboost           PARSEC         Base   T_eff             0.823540  0.316487
                                        log_g             0.794052  1.366310
                                        radius            0.878279  0.765709

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                                        log_g                    75 : 0.043 / 90 : 0.08 / 95 : 0.1315 / 99 : 0.70731
                                        radius              75 : 0.0216 / 90 : 0.03985 / 95 : 0.06493 / 99 : 0.33128
KNN               PARSEC         Base   T_eff              75 : 0.02298 / 90 : 0.04069 / 95 : 0.06435 / 99 : 0.15869
                                        log_g                 75 : 0.0988 / 90 : 0.1666 / 95 : 0.24706 / 99 : 0.6304
                                        radius             75 : 0.04965 / 90 : 0.08372 / 95 : 0.12244 / 99 : 0.30325
linear_regression PARSEC         Base   T_eff              75 : 0.20855 / 90 : 0.27287 / 95 : 0.30722 / 99 : 0.34225
                                        log_g              75 : 1.20825 / 90 : 1.42198 / 95 : 1.52277 / 99 : 1.68722
                                        radius              75 : 0.63804 / 90 : 0.74171 / 95 : 0.7997 / 99 : 0.91087
mlp               PARSEC         Base   T_eff               75 : 0.1697 / 90 : 0.25914 / 95 : 0.30838 / 99 : 0.39154
                                        log_g              75 : 0.59017 / 90 : 0.78507 / 95 : 0.89144 / 99 : 1.05907
                                        radius               75 : 0.32184 / 90 : 0.44405 / 95 : 0.51372 / 99 : 0.646
random_forest     PARSEC         Base   T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                        log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                        radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
xgboost           PARSEC         Base   T_eff               75 : 0.0978 / 90 : 0.14934 / 95 : 0.18727 / 99 : 0.24988
                                        log_g              75 : 0.42278 / 90 : 0.62987 / 95 : 0.77118 / 99 : 0.98055
                                        radius             75 : 0.21694 / 90 : 0.31853 / 95 : 0.38254 / 99 : 0.50061

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

## Getting the ranges for the values

In [6]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=False)

iso_unscaled_df = iso_handler.get_isochrone_dataframe()
display(iso_unscaled_df)
phase_filtered_iso_unscaled_df = Data_preparator.filter_data(iso_unscaled_df, {'label':[1, 2, 3, 4, 5, 6]})
print_all_uniques(phase_filtered_iso_unscaled_df)

Reading PARSEC dataframe from PARSEC_iso_full_data.csv file...

          logAge   logTe   logg  label  metallicity   Mass     Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090    1.636 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092    1.656 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098    1.725 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100    1.747 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106    1.811 -0.608
...          ...     ...    ...    ...          ...    ...      ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  143.400  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  149.900  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  156.500  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  164.400  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  154.100  3.204

[681303 rows x 8 columns]

logAge  : Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3

logTe  : Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721

logg  : Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428

Rpol  : Range : 0.11 - 687.5, Mean : 25.9755, Median : 10.37

logL  : Range : -3.42 - 4.8, Mean : 1.9902, Median : 1.855

In [9]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading PARSEC dataframe from PARSEC_rescaled_iso_full_data.csv file...

          logAge   logTe   logg  label  metallicity   Mass      Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090  0.213783 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092  0.219060 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098  0.236789 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100  0.242293 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106  0.257918 -0.608
...          ...     ...    ...    ...          ...    ...       ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  2.156549  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  2.175802  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  2.194514  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  2.215902  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  2.187803  3.204

[681303 rows x 8 columns]

In [11]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'label':[1, 2, 3, 4, 5, 6, 7]})
print_all_uniques(phase_filtered_iso_df)

logAge  : Range : 5.3 - 10.25, Mean : 9.1668, Median : 9.4

logTe  : Range : 3.36 - 4.5177, Mean : 3.7418, Median : 3.7133

logg  : Range : -0.66 - 5.345, Mean : 2.4609, Median : 2.429

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 13.952, Mean : 2.3888, Median : 1.345

Rpol  : Range : -0.98 - 2.9727, Mean : 1.0977, Median : 1.0445

logL  : Range : -3.42 - 4.968, Mean : 2.1118, Median : 1.905

## Comparing each model's results to keep the best ones with PARSEC dataset

### Linear regression

#### T_eff parameter

In [14]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             3.362 - 4.518
                                 Base_old       T_eff             3.362 - 4.518
                                 mass_smaller_3 T_eff             3.362 - 4.191
                                 scale_power    T_eff             3.362 - 4.518
                                 scale_quantile T_eff             3.362 - 4.518
                                 scale_robust   T_eff             3.362 - 4.518
                                 scale_standard T_eff             3.362 - 4.518

                                                                    RVE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             0.344
                                 Base_old       T_eff             0.248
                                 mass_smaller_3 T_eff             0.257
                                 scale_power    T_eff             0.288
                                 scale_quantile T_eff             0.256
                                 scale_robust   T_eff             0.344
                                 scale_standard T_eff             0.344

                                                                     RMSE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             12.733%
                                 Base_old       T_eff             11.832%
                                 mass_smaller_3 T_eff              10.31%
                                 scale_power    T_eff             13.267%
                                 scale_quantile T_eff             13.561%
                                 scale_robust   T_eff             12.733%
                                 scale_standard T_eff             12.733%

                                                                     MAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             9.351%
                                 Base_old       T_eff             7.903%
                                 mass_smaller_3 T_eff             7.729%
                                 scale_power    T_eff             9.707%
                                 scale_quantile T_eff             9.977%
                                 scale_robust   T_eff             9.351%
                                 scale_standard T_eff             9.351%

                                                                   MedAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             6.495%
                                 Base_old       T_eff             4.403%
                                 mass_smaller_3 T_eff             5.754%
                                 scale_power    T_eff             6.914%
                                 scale_quantile T_eff             7.398%
                                 scale_robust   T_eff             6.495%
                                 scale_standard T_eff             6.495%

                                                                   CORR  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             0.587
                                 Base_old       T_eff             0.498
                                 mass_smaller_3 T_eff             0.507
                                 scale_power    T_eff             0.537
                                 scale_quantile T_eff             0.506
                                 scale_robust   T_eff             0.587
                                 scale_standard T_eff             0.587

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             47.223%
                                 Base_old       T_eff             52.834%
                                 mass_smaller_3 T_eff              38.62%
                                 scale_power    T_eff             47.973%
                                 scale_quantile T_eff             51.154%
                                 scale_robust   T_eff             47.223%
                                 scale_standard T_eff             47.223%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%
                                 Base_old       T_eff             75 : 10.476% / 90 : 21.316% / 95 : 25.841% / 99 : 41.072%
                                 mass_smaller_3 T_eff             75 : 10.967% / 90 : 16.691% / 95 : 22.468% / 99 : 31.057%
                                 scale_power    T_eff               75 : 12.337% / 90 : 23.864% / 95 : 28.92% / 99 : 40.88%
                                 scale_quantile T_eff             75 : 12.621% / 90 : 23.093% / 95 : 29.267% / 99 : 43.133%
                                 scale_robust   T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%
                                 scale_standard T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%

                                                                   time
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           T_eff             0.358
                                 Base_old       T_eff             0.499
                                 mass_smaller_3 T_eff             0.274
                                 scale_power    T_eff             5.075
                                 scale_quantile T_eff             1.082
                                 scale_robust   T_eff             0.524
                                 scale_standard T_eff             0.423

Base, scale_standard et scale_robust donne les meilleurs résultats

#### log_g

In [15]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             -0.384 - 5.345
                                 Base_old       log_g             -0.664 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345

                                                                    RVE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             0.174
                                 Base_old       log_g             0.133
                                 mass_smaller_3 log_g             0.278
                                 scale_power    log_g             0.307
                                 scale_quantile log_g             0.274
                                 scale_robust   log_g             0.174
                                 scale_standard log_g             0.174

                                                                     RMSE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g              16.59%
                                 Base_old       log_g             16.191%
                                 mass_smaller_3 log_g             13.715%
                                 scale_power    log_g             15.196%
                                 scale_quantile log_g             15.549%
                                 scale_robust   log_g              16.59%
                                 scale_standard log_g              16.59%

                                                                      MAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             13.104%
                                 Base_old       log_g             10.822%
                                 mass_smaller_3 log_g             10.512%
                                 scale_power    log_g             11.679%
                                 scale_quantile log_g             12.038%
                                 scale_robust   log_g             13.104%
                                 scale_standard log_g             13.104%

                                                                   MedAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g              8.82%
                                 Base_old       log_g             4.342%
                                 mass_smaller_3 log_g             7.486%
                                 scale_power    log_g             7.197%
                                 scale_quantile log_g             8.791%
                                 scale_robust   log_g              8.82%
                                 scale_standard log_g              8.82%

                                                                   CORR  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             0.417
                                 Base_old       log_g             0.365
                                 mass_smaller_3 log_g             0.527
                                 scale_power    log_g             0.554
                                 scale_quantile log_g             0.524
                                 scale_robust   log_g             0.417
                                 scale_standard log_g             0.417

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             58.561%
                                 Base_old       log_g             61.079%
                                 mass_smaller_3 log_g             51.263%
                                 scale_power    log_g             48.812%
                                 scale_quantile log_g             54.104%
                                 scale_robust   log_g             58.561%
                                 scale_standard log_g             58.561%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%
                                 Base_old       log_g             75 : 18.694% / 90 : 30.784% / 95 : 35.339% / 99 : 44.086%
                                 mass_smaller_3 log_g             75 : 13.243% / 90 : 24.428% / 95 : 30.299% / 99 : 38.431%
                                 scale_power    log_g              75 : 19.212% / 90 : 27.035% / 95 : 30.81% / 99 : 36.535%
                                 scale_quantile log_g               75 : 19.87% / 90 : 26.84% / 95 : 29.953% / 99 : 38.288%
                                 scale_robust   log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%
                                 scale_standard log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%

                                                                   time
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           log_g             0.358
                                 Base_old       log_g             0.499
                                 mass_smaller_3 log_g             0.274
                                 scale_power    log_g             5.075
                                 scale_quantile log_g             1.082
                                 scale_robust   log_g             0.524
                                 scale_standard log_g             0.423

scale_power et scale_quantile donne les meilleurs résultats

#### Radius parameter

In [13]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["linear_regression"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            -0.976 - 2.837
                                 Base_old       radius            -0.976 - 2.973
                                 mass_smaller_3 radius            -0.976 - 2.363
                                 scale_power    radius            -0.976 - 2.837
                                 scale_quantile radius            -0.976 - 2.837
                                 scale_robust   radius            -0.976 - 2.837
                                 scale_standard radius            -0.976 - 2.837

                                                                    RVE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            0.306
                                 Base_old       radius            0.268
                                 mass_smaller_3 radius            0.331
                                 scale_power    radius            0.482
                                 scale_quantile radius            0.418
                                 scale_robust   radius            0.306
                                 scale_standard radius            0.306

                                                                     RMSE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            13.317%
                                 Base_old       radius             12.97%
                                 mass_smaller_3 radius            12.159%
                                 scale_power    radius            11.508%
                                 scale_quantile radius            12.196%
                                 scale_robust   radius            13.317%
                                 scale_standard radius            13.317%

                                                                      MAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            10.424%
                                 Base_old       radius              8.67%
                                 mass_smaller_3 radius             9.387%
                                 scale_power    radius             8.826%
                                 scale_quantile radius             9.516%
                                 scale_robust   radius            10.424%
                                 scale_standard radius            10.424%

                                                                   MedAE  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            7.199%
                                 Base_old       radius            3.638%
                                 mass_smaller_3 radius              6.9%
                                 scale_power    radius            5.401%
                                 scale_quantile radius            7.428%
                                 scale_robust   radius            7.199%
                                 scale_standard radius            7.199%

                                                                   CORR  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            0.553
                                 Base_old       radius            0.517
                                 mass_smaller_3 radius            0.576
                                 scale_power    radius            0.694
                                 scale_quantile radius            0.647
                                 scale_robust   radius            0.553
                                 scale_standard radius            0.553

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            46.708%
                                 Base_old       radius            49.112%
                                 mass_smaller_3 radius            43.776%
                                 scale_power    radius             37.13%
                                 scale_quantile radius            42.509%
                                 scale_robust   radius            46.708%
                                 scale_standard radius            46.708%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            75 : 15.422% / 90 : 22.006% / 95 : 26.756% / 99 : 37.275%
                                 Base_old       radius            75 : 14.617% / 90 : 24.018% / 95 : 28.274% / 99 : 37.145%
                                 mass_smaller_3 radius             75 : 11.71% / 90 : 21.728% / 95 : 26.777% / 99 : 33.912%
                                 scale_power    radius             75 : 14.73% / 90 : 20.479% / 95 : 23.026% / 99 : 28.056%
                                 scale_quantile radius             75 : 15.342% / 90 : 20.682% / 95 : 23.157% / 99 : 31.07%
                                 scale_robust   radius            75 : 15.422% / 90 : 22.006% / 95 : 26.756% / 99 : 37.275%
                                 scale_standard radius            75 : 15.422% / 90 : 22.006% / 95 : 26.756% / 99 : 37.275%

                                                                   time
model             physical_model filter         output_parameter
linear_regression PARSEC         Base           radius            0.358
                                 Base_old       radius            0.499
                                 mass_smaller_3 radius            0.274
                                 scale_power    radius            5.075
                                 scale_quantile radius            1.082
                                 scale_robust   radius            0.524
                                 scale_standard radius            0.423

scale_power et scale_quantile donne les meilleurs résultats

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour le log_g et le rayon et donne de bons résultats pour la T_eff

linear_regression	PARSEC	scale_power	T_eff	3.362 - 4.518	0.288	13.267%	9.707%	6.914%	0.537	47.973%	75 : 12.337% / 90 : 23.864% / 95 : 28.92% / 99 : 40.88%	5.075

linear_regression	PARSEC	scale_power	log_g	-0.384 - 5.345	0.307	15.196%	11.679%	7.197%	0.554	48.812%	75 : 19.212% / 90 : 27.035% / 95 : 30.81% / 99 : 36.535%	5.075

linear_regression	PARSEC	scale_power	radius	-0.976 - 2.837	0.482	11.508%	8.826%	5.401%	0.694	37.13%	75 : 14.73% / 90 : 20.479% / 95 : 23.026% / 99 : 28.056%	5.075

### Decision tree

#### T_eff parameter

In [16]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.362 - 4.518
                             Base_old       T_eff             3.362 - 4.518
                             mass_smaller_3 T_eff             3.362 - 4.191
                             scale_power    T_eff             3.362 - 4.518
                             scale_quantile T_eff             3.362 - 4.518
                             scale_robust   T_eff             3.362 - 4.518
                             scale_standard T_eff             3.362 - 4.518

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.945  3.682%
                             Base_old       T_eff             0.927  3.696%
                             mass_smaller_3 T_eff             0.887  4.017%
                             scale_power    T_eff             0.945  3.676%
                             scale_quantile T_eff             0.945  3.672%
                             scale_robust   T_eff             0.945  3.689%
                             scale_standard T_eff             0.945  3.673%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             1.083%  0.103%
                             Base_old       T_eff             1.303%   0.26%
                             mass_smaller_3 T_eff             1.278%  0.123%
                             scale_power    T_eff             1.082%  0.103%
                             scale_quantile T_eff             1.083%  0.104%
                             scale_robust   T_eff             1.084%  0.103%
                             scale_standard T_eff             1.082%  0.104%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.972   72.75%
                             Base_old       T_eff             0.963  72.565%
                             mass_smaller_3 T_eff             0.943  46.307%
                             scale_power    T_eff             0.973   72.75%
                             scale_quantile T_eff             0.973   72.75%
                             scale_robust   T_eff             0.972   72.75%
                             scale_standard T_eff             0.973   72.75%

                                                                                                         Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.111%
                             Base_old       T_eff              75 : 1.072% / 90 : 2.891% / 95 : 6.76% / 99 : 15.675%
                             mass_smaller_3 T_eff             75 : 0.582% / 90 : 2.539% / 95 : 7.591% / 99 : 22.254%
                             scale_power    T_eff             75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.056%
                             scale_quantile T_eff             75 : 0.575% / 90 : 2.267% / 95 : 5.596% / 99 : 17.082%
                             scale_robust   T_eff             75 : 0.571% / 90 : 2.267% / 95 : 5.602% / 99 : 17.138%
                             scale_standard T_eff             75 : 0.571% / 90 : 2.259% / 95 : 5.585% / 99 : 17.066%

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             6.434
                             Base_old       T_eff             8.568
                             mass_smaller_3 T_eff             4.517
                             scale_power    T_eff             9.373
                             scale_quantile T_eff             5.381
                             scale_robust   T_eff             5.471
                             scale_standard T_eff             4.587

scale_quantile, scale_standard et scale_power donnent les meilleurs résultats

#### log_g

In [17]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             -0.384 - 5.345
                             Base_old       log_g             -0.664 - 5.345
                             mass_smaller_3 log_g             -0.384 - 5.345
                             scale_power    log_g             -0.384 - 5.345
                             scale_quantile log_g             -0.384 - 5.345
                             scale_robust   log_g             -0.384 - 5.345
                             scale_standard log_g             -0.384 - 5.345

                                                                RVE     RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             0.754    9.06%
                             Base_old       log_g             0.760   8.517%
                             mass_smaller_3 log_g             0.614  10.022%
                             scale_power    log_g             0.755   9.036%
                             scale_quantile log_g             0.754   9.051%
                             scale_robust   log_g             0.753   9.069%
                             scale_standard log_g             0.754   9.055%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             2.629%  0.192%
                             Base_old       log_g             3.185%  0.566%
                             mass_smaller_3 log_g              3.01%  0.183%
                             scale_power    log_g             2.624%  0.192%
                             scale_quantile log_g             2.626%  0.192%
                             scale_robust   log_g             2.631%  0.192%
                             scale_standard log_g             2.626%  0.192%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             0.874  83.435%
                             Base_old       log_g             0.875  79.381%
                             mass_smaller_3 log_g             0.800  82.912%
                             scale_power    log_g             0.874  83.435%
                             scale_quantile log_g             0.874  83.435%
                             scale_robust   log_g             0.874  83.435%
                             scale_standard log_g             0.874  83.261%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             75 : 1.008% / 90 : 3.887% / 95 : 15.628% / 99 : 50.742%
                             Base_old       log_g              75 : 2.29% / 90 : 7.074% / 95 : 18.605% / 99 : 42.087%
                             mass_smaller_3 log_g              75 : 0.95% / 90 : 5.029% / 95 : 21.103% / 99 : 54.128%
                             scale_power    log_g              75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.55%
                             scale_quantile log_g              75 : 1.007% / 90 : 3.884% / 95 : 15.59% / 99 : 50.555%
                             scale_robust   log_g             75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.777%
                             scale_standard log_g             75 : 1.007% / 90 : 3.878% / 95 : 15.583% / 99 : 50.704%

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           log_g             6.434
                             Base_old       log_g             8.568
                             mass_smaller_3 log_g             4.517
                             scale_power    log_g             9.373
                             scale_quantile log_g             5.381
                             scale_robust   log_g             5.471
                             scale_standard log_g             4.587

scale_quantile, scale_standard et scale_power donnent les meilleurs résultats

#### Radius parameter

In [18]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            -0.976 - 2.837
                             Base_old       radius            -0.976 - 2.973
                             mass_smaller_3 radius            -0.976 - 2.363
                             scale_power    radius            -0.976 - 2.837
                             scale_quantile radius            -0.976 - 2.837
                             scale_robust   radius            -0.976 - 2.837
                             scale_standard radius            -0.976 - 2.837

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            0.819  6.804%
                             Base_old       radius            0.817  6.485%
                             mass_smaller_3 radius            0.666  8.598%
                             scale_power    radius            0.820  6.786%
                             scale_quantile radius            0.819  6.797%
                             scale_robust   radius            0.819   6.81%
                             scale_standard radius            0.819    6.8%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            1.974%  0.149%
                             Base_old       radius            2.427%  0.435%
                             mass_smaller_3 radius            2.585%  0.163%
                             scale_power    radius             1.97%  0.149%
                             scale_quantile radius            1.972%   0.15%
                             scale_robust   radius            1.976%  0.149%
                             scale_standard radius            1.972%  0.149%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            0.908  62.692%
                             Base_old       radius            0.906  60.403%
                             mass_smaller_3 radius            0.827  71.122%
                             scale_power    radius            0.908  62.692%
                             scale_quantile radius            0.908  62.692%
                             scale_robust   radius            0.908  62.692%
                             scale_standard radius            0.908  62.549%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 38.117%
                             Base_old       radius             75 : 1.745% / 90 : 5.383% / 95 : 14.165% / 99 : 32.04%
                             mass_smaller_3 radius            75 : 0.812% / 90 : 4.333% / 95 : 18.095% / 99 : 46.401%
                             scale_power    radius            75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 37.967%
                             scale_quantile radius            75 : 0.754% / 90 : 2.917% / 95 : 11.656% / 99 : 37.991%
                             scale_robust   radius            75 : 0.754% / 90 : 2.919% / 95 : 11.708% / 99 : 38.146%
                             scale_standard radius             75 : 0.754% / 90 : 2.91% / 95 : 11.654% / 99 : 38.099%

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           radius            6.434
                             Base_old       radius            8.568
                             mass_smaller_3 radius            4.517
                             scale_power    radius            9.373
                             scale_quantile radius            5.381
                             scale_robust   radius            5.471
                             scale_standard radius            4.587

scale_quantile et scale_power donnent les meilleurs résultats

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour tous les paramètres.

decision_tree	PARSEC	scale_power	T_eff	3.362 - 4.518	0.945	3.676%	1.082%	0.103%	0.973	72.75%	75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.056%	9.373

decision_tree	PARSEC	scale_power	log_g	-0.384 - 5.345	0.755	9.036%	2.624%	0.192%	0.874	83.435%	75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.55%	9.373

decision_tree	PARSEC	scale_power	radius	-0.976 - 2.837	0.820	6.786%	1.97%	0.149%	0.908	62.692%	75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 37.967%	9.373

### KNN

#### T_eff parameter

In [19]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                        value range    RVE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           T_eff             3.362 - 4.518  0.929
                     Base_old       T_eff             3.362 - 4.518  0.912
                     mass_smaller_3 T_eff             3.362 - 4.191  0.910
                     scale_power    T_eff             3.362 - 4.518  0.957
                     scale_quantile T_eff             3.362 - 4.518  0.956
                     scale_robust   T_eff             3.362 - 4.518  0.937
                     scale_standard T_eff             3.362 - 4.518  0.948

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           T_eff             4.198%  1.403%  0.163%
                     Base_old       T_eff             4.061%  1.542%  0.261%
                     mass_smaller_3 T_eff             3.584%   1.38%  0.147%
                     scale_power    T_eff             3.282%  1.214%  0.159%
                     scale_quantile T_eff             3.312%  1.247%  0.168%
                     scale_robust   T_eff             3.968%  1.361%  0.171%
                     scale_standard T_eff             3.587%  1.304%  0.183%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           T_eff             0.964   71.75%
                     Base_old       T_eff             0.955  75.121%
                     mass_smaller_3 T_eff             0.954  51.834%
                     scale_power    T_eff             0.978  70.377%
                     scale_quantile T_eff             0.978   71.75%
                     scale_robust   T_eff             0.968  71.753%
                     scale_standard T_eff             0.974  71.753%

                                                                                                 Percentiles  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           T_eff             75 : 1.151% / 90 : 3.444% / 95 : 6.523% / 99 : 17.315%
                     Base_old       T_eff             75 : 1.658% / 90 : 3.917% / 95 : 7.015% / 99 : 15.226%
                     mass_smaller_3 T_eff               75 : 0.92% / 90 : 3.958% / 95 : 7.304% / 99 : 17.38%
                     scale_power    T_eff             75 : 1.038% / 90 : 3.294% / 95 : 5.877% / 99 : 13.936%
                     scale_quantile T_eff             75 : 1.139% / 90 : 3.397% / 95 : 5.966% / 99 : 13.818%
                     scale_robust   T_eff              75 : 1.153% / 90 : 3.399% / 95 : 6.342% / 99 : 16.34%
                     scale_standard T_eff             75 : 1.182% / 90 : 3.384% / 95 : 6.063% / 99 : 14.922%

                                                       time
model physical_model filter         output_parameter
KNN   PARSEC         Base           T_eff             2.859
                     Base_old       T_eff             5.449
                     mass_smaller_3 T_eff             2.906
                     scale_power    T_eff             7.433
                     scale_quantile T_eff             3.562
                     scale_robust   T_eff             2.831
                     scale_standard T_eff             2.785

scale_power et scale_quantile donnent les meilleurs résultats

#### log_g

In [20]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           log_g             -0.384 - 5.345  0.797
                     Base_old       log_g             -0.664 - 5.345  0.782
                     mass_smaller_3 log_g             -0.384 - 5.345  0.707
                     scale_power    log_g             -0.384 - 5.345  0.814
                     scale_quantile log_g             -0.384 - 5.345  0.813
                     scale_robust   log_g             -0.384 - 5.345  0.801
                     scale_standard log_g             -0.384 - 5.345  0.808

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           log_g             8.229%  2.944%   0.23%
                     Base_old       log_g             8.117%  3.467%  0.439%
                     mass_smaller_3 log_g              8.73%  3.103%  0.161%
                     scale_power    log_g             7.879%  2.764%  0.209%
                     scale_quantile log_g             7.893%  2.784%  0.237%
                     scale_robust   log_g             8.138%  2.899%  0.237%
                     scale_standard log_g             7.995%  2.837%  0.244%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           log_g             0.894  80.911%
                     Base_old       log_g             0.885  77.237%
                     mass_smaller_3 log_g             0.843  80.904%
                     scale_power    log_g             0.903  80.911%
                     scale_quantile log_g             0.902  80.908%
                     scale_robust   log_g             0.896  80.911%
                     scale_standard log_g             0.900  80.911%

                                                                                                   Percentiles  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           log_g              75 : 1.547% / 90 : 7.788% / 95 : 18.059% / 99 : 39.135%
                     Base_old       log_g             75 : 3.238% / 90 : 10.225% / 95 : 18.655% / 99 : 35.647%
                     mass_smaller_3 log_g               75 : 1.082% / 90 : 9.935% / 95 : 20.15% / 99 : 40.547%
                     scale_power    log_g              75 : 1.421% / 90 : 7.136% / 95 : 16.486% / 99 : 37.924%
                     scale_quantile log_g              75 : 1.473% / 90 : 7.115% / 95 : 16.467% / 99 : 37.892%
                     scale_robust   log_g              75 : 1.519% / 90 : 7.593% / 95 : 17.645% / 99 : 38.791%
                     scale_standard log_g                 75 : 1.48% / 90 : 7.38% / 95 : 17.05% / 99 : 38.297%

                                                       time
model physical_model filter         output_parameter
KNN   PARSEC         Base           log_g             2.859
                     Base_old       log_g             5.449
                     mass_smaller_3 log_g             2.906
                     scale_power    log_g             7.433
                     scale_quantile log_g             3.562
                     scale_robust   log_g             2.831
                     scale_standard log_g             2.785

scale_power et scale_quantile donnent les meilleurs résultats

#### Radius parameter

In [21]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           radius            -0.976 - 2.837  0.850
                     Base_old       radius            -0.976 - 2.973  0.834
                     mass_smaller_3 radius            -0.976 - 2.363  0.746
                     scale_power    radius            -0.976 - 2.837  0.863
                     scale_quantile radius            -0.976 - 2.837  0.862
                     scale_robust   radius            -0.976 - 2.837  0.854
                     scale_standard radius            -0.976 - 2.837  0.859

                                                        RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           radius            6.185%  2.221%  0.191%
                     Base_old       radius            6.183%  2.648%  0.352%
                     mass_smaller_3 radius            7.492%   2.68%  0.156%
                     scale_power    radius            5.918%  2.083%  0.181%
                     scale_quantile radius            5.938%  2.117%  0.195%
                     scale_robust   radius            6.117%   2.19%  0.196%
                     scale_standard radius            6.011%  2.153%  0.207%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           radius            0.923  60.762%
                     Base_old       radius            0.914  58.901%
                     mass_smaller_3 radius            0.865  69.381%
                     scale_power    radius            0.929  60.762%
                     scale_quantile radius            0.929   60.76%
                     scale_robust   radius            0.924  60.762%
                     scale_standard radius            0.927  60.762%

                                                                                                  Percentiles  \
model physical_model filter         output_parameter
KNN   PARSEC         Base           radius            75 : 1.182% / 90 : 5.835% / 95 : 13.571% / 99 : 29.416%
                     Base_old       radius             75 : 2.467% / 90 : 7.783% / 95 : 14.21% / 99 : 27.153%
                     mass_smaller_3 radius              75 : 1.0% / 90 : 8.527% / 95 : 17.289% / 99 : 34.798%
                     scale_power    radius            75 : 1.067% / 90 : 5.347% / 95 : 12.383% / 99 : 28.486%
                     scale_quantile radius            75 : 1.176% / 90 : 5.389% / 95 : 12.365% / 99 : 28.477%
                     scale_robust   radius            75 : 1.178% / 90 : 5.696% / 95 : 13.257% / 99 : 29.171%
                     scale_standard radius            75 : 1.187% / 90 : 5.535% / 95 : 12.811% / 99 : 28.772%

                                                       time
model physical_model filter         output_parameter
KNN   PARSEC         Base           radius            2.859
                     Base_old       radius            5.449
                     mass_smaller_3 radius            2.906
                     scale_power    radius            7.433
                     scale_quantile radius            3.562
                     scale_robust   radius            2.831
                     scale_standard radius            2.785

scale_power et scale_quantile donnent les meilleurs résultats

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour tous les paramètres.

KNN	PARSEC	scale_power	T_eff	3.362 - 4.518	0.957	3.282%	1.214%	0.159%	0.978	70.377%	75 : 1.038% / 90 : 3.294% / 95 : 5.877% / 99 : 13.936%	7.433

KNN	PARSEC	scale_power	log_g	-0.384 - 5.345	0.814	7.879%	2.764%	0.209%	0.903	80.911%	75 : 1.421% / 90 : 7.136% / 95 : 16.486% / 99 : 37.924%	7.433

KNN	PARSEC	scale_power	radius	-0.976 - 2.837	0.863	5.918%	2.083%	0.181%	0.929	60.762%	75 : 1.067% / 90 : 5.347% / 95 : 12.383% / 99 : 28.486%	7.433

### Random forest

#### T_eff parameter

In [23]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff             3.362 - 4.518
                             Base_old       T_eff             3.362 - 4.518
                             mass_smaller_3 T_eff             3.362 - 4.191
                             scale_power    T_eff             3.362 - 4.518
                             scale_quantile T_eff             3.362 - 4.518
                             scale_robust   T_eff             3.362 - 4.518
                             scale_standard T_eff             3.362 - 4.518

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff             0.957  3.274%
                             Base_old       T_eff             0.940  3.342%
                             mass_smaller_3 T_eff             0.913  3.523%
                             scale_power    T_eff             0.957  3.276%
                             scale_quantile T_eff             0.957  3.276%
                             scale_robust   T_eff             0.956  3.285%
                             scale_standard T_eff             0.957  3.277%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff             1.055%   0.13%
                             Base_old       T_eff             1.275%  0.283%
                             mass_smaller_3 T_eff             1.232%  0.162%
                             scale_power    T_eff             1.055%  0.131%
                             scale_quantile T_eff             1.057%  0.133%
                             scale_robust   T_eff             1.056%   0.13%
                             scale_standard T_eff             1.055%  0.131%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff             0.978  71.737%
                             Base_old       T_eff             0.970  71.819%
                             mass_smaller_3 T_eff             0.956  34.462%
                             scale_power    T_eff             0.978  72.164%
                             scale_quantile T_eff             0.978  71.248%
                             scale_robust   T_eff             0.978  72.619%
                             scale_standard T_eff             0.978  72.102%

                                                                                                         Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff             75 : 0.627% / 90 : 2.517% / 95 : 5.594% / 99 : 14.742%
                             Base_old       T_eff             75 : 1.122% / 90 : 3.045% / 95 : 6.483% / 99 : 13.623%
                             mass_smaller_3 T_eff             75 : 0.655% / 90 : 2.899% / 95 : 7.294% / 99 : 18.046%
                             scale_power    T_eff              75 : 0.629% / 90 : 2.521% / 95 : 5.596% / 99 : 14.63%
                             scale_quantile T_eff             75 : 0.629% / 90 : 2.517% / 95 : 5.612% / 99 : 14.666%
                             scale_robust   T_eff             75 : 0.626% / 90 : 2.516% / 95 : 5.598% / 99 : 14.778%
                             scale_standard T_eff              75 : 0.627% / 90 : 2.52% / 95 : 5.588% / 99 : 14.661%

                                                                 time
model         physical_model filter         output_parameter
random_forest PARSEC         Base           T_eff              70.705
                             Base_old       T_eff             123.278
                             mass_smaller_3 T_eff              43.330
                             scale_power    T_eff              83.418
                             scale_quantile T_eff              82.528
                             scale_robust   T_eff              79.770
                             scale_standard T_eff              80.385

Base et ses scaling donnent des résultats similaires

#### log_g

In [25]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g             -0.384 - 5.345
                             Base_old       log_g             -0.664 - 5.345
                             mass_smaller_3 log_g             -0.384 - 5.345
                             scale_power    log_g             -0.384 - 5.345
                             scale_quantile log_g             -0.384 - 5.345
                             scale_robust   log_g             -0.384 - 5.345
                             scale_standard log_g             -0.384 - 5.345

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g             0.807  8.011%
                             Base_old       log_g             0.802  7.741%
                             mass_smaller_3 log_g             0.701  8.825%
                             scale_power    log_g             0.808  7.999%
                             scale_quantile log_g             0.808  7.994%
                             scale_robust   log_g             0.807  8.012%
                             scale_standard log_g             0.808  8.002%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g             2.553%  0.222%
                             Base_old       log_g             3.119%  0.617%
                             mass_smaller_3 log_g             2.908%  0.224%
                             scale_power    log_g             2.551%  0.223%
                             scale_quantile log_g             2.551%  0.222%
                             scale_robust   log_g             2.552%  0.221%
                             scale_standard log_g             2.552%  0.223%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g             0.900  80.657%
                             Base_old       log_g             0.896  76.044%
                             mass_smaller_3 log_g             0.841  80.404%
                             scale_power    log_g             0.900  80.826%
                             scale_quantile log_g             0.900  80.476%
                             scale_robust   log_g             0.900  81.346%
                             scale_standard log_g             0.900   81.48%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g              75 : 1.135% / 90 : 4.928% / 95 : 15.91% / 99 : 41.451%
                             Base_old       log_g             75 : 2.489% / 90 : 7.541% / 95 : 18.021% / 99 : 35.971%
                             mass_smaller_3 log_g             75 : 1.105% / 90 : 6.696% / 95 : 19.957% / 99 : 43.378%
                             scale_power    log_g             75 : 1.132% / 90 : 4.943% / 95 : 15.913% / 99 : 41.402%
                             scale_quantile log_g              75 : 1.133% / 90 : 4.948% / 95 : 15.96% / 99 : 41.481%
                             scale_robust   log_g             75 : 1.129% / 90 : 4.913% / 95 : 15.887% / 99 : 41.462%
                             scale_standard log_g             75 : 1.133% / 90 : 4.938% / 95 : 15.901% / 99 : 41.479%

                                                                 time
model         physical_model filter         output_parameter
random_forest PARSEC         Base           log_g              70.705
                             Base_old       log_g             123.278
                             mass_smaller_3 log_g              43.330
                             scale_power    log_g              83.418
                             scale_quantile log_g              82.528
                             scale_robust   log_g              79.770
                             scale_standard log_g              80.385

Base et ses scaling donnent des résultats similaires

#### Radius parameter

In [27]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius            -0.976 - 2.837
                             Base_old       radius            -0.976 - 2.973
                             mass_smaller_3 radius            -0.976 - 2.363
                             scale_power    radius            -0.976 - 2.837
                             scale_quantile radius            -0.976 - 2.837
                             scale_robust   radius            -0.976 - 2.837
                             scale_standard radius            -0.976 - 2.837

                                                                RVE    RMSE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius            0.858  6.016%
                             Base_old       radius            0.849  5.894%
                             mass_smaller_3 radius            0.741  7.571%
                             scale_power    radius            0.859  6.007%
                             scale_quantile radius            0.859  6.003%
                             scale_robust   radius            0.858  6.017%
                             scale_standard radius            0.859   6.01%

                                                                 MAE   MedAE  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius            1.916%  0.169%
                             Base_old       radius            2.376%  0.471%
                             mass_smaller_3 radius            2.497%  0.196%
                             scale_power    radius            1.915%   0.17%
                             scale_quantile radius            1.915%   0.17%
                             scale_robust   radius            1.916%  0.168%
                             scale_standard radius            1.915%   0.17%

                                                               CORR   MAX_ER  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius            0.927   60.58%
                             Base_old       radius            0.922  57.865%
                             mass_smaller_3 radius            0.863  68.962%
                             scale_power    radius            0.927  60.705%
                             scale_quantile radius            0.927  60.443%
                             scale_robust   radius            0.927  61.096%
                             scale_standard radius            0.927  61.196%

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius             75 : 0.85% / 90 : 3.686% / 95 : 11.939% / 99 : 31.138%
                             Base_old       radius            75 : 1.896% / 90 : 5.742% / 95 : 13.712% / 99 : 27.395%
                             mass_smaller_3 radius            75 : 0.948% / 90 : 5.753% / 95 : 17.126% / 99 : 37.202%
                             scale_power    radius            75 : 0.848% / 90 : 3.694% / 95 : 11.928% / 99 : 31.096%
                             scale_quantile radius              75 : 0.848% / 90 : 3.7% / 95 : 11.963% / 99 : 31.158%
                             scale_robust   radius             75 : 0.846% / 90 : 3.679% / 95 : 11.914% / 99 : 31.15%
                             scale_standard radius             75 : 0.849% / 90 : 3.692% / 95 : 11.925% / 99 : 31.17%

                                                                 time
model         physical_model filter         output_parameter
random_forest PARSEC         Base           radius             70.705
                             Base_old       radius            123.278
                             mass_smaller_3 radius             43.330
                             scale_power    radius             83.418
                             scale_quantile radius             82.528
                             scale_robust   radius             79.770
                             scale_standard radius             80.385

Base et ses scaling donnent des résultats similaires

#### Filtre choisi

Le filtre scale_quantile est choisi parce qu'il donne des résultats un tout petit peu meilleurs que les autres scaling et Base.

random_forest	PARSEC	scale_quantile	T_eff	3.362 - 4.518	0.957	3.276%	1.057%	0.133%	0.978	71.248%	75 : 0.629% / 90 : 2.517% / 95 : 5.612% / 99 : 14.666%	82.528

random_forest	PARSEC	scale_quantile	log_g	-0.384 - 5.345	0.808	7.994%	2.551%	0.222%	0.900	80.476%	75 : 1.133% / 90 : 4.948% / 95 : 15.96% / 99 : 41.481%	82.528

random_forest	PARSEC	scale_quantile	radius	-0.976 - 2.837	0.859	6.003%	1.915%	0.17%	0.927	60.443%	75 : 0.848% / 90 : 3.7% / 95 : 11.963% / 99 : 31.158%	82.528

### XGBoost

#### T_eff parameter

In [31]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                          value range    RVE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff             3.362 - 4.518  0.773
                       Base_old       T_eff             3.362 - 4.518  0.735
                       mass_smaller_3 T_eff             3.362 - 4.191  0.852
                       scale_power    T_eff             3.362 - 4.518  0.773
                       scale_quantile T_eff             3.362 - 4.518  0.773
                       scale_robust   T_eff             3.362 - 4.518  0.773
                       scale_standard T_eff             3.362 - 4.518  0.773

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff             7.499%  3.887%
                       Base_old       T_eff             7.026%  3.589%
                       mass_smaller_3 T_eff             4.595%  2.353%
                       scale_power    T_eff             7.499%  3.887%
                       scale_quantile T_eff             7.492%  3.889%
                       scale_robust   T_eff             7.499%  3.887%
                       scale_standard T_eff             7.499%  3.887%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff             1.057%  0.879
                       Base_old       T_eff             1.002%  0.857
                       mass_smaller_3 T_eff             0.748%  0.923
                       scale_power    T_eff             1.057%  0.879
                       scale_quantile T_eff              1.08%  0.879
                       scale_robust   T_eff             1.057%  0.879
                       scale_standard T_eff             1.057%  0.879

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff             59.381%
                       Base_old       T_eff             64.221%
                       mass_smaller_3 T_eff             39.146%
                       scale_power    T_eff             59.381%
                       scale_quantile T_eff             59.423%
                       scale_robust   T_eff             59.381%
                       scale_standard T_eff             59.381%

                                                                                                     Percentiles  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff              75 : 4.64% / 90 : 11.803% / 95 : 17.476% / 99 : 29.971%
                       Base_old       T_eff             75 : 4.117% / 90 : 10.592% / 95 : 15.648% / 99 : 28.553%
                       mass_smaller_3 T_eff              75 : 2.257% / 90 : 7.228% / 95 : 11.401% / 99 : 18.839%
                       scale_power    T_eff              75 : 4.64% / 90 : 11.803% / 95 : 17.476% / 99 : 29.971%
                       scale_quantile T_eff              75 : 4.673% / 90 : 11.745% / 95 : 17.487% / 99 : 29.89%
                       scale_robust   T_eff              75 : 4.64% / 90 : 11.803% / 95 : 17.476% / 99 : 29.971%
                       scale_standard T_eff              75 : 4.64% / 90 : 11.803% / 95 : 17.476% / 99 : 29.971%

                                                          time
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           T_eff              6.729
                       Base_old       T_eff             11.540
                       mass_smaller_3 T_eff              5.383
                       scale_power    T_eff             13.139
                       scale_quantile T_eff              8.293
                       scale_robust   T_eff              7.951
                       scale_standard T_eff              7.471

Base et ses scaling donnent les meilleurs résultats, scale_quantile donne des résultats un tout petit peu meilleurs

#### log_g

In [32]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g             -0.384 - 5.345  0.721
                       Base_old       log_g             -0.664 - 5.345  0.685
                       mass_smaller_3 log_g             -0.384 - 5.345  0.710
                       scale_power    log_g             -0.384 - 5.345  0.721
                       scale_quantile log_g             -0.384 - 5.345  0.722
                       scale_robust   log_g             -0.384 - 5.345  0.721
                       scale_standard log_g             -0.384 - 5.345  0.721

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g             9.647%  5.474%
                       Base_old       log_g             9.763%  5.695%
                       mass_smaller_3 log_g             8.688%  4.238%
                       scale_power    log_g             9.647%  5.474%
                       scale_quantile log_g              9.62%   5.44%
                       scale_robust   log_g             9.647%  5.474%
                       scale_standard log_g             9.647%  5.474%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g              1.87%  0.849
                       Base_old       log_g             2.187%  0.828
                       mass_smaller_3 log_g             1.219%  0.843
                       scale_power    log_g              1.87%  0.849
                       scale_quantile log_g             1.826%  0.850
                       scale_robust   log_g              1.87%  0.849
                       scale_standard log_g              1.87%  0.849

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g             76.063%
                       Base_old       log_g             71.799%
                       mass_smaller_3 log_g              80.62%
                       scale_power    log_g             76.063%
                       scale_quantile log_g             75.823%
                       scale_robust   log_g             76.063%
                       scale_standard log_g             76.063%

                                                                                                     Percentiles  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g             75 : 7.032% / 90 : 16.612% / 95 : 22.438% / 99 : 35.148%
                       Base_old       log_g              75 : 6.973% / 90 : 17.611% / 95 : 23.82% / 99 : 34.032%
                       mass_smaller_3 log_g             75 : 3.906% / 90 : 13.417% / 95 : 20.694% / 99 : 35.709%
                       scale_power    log_g             75 : 7.032% / 90 : 16.612% / 95 : 22.438% / 99 : 35.148%
                       scale_quantile log_g             75 : 6.936% / 90 : 16.583% / 95 : 22.397% / 99 : 35.042%
                       scale_robust   log_g             75 : 7.032% / 90 : 16.612% / 95 : 22.438% / 99 : 35.148%
                       scale_standard log_g             75 : 7.032% / 90 : 16.612% / 95 : 22.438% / 99 : 35.148%

                                                          time
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           log_g              6.729
                       Base_old       log_g             11.540
                       mass_smaller_3 log_g              5.383
                       scale_power    log_g             13.139
                       scale_quantile log_g              8.293
                       scale_robust   log_g              7.951
                       scale_standard log_g              7.471

scale_quantile donne les meilleurs résultats

#### Radius parameter

In [33]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["XGBoost"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                           value range    RVE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius            -0.976 - 2.837  0.795
                       Base_old       radius            -0.976 - 2.973  0.759
                       mass_smaller_3 radius            -0.976 - 2.363  0.750
                       scale_power    radius            -0.976 - 2.837  0.795
                       scale_quantile radius            -0.976 - 2.837  0.795
                       scale_robust   radius            -0.976 - 2.837  0.795
                       scale_standard radius            -0.976 - 2.837  0.795

                                                          RMSE     MAE  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius            7.247%  4.116%
                       Base_old       radius            7.447%  4.359%
                       mass_smaller_3 radius            7.439%  3.636%
                       scale_power    radius            7.247%  4.116%
                       scale_quantile radius            7.246%  4.113%
                       scale_robust   radius            7.247%  4.116%
                       scale_standard radius            7.247%  4.116%

                                                         MedAE   CORR  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius            1.422%  0.892
                       Base_old       radius            1.698%  0.871
                       mass_smaller_3 radius            1.066%  0.866
                       scale_power    radius            1.422%  0.892
                       scale_quantile radius            1.419%  0.892
                       scale_robust   radius            1.422%  0.892
                       scale_standard radius            1.422%  0.892

                                                         MAX_ER  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius            59.294%
                       Base_old       radius            52.824%
                       mass_smaller_3 radius             69.13%
                       scale_power    radius            59.294%
                       scale_quantile radius            58.518%
                       scale_robust   radius            59.294%
                       scale_standard radius            59.294%

                                                                                                     Percentiles  \
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius              75 : 5.232% / 90 : 12.505% / 95 : 16.8% / 99 : 26.445%
                       Base_old       radius             75 : 5.324% / 90 : 13.426% / 95 : 18.13% / 99 : 25.983%
                       mass_smaller_3 radius            75 : 3.357% / 90 : 11.459% / 95 : 17.698% / 99 : 30.626%
                       scale_power    radius              75 : 5.232% / 90 : 12.505% / 95 : 16.8% / 99 : 26.445%
                       scale_quantile radius            75 : 5.221% / 90 : 12.518% / 95 : 16.806% / 99 : 26.464%
                       scale_robust   radius              75 : 5.232% / 90 : 12.505% / 95 : 16.8% / 99 : 26.445%
                       scale_standard radius              75 : 5.232% / 90 : 12.505% / 95 : 16.8% / 99 : 26.445%

                                                          time
model   physical_model filter         output_parameter
XGBoost PARSEC         Base           radius             6.729
                       Base_old       radius            11.540
                       mass_smaller_3 radius             5.383
                       scale_power    radius            13.139
                       scale_quantile radius             8.293
                       scale_robust   radius             7.951
                       scale_standard radius             7.471

Base et ses scaling donnent les meilleurs résultats, scale_quantile donne des résultats un tout petit peu meilleurs

#### Filtre choisi

Le filtre scale_quantile est choisi parce qu'il donne des résultats un tout petit peu meilleurs que les autres scaling et Base

XGBoost	PARSEC	scale_quantile	T_eff	3.362 - 4.518	0.773	7.492%	3.889%	1.08%	0.879	59.423%	75 : 4.673% / 90 : 11.745% / 95 : 17.487% / 99 : 29.89%	8.293

XGBoost	PARSEC	scale_quantile	log_g	-0.384 - 5.345	0.722	9.62%	5.44%	1.826%	0.850	75.823%	75 : 6.936% / 90 : 16.583% / 95 : 22.397% / 99 : 35.042%	8.293

XGBoost	PARSEC	scale_quantile	radius	-0.976 - 2.837	0.795	7.246%	4.113%	1.419%	0.892	58.518%	75 : 5.221% / 90 : 12.518% / 95 : 16.806% / 99 : 26.464%	8.293

### MLP

#### T_eff parameter

In [34]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                model_names=["MLP"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                        value range    RVE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           T_eff             3.362 - 4.518  0.457
                     Base_old       T_eff             3.362 - 4.518  0.386
                     mass_smaller_3 T_eff             3.362 - 4.191  0.292
                     scale_power    T_eff             3.362 - 4.518  0.707
                     scale_quantile T_eff             3.362 - 4.518  0.607
                     scale_robust   T_eff             3.362 - 4.518  0.700
                     scale_standard T_eff             3.362 - 4.518  0.692

                                                         RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           T_eff             11.605%   8.09%  5.547%
                     Base_old       T_eff             10.767%  7.683%  5.682%
                     mass_smaller_3 T_eff             10.087%  7.467%  5.368%
                     scale_power    T_eff              8.518%  5.271%  2.932%
                     scale_quantile T_eff              9.861%  6.615%  4.068%
                     scale_robust   T_eff              8.621%    4.9%  2.076%
                     scale_standard T_eff              8.744%  5.476%  3.299%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           T_eff             0.688  72.031%
                     Base_old       T_eff             0.646  67.411%
                     mass_smaller_3 T_eff             0.658  76.477%
                     scale_power    T_eff             0.842  60.878%
                     scale_quantile T_eff             0.788  59.136%
                     scale_robust   T_eff             0.837  62.472%
                     scale_standard T_eff             0.834   62.77%

                                                                                                    Percentiles  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           T_eff              75 : 9.971% / 90 : 17.773% / 95 : 24.663% / 99 : 43.327%
                     Base_old       T_eff              75 : 9.851% / 90 : 16.343% / 95 : 21.799% / 99 : 40.542%
                     mass_smaller_3 T_eff             75 : 10.873% / 90 : 16.816% / 95 : 21.338% / 99 : 29.601%
                     scale_power    T_eff              75 : 6.371% / 90 : 13.033% / 95 : 19.431% / 99 : 32.767%
                     scale_quantile T_eff              75 : 8.809% / 90 : 16.048% / 95 : 21.256% / 99 : 35.816%
                     scale_robust   T_eff              75 : 5.659% / 90 : 13.409% / 95 : 19.875% / 99 : 35.423%
                     scale_standard T_eff              75 : 6.732% / 90 : 13.158% / 95 : 18.535% / 99 : 35.623%

                                                         time
model physical_model filter         output_parameter
MLP   PARSEC         Base           T_eff             116.133
                     Base_old       T_eff             219.148
                     mass_smaller_3 T_eff              87.952
                     scale_power    T_eff             221.278
                     scale_quantile T_eff             194.661
                     scale_robust   T_eff             204.411
                     scale_standard T_eff             204.223

scale_power donne les meilleurs résultats

#### log_g

In [35]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                model_names=["MLP"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           log_g             -0.384 - 5.345  0.508
                     Base_old       log_g             -0.664 - 5.345  0.420
                     mass_smaller_3 log_g             -0.384 - 5.345  0.449
                     scale_power    log_g             -0.384 - 5.345  0.725
                     scale_quantile log_g             -0.384 - 5.345  0.642
                     scale_robust   log_g             -0.384 - 5.345  0.700
                     scale_standard log_g             -0.384 - 5.345  0.678

                                                         RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           log_g             12.822%  8.747%  4.531%
                     Base_old       log_g             13.268%  8.347%  3.038%
                     mass_smaller_3 log_g             12.001%  8.056%  4.104%
                     scale_power    log_g              9.572%  5.371%  1.827%
                     scale_quantile log_g             10.977%  6.804%  3.135%
                     scale_robust   log_g             10.005%  5.698%  2.046%
                     scale_standard log_g              10.36%  6.107%  2.323%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           log_g             0.712  67.966%
                     Base_old       log_g             0.649  51.819%
                     mass_smaller_3 log_g             0.671  59.887%
                     scale_power    log_g             0.852  76.875%
                     scale_quantile log_g             0.801  65.953%
                     scale_robust   log_g             0.837  73.241%
                     scale_standard log_g             0.823  67.586%

                                                                                                    Percentiles  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           log_g             75 : 12.796% / 90 : 24.748% / 95 : 28.927% / 99 : 38.055%
                     Base_old       log_g                75 : 12.029% / 90 : 26.9% / 95 : 30.966% / 99 : 37.85%
                     mass_smaller_3 log_g             75 : 11.653% / 90 : 22.422% / 95 : 28.236% / 99 : 36.261%
                     scale_power    log_g              75 : 6.451% / 90 : 16.233% / 95 : 22.603% / 99 : 35.354%
                     scale_quantile log_g               75 : 8.979% / 90 : 19.399% / 95 : 26.256% / 99 : 37.02%
                     scale_robust   log_g               75 : 7.261% / 90 : 16.81% / 95 : 23.082% / 99 : 37.817%
                     scale_standard log_g              75 : 7.896% / 90 : 18.012% / 95 : 24.299% / 99 : 37.884%

                                                         time
model physical_model filter         output_parameter
MLP   PARSEC         Base           log_g             116.133
                     Base_old       log_g             219.148
                     mass_smaller_3 log_g              87.952
                     scale_power    log_g             221.278
                     scale_quantile log_g             194.661
                     scale_robust   log_g             204.411
                     scale_standard log_g             204.223

scale_power donne les meilleurs résultats

#### Radius parameter

In [36]:
compare_metrics(path, value_rounding=3, relative_values=True, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["MLP"],
                categories=["Global"]
                )

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           radius            -0.976 - 2.837  0.623
                     Base_old       radius            -0.976 - 2.973  0.552
                     mass_smaller_3 radius            -0.976 - 2.363  0.542
                     scale_power    radius            -0.976 - 2.837  0.798
                     scale_quantile radius            -0.976 - 2.837  0.728
                     scale_robust   radius            -0.976 - 2.837  0.779
                     scale_standard radius            -0.976 - 2.837  0.761

                                                         RMSE     MAE   MedAE  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           radius             9.833%  6.651%  3.493%
                     Base_old       radius            10.143%  6.342%  2.261%
                     mass_smaller_3 radius            10.061%   6.61%  3.409%
                     scale_power    radius             7.186%  4.024%  1.372%
                     scale_quantile radius             8.386%  5.346%  2.879%
                     scale_robust   radius             7.515%  4.311%  1.612%
                     scale_standard radius             7.817%  4.634%  1.882%

                                                       CORR   MAX_ER  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           radius            0.789  52.199%
                     Base_old       radius            0.745  39.092%
                     mass_smaller_3 radius            0.737  48.161%
                     scale_power    radius            0.894  58.533%
                     scale_quantile radius            0.853  48.931%
                     scale_robust   radius            0.883  56.118%
                     scale_standard radius            0.872  50.648%

                                                                                                   Percentiles  \
model physical_model filter         output_parameter
MLP   PARSEC         Base           radius            75 : 9.951% / 90 : 18.768% / 95 : 22.294% / 99 : 28.573%
                     Base_old       radius            75 : 9.298% / 90 : 20.626% / 95 : 23.819% / 99 : 28.612%
                     mass_smaller_3 radius            75 : 8.586% / 90 : 19.207% / 95 : 24.326% / 99 : 30.702%
                     scale_power    radius            75 : 4.884% / 90 : 12.112% / 95 : 16.875% / 99 : 26.688%
                     scale_quantile radius            75 : 6.941% / 90 : 14.631% / 95 : 19.811% / 99 : 28.305%
                     scale_robust   radius             75 : 5.47% / 90 : 12.593% / 95 : 17.359% / 99 : 28.341%
                     scale_standard radius              75 : 5.94% / 90 : 13.486% / 95 : 18.259% / 99 : 28.69%

                                                         time
model physical_model filter         output_parameter
MLP   PARSEC         Base           radius            116.133
                     Base_old       radius            219.148
                     mass_smaller_3 radius             87.952
                     scale_power    radius            221.278
                     scale_quantile radius            194.661
                     scale_robust   radius            204.411
                     scale_standard radius            204.223

scale_power donne les meilleurs résultats.

#### Filtre choisi

Le filtre scale_power est choisi parce qu'il donne les meilleurs résultats pour tous les paramètres

MLP	PARSEC	scale_power	T_eff	3.362 - 4.518	0.707	8.518%	5.271%	2.932%	0.842	60.878%	75 : 6.371% / 90 : 13.033% / 95 : 19.431% / 99 : 32.767%	221.278

MLP	PARSEC	scale_power	log_g	-0.384 - 5.345	0.725	9.572%	5.371%	1.827%	0.852	76.875%	75 : 6.451% / 90 : 16.233% / 95 : 22.603% / 99 : 35.354%	221.278

MLP	PARSEC	scale_power	radius	-0.976 - 2.837	0.798	7.186%	4.024%	1.372%	0.894	58.533%	75 : 4.884% / 90 : 12.112% / 95 : 16.875% / 99 : 26.688%	221.278

### Compilation des meilleurs modèles

#### T_eff parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | PARSEC | scale_power | T_eff | 3.362 - 4.518 | 0.288 | 13.267% | 9.707% | 6.914% | 0.537 | 47.973% | 75 : 12.337% / 90 : 23.864% / 95 : 28.92% / 99 : 40.88% | 5.075 |
| decision_tree | PARSEC | scale_power | T_eff | 3.362 - 4.518 | 0.945 | 3.676% | 1.082% | 0.103% | 0.973 | 72.75% | 75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.056% | 9.373 |
| KNN | PARSEC | scale_power | T_eff | 3.362 - 4.518 | 0.957 | 3.282% | 1.214% | 0.159% | 0.978 | 70.377% | 75 : 1.038% / 90 : 3.294% / 95 : 5.877% / 99 : 13.936% | 7.433 |
| random_forest | PARSEC | scale_quantile | T_eff | 3.362 - 4.518 | 0.957 | 3.276% | 1.057% | 0.133% | 0.978 | 71.248% | 75 : 0.629% / 90 : 2.517% / 95 : 5.612% / 99 : 14.666% | 82.528 |
| XGBoost | PARSEC | scale_quantile | T_eff | 3.362 - 4.518 | 0.773 | 7.492% | 3.889% | 1.08% | 0.879 | 59.423% | 75 : 4.673% / 90 : 11.745% / 95 : 17.487% / 99 : 29.89% | 8.293 |
| MLP | PARSEC | scale_power | T_eff | 3.362 - 4.518 | 0.707 | 8.518% | 5.271% | 2.932% | 0.842 | 60.878% | 75 : 6.371% / 90 : 13.033% / 95 : 19.431% / 99 : 32.767% | 221.278 |

The best models in order for the mass from best to worst are:

1. Random forest, KNN and Decision tree (the three models have similar results and better in some places while worse in others)
4. XGBoost
5. MLP
6. Linear regression (worse results than any other model on all metrics)

#### log_g parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | PARSEC | scale_power | log_g | -0.384 - 5.345 | 0.307 | 15.196% | 11.679% | 7.197% | 0.554 | 48.812% | 75 : 19.212% / 90 : 27.035% / 95 : 30.81% / 99 : 36.535% | 5.075 |
| decision_tree | PARSEC | scale_power | log_g | -0.384 - 5.345 | 0.755 | 9.036% | 2.624% | 0.192% | 0.874 | 83.435% | 75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.55% | 9.373 |
| KNN | PARSEC | scale_power | log_g | -0.384 - 5.345 | 0.814 | 7.879% | 2.764% | 0.209% | 0.903 | 80.911% | 75 : 1.421% / 90 : 7.136% / 95 : 16.486% / 99 : 37.924% | 7.433 |
| random_forest | PARSEC | scale_quantile | log_g | -0.384 - 5.345 | 0.808 | 7.994% | 2.551% | 0.222% | 0.900 | 80.476% | 75 : 1.133% / 90 : 4.948% / 95 : 15.96% / 99 : 41.481% | 82.528 |
| XGBoost | PARSEC | scale_quantile | log_g | -0.384 - 5.345 | 0.722 | 9.62% | 5.44% | 1.826% | 0.850 | 75.823% | 75 : 6.936% / 90 : 16.583% / 95 : 22.397% / 99 : 35.042% | 8.293 |
| MLP | PARSEC | scale_power | log_g | -0.384 - 5.345 | 0.725 | 9.572% | 5.371% | 1.827% | 0.852 | 76.875% | 75 : 6.451% / 90 : 16.233% / 95 : 22.603% / 99 : 35.354% | 221.278 |

The best models in order for the mass from best to worst are:

1. Random forest, KNN and Decision tree (the three models have similar results and better in some places while worse in others)
4. XGBoost and MLP
6. Linear regression (worse results than any other model on all metrics)

#### Radius parameter

| model | physical_model | filter | output_parameter | value range | RVE | RMSE | MAE | MedAE | CORR | MAX_ER | Percentiles | time |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| linear_regression | PARSEC | scale_power | radius | -0.976 - 2.837 | 0.482 | 11.508% | 8.826% | 5.401% | 0.694 | 37.13% | 75 : 14.73% / 90 : 20.479% / 95 : 23.026% / 99 : 28.056% | 5.075 |
| decision_tree | PARSEC | scale_power | radius | -0.976 - 2.837 | 0.820 | 6.786% | 1.97% | 0.149% | 0.908 | 62.692% | 75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 37.967% | 9.373 |
| KNN | PARSEC | scale_power | radius | -0.976 - 2.837 | 0.863 | 5.918% | 2.083% | 0.181% | 0.929 | 60.762% | 75 : 1.067% / 90 : 5.347% / 95 : 12.383% / 99 : 28.486% | 7.433 |
| random_forest | PARSEC | scale_quantile | radius | -0.976 - 2.837 | 0.859 | 6.003% | 1.915% | 0.17% | 0.927 | 60.443% | 75 : 0.848% / 90 : 3.7% / 95 : 11.963% / 99 : 31.158% | 82.528 |
| XGBoost | PARSEC | scale_quantile | radius | -0.976 - 2.837 | 0.795 | 7.246% | 4.113% | 1.419% | 0.892 | 58.518% | 75 : 5.221% / 90 : 12.518% / 95 : 16.806% / 99 : 26.464% | 8.293 |
| MLP | PARSEC | scale_power | radius | -0.976 - 2.837 | 0.798 | 7.186% | 4.024% | 1.372% | 0.894 | 58.533% | 75 : 4.884% / 90 : 12.112% / 95 : 16.875% / 99 : 26.688% | 221.278 |

The best models in order for the mass from best to worst are:

1. Random forest, KNN and Decision tree (the three models have similar results and better in some places while worse in others)
4. XGBoost and MLP
6. Linear regression (worse results than any other model on all metrics)

### Models to be fine-tuned
Random forest with scale_quantile, Decision tree with scale_power and KNN with scale_power

## Base vs scaling

### T_eff parameter

In [3]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9451742472012191
                                 scale_standard T_eff              0.9454400175053367
                                 scale_robust   T_eff              0.9449862108106163
                                 scale_power    T_eff              0.9453531983567844
                                 scale_quantile T_eff              0.9454924425303036
KNN               PARSEC         Base           T_eff              0.9289910884078197
                                 scale_standard T_eff              0.9480303632063517
                                 scale_robust   T_eff              0.9365109053953301
                                 scale_power    T_eff              0.9565000130469343
                                 scale_quantile T_eff              0.9556507709419844
linear_regression PARSEC         Base           T_eff             0.34445841658008647
                                 scale_standard T_eff              0.3444584165800867
                                 scale_robust   T_eff             0.34445841658008625
                                 scale_power    T_eff              0.2884077289161212
                                 scale_quantile T_eff             0.25648506893501555
mlp               PARSEC         Base           T_eff             0.45667538004833186
                                 scale_standard T_eff              0.6920242769293696
                                 scale_robust   T_eff               0.700230116495161
                                 scale_power    T_eff              0.7066315352569479
                                 scale_quantile T_eff               0.606870997000041
random_forest     PARSEC         Base           T_eff              0.9566608469406531
                                 scale_standard T_eff              0.9565918503519508
                                 scale_robust   T_eff              0.9563727567673882
                                 scale_power    T_eff              0.9566059926800171
                                 scale_quantile T_eff              0.9565984693936177
xgboost           PARSEC         Base           T_eff              0.7726322878335125
                                 scale_standard T_eff              0.7726322878335125
                                 scale_robust   T_eff              0.7726322878335125
                                 scale_power    T_eff              0.7726322878335125
                                 scale_quantile T_eff              0.7730300854750899

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.682%
                                 scale_standard T_eff              3.673%
                                 scale_robust   T_eff              3.689%
                                 scale_power    T_eff              3.676%
                                 scale_quantile T_eff              3.672%
KNN               PARSEC         Base           T_eff              4.198%
                                 scale_standard T_eff              3.587%
                                 scale_robust   T_eff              3.968%
                                 scale_power    T_eff              3.282%
                                 scale_quantile T_eff              3.312%
linear_regression PARSEC         Base           T_eff             12.733%
                                 scale_standard T_eff             12.733%
                                 scale_robust   T_eff             12.733%
                                 scale_power    T_eff             13.267%
                                 scale_quantile T_eff             13.561%
mlp               PARSEC         Base           T_eff             11.605%
                                 scale_standard T_eff              8.744%
                                 scale_robust   T_eff              8.621%
                                 scale_power    T_eff              8.518%
                                 scale_quantile T_eff              9.861%
random_forest     PARSEC         Base           T_eff              3.274%
                                 scale_standard T_eff              3.277%
                                 scale_robust   T_eff              3.285%
                                 scale_power    T_eff              3.276%
                                 scale_quantile T_eff              3.276%
xgboost           PARSEC         Base           T_eff              7.499%
                                 scale_standard T_eff              7.499%
                                 scale_robust   T_eff              7.499%
                                 scale_power    T_eff              7.499%
                                 scale_quantile T_eff              7.492%

                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             1.083%
                                 scale_standard T_eff             1.082%
                                 scale_robust   T_eff             1.084%
                                 scale_power    T_eff             1.082%
                                 scale_quantile T_eff             1.083%
KNN               PARSEC         Base           T_eff             1.403%
                                 scale_standard T_eff             1.304%
                                 scale_robust   T_eff             1.361%
                                 scale_power    T_eff             1.214%
                                 scale_quantile T_eff             1.247%
linear_regression PARSEC         Base           T_eff             9.351%
                                 scale_standard T_eff             9.351%
                                 scale_robust   T_eff             9.351%
                                 scale_power    T_eff             9.707%
                                 scale_quantile T_eff             9.977%
mlp               PARSEC         Base           T_eff              8.09%
                                 scale_standard T_eff             5.476%
                                 scale_robust   T_eff               4.9%
                                 scale_power    T_eff             5.271%
                                 scale_quantile T_eff             6.615%
random_forest     PARSEC         Base           T_eff             1.055%
                                 scale_standard T_eff             1.055%
                                 scale_robust   T_eff             1.056%
                                 scale_power    T_eff             1.055%
                                 scale_quantile T_eff             1.057%
xgboost           PARSEC         Base           T_eff             3.887%
                                 scale_standard T_eff             3.887%
                                 scale_robust   T_eff             3.887%
                                 scale_power    T_eff             3.887%
                                 scale_quantile T_eff             3.889%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.103%
                                 scale_standard T_eff             0.104%
                                 scale_robust   T_eff             0.103%
                                 scale_power    T_eff             0.103%
                                 scale_quantile T_eff             0.104%
KNN               PARSEC         Base           T_eff             0.163%
                                 scale_standard T_eff             0.183%
                                 scale_robust   T_eff             0.171%
                                 scale_power    T_eff             0.159%
                                 scale_quantile T_eff             0.168%
linear_regression PARSEC         Base           T_eff             6.495%
                                 scale_standard T_eff             6.495%
                                 scale_robust   T_eff             6.495%
                                 scale_power    T_eff             6.914%
                                 scale_quantile T_eff             7.398%
mlp               PARSEC         Base           T_eff             5.547%
                                 scale_standard T_eff             3.299%
                                 scale_robust   T_eff             2.076%
                                 scale_power    T_eff             2.932%
                                 scale_quantile T_eff             4.068%
random_forest     PARSEC         Base           T_eff              0.13%
                                 scale_standard T_eff             0.131%
                                 scale_robust   T_eff              0.13%
                                 scale_power    T_eff             0.131%
                                 scale_quantile T_eff             0.133%
xgboost           PARSEC         Base           T_eff             1.057%
                                 scale_standard T_eff             1.057%
                                 scale_robust   T_eff             1.057%
                                 scale_power    T_eff             1.057%
                                 scale_quantile T_eff              1.08%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9724235183367057
                                 scale_standard T_eff             0.9725590222382688
                                 scale_robust   T_eff              0.972325957435005
                                 scale_power    T_eff              0.972511433737684
                                 scale_quantile T_eff             0.9725796596239012
KNN               PARSEC         Base           T_eff             0.9638581868639022
                                 scale_standard T_eff             0.9736724135677752
                                 scale_robust   T_eff             0.9677477284515891
                                 scale_power    T_eff             0.9780089535586624
                                 scale_quantile T_eff             0.9775844950078258
linear_regression PARSEC         Base           T_eff             0.5869057992445806
                                 scale_standard T_eff             0.5869057992445811
                                 scale_robust   T_eff             0.5869057992445808
                                 scale_power    T_eff             0.5370360594041893
                                 scale_quantile T_eff              0.506443549680199
mlp               PARSEC         Base           T_eff             0.6876406178694955
                                 scale_standard T_eff             0.8337935865405114
                                 scale_robust   T_eff             0.8368133954130454
                                 scale_power    T_eff             0.8422553265766842
                                 scale_quantile T_eff             0.7877820818854055
random_forest     PARSEC         Base           T_eff             0.9781241008271904
                                 scale_standard T_eff             0.9780888516165498
                                 scale_robust   T_eff             0.9779769687492161
                                 scale_power    T_eff             0.9780957913953894
                                 scale_quantile T_eff             0.9780910250183794
xgboost           PARSEC         Base           T_eff              0.879158545551974
                                 scale_standard T_eff              0.879158545551974
                                 scale_robust   T_eff              0.879158545551974
                                 scale_power    T_eff              0.879158545551974
                                 scale_quantile T_eff             0.8793885641377528

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              72.75%
                                 scale_standard T_eff              72.75%
                                 scale_robust   T_eff              72.75%
                                 scale_power    T_eff              72.75%
                                 scale_quantile T_eff              72.75%
KNN               PARSEC         Base           T_eff              71.75%
                                 scale_standard T_eff             71.753%
                                 scale_robust   T_eff             71.753%
                                 scale_power    T_eff             70.377%
                                 scale_quantile T_eff              71.75%
linear_regression PARSEC         Base           T_eff             47.223%
                                 scale_standard T_eff             47.223%
                                 scale_robust   T_eff             47.223%
                                 scale_power    T_eff             47.973%
                                 scale_quantile T_eff             51.154%
mlp               PARSEC         Base           T_eff             72.031%
                                 scale_standard T_eff              62.77%
                                 scale_robust   T_eff             62.472%
                                 scale_power    T_eff             60.878%
                                 scale_quantile T_eff             59.136%
random_forest     PARSEC         Base           T_eff             71.737%
                                 scale_standard T_eff             72.102%
                                 scale_robust   T_eff             72.619%
                                 scale_power    T_eff             72.164%
                                 scale_quantile T_eff             71.248%
xgboost           PARSEC         Base           T_eff             59.381%
                                 scale_standard T_eff             59.381%
                                 scale_robust   T_eff             59.381%
                                 scale_power    T_eff             59.381%
                                 scale_quantile T_eff             59.423%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.111%
                                 scale_standard T_eff                75 : 0.571% / 90 : 2.259% / 95 : 5.585% / 99 : 17.066%
                                 scale_robust   T_eff                75 : 0.571% / 90 : 2.267% / 95 : 5.602% / 99 : 17.138%
                                 scale_power    T_eff                75 : 0.571% / 90 : 2.267% / 95 : 5.599% / 99 : 17.056%
                                 scale_quantile T_eff                75 : 0.575% / 90 : 2.267% / 95 : 5.596% / 99 : 17.082%
KNN               PARSEC         Base           T_eff                75 : 1.151% / 90 : 3.444% / 95 : 6.523% / 99 : 17.315%
                                 scale_standard T_eff                75 : 1.182% / 90 : 3.384% / 95 : 6.063% / 99 : 14.922%
                                 scale_robust   T_eff                 75 : 1.153% / 90 : 3.399% / 95 : 6.342% / 99 : 16.34%
                                 scale_power    T_eff                75 : 1.038% / 90 : 3.294% / 95 : 5.877% / 99 : 13.936%
                                 scale_quantile T_eff                75 : 1.139% / 90 : 3.397% / 95 : 5.966% / 99 : 13.818%
linear_regression PARSEC         Base           T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%
                                 scale_standard T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%
                                 scale_robust   T_eff             75 : 12.317% / 90 : 23.618% / 95 : 27.705% / 99 : 37.096%
                                 scale_power    T_eff               75 : 12.337% / 90 : 23.864% / 95 : 28.92% / 99 : 40.88%
                                 scale_quantile T_eff             75 : 12.621% / 90 : 23.093% / 95 : 29.267% / 99 : 43.133%
mlp               PARSEC         Base           T_eff              75 : 9.971% / 90 : 17.773% / 95 : 24.663% / 99 : 43.327%
                                 scale_standard T_eff              75 : 6.732% / 90 : 13.158% / 95 : 18.535% / 99 : 35.623%
                                 scale_robust   T_eff              75 : 5.659% / 90 : 13.409% / 95 : 19.875% / 99 : 35.423%
                                 scale_power    T_eff              75 : 6.371% / 90 : 13.033% / 95 : 19.431% / 99 : 32.767%

Results for the label category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 scale_standard T_eff             3.3621 - 4.5177
                                 scale_robust   T_eff             3.3621 - 4.5177
                                 scale_power    T_eff             3.3621 - 4.5177
                                 scale_quantile T_eff             3.3621 - 4.5177

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9748322909531495
                                 scale_standard T_eff              0.9757503045153407
                                 scale_robust   T_eff              0.9749175674559253
                                 scale_power    T_eff              0.9753031698008416
                                 scale_quantile T_eff              0.9752795584861008
KNN               PARSEC         Base           T_eff              0.9255387206020436
                                 scale_standard T_eff              0.9638608833470892
                                 scale_robust   T_eff              0.9398271890706307
                                 scale_power    T_eff              0.9821080295591219
                                 scale_quantile T_eff              0.9800113550394226
linear_regression PARSEC         Base           T_eff               0.597293514283356
                                 scale_standard T_eff              0.5972935142833498
                                 scale_robust   T_eff              0.5972935142833506
                                 scale_power    T_eff               0.599548254874145
                                 scale_quantile T_eff             0.45937526068733014
mlp               PARSEC         Base           T_eff              0.5907206955331745
                                 scale_standard T_eff              0.8512614412925299
                                 scale_robust   T_eff              0.8788345073361897
                                 scale_power    T_eff              0.8692371638286908
                                 scale_quantile T_eff              0.7158168450420492
random_forest     PARSEC         Base           T_eff               0.982663800306455
                                 scale_standard T_eff               0.982798003492336
                                 scale_robust   T_eff              0.9824019597155952
                                 scale_power    T_eff               0.982793955233488
                                 scale_quantile T_eff              0.9826071040761207
xgboost           PARSEC         Base           T_eff              0.9035438101538388
                                 scale_standard T_eff              0.9035438101538388
                                 scale_robust   T_eff              0.9035438101538388
                                 scale_power    T_eff              0.9035438101538388
                                 scale_quantile T_eff              0.9038442331107571

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.667%
                                 scale_standard T_eff                3.6%
                                 scale_robust   T_eff              3.662%
                                 scale_power    T_eff              3.633%
                                 scale_quantile T_eff              3.635%
KNN               PARSEC         Base           T_eff              6.411%
                                 scale_standard T_eff              4.421%
                                 scale_robust   T_eff              5.742%
                                 scale_power    T_eff              3.102%
                                 scale_quantile T_eff              3.286%
linear_regression PARSEC         Base           T_eff             18.623%
                                 scale_standard T_eff             18.623%
                                 scale_robust   T_eff             18.623%
                                 scale_power    T_eff              20.06%
                                 scale_quantile T_eff             21.211%
mlp               PARSEC         Base           T_eff             15.288%
                                 scale_standard T_eff              9.305%
                                 scale_robust   T_eff               8.59%
                                 scale_power    T_eff              8.688%
                                 scale_quantile T_eff             12.301%
random_forest     PARSEC         Base           T_eff              3.059%
                                 scale_standard T_eff              3.048%
                                 scale_robust   T_eff              3.083%
                                 scale_power    T_eff              3.047%
                                 scale_quantile T_eff              3.066%
xgboost           PARSEC         Base           T_eff              7.756%
                                 scale_standard T_eff              7.756%
                                 scale_robust   T_eff              7.756%
                                 scale_power    T_eff              7.756%
                                 scale_quantile T_eff              7.756%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.645%
                                 scale_standard T_eff              0.635%
                                 scale_robust   T_eff              0.642%
                                 scale_power    T_eff              0.641%
                                 scale_quantile T_eff              0.641%
KNN               PARSEC         Base           T_eff              1.706%
                                 scale_standard T_eff              1.254%
                                 scale_robust   T_eff              1.526%
                                 scale_power    T_eff              0.797%
                                 scale_quantile T_eff              1.002%
linear_regression PARSEC         Base           T_eff             15.651%
                                 scale_standard T_eff             15.651%
                                 scale_robust   T_eff             15.651%
                                 scale_power    T_eff             16.281%
                                 scale_quantile T_eff              17.11%
mlp               PARSEC         Base           T_eff             10.851%
                                 scale_standard T_eff              5.486%
                                 scale_robust   T_eff              4.504%
                                 scale_power    T_eff              5.325%
                                 scale_quantile T_eff              8.462%
random_forest     PARSEC         Base           T_eff              0.635%
                                 scale_standard T_eff              0.633%
                                 scale_robust   T_eff              0.635%
                                 scale_power    T_eff              0.634%
                                 scale_quantile T_eff              0.639%
xgboost           PARSEC         Base           T_eff              3.782%
                                 scale_standard T_eff              3.782%
                                 scale_robust   T_eff              3.782%
                                 scale_power    T_eff              3.782%
                                 scale_quantile T_eff              3.822%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.004%
                                 scale_standard T_eff              0.004%
                                 scale_robust   T_eff              0.004%
                                 scale_power    T_eff              0.004%
                                 scale_quantile T_eff              0.004%
KNN               PARSEC         Base           T_eff              0.175%
                                 scale_standard T_eff              0.258%
                                 scale_robust   T_eff              0.208%
                                 scale_power    T_eff               0.17%
                                 scale_quantile T_eff               0.19%
linear_regression PARSEC         Base           T_eff             11.865%
                                 scale_standard T_eff             11.865%
                                 scale_robust   T_eff             11.865%
                                 scale_power    T_eff             11.294%
                                 scale_quantile T_eff             11.799%
mlp               PARSEC         Base           T_eff               8.02%
                                 scale_standard T_eff               3.48%
                                 scale_robust   T_eff              2.531%
                                 scale_power    T_eff              3.563%
                                 scale_quantile T_eff              5.362%
random_forest     PARSEC         Base           T_eff              0.017%
                                 scale_standard T_eff              0.017%
                                 scale_robust   T_eff              0.017%
                                 scale_power    T_eff              0.017%
                                 scale_quantile T_eff              0.019%
xgboost           PARSEC         Base           T_eff              1.423%
                                 scale_standard T_eff              1.423%
                                 scale_robust   T_eff              1.423%
                                 scale_power    T_eff              1.423%
                                 scale_quantile T_eff              1.449%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9876003989251159
                                 scale_standard T_eff             0.9880496146989258
                                 scale_robust   T_eff             0.9876376203354993
                                 scale_power    T_eff             0.9878284091690117
                                 scale_quantile T_eff             0.9878143829255721
KNN               PARSEC         Base           T_eff             0.9623018163028533
                                 scale_standard T_eff             0.9818428211789911
                                 scale_robust   T_eff             0.9696161034878503
                                 scale_power    T_eff             0.9911440527978378
                                 scale_quantile T_eff             0.9901261656615532
linear_regression PARSEC         Base           T_eff             0.8536445700543512
                                 scale_standard T_eff             0.8536445700543511
                                 scale_robust   T_eff             0.8536445700543505
                                 scale_power    T_eff             0.9280608576001408
                                 scale_quantile T_eff             0.7976581642440426
mlp               PARSEC         Base           T_eff             0.7773454058575309
                                 scale_standard T_eff             0.9253934532099797
                                 scale_robust   T_eff             0.9380094715777688
                                 scale_power    T_eff             0.9366907680842597
                                 scale_quantile T_eff             0.8576640668487423
random_forest     PARSEC         Base           T_eff             0.9914002808313593
                                 scale_standard T_eff             0.9914649696591054
                                 scale_robust   T_eff             0.9912691218011552
                                 scale_power    T_eff             0.9914669463729288
                                 scale_quantile T_eff             0.9913687538052447
xgboost           PARSEC         Base           T_eff             0.9513542801799472
                                 scale_standard T_eff             0.9513542801799472
                                 scale_robust   T_eff             0.9513542801799472
                                 scale_power    T_eff             0.9513542801799472
                                 scale_quantile T_eff             0.9514993162229756

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             71.925%
                                 scale_standard T_eff             71.925%
                                 scale_robust   T_eff             71.925%
                                 scale_power    T_eff             71.925%
                                 scale_quantile T_eff             72.192%
KNN               PARSEC         Base           T_eff             71.506%
                                 scale_standard T_eff             71.753%
                                 scale_robust   T_eff             71.753%
                                 scale_power    T_eff             67.305%
                                 scale_quantile T_eff             70.756%
linear_regression PARSEC         Base           T_eff             47.223%
                                 scale_standard T_eff             47.223%
                                 scale_robust   T_eff             47.223%
                                 scale_power    T_eff             47.973%
                                 scale_quantile T_eff             51.154%
mlp               PARSEC         Base           T_eff             72.031%
                                 scale_standard T_eff              62.77%
                                 scale_robust   T_eff             62.345%
                                 scale_power    T_eff             60.878%
                                 scale_quantile T_eff             59.136%
random_forest     PARSEC         Base           T_eff             66.588%
                                 scale_standard T_eff             65.221%
                                 scale_robust   T_eff             66.613%
                                 scale_power    T_eff             65.982%
                                 scale_quantile T_eff             65.991%
xgboost           PARSEC         Base           T_eff             59.381%
                                 scale_standard T_eff             59.381%
                                 scale_robust   T_eff             59.381%
                                 scale_power    T_eff             59.381%
                                 scale_quantile T_eff             59.423%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 0.095% / 90 : 0.839% / 95 : 2.137% / 99 : 12.625%
                                 scale_standard T_eff                 75 : 0.095% / 90 : 0.848% / 95 : 2.12% / 99 : 11.942%
                                 scale_robust   T_eff                 75 : 0.095% / 90 : 0.848% / 95 : 2.12% / 99 : 12.223%
                                 scale_power    T_eff                75 : 0.095% / 90 : 0.848% / 95 : 2.137% / 99 : 12.203%
                                 scale_quantile T_eff                75 : 0.104% / 90 : 0.865% / 95 : 2.128% / 99 : 11.812%
KNN               PARSEC         Base           T_eff                 75 : 0.71% / 90 : 3.134% / 95 : 6.051% / 99 : 37.521%
                                 scale_standard T_eff                75 : 0.871% / 90 : 2.818% / 95 : 4.188% / 99 : 19.874%
                                 scale_robust   T_eff                75 : 0.732% / 90 : 2.935% / 95 : 4.663% / 99 : 31.774%
                                 scale_power    T_eff                75 : 0.469% / 90 : 1.663% / 95 : 3.368% / 99 : 10.758%
                                 scale_quantile T_eff                75 : 0.665% / 90 : 2.889% / 95 : 4.298% / 99 : 10.826%
linear_regression PARSEC         Base           T_eff             75 : 22.097% / 90 : 31.414% / 95 : 36.219% / 99 : 41.795%
                                 scale_standard T_eff             75 : 22.097% / 90 : 31.414% / 95 : 36.219% / 99 : 41.795%
                                 scale_robust   T_eff             75 : 22.097% / 90 : 31.414% / 95 : 36.219% / 99 : 41.795%
                                 scale_power    T_eff               75 : 23.403% / 90 : 36.4% / 95 : 40.408% / 99 : 44.805%
                                 scale_quantile T_eff             75 : 25.431% / 90 : 38.261% / 95 : 42.664% / 99 : 47.776%
mlp               PARSEC         Base           T_eff             75 : 13.266% / 90 : 23.821% / 95 : 34.427% / 99 : 54.457%
                                 scale_standard T_eff              75 : 6.363% / 90 : 10.142% / 95 : 17.355% / 99 : 44.791%
                                 scale_robust   T_eff               75 : 4.572% / 90 : 8.042% / 95 : 16.911% / 99 : 43.161%

Results for the label category with a value of 2.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446
KNN               PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446
linear_regression PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446
mlp               PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446
random_forest     PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446
xgboost           PARSEC         Base           T_eff             3.6053 - 4.446
                                 scale_standard T_eff             3.6053 - 4.446
                                 scale_robust   T_eff             3.6053 - 4.446
                                 scale_power    T_eff             3.6053 - 4.446
                                 scale_quantile T_eff             3.6053 - 4.446

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.872460228127739
                                 scale_standard T_eff               0.8733647988385779
                                 scale_robust   T_eff               0.8732613574498688
                                 scale_power    T_eff               0.8744415256893818
                                 scale_quantile T_eff               0.8736829102350739
KNN               PARSEC         Base           T_eff               0.9019213514815497
                                 scale_standard T_eff               0.9025090343673441
                                 scale_robust   T_eff               0.9031524138115453
                                 scale_power    T_eff               0.9082891600424591
                                 scale_quantile T_eff               0.8988541585913251
linear_regression PARSEC         Base           T_eff              0.24580413337093743
                                 scale_standard T_eff              0.24580413337093754
                                 scale_robust   T_eff              0.24580413337093776
                                 scale_power    T_eff               0.2470514899917956
                                 scale_quantile T_eff              0.23489224869810155
mlp               PARSEC         Base           T_eff             -0.06049696902287538
                                 scale_standard T_eff              0.10386767581860346
                                 scale_robust   T_eff              0.08085632344634686
                                 scale_power    T_eff               0.1412756244514598
                                 scale_quantile T_eff              0.18284761488134227
random_forest     PARSEC         Base           T_eff               0.8997608573485408
                                 scale_standard T_eff               0.9002187437381981
                                 scale_robust   T_eff               0.9004667454137519
                                 scale_power    T_eff                0.901494565941335
                                 scale_quantile T_eff               0.9000254775738121
xgboost           PARSEC         Base           T_eff               0.2421346697916199
                                 scale_standard T_eff               0.2421346697916199
                                 scale_robust   T_eff               0.2421346697916199
                                 scale_power    T_eff               0.2421346697916199
                                 scale_quantile T_eff               0.2372964557248708

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               7.44%
                                 scale_standard T_eff              7.412%
                                 scale_robust   T_eff               7.42%
                                 scale_power    T_eff               7.39%
                                 scale_quantile T_eff              7.406%
KNN               PARSEC         Base           T_eff              6.724%
                                 scale_standard T_eff              6.712%
                                 scale_robust   T_eff              6.688%
                                 scale_power    T_eff              6.867%
                                 scale_quantile T_eff              6.767%
linear_regression PARSEC         Base           T_eff             18.752%
                                 scale_standard T_eff             18.752%
                                 scale_robust   T_eff             18.752%
                                 scale_power    T_eff             18.607%
                                 scale_quantile T_eff             19.143%
mlp               PARSEC         Base           T_eff              23.99%
                                 scale_standard T_eff             20.934%
                                 scale_robust   T_eff             20.849%
                                 scale_power    T_eff             20.436%
                                 scale_quantile T_eff              21.28%
random_forest     PARSEC         Base           T_eff              6.651%
                                 scale_standard T_eff              6.634%
                                 scale_robust   T_eff               6.63%
                                 scale_power    T_eff              6.622%
                                 scale_quantile T_eff               6.64%
xgboost           PARSEC         Base           T_eff             19.444%
                                 scale_standard T_eff             19.444%
                                 scale_robust   T_eff             19.444%
                                 scale_power    T_eff             19.444%
                                 scale_quantile T_eff             19.395%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              4.021%
                                 scale_standard T_eff              4.014%
                                 scale_robust   T_eff               4.02%
                                 scale_power    T_eff              4.006%
                                 scale_quantile T_eff              4.017%
KNN               PARSEC         Base           T_eff              4.312%
                                 scale_standard T_eff              4.327%
                                 scale_robust   T_eff              4.309%
                                 scale_power    T_eff              4.504%
                                 scale_quantile T_eff              4.361%
linear_regression PARSEC         Base           T_eff             14.964%
                                 scale_standard T_eff             14.964%
                                 scale_robust   T_eff             14.964%
                                 scale_power    T_eff             14.649%
                                 scale_quantile T_eff             14.895%
mlp               PARSEC         Base           T_eff             17.862%
                                 scale_standard T_eff             15.578%
                                 scale_robust   T_eff             15.131%
                                 scale_power    T_eff             14.988%
                                 scale_quantile T_eff             16.237%
random_forest     PARSEC         Base           T_eff              3.869%
                                 scale_standard T_eff              3.859%
                                 scale_robust   T_eff              3.865%
                                 scale_power    T_eff              3.861%
                                 scale_quantile T_eff              3.866%
xgboost           PARSEC         Base           T_eff             14.634%
                                 scale_standard T_eff             14.634%
                                 scale_robust   T_eff             14.634%
                                 scale_power    T_eff             14.634%
                                 scale_quantile T_eff             14.601%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              1.811%
                                 scale_standard T_eff              1.808%
                                 scale_robust   T_eff              1.808%
                                 scale_power    T_eff              1.811%
                                 scale_quantile T_eff              1.811%
KNN               PARSEC         Base           T_eff              2.653%
                                 scale_standard T_eff              2.678%
                                 scale_robust   T_eff              2.672%
                                 scale_power    T_eff              2.881%
                                 scale_quantile T_eff              2.712%
linear_regression PARSEC         Base           T_eff             12.417%
                                 scale_standard T_eff             12.417%
                                 scale_robust   T_eff             12.417%
                                 scale_power    T_eff             11.775%
                                 scale_quantile T_eff             11.764%
mlp               PARSEC         Base           T_eff             13.258%
                                 scale_standard T_eff             11.678%
                                 scale_robust   T_eff             10.106%
                                 scale_power    T_eff             10.714%
                                 scale_quantile T_eff             12.652%
random_forest     PARSEC         Base           T_eff              1.947%
                                 scale_standard T_eff              1.934%
                                 scale_robust   T_eff              1.934%
                                 scale_power    T_eff              1.945%
                                 scale_quantile T_eff              1.927%
xgboost           PARSEC         Base           T_eff             10.656%
                                 scale_standard T_eff             10.656%
                                 scale_robust   T_eff             10.656%
                                 scale_power    T_eff             10.656%
                                 scale_quantile T_eff             10.642%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9441691057521153
                                 scale_standard T_eff              0.9446074534375856
                                 scale_robust   T_eff               0.944561942380967
                                 scale_power    T_eff              0.9449869914976895
                                 scale_quantile T_eff              0.9447496545349412
KNN               PARSEC         Base           T_eff              0.9541994998198405
                                 scale_standard T_eff              0.9544749444248902
                                 scale_robust   T_eff               0.954889302912259
                                 scale_power    T_eff              0.9558394593038567
                                 scale_quantile T_eff              0.9536042787229446
linear_regression PARSEC         Base           T_eff             0.49810122500597515
                                 scale_standard T_eff             0.49810122500597476
                                 scale_robust   T_eff              0.4981012250059749
                                 scale_power    T_eff              0.4973243661100871
                                 scale_quantile T_eff             0.48522666701395173
mlp               PARSEC         Base           T_eff               0.269179604340438
                                 scale_standard T_eff              0.4014959240596834
                                 scale_robust   T_eff               0.363569722366381
                                 scale_power    T_eff              0.4111072154318608
                                 scale_quantile T_eff              0.4388090225962256
random_forest     PARSEC         Base           T_eff              0.9549507593925414
                                 scale_standard T_eff              0.9552093618738898
                                 scale_robust   T_eff              0.9552451267893546
                                 scale_power    T_eff              0.9556779744879559
                                 scale_quantile T_eff              0.9551140805519215
xgboost           PARSEC         Base           T_eff              0.5078146897498674
                                 scale_standard T_eff              0.5078146897498674
                                 scale_robust   T_eff              0.5078146897498674
                                 scale_power    T_eff              0.5078146897498674
                                 scale_quantile T_eff              0.5052264532540854

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             98.025%
                                 scale_standard T_eff             98.025%
                                 scale_robust   T_eff             98.025%
                                 scale_power    T_eff             98.025%
                                 scale_quantile T_eff             98.025%
KNN               PARSEC         Base           T_eff             75.689%
                                 scale_standard T_eff             75.689%
                                 scale_robust   T_eff             75.689%
                                 scale_power    T_eff             75.658%
                                 scale_quantile T_eff             75.732%
linear_regression PARSEC         Base           T_eff             60.783%
                                 scale_standard T_eff             60.783%
                                 scale_robust   T_eff             60.783%
                                 scale_power    T_eff             59.659%
                                 scale_quantile T_eff             62.888%
mlp               PARSEC         Base           T_eff              91.71%
                                 scale_standard T_eff             79.922%
                                 scale_robust   T_eff             85.872%
                                 scale_power    T_eff             82.498%
                                 scale_quantile T_eff             76.568%
random_forest     PARSEC         Base           T_eff             91.103%
                                 scale_standard T_eff             89.879%
                                 scale_robust   T_eff             90.014%
                                 scale_power    T_eff             92.893%
                                 scale_quantile T_eff             91.446%
xgboost           PARSEC         Base           T_eff             80.315%
                                 scale_standard T_eff             80.315%
                                 scale_robust   T_eff             80.315%
                                 scale_power    T_eff             80.315%
                                 scale_quantile T_eff             80.569%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              75 : 4.426% / 90 : 10.253% / 95 : 16.975% / 99 : 28.523%
                                 scale_standard T_eff               75 : 4.424% / 90 : 10.211% / 95 : 16.93% / 99 : 28.441%
                                 scale_robust   T_eff              75 : 4.427% / 90 : 10.266% / 95 : 16.986% / 99 : 28.496%
                                 scale_power    T_eff               75 : 4.425% / 90 : 10.216% / 95 : 16.76% / 99 : 28.441%
                                 scale_quantile T_eff               75 : 4.426% / 90 : 10.28% / 95 : 16.894% / 99 : 28.452%
KNN               PARSEC         Base           T_eff              75 : 5.652% / 90 : 10.319% / 95 : 13.847% / 99 : 22.635%
                                 scale_standard T_eff              75 : 5.719% / 90 : 10.309% / 95 : 13.886% / 99 : 22.626%
                                 scale_robust   T_eff                75 : 5.643% / 90 : 10.271% / 95 : 13.88% / 99 : 22.36%
                                 scale_power    T_eff              75 : 5.985% / 90 : 10.508% / 95 : 14.137% / 99 : 22.823%
                                 scale_quantile T_eff              75 : 5.736% / 90 : 10.321% / 95 : 14.025% / 99 : 22.718%
linear_regression PARSEC         Base           T_eff              75 : 21.216% / 90 : 31.18% / 95 : 37.219% / 99 : 49.405%
                                 scale_standard T_eff              75 : 21.216% / 90 : 31.18% / 95 : 37.219% / 99 : 49.405%
                                 scale_robust   T_eff              75 : 21.216% / 90 : 31.18% / 95 : 37.219% / 99 : 49.405%
                                 scale_power    T_eff             75 : 20.931% / 90 : 31.291% / 95 : 37.757% / 99 : 49.671%
                                 scale_quantile T_eff             75 : 20.531% / 90 : 32.246% / 95 : 40.604% / 99 : 52.724%
mlp               PARSEC         Base           T_eff             75 : 24.852% / 90 : 40.536% / 95 : 51.705% / 99 : 71.969%
                                 scale_standard T_eff              75 : 20.24% / 90 : 35.434% / 95 : 46.832% / 99 : 63.436%
                                 scale_robust   T_eff             75 : 21.021% / 90 : 36.459% / 95 : 46.512% / 99 : 62.874%

Results for the label category with a value of 3.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459
KNN               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459
linear_regression PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459
mlp               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459
random_forest     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459
xgboost           PARSEC         Base           T_eff             3.4342 - 3.7459
                                 scale_standard T_eff             3.4342 - 3.7459
                                 scale_robust   T_eff             3.4342 - 3.7459
                                 scale_power    T_eff             3.4342 - 3.7459
                                 scale_quantile T_eff             3.4342 - 3.7459

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              -0.7632012932187855
                                 scale_standard T_eff               -0.765712135862846
                                 scale_robust   T_eff              -0.7618045724566715
                                 scale_power    T_eff              -0.7596825040201673
                                 scale_quantile T_eff               -0.759553384754228
KNN               PARSEC         Base           T_eff             -0.41965388075205157
                                 scale_standard T_eff             -0.42018751992952996
                                 scale_robust   T_eff              -0.4090065349839265
                                 scale_power    T_eff             -0.40627951341981006
                                 scale_quantile T_eff             -0.41617757506416564
linear_regression PARSEC         Base           T_eff               -3.483450834504893
                                 scale_standard T_eff              -3.4834508345047572
                                 scale_robust   T_eff              -3.4834508345048043
                                 scale_power    T_eff              -3.0883250413423964
                                 scale_quantile T_eff              -2.9259482915820443
mlp               PARSEC         Base           T_eff              -3.0626539193547986
                                 scale_standard T_eff              -3.4873794217578302
                                 scale_robust   T_eff              -2.6812646703417324
                                 scale_power    T_eff              -2.7000490876688024
                                 scale_quantile T_eff              -3.0778277483870173
random_forest     PARSEC         Base           T_eff              -0.5023320130390359
                                 scale_standard T_eff               -0.502167880219865
                                 scale_robust   T_eff              -0.5038973921571346
                                 scale_power    T_eff              -0.5017327367740403
                                 scale_quantile T_eff               -0.497386488375271
xgboost           PARSEC         Base           T_eff              -1.9217965476974368
                                 scale_standard T_eff              -1.9217965476974368
                                 scale_robust   T_eff              -1.9217965476974368
                                 scale_power    T_eff              -1.9217965476974368
                                 scale_quantile T_eff              -1.9137906879547835

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             19.896%
                                 scale_standard T_eff              19.91%
                                 scale_robust   T_eff             19.889%
                                 scale_power    T_eff             19.874%
                                 scale_quantile T_eff              19.88%
KNN               PARSEC         Base           T_eff             18.149%
                                 scale_standard T_eff             18.153%
                                 scale_robust   T_eff             18.082%
                                 scale_power    T_eff             18.034%
                                 scale_quantile T_eff             18.112%
linear_regression PARSEC         Base           T_eff             41.359%
                                 scale_standard T_eff             41.359%
                                 scale_robust   T_eff             41.359%
                                 scale_power    T_eff             42.487%
                                 scale_quantile T_eff             41.465%
mlp               PARSEC         Base           T_eff             37.217%
                                 scale_standard T_eff              34.56%
                                 scale_robust   T_eff             35.287%
                                 scale_power    T_eff             33.529%
                                 scale_quantile T_eff             33.912%
random_forest     PARSEC         Base           T_eff             18.473%
                                 scale_standard T_eff              18.47%
                                 scale_robust   T_eff              18.48%
                                 scale_power    T_eff             18.462%
                                 scale_quantile T_eff             18.444%
xgboost           PARSEC         Base           T_eff              30.84%
                                 scale_standard T_eff              30.84%
                                 scale_robust   T_eff              30.84%
                                 scale_power    T_eff              30.84%
                                 scale_quantile T_eff             30.771%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              8.733%
                                 scale_standard T_eff              8.737%
                                 scale_robust   T_eff               8.74%
                                 scale_power    T_eff              8.727%
                                 scale_quantile T_eff               8.73%
KNN               PARSEC         Base           T_eff              8.668%
                                 scale_standard T_eff               8.68%
                                 scale_robust   T_eff              8.657%
                                 scale_power    T_eff              8.625%
                                 scale_quantile T_eff              8.651%
linear_regression PARSEC         Base           T_eff             31.187%
                                 scale_standard T_eff             31.187%
                                 scale_robust   T_eff             31.187%
                                 scale_power    T_eff             33.119%
                                 scale_quantile T_eff             33.303%
mlp               PARSEC         Base           T_eff             28.052%
                                 scale_standard T_eff             24.472%
                                 scale_robust   T_eff             23.362%
                                 scale_power    T_eff             23.285%
                                 scale_quantile T_eff             24.927%
random_forest     PARSEC         Base           T_eff              8.402%
                                 scale_standard T_eff              8.396%
                                 scale_robust   T_eff              8.398%
                                 scale_power    T_eff              8.394%
                                 scale_quantile T_eff              8.393%
xgboost           PARSEC         Base           T_eff             19.855%
                                 scale_standard T_eff             19.855%
                                 scale_robust   T_eff             19.855%
                                 scale_power    T_eff             19.855%
                                 scale_quantile T_eff             19.758%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              1.205%
                                 scale_standard T_eff              1.207%
                                 scale_robust   T_eff              1.205%
                                 scale_power    T_eff              1.206%
                                 scale_quantile T_eff              1.206%
KNN               PARSEC         Base           T_eff              2.156%
                                 scale_standard T_eff              2.137%
                                 scale_robust   T_eff               2.13%
                                 scale_power    T_eff              2.073%
                                 scale_quantile T_eff              2.137%
linear_regression PARSEC         Base           T_eff               23.8%
                                 scale_standard T_eff               23.8%
                                 scale_robust   T_eff               23.8%
                                 scale_power    T_eff             27.444%
                                 scale_quantile T_eff             29.424%
mlp               PARSEC         Base           T_eff             20.548%
                                 scale_standard T_eff             16.051%
                                 scale_robust   T_eff             11.837%
                                 scale_power    T_eff             14.505%
                                 scale_quantile T_eff             17.176%
random_forest     PARSEC         Base           T_eff                1.5%
                                 scale_standard T_eff              1.501%
                                 scale_robust   T_eff              1.493%
                                 scale_power    T_eff              1.487%
                                 scale_quantile T_eff              1.492%
xgboost           PARSEC         Base           T_eff              8.087%
                                 scale_standard T_eff              8.087%
                                 scale_robust   T_eff              8.087%
                                 scale_power    T_eff              8.087%
                                 scale_quantile T_eff              7.953%

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.124189042946256
                                 scale_standard T_eff              0.12322660736756483
                                 scale_robust   T_eff              0.12379439602130168
                                 scale_power    T_eff              0.12450767903155473
                                 scale_quantile T_eff              0.12500378804352452
KNN               PARSEC         Base           T_eff              0.16510527785954335
                                 scale_standard T_eff              0.16146402687584283
                                 scale_robust   T_eff              0.16600544810889664
                                 scale_power    T_eff               0.1627432293310915
                                 scale_quantile T_eff              0.16615525739004816
linear_regression PARSEC         Base           T_eff              0.10169028688444401
                                 scale_standard T_eff              0.10169028688444436
                                 scale_robust   T_eff               0.1016902868844453
                                 scale_power    T_eff              0.12353176859941471
                                 scale_quantile T_eff              0.16349997369488806
mlp               PARSEC         Base           T_eff              0.07525042007796028
                                 scale_standard T_eff              0.06884655733649261
                                 scale_robust   T_eff             0.024273972408995363
                                 scale_power    T_eff              0.05911328788462665
                                 scale_quantile T_eff              0.03480395109735081
random_forest     PARSEC         Base           T_eff               0.1670618613045383
                                 scale_standard T_eff               0.1677053900099275
                                 scale_robust   T_eff              0.16732473819522553
                                 scale_power    T_eff              0.16690845551842973
                                 scale_quantile T_eff              0.16913492051098078
xgboost           PARSEC         Base           T_eff             0.050496683069772764
                                 scale_standard T_eff             0.050496683069772764
                                 scale_robust   T_eff             0.050496683069772764
                                 scale_power    T_eff             0.050496683069772764
                                 scale_quantile T_eff             0.050322641543631766

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             266.218%
                                 scale_standard T_eff             266.218%
                                 scale_robust   T_eff             266.218%
                                 scale_power    T_eff             266.218%
                                 scale_quantile T_eff             266.218%
KNN               PARSEC         Base           T_eff             260.918%
                                 scale_standard T_eff             260.918%
                                 scale_robust   T_eff             260.918%
                                 scale_power    T_eff             260.918%
                                 scale_quantile T_eff             260.918%
linear_regression PARSEC         Base           T_eff             121.945%
                                 scale_standard T_eff             121.945%
                                 scale_robust   T_eff             121.945%
                                 scale_power    T_eff             119.638%
                                 scale_quantile T_eff             114.293%
mlp               PARSEC         Base           T_eff             197.502%
                                 scale_standard T_eff             172.326%
                                 scale_robust   T_eff             160.228%
                                 scale_power    T_eff             133.354%
                                 scale_quantile T_eff             194.768%
random_forest     PARSEC         Base           T_eff             258.747%
                                 scale_standard T_eff             264.343%
                                 scale_robust   T_eff             262.436%
                                 scale_power    T_eff              264.26%
                                 scale_quantile T_eff             264.144%
xgboost           PARSEC         Base           T_eff             123.856%
                                 scale_standard T_eff             123.856%
                                 scale_robust   T_eff             123.856%
                                 scale_power    T_eff             123.856%
                                 scale_quantile T_eff             123.841%

                                                                                                                 Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               75 : 7.042% / 90 : 30.831% / 95 : 46.295% / 99 : 75.842%
                                 scale_standard T_eff                75 : 7.026% / 90 : 30.95% / 95 : 46.295% / 99 : 75.858%
                                 scale_robust   T_eff                75 : 7.048% / 90 : 30.95% / 95 : 46.301% / 99 : 76.012%
                                 scale_power    T_eff               75 : 7.058% / 90 : 30.751% / 95 : 46.141% / 99 : 75.858%
                                 scale_quantile T_eff               75 : 7.032% / 90 : 30.863% / 95 : 46.269% / 99 : 75.906%
KNN               PARSEC         Base           T_eff               75 : 9.387% / 90 : 26.814% / 95 : 40.542% / 99 : 68.322%
                                 scale_standard T_eff                75 : 9.381% / 90 : 26.763% / 95 : 40.86% / 99 : 68.194%
                                 scale_robust   T_eff               75 : 9.339% / 90 : 26.721% / 95 : 40.728% / 99 : 68.139%
                                 scale_power    T_eff               75 : 9.355% / 90 : 26.606% / 95 : 40.574% / 99 : 67.924%
                                 scale_quantile T_eff               75 : 9.413% / 90 : 26.644% / 95 : 40.359% / 99 : 68.377%
linear_regression PARSEC         Base           T_eff             75 : 42.031% / 90 : 75.585% / 95 : 95.342% / 99 : 108.572%
                                 scale_standard T_eff             75 : 42.031% / 90 : 75.585% / 95 : 95.342% / 99 : 108.572%
                                 scale_robust   T_eff             75 : 42.031% / 90 : 75.585% / 95 : 95.342% / 99 : 108.572%
                                 scale_power    T_eff             75 : 45.271% / 90 : 74.001% / 95 : 93.503% / 99 : 108.739%
                                 scale_quantile T_eff              75 : 47.369% / 90 : 68.72% / 95 : 85.034% / 99 : 100.581%
mlp               PARSEC         Base           T_eff             75 : 38.845% / 90 : 60.632% / 95 : 72.105% / 99 : 119.012%
                                 scale_standard T_eff             75 : 34.225% / 90 : 57.783% / 95 : 75.072% / 99 : 110.533%

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786
KNN               PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786
linear_regression PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786
mlp               PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786
random_forest     PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786
xgboost           PARSEC         Base           T_eff             3.5328 - 3.786
                                 scale_standard T_eff             3.5328 - 3.786
                                 scale_robust   T_eff             3.5328 - 3.786
                                 scale_power    T_eff             3.5328 - 3.786
                                 scale_quantile T_eff             3.5328 - 3.786

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.5441135519545068
                                 scale_standard T_eff              0.5280927951335781
                                 scale_robust   T_eff              0.5270607090720028
                                 scale_power    T_eff              0.5351324084733762
                                 scale_quantile T_eff              0.5507394226764424
KNN               PARSEC         Base           T_eff              0.6904163446197727
                                 scale_standard T_eff              0.7023329705648952
                                 scale_robust   T_eff              0.7011370890120614
                                 scale_power    T_eff              0.7013760378784186
                                 scale_quantile T_eff              0.6944922273208353
linear_regression PARSEC         Base           T_eff               -7.16132505869397
                                 scale_standard T_eff              -7.161325058693736
                                 scale_robust   T_eff             -7.1613250586937856
                                 scale_power    T_eff              -7.047126887293848
                                 scale_quantile T_eff               -6.80055105801536
mlp               PARSEC         Base           T_eff               -4.48744266439307
                                 scale_standard T_eff             -2.3196334647824774
                                 scale_robust   T_eff             -1.7695195893712037
                                 scale_power    T_eff             -2.1540534738830464
                                 scale_quantile T_eff             -3.6146175225387474
random_forest     PARSEC         Base           T_eff                0.65911942798238
                                 scale_standard T_eff              0.6504835140264941
                                 scale_robust   T_eff              0.6473068149930608
                                 scale_power    T_eff              0.6479223093474235
                                 scale_quantile T_eff              0.6570761061858112
xgboost           PARSEC         Base           T_eff             -0.3014297238793202
                                 scale_standard T_eff             -0.3014297238793202
                                 scale_robust   T_eff             -0.3014297238793202
                                 scale_power    T_eff             -0.3014297238793202
                                 scale_quantile T_eff             -0.2901452080480087

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              8.184%
                                 scale_standard T_eff              8.326%
                                 scale_robust   T_eff              8.335%
                                 scale_power    T_eff              8.264%
                                 scale_quantile T_eff              8.124%
KNN               PARSEC         Base           T_eff              6.744%
                                 scale_standard T_eff              6.613%
                                 scale_robust   T_eff              6.626%
                                 scale_power    T_eff              6.624%
                                 scale_quantile T_eff              6.699%
linear_regression PARSEC         Base           T_eff              35.89%
                                 scale_standard T_eff              35.89%
                                 scale_robust   T_eff              35.89%
                                 scale_power    T_eff             36.712%
                                 scale_quantile T_eff             36.285%
mlp               PARSEC         Base           T_eff             30.823%
                                 scale_standard T_eff              22.14%
                                 scale_robust   T_eff             21.403%
                                 scale_power    T_eff             21.888%
                                 scale_quantile T_eff             26.074%
random_forest     PARSEC         Base           T_eff              7.077%
                                 scale_standard T_eff              7.166%
                                 scale_robust   T_eff              7.198%
                                 scale_power    T_eff              7.192%
                                 scale_quantile T_eff              7.098%
xgboost           PARSEC         Base           T_eff             14.413%
                                 scale_standard T_eff             14.413%
                                 scale_robust   T_eff             14.413%
                                 scale_power    T_eff             14.413%
                                 scale_quantile T_eff             14.356%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              1.512%
                                 scale_standard T_eff               1.52%
                                 scale_robust   T_eff              1.517%
                                 scale_power    T_eff              1.514%
                                 scale_quantile T_eff              1.509%
KNN               PARSEC         Base           T_eff              1.642%
                                 scale_standard T_eff              1.623%
                                 scale_robust   T_eff              1.624%
                                 scale_power    T_eff                1.6%
                                 scale_quantile T_eff              1.617%
linear_regression PARSEC         Base           T_eff             23.971%
                                 scale_standard T_eff             23.971%
                                 scale_robust   T_eff             23.971%
                                 scale_power    T_eff             25.614%
                                 scale_quantile T_eff             26.874%
mlp               PARSEC         Base           T_eff             23.336%
                                 scale_standard T_eff             14.225%
                                 scale_robust   T_eff             10.741%
                                 scale_power    T_eff             13.046%
                                 scale_quantile T_eff             17.239%
random_forest     PARSEC         Base           T_eff              1.539%
                                 scale_standard T_eff              1.548%
                                 scale_robust   T_eff              1.548%
                                 scale_power    T_eff              1.545%
                                 scale_quantile T_eff              1.543%
xgboost           PARSEC         Base           T_eff              5.182%
                                 scale_standard T_eff              5.182%
                                 scale_robust   T_eff              5.182%
                                 scale_power    T_eff              5.182%
                                 scale_quantile T_eff              5.156%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.3%
                                 scale_standard T_eff                0.3%
                                 scale_robust   T_eff                0.3%
                                 scale_power    T_eff                0.3%
                                 scale_quantile T_eff                0.3%
KNN               PARSEC         Base           T_eff              0.158%
                                 scale_standard T_eff              0.158%
                                 scale_robust   T_eff              0.158%
                                 scale_power    T_eff              0.158%
                                 scale_quantile T_eff              0.166%
linear_regression PARSEC         Base           T_eff             17.219%
                                 scale_standard T_eff             17.219%
                                 scale_robust   T_eff             17.219%
                                 scale_power    T_eff             19.566%
                                 scale_quantile T_eff             21.902%
mlp               PARSEC         Base           T_eff             19.649%
                                 scale_standard T_eff               8.87%
                                 scale_robust   T_eff              5.751%
                                 scale_power    T_eff              7.635%
                                 scale_quantile T_eff             10.149%
random_forest     PARSEC         Base           T_eff               0.31%
                                 scale_standard T_eff              0.311%
                                 scale_robust   T_eff              0.309%
                                 scale_power    T_eff               0.31%
                                 scale_quantile T_eff              0.309%
xgboost           PARSEC         Base           T_eff              1.515%
                                 scale_standard T_eff              1.515%
                                 scale_robust   T_eff              1.515%
                                 scale_power    T_eff              1.515%
                                 scale_quantile T_eff              1.523%

                                                                                    CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 0.7961889196467123
                                 scale_standard T_eff                  0.790574363196574
                                 scale_robust   T_eff                 0.7900331363309497
                                 scale_power    T_eff                 0.7925872052261775
                                 scale_quantile T_eff                 0.7988385196849132
KNN               PARSEC         Base           T_eff                 0.8501678081907662
                                 scale_standard T_eff                 0.8561164660485321
                                 scale_robust   T_eff                 0.8554388871958112
                                 scale_power    T_eff                 0.8559705974042815
                                 scale_quantile T_eff                 0.8528384573483493
linear_regression PARSEC         Base           T_eff               -0.21481121752618543
                                 scale_standard T_eff                -0.2148112175261856
                                 scale_robust   T_eff               -0.21481121752618054
                                 scale_power    T_eff               -0.19922337375462204
                                 scale_quantile T_eff                -0.1422766584887203
mlp               PARSEC         Base           T_eff               0.023312409206957985
                                 scale_standard T_eff                0.05180661185182567
                                 scale_robust   T_eff             -0.0032172257194300453
                                 scale_power    T_eff                0.15967335511117234
                                 scale_quantile T_eff               -0.02409942462777568
random_forest     PARSEC         Base           T_eff                  0.836128348980831
                                 scale_standard T_eff                 0.8324765475492972
                                 scale_robust   T_eff                 0.8311900314409387
                                 scale_power    T_eff                 0.8314076620501698
                                 scale_quantile T_eff                 0.8352131385516689
xgboost           PARSEC         Base           T_eff                  0.377210711992698
                                 scale_standard T_eff                  0.377210711992698
                                 scale_robust   T_eff                  0.377210711992698
                                 scale_power    T_eff                  0.377210711992698
                                 scale_quantile T_eff                 0.3806784174818322

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              332.03%
                                 scale_standard T_eff              332.03%
                                 scale_robust   T_eff              332.03%
                                 scale_power    T_eff              332.03%
                                 scale_quantile T_eff              332.03%
KNN               PARSEC         Base           T_eff             327.464%
                                 scale_standard T_eff              325.94%
                                 scale_robust   T_eff             327.464%
                                 scale_power    T_eff             317.425%
                                 scale_quantile T_eff             327.464%
linear_regression PARSEC         Base           T_eff             147.685%
                                 scale_standard T_eff             147.685%
                                 scale_robust   T_eff             147.685%
                                 scale_power    T_eff             146.637%
                                 scale_quantile T_eff             140.268%
mlp               PARSEC         Base           T_eff             243.737%
                                 scale_standard T_eff             198.589%
                                 scale_robust   T_eff             197.164%
                                 scale_power    T_eff             161.249%
                                 scale_quantile T_eff             239.637%
random_forest     PARSEC         Base           T_eff             327.409%
                                 scale_standard T_eff             329.071%
                                 scale_robust   T_eff             331.433%
                                 scale_power    T_eff             329.355%
                                 scale_quantile T_eff              322.44%
xgboost           PARSEC         Base           T_eff             158.685%
                                 scale_standard T_eff             158.685%
                                 scale_robust   T_eff             158.685%
                                 scale_power    T_eff             158.685%
                                 scale_quantile T_eff             175.518%

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                  75 : 1.244% / 90 : 2.946% / 95 : 5.158% / 99 : 14.498%
                                 scale_standard T_eff                   75 : 1.244% / 90 : 2.942% / 95 : 5.15% / 99 : 14.427%
                                 scale_robust   T_eff                   75 : 1.244% / 90 : 2.938% / 95 : 5.13% / 99 : 14.415%
                                 scale_power    T_eff                  75 : 1.244% / 90 : 2.938% / 95 : 5.142% / 99 : 14.431%
                                 scale_quantile T_eff                  75 : 1.244% / 90 : 2.942% / 95 : 5.146% / 99 : 14.566%
KNN               PARSEC         Base           T_eff                  75 : 0.727% / 90 : 4.818% / 95 : 9.392% / 99 : 15.908%
                                 scale_standard T_eff                  75 : 0.727% / 90 : 4.897% / 95 : 9.423% / 99 : 15.932%
                                 scale_robust   T_eff                  75 : 0.735% / 90 : 4.771% / 95 : 9.415% / 99 : 15.466%
                                 scale_power    T_eff                  75 : 0.719% / 90 : 4.589% / 95 : 9.336% / 99 : 15.513%
                                 scale_quantile T_eff                  75 : 0.735% / 90 : 4.763% / 95 : 9.423% / 99 : 15.454%
linear_regression PARSEC         Base           T_eff              75 : 26.88% / 90 : 45.983% / 95 : 104.964% / 99 : 127.567%
                                 scale_standard T_eff              75 : 26.88% / 90 : 45.983% / 95 : 104.964% / 99 : 127.567%
                                 scale_robust   T_eff              75 : 26.88% / 90 : 45.983% / 95 : 104.964% / 99 : 127.567%
                                 scale_power    T_eff             75 : 29.463% / 90 : 47.168% / 95 : 101.947% / 99 : 126.679%
                                 scale_quantile T_eff              75 : 33.337% / 90 : 50.778% / 95 : 92.014% / 99 : 115.715%
mlp               PARSEC         Base           T_eff              75 : 28.558% / 90 : 39.755% / 95 : 61.209% / 99 : 108.594%
                                 scale_standard T_eff               75 : 19.143% / 90 : 28.337% / 95 : 49.459% / 99 : 81.102%

Results for the label category with a value of 5.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272
KNN               PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272
linear_regression PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272
mlp               PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272
random_forest     PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272
xgboost           PARSEC         Base           T_eff             3.5642 - 4.272
                                 scale_standard T_eff             3.5642 - 4.272
                                 scale_robust   T_eff             3.5642 - 4.272
                                 scale_power    T_eff             3.5642 - 4.272
                                 scale_quantile T_eff             3.5642 - 4.272

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.875456632791973
                                 scale_standard T_eff               0.8753790213593057
                                 scale_robust   T_eff               0.8759638416807798
                                 scale_power    T_eff               0.8718856861813428
                                 scale_quantile T_eff                0.872901526456852
KNN               PARSEC         Base           T_eff               0.8952904959736894
                                 scale_standard T_eff               0.8928281039510458
                                 scale_robust   T_eff               0.8953404425040046
                                 scale_power    T_eff               0.8917270958379928
                                 scale_quantile T_eff               0.8966643201433675
linear_regression PARSEC         Base           T_eff              0.13546196696769075
                                 scale_standard T_eff               0.1354619669676933
                                 scale_robust   T_eff               0.1354619669676972
                                 scale_power    T_eff              0.19658605406872476
                                 scale_quantile T_eff              0.21600646052770633
mlp               PARSEC         Base           T_eff             -0.29273083625011354
                                 scale_standard T_eff               0.2611773599171525
                                 scale_robust   T_eff              0.17784359940981853
                                 scale_power    T_eff              0.16702187373704802
                                 scale_quantile T_eff              0.10997475768226728
random_forest     PARSEC         Base           T_eff               0.9079086436663277
                                 scale_standard T_eff               0.9062134875978403
                                 scale_robust   T_eff               0.9061344884473743
                                 scale_power    T_eff               0.9056107960862043
                                 scale_quantile T_eff               0.9062623009064791
xgboost           PARSEC         Base           T_eff               0.4646243180794113
                                 scale_standard T_eff               0.4646243180794113
                                 scale_robust   T_eff               0.4646243180794113
                                 scale_power    T_eff               0.4646243180794113
                                 scale_quantile T_eff              0.45630595799045026

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              5.708%
                                 scale_standard T_eff               5.71%
                                 scale_robust   T_eff              5.696%
                                 scale_power    T_eff               5.79%
                                 scale_quantile T_eff              5.766%
KNN               PARSEC         Base           T_eff              5.243%
                                 scale_standard T_eff              5.308%
                                 scale_robust   T_eff              5.244%
                                 scale_power    T_eff              5.326%
                                 scale_quantile T_eff              5.206%
linear_regression PARSEC         Base           T_eff             22.815%
                                 scale_standard T_eff             22.815%
                                 scale_robust   T_eff             22.815%
                                 scale_power    T_eff             22.686%
                                 scale_quantile T_eff             21.477%
mlp               PARSEC         Base           T_eff              19.37%
                                 scale_standard T_eff             13.901%
                                 scale_robust   T_eff             15.125%
                                 scale_power    T_eff             14.853%
                                 scale_quantile T_eff             16.303%
random_forest     PARSEC         Base           T_eff              4.908%
                                 scale_standard T_eff              4.953%
                                 scale_robust   T_eff              4.955%
                                 scale_power    T_eff              4.969%
                                 scale_quantile T_eff              4.952%
xgboost           PARSEC         Base           T_eff             12.126%
                                 scale_standard T_eff             12.126%
                                 scale_robust   T_eff             12.126%
                                 scale_power    T_eff             12.126%
                                 scale_quantile T_eff             12.204%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              1.346%
                                 scale_standard T_eff              1.341%
                                 scale_robust   T_eff               1.34%
                                 scale_power    T_eff              1.352%
                                 scale_quantile T_eff              1.353%
KNN               PARSEC         Base           T_eff              2.055%
                                 scale_standard T_eff              2.071%
                                 scale_robust   T_eff               2.06%
                                 scale_power    T_eff              2.057%
                                 scale_quantile T_eff              2.013%
linear_regression PARSEC         Base           T_eff             19.384%
                                 scale_standard T_eff             19.384%
                                 scale_robust   T_eff             19.384%
                                 scale_power    T_eff             19.618%
                                 scale_quantile T_eff             18.866%
mlp               PARSEC         Base           T_eff             15.027%
                                 scale_standard T_eff               9.91%
                                 scale_robust   T_eff             10.777%
                                 scale_power    T_eff             10.606%
                                 scale_quantile T_eff             12.614%
random_forest     PARSEC         Base           T_eff              1.346%
                                 scale_standard T_eff              1.363%
                                 scale_robust   T_eff              1.361%
                                 scale_power    T_eff              1.354%
                                 scale_quantile T_eff              1.359%
xgboost           PARSEC         Base           T_eff              8.339%
                                 scale_standard T_eff              8.339%
                                 scale_robust   T_eff              8.339%
                                 scale_power    T_eff              8.339%
                                 scale_quantile T_eff              8.365%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.0%
                                 scale_standard T_eff                0.0%
                                 scale_robust   T_eff                0.0%
                                 scale_power    T_eff                0.0%
                                 scale_quantile T_eff                0.0%
KNN               PARSEC         Base           T_eff              0.155%
                                 scale_standard T_eff              0.153%
                                 scale_robust   T_eff              0.155%
                                 scale_power    T_eff              0.153%
                                 scale_quantile T_eff              0.161%
linear_regression PARSEC         Base           T_eff              15.99%
                                 scale_standard T_eff              15.99%
                                 scale_robust   T_eff              15.99%
                                 scale_power    T_eff             16.518%
                                 scale_quantile T_eff             16.548%
mlp               PARSEC         Base           T_eff              11.58%
                                 scale_standard T_eff              6.167%
                                 scale_robust   T_eff              6.756%
                                 scale_power    T_eff              6.952%
                                 scale_quantile T_eff             10.321%
random_forest     PARSEC         Base           T_eff              0.062%
                                 scale_standard T_eff              0.064%
                                 scale_robust   T_eff              0.063%
                                 scale_power    T_eff              0.063%
                                 scale_quantile T_eff              0.064%
xgboost           PARSEC         Base           T_eff              4.855%
                                 scale_standard T_eff              4.855%
                                 scale_robust   T_eff              4.855%
                                 scale_power    T_eff              4.855%
                                 scale_quantile T_eff              4.733%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9382230012465637
                                 scale_standard T_eff              0.9381838713498403
                                 scale_robust   T_eff              0.9384350097349261
                                 scale_power    T_eff              0.9365445651005092
                                 scale_quantile T_eff              0.9370107967865656
KNN               PARSEC         Base           T_eff              0.9462976094851531
                                 scale_standard T_eff              0.9452398286782703
                                 scale_robust   T_eff              0.9464624814372671
                                 scale_power    T_eff              0.9445340797138089
                                 scale_quantile T_eff              0.9469474004668283
linear_regression PARSEC         Base           T_eff             0.40357511224693443
                                 scale_standard T_eff              0.4035751122469339
                                 scale_robust   T_eff             0.40357511224693854
                                 scale_power    T_eff               0.451064720897424
                                 scale_quantile T_eff               0.468148137847202
mlp               PARSEC         Base           T_eff              0.3425653519856123
                                 scale_standard T_eff              0.5217169584286139
                                 scale_robust   T_eff              0.4629469301248009
                                 scale_power    T_eff               0.454930517930612
                                 scale_quantile T_eff             0.40781944845640894
random_forest     PARSEC         Base           T_eff              0.9534772118510992
                                 scale_standard T_eff              0.9526068756454232
                                 scale_robust   T_eff              0.9525855379158273
                                 scale_power    T_eff              0.9523482466235247
                                 scale_quantile T_eff              0.9526448688451884
xgboost           PARSEC         Base           T_eff                0.68203526589872
                                 scale_standard T_eff                0.68203526589872
                                 scale_robust   T_eff                0.68203526589872
                                 scale_power    T_eff                0.68203526589872
                                 scale_quantile T_eff              0.6757913087789336

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             103.801%
                                 scale_standard T_eff             103.801%
                                 scale_robust   T_eff             103.801%
                                 scale_power    T_eff             103.801%
                                 scale_quantile T_eff             103.801%
KNN               PARSEC         Base           T_eff              76.363%
                                 scale_standard T_eff              76.363%
                                 scale_robust   T_eff              76.363%
                                 scale_power    T_eff              76.363%
                                 scale_quantile T_eff              76.363%
linear_regression PARSEC         Base           T_eff              48.837%
                                 scale_standard T_eff              48.837%
                                 scale_robust   T_eff              48.837%
                                 scale_power    T_eff              48.555%
                                 scale_quantile T_eff              50.093%
mlp               PARSEC         Base           T_eff              77.303%
                                 scale_standard T_eff              58.409%
                                 scale_robust   T_eff              63.312%
                                 scale_power    T_eff              56.333%
                                 scale_quantile T_eff              62.711%
random_forest     PARSEC         Base           T_eff               71.01%
                                 scale_standard T_eff              70.941%
                                 scale_robust   T_eff              70.055%
                                 scale_power    T_eff              71.315%
                                 scale_quantile T_eff              72.621%
xgboost           PARSEC         Base           T_eff              78.243%
                                 scale_standard T_eff              78.243%
                                 scale_robust   T_eff              78.243%
                                 scale_power    T_eff              78.243%
                                 scale_quantile T_eff              78.218%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 0.254% / 90 : 2.218% / 95 : 5.736% / 99 : 30.191%
                                 scale_standard T_eff                75 : 0.249% / 90 : 2.218% / 95 : 5.711% / 99 : 30.184%
                                 scale_robust   T_eff                75 : 0.254% / 90 : 2.232% / 95 : 5.708% / 99 : 30.184%
                                 scale_power    T_eff                75 : 0.254% / 90 : 2.211% / 95 : 5.718% / 99 : 30.931%
                                 scale_quantile T_eff                 75 : 0.247% / 90 : 2.259% / 95 : 5.76% / 99 : 31.592%
KNN               PARSEC         Base           T_eff                75 : 2.077% / 90 : 5.259% / 95 : 9.261% / 99 : 25.588%
                                 scale_standard T_eff                75 : 2.094% / 90 : 5.276% / 95 : 9.445% / 99 : 26.994%
                                 scale_robust   T_eff                  75 : 2.08% / 90 : 5.29% / 95 : 9.315% / 99 : 27.152%
                                 scale_power    T_eff                  75 : 2.05% / 90 : 5.25% / 95 : 9.306% / 99 : 27.008%
                                 scale_quantile T_eff                 75 : 2.034% / 90 : 5.14% / 95 : 8.949% / 99 : 25.588%
linear_regression PARSEC         Base           T_eff             75 : 27.056% / 90 : 39.665% / 95 : 43.648% / 99 : 47.563%
                                 scale_standard T_eff             75 : 27.056% / 90 : 39.665% / 95 : 43.648% / 99 : 47.563%
                                 scale_robust   T_eff             75 : 27.056% / 90 : 39.665% / 95 : 43.648% / 99 : 47.563%
                                 scale_power    T_eff              75 : 26.267% / 90 : 38.874% / 95 : 43.11% / 99 : 46.509%
                                 scale_quantile T_eff             75 : 24.106% / 90 : 35.767% / 95 : 39.852% / 99 : 44.161%
mlp               PARSEC         Base           T_eff             75 : 18.813% / 90 : 32.396% / 95 : 42.357% / 99 : 56.854%
                                 scale_standard T_eff              75 : 14.743% / 90 : 23.418% / 95 : 30.24% / 99 : 42.012%
                                 scale_robust   T_eff              75 : 15.825% / 90 : 27.188% / 95 : 33.76% / 99 : 42.006%

Results for the label category with a value of 6.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601
KNN               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601
linear_regression PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601
mlp               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601
random_forest     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601
xgboost           PARSEC         Base           T_eff             3.5416 - 4.2601
                                 scale_standard T_eff             3.5416 - 4.2601
                                 scale_robust   T_eff             3.5416 - 4.2601
                                 scale_power    T_eff             3.5416 - 4.2601
                                 scale_quantile T_eff             3.5416 - 4.2601

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.9361134687179025
                                 scale_standard T_eff               0.9343331922797743
                                 scale_robust   T_eff               0.9313804625450004
                                 scale_power    T_eff               0.9335271417804964
                                 scale_quantile T_eff               0.9341691024450434
KNN               PARSEC         Base           T_eff               0.9418003454905226
                                 scale_standard T_eff               0.9444078157907692
                                 scale_robust   T_eff               0.9441429006917099
                                 scale_power    T_eff               0.9441888737073786
                                 scale_quantile T_eff               0.9445928714573544
linear_regression PARSEC         Base           T_eff              0.20764377732401518
                                 scale_standard T_eff               0.2076437773240165
                                 scale_robust   T_eff               0.2076437773240153
                                 scale_power    T_eff               0.2559986532156384
                                 scale_quantile T_eff              0.22723644316981695
mlp               PARSEC         Base           T_eff             0.032533794358943324
                                 scale_standard T_eff               0.4842996305738957
                                 scale_robust   T_eff               0.4473184175004995
                                 scale_power    T_eff              0.42606761473772015
                                 scale_quantile T_eff              0.28733267264363027
random_forest     PARSEC         Base           T_eff               0.9516275813074686
                                 scale_standard T_eff               0.9500674280981861
                                 scale_robust   T_eff               0.9505132486668101
                                 scale_power    T_eff               0.9500018968227976
                                 scale_quantile T_eff               0.9496981388910944
xgboost           PARSEC         Base           T_eff               0.6654556763318269
                                 scale_standard T_eff               0.6654556763318269
                                 scale_robust   T_eff               0.6654556763318269
                                 scale_power    T_eff               0.6654556763318269
                                 scale_quantile T_eff               0.6570018220816295

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              5.403%
                                 scale_standard T_eff              5.477%
                                 scale_robust   T_eff              5.599%
                                 scale_power    T_eff               5.51%
                                 scale_quantile T_eff              5.484%
KNN               PARSEC         Base           T_eff              5.161%
                                 scale_standard T_eff              5.048%
                                 scale_robust   T_eff              5.058%
                                 scale_power    T_eff              5.084%
                                 scale_quantile T_eff              5.035%
linear_regression PARSEC         Base           T_eff             23.357%
                                 scale_standard T_eff             23.357%
                                 scale_robust   T_eff             23.357%
                                 scale_power    T_eff             23.051%
                                 scale_quantile T_eff             21.942%
mlp               PARSEC         Base           T_eff             21.147%
                                 scale_standard T_eff             15.942%
                                 scale_robust   T_eff             15.967%
                                 scale_power    T_eff             16.303%
                                 scale_quantile T_eff             18.037%
random_forest     PARSEC         Base           T_eff              4.702%
                                 scale_standard T_eff              4.778%
                                 scale_robust   T_eff              4.756%
                                 scale_power    T_eff              4.779%
                                 scale_quantile T_eff              4.796%
xgboost           PARSEC         Base           T_eff             12.394%
                                 scale_standard T_eff             12.394%
                                 scale_robust   T_eff             12.394%
                                 scale_power    T_eff             12.394%
                                 scale_quantile T_eff             12.537%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              1.518%
                                 scale_standard T_eff              1.524%
                                 scale_robust   T_eff               1.56%
                                 scale_power    T_eff              1.543%
                                 scale_quantile T_eff              1.536%
KNN               PARSEC         Base           T_eff              2.788%
                                 scale_standard T_eff              2.761%
                                 scale_robust   T_eff              2.773%
                                 scale_power    T_eff               2.84%
                                 scale_quantile T_eff              2.733%
linear_regression PARSEC         Base           T_eff             19.841%
                                 scale_standard T_eff             19.841%
                                 scale_robust   T_eff             19.841%
                                 scale_power    T_eff             19.755%
                                 scale_quantile T_eff             18.835%
mlp               PARSEC         Base           T_eff             16.811%
                                 scale_standard T_eff             12.491%
                                 scale_robust   T_eff             12.453%
                                 scale_power    T_eff             12.893%
                                 scale_quantile T_eff              14.58%
random_forest     PARSEC         Base           T_eff              1.474%
                                 scale_standard T_eff              1.478%
                                 scale_robust   T_eff              1.477%
                                 scale_power    T_eff               1.49%
                                 scale_quantile T_eff              1.484%
xgboost           PARSEC         Base           T_eff              9.398%
                                 scale_standard T_eff              9.398%
                                 scale_robust   T_eff              9.398%
                                 scale_power    T_eff              9.398%
                                 scale_quantile T_eff              9.459%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.487%
                                 scale_standard T_eff              0.487%
                                 scale_robust   T_eff              0.487%
                                 scale_power    T_eff              0.487%
                                 scale_quantile T_eff              0.487%
KNN               PARSEC         Base           T_eff              1.598%
                                 scale_standard T_eff              1.606%
                                 scale_robust   T_eff              1.614%
                                 scale_power    T_eff              1.708%
                                 scale_quantile T_eff               1.55%
linear_regression PARSEC         Base           T_eff             17.694%
                                 scale_standard T_eff             17.694%
                                 scale_robust   T_eff             17.694%
                                 scale_power    T_eff             18.097%
                                 scale_quantile T_eff              17.91%
mlp               PARSEC         Base           T_eff             13.658%
                                 scale_standard T_eff             10.119%
                                 scale_robust   T_eff             10.233%
                                 scale_power    T_eff             10.522%
                                 scale_quantile T_eff              12.41%
random_forest     PARSEC         Base           T_eff              0.435%
                                 scale_standard T_eff              0.439%
                                 scale_robust   T_eff              0.434%
                                 scale_power    T_eff              0.441%
                                 scale_quantile T_eff              0.439%
xgboost           PARSEC         Base           T_eff              7.168%
                                 scale_standard T_eff              7.168%
                                 scale_robust   T_eff              7.168%
                                 scale_power    T_eff              7.168%
                                 scale_quantile T_eff              7.236%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9682850567668624
                                 scale_standard T_eff              0.9674263717777054
                                 scale_robust   T_eff               0.965932565824477
                                 scale_power    T_eff              0.9670225527037652
                                 scale_quantile T_eff              0.9673093167946908
KNN               PARSEC         Base           T_eff              0.9705614825838571
                                 scale_standard T_eff              0.9719813406171783
                                 scale_robust   T_eff              0.9718129118630896
                                 scale_power    T_eff              0.9718737095596546
                                 scale_quantile T_eff              0.9720023929849728
linear_regression PARSEC         Base           T_eff               0.478529160628656
                                 scale_standard T_eff              0.4785291606286608
                                 scale_robust   T_eff              0.4785291606286583
                                 scale_power    T_eff              0.5596994154891611
                                 scale_quantile T_eff              0.5821818966543868
mlp               PARSEC         Base           T_eff             0.41841265241488523
                                 scale_standard T_eff              0.7312419086278642
                                 scale_robust   T_eff              0.6807610260743331
                                 scale_power    T_eff              0.6693056665269731
                                 scale_quantile T_eff              0.5369717236148125
random_forest     PARSEC         Base           T_eff              0.9756452395472536
                                 scale_standard T_eff              0.9748678778726847
                                 scale_robust   T_eff              0.9750899354379826
                                 scale_power    T_eff              0.9748430077732182
                                 scale_quantile T_eff               0.974677051451561
xgboost           PARSEC         Base           T_eff              0.8235404788604241
                                 scale_standard T_eff              0.8235404788604241
                                 scale_robust   T_eff              0.8235404788604241
                                 scale_power    T_eff              0.8235404788604241
                                 scale_quantile T_eff              0.8180593997521997

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             101.364%
                                 scale_standard T_eff             101.364%
                                 scale_robust   T_eff             101.364%
                                 scale_power    T_eff             101.364%
                                 scale_quantile T_eff             101.364%
KNN               PARSEC         Base           T_eff              70.725%
                                 scale_standard T_eff              70.725%
                                 scale_robust   T_eff              72.042%
                                 scale_power    T_eff              70.725%
                                 scale_quantile T_eff              73.896%
linear_regression PARSEC         Base           T_eff              51.102%
                                 scale_standard T_eff              51.102%
                                 scale_robust   T_eff              51.102%
                                 scale_power    T_eff              50.012%
                                 scale_quantile T_eff              48.356%
mlp               PARSEC         Base           T_eff              70.754%
                                 scale_standard T_eff              53.058%
                                 scale_robust   T_eff              58.041%
                                 scale_power    T_eff              51.637%
                                 scale_quantile T_eff              62.835%
random_forest     PARSEC         Base           T_eff              76.433%
                                 scale_standard T_eff              77.143%
                                 scale_robust   T_eff              78.014%
                                 scale_power    T_eff              76.405%
                                 scale_quantile T_eff               77.49%
xgboost           PARSEC         Base           T_eff              44.048%
                                 scale_standard T_eff              44.048%
                                 scale_robust   T_eff              44.048%
                                 scale_power    T_eff              44.048%
                                 scale_quantile T_eff              59.856%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 1.308% / 90 : 2.547% / 95 : 4.363% / 99 : 26.219%
                                 scale_standard T_eff                75 : 1.308% / 90 : 2.525% / 95 : 4.379% / 99 : 25.964%
                                 scale_robust   T_eff                75 : 1.299% / 90 : 2.547% / 95 : 4.416% / 99 : 27.652%
                                 scale_power    T_eff                75 : 1.308% / 90 : 2.547% / 95 : 4.384% / 99 : 26.569%
                                 scale_quantile T_eff                75 : 1.294% / 90 : 2.547% / 95 : 4.384% / 99 : 27.353%
KNN               PARSEC         Base           T_eff                75 : 3.198% / 90 : 5.663% / 95 : 8.956% / 99 : 22.086%
                                 scale_standard T_eff                75 : 3.225% / 90 : 5.666% / 95 : 8.707% / 99 : 21.587%
                                 scale_robust   T_eff                  75 : 3.226% / 90 : 5.649% / 95 : 8.8% / 99 : 21.705%
                                 scale_power    T_eff                75 : 3.338% / 90 : 5.814% / 95 : 8.859% / 99 : 21.443%
                                 scale_quantile T_eff                75 : 3.205% / 90 : 5.699% / 95 : 8.654% / 99 : 21.261%
linear_regression PARSEC         Base           T_eff             75 : 29.026% / 90 : 37.978% / 95 : 42.759% / 99 : 47.634%
                                 scale_standard T_eff             75 : 29.026% / 90 : 37.978% / 95 : 42.759% / 99 : 47.634%
                                 scale_robust   T_eff             75 : 29.026% / 90 : 37.978% / 95 : 42.759% / 99 : 47.634%
                                 scale_power    T_eff             75 : 28.374% / 90 : 36.987% / 95 : 41.788% / 99 : 46.715%
                                 scale_quantile T_eff              75 : 26.701% / 90 : 34.903% / 95 : 39.431% / 99 : 44.37%
mlp               PARSEC         Base           T_eff              75 : 23.619% / 90 : 36.067% / 95 : 42.92% / 99 : 54.494%
                                 scale_standard T_eff              75 : 18.489% / 90 : 26.69% / 95 : 32.227% / 99 : 41.109%

### log_g parameter

In [4]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
KNN               PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
linear_regression PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
mlp               PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
random_forest     PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345
xgboost           PARSEC         Base           log_g             -0.384 - 5.345
                                 scale_standard log_g             -0.384 - 5.345
                                 scale_robust   log_g             -0.384 - 5.345
                                 scale_power    log_g             -0.384 - 5.345
                                 scale_quantile log_g             -0.384 - 5.345

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.7536570738013006
                                 scale_standard log_g              0.7539263112533031
                                 scale_robust   log_g              0.7531904474184777
                                 scale_power    log_g              0.7549410009802766
                                 scale_quantile log_g              0.7541598401658153
KNN               PARSEC         Base           log_g              0.7969225275315691
                                 scale_standard log_g              0.8081988023295883
                                 scale_robust   log_g              0.8013460836352126
                                 scale_power    log_g              0.8137589955569374
                                 scale_quantile log_g              0.8130338552874415
linear_regression PARSEC         Base           log_g              0.1740171909362369
                                 scale_standard log_g              0.1740171909362368
                                 scale_robust   log_g              0.1740171909362368
                                 scale_power    log_g              0.3070120017914916
                                 scale_quantile log_g             0.27447034001623405
mlp               PARSEC         Base           log_g              0.5075863573833721
                                 scale_standard log_g              0.6779198728794662
                                 scale_robust   log_g              0.6999176405398617
                                 scale_power    log_g              0.7250246824738618
                                 scale_quantile log_g              0.6418428033929072
random_forest     PARSEC         Base           log_g              0.8074266704690882
                                 scale_standard log_g              0.8078154931386199
                                 scale_robust   log_g              0.8073673493807803
                                 scale_power    log_g               0.807987705418437
                                 scale_quantile log_g              0.8082191093867832
xgboost           PARSEC         Base           log_g              0.7207144464742739
                                 scale_standard log_g              0.7207144464742739
                                 scale_robust   log_g              0.7207144464742739
                                 scale_power    log_g              0.7207144464742739
                                 scale_quantile log_g              0.7222571952540653

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               9.06%
                                 scale_standard log_g              9.055%
                                 scale_robust   log_g              9.069%
                                 scale_power    log_g              9.036%
                                 scale_quantile log_g              9.051%
KNN               PARSEC         Base           log_g              8.229%
                                 scale_standard log_g              7.995%
                                 scale_robust   log_g              8.138%
                                 scale_power    log_g              7.879%
                                 scale_quantile log_g              7.893%
linear_regression PARSEC         Base           log_g              16.59%
                                 scale_standard log_g              16.59%
                                 scale_robust   log_g              16.59%
                                 scale_power    log_g             15.196%
                                 scale_quantile log_g             15.549%
mlp               PARSEC         Base           log_g             12.822%
                                 scale_standard log_g              10.36%
                                 scale_robust   log_g             10.005%
                                 scale_power    log_g              9.572%
                                 scale_quantile log_g             10.977%
random_forest     PARSEC         Base           log_g              8.011%
                                 scale_standard log_g              8.002%
                                 scale_robust   log_g              8.012%
                                 scale_power    log_g              7.999%
                                 scale_quantile log_g              7.994%
xgboost           PARSEC         Base           log_g              9.647%
                                 scale_standard log_g              9.647%
                                 scale_robust   log_g              9.647%
                                 scale_power    log_g              9.647%
                                 scale_quantile log_g               9.62%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              2.629%
                                 scale_standard log_g              2.626%
                                 scale_robust   log_g              2.631%
                                 scale_power    log_g              2.624%
                                 scale_quantile log_g              2.626%
KNN               PARSEC         Base           log_g              2.944%
                                 scale_standard log_g              2.837%
                                 scale_robust   log_g              2.899%
                                 scale_power    log_g              2.764%
                                 scale_quantile log_g              2.784%
linear_regression PARSEC         Base           log_g             13.104%
                                 scale_standard log_g             13.104%
                                 scale_robust   log_g             13.104%
                                 scale_power    log_g             11.679%
                                 scale_quantile log_g             12.038%
mlp               PARSEC         Base           log_g              8.747%
                                 scale_standard log_g              6.107%
                                 scale_robust   log_g              5.698%
                                 scale_power    log_g              5.371%
                                 scale_quantile log_g              6.804%
random_forest     PARSEC         Base           log_g              2.553%
                                 scale_standard log_g              2.552%
                                 scale_robust   log_g              2.552%
                                 scale_power    log_g              2.551%
                                 scale_quantile log_g              2.551%
xgboost           PARSEC         Base           log_g              5.474%
                                 scale_standard log_g              5.474%
                                 scale_robust   log_g              5.474%
                                 scale_power    log_g              5.474%
                                 scale_quantile log_g               5.44%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.192%
                                 scale_standard log_g             0.192%
                                 scale_robust   log_g             0.192%
                                 scale_power    log_g             0.192%
                                 scale_quantile log_g             0.192%
KNN               PARSEC         Base           log_g              0.23%
                                 scale_standard log_g             0.244%
                                 scale_robust   log_g             0.237%
                                 scale_power    log_g             0.209%
                                 scale_quantile log_g             0.237%
linear_regression PARSEC         Base           log_g              8.82%
                                 scale_standard log_g              8.82%
                                 scale_robust   log_g              8.82%
                                 scale_power    log_g             7.197%
                                 scale_quantile log_g             8.791%
mlp               PARSEC         Base           log_g             4.531%
                                 scale_standard log_g             2.323%
                                 scale_robust   log_g             2.046%
                                 scale_power    log_g             1.827%
                                 scale_quantile log_g             3.135%
random_forest     PARSEC         Base           log_g             0.222%
                                 scale_standard log_g             0.223%
                                 scale_robust   log_g             0.221%
                                 scale_power    log_g             0.223%
                                 scale_quantile log_g             0.222%
xgboost           PARSEC         Base           log_g              1.87%
                                 scale_standard log_g              1.87%
                                 scale_robust   log_g              1.87%
                                 scale_power    log_g              1.87%
                                 scale_quantile log_g             1.826%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.8738266108931796
                                 scale_standard log_g              0.8739555494914786
                                 scale_robust   log_g               0.873587599040053
                                 scale_power    log_g              0.8744374556069411
                                 scale_quantile log_g              0.8740667394203638
KNN               PARSEC         Base           log_g              0.8935178759114629
                                 scale_standard log_g              0.8996181346528818
                                 scale_robust   log_g              0.8959292195126285
                                 scale_power    log_g               0.902638902162653
                                 scale_quantile log_g              0.9022672178111198
linear_regression PARSEC         Base           log_g             0.41715368143690107
                                 scale_standard log_g              0.4171536814369009
                                 scale_robust   log_g             0.41715368143690085
                                 scale_power    log_g              0.5540866388277222
                                 scale_quantile log_g               0.523899171392848
mlp               PARSEC         Base           log_g              0.7124610004519873
                                 scale_standard log_g              0.8233779831143158
                                 scale_robust   log_g              0.8367340353050561
                                 scale_power    log_g              0.8516718365794915
                                 scale_quantile log_g              0.8012040184996297
random_forest     PARSEC         Base           log_g              0.8998465625312148
                                 scale_standard log_g              0.9000435378254538
                                 scale_robust   log_g              0.8998165255092293
                                 scale_power    log_g              0.9001280336825566
                                 scale_quantile log_g              0.9002466206405032
xgboost           PARSEC         Base           log_g              0.8494127272684615
                                 scale_standard log_g              0.8494127272684615
                                 scale_robust   log_g              0.8494127272684615
                                 scale_power    log_g              0.8494127272684615
                                 scale_quantile log_g              0.8503306921291144

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             83.435%
                                 scale_standard log_g             83.261%
                                 scale_robust   log_g             83.435%
                                 scale_power    log_g             83.435%
                                 scale_quantile log_g             83.435%
KNN               PARSEC         Base           log_g             80.911%
                                 scale_standard log_g             80.911%
                                 scale_robust   log_g             80.911%
                                 scale_power    log_g             80.911%
                                 scale_quantile log_g             80.908%
linear_regression PARSEC         Base           log_g             58.561%
                                 scale_standard log_g             58.561%
                                 scale_robust   log_g             58.561%
                                 scale_power    log_g             48.812%
                                 scale_quantile log_g             54.104%
mlp               PARSEC         Base           log_g             67.966%
                                 scale_standard log_g             67.586%
                                 scale_robust   log_g             73.241%
                                 scale_power    log_g             76.875%
                                 scale_quantile log_g             65.953%
random_forest     PARSEC         Base           log_g             80.657%
                                 scale_standard log_g              81.48%
                                 scale_robust   log_g             81.346%
                                 scale_power    log_g             80.826%
                                 scale_quantile log_g             80.476%
xgboost           PARSEC         Base           log_g             76.063%
                                 scale_standard log_g             76.063%
                                 scale_robust   log_g             76.063%
                                 scale_power    log_g             76.063%
                                 scale_quantile log_g             75.823%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               75 : 1.008% / 90 : 3.887% / 95 : 15.628% / 99 : 50.742%
                                 scale_standard log_g               75 : 1.007% / 90 : 3.878% / 95 : 15.583% / 99 : 50.704%
                                 scale_robust   log_g               75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.777%
                                 scale_power    log_g                75 : 1.007% / 90 : 3.887% / 95 : 15.635% / 99 : 50.55%
                                 scale_quantile log_g                75 : 1.007% / 90 : 3.884% / 95 : 15.59% / 99 : 50.555%
KNN               PARSEC         Base           log_g               75 : 1.547% / 90 : 7.788% / 95 : 18.059% / 99 : 39.135%
                                 scale_standard log_g                  75 : 1.48% / 90 : 7.38% / 95 : 17.05% / 99 : 38.297%
                                 scale_robust   log_g               75 : 1.519% / 90 : 7.593% / 95 : 17.645% / 99 : 38.791%
                                 scale_power    log_g               75 : 1.421% / 90 : 7.136% / 95 : 16.486% / 99 : 37.924%
                                 scale_quantile log_g               75 : 1.473% / 90 : 7.115% / 95 : 16.467% / 99 : 37.892%
linear_regression PARSEC         Base           log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%
                                 scale_standard log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%
                                 scale_robust   log_g             75 : 19.745% / 90 : 28.314% / 95 : 32.875% / 99 : 42.085%
                                 scale_power    log_g              75 : 19.212% / 90 : 27.035% / 95 : 30.81% / 99 : 36.535%
                                 scale_quantile log_g               75 : 19.87% / 90 : 26.84% / 95 : 29.953% / 99 : 38.288%
mlp               PARSEC         Base           log_g             75 : 12.796% / 90 : 24.748% / 95 : 28.927% / 99 : 38.055%
                                 scale_standard log_g              75 : 7.896% / 90 : 18.012% / 95 : 24.299% / 99 : 37.884%
                                 scale_robust   log_g               75 : 7.261% / 90 : 16.81% / 95 : 23.082% / 99 : 37.817%

Results for the label category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345
KNN               PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345
linear_regression PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345
mlp               PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345
random_forest     PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345
xgboost           PARSEC         Base           log_g             3.233 - 5.345
                                 scale_standard log_g             3.233 - 5.345
                                 scale_robust   log_g             3.233 - 5.345
                                 scale_power    log_g             3.233 - 5.345
                                 scale_quantile log_g             3.233 - 5.345

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.22366302531475957
                                 scale_standard log_g             -0.19730786992476612
                                 scale_robust   log_g              -0.2145731255988126
                                 scale_power    log_g             -0.20556160478270935
                                 scale_quantile log_g             -0.20397251296193808
KNN               PARSEC         Base           log_g              -0.5685510473572672
                                 scale_standard log_g             -0.12578341719886565
                                 scale_robust   log_g             -0.40183002519091326
                                 scale_power    log_g              0.07188941852646846
                                 scale_quantile log_g              0.03934139387015889
linear_regression PARSEC         Base           log_g              -1.2252488306693854
                                 scale_standard log_g              -1.2252488306693432
                                 scale_robust   log_g              -1.2252488306693623
                                 scale_power    log_g               -4.175206049409114
                                 scale_quantile log_g              -3.6270418073665764
mlp               PARSEC         Base           log_g               -4.371543636897526
                                 scale_standard log_g              -1.5021144633208494
                                 scale_robust   log_g              -0.7942321526512297
                                 scale_power    log_g              -0.6751636757494193
                                 scale_quantile log_g              -2.5401030020977045
random_forest     PARSEC         Base           log_g              0.17211468827279353
                                 scale_standard log_g              0.18131509921027356
                                 scale_robust   log_g              0.17048734756969952
                                 scale_power    log_g              0.17137724293009893
                                 scale_quantile log_g              0.17796533680786653
xgboost           PARSEC         Base           log_g              -1.0124875678765508
                                 scale_standard log_g              -1.0124875678765508
                                 scale_robust   log_g              -1.0124875678765508
                                 scale_power    log_g              -1.0124875678765508
                                 scale_quantile log_g              -0.9907199861069069

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             18.015%
                                 scale_standard log_g             17.817%
                                 scale_robust   log_g             17.947%
                                 scale_power    log_g             17.881%
                                 scale_quantile log_g             17.868%
KNN               PARSEC         Base           log_g             20.991%
                                 scale_standard log_g             17.633%
                                 scale_robust   log_g             19.773%
                                 scale_power    log_g             15.919%
                                 scale_quantile log_g             16.184%
linear_regression PARSEC         Base           log_g             69.776%
                                 scale_standard log_g             69.776%
                                 scale_robust   log_g             69.776%
                                 scale_power    log_g             62.141%
                                 scale_quantile log_g               60.3%
mlp               PARSEC         Base           log_g             50.355%
                                 scale_standard log_g             28.548%
                                 scale_robust   log_g             24.069%
                                 scale_power    log_g             22.727%
                                 scale_quantile log_g             35.538%
random_forest     PARSEC         Base           log_g             14.962%
                                 scale_standard log_g              14.88%
                                 scale_robust   log_g             14.975%
                                 scale_power    log_g             14.967%
                                 scale_quantile log_g              14.91%
xgboost           PARSEC         Base           log_g              26.21%
                                 scale_standard log_g              26.21%
                                 scale_robust   log_g              26.21%
                                 scale_power    log_g              26.21%
                                 scale_quantile log_g             26.078%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              3.196%
                                 scale_standard log_g              3.151%
                                 scale_robust   log_g              3.179%
                                 scale_power    log_g              3.176%
                                 scale_quantile log_g              3.161%
KNN               PARSEC         Base           log_g              6.373%
                                 scale_standard log_g              5.024%
                                 scale_robust   log_g               5.83%
                                 scale_power    log_g              4.068%
                                 scale_quantile log_g              4.438%
linear_regression PARSEC         Base           log_g             65.529%
                                 scale_standard log_g             65.529%
                                 scale_robust   log_g             65.529%
                                 scale_power    log_g             57.712%
                                 scale_quantile log_g             56.272%
mlp               PARSEC         Base           log_g             36.886%
                                 scale_standard log_g             14.461%
                                 scale_robust   log_g             11.916%
                                 scale_power    log_g              10.68%
                                 scale_quantile log_g             20.581%
random_forest     PARSEC         Base           log_g              3.327%
                                 scale_standard log_g              3.314%
                                 scale_robust   log_g              3.323%
                                 scale_power    log_g              3.327%
                                 scale_quantile log_g              3.321%
xgboost           PARSEC         Base           log_g             15.113%
                                 scale_standard log_g             15.113%
                                 scale_robust   log_g             15.113%
                                 scale_power    log_g             15.113%
                                 scale_quantile log_g              15.02%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.036%
                                 scale_standard log_g              0.038%
                                 scale_robust   log_g              0.036%
                                 scale_power    log_g              0.036%
                                 scale_quantile log_g              0.044%
KNN               PARSEC         Base           log_g              0.331%
                                 scale_standard log_g              0.407%
                                 scale_robust   log_g               0.36%
                                 scale_power    log_g              0.246%
                                 scale_quantile log_g               0.36%
linear_regression PARSEC         Base           log_g             62.445%
                                 scale_standard log_g             62.445%
                                 scale_robust   log_g             62.445%
                                 scale_power    log_g             59.973%
                                 scale_quantile log_g             60.711%
mlp               PARSEC         Base           log_g             27.406%
                                 scale_standard log_g              2.686%
                                 scale_robust   log_g              3.443%
                                 scale_power    log_g               2.82%
                                 scale_quantile log_g              4.903%
random_forest     PARSEC         Base           log_g              0.046%
                                 scale_standard log_g              0.047%
                                 scale_robust   log_g              0.046%
                                 scale_power    log_g              0.046%
                                 scale_quantile log_g               0.05%
xgboost           PARSEC         Base           log_g              4.307%
                                 scale_standard log_g              4.307%
                                 scale_robust   log_g              4.307%
                                 scale_power    log_g              4.307%
                                 scale_quantile log_g              4.192%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.7053404051445747
                                 scale_standard log_g              0.7081715169736257
                                 scale_robust   log_g              0.7064456433814592
                                 scale_power    log_g              0.7077035551914663
                                 scale_quantile log_g              0.7074431985113896
KNN               PARSEC         Base           log_g               0.726834275461127
                                 scale_standard log_g              0.7414746317564871
                                 scale_robust   log_g              0.7318558385943664
                                 scale_power    log_g              0.7531650493996055
                                 scale_quantile log_g              0.7456154000428418
linear_regression PARSEC         Base           log_g             0.33703567351467884
                                 scale_standard log_g             0.33703567351468466
                                 scale_robust   log_g             0.33703567351468366
                                 scale_power    log_g              0.7966359242548076
                                 scale_quantile log_g              0.6855071267070832
mlp               PARSEC         Base           log_g              0.7792055306173461
                                 scale_standard log_g              0.7148746483979497
                                 scale_robust   log_g              0.7549808466533131
                                 scale_power    log_g              0.7531372733508812
                                 scale_quantile log_g              0.7208264748825957
random_forest     PARSEC         Base           log_g              0.7759789538352955
                                 scale_standard log_g                0.77756232439253
                                 scale_robust   log_g              0.7759872312386642
                                 scale_power    log_g              0.7755834972688167
                                 scale_quantile log_g              0.7771055642531638
xgboost           PARSEC         Base           log_g              0.8095818883794095
                                 scale_standard log_g              0.8095818883794095
                                 scale_robust   log_g              0.8095818883794095
                                 scale_power    log_g              0.8095818883794095
                                 scale_quantile log_g              0.8124836489324698

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             226.326%
                                 scale_standard log_g             222.443%
                                 scale_robust   log_g             226.326%
                                 scale_power    log_g             226.326%
                                 scale_quantile log_g             226.326%
KNN               PARSEC         Base           log_g             213.684%
                                 scale_standard log_g             213.684%
                                 scale_robust   log_g             213.684%
                                 scale_power    log_g             213.684%
                                 scale_quantile log_g             213.684%
linear_regression PARSEC         Base           log_g             158.852%
                                 scale_standard log_g             158.852%
                                 scale_robust   log_g             158.852%
                                 scale_power    log_g             109.567%
                                 scale_quantile log_g             117.069%
mlp               PARSEC         Base           log_g             128.362%
                                 scale_standard log_g             131.417%
                                 scale_robust   log_g             125.889%
                                 scale_power    log_g             134.374%
                                 scale_quantile log_g             133.301%
random_forest     PARSEC         Base           log_g              200.11%
                                 scale_standard log_g             198.388%
                                 scale_robust   log_g              204.88%
                                 scale_power    log_g             205.661%
                                 scale_quantile log_g             191.424%
xgboost           PARSEC         Base           log_g             169.765%
                                 scale_standard log_g             169.765%
                                 scale_robust   log_g             169.765%
                                 scale_power    log_g             169.765%
                                 scale_quantile log_g             192.836%

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                   75 : 0.284% / 90 : 1.231% / 95 : 3.03% / 99 : 93.205%
                                 scale_standard log_g                    75 : 0.284% / 90 : 1.231% / 95 : 3.03% / 99 : 93.04%
                                 scale_robust   log_g                   75 : 0.284% / 90 : 1.231% / 95 : 3.03% / 99 : 93.143%
                                 scale_power    log_g                  75 : 0.284% / 90 : 1.231% / 95 : 3.078% / 99 : 93.143%
                                 scale_quantile log_g                   75 : 0.284% / 90 : 1.231% / 95 : 3.03% / 99 : 93.143%
KNN               PARSEC         Base           log_g               75 : 1.297% / 90 : 10.975% / 95 : 40.152% / 99 : 105.519%
                                 scale_standard log_g                  75 : 1.458% / 90 : 4.28% / 95 : 37.261% / 99 : 92.993%
                                 scale_robust   log_g                75 : 1.297% / 90 : 5.952% / 95 : 38.456% / 99 : 100.125%
                                 scale_power    log_g                 75 : 0.824% / 90 : 2.888% / 95 : 36.203% / 99 : 87.143%
                                 scale_quantile log_g                 75 : 1.411% / 90 : 4.318% / 95 : 36.465% / 99 : 86.954%
linear_regression PARSEC         Base           log_g             75 : 82.566% / 90 : 96.036% / 95 : 107.757% / 99 : 132.505%
                                 scale_standard log_g             75 : 82.566% / 90 : 96.036% / 95 : 107.757% / 99 : 132.505%
                                 scale_robust   log_g             75 : 82.566% / 90 : 96.036% / 95 : 107.757% / 99 : 132.505%
                                 scale_power    log_g               75 : 75.573% / 90 : 85.619% / 95 : 89.676% / 99 : 95.357%
                                 scale_quantile log_g                75 : 71.49% / 90 : 79.876% / 95 : 84.416% / 99 : 93.735%
mlp               PARSEC         Base           log_g              75 : 71.715% / 90 : 79.992% / 95 : 87.624% / 99 : 107.038%
                                 scale_standard log_g               75 : 7.678% / 90 : 54.627% / 95 : 71.775% / 99 : 100.395%
                                 scale_robust   log_g                  75 : 7.787% / 90 : 38.277% / 95 : 62.12% / 99 : 98.38%

Results for the label category with a value of 2.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299
KNN               PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299
linear_regression PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299
mlp               PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299
random_forest     PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299
xgboost           PARSEC         Base           log_g             0.638 - 4.299
                                 scale_standard log_g             0.638 - 4.299
                                 scale_robust   log_g             0.638 - 4.299
                                 scale_power    log_g             0.638 - 4.299
                                 scale_quantile log_g             0.638 - 4.299

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.20108117139632975
                                 scale_standard log_g             0.20188562500755614
                                 scale_robust   log_g             0.19817400174858324
                                 scale_power    log_g             0.21063946678256884
                                 scale_quantile log_g              0.2022893510152015
KNN               PARSEC         Base           log_g               0.551332428608432
                                 scale_standard log_g              0.5498139783506506
                                 scale_robust   log_g              0.5507478438161073
                                 scale_power    log_g               0.565558984894846
                                 scale_quantile log_g              0.5390409677967032
linear_regression PARSEC         Base           log_g             0.20729145625045087
                                 scale_standard log_g              0.2072914562504592
                                 scale_robust   log_g              0.2072914562504582
                                 scale_power    log_g              0.2814406255147278
                                 scale_quantile log_g             0.13016338408501127
mlp               PARSEC         Base           log_g             0.42018335004606344
                                 scale_standard log_g             0.15273707143059811
                                 scale_robust   log_g             0.22694013904331445
                                 scale_power    log_g              0.2872169691172122
                                 scale_quantile log_g              0.3744179494549351
random_forest     PARSEC         Base           log_g              0.4626143591760997
                                 scale_standard log_g              0.4629207374972585
                                 scale_robust   log_g              0.4624974507669598
                                 scale_power    log_g             0.46949483029736805
                                 scale_quantile log_g             0.46443176397499897
xgboost           PARSEC         Base           log_g             0.35000992847659496
                                 scale_standard log_g             0.35000992847659496
                                 scale_robust   log_g             0.35000992847659496
                                 scale_power    log_g             0.35000992847659496
                                 scale_quantile log_g             0.34277234276374957

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             20.653%
                                 scale_standard log_g             20.639%
                                 scale_robust   log_g             20.695%
                                 scale_power    log_g             20.537%
                                 scale_quantile log_g             20.638%
KNN               PARSEC         Base           log_g             16.174%
                                 scale_standard log_g             16.205%
                                 scale_robust   log_g             16.184%
                                 scale_power    log_g             16.262%
                                 scale_quantile log_g             16.313%
linear_regression PARSEC         Base           log_g             21.985%
                                 scale_standard log_g             21.985%
                                 scale_robust   log_g             21.985%
                                 scale_power    log_g             23.264%
                                 scale_quantile log_g             24.552%
mlp               PARSEC         Base           log_g             25.921%
                                 scale_standard log_g             24.035%
                                 scale_robust   log_g             23.283%
                                 scale_power    log_g             23.023%
                                 scale_quantile log_g             24.991%
random_forest     PARSEC         Base           log_g             17.271%
                                 scale_standard log_g             17.262%
                                 scale_robust   log_g             17.272%
                                 scale_power    log_g              17.19%
                                 scale_quantile log_g             17.239%
xgboost           PARSEC         Base           log_g              22.73%
                                 scale_standard log_g              22.73%
                                 scale_robust   log_g              22.73%
                                 scale_power    log_g              22.73%
                                 scale_quantile log_g              22.67%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              8.276%
                                 scale_standard log_g              8.267%
                                 scale_robust   log_g              8.296%
                                 scale_power    log_g              8.236%
                                 scale_quantile log_g              8.275%
KNN               PARSEC         Base           log_g              8.391%
                                 scale_standard log_g              8.413%
                                 scale_robust   log_g              8.391%
                                 scale_power    log_g              8.562%
                                 scale_quantile log_g              8.465%
linear_regression PARSEC         Base           log_g             18.138%
                                 scale_standard log_g             18.138%
                                 scale_robust   log_g             18.138%
                                 scale_power    log_g             20.201%
                                 scale_quantile log_g             21.649%
mlp               PARSEC         Base           log_g             22.119%
                                 scale_standard log_g              19.14%
                                 scale_robust   log_g             18.343%
                                 scale_power    log_g             17.927%
                                 scale_quantile log_g             20.553%
random_forest     PARSEC         Base           log_g              7.904%
                                 scale_standard log_g              7.893%
                                 scale_robust   log_g              7.897%
                                 scale_power    log_g              7.877%
                                 scale_quantile log_g              7.896%
xgboost           PARSEC         Base           log_g             18.338%
                                 scale_standard log_g             18.338%
                                 scale_robust   log_g             18.338%
                                 scale_power    log_g             18.338%
                                 scale_quantile log_g              18.28%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              1.639%
                                 scale_standard log_g              1.639%
                                 scale_robust   log_g              1.639%
                                 scale_power    log_g              1.639%
                                 scale_quantile log_g              1.639%
KNN               PARSEC         Base           log_g              2.502%
                                 scale_standard log_g              2.524%
                                 scale_robust   log_g              2.524%
                                 scale_power    log_g              2.721%
                                 scale_quantile log_g              2.573%
linear_regression PARSEC         Base           log_g             16.731%
                                 scale_standard log_g             16.731%
                                 scale_robust   log_g             16.731%
                                 scale_power    log_g             20.126%
                                 scale_quantile log_g             22.191%
mlp               PARSEC         Base           log_g             22.733%
                                 scale_standard log_g             15.909%
                                 scale_robust   log_g             15.043%
                                 scale_power    log_g             13.909%
                                 scale_quantile log_g             19.098%
random_forest     PARSEC         Base           log_g              1.859%
                                 scale_standard log_g              1.851%
                                 scale_robust   log_g              1.846%
                                 scale_power    log_g               1.86%
                                 scale_quantile log_g              1.856%
xgboost           PARSEC         Base           log_g             15.978%
                                 scale_standard log_g             15.978%
                                 scale_robust   log_g             15.978%
                                 scale_power    log_g             15.978%
                                 scale_quantile log_g             15.912%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.6543935473449031
                                 scale_standard log_g              0.654731564664574
                                 scale_robust   log_g             0.6531520090048356
                                 scale_power    log_g             0.6574083253353311
                                 scale_quantile log_g             0.6547880100556327
KNN               PARSEC         Base           log_g             0.7693849003643232
                                 scale_standard log_g             0.7687380780954205
                                 scale_robust   log_g             0.7692095112378741
                                 scale_power    log_g             0.7758256932291288
                                 scale_quantile log_g             0.7641256296544156
linear_regression PARSEC         Base           log_g              0.493104879406129
                                 scale_standard log_g             0.4931048794061357
                                 scale_robust   log_g             0.4931048794061351
                                 scale_power    log_g             0.6149835450492734
                                 scale_quantile log_g             0.4236216845709691
mlp               PARSEC         Base           log_g             0.6521638888149588
                                 scale_standard log_g             0.5374215912902183
                                 scale_robust   log_g             0.5785004562328788
                                 scale_power    log_g             0.5962598648492033
                                 scale_quantile log_g             0.6193195809203158
random_forest     PARSEC         Base           log_g              0.737427211287738
                                 scale_standard log_g             0.7375860413277311
                                 scale_robust   log_g             0.7374043837125458
                                 scale_power    log_g             0.7399763330504997
                                 scale_quantile log_g             0.7382704203912901
xgboost           PARSEC         Base           log_g             0.6120898372154866
                                 scale_standard log_g             0.6120898372154866
                                 scale_robust   log_g             0.6120898372154866
                                 scale_power    log_g             0.6120898372154866
                                 scale_quantile log_g             0.6065642350105106

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             113.931%
                                 scale_standard log_g             113.931%
                                 scale_robust   log_g             113.931%
                                 scale_power    log_g             113.931%
                                 scale_quantile log_g             113.931%
KNN               PARSEC         Base           log_g             108.358%
                                 scale_standard log_g             108.358%
                                 scale_robust   log_g             108.358%
                                 scale_power    log_g             108.358%
                                 scale_quantile log_g             106.501%
linear_regression PARSEC         Base           log_g              78.896%
                                 scale_standard log_g              78.896%
                                 scale_robust   log_g              78.896%
                                 scale_power    log_g               55.68%
                                 scale_quantile log_g              54.726%
mlp               PARSEC         Base           log_g              64.876%
                                 scale_standard log_g              71.966%
                                 scale_robust   log_g              71.916%
                                 scale_power    log_g               70.66%
                                 scale_quantile log_g              70.728%
random_forest     PARSEC         Base           log_g             100.601%
                                 scale_standard log_g              99.452%
                                 scale_robust   log_g             100.307%
                                 scale_power    log_g              98.537%
                                 scale_quantile log_g              97.598%
xgboost           PARSEC         Base           log_g              73.628%
                                 scale_standard log_g              73.628%
                                 scale_robust   log_g              73.628%
                                 scale_power    log_g              73.628%
                                 scale_quantile log_g              73.365%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 4.269% / 90 : 27.787% / 95 : 49.7% / 99 : 92.293%
                                 scale_standard log_g               75 : 4.269% / 90 : 27.715% / 95 : 49.733% / 99 : 92.21%
                                 scale_robust   log_g               75 : 4.27% / 90 : 27.848% / 95 : 50.366% / 99 : 92.295%
                                 scale_power    log_g              75 : 4.261% / 90 : 27.604% / 95 : 48.301% / 99 : 92.044%
                                 scale_quantile log_g                75 : 4.27% / 90 : 27.787% / 95 : 49.625% / 99 : 92.27%
KNN               PARSEC         Base           log_g              75 : 7.217% / 90 : 29.746% / 95 : 38.665% / 99 : 62.036%
                                 scale_standard log_g               75 : 7.187% / 90 : 29.764% / 95 : 38.747% / 99 : 62.41%
                                 scale_robust   log_g               75 : 7.136% / 90 : 29.636% / 95 : 38.701% / 99 : 62.41%
                                 scale_power    log_g              75 : 7.523% / 90 : 29.678% / 95 : 38.376% / 99 : 63.208%
                                 scale_quantile log_g              75 : 7.218% / 90 : 29.644% / 95 : 38.636% / 99 : 63.801%
linear_regression PARSEC         Base           log_g              75 : 25.664% / 90 : 33.884% / 95 : 40.36% / 99 : 57.319%
                                 scale_standard log_g              75 : 25.664% / 90 : 33.884% / 95 : 40.36% / 99 : 57.319%
                                 scale_robust   log_g              75 : 25.664% / 90 : 33.884% / 95 : 40.36% / 99 : 57.319%
                                 scale_power    log_g              75 : 28.83% / 90 : 35.411% / 95 : 39.592% / 99 : 45.709%
                                 scale_quantile log_g              75 : 30.612% / 90 : 36.711% / 95 : 39.96% / 99 : 45.199%
mlp               PARSEC         Base           log_g               75 : 32.0% / 90 : 38.802% / 95 : 44.211% / 99 : 56.061%
                                 scale_standard log_g              75 : 30.266% / 90 : 38.763% / 95 : 44.468% / 99 : 59.25%
                                 scale_robust   log_g               75 : 29.697% / 90 : 37.125% / 95 : 43.7% / 99 : 58.431%

Results for the label category with a value of 3.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823
KNN               PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823
linear_regression PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823
mlp               PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823
random_forest     PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823
xgboost           PARSEC         Base           log_g             -0.384 - 3.823
                                 scale_standard log_g             -0.384 - 3.823
                                 scale_robust   log_g             -0.384 - 3.823
                                 scale_power    log_g             -0.384 - 3.823
                                 scale_quantile log_g             -0.384 - 3.823

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              -0.4342441850216521
                                 scale_standard log_g              -0.4372540042243023
                                 scale_robust   log_g              -0.4372041368032258
                                 scale_power    log_g             -0.43137194149452296
                                 scale_quantile log_g              -0.4337623278582614
KNN               PARSEC         Base           log_g             -0.09689368389630881
                                 scale_standard log_g             -0.09782846686966074
                                 scale_robust   log_g             -0.09708551441964519
                                 scale_power    log_g             -0.09603196405874481
                                 scale_quantile log_g             -0.09111889568070564
linear_regression PARSEC         Base           log_g              0.16872633450213492
                                 scale_standard log_g              0.16872633450214092
                                 scale_robust   log_g              0.16872633450213936
                                 scale_power    log_g              0.07348496986835296
                                 scale_quantile log_g             -0.06776659170785715
mlp               PARSEC         Base           log_g              0.20179797271613364
                                 scale_standard log_g             -0.03089874552347993
                                 scale_robust   log_g             -0.02092744844991845
                                 scale_power    log_g              0.05867590965088465
                                 scale_quantile log_g              0.08304240929782647
random_forest     PARSEC         Base           log_g             -0.17211974773342287
                                 scale_standard log_g             -0.16995352824917687
                                 scale_robust   log_g             -0.17132950270818137
                                 scale_power    log_g              -0.1698801481182357
                                 scale_quantile log_g              -0.1665173081099136
xgboost           PARSEC         Base           log_g              0.06308841876492932
                                 scale_standard log_g              0.06308841876492932
                                 scale_robust   log_g              0.06308841876492932
                                 scale_power    log_g              0.06308841876492932
                                 scale_quantile log_g              0.06389146449701089

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             23.311%
                                 scale_standard log_g             23.336%
                                 scale_robust   log_g             23.335%
                                 scale_power    log_g             23.285%
                                 scale_quantile log_g             23.312%
KNN               PARSEC         Base           log_g             20.726%
                                 scale_standard log_g             20.731%
                                 scale_robust   log_g             20.724%
                                 scale_power    log_g              20.68%
                                 scale_quantile log_g             20.656%
linear_regression PARSEC         Base           log_g             24.666%
                                 scale_standard log_g             24.666%
                                 scale_robust   log_g             24.666%
                                 scale_power    log_g             23.122%
                                 scale_quantile log_g             23.428%
mlp               PARSEC         Base           log_g             20.888%
                                 scale_standard log_g             21.734%
                                 scale_robust   log_g             22.208%
                                 scale_power    log_g             20.999%
                                 scale_quantile log_g             20.833%
random_forest     PARSEC         Base           log_g             21.202%
                                 scale_standard log_g             21.182%
                                 scale_robust   log_g             21.194%
                                 scale_power    log_g             21.174%
                                 scale_quantile log_g             21.155%
xgboost           PARSEC         Base           log_g             21.008%
                                 scale_standard log_g             21.008%
                                 scale_robust   log_g             21.008%
                                 scale_power    log_g             21.008%
                                 scale_quantile log_g             20.986%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             11.188%
                                 scale_standard log_g             11.197%
                                 scale_robust   log_g             11.198%
                                 scale_power    log_g             11.182%
                                 scale_quantile log_g             11.187%
KNN               PARSEC         Base           log_g             10.986%
                                 scale_standard log_g             10.988%
                                 scale_robust   log_g             10.983%
                                 scale_power    log_g              10.97%
                                 scale_quantile log_g              10.96%
linear_regression PARSEC         Base           log_g               19.6%
                                 scale_standard log_g               19.6%
                                 scale_robust   log_g               19.6%
                                 scale_power    log_g             17.536%
                                 scale_quantile log_g             17.344%
mlp               PARSEC         Base           log_g             15.059%
                                 scale_standard log_g              15.18%
                                 scale_robust   log_g             15.066%
                                 scale_power    log_g             14.326%
                                 scale_quantile log_g             14.622%
random_forest     PARSEC         Base           log_g             10.722%
                                 scale_standard log_g             10.717%
                                 scale_robust   log_g             10.717%
                                 scale_power    log_g             10.719%
                                 scale_quantile log_g             10.712%
xgboost           PARSEC         Base           log_g             14.172%
                                 scale_standard log_g             14.172%
                                 scale_robust   log_g             14.172%
                                 scale_power    log_g             14.172%
                                 scale_quantile log_g             14.114%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              1.573%
                                 scale_standard log_g              1.573%
                                 scale_robust   log_g              1.573%
                                 scale_power    log_g              1.573%
                                 scale_quantile log_g              1.573%
KNN               PARSEC         Base           log_g              2.603%
                                 scale_standard log_g               2.61%
                                 scale_robust   log_g              2.605%
                                 scale_power    log_g              2.591%
                                 scale_quantile log_g              2.581%
linear_regression PARSEC         Base           log_g             15.412%
                                 scale_standard log_g             15.412%
                                 scale_robust   log_g             15.412%
                                 scale_power    log_g              11.73%
                                 scale_quantile log_g             10.508%
mlp               PARSEC         Base           log_g               9.13%
                                 scale_standard log_g             10.001%
                                 scale_robust   log_g              9.191%
                                 scale_power    log_g              8.648%
                                 scale_quantile log_g              9.612%
random_forest     PARSEC         Base           log_g               1.84%
                                 scale_standard log_g              1.839%
                                 scale_robust   log_g              1.835%
                                 scale_power    log_g              1.832%
                                 scale_quantile log_g              1.837%
xgboost           PARSEC         Base           log_g               8.56%
                                 scale_standard log_g               8.56%
                                 scale_robust   log_g               8.56%
                                 scale_power    log_g               8.56%
                                 scale_quantile log_g              8.457%

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                0.240075575575364
                                 scale_standard log_g               0.2387522773867078
                                 scale_robust   log_g              0.23906771514112982
                                 scale_power    log_g              0.24032476615948076
                                 scale_quantile log_g              0.24001275436501512
KNN               PARSEC         Base           log_g              0.30429608142710995
                                 scale_standard log_g               0.3028794355516005
                                 scale_robust   log_g               0.3041444015820934
                                 scale_power    log_g                 0.30290862375281
                                 scale_quantile log_g               0.3072740290826164
linear_regression PARSEC         Base           log_g              0.41099301685375894
                                 scale_standard log_g              0.41099301685376627
                                 scale_robust   log_g              0.41099301685376416
                                 scale_power    log_g               0.2719241101052986
                                 scale_quantile log_g             -0.05831255288278738
mlp               PARSEC         Base           log_g              0.45746960129678993
                                 scale_standard log_g              0.20165562118200242
                                 scale_robust   log_g               0.2119230917669726
                                 scale_power    log_g               0.2789396723209431
                                 scale_quantile log_g              0.31479592230393755
random_forest     PARSEC         Base           log_g              0.30681622944559384
                                 scale_standard log_g               0.3074731697827142
                                 scale_robust   log_g              0.30721927246214564
                                 scale_power    log_g              0.30694538682614547
                                 scale_quantile log_g              0.30874058139967386
xgboost           PARSEC         Base           log_g              0.29917511289779664
                                 scale_standard log_g              0.29917511289779664
                                 scale_robust   log_g              0.29917511289779664
                                 scale_power    log_g              0.29917511289779664
                                 scale_quantile log_g               0.3011454731522732

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             113.382%
                                 scale_standard log_g             113.382%
                                 scale_robust   log_g             113.382%
                                 scale_power    log_g             113.382%
                                 scale_quantile log_g             113.382%
KNN               PARSEC         Base           log_g             110.183%
                                 scale_standard log_g             110.183%
                                 scale_robust   log_g             110.183%
                                 scale_power    log_g             110.183%
                                 scale_quantile log_g             110.178%
linear_regression PARSEC         Base           log_g              67.923%
                                 scale_standard log_g              67.923%
                                 scale_robust   log_g              67.923%
                                 scale_power    log_g              66.471%
                                 scale_quantile log_g              73.677%
mlp               PARSEC         Base           log_g              92.555%
                                 scale_standard log_g              92.037%
                                 scale_robust   log_g              99.738%
                                 scale_power    log_g             104.687%
                                 scale_quantile log_g              89.814%
random_forest     PARSEC         Base           log_g             109.838%
                                 scale_standard log_g             110.958%
                                 scale_robust   log_g             110.776%
                                 scale_power    log_g             110.067%
                                 scale_quantile log_g             109.591%
xgboost           PARSEC         Base           log_g              103.58%
                                 scale_standard log_g              103.58%
                                 scale_robust   log_g              103.58%
                                 scale_power    log_g              103.58%
                                 scale_quantile log_g             103.254%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             75 : 10.002% / 90 : 42.887% / 95 : 60.114% / 99 : 91.053%
                                 scale_standard log_g              75 : 9.983% / 90 : 42.976% / 95 : 60.257% / 99 : 91.135%
                                 scale_robust   log_g              75 : 9.988% / 90 : 42.991% / 95 : 60.192% / 99 : 91.282%
                                 scale_power    log_g             75 : 10.008% / 90 : 42.786% / 95 : 60.019% / 99 : 90.994%
                                 scale_quantile log_g              75 : 9.986% / 90 : 42.976% / 95 : 60.096% / 99 : 91.053%
KNN               PARSEC         Base           log_g              75 : 14.276% / 90 : 36.406% / 95 : 49.542% / 99 : 87.82%
                                 scale_standard log_g             75 : 14.295% / 90 : 36.415% / 95 : 49.433% / 99 : 87.461%
                                 scale_robust   log_g               75 : 14.3% / 90 : 36.328% / 95 : 49.447% / 99 : 87.427%
                                 scale_power    log_g             75 : 14.277% / 90 : 36.106% / 95 : 49.371% / 99 : 87.375%
                                 scale_quantile log_g              75 : 14.22% / 90 : 36.268% / 95 : 49.218% / 99 : 87.283%
linear_regression PARSEC         Base           log_g              75 : 29.188% / 90 : 42.399% / 95 : 51.126% / 99 : 58.04%
                                 scale_standard log_g              75 : 29.188% / 90 : 42.399% / 95 : 51.126% / 99 : 58.04%
                                 scale_robust   log_g              75 : 29.188% / 90 : 42.399% / 95 : 51.126% / 99 : 58.04%
                                 scale_power    log_g              75 : 26.194% / 90 : 41.69% / 95 : 50.108% / 99 : 58.325%
                                 scale_quantile log_g             75 : 26.265% / 90 : 42.579% / 95 : 50.519% / 99 : 62.129%
mlp               PARSEC         Base           log_g              75 : 20.33% / 90 : 38.809% / 95 : 48.088% / 99 : 59.235%
                                 scale_standard log_g             75 : 21.625% / 90 : 37.529% / 95 : 48.455% / 99 : 68.459%

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978
KNN               PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978
linear_regression PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978
mlp               PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978
random_forest     PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978
xgboost           PARSEC         Base           log_g             -0.102 - 2.978
                                 scale_standard log_g             -0.102 - 2.978
                                 scale_robust   log_g             -0.102 - 2.978
                                 scale_power    log_g             -0.102 - 2.978
                                 scale_quantile log_g             -0.102 - 2.978

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.8996188259668024
                                 scale_standard log_g               0.8981436482040694
                                 scale_robust   log_g               0.8981957195816977
                                 scale_power    log_g               0.8988584958876358
                                 scale_quantile log_g               0.8999940996846196
KNN               PARSEC         Base           log_g               0.8882757130576726
                                 scale_standard log_g               0.8883561017225977
                                 scale_robust   log_g               0.8888314051581148
                                 scale_power    log_g               0.8899795114959481
                                 scale_quantile log_g                0.888832861169139
linear_regression PARSEC         Base           log_g              0.41809683900763883
                                 scale_standard log_g              0.41809683900766137
                                 scale_robust   log_g              0.41809683900765826
                                 scale_power    log_g               0.4560171589342089
                                 scale_quantile log_g             0.023781636036321663
mlp               PARSEC         Base           log_g               0.7089460485360655
                                 scale_standard log_g               0.5906429823096451
                                 scale_robust   log_g               0.6343232636173806
                                 scale_power    log_g               0.6790950303066797
                                 scale_quantile log_g               0.5511340006613421
random_forest     PARSEC         Base           log_g               0.9145444334060797
                                 scale_standard log_g               0.9134122881562983
                                 scale_robust   log_g               0.9131736786892325
                                 scale_power    log_g               0.9133007614732148
                                 scale_quantile log_g               0.9145103011700585
xgboost           PARSEC         Base           log_g                0.787073838129444
                                 scale_standard log_g                0.787073838129444
                                 scale_robust   log_g                0.787073838129444
                                 scale_power    log_g                0.787073838129444
                                 scale_quantile log_g               0.7926473162064176

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               4.12%
                                 scale_standard log_g               4.15%
                                 scale_robust   log_g              4.149%
                                 scale_power    log_g              4.135%
                                 scale_quantile log_g              4.112%
KNN               PARSEC         Base           log_g              4.347%
                                 scale_standard log_g              4.346%
                                 scale_robust   log_g              4.336%
                                 scale_power    log_g              4.314%
                                 scale_quantile log_g              4.336%
linear_regression PARSEC         Base           log_g             16.107%
                                 scale_standard log_g             16.107%
                                 scale_robust   log_g             16.107%
                                 scale_power    log_g             14.648%
                                 scale_quantile log_g             16.798%
mlp               PARSEC         Base           log_g              10.42%
                                 scale_standard log_g              8.703%
                                 scale_robust   log_g              8.281%
                                 scale_power    log_g              7.501%
                                 scale_quantile log_g              8.778%
random_forest     PARSEC         Base           log_g              3.801%
                                 scale_standard log_g              3.826%
                                 scale_robust   log_g              3.832%
                                 scale_power    log_g              3.829%
                                 scale_quantile log_g              3.802%
xgboost           PARSEC         Base           log_g              6.524%
                                 scale_standard log_g              6.524%
                                 scale_robust   log_g              6.524%
                                 scale_power    log_g              6.524%
                                 scale_quantile log_g              6.427%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              1.401%
                                 scale_standard log_g              1.403%
                                 scale_robust   log_g              1.402%
                                 scale_power    log_g                1.4%
                                 scale_quantile log_g                1.4%
KNN               PARSEC         Base           log_g               1.56%
                                 scale_standard log_g              1.561%
                                 scale_robust   log_g              1.556%
                                 scale_power    log_g              1.538%
                                 scale_quantile log_g              1.545%
linear_regression PARSEC         Base           log_g             12.889%
                                 scale_standard log_g             12.889%
                                 scale_robust   log_g             12.889%
                                 scale_power    log_g             11.285%
                                 scale_quantile log_g             12.422%
mlp               PARSEC         Base           log_g              8.008%
                                 scale_standard log_g              5.452%
                                 scale_robust   log_g              4.799%
                                 scale_power    log_g              4.222%
                                 scale_quantile log_g              5.964%
random_forest     PARSEC         Base           log_g              1.394%
                                 scale_standard log_g              1.399%
                                 scale_robust   log_g              1.397%
                                 scale_power    log_g              1.395%
                                 scale_quantile log_g              1.395%
xgboost           PARSEC         Base           log_g              3.496%
                                 scale_standard log_g              3.496%
                                 scale_robust   log_g              3.496%
                                 scale_power    log_g              3.496%
                                 scale_quantile log_g              3.408%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.287%
                                 scale_standard log_g              0.287%
                                 scale_robust   log_g              0.287%
                                 scale_power    log_g              0.287%
                                 scale_quantile log_g              0.287%
KNN               PARSEC         Base           log_g              0.136%
                                 scale_standard log_g              0.136%
                                 scale_robust   log_g              0.136%
                                 scale_power    log_g              0.136%
                                 scale_quantile log_g              0.136%
linear_regression PARSEC         Base           log_g             11.196%
                                 scale_standard log_g             11.196%
                                 scale_robust   log_g             11.196%
                                 scale_power    log_g             10.086%
                                 scale_quantile log_g             10.067%
mlp               PARSEC         Base           log_g              6.686%
                                 scale_standard log_g              3.193%
                                 scale_robust   log_g              2.667%
                                 scale_power    log_g              2.225%
                                 scale_quantile log_g              4.066%
random_forest     PARSEC         Base           log_g              0.294%
                                 scale_standard log_g              0.294%
                                 scale_robust   log_g              0.293%
                                 scale_power    log_g              0.294%
                                 scale_quantile log_g              0.295%
xgboost           PARSEC         Base           log_g              1.504%
                                 scale_standard log_g              1.504%
                                 scale_robust   log_g              1.504%
                                 scale_power    log_g              1.504%
                                 scale_quantile log_g              1.464%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.9495173145621928
                                 scale_standard log_g             0.9487824066213306
                                 scale_robust   log_g             0.9487923398806086
                                 scale_power    log_g             0.9491160298108762
                                 scale_quantile log_g             0.9497191439032258
KNN               PARSEC         Base           log_g             0.9441238142534801
                                 scale_standard log_g             0.9443346419781251
                                 scale_robust   log_g             0.9445532819799738
                                 scale_power    log_g             0.9451127713454177
                                 scale_quantile log_g             0.9445728745158648
linear_regression PARSEC         Base           log_g             0.6483869807966186
                                 scale_standard log_g             0.6483869807966377
                                 scale_robust   log_g             0.6483869807966347
                                 scale_power    log_g             0.7648846954755391
                                 scale_quantile log_g             0.3021438764042472
mlp               PARSEC         Base           log_g             0.8740210618735573
                                 scale_standard log_g             0.7750974765150644
                                 scale_robust   log_g             0.8152264379977063
                                 scale_power    log_g             0.8566536783722343
                                 scale_quantile log_g             0.7428858816142802
random_forest     PARSEC         Base           log_g              0.956704367836196
                                 scale_standard log_g              0.956123344408936
                                 scale_robust   log_g             0.9559976331815521
                                 scale_power    log_g             0.9560621271369991
                                 scale_quantile log_g             0.9566765276662501
xgboost           PARSEC         Base           log_g             0.8930521859521106
                                 scale_standard log_g             0.8930521859521106
                                 scale_robust   log_g             0.8930521859521106
                                 scale_power    log_g             0.8930521859521106
                                 scale_quantile log_g             0.8958903518594364

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             114.562%
                                 scale_standard log_g             114.562%
                                 scale_robust   log_g             114.562%
                                 scale_power    log_g             114.562%
                                 scale_quantile log_g             114.562%
KNN               PARSEC         Base           log_g             113.636%
                                 scale_standard log_g             113.156%
                                 scale_robust   log_g             113.636%
                                 scale_power    log_g             110.201%
                                 scale_quantile log_g             113.636%
linear_regression PARSEC         Base           log_g              61.457%
                                 scale_standard log_g              61.457%
                                 scale_robust   log_g              61.457%
                                 scale_power    log_g              78.174%
                                 scale_quantile log_g              87.826%
mlp               PARSEC         Base           log_g              65.415%
                                 scale_standard log_g              84.024%
                                 scale_robust   log_g              77.704%
                                 scale_power    log_g              60.099%
                                 scale_quantile log_g              82.653%
random_forest     PARSEC         Base           log_g             113.169%
                                 scale_standard log_g             113.655%
                                 scale_robust   log_g             114.468%
                                 scale_power    log_g             113.801%
                                 scale_quantile log_g              111.35%
xgboost           PARSEC         Base           log_g              52.596%
                                 scale_standard log_g              52.596%
                                 scale_robust   log_g              52.596%
                                 scale_power    log_g              52.596%
                                 scale_quantile log_g              53.947%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 1.376% / 90 : 3.311% / 95 : 5.633% / 99 : 15.992%
                                 scale_standard log_g                 75 : 1.376% / 90 : 3.309% / 95 : 5.63% / 99 : 15.992%
                                 scale_robust   log_g                 75 : 1.376% / 90 : 3.308% / 95 : 5.63% / 99 : 15.983%
                                 scale_power    log_g                75 : 1.376% / 90 : 3.303% / 95 : 5.617% / 99 : 15.972%
                                 scale_quantile log_g                75 : 1.377% / 90 : 3.311% / 95 : 5.634% / 99 : 15.972%
KNN               PARSEC         Base           log_g                75 : 0.558% / 90 : 5.838% / 95 : 10.929% / 99 : 16.29%
                                 scale_standard log_g                75 : 0.558% / 90 : 5.89% / 95 : 10.981% / 99 : 16.383%
                                 scale_robust   log_g               75 : 0.565% / 90 : 5.909% / 95 : 10.903% / 99 : 16.255%
                                 scale_power    log_g               75 : 0.552% / 90 : 5.721% / 95 : 10.896% / 99 : 16.227%
                                 scale_quantile log_g                75 : 0.558% / 90 : 5.74% / 95 : 10.896% / 99 : 16.177%
linear_regression PARSEC         Base           log_g             75 : 14.233% / 90 : 16.839% / 95 : 40.628% / 99 : 49.385%
                                 scale_standard log_g             75 : 14.233% / 90 : 16.839% / 95 : 40.628% / 99 : 49.385%
                                 scale_robust   log_g             75 : 14.233% / 90 : 16.839% / 95 : 40.628% / 99 : 49.385%
                                 scale_power    log_g             75 : 12.621% / 90 : 14.754% / 95 : 36.766% / 99 : 50.852%
                                 scale_quantile log_g             75 : 16.582% / 90 : 21.198% / 95 : 39.998% / 99 : 57.034%
mlp               PARSEC         Base           log_g              75 : 9.508% / 90 : 15.529% / 95 : 23.702% / 99 : 30.981%
                                 scale_standard log_g              75 : 6.463% / 90 : 12.985% / 95 : 19.352% / 99 : 33.262%
                                 scale_robust   log_g              75 : 4.994% / 90 : 11.268% / 95 : 19.764% / 99 : 34.157%

Results for the label category with a value of 5.0

                                                                  value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963
KNN               PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963
linear_regression PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963
mlp               PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963
random_forest     PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963
xgboost           PARSEC         Base           log_g             0.2 - 2.963
                                 scale_standard log_g             0.2 - 2.963
                                 scale_robust   log_g             0.2 - 2.963
                                 scale_power    log_g             0.2 - 2.963
                                 scale_quantile log_g             0.2 - 2.963

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9533659103656469
                                 scale_standard log_g              0.9533485737072066
                                 scale_robust   log_g              0.9532789186216881
                                 scale_power    log_g              0.9521181375499432
                                 scale_quantile log_g              0.9522182888582038
KNN               PARSEC         Base           log_g              0.9638467570643746
                                 scale_standard log_g               0.963197224040301
                                 scale_robust   log_g              0.9640646862822204
                                 scale_power    log_g              0.9629049549462361
                                 scale_quantile log_g               0.964664500593584
linear_regression PARSEC         Base           log_g              0.4678537575861228
                                 scale_standard log_g              0.4678537575861248
                                 scale_robust   log_g             0.46785375758612513
                                 scale_power    log_g               0.286536934088894
                                 scale_quantile log_g             0.04306140285593518
mlp               PARSEC         Base           log_g              0.6986586890359093
                                 scale_standard log_g              0.7210029626179728
                                 scale_robust   log_g               0.724772146546802
                                 scale_power    log_g              0.7205461495800787
                                 scale_quantile log_g              0.6929442327624743
random_forest     PARSEC         Base           log_g              0.9666549586583413
                                 scale_standard log_g              0.9659864195932849
                                 scale_robust   log_g              0.9658157447466269
                                 scale_power    log_g              0.9658374364723361
                                 scale_quantile log_g              0.9659784441439998
xgboost           PARSEC         Base           log_g              0.8051410225359259
                                 scale_standard log_g              0.8051410225359259
                                 scale_robust   log_g              0.8051410225359259
                                 scale_power    log_g              0.8051410225359259
                                 scale_quantile log_g              0.8026180201092282

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              5.689%
                                 scale_standard log_g               5.69%
                                 scale_robust   log_g              5.694%
                                 scale_power    log_g              5.764%
                                 scale_quantile log_g              5.758%
KNN               PARSEC         Base           log_g              5.023%
                                 scale_standard log_g              5.074%
                                 scale_robust   log_g              5.011%
                                 scale_power    log_g              5.084%
                                 scale_quantile log_g              4.963%
linear_regression PARSEC         Base           log_g             28.056%
                                 scale_standard log_g             28.056%
                                 scale_robust   log_g             28.056%
                                 scale_power    log_g             26.819%
                                 scale_quantile log_g             31.116%
mlp               PARSEC         Base           log_g             15.452%
                                 scale_standard log_g             13.914%
                                 scale_robust   log_g             14.032%
                                 scale_power    log_g             14.033%
                                 scale_quantile log_g             14.888%
random_forest     PARSEC         Base           log_g              4.811%
                                 scale_standard log_g              4.859%
                                 scale_robust   log_g              4.871%
                                 scale_power    log_g              4.869%
                                 scale_quantile log_g              4.859%
xgboost           PARSEC         Base           log_g             11.934%
                                 scale_standard log_g             11.934%
                                 scale_robust   log_g             11.934%
                                 scale_power    log_g             11.934%
                                 scale_quantile log_g             12.014%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              1.359%
                                 scale_standard log_g              1.355%
                                 scale_robust   log_g              1.358%
                                 scale_power    log_g              1.366%
                                 scale_quantile log_g              1.369%
KNN               PARSEC         Base           log_g              1.975%
                                 scale_standard log_g              1.984%
                                 scale_robust   log_g              1.977%
                                 scale_power    log_g              1.967%
                                 scale_quantile log_g              1.929%
linear_regression PARSEC         Base           log_g             23.898%
                                 scale_standard log_g             23.898%
                                 scale_robust   log_g             23.898%
                                 scale_power    log_g             19.192%
                                 scale_quantile log_g             22.804%
mlp               PARSEC         Base           log_g              11.59%
                                 scale_standard log_g             10.105%
                                 scale_robust   log_g              9.922%
                                 scale_power    log_g             10.226%
                                 scale_quantile log_g             10.897%
random_forest     PARSEC         Base           log_g              1.385%
                                 scale_standard log_g              1.401%
                                 scale_robust   log_g                1.4%
                                 scale_power    log_g              1.393%
                                 scale_quantile log_g              1.396%
xgboost           PARSEC         Base           log_g              8.159%
                                 scale_standard log_g              8.159%
                                 scale_robust   log_g              8.159%
                                 scale_power    log_g              8.159%
                                 scale_quantile log_g              8.234%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.036%
                                 scale_standard log_g              0.036%
                                 scale_robust   log_g              0.036%
                                 scale_power    log_g              0.036%
                                 scale_quantile log_g              0.036%
KNN               PARSEC         Base           log_g              0.145%
                                 scale_standard log_g              0.145%
                                 scale_robust   log_g              0.145%
                                 scale_power    log_g              0.145%
                                 scale_quantile log_g              0.159%
linear_regression PARSEC         Base           log_g             22.172%
                                 scale_standard log_g             22.172%
                                 scale_robust   log_g             22.172%
                                 scale_power    log_g             11.048%
                                 scale_quantile log_g              14.45%
mlp               PARSEC         Base           log_g              7.974%
                                 scale_standard log_g              7.016%
                                 scale_robust   log_g                5.9%
                                 scale_power    log_g              6.973%
                                 scale_quantile log_g               7.65%
random_forest     PARSEC         Base           log_g              0.054%
                                 scale_standard log_g              0.055%
                                 scale_robust   log_g              0.054%
                                 scale_power    log_g              0.055%
                                 scale_quantile log_g              0.055%
xgboost           PARSEC         Base           log_g              4.676%
                                 scale_standard log_g              4.676%
                                 scale_robust   log_g              4.676%
                                 scale_power    log_g              4.676%
                                 scale_quantile log_g              4.809%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9768621176667662
                                 scale_standard log_g              0.9768409052245859
                                 scale_robust   log_g              0.9768119563948813
                                 scale_power    log_g              0.9762369060254048
                                 scale_quantile log_g              0.9762890354348172
KNN               PARSEC         Base           log_g              0.9819199172421853
                                 scale_standard log_g              0.9815512589272011
                                 scale_robust   log_g              0.9819950401322295
                                 scale_power    log_g              0.9813451971854734
                                 scale_quantile log_g              0.9822955362632386
linear_regression PARSEC         Base           log_g              0.7008181919711453
                                 scale_standard log_g              0.7008181919711471
                                 scale_robust   log_g              0.7008181919711474
                                 scale_power    log_g              0.7013119937258593
                                 scale_quantile log_g             0.20872115282201356
mlp               PARSEC         Base           log_g              0.8616045482860637
                                 scale_standard log_g              0.8610516588847313
                                 scale_robust   log_g              0.8609810641580103
                                 scale_power    log_g              0.8565725777145421
                                 scale_quantile log_g              0.8351979482515052
random_forest     PARSEC         Base           log_g              0.9833138504657927
                                 scale_standard log_g              0.9829783260133274
                                 scale_robust   log_g              0.9828944542834197
                                 scale_power    log_g              0.9829042497247098
                                 scale_quantile log_g              0.9829752101049196
xgboost           PARSEC         Base           log_g              0.8996437217333252
                                 scale_standard log_g              0.8996437217333252
                                 scale_robust   log_g              0.8996437217333252
                                 scale_power    log_g              0.8996437217333252
                                 scale_quantile log_g              0.8981261747035376

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             108.867%
                                 scale_standard log_g             108.867%
                                 scale_robust   log_g             108.867%
                                 scale_power    log_g             108.867%
                                 scale_quantile log_g             108.867%
KNN               PARSEC         Base           log_g               73.29%
                                 scale_standard log_g               73.29%
                                 scale_robust   log_g               73.29%
                                 scale_power    log_g               73.29%
                                 scale_quantile log_g               73.29%
linear_regression PARSEC         Base           log_g              73.913%
                                 scale_standard log_g              73.913%
                                 scale_robust   log_g              73.913%
                                 scale_power    log_g              76.753%
                                 scale_quantile log_g              87.664%
mlp               PARSEC         Base           log_g              61.157%
                                 scale_standard log_g              68.442%
                                 scale_robust   log_g              59.158%
                                 scale_power    log_g              52.341%
                                 scale_quantile log_g               58.54%
random_forest     PARSEC         Base           log_g               72.41%
                                 scale_standard log_g              71.428%
                                 scale_robust   log_g              71.144%
                                 scale_power    log_g               72.01%
                                 scale_quantile log_g              71.685%
xgboost           PARSEC         Base           log_g              73.157%
                                 scale_standard log_g              73.157%
                                 scale_robust   log_g              73.157%
                                 scale_power    log_g              73.157%
                                 scale_quantile log_g              74.086%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 0.181% / 90 : 2.208% / 95 : 6.075% / 99 : 29.941%
                                 scale_standard log_g                75 : 0.181% / 90 : 2.208% / 95 : 6.074% / 99 : 29.941%
                                 scale_robust   log_g                75 : 0.181% / 90 : 2.179% / 95 : 6.044% / 99 : 30.138%
                                 scale_power    log_g                75 : 0.181% / 90 : 2.199% / 95 : 6.044% / 99 : 30.777%
                                 scale_quantile log_g                75 : 0.181% / 90 : 2.208% / 95 : 6.069% / 99 : 31.167%
KNN               PARSEC         Base           log_g                75 : 1.976% / 90 : 5.139% / 95 : 8.878% / 99 : 24.362%
                                 scale_standard log_g                75 : 1.976% / 90 : 5.132% / 95 : 9.052% / 99 : 25.288%
                                 scale_robust   log_g                75 : 1.969% / 90 : 5.161% / 95 : 8.911% / 99 : 25.591%
                                 scale_power    log_g                 75 : 1.94% / 90 : 5.024% / 95 : 8.845% / 99 : 25.713%
                                 scale_quantile log_g                75 : 1.954% / 90 : 4.944% / 95 : 8.639% / 99 : 24.316%
linear_regression PARSEC         Base           log_g             75 : 36.381% / 90 : 44.606% / 95 : 47.767% / 99 : 51.575%
                                 scale_standard log_g             75 : 36.381% / 90 : 44.606% / 95 : 47.767% / 99 : 51.575%
                                 scale_robust   log_g             75 : 36.381% / 90 : 44.606% / 95 : 47.767% / 99 : 51.575%
                                 scale_power    log_g             75 : 29.598% / 90 : 50.249% / 95 : 57.843% / 99 : 71.919%
                                 scale_quantile log_g              75 : 34.848% / 90 : 56.547% / 95 : 66.328% / 99 : 83.22%
mlp               PARSEC         Base           log_g             75 : 18.033% / 90 : 27.323% / 95 : 31.689% / 99 : 40.176%
                                 scale_standard log_g             75 : 14.632% / 90 : 23.748% / 95 : 29.134% / 99 : 40.066%
                                 scale_robust   log_g              75 : 15.105% / 90 : 25.42% / 95 : 30.353% / 99 : 38.796%
                                 scale_power    log_g             75 : 14.871% / 90 : 25.138% / 95 : 30.242% / 99 : 38.908%

Results for the label category with a value of 6.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837
KNN               PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837
linear_regression PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837
mlp               PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837
random_forest     PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837
xgboost           PARSEC         Base           log_g             -0.017 - 2.837
                                 scale_standard log_g             -0.017 - 2.837
                                 scale_robust   log_g             -0.017 - 2.837
                                 scale_power    log_g             -0.017 - 2.837
                                 scale_quantile log_g             -0.017 - 2.837

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.9311821113501082
                                 scale_standard log_g                0.929517539338161
                                 scale_robust   log_g               0.9264577275114696
                                 scale_power    log_g               0.9289414280679307
                                 scale_quantile log_g               0.9295724300465816
KNN               PARSEC         Base           log_g               0.9376850472249867
                                 scale_standard log_g               0.9409178852004807
                                 scale_robust   log_g               0.9404608022925783
                                 scale_power    log_g                0.940692353807718
                                 scale_quantile log_g               0.9411621939587971
linear_regression PARSEC         Base           log_g               -0.725236777537009
                                 scale_standard log_g              -0.7252367775369954
                                 scale_robust   log_g              -0.7252367775370083
                                 scale_power    log_g              0.09098109521949538
                                 scale_quantile log_g             -0.14353134768152187
mlp               PARSEC         Base           log_g              0.45945948611375387
                                 scale_standard log_g               0.5280938995039888
                                 scale_robust   log_g              0.48892627175266745
                                 scale_power    log_g              0.42620805702358455
                                 scale_quantile log_g              0.31121517373373686
random_forest     PARSEC         Base           log_g               0.9485394146228903
                                 scale_standard log_g               0.9466486612623207
                                 scale_robust   log_g               0.9474876626707291
                                 scale_power    log_g               0.9466566285258117
                                 scale_quantile log_g               0.9463054381139128
xgboost           PARSEC         Base           log_g               0.6299752924480326
                                 scale_standard log_g               0.6299752924480326
                                 scale_robust   log_g               0.6299752924480326
                                 scale_power    log_g               0.6299752924480326
                                 scale_quantile log_g               0.6241313903901236

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              5.466%
                                 scale_standard log_g              5.531%
                                 scale_robust   log_g              5.651%
                                 scale_power    log_g              5.553%
                                 scale_quantile log_g              5.529%
KNN               PARSEC         Base           log_g              5.204%
                                 scale_standard log_g              5.072%
                                 scale_robust   log_g               5.09%
                                 scale_power    log_g              5.107%
                                 scale_quantile log_g              5.057%
linear_regression PARSEC         Base           log_g             34.264%
                                 scale_standard log_g             34.264%
                                 scale_robust   log_g             34.264%
                                 scale_power    log_g             27.616%
                                 scale_quantile log_g             31.486%
mlp               PARSEC         Base           log_g             16.917%
                                 scale_standard log_g             14.328%
                                 scale_robust   log_g             14.936%
                                 scale_power    log_g             15.813%
                                 scale_quantile log_g             17.293%
random_forest     PARSEC         Base           log_g               4.73%
                                 scale_standard log_g              4.816%
                                 scale_robust   log_g              4.778%
                                 scale_power    log_g              4.814%
                                 scale_quantile log_g              4.832%
xgboost           PARSEC         Base           log_g             13.145%
                                 scale_standard log_g             13.145%
                                 scale_robust   log_g             13.145%
                                 scale_power    log_g             13.145%
                                 scale_quantile log_g             13.211%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              1.634%
                                 scale_standard log_g              1.635%
                                 scale_robust   log_g              1.668%
                                 scale_power    log_g              1.656%
                                 scale_quantile log_g              1.646%
KNN               PARSEC         Base           log_g              2.941%
                                 scale_standard log_g              2.906%
                                 scale_robust   log_g              2.923%
                                 scale_power    log_g              2.988%
                                 scale_quantile log_g              2.874%
linear_regression PARSEC         Base           log_g             31.365%
                                 scale_standard log_g             31.365%
                                 scale_robust   log_g             31.365%
                                 scale_power    log_g             21.329%
                                 scale_quantile log_g             23.941%
mlp               PARSEC         Base           log_g             14.079%
                                 scale_standard log_g             11.512%
                                 scale_robust   log_g             12.085%
                                 scale_power    log_g             12.715%
                                 scale_quantile log_g             13.898%
random_forest     PARSEC         Base           log_g              1.577%
                                 scale_standard log_g              1.579%
                                 scale_robust   log_g              1.575%
                                 scale_power    log_g              1.595%
                                 scale_quantile log_g              1.588%
xgboost           PARSEC         Base           log_g             10.309%
                                 scale_standard log_g             10.309%
                                 scale_robust   log_g             10.309%
                                 scale_power    log_g             10.309%
                                 scale_quantile log_g             10.361%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.631%
                                 scale_standard log_g              0.631%
                                 scale_robust   log_g              0.631%
                                 scale_power    log_g              0.631%
                                 scale_quantile log_g              0.631%
KNN               PARSEC         Base           log_g              1.847%
                                 scale_standard log_g               1.85%
                                 scale_robust   log_g              1.857%
                                 scale_power    log_g              1.948%
                                 scale_quantile log_g               1.78%
linear_regression PARSEC         Base           log_g             30.591%
                                 scale_standard log_g             30.591%
                                 scale_robust   log_g             30.591%
                                 scale_power    log_g             15.597%
                                 scale_quantile log_g              17.68%
mlp               PARSEC         Base           log_g              12.45%
                                 scale_standard log_g              9.752%
                                 scale_robust   log_g             10.178%
                                 scale_power    log_g             10.539%
                                 scale_quantile log_g             11.959%
random_forest     PARSEC         Base           log_g              0.526%
                                 scale_standard log_g              0.525%
                                 scale_robust   log_g              0.525%
                                 scale_power    log_g              0.534%
                                 scale_quantile log_g              0.526%
xgboost           PARSEC         Base           log_g              8.442%
                                 scale_standard log_g              8.442%
                                 scale_robust   log_g              8.442%
                                 scale_power    log_g              8.442%
                                 scale_quantile log_g              8.501%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9659004318793163
                                 scale_standard log_g              0.9650589447380389
                                 scale_robust   log_g              0.9635466094105348
                                 scale_power    log_g              0.9647425740440753
                                 scale_quantile log_g              0.9650973625812314
KNN               PARSEC         Base           log_g               0.968447483894023
                                 scale_standard log_g               0.970211180958711
                                 scale_robust   log_g              0.9699407358477989
                                 scale_power    log_g              0.9700165488353681
                                 scale_quantile log_g              0.9702617243563453
linear_regression PARSEC         Base           log_g              0.2742120379276352
                                 scale_standard log_g              0.2742120379276403
                                 scale_robust   log_g             0.27421203792763815
                                 scale_power    log_g              0.3016512920838976
                                 scale_quantile log_g             -0.1943233399434064
mlp               PARSEC         Base           log_g              0.6800634465130304
                                 scale_standard log_g              0.7268106583802572
                                 scale_robust   log_g              0.7001571094555059
                                 scale_power    log_g              0.6575940048604938
                                 scale_quantile log_g              0.5894688481376272
random_forest     PARSEC         Base           log_g              0.9740958718877286
                                 scale_standard log_g               0.973135028249065
                                 scale_robust   log_g              0.9735635149541543
                                 scale_power    log_g              0.9731371336419753
                                 scale_quantile log_g              0.9729570837990279
xgboost           PARSEC         Base           log_g              0.7940521336810684
                                 scale_standard log_g              0.7940521336810684
                                 scale_robust   log_g              0.7940521336810684
                                 scale_power    log_g              0.7940521336810684
                                 scale_quantile log_g              0.7906533898659439

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             105.746%
                                 scale_standard log_g             105.746%
                                 scale_robust   log_g             105.746%
                                 scale_power    log_g             105.746%
                                 scale_quantile log_g             105.746%
KNN               PARSEC         Base           log_g              73.889%
                                 scale_standard log_g              73.889%
                                 scale_robust   log_g              75.067%
                                 scale_power    log_g              73.889%
                                 scale_quantile log_g              76.755%
linear_regression PARSEC         Base           log_g              70.558%
                                 scale_standard log_g              70.558%
                                 scale_robust   log_g              70.558%
                                 scale_power    log_g              82.055%
                                 scale_quantile log_g               92.58%
mlp               PARSEC         Base           log_g              54.373%
                                 scale_standard log_g              43.467%
                                 scale_robust   log_g              47.403%
                                 scale_power    log_g              47.736%
                                 scale_quantile log_g              64.972%
random_forest     PARSEC         Base           log_g              75.422%
                                 scale_standard log_g              76.021%
                                 scale_robust   log_g               76.63%
                                 scale_power    log_g              75.619%
                                 scale_quantile log_g               76.26%
xgboost           PARSEC         Base           log_g              47.874%
                                 scale_standard log_g              47.874%
                                 scale_robust   log_g              47.874%
                                 scale_power    log_g              47.874%
                                 scale_quantile log_g              62.131%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 1.507% / 90 : 2.803% / 95 : 4.608% / 99 : 24.783%
                                 scale_standard log_g                75 : 1.507% / 90 : 2.781% / 95 : 4.628% / 99 : 24.012%
                                 scale_robust   log_g                75 : 1.507% / 90 : 2.803% / 95 : 4.642% / 99 : 27.446%
                                 scale_power    log_g                 75 : 1.542% / 90 : 2.838% / 95 : 4.65% / 99 : 25.457%
                                 scale_quantile log_g                75 : 1.507% / 90 : 2.803% / 95 : 4.601% / 99 : 25.628%
KNN               PARSEC         Base           log_g                75 : 3.462% / 90 : 5.837% / 95 : 8.657% / 99 : 22.088%
                                 scale_standard log_g                75 : 3.464% / 90 : 5.811% / 95 : 8.346% / 99 : 21.492%
                                 scale_robust   log_g                75 : 3.485% / 90 : 5.802% / 95 : 8.488% / 99 : 21.469%
                                 scale_power    log_g                75 : 3.609% / 90 : 5.957% / 95 : 8.488% / 99 : 21.481%
                                 scale_quantile log_g                75 : 3.455% / 90 : 5.844% / 95 : 8.479% / 99 : 21.166%
linear_regression PARSEC         Base           log_g             75 : 42.335% / 90 : 49.824% / 95 : 53.356% / 99 : 59.118%
                                 scale_standard log_g             75 : 42.335% / 90 : 49.824% / 95 : 53.356% / 99 : 59.118%
                                 scale_robust   log_g             75 : 42.335% / 90 : 49.824% / 95 : 53.356% / 99 : 59.118%
                                 scale_power    log_g             75 : 32.528% / 90 : 48.457% / 95 : 55.334% / 99 : 71.027%
                                 scale_quantile log_g              75 : 37.377% / 90 : 55.262% / 95 : 63.31% / 99 : 81.725%
mlp               PARSEC         Base           log_g             75 : 20.679% / 90 : 27.508% / 95 : 31.235% / 99 : 37.108%
                                 scale_standard log_g             75 : 17.202% / 90 : 23.937% / 95 : 27.572% / 99 : 34.608%
                                 scale_robust   log_g             75 : 17.685% / 90 : 24.865% / 95 : 28.708% / 99 : 35.974%

### Radius parameter

In [5]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                data_filters=["Base", "scale_standard", "scale_robust", "scale_power", "scale_quantile"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003
KNN               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003
mlp               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_standard radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_robust   radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_power    radius            -0.9763360818022064 - 2.8372727025023003
                                 scale_quantile radius            -0.9763360818022064 - 2.8372727025023003

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.8188802537475399
                                 scale_standard radius             0.8190747575366757
                                 scale_robust   radius             0.8185432995307229
                                 scale_power    radius             0.8198195793722163
                                 scale_quantile radius             0.8192489179790492
KNN               PARSEC         Base           radius             0.8504530694492762
                                 scale_standard radius             0.8586704103799776
                                 scale_robust   radius             0.8536930713801498
                                 scale_power    radius             0.8630060550997996
                                 scale_quantile radius             0.8620816642470333
linear_regression PARSEC         Base           radius              0.306153058491456
                                 scale_standard radius              0.306153058491456
                                 scale_robust   radius              0.306153058491456
                                 scale_power    radius            0.48191363727410264
                                 scale_quantile radius             0.4181221591335167
mlp               PARSEC         Base           radius             0.6228554128105982
                                 scale_standard radius             0.7609447580918802
                                 scale_robust   radius             0.7791825930560183
                                 scale_power    radius             0.7979741080602429
                                 scale_quantile radius             0.7282881435705018
random_forest     PARSEC         Base           radius             0.8584173604243724
                                 scale_standard radius             0.8587010025371918
                                 scale_robust   radius             0.8583730087252667
                                 scale_power    radius             0.8588306713835852
                                 scale_quantile radius             0.8590000765896002
xgboost           PARSEC         Base           radius             0.7945230921341289
                                 scale_standard radius             0.7945230921341289
                                 scale_robust   radius             0.7945230921341289
                                 scale_power    radius             0.7945230921341289
                                 scale_quantile radius             0.7945842554530732

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.804%
                                 scale_standard radius               6.8%
                                 scale_robust   radius              6.81%
                                 scale_power    radius             6.786%
                                 scale_quantile radius             6.797%
KNN               PARSEC         Base           radius             6.185%
                                 scale_standard radius             6.011%
                                 scale_robust   radius             6.117%
                                 scale_power    radius             5.918%
                                 scale_quantile radius             5.938%
linear_regression PARSEC         Base           radius            13.317%
                                 scale_standard radius            13.317%
                                 scale_robust   radius            13.317%
                                 scale_power    radius            11.508%
                                 scale_quantile radius            12.196%
mlp               PARSEC         Base           radius             9.833%
                                 scale_standard radius             7.817%
                                 scale_robust   radius             7.515%
                                 scale_power    radius             7.186%
                                 scale_quantile radius             8.386%
random_forest     PARSEC         Base           radius             6.016%
                                 scale_standard radius              6.01%
                                 scale_robust   radius             6.017%
                                 scale_power    radius             6.007%
                                 scale_quantile radius             6.003%
xgboost           PARSEC         Base           radius             7.247%
                                 scale_standard radius             7.247%
                                 scale_robust   radius             7.247%
                                 scale_power    radius             7.247%
                                 scale_quantile radius             7.246%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.974%
                                 scale_standard radius             1.972%
                                 scale_robust   radius             1.976%
                                 scale_power    radius              1.97%
                                 scale_quantile radius             1.972%
KNN               PARSEC         Base           radius             2.221%
                                 scale_standard radius             2.153%
                                 scale_robust   radius              2.19%
                                 scale_power    radius             2.083%
                                 scale_quantile radius             2.117%
linear_regression PARSEC         Base           radius            10.424%
                                 scale_standard radius            10.424%
                                 scale_robust   radius            10.424%
                                 scale_power    radius             8.826%
                                 scale_quantile radius             9.516%
mlp               PARSEC         Base           radius             6.651%
                                 scale_standard radius             4.634%
                                 scale_robust   radius             4.311%
                                 scale_power    radius             4.024%
                                 scale_quantile radius             5.346%
random_forest     PARSEC         Base           radius             1.916%
                                 scale_standard radius             1.915%
                                 scale_robust   radius             1.916%
                                 scale_power    radius             1.915%
                                 scale_quantile radius             1.915%
xgboost           PARSEC         Base           radius             4.116%
                                 scale_standard radius             4.116%
                                 scale_robust   radius             4.116%
                                 scale_power    radius             4.116%
                                 scale_quantile radius             4.113%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.149%
                                 scale_standard radius            0.149%
                                 scale_robust   radius            0.149%
                                 scale_power    radius            0.149%
                                 scale_quantile radius             0.15%
KNN               PARSEC         Base           radius            0.191%
                                 scale_standard radius            0.207%
                                 scale_robust   radius            0.196%
                                 scale_power    radius            0.181%
                                 scale_quantile radius            0.195%
linear_regression PARSEC         Base           radius            7.199%
                                 scale_standard radius            7.199%
                                 scale_robust   radius            7.199%
                                 scale_power    radius            5.401%
                                 scale_quantile radius            7.428%
mlp               PARSEC         Base           radius            3.493%
                                 scale_standard radius            1.882%
                                 scale_robust   radius            1.612%
                                 scale_power    radius            1.372%
                                 scale_quantile radius            2.879%
random_forest     PARSEC         Base           radius            0.169%
                                 scale_standard radius             0.17%
                                 scale_robust   radius            0.168%
                                 scale_power    radius             0.17%
                                 scale_quantile radius             0.17%
xgboost           PARSEC         Base           radius            1.422%
                                 scale_standard radius            1.422%
                                 scale_robust   radius            1.422%
                                 scale_power    radius            1.422%
                                 scale_quantile radius            1.419%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9078549079572853
                                 scale_standard radius            0.9079473677307951
                                 scale_robust   radius            0.9076828599466551
                                 scale_power    radius            0.9083083280558879
                                 scale_quantile radius            0.9080365074590928
KNN               PARSEC         Base           radius            0.9227969605947961
                                 scale_standard radius            0.9270393060711309
                                 scale_robust   radius            0.9244860408772165
                                 scale_power    radius            0.9293254559170496
                                 scale_quantile radius            0.9288046951373076
linear_regression PARSEC         Base           radius            0.5533109976788975
                                 scale_standard radius            0.5533109976788975
                                 scale_robust   radius            0.5533109976788976
                                 scale_power    radius            0.6941999986298386
                                 scale_quantile radius            0.6466236629435865
mlp               PARSEC         Base           radius            0.7892150515996972
                                 scale_standard radius            0.8723224815682044
                                 scale_robust   radius            0.8827279173710678
                                 scale_power    radius            0.8936129456621495
                                 scale_quantile radius            0.8534087801706158
random_forest     PARSEC         Base           radius            0.9271725495364581
                                 scale_standard radius            0.9273142734241677
                                 scale_robust   radius            0.9271496909205685
                                 scale_power    radius             0.927379865342682
                                 scale_quantile radius            0.9274659298564655
xgboost           PARSEC         Base           radius            0.8915692177111999
                                 scale_standard radius            0.8915692177111999
                                 scale_robust   radius            0.8915692177111999
                                 scale_power    radius            0.8915692177111999
                                 scale_quantile radius            0.8916028355793677

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            62.692%
                                 scale_standard radius            62.549%
                                 scale_robust   radius            62.692%
                                 scale_power    radius            62.692%
                                 scale_quantile radius            62.692%
KNN               PARSEC         Base           radius            60.762%
                                 scale_standard radius            60.762%
                                 scale_robust   radius            60.762%
                                 scale_power    radius            60.762%
                                 scale_quantile radius             60.76%
linear_regression PARSEC         Base           radius            46.708%
                                 scale_standard radius            46.708%
                                 scale_robust   radius            46.708%
                                 scale_power    radius             37.13%
                                 scale_quantile radius            42.509%
mlp               PARSEC         Base           radius            52.199%
                                 scale_standard radius            50.648%
                                 scale_robust   radius            56.118%
                                 scale_power    radius            58.533%
                                 scale_quantile radius            48.931%
random_forest     PARSEC         Base           radius             60.58%
                                 scale_standard radius            61.196%
                                 scale_robust   radius            61.096%
                                 scale_power    radius            60.705%
                                 scale_quantile radius            60.443%
xgboost           PARSEC         Base           radius            59.294%
                                 scale_standard radius            59.294%
                                 scale_robust   radius            59.294%
                                 scale_power    radius            59.294%
                                 scale_quantile radius            58.518%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 38.117%
                                 scale_standard radius               75 : 0.754% / 90 : 2.91% / 95 : 11.654% / 99 : 38.099%
                                 scale_robust   radius              75 : 0.754% / 90 : 2.919% / 95 : 11.708% / 99 : 38.146%
                                 scale_power    radius              75 : 0.754% / 90 : 2.918% / 95 : 11.708% / 99 : 37.967%
                                 scale_quantile radius              75 : 0.754% / 90 : 2.917% / 95 : 11.656% / 99 : 37.991%
KNN               PARSEC         Base           radius              75 : 1.182% / 90 : 5.835% / 95 : 13.571% / 99 : 29.416%
                                 scale_standard radius              75 : 1.187% / 90 : 5.535% / 95 : 12.811% / 99 : 28.772%
                                 scale_robust   radius              75 : 1.178% / 90 : 5.696% / 95 : 13.257% / 99 : 29.171%
                                 scale_power    radius              75 : 1.067% / 90 : 5.347% / 95 : 12.383% / 99 : 28.486%
                                 scale_quantile radius              75 : 1.176% / 90 : 5.389% / 95 : 12.365% / 99 : 28.477%
linear_regression PARSEC         Base           radius            75 : 15.422% / 90 : 22.006% / 95 : 26.756% / 99 : 37.275%
                                 scale_standard radius            75 : 15.422% / 90 : 22.006% / 95 : 26.756% / 99 : 37.275%

Results for the label category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815
KNN               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815
mlp               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_standard radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_robust   radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_power    radius            -0.9763360818022064 - 1.1687920203141815
                                 scale_quantile radius            -0.9763360818022064 - 1.1687920203141815

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius               0.7363724523806283
                                 scale_standard radius               0.7419206968799053
                                 scale_robust   radius                0.738281930565384
                                 scale_power    radius               0.7401345884210887
                                 scale_quantile radius               0.7405548226925223
KNN               PARSEC         Base           radius               0.6600434525070423
                                 scale_standard radius               0.7543806153801486
                                 scale_robust   radius               0.6956836920878375
                                 scale_power    radius               0.7998821386337984
                                 scale_quantile radius                0.787733169233738
linear_regression PARSEC         Base           radius               0.2911261433374668
                                 scale_standard radius               0.2911261433374748
                                 scale_robust   radius               0.2911261433374712
                                 scale_power    radius             -0.14206133784661334
                                 scale_quantile radius            -0.037387340131723734
mlp               PARSEC         Base           radius             -0.17637582185160272
                                 scale_standard radius               0.4709409868157749
                                 scale_robust   radius               0.5924749489555952
                                 scale_power    radius               0.6475073704354485
                                 scale_quantile radius              0.24804334713329645
random_forest     PARSEC         Base           radius                0.821604552614865
                                 scale_standard radius               0.8235812198711056
                                 scale_robust   radius               0.8212550572178736
                                 scale_power    radius               0.8214644325384362
                                 scale_quantile radius               0.8228689353429535
xgboost           PARSEC         Base           radius               0.5662612193213132
                                 scale_standard radius               0.5662612193213132
                                 scale_robust   radius               0.5662612193213132
                                 scale_power    radius               0.5662612193213132
                                 scale_quantile radius               0.5623545428425764

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             8.877%
                                 scale_standard radius             8.782%
                                 scale_robust   radius             8.844%
                                 scale_power    radius             8.813%
                                 scale_quantile radius             8.805%
KNN               PARSEC         Base           radius            10.375%
                                 scale_standard radius             8.746%
                                 scale_robust   radius             9.781%
                                 scale_power    radius             7.852%
                                 scale_quantile radius             8.073%
linear_regression PARSEC         Base           radius            37.673%
                                 scale_standard radius            37.673%
                                 scale_robust   radius            37.673%
                                 scale_power    radius            30.494%
                                 scale_quantile radius            29.774%
mlp               PARSEC         Base           radius            25.346%
                                 scale_standard radius            13.912%
                                 scale_robust   radius            11.945%
                                 scale_power    radius             11.16%
                                 scale_quantile radius            18.031%
random_forest     PARSEC         Base           radius             7.373%
                                 scale_standard radius             7.333%
                                 scale_robust   radius              7.38%
                                 scale_power    radius             7.376%
                                 scale_quantile radius             7.348%
xgboost           PARSEC         Base           radius            12.901%
                                 scale_standard radius            12.901%
                                 scale_robust   radius            12.901%
                                 scale_power    radius            12.901%
                                 scale_quantile radius            12.958%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.589%
                                 scale_standard radius             1.568%
                                 scale_robust   radius             1.581%
                                 scale_power    radius              1.58%
                                 scale_quantile radius             1.573%
KNN               PARSEC         Base           radius             3.233%
                                 scale_standard radius             2.675%
                                 scale_robust   radius             2.996%
                                 scale_power    radius             2.081%
                                 scale_quantile radius             2.416%
linear_regression PARSEC         Base           radius            34.827%
                                 scale_standard radius            34.827%
                                 scale_robust   radius            34.827%
                                 scale_power    radius            28.417%
                                 scale_quantile radius            27.817%
mlp               PARSEC         Base           radius            18.723%
                                 scale_standard radius             7.163%
                                 scale_robust   radius             5.983%
                                 scale_power    radius             5.225%
                                 scale_quantile radius            11.263%
random_forest     PARSEC         Base           radius             1.647%
                                 scale_standard radius             1.641%
                                 scale_robust   radius             1.645%
                                 scale_power    radius             1.647%
                                 scale_quantile radius             1.644%
xgboost           PARSEC         Base           radius              7.49%
                                 scale_standard radius              7.49%
                                 scale_robust   radius              7.49%
                                 scale_power    radius              7.49%
                                 scale_quantile radius             7.523%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.019%
                                 scale_standard radius             0.019%
                                 scale_robust   radius             0.018%
                                 scale_power    radius             0.019%
                                 scale_quantile radius             0.019%
KNN               PARSEC         Base           radius             0.231%
                                 scale_standard radius             0.311%
                                 scale_robust   radius             0.257%
                                 scale_power    radius              0.21%
                                 scale_quantile radius             0.252%
linear_regression PARSEC         Base           radius            31.484%
                                 scale_standard radius            31.484%
                                 scale_robust   radius            31.484%
                                 scale_power    radius            29.957%
                                 scale_quantile radius            29.842%
mlp               PARSEC         Base           radius             13.37%
                                 scale_standard radius             1.564%
                                 scale_robust   radius              1.74%
                                 scale_power    radius             1.263%
                                 scale_quantile radius             4.213%
random_forest     PARSEC         Base           radius             0.026%
                                 scale_standard radius             0.027%
                                 scale_robust   radius             0.026%
                                 scale_power    radius             0.026%
                                 scale_quantile radius             0.028%
xgboost           PARSEC         Base           radius             2.385%
                                 scale_standard radius             2.385%
                                 scale_robust   radius             2.385%
                                 scale_power    radius             2.385%
                                 scale_quantile radius             2.385%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.891072495933085
                                 scale_standard radius            0.8928647443436053
                                 scale_robust   radius            0.8917350869577356
                                 scale_power    radius            0.8923579243420225
                                 scale_quantile radius            0.8924437137516856
KNN               PARSEC         Base           radius            0.8859021657633167
                                 scale_standard radius            0.9016261189235775
                                 scale_robust   radius            0.8914982490901747
                                 scale_power    radius            0.9132646003322126
                                 scale_quantile radius            0.9069845038388326
linear_regression PARSEC         Base           radius            0.6331630624513377
                                 scale_standard radius            0.6331630624513427
                                 scale_robust   radius            0.6331630624513411
                                 scale_power    radius            0.9059249394544188
                                 scale_quantile radius            0.8117860460150378
mlp               PARSEC         Base           radius            0.7838452832290015
                                 scale_standard radius            0.8409758815727522
                                 scale_robust   radius            0.8790956561834585
                                 scale_power    radius            0.8799960122650446
                                 scale_quantile radius            0.8033663175160286
random_forest     PARSEC         Base           radius            0.9227998598367169
                                 scale_standard radius            0.9235477498585641
                                 scale_robust   radius             0.922726008506314
                                 scale_power    radius            0.9226769514994266
                                 scale_quantile radius            0.9233222632239165
xgboost           PARSEC         Base           radius            0.8825965510893421
                                 scale_standard radius            0.8825965510893421
                                 scale_robust   radius            0.8825965510893421
                                 scale_power    radius            0.8825965510893421
                                 scale_quantile radius            0.8813293694382052

                                                                    MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            111.453%
                                 scale_standard radius            109.496%
                                 scale_robust   radius            111.453%
                                 scale_power    radius            111.453%
                                 scale_quantile radius            111.453%
KNN               PARSEC         Base           radius            105.176%
                                 scale_standard radius            105.176%
                                 scale_robust   radius            105.176%
                                 scale_power    radius            105.176%
                                 scale_quantile radius            105.176%
linear_regression PARSEC         Base           radius             83.037%
                                 scale_standard radius             83.037%
                                 scale_robust   radius             83.037%
                                 scale_power    radius             55.083%
                                 scale_quantile radius             73.967%
mlp               PARSEC         Base           radius             64.472%
                                 scale_standard radius             65.315%
                                 scale_robust   radius             61.423%
                                 scale_power    radius             65.539%
                                 scale_quantile radius              67.95%
random_forest     PARSEC         Base           radius             98.493%
                                 scale_standard radius              97.66%
                                 scale_robust   radius            100.852%
                                 scale_power    radius            101.241%
                                 scale_quantile radius             94.243%
xgboost           PARSEC         Base           radius             79.564%
                                 scale_standard radius             79.564%
                                 scale_robust   radius             79.564%
                                 scale_power    radius             79.564%
                                 scale_quantile radius             77.211%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                 75 : 0.156% / 90 : 0.677% / 95 : 1.6% / 99 : 45.886%
                                 scale_standard radius               75 : 0.158% / 90 : 0.682% / 95 : 1.585% / 99 : 45.806%
                                 scale_robust   radius               75 : 0.157% / 90 : 0.682% / 95 : 1.589% / 99 : 45.866%
                                 scale_power    radius               75 : 0.156% / 90 : 0.679% / 95 : 1.598% / 99 : 45.866%
                                 scale_quantile radius                 75 : 0.162% / 90 : 0.688% / 95 : 1.6% / 99 : 45.866%
KNN               PARSEC         Base           radius              75 : 0.845% / 90 : 5.525% / 95 : 19.794% / 99 : 52.228%
                                 scale_standard radius              75 : 0.989% / 90 : 3.708% / 95 : 18.348% / 99 : 45.836%
                                 scale_robust   radius               75 : 0.863% / 90 : 4.026% / 95 : 18.942% / 99 : 49.68%
                                 scale_power    radius              75 : 0.587% / 90 : 1.504% / 95 : 17.832% / 99 : 42.902%
                                 scale_quantile radius              75 : 0.894% / 90 : 3.757% / 95 : 17.965% / 99 : 42.809%
linear_regression PARSEC         Base           radius              75 : 42.447% / 90 : 55.4% / 95 : 64.969% / 99 : 75.729%

Results for the label category with a value of 2.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206
KNN               PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206
linear_regression PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206
mlp               PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206
random_forest     PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206
xgboost           PARSEC         Base           radius            0.0199466816788423 - 2.458486763798206
                                 scale_standard radius            0.0199466816788423 - 2.458486763798206
                                 scale_robust   radius            0.0199466816788423 - 2.458486763798206
                                 scale_power    radius            0.0199466816788423 - 2.458486763798206
                                 scale_quantile radius            0.0199466816788423 - 2.458486763798206

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.5645314183359549
                                 scale_standard radius            0.5649930074807838
                                 scale_robust   radius            0.5629713533272653
                                 scale_power    radius            0.5697500422865627
                                 scale_quantile radius            0.5652103012578242
KNN               PARSEC         Base           radius            0.7554229207106287
                                 scale_standard radius            0.7545975326040062
                                 scale_robust   radius            0.7551103124773941
                                 scale_power    radius            0.7631697789826564
                                 scale_quantile radius            0.7487329122622766
linear_regression PARSEC         Base           radius            0.5386038834226268
                                 scale_standard radius            0.5386038834226305
                                 scale_robust   radius            0.5386038834226299
                                 scale_power    radius            0.5862983211742124
                                 scale_quantile radius            0.4349192504541818
mlp               PARSEC         Base           radius            0.6582559034694251
                                 scale_standard radius            0.5242754082118648
                                 scale_robust   radius            0.5725493030852838
                                 scale_power    radius            0.6108724255890895
                                 scale_quantile radius             0.650494230368666
random_forest     PARSEC         Base           radius            0.7071019602387656
                                 scale_standard radius            0.7072693846664545
                                 scale_robust   radius            0.7070401483827822
                                 scale_power    radius             0.710842098161532
                                 scale_quantile radius            0.7080932101390345
xgboost           PARSEC         Base           radius            0.6440509775938494
                                 scale_standard radius            0.6440509775938494
                                 scale_robust   radius            0.6440509775938494
                                 scale_power    radius            0.6440509775938494
                                 scale_quantile radius            0.6408192851577292

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            15.505%
                                 scale_standard radius            15.493%
                                 scale_robust   radius            15.535%
                                 scale_power    radius            15.417%
                                 scale_quantile radius            15.493%
KNN               PARSEC         Base           radius            12.142%
                                 scale_standard radius            12.166%
                                 scale_robust   radius             12.15%
                                 scale_power    radius            12.209%
                                 scale_quantile radius            12.246%
linear_regression PARSEC         Base           radius            16.594%
                                 scale_standard radius            16.594%
                                 scale_robust   radius            16.594%
                                 scale_power    radius             17.88%
                                 scale_quantile radius            19.535%
mlp               PARSEC         Base           radius            19.573%
                                 scale_standard radius            18.192%
                                 scale_robust   radius            17.679%
                                 scale_power    radius            17.241%
                                 scale_quantile radius            19.046%
random_forest     PARSEC         Base           radius            12.965%
                                 scale_standard radius            12.958%
                                 scale_robust   radius            12.966%
                                 scale_power    radius            12.904%
                                 scale_quantile radius            12.941%
xgboost           PARSEC         Base           radius            17.119%
                                 scale_standard radius            17.119%
                                 scale_robust   radius            17.119%
                                 scale_power    radius            17.119%
                                 scale_quantile radius            17.032%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.216%
                                 scale_standard radius             6.208%
                                 scale_robust   radius              6.23%
                                 scale_power    radius             6.185%
                                 scale_quantile radius             6.215%
KNN               PARSEC         Base           radius             6.302%
                                 scale_standard radius             6.318%
                                 scale_robust   radius             6.302%
                                 scale_power    radius             6.431%
                                 scale_quantile radius             6.358%
linear_regression PARSEC         Base           radius            13.566%
                                 scale_standard radius            13.566%
                                 scale_robust   radius            13.566%
                                 scale_power    radius            15.654%
                                 scale_quantile radius            17.316%
mlp               PARSEC         Base           radius            16.707%
                                 scale_standard radius            14.544%
                                 scale_robust   radius            13.953%
                                 scale_power    radius            13.394%
                                 scale_quantile radius             15.63%
random_forest     PARSEC         Base           radius             5.935%
                                 scale_standard radius             5.927%
                                 scale_robust   radius              5.93%
                                 scale_power    radius             5.915%
                                 scale_quantile radius             5.929%
xgboost           PARSEC         Base           radius            13.802%
                                 scale_standard radius            13.802%
                                 scale_robust   radius            13.802%
                                 scale_power    radius            13.802%
                                 scale_quantile radius            13.721%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.237%
                                 scale_standard radius             1.237%
                                 scale_robust   radius             1.237%
                                 scale_power    radius             1.236%
                                 scale_quantile radius             1.237%
KNN               PARSEC         Base           radius             1.885%
                                 scale_standard radius             1.899%
                                 scale_robust   radius             1.899%
                                 scale_power    radius              2.05%
                                 scale_quantile radius             1.936%
linear_regression PARSEC         Base           radius            12.283%
                                 scale_standard radius            12.283%
                                 scale_robust   radius            12.283%
                                 scale_power    radius            15.756%
                                 scale_quantile radius            17.834%
mlp               PARSEC         Base           radius            16.947%
                                 scale_standard radius            12.217%
                                 scale_robust   radius            11.378%
                                 scale_power    radius            10.334%
                                 scale_quantile radius            14.627%
random_forest     PARSEC         Base           radius             1.397%
                                 scale_standard radius             1.392%
                                 scale_robust   radius             1.389%
                                 scale_power    radius             1.398%
                                 scale_quantile radius             1.394%
xgboost           PARSEC         Base           radius            12.013%
                                 scale_standard radius            12.013%
                                 scale_robust   radius            12.013%
                                 scale_power    radius            12.013%
                                 scale_quantile radius            11.907%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.7801787228457896
                                 scale_standard radius            0.7803794098221069
                                 scale_robust   radius            0.7792945737581626
                                 scale_power    radius            0.7825133738100766
                                 scale_quantile radius            0.7804537760618574
KNN               PARSEC         Base           radius             0.869666457596233
                                 scale_standard radius            0.8692172701561303
                                 scale_robust   radius            0.8694990364150721
                                 scale_power    radius             0.873986274124419
                                 scale_quantile radius            0.8659957678589498
linear_regression PARSEC         Base           radius            0.7362360964966685
                                 scale_standard radius            0.7362360964966709
                                 scale_robust   radius            0.7362360964966705
                                 scale_power    radius            0.8431423823546312
                                 scale_quantile radius            0.7719987385828924
mlp               PARSEC         Base           radius            0.8193237357637003
                                 scale_standard radius            0.7434310228191625
                                 scale_robust   radius            0.7728288551061108
                                 scale_power    radius            0.7885941246572536
                                 scale_quantile radius            0.8066236711021859
random_forest     PARSEC         Base           radius            0.8450590476514552
                                 scale_standard radius            0.8451413223751987
                                 scale_robust   radius            0.8450349595379226
                                 scale_power    radius            0.8469441458845031
                                 scale_quantile radius            0.8455906708143831
xgboost           PARSEC         Base           radius            0.8027978602985453
                                 scale_standard radius            0.8027978602985453
                                 scale_robust   radius            0.8027978602985453
                                 scale_power    radius            0.8027978602985453
                                 scale_quantile radius            0.8008519306535477

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            85.547%
                                 scale_standard radius            85.547%
                                 scale_robust   radius            85.547%
                                 scale_power    radius            85.547%
                                 scale_quantile radius            85.547%
KNN               PARSEC         Base           radius            81.326%
                                 scale_standard radius            81.326%
                                 scale_robust   radius            81.326%
                                 scale_power    radius            81.326%
                                 scale_quantile radius             79.86%
linear_regression PARSEC         Base           radius            63.302%
                                 scale_standard radius            63.302%
                                 scale_robust   radius            63.302%
                                 scale_power    radius            41.302%
                                 scale_quantile radius             43.57%
mlp               PARSEC         Base           radius            51.804%
                                 scale_standard radius             56.06%
                                 scale_robust   radius            53.533%
                                 scale_power    radius            52.543%
                                 scale_quantile radius            54.817%
random_forest     PARSEC         Base           radius            75.499%
                                 scale_standard radius             74.65%
                                 scale_robust   radius            75.276%
                                 scale_power    radius            73.962%
                                 scale_quantile radius            73.256%
xgboost           PARSEC         Base           radius             56.29%
                                 scale_standard radius             56.29%
                                 scale_robust   radius             56.29%
                                 scale_power    radius             56.29%
                                 scale_quantile radius            55.315%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 3.203% / 90 : 20.846% / 95 : 37.345% / 99 : 69.258%
                                 scale_standard radius             75 : 3.203% / 90 : 20.791% / 95 : 37.345% / 99 : 69.218%
                                 scale_robust   radius             75 : 3.203% / 90 : 20.894% / 95 : 37.813% / 99 : 69.263%
                                 scale_power    radius               75 : 3.2% / 90 : 20.714% / 95 : 36.262% / 99 : 69.093%
                                 scale_quantile radius             75 : 3.203% / 90 : 20.854% / 95 : 37.264% / 99 : 69.258%
KNN               PARSEC         Base           radius             75 : 5.415% / 90 : 22.334% / 95 : 29.021% / 99 : 46.562%
                                 scale_standard radius             75 : 5.395% / 90 : 22.351% / 95 : 29.088% / 99 : 46.879%
                                 scale_robust   radius             75 : 5.358% / 90 : 22.256% / 95 : 29.043% / 99 : 46.879%
                                 scale_power    radius               75 : 5.65% / 90 : 22.275% / 95 : 28.804% / 99 : 47.45%
                                 scale_quantile radius             75 : 5.418% / 90 : 22.255% / 95 : 29.008% / 99 : 47.905%
linear_regression PARSEC         Base           radius            75 : 19.241% / 90 : 25.372% / 95 : 30.608% / 99 : 45.066%
                                 scale_standard radius            75 : 19.241% / 90 : 25.372% / 95 : 30.608% / 99 : 45.066%
                                 scale_robust   radius            75 : 19.241% / 90 : 25.372% / 95 : 30.608% / 99 : 45.066%

Results for the label category with a value of 3.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003
KNN               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003
linear_regression PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003
mlp               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003
random_forest     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003
xgboost           PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 scale_standard radius            0.287801729930226 - 2.8372727025023003
                                 scale_robust   radius            0.287801729930226 - 2.8372727025023003
                                 scale_power    radius            0.287801729930226 - 2.8372727025023003
                                 scale_quantile radius            0.287801729930226 - 2.8372727025023003

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             -0.02946301764281367
                                 scale_standard radius            -0.031623553392722714
                                 scale_robust   radius            -0.031589700384734964
                                 scale_power    radius            -0.027397932441828532
                                 scale_quantile radius             -0.02911616191947064
KNN               PARSEC         Base           radius               0.2126456955697713
                                 scale_standard radius               0.2119780825072135
                                 scale_robust   radius               0.2125107538783968
                                 scale_power    radius               0.2132992700381212
                                 scale_quantile radius              0.21678793554238673
linear_regression PARSEC         Base           radius              0.40239652704002404
                                 scale_standard radius               0.4023965270400276
                                 scale_robust   radius               0.4023965270400267
                                 scale_power    radius               0.3159107747865375
                                 scale_quantile radius              0.14506856836084825
mlp               PARSEC         Base           radius               0.4143768132236899
                                 scale_standard radius               0.2506688895955046
                                 scale_robust   radius               0.2665522741664078
                                 scale_power    radius              0.32877256546881606
                                 scale_quantile radius               0.3349612293185126
random_forest     PARSEC         Base           radius              0.15865465480581487
                                 scale_standard radius              0.16021275073033647
                                 scale_robust   radius              0.15922043481968684
                                 scale_power    radius              0.16027210937312186
                                 scale_quantile radius              0.16267721596443907
xgboost           PARSEC         Base           radius              0.32815972103674085
                                 scale_standard radius              0.32815972103674085
                                 scale_robust   radius              0.32815972103674085
                                 scale_power    radius              0.32815972103674085
                                 scale_quantile radius               0.3263918244702879

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            19.234%
                                 scale_standard radius            19.255%
                                 scale_robust   radius            19.254%
                                 scale_power    radius            19.213%
                                 scale_quantile radius            19.235%
KNN               PARSEC         Base           radius            17.102%
                                 scale_standard radius            17.107%
                                 scale_robust   radius            17.101%
                                 scale_power    radius            17.064%
                                 scale_quantile radius            17.045%
linear_regression PARSEC         Base           radius            20.907%
                                 scale_standard radius            20.907%
                                 scale_robust   radius            20.907%
                                 scale_power    radius            19.115%
                                 scale_quantile radius            19.845%
mlp               PARSEC         Base           radius            17.362%
                                 scale_standard radius            18.045%
                                 scale_robust   radius            18.178%
                                 scale_power    radius            17.331%
                                 scale_quantile radius            17.295%
random_forest     PARSEC         Base           radius            17.495%
                                 scale_standard radius            17.478%
                                 scale_robust   radius            17.488%
                                 scale_power    radius            17.472%
                                 scale_quantile radius            17.456%
xgboost           PARSEC         Base           radius            17.317%
                                 scale_standard radius            17.317%
                                 scale_robust   radius            17.317%
                                 scale_power    radius            17.317%
                                 scale_quantile radius            17.312%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             9.233%
                                 scale_standard radius              9.24%
                                 scale_robust   radius             9.241%
                                 scale_power    radius             9.227%
                                 scale_quantile radius             9.232%
KNN               PARSEC         Base           radius             9.066%
                                 scale_standard radius             9.068%
                                 scale_robust   radius             9.064%
                                 scale_power    radius             9.053%
                                 scale_quantile radius             9.045%
linear_regression PARSEC         Base           radius            16.752%
                                 scale_standard radius            16.752%
                                 scale_robust   radius            16.752%
                                 scale_power    radius            14.324%
                                 scale_quantile radius            14.403%
mlp               PARSEC         Base           radius            12.541%
                                 scale_standard radius            12.546%
                                 scale_robust   radius            12.325%
                                 scale_power    radius             11.78%
                                 scale_quantile radius            12.163%
random_forest     PARSEC         Base           radius             8.848%
                                 scale_standard radius             8.844%
                                 scale_robust   radius             8.845%
                                 scale_power    radius             8.846%
                                 scale_quantile radius              8.84%
xgboost           PARSEC         Base           radius            11.671%
                                 scale_standard radius            11.671%
                                 scale_robust   radius            11.671%
                                 scale_power    radius            11.671%
                                 scale_quantile radius            11.636%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.303%
                                 scale_standard radius             1.303%
                                 scale_robust   radius             1.303%
                                 scale_power    radius             1.304%
                                 scale_quantile radius             1.303%
KNN               PARSEC         Base           radius             2.147%
                                 scale_standard radius             2.154%
                                 scale_robust   radius             2.152%
                                 scale_power    radius             2.135%
                                 scale_quantile radius             2.131%
linear_regression PARSEC         Base           radius            13.515%
                                 scale_standard radius            13.515%
                                 scale_robust   radius            13.515%
                                 scale_power    radius             9.129%
                                 scale_quantile radius              8.85%
mlp               PARSEC         Base           radius             7.655%
                                 scale_standard radius             8.178%
                                 scale_robust   radius             7.535%
                                 scale_power    radius              7.02%
                                 scale_quantile radius             7.832%
random_forest     PARSEC         Base           radius              1.52%
                                 scale_standard radius             1.523%
                                 scale_robust   radius             1.518%
                                 scale_power    radius             1.513%
                                 scale_quantile radius             1.519%
xgboost           PARSEC         Base           radius             7.069%
                                 scale_standard radius             7.069%
                                 scale_robust   radius             7.069%
                                 scale_power    radius             7.069%
                                 scale_quantile radius             6.994%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius               0.48432930509787
                                 scale_standard radius            0.48343747659056696
                                 scale_robust   radius            0.48359059061342613
                                 scale_power    radius            0.48483694929826304
                                 scale_quantile radius             0.4845316296372623
KNN               PARSEC         Base           radius             0.5586784851770883
                                 scale_standard radius             0.5578620615909367
                                 scale_robust   radius             0.5585891053469288
                                 scale_power    radius             0.5586302977738774
                                 scale_quantile radius             0.5604056714080995
linear_regression PARSEC         Base           radius             0.6386077306015067
                                 scale_standard radius             0.6386077306015095
                                 scale_robust   radius             0.6386077306015089
                                 scale_power    radius              0.585537451897772
                                 scale_quantile radius            0.38169769332144904
mlp               PARSEC         Base           radius              0.647683215963242
                                 scale_standard radius             0.5091438841795103
                                 scale_robust   radius             0.5240429843152197
                                 scale_power    radius             0.5735103320349993
                                 scale_quantile radius             0.5808105639156289
random_forest     PARSEC         Base           radius             0.5459579150223091
                                 scale_standard radius             0.5465028988829723
                                 scale_robust   radius             0.5462048614584301
                                 scale_power    radius             0.5464073763893909
                                 scale_quantile radius             0.5475726007682584
xgboost           PARSEC         Base           radius             0.5745391025849726
                                 scale_standard radius             0.5745391025849726
                                 scale_robust   radius             0.5745391025849726
                                 scale_power    radius             0.5745391025849726
                                 scale_quantile radius             0.5734161356441166

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            93.563%
                                 scale_standard radius            93.563%
                                 scale_robust   radius            93.563%
                                 scale_power    radius            93.563%
                                 scale_quantile radius            93.563%
KNN               PARSEC         Base           radius            90.891%
                                 scale_standard radius            90.891%
                                 scale_robust   radius            90.891%
                                 scale_power    radius            90.891%
                                 scale_quantile radius            90.887%
linear_regression PARSEC         Base           radius             55.83%
                                 scale_standard radius             55.83%
                                 scale_robust   radius             55.83%
                                 scale_power    radius            55.541%
                                 scale_quantile radius            63.586%
mlp               PARSEC         Base           radius            78.082%
                                 scale_standard radius            75.762%
                                 scale_robust   radius            83.943%
                                 scale_power    radius            87.557%
                                 scale_quantile radius            73.194%
random_forest     PARSEC         Base           radius            90.619%
                                 scale_standard radius             91.54%
                                 scale_robust   radius             91.39%
                                 scale_power    radius            90.805%
                                 scale_quantile radius            90.413%
xgboost           PARSEC         Base           radius            88.694%
                                 scale_standard radius            88.694%
                                 scale_robust   radius            88.694%
                                 scale_power    radius            88.694%
                                 scale_quantile radius            87.534%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 8.245% / 90 : 35.388% / 95 : 49.59% / 99 : 75.107%
                                 scale_standard radius              75 : 8.23% / 90 : 35.432% / 95 : 49.724% / 99 : 75.198%
                                 scale_robust   radius              75 : 8.239% / 90 : 35.454% / 95 : 49.67% / 99 : 75.309%
                                 scale_power    radius             75 : 8.248% / 90 : 35.314% / 95 : 49.537% / 99 : 75.083%
                                 scale_quantile radius             75 : 8.238% / 90 : 35.425% / 95 : 49.588% / 99 : 75.107%
KNN               PARSEC         Base           radius            75 : 11.783% / 90 : 30.047% / 95 : 40.878% / 99 : 72.464%
                                 scale_standard radius               75 : 11.8% / 90 : 30.05% / 95 : 40.792% / 99 : 72.188%
                                 scale_robust   radius             75 : 11.807% / 90 : 30.002% / 95 : 40.82% / 99 : 72.158%
                                 scale_power    radius            75 : 11.782% / 90 : 29.788% / 95 : 40.749% / 99 : 72.111%
                                 scale_quantile radius             75 : 11.759% / 90 : 29.92% / 95 : 40.621% / 99 : 72.016%
linear_regression PARSEC         Base           radius              75 : 24.914% / 90 : 35.64% / 95 : 42.59% / 99 : 48.337%
                                 scale_standard radius              75 : 24.914% / 90 : 35.64% / 95 : 42.59% / 99 : 48.337%

Results for the label category with a value of 4.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454
KNN               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454
linear_regression PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454
mlp               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454
random_forest     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454
xgboost           PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 scale_standard radius            0.7818989193511491 - 2.8272399995056454
                                 scale_robust   radius            0.7818989193511491 - 2.8272399995056454
                                 scale_power    radius            0.7818989193511491 - 2.8272399995056454
                                 scale_quantile radius            0.7818989193511491 - 2.8272399995056454

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.955620286412061
                                 scale_standard radius             0.9549633909408961
                                 scale_robust   radius             0.9550126676425285
                                 scale_power    radius             0.9552806516856959
                                 scale_quantile radius              0.955785489551203
KNN               PARSEC         Base           radius             0.9504855107562155
                                 scale_standard radius             0.9505150013919571
                                 scale_robust   radius             0.9507288248161286
                                 scale_power    radius             0.9512356138832756
                                 scale_quantile radius             0.9507153297464088
linear_regression PARSEC         Base           radius             0.7084371651989534
                                 scale_standard radius             0.7084371651989614
                                 scale_robust   radius               0.70843716519896
                                 scale_power    radius             0.7367880411142131
                                 scale_quantile radius            0.36578390517871806
mlp               PARSEC         Base           radius             0.8215956330914591
                                 scale_standard radius             0.8116747119453764
                                 scale_robust   radius             0.8379568670128494
                                 scale_power    radius             0.8597711268934293
                                 scale_quantile radius             0.7925635916314474
random_forest     PARSEC         Base           radius             0.9621702735006398
                                 scale_standard radius             0.9616574874791349
                                 scale_robust   radius             0.9615600394860867
                                 scale_power    radius             0.9616085145085055
                                 scale_quantile radius             0.9621530806179266
xgboost           PARSEC         Base           radius             0.9067948297537736
                                 scale_standard radius             0.9067948297537736
                                 scale_robust   radius             0.9067948297537736
                                 scale_power    radius             0.9067948297537736
                                 scale_quantile radius             0.9068894665213345

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius               3.1%
                                 scale_standard radius             3.123%
                                 scale_robust   radius             3.121%
                                 scale_power    radius             3.112%
                                 scale_quantile radius             3.095%
KNN               PARSEC         Base           radius             3.275%
                                 scale_standard radius             3.274%
                                 scale_robust   radius             3.267%
                                 scale_power    radius              3.25%
                                 scale_quantile radius             3.267%
linear_regression PARSEC         Base           radius            12.782%
                                 scale_standard radius            12.782%
                                 scale_robust   radius            12.782%
                                 scale_power    radius            11.178%
                                 scale_quantile radius            14.155%
mlp               PARSEC         Base           radius              8.08%
                                 scale_standard radius             6.645%
                                 scale_robust   radius             6.145%
                                 scale_power    radius             5.624%
                                 scale_quantile radius              6.76%
random_forest     PARSEC         Base           radius             2.863%
                                 scale_standard radius             2.882%
                                 scale_robust   radius             2.885%
                                 scale_power    radius             2.883%
                                 scale_quantile radius             2.863%
xgboost           PARSEC         Base           radius             4.872%
                                 scale_standard radius             4.872%
                                 scale_robust   radius             4.872%
                                 scale_power    radius             4.872%
                                 scale_quantile radius              4.87%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.056%
                                 scale_standard radius             1.057%
                                 scale_robust   radius             1.057%
                                 scale_power    radius             1.055%
                                 scale_quantile radius             1.055%
KNN               PARSEC         Base           radius             1.174%
                                 scale_standard radius             1.176%
                                 scale_robust   radius             1.172%
                                 scale_power    radius             1.158%
                                 scale_quantile radius             1.164%
linear_regression PARSEC         Base           radius            10.252%
                                 scale_standard radius            10.252%
                                 scale_robust   radius            10.252%
                                 scale_power    radius             8.483%
                                 scale_quantile radius            10.487%
mlp               PARSEC         Base           radius             5.709%
                                 scale_standard radius             4.154%
                                 scale_robust   radius              3.65%
                                 scale_power    radius             3.161%
                                 scale_quantile radius             4.802%
random_forest     PARSEC         Base           radius             1.051%
                                 scale_standard radius             1.055%
                                 scale_robust   radius             1.053%
                                 scale_power    radius             1.052%
                                 scale_quantile radius             1.052%
xgboost           PARSEC         Base           radius             2.612%
                                 scale_standard radius             2.612%
                                 scale_robust   radius             2.612%
                                 scale_power    radius             2.612%
                                 scale_quantile radius             2.613%

                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.216%
                                 scale_standard radius            0.216%
                                 scale_robust   radius            0.216%
                                 scale_power    radius            0.216%
                                 scale_quantile radius            0.216%
KNN               PARSEC         Base           radius            0.104%
                                 scale_standard radius            0.104%
                                 scale_robust   radius            0.104%
                                 scale_power    radius            0.103%
                                 scale_quantile radius            0.105%
linear_regression PARSEC         Base           radius            9.234%
                                 scale_standard radius            9.234%
                                 scale_robust   radius            9.234%
                                 scale_power    radius            7.548%
                                 scale_quantile radius            8.495%
mlp               PARSEC         Base           radius            3.921%
                                 scale_standard radius            2.439%
                                 scale_robust   radius            2.185%
                                 scale_power    radius            1.621%
                                 scale_quantile radius             3.44%
random_forest     PARSEC         Base           radius            0.222%
                                 scale_standard radius            0.223%
                                 scale_robust   radius            0.222%
                                 scale_power    radius            0.222%
                                 scale_quantile radius            0.223%
xgboost           PARSEC         Base           radius            1.129%
                                 scale_standard radius            1.129%
                                 scale_robust   radius            1.129%
                                 scale_power    radius            1.129%
                                 scale_quantile radius            1.119%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9776881908040265
                                 scale_standard radius            0.9773554788358731
                                 scale_robust   radius              0.97737833877758
                                 scale_power    radius            0.9775099680966546
                                 scale_quantile radius            0.9777746834262696
KNN               PARSEC         Base           radius            0.9751848834547058
                                 scale_standard radius            0.9752511244622727
                                 scale_robust   radius            0.9753489556594741
                                 scale_power    radius            0.9755978824514299
                                 scale_quantile radius            0.9753461370676502
linear_regression PARSEC         Base           radius            0.8876723080274312
                                 scale_standard radius            0.8876723080274366
                                 scale_robust   radius            0.8876723080274354
                                 scale_power    radius            0.9129925126911177
                                 scale_quantile radius            0.6302618020242079
mlp               PARSEC         Base           radius            0.9198956642376998
                                 scale_standard radius            0.9103235469051306
                                 scale_robust   radius            0.9353415383881637
                                 scale_power    radius            0.9507273947522632
                                 scale_quantile radius            0.8982782242437369
random_forest     PARSEC         Base           radius            0.9809328484849373
                                 scale_standard radius            0.9806713895150779
                                 scale_robust   radius            0.9806213410226131
                                 scale_power    radius            0.9806448759412214
                                 scale_quantile radius            0.9809217487585246
xgboost           PARSEC         Base           radius            0.9577760766716373
                                 scale_standard radius            0.9577760766716373
                                 scale_robust   radius            0.9577760766716373
                                 scale_power    radius            0.9577760766716373
                                 scale_quantile radius            0.9577586331526715

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            86.295%
                                 scale_standard radius            86.295%
                                 scale_robust   radius            86.295%
                                 scale_power    radius            86.295%
                                 scale_quantile radius            86.295%
KNN               PARSEC         Base           radius            85.591%
                                 scale_standard radius            85.227%
                                 scale_robust   radius            85.591%
                                 scale_power    radius            82.979%
                                 scale_quantile radius            85.591%
linear_regression PARSEC         Base           radius            46.998%
                                 scale_standard radius            46.998%
                                 scale_robust   radius            46.998%
                                 scale_power    radius            62.854%
                                 scale_quantile radius            72.708%
mlp               PARSEC         Base           radius            57.374%
                                 scale_standard radius            68.129%
                                 scale_robust   radius            59.157%
                                 scale_power    radius            45.446%
                                 scale_quantile radius            60.976%
random_forest     PARSEC         Base           radius            85.244%
                                 scale_standard radius            85.611%
                                 scale_robust   radius            86.224%
                                 scale_power    radius            85.721%
                                 scale_quantile radius            83.876%
xgboost           PARSEC         Base           radius            38.614%
                                 scale_standard radius            38.614%
                                 scale_robust   radius            38.614%
                                 scale_power    radius            38.614%
                                 scale_quantile radius            42.695%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius               75 : 1.035% / 90 : 2.497% / 95 : 4.261% / 99 : 12.017%
                                 scale_standard radius               75 : 1.035% / 90 : 2.496% / 95 : 4.258% / 99 : 12.021%
                                 scale_robust   radius               75 : 1.035% / 90 : 2.496% / 95 : 4.258% / 99 : 12.016%
                                 scale_power    radius                75 : 1.034% / 90 : 2.494% / 95 : 4.25% / 99 : 12.015%
                                 scale_quantile radius                75 : 1.035% / 90 : 2.496% / 95 : 4.266% / 99 : 12.01%
KNN               PARSEC         Base           radius                75 : 0.42% / 90 : 4.399% / 95 : 8.237% / 99 : 12.271%
                                 scale_standard radius               75 : 0.419% / 90 : 4.437% / 95 : 8.283% / 99 : 12.331%
                                 scale_robust   radius               75 : 0.423% / 90 : 4.455% / 95 : 8.213% / 99 : 12.248%
                                 scale_power    radius               75 : 0.416% / 90 : 4.331% / 95 : 8.211% / 99 : 12.208%
                                 scale_quantile radius               75 : 0.419% / 90 : 4.325% / 95 : 8.216% / 99 : 12.159%
linear_regression PARSEC         Base           radius            75 : 11.648% / 90 : 14.028% / 95 : 31.448% / 99 : 38.618%
                                 scale_standard radius            75 : 11.648% / 90 : 14.028% / 95 : 31.448% / 99 : 38.618%

Results for the label category with a value of 5.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504
KNN               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504
linear_regression PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504
mlp               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504
random_forest     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504
xgboost           PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 scale_standard radius            0.8787515201730021 - 2.669967369908504
                                 scale_robust   radius            0.8787515201730021 - 2.669967369908504
                                 scale_power    radius            0.8787515201730021 - 2.669967369908504
                                 scale_quantile radius            0.8787515201730021 - 2.669967369908504

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9761610949531048
                                 scale_standard radius             0.9762424646167946
                                 scale_robust   radius              0.976245405063336
                                 scale_power    radius             0.9755835791056006
                                 scale_quantile radius             0.9755756387205213
KNN               PARSEC         Base           radius             0.9810026567945801
                                 scale_standard radius             0.9806968214509031
                                 scale_robust   radius             0.9812268758639455
                                 scale_power    radius             0.9805314943993685
                                 scale_quantile radius             0.9817212761970521
linear_regression PARSEC         Base           radius             0.6936214748871703
                                 scale_standard radius             0.6936214748871714
                                 scale_robust   radius             0.6936214748871712
                                 scale_power    radius             0.5032497201307835
                                 scale_quantile radius            0.24772131390666474
mlp               PARSEC         Base           radius             0.7905570860440205
                                 scale_standard radius             0.8301644048726936
                                 scale_robust   radius             0.8411207960387785
                                 scale_power    radius             0.8453544284404589
                                 scale_quantile radius             0.8263986319279284
random_forest     PARSEC         Base           radius             0.9833215630488885
                                 scale_standard radius             0.9829332032382784
                                 scale_robust   radius             0.9828145126950631
                                 scale_power    radius             0.9828533814188873
                                 scale_quantile radius             0.9829280429631515
xgboost           PARSEC         Base           radius             0.8909704249855909
                                 scale_standard radius             0.8909704249855909
                                 scale_robust   radius             0.8909704249855909
                                 scale_power    radius             0.8909704249855909
                                 scale_quantile radius             0.8888130852425261

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             4.162%
                                 scale_standard radius             4.155%
                                 scale_robust   radius             4.155%
                                 scale_power    radius             4.212%
                                 scale_quantile radius             4.213%
KNN               PARSEC         Base           radius             3.728%
                                 scale_standard radius             3.763%
                                 scale_robust   radius             3.709%
                                 scale_power    radius             3.771%
                                 scale_quantile radius             3.654%
linear_regression PARSEC         Base           radius            23.028%
                                 scale_standard radius            23.028%
                                 scale_robust   radius            23.028%
                                 scale_power    radius            22.349%
                                 scale_quantile radius            27.524%
mlp               PARSEC         Base           radius            13.714%
                                 scale_standard radius            11.118%
                                 scale_robust   radius            10.918%
                                 scale_power    radius            10.801%
                                 scale_quantile radius            11.471%
random_forest     PARSEC         Base           radius             3.481%
                                 scale_standard radius             3.522%
                                 scale_robust   radius             3.534%
                                 scale_power    radius              3.53%
                                 scale_quantile radius             3.522%
xgboost           PARSEC         Base           radius              9.19%
                                 scale_standard radius              9.19%
                                 scale_robust   radius              9.19%
                                 scale_power    radius              9.19%
                                 scale_quantile radius             9.266%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.954%
                                 scale_standard radius              0.95%
                                 scale_robust   radius             0.953%
                                 scale_power    radius             0.958%
                                 scale_quantile radius              0.96%
KNN               PARSEC         Base           radius              1.44%
                                 scale_standard radius             1.445%
                                 scale_robust   radius              1.44%
                                 scale_power    radius             1.434%
                                 scale_quantile radius             1.401%
linear_regression PARSEC         Base           radius            20.173%
                                 scale_standard radius            20.173%
                                 scale_robust   radius            20.173%
                                 scale_power    radius            15.948%
                                 scale_quantile radius            20.579%
mlp               PARSEC         Base           radius            10.238%
                                 scale_standard radius             8.232%
                                 scale_robust   radius             7.829%
                                 scale_power    radius             7.907%
                                 scale_quantile radius             8.432%
random_forest     PARSEC         Base           radius             0.977%
                                 scale_standard radius              0.99%
                                 scale_robust   radius             0.989%
                                 scale_power    radius             0.984%
                                 scale_quantile radius             0.985%
xgboost           PARSEC         Base           radius             6.298%
                                 scale_standard radius             6.298%
                                 scale_robust   radius             6.298%
                                 scale_power    radius             6.298%
                                 scale_quantile radius             6.371%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.032%
                                 scale_standard radius             0.032%
                                 scale_robust   radius             0.032%
                                 scale_power    radius             0.032%
                                 scale_quantile radius             0.032%
KNN               PARSEC         Base           radius             0.106%
                                 scale_standard radius             0.107%
                                 scale_robust   radius             0.108%
                                 scale_power    radius             0.107%
                                 scale_quantile radius              0.12%
linear_regression PARSEC         Base           radius            19.101%
                                 scale_standard radius            19.101%
                                 scale_robust   radius            19.101%
                                 scale_power    radius             9.383%
                                 scale_quantile radius            13.455%
mlp               PARSEC         Base           radius             7.368%
                                 scale_standard radius             6.123%
                                 scale_robust   radius              4.88%
                                 scale_power    radius             5.236%
                                 scale_quantile radius             6.013%
random_forest     PARSEC         Base           radius             0.043%
                                 scale_standard radius             0.043%
                                 scale_robust   radius             0.043%
                                 scale_power    radius             0.043%
                                 scale_quantile radius             0.043%
xgboost           PARSEC         Base           radius               3.7%
                                 scale_standard radius               3.7%
                                 scale_robust   radius               3.7%
                                 scale_power    radius               3.7%
                                 scale_quantile radius             3.717%

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9881339932310456
                                 scale_standard radius            0.9881697845848246
                                 scale_robust   radius            0.9881736407416106
                                 scale_power    radius            0.9878421366369393
                                 scale_quantile radius            0.9878396120905139
KNN               PARSEC         Base           radius            0.9905459125164942
                                 scale_standard radius            0.9903821015269394
                                 scale_robust   radius            0.9906451978919714
                                 scale_power    radius            0.9902645883704929
                                 scale_quantile radius             0.990879323989931
linear_regression PARSEC         Base           radius            0.8405054746921199
                                 scale_standard radius            0.8405054746921201
                                 scale_robust   radius            0.8405054746921203
                                 scale_power    radius            0.8706264389243104
                                 scale_quantile radius            0.6594561574519051
mlp               PARSEC         Base           radius            0.9044015052723806
                                 scale_standard radius            0.9230710358791064
                                 scale_robust   radius             0.926553830299219
                                 scale_power    radius            0.9253051762410847
                                 scale_quantile radius            0.9125099582868028
random_forest     PARSEC         Base           radius            0.9916566947756928
                                 scale_standard radius            0.9914623985753106
                                 scale_robust   radius            0.9914031116731804
                                 scale_power    radius            0.9914217579236245
                                 scale_quantile radius             0.991459863809134
xgboost           PARSEC         Base           radius            0.9457856207944926
                                 scale_standard radius            0.9457856207944926
                                 scale_robust   radius            0.9457856207944926
                                 scale_power    radius            0.9457856207944926
                                 scale_quantile radius             0.944739562049732

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            84.065%
                                 scale_standard radius            84.065%
                                 scale_robust   radius            84.065%
                                 scale_power    radius            84.065%
                                 scale_quantile radius            84.065%
KNN               PARSEC         Base           radius            57.193%
                                 scale_standard radius            57.193%
                                 scale_robust   radius            57.193%
                                 scale_power    radius            57.193%
                                 scale_quantile radius            57.193%
linear_regression PARSEC         Base           radius            60.713%
                                 scale_standard radius            60.713%
                                 scale_robust   radius            60.713%
                                 scale_power    radius            63.749%
                                 scale_quantile radius            75.381%
mlp               PARSEC         Base           radius            59.852%
                                 scale_standard radius            57.474%
                                 scale_robust   radius            44.016%
                                 scale_power    radius            40.447%
                                 scale_quantile radius            45.219%
random_forest     PARSEC         Base           radius            56.794%
                                 scale_standard radius            56.032%
                                 scale_robust   radius            55.814%
                                 scale_power    radius            56.484%
                                 scale_quantile radius            56.229%
xgboost           PARSEC         Base           radius            55.377%
                                 scale_standard radius            55.377%
                                 scale_robust   radius            55.377%
                                 scale_power    radius            55.377%
                                 scale_quantile radius            55.507%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                 75 : 0.119% / 90 : 1.513% / 95 : 3.95% / 99 : 20.92%
                                 scale_standard radius                75 : 0.121% / 90 : 1.503% / 95 : 3.96% / 99 : 20.796%
                                 scale_robust   radius               75 : 0.121% / 90 : 1.498% / 95 : 3.925% / 99 : 20.822%
                                 scale_power    radius                75 : 0.12% / 90 : 1.496% / 95 : 3.921% / 99 : 21.093%
                                 scale_quantile radius                75 : 0.12% / 90 : 1.522% / 95 : 3.925% / 99 : 21.517%
KNN               PARSEC         Base           radius                75 : 1.43% / 90 : 3.726% / 95 : 6.455% / 99 : 17.981%
                                 scale_standard radius                75 : 1.431% / 90 : 3.705% / 95 : 6.483% / 99 : 18.03%
                                 scale_robust   radius                75 : 1.416% / 90 : 3.73% / 95 : 6.493% / 99 : 17.993%
                                 scale_power    radius               75 : 1.407% / 90 : 3.628% / 95 : 6.448% / 99 : 18.231%
                                 scale_quantile radius                75 : 1.421% / 90 : 3.593% / 95 : 6.128% / 99 : 17.43%
linear_regression PARSEC         Base           radius            75 : 29.536% / 90 : 35.615% / 95 : 37.963% / 99 : 42.275%
                                 scale_standard radius            75 : 29.536% / 90 : 35.615% / 95 : 37.963% / 99 : 42.275%

Results for the label category with a value of 6.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675
KNN               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675
linear_regression PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675
mlp               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675
random_forest     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675
xgboost           PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 scale_standard radius            0.9630791606418272 - 2.7777891874348675
                                 scale_robust   radius            0.9630791606418272 - 2.7777891874348675
                                 scale_power    radius            0.9630791606418272 - 2.7777891874348675
                                 scale_quantile radius            0.9630791606418272 - 2.7777891874348675

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9590838171586634
                                 scale_standard radius               0.95810974927928
                                 scale_robust   radius             0.9562158640486909
                                 scale_power    radius             0.9576536633640427
                                 scale_quantile radius              0.957988371835899
KNN               PARSEC         Base           radius             0.9629697658705128
                                 scale_standard radius             0.9649142707322438
                                 scale_robust   radius             0.9646359840717263
                                 scale_power    radius              0.964740479505958
                                 scale_quantile radius             0.9650623528488974
linear_regression PARSEC         Base           radius            -0.1780265156579326
                                 scale_standard radius            -0.1780265156579226
                                 scale_robust   radius            -0.1780265156579306
                                 scale_power    radius              0.387402232018752
                                 scale_quantile radius            0.11172113876600132
mlp               PARSEC         Base           radius             0.6180409605152396
                                 scale_standard radius             0.7065997391615801
                                 scale_robust   radius             0.6778744176587514
                                 scale_power    radius              0.634119491541755
                                 scale_quantile radius             0.5701287517005611
random_forest     PARSEC         Base           radius             0.9697670887087206
                                 scale_standard radius             0.9685329576923277
                                 scale_robust   radius             0.9691685489799873
                                 scale_power    radius             0.9686465917397759
                                 scale_quantile radius             0.9683971035506704
xgboost           PARSEC         Base           radius              0.769792515363512
                                 scale_standard radius              0.769792515363512
                                 scale_robust   radius              0.769792515363512
                                 scale_power    radius              0.769792515363512
                                 scale_quantile radius             0.7651011313125884

                                                                     RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             4.249%
                                 scale_standard radius             4.298%
                                 scale_robust   radius             4.395%
                                 scale_power    radius             4.321%
                                 scale_quantile radius             4.305%
KNN               PARSEC         Base           radius             4.043%
                                 scale_standard radius             3.939%
                                 scale_robust   radius             3.953%
                                 scale_power    radius             3.969%
                                 scale_quantile radius             3.927%
linear_regression PARSEC         Base           radius            28.786%
                                 scale_standard radius            28.786%
                                 scale_robust   radius            28.786%
                                 scale_power    radius            22.898%
                                 scale_quantile radius            27.979%
mlp               PARSEC         Base           radius             14.99%
                                 scale_standard radius            11.368%
                                 scale_robust   radius            11.971%
                                 scale_power    radius            12.786%
                                 scale_quantile radius            13.767%
random_forest     PARSEC         Base           radius             3.655%
                                 scale_standard radius             3.729%
                                 scale_robust   radius             3.691%
                                 scale_power    radius              3.72%
                                 scale_quantile radius             3.738%
xgboost           PARSEC         Base           radius            10.502%
                                 scale_standard radius            10.502%
                                 scale_robust   radius            10.502%
                                 scale_power    radius            10.502%
                                 scale_quantile radius            10.551%

                                                                      MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.255%
                                 scale_standard radius             1.256%
                                 scale_robust   radius             1.283%
                                 scale_power    radius             1.273%
                                 scale_quantile radius             1.266%
KNN               PARSEC         Base           radius             2.296%
                                 scale_standard radius             2.269%
                                 scale_robust   radius             2.282%
                                 scale_power    radius             2.335%
                                 scale_quantile radius             2.245%
linear_regression PARSEC         Base           radius            26.538%
                                 scale_standard radius            26.538%
                                 scale_robust   radius            26.538%
                                 scale_power    radius            17.127%
                                 scale_quantile radius            21.393%
mlp               PARSEC         Base           radius            12.345%
                                 scale_standard radius             9.219%
                                 scale_robust   radius             9.729%
                                 scale_power    radius            10.329%
                                 scale_quantile radius            11.083%
random_forest     PARSEC         Base           radius             1.212%
                                 scale_standard radius             1.215%
                                 scale_robust   radius              1.21%
                                 scale_power    radius             1.226%
                                 scale_quantile radius             1.221%
xgboost           PARSEC         Base           radius              8.26%
                                 scale_standard radius              8.26%
                                 scale_robust   radius              8.26%
                                 scale_power    radius              8.26%
                                 scale_quantile radius             8.266%

                                                                    MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.48%
                                 scale_standard radius             0.475%
                                 scale_robust   radius             0.479%
                                 scale_power    radius             0.478%
                                 scale_quantile radius             0.474%
KNN               PARSEC         Base           radius             1.441%
                                 scale_standard radius             1.443%
                                 scale_robust   radius             1.459%
                                 scale_power    radius             1.531%
                                 scale_quantile radius             1.393%
linear_regression PARSEC         Base           radius            26.238%
                                 scale_standard radius            26.238%
                                 scale_robust   radius            26.238%
                                 scale_power    radius            11.824%
                                 scale_quantile radius            16.019%
mlp               PARSEC         Base           radius            10.945%
                                 scale_standard radius             7.982%
                                 scale_robust   radius             8.245%
                                 scale_power    radius             8.799%
                                 scale_quantile radius              9.53%
random_forest     PARSEC         Base           radius             0.405%
                                 scale_standard radius              0.41%
                                 scale_robust   radius             0.411%
                                 scale_power    radius             0.415%
                                 scale_quantile radius             0.408%
xgboost           PARSEC         Base           radius              6.83%
                                 scale_standard radius              6.83%
                                 scale_robust   radius              6.83%
                                 scale_power    radius              6.83%
                                 scale_quantile radius             6.765%

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9796178563497766
                                 scale_standard radius             0.9791217496490405
                                 scale_robust   radius             0.9781828166511071
                                 scale_power    radius             0.9788779965468669
                                 scale_quantile radius             0.9790731297291823
KNN               PARSEC         Base           radius             0.9813761923561958
                                 scale_standard radius             0.9824032307874441
                                 scale_robust   radius             0.9822499484694122
                                 scale_power    radius             0.9822690299798329
                                 scale_quantile radius             0.9824444186385364
linear_regression PARSEC         Base           radius             0.5867748937794232
                                 scale_standard radius             0.5867748937794255
                                 scale_robust   radius             0.5867748937794242
                                 scale_power    radius             0.6584052608392225
                                 scale_quantile radius            0.34054636601124916
mlp               PARSEC         Base           radius             0.7909518021844507
                                 scale_standard radius             0.8407329459811361
                                 scale_robust   radius              0.824534658097215
                                 scale_power    radius             0.8010220572081199
                                 scale_quantile radius             0.7674276368341325
random_forest     PARSEC         Base           radius             0.9848075867184325
                                 scale_standard radius             0.9841817452639738
                                 scale_robust   radius             0.9845047742255337
                                 scale_power    radius             0.9842375832890513
                                 scale_quantile radius             0.9841127357992805
xgboost           PARSEC         Base           radius             0.8782788575526104
                                 scale_standard radius             0.8782788575526104
                                 scale_robust   radius             0.8782788575526104
                                 scale_power    radius             0.8782788575526104
                                 scale_quantile radius             0.8756458276813881

                                                                   MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            84.501%
                                 scale_standard radius             83.29%
                                 scale_robust   radius            84.501%
                                 scale_power    radius             83.29%
                                 scale_quantile radius            84.501%
KNN               PARSEC         Base           radius            60.023%
                                 scale_standard radius            60.023%
                                 scale_robust   radius             60.95%
                                 scale_power    radius            60.023%
                                 scale_quantile radius            62.282%
linear_regression PARSEC         Base           radius            59.289%
                                 scale_standard radius            59.289%
                                 scale_robust   radius            59.289%
                                 scale_power    radius            68.997%
                                 scale_quantile radius            80.155%
mlp               PARSEC         Base           radius            51.848%
                                 scale_standard radius            34.728%
                                 scale_robust   radius            37.628%
                                 scale_power    radius            37.899%
                                 scale_quantile radius            50.725%
random_forest     PARSEC         Base           radius            61.225%
                                 scale_standard radius            61.698%
                                 scale_robust   radius            61.719%
                                 scale_power    radius             61.38%
                                 scale_quantile radius            61.819%
xgboost           PARSEC         Base           radius            42.195%
                                 scale_standard radius            42.195%
                                 scale_robust   radius            42.195%
                                 scale_power    radius            42.195%
                                 scale_quantile radius            49.277%

                                                                                                                Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                75 : 1.19% / 90 : 2.196% / 95 : 3.578% / 99 : 18.255%
                                 scale_standard radius               75 : 1.184% / 90 : 2.179% / 95 : 3.595% / 99 : 17.819%
                                 scale_robust   radius               75 : 1.188% / 90 : 2.181% / 95 : 3.639% / 99 : 19.849%
                                 scale_power    radius               75 : 1.201% / 90 : 2.226% / 95 : 3.623% / 99 : 19.062%
                                 scale_quantile radius               75 : 1.183% / 90 : 2.179% / 95 : 3.572% / 99 : 19.654%
KNN               PARSEC         Base           radius               75 : 2.736% / 90 : 4.613% / 95 : 6.747% / 99 : 16.711%
                                 scale_standard radius                75 : 2.75% / 90 : 4.591% / 95 : 6.563% / 99 : 16.244%
                                 scale_robust   radius               75 : 2.758% / 90 : 4.595% / 95 : 6.647% / 99 : 16.181%
                                 scale_power    radius               75 : 2.847% / 90 : 4.718% / 95 : 6.619% / 99 : 16.244%
                                 scale_quantile radius               75 : 2.732% / 90 : 4.607% / 95 : 6.627% / 99 : 16.106%
linear_regression PARSEC         Base           radius            75 : 35.159% / 90 : 40.872% / 95 : 44.068% / 99 : 50.194%
                                 scale_standard radius            75 : 35.159% / 90 : 40.872% / 95 : 44.068% / 99 : 50.194%

les résultats avec du scaling sont très proche de Base, il n'y a pas d'intérêt à utilise le scaling pour ce modèle

## Base vs Base_old

| Parameter      | Base                                                   | Base_old                                               |
| -------------  | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       | Range : 5.3 - 10.25, Mean : 9.1668, Median : 9.4       |
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   | Range : 0.09 - 13.952, Mean : 2.3888, Median : 1.345   |
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   | Range : 3.36 - 4.5177, Mean : 3.7418, Median : 3.7133  |
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   | Range : -0.66 - 5.345, Mean : 2.4609, Median : 2.429   |
| log_R          | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 | Range : -0.98 - 2.9727, Mean : 1.0977, Median : 1.0445 |

In [13]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.3621 - 4.5177
                                      log_g                 -0.664 - 5.345
                                      radius            -0.97634 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94001  0.03862
                                      log_g             0.80188  0.46515
                                      radius            0.84875  0.23276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01473  0.00327
                                      log_g             0.18745  0.03707
                                      radius            0.09385  0.01859

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.96959  0.82994
                                      log_g             0.89625  4.56946
                                      radius            0.92171  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.01297 / 90 : 0.03519 / 95 : 0.07492 / 99 : 0.15743
                                      log_g              75 : 0.14956 / 90 : 0.45314 / 95 : 1.08289 / 99 : 2.16149
                                      radius             75 : 0.07486 / 90 : 0.22674 / 95 : 0.54149 / 99 : 1.08185

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.3621 - 4.5177
                                      log_g                  3.241 - 5.345
                                      radius            -0.97634 - 1.16524

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.97353  0.04386
                                      log_g            -0.13311  0.37086
                                      radius            0.75594  0.18566

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.00886  0.00019
                                      log_g             0.08488  0.00096
                                      radius            0.04266  0.00056

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.98692  0.78713
                                      log_g             0.74219  4.42400
                                      radius            0.90123  2.21647

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.00248 / 90 : 0.01189 / 95 : 0.03921 / 99 : 0.15878
                                      log_g               75 : 0.00719 / 90 : 0.05995 / 95 : 0.43503 / 99 : 2.0369
                                      radius             75 : 0.00417 / 90 : 0.03049 / 95 : 0.21772 / 99 : 1.01901

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 2.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                 3.602 - 4.446
                                      log_g                 0.638 - 4.283
                                      radius            0.01995 - 2.45849

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.89274  0.05766
                                      log_g             0.44545  0.64549
                                      radius            0.69784  0.32276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.03358  0.01668
                                      log_g             0.30077  0.06876
                                      radius            0.15043  0.03445

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.95186  0.76853
                                      log_g             0.72854  3.87044
                                      radius            0.83972  1.93497

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.04114 / 90 : 0.08721 / 95 : 0.12506 / 99 : 0.20918
                                      log_g              75 : 0.20417 / 90 : 1.09676 / 95 : 1.69667 / 99 : 2.63871
                                      radius              75 : 0.10188 / 90 : 0.54834 / 95 : 0.84849 / 99 : 1.3189

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 3.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff            -0.49173  0.05765
                                      log_g            -0.15647  0.88771
                                      radius            0.16704  0.44391

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.02682  0.00537
                                      log_g             0.45942  0.08292
                                      radius            0.22974  0.04154

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.17087  0.82994
                                      log_g             0.30896  4.56946
                                      radius            0.54703  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.02652 / 90 : 0.08725 / 95 : 0.12803 / 99 : 0.21171
                                      log_g              75 : 0.53918 / 90 : 1.61797 / 95 : 2.17152 / 99 : 3.53068
                                      radius               75 : 0.2701 / 90 : 0.80932 / 95 : 1.0859 / 99 : 1.76536

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 4.0

                                                           value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             3.5301 - 3.786
                                      log_g             -0.122 - 2.979
                                      radius            0.7819 - 2.832

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.62291  0.01905
                                      log_g             0.87922  0.14520
                                      radius            0.94651  0.07263

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.00587  0.00167
                                      log_g             0.07179  0.02536
                                      radius            0.03594  0.01275

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.82182  0.82261
                                      log_g             0.93934  3.47101
                                      radius            0.97290  1.73608

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.00674 / 90 : 0.01467 / 95 : 0.02069 / 99 : 0.04566
                                      log_g              75 : 0.09598 / 90 : 0.19284 / 95 : 0.27143 / 99 : 0.54299
                                      radius             75 : 0.04805 / 90 : 0.09664 / 95 : 0.13622 / 99 : 0.27081

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.5644 - 4.272
                                      log_g                 0.206 - 2.963
                                      radius            0.87875 - 2.66699

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.88479  0.03892
                                      log_g             0.89409  0.24161
                                      radius            0.94160  0.11889

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01249  0.00060
                                      log_g             0.07722  0.00207
                                      radius            0.03706  0.00105

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94302  0.53028
                                      log_g             0.94879  2.36347
                                      radius            0.97122  1.18061

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               75 : 0.00692 / 90 : 0.03075 / 95 : 0.06821 / 99 : 0.1944
                                      log_g               75 : 0.0347 / 90 : 0.18247 / 95 : 0.44613 / 99 : 1.26442
                                      radius             75 : 0.01622 / 90 : 0.08491 / 95 : 0.20976 / 99 : 0.63122

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 6.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               3.5437 - 4.2601
                                      log_g                -0.019 - 2.869
                                      radius            0.94052 - 2.77967

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.88415  0.05357
                                      log_g             0.52971  0.42553
                                      radius            0.71494  0.21300

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.02094  0.00370
                                      log_g             0.16158  0.01940
                                      radius            0.08069  0.00953

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94640  0.50684
                                      log_g             0.80283  2.36551
                                      radius            0.86588  1.17960

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               75 : 0.01251 / 90 : 0.0605 / 95 : 0.12239 / 99 : 0.24719
                                      log_g               75 : 0.07115 / 90 : 0.49024 / 95 : 1.12512 / 99 : 1.9852
                                      radius             75 : 0.03539 / 90 : 0.24311 / 95 : 0.56037 / 99 : 0.99745

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 7.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               3.4527 - 4.0581
                                      log_g                -0.664 - 2.879
                                      radius            0.78732 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.65780  0.03328
                                      log_g             0.70477  0.43448
                                      radius            0.80831  0.21778

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01583  0.00563
                                      log_g             0.21753  0.07651
                                      radius            0.10915  0.03865

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.81224  0.65706
                                      log_g             0.83957  4.53161
                                      radius            0.89907  2.27642

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.01721 / 90 : 0.03676 / 95 : 0.07856 / 99 : 0.13199
                                      log_g                75 : 0.2363 / 90 : 0.5294 / 95 : 1.12638 / 99 : 1.82932
                                      radius             75 : 0.11868 / 90 : 0.26535 / 95 : 0.56384 / 99 : 0.91586

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

In [14]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.3621 - 4.5177
                                      log_g                 -0.384 - 5.345
                                      radius            -0.97634 - 2.83727
                             Base_old T_eff                3.3621 - 4.5177
                                      log_g                 -0.664 - 5.345
                                      radius            -0.97634 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95666  0.03783
                                      log_g             0.80743  0.45892
                                      radius            0.85842  0.22942
                             Base_old T_eff             0.94001  0.03862
                                      log_g             0.80188  0.46515
                                      radius            0.84875  0.23276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01220  0.00150
                                      log_g             0.14624  0.01272
                                      radius            0.07307  0.00644
                             Base_old T_eff             0.01473  0.00327
                                      log_g             0.18745  0.03707
                                      radius            0.09385  0.01859

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.97812  0.82900
                                      log_g             0.89985  4.62086
                                      radius            0.92717  2.31030
                             Base_old T_eff             0.96959  0.82994
                                      log_g             0.89625  4.56946
                                      radius            0.92171  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                      log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                      radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
                             Base_old T_eff              75 : 0.01297 / 90 : 0.03519 / 95 : 0.07492 / 99 : 0.15743
                                      log_g              75 : 0.14956 / 90 : 0.45314 / 95 : 1.08289 / 99 : 2.16149
                                      radius             75 : 0.07486 / 90 : 0.22674 / 95 : 0.54149 / 99 : 1.08185

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.3621 - 4.5177
                                      log_g                  3.233 - 5.345
                                      radius            -0.97634 - 1.16879
                             Base_old T_eff                3.3621 - 4.5177
                                      log_g                  3.241 - 5.345
                                      radius            -0.97634 - 1.16524

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.98266  0.03535
                                      log_g             0.17211  0.31599
                                      radius            0.82160  0.15816
                             Base_old T_eff             0.97353  0.04386
                                      log_g            -0.13311  0.37086
                                      radius            0.75594  0.18566

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00734  0.00019
                                      log_g             0.07026  0.00098
                                      radius            0.03533  0.00057
                             Base_old T_eff             0.00886  0.00019
                                      log_g             0.08488  0.00096
                                      radius            0.04266  0.00056

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.99140  0.76950
                                      log_g             0.77598  4.22632
                                      radius            0.92280  2.11281
                             Base_old T_eff             0.98692  0.78713
                                      log_g             0.74219  4.42400
                                      radius            0.90123  2.21647

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                      log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                      radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
                             Base_old T_eff              75 : 0.00248 / 90 : 0.01189 / 95 : 0.03921 / 99 : 0.15878
                                      log_g               75 : 0.00719 / 90 : 0.05995 / 95 : 0.43503 / 99 : 2.0369
                                      radius             75 : 0.00417 / 90 : 0.03049 / 95 : 0.21772 / 99 : 1.01901

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 2.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.6053 - 4.446
                                      log_g                 0.638 - 4.299
                                      radius            0.01995 - 2.45849
                             Base_old T_eff                 3.602 - 4.446
                                      log_g                 0.638 - 4.283
                                      radius            0.01995 - 2.45849

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.89976  0.05591
                                      log_g             0.46261  0.63227
                                      radius            0.70710  0.31615
                             Base_old T_eff             0.89274  0.05766
                                      log_g             0.44545  0.64549
                                      radius            0.69784  0.32276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.03253  0.01636
                                      log_g             0.28937  0.06806
                                      radius            0.14474  0.03407
                             Base_old T_eff             0.03358  0.01668
                                      log_g             0.30077  0.06876
                                      radius            0.15043  0.03445

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95495  0.76590
                                      log_g             0.73743  3.68299
                                      radius            0.84506  1.84107
                             Base_old T_eff             0.95186  0.76853
                                      log_g             0.72854  3.87044
                                      radius            0.83972  1.93497

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                      log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                      radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
                             Base_old T_eff              75 : 0.04114 / 90 : 0.08721 / 95 : 0.12506 / 99 : 0.20918
                                      log_g              75 : 0.20417 / 90 : 1.09676 / 95 : 1.69667 / 99 : 2.63871
                                      radius              75 : 0.10188 / 90 : 0.54834 / 95 : 0.84849 / 99 : 1.3189

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 3.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727
                             Base_old T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff            -0.50233  0.05758
                                      log_g            -0.17212  0.89197
                                      radius            0.15865  0.44602
                             Base_old T_eff            -0.49173  0.05765
                                      log_g            -0.15647  0.88771
                                      radius            0.16704  0.44391

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.02619  0.00468
                                      log_g             0.45108  0.07740
                                      radius            0.22559  0.03876
                             Base_old T_eff             0.02682  0.00537
                                      log_g             0.45942  0.08292
                                      radius            0.22974  0.04154

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.16706  0.80651
                                      log_g             0.30682  4.62086
                                      radius            0.54596  2.31030
                             Base_old T_eff             0.17087  0.82994
                                      log_g             0.30896  4.56946
                                      radius            0.54703  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                      log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                      radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
                             Base_old T_eff              75 : 0.02652 / 90 : 0.08725 / 95 : 0.12803 / 99 : 0.21171
                                      log_g              75 : 0.53918 / 90 : 1.61797 / 95 : 2.17152 / 99 : 3.53068
                                      radius               75 : 0.2701 / 90 : 0.80932 / 95 : 1.0859 / 99 : 1.76536

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 4.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               3.5328 - 3.786
                                      log_g               -0.102 - 2.978
                                      radius            0.7819 - 2.82724
                             Base_old T_eff               3.5301 - 3.786
                                      log_g               -0.122 - 2.979
                                      radius              0.7819 - 2.832

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.65912  0.01792
                                      log_g             0.91454  0.11709
                                      radius            0.96217  0.05855
                             Base_old T_eff             0.62291  0.01905
                                      log_g             0.87922  0.14520
                                      radius            0.94651  0.07263

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00390  0.00079
                                      log_g             0.04294  0.00904
                                      radius            0.02149  0.00453
                             Base_old T_eff             0.00587  0.00167
                                      log_g             0.07179  0.02536
                                      radius            0.03594  0.01275

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.83613  0.82900
                                      log_g             0.95670  3.48559
                                      radius            0.98093  1.74352
                             Base_old T_eff             0.82182  0.82261
                                      log_g             0.93934  3.47101
                                      radius            0.97290  1.73608

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                      log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                      radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
                             Base_old T_eff              75 : 0.00674 / 90 : 0.01467 / 95 : 0.02069 / 99 : 0.04566
                                      log_g              75 : 0.09598 / 90 : 0.19284 / 95 : 0.27143 / 99 : 0.54299
                                      radius             75 : 0.04805 / 90 : 0.09664 / 95 : 0.13622 / 99 : 0.27081

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.5642 - 4.272
                                      log_g                   0.2 - 2.963
                                      radius            0.87875 - 2.66997
                             Base_old T_eff                3.5644 - 4.272
                                      log_g                 0.206 - 2.963
                                      radius            0.87875 - 2.66699

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.90791  0.03474
                                      log_g             0.96665  0.13291
                                      radius            0.98332  0.06236
                             Base_old T_eff             0.88479  0.03892
                                      log_g             0.89409  0.24161
                                      radius            0.94160  0.11889

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00953  0.00044
                                      log_g             0.03826  0.00149
                                      radius            0.01750  0.00077
                             Base_old T_eff             0.01249  0.00060
                                      log_g             0.07722  0.00207
                                      radius            0.03706  0.00105

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95348  0.50261
                                      log_g             0.98331  2.00068
                                      radius            0.99166  1.01731
                             Base_old T_eff             0.94302  0.53028
                                      log_g             0.94879  2.36347
                                      radius            0.97122  1.18061

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                      log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                      radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
                             Base_old T_eff               75 : 0.00692 / 90 : 0.03075 / 95 : 0.06821 / 99 : 0.1944
                                      log_g               75 : 0.0347 / 90 : 0.18247 / 95 : 0.44613 / 99 : 1.26442
                                      radius             75 : 0.01622 / 90 : 0.08491 / 95 : 0.20976 / 99 : 0.63122

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 6.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               3.5416 - 4.2601
                                      log_g                -0.017 - 2.837
                                      radius            0.96308 - 2.77779
                             Base_old T_eff               3.5437 - 4.2601
                                      log_g                -0.019 - 2.869
                                      radius            0.94052 - 2.77967

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95163  0.03379
                                      log_g             0.94854  0.13499
                                      radius            0.96977  0.06633
                             Base_old T_eff             0.88415  0.05357
                                      log_g             0.52971  0.42553
                                      radius            0.71494  0.21300

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01059  0.00312
                                      log_g             0.04500  0.01502
                                      radius            0.02199  0.00736
                             Base_old T_eff             0.02094  0.00370
                                      log_g             0.16158  0.01940
                                      radius            0.08069  0.00953

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.97565  0.54917
                                      log_g             0.97410  2.15254
                                      radius            0.98481  1.11106
                             Base_old T_eff             0.94640  0.50684
                                      log_g             0.80283  2.36551
                                      radius            0.86588  1.17960

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                      log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                      radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
                             Base_old T_eff               75 : 0.01251 / 90 : 0.0605 / 95 : 0.12239 / 99 : 0.24719
                                      log_g               75 : 0.07115 / 90 : 0.49024 / 95 : 1.12512 / 99 : 1.9852
                                      radius             75 : 0.03539 / 90 : 0.24311 / 95 : 0.56037 / 99 : 0.99745

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

In [15]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.3621 - 4.5177
                                      log_g                                       -0.384 - 5.345
                                      radius            -0.9763360818022064 - 2.8372727025023003
                             Base_old T_eff                                      3.3621 - 4.5177
                                      log_g                                       -0.664 - 5.345
                                      radius            -0.9763360818022064 - 2.9727118405470665

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9566608469406531
                                      log_g             0.8074266704690882
                                      radius            0.8584173604243724
                             Base_old T_eff             0.9400055838628675
                                      log_g             0.8018764240434271
                                      radius            0.8487511273210078

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             3.27404%  1.05542%
                                      log_g             8.01056%  2.55264%
                                      radius            6.01582%  1.91598%
                             Base_old T_eff             3.34222%  1.27496%
                                      log_g             7.74092%  3.11946%
                                      radius            5.89414%  2.37645%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.12987%
                                      log_g             0.22197%
                                      radius            0.16887%
                             Base_old T_eff             0.28275%
                                      log_g             0.61688%
                                      radius             0.4707%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9781241008271904
                                      log_g             0.8998465625312148
                                      radius            0.9271725495364581
                             Base_old T_eff               0.96959438256482
                                      log_g             0.8962498071639723
                                      radius            0.9217125416456452

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              71.7375%
                                      log_g             80.65743%
                                      radius            60.58031%
                             Base_old T_eff             71.81869%
                                      log_g             76.04366%
                                      radius            57.86477%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.62651% / 90 : 2.51731% / 95 : 5.59363% / 99 : 14.74213%
                                      log_g             75 : 1.13458% / 90 : 4.92756% / 95 : 15.90993% / 99 : 41.45104%
                                      radius            75 : 0.85011% / 90 : 3.68601% / 95 : 11.93856% / 99 : 31.13822%
                             Base_old T_eff              75 : 1.12236% / 90 : 3.04517% / 95 : 6.48321% / 99 : 13.62323%
                                      log_g             75 : 2.48893% / 90 : 7.54102% / 95 : 18.02113% / 99 : 35.97088%
                                      radius            75 : 1.89565% / 90 : 5.74164% / 95 : 13.71191% / 99 : 27.39521%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 1.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.3621 - 4.5177
                                      log_g                                        3.233 - 5.345
                                      radius            -0.9763360818022064 - 1.1687920203141815
                             Base_old T_eff                                      3.3621 - 4.5177
                                      log_g                                        3.241 - 5.345
                                      radius             -0.9763360818022064 - 1.165244326125311

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                0.982663800306455
                                      log_g              0.17211468827279353
                                      radius               0.821604552614865
                             Base_old T_eff                0.973528897128316
                                      log_g             -0.13310881348647374
                                      radius               0.755936919156293

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              3.05914%   0.6353%
                                      log_g             14.96154%  3.32668%
                                      radius             7.37316%  1.64715%
                             Base_old T_eff              3.79505%  0.76704%
                                      log_g             17.62646%  4.03418%
                                      radius             8.66933%  1.99187%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01661%
                                      log_g              0.0464%
                                      radius            0.02638%
                             Base_old T_eff             0.01683%
                                      log_g             0.04563%
                                      radius            0.02623%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9914002808313593
                                      log_g             0.7759789538352955
                                      radius            0.9227998598367169
                             Base_old T_eff             0.9869182882562207
                                      log_g             0.7421949820009498
                                      radius            0.9012337185646798

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              66.58844%
                                      log_g             200.10967%
                                      radius             98.49346%
                             Base_old T_eff              68.11462%
                                      log_g             210.26613%
                                      radius            103.49706%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.20336% / 90 : 0.93977% / 95 : 2.65317% / 99 : 11.18813%
                                      log_g             75 : 0.32244% / 90 : 2.31913% / 95 : 15.31534% / 99 : 83.69934%
                                      radius             75 : 0.18554% / 90 : 1.16543% / 95 : 7.53521% / 99 : 41.25068%
                             Base_old T_eff               75 : 0.21461% / 90 : 1.0289% / 95 : 3.39304% / 99 : 13.74005%
                                      log_g             75 : 0.34173% / 90 : 2.84933% / 95 : 20.67633% / 99 : 96.81084%
                                      radius            75 : 0.19472% / 90 : 1.42371% / 95 : 10.16632% / 99 : 47.58215%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 2.0

                                                                                   value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                     3.6053 - 4.446
                                      log_g                                      0.638 - 4.299
                                      radius            0.0199466816788423 - 2.458486763798206
                             Base_old T_eff                                      3.602 - 4.446
                                      log_g                                      0.638 - 4.283
                                      radius            0.0199466816788423 - 2.458486763798206

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.8997608573485408
                                      log_g             0.4626143591760997
                                      radius            0.7071019602387656
                             Base_old T_eff             0.8927407703700583
                                      log_g             0.4454468449443749
                                      radius            0.6978393346553258

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              6.65051%  3.86929%
                                      log_g              17.2705%  7.90419%
                                      radius            12.96467%  5.93547%
                             Base_old T_eff              6.83203%  3.97892%
                                      log_g             17.70896%  8.25146%
                                      radius            13.23582%  6.16892%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             1.94655%
                                      log_g             1.85908%
                                      radius            1.39712%
                             Base_old T_eff             1.97679%
                                      log_g             1.88632%
                                      radius            1.41275%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9549507593925414
                                      log_g              0.737427211287738
                                      radius            0.8450590476514552
                             Base_old T_eff             0.9518559539733927
                                      log_g             0.7285415603671077
                                      radius            0.8397198459667251

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               91.1031%
                                      log_g             100.60066%
                                      radius               75.499%
                             Base_old T_eff              91.05832%
                                      log_g             106.18491%
                                      radius             79.34946%

                                                                                                             Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 4.69252% / 90 : 9.98454% / 95 : 14.49506% / 99 : 23.70881%
                                      log_g              75 : 5.3103% / 90 : 27.99372% / 95 : 45.70773% / 99 : 72.12101%
                                      radius            75 : 3.98763% / 90 : 21.01011% / 95 : 34.30987% / 99 : 54.14797%
                             Base_old T_eff             75 : 4.87441% / 90 : 10.33294% / 95 : 14.81754% / 99 : 24.78436%
                                      log_g             75 : 5.60137% / 90 : 30.08944% / 95 : 46.54787% / 99 : 72.39259%
                                      radius              75 : 4.17791% / 90 : 22.48641% / 95 : 34.795% / 99 : 54.08564%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 3.0

                                                                                   value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                    3.4342 - 3.7459
                                      log_g                                     -0.384 - 3.823
                                      radius            0.287801729930226 - 2.8372727025023003
                             Base_old T_eff                                    3.4342 - 3.7459
                                      log_g                                     -0.384 - 3.823
                                      radius            0.287801729930226 - 2.8372727025023003

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              -0.5023320130390359
                                      log_g             -0.17211974773342287
                                      radius             0.15865465480581487
                             Base_old T_eff              -0.4917289111288492
                                      log_g             -0.15646503726293726
                                      radius              0.1670434959764765

                                                             RMSE        MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             18.47271%   8.40197%
                                      log_g             21.20201%  10.72202%
                                      radius            17.49471%   8.84842%
                             Base_old T_eff             18.49658%   8.60292%
                                      log_g             21.10084%  10.92031%
                                      radius            17.41182%   9.01137%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             1.50034%
                                      log_g             1.83977%
                                      radius            1.52046%
                             Base_old T_eff             1.72423%
                                      log_g             1.97093%
                                      radius            1.62947%

                                                                       CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              0.1670618613045383
                                      log_g             0.30681622944559384
                                      radius             0.5459579150223091
                             Base_old T_eff             0.17087474457579632
                                      log_g             0.30896325426816623
                                      radius              0.547026492319328

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             258.74655%
                                      log_g             109.83751%
                                      radius             90.61865%
                             Base_old T_eff             266.26139%
                                      log_g             108.61573%
                                      radius             89.63066%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 7.94033% / 90 : 27.38851% / 95 : 41.81585% / 99 : 68.2804%
                                      log_g             75 : 11.76444% / 90 : 38.38769% / 95 : 52.85477% / 99 : 84.77561%
                                      radius              75 : 9.72515% / 90 : 31.67245% / 95 : 43.60591% / 99 : 69.9604%
                             Base_old T_eff              75 : 8.50818% / 90 : 27.99166% / 95 : 41.07475% / 99 : 67.92108%
                                      log_g               75 : 12.81626% / 90 : 38.459% / 95 : 51.61683% / 99 : 83.92394%
                                      radius            75 : 10.59435% / 90 : 31.74463% / 95 : 42.59315% / 99 : 69.24417%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 4.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.5328 - 3.786
                                      log_g                                      -0.102 - 2.978
                                      radius            0.7818989193511491 - 2.8272399995056454
                             Base_old T_eff                                      3.5301 - 3.786
                                      log_g                                      -0.122 - 2.979
                                      radius             0.7818989193511491 - 2.831997677235896

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               0.65911942798238
                                      log_g             0.9145444334060797
                                      radius            0.9621702735006398
                             Base_old T_eff             0.6229105972444626
                                      log_g             0.8792208971421926
                                      radius             0.946513857443982

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             7.07675%  1.53908%
                                      log_g             3.80149%   1.3943%
                                      radius            2.86253%  1.05076%
                             Base_old T_eff             7.44586%   2.2939%
                                      log_g             4.68252%  2.31494%
                                      radius            3.54265%  1.75331%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.31043%
                                      log_g              0.2936%
                                      radius            0.22172%
                             Base_old T_eff             0.65412%
                                      log_g             0.81782%
                                      radius            0.62208%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              0.836128348980831
                                      log_g              0.956704367836196
                                      radius            0.9809328484849373
                             Base_old T_eff              0.821823767317247
                                      log_g             0.9393382069091358
                                      radius            0.9728959660019413

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             327.40858%
                                      log_g             113.16865%
                                      radius             85.24363%
                             Base_old T_eff             321.45719%
                                      log_g             111.93189%
                                      radius              84.6826%

                                                                                                           Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             75 : 1.26382% / 90 : 3.10032% / 95 : 5.51343% / 99 : 16.12164%
                                      log_g             75 : 1.39286% / 90 : 3.35584% / 95 : 5.74481% / 99 : 16.01786%
                                      radius             75 : 1.04579% / 90 : 2.53601% / 95 : 4.3406% / 99 : 12.03907%
                             Base_old T_eff             75 : 2.63384% / 90 : 5.73271% / 95 : 8.08519% / 99 : 17.84291%
                                      log_g             75 : 3.09513% / 90 : 6.21864% / 95 : 8.75298% / 99 : 17.51016%
                                      radius            75 : 2.34379% / 90 : 4.71392% / 95 : 6.64456% / 99 : 13.20961%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 5.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.5642 - 4.272
                                      log_g                                         0.2 - 2.963
                                      radius             0.8787515201730021 - 2.669967369908504
                             Base_old T_eff                                      3.5644 - 4.272
                                      log_g                                       0.206 - 2.963
                                      radius            0.8787515201730021 - 2.6669857183296606

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9079086436663277
                                      log_g             0.9666549586583413
                                      radius            0.9833215630488885
                             Base_old T_eff             0.8847861253902843
                                      log_g              0.894091099961791
                                      radius            0.9415960186573777

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             4.90803%  1.34626%
                                      log_g             4.81053%   1.3849%
                                      radius            3.48136%  0.97724%
                             Base_old T_eff             5.49969%  1.76513%
                                      log_g             8.76338%  2.80087%
                                      radius            6.64855%  2.07245%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.06174%
                                      log_g             0.05393%
                                      radius            0.04283%
                             Base_old T_eff             0.08437%
                                      log_g             0.07508%
                                      radius            0.05848%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9534772118510992
                                      log_g             0.9833138504657927
                                      radius            0.9916566947756928
                             Base_old T_eff             0.9430227249846139
                                      log_g             0.9487935634643654
                                      radius            0.9712195233410787

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              71.0099%
                                      log_g             72.40974%
                                      radius            56.79423%
                             Base_old T_eff             74.94096%
                                      log_g             85.72627%
                                      radius            66.02081%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.55524% / 90 : 2.82142% / 95 : 6.08929% / 99 : 26.40294%
                                      log_g                75 : 0.58053% / 90 : 3.20413% / 95 : 6.8527% / 99 : 24.8802%
                                      radius             75 : 0.40419% / 90 : 2.21135% / 95 : 4.93687% / 99 : 17.36697%
                             Base_old T_eff              75 : 0.97795% / 90 : 4.34568% / 95 : 9.63963% / 99 : 27.47315%
                                      log_g             75 : 1.25861% / 90 : 6.61843% / 95 : 16.18172% / 99 : 45.86217%
                                      radius            75 : 0.90704% / 90 : 4.74826% / 95 : 11.73001% / 99 : 35.29851%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 6.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                     3.5416 - 4.2601
                                      log_g                                      -0.017 - 2.837
                                      radius            0.9630791606418272 - 2.7777891874348675
                             Base_old T_eff                                     3.5437 - 4.2601
                                      log_g                                      -0.019 - 2.869
                                      radius             0.9405164849325672 - 2.779668627207148

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9516275813074686
                                      log_g             0.9485394146228903
                                      radius            0.9697670887087206
                             Base_old T_eff             0.8841526345883329
                                      log_g             0.5297053497785793
                                      radius            0.7149449017388567

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             4.70228%  1.47386%
                                      log_g             4.72993%  1.57686%
                                      radius            3.65497%  1.21203%
                             Base_old T_eff             7.47708%  2.92285%
                                      log_g             14.7343%  5.59501%
                                      radius            11.5817%  4.38722%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.43451%
                                      log_g             0.52642%
                                      radius            0.40548%
                             Base_old T_eff             0.51651%
                                      log_g             0.67173%
                                      radius            0.51832%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9756452395472536
                                      log_g             0.9740958718877286
                                      radius            0.9848075867184325
                             Base_old T_eff              0.946399693541685
                                      log_g              0.802827285555517
                                      radius            0.8658808046077017

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             76.43337%
                                      log_g             75.42176%
                                      radius            61.22537%
                             Base_old T_eff             70.74888%
                                      log_g              81.9081%
                                      radius            64.13849%

                                                                                                             Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                 75 : 1.19276% / 90 : 2.746% / 95 : 5.16632% / 99 : 24.46207%
                                      log_g                75 : 1.44149% / 90 : 3.11528% / 95 : 5.24387% / 99 : 23.5417%
                                      radius              75 : 1.12911% / 90 : 2.39267% / 95 : 4.05354% / 99 : 16.37397%
                             Base_old T_eff                75 : 1.74623% / 90 : 8.445% / 95 : 17.08403% / 99 : 34.50447%
                                      log_g             75 : 2.46364% / 90 : 16.97507% / 95 : 38.95845% / 99 : 68.73961%
                                      radius            75 : 1.92426% / 90 : 13.21859% / 95 : 30.46893% / 99 : 54.23423%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

### Conclusion

Removing phase 7 (EAGB) improves the results of Global by a small margin. Most of this improvement can be seen in phase 6 which phase 7 superpose the most with.

Since there are no TPAGB phase, the improvement is less apparent than with the MIST dataset but it is still present.

## Base vs mass_filtered

| Parameter      | Base                                                   | mass_smaller_3                                         | 
| -------------  | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       | Range : 6.8 - 10.25, Mean : 9.4807, Median : 9.5       | 
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   | Range : 0.09 - 13.943, Mean : 2.3223, Median : 1.331   | 
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   | Range : 3.36 - 4.1907, Mean : 3.732, Median : 3.7204   | 
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   | Range : -0.38 - 5.345, Mean : 2.8946, Median : 2.504   | 
| R              | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 | Range : -0.98 - 2.3632, Mean : 0.8085, Median : 1.0017 |

### T_eff parameter

In [16]:
compare_metrics(path, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9451742472012191
                                 mass_smaller_3 T_eff              0.8871586813443988
KNN               PARSEC         Base           T_eff              0.9289910884078197
                                 mass_smaller_3 T_eff               0.910185955691971
linear_regression PARSEC         Base           T_eff             0.34445841658008647
                                 mass_smaller_3 T_eff              0.2566977420116534
mlp               PARSEC         Base           T_eff             0.45667538004833186
                                 mass_smaller_3 T_eff             0.29160421609577014
random_forest     PARSEC         Base           T_eff              0.9566608469406531
                                 mass_smaller_3 T_eff               0.913203605722624
xgboost           PARSEC         Base           T_eff              0.7726322878335125
                                 mass_smaller_3 T_eff              0.8523662223135867

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.042554292673794465
                                 mass_smaller_3 T_eff              0.03328590494814946
KNN               PARSEC         Base           T_eff              0.04851081543113413
                                 mass_smaller_3 T_eff              0.02969603069690199
linear_regression PARSEC         Base           T_eff              0.14714610399062228
                                 mass_smaller_3 T_eff              0.08542972296861495
mlp               PARSEC         Base           T_eff              0.13410280662162238
                                 mass_smaller_3 T_eff               0.0835840021057498
random_forest     PARSEC         Base           T_eff              0.03783483575687937
                                 mass_smaller_3 T_eff              0.02919290534578891
xgboost           PARSEC         Base           T_eff              0.08665888725371604
                                 mass_smaller_3 T_eff              0.03807317898165961

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.012520623599939452
                                 mass_smaller_3 T_eff             0.010588167800465901
KNN               PARSEC         Base           T_eff               0.0162096969395537
                                 mass_smaller_3 T_eff             0.011431817655160359
linear_regression PARSEC         Base           T_eff              0.10806443419089096
                                 mass_smaller_3 T_eff              0.06404163652696164
mlp               PARSEC         Base           T_eff              0.09348296889333235
                                 mass_smaller_3 T_eff             0.061867837532265164
random_forest     PARSEC         Base           T_eff              0.01219639278844237
                                 mass_smaller_3 T_eff             0.010209152963035109
xgboost           PARSEC         Base           T_eff             0.044921245386785554
                                 mass_smaller_3 T_eff             0.019494483185781827

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.001191428571428066
                                 mass_smaller_3 T_eff               0.00101575187969849
KNN               PARSEC         Base           T_eff             0.0018799999999998818
                                 mass_smaller_3 T_eff             0.0012199999999999989
linear_regression PARSEC         Base           T_eff               0.07505188017050912
                                 mass_smaller_3 T_eff              0.047681310121496345
mlp               PARSEC         Base           T_eff               0.06409550839974631
                                 mass_smaller_3 T_eff               0.04447700503672225
random_forest     PARSEC         Base           T_eff             0.0015007253298946477
                                 mass_smaller_3 T_eff             0.0013401235282757273
xgboost           PARSEC         Base           T_eff              0.012216230392456007
                                 mass_smaller_3 T_eff              0.006201692199707232

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9724235183367057
                                 mass_smaller_3 T_eff             0.9429494041263922
KNN               PARSEC         Base           T_eff             0.9638581868639022
                                 mass_smaller_3 T_eff              0.954103921746265
linear_regression PARSEC         Base           T_eff             0.5869057992445806
                                 mass_smaller_3 T_eff             0.5066534739968079
mlp               PARSEC         Base           T_eff             0.6876406178694955
                                 mass_smaller_3 T_eff             0.6575036455434058
random_forest     PARSEC         Base           T_eff             0.9781241008271904
                                 mass_smaller_3 T_eff             0.9558172268263041
xgboost           PARSEC         Base           T_eff              0.879158545551974
                                 mass_smaller_3 T_eff              0.923428111605875

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                          0.8407
                                 mass_smaller_3 T_eff              0.3836999999999997
KNN               PARSEC         Base           T_eff              0.8291399999999998
                                 mass_smaller_3 T_eff                          0.4295
linear_regression PARSEC         Base           T_eff              0.5457108330954776
                                 mass_smaller_3 T_eff             0.32000842330395507
mlp               PARSEC         Base           T_eff              0.8323897989412399
                                 mass_smaller_3 T_eff              0.6336879767814234
random_forest     PARSEC         Base           T_eff              0.8289985333333334
                                 mass_smaller_3 T_eff             0.28554875000000557
xgboost           PARSEC         Base           T_eff              0.6862123130798343
                                 mass_smaller_3 T_eff               0.324363548278809

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                                 mass_smaller_3 T_eff                75 : 0.00482 / 90 : 0.02104 / 95 : 0.0629 / 99 : 0.1844
KNN               PARSEC         Base           T_eff                75 : 0.0133 / 90 : 0.0398 / 95 : 0.07538 / 99 : 0.20009
                                 mass_smaller_3 T_eff               75 : 0.00762 / 90 : 0.0328 / 95 : 0.06052 / 99 : 0.14401
linear_regression PARSEC         Base           T_eff              75 : 0.14234 / 90 : 0.27293 / 95 : 0.32016 / 99 : 0.42868
                                 mass_smaller_3 T_eff               75 : 0.09087 / 90 : 0.1383 / 95 : 0.18617 / 99 : 0.25734
mlp               PARSEC         Base           T_eff                75 : 0.11522 / 90 : 0.20538 / 95 : 0.285 / 99 : 0.50069
                                 mass_smaller_3 T_eff              75 : 0.09009 / 90 : 0.13934 / 95 : 0.17681 / 99 : 0.24527
random_forest     PARSEC         Base           T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                 mass_smaller_3 T_eff              75 : 0.00543 / 90 : 0.02402 / 95 : 0.06044 / 99 : 0.14953
xgboost           PARSEC         Base           T_eff              75 : 0.05362 / 90 : 0.13639 / 95 : 0.20195 / 99 : 0.34634
                                 mass_smaller_3 T_eff                75 : 0.0187 / 90 : 0.05989 / 95 : 0.09447 / 99 : 0.1561

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9748322909531495
                                 mass_smaller_3 T_eff              0.975213198122586
KNN               PARSEC         Base           T_eff             0.9255387206020436
                                 mass_smaller_3 T_eff             0.9782428408568564
linear_regression PARSEC         Base           T_eff              0.597293514283356
                                 mass_smaller_3 T_eff             0.4252524861822299
mlp               PARSEC         Base           T_eff             0.5907206955331745
                                 mass_smaller_3 T_eff             0.5607280311364085
random_forest     PARSEC         Base           T_eff              0.982663800306455
                                 mass_smaller_3 T_eff             0.9843920547198056
xgboost           PARSEC         Base           T_eff             0.9035438101538388
                                 mass_smaller_3 T_eff             0.9514662316909307

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.0423812576414891
                                 mass_smaller_3 T_eff             0.025525608230402626
KNN               PARSEC         Base           T_eff               0.0740899334278856
                                 mass_smaller_3 T_eff              0.02416811908066164
linear_regression PARSEC         Base           T_eff               0.2152050705682071
                                 mass_smaller_3 T_eff              0.14224797949784304
mlp               PARSEC         Base           T_eff              0.17666405999646342
                                 mass_smaller_3 T_eff              0.11589381843074006
random_forest     PARSEC         Base           T_eff              0.03535147273459422
                                 mass_smaller_3 T_eff              0.02044262538990222
xgboost           PARSEC         Base           T_eff              0.08962926996366931
                                 mass_smaller_3 T_eff             0.039055830909155265

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.007449396025994484
                                 mass_smaller_3 T_eff             0.005852321173799819
KNN               PARSEC         Base           T_eff             0.019715328052154795
                                 mass_smaller_3 T_eff             0.009073475638292344
linear_regression PARSEC         Base           T_eff              0.18085985421238407
                                 mass_smaller_3 T_eff               0.1252941437867672
mlp               PARSEC         Base           T_eff              0.12539880208477472
                                 mass_smaller_3 T_eff              0.09347082372740609
random_forest     PARSEC         Base           T_eff             0.007341501892044874
                                 mass_smaller_3 T_eff             0.005841865256728682
xgboost           PARSEC         Base           T_eff              0.04370062094663365
                                 mass_smaller_3 T_eff              0.02276255512854454

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              4.999999999988347e-05
                                 mass_smaller_3 T_eff              6.666666666665932e-05
KNN               PARSEC         Base           T_eff               0.002020000000000355
                                 mass_smaller_3 T_eff              0.0018599999999997507
linear_regression PARSEC         Base           T_eff                0.13710958116446115
                                 mass_smaller_3 T_eff                0.10865869006110951
mlp               PARSEC         Base           T_eff                0.09267960050543134
                                 mass_smaller_3 T_eff                0.08217875082639203
random_forest     PARSEC         Base           T_eff             0.00019199999999486295
                                 mass_smaller_3 T_eff             0.00015898809523351431
xgboost           PARSEC         Base           T_eff               0.016440191650390457
                                 mass_smaller_3 T_eff               0.010862756729125955

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9876003989251159
                                 mass_smaller_3 T_eff             0.9879085497518846
KNN               PARSEC         Base           T_eff             0.9623018163028533
                                 mass_smaller_3 T_eff             0.9892128560826348
linear_regression PARSEC         Base           T_eff             0.8536445700543512
                                 mass_smaller_3 T_eff             0.7428268179996913
mlp               PARSEC         Base           T_eff             0.7773454058575309
                                 mass_smaller_3 T_eff             0.7912014877978358
random_forest     PARSEC         Base           T_eff             0.9914002808313593
                                 mass_smaller_3 T_eff             0.9923334481253897
xgboost           PARSEC         Base           T_eff             0.9513542801799472
                                 mass_smaller_3 T_eff              0.975709546834514

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8311642857142854
                                 mass_smaller_3 T_eff              0.3836999999999997
KNN               PARSEC         Base           T_eff              0.8263199999999999
                                 mass_smaller_3 T_eff                          0.4295
linear_regression PARSEC         Base           T_eff              0.5457108330954776
                                 mass_smaller_3 T_eff             0.32000842330395507
mlp               PARSEC         Base           T_eff              0.8323897989412399
                                 mass_smaller_3 T_eff              0.6336879767814234
random_forest     PARSEC         Base           T_eff              0.7694960000000011
                                 mass_smaller_3 T_eff             0.24687900000000074
xgboost           PARSEC         Base           T_eff              0.6862123130798343
                                 mass_smaller_3 T_eff               0.324363548278809

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                  75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                                 mass_smaller_3 T_eff                 75 : 0.0006 / 90 : 0.0085 / 95 : 0.0246 / 99 : 0.12535
KNN               PARSEC         Base           T_eff               75 : 0.0082 / 90 : 0.03622 / 95 : 0.06993 / 99 : 0.43359
                                 mass_smaller_3 T_eff              75 : 0.00648 / 90 : 0.02524 / 95 : 0.04408 / 99 : 0.11518
linear_regression PARSEC         Base           T_eff              75 : 0.25535 / 90 : 0.36302 / 95 : 0.41855 / 99 : 0.48298
                                 mass_smaller_3 T_eff               75 : 0.17008 / 90 : 0.22874 / 95 : 0.25406 / 99 : 0.2871
mlp               PARSEC         Base           T_eff                75 : 0.1533 / 90 : 0.27528 / 95 : 0.39784 / 99 : 0.6293
                                 mass_smaller_3 T_eff              75 : 0.13552 / 90 : 0.18752 / 95 : 0.21801 / 99 : 0.28095
random_forest     PARSEC         Base           T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                 mass_smaller_3 T_eff              75 : 0.00218 / 90 : 0.01083 / 95 : 0.03187 / 99 : 0.10912
xgboost           PARSEC         Base           T_eff              75 : 0.04522 / 90 : 0.09853 / 95 : 0.19258 / 99 : 0.44504
                                 mass_smaller_3 T_eff               75 : 0.02806 / 90 : 0.0595 / 95 : 0.08534 / 99 : 0.16151

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 2.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
KNN               PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
linear_regression PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
mlp               PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
random_forest     PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
xgboost           PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.872460228127739
                                 mass_smaller_3 T_eff               0.6049838323957871
KNN               PARSEC         Base           T_eff               0.9019213514815497
                                 mass_smaller_3 T_eff               0.7699945838955977
linear_regression PARSEC         Base           T_eff              0.24580413337093743
                                 mass_smaller_3 T_eff               0.3554085864147183
mlp               PARSEC         Base           T_eff             -0.06049696902287538
                                 mass_smaller_3 T_eff             0.040501860137208356
random_forest     PARSEC         Base           T_eff               0.8997608573485408
                                 mass_smaller_3 T_eff               0.7442416030826616
xgboost           PARSEC         Base           T_eff               0.2421346697916199
                                 mass_smaller_3 T_eff               0.5017650969894539

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.06255115396094892
                                 mass_smaller_3 T_eff              0.06317765357377349
KNN               PARSEC         Base           T_eff             0.056525460890971636
                                 mass_smaller_3 T_eff             0.051237771238936095
linear_regression PARSEC         Base           T_eff               0.1576451482232392
                                 mass_smaller_3 T_eff              0.10163849124145655
mlp               PARSEC         Base           T_eff               0.2016864006088252
                                 mass_smaller_3 T_eff              0.11580973375261623
random_forest     PARSEC         Base           T_eff             0.055910823269444784
                                 mass_smaller_3 T_eff              0.05247428964475242
xgboost           PARSEC         Base           T_eff              0.16346869278380277
                                 mass_smaller_3 T_eff              0.07935581863957553

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.03380714142468827
                                 mass_smaller_3 T_eff              0.03278852938657706
KNN               PARSEC         Base           T_eff              0.03625290530068196
                                 mass_smaller_3 T_eff             0.034125246006389776
linear_regression PARSEC         Base           T_eff              0.12579879104006494
                                 mass_smaller_3 T_eff              0.08213297366502408
mlp               PARSEC         Base           T_eff               0.1501671715231214
                                 mass_smaller_3 T_eff              0.09758225236026025
random_forest     PARSEC         Base           T_eff              0.03252911291352382
                                 mass_smaller_3 T_eff              0.03089406866793464
xgboost           PARSEC         Base           T_eff              0.12303096453821297
                                 mass_smaller_3 T_eff              0.06510858154638126

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.015225000000000044
                                 mass_smaller_3 T_eff             0.009400000000000297
KNN               PARSEC         Base           T_eff             0.022299999999999764
                                 mass_smaller_3 T_eff              0.01910999999999996
linear_regression PARSEC         Base           T_eff              0.10439328495368216
                                 mass_smaller_3 T_eff              0.07118473120414981
mlp               PARSEC         Base           T_eff              0.11146029498426513
                                 mass_smaller_3 T_eff              0.08883450516525526
random_forest     PARSEC         Base           T_eff              0.01636466238414358
                                 mass_smaller_3 T_eff             0.012408954761905067
xgboost           PARSEC         Base           T_eff              0.08958496551513662
                                 mass_smaller_3 T_eff              0.05606627845764156

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9441691057521153
                                 mass_smaller_3 T_eff              0.8925416933006906
KNN               PARSEC         Base           T_eff              0.9541994998198405
                                 mass_smaller_3 T_eff              0.9309697248307426
linear_regression PARSEC         Base           T_eff             0.49810122500597515
                                 mass_smaller_3 T_eff              0.5966831965905013
mlp               PARSEC         Base           T_eff               0.269179604340438
                                 mass_smaller_3 T_eff              0.5177989569662957
random_forest     PARSEC         Base           T_eff              0.9549507593925414
                                 mass_smaller_3 T_eff              0.9269223296620183
xgboost           PARSEC         Base           T_eff              0.5078146897498674
                                 mass_smaller_3 T_eff              0.7570231687633359

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8240999999999996
                                 mass_smaller_3 T_eff              0.2875000000000001
KNN               PARSEC         Base           T_eff              0.6363200000000004
                                 mass_smaller_3 T_eff              0.2595200000000002
linear_regression PARSEC         Base           T_eff              0.5110059990755276
                                 mass_smaller_3 T_eff              0.3040571798406537
mlp               PARSEC         Base           T_eff              0.7710058375102826
                                 mass_smaller_3 T_eff              0.3220619560000175
random_forest     PARSEC         Base           T_eff              0.7659037285714314
                                 mass_smaller_3 T_eff             0.24106511991869795
xgboost           PARSEC         Base           T_eff              0.6752104206085203
                                 mass_smaller_3 T_eff              0.3175848976135258

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                                 mass_smaller_3 T_eff               75 : 0.02955 / 90 : 0.11347 / 95 : 0.16941 / 99 : 0.2382
KNN               PARSEC         Base           T_eff              75 : 0.04752 / 90 : 0.08675 / 95 : 0.11641 / 99 : 0.19029
                                 mass_smaller_3 T_eff               75 : 0.04733 / 90 : 0.0914 / 95 : 0.11968 / 99 : 0.16175
linear_regression PARSEC         Base           T_eff               75 : 0.17836 / 90 : 0.26213 / 95 : 0.3129 / 99 : 0.41535
                                 mass_smaller_3 T_eff              75 : 0.11261 / 90 : 0.17127 / 95 : 0.20611 / 99 : 0.25215
mlp               PARSEC         Base           T_eff              75 : 0.20893 / 90 : 0.34079 / 95 : 0.43468 / 99 : 0.60504
                                 mass_smaller_3 T_eff              75 : 0.14003 / 90 : 0.18644 / 95 : 0.21327 / 99 : 0.25318
random_forest     PARSEC         Base           T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                 mass_smaller_3 T_eff              75 : 0.03636 / 90 : 0.09812 / 95 : 0.13041 / 99 : 0.18235
xgboost           PARSEC         Base           T_eff              75 : 0.17025 / 90 : 0.27651 / 95 : 0.35297 / 99 : 0.48104
                                 mass_smaller_3 T_eff              75 : 0.09128 / 90 : 0.12553 / 95 : 0.15135 / 99 : 0.20765

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 3.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
KNN               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
linear_regression PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
mlp               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
random_forest     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
xgboost           PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              -0.7632012932187855
                                 mass_smaller_3 T_eff              -0.5234705113818034
KNN               PARSEC         Base           T_eff             -0.41965388075205157
                                 mass_smaller_3 T_eff               -0.190960566612143
linear_regression PARSEC         Base           T_eff               -3.483450834504893
                                 mass_smaller_3 T_eff             -0.20316412930548045
mlp               PARSEC         Base           T_eff              -3.0626539193547986
                                 mass_smaller_3 T_eff              -1.7375683728213511
random_forest     PARSEC         Base           T_eff              -0.5023320130390359
                                 mass_smaller_3 T_eff             -0.23812916797553374
xgboost           PARSEC         Base           T_eff              -1.9217965476974368
                                 mass_smaller_3 T_eff             -0.15704650262152264

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.062014552223464726
                                 mass_smaller_3 T_eff              0.05848860953001508
KNN               PARSEC         Base           T_eff              0.05656926394300638
                                 mass_smaller_3 T_eff              0.05273060740093908
linear_regression PARSEC         Base           T_eff              0.12891641417073876
                                 mass_smaller_3 T_eff              0.07908477674132959
mlp               PARSEC         Base           T_eff              0.11600524039538827
                                 mass_smaller_3 T_eff              0.08478311269948922
random_forest     PARSEC         Base           T_eff              0.05757943586910902
                                 mass_smaller_3 T_eff              0.05312077035227188
xgboost           PARSEC         Base           T_eff              0.09612792095128411
                                 mass_smaller_3 T_eff             0.056620517675600175

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.027219918269213918
                                 mass_smaller_3 T_eff             0.028422840214358244
KNN               PARSEC         Base           T_eff             0.027019570776689806
                                 mass_smaller_3 T_eff              0.02796061059294737
linear_regression PARSEC         Base           T_eff              0.09720929302507696
                                 mass_smaller_3 T_eff              0.06453246305935913
mlp               PARSEC         Base           T_eff              0.08743946502025537
                                 mass_smaller_3 T_eff              0.06281880008987074
random_forest     PARSEC         Base           T_eff              0.02618894131123609
                                 mass_smaller_3 T_eff             0.027068693641862922
xgboost           PARSEC         Base           T_eff              0.06188901809704532
                                 mass_smaller_3 T_eff              0.03556526711127393

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0037571428571430143
                                 mass_smaller_3 T_eff              0.003509999999999014
KNN               PARSEC         Base           T_eff              0.006720000000000059
                                 mass_smaller_3 T_eff              0.006499999999999506
linear_regression PARSEC         Base           T_eff               0.07418431701105521
                                 mass_smaller_3 T_eff              0.058262105991064406
mlp               PARSEC         Base           T_eff                 0.064048664167482
                                 mass_smaller_3 T_eff              0.044861511364908235
random_forest     PARSEC         Base           T_eff             0.0046765708158016395
                                 mass_smaller_3 T_eff              0.004435026190476421
xgboost           PARSEC         Base           T_eff              0.025207269287109257
                                 mass_smaller_3 T_eff              0.015437748336792012

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.124189042946256
                                 mass_smaller_3 T_eff              0.11942462598385166
KNN               PARSEC         Base           T_eff              0.16510527785954335
                                 mass_smaller_3 T_eff               0.1668115647943539
linear_regression PARSEC         Base           T_eff              0.10169028688444401
                                 mass_smaller_3 T_eff               0.4059287004302059
mlp               PARSEC         Base           T_eff              0.07525042007796028
                                 mass_smaller_3 T_eff               0.3133821552638225
random_forest     PARSEC         Base           T_eff               0.1670618613045383
                                 mass_smaller_3 T_eff              0.18654793310689494
xgboost           PARSEC         Base           T_eff             0.050496683069772764
                                 mass_smaller_3 T_eff               0.2693434343187326

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8298000000000001
                                 mass_smaller_3 T_eff              0.2891999999999997
KNN               PARSEC         Base           T_eff              0.8132800000000002
                                 mass_smaller_3 T_eff              0.2891999999999997
linear_regression PARSEC         Base           T_eff             0.38010161373098983
                                 mass_smaller_3 T_eff             0.20863165093929892
mlp               PARSEC         Base           T_eff              0.6156126340493939
                                 mass_smaller_3 T_eff              0.3090762203689881
random_forest     PARSEC         Base           T_eff              0.8065130083333316
                                 mass_smaller_3 T_eff             0.28554875000000557
xgboost           PARSEC         Base           T_eff              0.3860601097106935
                                 mass_smaller_3 T_eff              0.2648350852966308

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                                 mass_smaller_3 T_eff              75 : 0.02726 / 90 : 0.10436 / 95 : 0.14774 / 99 : 0.22839
KNN               PARSEC         Base           T_eff              75 : 0.02926 / 90 : 0.08358 / 95 : 0.12637 / 99 : 0.21296
                                 mass_smaller_3 T_eff              75 : 0.03537 / 90 : 0.08926 / 95 : 0.12984 / 99 : 0.20084
linear_regression PARSEC         Base           T_eff               75 : 0.13101 / 90 : 0.2356 / 95 : 0.29718 / 99 : 0.33842
                                 mass_smaller_3 T_eff               75 : 0.0969 / 90 : 0.13086 / 95 : 0.14875 / 99 : 0.17746
mlp               PARSEC         Base           T_eff              75 : 0.12108 / 90 : 0.18899 / 95 : 0.22475 / 99 : 0.37096
                                 mass_smaller_3 T_eff              75 : 0.09278 / 90 : 0.14159 / 95 : 0.17841 / 99 : 0.25178
random_forest     PARSEC         Base           T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                 mass_smaller_3 T_eff              75 : 0.03062 / 90 : 0.09186 / 95 : 0.13158 / 99 : 0.20429
xgboost           PARSEC         Base           T_eff              75 : 0.09793 / 90 : 0.17076 / 95 : 0.22502 / 99 : 0.30108
                                 mass_smaller_3 T_eff              75 : 0.05157 / 90 : 0.10639 / 95 : 0.13362 / 99 : 0.17684

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
KNN               PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
linear_regression PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
mlp               PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
random_forest     PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
xgboost           PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.5441135519545068
                                 mass_smaller_3 T_eff              0.9242961999199967
KNN               PARSEC         Base           T_eff              0.6904163446197727
                                 mass_smaller_3 T_eff              0.8967013519648316
linear_regression PARSEC         Base           T_eff               -7.16132505869397
                                 mass_smaller_3 T_eff             -1.5686771055412678
mlp               PARSEC         Base           T_eff               -4.48744266439307
                                 mass_smaller_3 T_eff              -4.154786944185996
random_forest     PARSEC         Base           T_eff                0.65911942798238
                                 mass_smaller_3 T_eff              0.9288857018029434
xgboost           PARSEC         Base           T_eff             -0.3014297238793202
                                 mass_smaller_3 T_eff              0.8292302542118786

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.020721238317739282
                                 mass_smaller_3 T_eff             0.007156302955568765
KNN               PARSEC         Base           T_eff             0.017075614604465876
                                 mass_smaller_3 T_eff              0.00833909804396656
linear_regression PARSEC         Base           T_eff              0.09087287967461888
                                 mass_smaller_3 T_eff             0.042993461978324536
mlp               PARSEC         Base           T_eff              0.07804506883423629
                                 mass_smaller_3 T_eff              0.05849140444577535
random_forest     PARSEC         Base           T_eff             0.017918341936679124
                                 mass_smaller_3 T_eff             0.006938251111008831
xgboost           PARSEC         Base           T_eff             0.036494009132568096
                                 mass_smaller_3 T_eff             0.010883776366202249

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0038289243446757216
                                 mass_smaller_3 T_eff             0.0030461141057490874
KNN               PARSEC         Base           T_eff             0.0041563830424764725
                                 mass_smaller_3 T_eff              0.003256445823865216
linear_regression PARSEC         Base           T_eff                0.0606939285303933
                                 mass_smaller_3 T_eff              0.034454346136405446
mlp               PARSEC         Base           T_eff              0.059086141528507476
                                 mass_smaller_3 T_eff               0.04363169024712285
random_forest     PARSEC         Base           T_eff             0.0038969391184098512
                                 mass_smaller_3 T_eff             0.0030534498752840147
xgboost           PARSEC         Base           T_eff              0.013120298537824896
                                 mass_smaller_3 T_eff              0.005731549104600593

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.0007587628865994844
                                 mass_smaller_3 T_eff              0.0008441558441583119
KNN               PARSEC         Base           T_eff             0.00040000000000040004
                                 mass_smaller_3 T_eff              0.0004199999999996429
linear_regression PARSEC         Base           T_eff                0.04359967210407634
                                 mass_smaller_3 T_eff                0.03048185133489234
mlp               PARSEC         Base           T_eff               0.049751120543306104
                                 mass_smaller_3 T_eff                0.03042273481751101
random_forest     PARSEC         Base           T_eff               0.000785999999997955
                                 mass_smaller_3 T_eff              0.0008633150266730283
xgboost           PARSEC         Base           T_eff               0.003836515426635767
                                 mass_smaller_3 T_eff               0.003026749801635642

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.7961889196467123
                                 mass_smaller_3 T_eff               0.9626419908201415
KNN               PARSEC         Base           T_eff               0.8501678081907662
                                 mass_smaller_3 T_eff               0.9500095724320192
linear_regression PARSEC         Base           T_eff             -0.21481121752618543
                                 mass_smaller_3 T_eff              0.31895709607702794
mlp               PARSEC         Base           T_eff             0.023312409206957985
                                 mass_smaller_3 T_eff              0.42274488488999873
random_forest     PARSEC         Base           T_eff                0.836128348980831
                                 mass_smaller_3 T_eff                0.964809662060515
xgboost           PARSEC         Base           T_eff                0.377210711992698
                                 mass_smaller_3 T_eff                0.910803401441279

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                          0.8407
                                 mass_smaller_3 T_eff             0.24480000000000013
KNN               PARSEC         Base           T_eff              0.8291399999999998
                                 mass_smaller_3 T_eff              0.1180800000000004
linear_regression PARSEC         Base           T_eff              0.3739373413922791
                                 mass_smaller_3 T_eff             0.18821207195901835
mlp               PARSEC         Base           T_eff              0.6171417815751772
                                 mass_smaller_3 T_eff             0.29646057849323393
random_forest     PARSEC         Base           T_eff              0.8289985333333334
                                 mass_smaller_3 T_eff             0.14136300000000412
xgboost           PARSEC         Base           T_eff             0.40178928604125996
                                 mass_smaller_3 T_eff             0.15799813423156728

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                                 mass_smaller_3 T_eff               75 : 0.00318 / 90 : 0.00748 / 95 : 0.01282 / 99 : 0.0312
KNN               PARSEC         Base           T_eff               75 : 0.00184 / 90 : 0.0122 / 95 : 0.02378 / 99 : 0.04028
                                 mass_smaller_3 T_eff               75 : 0.00178 / 90 : 0.00984 / 95 : 0.0233 / 99 : 0.03445
linear_regression PARSEC         Base           T_eff                75 : 0.06806 / 90 : 0.11643 / 95 : 0.26577 / 99 : 0.323
                                 mass_smaller_3 T_eff                75 : 0.04819 / 90 : 0.0655 / 95 : 0.07947 / 99 : 0.1237
mlp               PARSEC         Base           T_eff              75 : 0.07231 / 90 : 0.10066 / 95 : 0.15498 / 99 : 0.27496
                                 mass_smaller_3 T_eff              75 : 0.06152 / 90 : 0.09961 / 95 : 0.11919 / 99 : 0.17187
random_forest     PARSEC         Base           T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                 mass_smaller_3 T_eff                75 : 0.00319 / 90 : 0.00759 / 95 : 0.013 / 99 : 0.03133
xgboost           PARSEC         Base           T_eff              75 : 0.00977 / 90 : 0.01972 / 95 : 0.05406 / 99 : 0.19767
                                 mass_smaller_3 T_eff              75 : 0.00716 / 90 : 0.01249 / 95 : 0.01729 / 99 : 0.04419

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 5.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
KNN               PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
linear_regression PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
mlp               PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
random_forest     PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
xgboost           PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.875456632791973
                                 mass_smaller_3 T_eff                0.867553551301494
KNN               PARSEC         Base           T_eff               0.8952904959736894
                                 mass_smaller_3 T_eff                 0.96336943698678
linear_regression PARSEC         Base           T_eff              0.13546196696769075
                                 mass_smaller_3 T_eff                0.668506592185953
mlp               PARSEC         Base           T_eff             -0.29273083625011354
                                 mass_smaller_3 T_eff              -0.4869112855205724
random_forest     PARSEC         Base           T_eff               0.9079086436663277
                                 mass_smaller_3 T_eff               0.9604125945272385
xgboost           PARSEC         Base           T_eff               0.4646243180794113
                                 mass_smaller_3 T_eff               0.7170427591317867

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.0404003814429823
                                 mass_smaller_3 T_eff              0.013122882060035538
KNN               PARSEC         Base           T_eff               0.03711047830863781
                                 mass_smaller_3 T_eff              0.006928575573769303
linear_regression PARSEC         Base           T_eff               0.16148586925420585
                                 mass_smaller_3 T_eff               0.07478912830666538
mlp               PARSEC         Base           T_eff               0.13709882557268205
                                 mass_smaller_3 T_eff               0.05985136333829618
random_forest     PARSEC         Base           T_eff               0.03473902067670326
                                 mass_smaller_3 T_eff             0.0071748688474133895
xgboost           PARSEC         Base           T_eff               0.08582596740917203
                                 mass_smaller_3 T_eff              0.019185446266324447

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.009523709897636998
                                 mass_smaller_3 T_eff             0.0015745356602996682
KNN               PARSEC         Base           T_eff              0.014543067715688269
                                 mass_smaller_3 T_eff             0.0019761283234454446
linear_regression PARSEC         Base           T_eff               0.13719830717896403
                                 mass_smaller_3 T_eff               0.07201459153124953
mlp               PARSEC         Base           T_eff               0.10635807796242833
                                 mass_smaller_3 T_eff               0.04651173163409056
random_forest     PARSEC         Base           T_eff              0.009528858618003498
                                 mass_smaller_3 T_eff             0.0021912574230866077
xgboost           PARSEC         Base           T_eff               0.05902249643570652
                                 mass_smaller_3 T_eff              0.013598684864299836

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              4.440892098500626e-16
                                 mass_smaller_3 T_eff                                0.0
KNN               PARSEC         Base           T_eff               0.001100000000000101
                                 mass_smaller_3 T_eff              4.000000000026205e-05
linear_regression PARSEC         Base           T_eff                0.11317556965713527
                                 mass_smaller_3 T_eff                0.07328150743468687
mlp               PARSEC         Base           T_eff                  0.081959774798813
                                 mass_smaller_3 T_eff                 0.0352046988004604
random_forest     PARSEC         Base           T_eff             0.00043700000000024275
                                 mass_smaller_3 T_eff              0.0001320000000011312
xgboost           PARSEC         Base           T_eff               0.034365868377685516
                                 mass_smaller_3 T_eff               0.009320376968383837

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9382230012465637
                                 mass_smaller_3 T_eff              0.9400210765627829
KNN               PARSEC         Base           T_eff              0.9462976094851531
                                 mass_smaller_3 T_eff              0.9815747427610161
linear_regression PARSEC         Base           T_eff             0.40357511224693443
                                 mass_smaller_3 T_eff              0.8200960609467987
mlp               PARSEC         Base           T_eff              0.3425653519856123
                                 mass_smaller_3 T_eff              0.7456514404575488
random_forest     PARSEC         Base           T_eff              0.9534772118510992
                                 mass_smaller_3 T_eff              0.9805720984574089
xgboost           PARSEC         Base           T_eff                0.68203526589872
                                 mass_smaller_3 T_eff              0.8558303476868421

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.7346999999999997
                                 mass_smaller_3 T_eff             0.31820000000000004
KNN               PARSEC         Base           T_eff              0.5404999999999998
                                 mass_smaller_3 T_eff              0.1918599999999997
linear_regression PARSEC         Base           T_eff             0.34566965758396906
                                 mass_smaller_3 T_eff             0.14286852672435746
mlp               PARSEC         Base           T_eff              0.5471516729521126
                                 mass_smaller_3 T_eff             0.23403602479640107
random_forest     PARSEC         Base           T_eff               0.502608099999998
                                 mass_smaller_3 T_eff             0.09220366666666369
xgboost           PARSEC         Base           T_eff               0.553806636047363
                                 mass_smaller_3 T_eff             0.13106379623413078

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                                 mass_smaller_3 T_eff                   75 : 5e-05 / 90 : 0.0001 / 95 : 0.0021 / 99 : 0.0425
KNN               PARSEC         Base           T_eff               75 : 0.0147 / 90 : 0.03722 / 95 : 0.06555 / 99 : 0.18111
                                 mass_smaller_3 T_eff               75 : 0.00028 / 90 : 0.0059 / 95 : 0.01231 / 99 : 0.02871
linear_regression PARSEC         Base           T_eff               75 : 0.1915 / 90 : 0.28075 / 95 : 0.30894 / 99 : 0.33665
                                 mass_smaller_3 T_eff              75 : 0.08641 / 90 : 0.09691 / 95 : 0.10075 / 99 : 0.10615
mlp               PARSEC         Base           T_eff                75 : 0.13316 / 90 : 0.2293 / 95 : 0.2998 / 99 : 0.40241
                                 mass_smaller_3 T_eff                75 : 0.06233 / 90 : 0.0923 / 95 : 0.1206 / 99 : 0.19051
random_forest     PARSEC         Base           T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                 mass_smaller_3 T_eff              75 : 0.00104 / 90 : 0.00509 / 95 : 0.01198 / 99 : 0.03638
xgboost           PARSEC         Base           T_eff              75 : 0.08836 / 90 : 0.14542 / 95 : 0.18122 / 99 : 0.26898
                                 mass_smaller_3 T_eff              75 : 0.01782 / 90 : 0.03164 / 95 : 0.04145 / 99 : 0.06319

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 6.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
KNN               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
linear_regression PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
mlp               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
random_forest     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
xgboost           PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.9361134687179025
                                 mass_smaller_3 T_eff               0.9344208412339422
KNN               PARSEC         Base           T_eff               0.9418003454905226
                                 mass_smaller_3 T_eff               0.8942508407557085
linear_regression PARSEC         Base           T_eff              0.20764377732401518
                                 mass_smaller_3 T_eff               0.5166524600554323
mlp               PARSEC         Base           T_eff             0.032533794358943324
                                 mass_smaller_3 T_eff              -0.8772552924720776
random_forest     PARSEC         Base           T_eff               0.9516275813074686
                                 mass_smaller_3 T_eff               0.9733172442765325
xgboost           PARSEC         Base           T_eff               0.6654556763318269
                                 mass_smaller_3 T_eff               0.6136185070108772

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.038817942968688686
                                 mass_smaller_3 T_eff             0.009947309738953879
KNN               PARSEC         Base           T_eff              0.03707878942589577
                                 mass_smaller_3 T_eff              0.01295611547006416
linear_regression PARSEC         Base           T_eff               0.1678192510763587
                                 mass_smaller_3 T_eff              0.08979673999415073
mlp               PARSEC         Base           T_eff              0.15194250392767136
                                 mass_smaller_3 T_eff              0.08952545832863493
random_forest     PARSEC         Base           T_eff              0.03378586126202459
                                 mass_smaller_3 T_eff             0.006343508147581037
xgboost           PARSEC         Base           T_eff              0.08905194351552072
                                 mass_smaller_3 T_eff             0.024294606184243273

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.010905352896371222
                                 mass_smaller_3 T_eff              0.003275683015649687
KNN               PARSEC         Base           T_eff                0.0200289228367529
                                 mass_smaller_3 T_eff              0.009480039447731752
linear_regression PARSEC         Base           T_eff                 0.142558114990346
                                 mass_smaller_3 T_eff               0.08574514045736377
mlp               PARSEC         Base           T_eff               0.12078806581546199
                                 mass_smaller_3 T_eff               0.07399730524660289
random_forest     PARSEC         Base           T_eff              0.010589656124915763
                                 mass_smaller_3 T_eff             0.0030457676521849462
xgboost           PARSEC         Base           T_eff               0.06752463157396035
                                 mass_smaller_3 T_eff               0.01811025127634103

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0035000000000007248
                                 mass_smaller_3 T_eff              0.001966666666666672
KNN               PARSEC         Base           T_eff              0.011480000000000157
                                 mass_smaller_3 T_eff              0.007039999999999491
linear_regression PARSEC         Base           T_eff               0.12713358897186677
                                 mass_smaller_3 T_eff               0.08592582620527445
mlp               PARSEC         Base           T_eff               0.09813067909362583
                                 mass_smaller_3 T_eff               0.06298795236640853
random_forest     PARSEC         Base           T_eff             0.0031219369047614798
                                 mass_smaller_3 T_eff             0.0017529666666700194
xgboost           PARSEC         Base           T_eff              0.051502188873290944
                                 mass_smaller_3 T_eff              0.013554772949218918

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9682850567668624
                                 mass_smaller_3 T_eff              0.9679753590180824
KNN               PARSEC         Base           T_eff              0.9705614825838571
                                 mass_smaller_3 T_eff              0.9491856526161931
linear_regression PARSEC         Base           T_eff               0.478529160628656
                                 mass_smaller_3 T_eff              0.7242784910979044
mlp               PARSEC         Base           T_eff             0.41841265241488523
                                 mass_smaller_3 T_eff              0.6747902488625411
random_forest     PARSEC         Base           T_eff              0.9756452395472536
                                 mass_smaller_3 T_eff              0.9866197822722799
xgboost           PARSEC         Base           T_eff              0.8235404788604241
                                 mass_smaller_3 T_eff              0.7835296275337241

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.7282999999999995
                                 mass_smaller_3 T_eff                          0.2946
KNN               PARSEC         Base           T_eff              0.5081600000000002
                                 mass_smaller_3 T_eff             0.06072000000000077
linear_regression PARSEC         Base           T_eff              0.3671658110993148
                                 mass_smaller_3 T_eff             0.16529944266660213
mlp               PARSEC         Base           T_eff              0.5083662169085255
                                 mass_smaller_3 T_eff             0.24357605913495872
random_forest     PARSEC         Base           T_eff              0.5491737666666734
                                 mass_smaller_3 T_eff              0.1298869595238119
xgboost           PARSEC         Base           T_eff              0.3164865329742428
                                 mass_smaller_3 T_eff             0.08730419883728047

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                                 mass_smaller_3 T_eff              75 : 0.00418 / 90 : 0.00735 / 95 : 0.00924 / 99 : 0.01914
KNN               PARSEC         Base           T_eff              75 : 0.02298 / 90 : 0.04069 / 95 : 0.06435 / 99 : 0.15869
                                 mass_smaller_3 T_eff              75 : 0.01298 / 90 : 0.02106 / 95 : 0.02676 / 99 : 0.04192
linear_regression PARSEC         Base           T_eff              75 : 0.20855 / 90 : 0.27287 / 95 : 0.30722 / 99 : 0.34225
                                 mass_smaller_3 T_eff              75 : 0.10347 / 90 : 0.12041 / 95 : 0.12707 / 99 : 0.14415
mlp               PARSEC         Base           T_eff               75 : 0.1697 / 90 : 0.25914 / 95 : 0.30838 / 99 : 0.39154
                                 mass_smaller_3 T_eff               75 : 0.10374 / 90 : 0.15093 / 95 : 0.17498 / 99 : 0.2011
random_forest     PARSEC         Base           T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                 mass_smaller_3 T_eff                75 : 0.004 / 90 : 0.00689 / 95 : 0.00923 / 99 : 0.01743
xgboost           PARSEC         Base           T_eff               75 : 0.0978 / 90 : 0.14934 / 95 : 0.18727 / 99 : 0.24988
                                 mass_smaller_3 T_eff              75 : 0.02496 / 90 : 0.03946 / 95 : 0.05351 / 99 : 0.07458

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER

KNN : 
- mass_smaller_3 : better/similar results to Base

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER

XGBoost : 
- mass_smaller_3 : better results than Base on every metric

MLP : 
- mass_smaller_3 : similar results than Base on every metric except MAX_ER

#### Conclusions on T_eff

Filtering with mass_smaller_3 mostly gives better results on every metric.

#### Best models for the T_eff parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and XGBoost.

### Radius parameter

In [17]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
KNN               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
mlp               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8188802537475399
                                 mass_smaller_3 radius            0.6656875093221303
KNN               PARSEC         Base           radius            0.8504530694492762
                                 mass_smaller_3 radius            0.7461594476972371
linear_regression PARSEC         Base           radius             0.306153058491456
                                 mass_smaller_3 radius            0.3314355213392083
mlp               PARSEC         Base           radius            0.6228554128105982
                                 mass_smaller_3 radius            0.5423045430426903
random_forest     PARSEC         Base           radius            0.8584173604243724
                                 mass_smaller_3 radius            0.7407905526574192
xgboost           PARSEC         Base           radius            0.7945230921341289
                                 mass_smaller_3 radius            0.7497460834843865

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.25948245112260193
                                 mass_smaller_3 radius            0.28712955880678553
KNN               PARSEC         Base           radius             0.2358770846024068
                                 mass_smaller_3 radius            0.25019731745221385
linear_regression PARSEC         Base           radius              0.507872479197307
                                 mass_smaller_3 radius             0.4060441237499527
mlp               PARSEC         Base           radius            0.37498636922431416
                                 mass_smaller_3 radius             0.3359946545077814
random_forest     PARSEC         Base           radius            0.22941978755764808
                                 mass_smaller_3 radius            0.25282928243556957
xgboost           PARSEC         Base           radius            0.27637866309651515
                                 mass_smaller_3 radius            0.24842314472263485

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.07527911151810734
                                 mass_smaller_3 radius            0.08632530853853265
KNN               PARSEC         Base           radius             0.0846864913145467
                                 mass_smaller_3 radius            0.08949852307856042
linear_regression PARSEC         Base           radius            0.39753794061010017
                                 mass_smaller_3 radius            0.31348689994675705
mlp               PARSEC         Base           radius            0.25364283689755424
                                 mass_smaller_3 radius             0.2207560899464196
random_forest     PARSEC         Base           radius            0.07306790793549578
                                 mass_smaller_3 radius             0.0833807631223743
xgboost           PARSEC         Base           radius              0.156982113190067
                                 mass_smaller_3 radius            0.12143441529830028

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0056727093489148395
                                 mass_smaller_3 radius             0.005455509201885644
KNN               PARSEC         Base           radius             0.007272808772476278
                                 mass_smaller_3 radius             0.005215953656321076
linear_regression PARSEC         Base           radius               0.2745446720480792
                                 mass_smaller_3 radius              0.23043334862203918
mlp               PARSEC         Base           radius              0.13319718920440615
                                 mass_smaller_3 radius              0.11385103382431644
random_forest     PARSEC         Base           radius             0.006440088206492278
                                 mass_smaller_3 radius             0.006542786149945967
xgboost           PARSEC         Base           radius              0.05423633153337293
                                 mass_smaller_3 radius             0.035588404313140976

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9078549079572853
                                 mass_smaller_3 radius            0.8272413120780314
KNN               PARSEC         Base           radius            0.9227969605947961
                                 mass_smaller_3 radius            0.8649063238059407
linear_regression PARSEC         Base           radius            0.5533109976788975
                                 mass_smaller_3 radius            0.5757043716529034
mlp               PARSEC         Base           radius            0.7892150515996972
                                 mass_smaller_3 radius            0.7365739150319188
random_forest     PARSEC         Base           radius            0.9271725495364581
                                 mass_smaller_3 radius             0.863219732122844
xgboost           PARSEC         Base           radius            0.8915692177111999
                                 mass_smaller_3 radius            0.8661602334586869

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.390815363619212
                                 mass_smaller_3 radius            2.3751855303079865
KNN               PARSEC         Base           radius            2.3172378341427184
                                 mass_smaller_3 radius            2.3170361323390436
linear_regression PARSEC         Base           radius             1.781259161764016
                                 mass_smaller_3 radius            1.4619464165080611
mlp               PARSEC         Base           radius            1.9906768274128068
                                 mass_smaller_3 radius            1.6083701045455463
random_forest     PARSEC         Base           radius             2.310296151725146
                                 mass_smaller_3 radius            2.3030305939409654
xgboost           PARSEC         Base           radius             2.261232186873491
                                 mass_smaller_3 radius             2.308647204488007

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.02877 / 90 : 0.11129 / 95 : 0.4465 / 99 : 1.45363
                                 mass_smaller_3 radius               75 : 0.02711 / 90 : 0.1447 / 95 : 0.6043 / 99 : 1.54958
KNN               PARSEC         Base           radius             75 : 0.04507 / 90 : 0.22252 / 95 : 0.51756 / 99 : 1.12183
                                 mass_smaller_3 radius              75 : 0.03339 / 90 : 0.28478 / 95 : 0.57739 / 99 : 1.1621
linear_regression PARSEC         Base           radius             75 : 0.58813 / 90 : 0.83923 / 95 : 1.02037 / 99 : 1.42151
                                 mass_smaller_3 radius              75 : 0.39108 / 90 : 0.72563 / 95 : 0.89423 / 99 : 1.1325
mlp               PARSEC         Base           radius             75 : 0.37949 / 90 : 0.71574 / 95 : 0.85022 / 99 : 1.08968
                                 mass_smaller_3 radius              75 : 0.28673 / 90 : 0.64143 / 95 : 0.81239 / 99 : 1.0253
random_forest     PARSEC         Base           radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
                                 mass_smaller_3 radius              75 : 0.03167 / 90 : 0.19214 / 95 : 0.57193 / 99 : 1.2424
xgboost           PARSEC         Base           radius             75 : 0.19952 / 90 : 0.47689 / 95 : 0.64069 / 99 : 1.00851
                                 mass_smaller_3 radius              75 : 0.1121 / 90 : 0.38269 / 95 : 0.59104 / 99 : 1.02277

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
KNN               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
mlp               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.7363724523806283
                                 mass_smaller_3 radius              0.5692154631580525
KNN               PARSEC         Base           radius              0.6600434525070423
                                 mass_smaller_3 radius              0.6478433146027724
linear_regression PARSEC         Base           radius              0.2911261433374668
                                 mass_smaller_3 radius            -0.38728983206769274
mlp               PARSEC         Base           radius            -0.17637582185160272
                                 mass_smaller_3 radius            -0.34828652576951313
random_forest     PARSEC         Base           radius               0.821604552614865
                                 mass_smaller_3 radius              0.7078963482896191
xgboost           PARSEC         Base           radius              0.5662612193213132
                                 mass_smaller_3 radius              0.5422178342312092

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.19042170257723945
                                 mass_smaller_3 radius             0.2002492504816667
KNN               PARSEC         Base           radius            0.22254830368573666
                                 mass_smaller_3 radius            0.18466113789326627
linear_regression PARSEC         Base           radius             0.8081240809409921
                                 mass_smaller_3 radius             0.6238573686801736
mlp               PARSEC         Base           radius             0.5437082254759342
                                 mass_smaller_3 radius              0.472819399821771
random_forest     PARSEC         Base           radius            0.15816370646342748
                                 mass_smaller_3 radius             0.1667421390538769
xgboost           PARSEC         Base           radius             0.2767403003739343
                                 mass_smaller_3 radius            0.22937690365350963

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.03409305225688784
                                 mass_smaller_3 radius             0.03698449906826638
KNN               PARSEC         Base           radius             0.06934657256026752
                                 mass_smaller_3 radius            0.054267388740391186
linear_regression PARSEC         Base           radius              0.7470748806993995
                                 mass_smaller_3 radius               0.560992030142771
mlp               PARSEC         Base           radius             0.40163841078936713
                                 mass_smaller_3 radius             0.33536675165391694
random_forest     PARSEC         Base           radius             0.03533338889206165
                                 mass_smaller_3 radius             0.03912195237829962
xgboost           PARSEC         Base           radius             0.16067151495024773
                                 mass_smaller_3 radius             0.12925411294122657

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.00039910653829717396
                                 mass_smaller_3 radius             0.0004485157721801081
KNN               PARSEC         Base           radius              0.004955741336719395
                                 mass_smaller_3 radius              0.004012748495691439
linear_regression PARSEC         Base           radius                 0.675373079244163
                                 mass_smaller_3 radius                 0.560119894578202
mlp               PARSEC         Base           radius               0.28679780926280607
                                 mass_smaller_3 radius               0.14235719581670492
random_forest     PARSEC         Base           radius             0.0005658977502006612
                                 mass_smaller_3 radius             0.0005257708673146594
xgboost           PARSEC         Base           radius               0.05116864033877122
                                 mass_smaller_3 radius               0.04343078970780857

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.891072495933085
                                 mass_smaller_3 radius             0.841483379572012
KNN               PARSEC         Base           radius            0.8859021657633167
                                 mass_smaller_3 radius            0.8655486583798956
linear_regression PARSEC         Base           radius            0.6331630624513377
                                 mass_smaller_3 radius            0.6192330441146768
mlp               PARSEC         Base           radius            0.7838452832290015
                                 mass_smaller_3 radius            0.7675803839055694
random_forest     PARSEC         Base           radius            0.9227998598367169
                                 mass_smaller_3 radius            0.8848730507935565
xgboost           PARSEC         Base           radius            0.8825965510893421
                                 mass_smaller_3 radius            0.8679802205239031

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.390815363619212
                                 mass_smaller_3 radius            2.3751855303079865
KNN               PARSEC         Base           radius            2.2561552794953266
                                 mass_smaller_3 radius             2.170880800930863
linear_regression PARSEC         Base           radius             1.781259161764016
                                 mass_smaller_3 radius            1.4371270520309136
mlp               PARSEC         Base           radius            1.3830092228942736
                                 mass_smaller_3 radius             1.013206438629486
random_forest     PARSEC         Base           radius            2.1128109169722986
                                 mass_smaller_3 radius             2.030694118628242
xgboost           PARSEC         Base           radius            1.7067418181404244
                                 mass_smaller_3 radius            1.6626087636745353

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00335 / 90 : 0.01452 / 95 : 0.03433 / 99 : 0.98432
                                 mass_smaller_3 radius              75 : 0.00233 / 90 : 0.01144 / 95 : 0.03412 / 99 : 0.9722
KNN               PARSEC         Base           radius             75 : 0.01813 / 90 : 0.11851 / 95 : 0.42461 / 99 : 1.12036
                                 mass_smaller_3 radius               75 : 0.01391 / 90 : 0.05477 / 95 : 0.397 / 99 : 0.94818
linear_regression PARSEC         Base           radius              75 : 0.91055 / 90 : 1.1884 / 95 : 1.39367 / 99 : 1.62448
                                 mass_smaller_3 radius             75 : 0.77688 / 90 : 0.92169 / 95 : 0.98044 / 99 : 1.09332
mlp               PARSEC         Base           radius              75 : 0.76117 / 90 : 0.89535 / 95 : 0.96146 / 99 : 1.1454
                                 mass_smaller_3 radius             75 : 0.67046 / 90 : 0.83521 / 95 : 0.88264 / 99 : 0.95108
random_forest     PARSEC         Base           radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
                                 mass_smaller_3 radius              75 : 0.00322 / 90 : 0.0328 / 95 : 0.21253 / 99 : 0.89905
xgboost           PARSEC         Base           radius             75 : 0.21204 / 90 : 0.51508 / 95 : 0.66892 / 99 : 0.95761
                                 mass_smaller_3 radius             75 : 0.15684 / 90 : 0.39389 / 95 : 0.55229 / 99 : 0.83087

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 2.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
KNN               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
linear_regression PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
mlp               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
random_forest     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
xgboost           PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.5645314183359549
                                 mass_smaller_3 radius              -2.732952353195582
KNN               PARSEC         Base           radius              0.7554229207106287
                                 mass_smaller_3 radius             -0.9202566498577154
linear_regression PARSEC         Base           radius              0.5386038834226268
                                 mass_smaller_3 radius               0.408572591522509
mlp               PARSEC         Base           radius              0.6582559034694251
                                 mass_smaller_3 radius            0.005650543995053381
random_forest     PARSEC         Base           radius              0.7071019602387656
                                 mass_smaller_3 radius             -1.3305951778814302
xgboost           PARSEC         Base           radius              0.6440509775938494
                                 mass_smaller_3 radius            -0.25643982288806044

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.37808377490281414
                                 mass_smaller_3 radius             0.5231844849065922
KNN               PARSEC         Base           radius             0.2960988592039106
                                 mass_smaller_3 radius             0.4049513691727813
linear_regression PARSEC         Base           radius            0.40465135367108096
                                 mass_smaller_3 radius             0.4662014379721217
mlp               PARSEC         Base           radius            0.47730657095930035
                                 mass_smaller_3 radius            0.47330015800807174
random_forest     PARSEC         Base           radius             0.3161486321555061
                                 mass_smaller_3 radius            0.42992643766008815
xgboost           PARSEC         Base           radius            0.41744405306674026
                                 mass_smaller_3 radius            0.39855546992362545

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.15156764565330214
                                 mass_smaller_3 radius            0.23789707005160315
KNN               PARSEC         Base           radius            0.15368204149587342
                                 mass_smaller_3 radius            0.23628660939138874
linear_regression PARSEC         Base           radius            0.33080701925341655
                                 mass_smaller_3 radius            0.42671744861168726
mlp               PARSEC         Base           radius            0.40741811308800074
                                 mass_smaller_3 radius             0.4212535662836884
random_forest     PARSEC         Base           radius             0.1447388228438247
                                 mass_smaller_3 radius            0.22443456672494236
xgboost           PARSEC         Base           radius             0.3365678257047855
                                 mass_smaller_3 radius             0.3165983728312409

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.030172026537108265
                                 mass_smaller_3 radius             0.01610977354066312
KNN               PARSEC         Base           radius             0.04596530180713654
                                 mass_smaller_3 radius            0.037053589010871024
linear_regression PARSEC         Base           radius              0.2995236211924257
                                 mass_smaller_3 radius             0.41432745731367254
mlp               PARSEC         Base           radius              0.4132640244619854
                                 mass_smaller_3 radius              0.4519084128446092
random_forest     PARSEC         Base           radius             0.03406943232764609
                                 mass_smaller_3 radius             0.02599109454173537
xgboost           PARSEC         Base           radius              0.2929446210015452
                                 mass_smaller_3 radius              0.2661512237171837

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.7801787228457896
                                 mass_smaller_3 radius            0.09611120123386492
KNN               PARSEC         Base           radius              0.869666457596233
                                 mass_smaller_3 radius            0.14686392564473957
linear_regression PARSEC         Base           radius             0.7362360964966685
                                 mass_smaller_3 radius             0.6610338587317061
mlp               PARSEC         Base           radius             0.8193237357637003
                                 mass_smaller_3 radius            0.22248759544396704
random_forest     PARSEC         Base           radius             0.8450590476514552
                                 mass_smaller_3 radius            0.16662394884988382
xgboost           PARSEC         Base           radius             0.8027978602985453
                                 mass_smaller_3 radius            0.28534341589559026

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            2.0861071059413177
                                 mass_smaller_3 radius             2.108165755165133
KNN               PARSEC         Base           radius            1.9831724722172852
                                 mass_smaller_3 radius            1.9979948798223217
linear_regression PARSEC         Base           radius             1.543650323988387
                                 mass_smaller_3 radius            1.0813481030120495
mlp               PARSEC         Base           radius            1.2632732985815067
                                 mass_smaller_3 radius             0.949951254765336
random_forest     PARSEC         Base           radius            1.8410733083557265
                                 mass_smaller_3 radius            1.8728481720300576
xgboost           PARSEC         Base           radius            1.3726508129754227
                                 mass_smaller_3 radius            1.3281151282144188

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.07811 / 90 : 0.50835 / 95 : 0.91068 / 99 : 1.68888
                                 mass_smaller_3 radius             75 : 0.06712 / 90 : 0.85924 / 95 : 1.48307 / 99 : 1.80229
KNN               PARSEC         Base           radius              75 : 0.13204 / 90 : 0.54463 / 95 : 0.7077 / 99 : 1.13544
                                 mass_smaller_3 radius              75 : 0.4576 / 90 : 0.69305 / 95 : 0.90247 / 99 : 1.35522
linear_regression PARSEC         Base           radius               75 : 0.4692 / 90 : 0.6187 / 95 : 0.74639 / 99 : 1.09896
                                 mass_smaller_3 radius               75 : 0.547 / 90 : 0.68942 / 95 : 0.77209 / 99 : 0.88949
mlp               PARSEC         Base           radius             75 : 0.58918 / 90 : 0.71959 / 95 : 0.80987 / 99 : 1.03145
                                 mass_smaller_3 radius             75 : 0.59327 / 90 : 0.68334 / 95 : 0.73229 / 99 : 0.82022
random_forest     PARSEC         Base           radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
                                 mass_smaller_3 radius              75 : 0.3372 / 90 : 0.80704 / 95 : 1.10049 / 99 : 1.44024
xgboost           PARSEC         Base           radius              75 : 0.51575 / 90 : 0.67511 / 95 : 0.7715 / 99 : 1.00317
                                 mass_smaller_3 radius             75 : 0.51067 / 90 : 0.65038 / 95 : 0.72415 / 99 : 0.89627

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 3.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
KNN               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
linear_regression PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
mlp               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
random_forest     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
xgboost           PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.02946301764281367
                                 mass_smaller_3 radius             -0.9330922497996494
KNN               PARSEC         Base           radius              0.2126456955697713
                                 mass_smaller_3 radius            -0.46783962630115017
linear_regression PARSEC         Base           radius             0.40239652704002404
                                 mass_smaller_3 radius            -0.12787916890519835
mlp               PARSEC         Base           radius              0.4143768132236899
                                 mass_smaller_3 radius             -0.0893119161118534
random_forest     PARSEC         Base           radius             0.15865465480581487
                                 mass_smaller_3 radius             -0.5645747588756191
xgboost           PARSEC         Base           radius             0.32815972103674085
                                 mass_smaller_3 radius             -0.2251646750005729

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.4903637513845105
                                 mass_smaller_3 radius             0.5262572219362908
KNN               PARSEC         Base           radius            0.43601461223627697
                                 mass_smaller_3 radius             0.4662467664879875
linear_regression PARSEC         Base           radius              0.533016296734985
                                 mass_smaller_3 radius             0.4915146510520734
mlp               PARSEC         Base           radius            0.44264411891468897
                                 mass_smaller_3 radius            0.44790309998438826
random_forest     PARSEC         Base           radius             0.4460226626254374
                                 mass_smaller_3 radius             0.4762926991048335
xgboost           PARSEC         Base           radius            0.44149755833283194
                                 mass_smaller_3 radius             0.4415617858022193

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.23538369789146726
                                 mass_smaller_3 radius            0.26561495858669637
KNN               PARSEC         Base           radius            0.23114155137514683
                                 mass_smaller_3 radius            0.25892717130089077
linear_regression PARSEC         Base           radius            0.42708321112310144
                                 mass_smaller_3 radius            0.35930891035661744
mlp               PARSEC         Base           radius             0.3197213842867725
                                 mass_smaller_3 radius            0.31264852610130883
random_forest     PARSEC         Base           radius             0.2255880172344884
                                 mass_smaller_3 radius             0.2529020865834376
xgboost           PARSEC         Base           radius            0.29753876544535374
                                 mass_smaller_3 radius             0.2773689705140357

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.03323089669044604
                                 mass_smaller_3 radius            0.033151113745310434
KNN               PARSEC         Base           radius               0.054727338410409
                                 mass_smaller_3 radius             0.06230087645619675
linear_regression PARSEC         Base           radius              0.3445574532685126
                                 mass_smaller_3 radius             0.25434597222935507
mlp               PARSEC         Base           radius              0.1951720251814788
                                 mass_smaller_3 radius             0.17520707437201888
random_forest     PARSEC         Base           radius             0.03876380575304095
                                 mass_smaller_3 radius            0.039830499274152276
xgboost           PARSEC         Base           radius             0.18021677749609738
                                 mass_smaller_3 radius             0.13000350013459738

                                                                                   CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                 0.48432930509787
                                 mass_smaller_3 radius             -0.05138340572707176
KNN               PARSEC         Base           radius               0.5586784851770883
                                 mass_smaller_3 radius             -0.07089920877731852
linear_regression PARSEC         Base           radius               0.6386077306015067
                                 mass_smaller_3 radius            -0.030605746658701118
mlp               PARSEC         Base           radius                0.647683215963242
                                 mass_smaller_3 radius             -0.08400726754254777
random_forest     PARSEC         Base           radius               0.5459579150223091
                                 mass_smaller_3 radius            -0.010074158034539975
xgboost           PARSEC         Base           radius               0.5745391025849726
                                 mass_smaller_3 radius             -0.07409150503503559

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.385359462647806
                                 mass_smaller_3 radius            2.3555532954792158
KNN               PARSEC         Base           radius            2.3172378341427184
                                 mass_smaller_3 radius            2.3170361323390436
linear_regression PARSEC         Base           radius             1.423367576672751
                                 mass_smaller_3 radius            1.4619464165080611
mlp               PARSEC         Base           radius            1.9906768274128068
                                 mass_smaller_3 radius            1.6083701045455463
random_forest     PARSEC         Base           radius             2.310296151725146
                                 mass_smaller_3 radius            2.3030305939409654
xgboost           PARSEC         Base           radius             2.261232186873491
                                 mass_smaller_3 radius             2.308647204488007

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.21021 / 90 : 0.9022 / 95 : 1.26428 / 99 : 1.91484
                                 mass_smaller_3 radius             75 : 0.29907 / 90 : 0.98619 / 95 : 1.32354 / 99 : 1.93994
KNN               PARSEC         Base           radius              75 : 0.3004 / 90 : 0.76603 / 95 : 1.04217 / 99 : 1.84744
                                 mass_smaller_3 radius               75 : 0.37173 / 90 : 0.82247 / 95 : 1.0769 / 99 : 1.8932
linear_regression PARSEC         Base           radius             75 : 0.63518 / 90 : 0.90864 / 95 : 1.08583 / 99 : 1.23233
                                 mass_smaller_3 radius             75 : 0.46682 / 90 : 0.94571 / 95 : 1.11289 / 99 : 1.29303
mlp               PARSEC         Base           radius              75 : 0.44388 / 90 : 0.81582 / 95 : 1.00769 / 99 : 1.2349
                                 mass_smaller_3 radius             75 : 0.44437 / 90 : 0.85005 / 95 : 1.02951 / 99 : 1.25741
random_forest     PARSEC         Base           radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
                                 mass_smaller_3 radius              75 : 0.3279 / 90 : 0.87845 / 95 : 1.14836 / 99 : 1.84111
xgboost           PARSEC         Base           radius             75 : 0.43744 / 90 : 0.74514 / 95 : 0.97449 / 99 : 1.46297
                                 mass_smaller_3 radius              75 : 0.3877 / 90 : 0.79763 / 95 : 1.00973 / 99 : 1.56273

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 4.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
KNN               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
linear_regression PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
mlp               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
random_forest     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
xgboost           PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.955620286412061
                                 mass_smaller_3 radius             0.5472382672914728
KNN               PARSEC         Base           radius             0.9504855107562155
                                 mass_smaller_3 radius            0.32842372582011825
linear_regression PARSEC         Base           radius             0.7084371651989534
                                 mass_smaller_3 radius            -0.8336303698007064
mlp               PARSEC         Base           radius             0.8215956330914591
                                 mass_smaller_3 radius            -1.0286431546556236
random_forest     PARSEC         Base           radius             0.9621702735006398
                                 mass_smaller_3 radius             0.5693692452409231
xgboost           PARSEC         Base           radius             0.9067948297537736
                                 mass_smaller_3 radius             0.4280597852922512

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.06341420958190282
                                 mass_smaller_3 radius            0.049324340834726234
KNN               PARSEC         Base           radius              0.0669811006524331
                                 mass_smaller_3 radius             0.05994582584176247
linear_regression PARSEC         Base           radius             0.26144268756230293
                                 mass_smaller_3 radius             0.19840935212881075
mlp               PARSEC         Base           radius              0.1652573269566529
                                 mass_smaller_3 radius             0.14894403454528876
random_forest     PARSEC         Base           radius             0.05854848516325554
                                 mass_smaller_3 radius               0.048119276752695
xgboost           PARSEC         Base           radius             0.09965114225438286
                                 mass_smaller_3 radius             0.05763696437770313

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.02159202040873627
                                 mass_smaller_3 radius             0.02061003944030581
KNN               PARSEC         Base           radius             0.02401669344408429
                                 mass_smaller_3 radius             0.02233752092815773
linear_regression PARSEC         Base           radius             0.20969472784333076
                                 mass_smaller_3 radius             0.18207963853249468
mlp               PARSEC         Base           radius             0.11676079932176552
                                 mass_smaller_3 radius             0.11621983574137043
random_forest     PARSEC         Base           radius            0.021491570434441845
                                 mass_smaller_3 radius             0.02055111897999929
xgboost           PARSEC         Base           radius             0.05342207596724462
                                 mass_smaller_3 radius            0.034907698087998866

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.004419931983550951
                                 mass_smaller_3 radius             0.004948289058039235
KNN               PARSEC         Base           radius            0.0021175757987152988
                                 mass_smaller_3 radius            0.0022124717172875563
linear_regression PARSEC         Base           radius              0.18887631683240547
                                 mass_smaller_3 radius              0.19386677933122742
mlp               PARSEC         Base           radius              0.08020351535631742
                                 mass_smaller_3 radius              0.09469860849448009
random_forest     PARSEC         Base           radius             0.004534967156486047
                                 mass_smaller_3 radius            0.0050174952592660915
xgboost           PARSEC         Base           radius             0.023085902380919787
                                 mass_smaller_3 radius             0.018800382563634477

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9776881908040265
                                 mass_smaller_3 radius             0.8269489220885603
KNN               PARSEC         Base           radius             0.9751848834547058
                                 mass_smaller_3 radius              0.777409997990249
linear_regression PARSEC         Base           radius             0.8876723080274312
                                 mass_smaller_3 radius            0.27229610134162063
mlp               PARSEC         Base           radius             0.9198956642376998
                                 mass_smaller_3 radius             0.4714277176746543
random_forest     PARSEC         Base           radius             0.9809328484849373
                                 mass_smaller_3 radius             0.8329855500178989
xgboost           PARSEC         Base           radius             0.9577760766716373
                                 mass_smaller_3 radius             0.7180532680216085

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.7650343537442144
                                 mass_smaller_3 radius             1.1059119821850276
KNN               PARSEC         Base           radius             1.7506203509415466
                                 mass_smaller_3 radius               0.61135975949587
linear_regression PARSEC         Base           radius             0.9612784106621741
                                 mass_smaller_3 radius            0.48630957221819804
mlp               PARSEC         Base           radius             1.1734950373746966
                                 mass_smaller_3 radius             0.7356309221400916
random_forest     PARSEC         Base           radius              1.743523039119606
                                 mass_smaller_3 radius              1.017409421876096
xgboost           PARSEC         Base           radius             0.7897854198667069
                                 mass_smaller_3 radius             0.5816839944946661

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.02116 / 90 : 0.05107 / 95 : 0.08715 / 99 : 0.24579
                                 mass_smaller_3 radius             75 : 0.02162 / 90 : 0.05154 / 95 : 0.09057 / 99 : 0.21606
KNN               PARSEC         Base           radius             75 : 0.00859 / 90 : 0.08998 / 95 : 0.16848 / 99 : 0.25098
                                 mass_smaller_3 radius             75 : 0.00821 / 90 : 0.08176 / 95 : 0.16313 / 99 : 0.24025
linear_regression PARSEC         Base           radius             75 : 0.23824 / 90 : 0.28693 / 95 : 0.64321 / 99 : 0.78988
                                 mass_smaller_3 radius             75 : 0.24083 / 90 : 0.28046 / 95 : 0.29632 / 99 : 0.31766
mlp               PARSEC         Base           radius             75 : 0.15069 / 90 : 0.24565 / 95 : 0.36761 / 99 : 0.57346
                                 mass_smaller_3 radius             75 : 0.15611 / 90 : 0.24325 / 95 : 0.31164 / 99 : 0.41249
random_forest     PARSEC         Base           radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
                                 mass_smaller_3 radius             75 : 0.02171 / 90 : 0.05158 / 95 : 0.08985 / 99 : 0.21559
xgboost           PARSEC         Base           radius             75 : 0.05941 / 90 : 0.13327 / 95 : 0.19754 / 99 : 0.46263
                                 mass_smaller_3 radius             75 : 0.04624 / 90 : 0.08593 / 95 : 0.11762 / 99 : 0.22241

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 5.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
KNN               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
linear_regression PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
mlp               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
random_forest     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
xgboost           PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9761610949531048
                                 mass_smaller_3 radius             0.7814373029112099
KNN               PARSEC         Base           radius             0.9810026567945801
                                 mass_smaller_3 radius             0.9645065051911283
linear_regression PARSEC         Base           radius             0.6936214748871703
                                 mass_smaller_3 radius            -0.3964676844578261
mlp               PARSEC         Base           radius             0.7905570860440205
                                 mass_smaller_3 radius            -0.1946802397138625
random_forest     PARSEC         Base           radius             0.9833215630488885
                                 mass_smaller_3 radius             0.8929394429365533
xgboost           PARSEC         Base           radius             0.8909704249855909
                                 mass_smaller_3 radius             0.7443264863863341

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.07455089392624331
                                 mass_smaller_3 radius            0.038217587148684895
KNN               PARSEC         Base           radius             0.06677184999270079
                                 mass_smaller_3 radius            0.015509602024441337
linear_regression PARSEC         Base           radius             0.41248818706480006
                                 mass_smaller_3 radius             0.24546889584204587
mlp               PARSEC         Base           radius              0.2456399951429642
                                 mass_smaller_3 radius             0.09003793207860139
random_forest     PARSEC         Base           radius             0.06235858799879652
                                 mass_smaller_3 radius            0.026947837505247645
xgboost           PARSEC         Base           radius             0.16460758707216622
                                 mass_smaller_3 radius             0.04423196006989856

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.01708858666755633
                                 mass_smaller_3 radius            0.006064160573840622
KNN               PARSEC         Base           radius             0.02578917817801487
                                 mass_smaller_3 radius            0.004961669663094179
linear_regression PARSEC         Base           radius              0.3613406262384508
                                 mass_smaller_3 radius             0.22654569251941534
mlp               PARSEC         Base           radius             0.18339354368706592
                                 mass_smaller_3 radius             0.07267934776132995
random_forest     PARSEC         Base           radius             0.01750445369583531
                                 mass_smaller_3 radius            0.007932542080921262
xgboost           PARSEC         Base           radius             0.11280228324849544
                                 mass_smaller_3 radius            0.030504279594149763

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0005723644632364966
                                 mass_smaller_3 radius            0.00047703704478119224
KNN               PARSEC         Base           radius                0.0019053567981413
                                 mass_smaller_3 radius             0.0006023351400117338
linear_regression PARSEC         Base           radius                0.3421354125013407
                                 mass_smaller_3 radius               0.23410488962537546
mlp               PARSEC         Base           radius               0.13197290158446684
                                 mass_smaller_3 radius               0.06432920711121848
random_forest     PARSEC         Base           radius              0.000767228879044568
                                 mass_smaller_3 radius             0.0005515727925315961
xgboost           PARSEC         Base           radius               0.06626665562742962
                                 mass_smaller_3 radius              0.020410160829255508

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9881339932310456
                                 mass_smaller_3 radius             0.9026259569825558
KNN               PARSEC         Base           radius             0.9905459125164942
                                 mass_smaller_3 radius             0.9823878588468848
linear_regression PARSEC         Base           radius             0.8405054746921199
                                 mass_smaller_3 radius             0.8014000931277628
mlp               PARSEC         Base           radius             0.9044015052723806
                                 mass_smaller_3 radius            0.35215172443664977
random_forest     PARSEC         Base           radius             0.9916566947756928
                                 mass_smaller_3 radius             0.9490747005848708
xgboost           PARSEC         Base           radius             0.9457856207944926
                                 mass_smaller_3 radius             0.8758676293580796

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.5057783282948216
                                 mass_smaller_3 radius             0.7113066837691322
KNN               PARSEC         Base           radius              1.024449153836383
                                 mass_smaller_3 radius            0.38799515721747835
linear_regression PARSEC         Base           radius              1.087497647916335
                                 mass_smaller_3 radius            0.46360599668719993
mlp               PARSEC         Base           radius             1.0720720071726242
                                 mass_smaller_3 radius             0.3638719861686015
random_forest     PARSEC         Base           radius             1.0173073204712826
                                 mass_smaller_3 radius            0.34711194509974175
xgboost           PARSEC         Base           radius             0.9919143971648867
                                 mass_smaller_3 radius            0.34005165922888625

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00213 / 90 : 0.02711 / 95 : 0.07076 / 99 : 0.37473
                                 mass_smaller_3 radius             75 : 0.00093 / 90 : 0.00181 / 95 : 0.00807 / 99 : 0.20827
KNN               PARSEC         Base           radius             75 : 0.02562 / 90 : 0.06674 / 95 : 0.11563 / 99 : 0.32208
                                 mass_smaller_3 radius             75 : 0.00187 / 90 : 0.01411 / 95 : 0.02851 / 99 : 0.06447
linear_regression PARSEC         Base           radius                75 : 0.52905 / 90 : 0.63795 / 95 : 0.68 / 99 : 0.75724
                                 mass_smaller_3 radius             75 : 0.29668 / 90 : 0.34515 / 95 : 0.36162 / 99 : 0.38675
mlp               PARSEC         Base           radius              75 : 0.26965 / 90 : 0.42654 / 95 : 0.50947 / 99 : 0.6911
                                 mass_smaller_3 radius              75 : 0.09908 / 90 : 0.1441 / 95 : 0.17159 / 99 : 0.24825
random_forest     PARSEC         Base           radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
                                 mass_smaller_3 radius             75 : 0.00272 / 90 : 0.01729 / 95 : 0.04211 / 99 : 0.13869
xgboost           PARSEC         Base           radius             75 : 0.17244 / 90 : 0.27989 / 95 : 0.34668 / 99 : 0.52946
                                 mass_smaller_3 radius             75 : 0.04005 / 90 : 0.07041 / 95 : 0.09715 / 99 : 0.15125

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 6.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
KNN               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
linear_regression PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
mlp               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
random_forest     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
xgboost           PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.9590838171586634
                                 mass_smaller_3 radius              0.8901791420736058
KNN               PARSEC         Base           radius              0.9629697658705128
                                 mass_smaller_3 radius              0.8299459557606574
linear_regression PARSEC         Base           radius             -0.1780265156579326
                                 mass_smaller_3 radius            -0.35462831819438545
mlp               PARSEC         Base           radius              0.6180409605152396
                                 mass_smaller_3 radius             -0.2773693742034451
random_forest     PARSEC         Base           radius              0.9697670887087206
                                 mass_smaller_3 radius              0.9328840101426675
xgboost           PARSEC         Base           radius               0.769792515363512
                                 mass_smaller_3 radius             0.45194161207274786

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.07710366131236392
                                 mass_smaller_3 radius              0.0319962014335555
KNN               PARSEC         Base           radius             0.07336873948132151
                                 mass_smaller_3 radius            0.040932981154472386
linear_regression PARSEC         Base           radius              0.5223847164290274
                                 mass_smaller_3 radius             0.12931194582653843
mlp               PARSEC         Base           radius              0.2720273473516592
                                 mass_smaller_3 radius             0.18511855365247315
random_forest     PARSEC         Base           radius             0.06632705239911885
                                 mass_smaller_3 radius             0.02502506810081321
xgboost           PARSEC         Base           radius              0.1905818443404726
                                 mass_smaller_3 radius             0.07985654117355773

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.022776610588325197
                                 mass_smaller_3 radius            0.015753888496454357
KNN               PARSEC         Base           radius             0.04166830194669774
                                 mass_smaller_3 radius             0.03152288184815854
linear_regression PARSEC         Base           radius              0.4815810448410679
                                 mass_smaller_3 radius             0.10139189596401278
mlp               PARSEC         Base           radius             0.22403130056654885
                                 mass_smaller_3 radius             0.15857075425837003
random_forest     PARSEC         Base           radius             0.02199490853649632
                                 mass_smaller_3 radius            0.014616888347962017
xgboost           PARSEC         Base           radius              0.1498862826198757
                                 mass_smaller_3 radius             0.06113557032451997

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.00870387997298483
                                 mass_smaller_3 radius            0.009029316541800059
KNN               PARSEC         Base           radius             0.02615840264183933
                                 mass_smaller_3 radius            0.025353309054399142
linear_regression PARSEC         Base           radius              0.4761420456167055
                                 mass_smaller_3 radius             0.08209654511713893
mlp               PARSEC         Base           radius             0.19861505214230768
                                 mass_smaller_3 radius             0.15001463390151648
random_forest     PARSEC         Base           radius            0.007358222039419937
                                 mass_smaller_3 radius            0.007878084020764398
xgboost           PARSEC         Base           radius             0.12394579245609716
                                 mass_smaller_3 radius             0.04875754543333888

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9796178563497766
                                 mass_smaller_3 radius             0.9462666999561264
KNN               PARSEC         Base           radius             0.9813761923561958
                                 mass_smaller_3 radius             0.9111394452784567
linear_regression PARSEC         Base           radius             0.5867748937794232
                                 mass_smaller_3 radius             0.7747078206853004
mlp               PARSEC         Base           radius             0.7909518021844507
                                 mass_smaller_3 radius            0.20303152951224382
random_forest     PARSEC         Base           radius             0.9848075867184325
                                 mass_smaller_3 radius             0.9662451252072484
xgboost           PARSEC         Base           radius             0.8782788575526104
                                 mass_smaller_3 radius              0.749992482346073

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.5334413077139653
                                 mass_smaller_3 radius             0.6934718758359137
KNN               PARSEC         Base           radius             1.0892491343411437
                                 mass_smaller_3 radius            0.18171588646056636
linear_regression PARSEC         Base           radius              1.075929559325979
                                 mass_smaller_3 radius             0.4477054589905358
mlp               PARSEC         Base           radius             0.9408848622829691
                                 mass_smaller_3 radius            0.44537434673666687
random_forest     PARSEC         Base           radius             1.1110629174530526
                                 mass_smaller_3 radius              0.288983406772515
xgboost           PARSEC         Base           radius             0.7657090029730922
                                 mass_smaller_3 radius            0.26873545478870087

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.0216 / 90 : 0.03985 / 95 : 0.06493 / 99 : 0.33128
                                 mass_smaller_3 radius             75 : 0.02187 / 90 : 0.03853 / 95 : 0.05444 / 99 : 0.10862
KNN               PARSEC         Base           radius             75 : 0.04965 / 90 : 0.08372 / 95 : 0.12244 / 99 : 0.30325
                                 mass_smaller_3 radius              75 : 0.04407 / 90 : 0.06735 / 95 : 0.0835 / 99 : 0.11486
linear_regression PARSEC         Base           radius              75 : 0.63804 / 90 : 0.74171 / 95 : 0.7997 / 99 : 0.91087
                                 mass_smaller_3 radius              75 : 0.14655 / 90 : 0.2121 / 95 : 0.26202 / 99 : 0.34608
mlp               PARSEC         Base           radius               75 : 0.32184 / 90 : 0.44405 / 95 : 0.51372 / 99 : 0.646
                                 mass_smaller_3 radius             75 : 0.22481 / 90 : 0.28686 / 95 : 0.33359 / 99 : 0.39206
random_forest     PARSEC         Base           radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
                                 mass_smaller_3 radius              75 : 0.0212 / 90 : 0.03843 / 95 : 0.05048 / 99 : 0.08935
xgboost           PARSEC         Base           radius             75 : 0.21694 / 90 : 0.31853 / 95 : 0.38254 / 99 : 0.50061
                                 mass_smaller_3 radius               75 : 0.0838 / 90 : 0.13464 / 95 : 0.16785 / 99 : 0.2255

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Linear regression : 
- mass_smaller_3 : better/similar results to Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

Random forest : 
- mass_smaller_3 : worse results than Base on every metric

XGBoost : 
- mass_smaller_3 : better/similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse/similar results to Base on every metric

#### Conclusions on radius

When filtering using mass_smaller_3, the results mostly worsen except for XGBoost and linear regression.

#### Best models for the radius parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### log_g parameter

In [19]:
compare_metrics(path, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
KNN               PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
linear_regression PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
mlp               PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
random_forest     PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
xgboost           PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.7536570738013006
                                 mass_smaller_3 log_g              0.614496340978034
KNN               PARSEC         Base           log_g             0.7969225275315691
                                 mass_smaller_3 log_g             0.7074902482099952
linear_regression PARSEC         Base           log_g             0.1740171909362369
                                 mass_smaller_3 log_g             0.2780976672847234
mlp               PARSEC         Base           log_g             0.5075863573833721
                                 mass_smaller_3 log_g             0.4491367775194661
random_forest     PARSEC         Base           log_g             0.8074266704690882
                                 mass_smaller_3 log_g               0.70112405424908
xgboost           PARSEC         Base           log_g             0.7207144464742739
                                 mass_smaller_3 log_g             0.7103009735205652

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.5190543242870183
                                 mass_smaller_3 log_g              0.5741879827647468
KNN               PARSEC         Base           log_g             0.47145630056607196
                                 mass_smaller_3 log_g              0.5001617633029353
linear_regression PARSEC         Base           log_g               0.950442888851383
                                 mass_smaller_3 log_g              0.7857403351048409
mlp               PARSEC         Base           log_g              0.7345510679198198
                                 mass_smaller_3 log_g              0.6875342891265775
random_forest     PARSEC         Base           log_g              0.4589248718978013
                                 mass_smaller_3 log_g              0.5055751085850891
xgboost           PARSEC         Base           log_g              0.5526686841050604
                                 mass_smaller_3 log_g             0.49775238021746787

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.15060909496410327
                                 mass_smaller_3 log_g             0.17243286562331026
KNN               PARSEC         Base           log_g             0.16864683262044497
                                 mass_smaller_3 log_g             0.17779208622084253
linear_regression PARSEC         Base           log_g              0.7507155523234634
                                 mass_smaller_3 log_g              0.6022281394911589
mlp               PARSEC         Base           log_g              0.5010944235421306
                                 mass_smaller_3 log_g             0.46154356314230977
random_forest     PARSEC         Base           log_g             0.14624083345990166
                                 mass_smaller_3 log_g             0.16660204760430417
xgboost           PARSEC         Base           log_g               0.313614388728856
                                 mass_smaller_3 log_g              0.2428021744059252

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.01100000000000012
                                 mass_smaller_3 log_g             0.010500000000000398
KNN               PARSEC         Base           log_g             0.013200000000000323
                                 mass_smaller_3 log_g             0.009200000000000763
linear_regression PARSEC         Base           log_g               0.5052899263280148
                                 mass_smaller_3 log_g               0.4288445972044663
mlp               PARSEC         Base           log_g              0.25958360258796387
                                 mass_smaller_3 log_g              0.23512261336306195
random_forest     PARSEC         Base           log_g             0.012716574855699436
                                 mass_smaller_3 log_g             0.012856708461763011
xgboost           PARSEC         Base           log_g              0.10713393402099625
                                 mass_smaller_3 log_g              0.06981694793701188

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.8738266108931796
                                 mass_smaller_3 log_g              0.7996749450421449
KNN               PARSEC         Base           log_g              0.8935178759114629
                                 mass_smaller_3 log_g              0.8426181338086113
linear_regression PARSEC         Base           log_g             0.41715368143690107
                                 mass_smaller_3 log_g              0.5273496655379108
mlp               PARSEC         Base           log_g              0.7124610004519873
                                 mass_smaller_3 log_g              0.6706293959928037
random_forest     PARSEC         Base           log_g              0.8998465625312148
                                 mass_smaller_3 log_g              0.8408310250847246
xgboost           PARSEC         Base           log_g              0.8494127272684615
                                 mass_smaller_3 log_g              0.8431824079541927

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              4.779999999999999
                                 mass_smaller_3 log_g                           4.75
KNN               PARSEC         Base           log_g                         4.6354
                                 mass_smaller_3 log_g              4.634999999999999
linear_regression PARSEC         Base           log_g             3.3549603792326215
                                 mass_smaller_3 log_g              2.936832576342485
mlp               PARSEC         Base           log_g              3.893785889637569
                                 mass_smaller_3 log_g             3.4309115370204775
random_forest     PARSEC         Base           log_g              4.620864250000007
                                 mass_smaller_3 log_g             4.6063405009041585
xgboost           PARSEC         Base           log_g              4.357620960235596
                                 mass_smaller_3 log_g              4.618734474182129

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 0.05772 / 90 : 0.22267 / 95 : 0.89533 / 99 : 2.907
                                 mass_smaller_3 log_g                  75 : 0.05442 / 90 : 0.28814 / 95 : 1.209 / 99 : 3.101
KNN               PARSEC         Base           log_g                 75 : 0.0886 / 90 : 0.4462 / 95 : 1.0346 / 99 : 2.24206
                                 mass_smaller_3 log_g                  75 : 0.062 / 90 : 0.5692 / 95 : 1.1544 / 99 : 2.32292
linear_regression PARSEC         Base           log_g              75 : 1.13119 / 90 : 1.62211 / 95 : 1.88341 / 99 : 2.41107
                                 mass_smaller_3 log_g              75 : 0.75872 / 90 : 1.39948 / 95 : 1.73583 / 99 : 2.20171
mlp               PARSEC         Base           log_g              75 : 0.73311 / 90 : 1.41779 / 95 : 1.65723 / 99 : 2.18019
                                 mass_smaller_3 log_g               75 : 0.6676 / 90 : 1.28453 / 95 : 1.61766 / 99 : 2.07739
random_forest     PARSEC         Base           log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                 mass_smaller_3 log_g              75 : 0.06329 / 90 : 0.38362 / 95 : 1.14334 / 99 : 2.48512
xgboost           PARSEC         Base           log_g               75 : 0.40285 / 90 : 0.95171 / 95 : 1.2855 / 99 : 2.01364
                                 mass_smaller_3 log_g              75 : 0.22379 / 90 : 0.76868 / 95 : 1.18554 / 99 : 2.04576

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
KNN               PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
linear_regression PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
mlp               PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
random_forest     PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
xgboost           PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              -0.22366302531475957
                                 mass_smaller_3 log_g               -0.4913583627937592
KNN               PARSEC         Base           log_g               -0.5685510473572672
                                 mass_smaller_3 log_g              -0.21372743099124003
linear_regression PARSEC         Base           log_g               -1.2252488306693854
                                 mass_smaller_3 log_g                -3.275418831406798
mlp               PARSEC         Base           log_g                -4.371543636897526
                                 mass_smaller_3 log_g                -3.868650811787682
random_forest     PARSEC         Base           log_g               0.17211468827279353
                                 mass_smaller_3 log_g             -0.011329182377379121
xgboost           PARSEC         Base           log_g               -1.0124875678765508
                                 mass_smaller_3 log_g               -0.6001570140062298

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.3804738903721785
                                 mass_smaller_3 log_g             0.40044279595694104
KNN               PARSEC         Base           log_g              0.4433203725835331
                                 mass_smaller_3 log_g              0.3684311737170496
linear_regression PARSEC         Base           log_g              1.4736793628524247
                                 mass_smaller_3 log_g              1.2034244710801263
mlp               PARSEC         Base           log_g              1.0634881908332428
                                 mass_smaller_3 log_g               0.938630709588942
random_forest     PARSEC         Base           log_g             0.31598778809171013
                                 mass_smaller_3 log_g             0.33344741344998047
xgboost           PARSEC         Base           log_g                0.55356010503011
                                 mass_smaller_3 log_g              0.4608442281579774

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.0674954147134116
                                 mass_smaller_3 log_g             0.07341851606825935
KNN               PARSEC         Base           log_g              0.1346078724936512
                                 mass_smaller_3 log_g             0.10335706411523063
linear_regression PARSEC         Base           log_g              1.3839826888373719
                                 mass_smaller_3 log_g              1.0842145783746058
mlp               PARSEC         Base           log_g              0.7790407681121997
                                 mass_smaller_3 log_g              0.6733604896505861
random_forest     PARSEC         Base           log_g             0.07025955886257117
                                 mass_smaller_3 log_g              0.0779484265301924
xgboost           PARSEC         Base           log_g             0.31917765404091575
                                 mass_smaller_3 log_g             0.25720931950684656

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.0007500000000000284
                                 mass_smaller_3 log_g             0.0009999999999994458
KNN               PARSEC         Base           log_g              0.007000000000000561
                                 mass_smaller_3 log_g              0.005199999999999427
linear_regression PARSEC         Base           log_g                 1.318829272889185
                                 mass_smaller_3 log_g                1.1140769299772573
mlp               PARSEC         Base           log_g                 0.578821821548086
                                 mass_smaller_3 log_g                0.3018774212820845
random_forest     PARSEC         Base           log_g             0.0009799999999917652
                                 mass_smaller_3 log_g             0.0009199999999998099
xgboost           PARSEC         Base           log_g               0.09096437835693338
                                 mass_smaller_3 log_g               0.07795264053344741

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.7053404051445747
                                 mass_smaller_3 log_g              0.6684831846270675
KNN               PARSEC         Base           log_g               0.726834275461127
                                 mass_smaller_3 log_g              0.7127792459877859
linear_regression PARSEC         Base           log_g             0.33703567351467884
                                 mass_smaller_3 log_g              0.5893814048738154
mlp               PARSEC         Base           log_g              0.7792055306173461
                                 mass_smaller_3 log_g              0.7249651329375316
random_forest     PARSEC         Base           log_g              0.7759789538352955
                                 mass_smaller_3 log_g              0.7416104362495699
xgboost           PARSEC         Base           log_g              0.8095818883794095
                                 mass_smaller_3 log_g              0.7734199570754127

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              4.779999999999999
                                 mass_smaller_3 log_g                           4.75
KNN               PARSEC         Base           log_g                          4.513
                                 mass_smaller_3 log_g              4.341399999999999
linear_regression PARSEC         Base           log_g             3.3549603792326215
                                 mass_smaller_3 log_g              2.223276704591555
mlp               PARSEC         Base           log_g             2.7110084335766444
                                 mass_smaller_3 log_g              1.965581096787684
random_forest     PARSEC         Base           log_g              4.226316213803089
                                 mass_smaller_3 log_g              4.061556465099716
xgboost           PARSEC         Base           log_g              3.585430902481079
                                 mass_smaller_3 log_g             3.6259056000709533

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                     75 : 0.006 / 90 : 0.026 / 95 : 0.064 / 99 : 1.9685
                                 mass_smaller_3 log_g                   75 : 0.004 / 90 : 0.02 / 95 : 0.06495 / 99 : 1.94447
KNN               PARSEC         Base           log_g                  75 : 0.0274 / 90 : 0.2318 / 95 : 0.848 / 99 : 2.22856
                                 mass_smaller_3 log_g                  75 : 0.0188 / 90 : 0.068 / 95 : 0.7936 / 99 : 1.89692
linear_regression PARSEC         Base           log_g               75 : 1.74379 / 90 : 2.02828 / 95 : 2.27583 / 99 : 2.7985
                                 mass_smaller_3 log_g                75 : 1.4902 / 90 : 1.7786 / 95 : 1.87714 / 99 : 2.02769
mlp               PARSEC         Base           log_g              75 : 1.51463 / 90 : 1.68943 / 95 : 1.85061 / 99 : 2.26065
                                 mass_smaller_3 log_g                75 : 1.337 / 90 : 1.67464 / 95 : 1.76603 / 99 : 1.86737
random_forest     PARSEC         Base           log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                 mass_smaller_3 log_g              75 : 0.00543 / 90 : 0.06492 / 95 : 0.42355 / 99 : 1.79859
xgboost           PARSEC         Base           log_g              75 : 0.43347 / 90 : 1.03051 / 95 : 1.34273 / 99 : 1.90141
                                 mass_smaller_3 log_g                 75 : 0.32566 / 90 : 0.798 / 95 : 1.10784 / 99 : 1.6715

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 2.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
KNN               PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
linear_regression PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
mlp               PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
random_forest     PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
xgboost           PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.20108117139632975
                                 mass_smaller_3 log_g                 -5.81812692567734
KNN               PARSEC         Base           log_g                 0.551332428608432
                                 mass_smaller_3 log_g               -2.5068845861149858
linear_regression PARSEC         Base           log_g               0.20729145625045087
                                 mass_smaller_3 log_g             -0.027980441684109847
mlp               PARSEC         Base           log_g               0.42018335004606344
                                 mass_smaller_3 log_g               -0.9837728761605316
random_forest     PARSEC         Base           log_g                0.4626143591760997
                                 mass_smaller_3 log_g               -3.2568541084898603
xgboost           PARSEC         Base           log_g               0.35000992847659496
                                 mass_smaller_3 log_g               -1.3121363760708706

                                                                                RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.7561211004774188
                                 mass_smaller_3 log_g             1.0463984851401869
KNN               PARSEC         Base           log_g             0.5921304852198191
                                 mass_smaller_3 log_g             0.8098841803265027
linear_regression PARSEC         Base           log_g             0.8048821107537918
                                 mass_smaller_3 log_g             0.9174628418935944
mlp               PARSEC         Base           log_g             0.9489659448639525
                                 mass_smaller_3 log_g             0.9294766901798789
random_forest     PARSEC         Base           log_g             0.6322730705325913
                                 mass_smaller_3 log_g             0.8598902436974643
xgboost           PARSEC         Base           log_g              0.832163042077831
                                 mass_smaller_3 log_g             0.7987716167825999

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.30299790989997644
                                 mass_smaller_3 log_g              0.4757052385721764
KNN               PARSEC         Base           log_g             0.30719576100433976
                                 mass_smaller_3 log_g              0.4724216773162939
linear_regression PARSEC         Base           log_g              0.6640426255531428
                                 mass_smaller_3 log_g              0.8411477623788803
mlp               PARSEC         Base           log_g              0.8097761783822659
                                 mass_smaller_3 log_g              0.8202772569017484
random_forest     PARSEC         Base           log_g              0.2893723786433942
                                 mass_smaller_3 log_g             0.44883480568115963
xgboost           PARSEC         Base           log_g              0.6713615037908816
                                 mass_smaller_3 log_g              0.6331751794297094

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.06000000000000005
                                 mass_smaller_3 log_g              0.03200000000000003
KNN               PARSEC         Base           log_g              0.09160000000000013
                                 mass_smaller_3 log_g              0.07390000000000008
linear_regression PARSEC         Base           log_g               0.6125379386601224
                                 mass_smaller_3 log_g                0.828322316142847
mlp               PARSEC         Base           log_g               0.8322471385767223
                                 mass_smaller_3 log_g               0.8687189969637106
random_forest     PARSEC         Base           log_g              0.06806103589466095
                                 mass_smaller_3 log_g             0.051811014568760694
xgboost           PARSEC         Base           log_g               0.5849574146270751
                                 mass_smaller_3 log_g               0.5260204954147338

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.6543935473449031
                                 mass_smaller_3 log_g              0.04590994627709065
KNN               PARSEC         Base           log_g               0.7693849003643232
                                 mass_smaller_3 log_g              0.05468711496212319
linear_regression PARSEC         Base           log_g                0.493104879406129
                                 mass_smaller_3 log_g              0.32866941676222167
mlp               PARSEC         Base           log_g               0.6521638888149588
                                 mass_smaller_3 log_g             -0.26171239282065073
random_forest     PARSEC         Base           log_g                0.737427211287738
                                 mass_smaller_3 log_g              0.09053666406842789
xgboost           PARSEC         Base           log_g               0.6120898372154866
                                 mass_smaller_3 log_g              0.08962101173691343

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                          4.171
                                 mass_smaller_3 log_g              4.218000000000001
KNN               PARSEC         Base           log_g             3.9669999999999996
                                 mass_smaller_3 log_g             3.9967999999999995
linear_regression PARSEC         Base           log_g              2.888378364365141
                                 mass_smaller_3 log_g             1.9747558791773958
mlp               PARSEC         Base           log_g              2.375105573667385
                                 mass_smaller_3 log_g             1.8524857842642022
random_forest     PARSEC         Base           log_g             3.6829900000000007
                                 mass_smaller_3 log_g                          3.747
xgboost           PARSEC         Base           log_g              2.695528434753418
                                 mass_smaller_3 log_g              2.927567584991455

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              75 : 0.15628 / 90 : 1.01729 / 95 : 1.81952 / 99 : 3.37886
                                 mass_smaller_3 log_g                   75 : 0.13406 / 90 : 1.7185 / 95 : 2.965 / 99 : 3.604
KNN               PARSEC         Base           log_g                 75 : 0.2642 / 90 : 1.089 / 95 : 1.41552 / 99 : 2.27112
                                 mass_smaller_3 log_g               75 : 0.91525 / 90 : 1.3874 / 95 : 1.80435 / 99 : 2.71107
linear_regression PARSEC         Base           log_g              75 : 0.93956 / 90 : 1.24051 / 95 : 1.47758 / 99 : 2.09846
                                 mass_smaller_3 log_g               75 : 1.08461 / 90 : 1.3396 / 95 : 1.49714 / 99 : 1.71783
mlp               PARSEC         Base           log_g              75 : 1.17152 / 90 : 1.42053 / 95 : 1.61857 / 99 : 2.05238
                                 mass_smaller_3 log_g               75 : 1.1808 / 90 : 1.36753 / 95 : 1.46222 / 99 : 1.63853
random_forest     PARSEC         Base           log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                 mass_smaller_3 log_g              75 : 0.67449 / 90 : 1.61414 / 95 : 2.20096 / 99 : 2.88029
xgboost           PARSEC         Base           log_g               75 : 1.02779 / 90 : 1.3463 / 95 : 1.53656 / 99 : 1.99333
                                 mass_smaller_3 log_g               75 : 1.02728 / 90 : 1.29965 / 95 : 1.4458 / 99 : 1.79904

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 3.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
KNN               PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
linear_regression PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
mlp               PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
random_forest     PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
xgboost           PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              -0.4342441850216521
                                 mass_smaller_3 log_g               -0.880261906687066
KNN               PARSEC         Base           log_g             -0.09689368389630881
                                 mass_smaller_3 log_g               -0.427641034000505
linear_regression PARSEC         Base           log_g              0.16872633450213492
                                 mass_smaller_3 log_g             -0.07393039338067586
mlp               PARSEC         Base           log_g              0.20179797271613364
                                 mass_smaller_3 log_g             -0.08999932766193641
random_forest     PARSEC         Base           log_g             -0.17211974773342287
                                 mass_smaller_3 log_g              -0.5217660400358439
xgboost           PARSEC         Base           log_g              0.06308841876492932
                                 mass_smaller_3 log_g                -0.19417234585858

                                                                                RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.9806733151868601
                                 mass_smaller_3 log_g             1.0524628039553423
KNN               PARSEC         Base           log_g              0.871943985963139
                                 mass_smaller_3 log_g             0.9324055656208091
linear_regression PARSEC         Base           log_g             1.0376784628560318
                                 mass_smaller_3 log_g             0.9684705976926009
mlp               PARSEC         Base           log_g             0.8787774752504091
                                 mass_smaller_3 log_g             0.9170710825508944
random_forest     PARSEC         Base           log_g             0.8919685917893991
                                 mass_smaller_3 log_g             0.9525083924664207
xgboost           PARSEC         Base           log_g             0.8838233864363637
                                 mass_smaller_3 log_g              0.884134270404242

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.4706731696496021
                                 mass_smaller_3 log_g              0.5311386742407748
KNN               PARSEC         Base           log_g              0.4621658142408975
                                 mass_smaller_3 log_g              0.5177275635100691
linear_regression PARSEC         Base           log_g               0.824557446497259
                                 mass_smaller_3 log_g               0.703052358506027
mlp               PARSEC         Base           log_g              0.6335271542640621
                                 mass_smaller_3 log_g              0.6460260954776122
random_forest     PARSEC         Base           log_g             0.45107542838461695
                                 mass_smaller_3 log_g              0.5057081491788876
xgboost           PARSEC         Base           log_g               0.596223000234553
                                 mass_smaller_3 log_g              0.5557107972143425

                                                                                MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.06618847006651918
                                 mass_smaller_3 log_g              0.0662121212121205
KNN               PARSEC         Base           log_g             0.10949999999999993
                                 mass_smaller_3 log_g              0.1245999999999996
linear_regression PARSEC         Base           log_g              0.6483713689644435
                                 mass_smaller_3 log_g             0.48444218901040426
mlp               PARSEC         Base           log_g             0.38409884117374316
                                 mass_smaller_3 log_g             0.41266565000962974
random_forest     PARSEC         Base           log_g             0.07739903932491243
                                 mass_smaller_3 log_g             0.07966892748917664
xgboost           PARSEC         Base           log_g              0.3601102428436279
                                 mass_smaller_3 log_g              0.2606408271789551

                                                                                    CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                  0.240075575575364
                                 mass_smaller_3 log_g               -0.07296696718913202
KNN               PARSEC         Base           log_g                0.30429608142710995
                                 mass_smaller_3 log_g               -0.12680921360913017
linear_regression PARSEC         Base           log_g                0.41099301685375894
                                 mass_smaller_3 log_g              0.0006934333213137371
mlp               PARSEC         Base           log_g                0.45746960129678993
                                 mass_smaller_3 log_g             -0.0006398085089834495
random_forest     PARSEC         Base           log_g                0.30681622944559384
                                 mass_smaller_3 log_g               -0.03516617995366493
xgboost           PARSEC         Base           log_g                0.29917511289779664
                                 mass_smaller_3 log_g                -0.1010028439246436

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             4.7700000000000005
                                 mass_smaller_3 log_g                           4.71
KNN               PARSEC         Base           log_g                         4.6354
                                 mass_smaller_3 log_g              4.634999999999999
linear_regression PARSEC         Base           log_g              2.857540161797114
                                 mass_smaller_3 log_g              2.936832576342485
mlp               PARSEC         Base           log_g              3.893785889637569
                                 mass_smaller_3 log_g             3.4309115370204775
random_forest     PARSEC         Base           log_g              4.620864250000007
                                 mass_smaller_3 log_g             4.6063405009041585
xgboost           PARSEC         Base           log_g              4.357620960235596
                                 mass_smaller_3 log_g              4.618734474182129

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 0.42077 / 90 : 1.80427 / 95 : 2.529 / 99 : 3.83062
                                 mass_smaller_3 log_g                    75 : 0.597 / 90 : 1.973 / 95 : 2.648 / 99 : 3.88029
KNN               PARSEC         Base           log_g                 75 : 0.6006 / 90 : 1.5316 / 95 : 2.08425 / 99 : 3.6946
                                 mass_smaller_3 log_g               75 : 0.7435 / 90 : 1.64504 / 95 : 2.15458 / 99 : 3.78594
linear_regression PARSEC         Base           log_g              75 : 1.22793 / 90 : 1.78372 / 95 : 2.15088 / 99 : 2.44176
                                 mass_smaller_3 log_g              75 : 0.91576 / 90 : 1.87167 / 95 : 2.20908 / 99 : 2.56074
mlp               PARSEC         Base           log_g              75 : 0.85527 / 90 : 1.63268 / 95 : 2.02307 / 99 : 2.49201
                                 mass_smaller_3 log_g              75 : 0.92326 / 90 : 1.72094 / 95 : 2.08946 / 99 : 2.58135
random_forest     PARSEC         Base           log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                 mass_smaller_3 log_g                75 : 0.6549 / 90 : 1.75629 / 95 : 2.2964 / 99 : 3.68208
xgboost           PARSEC         Base           log_g               75 : 0.87508 / 90 : 1.49202 / 95 : 1.96052 / 99 : 2.9245
                                 mass_smaller_3 log_g                75 : 0.77053 / 90 : 1.594 / 95 : 2.02284 / 99 : 3.12637

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
KNN               PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
linear_regression PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
mlp               PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
random_forest     PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
xgboost           PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.8996188259668024
                                 mass_smaller_3 log_g              0.11404521047206362
KNN               PARSEC         Base           log_g               0.8882757130576726
                                 mass_smaller_3 log_g             -0.31793523499230036
linear_regression PARSEC         Base           log_g              0.41809683900763883
                                 mass_smaller_3 log_g              -1.7831529887251545
mlp               PARSEC         Base           log_g               0.7089460485360655
                                 mass_smaller_3 log_g               -4.904534322938302
random_forest     PARSEC         Base           log_g               0.9145444334060797
                                 mass_smaller_3 log_g              0.15786114968184173
xgboost           PARSEC         Base           log_g                0.787073838129444
                                 mass_smaller_3 log_g             -0.12004805436251598

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                0.12689924955296
                                 mass_smaller_3 log_g             0.09808715446053273
KNN               PARSEC         Base           log_g             0.13387680251544362
                                 mass_smaller_3 log_g               0.119385158583499
linear_regression PARSEC         Base           log_g             0.49609832945006466
                                 mass_smaller_3 log_g              0.3724657711181218
mlp               PARSEC         Base           log_g             0.32092417624011965
                                 mass_smaller_3 log_g              0.3540306932941142
random_forest     PARSEC         Base           log_g             0.11708589447086708
                                 mass_smaller_3 log_g             0.09566176938117092
xgboost           PARSEC         Base           log_g             0.20092473448709836
                                 mass_smaller_3 log_g              0.1148964453020636

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.043146619696415985
                                 mass_smaller_3 log_g               0.0410719577914542
KNN               PARSEC         Base           log_g              0.04803300372999391
                                 mass_smaller_3 log_g              0.04453094274788007
linear_regression PARSEC         Base           log_g              0.39697599961128927
                                 mass_smaller_3 log_g              0.34387720192633203
mlp               PARSEC         Base           log_g              0.24665996550158628
                                 mass_smaller_3 log_g               0.2655460784977146
random_forest     PARSEC         Base           log_g              0.04294454665629935
                                 mass_smaller_3 log_g              0.04095225794311631
xgboost           PARSEC         Base           log_g              0.10766642553555553
                                 mass_smaller_3 log_g              0.06971391476119151

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.008835526315790432
                                 mass_smaller_3 log_g              0.009866666666666912
KNN               PARSEC         Base           log_g             0.0041999999999999815
                                 mass_smaller_3 log_g             0.0043999999999999595
linear_regression PARSEC         Base           log_g               0.34484031970743656
                                 mass_smaller_3 log_g               0.36121216792041055
mlp               PARSEC         Base           log_g               0.20593015490835187
                                 mass_smaller_3 log_g               0.19368218166878393
random_forest     PARSEC         Base           log_g              0.009042807821093124
                                 mass_smaller_3 log_g               0.01002720265485646
xgboost           PARSEC         Base           log_g               0.04631657028198255
                                 mass_smaller_3 log_g               0.03659584045410158

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.9495173145621928
                                 mass_smaller_3 log_g               0.6561391172740382
KNN               PARSEC         Base           log_g               0.9441238142534801
                                 mass_smaller_3 log_g               0.5749815519721571
linear_regression PARSEC         Base           log_g               0.6483869807966186
                                 mass_smaller_3 log_g              0.20020399851840714
mlp               PARSEC         Base           log_g               0.8740210618735573
                                 mass_smaller_3 log_g             -0.04805077284622189
random_forest     PARSEC         Base           log_g                0.956704367836196
                                 mass_smaller_3 log_g               0.6650497474294527
xgboost           PARSEC         Base           log_g               0.8930521859521106
                                 mass_smaller_3 log_g              0.40278718654302287

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.5284999999999997
                                 mass_smaller_3 log_g                          2.212
KNN               PARSEC         Base           log_g             3.4999999999999996
                                 mass_smaller_3 log_g             1.2215999999999996
linear_regression PARSEC         Base           log_g             1.8928720936217218
                                 mass_smaller_3 log_g             0.9553918752627246
mlp               PARSEC         Base           log_g             2.0147816415537525
                                 mass_smaller_3 log_g             1.5925339120942983
random_forest     PARSEC         Base           log_g              3.485594333333332
                                 mass_smaller_3 log_g             2.0349299999999992
xgboost           PARSEC         Base           log_g             1.6199701566696167
                                 mass_smaller_3 log_g             1.1789817924499513

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               75 : 0.04239 / 90 : 0.10199 / 95 : 0.1735 / 99 : 0.49256
                                 mass_smaller_3 log_g              75 : 0.04329 / 90 : 0.10266 / 95 : 0.17963 / 99 : 0.42992
KNN               PARSEC         Base           log_g                 75 : 0.0172 / 90 : 0.1798 / 95 : 0.3366 / 99 : 0.50174
                                 mass_smaller_3 log_g                    75 : 0.0164 / 90 : 0.1626 / 95 : 0.3252 / 99 : 0.48
linear_regression PARSEC         Base           log_g              75 : 0.43839 / 90 : 0.51863 / 95 : 1.25134 / 99 : 1.52105
                                 mass_smaller_3 log_g              75 : 0.44919 / 90 : 0.52292 / 95 : 0.55141 / 99 : 0.59301
mlp               PARSEC         Base           log_g               75 : 0.29286 / 90 : 0.4783 / 95 : 0.73003 / 99 : 0.95422
                                 mass_smaller_3 log_g              75 : 0.33731 / 90 : 0.66023 / 95 : 0.79214 / 99 : 0.95453
random_forest     PARSEC         Base           log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                 mass_smaller_3 log_g               75 : 0.04351 / 90 : 0.10283 / 95 : 0.1785 / 99 : 0.42989
xgboost           PARSEC         Base           log_g              75 : 0.11966 / 90 : 0.26802 / 95 : 0.40739 / 99 : 0.93169
                                 mass_smaller_3 log_g              75 : 0.09323 / 90 : 0.17088 / 95 : 0.23277 / 99 : 0.43226

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 5.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
KNN               PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
linear_regression PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
mlp               PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
random_forest     PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
xgboost           PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9533659103656469
                                 mass_smaller_3 log_g              0.6262346430201227
KNN               PARSEC         Base           log_g              0.9638467570643746
                                 mass_smaller_3 log_g              0.9405659745504094
linear_regression PARSEC         Base           log_g              0.4678537575861228
                                 mass_smaller_3 log_g             -0.5118505323003208
mlp               PARSEC         Base           log_g              0.6986586890359093
                                 mass_smaller_3 log_g             -1.6619991985832945
random_forest     PARSEC         Base           log_g              0.9666549586583413
                                 mass_smaller_3 log_g              0.8170329219219435
xgboost           PARSEC         Base           log_g              0.8051410225359259
                                 mass_smaller_3 log_g              0.5365616668373909

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.15717495828060182
                                 mass_smaller_3 log_g              0.07623685781704885
KNN               PARSEC         Base           log_g              0.13879269452312337
                                 mass_smaller_3 log_g             0.030607814134481548
linear_regression PARSEC         Base           log_g               0.7751878266344273
                                 mass_smaller_3 log_g              0.38366584599722453
mlp               PARSEC         Base           log_g              0.42693670808661904
                                 mass_smaller_3 log_g                0.206625090379991
random_forest     PARSEC         Base           log_g              0.13291489163846407
                                 mass_smaller_3 log_g              0.05373796459134662
xgboost           PARSEC         Base           log_g              0.32974514473389915
                                 mass_smaller_3 log_g              0.09136623908356702

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.03755731681283733
                                 mass_smaller_3 log_g             0.011930591571911515
KNN               PARSEC         Base           log_g             0.054555577970546706
                                 mass_smaller_3 log_g             0.009592704900021983
linear_regression PARSEC         Base           log_g               0.6603042198897785
                                 mass_smaller_3 log_g               0.3545264358082975
mlp               PARSEC         Base           log_g              0.32023937085513465
                                 mass_smaller_3 log_g              0.15821347390751872
random_forest     PARSEC         Base           log_g             0.038264850601011854
                                 mass_smaller_3 log_g             0.015771415708761283
xgboost           PARSEC         Base           log_g              0.22544233025995322
                                 mass_smaller_3 log_g              0.06401342476207957

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.0009999999999998899
                                 mass_smaller_3 log_g             0.0009999999999998899
KNN               PARSEC         Base           log_g             0.0040000000000000036
                                 mass_smaller_3 log_g             0.0011999999999994237
linear_regression PARSEC         Base           log_g                0.6126151759684642
                                 mass_smaller_3 log_g                0.3751810808229963
mlp               PARSEC         Base           log_g                0.2203168324483551
                                 mass_smaller_3 log_g               0.12841863737238812
random_forest     PARSEC         Base           log_g             0.0014899999999975488
                                 mass_smaller_3 log_g             0.0010750000000019355
xgboost           PARSEC         Base           log_g                0.1291932544708252
                                 mass_smaller_3 log_g              0.044125329971313576

                                                                                    CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                 0.9768621176667662
                                 mass_smaller_3 log_g                 0.8466213690973723
KNN               PARSEC         Base           log_g                 0.9819199172421853
                                 mass_smaller_3 log_g                 0.9711446067295945
linear_regression PARSEC         Base           log_g                 0.7008181919711453
                                 mass_smaller_3 log_g                 0.6331357178312571
mlp               PARSEC         Base           log_g                 0.8616045482860637
                                 mass_smaller_3 log_g             -0.0053274365352318385
random_forest     PARSEC         Base           log_g                 0.9833138504657927
                                 mass_smaller_3 log_g                 0.9159047942410397
xgboost           PARSEC         Base           log_g                 0.8996437217333252
                                 mass_smaller_3 log_g                 0.7992078903237559

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                          3.008
                                 mass_smaller_3 log_g             1.4170000000000003
KNN               PARSEC         Base           log_g                          2.025
                                 mass_smaller_3 log_g             0.7721999999999998
linear_regression PARSEC         Base           log_g             2.0422025470259753
                                 mass_smaller_3 log_g             0.7296908218483917
mlp               PARSEC         Base           log_g             1.6897660627487243
                                 mass_smaller_3 log_g             0.8689507371631446
random_forest     PARSEC         Base           log_g              2.000681000000001
                                 mass_smaller_3 log_g             0.6925351428571425
xgboost           PARSEC         Base           log_g             2.0213280515670777
                                 mass_smaller_3 log_g             0.5518983612060548

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                  75 : 0.005 / 90 : 0.061 / 95 : 0.16786 / 99 : 0.82728
                                 mass_smaller_3 log_g                    75 : 0.002 / 90 : 0.003 / 95 : 0.0155 / 99 : 0.4175
KNN               PARSEC         Base           log_g                  75 : 0.0546 / 90 : 0.142 / 95 : 0.2453 / 99 : 0.67312
                                 mass_smaller_3 log_g                  75 : 0.0034 / 90 : 0.0262 / 95 : 0.0547 / 99 : 0.1265
linear_regression PARSEC         Base           log_g                75 : 1.0052 / 90 : 1.23247 / 95 : 1.3198 / 99 : 1.42503
                                 mass_smaller_3 log_g               75 : 0.46426 / 90 : 0.52389 / 95 : 0.54618 / 99 : 0.5827
mlp               PARSEC         Base           log_g              75 : 0.49825 / 90 : 0.75493 / 95 : 0.87557 / 99 : 1.11006
                                 mass_smaller_3 log_g              75 : 0.22548 / 90 : 0.33275 / 95 : 0.42431 / 99 : 0.59992
random_forest     PARSEC         Base           log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                 mass_smaller_3 log_g              75 : 0.00538 / 90 : 0.03457 / 95 : 0.08417 / 99 : 0.27399
xgboost           PARSEC         Base           log_g              75 : 0.33553 / 90 : 0.56962 / 95 : 0.69518 / 99 : 1.03312
                                 mass_smaller_3 log_g              75 : 0.08605 / 90 : 0.14662 / 95 : 0.19723 / 99 : 0.30599

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 6.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
KNN               PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
linear_regression PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
mlp               PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
random_forest     PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
xgboost           PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9311821113501082
                                 mass_smaller_3 log_g              0.8214014947758541
KNN               PARSEC         Base           log_g              0.9376850472249867
                                 mass_smaller_3 log_g              0.7243220607861849
linear_regression PARSEC         Base           log_g              -0.725236777537009
                                 mass_smaller_3 log_g             -0.4352627390919068
mlp               PARSEC         Base           log_g             0.45945948611375387
                                 mass_smaller_3 log_g             -1.5911214768574262
random_forest     PARSEC         Base           log_g              0.9485394146228903
                                 mass_smaller_3 log_g               0.890498434582598
xgboost           PARSEC         Base           log_g              0.6299752924480326
                                 mass_smaller_3 log_g             0.12597016843511355

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.15600976608096281
                                 mass_smaller_3 log_g              0.06388898546747886
KNN               PARSEC         Base           log_g              0.14852986204704607
                                 mass_smaller_3 log_g              0.08160418202920015
linear_regression PARSEC         Base           log_g               0.9778939817449916
                                 mass_smaller_3 log_g               0.1843484443498175
mlp               PARSEC         Base           log_g               0.4828140782596478
                                 mass_smaller_3 log_g              0.41382998356065887
random_forest     PARSEC         Base           log_g              0.13499216064629066
                                 mass_smaller_3 log_g             0.050048785986341375
xgboost           PARSEC         Base           log_g               0.3751694022658579
                                 mass_smaller_3 log_g              0.15861226669062742

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.04662199042529842
                                 mass_smaller_3 log_g             0.031483797547070556
KNN               PARSEC         Base           log_g              0.08393938447814452
                                 mass_smaller_3 log_g              0.06278251150558842
linear_regression PARSEC         Base           log_g               0.8951615474508734
                                 mass_smaller_3 log_g              0.14546094915210817
mlp               PARSEC         Base           log_g                0.401809244761115
                                 mass_smaller_3 log_g               0.3547322469837879
random_forest     PARSEC         Base           log_g              0.04500354176302885
                                 mass_smaller_3 log_g             0.029233394187855095
xgboost           PARSEC         Base           log_g               0.2942276428030816
                                 mass_smaller_3 log_g               0.1214680163391635

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.018000000000000016
                                 mass_smaller_3 log_g             0.018000000000000238
KNN               PARSEC         Base           log_g              0.05269999999999997
                                 mass_smaller_3 log_g              0.05039999999999978
linear_regression PARSEC         Base           log_g               0.8730742498357572
                                 mass_smaller_3 log_g              0.12280681136615179
mlp               PARSEC         Base           log_g              0.35531851890717814
                                 mass_smaller_3 log_g               0.3447107617701137
random_forest     PARSEC         Base           log_g              0.01502404127816695
                                 mass_smaller_3 log_g                0.015539999999997
xgboost           PARSEC         Base           log_g              0.24093734741210926
                                 mass_smaller_3 log_g              0.09741741752624522

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.9659004318793163
                                 mass_smaller_3 log_g               0.9137753224431725
KNN               PARSEC         Base           log_g                0.968447483894023
                                 mass_smaller_3 log_g               0.8514922936185082
linear_regression PARSEC         Base           log_g               0.2742120379276352
                                 mass_smaller_3 log_g               0.6041004197350325
mlp               PARSEC         Base           log_g               0.6800634465130304
                                 mass_smaller_3 log_g             -0.10822335924689093
random_forest     PARSEC         Base           log_g               0.9740958718877286
                                 mass_smaller_3 log_g               0.9447824833511316
xgboost           PARSEC         Base           log_g               0.7940521336810684
                                 mass_smaller_3 log_g               0.6077592472897164

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.0180000000000002
                                 mass_smaller_3 log_g             1.3810000000000002
KNN               PARSEC         Base           log_g             2.1087999999999996
                                 mass_smaller_3 log_g             0.3613999999999997
linear_regression PARSEC         Base           log_g             2.0137390311160424
                                 mass_smaller_3 log_g             0.6964242589225278
mlp               PARSEC         Base           log_g              1.551814174411986
                                 mass_smaller_3 log_g              0.973258697237001
random_forest     PARSEC         Base           log_g              2.152537166666666
                                 mass_smaller_3 log_g             0.5774567619047599
xgboost           PARSEC         Base           log_g             1.3663098917007446
                                 mass_smaller_3 log_g             0.5920764636993407

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                    75 : 0.043 / 90 : 0.08 / 95 : 0.1315 / 99 : 0.70731
                                 mass_smaller_3 log_g                 75 : 0.0438 / 90 : 0.0775 / 95 : 0.10975 / 99 : 0.2165
KNN               PARSEC         Base           log_g                 75 : 0.0988 / 90 : 0.1666 / 95 : 0.24706 / 99 : 0.6304
                                 mass_smaller_3 log_g                   75 : 0.0876 / 90 : 0.134 / 95 : 0.1662 / 99 : 0.2294
linear_regression PARSEC         Base           log_g              75 : 1.20825 / 90 : 1.42198 / 95 : 1.52277 / 99 : 1.68722
                                 mass_smaller_3 log_g               75 : 0.20489 / 90 : 0.29739 / 95 : 0.3643 / 99 : 0.50017
mlp               PARSEC         Base           log_g              75 : 0.59017 / 90 : 0.78507 / 95 : 0.89144 / 99 : 1.05907
                                 mass_smaller_3 log_g              75 : 0.50636 / 90 : 0.64737 / 95 : 0.71943 / 99 : 0.86732
random_forest     PARSEC         Base           log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                 mass_smaller_3 log_g              75 : 0.04189 / 90 : 0.07674 / 95 : 0.10107 / 99 : 0.17798
xgboost           PARSEC         Base           log_g              75 : 0.42278 / 90 : 0.62987 / 95 : 0.77118 / 99 : 0.98055
                                 mass_smaller_3 log_g              75 : 0.16865 / 90 : 0.26397 / 95 : 0.32656 / 99 : 0.45799

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Linear regression : 
- mass_smaller_3 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

XGBoost : 
- mass_smaller_3 : better/similar results to Base on every metric

MLP : 
- mass_smaller_3 : better results than Base on every metric

#### Conclusions on log_g

When filtering using mass_smaller_3, the results worsen for half the models and improves for the other half.

Since the results worsen for the best 3 models, it is not interesting to use this filtering.

#### Best models for the log_g parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### Conclusion for every filtering

mass_smaller_3 filtering is only beneficial for the T_eff parameters but the difference is not that extreme.

We will use the Base filtering with Random forest, KNN and decision tree.