# Results comparison for PARSEC filtering of model B

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the PARSEC dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

This part was done after the one on MIST so I will only try the filtering which made a positive difference.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_B/default_models"

In [4]:
compare_metrics(path, 
                output_parameters=["T_eff"],
                model_names=["decision_tree"],
                physical_models=["PARSEC"])

Results for the Global category with a value of 1.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.3621 - 4.5177
                             Base_old       T_eff             3.3621 - 4.5177
                             mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9451742472012191
                             Base_old       T_eff             0.9266408296408541
                             mass_smaller_3 T_eff             0.8871586813443988

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.042554292673794465
                             Base_old       T_eff             0.042708232796530986
                             mass_smaller_3 T_eff              0.03328590494814946

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.012520623599939452
                             Base_old       T_eff             0.015061017757280377
                             mass_smaller_3 T_eff             0.010588167800465901

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.001191428571428066
                             Base_old       T_eff             0.0030093023255806095
                             mass_smaller_3 T_eff               0.00101575187969849

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9724235183367057
                             Base_old       T_eff             0.9629323431134735
                             mass_smaller_3 T_eff             0.9429494041263922

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                         0.8407
                             Base_old       T_eff             0.8385666666666673
                             mass_smaller_3 T_eff             0.3836999999999997

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                             Base_old       T_eff              75 : 0.01239 / 90 : 0.03341 / 95 : 0.07812 / 99 : 0.18114
                             mass_smaller_3 T_eff                75 : 0.00482 / 90 : 0.02104 / 95 : 0.0629 / 99 : 0.1844

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 1.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.3621 - 4.5177
                             Base_old       T_eff             3.3621 - 4.5177
                             mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9748322909531495
                             Base_old       T_eff             0.9646985208110654
                             mass_smaller_3 T_eff              0.975213198122586

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.0423812576414891
                             Base_old       T_eff               0.0504197511354913
                             mass_smaller_3 T_eff             0.025525608230402626

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.007449396025994484
                             Base_old       T_eff             0.008843633573122251
                             mass_smaller_3 T_eff             0.005852321173799819

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             4.999999999988347e-05
                             Base_old       T_eff             4.999999999988347e-05
                             mass_smaller_3 T_eff             6.666666666665932e-05

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9876003989251159
                             Base_old       T_eff             0.9826770838721797
                             mass_smaller_3 T_eff             0.9879085497518846

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8311642857142854
                             Base_old       T_eff             0.8181000000000003
                             mass_smaller_3 T_eff             0.3836999999999997

                                                                                                           Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                             Base_old       T_eff               75 : 0.0011 / 90 : 0.0103 / 95 : 0.02628 / 99 : 0.201
                             mass_smaller_3 T_eff              75 : 0.0006 / 90 : 0.0085 / 95 : 0.0246 / 99 : 0.12535

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 2.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              3.6053 - 4.446
                             Base_old       T_eff               3.602 - 4.446
                             mass_smaller_3 T_eff             3.6813 - 4.1397

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.872460228127739
                             Base_old       T_eff             0.8653488782920009
                             mass_smaller_3 T_eff             0.6049838323957871

                                                                             RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.06255115396094892
                             Base_old       T_eff               0.064121708121317
                             mass_smaller_3 T_eff             0.06317765357377349

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.03380714142468827
                             Base_old       T_eff             0.034932939805899156
                             mass_smaller_3 T_eff              0.03278852938657706

                                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.015225000000000044
                             Base_old       T_eff             0.015500000000000291
                             mass_smaller_3 T_eff             0.009400000000000297

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9441691057521153
                             Base_old       T_eff             0.9411344598039713
                             mass_smaller_3 T_eff             0.8925416933006906

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8240999999999996
                             Base_old       T_eff             0.8071999999999999
                             mass_smaller_3 T_eff             0.2875000000000001

                                                                                                             Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                             Base_old       T_eff              75 : 0.0391 / 90 : 0.09034 / 95 : 0.14529 / 99 : 0.24239
                             mass_smaller_3 T_eff              75 : 0.02955 / 90 : 0.11347 / 95 : 0.16941 / 99 : 0.2382

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 3.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.4342 - 3.7459
                             Base_old       T_eff             3.4342 - 3.7459
                             mass_smaller_3 T_eff             3.4342 - 3.7459

                                                                              RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             -0.7632012932187855
                             Base_old       T_eff             -0.7446428496459467
                             mass_smaller_3 T_eff             -0.5234705113818034

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.062014552223464726
                             Base_old       T_eff              0.06199437972179435
                             mass_smaller_3 T_eff              0.05848860953001508

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.027219918269213918
                             Base_old       T_eff             0.027880328284992886
                             mass_smaller_3 T_eff             0.028422840214358244

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0037571428571430143
                             Base_old       T_eff              0.004349999999999632
                             mass_smaller_3 T_eff              0.003509999999999014

                                                                             CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.124189042946256
                             Base_old       T_eff             0.12999551271619822
                             mass_smaller_3 T_eff             0.11942462598385166

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.8298000000000001
                             Base_old       T_eff             0.8385666666666673
                             mass_smaller_3 T_eff             0.2891999999999997

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                             Base_old       T_eff              75 : 0.02405 / 90 : 0.09619 / 95 : 0.14095 / 99 : 0.23488
                             mass_smaller_3 T_eff              75 : 0.02726 / 90 : 0.10436 / 95 : 0.14774 / 99 : 0.22839

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 4.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.5328 - 3.786
                             Base_old       T_eff             3.5301 - 3.786
                             mass_smaller_3 T_eff             3.6191 - 3.786

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.5441135519545068
                             Base_old       T_eff             0.4919354858527928
                             mass_smaller_3 T_eff             0.9242961999199967

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.020721238317739282
                             Base_old       T_eff             0.022068366528774426
                             mass_smaller_3 T_eff             0.007156302955568765

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0038289243446757216
                             Base_old       T_eff              0.005905391575893141
                             mass_smaller_3 T_eff             0.0030461141057490874

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0007587628865994844
                             Base_old       T_eff             0.0016611628857552407
                             mass_smaller_3 T_eff             0.0008441558441583119

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.7961889196467123
                             Base_old       T_eff             0.7769222769874299
                             mass_smaller_3 T_eff             0.9626419908201415

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                          0.8407
                             Base_old       T_eff              0.8258000000000001
                             mass_smaller_3 T_eff             0.24480000000000013

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                             Base_old       T_eff              75 : 0.00662 / 90 : 0.01444 / 95 : 0.02037 / 99 : 0.04379
                             mass_smaller_3 T_eff               75 : 0.00318 / 90 : 0.00748 / 95 : 0.01282 / 99 : 0.0312

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 5.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              3.5642 - 4.272
                             Base_old       T_eff              3.5644 - 4.272
                             mass_smaller_3 T_eff             3.6805 - 3.8635

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.875456632791973
                             Base_old       T_eff             0.8420309857438173
                             mass_smaller_3 T_eff              0.867553551301494

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff               0.0404003814429823
                             Base_old       T_eff              0.04552491349501501
                             mass_smaller_3 T_eff             0.013122882060035538

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.009523709897636998
                             Base_old       T_eff              0.012801870846465514
                             mass_smaller_3 T_eff             0.0015745356602996682

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             4.440892098500626e-16
                             Base_old       T_eff             4.440892098500626e-16
                             mass_smaller_3 T_eff                               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9382230012465637
                             Base_old       T_eff             0.9245126669295642
                             mass_smaller_3 T_eff             0.9400210765627829

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              0.7346999999999997
                             Base_old       T_eff              0.5848999999999998
                             mass_smaller_3 T_eff             0.31820000000000004

                                                                                                             Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                             Base_old       T_eff              75 : 0.0034 / 90 : 0.02434 / 95 : 0.08046 / 99 : 0.21703
                             mass_smaller_3 T_eff                  75 : 5e-05 / 90 : 0.0001 / 95 : 0.0021 / 99 : 0.0425

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

Results for the label category with a value of 6.0

                                                                  value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             3.5416 - 4.2601
                             Base_old       T_eff             3.5437 - 4.2601
                             mass_smaller_3 T_eff             3.6516 - 3.8551

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9361134687179025
                             Base_old       T_eff             0.8509271515153556
                             mass_smaller_3 T_eff             0.9344208412339422

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.038817942968688686
                             Base_old       T_eff             0.060310058384806735
                             mass_smaller_3 T_eff             0.009947309738953879

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.010905352896371222
                             Base_old       T_eff              0.02210327067054398
                             mass_smaller_3 T_eff             0.003275683015649687

                                                                              MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.0035000000000007248
                             Base_old       T_eff             0.0040000000000000036
                             mass_smaller_3 T_eff              0.001966666666666672

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.9682850567668624
                             Base_old       T_eff             0.9331089743270826
                             mass_smaller_3 T_eff             0.9679753590180824

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff             0.7282999999999995
                             Base_old       T_eff             0.7282999999999995
                             mass_smaller_3 T_eff                         0.2946

                                                                                                              Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                             Base_old       T_eff                 75 : 0.012 / 90 : 0.05822 / 95 : 0.1444 / 99 : 0.26733
                             mass_smaller_3 T_eff              75 : 0.00418 / 90 : 0.00735 / 95 : 0.00924 / 99 : 0.01914

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           T_eff              6.434222936630249
                             Base_old       T_eff              8.568377017974854
                             mass_smaller_3 T_eff             4.5170204639434814

In [ ]:
compare_metrics(path, value_rounding=6,
                output_parameters=["T_eff", "radius", "log_g"],
                physical_models=["PARSEC"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                                   value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
KNN               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
linear_regression PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
mlp               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
random_forest     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273
xgboost           PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                   -0.384 - 5.345
                                        radius            -0.976336 - 2.837273

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.945174  0.042554
                                        log_g             0.753657  0.519054
                                        radius            0.818880  0.259482
KNN               PARSEC         Base   T_eff             0.928991  0.048511
                                        log_g             0.796923  0.471456
                                        radius            0.850453  0.235877
linear_regression PARSEC         Base   T_eff             0.344458  0.147146
                                        log_g             0.174017  0.950443
                                        radius            0.306153  0.507872
mlp               PARSEC         Base   T_eff             0.456675  0.134103
                                        log_g             0.507586  0.734551
                                        radius            0.622855  0.374986
random_forest     PARSEC         Base   T_eff             0.956661  0.037835
                                        log_g             0.807427  0.458925
                                        radius            0.858417  0.229420
xgboost           PARSEC         Base   T_eff             0.772632  0.086659
                                        log_g             0.720714  0.552669
                                        radius            0.794523  0.276379

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.012521  0.001191
                                        log_g             0.150609  0.011000
                                        radius            0.075279  0.005673
KNN               PARSEC         Base   T_eff             0.016210  0.001880
                                        log_g             0.168647  0.013200
                                        radius            0.084686  0.007273
linear_regression PARSEC         Base   T_eff             0.108064  0.075052
                                        log_g             0.750716  0.505290
                                        radius            0.397538  0.274545
mlp               PARSEC         Base   T_eff             0.093483  0.064096
                                        log_g             0.501094  0.259584
                                        radius            0.253643  0.133197
random_forest     PARSEC         Base   T_eff             0.012196  0.001501
                                        log_g             0.146241  0.012717
                                        radius            0.073068  0.006440
xgboost           PARSEC         Base   T_eff             0.044921  0.012216
                                        log_g             0.313614  0.107134
                                        radius            0.156982  0.054236

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.972424  0.840700
                                        log_g             0.873827  4.780000
                                        radius            0.907855  2.390815
KNN               PARSEC         Base   T_eff             0.963858  0.829140
                                        log_g             0.893518  4.635400
                                        radius            0.922797  2.317238
linear_regression PARSEC         Base   T_eff             0.586906  0.545711
                                        log_g             0.417154  3.354960
                                        radius            0.553311  1.781259
mlp               PARSEC         Base   T_eff             0.687641  0.832390
                                        log_g             0.712461  3.893786
                                        radius            0.789215  1.990677
random_forest     PARSEC         Base   T_eff             0.978124  0.828999
                                        log_g             0.899847  4.620864
                                        radius            0.927173  2.310296
xgboost           PARSEC         Base   T_eff             0.879159  0.686212
                                        log_g             0.849413  4.357621
                                        radius            0.891569  2.261232

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                                        log_g                75 : 0.05772 / 90 : 0.22267 / 95 : 0.89533 / 99 : 2.907
                                        radius              75 : 0.02877 / 90 : 0.11129 / 95 : 0.4465 / 99 : 1.45363
KNN               PARSEC         Base   T_eff                75 : 0.0133 / 90 : 0.0398 / 95 : 0.07538 / 99 : 0.20009
                                        log_g                 75 : 0.0886 / 90 : 0.4462 / 95 : 1.0346 / 99 : 2.24206
                                        radius             75 : 0.04507 / 90 : 0.22252 / 95 : 0.51756 / 99 : 1.12183
linear_regression PARSEC         Base   T_eff              75 : 0.14234 / 90 : 0.27293 / 95 : 0.32016 / 99 : 0.42868
                                        log_g              75 : 1.13119 / 90 : 1.62211 / 95 : 1.88341 / 99 : 2.41107
                                        radius             75 : 0.58813 / 90 : 0.83923 / 95 : 1.02037 / 99 : 1.42151
mlp               PARSEC         Base   T_eff                75 : 0.11522 / 90 : 0.20538 / 95 : 0.285 / 99 : 0.50069
                                        log_g              75 : 0.73311 / 90 : 1.41779 / 95 : 1.65723 / 99 : 2.18019
                                        radius             75 : 0.37949 / 90 : 0.71574 / 95 : 0.85022 / 99 : 1.08968
random_forest     PARSEC         Base   T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                        log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                        radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
xgboost           PARSEC         Base   T_eff              75 : 0.05362 / 90 : 0.13639 / 95 : 0.20195 / 99 : 0.34634
                                        log_g               75 : 0.40285 / 90 : 0.95171 / 95 : 1.2855 / 99 : 2.01364
                                        radius             75 : 0.19952 / 90 : 0.47689 / 95 : 0.64069 / 99 : 1.00851

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 1.0

                                                                   value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
KNN               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
linear_regression PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
mlp               PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
random_forest     PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792
xgboost           PARSEC         Base   T_eff                  3.3621 - 4.5177
                                        log_g                    3.233 - 5.345
                                        radius            -0.976336 - 1.168792

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.974832  0.042381
                                        log_g            -0.223663  0.380474
                                        radius            0.736372  0.190422
KNN               PARSEC         Base   T_eff             0.925539  0.074090
                                        log_g            -0.568551  0.443320
                                        radius            0.660043  0.222548
linear_regression PARSEC         Base   T_eff             0.597294  0.215205
                                        log_g            -1.225249  1.473679
                                        radius            0.291126  0.808124
mlp               PARSEC         Base   T_eff             0.590721  0.176664
                                        log_g            -4.371544  1.063488
                                        radius           -0.176376  0.543708
random_forest     PARSEC         Base   T_eff             0.982664  0.035351
                                        log_g             0.172115  0.315988
                                        radius            0.821605  0.158164
xgboost           PARSEC         Base   T_eff             0.903544  0.089629
                                        log_g            -1.012488  0.553560
                                        radius            0.566261  0.276740

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.007449  0.000050
                                        log_g             0.067495  0.000750
                                        radius            0.034093  0.000399
KNN               PARSEC         Base   T_eff             0.019715  0.002020
                                        log_g             0.134608  0.007000
                                        radius            0.069347  0.004956
linear_regression PARSEC         Base   T_eff             0.180860  0.137110
                                        log_g             1.383983  1.318829
                                        radius            0.747075  0.675373
mlp               PARSEC         Base   T_eff             0.125399  0.092680
                                        log_g             0.779041  0.578822
                                        radius            0.401638  0.286798
random_forest     PARSEC         Base   T_eff             0.007342  0.000192
                                        log_g             0.070260  0.000980
                                        radius            0.035333  0.000566
xgboost           PARSEC         Base   T_eff             0.043701  0.016440
                                        log_g             0.319178  0.090964
                                        radius            0.160672  0.051169

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.987600  0.831164
                                        log_g             0.705340  4.780000
                                        radius            0.891072  2.390815
KNN               PARSEC         Base   T_eff             0.962302  0.826320
                                        log_g             0.726834  4.513000
                                        radius            0.885902  2.256155
linear_regression PARSEC         Base   T_eff             0.853645  0.545711
                                        log_g             0.337036  3.354960
                                        radius            0.633163  1.781259
mlp               PARSEC         Base   T_eff             0.777345  0.832390
                                        log_g             0.779206  2.711008
                                        radius            0.783845  1.383009
random_forest     PARSEC         Base   T_eff             0.991400  0.769496
                                        log_g             0.775979  4.226316
                                        radius            0.922800  2.112811
xgboost           PARSEC         Base   T_eff             0.951354  0.686212
                                        log_g             0.809582  3.585431
                                        radius            0.882597  1.706742

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                                        log_g                     75 : 0.006 / 90 : 0.026 / 95 : 0.064 / 99 : 1.9685
                                        radius             75 : 0.00335 / 90 : 0.01452 / 95 : 0.03433 / 99 : 0.98432
KNN               PARSEC         Base   T_eff               75 : 0.0082 / 90 : 0.03622 / 95 : 0.06993 / 99 : 0.43359
                                        log_g                  75 : 0.0274 / 90 : 0.2318 / 95 : 0.848 / 99 : 2.22856
                                        radius             75 : 0.01813 / 90 : 0.11851 / 95 : 0.42461 / 99 : 1.12036
linear_regression PARSEC         Base   T_eff              75 : 0.25535 / 90 : 0.36302 / 95 : 0.41855 / 99 : 0.48298
                                        log_g               75 : 1.74379 / 90 : 2.02828 / 95 : 2.27583 / 99 : 2.7985
                                        radius              75 : 0.91055 / 90 : 1.1884 / 95 : 1.39367 / 99 : 1.62448
mlp               PARSEC         Base   T_eff                75 : 0.1533 / 90 : 0.27528 / 95 : 0.39784 / 99 : 0.6293
                                        log_g              75 : 1.51463 / 90 : 1.68943 / 95 : 1.85061 / 99 : 2.26065
                                        radius              75 : 0.76117 / 90 : 0.89535 / 95 : 0.96146 / 99 : 1.1454
random_forest     PARSEC         Base   T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                        log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                        radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
xgboost           PARSEC         Base   T_eff              75 : 0.04522 / 90 : 0.09853 / 95 : 0.19258 / 99 : 0.44504
                                        log_g              75 : 0.43347 / 90 : 1.03051 / 95 : 1.34273 / 99 : 1.90141
                                        radius             75 : 0.21204 / 90 : 0.51508 / 95 : 0.66892 / 99 : 0.95761

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 2.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
KNN               PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
linear_regression PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
mlp               PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
random_forest     PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487
xgboost           PARSEC         Base   T_eff                  3.6053 - 4.446
                                        log_g                   0.638 - 4.299
                                        radius            0.019947 - 2.458487

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.872460  0.062551
                                        log_g             0.201081  0.756121
                                        radius            0.564531  0.378084
KNN               PARSEC         Base   T_eff             0.901921  0.056525
                                        log_g             0.551332  0.592130
                                        radius            0.755423  0.296099
linear_regression PARSEC         Base   T_eff             0.245804  0.157645
                                        log_g             0.207291  0.804882
                                        radius            0.538604  0.404651
mlp               PARSEC         Base   T_eff            -0.060497  0.201686
                                        log_g             0.420183  0.948966
                                        radius            0.658256  0.477307
random_forest     PARSEC         Base   T_eff             0.899761  0.055911
                                        log_g             0.462614  0.632273
                                        radius            0.707102  0.316149
xgboost           PARSEC         Base   T_eff             0.242135  0.163469
                                        log_g             0.350010  0.832163
                                        radius            0.644051  0.417444

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.033807  0.015225
                                        log_g             0.302998  0.060000
                                        radius            0.151568  0.030172
KNN               PARSEC         Base   T_eff             0.036253  0.022300
                                        log_g             0.307196  0.091600
                                        radius            0.153682  0.045965
linear_regression PARSEC         Base   T_eff             0.125799  0.104393
                                        log_g             0.664043  0.612538
                                        radius            0.330807  0.299524
mlp               PARSEC         Base   T_eff             0.150167  0.111460
                                        log_g             0.809776  0.832247
                                        radius            0.407418  0.413264
random_forest     PARSEC         Base   T_eff             0.032529  0.016365
                                        log_g             0.289372  0.068061
                                        radius            0.144739  0.034069
xgboost           PARSEC         Base   T_eff             0.123031  0.089585
                                        log_g             0.671362  0.584957
                                        radius            0.336568  0.292945

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.944169  0.824100
                                        log_g             0.654394  4.171000
                                        radius            0.780179  2.086107
KNN               PARSEC         Base   T_eff             0.954199  0.636320
                                        log_g             0.769385  3.967000
                                        radius            0.869666  1.983172
linear_regression PARSEC         Base   T_eff             0.498101  0.511006
                                        log_g             0.493105  2.888378
                                        radius            0.736236  1.543650
mlp               PARSEC         Base   T_eff             0.269180  0.771006
                                        log_g             0.652164  2.375106
                                        radius            0.819324  1.263273
random_forest     PARSEC         Base   T_eff             0.954951  0.765904
                                        log_g             0.737427  3.682990
                                        radius            0.845059  1.841073
xgboost           PARSEC         Base   T_eff             0.507815  0.675210
                                        log_g             0.612090  2.695528
                                        radius            0.802798  1.372651

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                                        log_g              75 : 0.15628 / 90 : 1.01729 / 95 : 1.81952 / 99 : 3.37886
                                        radius             75 : 0.07811 / 90 : 0.50835 / 95 : 0.91068 / 99 : 1.68888
KNN               PARSEC         Base   T_eff              75 : 0.04752 / 90 : 0.08675 / 95 : 0.11641 / 99 : 0.19029
                                        log_g                 75 : 0.2642 / 90 : 1.089 / 95 : 1.41552 / 99 : 2.27112
                                        radius              75 : 0.13204 / 90 : 0.54463 / 95 : 0.7077 / 99 : 1.13544
linear_regression PARSEC         Base   T_eff               75 : 0.17836 / 90 : 0.26213 / 95 : 0.3129 / 99 : 0.41535
                                        log_g              75 : 0.93956 / 90 : 1.24051 / 95 : 1.47758 / 99 : 2.09846
                                        radius               75 : 0.4692 / 90 : 0.6187 / 95 : 0.74639 / 99 : 1.09896
mlp               PARSEC         Base   T_eff              75 : 0.20893 / 90 : 0.34079 / 95 : 0.43468 / 99 : 0.60504
                                        log_g              75 : 1.17152 / 90 : 1.42053 / 95 : 1.61857 / 99 : 2.05238
                                        radius             75 : 0.58918 / 90 : 0.71959 / 95 : 0.80987 / 99 : 1.03145
random_forest     PARSEC         Base   T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                        log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                        radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
xgboost           PARSEC         Base   T_eff              75 : 0.17025 / 90 : 0.27651 / 95 : 0.35297 / 99 : 0.48104
                                        log_g               75 : 1.02779 / 90 : 1.3463 / 95 : 1.53656 / 99 : 1.99333
                                        radius              75 : 0.51575 / 90 : 0.67511 / 95 : 0.7715 / 99 : 1.00317

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 3.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
KNN               PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
linear_regression PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
mlp               PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
random_forest     PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273
xgboost           PARSEC         Base   T_eff                 3.4342 - 3.7459
                                        log_g                  -0.384 - 3.823
                                        radius            0.287802 - 2.837273

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff            -0.763201  0.062015
                                        log_g            -0.434244  0.980673
                                        radius           -0.029463  0.490364
KNN               PARSEC         Base   T_eff            -0.419654  0.056569
                                        log_g            -0.096894  0.871944
                                        radius            0.212646  0.436015
linear_regression PARSEC         Base   T_eff            -3.483451  0.128916
                                        log_g             0.168726  1.037678
                                        radius            0.402397  0.533016
mlp               PARSEC         Base   T_eff            -3.062654  0.116005
                                        log_g             0.201798  0.878777
                                        radius            0.414377  0.442644
random_forest     PARSEC         Base   T_eff            -0.502332  0.057579
                                        log_g            -0.172120  0.891969
                                        radius            0.158655  0.446023
xgboost           PARSEC         Base   T_eff            -1.921797  0.096128
                                        log_g             0.063088  0.883823
                                        radius            0.328160  0.441498

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.027220  0.003757
                                        log_g             0.470673  0.066188
                                        radius            0.235384  0.033231
KNN               PARSEC         Base   T_eff             0.027020  0.006720
                                        log_g             0.462166  0.109500
                                        radius            0.231142  0.054727
linear_regression PARSEC         Base   T_eff             0.097209  0.074184
                                        log_g             0.824557  0.648371
                                        radius            0.427083  0.344557
mlp               PARSEC         Base   T_eff             0.087439  0.064049
                                        log_g             0.633527  0.384099
                                        radius            0.319721  0.195172
random_forest     PARSEC         Base   T_eff             0.026189  0.004677
                                        log_g             0.451075  0.077399
                                        radius            0.225588  0.038764
xgboost           PARSEC         Base   T_eff             0.061889  0.025207
                                        log_g             0.596223  0.360110
                                        radius            0.297539  0.180217

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.124189  0.829800
                                        log_g             0.240076  4.770000
                                        radius            0.484329  2.385359
KNN               PARSEC         Base   T_eff             0.165105  0.813280
                                        log_g             0.304296  4.635400
                                        radius            0.558678  2.317238
linear_regression PARSEC         Base   T_eff             0.101690  0.380102
                                        log_g             0.410993  2.857540
                                        radius            0.638608  1.423368
mlp               PARSEC         Base   T_eff             0.075250  0.615613
                                        log_g             0.457470  3.893786
                                        radius            0.647683  1.990677
random_forest     PARSEC         Base   T_eff             0.167062  0.806513
                                        log_g             0.306816  4.620864
                                        radius            0.545958  2.310296
xgboost           PARSEC         Base   T_eff             0.050497  0.386060
                                        log_g             0.299175  4.357621
                                        radius            0.574539  2.261232

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                                        log_g                75 : 0.42077 / 90 : 1.80427 / 95 : 2.529 / 99 : 3.83062
                                        radius              75 : 0.21021 / 90 : 0.9022 / 95 : 1.26428 / 99 : 1.91484
KNN               PARSEC         Base   T_eff              75 : 0.02926 / 90 : 0.08358 / 95 : 0.12637 / 99 : 0.21296
                                        log_g                 75 : 0.6006 / 90 : 1.5316 / 95 : 2.08425 / 99 : 3.6946
                                        radius              75 : 0.3004 / 90 : 0.76603 / 95 : 1.04217 / 99 : 1.84744
linear_regression PARSEC         Base   T_eff               75 : 0.13101 / 90 : 0.2356 / 95 : 0.29718 / 99 : 0.33842
                                        log_g              75 : 1.22793 / 90 : 1.78372 / 95 : 2.15088 / 99 : 2.44176
                                        radius             75 : 0.63518 / 90 : 0.90864 / 95 : 1.08583 / 99 : 1.23233
mlp               PARSEC         Base   T_eff              75 : 0.12108 / 90 : 0.18899 / 95 : 0.22475 / 99 : 0.37096
                                        log_g              75 : 0.85527 / 90 : 1.63268 / 95 : 2.02307 / 99 : 2.49201
                                        radius              75 : 0.44388 / 90 : 0.81582 / 95 : 1.00769 / 99 : 1.2349
random_forest     PARSEC         Base   T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                        log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                        radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
xgboost           PARSEC         Base   T_eff              75 : 0.09793 / 90 : 0.17076 / 95 : 0.22502 / 99 : 0.30108
                                        log_g               75 : 0.87508 / 90 : 1.49202 / 95 : 1.96052 / 99 : 2.9245
                                        radius             75 : 0.43744 / 90 : 0.74514 / 95 : 0.97449 / 99 : 1.46297

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 4.0

                                                                 value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
KNN               PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
linear_regression PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
mlp               PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
random_forest     PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724
xgboost           PARSEC         Base   T_eff                 3.5328 - 3.786
                                        log_g                 -0.102 - 2.978
                                        radius            0.781899 - 2.82724

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.544114  0.020721
                                        log_g             0.899619  0.126899
                                        radius            0.955620  0.063414
KNN               PARSEC         Base   T_eff             0.690416  0.017076
                                        log_g             0.888276  0.133877
                                        radius            0.950486  0.066981
linear_regression PARSEC         Base   T_eff            -7.161325  0.090873
                                        log_g             0.418097  0.496098
                                        radius            0.708437  0.261443
mlp               PARSEC         Base   T_eff            -4.487443  0.078045
                                        log_g             0.708946  0.320924
                                        radius            0.821596  0.165257
random_forest     PARSEC         Base   T_eff             0.659119  0.017918
                                        log_g             0.914544  0.117086
                                        radius            0.962170  0.058548
xgboost           PARSEC         Base   T_eff            -0.301430  0.036494
                                        log_g             0.787074  0.200925
                                        radius            0.906795  0.099651

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.003829  0.000759
                                        log_g             0.043147  0.008836
                                        radius            0.021592  0.004420
KNN               PARSEC         Base   T_eff             0.004156  0.000400
                                        log_g             0.048033  0.004200
                                        radius            0.024017  0.002118
linear_regression PARSEC         Base   T_eff             0.060694  0.043600
                                        log_g             0.396976  0.344840
                                        radius            0.209695  0.188876
mlp               PARSEC         Base   T_eff             0.059086  0.049751
                                        log_g             0.246660  0.205930
                                        radius            0.116761  0.080204
random_forest     PARSEC         Base   T_eff             0.003897  0.000786
                                        log_g             0.042945  0.009043
                                        radius            0.021492  0.004535
xgboost           PARSEC         Base   T_eff             0.013120  0.003837
                                        log_g             0.107666  0.046317
                                        radius            0.053422  0.023086

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.796189  0.840700
                                        log_g             0.949517  3.528500
                                        radius            0.977688  1.765034
KNN               PARSEC         Base   T_eff             0.850168  0.829140
                                        log_g             0.944124  3.500000
                                        radius            0.975185  1.750620
linear_regression PARSEC         Base   T_eff            -0.214811  0.373937
                                        log_g             0.648387  1.892872
                                        radius            0.887672  0.961278
mlp               PARSEC         Base   T_eff             0.023312  0.617142
                                        log_g             0.874021  2.014782
                                        radius            0.919896  1.173495
random_forest     PARSEC         Base   T_eff             0.836128  0.828999
                                        log_g             0.956704  3.485594
                                        radius            0.980933  1.743523
xgboost           PARSEC         Base   T_eff             0.377211  0.401789
                                        log_g             0.893052  1.619970
                                        radius            0.957776  0.789785

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                                        log_g               75 : 0.04239 / 90 : 0.10199 / 95 : 0.1735 / 99 : 0.49256
                                        radius             75 : 0.02116 / 90 : 0.05107 / 95 : 0.08715 / 99 : 0.24579
KNN               PARSEC         Base   T_eff               75 : 0.00184 / 90 : 0.0122 / 95 : 0.02378 / 99 : 0.04028
                                        log_g                 75 : 0.0172 / 90 : 0.1798 / 95 : 0.3366 / 99 : 0.50174
                                        radius             75 : 0.00859 / 90 : 0.08998 / 95 : 0.16848 / 99 : 0.25098
linear_regression PARSEC         Base   T_eff                75 : 0.06806 / 90 : 0.11643 / 95 : 0.26577 / 99 : 0.323
                                        log_g              75 : 0.43839 / 90 : 0.51863 / 95 : 1.25134 / 99 : 1.52105
                                        radius             75 : 0.23824 / 90 : 0.28693 / 95 : 0.64321 / 99 : 0.78988
mlp               PARSEC         Base   T_eff              75 : 0.07231 / 90 : 0.10066 / 95 : 0.15498 / 99 : 0.27496
                                        log_g               75 : 0.29286 / 90 : 0.4783 / 95 : 0.73003 / 99 : 0.95422
                                        radius             75 : 0.15069 / 90 : 0.24565 / 95 : 0.36761 / 99 : 0.57346
random_forest     PARSEC         Base   T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                        log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                        radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
xgboost           PARSEC         Base   T_eff              75 : 0.00977 / 90 : 0.01972 / 95 : 0.05406 / 99 : 0.19767
                                        log_g              75 : 0.11966 / 90 : 0.26802 / 95 : 0.40739 / 99 : 0.93169
                                        radius             75 : 0.05941 / 90 : 0.13327 / 95 : 0.19754 / 99 : 0.46263

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 5.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
KNN               PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
linear_regression PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
mlp               PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
random_forest     PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967
xgboost           PARSEC         Base   T_eff                  3.5642 - 4.272
                                        log_g                     0.2 - 2.963
                                        radius            0.878752 - 2.669967

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.875457  0.040400
                                        log_g             0.953366  0.157175
                                        radius            0.976161  0.074551
KNN               PARSEC         Base   T_eff             0.895290  0.037110
                                        log_g             0.963847  0.138793
                                        radius            0.981003  0.066772
linear_regression PARSEC         Base   T_eff             0.135462  0.161486
                                        log_g             0.467854  0.775188
                                        radius            0.693621  0.412488
mlp               PARSEC         Base   T_eff            -0.292731  0.137099
                                        log_g             0.698659  0.426937
                                        radius            0.790557  0.245640
random_forest     PARSEC         Base   T_eff             0.907909  0.034739
                                        log_g             0.966655  0.132915
                                        radius            0.983322  0.062359
xgboost           PARSEC         Base   T_eff             0.464624  0.085826
                                        log_g             0.805141  0.329745
                                        radius            0.890970  0.164608

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.009524  0.000000
                                        log_g             0.037557  0.001000
                                        radius            0.017089  0.000572
KNN               PARSEC         Base   T_eff             0.014543  0.001100
                                        log_g             0.054556  0.004000
                                        radius            0.025789  0.001905
linear_regression PARSEC         Base   T_eff             0.137198  0.113176
                                        log_g             0.660304  0.612615
                                        radius            0.361341  0.342135
mlp               PARSEC         Base   T_eff             0.106358  0.081960
                                        log_g             0.320239  0.220317
                                        radius            0.183394  0.131973
random_forest     PARSEC         Base   T_eff             0.009529  0.000437
                                        log_g             0.038265  0.001490
                                        radius            0.017504  0.000767
xgboost           PARSEC         Base   T_eff             0.059022  0.034366
                                        log_g             0.225442  0.129193
                                        radius            0.112802  0.066267

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.938223  0.734700
                                        log_g             0.976862  3.008000
                                        radius            0.988134  1.505778
KNN               PARSEC         Base   T_eff             0.946298  0.540500
                                        log_g             0.981920  2.025000
                                        radius            0.990546  1.024449
linear_regression PARSEC         Base   T_eff             0.403575  0.345670
                                        log_g             0.700818  2.042203
                                        radius            0.840505  1.087498
mlp               PARSEC         Base   T_eff             0.342565  0.547152
                                        log_g             0.861605  1.689766
                                        radius            0.904402  1.072072
random_forest     PARSEC         Base   T_eff             0.953477  0.502608
                                        log_g             0.983314  2.000681
                                        radius            0.991657  1.017307
xgboost           PARSEC         Base   T_eff             0.682035  0.553807
                                        log_g             0.899644  2.021328
                                        radius            0.945786  0.991914

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                                        log_g                  75 : 0.005 / 90 : 0.061 / 95 : 0.16786 / 99 : 0.82728
                                        radius             75 : 0.00213 / 90 : 0.02711 / 95 : 0.07076 / 99 : 0.37473
KNN               PARSEC         Base   T_eff               75 : 0.0147 / 90 : 0.03722 / 95 : 0.06555 / 99 : 0.18111
                                        log_g                  75 : 0.0546 / 90 : 0.142 / 95 : 0.2453 / 99 : 0.67312
                                        radius             75 : 0.02562 / 90 : 0.06674 / 95 : 0.11563 / 99 : 0.32208
linear_regression PARSEC         Base   T_eff               75 : 0.1915 / 90 : 0.28075 / 95 : 0.30894 / 99 : 0.33665
                                        log_g                75 : 1.0052 / 90 : 1.23247 / 95 : 1.3198 / 99 : 1.42503
                                        radius                75 : 0.52905 / 90 : 0.63795 / 95 : 0.68 / 99 : 0.75724
mlp               PARSEC         Base   T_eff                75 : 0.13316 / 90 : 0.2293 / 95 : 0.2998 / 99 : 0.40241
                                        log_g              75 : 0.49825 / 90 : 0.75493 / 95 : 0.87557 / 99 : 1.11006
                                        radius              75 : 0.26965 / 90 : 0.42654 / 95 : 0.50947 / 99 : 0.6911
random_forest     PARSEC         Base   T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                        log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                        radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
xgboost           PARSEC         Base   T_eff              75 : 0.08836 / 90 : 0.14542 / 95 : 0.18122 / 99 : 0.26898
                                        log_g              75 : 0.33553 / 90 : 0.56962 / 95 : 0.69518 / 99 : 1.03312
                                        radius             75 : 0.17244 / 90 : 0.27989 / 95 : 0.34668 / 99 : 0.52946

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

Results for the label category with a value of 6.0

                                                                  value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
KNN               PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
linear_regression PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
mlp               PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
random_forest     PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789
xgboost           PARSEC         Base   T_eff                 3.5416 - 4.2601
                                        log_g                  -0.017 - 2.837
                                        radius            0.963079 - 2.777789

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.936113  0.038818
                                        log_g             0.931182  0.156010
                                        radius            0.959084  0.077104
KNN               PARSEC         Base   T_eff             0.941800  0.037079
                                        log_g             0.937685  0.148530
                                        radius            0.962970  0.073369
linear_regression PARSEC         Base   T_eff             0.207644  0.167819
                                        log_g            -0.725237  0.977894
                                        radius           -0.178027  0.522385
mlp               PARSEC         Base   T_eff             0.032534  0.151943
                                        log_g             0.459459  0.482814
                                        radius            0.618041  0.272027
random_forest     PARSEC         Base   T_eff             0.951628  0.033786
                                        log_g             0.948539  0.134992
                                        radius            0.969767  0.066327
xgboost           PARSEC         Base   T_eff             0.665456  0.089052
                                        log_g             0.629975  0.375169
                                        radius            0.769793  0.190582

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.010905  0.003500
                                        log_g             0.046622  0.018000
                                        radius            0.022777  0.008704
KNN               PARSEC         Base   T_eff             0.020029  0.011480
                                        log_g             0.083939  0.052700
                                        radius            0.041668  0.026158
linear_regression PARSEC         Base   T_eff             0.142558  0.127134
                                        log_g             0.895162  0.873074
                                        radius            0.481581  0.476142
mlp               PARSEC         Base   T_eff             0.120788  0.098131
                                        log_g             0.401809  0.355319
                                        radius            0.224031  0.198615
random_forest     PARSEC         Base   T_eff             0.010590  0.003122
                                        log_g             0.045004  0.015024
                                        radius            0.021995  0.007358
xgboost           PARSEC         Base   T_eff             0.067525  0.051502
                                        log_g             0.294228  0.240937
                                        radius            0.149886  0.123946

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff             0.968285  0.728300
                                        log_g             0.965900  3.018000
                                        radius            0.979618  1.533441
KNN               PARSEC         Base   T_eff             0.970561  0.508160
                                        log_g             0.968447  2.108800
                                        radius            0.981376  1.089249
linear_regression PARSEC         Base   T_eff             0.478529  0.367166
                                        log_g             0.274212  2.013739
                                        radius            0.586775  1.075930
mlp               PARSEC         Base   T_eff             0.418413  0.508366
                                        log_g             0.680063  1.551814
                                        radius            0.790952  0.940885
random_forest     PARSEC         Base   T_eff             0.975645  0.549174
                                        log_g             0.974096  2.152537
                                        radius            0.984808  1.111063
xgboost           PARSEC         Base   T_eff             0.823540  0.316487
                                        log_g             0.794052  1.366310
                                        radius            0.878279  0.765709

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                                        log_g                    75 : 0.043 / 90 : 0.08 / 95 : 0.1315 / 99 : 0.70731
                                        radius              75 : 0.0216 / 90 : 0.03985 / 95 : 0.06493 / 99 : 0.33128
KNN               PARSEC         Base   T_eff              75 : 0.02298 / 90 : 0.04069 / 95 : 0.06435 / 99 : 0.15869
                                        log_g                 75 : 0.0988 / 90 : 0.1666 / 95 : 0.24706 / 99 : 0.6304
                                        radius             75 : 0.04965 / 90 : 0.08372 / 95 : 0.12244 / 99 : 0.30325
linear_regression PARSEC         Base   T_eff              75 : 0.20855 / 90 : 0.27287 / 95 : 0.30722 / 99 : 0.34225
                                        log_g              75 : 1.20825 / 90 : 1.42198 / 95 : 1.52277 / 99 : 1.68722
                                        radius              75 : 0.63804 / 90 : 0.74171 / 95 : 0.7997 / 99 : 0.91087
mlp               PARSEC         Base   T_eff               75 : 0.1697 / 90 : 0.25914 / 95 : 0.30838 / 99 : 0.39154
                                        log_g              75 : 0.59017 / 90 : 0.78507 / 95 : 0.89144 / 99 : 1.05907
                                        radius               75 : 0.32184 / 90 : 0.44405 / 95 : 0.51372 / 99 : 0.646
random_forest     PARSEC         Base   T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                        log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                        radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
xgboost           PARSEC         Base   T_eff               75 : 0.0978 / 90 : 0.14934 / 95 : 0.18727 / 99 : 0.24988
                                        log_g              75 : 0.42278 / 90 : 0.62987 / 95 : 0.77118 / 99 : 0.98055
                                        radius             75 : 0.21694 / 90 : 0.31853 / 95 : 0.38254 / 99 : 0.50061

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   T_eff               6.434223
                                        log_g               6.434223
                                        radius              6.434223
KNN               PARSEC         Base   T_eff               2.859384
                                        log_g               2.859384
                                        radius              2.859384
linear_regression PARSEC         Base   T_eff               0.358326
                                        log_g               0.358326
                                        radius              0.358326
mlp               PARSEC         Base   T_eff             116.133477
                                        log_g             116.133477
                                        radius            116.133477
random_forest     PARSEC         Base   T_eff              70.705450
                                        log_g              70.705450
                                        radius             70.705450
xgboost           PARSEC         Base   T_eff               6.729006
                                        log_g               6.729006
                                        radius              6.729006

## Getting the ranges for the values

In [6]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=False)

iso_unscaled_df = iso_handler.get_isochrone_dataframe()
display(iso_unscaled_df)
phase_filtered_iso_unscaled_df = Data_preparator.filter_data(iso_unscaled_df, {'label':[1, 2, 3, 4, 5, 6]})
print_all_uniques(phase_filtered_iso_unscaled_df)

Reading PARSEC dataframe from PARSEC_iso_full_data.csv file...

          logAge   logTe   logg  label  metallicity   Mass     Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090    1.636 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092    1.656 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098    1.725 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100    1.747 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106    1.811 -0.608
...          ...     ...    ...    ...          ...    ...      ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  143.400  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  149.900  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  156.500  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  164.400  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  154.100  3.204

[681303 rows x 8 columns]

logAge  : Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3

logTe  : Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721

logg  : Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428

Rpol  : Range : 0.11 - 687.5, Mean : 25.9755, Median : 10.37

logL  : Range : -3.42 - 4.8, Mean : 1.9902, Median : 1.855

In [9]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading PARSEC dataframe from PARSEC_rescaled_iso_full_data.csv file...

          logAge   logTe   logg  label  metallicity   Mass      Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090  0.213783 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092  0.219060 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098  0.236789 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100  0.242293 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106  0.257918 -0.608
...          ...     ...    ...    ...          ...    ...       ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  2.156549  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  2.175802  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  2.194514  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  2.215902  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  2.187803  3.204

[681303 rows x 8 columns]

In [11]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'label':[1, 2, 3, 4, 5, 6, 7]})
print_all_uniques(phase_filtered_iso_df)

logAge  : Range : 5.3 - 10.25, Mean : 9.1668, Median : 9.4

logTe  : Range : 3.36 - 4.5177, Mean : 3.7418, Median : 3.7133

logg  : Range : -0.66 - 5.345, Mean : 2.4609, Median : 2.429

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 13.952, Mean : 2.3888, Median : 1.345

Rpol  : Range : -0.98 - 2.9727, Mean : 1.0977, Median : 1.0445

logL  : Range : -3.42 - 4.968, Mean : 2.1118, Median : 1.905

## Base vs Base_old

| Parameter      | Base                                                   | Base_old                                               |
| -------------  | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       | Range : 5.3 - 10.25, Mean : 9.1668, Median : 9.4       |
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   | Range : 0.09 - 13.952, Mean : 2.3888, Median : 1.345   |
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   | Range : 3.36 - 4.5177, Mean : 3.7418, Median : 3.7133  |
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   | Range : -0.66 - 5.345, Mean : 2.4609, Median : 2.429   |
| log_R          | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 | Range : -0.98 - 2.9727, Mean : 1.0977, Median : 1.0445 |

In [13]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.3621 - 4.5177
                                      log_g                 -0.664 - 5.345
                                      radius            -0.97634 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94001  0.03862
                                      log_g             0.80188  0.46515
                                      radius            0.84875  0.23276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01473  0.00327
                                      log_g             0.18745  0.03707
                                      radius            0.09385  0.01859

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.96959  0.82994
                                      log_g             0.89625  4.56946
                                      radius            0.92171  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.01297 / 90 : 0.03519 / 95 : 0.07492 / 99 : 0.15743
                                      log_g              75 : 0.14956 / 90 : 0.45314 / 95 : 1.08289 / 99 : 2.16149
                                      radius             75 : 0.07486 / 90 : 0.22674 / 95 : 0.54149 / 99 : 1.08185

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.3621 - 4.5177
                                      log_g                  3.241 - 5.345
                                      radius            -0.97634 - 1.16524

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.97353  0.04386
                                      log_g            -0.13311  0.37086
                                      radius            0.75594  0.18566

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.00886  0.00019
                                      log_g             0.08488  0.00096
                                      radius            0.04266  0.00056

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.98692  0.78713
                                      log_g             0.74219  4.42400
                                      radius            0.90123  2.21647

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.00248 / 90 : 0.01189 / 95 : 0.03921 / 99 : 0.15878
                                      log_g               75 : 0.00719 / 90 : 0.05995 / 95 : 0.43503 / 99 : 2.0369
                                      radius             75 : 0.00417 / 90 : 0.03049 / 95 : 0.21772 / 99 : 1.01901

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 2.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                 3.602 - 4.446
                                      log_g                 0.638 - 4.283
                                      radius            0.01995 - 2.45849

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.89274  0.05766
                                      log_g             0.44545  0.64549
                                      radius            0.69784  0.32276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.03358  0.01668
                                      log_g             0.30077  0.06876
                                      radius            0.15043  0.03445

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.95186  0.76853
                                      log_g             0.72854  3.87044
                                      radius            0.83972  1.93497

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.04114 / 90 : 0.08721 / 95 : 0.12506 / 99 : 0.20918
                                      log_g              75 : 0.20417 / 90 : 1.09676 / 95 : 1.69667 / 99 : 2.63871
                                      radius              75 : 0.10188 / 90 : 0.54834 / 95 : 0.84849 / 99 : 1.3189

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 3.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff            -0.49173  0.05765
                                      log_g            -0.15647  0.88771
                                      radius            0.16704  0.44391

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.02682  0.00537
                                      log_g             0.45942  0.08292
                                      radius            0.22974  0.04154

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.17087  0.82994
                                      log_g             0.30896  4.56946
                                      radius            0.54703  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.02652 / 90 : 0.08725 / 95 : 0.12803 / 99 : 0.21171
                                      log_g              75 : 0.53918 / 90 : 1.61797 / 95 : 2.17152 / 99 : 3.53068
                                      radius               75 : 0.2701 / 90 : 0.80932 / 95 : 1.0859 / 99 : 1.76536

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 4.0

                                                           value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             3.5301 - 3.786
                                      log_g             -0.122 - 2.979
                                      radius            0.7819 - 2.832

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.62291  0.01905
                                      log_g             0.87922  0.14520
                                      radius            0.94651  0.07263

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.00587  0.00167
                                      log_g             0.07179  0.02536
                                      radius            0.03594  0.01275

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.82182  0.82261
                                      log_g             0.93934  3.47101
                                      radius            0.97290  1.73608

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.00674 / 90 : 0.01467 / 95 : 0.02069 / 99 : 0.04566
                                      log_g              75 : 0.09598 / 90 : 0.19284 / 95 : 0.27143 / 99 : 0.54299
                                      radius             75 : 0.04805 / 90 : 0.09664 / 95 : 0.13622 / 99 : 0.27081

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff                3.5644 - 4.272
                                      log_g                 0.206 - 2.963
                                      radius            0.87875 - 2.66699

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.88479  0.03892
                                      log_g             0.89409  0.24161
                                      radius            0.94160  0.11889

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01249  0.00060
                                      log_g             0.07722  0.00207
                                      radius            0.03706  0.00105

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94302  0.53028
                                      log_g             0.94879  2.36347
                                      radius            0.97122  1.18061

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               75 : 0.00692 / 90 : 0.03075 / 95 : 0.06821 / 99 : 0.1944
                                      log_g               75 : 0.0347 / 90 : 0.18247 / 95 : 0.44613 / 99 : 1.26442
                                      radius             75 : 0.01622 / 90 : 0.08491 / 95 : 0.20976 / 99 : 0.63122

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 6.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               3.5437 - 4.2601
                                      log_g                -0.019 - 2.869
                                      radius            0.94052 - 2.77967

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.88415  0.05357
                                      log_g             0.52971  0.42553
                                      radius            0.71494  0.21300

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.02094  0.00370
                                      log_g             0.16158  0.01940
                                      radius            0.08069  0.00953

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.94640  0.50684
                                      log_g             0.80283  2.36551
                                      radius            0.86588  1.17960

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               75 : 0.01251 / 90 : 0.0605 / 95 : 0.12239 / 99 : 0.24719
                                      log_g               75 : 0.07115 / 90 : 0.49024 / 95 : 1.12512 / 99 : 1.9852
                                      radius             75 : 0.03539 / 90 : 0.24311 / 95 : 0.56037 / 99 : 0.99745

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

Results for the label category with a value of 7.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff               3.4527 - 4.0581
                                      log_g                -0.664 - 2.879
                                      radius            0.78732 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.65780  0.03328
                                      log_g             0.70477  0.43448
                                      radius            0.80831  0.21778

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.01583  0.00563
                                      log_g             0.21753  0.07651
                                      radius            0.10915  0.03865

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             0.81224  0.65706
                                      log_g             0.83957  4.53161
                                      radius            0.89907  2.27642

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff              75 : 0.01721 / 90 : 0.03676 / 95 : 0.07856 / 99 : 0.13199
                                      log_g                75 : 0.2363 / 90 : 0.5294 / 95 : 1.12638 / 99 : 1.82932
                                      radius             75 : 0.11868 / 90 : 0.26535 / 95 : 0.56384 / 99 : 0.91586

                                                            time
model         physical_model filter   output_parameter
random_forest PARSEC         Base_old T_eff             123.2777
                                      log_g             123.2777
                                      radius            123.2777

In [14]:
compare_metrics(path, value_rounding=5,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.3621 - 4.5177
                                      log_g                 -0.384 - 5.345
                                      radius            -0.97634 - 2.83727
                             Base_old T_eff                3.3621 - 4.5177
                                      log_g                 -0.664 - 5.345
                                      radius            -0.97634 - 2.97271

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95666  0.03783
                                      log_g             0.80743  0.45892
                                      radius            0.85842  0.22942
                             Base_old T_eff             0.94001  0.03862
                                      log_g             0.80188  0.46515
                                      radius            0.84875  0.23276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01220  0.00150
                                      log_g             0.14624  0.01272
                                      radius            0.07307  0.00644
                             Base_old T_eff             0.01473  0.00327
                                      log_g             0.18745  0.03707
                                      radius            0.09385  0.01859

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.97812  0.82900
                                      log_g             0.89985  4.62086
                                      radius            0.92717  2.31030
                             Base_old T_eff             0.96959  0.82994
                                      log_g             0.89625  4.56946
                                      radius            0.92171  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                      log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                      radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
                             Base_old T_eff              75 : 0.01297 / 90 : 0.03519 / 95 : 0.07492 / 99 : 0.15743
                                      log_g              75 : 0.14956 / 90 : 0.45314 / 95 : 1.08289 / 99 : 2.16149
                                      radius             75 : 0.07486 / 90 : 0.22674 / 95 : 0.54149 / 99 : 1.08185

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 1.0

                                                               value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.3621 - 4.5177
                                      log_g                  3.233 - 5.345
                                      radius            -0.97634 - 1.16879
                             Base_old T_eff                3.3621 - 4.5177
                                      log_g                  3.241 - 5.345
                                      radius            -0.97634 - 1.16524

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.98266  0.03535
                                      log_g             0.17211  0.31599
                                      radius            0.82160  0.15816
                             Base_old T_eff             0.97353  0.04386
                                      log_g            -0.13311  0.37086
                                      radius            0.75594  0.18566

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00734  0.00019
                                      log_g             0.07026  0.00098
                                      radius            0.03533  0.00057
                             Base_old T_eff             0.00886  0.00019
                                      log_g             0.08488  0.00096
                                      radius            0.04266  0.00056

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.99140  0.76950
                                      log_g             0.77598  4.22632
                                      radius            0.92280  2.11281
                             Base_old T_eff             0.98692  0.78713
                                      log_g             0.74219  4.42400
                                      radius            0.90123  2.21647

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                      log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                      radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
                             Base_old T_eff              75 : 0.00248 / 90 : 0.01189 / 95 : 0.03921 / 99 : 0.15878
                                      log_g               75 : 0.00719 / 90 : 0.05995 / 95 : 0.43503 / 99 : 2.0369
                                      radius             75 : 0.00417 / 90 : 0.03049 / 95 : 0.21772 / 99 : 1.01901

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 2.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.6053 - 4.446
                                      log_g                 0.638 - 4.299
                                      radius            0.01995 - 2.45849
                             Base_old T_eff                 3.602 - 4.446
                                      log_g                 0.638 - 4.283
                                      radius            0.01995 - 2.45849

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.89976  0.05591
                                      log_g             0.46261  0.63227
                                      radius            0.70710  0.31615
                             Base_old T_eff             0.89274  0.05766
                                      log_g             0.44545  0.64549
                                      radius            0.69784  0.32276

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.03253  0.01636
                                      log_g             0.28937  0.06806
                                      radius            0.14474  0.03407
                             Base_old T_eff             0.03358  0.01668
                                      log_g             0.30077  0.06876
                                      radius            0.15043  0.03445

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95495  0.76590
                                      log_g             0.73743  3.68299
                                      radius            0.84506  1.84107
                             Base_old T_eff             0.95186  0.76853
                                      log_g             0.72854  3.87044
                                      radius            0.83972  1.93497

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                      log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                      radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
                             Base_old T_eff              75 : 0.04114 / 90 : 0.08721 / 95 : 0.12506 / 99 : 0.20918
                                      log_g              75 : 0.20417 / 90 : 1.09676 / 95 : 1.69667 / 99 : 2.63871
                                      radius              75 : 0.10188 / 90 : 0.54834 / 95 : 0.84849 / 99 : 1.3189

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 3.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727
                             Base_old T_eff              3.4342 - 3.7459
                                      log_g               -0.384 - 3.823
                                      radius            0.2878 - 2.83727

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff            -0.50233  0.05758
                                      log_g            -0.17212  0.89197
                                      radius            0.15865  0.44602
                             Base_old T_eff            -0.49173  0.05765
                                      log_g            -0.15647  0.88771
                                      radius            0.16704  0.44391

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.02619  0.00468
                                      log_g             0.45108  0.07740
                                      radius            0.22559  0.03876
                             Base_old T_eff             0.02682  0.00537
                                      log_g             0.45942  0.08292
                                      radius            0.22974  0.04154

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.16706  0.80651
                                      log_g             0.30682  4.62086
                                      radius            0.54596  2.31030
                             Base_old T_eff             0.17087  0.82994
                                      log_g             0.30896  4.56946
                                      radius            0.54703  2.28511

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                      log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                      radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
                             Base_old T_eff              75 : 0.02652 / 90 : 0.08725 / 95 : 0.12803 / 99 : 0.21171
                                      log_g              75 : 0.53918 / 90 : 1.61797 / 95 : 2.17152 / 99 : 3.53068
                                      radius               75 : 0.2701 / 90 : 0.80932 / 95 : 1.0859 / 99 : 1.76536

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 4.0

                                                             value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               3.5328 - 3.786
                                      log_g               -0.102 - 2.978
                                      radius            0.7819 - 2.82724
                             Base_old T_eff               3.5301 - 3.786
                                      log_g               -0.122 - 2.979
                                      radius              0.7819 - 2.832

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.65912  0.01792
                                      log_g             0.91454  0.11709
                                      radius            0.96217  0.05855
                             Base_old T_eff             0.62291  0.01905
                                      log_g             0.87922  0.14520
                                      radius            0.94651  0.07263

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00390  0.00079
                                      log_g             0.04294  0.00904
                                      radius            0.02149  0.00453
                             Base_old T_eff             0.00587  0.00167
                                      log_g             0.07179  0.02536
                                      radius            0.03594  0.01275

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.83613  0.82900
                                      log_g             0.95670  3.48559
                                      radius            0.98093  1.74352
                             Base_old T_eff             0.82182  0.82261
                                      log_g             0.93934  3.47101
                                      radius            0.97290  1.73608

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                      log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                      radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
                             Base_old T_eff              75 : 0.00674 / 90 : 0.01467 / 95 : 0.02069 / 99 : 0.04566
                                      log_g              75 : 0.09598 / 90 : 0.19284 / 95 : 0.27143 / 99 : 0.54299
                                      radius             75 : 0.04805 / 90 : 0.09664 / 95 : 0.13622 / 99 : 0.27081

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 5.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                3.5642 - 4.272
                                      log_g                   0.2 - 2.963
                                      radius            0.87875 - 2.66997
                             Base_old T_eff                3.5644 - 4.272
                                      log_g                 0.206 - 2.963
                                      radius            0.87875 - 2.66699

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.90791  0.03474
                                      log_g             0.96665  0.13291
                                      radius            0.98332  0.06236
                             Base_old T_eff             0.88479  0.03892
                                      log_g             0.89409  0.24161
                                      radius            0.94160  0.11889

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.00953  0.00044
                                      log_g             0.03826  0.00149
                                      radius            0.01750  0.00077
                             Base_old T_eff             0.01249  0.00060
                                      log_g             0.07722  0.00207
                                      radius            0.03706  0.00105

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95348  0.50261
                                      log_g             0.98331  2.00068
                                      radius            0.99166  1.01731
                             Base_old T_eff             0.94302  0.53028
                                      log_g             0.94879  2.36347
                                      radius            0.97122  1.18061

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                      log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                      radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
                             Base_old T_eff               75 : 0.00692 / 90 : 0.03075 / 95 : 0.06821 / 99 : 0.1944
                                      log_g               75 : 0.0347 / 90 : 0.18247 / 95 : 0.44613 / 99 : 1.26442
                                      radius             75 : 0.01622 / 90 : 0.08491 / 95 : 0.20976 / 99 : 0.63122

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

Results for the label category with a value of 6.0

                                                              value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               3.5416 - 4.2601
                                      log_g                -0.017 - 2.837
                                      radius            0.96308 - 2.77779
                             Base_old T_eff               3.5437 - 4.2601
                                      log_g                -0.019 - 2.869
                                      radius            0.94052 - 2.77967

                                                            RVE     RMSE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.95163  0.03379
                                      log_g             0.94854  0.13499
                                      radius            0.96977  0.06633
                             Base_old T_eff             0.88415  0.05357
                                      log_g             0.52971  0.42553
                                      radius            0.71494  0.21300

                                                            MAE    MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01059  0.00312
                                      log_g             0.04500  0.01502
                                      radius            0.02199  0.00736
                             Base_old T_eff             0.02094  0.00370
                                      log_g             0.16158  0.01940
                                      radius            0.08069  0.00953

                                                           CORR   MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.97565  0.54917
                                      log_g             0.97410  2.15254
                                      radius            0.98481  1.11106
                             Base_old T_eff             0.94640  0.50684
                                      log_g             0.80283  2.36551
                                      radius            0.86588  1.17960

                                                                                                        Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                      log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                      radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
                             Base_old T_eff               75 : 0.01251 / 90 : 0.0605 / 95 : 0.12239 / 99 : 0.24719
                                      log_g               75 : 0.07115 / 90 : 0.49024 / 95 : 1.12512 / 99 : 1.9852
                                      radius             75 : 0.03539 / 90 : 0.24311 / 95 : 0.56037 / 99 : 0.99745

                                                             time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545
                                      log_g              70.70545
                                      radius             70.70545
                             Base_old T_eff             123.27770
                                      log_g             123.27770
                                      radius            123.27770

In [15]:
compare_metrics(path, value_rounding=5, relative_values=True,
                output_parameters=["T_eff", "log_g", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base", "Base_old"])

Results for the Global category with a value of 1.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.3621 - 4.5177
                                      log_g                                       -0.384 - 5.345
                                      radius            -0.9763360818022064 - 2.8372727025023003
                             Base_old T_eff                                      3.3621 - 4.5177
                                      log_g                                       -0.664 - 5.345
                                      radius            -0.9763360818022064 - 2.9727118405470665

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9566608469406531
                                      log_g             0.8074266704690882
                                      radius            0.8584173604243724
                             Base_old T_eff             0.9400055838628675
                                      log_g             0.8018764240434271
                                      radius            0.8487511273210078

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             3.27404%  1.05542%
                                      log_g             8.01056%  2.55264%
                                      radius            6.01582%  1.91598%
                             Base_old T_eff             3.34222%  1.27496%
                                      log_g             7.74092%  3.11946%
                                      radius            5.89414%  2.37645%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.12987%
                                      log_g             0.22197%
                                      radius            0.16887%
                             Base_old T_eff             0.28275%
                                      log_g             0.61688%
                                      radius             0.4707%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9781241008271904
                                      log_g             0.8998465625312148
                                      radius            0.9271725495364581
                             Base_old T_eff               0.96959438256482
                                      log_g             0.8962498071639723
                                      radius            0.9217125416456452

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              71.7375%
                                      log_g             80.65743%
                                      radius            60.58031%
                             Base_old T_eff             71.81869%
                                      log_g             76.04366%
                                      radius            57.86477%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.62651% / 90 : 2.51731% / 95 : 5.59363% / 99 : 14.74213%
                                      log_g             75 : 1.13458% / 90 : 4.92756% / 95 : 15.90993% / 99 : 41.45104%
                                      radius            75 : 0.85011% / 90 : 3.68601% / 95 : 11.93856% / 99 : 31.13822%
                             Base_old T_eff              75 : 1.12236% / 90 : 3.04517% / 95 : 6.48321% / 99 : 13.62323%
                                      log_g             75 : 2.48893% / 90 : 7.54102% / 95 : 18.02113% / 99 : 35.97088%
                                      radius            75 : 1.89565% / 90 : 5.74164% / 95 : 13.71191% / 99 : 27.39521%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 1.0

                                                                                     value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.3621 - 4.5177
                                      log_g                                        3.233 - 5.345
                                      radius            -0.9763360818022064 - 1.1687920203141815
                             Base_old T_eff                                      3.3621 - 4.5177
                                      log_g                                        3.241 - 5.345
                                      radius             -0.9763360818022064 - 1.165244326125311

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                0.982663800306455
                                      log_g              0.17211468827279353
                                      radius               0.821604552614865
                             Base_old T_eff                0.973528897128316
                                      log_g             -0.13310881348647374
                                      radius               0.755936919156293

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              3.05914%   0.6353%
                                      log_g             14.96154%  3.32668%
                                      radius             7.37316%  1.64715%
                             Base_old T_eff              3.79505%  0.76704%
                                      log_g             17.62646%  4.03418%
                                      radius             8.66933%  1.99187%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.01661%
                                      log_g              0.0464%
                                      radius            0.02638%
                             Base_old T_eff             0.01683%
                                      log_g             0.04563%
                                      radius            0.02623%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9914002808313593
                                      log_g             0.7759789538352955
                                      radius            0.9227998598367169
                             Base_old T_eff             0.9869182882562207
                                      log_g             0.7421949820009498
                                      radius            0.9012337185646798

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              66.58844%
                                      log_g             200.10967%
                                      radius             98.49346%
                             Base_old T_eff              68.11462%
                                      log_g             210.26613%
                                      radius            103.49706%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.20336% / 90 : 0.93977% / 95 : 2.65317% / 99 : 11.18813%
                                      log_g             75 : 0.32244% / 90 : 2.31913% / 95 : 15.31534% / 99 : 83.69934%
                                      radius             75 : 0.18554% / 90 : 1.16543% / 95 : 7.53521% / 99 : 41.25068%
                             Base_old T_eff               75 : 0.21461% / 90 : 1.0289% / 95 : 3.39304% / 99 : 13.74005%
                                      log_g             75 : 0.34173% / 90 : 2.84933% / 95 : 20.67633% / 99 : 96.81084%
                                      radius            75 : 0.19472% / 90 : 1.42371% / 95 : 10.16632% / 99 : 47.58215%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 2.0

                                                                                   value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                     3.6053 - 4.446
                                      log_g                                      0.638 - 4.299
                                      radius            0.0199466816788423 - 2.458486763798206
                             Base_old T_eff                                      3.602 - 4.446
                                      log_g                                      0.638 - 4.283
                                      radius            0.0199466816788423 - 2.458486763798206

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.8997608573485408
                                      log_g             0.4626143591760997
                                      radius            0.7071019602387656
                             Base_old T_eff             0.8927407703700583
                                      log_g             0.4454468449443749
                                      radius            0.6978393346553258

                                                             RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              6.65051%  3.86929%
                                      log_g              17.2705%  7.90419%
                                      radius            12.96467%  5.93547%
                             Base_old T_eff              6.83203%  3.97892%
                                      log_g             17.70896%  8.25146%
                                      radius            13.23582%  6.16892%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             1.94655%
                                      log_g             1.85908%
                                      radius            1.39712%
                             Base_old T_eff             1.97679%
                                      log_g             1.88632%
                                      radius            1.41275%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9549507593925414
                                      log_g              0.737427211287738
                                      radius            0.8450590476514552
                             Base_old T_eff             0.9518559539733927
                                      log_g             0.7285415603671077
                                      radius            0.8397198459667251

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               91.1031%
                                      log_g             100.60066%
                                      radius               75.499%
                             Base_old T_eff              91.05832%
                                      log_g             106.18491%
                                      radius             79.34946%

                                                                                                             Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 4.69252% / 90 : 9.98454% / 95 : 14.49506% / 99 : 23.70881%
                                      log_g              75 : 5.3103% / 90 : 27.99372% / 95 : 45.70773% / 99 : 72.12101%
                                      radius            75 : 3.98763% / 90 : 21.01011% / 95 : 34.30987% / 99 : 54.14797%
                             Base_old T_eff             75 : 4.87441% / 90 : 10.33294% / 95 : 14.81754% / 99 : 24.78436%
                                      log_g             75 : 5.60137% / 90 : 30.08944% / 95 : 46.54787% / 99 : 72.39259%
                                      radius              75 : 4.17791% / 90 : 22.48641% / 95 : 34.795% / 99 : 54.08564%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 3.0

                                                                                   value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                    3.4342 - 3.7459
                                      log_g                                     -0.384 - 3.823
                                      radius            0.287801729930226 - 2.8372727025023003
                             Base_old T_eff                                    3.4342 - 3.7459
                                      log_g                                     -0.384 - 3.823
                                      radius            0.287801729930226 - 2.8372727025023003

                                                                         RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              -0.5023320130390359
                                      log_g             -0.17211974773342287
                                      radius             0.15865465480581487
                             Base_old T_eff              -0.4917289111288492
                                      log_g             -0.15646503726293726
                                      radius              0.1670434959764765

                                                             RMSE        MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             18.47271%   8.40197%
                                      log_g             21.20201%  10.72202%
                                      radius            17.49471%   8.84842%
                             Base_old T_eff             18.49658%   8.60292%
                                      log_g             21.10084%  10.92031%
                                      radius            17.41182%   9.01137%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             1.50034%
                                      log_g             1.83977%
                                      radius            1.52046%
                             Base_old T_eff             1.72423%
                                      log_g             1.97093%
                                      radius            1.62947%

                                                                       CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              0.1670618613045383
                                      log_g             0.30681622944559384
                                      radius             0.5459579150223091
                             Base_old T_eff             0.17087474457579632
                                      log_g             0.30896325426816623
                                      radius              0.547026492319328

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             258.74655%
                                      log_g             109.83751%
                                      radius             90.61865%
                             Base_old T_eff             266.26139%
                                      log_g             108.61573%
                                      radius             89.63066%

                                                                                                              Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               75 : 7.94033% / 90 : 27.38851% / 95 : 41.81585% / 99 : 68.2804%
                                      log_g             75 : 11.76444% / 90 : 38.38769% / 95 : 52.85477% / 99 : 84.77561%
                                      radius              75 : 9.72515% / 90 : 31.67245% / 95 : 43.60591% / 99 : 69.9604%
                             Base_old T_eff              75 : 8.50818% / 90 : 27.99166% / 95 : 41.07475% / 99 : 67.92108%
                                      log_g               75 : 12.81626% / 90 : 38.459% / 95 : 51.61683% / 99 : 83.92394%
                                      radius            75 : 10.59435% / 90 : 31.74463% / 95 : 42.59315% / 99 : 69.24417%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 4.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.5328 - 3.786
                                      log_g                                      -0.102 - 2.978
                                      radius            0.7818989193511491 - 2.8272399995056454
                             Base_old T_eff                                      3.5301 - 3.786
                                      log_g                                      -0.122 - 2.979
                                      radius             0.7818989193511491 - 2.831997677235896

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff               0.65911942798238
                                      log_g             0.9145444334060797
                                      radius            0.9621702735006398
                             Base_old T_eff             0.6229105972444626
                                      log_g             0.8792208971421926
                                      radius             0.946513857443982

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             7.07675%  1.53908%
                                      log_g             3.80149%   1.3943%
                                      radius            2.86253%  1.05076%
                             Base_old T_eff             7.44586%   2.2939%
                                      log_g             4.68252%  2.31494%
                                      radius            3.54265%  1.75331%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.31043%
                                      log_g              0.2936%
                                      radius            0.22172%
                             Base_old T_eff             0.65412%
                                      log_g             0.81782%
                                      radius            0.62208%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              0.836128348980831
                                      log_g              0.956704367836196
                                      radius            0.9809328484849373
                             Base_old T_eff              0.821823767317247
                                      log_g             0.9393382069091358
                                      radius            0.9728959660019413

                                                            MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             327.40858%
                                      log_g             113.16865%
                                      radius             85.24363%
                             Base_old T_eff             321.45719%
                                      log_g             111.93189%
                                      radius              84.6826%

                                                                                                           Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             75 : 1.26382% / 90 : 3.10032% / 95 : 5.51343% / 99 : 16.12164%
                                      log_g             75 : 1.39286% / 90 : 3.35584% / 95 : 5.74481% / 99 : 16.01786%
                                      radius             75 : 1.04579% / 90 : 2.53601% / 95 : 4.3406% / 99 : 12.03907%
                             Base_old T_eff             75 : 2.63384% / 90 : 5.73271% / 95 : 8.08519% / 99 : 17.84291%
                                      log_g             75 : 3.09513% / 90 : 6.21864% / 95 : 8.75298% / 99 : 17.51016%
                                      radius            75 : 2.34379% / 90 : 4.71392% / 95 : 6.64456% / 99 : 13.20961%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 5.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                      3.5642 - 4.272
                                      log_g                                         0.2 - 2.963
                                      radius             0.8787515201730021 - 2.669967369908504
                             Base_old T_eff                                      3.5644 - 4.272
                                      log_g                                       0.206 - 2.963
                                      radius            0.8787515201730021 - 2.6669857183296606

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9079086436663277
                                      log_g             0.9666549586583413
                                      radius            0.9833215630488885
                             Base_old T_eff             0.8847861253902843
                                      log_g              0.894091099961791
                                      radius            0.9415960186573777

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             4.90803%  1.34626%
                                      log_g             4.81053%   1.3849%
                                      radius            3.48136%  0.97724%
                             Base_old T_eff             5.49969%  1.76513%
                                      log_g             8.76338%  2.80087%
                                      radius            6.64855%  2.07245%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.06174%
                                      log_g             0.05393%
                                      radius            0.04283%
                             Base_old T_eff             0.08437%
                                      log_g             0.07508%
                                      radius            0.05848%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9534772118510992
                                      log_g             0.9833138504657927
                                      radius            0.9916566947756928
                             Base_old T_eff             0.9430227249846139
                                      log_g             0.9487935634643654
                                      radius            0.9712195233410787

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              71.0099%
                                      log_g             72.40974%
                                      radius            56.79423%
                             Base_old T_eff             74.94096%
                                      log_g             85.72627%
                                      radius            66.02081%

                                                                                                            Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              75 : 0.55524% / 90 : 2.82142% / 95 : 6.08929% / 99 : 26.40294%
                                      log_g                75 : 0.58053% / 90 : 3.20413% / 95 : 6.8527% / 99 : 24.8802%
                                      radius             75 : 0.40419% / 90 : 2.21135% / 95 : 4.93687% / 99 : 17.36697%
                             Base_old T_eff              75 : 0.97795% / 90 : 4.34568% / 95 : 9.63963% / 99 : 27.47315%
                                      log_g             75 : 1.25861% / 90 : 6.61843% / 95 : 16.18172% / 99 : 45.86217%
                                      radius            75 : 0.90704% / 90 : 4.74826% / 95 : 11.73001% / 99 : 35.29851%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

Results for the label category with a value of 6.0

                                                                                    value range  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                                     3.5416 - 4.2601
                                      log_g                                      -0.017 - 2.837
                                      radius            0.9630791606418272 - 2.7777891874348675
                             Base_old T_eff                                     3.5437 - 4.2601
                                      log_g                                      -0.019 - 2.869
                                      radius             0.9405164849325672 - 2.779668627207148

                                                                       RVE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9516275813074686
                                      log_g             0.9485394146228903
                                      radius            0.9697670887087206
                             Base_old T_eff             0.8841526345883329
                                      log_g             0.5297053497785793
                                      radius            0.7149449017388567

                                                            RMSE       MAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             4.70228%  1.47386%
                                      log_g             4.72993%  1.57686%
                                      radius            3.65497%  1.21203%
                             Base_old T_eff             7.47708%  2.92285%
                                      log_g             14.7343%  5.59501%
                                      radius            11.5817%  4.38722%

                                                           MedAE  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.43451%
                                      log_g             0.52642%
                                      radius            0.40548%
                             Base_old T_eff             0.51651%
                                      log_g             0.67173%
                                      radius            0.51832%

                                                                      CORR  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             0.9756452395472536
                                      log_g             0.9740958718877286
                                      radius            0.9848075867184325
                             Base_old T_eff              0.946399693541685
                                      log_g              0.802827285555517
                                      radius            0.8658808046077017

                                                           MAX_ER  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff             76.43337%
                                      log_g             75.42176%
                                      radius            61.22537%
                             Base_old T_eff             70.74888%
                                      log_g              81.9081%
                                      radius            64.13849%

                                                                                                             Percentiles  \
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff                 75 : 1.19276% / 90 : 2.746% / 95 : 5.16632% / 99 : 24.46207%
                                      log_g                75 : 1.44149% / 90 : 3.11528% / 95 : 5.24387% / 99 : 23.5417%
                                      radius              75 : 1.12911% / 90 : 2.39267% / 95 : 4.05354% / 99 : 16.37397%
                             Base_old T_eff                75 : 1.74623% / 90 : 8.445% / 95 : 17.08403% / 99 : 34.50447%
                                      log_g             75 : 2.46364% / 90 : 16.97507% / 95 : 38.95845% / 99 : 68.73961%
                                      radius            75 : 1.92426% / 90 : 13.21859% / 95 : 30.46893% / 99 : 54.23423%

                                                                      time
model         physical_model filter   output_parameter
random_forest PARSEC         Base     T_eff              70.70545029640198
                                      log_g              70.70545029640198
                                      radius             70.70545029640198
                             Base_old T_eff             123.27769899368286
                                      log_g             123.27769899368286
                                      radius            123.27769899368286

### Conclusion

Removing phase 7 (EAGB) improves the results of Global by a small margin. Most of this improvement can be seen in phase 6 which phase 7 superpose the most with.

Since there are no TPAGB phase, the improvement is less apparent than with the MIST dataset but it is still present.

## Base vs mass_filtered

| Parameter      | Base                                                   | mass_smaller_3                                         | 
| -------------  | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       | Range : 6.8 - 10.25, Mean : 9.4807, Median : 9.5       | 
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   | Range : 0.09 - 13.943, Mean : 2.3223, Median : 1.331   | 
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   | Range : 3.36 - 4.1907, Mean : 3.732, Median : 3.7204   | 
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   | Range : -0.38 - 5.345, Mean : 2.8946, Median : 2.504   | 
| R              | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 | Range : -0.98 - 2.3632, Mean : 0.8085, Median : 1.0017 |

### T_eff parameter

In [16]:
compare_metrics(path, 
                output_parameters=["T_eff"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9451742472012191
                                 mass_smaller_3 T_eff              0.8871586813443988
KNN               PARSEC         Base           T_eff              0.9289910884078197
                                 mass_smaller_3 T_eff               0.910185955691971
linear_regression PARSEC         Base           T_eff             0.34445841658008647
                                 mass_smaller_3 T_eff              0.2566977420116534
mlp               PARSEC         Base           T_eff             0.45667538004833186
                                 mass_smaller_3 T_eff             0.29160421609577014
random_forest     PARSEC         Base           T_eff              0.9566608469406531
                                 mass_smaller_3 T_eff               0.913203605722624
xgboost           PARSEC         Base           T_eff              0.7726322878335125
                                 mass_smaller_3 T_eff              0.8523662223135867

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.042554292673794465
                                 mass_smaller_3 T_eff              0.03328590494814946
KNN               PARSEC         Base           T_eff              0.04851081543113413
                                 mass_smaller_3 T_eff              0.02969603069690199
linear_regression PARSEC         Base           T_eff              0.14714610399062228
                                 mass_smaller_3 T_eff              0.08542972296861495
mlp               PARSEC         Base           T_eff              0.13410280662162238
                                 mass_smaller_3 T_eff               0.0835840021057498
random_forest     PARSEC         Base           T_eff              0.03783483575687937
                                 mass_smaller_3 T_eff              0.02919290534578891
xgboost           PARSEC         Base           T_eff              0.08665888725371604
                                 mass_smaller_3 T_eff              0.03807317898165961

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.012520623599939452
                                 mass_smaller_3 T_eff             0.010588167800465901
KNN               PARSEC         Base           T_eff               0.0162096969395537
                                 mass_smaller_3 T_eff             0.011431817655160359
linear_regression PARSEC         Base           T_eff              0.10806443419089096
                                 mass_smaller_3 T_eff              0.06404163652696164
mlp               PARSEC         Base           T_eff              0.09348296889333235
                                 mass_smaller_3 T_eff             0.061867837532265164
random_forest     PARSEC         Base           T_eff              0.01219639278844237
                                 mass_smaller_3 T_eff             0.010209152963035109
xgboost           PARSEC         Base           T_eff             0.044921245386785554
                                 mass_smaller_3 T_eff             0.019494483185781827

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.001191428571428066
                                 mass_smaller_3 T_eff               0.00101575187969849
KNN               PARSEC         Base           T_eff             0.0018799999999998818
                                 mass_smaller_3 T_eff             0.0012199999999999989
linear_regression PARSEC         Base           T_eff               0.07505188017050912
                                 mass_smaller_3 T_eff              0.047681310121496345
mlp               PARSEC         Base           T_eff               0.06409550839974631
                                 mass_smaller_3 T_eff               0.04447700503672225
random_forest     PARSEC         Base           T_eff             0.0015007253298946477
                                 mass_smaller_3 T_eff             0.0013401235282757273
xgboost           PARSEC         Base           T_eff              0.012216230392456007
                                 mass_smaller_3 T_eff              0.006201692199707232

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9724235183367057
                                 mass_smaller_3 T_eff             0.9429494041263922
KNN               PARSEC         Base           T_eff             0.9638581868639022
                                 mass_smaller_3 T_eff              0.954103921746265
linear_regression PARSEC         Base           T_eff             0.5869057992445806
                                 mass_smaller_3 T_eff             0.5066534739968079
mlp               PARSEC         Base           T_eff             0.6876406178694955
                                 mass_smaller_3 T_eff             0.6575036455434058
random_forest     PARSEC         Base           T_eff             0.9781241008271904
                                 mass_smaller_3 T_eff             0.9558172268263041
xgboost           PARSEC         Base           T_eff              0.879158545551974
                                 mass_smaller_3 T_eff              0.923428111605875

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                          0.8407
                                 mass_smaller_3 T_eff              0.3836999999999997
KNN               PARSEC         Base           T_eff              0.8291399999999998
                                 mass_smaller_3 T_eff                          0.4295
linear_regression PARSEC         Base           T_eff              0.5457108330954776
                                 mass_smaller_3 T_eff             0.32000842330395507
mlp               PARSEC         Base           T_eff              0.8323897989412399
                                 mass_smaller_3 T_eff              0.6336879767814234
random_forest     PARSEC         Base           T_eff              0.8289985333333334
                                 mass_smaller_3 T_eff             0.28554875000000557
xgboost           PARSEC         Base           T_eff              0.6862123130798343
                                 mass_smaller_3 T_eff               0.324363548278809

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.0066 / 90 : 0.0262 / 95 : 0.0647 / 99 : 0.19773
                                 mass_smaller_3 T_eff                75 : 0.00482 / 90 : 0.02104 / 95 : 0.0629 / 99 : 0.1844
KNN               PARSEC         Base           T_eff                75 : 0.0133 / 90 : 0.0398 / 95 : 0.07538 / 99 : 0.20009
                                 mass_smaller_3 T_eff               75 : 0.00762 / 90 : 0.0328 / 95 : 0.06052 / 99 : 0.14401
linear_regression PARSEC         Base           T_eff              75 : 0.14234 / 90 : 0.27293 / 95 : 0.32016 / 99 : 0.42868
                                 mass_smaller_3 T_eff               75 : 0.09087 / 90 : 0.1383 / 95 : 0.18617 / 99 : 0.25734
mlp               PARSEC         Base           T_eff                75 : 0.11522 / 90 : 0.20538 / 95 : 0.285 / 99 : 0.50069
                                 mass_smaller_3 T_eff              75 : 0.09009 / 90 : 0.13934 / 95 : 0.17681 / 99 : 0.24527
random_forest     PARSEC         Base           T_eff              75 : 0.00724 / 90 : 0.02909 / 95 : 0.06464 / 99 : 0.17036
                                 mass_smaller_3 T_eff              75 : 0.00543 / 90 : 0.02402 / 95 : 0.06044 / 99 : 0.14953
xgboost           PARSEC         Base           T_eff              75 : 0.05362 / 90 : 0.13639 / 95 : 0.20195 / 99 : 0.34634
                                 mass_smaller_3 T_eff                75 : 0.0187 / 90 : 0.05989 / 95 : 0.09447 / 99 : 0.1561

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 1.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
KNN               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
linear_regression PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
mlp               PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
random_forest     PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907
xgboost           PARSEC         Base           T_eff             3.3621 - 4.5177
                                 mass_smaller_3 T_eff             3.3621 - 4.1907

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9748322909531495
                                 mass_smaller_3 T_eff              0.975213198122586
KNN               PARSEC         Base           T_eff             0.9255387206020436
                                 mass_smaller_3 T_eff             0.9782428408568564
linear_regression PARSEC         Base           T_eff              0.597293514283356
                                 mass_smaller_3 T_eff             0.4252524861822299
mlp               PARSEC         Base           T_eff             0.5907206955331745
                                 mass_smaller_3 T_eff             0.5607280311364085
random_forest     PARSEC         Base           T_eff              0.982663800306455
                                 mass_smaller_3 T_eff             0.9843920547198056
xgboost           PARSEC         Base           T_eff             0.9035438101538388
                                 mass_smaller_3 T_eff             0.9514662316909307

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.0423812576414891
                                 mass_smaller_3 T_eff             0.025525608230402626
KNN               PARSEC         Base           T_eff               0.0740899334278856
                                 mass_smaller_3 T_eff              0.02416811908066164
linear_regression PARSEC         Base           T_eff               0.2152050705682071
                                 mass_smaller_3 T_eff              0.14224797949784304
mlp               PARSEC         Base           T_eff              0.17666405999646342
                                 mass_smaller_3 T_eff              0.11589381843074006
random_forest     PARSEC         Base           T_eff              0.03535147273459422
                                 mass_smaller_3 T_eff              0.02044262538990222
xgboost           PARSEC         Base           T_eff              0.08962926996366931
                                 mass_smaller_3 T_eff             0.039055830909155265

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.007449396025994484
                                 mass_smaller_3 T_eff             0.005852321173799819
KNN               PARSEC         Base           T_eff             0.019715328052154795
                                 mass_smaller_3 T_eff             0.009073475638292344
linear_regression PARSEC         Base           T_eff              0.18085985421238407
                                 mass_smaller_3 T_eff               0.1252941437867672
mlp               PARSEC         Base           T_eff              0.12539880208477472
                                 mass_smaller_3 T_eff              0.09347082372740609
random_forest     PARSEC         Base           T_eff             0.007341501892044874
                                 mass_smaller_3 T_eff             0.005841865256728682
xgboost           PARSEC         Base           T_eff              0.04370062094663365
                                 mass_smaller_3 T_eff              0.02276255512854454

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              4.999999999988347e-05
                                 mass_smaller_3 T_eff              6.666666666665932e-05
KNN               PARSEC         Base           T_eff               0.002020000000000355
                                 mass_smaller_3 T_eff              0.0018599999999997507
linear_regression PARSEC         Base           T_eff                0.13710958116446115
                                 mass_smaller_3 T_eff                0.10865869006110951
mlp               PARSEC         Base           T_eff                0.09267960050543134
                                 mass_smaller_3 T_eff                0.08217875082639203
random_forest     PARSEC         Base           T_eff             0.00019199999999486295
                                 mass_smaller_3 T_eff             0.00015898809523351431
xgboost           PARSEC         Base           T_eff               0.016440191650390457
                                 mass_smaller_3 T_eff               0.010862756729125955

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.9876003989251159
                                 mass_smaller_3 T_eff             0.9879085497518846
KNN               PARSEC         Base           T_eff             0.9623018163028533
                                 mass_smaller_3 T_eff             0.9892128560826348
linear_regression PARSEC         Base           T_eff             0.8536445700543512
                                 mass_smaller_3 T_eff             0.7428268179996913
mlp               PARSEC         Base           T_eff             0.7773454058575309
                                 mass_smaller_3 T_eff             0.7912014877978358
random_forest     PARSEC         Base           T_eff             0.9914002808313593
                                 mass_smaller_3 T_eff             0.9923334481253897
xgboost           PARSEC         Base           T_eff             0.9513542801799472
                                 mass_smaller_3 T_eff              0.975709546834514

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8311642857142854
                                 mass_smaller_3 T_eff              0.3836999999999997
KNN               PARSEC         Base           T_eff              0.8263199999999999
                                 mass_smaller_3 T_eff                          0.4295
linear_regression PARSEC         Base           T_eff              0.5457108330954776
                                 mass_smaller_3 T_eff             0.32000842330395507
mlp               PARSEC         Base           T_eff              0.8323897989412399
                                 mass_smaller_3 T_eff              0.6336879767814234
random_forest     PARSEC         Base           T_eff              0.7694960000000011
                                 mass_smaller_3 T_eff             0.24687900000000074
xgboost           PARSEC         Base           T_eff              0.6862123130798343
                                 mass_smaller_3 T_eff               0.324363548278809

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                  75 : 0.0011 / 90 : 0.0097 / 95 : 0.0247 / 99 : 0.1459
                                 mass_smaller_3 T_eff                 75 : 0.0006 / 90 : 0.0085 / 95 : 0.0246 / 99 : 0.12535
KNN               PARSEC         Base           T_eff               75 : 0.0082 / 90 : 0.03622 / 95 : 0.06993 / 99 : 0.43359
                                 mass_smaller_3 T_eff              75 : 0.00648 / 90 : 0.02524 / 95 : 0.04408 / 99 : 0.11518
linear_regression PARSEC         Base           T_eff              75 : 0.25535 / 90 : 0.36302 / 95 : 0.41855 / 99 : 0.48298
                                 mass_smaller_3 T_eff               75 : 0.17008 / 90 : 0.22874 / 95 : 0.25406 / 99 : 0.2871
mlp               PARSEC         Base           T_eff                75 : 0.1533 / 90 : 0.27528 / 95 : 0.39784 / 99 : 0.6293
                                 mass_smaller_3 T_eff              75 : 0.13552 / 90 : 0.18752 / 95 : 0.21801 / 99 : 0.28095
random_forest     PARSEC         Base           T_eff              75 : 0.00235 / 90 : 0.01086 / 95 : 0.03066 / 99 : 0.12929
                                 mass_smaller_3 T_eff              75 : 0.00218 / 90 : 0.01083 / 95 : 0.03187 / 99 : 0.10912
xgboost           PARSEC         Base           T_eff              75 : 0.04522 / 90 : 0.09853 / 95 : 0.19258 / 99 : 0.44504
                                 mass_smaller_3 T_eff               75 : 0.02806 / 90 : 0.0595 / 95 : 0.08534 / 99 : 0.16151

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 2.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
KNN               PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
linear_regression PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
mlp               PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
random_forest     PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397
xgboost           PARSEC         Base           T_eff              3.6053 - 4.446
                                 mass_smaller_3 T_eff             3.6813 - 4.1397

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.872460228127739
                                 mass_smaller_3 T_eff               0.6049838323957871
KNN               PARSEC         Base           T_eff               0.9019213514815497
                                 mass_smaller_3 T_eff               0.7699945838955977
linear_regression PARSEC         Base           T_eff              0.24580413337093743
                                 mass_smaller_3 T_eff               0.3554085864147183
mlp               PARSEC         Base           T_eff             -0.06049696902287538
                                 mass_smaller_3 T_eff             0.040501860137208356
random_forest     PARSEC         Base           T_eff               0.8997608573485408
                                 mass_smaller_3 T_eff               0.7442416030826616
xgboost           PARSEC         Base           T_eff               0.2421346697916199
                                 mass_smaller_3 T_eff               0.5017650969894539

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.06255115396094892
                                 mass_smaller_3 T_eff              0.06317765357377349
KNN               PARSEC         Base           T_eff             0.056525460890971636
                                 mass_smaller_3 T_eff             0.051237771238936095
linear_regression PARSEC         Base           T_eff               0.1576451482232392
                                 mass_smaller_3 T_eff              0.10163849124145655
mlp               PARSEC         Base           T_eff               0.2016864006088252
                                 mass_smaller_3 T_eff              0.11580973375261623
random_forest     PARSEC         Base           T_eff             0.055910823269444784
                                 mass_smaller_3 T_eff              0.05247428964475242
xgboost           PARSEC         Base           T_eff              0.16346869278380277
                                 mass_smaller_3 T_eff              0.07935581863957553

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.03380714142468827
                                 mass_smaller_3 T_eff              0.03278852938657706
KNN               PARSEC         Base           T_eff              0.03625290530068196
                                 mass_smaller_3 T_eff             0.034125246006389776
linear_regression PARSEC         Base           T_eff              0.12579879104006494
                                 mass_smaller_3 T_eff              0.08213297366502408
mlp               PARSEC         Base           T_eff               0.1501671715231214
                                 mass_smaller_3 T_eff              0.09758225236026025
random_forest     PARSEC         Base           T_eff              0.03252911291352382
                                 mass_smaller_3 T_eff              0.03089406866793464
xgboost           PARSEC         Base           T_eff              0.12303096453821297
                                 mass_smaller_3 T_eff              0.06510858154638126

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.015225000000000044
                                 mass_smaller_3 T_eff             0.009400000000000297
KNN               PARSEC         Base           T_eff             0.022299999999999764
                                 mass_smaller_3 T_eff              0.01910999999999996
linear_regression PARSEC         Base           T_eff              0.10439328495368216
                                 mass_smaller_3 T_eff              0.07118473120414981
mlp               PARSEC         Base           T_eff              0.11146029498426513
                                 mass_smaller_3 T_eff              0.08883450516525526
random_forest     PARSEC         Base           T_eff              0.01636466238414358
                                 mass_smaller_3 T_eff             0.012408954761905067
xgboost           PARSEC         Base           T_eff              0.08958496551513662
                                 mass_smaller_3 T_eff              0.05606627845764156

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9441691057521153
                                 mass_smaller_3 T_eff              0.8925416933006906
KNN               PARSEC         Base           T_eff              0.9541994998198405
                                 mass_smaller_3 T_eff              0.9309697248307426
linear_regression PARSEC         Base           T_eff             0.49810122500597515
                                 mass_smaller_3 T_eff              0.5966831965905013
mlp               PARSEC         Base           T_eff               0.269179604340438
                                 mass_smaller_3 T_eff              0.5177989569662957
random_forest     PARSEC         Base           T_eff              0.9549507593925414
                                 mass_smaller_3 T_eff              0.9269223296620183
xgboost           PARSEC         Base           T_eff              0.5078146897498674
                                 mass_smaller_3 T_eff              0.7570231687633359

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8240999999999996
                                 mass_smaller_3 T_eff              0.2875000000000001
KNN               PARSEC         Base           T_eff              0.6363200000000004
                                 mass_smaller_3 T_eff              0.2595200000000002
linear_regression PARSEC         Base           T_eff              0.5110059990755276
                                 mass_smaller_3 T_eff              0.3040571798406537
mlp               PARSEC         Base           T_eff              0.7710058375102826
                                 mass_smaller_3 T_eff              0.3220619560000175
random_forest     PARSEC         Base           T_eff              0.7659037285714314
                                 mass_smaller_3 T_eff             0.24106511991869795
xgboost           PARSEC         Base           T_eff              0.6752104206085203
                                 mass_smaller_3 T_eff              0.3175848976135258

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               75 : 0.03721 / 90 : 0.0862 / 95 : 0.14271 / 99 : 0.23979
                                 mass_smaller_3 T_eff               75 : 0.02955 / 90 : 0.11347 / 95 : 0.16941 / 99 : 0.2382
KNN               PARSEC         Base           T_eff              75 : 0.04752 / 90 : 0.08675 / 95 : 0.11641 / 99 : 0.19029
                                 mass_smaller_3 T_eff               75 : 0.04733 / 90 : 0.0914 / 95 : 0.11968 / 99 : 0.16175
linear_regression PARSEC         Base           T_eff               75 : 0.17836 / 90 : 0.26213 / 95 : 0.3129 / 99 : 0.41535
                                 mass_smaller_3 T_eff              75 : 0.11261 / 90 : 0.17127 / 95 : 0.20611 / 99 : 0.25215
mlp               PARSEC         Base           T_eff              75 : 0.20893 / 90 : 0.34079 / 95 : 0.43468 / 99 : 0.60504
                                 mass_smaller_3 T_eff              75 : 0.14003 / 90 : 0.18644 / 95 : 0.21327 / 99 : 0.25318
random_forest     PARSEC         Base           T_eff              75 : 0.03945 / 90 : 0.08394 / 95 : 0.12186 / 99 : 0.19932
                                 mass_smaller_3 T_eff              75 : 0.03636 / 90 : 0.09812 / 95 : 0.13041 / 99 : 0.18235
xgboost           PARSEC         Base           T_eff              75 : 0.17025 / 90 : 0.27651 / 95 : 0.35297 / 99 : 0.48104
                                 mass_smaller_3 T_eff              75 : 0.09128 / 90 : 0.12553 / 95 : 0.15135 / 99 : 0.20765

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 3.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
KNN               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
linear_regression PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
mlp               PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
random_forest     PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459
xgboost           PARSEC         Base           T_eff             3.4342 - 3.7459
                                 mass_smaller_3 T_eff             3.4342 - 3.7459

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              -0.7632012932187855
                                 mass_smaller_3 T_eff              -0.5234705113818034
KNN               PARSEC         Base           T_eff             -0.41965388075205157
                                 mass_smaller_3 T_eff               -0.190960566612143
linear_regression PARSEC         Base           T_eff               -3.483450834504893
                                 mass_smaller_3 T_eff             -0.20316412930548045
mlp               PARSEC         Base           T_eff              -3.0626539193547986
                                 mass_smaller_3 T_eff              -1.7375683728213511
random_forest     PARSEC         Base           T_eff              -0.5023320130390359
                                 mass_smaller_3 T_eff             -0.23812916797553374
xgboost           PARSEC         Base           T_eff              -1.9217965476974368
                                 mass_smaller_3 T_eff             -0.15704650262152264

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.062014552223464726
                                 mass_smaller_3 T_eff              0.05848860953001508
KNN               PARSEC         Base           T_eff              0.05656926394300638
                                 mass_smaller_3 T_eff              0.05273060740093908
linear_regression PARSEC         Base           T_eff              0.12891641417073876
                                 mass_smaller_3 T_eff              0.07908477674132959
mlp               PARSEC         Base           T_eff              0.11600524039538827
                                 mass_smaller_3 T_eff              0.08478311269948922
random_forest     PARSEC         Base           T_eff              0.05757943586910902
                                 mass_smaller_3 T_eff              0.05312077035227188
xgboost           PARSEC         Base           T_eff              0.09612792095128411
                                 mass_smaller_3 T_eff             0.056620517675600175

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.027219918269213918
                                 mass_smaller_3 T_eff             0.028422840214358244
KNN               PARSEC         Base           T_eff             0.027019570776689806
                                 mass_smaller_3 T_eff              0.02796061059294737
linear_regression PARSEC         Base           T_eff              0.09720929302507696
                                 mass_smaller_3 T_eff              0.06453246305935913
mlp               PARSEC         Base           T_eff              0.08743946502025537
                                 mass_smaller_3 T_eff              0.06281880008987074
random_forest     PARSEC         Base           T_eff              0.02618894131123609
                                 mass_smaller_3 T_eff             0.027068693641862922
xgboost           PARSEC         Base           T_eff              0.06188901809704532
                                 mass_smaller_3 T_eff              0.03556526711127393

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0037571428571430143
                                 mass_smaller_3 T_eff              0.003509999999999014
KNN               PARSEC         Base           T_eff              0.006720000000000059
                                 mass_smaller_3 T_eff              0.006499999999999506
linear_regression PARSEC         Base           T_eff               0.07418431701105521
                                 mass_smaller_3 T_eff              0.058262105991064406
mlp               PARSEC         Base           T_eff                 0.064048664167482
                                 mass_smaller_3 T_eff              0.044861511364908235
random_forest     PARSEC         Base           T_eff             0.0046765708158016395
                                 mass_smaller_3 T_eff              0.004435026190476421
xgboost           PARSEC         Base           T_eff              0.025207269287109257
                                 mass_smaller_3 T_eff              0.015437748336792012

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.124189042946256
                                 mass_smaller_3 T_eff              0.11942462598385166
KNN               PARSEC         Base           T_eff              0.16510527785954335
                                 mass_smaller_3 T_eff               0.1668115647943539
linear_regression PARSEC         Base           T_eff              0.10169028688444401
                                 mass_smaller_3 T_eff               0.4059287004302059
mlp               PARSEC         Base           T_eff              0.07525042007796028
                                 mass_smaller_3 T_eff               0.3133821552638225
random_forest     PARSEC         Base           T_eff               0.1670618613045383
                                 mass_smaller_3 T_eff              0.18654793310689494
xgboost           PARSEC         Base           T_eff             0.050496683069772764
                                 mass_smaller_3 T_eff               0.2693434343187326

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.8298000000000001
                                 mass_smaller_3 T_eff              0.2891999999999997
KNN               PARSEC         Base           T_eff              0.8132800000000002
                                 mass_smaller_3 T_eff              0.2891999999999997
linear_regression PARSEC         Base           T_eff             0.38010161373098983
                                 mass_smaller_3 T_eff             0.20863165093929892
mlp               PARSEC         Base           T_eff              0.6156126340493939
                                 mass_smaller_3 T_eff              0.3090762203689881
random_forest     PARSEC         Base           T_eff              0.8065130083333316
                                 mass_smaller_3 T_eff             0.28554875000000557
xgboost           PARSEC         Base           T_eff              0.3860601097106935
                                 mass_smaller_3 T_eff              0.2648350852966308

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.02195 / 90 : 0.0961 / 95 : 0.1443 / 99 : 0.2364
                                 mass_smaller_3 T_eff              75 : 0.02726 / 90 : 0.10436 / 95 : 0.14774 / 99 : 0.22839
KNN               PARSEC         Base           T_eff              75 : 0.02926 / 90 : 0.08358 / 95 : 0.12637 / 99 : 0.21296
                                 mass_smaller_3 T_eff              75 : 0.03537 / 90 : 0.08926 / 95 : 0.12984 / 99 : 0.20084
linear_regression PARSEC         Base           T_eff               75 : 0.13101 / 90 : 0.2356 / 95 : 0.29718 / 99 : 0.33842
                                 mass_smaller_3 T_eff               75 : 0.0969 / 90 : 0.13086 / 95 : 0.14875 / 99 : 0.17746
mlp               PARSEC         Base           T_eff              75 : 0.12108 / 90 : 0.18899 / 95 : 0.22475 / 99 : 0.37096
                                 mass_smaller_3 T_eff              75 : 0.09278 / 90 : 0.14159 / 95 : 0.17841 / 99 : 0.25178
random_forest     PARSEC         Base           T_eff              75 : 0.02475 / 90 : 0.08537 / 95 : 0.13034 / 99 : 0.21283
                                 mass_smaller_3 T_eff              75 : 0.03062 / 90 : 0.09186 / 95 : 0.13158 / 99 : 0.20429
xgboost           PARSEC         Base           T_eff              75 : 0.09793 / 90 : 0.17076 / 95 : 0.22502 / 99 : 0.30108
                                 mass_smaller_3 T_eff              75 : 0.05157 / 90 : 0.10639 / 95 : 0.13362 / 99 : 0.17684

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
KNN               PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
linear_regression PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
mlp               PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
random_forest     PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786
xgboost           PARSEC         Base           T_eff             3.5328 - 3.786
                                 mass_smaller_3 T_eff             3.6191 - 3.786

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.5441135519545068
                                 mass_smaller_3 T_eff              0.9242961999199967
KNN               PARSEC         Base           T_eff              0.6904163446197727
                                 mass_smaller_3 T_eff              0.8967013519648316
linear_regression PARSEC         Base           T_eff               -7.16132505869397
                                 mass_smaller_3 T_eff             -1.5686771055412678
mlp               PARSEC         Base           T_eff               -4.48744266439307
                                 mass_smaller_3 T_eff              -4.154786944185996
random_forest     PARSEC         Base           T_eff                0.65911942798238
                                 mass_smaller_3 T_eff              0.9288857018029434
xgboost           PARSEC         Base           T_eff             -0.3014297238793202
                                 mass_smaller_3 T_eff              0.8292302542118786

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.020721238317739282
                                 mass_smaller_3 T_eff             0.007156302955568765
KNN               PARSEC         Base           T_eff             0.017075614604465876
                                 mass_smaller_3 T_eff              0.00833909804396656
linear_regression PARSEC         Base           T_eff              0.09087287967461888
                                 mass_smaller_3 T_eff             0.042993461978324536
mlp               PARSEC         Base           T_eff              0.07804506883423629
                                 mass_smaller_3 T_eff              0.05849140444577535
random_forest     PARSEC         Base           T_eff             0.017918341936679124
                                 mass_smaller_3 T_eff             0.006938251111008831
xgboost           PARSEC         Base           T_eff             0.036494009132568096
                                 mass_smaller_3 T_eff             0.010883776366202249

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0038289243446757216
                                 mass_smaller_3 T_eff             0.0030461141057490874
KNN               PARSEC         Base           T_eff             0.0041563830424764725
                                 mass_smaller_3 T_eff              0.003256445823865216
linear_regression PARSEC         Base           T_eff                0.0606939285303933
                                 mass_smaller_3 T_eff              0.034454346136405446
mlp               PARSEC         Base           T_eff              0.059086141528507476
                                 mass_smaller_3 T_eff               0.04363169024712285
random_forest     PARSEC         Base           T_eff             0.0038969391184098512
                                 mass_smaller_3 T_eff             0.0030534498752840147
xgboost           PARSEC         Base           T_eff              0.013120298537824896
                                 mass_smaller_3 T_eff              0.005731549104600593

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.0007587628865994844
                                 mass_smaller_3 T_eff              0.0008441558441583119
KNN               PARSEC         Base           T_eff             0.00040000000000040004
                                 mass_smaller_3 T_eff              0.0004199999999996429
linear_regression PARSEC         Base           T_eff                0.04359967210407634
                                 mass_smaller_3 T_eff                0.03048185133489234
mlp               PARSEC         Base           T_eff               0.049751120543306104
                                 mass_smaller_3 T_eff                0.03042273481751101
random_forest     PARSEC         Base           T_eff               0.000785999999997955
                                 mass_smaller_3 T_eff              0.0008633150266730283
xgboost           PARSEC         Base           T_eff               0.003836515426635767
                                 mass_smaller_3 T_eff               0.003026749801635642

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.7961889196467123
                                 mass_smaller_3 T_eff               0.9626419908201415
KNN               PARSEC         Base           T_eff               0.8501678081907662
                                 mass_smaller_3 T_eff               0.9500095724320192
linear_regression PARSEC         Base           T_eff             -0.21481121752618543
                                 mass_smaller_3 T_eff              0.31895709607702794
mlp               PARSEC         Base           T_eff             0.023312409206957985
                                 mass_smaller_3 T_eff              0.42274488488999873
random_forest     PARSEC         Base           T_eff                0.836128348980831
                                 mass_smaller_3 T_eff                0.964809662060515
xgboost           PARSEC         Base           T_eff                0.377210711992698
                                 mass_smaller_3 T_eff                0.910803401441279

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                          0.8407
                                 mass_smaller_3 T_eff             0.24480000000000013
KNN               PARSEC         Base           T_eff              0.8291399999999998
                                 mass_smaller_3 T_eff              0.1180800000000004
linear_regression PARSEC         Base           T_eff              0.3739373413922791
                                 mass_smaller_3 T_eff             0.18821207195901835
mlp               PARSEC         Base           T_eff              0.6171417815751772
                                 mass_smaller_3 T_eff             0.29646057849323393
random_forest     PARSEC         Base           T_eff              0.8289985333333334
                                 mass_smaller_3 T_eff             0.14136300000000412
xgboost           PARSEC         Base           T_eff             0.40178928604125996
                                 mass_smaller_3 T_eff             0.15799813423156728

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              75 : 0.00315 / 90 : 0.00746 / 95 : 0.01306 / 99 : 0.03671
                                 mass_smaller_3 T_eff               75 : 0.00318 / 90 : 0.00748 / 95 : 0.01282 / 99 : 0.0312
KNN               PARSEC         Base           T_eff               75 : 0.00184 / 90 : 0.0122 / 95 : 0.02378 / 99 : 0.04028
                                 mass_smaller_3 T_eff               75 : 0.00178 / 90 : 0.00984 / 95 : 0.0233 / 99 : 0.03445
linear_regression PARSEC         Base           T_eff                75 : 0.06806 / 90 : 0.11643 / 95 : 0.26577 / 99 : 0.323
                                 mass_smaller_3 T_eff                75 : 0.04819 / 90 : 0.0655 / 95 : 0.07947 / 99 : 0.1237
mlp               PARSEC         Base           T_eff              75 : 0.07231 / 90 : 0.10066 / 95 : 0.15498 / 99 : 0.27496
                                 mass_smaller_3 T_eff              75 : 0.06152 / 90 : 0.09961 / 95 : 0.11919 / 99 : 0.17187
random_forest     PARSEC         Base           T_eff               75 : 0.0032 / 90 : 0.00785 / 95 : 0.01396 / 99 : 0.04082
                                 mass_smaller_3 T_eff                75 : 0.00319 / 90 : 0.00759 / 95 : 0.013 / 99 : 0.03133
xgboost           PARSEC         Base           T_eff              75 : 0.00977 / 90 : 0.01972 / 95 : 0.05406 / 99 : 0.19767
                                 mass_smaller_3 T_eff              75 : 0.00716 / 90 : 0.01249 / 95 : 0.01729 / 99 : 0.04419

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 5.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
KNN               PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
linear_regression PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
mlp               PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
random_forest     PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635
xgboost           PARSEC         Base           T_eff              3.5642 - 4.272
                                 mass_smaller_3 T_eff             3.6805 - 3.8635

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.875456632791973
                                 mass_smaller_3 T_eff                0.867553551301494
KNN               PARSEC         Base           T_eff               0.8952904959736894
                                 mass_smaller_3 T_eff                 0.96336943698678
linear_regression PARSEC         Base           T_eff              0.13546196696769075
                                 mass_smaller_3 T_eff                0.668506592185953
mlp               PARSEC         Base           T_eff             -0.29273083625011354
                                 mass_smaller_3 T_eff              -0.4869112855205724
random_forest     PARSEC         Base           T_eff               0.9079086436663277
                                 mass_smaller_3 T_eff               0.9604125945272385
xgboost           PARSEC         Base           T_eff               0.4646243180794113
                                 mass_smaller_3 T_eff               0.7170427591317867

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                0.0404003814429823
                                 mass_smaller_3 T_eff              0.013122882060035538
KNN               PARSEC         Base           T_eff               0.03711047830863781
                                 mass_smaller_3 T_eff              0.006928575573769303
linear_regression PARSEC         Base           T_eff               0.16148586925420585
                                 mass_smaller_3 T_eff               0.07478912830666538
mlp               PARSEC         Base           T_eff               0.13709882557268205
                                 mass_smaller_3 T_eff               0.05985136333829618
random_forest     PARSEC         Base           T_eff               0.03473902067670326
                                 mass_smaller_3 T_eff             0.0071748688474133895
xgboost           PARSEC         Base           T_eff               0.08582596740917203
                                 mass_smaller_3 T_eff              0.019185446266324447

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.009523709897636998
                                 mass_smaller_3 T_eff             0.0015745356602996682
KNN               PARSEC         Base           T_eff              0.014543067715688269
                                 mass_smaller_3 T_eff             0.0019761283234454446
linear_regression PARSEC         Base           T_eff               0.13719830717896403
                                 mass_smaller_3 T_eff               0.07201459153124953
mlp               PARSEC         Base           T_eff               0.10635807796242833
                                 mass_smaller_3 T_eff               0.04651173163409056
random_forest     PARSEC         Base           T_eff              0.009528858618003498
                                 mass_smaller_3 T_eff             0.0021912574230866077
xgboost           PARSEC         Base           T_eff               0.05902249643570652
                                 mass_smaller_3 T_eff              0.013598684864299836

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              4.440892098500626e-16
                                 mass_smaller_3 T_eff                                0.0
KNN               PARSEC         Base           T_eff               0.001100000000000101
                                 mass_smaller_3 T_eff              4.000000000026205e-05
linear_regression PARSEC         Base           T_eff                0.11317556965713527
                                 mass_smaller_3 T_eff                0.07328150743468687
mlp               PARSEC         Base           T_eff                  0.081959774798813
                                 mass_smaller_3 T_eff                 0.0352046988004604
random_forest     PARSEC         Base           T_eff             0.00043700000000024275
                                 mass_smaller_3 T_eff              0.0001320000000011312
xgboost           PARSEC         Base           T_eff               0.034365868377685516
                                 mass_smaller_3 T_eff               0.009320376968383837

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9382230012465637
                                 mass_smaller_3 T_eff              0.9400210765627829
KNN               PARSEC         Base           T_eff              0.9462976094851531
                                 mass_smaller_3 T_eff              0.9815747427610161
linear_regression PARSEC         Base           T_eff             0.40357511224693443
                                 mass_smaller_3 T_eff              0.8200960609467987
mlp               PARSEC         Base           T_eff              0.3425653519856123
                                 mass_smaller_3 T_eff              0.7456514404575488
random_forest     PARSEC         Base           T_eff              0.9534772118510992
                                 mass_smaller_3 T_eff              0.9805720984574089
xgboost           PARSEC         Base           T_eff                0.68203526589872
                                 mass_smaller_3 T_eff              0.8558303476868421

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.7346999999999997
                                 mass_smaller_3 T_eff             0.31820000000000004
KNN               PARSEC         Base           T_eff              0.5404999999999998
                                 mass_smaller_3 T_eff              0.1918599999999997
linear_regression PARSEC         Base           T_eff             0.34566965758396906
                                 mass_smaller_3 T_eff             0.14286852672435746
mlp               PARSEC         Base           T_eff              0.5471516729521126
                                 mass_smaller_3 T_eff             0.23403602479640107
random_forest     PARSEC         Base           T_eff               0.502608099999998
                                 mass_smaller_3 T_eff             0.09220366666666369
xgboost           PARSEC         Base           T_eff               0.553806636047363
                                 mass_smaller_3 T_eff             0.13106379623413078

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                 75 : 0.0018 / 90 : 0.0157 / 95 : 0.0406 / 99 : 0.21369
                                 mass_smaller_3 T_eff                   75 : 5e-05 / 90 : 0.0001 / 95 : 0.0021 / 99 : 0.0425
KNN               PARSEC         Base           T_eff               75 : 0.0147 / 90 : 0.03722 / 95 : 0.06555 / 99 : 0.18111
                                 mass_smaller_3 T_eff               75 : 0.00028 / 90 : 0.0059 / 95 : 0.01231 / 99 : 0.02871
linear_regression PARSEC         Base           T_eff               75 : 0.1915 / 90 : 0.28075 / 95 : 0.30894 / 99 : 0.33665
                                 mass_smaller_3 T_eff              75 : 0.08641 / 90 : 0.09691 / 95 : 0.10075 / 99 : 0.10615
mlp               PARSEC         Base           T_eff                75 : 0.13316 / 90 : 0.2293 / 95 : 0.2998 / 99 : 0.40241
                                 mass_smaller_3 T_eff                75 : 0.06233 / 90 : 0.0923 / 95 : 0.1206 / 99 : 0.19051
random_forest     PARSEC         Base           T_eff               75 : 0.00393 / 90 : 0.01997 / 95 : 0.0431 / 99 : 0.18688
                                 mass_smaller_3 T_eff              75 : 0.00104 / 90 : 0.00509 / 95 : 0.01198 / 99 : 0.03638
xgboost           PARSEC         Base           T_eff              75 : 0.08836 / 90 : 0.14542 / 95 : 0.18122 / 99 : 0.26898
                                 mass_smaller_3 T_eff              75 : 0.01782 / 90 : 0.03164 / 95 : 0.04145 / 99 : 0.06319

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Results for the label category with a value of 6.0

                                                                      value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
KNN               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
linear_regression PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
mlp               PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
random_forest     PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551
xgboost           PARSEC         Base           T_eff             3.5416 - 4.2601
                                 mass_smaller_3 T_eff             3.6516 - 3.8551

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff               0.9361134687179025
                                 mass_smaller_3 T_eff               0.9344208412339422
KNN               PARSEC         Base           T_eff               0.9418003454905226
                                 mass_smaller_3 T_eff               0.8942508407557085
linear_regression PARSEC         Base           T_eff              0.20764377732401518
                                 mass_smaller_3 T_eff               0.5166524600554323
mlp               PARSEC         Base           T_eff             0.032533794358943324
                                 mass_smaller_3 T_eff              -0.8772552924720776
random_forest     PARSEC         Base           T_eff               0.9516275813074686
                                 mass_smaller_3 T_eff               0.9733172442765325
xgboost           PARSEC         Base           T_eff               0.6654556763318269
                                 mass_smaller_3 T_eff               0.6136185070108772

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.038817942968688686
                                 mass_smaller_3 T_eff             0.009947309738953879
KNN               PARSEC         Base           T_eff              0.03707878942589577
                                 mass_smaller_3 T_eff              0.01295611547006416
linear_regression PARSEC         Base           T_eff               0.1678192510763587
                                 mass_smaller_3 T_eff              0.08979673999415073
mlp               PARSEC         Base           T_eff              0.15194250392767136
                                 mass_smaller_3 T_eff              0.08952545832863493
random_forest     PARSEC         Base           T_eff              0.03378586126202459
                                 mass_smaller_3 T_eff             0.006343508147581037
xgboost           PARSEC         Base           T_eff              0.08905194351552072
                                 mass_smaller_3 T_eff             0.024294606184243273

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.010905352896371222
                                 mass_smaller_3 T_eff              0.003275683015649687
KNN               PARSEC         Base           T_eff                0.0200289228367529
                                 mass_smaller_3 T_eff              0.009480039447731752
linear_regression PARSEC         Base           T_eff                 0.142558114990346
                                 mass_smaller_3 T_eff               0.08574514045736377
mlp               PARSEC         Base           T_eff               0.12078806581546199
                                 mass_smaller_3 T_eff               0.07399730524660289
random_forest     PARSEC         Base           T_eff              0.010589656124915763
                                 mass_smaller_3 T_eff             0.0030457676521849462
xgboost           PARSEC         Base           T_eff               0.06752463157396035
                                 mass_smaller_3 T_eff               0.01811025127634103

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff             0.0035000000000007248
                                 mass_smaller_3 T_eff              0.001966666666666672
KNN               PARSEC         Base           T_eff              0.011480000000000157
                                 mass_smaller_3 T_eff              0.007039999999999491
linear_regression PARSEC         Base           T_eff               0.12713358897186677
                                 mass_smaller_3 T_eff               0.08592582620527445
mlp               PARSEC         Base           T_eff               0.09813067909362583
                                 mass_smaller_3 T_eff               0.06298795236640853
random_forest     PARSEC         Base           T_eff             0.0031219369047614798
                                 mass_smaller_3 T_eff             0.0017529666666700194
xgboost           PARSEC         Base           T_eff              0.051502188873290944
                                 mass_smaller_3 T_eff              0.013554772949218918

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.9682850567668624
                                 mass_smaller_3 T_eff              0.9679753590180824
KNN               PARSEC         Base           T_eff              0.9705614825838571
                                 mass_smaller_3 T_eff              0.9491856526161931
linear_regression PARSEC         Base           T_eff               0.478529160628656
                                 mass_smaller_3 T_eff              0.7242784910979044
mlp               PARSEC         Base           T_eff             0.41841265241488523
                                 mass_smaller_3 T_eff              0.6747902488625411
random_forest     PARSEC         Base           T_eff              0.9756452395472536
                                 mass_smaller_3 T_eff              0.9866197822722799
xgboost           PARSEC         Base           T_eff              0.8235404788604241
                                 mass_smaller_3 T_eff              0.7835296275337241

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              0.7282999999999995
                                 mass_smaller_3 T_eff                          0.2946
KNN               PARSEC         Base           T_eff              0.5081600000000002
                                 mass_smaller_3 T_eff             0.06072000000000077
linear_regression PARSEC         Base           T_eff              0.3671658110993148
                                 mass_smaller_3 T_eff             0.16529944266660213
mlp               PARSEC         Base           T_eff              0.5083662169085255
                                 mass_smaller_3 T_eff             0.24357605913495872
random_forest     PARSEC         Base           T_eff              0.5491737666666734
                                 mass_smaller_3 T_eff              0.1298869595238119
xgboost           PARSEC         Base           T_eff              0.3164865329742428
                                 mass_smaller_3 T_eff             0.08730419883728047

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff                75 : 0.0094 / 90 : 0.0183 / 95 : 0.03135 / 99 : 0.18838
                                 mass_smaller_3 T_eff              75 : 0.00418 / 90 : 0.00735 / 95 : 0.00924 / 99 : 0.01914
KNN               PARSEC         Base           T_eff              75 : 0.02298 / 90 : 0.04069 / 95 : 0.06435 / 99 : 0.15869
                                 mass_smaller_3 T_eff              75 : 0.01298 / 90 : 0.02106 / 95 : 0.02676 / 99 : 0.04192
linear_regression PARSEC         Base           T_eff              75 : 0.20855 / 90 : 0.27287 / 95 : 0.30722 / 99 : 0.34225
                                 mass_smaller_3 T_eff              75 : 0.10347 / 90 : 0.12041 / 95 : 0.12707 / 99 : 0.14415
mlp               PARSEC         Base           T_eff               75 : 0.1697 / 90 : 0.25914 / 95 : 0.30838 / 99 : 0.39154
                                 mass_smaller_3 T_eff               75 : 0.10374 / 90 : 0.15093 / 95 : 0.17498 / 99 : 0.2011
random_forest     PARSEC         Base           T_eff              75 : 0.00857 / 90 : 0.01973 / 95 : 0.03712 / 99 : 0.17576
                                 mass_smaller_3 T_eff                75 : 0.004 / 90 : 0.00689 / 95 : 0.00923 / 99 : 0.01743
xgboost           PARSEC         Base           T_eff               75 : 0.0978 / 90 : 0.14934 / 95 : 0.18727 / 99 : 0.24988
                                 mass_smaller_3 T_eff              75 : 0.02496 / 90 : 0.03946 / 95 : 0.05351 / 99 : 0.07458

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           T_eff              6.434222936630249
                                 mass_smaller_3 T_eff             4.5170204639434814
KNN               PARSEC         Base           T_eff              2.859384298324585
                                 mass_smaller_3 T_eff              2.906430959701538
linear_regression PARSEC         Base           T_eff             0.3583259582519531
                                 mass_smaller_3 T_eff             0.2743659019470215
mlp               PARSEC         Base           T_eff             116.13347673416138
                                 mass_smaller_3 T_eff              87.95152354240417
random_forest     PARSEC         Base           T_eff              70.70545029640198
                                 mass_smaller_3 T_eff             43.329623222351074
xgboost           PARSEC         Base           T_eff              6.729006052017212
                                 mass_smaller_3 T_eff              5.382724046707153

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER

KNN : 
- mass_smaller_3 : better/similar results to Base

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER

XGBoost : 
- mass_smaller_3 : better results than Base on every metric

MLP : 
- mass_smaller_3 : similar results than Base on every metric except MAX_ER

#### Conclusions on T_eff

Filtering with mass_smaller_3 mostly gives better results on every metric.

#### Best models for the T_eff parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and XGBoost.

### Radius parameter

In [17]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
KNN               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
mlp               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8188802537475399
                                 mass_smaller_3 radius            0.6656875093221303
KNN               PARSEC         Base           radius            0.8504530694492762
                                 mass_smaller_3 radius            0.7461594476972371
linear_regression PARSEC         Base           radius             0.306153058491456
                                 mass_smaller_3 radius            0.3314355213392083
mlp               PARSEC         Base           radius            0.6228554128105982
                                 mass_smaller_3 radius            0.5423045430426903
random_forest     PARSEC         Base           radius            0.8584173604243724
                                 mass_smaller_3 radius            0.7407905526574192
xgboost           PARSEC         Base           radius            0.7945230921341289
                                 mass_smaller_3 radius            0.7497460834843865

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.25948245112260193
                                 mass_smaller_3 radius            0.28712955880678553
KNN               PARSEC         Base           radius             0.2358770846024068
                                 mass_smaller_3 radius            0.25019731745221385
linear_regression PARSEC         Base           radius              0.507872479197307
                                 mass_smaller_3 radius             0.4060441237499527
mlp               PARSEC         Base           radius            0.37498636922431416
                                 mass_smaller_3 radius             0.3359946545077814
random_forest     PARSEC         Base           radius            0.22941978755764808
                                 mass_smaller_3 radius            0.25282928243556957
xgboost           PARSEC         Base           radius            0.27637866309651515
                                 mass_smaller_3 radius            0.24842314472263485

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.07527911151810734
                                 mass_smaller_3 radius            0.08632530853853265
KNN               PARSEC         Base           radius             0.0846864913145467
                                 mass_smaller_3 radius            0.08949852307856042
linear_regression PARSEC         Base           radius            0.39753794061010017
                                 mass_smaller_3 radius            0.31348689994675705
mlp               PARSEC         Base           radius            0.25364283689755424
                                 mass_smaller_3 radius             0.2207560899464196
random_forest     PARSEC         Base           radius            0.07306790793549578
                                 mass_smaller_3 radius             0.0833807631223743
xgboost           PARSEC         Base           radius              0.156982113190067
                                 mass_smaller_3 radius            0.12143441529830028

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0056727093489148395
                                 mass_smaller_3 radius             0.005455509201885644
KNN               PARSEC         Base           radius             0.007272808772476278
                                 mass_smaller_3 radius             0.005215953656321076
linear_regression PARSEC         Base           radius               0.2745446720480792
                                 mass_smaller_3 radius              0.23043334862203918
mlp               PARSEC         Base           radius              0.13319718920440615
                                 mass_smaller_3 radius              0.11385103382431644
random_forest     PARSEC         Base           radius             0.006440088206492278
                                 mass_smaller_3 radius             0.006542786149945967
xgboost           PARSEC         Base           radius              0.05423633153337293
                                 mass_smaller_3 radius             0.035588404313140976

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9078549079572853
                                 mass_smaller_3 radius            0.8272413120780314
KNN               PARSEC         Base           radius            0.9227969605947961
                                 mass_smaller_3 radius            0.8649063238059407
linear_regression PARSEC         Base           radius            0.5533109976788975
                                 mass_smaller_3 radius            0.5757043716529034
mlp               PARSEC         Base           radius            0.7892150515996972
                                 mass_smaller_3 radius            0.7365739150319188
random_forest     PARSEC         Base           radius            0.9271725495364581
                                 mass_smaller_3 radius             0.863219732122844
xgboost           PARSEC         Base           radius            0.8915692177111999
                                 mass_smaller_3 radius            0.8661602334586869

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.390815363619212
                                 mass_smaller_3 radius            2.3751855303079865
KNN               PARSEC         Base           radius            2.3172378341427184
                                 mass_smaller_3 radius            2.3170361323390436
linear_regression PARSEC         Base           radius             1.781259161764016
                                 mass_smaller_3 radius            1.4619464165080611
mlp               PARSEC         Base           radius            1.9906768274128068
                                 mass_smaller_3 radius            1.6083701045455463
random_forest     PARSEC         Base           radius             2.310296151725146
                                 mass_smaller_3 radius            2.3030305939409654
xgboost           PARSEC         Base           radius             2.261232186873491
                                 mass_smaller_3 radius             2.308647204488007

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.02877 / 90 : 0.11129 / 95 : 0.4465 / 99 : 1.45363
                                 mass_smaller_3 radius               75 : 0.02711 / 90 : 0.1447 / 95 : 0.6043 / 99 : 1.54958
KNN               PARSEC         Base           radius             75 : 0.04507 / 90 : 0.22252 / 95 : 0.51756 / 99 : 1.12183
                                 mass_smaller_3 radius              75 : 0.03339 / 90 : 0.28478 / 95 : 0.57739 / 99 : 1.1621
linear_regression PARSEC         Base           radius             75 : 0.58813 / 90 : 0.83923 / 95 : 1.02037 / 99 : 1.42151
                                 mass_smaller_3 radius              75 : 0.39108 / 90 : 0.72563 / 95 : 0.89423 / 99 : 1.1325
mlp               PARSEC         Base           radius             75 : 0.37949 / 90 : 0.71574 / 95 : 0.85022 / 99 : 1.08968
                                 mass_smaller_3 radius              75 : 0.28673 / 90 : 0.64143 / 95 : 0.81239 / 99 : 1.0253
random_forest     PARSEC         Base           radius             75 : 0.03242 / 90 : 0.14057 / 95 : 0.45529 / 99 : 1.18749
                                 mass_smaller_3 radius              75 : 0.03167 / 90 : 0.19214 / 95 : 0.57193 / 99 : 1.2424
xgboost           PARSEC         Base           radius             75 : 0.19952 / 90 : 0.47689 / 95 : 0.64069 / 99 : 1.00851
                                 mass_smaller_3 radius              75 : 0.1121 / 90 : 0.38269 / 95 : 0.59104 / 99 : 1.02277

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
KNN               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
mlp               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.7363724523806283
                                 mass_smaller_3 radius              0.5692154631580525
KNN               PARSEC         Base           radius              0.6600434525070423
                                 mass_smaller_3 radius              0.6478433146027724
linear_regression PARSEC         Base           radius              0.2911261433374668
                                 mass_smaller_3 radius            -0.38728983206769274
mlp               PARSEC         Base           radius            -0.17637582185160272
                                 mass_smaller_3 radius            -0.34828652576951313
random_forest     PARSEC         Base           radius               0.821604552614865
                                 mass_smaller_3 radius              0.7078963482896191
xgboost           PARSEC         Base           radius              0.5662612193213132
                                 mass_smaller_3 radius              0.5422178342312092

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.19042170257723945
                                 mass_smaller_3 radius             0.2002492504816667
KNN               PARSEC         Base           radius            0.22254830368573666
                                 mass_smaller_3 radius            0.18466113789326627
linear_regression PARSEC         Base           radius             0.8081240809409921
                                 mass_smaller_3 radius             0.6238573686801736
mlp               PARSEC         Base           radius             0.5437082254759342
                                 mass_smaller_3 radius              0.472819399821771
random_forest     PARSEC         Base           radius            0.15816370646342748
                                 mass_smaller_3 radius             0.1667421390538769
xgboost           PARSEC         Base           radius             0.2767403003739343
                                 mass_smaller_3 radius            0.22937690365350963

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.03409305225688784
                                 mass_smaller_3 radius             0.03698449906826638
KNN               PARSEC         Base           radius             0.06934657256026752
                                 mass_smaller_3 radius            0.054267388740391186
linear_regression PARSEC         Base           radius              0.7470748806993995
                                 mass_smaller_3 radius               0.560992030142771
mlp               PARSEC         Base           radius             0.40163841078936713
                                 mass_smaller_3 radius             0.33536675165391694
random_forest     PARSEC         Base           radius             0.03533338889206165
                                 mass_smaller_3 radius             0.03912195237829962
xgboost           PARSEC         Base           radius             0.16067151495024773
                                 mass_smaller_3 radius             0.12925411294122657

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.00039910653829717396
                                 mass_smaller_3 radius             0.0004485157721801081
KNN               PARSEC         Base           radius              0.004955741336719395
                                 mass_smaller_3 radius              0.004012748495691439
linear_regression PARSEC         Base           radius                 0.675373079244163
                                 mass_smaller_3 radius                 0.560119894578202
mlp               PARSEC         Base           radius               0.28679780926280607
                                 mass_smaller_3 radius               0.14235719581670492
random_forest     PARSEC         Base           radius             0.0005658977502006612
                                 mass_smaller_3 radius             0.0005257708673146594
xgboost           PARSEC         Base           radius               0.05116864033877122
                                 mass_smaller_3 radius               0.04343078970780857

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.891072495933085
                                 mass_smaller_3 radius             0.841483379572012
KNN               PARSEC         Base           radius            0.8859021657633167
                                 mass_smaller_3 radius            0.8655486583798956
linear_regression PARSEC         Base           radius            0.6331630624513377
                                 mass_smaller_3 radius            0.6192330441146768
mlp               PARSEC         Base           radius            0.7838452832290015
                                 mass_smaller_3 radius            0.7675803839055694
random_forest     PARSEC         Base           radius            0.9227998598367169
                                 mass_smaller_3 radius            0.8848730507935565
xgboost           PARSEC         Base           radius            0.8825965510893421
                                 mass_smaller_3 radius            0.8679802205239031

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.390815363619212
                                 mass_smaller_3 radius            2.3751855303079865
KNN               PARSEC         Base           radius            2.2561552794953266
                                 mass_smaller_3 radius             2.170880800930863
linear_regression PARSEC         Base           radius             1.781259161764016
                                 mass_smaller_3 radius            1.4371270520309136
mlp               PARSEC         Base           radius            1.3830092228942736
                                 mass_smaller_3 radius             1.013206438629486
random_forest     PARSEC         Base           radius            2.1128109169722986
                                 mass_smaller_3 radius             2.030694118628242
xgboost           PARSEC         Base           radius            1.7067418181404244
                                 mass_smaller_3 radius            1.6626087636745353

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00335 / 90 : 0.01452 / 95 : 0.03433 / 99 : 0.98432
                                 mass_smaller_3 radius              75 : 0.00233 / 90 : 0.01144 / 95 : 0.03412 / 99 : 0.9722
KNN               PARSEC         Base           radius             75 : 0.01813 / 90 : 0.11851 / 95 : 0.42461 / 99 : 1.12036
                                 mass_smaller_3 radius               75 : 0.01391 / 90 : 0.05477 / 95 : 0.397 / 99 : 0.94818
linear_regression PARSEC         Base           radius              75 : 0.91055 / 90 : 1.1884 / 95 : 1.39367 / 99 : 1.62448
                                 mass_smaller_3 radius             75 : 0.77688 / 90 : 0.92169 / 95 : 0.98044 / 99 : 1.09332
mlp               PARSEC         Base           radius              75 : 0.76117 / 90 : 0.89535 / 95 : 0.96146 / 99 : 1.1454
                                 mass_smaller_3 radius             75 : 0.67046 / 90 : 0.83521 / 95 : 0.88264 / 99 : 0.95108
random_forest     PARSEC         Base           radius               75 : 0.00398 / 90 : 0.025 / 95 : 0.16164 / 99 : 0.88488
                                 mass_smaller_3 radius              75 : 0.00322 / 90 : 0.0328 / 95 : 0.21253 / 99 : 0.89905
xgboost           PARSEC         Base           radius             75 : 0.21204 / 90 : 0.51508 / 95 : 0.66892 / 99 : 0.95761
                                 mass_smaller_3 radius             75 : 0.15684 / 90 : 0.39389 / 95 : 0.55229 / 99 : 0.83087

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 2.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
KNN               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
linear_regression PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
mlp               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
random_forest     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
xgboost           PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.5645314183359549
                                 mass_smaller_3 radius              -2.732952353195582
KNN               PARSEC         Base           radius              0.7554229207106287
                                 mass_smaller_3 radius             -0.9202566498577154
linear_regression PARSEC         Base           radius              0.5386038834226268
                                 mass_smaller_3 radius               0.408572591522509
mlp               PARSEC         Base           radius              0.6582559034694251
                                 mass_smaller_3 radius            0.005650543995053381
random_forest     PARSEC         Base           radius              0.7071019602387656
                                 mass_smaller_3 radius             -1.3305951778814302
xgboost           PARSEC         Base           radius              0.6440509775938494
                                 mass_smaller_3 radius            -0.25643982288806044

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.37808377490281414
                                 mass_smaller_3 radius             0.5231844849065922
KNN               PARSEC         Base           radius             0.2960988592039106
                                 mass_smaller_3 radius             0.4049513691727813
linear_regression PARSEC         Base           radius            0.40465135367108096
                                 mass_smaller_3 radius             0.4662014379721217
mlp               PARSEC         Base           radius            0.47730657095930035
                                 mass_smaller_3 radius            0.47330015800807174
random_forest     PARSEC         Base           radius             0.3161486321555061
                                 mass_smaller_3 radius            0.42992643766008815
xgboost           PARSEC         Base           radius            0.41744405306674026
                                 mass_smaller_3 radius            0.39855546992362545

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.15156764565330214
                                 mass_smaller_3 radius            0.23789707005160315
KNN               PARSEC         Base           radius            0.15368204149587342
                                 mass_smaller_3 radius            0.23628660939138874
linear_regression PARSEC         Base           radius            0.33080701925341655
                                 mass_smaller_3 radius            0.42671744861168726
mlp               PARSEC         Base           radius            0.40741811308800074
                                 mass_smaller_3 radius             0.4212535662836884
random_forest     PARSEC         Base           radius             0.1447388228438247
                                 mass_smaller_3 radius            0.22443456672494236
xgboost           PARSEC         Base           radius             0.3365678257047855
                                 mass_smaller_3 radius             0.3165983728312409

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.030172026537108265
                                 mass_smaller_3 radius             0.01610977354066312
KNN               PARSEC         Base           radius             0.04596530180713654
                                 mass_smaller_3 radius            0.037053589010871024
linear_regression PARSEC         Base           radius              0.2995236211924257
                                 mass_smaller_3 radius             0.41432745731367254
mlp               PARSEC         Base           radius              0.4132640244619854
                                 mass_smaller_3 radius              0.4519084128446092
random_forest     PARSEC         Base           radius             0.03406943232764609
                                 mass_smaller_3 radius             0.02599109454173537
xgboost           PARSEC         Base           radius              0.2929446210015452
                                 mass_smaller_3 radius              0.2661512237171837

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.7801787228457896
                                 mass_smaller_3 radius            0.09611120123386492
KNN               PARSEC         Base           radius              0.869666457596233
                                 mass_smaller_3 radius            0.14686392564473957
linear_regression PARSEC         Base           radius             0.7362360964966685
                                 mass_smaller_3 radius             0.6610338587317061
mlp               PARSEC         Base           radius             0.8193237357637003
                                 mass_smaller_3 radius            0.22248759544396704
random_forest     PARSEC         Base           radius             0.8450590476514552
                                 mass_smaller_3 radius            0.16662394884988382
xgboost           PARSEC         Base           radius             0.8027978602985453
                                 mass_smaller_3 radius            0.28534341589559026

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            2.0861071059413177
                                 mass_smaller_3 radius             2.108165755165133
KNN               PARSEC         Base           radius            1.9831724722172852
                                 mass_smaller_3 radius            1.9979948798223217
linear_regression PARSEC         Base           radius             1.543650323988387
                                 mass_smaller_3 radius            1.0813481030120495
mlp               PARSEC         Base           radius            1.2632732985815067
                                 mass_smaller_3 radius             0.949951254765336
random_forest     PARSEC         Base           radius            1.8410733083557265
                                 mass_smaller_3 radius            1.8728481720300576
xgboost           PARSEC         Base           radius            1.3726508129754227
                                 mass_smaller_3 radius            1.3281151282144188

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.07811 / 90 : 0.50835 / 95 : 0.91068 / 99 : 1.68888
                                 mass_smaller_3 radius             75 : 0.06712 / 90 : 0.85924 / 95 : 1.48307 / 99 : 1.80229
KNN               PARSEC         Base           radius              75 : 0.13204 / 90 : 0.54463 / 95 : 0.7077 / 99 : 1.13544
                                 mass_smaller_3 radius              75 : 0.4576 / 90 : 0.69305 / 95 : 0.90247 / 99 : 1.35522
linear_regression PARSEC         Base           radius               75 : 0.4692 / 90 : 0.6187 / 95 : 0.74639 / 99 : 1.09896
                                 mass_smaller_3 radius               75 : 0.547 / 90 : 0.68942 / 95 : 0.77209 / 99 : 0.88949
mlp               PARSEC         Base           radius             75 : 0.58918 / 90 : 0.71959 / 95 : 0.80987 / 99 : 1.03145
                                 mass_smaller_3 radius             75 : 0.59327 / 90 : 0.68334 / 95 : 0.73229 / 99 : 0.82022
random_forest     PARSEC         Base           radius             75 : 0.09724 / 90 : 0.51234 / 95 : 0.83666 / 99 : 1.32042
                                 mass_smaller_3 radius              75 : 0.3372 / 90 : 0.80704 / 95 : 1.10049 / 99 : 1.44024
xgboost           PARSEC         Base           radius              75 : 0.51575 / 90 : 0.67511 / 95 : 0.7715 / 99 : 1.00317
                                 mass_smaller_3 radius             75 : 0.51067 / 90 : 0.65038 / 95 : 0.72415 / 99 : 0.89627

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 3.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
KNN               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
linear_regression PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
mlp               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
random_forest     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
xgboost           PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.02946301764281367
                                 mass_smaller_3 radius             -0.9330922497996494
KNN               PARSEC         Base           radius              0.2126456955697713
                                 mass_smaller_3 radius            -0.46783962630115017
linear_regression PARSEC         Base           radius             0.40239652704002404
                                 mass_smaller_3 radius            -0.12787916890519835
mlp               PARSEC         Base           radius              0.4143768132236899
                                 mass_smaller_3 radius             -0.0893119161118534
random_forest     PARSEC         Base           radius             0.15865465480581487
                                 mass_smaller_3 radius             -0.5645747588756191
xgboost           PARSEC         Base           radius             0.32815972103674085
                                 mass_smaller_3 radius             -0.2251646750005729

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.4903637513845105
                                 mass_smaller_3 radius             0.5262572219362908
KNN               PARSEC         Base           radius            0.43601461223627697
                                 mass_smaller_3 radius             0.4662467664879875
linear_regression PARSEC         Base           radius              0.533016296734985
                                 mass_smaller_3 radius             0.4915146510520734
mlp               PARSEC         Base           radius            0.44264411891468897
                                 mass_smaller_3 radius            0.44790309998438826
random_forest     PARSEC         Base           radius             0.4460226626254374
                                 mass_smaller_3 radius             0.4762926991048335
xgboost           PARSEC         Base           radius            0.44149755833283194
                                 mass_smaller_3 radius             0.4415617858022193

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.23538369789146726
                                 mass_smaller_3 radius            0.26561495858669637
KNN               PARSEC         Base           radius            0.23114155137514683
                                 mass_smaller_3 radius            0.25892717130089077
linear_regression PARSEC         Base           radius            0.42708321112310144
                                 mass_smaller_3 radius            0.35930891035661744
mlp               PARSEC         Base           radius             0.3197213842867725
                                 mass_smaller_3 radius            0.31264852610130883
random_forest     PARSEC         Base           radius             0.2255880172344884
                                 mass_smaller_3 radius             0.2529020865834376
xgboost           PARSEC         Base           radius            0.29753876544535374
                                 mass_smaller_3 radius             0.2773689705140357

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.03323089669044604
                                 mass_smaller_3 radius            0.033151113745310434
KNN               PARSEC         Base           radius               0.054727338410409
                                 mass_smaller_3 radius             0.06230087645619675
linear_regression PARSEC         Base           radius              0.3445574532685126
                                 mass_smaller_3 radius             0.25434597222935507
mlp               PARSEC         Base           radius              0.1951720251814788
                                 mass_smaller_3 radius             0.17520707437201888
random_forest     PARSEC         Base           radius             0.03876380575304095
                                 mass_smaller_3 radius            0.039830499274152276
xgboost           PARSEC         Base           radius             0.18021677749609738
                                 mass_smaller_3 radius             0.13000350013459738

                                                                                   CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                 0.48432930509787
                                 mass_smaller_3 radius             -0.05138340572707176
KNN               PARSEC         Base           radius               0.5586784851770883
                                 mass_smaller_3 radius             -0.07089920877731852
linear_regression PARSEC         Base           radius               0.6386077306015067
                                 mass_smaller_3 radius            -0.030605746658701118
mlp               PARSEC         Base           radius                0.647683215963242
                                 mass_smaller_3 radius             -0.08400726754254777
random_forest     PARSEC         Base           radius               0.5459579150223091
                                 mass_smaller_3 radius            -0.010074158034539975
xgboost           PARSEC         Base           radius               0.5745391025849726
                                 mass_smaller_3 radius             -0.07409150503503559

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.385359462647806
                                 mass_smaller_3 radius            2.3555532954792158
KNN               PARSEC         Base           radius            2.3172378341427184
                                 mass_smaller_3 radius            2.3170361323390436
linear_regression PARSEC         Base           radius             1.423367576672751
                                 mass_smaller_3 radius            1.4619464165080611
mlp               PARSEC         Base           radius            1.9906768274128068
                                 mass_smaller_3 radius            1.6083701045455463
random_forest     PARSEC         Base           radius             2.310296151725146
                                 mass_smaller_3 radius            2.3030305939409654
xgboost           PARSEC         Base           radius             2.261232186873491
                                 mass_smaller_3 radius             2.308647204488007

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.21021 / 90 : 0.9022 / 95 : 1.26428 / 99 : 1.91484
                                 mass_smaller_3 radius             75 : 0.29907 / 90 : 0.98619 / 95 : 1.32354 / 99 : 1.93994
KNN               PARSEC         Base           radius              75 : 0.3004 / 90 : 0.76603 / 95 : 1.04217 / 99 : 1.84744
                                 mass_smaller_3 radius               75 : 0.37173 / 90 : 0.82247 / 95 : 1.0769 / 99 : 1.8932
linear_regression PARSEC         Base           radius             75 : 0.63518 / 90 : 0.90864 / 95 : 1.08583 / 99 : 1.23233
                                 mass_smaller_3 radius             75 : 0.46682 / 90 : 0.94571 / 95 : 1.11289 / 99 : 1.29303
mlp               PARSEC         Base           radius              75 : 0.44388 / 90 : 0.81582 / 95 : 1.00769 / 99 : 1.2349
                                 mass_smaller_3 radius             75 : 0.44437 / 90 : 0.85005 / 95 : 1.02951 / 99 : 1.25741
random_forest     PARSEC         Base           radius             75 : 0.24794 / 90 : 0.80748 / 95 : 1.11172 / 99 : 1.78362
                                 mass_smaller_3 radius              75 : 0.3279 / 90 : 0.87845 / 95 : 1.14836 / 99 : 1.84111
xgboost           PARSEC         Base           radius             75 : 0.43744 / 90 : 0.74514 / 95 : 0.97449 / 99 : 1.46297
                                 mass_smaller_3 radius              75 : 0.3877 / 90 : 0.79763 / 95 : 1.00973 / 99 : 1.56273

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 4.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
KNN               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
linear_regression PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
mlp               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
random_forest     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
xgboost           PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.955620286412061
                                 mass_smaller_3 radius             0.5472382672914728
KNN               PARSEC         Base           radius             0.9504855107562155
                                 mass_smaller_3 radius            0.32842372582011825
linear_regression PARSEC         Base           radius             0.7084371651989534
                                 mass_smaller_3 radius            -0.8336303698007064
mlp               PARSEC         Base           radius             0.8215956330914591
                                 mass_smaller_3 radius            -1.0286431546556236
random_forest     PARSEC         Base           radius             0.9621702735006398
                                 mass_smaller_3 radius             0.5693692452409231
xgboost           PARSEC         Base           radius             0.9067948297537736
                                 mass_smaller_3 radius             0.4280597852922512

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.06341420958190282
                                 mass_smaller_3 radius            0.049324340834726234
KNN               PARSEC         Base           radius              0.0669811006524331
                                 mass_smaller_3 radius             0.05994582584176247
linear_regression PARSEC         Base           radius             0.26144268756230293
                                 mass_smaller_3 radius             0.19840935212881075
mlp               PARSEC         Base           radius              0.1652573269566529
                                 mass_smaller_3 radius             0.14894403454528876
random_forest     PARSEC         Base           radius             0.05854848516325554
                                 mass_smaller_3 radius               0.048119276752695
xgboost           PARSEC         Base           radius             0.09965114225438286
                                 mass_smaller_3 radius             0.05763696437770313

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.02159202040873627
                                 mass_smaller_3 radius             0.02061003944030581
KNN               PARSEC         Base           radius             0.02401669344408429
                                 mass_smaller_3 radius             0.02233752092815773
linear_regression PARSEC         Base           radius             0.20969472784333076
                                 mass_smaller_3 radius             0.18207963853249468
mlp               PARSEC         Base           radius             0.11676079932176552
                                 mass_smaller_3 radius             0.11621983574137043
random_forest     PARSEC         Base           radius            0.021491570434441845
                                 mass_smaller_3 radius             0.02055111897999929
xgboost           PARSEC         Base           radius             0.05342207596724462
                                 mass_smaller_3 radius            0.034907698087998866

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.004419931983550951
                                 mass_smaller_3 radius             0.004948289058039235
KNN               PARSEC         Base           radius            0.0021175757987152988
                                 mass_smaller_3 radius            0.0022124717172875563
linear_regression PARSEC         Base           radius              0.18887631683240547
                                 mass_smaller_3 radius              0.19386677933122742
mlp               PARSEC         Base           radius              0.08020351535631742
                                 mass_smaller_3 radius              0.09469860849448009
random_forest     PARSEC         Base           radius             0.004534967156486047
                                 mass_smaller_3 radius            0.0050174952592660915
xgboost           PARSEC         Base           radius             0.023085902380919787
                                 mass_smaller_3 radius             0.018800382563634477

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9776881908040265
                                 mass_smaller_3 radius             0.8269489220885603
KNN               PARSEC         Base           radius             0.9751848834547058
                                 mass_smaller_3 radius              0.777409997990249
linear_regression PARSEC         Base           radius             0.8876723080274312
                                 mass_smaller_3 radius            0.27229610134162063
mlp               PARSEC         Base           radius             0.9198956642376998
                                 mass_smaller_3 radius             0.4714277176746543
random_forest     PARSEC         Base           radius             0.9809328484849373
                                 mass_smaller_3 radius             0.8329855500178989
xgboost           PARSEC         Base           radius             0.9577760766716373
                                 mass_smaller_3 radius             0.7180532680216085

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.7650343537442144
                                 mass_smaller_3 radius             1.1059119821850276
KNN               PARSEC         Base           radius             1.7506203509415466
                                 mass_smaller_3 radius               0.61135975949587
linear_regression PARSEC         Base           radius             0.9612784106621741
                                 mass_smaller_3 radius            0.48630957221819804
mlp               PARSEC         Base           radius             1.1734950373746966
                                 mass_smaller_3 radius             0.7356309221400916
random_forest     PARSEC         Base           radius              1.743523039119606
                                 mass_smaller_3 radius              1.017409421876096
xgboost           PARSEC         Base           radius             0.7897854198667069
                                 mass_smaller_3 radius             0.5816839944946661

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.02116 / 90 : 0.05107 / 95 : 0.08715 / 99 : 0.24579
                                 mass_smaller_3 radius             75 : 0.02162 / 90 : 0.05154 / 95 : 0.09057 / 99 : 0.21606
KNN               PARSEC         Base           radius             75 : 0.00859 / 90 : 0.08998 / 95 : 0.16848 / 99 : 0.25098
                                 mass_smaller_3 radius             75 : 0.00821 / 90 : 0.08176 / 95 : 0.16313 / 99 : 0.24025
linear_regression PARSEC         Base           radius             75 : 0.23824 / 90 : 0.28693 / 95 : 0.64321 / 99 : 0.78988
                                 mass_smaller_3 radius             75 : 0.24083 / 90 : 0.28046 / 95 : 0.29632 / 99 : 0.31766
mlp               PARSEC         Base           radius             75 : 0.15069 / 90 : 0.24565 / 95 : 0.36761 / 99 : 0.57346
                                 mass_smaller_3 radius             75 : 0.15611 / 90 : 0.24325 / 95 : 0.31164 / 99 : 0.41249
random_forest     PARSEC         Base           radius             75 : 0.02139 / 90 : 0.05187 / 95 : 0.08878 / 99 : 0.24624
                                 mass_smaller_3 radius             75 : 0.02171 / 90 : 0.05158 / 95 : 0.08985 / 99 : 0.21559
xgboost           PARSEC         Base           radius             75 : 0.05941 / 90 : 0.13327 / 95 : 0.19754 / 99 : 0.46263
                                 mass_smaller_3 radius             75 : 0.04624 / 90 : 0.08593 / 95 : 0.11762 / 99 : 0.22241

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 5.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
KNN               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
linear_regression PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
mlp               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
random_forest     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
xgboost           PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9761610949531048
                                 mass_smaller_3 radius             0.7814373029112099
KNN               PARSEC         Base           radius             0.9810026567945801
                                 mass_smaller_3 radius             0.9645065051911283
linear_regression PARSEC         Base           radius             0.6936214748871703
                                 mass_smaller_3 radius            -0.3964676844578261
mlp               PARSEC         Base           radius             0.7905570860440205
                                 mass_smaller_3 radius            -0.1946802397138625
random_forest     PARSEC         Base           radius             0.9833215630488885
                                 mass_smaller_3 radius             0.8929394429365533
xgboost           PARSEC         Base           radius             0.8909704249855909
                                 mass_smaller_3 radius             0.7443264863863341

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.07455089392624331
                                 mass_smaller_3 radius            0.038217587148684895
KNN               PARSEC         Base           radius             0.06677184999270079
                                 mass_smaller_3 radius            0.015509602024441337
linear_regression PARSEC         Base           radius             0.41248818706480006
                                 mass_smaller_3 radius             0.24546889584204587
mlp               PARSEC         Base           radius              0.2456399951429642
                                 mass_smaller_3 radius             0.09003793207860139
random_forest     PARSEC         Base           radius             0.06235858799879652
                                 mass_smaller_3 radius            0.026947837505247645
xgboost           PARSEC         Base           radius             0.16460758707216622
                                 mass_smaller_3 radius             0.04423196006989856

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.01708858666755633
                                 mass_smaller_3 radius            0.006064160573840622
KNN               PARSEC         Base           radius             0.02578917817801487
                                 mass_smaller_3 radius            0.004961669663094179
linear_regression PARSEC         Base           radius              0.3613406262384508
                                 mass_smaller_3 radius             0.22654569251941534
mlp               PARSEC         Base           radius             0.18339354368706592
                                 mass_smaller_3 radius             0.07267934776132995
random_forest     PARSEC         Base           radius             0.01750445369583531
                                 mass_smaller_3 radius            0.007932542080921262
xgboost           PARSEC         Base           radius             0.11280228324849544
                                 mass_smaller_3 radius            0.030504279594149763

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0005723644632364966
                                 mass_smaller_3 radius            0.00047703704478119224
KNN               PARSEC         Base           radius                0.0019053567981413
                                 mass_smaller_3 radius             0.0006023351400117338
linear_regression PARSEC         Base           radius                0.3421354125013407
                                 mass_smaller_3 radius               0.23410488962537546
mlp               PARSEC         Base           radius               0.13197290158446684
                                 mass_smaller_3 radius               0.06432920711121848
random_forest     PARSEC         Base           radius              0.000767228879044568
                                 mass_smaller_3 radius             0.0005515727925315961
xgboost           PARSEC         Base           radius               0.06626665562742962
                                 mass_smaller_3 radius              0.020410160829255508

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9881339932310456
                                 mass_smaller_3 radius             0.9026259569825558
KNN               PARSEC         Base           radius             0.9905459125164942
                                 mass_smaller_3 radius             0.9823878588468848
linear_regression PARSEC         Base           radius             0.8405054746921199
                                 mass_smaller_3 radius             0.8014000931277628
mlp               PARSEC         Base           radius             0.9044015052723806
                                 mass_smaller_3 radius            0.35215172443664977
random_forest     PARSEC         Base           radius             0.9916566947756928
                                 mass_smaller_3 radius             0.9490747005848708
xgboost           PARSEC         Base           radius             0.9457856207944926
                                 mass_smaller_3 radius             0.8758676293580796

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.5057783282948216
                                 mass_smaller_3 radius             0.7113066837691322
KNN               PARSEC         Base           radius              1.024449153836383
                                 mass_smaller_3 radius            0.38799515721747835
linear_regression PARSEC         Base           radius              1.087497647916335
                                 mass_smaller_3 radius            0.46360599668719993
mlp               PARSEC         Base           radius             1.0720720071726242
                                 mass_smaller_3 radius             0.3638719861686015
random_forest     PARSEC         Base           radius             1.0173073204712826
                                 mass_smaller_3 radius            0.34711194509974175
xgboost           PARSEC         Base           radius             0.9919143971648867
                                 mass_smaller_3 radius            0.34005165922888625

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00213 / 90 : 0.02711 / 95 : 0.07076 / 99 : 0.37473
                                 mass_smaller_3 radius             75 : 0.00093 / 90 : 0.00181 / 95 : 0.00807 / 99 : 0.20827
KNN               PARSEC         Base           radius             75 : 0.02562 / 90 : 0.06674 / 95 : 0.11563 / 99 : 0.32208
                                 mass_smaller_3 radius             75 : 0.00187 / 90 : 0.01411 / 95 : 0.02851 / 99 : 0.06447
linear_regression PARSEC         Base           radius                75 : 0.52905 / 90 : 0.63795 / 95 : 0.68 / 99 : 0.75724
                                 mass_smaller_3 radius             75 : 0.29668 / 90 : 0.34515 / 95 : 0.36162 / 99 : 0.38675
mlp               PARSEC         Base           radius              75 : 0.26965 / 90 : 0.42654 / 95 : 0.50947 / 99 : 0.6911
                                 mass_smaller_3 radius              75 : 0.09908 / 90 : 0.1441 / 95 : 0.17159 / 99 : 0.24825
random_forest     PARSEC         Base           radius             75 : 0.00724 / 90 : 0.03961 / 95 : 0.08843 / 99 : 0.31108
                                 mass_smaller_3 radius             75 : 0.00272 / 90 : 0.01729 / 95 : 0.04211 / 99 : 0.13869
xgboost           PARSEC         Base           radius             75 : 0.17244 / 90 : 0.27989 / 95 : 0.34668 / 99 : 0.52946
                                 mass_smaller_3 radius             75 : 0.04005 / 90 : 0.07041 / 95 : 0.09715 / 99 : 0.15125

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Results for the label category with a value of 6.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
KNN               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
linear_regression PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
mlp               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
random_forest     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
xgboost           PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.9590838171586634
                                 mass_smaller_3 radius              0.8901791420736058
KNN               PARSEC         Base           radius              0.9629697658705128
                                 mass_smaller_3 radius              0.8299459557606574
linear_regression PARSEC         Base           radius             -0.1780265156579326
                                 mass_smaller_3 radius            -0.35462831819438545
mlp               PARSEC         Base           radius              0.6180409605152396
                                 mass_smaller_3 radius             -0.2773693742034451
random_forest     PARSEC         Base           radius              0.9697670887087206
                                 mass_smaller_3 radius              0.9328840101426675
xgboost           PARSEC         Base           radius               0.769792515363512
                                 mass_smaller_3 radius             0.45194161207274786

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.07710366131236392
                                 mass_smaller_3 radius              0.0319962014335555
KNN               PARSEC         Base           radius             0.07336873948132151
                                 mass_smaller_3 radius            0.040932981154472386
linear_regression PARSEC         Base           radius              0.5223847164290274
                                 mass_smaller_3 radius             0.12931194582653843
mlp               PARSEC         Base           radius              0.2720273473516592
                                 mass_smaller_3 radius             0.18511855365247315
random_forest     PARSEC         Base           radius             0.06632705239911885
                                 mass_smaller_3 radius             0.02502506810081321
xgboost           PARSEC         Base           radius              0.1905818443404726
                                 mass_smaller_3 radius             0.07985654117355773

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.022776610588325197
                                 mass_smaller_3 radius            0.015753888496454357
KNN               PARSEC         Base           radius             0.04166830194669774
                                 mass_smaller_3 radius             0.03152288184815854
linear_regression PARSEC         Base           radius              0.4815810448410679
                                 mass_smaller_3 radius             0.10139189596401278
mlp               PARSEC         Base           radius             0.22403130056654885
                                 mass_smaller_3 radius             0.15857075425837003
random_forest     PARSEC         Base           radius             0.02199490853649632
                                 mass_smaller_3 radius            0.014616888347962017
xgboost           PARSEC         Base           radius              0.1498862826198757
                                 mass_smaller_3 radius             0.06113557032451997

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.00870387997298483
                                 mass_smaller_3 radius            0.009029316541800059
KNN               PARSEC         Base           radius             0.02615840264183933
                                 mass_smaller_3 radius            0.025353309054399142
linear_regression PARSEC         Base           radius              0.4761420456167055
                                 mass_smaller_3 radius             0.08209654511713893
mlp               PARSEC         Base           radius             0.19861505214230768
                                 mass_smaller_3 radius             0.15001463390151648
random_forest     PARSEC         Base           radius            0.007358222039419937
                                 mass_smaller_3 radius            0.007878084020764398
xgboost           PARSEC         Base           radius             0.12394579245609716
                                 mass_smaller_3 radius             0.04875754543333888

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.9796178563497766
                                 mass_smaller_3 radius             0.9462666999561264
KNN               PARSEC         Base           radius             0.9813761923561958
                                 mass_smaller_3 radius             0.9111394452784567
linear_regression PARSEC         Base           radius             0.5867748937794232
                                 mass_smaller_3 radius             0.7747078206853004
mlp               PARSEC         Base           radius             0.7909518021844507
                                 mass_smaller_3 radius            0.20303152951224382
random_forest     PARSEC         Base           radius             0.9848075867184325
                                 mass_smaller_3 radius             0.9662451252072484
xgboost           PARSEC         Base           radius             0.8782788575526104
                                 mass_smaller_3 radius              0.749992482346073

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             1.5334413077139653
                                 mass_smaller_3 radius             0.6934718758359137
KNN               PARSEC         Base           radius             1.0892491343411437
                                 mass_smaller_3 radius            0.18171588646056636
linear_regression PARSEC         Base           radius              1.075929559325979
                                 mass_smaller_3 radius             0.4477054589905358
mlp               PARSEC         Base           radius             0.9408848622829691
                                 mass_smaller_3 radius            0.44537434673666687
random_forest     PARSEC         Base           radius             1.1110629174530526
                                 mass_smaller_3 radius              0.288983406772515
xgboost           PARSEC         Base           radius             0.7657090029730922
                                 mass_smaller_3 radius            0.26873545478870087

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.0216 / 90 : 0.03985 / 95 : 0.06493 / 99 : 0.33128
                                 mass_smaller_3 radius             75 : 0.02187 / 90 : 0.03853 / 95 : 0.05444 / 99 : 0.10862
KNN               PARSEC         Base           radius             75 : 0.04965 / 90 : 0.08372 / 95 : 0.12244 / 99 : 0.30325
                                 mass_smaller_3 radius              75 : 0.04407 / 90 : 0.06735 / 95 : 0.0835 / 99 : 0.11486
linear_regression PARSEC         Base           radius              75 : 0.63804 / 90 : 0.74171 / 95 : 0.7997 / 99 : 0.91087
                                 mass_smaller_3 radius              75 : 0.14655 / 90 : 0.2121 / 95 : 0.26202 / 99 : 0.34608
mlp               PARSEC         Base           radius               75 : 0.32184 / 90 : 0.44405 / 95 : 0.51372 / 99 : 0.646
                                 mass_smaller_3 radius             75 : 0.22481 / 90 : 0.28686 / 95 : 0.33359 / 99 : 0.39206
random_forest     PARSEC         Base           radius             75 : 0.02049 / 90 : 0.04342 / 95 : 0.07356 / 99 : 0.29714
                                 mass_smaller_3 radius              75 : 0.0212 / 90 : 0.03843 / 95 : 0.05048 / 99 : 0.08935
xgboost           PARSEC         Base           radius             75 : 0.21694 / 90 : 0.31853 / 95 : 0.38254 / 99 : 0.50061
                                 mass_smaller_3 radius               75 : 0.0838 / 90 : 0.13464 / 95 : 0.16785 / 99 : 0.2255

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.434222936630249
                                 mass_smaller_3 radius            4.5170204639434814
KNN               PARSEC         Base           radius             2.859384298324585
                                 mass_smaller_3 radius             2.906430959701538
linear_regression PARSEC         Base           radius            0.3583259582519531
                                 mass_smaller_3 radius            0.2743659019470215
mlp               PARSEC         Base           radius            116.13347673416138
                                 mass_smaller_3 radius             87.95152354240417
random_forest     PARSEC         Base           radius             70.70545029640198
                                 mass_smaller_3 radius            43.329623222351074
xgboost           PARSEC         Base           radius             6.729006052017212
                                 mass_smaller_3 radius             5.382724046707153

Linear regression : 
- mass_smaller_3 : better/similar results to Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

Random forest : 
- mass_smaller_3 : worse results than Base on every metric

XGBoost : 
- mass_smaller_3 : better/similar results to Base on every metric

MLP : 
- mass_smaller_3 : worse/similar results to Base on every metric

#### Conclusions on radius

When filtering using mass_smaller_3, the results mostly worsen except for XGBoost and linear regression.

#### Best models for the radius parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### log_g parameter

In [19]:
compare_metrics(path, 
                output_parameters=["log_g"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
KNN               PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
linear_regression PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
mlp               PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
random_forest     PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345
xgboost           PARSEC         Base           log_g             -0.384 - 5.345
                                 mass_smaller_3 log_g             -0.384 - 5.345

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.7536570738013006
                                 mass_smaller_3 log_g              0.614496340978034
KNN               PARSEC         Base           log_g             0.7969225275315691
                                 mass_smaller_3 log_g             0.7074902482099952
linear_regression PARSEC         Base           log_g             0.1740171909362369
                                 mass_smaller_3 log_g             0.2780976672847234
mlp               PARSEC         Base           log_g             0.5075863573833721
                                 mass_smaller_3 log_g             0.4491367775194661
random_forest     PARSEC         Base           log_g             0.8074266704690882
                                 mass_smaller_3 log_g               0.70112405424908
xgboost           PARSEC         Base           log_g             0.7207144464742739
                                 mass_smaller_3 log_g             0.7103009735205652

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.5190543242870183
                                 mass_smaller_3 log_g              0.5741879827647468
KNN               PARSEC         Base           log_g             0.47145630056607196
                                 mass_smaller_3 log_g              0.5001617633029353
linear_regression PARSEC         Base           log_g               0.950442888851383
                                 mass_smaller_3 log_g              0.7857403351048409
mlp               PARSEC         Base           log_g              0.7345510679198198
                                 mass_smaller_3 log_g              0.6875342891265775
random_forest     PARSEC         Base           log_g              0.4589248718978013
                                 mass_smaller_3 log_g              0.5055751085850891
xgboost           PARSEC         Base           log_g              0.5526686841050604
                                 mass_smaller_3 log_g             0.49775238021746787

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.15060909496410327
                                 mass_smaller_3 log_g             0.17243286562331026
KNN               PARSEC         Base           log_g             0.16864683262044497
                                 mass_smaller_3 log_g             0.17779208622084253
linear_regression PARSEC         Base           log_g              0.7507155523234634
                                 mass_smaller_3 log_g              0.6022281394911589
mlp               PARSEC         Base           log_g              0.5010944235421306
                                 mass_smaller_3 log_g             0.46154356314230977
random_forest     PARSEC         Base           log_g             0.14624083345990166
                                 mass_smaller_3 log_g             0.16660204760430417
xgboost           PARSEC         Base           log_g               0.313614388728856
                                 mass_smaller_3 log_g              0.2428021744059252

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.01100000000000012
                                 mass_smaller_3 log_g             0.010500000000000398
KNN               PARSEC         Base           log_g             0.013200000000000323
                                 mass_smaller_3 log_g             0.009200000000000763
linear_regression PARSEC         Base           log_g               0.5052899263280148
                                 mass_smaller_3 log_g               0.4288445972044663
mlp               PARSEC         Base           log_g              0.25958360258796387
                                 mass_smaller_3 log_g              0.23512261336306195
random_forest     PARSEC         Base           log_g             0.012716574855699436
                                 mass_smaller_3 log_g             0.012856708461763011
xgboost           PARSEC         Base           log_g              0.10713393402099625
                                 mass_smaller_3 log_g              0.06981694793701188

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.8738266108931796
                                 mass_smaller_3 log_g              0.7996749450421449
KNN               PARSEC         Base           log_g              0.8935178759114629
                                 mass_smaller_3 log_g              0.8426181338086113
linear_regression PARSEC         Base           log_g             0.41715368143690107
                                 mass_smaller_3 log_g              0.5273496655379108
mlp               PARSEC         Base           log_g              0.7124610004519873
                                 mass_smaller_3 log_g              0.6706293959928037
random_forest     PARSEC         Base           log_g              0.8998465625312148
                                 mass_smaller_3 log_g              0.8408310250847246
xgboost           PARSEC         Base           log_g              0.8494127272684615
                                 mass_smaller_3 log_g              0.8431824079541927

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              4.779999999999999
                                 mass_smaller_3 log_g                           4.75
KNN               PARSEC         Base           log_g                         4.6354
                                 mass_smaller_3 log_g              4.634999999999999
linear_regression PARSEC         Base           log_g             3.3549603792326215
                                 mass_smaller_3 log_g              2.936832576342485
mlp               PARSEC         Base           log_g              3.893785889637569
                                 mass_smaller_3 log_g             3.4309115370204775
random_forest     PARSEC         Base           log_g              4.620864250000007
                                 mass_smaller_3 log_g             4.6063405009041585
xgboost           PARSEC         Base           log_g              4.357620960235596
                                 mass_smaller_3 log_g              4.618734474182129

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 0.05772 / 90 : 0.22267 / 95 : 0.89533 / 99 : 2.907
                                 mass_smaller_3 log_g                  75 : 0.05442 / 90 : 0.28814 / 95 : 1.209 / 99 : 3.101
KNN               PARSEC         Base           log_g                 75 : 0.0886 / 90 : 0.4462 / 95 : 1.0346 / 99 : 2.24206
                                 mass_smaller_3 log_g                  75 : 0.062 / 90 : 0.5692 / 95 : 1.1544 / 99 : 2.32292
linear_regression PARSEC         Base           log_g              75 : 1.13119 / 90 : 1.62211 / 95 : 1.88341 / 99 : 2.41107
                                 mass_smaller_3 log_g              75 : 0.75872 / 90 : 1.39948 / 95 : 1.73583 / 99 : 2.20171
mlp               PARSEC         Base           log_g              75 : 0.73311 / 90 : 1.41779 / 95 : 1.65723 / 99 : 2.18019
                                 mass_smaller_3 log_g               75 : 0.6676 / 90 : 1.28453 / 95 : 1.61766 / 99 : 2.07739
random_forest     PARSEC         Base           log_g                 75 : 0.065 / 90 : 0.2823 / 95 : 0.91148 / 99 : 2.37473
                                 mass_smaller_3 log_g              75 : 0.06329 / 90 : 0.38362 / 95 : 1.14334 / 99 : 2.48512
xgboost           PARSEC         Base           log_g               75 : 0.40285 / 90 : 0.95171 / 95 : 1.2855 / 99 : 2.01364
                                 mass_smaller_3 log_g              75 : 0.22379 / 90 : 0.76868 / 95 : 1.18554 / 99 : 2.04576

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
KNN               PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
linear_regression PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
mlp               PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
random_forest     PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345
xgboost           PARSEC         Base           log_g             3.233 - 5.345
                                 mass_smaller_3 log_g             3.465 - 5.345

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              -0.22366302531475957
                                 mass_smaller_3 log_g               -0.4913583627937592
KNN               PARSEC         Base           log_g               -0.5685510473572672
                                 mass_smaller_3 log_g              -0.21372743099124003
linear_regression PARSEC         Base           log_g               -1.2252488306693854
                                 mass_smaller_3 log_g                -3.275418831406798
mlp               PARSEC         Base           log_g                -4.371543636897526
                                 mass_smaller_3 log_g                -3.868650811787682
random_forest     PARSEC         Base           log_g               0.17211468827279353
                                 mass_smaller_3 log_g             -0.011329182377379121
xgboost           PARSEC         Base           log_g               -1.0124875678765508
                                 mass_smaller_3 log_g               -0.6001570140062298

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.3804738903721785
                                 mass_smaller_3 log_g             0.40044279595694104
KNN               PARSEC         Base           log_g              0.4433203725835331
                                 mass_smaller_3 log_g              0.3684311737170496
linear_regression PARSEC         Base           log_g              1.4736793628524247
                                 mass_smaller_3 log_g              1.2034244710801263
mlp               PARSEC         Base           log_g              1.0634881908332428
                                 mass_smaller_3 log_g               0.938630709588942
random_forest     PARSEC         Base           log_g             0.31598778809171013
                                 mass_smaller_3 log_g             0.33344741344998047
xgboost           PARSEC         Base           log_g                0.55356010503011
                                 mass_smaller_3 log_g              0.4608442281579774

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.0674954147134116
                                 mass_smaller_3 log_g             0.07341851606825935
KNN               PARSEC         Base           log_g              0.1346078724936512
                                 mass_smaller_3 log_g             0.10335706411523063
linear_regression PARSEC         Base           log_g              1.3839826888373719
                                 mass_smaller_3 log_g              1.0842145783746058
mlp               PARSEC         Base           log_g              0.7790407681121997
                                 mass_smaller_3 log_g              0.6733604896505861
random_forest     PARSEC         Base           log_g             0.07025955886257117
                                 mass_smaller_3 log_g              0.0779484265301924
xgboost           PARSEC         Base           log_g             0.31917765404091575
                                 mass_smaller_3 log_g             0.25720931950684656

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.0007500000000000284
                                 mass_smaller_3 log_g             0.0009999999999994458
KNN               PARSEC         Base           log_g              0.007000000000000561
                                 mass_smaller_3 log_g              0.005199999999999427
linear_regression PARSEC         Base           log_g                 1.318829272889185
                                 mass_smaller_3 log_g                1.1140769299772573
mlp               PARSEC         Base           log_g                 0.578821821548086
                                 mass_smaller_3 log_g                0.3018774212820845
random_forest     PARSEC         Base           log_g             0.0009799999999917652
                                 mass_smaller_3 log_g             0.0009199999999998099
xgboost           PARSEC         Base           log_g               0.09096437835693338
                                 mass_smaller_3 log_g               0.07795264053344741

                                                                                 CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.7053404051445747
                                 mass_smaller_3 log_g              0.6684831846270675
KNN               PARSEC         Base           log_g               0.726834275461127
                                 mass_smaller_3 log_g              0.7127792459877859
linear_regression PARSEC         Base           log_g             0.33703567351467884
                                 mass_smaller_3 log_g              0.5893814048738154
mlp               PARSEC         Base           log_g              0.7792055306173461
                                 mass_smaller_3 log_g              0.7249651329375316
random_forest     PARSEC         Base           log_g              0.7759789538352955
                                 mass_smaller_3 log_g              0.7416104362495699
xgboost           PARSEC         Base           log_g              0.8095818883794095
                                 mass_smaller_3 log_g              0.7734199570754127

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              4.779999999999999
                                 mass_smaller_3 log_g                           4.75
KNN               PARSEC         Base           log_g                          4.513
                                 mass_smaller_3 log_g              4.341399999999999
linear_regression PARSEC         Base           log_g             3.3549603792326215
                                 mass_smaller_3 log_g              2.223276704591555
mlp               PARSEC         Base           log_g             2.7110084335766444
                                 mass_smaller_3 log_g              1.965581096787684
random_forest     PARSEC         Base           log_g              4.226316213803089
                                 mass_smaller_3 log_g              4.061556465099716
xgboost           PARSEC         Base           log_g              3.585430902481079
                                 mass_smaller_3 log_g             3.6259056000709533

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                     75 : 0.006 / 90 : 0.026 / 95 : 0.064 / 99 : 1.9685
                                 mass_smaller_3 log_g                   75 : 0.004 / 90 : 0.02 / 95 : 0.06495 / 99 : 1.94447
KNN               PARSEC         Base           log_g                  75 : 0.0274 / 90 : 0.2318 / 95 : 0.848 / 99 : 2.22856
                                 mass_smaller_3 log_g                  75 : 0.0188 / 90 : 0.068 / 95 : 0.7936 / 99 : 1.89692
linear_regression PARSEC         Base           log_g               75 : 1.74379 / 90 : 2.02828 / 95 : 2.27583 / 99 : 2.7985
                                 mass_smaller_3 log_g                75 : 1.4902 / 90 : 1.7786 / 95 : 1.87714 / 99 : 2.02769
mlp               PARSEC         Base           log_g              75 : 1.51463 / 90 : 1.68943 / 95 : 1.85061 / 99 : 2.26065
                                 mass_smaller_3 log_g                75 : 1.337 / 90 : 1.67464 / 95 : 1.76603 / 99 : 1.86737
random_forest     PARSEC         Base           log_g              75 : 0.00681 / 90 : 0.04898 / 95 : 0.32346 / 99 : 1.76773
                                 mass_smaller_3 log_g              75 : 0.00543 / 90 : 0.06492 / 95 : 0.42355 / 99 : 1.79859
xgboost           PARSEC         Base           log_g              75 : 0.43347 / 90 : 1.03051 / 95 : 1.34273 / 99 : 1.90141
                                 mass_smaller_3 log_g                 75 : 0.32566 / 90 : 0.798 / 95 : 1.10784 / 99 : 1.6715

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 2.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
KNN               PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
linear_regression PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
mlp               PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
random_forest     PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299
xgboost           PARSEC         Base           log_g             0.638 - 4.299
                                 mass_smaller_3 log_g             2.456 - 4.299

                                                                                    RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.20108117139632975
                                 mass_smaller_3 log_g                 -5.81812692567734
KNN               PARSEC         Base           log_g                 0.551332428608432
                                 mass_smaller_3 log_g               -2.5068845861149858
linear_regression PARSEC         Base           log_g               0.20729145625045087
                                 mass_smaller_3 log_g             -0.027980441684109847
mlp               PARSEC         Base           log_g               0.42018335004606344
                                 mass_smaller_3 log_g               -0.9837728761605316
random_forest     PARSEC         Base           log_g                0.4626143591760997
                                 mass_smaller_3 log_g               -3.2568541084898603
xgboost           PARSEC         Base           log_g               0.35000992847659496
                                 mass_smaller_3 log_g               -1.3121363760708706

                                                                                RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.7561211004774188
                                 mass_smaller_3 log_g             1.0463984851401869
KNN               PARSEC         Base           log_g             0.5921304852198191
                                 mass_smaller_3 log_g             0.8098841803265027
linear_regression PARSEC         Base           log_g             0.8048821107537918
                                 mass_smaller_3 log_g             0.9174628418935944
mlp               PARSEC         Base           log_g             0.9489659448639525
                                 mass_smaller_3 log_g             0.9294766901798789
random_forest     PARSEC         Base           log_g             0.6322730705325913
                                 mass_smaller_3 log_g             0.8598902436974643
xgboost           PARSEC         Base           log_g              0.832163042077831
                                 mass_smaller_3 log_g             0.7987716167825999

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.30299790989997644
                                 mass_smaller_3 log_g              0.4757052385721764
KNN               PARSEC         Base           log_g             0.30719576100433976
                                 mass_smaller_3 log_g              0.4724216773162939
linear_regression PARSEC         Base           log_g              0.6640426255531428
                                 mass_smaller_3 log_g              0.8411477623788803
mlp               PARSEC         Base           log_g              0.8097761783822659
                                 mass_smaller_3 log_g              0.8202772569017484
random_forest     PARSEC         Base           log_g              0.2893723786433942
                                 mass_smaller_3 log_g             0.44883480568115963
xgboost           PARSEC         Base           log_g              0.6713615037908816
                                 mass_smaller_3 log_g              0.6331751794297094

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.06000000000000005
                                 mass_smaller_3 log_g              0.03200000000000003
KNN               PARSEC         Base           log_g              0.09160000000000013
                                 mass_smaller_3 log_g              0.07390000000000008
linear_regression PARSEC         Base           log_g               0.6125379386601224
                                 mass_smaller_3 log_g                0.828322316142847
mlp               PARSEC         Base           log_g               0.8322471385767223
                                 mass_smaller_3 log_g               0.8687189969637106
random_forest     PARSEC         Base           log_g              0.06806103589466095
                                 mass_smaller_3 log_g             0.051811014568760694
xgboost           PARSEC         Base           log_g               0.5849574146270751
                                 mass_smaller_3 log_g               0.5260204954147338

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.6543935473449031
                                 mass_smaller_3 log_g              0.04590994627709065
KNN               PARSEC         Base           log_g               0.7693849003643232
                                 mass_smaller_3 log_g              0.05468711496212319
linear_regression PARSEC         Base           log_g                0.493104879406129
                                 mass_smaller_3 log_g              0.32866941676222167
mlp               PARSEC         Base           log_g               0.6521638888149588
                                 mass_smaller_3 log_g             -0.26171239282065073
random_forest     PARSEC         Base           log_g                0.737427211287738
                                 mass_smaller_3 log_g              0.09053666406842789
xgboost           PARSEC         Base           log_g               0.6120898372154866
                                 mass_smaller_3 log_g              0.08962101173691343

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                          4.171
                                 mass_smaller_3 log_g              4.218000000000001
KNN               PARSEC         Base           log_g             3.9669999999999996
                                 mass_smaller_3 log_g             3.9967999999999995
linear_regression PARSEC         Base           log_g              2.888378364365141
                                 mass_smaller_3 log_g             1.9747558791773958
mlp               PARSEC         Base           log_g              2.375105573667385
                                 mass_smaller_3 log_g             1.8524857842642022
random_forest     PARSEC         Base           log_g             3.6829900000000007
                                 mass_smaller_3 log_g                          3.747
xgboost           PARSEC         Base           log_g              2.695528434753418
                                 mass_smaller_3 log_g              2.927567584991455

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              75 : 0.15628 / 90 : 1.01729 / 95 : 1.81952 / 99 : 3.37886
                                 mass_smaller_3 log_g                   75 : 0.13406 / 90 : 1.7185 / 95 : 2.965 / 99 : 3.604
KNN               PARSEC         Base           log_g                 75 : 0.2642 / 90 : 1.089 / 95 : 1.41552 / 99 : 2.27112
                                 mass_smaller_3 log_g               75 : 0.91525 / 90 : 1.3874 / 95 : 1.80435 / 99 : 2.71107
linear_regression PARSEC         Base           log_g              75 : 0.93956 / 90 : 1.24051 / 95 : 1.47758 / 99 : 2.09846
                                 mass_smaller_3 log_g               75 : 1.08461 / 90 : 1.3396 / 95 : 1.49714 / 99 : 1.71783
mlp               PARSEC         Base           log_g              75 : 1.17152 / 90 : 1.42053 / 95 : 1.61857 / 99 : 2.05238
                                 mass_smaller_3 log_g               75 : 1.1808 / 90 : 1.36753 / 95 : 1.46222 / 99 : 1.63853
random_forest     PARSEC         Base           log_g              75 : 0.19441 / 90 : 1.02485 / 95 : 1.67336 / 99 : 2.64035
                                 mass_smaller_3 log_g              75 : 0.67449 / 90 : 1.61414 / 95 : 2.20096 / 99 : 2.88029
xgboost           PARSEC         Base           log_g               75 : 1.02779 / 90 : 1.3463 / 95 : 1.53656 / 99 : 1.99333
                                 mass_smaller_3 log_g               75 : 1.02728 / 90 : 1.29965 / 95 : 1.4458 / 99 : 1.79904

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 3.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
KNN               PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
linear_regression PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
mlp               PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
random_forest     PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823
xgboost           PARSEC         Base           log_g             -0.384 - 3.823
                                 mass_smaller_3 log_g             -0.384 - 3.823

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              -0.4342441850216521
                                 mass_smaller_3 log_g               -0.880261906687066
KNN               PARSEC         Base           log_g             -0.09689368389630881
                                 mass_smaller_3 log_g               -0.427641034000505
linear_regression PARSEC         Base           log_g              0.16872633450213492
                                 mass_smaller_3 log_g             -0.07393039338067586
mlp               PARSEC         Base           log_g              0.20179797271613364
                                 mass_smaller_3 log_g             -0.08999932766193641
random_forest     PARSEC         Base           log_g             -0.17211974773342287
                                 mass_smaller_3 log_g              -0.5217660400358439
xgboost           PARSEC         Base           log_g              0.06308841876492932
                                 mass_smaller_3 log_g                -0.19417234585858

                                                                                RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.9806733151868601
                                 mass_smaller_3 log_g             1.0524628039553423
KNN               PARSEC         Base           log_g              0.871943985963139
                                 mass_smaller_3 log_g             0.9324055656208091
linear_regression PARSEC         Base           log_g             1.0376784628560318
                                 mass_smaller_3 log_g             0.9684705976926009
mlp               PARSEC         Base           log_g             0.8787774752504091
                                 mass_smaller_3 log_g             0.9170710825508944
random_forest     PARSEC         Base           log_g             0.8919685917893991
                                 mass_smaller_3 log_g             0.9525083924664207
xgboost           PARSEC         Base           log_g             0.8838233864363637
                                 mass_smaller_3 log_g              0.884134270404242

                                                                                  MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.4706731696496021
                                 mass_smaller_3 log_g              0.5311386742407748
KNN               PARSEC         Base           log_g              0.4621658142408975
                                 mass_smaller_3 log_g              0.5177275635100691
linear_regression PARSEC         Base           log_g               0.824557446497259
                                 mass_smaller_3 log_g               0.703052358506027
mlp               PARSEC         Base           log_g              0.6335271542640621
                                 mass_smaller_3 log_g              0.6460260954776122
random_forest     PARSEC         Base           log_g             0.45107542838461695
                                 mass_smaller_3 log_g              0.5057081491788876
xgboost           PARSEC         Base           log_g               0.596223000234553
                                 mass_smaller_3 log_g              0.5557107972143425

                                                                                MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.06618847006651918
                                 mass_smaller_3 log_g              0.0662121212121205
KNN               PARSEC         Base           log_g             0.10949999999999993
                                 mass_smaller_3 log_g              0.1245999999999996
linear_regression PARSEC         Base           log_g              0.6483713689644435
                                 mass_smaller_3 log_g             0.48444218901040426
mlp               PARSEC         Base           log_g             0.38409884117374316
                                 mass_smaller_3 log_g             0.41266565000962974
random_forest     PARSEC         Base           log_g             0.07739903932491243
                                 mass_smaller_3 log_g             0.07966892748917664
xgboost           PARSEC         Base           log_g              0.3601102428436279
                                 mass_smaller_3 log_g              0.2606408271789551

                                                                                    CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                  0.240075575575364
                                 mass_smaller_3 log_g               -0.07296696718913202
KNN               PARSEC         Base           log_g                0.30429608142710995
                                 mass_smaller_3 log_g               -0.12680921360913017
linear_regression PARSEC         Base           log_g                0.41099301685375894
                                 mass_smaller_3 log_g              0.0006934333213137371
mlp               PARSEC         Base           log_g                0.45746960129678993
                                 mass_smaller_3 log_g             -0.0006398085089834495
random_forest     PARSEC         Base           log_g                0.30681622944559384
                                 mass_smaller_3 log_g               -0.03516617995366493
xgboost           PARSEC         Base           log_g                0.29917511289779664
                                 mass_smaller_3 log_g                -0.1010028439246436

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             4.7700000000000005
                                 mass_smaller_3 log_g                           4.71
KNN               PARSEC         Base           log_g                         4.6354
                                 mass_smaller_3 log_g              4.634999999999999
linear_regression PARSEC         Base           log_g              2.857540161797114
                                 mass_smaller_3 log_g              2.936832576342485
mlp               PARSEC         Base           log_g              3.893785889637569
                                 mass_smaller_3 log_g             3.4309115370204775
random_forest     PARSEC         Base           log_g              4.620864250000007
                                 mass_smaller_3 log_g             4.6063405009041585
xgboost           PARSEC         Base           log_g              4.357620960235596
                                 mass_smaller_3 log_g              4.618734474182129

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                75 : 0.42077 / 90 : 1.80427 / 95 : 2.529 / 99 : 3.83062
                                 mass_smaller_3 log_g                    75 : 0.597 / 90 : 1.973 / 95 : 2.648 / 99 : 3.88029
KNN               PARSEC         Base           log_g                 75 : 0.6006 / 90 : 1.5316 / 95 : 2.08425 / 99 : 3.6946
                                 mass_smaller_3 log_g               75 : 0.7435 / 90 : 1.64504 / 95 : 2.15458 / 99 : 3.78594
linear_regression PARSEC         Base           log_g              75 : 1.22793 / 90 : 1.78372 / 95 : 2.15088 / 99 : 2.44176
                                 mass_smaller_3 log_g              75 : 0.91576 / 90 : 1.87167 / 95 : 2.20908 / 99 : 2.56074
mlp               PARSEC         Base           log_g              75 : 0.85527 / 90 : 1.63268 / 95 : 2.02307 / 99 : 2.49201
                                 mass_smaller_3 log_g              75 : 0.92326 / 90 : 1.72094 / 95 : 2.08946 / 99 : 2.58135
random_forest     PARSEC         Base           log_g               75 : 0.49493 / 90 : 1.61497 / 95 : 2.2236 / 99 : 3.56651
                                 mass_smaller_3 log_g                75 : 0.6549 / 90 : 1.75629 / 95 : 2.2964 / 99 : 3.68208
xgboost           PARSEC         Base           log_g               75 : 0.87508 / 90 : 1.49202 / 95 : 1.96052 / 99 : 2.9245
                                 mass_smaller_3 log_g                75 : 0.77053 / 90 : 1.594 / 95 : 2.02284 / 99 : 3.12637

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
KNN               PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
linear_regression PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
mlp               PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
random_forest     PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979
xgboost           PARSEC         Base           log_g             -0.102 - 2.978
                                 mass_smaller_3 log_g              1.664 - 2.979

                                                                                   RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.8996188259668024
                                 mass_smaller_3 log_g              0.11404521047206362
KNN               PARSEC         Base           log_g               0.8882757130576726
                                 mass_smaller_3 log_g             -0.31793523499230036
linear_regression PARSEC         Base           log_g              0.41809683900763883
                                 mass_smaller_3 log_g              -1.7831529887251545
mlp               PARSEC         Base           log_g               0.7089460485360655
                                 mass_smaller_3 log_g               -4.904534322938302
random_forest     PARSEC         Base           log_g               0.9145444334060797
                                 mass_smaller_3 log_g              0.15786114968184173
xgboost           PARSEC         Base           log_g                0.787073838129444
                                 mass_smaller_3 log_g             -0.12004805436251598

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                0.12689924955296
                                 mass_smaller_3 log_g             0.09808715446053273
KNN               PARSEC         Base           log_g             0.13387680251544362
                                 mass_smaller_3 log_g               0.119385158583499
linear_regression PARSEC         Base           log_g             0.49609832945006466
                                 mass_smaller_3 log_g              0.3724657711181218
mlp               PARSEC         Base           log_g             0.32092417624011965
                                 mass_smaller_3 log_g              0.3540306932941142
random_forest     PARSEC         Base           log_g             0.11708589447086708
                                 mass_smaller_3 log_g             0.09566176938117092
xgboost           PARSEC         Base           log_g             0.20092473448709836
                                 mass_smaller_3 log_g              0.1148964453020636

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.043146619696415985
                                 mass_smaller_3 log_g               0.0410719577914542
KNN               PARSEC         Base           log_g              0.04803300372999391
                                 mass_smaller_3 log_g              0.04453094274788007
linear_regression PARSEC         Base           log_g              0.39697599961128927
                                 mass_smaller_3 log_g              0.34387720192633203
mlp               PARSEC         Base           log_g              0.24665996550158628
                                 mass_smaller_3 log_g               0.2655460784977146
random_forest     PARSEC         Base           log_g              0.04294454665629935
                                 mass_smaller_3 log_g              0.04095225794311631
xgboost           PARSEC         Base           log_g              0.10766642553555553
                                 mass_smaller_3 log_g              0.06971391476119151

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.008835526315790432
                                 mass_smaller_3 log_g              0.009866666666666912
KNN               PARSEC         Base           log_g             0.0041999999999999815
                                 mass_smaller_3 log_g             0.0043999999999999595
linear_regression PARSEC         Base           log_g               0.34484031970743656
                                 mass_smaller_3 log_g               0.36121216792041055
mlp               PARSEC         Base           log_g               0.20593015490835187
                                 mass_smaller_3 log_g               0.19368218166878393
random_forest     PARSEC         Base           log_g              0.009042807821093124
                                 mass_smaller_3 log_g               0.01002720265485646
xgboost           PARSEC         Base           log_g               0.04631657028198255
                                 mass_smaller_3 log_g               0.03659584045410158

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.9495173145621928
                                 mass_smaller_3 log_g               0.6561391172740382
KNN               PARSEC         Base           log_g               0.9441238142534801
                                 mass_smaller_3 log_g               0.5749815519721571
linear_regression PARSEC         Base           log_g               0.6483869807966186
                                 mass_smaller_3 log_g              0.20020399851840714
mlp               PARSEC         Base           log_g               0.8740210618735573
                                 mass_smaller_3 log_g             -0.04805077284622189
random_forest     PARSEC         Base           log_g                0.956704367836196
                                 mass_smaller_3 log_g               0.6650497474294527
xgboost           PARSEC         Base           log_g               0.8930521859521106
                                 mass_smaller_3 log_g              0.40278718654302287

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.5284999999999997
                                 mass_smaller_3 log_g                          2.212
KNN               PARSEC         Base           log_g             3.4999999999999996
                                 mass_smaller_3 log_g             1.2215999999999996
linear_regression PARSEC         Base           log_g             1.8928720936217218
                                 mass_smaller_3 log_g             0.9553918752627246
mlp               PARSEC         Base           log_g             2.0147816415537525
                                 mass_smaller_3 log_g             1.5925339120942983
random_forest     PARSEC         Base           log_g              3.485594333333332
                                 mass_smaller_3 log_g             2.0349299999999992
xgboost           PARSEC         Base           log_g             1.6199701566696167
                                 mass_smaller_3 log_g             1.1789817924499513

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               75 : 0.04239 / 90 : 0.10199 / 95 : 0.1735 / 99 : 0.49256
                                 mass_smaller_3 log_g              75 : 0.04329 / 90 : 0.10266 / 95 : 0.17963 / 99 : 0.42992
KNN               PARSEC         Base           log_g                 75 : 0.0172 / 90 : 0.1798 / 95 : 0.3366 / 99 : 0.50174
                                 mass_smaller_3 log_g                    75 : 0.0164 / 90 : 0.1626 / 95 : 0.3252 / 99 : 0.48
linear_regression PARSEC         Base           log_g              75 : 0.43839 / 90 : 0.51863 / 95 : 1.25134 / 99 : 1.52105
                                 mass_smaller_3 log_g              75 : 0.44919 / 90 : 0.52292 / 95 : 0.55141 / 99 : 0.59301
mlp               PARSEC         Base           log_g               75 : 0.29286 / 90 : 0.4783 / 95 : 0.73003 / 99 : 0.95422
                                 mass_smaller_3 log_g              75 : 0.33731 / 90 : 0.66023 / 95 : 0.79214 / 99 : 0.95453
random_forest     PARSEC         Base           log_g               75 : 0.0429 / 90 : 0.10336 / 95 : 0.17694 / 99 : 0.49335
                                 mass_smaller_3 log_g               75 : 0.04351 / 90 : 0.10283 / 95 : 0.1785 / 99 : 0.42989
xgboost           PARSEC         Base           log_g              75 : 0.11966 / 90 : 0.26802 / 95 : 0.40739 / 99 : 0.93169
                                 mass_smaller_3 log_g              75 : 0.09323 / 90 : 0.17088 / 95 : 0.23277 / 99 : 0.43226

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 5.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
KNN               PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
linear_regression PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
mlp               PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
random_forest     PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963
xgboost           PARSEC         Base           log_g               0.2 - 2.963
                                 mass_smaller_3 log_g             2.306 - 2.963

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9533659103656469
                                 mass_smaller_3 log_g              0.6262346430201227
KNN               PARSEC         Base           log_g              0.9638467570643746
                                 mass_smaller_3 log_g              0.9405659745504094
linear_regression PARSEC         Base           log_g              0.4678537575861228
                                 mass_smaller_3 log_g             -0.5118505323003208
mlp               PARSEC         Base           log_g              0.6986586890359093
                                 mass_smaller_3 log_g             -1.6619991985832945
random_forest     PARSEC         Base           log_g              0.9666549586583413
                                 mass_smaller_3 log_g              0.8170329219219435
xgboost           PARSEC         Base           log_g              0.8051410225359259
                                 mass_smaller_3 log_g              0.5365616668373909

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.15717495828060182
                                 mass_smaller_3 log_g              0.07623685781704885
KNN               PARSEC         Base           log_g              0.13879269452312337
                                 mass_smaller_3 log_g             0.030607814134481548
linear_regression PARSEC         Base           log_g               0.7751878266344273
                                 mass_smaller_3 log_g              0.38366584599722453
mlp               PARSEC         Base           log_g              0.42693670808661904
                                 mass_smaller_3 log_g                0.206625090379991
random_forest     PARSEC         Base           log_g              0.13291489163846407
                                 mass_smaller_3 log_g              0.05373796459134662
xgboost           PARSEC         Base           log_g              0.32974514473389915
                                 mass_smaller_3 log_g              0.09136623908356702

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.03755731681283733
                                 mass_smaller_3 log_g             0.011930591571911515
KNN               PARSEC         Base           log_g             0.054555577970546706
                                 mass_smaller_3 log_g             0.009592704900021983
linear_regression PARSEC         Base           log_g               0.6603042198897785
                                 mass_smaller_3 log_g               0.3545264358082975
mlp               PARSEC         Base           log_g              0.32023937085513465
                                 mass_smaller_3 log_g              0.15821347390751872
random_forest     PARSEC         Base           log_g             0.038264850601011854
                                 mass_smaller_3 log_g             0.015771415708761283
xgboost           PARSEC         Base           log_g              0.22544233025995322
                                 mass_smaller_3 log_g              0.06401342476207957

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.0009999999999998899
                                 mass_smaller_3 log_g             0.0009999999999998899
KNN               PARSEC         Base           log_g             0.0040000000000000036
                                 mass_smaller_3 log_g             0.0011999999999994237
linear_regression PARSEC         Base           log_g                0.6126151759684642
                                 mass_smaller_3 log_g                0.3751810808229963
mlp               PARSEC         Base           log_g                0.2203168324483551
                                 mass_smaller_3 log_g               0.12841863737238812
random_forest     PARSEC         Base           log_g             0.0014899999999975488
                                 mass_smaller_3 log_g             0.0010750000000019355
xgboost           PARSEC         Base           log_g                0.1291932544708252
                                 mass_smaller_3 log_g              0.044125329971313576

                                                                                    CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                 0.9768621176667662
                                 mass_smaller_3 log_g                 0.8466213690973723
KNN               PARSEC         Base           log_g                 0.9819199172421853
                                 mass_smaller_3 log_g                 0.9711446067295945
linear_regression PARSEC         Base           log_g                 0.7008181919711453
                                 mass_smaller_3 log_g                 0.6331357178312571
mlp               PARSEC         Base           log_g                 0.8616045482860637
                                 mass_smaller_3 log_g             -0.0053274365352318385
random_forest     PARSEC         Base           log_g                 0.9833138504657927
                                 mass_smaller_3 log_g                 0.9159047942410397
xgboost           PARSEC         Base           log_g                 0.8996437217333252
                                 mass_smaller_3 log_g                 0.7992078903237559

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                          3.008
                                 mass_smaller_3 log_g             1.4170000000000003
KNN               PARSEC         Base           log_g                          2.025
                                 mass_smaller_3 log_g             0.7721999999999998
linear_regression PARSEC         Base           log_g             2.0422025470259753
                                 mass_smaller_3 log_g             0.7296908218483917
mlp               PARSEC         Base           log_g             1.6897660627487243
                                 mass_smaller_3 log_g             0.8689507371631446
random_forest     PARSEC         Base           log_g              2.000681000000001
                                 mass_smaller_3 log_g             0.6925351428571425
xgboost           PARSEC         Base           log_g             2.0213280515670777
                                 mass_smaller_3 log_g             0.5518983612060548

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                  75 : 0.005 / 90 : 0.061 / 95 : 0.16786 / 99 : 0.82728
                                 mass_smaller_3 log_g                    75 : 0.002 / 90 : 0.003 / 95 : 0.0155 / 99 : 0.4175
KNN               PARSEC         Base           log_g                  75 : 0.0546 / 90 : 0.142 / 95 : 0.2453 / 99 : 0.67312
                                 mass_smaller_3 log_g                  75 : 0.0034 / 90 : 0.0262 / 95 : 0.0547 / 99 : 0.1265
linear_regression PARSEC         Base           log_g                75 : 1.0052 / 90 : 1.23247 / 95 : 1.3198 / 99 : 1.42503
                                 mass_smaller_3 log_g               75 : 0.46426 / 90 : 0.52389 / 95 : 0.54618 / 99 : 0.5827
mlp               PARSEC         Base           log_g              75 : 0.49825 / 90 : 0.75493 / 95 : 0.87557 / 99 : 1.11006
                                 mass_smaller_3 log_g              75 : 0.22548 / 90 : 0.33275 / 95 : 0.42431 / 99 : 0.59992
random_forest     PARSEC         Base           log_g              75 : 0.01604 / 90 : 0.08853 / 95 : 0.18934 / 99 : 0.68744
                                 mass_smaller_3 log_g              75 : 0.00538 / 90 : 0.03457 / 95 : 0.08417 / 99 : 0.27399
xgboost           PARSEC         Base           log_g              75 : 0.33553 / 90 : 0.56962 / 95 : 0.69518 / 99 : 1.03312
                                 mass_smaller_3 log_g              75 : 0.08605 / 90 : 0.14662 / 95 : 0.19723 / 99 : 0.30599

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Results for the label category with a value of 6.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
KNN               PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
linear_regression PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
mlp               PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
random_forest     PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869
xgboost           PARSEC         Base           log_g             -0.017 - 2.837
                                 mass_smaller_3 log_g              2.046 - 2.869

                                                                                  RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.9311821113501082
                                 mass_smaller_3 log_g              0.8214014947758541
KNN               PARSEC         Base           log_g              0.9376850472249867
                                 mass_smaller_3 log_g              0.7243220607861849
linear_regression PARSEC         Base           log_g              -0.725236777537009
                                 mass_smaller_3 log_g             -0.4352627390919068
mlp               PARSEC         Base           log_g             0.45945948611375387
                                 mass_smaller_3 log_g             -1.5911214768574262
random_forest     PARSEC         Base           log_g              0.9485394146228903
                                 mass_smaller_3 log_g               0.890498434582598
xgboost           PARSEC         Base           log_g              0.6299752924480326
                                 mass_smaller_3 log_g             0.12597016843511355

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.15600976608096281
                                 mass_smaller_3 log_g              0.06388898546747886
KNN               PARSEC         Base           log_g              0.14852986204704607
                                 mass_smaller_3 log_g              0.08160418202920015
linear_regression PARSEC         Base           log_g               0.9778939817449916
                                 mass_smaller_3 log_g               0.1843484443498175
mlp               PARSEC         Base           log_g               0.4828140782596478
                                 mass_smaller_3 log_g              0.41382998356065887
random_forest     PARSEC         Base           log_g              0.13499216064629066
                                 mass_smaller_3 log_g             0.050048785986341375
xgboost           PARSEC         Base           log_g               0.3751694022658579
                                 mass_smaller_3 log_g              0.15861226669062742

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              0.04662199042529842
                                 mass_smaller_3 log_g             0.031483797547070556
KNN               PARSEC         Base           log_g              0.08393938447814452
                                 mass_smaller_3 log_g              0.06278251150558842
linear_regression PARSEC         Base           log_g               0.8951615474508734
                                 mass_smaller_3 log_g              0.14546094915210817
mlp               PARSEC         Base           log_g                0.401809244761115
                                 mass_smaller_3 log_g               0.3547322469837879
random_forest     PARSEC         Base           log_g              0.04500354176302885
                                 mass_smaller_3 log_g             0.029233394187855095
xgboost           PARSEC         Base           log_g               0.2942276428030816
                                 mass_smaller_3 log_g               0.1214680163391635

                                                                                 MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             0.018000000000000016
                                 mass_smaller_3 log_g             0.018000000000000238
KNN               PARSEC         Base           log_g              0.05269999999999997
                                 mass_smaller_3 log_g              0.05039999999999978
linear_regression PARSEC         Base           log_g               0.8730742498357572
                                 mass_smaller_3 log_g              0.12280681136615179
mlp               PARSEC         Base           log_g              0.35531851890717814
                                 mass_smaller_3 log_g               0.3447107617701137
random_forest     PARSEC         Base           log_g              0.01502404127816695
                                 mass_smaller_3 log_g                0.015539999999997
xgboost           PARSEC         Base           log_g              0.24093734741210926
                                 mass_smaller_3 log_g              0.09741741752624522

                                                                                  CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g               0.9659004318793163
                                 mass_smaller_3 log_g               0.9137753224431725
KNN               PARSEC         Base           log_g                0.968447483894023
                                 mass_smaller_3 log_g               0.8514922936185082
linear_regression PARSEC         Base           log_g               0.2742120379276352
                                 mass_smaller_3 log_g               0.6041004197350325
mlp               PARSEC         Base           log_g               0.6800634465130304
                                 mass_smaller_3 log_g             -0.10822335924689093
random_forest     PARSEC         Base           log_g               0.9740958718877286
                                 mass_smaller_3 log_g               0.9447824833511316
xgboost           PARSEC         Base           log_g               0.7940521336810684
                                 mass_smaller_3 log_g               0.6077592472897164

                                                                              MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g             3.0180000000000002
                                 mass_smaller_3 log_g             1.3810000000000002
KNN               PARSEC         Base           log_g             2.1087999999999996
                                 mass_smaller_3 log_g             0.3613999999999997
linear_regression PARSEC         Base           log_g             2.0137390311160424
                                 mass_smaller_3 log_g             0.6964242589225278
mlp               PARSEC         Base           log_g              1.551814174411986
                                 mass_smaller_3 log_g              0.973258697237001
random_forest     PARSEC         Base           log_g              2.152537166666666
                                 mass_smaller_3 log_g             0.5774567619047599
xgboost           PARSEC         Base           log_g             1.3663098917007446
                                 mass_smaller_3 log_g             0.5920764636993407

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g                    75 : 0.043 / 90 : 0.08 / 95 : 0.1315 / 99 : 0.70731
                                 mass_smaller_3 log_g                 75 : 0.0438 / 90 : 0.0775 / 95 : 0.10975 / 99 : 0.2165
KNN               PARSEC         Base           log_g                 75 : 0.0988 / 90 : 0.1666 / 95 : 0.24706 / 99 : 0.6304
                                 mass_smaller_3 log_g                   75 : 0.0876 / 90 : 0.134 / 95 : 0.1662 / 99 : 0.2294
linear_regression PARSEC         Base           log_g              75 : 1.20825 / 90 : 1.42198 / 95 : 1.52277 / 99 : 1.68722
                                 mass_smaller_3 log_g               75 : 0.20489 / 90 : 0.29739 / 95 : 0.3643 / 99 : 0.50017
mlp               PARSEC         Base           log_g              75 : 0.59017 / 90 : 0.78507 / 95 : 0.89144 / 99 : 1.05907
                                 mass_smaller_3 log_g              75 : 0.50636 / 90 : 0.64737 / 95 : 0.71943 / 99 : 0.86732
random_forest     PARSEC         Base           log_g              75 : 0.04114 / 90 : 0.08891 / 95 : 0.14966 / 99 : 0.67188
                                 mass_smaller_3 log_g              75 : 0.04189 / 90 : 0.07674 / 95 : 0.10107 / 99 : 0.17798
xgboost           PARSEC         Base           log_g              75 : 0.42278 / 90 : 0.62987 / 95 : 0.77118 / 99 : 0.98055
                                 mass_smaller_3 log_g              75 : 0.16865 / 90 : 0.26397 / 95 : 0.32656 / 99 : 0.45799

                                                                                time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           log_g              6.434222936630249
                                 mass_smaller_3 log_g             4.5170204639434814
KNN               PARSEC         Base           log_g              2.859384298324585
                                 mass_smaller_3 log_g              2.906430959701538
linear_regression PARSEC         Base           log_g             0.3583259582519531
                                 mass_smaller_3 log_g             0.2743659019470215
mlp               PARSEC         Base           log_g             116.13347673416138
                                 mass_smaller_3 log_g              87.95152354240417
random_forest     PARSEC         Base           log_g              70.70545029640198
                                 mass_smaller_3 log_g             43.329623222351074
xgboost           PARSEC         Base           log_g              6.729006052017212
                                 mass_smaller_3 log_g              5.382724046707153

Linear regression : 
- mass_smaller_3 : better results than Base on every metric

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

Random forest : 
- mass_smaller_3 : worse results than Base on every metric except MedAE and P75

XGBoost : 
- mass_smaller_3 : better/similar results to Base on every metric

MLP : 
- mass_smaller_3 : better results than Base on every metric

#### Conclusions on log_g

When filtering using mass_smaller_3, the results worsen for half the models and improves for the other half.

Since the results worsen for the best 3 models, it is not interesting to use this filtering.

#### Best models for the log_g parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

### Conclusion for every filtering

mass_smaller_3 filtering is only beneficial for the T_eff parameters but the difference is not that extreme.

We will use the Base filtering with Random forest, KNN and decision tree.