# Results comparison for MIST with fine-tuned models of model A partial

In this notebook, I will compare the results of the different fine tuned models (only the MIST dataset).

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_A_partial/fine_tuned_models"

## Getting the ranges for the values

In [ ]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                              ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol'], 
                              "PARSEC", rescale=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Comparison

| Parameter      | Base                                                   |
| -------------  | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       |
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   |
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   |
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   |
| R              | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 |

### Mass parameter

In [6]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["mass"],
                physical_models=["PARSEC"],)

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.9998659268257796,0.24%,0.046%,0.0%,0.9999329612117518,9.687%,75 : 0.0% / 90 : 0.043% / 95 : 0.238% / 99 : 1.126%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.9993570020279945,0.525%,0.156%,0.005%,0.9996801634761181,26.547%,75 : 0.093% / 90 : 0.407% / 95 : 0.789% / 99 : 2.266%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.999956085699885,0.137%,0.037%,0.002%,0.9999781338211671,7.979%,75 : 0.014% / 90 : 0.086% / 95 : 0.189% / 99 : 0.594%,670.4926252365112

Results for the label category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.9996325359083561,0.418%,0.097%,0.0%,0.9998162634256244,9.687%,75 : 0.007% / 90 : 0.152% / 95 : 0.498% / 99 : 2.086%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.998459614321629,0.855%,0.293%,0.053%,0.9992385948243597,26.547%,75 : 0.21% / 90 : 0.719% / 95 : 1.36% / 99 : 4.01%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,0.09 - 13.943,0.9999231735740294,0.191%,0.049%,0.005%,0.9999618104342513,7.979%,75 : 0.026% / 90 : 0.112% / 95 : 0.227% / 99 : 0.698%,670.4926252365112

Results for the label category with a value of 2.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,0.726 - 13.901,0.9999459944210803,0.187%,0.048%,0.0%,0.9999730942062753,4.372%,75 : 0.008% / 90 : 0.129% / 95 : 0.311% / 99 : 0.767%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,0.726 - 13.901,0.9990776247215951,0.773%,0.351%,0.099%,0.9995388450518422,9.535%,75 : 0.365% / 90 : 0.921% / 95 : 1.597% / 99 : 3.604%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,0.726 - 13.901,0.9999538131821172,0.173%,0.067%,0.014%,0.9999769065962484,4.054%,75 : 0.07% / 90 : 0.176% / 95 : 0.277% / 99 : 0.691%,670.4926252365112

Results for the label category with a value of 3.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,0.655 - 13.903,0.9999153817902754,0.16%,0.049%,0.0%,0.9999578793870033,2.438%,75 : 0.0% / 90 : 0.166% / 95 : 0.317% / 99 : 0.679%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,0.655 - 13.903,0.9997251086817364,0.29%,0.112%,0.023%,0.9998632050061758,8.362%,75 : 0.105% / 90 : 0.301% / 95 : 0.563% / 99 : 1.112%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,0.655 - 13.903,0.9999667736640507,0.101%,0.036%,0.003%,0.9999834859483046,2.144%,75 : 0.027% / 90 : 0.1% / 95 : 0.18% / 99 : 0.47%,670.4926252365112

Results for the label category with a value of 4.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,0.644 - 13.912,0.9999706129975968,0.068%,0.007%,0.0%,0.9999853151404752,2.171%,75 : 0.0% / 90 : 0.002% / 95 : 0.008% / 99 : 0.166%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,0.644 - 13.912,0.9999623067509636,0.077%,0.013%,0.0%,0.9999811573986328,5.671%,75 : 0.001% / 90 : 0.008% / 95 : 0.037% / 99 : 0.35%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,0.644 - 13.912,0.9999900512871255,0.04%,0.006%,0.0%,0.999995025638174,1.638%,75 : 0.001% / 90 : 0.006% / 95 : 0.013% / 99 : 0.161%,670.4926252365112

Results for the label category with a value of 5.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,1.892 - 13.29,0.9999220872630342,0.253%,0.062%,0.003%,0.9999611343306434,7.036%,75 : 0.009% / 90 : 0.053% / 95 : 0.421% / 99 : 1.255%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,1.892 - 13.29,0.9995593323334033,0.602%,0.232%,0.012%,0.9997840835767307,7.788%,75 : 0.201% / 90 : 0.643% / 95 : 1.185% / 99 : 2.97%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,1.892 - 13.29,0.9999712818896508,0.154%,0.058%,0.011%,0.9999858897856913,2.775%,75 : 0.044% / 90 : 0.162% / 95 : 0.288% / 99 : 0.701%,670.4926252365112

Results for the label category with a value of 6.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,mass,1.921 - 13.588,0.9996916587263293,0.53%,0.194%,0.0%,0.9998472822672069,6.814%,75 : 0.017% / 90 : 0.737% / 95 : 1.397% / 99 : 2.177%,6.220294952392578
KNN,PARSEC,mass_smaller_14,mass,1.921 - 13.588,0.9990715001226405,1.008%,0.677%,0.442%,0.9995374448157069,7.618%,75 : 0.942% / 90 : 1.521% / 95 : 2.162% / 99 : 3.546%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,mass,1.921 - 13.588,0.9998313062195359,0.424%,0.248%,0.082%,0.9999165238324409,2.549%,75 : 0.371% / 90 : 0.743% / 95 : 1.008% / 99 : 1.401%,670.4926252365112

### Radius parameter

In [8]:
compare_metrics(path, value_rounding=3, relative_values=True,
                output_parameters=["radius"],
                physical_models=["PARSEC"],)

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 2.8372727025023003,0.9998039660666189,0.224%,0.065%,0.0%,0.9999020058128616,8.849%,75 : 0.016% / 90 : 0.188% / 95 : 0.419% / 99 : 0.872%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 2.8372727025023003,0.9998614711765342,0.188%,0.082%,0.013%,0.9999307332769954,7.299%,75 : 0.101% / 90 : 0.241% / 95 : 0.353% / 99 : 0.677%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 2.8372727025023003,0.9999500232094234,0.113%,0.033%,0.006%,0.9999750156989765,5.023%,75 : 0.019% / 90 : 0.082% / 95 : 0.162% / 99 : 0.439%,670.4926252365112

Results for the label category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 1.1687920203141815,0.9996530610796055,0.318%,0.117%,0.0%,0.9998265636626478,7.024%,75 : 0.081% / 90 : 0.353% / 95 : 0.635% / 99 : 1.488%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 1.1687920203141815,0.9995123347937918,0.377%,0.232%,0.126%,0.9997569535603915,4.062%,75 : 0.323% / 90 : 0.603% / 95 : 0.82% / 99 : 1.353%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,-0.9763360818022064 - 1.1687920203141815,0.9999482757625959,0.123%,0.051%,0.012%,0.9999742405063983,4.622%,75 : 0.048% / 90 : 0.14% / 95 : 0.233% / 99 : 0.526%,670.4926252365112

Results for the label category with a value of 2.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,0.0199466816788423 - 2.458486763798206,0.999286726479723,0.593%,0.228%,0.0%,0.9996474507807832,13.838%,75 : 0.273% / 90 : 0.796% / 95 : 1.044% / 99 : 1.955%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,0.0199466816788423 - 2.458486763798206,0.9994831993642557,0.507%,0.261%,0.161%,0.9997645665627639,11.416%,75 : 0.317% / 90 : 0.54% / 95 : 0.74% / 99 : 1.854%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,0.0199466816788423 - 2.458486763798206,0.9998423625993466,0.282%,0.107%,0.027%,0.9999318885359478,7.123%,75 : 0.101% / 90 : 0.278% / 95 : 0.449% / 99 : 1.087%,670.4926252365112

Results for the label category with a value of 3.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,0.287801729930226 - 2.8372727025023003,0.999505935280926,0.41%,0.17%,0.0%,0.9997531913596872,6.777%,75 : 0.125% / 90 : 0.677% / 95 : 1.015% / 99 : 1.561%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,0.287801729930226 - 2.8372727025023003,0.9998043952109233,0.258%,0.156%,0.071%,0.999902225396814,2.705%,75 : 0.227% / 90 : 0.423% / 95 : 0.577% / 99 : 0.937%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,0.287801729930226 - 2.8372727025023003,0.9999389809557478,0.147%,0.067%,0.013%,0.9999695003729878,2.256%,75 : 0.06% / 90 : 0.212% / 95 : 0.326% / 99 : 0.634%,670.4926252365112

Results for the label category with a value of 4.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,0.7818989193511491 - 2.8272399995056454,0.9999392441509765,0.115%,0.021%,0.003%,0.9999696248543333,4.321%,75 : 0.013% / 90 : 0.021% / 95 : 0.04% / 99 : 0.473%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,0.7818989193511491 - 2.8272399995056454,0.9999834349370542,0.06%,0.019%,0.008%,0.9999917176844184,2.158%,75 : 0.017% / 90 : 0.025% / 95 : 0.056% / 99 : 0.282%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,0.7818989193511491 - 2.8272399995056454,0.9999895649618741,0.047%,0.014%,0.006%,0.9999947879853742,2.31%,75 : 0.013% / 90 : 0.021% / 95 : 0.038% / 99 : 0.201%,670.4926252365112

Results for the label category with a value of 5.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,0.8787515201730021 - 2.669967369908504,0.9993025809442532,0.713%,0.164%,0.018%,0.9996515952438585,18.03%,75 : 0.051% / 90 : 0.298% / 95 : 0.796% / 99 : 2.957%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,0.8787515201730021 - 2.669967369908504,0.9995052592465578,0.601%,0.214%,0.034%,0.9997539701838383,10.399%,75 : 0.203% / 90 : 0.514% / 95 : 0.827% / 99 : 2.92%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,0.8787515201730021 - 2.669967369908504,0.9996366377692679,0.52%,0.137%,0.026%,0.9998224015933328,10.695%,75 : 0.067% / 90 : 0.246% / 95 : 0.506% / 99 : 2.447%,670.4926252365112

Results for the label category with a value of 6.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,mass_smaller_14,radius,0.9630791606418272 - 2.7777891874348675,0.998337585740948,0.861%,0.33%,0.0%,0.9991705421038831,14.128%,75 : 0.345% / 90 : 1.019% / 95 : 1.584% / 99 : 3.726%,6.220294952392578
KNN,PARSEC,mass_smaller_14,radius,0.9630791606418272 - 2.7777891874348675,0.9990559620004439,0.674%,0.406%,0.277%,0.9995340753076349,9.221%,75 : 0.525% / 90 : 0.832% / 95 : 1.099% / 99 : 2.734%,9.992894172668457
random_forest,PARSEC,mass_smaller_14,radius,0.9630791606418272 - 2.7777891874348675,0.9993836491781928,0.56%,0.29%,0.086%,0.9996918425356217,6.382%,75 : 0.35% / 90 : 0.872% / 95 : 1.197% / 99 : 2.153%,670.4926252365112

Random forest is the best model from all the fine tuned ones