# Results comparison for MIST with fine-tuned models of model A partial

In this notebook, I will compare the results of the different fine tuned models (only the MIST dataset).

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path_default = pre_path + "results/model_A_partial/default_models"
path_fine_tuned = pre_path + "results/model_A_partial/fine_tuned_models"

## Getting the ranges for the values

In [ ]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                              ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol'], 
                              "PARSEC", rescale=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading MIST dataframe from MIST_reclassified_iso_full_data.csv file...

,log10_isochrone_age_yr,log_Teff,log_g,phase,metallicity,star_mass,log_R,log_L
0,5.0,3.486221,3.131342,-1.0,-0.25,0.100000,0.153402,-0.793667
1,5.0,3.487362,3.126808,-1.0,-0.25,0.102645,0.160326,-0.775254
2,5.0,3.489243,3.119367,-1.0,-0.25,0.107039,0.171785,-0.744810
3,5.0,3.491102,3.112165,-1.0,-0.25,0.111419,0.183099,-0.714749
4,5.0,3.492937,3.105143,-1.0,-0.25,0.115789,0.194305,-0.684996
...,...,...,...,...,...,...,...,...
1467117,10.3,4.402490,7.777159,6.0,0.50,0.532726,-1.806255,-1.047903
1467118,10.3,4.387132,7.783242,6.0,0.50,0.532730,-1.809295,-1.115415
1467119,10.3,4.371789,7.789130,6.0,0.50,0.532735,-1.812237,-1.182672
1467120,10.3,4.356480,7.794844,6.0,0.50,0.532741,-1.815091,-1.249617
1467121,10.3,4.341226,7.800376,6.0,0.50,0.532749,-1.817854,-1.316157

In [4]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'phase':[0, 2, 3], 'star_mass':("<", 30)})
print_all_uniques(phase_filtered_iso_df)

log10_isochrone_age_yr  : Range : 5.0 - 10.3, Mean : 8.2913, Median : 8.3

log_Teff  : Range : 3.34 - 5.3542, Mean : 3.9814, Median : 3.9163

log_g  : Range : -1.08 - 6.2434, Mean : 3.5356, Median : 3.9078

Values in phase column : 0.0, 2.0, 3.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, 0.0, 0.25, 0.5

star_mass  : Range : 0.1 - 29.9991, Mean : 5.0421, Median : 2.422

log_R  : Range : -1.0 - 3.1298, Mean : 0.6593, Median : 0.6146

log_L  : Range : -3.33 - 5.9763, Mean : 2.1988, Median : 2.3277

## Default vs fine-tuned

### Decision tree

In [3]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               0.09 - 13.943
                                            radius            -0.976 - 2.837

                                                              RVE   RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              1.0  0.034
                                            radius            1.0  0.009

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              0.006    0.0
                                            radius            0.003    0.0

                                                              CORR  MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               1.0   1.239
                                            radius             1.0   0.341

                                                                                                            Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass                       75 : 0.0 / 90 : 0.007 / 95 : 0.034 / 99 : 0.158
                                            radius             75 : 0.0006 / 90 : 0.00725 / 95 : 0.01618 / 99 : 0.0339

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              7.206
                                            radius            7.206

In [4]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_quantile"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               0.09 - 13.943
                                            radius            -0.976 - 2.837

                                                              RVE   RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              1.0  0.034
                                            radius            1.0  0.009

                                                                MAE  MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              0.006    0.0
                                            radius            0.003    0.0

                                                              CORR  MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass               1.0   1.343
                                            radius             1.0   0.337

                                                                                                            Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass                       75 : 0.0 / 90 : 0.007 / 95 : 0.034 / 99 : 0.156
                                            radius             75 : 0.0006 / 90 : 0.00729 / 95 : 0.01614 / 99 : 0.0337

                                                               time
model         physical_model filter         output_parameter
decision_tree PARSEC         scale_quantile mass              7.506
                                            radius            7.506

Slightly worse results after fine-tuning

### KNN

In [10]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_standard"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass               0.09 - 13.943  0.999
                                    radius            -0.976 - 2.837  1.000

                                                       RMSE    MAE  MedAE  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass              0.080  0.025  0.001
                                    radius            0.008  0.004  0.001

                                                      CORR  MAX_ER  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass               1.0   1.672
                                    radius             1.0   0.208

                                                                                                      Percentiles  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass                   75 : 0.0152 / 90 : 0.0668 / 95 : 0.1316 / 99 : 0.3768
                                    radius             75 : 0.00518 / 90 : 0.01139 / 95 : 0.01614 / 99 : 0.02878

                                                       time
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass              4.524
                                    radius            4.524

In [11]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_standard"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range    RVE  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass               0.09 - 13.943  0.999
                                    radius            -0.976 - 2.837  1.000

                                                       RMSE    MAE  MedAE  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass              0.068  0.020  0.001
                                    radius            0.007  0.003  0.001

                                                      CORR  MAX_ER  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass               1.0    1.71
                                    radius             1.0    0.21

                                                                                                      Percentiles  \
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass               75 : 0.01141 / 90 : 0.05086 / 95 : 0.10294 / 99 : 0.30284
                                    radius             75 : 0.00402 / 90 : 0.00943 / 95 : 0.01391 / 99 : 0.02581

                                                       time
model physical_model filter         output_parameter
KNN   PARSEC         scale_standard mass              4.815
                                    radius            4.815

Slight improvement after fine-tuning

### Random forest

In [12]:
compare_metrics(path_default, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range  RVE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               0.09 - 13.943  1.0
                                    radius            -0.976 - 2.837  1.0

                                                       RMSE    MAE  MedAE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              0.021  0.005    0.0
                                    radius            0.005  0.001    0.0

                                                      CORR  MAX_ER  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               1.0   0.762
                                    radius             1.0   0.263

                                                                                                      Percentiles  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               75 : 0.00106 / 90 : 0.01192 / 95 : 0.02784 / 99 : 0.09206
                                    radius             75 : 0.00056 / 90 : 0.00364 / 95 : 0.00759 / 99 : 0.01926

                                                         time
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              100.594
                                    radius            100.594

In [13]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass", "radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base"],
                categories=["Global"])

Results for the Global category with a value of 1.0

                                                         value range  RVE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               0.09 - 13.943  1.0
                                    radius            -0.976 - 2.837  1.0

                                                       RMSE    MAE  MedAE  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              0.019  0.005    0.0
                                    radius            0.004  0.001    0.0

                                                      CORR  MAX_ER  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               1.0   1.149
                                    radius             1.0   0.192

                                                                                                     Percentiles  \
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass               75 : 0.00208 / 90 : 0.01218 / 95 : 0.02662 / 99 : 0.0834
                                    radius              75 : 0.00075 / 90 : 0.0032 / 95 : 0.0063 / 99 : 0.01688

                                                        time
model         physical_model filter output_parameter
random_forest PARSEC         Base   mass              153.88
                                    radius            153.88

Better MAX_ER for radius but worse for mass. better until the 99th percentile

## Comparison between fine tuned models

| Parameter      | Base                                                   |
| -------------  | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       |
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   |
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   |
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   |
| R              | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 |

### Mass parameter

In [15]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_standard"],
                categories=["Global"])

compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_quantile"],
                categories=["Global"])

compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["mass"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base"],
                categories=["Global"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,PARSEC,scale_standard,mass,0.09 - 13.943,0.999,0.068,0.02,0.001,1.0,1.71,75 : 0.01141 / 90 : 0.05086 / 95 : 0.10294 / 99 : 0.30284,4.815

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,scale_quantile,mass,0.09 - 13.943,1.0,0.038,0.009,0.0,1.0,1.471,75 : 0.001 / 90 : 0.021 / 95 : 0.0492 / 99 : 0.17067,7.403

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
random_forest,PARSEC,Base,mass,0.09 - 13.943,1.0,0.019,0.005,0.0,1.0,1.149,75 : 0.00208 / 90 : 0.01218 / 95 : 0.02662 / 99 : 0.0834,153.88

### Radius parameter

In [16]:
compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["KNN"],
                data_filters=["scale_standard"],
                categories=["Global"])

compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["decision_tree"],
                data_filters=["scale_quantile"],
                categories=["Global"])

compare_metrics(path_fine_tuned, value_rounding=3, relative_values=False,
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                model_names=["random_forest"],
                data_filters=["Base"],
                categories=["Global"])

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
KNN,PARSEC,scale_standard,radius,-0.976 - 2.837,1.0,0.007,0.003,0.001,1.0,0.21,75 : 0.00402 / 90 : 0.00943 / 95 : 0.01391 / 99 : 0.02581,4.815

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
decision_tree,PARSEC,scale_quantile,radius,-0.976 - 2.837,0.999,0.015,0.004,0.0,1.0,0.374,75 : 0.00162 / 90 : 0.01253 / 95 : 0.02509 / 99 : 0.06851,7.403

Results for the Global category with a value of 1.0

,,,,value range,RVE,RMSE,MAE,MedAE,CORR,MAX_ER,Percentiles,time
model,physical_model,filter,output_parameter,,,,,,,,,
random_forest,PARSEC,Base,radius,-0.976 - 2.837,1.0,0.004,0.001,0.0,1.0,0.192,75 : 0.00075 / 90 : 0.0032 / 95 : 0.0063 / 99 : 0.01688,153.88

Random forest is the best model from all the fine tuned ones