# Results comparison for PARSEC filtering of model A partial

In this notebook, I will compare the results of the different models relative to how the data was filtered (only the PARSEC dataset).

I will first look at how the filter on one value affected the other (if it didn't affect it, I will not write it) and then see how it affected the results of each model.

This part was done after the one on MIST so I will only try the filtering which made a positive difference.

In [1]:
from ML.utils.utils import *
from physics.Iso_data_handler import Iso_data_handler
from ML.utils.Data_preparator import Data_preparator

In [2]:
pre_path = "../../../../../../"
path = pre_path + "results/model_A_partial/default_models"

In [3]:
compare_metrics(path, 
                output_parameters=["mass"],
                model_names=["decision_tree"],
                physical_models=["PARSEC"])

Results for the Global category with a value of 1.0

                                                                value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.09 - 13.943
                             mass_smaller_3 mass               0.09 - 2.999

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9998645662248727
                             mass_smaller_3 mass              0.9995097172639185

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.03334990805479929
                             mass_smaller_3 mass              0.012309382125473058

                                                                               MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.00636864266742792
                             mass_smaller_3 mass              0.002447377814813581

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999322808272706
                             mass_smaller_3 mass              0.9997548436797105

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               1.633000000000001
                             mass_smaller_3 mass              0.3540000000000001

                                                                                                    Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.0 / 90 : 0.006 / 95 : 0.033 / 99 : 0.155
                             mass_smaller_3 mass               75 : 0.0 / 90 : 0.001 / 95 : 0.015 / 99 : 0.055

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 1.0

                                                                value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.09 - 13.943
                             mass_smaller_3 mass               0.09 - 2.999

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9996254161385038
                             mass_smaller_3 mass              0.9996015588887927

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.05840340529668738
                             mass_smaller_3 mass              0.012820296118616454

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.013469273504042142
                             mass_smaller_3 mass              0.0035584884648051022

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9998127048400395
                             mass_smaller_3 mass              0.9998008347548047

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               1.633000000000001
                             mass_smaller_3 mass              0.3129999999999997

                                                                                                      Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.001 / 90 : 0.022 / 95 : 0.068 / 99 : 0.294
                             mass_smaller_3 mass                75 : 0.001 / 90 : 0.01 / 95 : 0.021 / 99 : 0.059

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 2.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.726 - 13.901
                             mass_smaller_3 mass               0.726 - 2.996

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999459955708547
                             mass_smaller_3 mass              0.9997295898528473

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.024641225603144138
                             mass_smaller_3 mass              0.010414439165456313

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.006320830750155019
                             mass_smaller_3 mass              0.0028242811501597623

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999730941677303
                             mass_smaller_3 mass               0.999864795213471

                                                                          MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.6719999999999988
                             mass_smaller_3 mass                           0.129

                                                                                                      Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.001 / 90 : 0.017 / 95 : 0.042 / 99 : 0.101
                             mass_smaller_3 mass                 75 : 0.0 / 90 : 0.004 / 95 : 0.019 / 99 : 0.044

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 3.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.655 - 13.903
                             mass_smaller_3 mass               0.655 - 2.999

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999157323462134
                             mass_smaller_3 mass                0.99861327985488

                                                                             RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.02111697760575715
                             mass_smaller_3 mass              0.01755050494298746

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.006363201975499179
                             mass_smaller_3 mass              0.0055081029656236956

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999580761223028
                             mass_smaller_3 mass              0.9993132163897192

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.29800000000000004
                             mass_smaller_3 mass               0.3540000000000001

                                                                                                      Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass                  75 : 0.0 / 90 : 0.021 / 95 : 0.041 / 99 : 0.09
                             mass_smaller_3 mass               75 : 0.0 / 90 : 0.019 / 95 : 0.039 / 99 : 0.07298

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 4.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.644 - 13.912
                             mass_smaller_3 mass               0.644 - 2.999

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.999970695956602
                             mass_smaller_3 mass              0.9998373143257983

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.009049336314518173
                             mass_smaller_3 mass              0.005218977188543175

                                                                                 MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0009132218865141464
                             mass_smaller_3 mass              0.00033790644590227324

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999853547030013
                             mass_smaller_3 mass              0.9999187871020149

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.28800000000000026
                             mass_smaller_3 mass              0.30100000000000016

                                                                                                      Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.0 / 90 : 0.00029 / 95 : 0.001 / 99 : 0.021
                             mass_smaller_3 mass                   75 : 0.0 / 90 : 0.0 / 95 : 0.001 / 99 : 0.003

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 5.0

                                                                value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              1.892 - 13.29
                             mass_smaller_3 mass              1.892 - 2.999

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999254209050206
                             mass_smaller_3 mass              0.9986650648091511

                                                                              RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.02821057356190365
                             mass_smaller_3 mass              0.010391487843661796

                                                                                MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.006970776455293335
                             mass_smaller_3 mass              0.0023298176225005534

                                                                               MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              1.7763568394002505e-15
                             mass_smaller_3 mass               0.0009999999999998899

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9999627958098751
                             mass_smaller_3 mass              0.9993342118380482

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.47300000000000075
                             mass_smaller_3 mass               0.2549999999999999

                                                                                                       Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.001 / 90 : 0.005 / 95 : 0.047 / 99 : 0.1443
                             mass_smaller_3 mass                75 : 0.002 / 90 : 0.003 / 95 : 0.005 / 99 : 0.046

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

Results for the label category with a value of 6.0

                                                                 value range  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              1.921 - 13.588
                             mass_smaller_3 mass               1.921 - 2.995

                                                                             RVE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9996933141748274
                             mass_smaller_3 mass              0.9657495404723373

                                                                             RMSE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.06172729882855662
                             mass_smaller_3 mass              0.06332145637623032

                                                                              MAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.02262963995440585
                             mass_smaller_3 mass              0.02487310979618674

                                                             MedAE  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.0
                             mass_smaller_3 mass               0.0

                                                                            CORR  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              0.9998480455340994
                             mass_smaller_3 mass              0.9834731625011262

                                                                           MAX_ER  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               0.5660000000000007
                             mass_smaller_3 mass              0.29700000000000015

                                                                                                          Percentiles  \
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass               75 : 0.002 / 90 : 0.084 / 95 : 0.16465 / 99 : 0.26366
                             mass_smaller_3 mass                   75 : 0.001 / 90 : 0.156 / 95 : 0.177 / 99 : 0.196

                                                                            time
model         physical_model filter         output_parameter
decision_tree PARSEC         Base           mass              6.6589062213897705
                             mass_smaller_3 mass               5.519447326660156

In [4]:
compare_metrics(path, value_rounding=6,
                output_parameters=["mass", "radius"], # output_parameters=["radius"],
                physical_models=["PARSEC"],
                data_filters=["Base"])

Results for the Global category with a value of 1.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass               -13.853000
                                        radius              -3.813609
KNN               PARSEC         Base   mass               -13.853000
                                        radius              -3.813609
linear_regression PARSEC         Base   mass               -13.853000
                                        radius              -3.813609
mlp               PARSEC         Base   mass               -13.853000
                                        radius              -3.813609
random_forest     PARSEC         Base   mass               -13.853000
                                        radius              -3.813609
xgboost           PARSEC         Base   mass               -13.853000
                                        radius              -3.813609

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999865  0.033350
                                        radius            0.999803  0.008555
KNN               PARSEC         Base   mass              0.998861  0.096719
                                        radius            0.999829  0.007986
linear_regression PARSEC         Base   mass              0.824519  1.200345
                                        radius            0.993519  0.049086
mlp               PARSEC         Base   mass              0.998353  0.116597
                                        radius            0.999262  0.016770
random_forest     PARSEC         Base   mass              0.999948  0.020633
                                        radius            0.999933  0.004985
xgboost           PARSEC         Base   mass              0.999713  0.048516
                                        radius            0.999779  0.009065

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.006369  0.000000
                                        radius            0.002483  0.000000
KNN               PARSEC         Base   mass              0.028863  0.000800
                                        radius            0.003651  0.000693
linear_regression PARSEC         Base   mass              0.873056  0.656142
                                        radius            0.033081  0.022262
mlp               PARSEC         Base   mass              0.065627  0.040685
                                        radius            0.012107  0.009008
random_forest     PARSEC         Base   mass              0.005153  0.000020
                                        radius            0.001396  0.000155
xgboost           PARSEC         Base   mass              0.022327  0.008370
                                        radius            0.005657  0.003274

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999932  1.633000
                                        radius            0.999902  0.337378
KNN               PARSEC         Base   mass              0.999434  5.044600
                                        radius            0.999914  0.287150
linear_regression PARSEC         Base   mass              0.908030  5.809023
                                        radius            0.996754  0.350667
mlp               PARSEC         Base   mass              0.999196  2.134768
                                        radius            0.999637  0.243754
random_forest     PARSEC         Base   mass              0.999974  0.762130
                                        radius            0.999967  0.263343
xgboost           PARSEC         Base   mass              0.999857  1.469593
                                        radius            0.999889  0.176007

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                         75 : 0.0 / 90 : 0.006 / 95 : 0.033 / 99 : 0.155
                                        radius             75 : 0.00058 / 90 : 0.00718 / 95 : 0.01609 / 99 : 0.03359
KNN               PARSEC         Base   mass                      75 : 0.0186 / 90 : 0.077 / 95 : 0.14 / 99 : 0.4044
                                        radius              75 : 0.00479 / 90 : 0.01039 / 95 : 0.01472 / 99 : 0.0293
linear_regression PARSEC         Base   mass               75 : 1.09438 / 90 : 1.88298 / 95 : 2.55432 / 99 : 4.24433
                                        radius               75 : 0.042 / 90 : 0.07847 / 95 : 0.10191 / 99 : 0.18132
mlp               PARSEC         Base   mass               75 : 0.06948 / 90 : 0.13224 / 95 : 0.22434 / 99 : 0.50433
                                        radius             75 : 0.01608 / 90 : 0.02669 / 95 : 0.03443 / 99 : 0.05079
random_forest     PARSEC         Base   mass               75 : 0.00106 / 90 : 0.01192 / 95 : 0.02784 / 99 : 0.09206
                                        radius             75 : 0.00056 / 90 : 0.00364 / 95 : 0.00759 / 99 : 0.01926
xgboost           PARSEC         Base   mass                75 : 0.02349 / 90 : 0.05388 / 95 : 0.08728 / 99 : 0.2091
                                        radius             75 : 0.00752 / 90 : 0.01364 / 95 : 0.01837 / 99 : 0.03161

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 1.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass               -13.853000
                                        radius              -2.145128
KNN               PARSEC         Base   mass               -13.853000
                                        radius              -2.145128
linear_regression PARSEC         Base   mass               -13.853000
                                        radius              -2.145128
mlp               PARSEC         Base   mass               -13.853000
                                        radius              -2.145128
random_forest     PARSEC         Base   mass               -13.853000
                                        radius              -2.145128
xgboost           PARSEC         Base   mass               -13.853000
                                        radius              -2.145128

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999625  0.058403
                                        radius            0.999651  0.006837
KNN               PARSEC         Base   mass              0.997018  0.164775
                                        radius            0.999190  0.010436
linear_regression PARSEC         Base   mass              0.714080  1.626071
                                        radius            0.948411  0.083286
mlp               PARSEC         Base   mass              0.998750  0.107277
                                        radius            0.998165  0.016797
random_forest     PARSEC         Base   mass              0.999885  0.032422
                                        radius            0.999920  0.003279
xgboost           PARSEC         Base   mass              0.999135  0.088755
                                        radius            0.999250  0.010026

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.013469  0.000000
                                        radius            0.002510  0.000000
KNN               PARSEC         Base   mass              0.056744  0.011000
                                        radius            0.006518  0.004031
linear_regression PARSEC         Base   mass              1.356202  1.215152
                                        radius            0.063475  0.053155
mlp               PARSEC         Base   mass              0.061147  0.038194
                                        radius            0.012590  0.009689
random_forest     PARSEC         Base   mass              0.008655  0.000260
                                        radius            0.001306  0.000181
xgboost           PARSEC         Base   mass              0.046886  0.020626
                                        radius            0.006852  0.004714

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999813  1.633000
                                        radius            0.999826  0.119186
KNN               PARSEC         Base   mass              0.998527  5.044600
                                        radius            0.999597  0.136909
linear_regression PARSEC         Base   mass              0.877384  5.809023
                                        radius            0.973870  0.350667
mlp               PARSEC         Base   mass              0.999380  1.475880
                                        radius            0.999119  0.156163
random_forest     PARSEC         Base   mass              0.999942  0.762130
                                        radius            0.999960  0.070766
xgboost           PARSEC         Base   mass              0.999568  1.469593
                                        radius            0.999625  0.088963

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                       75 : 0.001 / 90 : 0.022 / 95 : 0.068 / 99 : 0.294
                                        radius             75 : 0.00173 / 90 : 0.00758 / 95 : 0.01356 / 99 : 0.03205
KNN               PARSEC         Base   mass                  75 : 0.0436 / 90 : 0.1408 / 95 : 0.26435 / 99 : 0.7288
                                        radius             75 : 0.00911 / 90 : 0.01562 / 95 : 0.02098 / 99 : 0.03851
linear_regression PARSEC         Base   mass               75 : 1.92099 / 90 : 2.50743 / 95 : 2.94777 / 99 : 4.13453
                                        radius                75 : 0.08971 / 90 : 0.11906 / 95 : 0.168 / 99 : 0.2684
mlp               PARSEC         Base   mass                75 : 0.06655 / 90 : 0.1243 / 95 : 0.19734 / 99 : 0.46885
                                        radius              75 : 0.01747 / 90 : 0.02666 / 95 : 0.03381 / 99 : 0.0517
random_forest     PARSEC         Base   mass               75 : 0.00335 / 90 : 0.01908 / 95 : 0.04398 / 99 : 0.14915
                                        radius              75 : 0.00108 / 90 : 0.0039 / 95 : 0.00676 / 99 : 0.01445
xgboost           PARSEC         Base   mass               75 : 0.05201 / 90 : 0.11997 / 95 : 0.18982 / 99 : 0.37039
                                        radius             75 : 0.00918 / 90 : 0.01517 / 95 : 0.02011 / 99 : 0.03502

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 2.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                -13.17500
                                        radius               -2.43854
KNN               PARSEC         Base   mass                -13.17500
                                        radius               -2.43854
linear_regression PARSEC         Base   mass                -13.17500
                                        radius               -2.43854
mlp               PARSEC         Base   mass                -13.17500
                                        radius               -2.43854
random_forest     PARSEC         Base   mass                -13.17500
                                        radius               -2.43854
xgboost           PARSEC         Base   mass                -13.17500
                                        radius               -2.43854

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999946  0.024641
                                        radius            0.999309  0.014232
KNN               PARSEC         Base   mass              0.998659  0.122870
                                        radius            0.999506  0.012077
linear_regression PARSEC         Base   mass              0.817099  1.456807
                                        radius            0.997770  0.038904
mlp               PARSEC         Base   mass              0.996562  0.207934
                                        radius            0.998691  0.019628
random_forest     PARSEC         Base   mass              0.999971  0.017959
                                        radius            0.999767  0.008291
xgboost           PARSEC         Base   mass              0.999888  0.036123
                                        radius            0.999440  0.012850

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.006321  0.000000
                                        radius            0.005531  0.000000
KNN               PARSEC         Base   mass              0.057315  0.019000
                                        radius            0.006557  0.004362
linear_regression PARSEC         Base   mass              1.080739  0.878468
                                        radius            0.030591  0.025143
mlp               PARSEC         Base   mass              0.121307  0.058414
                                        radius            0.015367  0.012451
random_forest     PARSEC         Base   mass              0.006954  0.000580
                                        radius            0.002824  0.000449
xgboost           PARSEC         Base   mass              0.023997  0.015143
                                        radius            0.009513  0.007497

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999973  0.672000
                                        radius            0.999658  0.337378
KNN               PARSEC         Base   mass              0.999335  1.390200
                                        radius            0.999768  0.287150
linear_regression PARSEC         Base   mass              0.910516  5.531745
                                        radius            0.999102  0.115892
mlp               PARSEC         Base   mass              0.998860  2.134768
                                        radius            0.999372  0.089752
random_forest     PARSEC         Base   mass              0.999986  0.565460
                                        radius            0.999888  0.263343
xgboost           PARSEC         Base   mass              0.999947  0.320078
                                        radius            0.999727  0.153522

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                       75 : 0.001 / 90 : 0.017 / 95 : 0.042 / 99 : 0.101
                                        radius             75 : 0.00665 / 90 : 0.01939 / 95 : 0.02552 / 99 : 0.04732
KNN               PARSEC         Base   mass                75 : 0.0628 / 90 : 0.14326 / 95 : 0.24146 / 99 : 0.56873
                                        radius             75 : 0.00805 / 90 : 0.01282 / 95 : 0.01738 / 99 : 0.04106
linear_regression PARSEC         Base   mass                75 : 1.18462 / 90 : 2.15073 / 95 : 3.42736 / 99 : 4.8223
                                        radius             75 : 0.04435 / 90 : 0.06666 / 95 : 0.07915 / 99 : 0.09843
mlp               PARSEC         Base   mass               75 : 0.13817 / 90 : 0.33275 / 95 : 0.46247 / 99 : 0.79147
                                        radius              75 : 0.02194 / 90 : 0.03285 / 95 : 0.0398 / 99 : 0.05137
random_forest     PARSEC         Base   mass                  75 : 0.0067 / 90 : 0.02156 / 95 : 0.034 / 99 : 0.06874
                                        radius             75 : 0.00272 / 90 : 0.00772 / 95 : 0.01204 / 99 : 0.02904
xgboost           PARSEC         Base   mass               75 : 0.03125 / 90 : 0.05624 / 95 : 0.07732 / 99 : 0.12994
                                        radius              75 : 0.01319 / 90 : 0.0197 / 95 : 0.02477 / 99 : 0.03776

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 3.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass               -13.248000
                                        radius              -2.549471
KNN               PARSEC         Base   mass               -13.248000
                                        radius              -2.549471
linear_regression PARSEC         Base   mass               -13.248000
                                        radius              -2.549471
mlp               PARSEC         Base   mass               -13.248000
                                        radius              -2.549471
random_forest     PARSEC         Base   mass               -13.248000
                                        radius              -2.549471
xgboost           PARSEC         Base   mass               -13.248000
                                        radius              -2.549471

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999916  0.021117
                                        radius            0.999490  0.010605
KNN               PARSEC         Base   mass              0.999517  0.050911
                                        radius            0.999785  0.006897
linear_regression PARSEC         Base   mass              0.811871  1.028619
                                        radius            0.991539  0.043567
mlp               PARSEC         Base   mass              0.997851  0.110558
                                        radius            0.998628  0.019488
random_forest     PARSEC         Base   mass              0.999961  0.014445
                                        radius            0.999861  0.005554
xgboost           PARSEC         Base   mass              0.999917  0.021505
                                        radius            0.999550  0.009974

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.006363  0.000000
                                        radius            0.004374  0.000000
KNN               PARSEC         Base   mass              0.019783  0.004200
                                        radius            0.004363  0.002251
linear_regression PARSEC         Base   mass              0.798285  0.725670
                                        radius            0.030996  0.019345
mlp               PARSEC         Base   mass              0.061172  0.041368
                                        radius            0.015286  0.012386
random_forest     PARSEC         Base   mass              0.005361  0.000110
                                        radius            0.002267  0.000271
xgboost           PARSEC         Base   mass              0.013999  0.008305
                                        radius            0.007081  0.005081

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999958  0.298000
                                        radius            0.999746  0.200094
KNN               PARSEC         Base   mass              0.999760  1.002400
                                        radius            0.999892  0.067436
linear_regression PARSEC         Base   mass              0.901331  5.531586
                                        radius            0.997057  0.169754
mlp               PARSEC         Base   mass              0.999093  1.655869
                                        radius            0.999365  0.078669
random_forest     PARSEC         Base   mass              0.999981  0.208600
                                        radius            0.999930  0.114264
xgboost           PARSEC         Base   mass              0.999964  0.193928
                                        radius            0.999775  0.104068

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                          75 : 0.0 / 90 : 0.021 / 95 : 0.041 / 99 : 0.09
                                        radius             75 : 0.00313 / 90 : 0.01749 / 95 : 0.02603 / 99 : 0.04039
KNN               PARSEC         Base   mass                  75 : 0.0184 / 90 : 0.0568 / 95 : 0.0952 / 99 : 0.19975
                                        radius             75 : 0.00643 / 90 : 0.01145 / 95 : 0.01513 / 99 : 0.02357
linear_regression PARSEC         Base   mass               75 : 1.06071 / 90 : 1.40396 / 95 : 1.71243 / 99 : 3.86906
                                        radius             75 : 0.04228 / 90 : 0.07698 / 95 : 0.09991 / 99 : 0.13118
mlp               PARSEC         Base   mass                75 : 0.07073 / 90 : 0.11101 / 95 : 0.1669 / 99 : 0.47099
                                        radius             75 : 0.02187 / 90 : 0.03281 / 95 : 0.03944 / 99 : 0.05118
random_forest     PARSEC         Base   mass               75 : 0.00348 / 90 : 0.01752 / 95 : 0.02849 / 99 : 0.06704
                                        radius               75 : 0.00178 / 90 : 0.0075 / 95 : 0.01174 / 99 : 0.0229
xgboost           PARSEC         Base   mass               75 : 0.01736 / 90 : 0.03379 / 95 : 0.04823 / 99 : 0.07899
                                        radius              75 : 0.00985 / 90 : 0.0159 / 95 : 0.02011 / 99 : 0.03105

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 4.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass               -13.268000
                                        radius              -2.045341
KNN               PARSEC         Base   mass               -13.268000
                                        radius              -2.045341
linear_regression PARSEC         Base   mass               -13.268000
                                        radius              -2.045341
mlp               PARSEC         Base   mass               -13.268000
                                        radius              -2.045341
random_forest     PARSEC         Base   mass               -13.268000
                                        radius              -2.045341
xgboost           PARSEC         Base   mass               -13.268000
                                        radius              -2.045341

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999971  0.009049
                                        radius            0.999941  0.002317
KNN               PARSEC         Base   mass              0.999930  0.013994
                                        radius            0.999977  0.001445
linear_regression PARSEC         Base   mass              0.867386  0.624989
                                        radius            0.995110  0.023066
mlp               PARSEC         Base   mass              0.999370  0.049922
                                        radius            0.998980  0.011435
random_forest     PARSEC         Base   mass              0.999987  0.005918
                                        radius            0.999986  0.001143
xgboost           PARSEC         Base   mass              0.999946  0.012407
                                        radius            0.999825  0.003975

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.000913  0.000000
                                        radius            0.000415  0.000053
KNN               PARSEC         Base   mass              0.002426  0.000000
                                        radius            0.000483  0.000167
linear_regression PARSEC         Base   mass              0.482855  0.436613
                                        radius            0.018915  0.016702
mlp               PARSEC         Base   mass              0.038838  0.034466
                                        radius            0.008497  0.006984
random_forest     PARSEC         Base   mass              0.000780  0.000000
                                        radius            0.000275  0.000079
xgboost           PARSEC         Base   mass              0.007319  0.003980
                                        radius            0.002574  0.001669

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999985  0.288000
                                        radius            0.999970  0.097641
KNN               PARSEC         Base   mass              0.999965  0.767600
                                        radius            0.999988  0.040197
linear_regression PARSEC         Base   mass              0.931643  5.210986
                                        radius            0.997902  0.072218
mlp               PARSEC         Base   mass              0.999726  1.029266
                                        radius            0.999514  0.075459
random_forest     PARSEC         Base   mass              0.999994  0.185620
                                        radius            0.999993  0.046870
xgboost           PARSEC         Base   mass              0.999973  0.144924
                                        radius            0.999913  0.050582

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                       75 : 0.0 / 90 : 0.00029 / 95 : 0.001 / 99 : 0.021
                                        radius              75 : 0.00027 / 90 : 0.00042 / 95 : 0.0008 / 99 : 0.00947
KNN               PARSEC         Base   mass                    75 : 0.0004 / 90 : 0.0012 / 95 : 0.008 / 99 : 0.0614
                                        radius             75 : 0.00034 / 90 : 0.00072 / 95 : 0.00169 / 99 : 0.00741
linear_regression PARSEC         Base   mass                75 : 0.65434 / 90 : 0.83563 / 95 : 1.00776 / 99 : 1.7564
                                        radius               75 : 0.028 / 90 : 0.03842 / 95 : 0.04386 / 99 : 0.05087
mlp               PARSEC         Base   mass               75 : 0.05198 / 90 : 0.07234 / 95 : 0.08906 / 99 : 0.14161
                                        radius             75 : 0.01132 / 90 : 0.01622 / 95 : 0.02247 / 99 : 0.03948
random_forest     PARSEC         Base   mass                   75 : 3e-05 / 90 : 0.00052 / 95 : 0.001 / 99 : 0.02242
                                        radius             75 : 0.00023 / 90 : 0.00039 / 95 : 0.00062 / 99 : 0.00506
xgboost           PARSEC         Base   mass                75 : 0.0084 / 90 : 0.01727 / 95 : 0.02663 / 99 : 0.05132
                                        radius               75 : 0.00324 / 90 : 0.00571 / 95 : 0.0081 / 99 : 0.0149

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 5.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass               -11.398000
                                        radius              -1.791216
KNN               PARSEC         Base   mass               -11.398000
                                        radius              -1.791216
linear_regression PARSEC         Base   mass               -11.398000
                                        radius              -1.791216
mlp               PARSEC         Base   mass               -11.398000
                                        radius              -1.791216
random_forest     PARSEC         Base   mass               -11.398000
                                        radius              -1.791216
xgboost           PARSEC         Base   mass               -11.398000
                                        radius              -1.791216

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999925  0.028211
                                        radius            0.999301  0.012790
KNN               PARSEC         Base   mass              0.999257  0.089024
                                        radius            0.999409  0.011791
linear_regression PARSEC         Base   mass              0.770933  1.571206
                                        radius            0.995020  0.046608
mlp               PARSEC         Base   mass              0.997985  0.161429
                                        radius            0.997415  0.024693
random_forest     PARSEC         Base   mass              0.999970  0.017908
                                        radius            0.999646  0.009147
xgboost           PARSEC         Base   mass              0.999845  0.040712
                                        radius            0.999230  0.013566

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.006971  0.000000
                                        radius            0.002973  0.000317
KNN               PARSEC         Base   mass              0.035878  0.002200
                                        radius            0.004346  0.000888
linear_regression PARSEC         Base   mass              1.179948  0.810099
                                        radius            0.032794  0.027888
mlp               PARSEC         Base   mass              0.112139  0.073580
                                        radius            0.015297  0.010592
random_forest     PARSEC         Base   mass              0.005831  0.000790
                                        radius            0.002224  0.000317
xgboost           PARSEC         Base   mass              0.027355  0.019801
                                        radius            0.007981  0.005328

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999963  0.473000
                                        radius            0.999651  0.322955
KNN               PARSEC         Base   mass              0.999632  1.081000
                                        radius            0.999706  0.190430
linear_regression PARSEC         Base   mass              0.952132  5.145376
                                        radius            0.997510  0.287674
mlp               PARSEC         Base   mass              0.999100  0.934454
                                        radius            0.998708  0.243754
random_forest     PARSEC         Base   mass              0.999985  0.374280
                                        radius            0.999824  0.189062
xgboost           PARSEC         Base   mass              0.999929  0.404971
                                        radius            0.999616  0.176007

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                      75 : 0.001 / 90 : 0.005 / 95 : 0.047 / 99 : 0.1443
                                        radius             75 : 0.00091 / 90 : 0.00525 / 95 : 0.01429 / 99 : 0.05224
KNN               PARSEC         Base   mass                    75 : 0.033 / 90 : 0.1046 / 95 : 0.1826 / 99 : 0.4121
                                        radius             75 : 0.00428 / 90 : 0.00969 / 95 : 0.01548 / 99 : 0.06408
linear_regression PARSEC         Base   mass               75 : 1.22962 / 90 : 2.86674 / 95 : 3.83857 / 99 : 4.78891
                                        radius             75 : 0.04486 / 90 : 0.05235 / 95 : 0.08853 / 99 : 0.18383
mlp               PARSEC         Base   mass                75 : 0.14744 / 90 : 0.26166 / 95 : 0.3546 / 99 : 0.56036
                                        radius             75 : 0.01907 / 90 : 0.03041 / 95 : 0.04039 / 99 : 0.10363
random_forest     PARSEC         Base   mass               75 : 0.00262 / 90 : 0.01574 / 95 : 0.03219 / 99 : 0.08003
                                        radius             75 : 0.00084 / 90 : 0.00398 / 95 : 0.00949 / 99 : 0.04178
xgboost           PARSEC         Base   mass                75 : 0.03651 / 90 : 0.05512 / 95 : 0.07148 / 99 : 0.1565
                                        radius              75 : 0.00979 / 90 : 0.0157 / 95 : 0.02181 / 99 : 0.05548

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

Results for the label category with a value of 6.0

                                                          value range  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                -11.66700
                                        radius               -1.81471
KNN               PARSEC         Base   mass                -11.66700
                                        radius               -1.81471
linear_regression PARSEC         Base   mass                -11.66700
                                        radius               -1.81471
mlp               PARSEC         Base   mass                -11.66700
                                        radius               -1.81471
random_forest     PARSEC         Base   mass                -11.66700
                                        radius               -1.81471
xgboost           PARSEC         Base   mass                -11.66700
                                        radius               -1.81471

                                                               RVE      RMSE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999693  0.061727
                                        radius            0.998273  0.015943
KNN               PARSEC         Base   mass              0.998432  0.145122
                                        radius            0.998846  0.013376
linear_regression PARSEC         Base   mass              0.691928  1.955836
                                        radius            0.993820  0.037482
mlp               PARSEC         Base   mass              0.996778  0.214841
                                        radius            0.996490  0.024365
random_forest     PARSEC         Base   mass              0.999820  0.049511
                                        radius            0.999277  0.010482
xgboost           PARSEC         Base   mass              0.999719  0.081495
                                        radius            0.998658  0.014211

                                                               MAE     MedAE  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.022630  0.000000
                                        radius            0.006178  0.000000
KNN               PARSEC         Base   mass              0.099202  0.072600
                                        radius            0.008115  0.005617
linear_regression PARSEC         Base   mass              1.485631  1.083904
                                        radius            0.024566  0.016577
mlp               PARSEC         Base   mass              0.164628  0.125985
                                        radius            0.018642  0.015196
random_forest     PARSEC         Base   mass              0.024444  0.001860
                                        radius            0.004453  0.000528
xgboost           PARSEC         Base   mass              0.065723  0.054516
                                        radius            0.010265  0.007910

                                                              CORR    MAX_ER  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass              0.999848  0.566000
                                        radius            0.999138  0.256387
KNN               PARSEC         Base   mass              0.999218  1.149800
                                        radius            0.999428  0.168790
linear_regression PARSEC         Base   mass              0.942583  5.418317
                                        radius            0.996947  0.221112
mlp               PARSEC         Base   mass              0.998454  1.007993
                                        radius            0.998250  0.153223
random_forest     PARSEC         Base   mass              0.999912  0.442430
                                        radius            0.999639  0.136455
xgboost           PARSEC         Base   mass              0.999860  0.359774
                                        radius            0.999340  0.123532

                                                                                                          Percentiles  \
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                   75 : 0.002 / 90 : 0.084 / 95 : 0.16465 / 99 : 0.26366
                                        radius             75 : 0.00656 / 90 : 0.01915 / 95 : 0.03033 / 99 : 0.06953
KNN               PARSEC         Base   mass                  75 : 0.129 / 90 : 0.2116 / 95 : 0.30706 / 99 : 0.52326
                                        radius             75 : 0.01013 / 90 : 0.01569 / 95 : 0.02182 / 99 : 0.05852
linear_regression PARSEC         Base   mass                75 : 1.75367 / 90 : 3.62005 / 95 : 4.39414 / 99 : 5.2987
                                        radius              75 : 0.03082 / 90 : 0.05156 / 95 : 0.0835 / 99 : 0.14989
mlp               PARSEC         Base   mass               75 : 0.21448 / 90 : 0.32971 / 95 : 0.44675 / 99 : 0.68386
                                        radius             75 : 0.02618 / 90 : 0.03718 / 95 : 0.04612 / 99 : 0.07668
random_forest     PARSEC         Base   mass                 75 : 0.03292 / 90 : 0.085 / 95 : 0.12258 / 99 : 0.17644
                                        radius             75 : 0.00441 / 90 : 0.01383 / 95 : 0.02143 / 99 : 0.04544
xgboost           PARSEC         Base   mass               75 : 0.09542 / 90 : 0.12974 / 95 : 0.15166 / 99 : 0.21589
                                        radius                75 : 0.01383 / 90 : 0.02107 / 95 : 0.02714 / 99 : 0.05

                                                                time
model             physical_model filter output_parameter
decision_tree     PARSEC         Base   mass                6.658906
                                        radius              6.658906
KNN               PARSEC         Base   mass                3.132416
                                        radius              3.132416
linear_regression PARSEC         Base   mass                0.320629
                                        radius              0.320629
mlp               PARSEC         Base   mass              197.364993
                                        radius            197.364993
random_forest     PARSEC         Base   mass              100.594117
                                        radius            100.594117
xgboost           PARSEC         Base   mass                6.120966
                                        radius              6.120966

## Getting the ranges for the values

In [5]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=False)

iso_unscaled_df = iso_handler.get_isochrone_dataframe()
display(iso_unscaled_df)
phase_filtered_iso_unscaled_df = Data_preparator.filter_data(iso_unscaled_df, {'label':[1, 2, 3, 4, 5, 6]})
print_all_uniques(phase_filtered_iso_unscaled_df)

Reading PARSEC dataframe from csv file...

          logAge   logTe   logg  label  metallicity   Mass     Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090    1.636 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092    1.656 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098    1.725 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100    1.747 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106    1.811 -0.608
...          ...     ...    ...    ...          ...    ...      ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  143.400  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  149.900  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  156.500  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  164.400  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  154.100  3.204

[681303 rows x 8 columns]

logAge  : Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3

logTe  : Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721

logg  : Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428

Rpol  : Range : 0.11 - 687.5, Mean : 25.9755, Median : 10.37

logL  : Range : -3.42 - 4.8, Mean : 1.9902, Median : 1.855

In [6]:
iso_handler = Iso_data_handler("C:/Users/antoi/Code/unif/MA2/thesis/data/PARSEC/", 
                                ['logAge', 'logTe', 'logg', 'label', 'metallicity', 'Mass', 'Rpol', 'logL'], 
                                "PARSEC", rescale=True)

iso_df = iso_handler.get_isochrone_dataframe()
display(iso_df)

Reading PARSEC dataframe from csv file...

          logAge   logTe   logg  label  metallicity   Mass      Rpol   logL
0        5.00000  3.4744  2.965    0.0        -0.25  0.090  0.213783 -0.723
1        5.00000  3.4752  2.963    0.0        -0.25  0.092  0.219060 -0.711
2        5.00000  3.4780  2.956    0.0        -0.25  0.098  0.236789 -0.664
3        5.00000  3.4789  2.954    0.0        -0.25  0.100  0.242293 -0.649
4        5.00000  3.4819  2.950    0.0        -0.25  0.106  0.257918 -0.608
...          ...     ...    ...    ...          ...    ...       ...    ...
681298  10.25002  3.4812  0.032    7.0         0.50  0.801  2.156549  3.187
681299  10.25002  3.4776 -0.004    7.0         0.50  0.801  2.175802  3.208
681300  10.25002  3.4742 -0.038    7.0         0.50  0.800  2.194514  3.228
681301  10.25002  3.4701 -0.077    7.0         0.50  0.800  2.215902  3.250
681302  10.25002  3.4774 -0.002    7.0         0.50  0.799  2.187803  3.204

[681303 rows x 8 columns]

In [7]:
phase_filtered_iso_df = Data_preparator.filter_data(iso_df, {'label':[1, 2, 3, 4, 5, 6], 'Mass':('<', 3)})
print_all_uniques(phase_filtered_iso_df)

logAge  : Range : 6.8 - 10.25, Mean : 9.4807, Median : 9.5

logTe  : Range : 3.36 - 4.1907, Mean : 3.732, Median : 3.7204

logg  : Range : -0.38 - 5.345, Mean : 2.8946, Median : 2.504

Values in label column : 1.0, 2.0, 3.0, 4.0, 5.0, 6.0

Values in metallicity column : -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5, -2.75, 0.0, 0.25, 0.5

Mass  : Range : 0.09 - 2.999, Mean : 1.3031, Median : 1.178

Rpol  : Range : -0.98 - 2.3632, Mean : 0.8085, Median : 1.0017

logL  : Range : -3.42 - 3.418, Mean : 1.4962, Median : 1.765

## Base vs mass_filtered

| Parameter      | Base                                                   | mass_smaller_3                                         | 
| -------------  | ------------------------------------------------------ | ------------------------------------------------------ |
| age            | Range : 5.3 - 10.25, Mean : 9.0428, Median : 9.3       | Range : 6.8 - 10.25, Mean : 9.4807, Median : 9.5       | 
| mass           | Range : 0.09 - 13.952, Mean : 2.6725, Median : 1.428   | Range : 0.09 - 13.943, Mean : 2.3223, Median : 1.331   | 
| log_teff       | Range : 3.36 - 4.5177, Mean : 3.7779, Median : 3.721   | Range : 3.36 - 4.1907, Mean : 3.732, Median : 3.7204   | 
| log_g          | Range : -0.38 - 5.345, Mean : 2.7607, Median : 2.486   | Range : -0.38 - 5.345, Mean : 2.8946, Median : 2.504   | 
| R              | Range : -0.98 - 2.8373, Mean : 0.9648, Median : 1.0158 | Range : -0.98 - 2.3632, Mean : 0.8085, Median : 1.0017 |

### Mass parameter

In [8]:
compare_metrics(path, 
                output_parameters=["mass"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
KNN               PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
linear_regression PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
mlp               PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
random_forest     PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
xgboost           PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9998645662248727
                                 mass_smaller_3 mass              0.9995097172639185
KNN               PARSEC         Base           mass              0.9988608487584029
                                 mass_smaller_3 mass               0.998554141615815
linear_regression PARSEC         Base           mass              0.8245192246522494
                                 mass_smaller_3 mass              0.8070909702548619
mlp               PARSEC         Base           mass              0.9983534028469553
                                 mass_smaller_3 mass              0.9945446475434773
random_forest     PARSEC         Base           mass              0.9999481912588017
                                 mass_smaller_3 mass              0.9997602181989972
xgboost           PARSEC         Base           mass              0.9997133275725368
                                 mass_smaller_3 mass              0.9994355457039024

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.03334990805479929
                                 mass_smaller_3 mass              0.012309382125473058
KNN               PARSEC         Base           mass               0.09671927231352594
                                 mass_smaller_3 mass               0.02113170612567758
linear_regression PARSEC         Base           mass                1.2003447306000146
                                 mass_smaller_3 mass               0.24407597375509524
mlp               PARSEC         Base           mass               0.11659697793243133
                                 mass_smaller_3 mass               0.04563864298494231
random_forest     PARSEC         Base           mass              0.020632658357763397
                                 mass_smaller_3 mass                0.0086141814698752
xgboost           PARSEC         Base           mass              0.048515978548631995
                                 mass_smaller_3 mass              0.013202715929206191

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                0.00636864266742792
                                 mass_smaller_3 mass               0.002447377814813581
KNN               PARSEC         Base           mass               0.028862591597864654
                                 mass_smaller_3 mass               0.007344951140065155
linear_regression PARSEC         Base           mass                 0.8730563528829388
                                 mass_smaller_3 mass                 0.1675072686662634
mlp               PARSEC         Base           mass                0.06562671131920006
                                 mass_smaller_3 mass                0.03319214115687358
random_forest     PARSEC         Base           mass               0.005152606440781571
                                 mass_smaller_3 mass              0.0020254892604256534
xgboost           PARSEC         Base           mass               0.022327179582419036
                                 mass_smaller_3 mass               0.006638969286253388

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                 0.0
                                 mass_smaller_3 mass                                 0.0
KNN               PARSEC         Base           mass               0.0007999999999999119
                                 mass_smaller_3 mass              0.00039999999999995595
linear_regression PARSEC         Base           mass                  0.6561422562696339
                                 mass_smaller_3 mass                 0.11442554158758078
mlp               PARSEC         Base           mass                 0.04068492810085961
                                 mass_smaller_3 mass                0.023275940919077365
random_forest     PARSEC         Base           mass              2.0000000000311435e-05
                                 mass_smaller_3 mass              3.1086244689504383e-15
xgboost           PARSEC         Base           mass                0.008370099544525167
                                 mass_smaller_3 mass               0.0028146095275879413

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999322808272706
                                 mass_smaller_3 mass              0.9997548436797105
KNN               PARSEC         Base           mass              0.9994343850523681
                                 mass_smaller_3 mass              0.9992797790602066
linear_regression PARSEC         Base           mass               0.908030409622356
                                 mass_smaller_3 mass              0.8983824188300313
mlp               PARSEC         Base           mass              0.9991962011554283
                                 mass_smaller_3 mass              0.9972964905357999
random_forest     PARSEC         Base           mass              0.9999741079763345
                                 mass_smaller_3 mass              0.9998803002856723
xgboost           PARSEC         Base           mass              0.9998566642631501
                                 mass_smaller_3 mass              0.9997177428853014

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                1.633000000000001
                                 mass_smaller_3 mass               0.3540000000000001
KNN               PARSEC         Base           mass                5.044599999999999
                                 mass_smaller_3 mass               0.6562000000000001
linear_regression PARSEC         Base           mass                5.809022809397376
                                 mass_smaller_3 mass               1.6127551731539427
mlp               PARSEC         Base           mass                 2.13476847638778
                                 mass_smaller_3 mass               0.3072140732316573
random_forest     PARSEC         Base           mass               0.7621299999999884
                                 mass_smaller_3 mass               0.2166599999999983
xgboost           PARSEC         Base           mass               1.4695928878784184
                                 mass_smaller_3 mass              0.23273415374755846

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                         75 : 0.0 / 90 : 0.006 / 95 : 0.033 / 99 : 0.155
                                 mass_smaller_3 mass                         75 : 0.0 / 90 : 0.001 / 95 : 0.015 / 99 : 0.055
KNN               PARSEC         Base           mass                      75 : 0.0186 / 90 : 0.077 / 95 : 0.14 / 99 : 0.4044
                                 mass_smaller_3 mass                       75 : 0.0052 / 90 : 0.021 / 95 : 0.0392 / 99 : 0.1
linear_regression PARSEC         Base           mass               75 : 1.09438 / 90 : 1.88298 / 95 : 2.55432 / 99 : 4.24433
                                 mass_smaller_3 mass                75 : 0.19983 / 90 : 0.39727 / 95 : 0.54366 / 99 : 0.8269
mlp               PARSEC         Base           mass               75 : 0.06948 / 90 : 0.13224 / 95 : 0.22434 / 99 : 0.50433
                                 mass_smaller_3 mass               75 : 0.04609 / 90 : 0.07239 / 95 : 0.09941 / 99 : 0.14803
random_forest     PARSEC         Base           mass               75 : 0.00106 / 90 : 0.01192 / 95 : 0.02784 / 99 : 0.09206
                                 mass_smaller_3 mass               75 : 0.00041 / 90 : 0.00377 / 95 : 0.01182 / 99 : 0.03543
xgboost           PARSEC         Base           mass                75 : 0.02349 / 90 : 0.05388 / 95 : 0.08728 / 99 : 0.2091
                                 mass_smaller_3 mass               75 : 0.00735 / 90 : 0.01634 / 95 : 0.02516 / 99 : 0.05503

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 1.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
KNN               PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
linear_regression PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
mlp               PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
random_forest     PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999
xgboost           PARSEC         Base           mass              0.09 - 13.943
                                 mass_smaller_3 mass               0.09 - 2.999

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9996254161385038
                                 mass_smaller_3 mass              0.9996015588887927
KNN               PARSEC         Base           mass              0.9970182995079786
                                 mass_smaller_3 mass              0.9975156675436833
linear_regression PARSEC         Base           mass              0.7140803707653656
                                 mass_smaller_3 mass              0.6611637557456042
mlp               PARSEC         Base           mass              0.9987502420585099
                                 mass_smaller_3 mass              0.9959413312589612
random_forest     PARSEC         Base           mass              0.9998845663220531
                                 mass_smaller_3 mass              0.9998752417991507
xgboost           PARSEC         Base           mass              0.9991350851722829
                                 mass_smaller_3 mass              0.9989190774264869

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.05840340529668738
                                 mass_smaller_3 mass              0.012820296118616454
KNN               PARSEC         Base           mass                0.1647753704342362
                                 mass_smaller_3 mass               0.03200672224450317
linear_regression PARSEC         Base           mass                1.6260706065843913
                                 mass_smaller_3 mass               0.37973772350493834
mlp               PARSEC         Base           mass                0.1072766146118961
                                 mass_smaller_3 mass               0.04512281166038729
random_forest     PARSEC         Base           mass               0.03242170732272036
                                 mass_smaller_3 mass              0.007178831032769633
xgboost           PARSEC         Base           mass                0.0887554156625211
                                 mass_smaller_3 mass              0.021113900039454164

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.013469273504042142
                                 mass_smaller_3 mass              0.0035584884648051022
KNN               PARSEC         Base           mass               0.056744259561081006
                                 mass_smaller_3 mass               0.014979059851281788
linear_regression PARSEC         Base           mass                 1.3562018118194228
                                 mass_smaller_3 mass                 0.2880276381631927
mlp               PARSEC         Base           mass                0.06114685121302729
                                 mass_smaller_3 mass               0.032799531764147266
random_forest     PARSEC         Base           mass               0.008655048540270082
                                 mass_smaller_3 mass               0.002345166030215883
xgboost           PARSEC         Base           mass               0.046886387633201056
                                 mass_smaller_3 mass               0.012955817968592393

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                 0.0
                                 mass_smaller_3 mass                                 0.0
KNN               PARSEC         Base           mass                 0.01100000000000012
                                 mass_smaller_3 mass               0.0050000000000001155
linear_regression PARSEC         Base           mass                  1.2151522118086535
                                 mass_smaller_3 mass                 0.23494432335679732
mlp               PARSEC         Base           mass                 0.03819388341543445
                                 mass_smaller_3 mass                 0.02349955432136208
random_forest     PARSEC         Base           mass               0.0002600000000016478
                                 mass_smaller_3 mass              0.00012999999999940837
xgboost           PARSEC         Base           mass                0.020626248836517425
                                 mass_smaller_3 mass                0.007141310691833547

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9998127048400395
                                 mass_smaller_3 mass              0.9998008347548047
KNN               PARSEC         Base           mass              0.9985271249816617
                                 mass_smaller_3 mass              0.9987703679142015
linear_regression PARSEC         Base           mass              0.8773843227443292
                                 mass_smaller_3 mass              0.8695920943962187
mlp               PARSEC         Base           mass              0.9993800839205965
                                 mass_smaller_3 mass              0.9980929605760922
random_forest     PARSEC         Base           mass              0.9999423032749245
                                 mass_smaller_3 mass               0.999937968724471
xgboost           PARSEC         Base           mass               0.999567813034968
                                 mass_smaller_3 mass               0.999460435153906

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                1.633000000000001
                                 mass_smaller_3 mass               0.3129999999999997
KNN               PARSEC         Base           mass                5.044599999999999
                                 mass_smaller_3 mass               0.6562000000000001
linear_regression PARSEC         Base           mass                5.809022809397376
                                 mass_smaller_3 mass               1.6127551731539427
mlp               PARSEC         Base           mass               1.4758801510183677
                                 mass_smaller_3 mass               0.3072140732316573
random_forest     PARSEC         Base           mass               0.7621299999999884
                                 mass_smaller_3 mass              0.15781000000000134
xgboost           PARSEC         Base           mass               1.4695928878784184
                                 mass_smaller_3 mass              0.23273415374755846

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                       75 : 0.001 / 90 : 0.022 / 95 : 0.068 / 99 : 0.294
                                 mass_smaller_3 mass                        75 : 0.001 / 90 : 0.01 / 95 : 0.021 / 99 : 0.059
KNN               PARSEC         Base           mass                  75 : 0.0436 / 90 : 0.1408 / 95 : 0.26435 / 99 : 0.7288
                                 mass_smaller_3 mass                    75 : 0.0166 / 90 : 0.0396 / 95 : 0.064 / 99 : 0.1372
linear_regression PARSEC         Base           mass               75 : 1.92099 / 90 : 2.50743 / 95 : 2.94777 / 99 : 4.13453
                                 mass_smaller_3 mass                75 : 0.38605 / 90 : 0.6142 / 95 : 0.81103 / 99 : 1.14065
mlp               PARSEC         Base           mass                75 : 0.06655 / 90 : 0.1243 / 95 : 0.19734 / 99 : 0.46885
                                 mass_smaller_3 mass               75 : 0.04575 / 90 : 0.07177 / 95 : 0.09324 / 99 : 0.14826
random_forest     PARSEC         Base           mass               75 : 0.00335 / 90 : 0.01908 / 95 : 0.04398 / 99 : 0.14915
                                 mass_smaller_3 mass               75 : 0.00116 / 90 : 0.00673 / 95 : 0.01289 / 99 : 0.03221
xgboost           PARSEC         Base           mass               75 : 0.05201 / 90 : 0.11997 / 95 : 0.18982 / 99 : 0.37039
                                 mass_smaller_3 mass                75 : 0.01686 / 90 : 0.0317 / 95 : 0.04397 / 99 : 0.08149

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 2.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996
KNN               PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996
linear_regression PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996
mlp               PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996
random_forest     PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996
xgboost           PARSEC         Base           mass              0.726 - 13.901
                                 mass_smaller_3 mass               0.726 - 2.996

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999459955708547
                                 mass_smaller_3 mass              0.9997295898528473
KNN               PARSEC         Base           mass              0.9986590142761502
                                 mass_smaller_3 mass              0.9990663179816773
linear_regression PARSEC         Base           mass              0.8170987684749786
                                 mass_smaller_3 mass              0.9233322195098903
mlp               PARSEC         Base           mass              0.9965617240052644
                                 mass_smaller_3 mass              0.9945807875223214
random_forest     PARSEC         Base           mass              0.9999713505655556
                                 mass_smaller_3 mass              0.9998663184264494
xgboost           PARSEC         Base           mass               0.999888070822217
                                 mass_smaller_3 mass              0.9997386147290966

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.024641225603144138
                                 mass_smaller_3 mass              0.010414439165456313
KNN               PARSEC         Base           mass               0.12286979026424039
                                 mass_smaller_3 mass              0.019450754397847075
linear_regression PARSEC         Base           mass                1.4568068548859194
                                 mass_smaller_3 mass                0.2709853438680536
mlp               PARSEC         Base           mass                0.2079340935215777
                                 mass_smaller_3 mass               0.04816486056185164
random_forest     PARSEC         Base           mass               0.01795925059369213
                                 mass_smaller_3 mass              0.007393924444293661
xgboost           PARSEC         Base           mass               0.03612342170599431
                                 mass_smaller_3 mass              0.010224238799817249

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.006320830750155019
                                 mass_smaller_3 mass              0.0028242811501597623
KNN               PARSEC         Base           mass                0.05731495660260385
                                 mass_smaller_3 mass                 0.0109082428115016
linear_regression PARSEC         Base           mass                 1.0807392493061083
                                 mass_smaller_3 mass                0.21390872950799075
mlp               PARSEC         Base           mass                0.12130712141410704
                                 mass_smaller_3 mass               0.035365194476629745
random_forest     PARSEC         Base           mass              0.0069542368802229665
                                 mass_smaller_3 mass              0.0030803784478173725
xgboost           PARSEC         Base           mass                0.02399718580019451
                                 mass_smaller_3 mass               0.006961948929617581

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                0.0
                                 mass_smaller_3 mass                                0.0
KNN               PARSEC         Base           mass               0.018999999999999906
                                 mass_smaller_3 mass               0.005799999999999805
linear_regression PARSEC         Base           mass                  0.878467562354595
                                 mass_smaller_3 mass                0.17897850878126775
mlp               PARSEC         Base           mass               0.058413586733669476
                                 mass_smaller_3 mass               0.027034934691084755
random_forest     PARSEC         Base           mass              0.0005800000000046879
                                 mass_smaller_3 mass              0.0002399999999991298
xgboost           PARSEC         Base           mass                0.01514275693893452
                                 mass_smaller_3 mass              0.0046716270446776065

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999730941677303
                                 mass_smaller_3 mass               0.999864795213471
KNN               PARSEC         Base           mass              0.9993351850480691
                                 mass_smaller_3 mass              0.9995595096150178
linear_regression PARSEC         Base           mass              0.9105157535025173
                                 mass_smaller_3 mass                0.96474168346435
mlp               PARSEC         Base           mass              0.9988595292125967
                                 mass_smaller_3 mass              0.9973159550216337
random_forest     PARSEC         Base           mass              0.9999857375598071
                                 mass_smaller_3 mass              0.9999335195331801
xgboost           PARSEC         Base           mass              0.9999466740441237
                                 mass_smaller_3 mass              0.9998695325352005

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.6719999999999988
                                 mass_smaller_3 mass                            0.129
KNN               PARSEC         Base           mass                           1.3902
                                 mass_smaller_3 mass              0.19419999999999993
linear_regression PARSEC         Base           mass                5.531744924052422
                                 mass_smaller_3 mass               0.8713407094861472
mlp               PARSEC         Base           mass                 2.13476847638778
                                 mass_smaller_3 mass              0.26258076456827206
random_forest     PARSEC         Base           mass               0.5654600000000052
                                 mass_smaller_3 mass              0.09384999999999843
xgboost           PARSEC         Base           mass               0.3200783462524406
                                 mass_smaller_3 mass              0.09049644279479985

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                       75 : 0.001 / 90 : 0.017 / 95 : 0.042 / 99 : 0.101
                                 mass_smaller_3 mass                         75 : 0.0 / 90 : 0.004 / 95 : 0.019 / 99 : 0.044
KNN               PARSEC         Base           mass                75 : 0.0628 / 90 : 0.14326 / 95 : 0.24146 / 99 : 0.56873
                                 mass_smaller_3 mass                     75 : 0.0152 / 90 : 0.026 / 95 : 0.0426 / 99 : 0.085
linear_regression PARSEC         Base           mass                75 : 1.18462 / 90 : 2.15073 / 95 : 3.42736 / 99 : 4.8223
                                 mass_smaller_3 mass                75 : 0.30201 / 90 : 0.45789 / 95 : 0.55721 / 99 : 0.7001
mlp               PARSEC         Base           mass               75 : 0.13817 / 90 : 0.33275 / 95 : 0.46247 / 99 : 0.79147
                                 mass_smaller_3 mass                75 : 0.0481 / 90 : 0.07652 / 95 : 0.09967 / 99 : 0.15319
random_forest     PARSEC         Base           mass                  75 : 0.0067 / 90 : 0.02156 / 95 : 0.034 / 99 : 0.06874
                                 mass_smaller_3 mass                 75 : 0.00272 / 90 : 0.01024 / 95 : 0.0165 / 99 : 0.0305
xgboost           PARSEC         Base           mass               75 : 0.03125 / 90 : 0.05624 / 95 : 0.07732 / 99 : 0.12994
                                 mass_smaller_3 mass                75 : 0.0089 / 90 : 0.01631 / 95 : 0.02204 / 99 : 0.03571

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 3.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999
KNN               PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999
linear_regression PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999
mlp               PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999
random_forest     PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999
xgboost           PARSEC         Base           mass              0.655 - 13.903
                                 mass_smaller_3 mass               0.655 - 2.999

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999157323462134
                                 mass_smaller_3 mass                0.99861327985488
KNN               PARSEC         Base           mass              0.9995167309456113
                                 mass_smaller_3 mass               0.998050670293343
linear_regression PARSEC         Base           mass              0.8118713347684259
                                 mass_smaller_3 mass              0.8337149963869681
mlp               PARSEC         Base           mass              0.9978508313372416
                                 mass_smaller_3 mass              0.9897232395118077
random_forest     PARSEC         Base           mass              0.9999606928548479
                                 mass_smaller_3 mass              0.9994000178100041
xgboost           PARSEC         Base           mass              0.9999166189115193
                                 mass_smaller_3 mass                0.99956444690536

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.02111697760575715
                                 mass_smaller_3 mass               0.01755050494298746
KNN               PARSEC         Base           mass               0.05091132504067333
                                 mass_smaller_3 mass               0.02095812302576166
linear_regression PARSEC         Base           mass                 1.028619336005366
                                 mass_smaller_3 mass               0.19256067363637497
mlp               PARSEC         Base           mass                0.1105583542450437
                                 mass_smaller_3 mass               0.06583455888867584
random_forest     PARSEC         Base           mass              0.014444600080848186
                                 mass_smaller_3 mass              0.011544438365359079
xgboost           PARSEC         Base           mass               0.02150453950467348
                                 mass_smaller_3 mass              0.009849838286903901

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.006363201975499179
                                 mass_smaller_3 mass              0.0055081029656236956
KNN               PARSEC         Base           mass               0.019782555375986315
                                 mass_smaller_3 mass               0.009882620508080557
linear_regression PARSEC         Base           mass                 0.7982852936318392
                                 mass_smaller_3 mass                0.14199705460905987
mlp               PARSEC         Base           mass                0.06117234369426384
                                 mass_smaller_3 mass                0.05198597481357024
random_forest     PARSEC         Base           mass               0.005360876706283088
                                 mass_smaller_3 mass               0.004430093546489173
xgboost           PARSEC         Base           mass                0.01399919481831184
                                 mass_smaller_3 mass                0.00583951702144097

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                 0.0
                                 mass_smaller_3 mass                                 0.0
KNN               PARSEC         Base           mass               0.0041999999999999815
                                 mass_smaller_3 mass               0.0011999999999999789
linear_regression PARSEC         Base           mass                  0.7256700925698434
                                 mass_smaller_3 mass                 0.10282662419743183
mlp               PARSEC         Base           mass                0.041368351376828594
                                 mass_smaller_3 mass                 0.04210076301968346
random_forest     PARSEC         Base           mass              0.00011000000000160881
                                 mass_smaller_3 mass              5.9999999998616715e-05
xgboost           PARSEC         Base           mass                0.008305312156677402
                                 mass_smaller_3 mass               0.0032798461914063104

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999580761223028
                                 mass_smaller_3 mass              0.9993132163897192
KNN               PARSEC         Base           mass              0.9997602243958886
                                 mass_smaller_3 mass              0.9991013388610349
linear_regression PARSEC         Base           mass              0.9013308703335325
                                 mass_smaller_3 mass              0.9156996541366172
mlp               PARSEC         Base           mass              0.9990933124095018
                                 mass_smaller_3 mass               0.995219751424935
random_forest     PARSEC         Base           mass              0.9999806231984508
                                 mass_smaller_3 mass               0.999705645937757
xgboost           PARSEC         Base           mass              0.9999639214770979
                                 mass_smaller_3 mass              0.9997975600200647

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.29800000000000004
                                 mass_smaller_3 mass               0.3540000000000001
KNN               PARSEC         Base           mass               1.0024000000000015
                                 mass_smaller_3 mass              0.18800000000000017
linear_regression PARSEC         Base           mass                5.531585616705733
                                 mass_smaller_3 mass               0.8694358979128181
mlp               PARSEC         Base           mass               1.6558692953117884
                                 mass_smaller_3 mass              0.24521810273620437
random_forest     PARSEC         Base           mass              0.20860000000000323
                                 mass_smaller_3 mass              0.19652166666666337
xgboost           PARSEC         Base           mass              0.19392802429199207
                                 mass_smaller_3 mass              0.15918249893188463

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                          75 : 0.0 / 90 : 0.021 / 95 : 0.041 / 99 : 0.09
                                 mass_smaller_3 mass                       75 : 0.0 / 90 : 0.019 / 95 : 0.039 / 99 : 0.07298
KNN               PARSEC         Base           mass                  75 : 0.0184 / 90 : 0.0568 / 95 : 0.0952 / 99 : 0.19975
                                 mass_smaller_3 mass                   75 : 0.0114 / 90 : 0.0286 / 95 : 0.0452 / 99 : 0.0944
linear_regression PARSEC         Base           mass               75 : 1.06071 / 90 : 1.40396 / 95 : 1.71243 / 99 : 3.86906
                                 mass_smaller_3 mass               75 : 0.19458 / 90 : 0.31906 / 95 : 0.39626 / 99 : 0.62712
mlp               PARSEC         Base           mass                75 : 0.07073 / 90 : 0.11101 / 95 : 0.1669 / 99 : 0.47099
                                 mass_smaller_3 mass               75 : 0.07597 / 90 : 0.11354 / 95 : 0.13299 / 99 : 0.15806
random_forest     PARSEC         Base           mass               75 : 0.00348 / 90 : 0.01752 / 95 : 0.02849 / 99 : 0.06704
                                 mass_smaller_3 mass               75 : 0.00236 / 90 : 0.01616 / 95 : 0.02571 / 99 : 0.04831
xgboost           PARSEC         Base           mass               75 : 0.01736 / 90 : 0.03379 / 95 : 0.04823 / 99 : 0.07899
                                 mass_smaller_3 mass               75 : 0.00703 / 90 : 0.01378 / 95 : 0.01974 / 99 : 0.03933

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 4.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999
KNN               PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999
linear_regression PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999
mlp               PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999
random_forest     PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999
xgboost           PARSEC         Base           mass              0.644 - 13.912
                                 mass_smaller_3 mass               0.644 - 2.999

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.999970695956602
                                 mass_smaller_3 mass              0.9998373143257983
KNN               PARSEC         Base           mass              0.9999301649912623
                                 mass_smaller_3 mass                0.99967230648623
linear_regression PARSEC         Base           mass              0.8673858809997186
                                 mass_smaller_3 mass              0.9143231409356115
mlp               PARSEC         Base           mass              0.9993699743754522
                                 mass_smaller_3 mass              0.9951493376920757
random_forest     PARSEC         Base           mass              0.9999874812813667
                                 mass_smaller_3 mass              0.9999251706736176
xgboost           PARSEC         Base           mass               0.999945576093108
                                 mass_smaller_3 mass              0.9997670891126287

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.009049336314518173
                                 mass_smaller_3 mass               0.005218977188543175
KNN               PARSEC         Base           mass               0.013994089169513078
                                 mass_smaller_3 mass               0.007427031968252973
linear_regression PARSEC         Base           mass                  0.624988943052741
                                 mass_smaller_3 mass                 0.1258929098895129
mlp               PARSEC         Base           mass                0.04992182351338668
                                 mass_smaller_3 mass               0.030180587377619507
random_forest     PARSEC         Base           mass               0.005918413312542843
                                 mass_smaller_3 mass              0.0035405392044352674
xgboost           PARSEC         Base           mass               0.012407003542950264
                                 mass_smaller_3 mass               0.006266883713411551

                                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.0009132218865141464
                                 mass_smaller_3 mass              0.00033790644590227324
KNN               PARSEC         Base           mass                0.002426308339274471
                                 mass_smaller_3 mass               0.0011511788505237618
linear_regression PARSEC         Base           mass                  0.4828553295942969
                                 mass_smaller_3 mass                 0.09719351237969498
mlp               PARSEC         Base           mass                 0.03883776474254258
                                 mass_smaller_3 mass                0.023785823261607837
random_forest     PARSEC         Base           mass               0.0007802653924923397
                                 mass_smaller_3 mass               0.0003403567610074432
xgboost           PARSEC         Base           mass                0.007319095271953337
                                 mass_smaller_3 mass                0.003433100619588571

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                 0.0
                                 mass_smaller_3 mass                                 0.0
KNN               PARSEC         Base           mass                                 0.0
                                 mass_smaller_3 mass                                 0.0
linear_regression PARSEC         Base           mass                 0.43661272453248223
                                 mass_smaller_3 mass                 0.08225444613562294
mlp               PARSEC         Base           mass                 0.03446639749672209
                                 mass_smaller_3 mass                0.019069356461244746
random_forest     PARSEC         Base           mass              1.7763568394002505e-15
                                 mass_smaller_3 mass              1.5543122344752192e-15
xgboost           PARSEC         Base           mass                0.003980285644531234
                                 mass_smaller_3 mass                0.001737246513366708

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999853547030013
                                 mass_smaller_3 mass              0.9999187871020149
KNN               PARSEC         Base           mass              0.9999651040590062
                                 mass_smaller_3 mass              0.9998421275157895
linear_regression PARSEC         Base           mass              0.9316431842999809
                                 mass_smaller_3 mass              0.9677543073671399
mlp               PARSEC         Base           mass              0.9997264772301635
                                 mass_smaller_3 mass               0.997666761260595
random_forest     PARSEC         Base           mass              0.9999937468332423
                                 mass_smaller_3 mass              0.9999627945862961
xgboost           PARSEC         Base           mass              0.9999728822762822
                                 mass_smaller_3 mass              0.9998845454739793

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.28800000000000026
                                 mass_smaller_3 mass              0.30100000000000016
KNN               PARSEC         Base           mass               0.7675999999999998
                                 mass_smaller_3 mass              0.20679999999999987
linear_regression PARSEC         Base           mass               5.2109862837012795
                                 mass_smaller_3 mass               0.8322531289040245
mlp               PARSEC         Base           mass               1.0292663089086531
                                 mass_smaller_3 mass              0.20606739882597758
random_forest     PARSEC         Base           mass              0.18562000000000145
                                 mass_smaller_3 mass              0.17535999999999774
xgboost           PARSEC         Base           mass              0.14492399597167882
                                 mass_smaller_3 mass              0.11698207283020023

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                       75 : 0.0 / 90 : 0.00029 / 95 : 0.001 / 99 : 0.021
                                 mass_smaller_3 mass                           75 : 0.0 / 90 : 0.0 / 95 : 0.001 / 99 : 0.003
KNN               PARSEC         Base           mass                    75 : 0.0004 / 90 : 0.0012 / 95 : 0.008 / 99 : 0.0614
                                 mass_smaller_3 mass                   75 : 0.0004 / 90 : 0.0008 / 95 : 0.0014 / 99 : 0.0322
linear_regression PARSEC         Base           mass                75 : 0.65434 / 90 : 0.83563 / 95 : 1.00776 / 99 : 1.7564
                                 mass_smaller_3 mass               75 : 0.13848 / 90 : 0.18024 / 95 : 0.19626 / 99 : 0.42277
mlp               PARSEC         Base           mass               75 : 0.05198 / 90 : 0.07234 / 95 : 0.08906 / 99 : 0.14161
                                 mass_smaller_3 mass               75 : 0.03291 / 90 : 0.05223 / 95 : 0.05906 / 99 : 0.07814
random_forest     PARSEC         Base           mass                   75 : 3e-05 / 90 : 0.00052 / 95 : 0.001 / 99 : 0.02242
                                 mass_smaller_3 mass                  75 : 1e-05 / 90 : 0.00038 / 95 : 0.0008 / 99 : 0.00452
xgboost           PARSEC         Base           mass                75 : 0.0084 / 90 : 0.01727 / 95 : 0.02663 / 99 : 0.05132
                                 mass_smaller_3 mass                 75 : 0.0038 / 90 : 0.00834 / 95 : 0.01267 / 99 : 0.0256

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 5.0

                                                                    value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999
KNN               PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999
linear_regression PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999
mlp               PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999
random_forest     PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999
xgboost           PARSEC         Base           mass              1.892 - 13.29
                                 mass_smaller_3 mass              1.892 - 2.999

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999254209050206
                                 mass_smaller_3 mass              0.9986650648091511
KNN               PARSEC         Base           mass              0.9992568821137228
                                 mass_smaller_3 mass              0.9947009392829238
linear_regression PARSEC         Base           mass              0.7709329316092588
                                 mass_smaller_3 mass              0.7251082814289855
mlp               PARSEC         Base           mass               0.997984894161209
                                 mass_smaller_3 mass              0.9657110380168625
random_forest     PARSEC         Base           mass              0.9999699330578958
                                 mass_smaller_3 mass              0.9994501720459033
xgboost           PARSEC         Base           mass              0.9998450477989594
                                 mass_smaller_3 mass               0.997534364823994

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.02821057356190365
                                 mass_smaller_3 mass              0.010391487843661796
KNN               PARSEC         Base           mass               0.08902355338689272
                                 mass_smaller_3 mass              0.021927820508182483
linear_regression PARSEC         Base           mass                1.5712064628962854
                                 mass_smaller_3 mass                0.5369350971520952
mlp               PARSEC         Base           mass                0.1614285549724164
                                 mass_smaller_3 mass              0.058575623036359464
random_forest     PARSEC         Base           mass               0.01790768649347343
                                 mass_smaller_3 mass              0.006762368094453291
xgboost           PARSEC         Base           mass               0.04071165585577291
                                 mass_smaller_3 mass              0.014551349963586601

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.006970776455293335
                                 mass_smaller_3 mass              0.0023298176225005534
KNN               PARSEC         Base           mass                0.03587811176114586
                                 mass_smaller_3 mass               0.009514260602065493
linear_regression PARSEC         Base           mass                 1.1799482615688113
                                 mass_smaller_3 mass                 0.5159305316170868
mlp               PARSEC         Base           mass                0.11213866289748539
                                 mass_smaller_3 mass                0.04548833858351667
random_forest     PARSEC         Base           mass              0.0058314671034786734
                                 mass_smaller_3 mass               0.002141677539433776
xgboost           PARSEC         Base           mass               0.027355252795963014
                                 mass_smaller_3 mass               0.010546056811769197

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              1.7763568394002505e-15
                                 mass_smaller_3 mass               0.0009999999999998899
KNN               PARSEC         Base           mass               0.0021999999999997577
                                 mass_smaller_3 mass                0.001000000000000334
linear_regression PARSEC         Base           mass                  0.8100991387664083
                                 mass_smaller_3 mass                  0.5159699940644744
mlp               PARSEC         Base           mass                 0.07357954631193664
                                 mass_smaller_3 mass                 0.03515938052849599
random_forest     PARSEC         Base           mass               0.0007900000000025109
                                 mass_smaller_3 mass               0.0006566666666691923
xgboost           PARSEC         Base           mass                 0.01980073928833015
                                 mass_smaller_3 mass                0.007963695526123082

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9999627958098751
                                 mass_smaller_3 mass              0.9993342118380482
KNN               PARSEC         Base           mass              0.9996315855625986
                                 mass_smaller_3 mass              0.9978268060819806
linear_regression PARSEC         Base           mass              0.9521317173717947
                                 mass_smaller_3 mass              0.9389557526430963
mlp               PARSEC         Base           mass              0.9990999609966714
                                 mass_smaller_3 mass              0.9838742845405452
random_forest     PARSEC         Base           mass              0.9999850304577665
                                 mass_smaller_3 mass              0.9997267915205063
xgboost           PARSEC         Base           mass               0.999928522371786
                                 mass_smaller_3 mass              0.9989065629832538

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.47300000000000075
                                 mass_smaller_3 mass               0.2549999999999999
KNN               PARSEC         Base           mass               1.0809999999999995
                                 mass_smaller_3 mass              0.13040000000000007
linear_regression PARSEC         Base           mass                5.145375592219974
                                 mass_smaller_3 mass               0.8180775838235617
mlp               PARSEC         Base           mass               0.9344544044088181
                                 mass_smaller_3 mass              0.17575173791250354
random_forest     PARSEC         Base           mass              0.37428000000001305
                                 mass_smaller_3 mass              0.11288000000000054
xgboost           PARSEC         Base           mass               0.4049706649780269
                                 mass_smaller_3 mass              0.10421278572082526

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                      75 : 0.001 / 90 : 0.005 / 95 : 0.047 / 99 : 0.1443
                                 mass_smaller_3 mass                       75 : 0.002 / 90 : 0.003 / 95 : 0.005 / 99 : 0.046
KNN               PARSEC         Base           mass                    75 : 0.033 / 90 : 0.1046 / 95 : 0.1826 / 99 : 0.4121
                                 mass_smaller_3 mass                     75 : 0.0064 / 90 : 0.035 / 95 : 0.058 / 99 : 0.0908
linear_regression PARSEC         Base           mass               75 : 1.22962 / 90 : 2.86674 / 95 : 3.83857 / 99 : 4.78891
                                 mass_smaller_3 mass                 75 : 0.63479 / 90 : 0.7154 / 95 : 0.75121 / 99 : 0.7878
mlp               PARSEC         Base           mass                75 : 0.14744 / 90 : 0.26166 / 95 : 0.3546 / 99 : 0.56036
                                 mass_smaller_3 mass               75 : 0.06486 / 90 : 0.10539 / 95 : 0.12248 / 99 : 0.14188
random_forest     PARSEC         Base           mass               75 : 0.00262 / 90 : 0.01574 / 95 : 0.03219 / 99 : 0.08003
                                 mass_smaller_3 mass               75 : 0.00156 / 90 : 0.00343 / 95 : 0.00739 / 99 : 0.03583
xgboost           PARSEC         Base           mass                75 : 0.03651 / 90 : 0.05512 / 95 : 0.07148 / 99 : 0.1565
                                 mass_smaller_3 mass                  75 : 0.01449 / 90 : 0.0225 / 95 : 0.02802 / 99 : 0.049

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Results for the label category with a value of 6.0

                                                                     value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995
KNN               PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995
linear_regression PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995
mlp               PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995
random_forest     PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995
xgboost           PARSEC         Base           mass              1.921 - 13.588
                                 mass_smaller_3 mass               1.921 - 2.995

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9996933141748274
                                 mass_smaller_3 mass              0.9657495404723373
KNN               PARSEC         Base           mass               0.998431665913449
                                 mass_smaller_3 mass              0.9760718063545405
linear_regression PARSEC         Base           mass              0.6919278569232218
                                 mass_smaller_3 mass              0.7403532787733614
mlp               PARSEC         Base           mass              0.9967781161395497
                                 mass_smaller_3 mass              0.9300202676999519
random_forest     PARSEC         Base           mass              0.9998199689239768
                                 mass_smaller_3 mass              0.9767683692968053
xgboost           PARSEC         Base           mass               0.999718824733582
                                 mass_smaller_3 mass              0.9790471900319964

                                                                                 RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.06172729882855662
                                 mass_smaller_3 mass              0.06332145637623032
KNN               PARSEC         Base           mass              0.14512225523747085
                                 mass_smaller_3 mass              0.09837849222139676
linear_regression PARSEC         Base           mass               1.9558360343543915
                                 mass_smaller_3 mass               0.4924490923500778
mlp               PARSEC         Base           mass              0.21484124503991228
                                 mass_smaller_3 mass              0.11811998545751141
random_forest     PARSEC         Base           mass              0.04951056752219542
                                 mass_smaller_3 mass              0.05625480957996152
xgboost           PARSEC         Base           mass              0.08149471031497761
                                 mass_smaller_3 mass              0.05996131326411839

                                                                                   MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.02262963995440585
                                 mass_smaller_3 mass               0.02487310979618674
KNN               PARSEC         Base           mass               0.09920200713648526
                                 mass_smaller_3 mass                0.0862803418803419
linear_regression PARSEC         Base           mass                1.4856310267003556
                                 mass_smaller_3 mass               0.46472731130833284
mlp               PARSEC         Base           mass               0.16462778529642247
                                 mass_smaller_3 mass               0.10520308546153971
random_forest     PARSEC         Base           mass               0.02444380056072489
                                 mass_smaller_3 mass              0.028416842453131693
xgboost           PARSEC         Base           mass                0.0657228688687538
                                 mass_smaller_3 mass              0.041469206952327656

                                                                                  MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                                0.0
                                 mass_smaller_3 mass                                0.0
KNN               PARSEC         Base           mass                             0.0726
                                 mass_smaller_3 mass                0.09019999999999984
linear_regression PARSEC         Base           mass                 1.0839037686723247
                                 mass_smaller_3 mass                 0.4559993304649619
mlp               PARSEC         Base           mass                 0.1259848416645064
                                 mass_smaller_3 mass                0.11050489158659182
random_forest     PARSEC         Base           mass              0.0018599999999882044
                                 mass_smaller_3 mass              0.0004099999999973569
xgboost           PARSEC         Base           mass                0.05451627159118644
                                 mass_smaller_3 mass               0.019595645904541215

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass              0.9998480455340994
                                 mass_smaller_3 mass              0.9834731625011262
KNN               PARSEC         Base           mass              0.9992178609698728
                                 mass_smaller_3 mass              0.9901335340368662
linear_regression PARSEC         Base           mass              0.9425832539437553
                                 mass_smaller_3 mass              0.9395998233541952
mlp               PARSEC         Base           mass              0.9984537736632414
                                 mass_smaller_3 mass              0.9801400044907306
random_forest     PARSEC         Base           mass               0.999911675428213
                                 mass_smaller_3 mass              0.9887687322739708
xgboost           PARSEC         Base           mass              0.9998602101595032
                                 mass_smaller_3 mass               0.991648820226214

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               0.5660000000000007
                                 mass_smaller_3 mass              0.29700000000000015
KNN               PARSEC         Base           mass                1.149799999999999
                                 mass_smaller_3 mass               0.2232000000000003
linear_regression PARSEC         Base           mass               5.4183167952317906
                                 mass_smaller_3 mass               0.8697596783970951
mlp               PARSEC         Base           mass               1.0079926182363437
                                 mass_smaller_3 mass              0.26244979988396144
random_forest     PARSEC         Base           mass              0.44243000000000166
                                 mass_smaller_3 mass               0.2166599999999983
xgboost           PARSEC         Base           mass               0.3597741470336917
                                 mass_smaller_3 mass              0.17185504627227788

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass                   75 : 0.002 / 90 : 0.084 / 95 : 0.16465 / 99 : 0.26366
                                 mass_smaller_3 mass                       75 : 0.001 / 90 : 0.156 / 95 : 0.177 / 99 : 0.196
KNN               PARSEC         Base           mass                  75 : 0.129 / 90 : 0.2116 / 95 : 0.30706 / 99 : 0.52326
                                 mass_smaller_3 mass                    75 : 0.122 / 90 : 0.151 / 95 : 0.1662 / 99 : 0.18436
linear_regression PARSEC         Base           mass                75 : 1.75367 / 90 : 3.62005 / 95 : 4.39414 / 99 : 5.2987
                                 mass_smaller_3 mass                75 : 0.59169 / 90 : 0.68558 / 95 : 0.73834 / 99 : 0.7952
mlp               PARSEC         Base           mass               75 : 0.21448 / 90 : 0.32971 / 95 : 0.44675 / 99 : 0.68386
                                 mass_smaller_3 mass               75 : 0.14198 / 90 : 0.17347 / 95 : 0.19225 / 99 : 0.22213
random_forest     PARSEC         Base           mass                 75 : 0.03292 / 90 : 0.085 / 95 : 0.12258 / 99 : 0.17644
                                 mass_smaller_3 mass               75 : 0.03987 / 90 : 0.11424 / 95 : 0.14456 / 99 : 0.16979
xgboost           PARSEC         Base           mass               75 : 0.09542 / 90 : 0.12974 / 95 : 0.15166 / 99 : 0.21589
                                 mass_smaller_3 mass                75 : 0.0741 / 90 : 0.11221 / 95 : 0.12545 / 99 : 0.14639

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           mass               6.6589062213897705
                                 mass_smaller_3 mass                5.519447326660156
KNN               PARSEC         Base           mass                3.132415533065796
                                 mass_smaller_3 mass               2.1986701488494873
linear_regression PARSEC         Base           mass               0.3206288814544678
                                 mass_smaller_3 mass              0.22408533096313477
mlp               PARSEC         Base           mass                197.3649926185608
                                 mass_smaller_3 mass                78.52664422988892
random_forest     PARSEC         Base           mass               100.59411668777466
                                 mass_smaller_3 mass               57.704763412475586
xgboost           PARSEC         Base           mass                6.120966196060181
                                 mass_smaller_3 mass                4.052688121795654

Every comparison is proportional to the mass.

Linear regression : 
- mass_smaller_3 : better results than Base on every metric except MAX_ER

Decision tree : 
- mass_smaller_3 : worse results than Base on every metric.

KNN : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER.

Random forest : 
- mass_smaller_3 : worse results than Base on every.

XGBoost : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER.

MLP : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER.

#### Conclusions on mass

Filtering with mass_smaller_3 gives worse results on every metric except for MAX_ER and the results of linear regression.

#### Best models for the mass parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and XGBoost.

&emsp; => important to note that the MedAE for random forest and decision tree is very close to 0, actually 0 for decision tree. \
&emsp; &emsp; This could be due to the fact that the PARSEC grids are discrete and the tree models accomodate well with this structure. \
&emsp; &emsp; These models might not be able to generalise enough for real-world data if they follow the grid too closely. \

### Radius parameter

In [10]:
compare_metrics(path, 
                output_parameters=["radius"],
                physical_models=["PARSEC"],
                data_filters=["Base", "mass_smaller_3"])

Results for the Global category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
KNN               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
mlp               PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 2.8372727025023003
                                 mass_smaller_3 radius             -0.9763360818022064 - 2.363235804483694

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9998031253046735
                                 mass_smaller_3 radius            0.9998730979524277
KNN               PARSEC         Base           radius            0.9998285017368778
                                 mass_smaller_3 radius            0.9998614402889981
linear_regression PARSEC         Base           radius            0.9935185560534721
                                 mass_smaller_3 radius            0.9912176219639253
mlp               PARSEC         Base           radius            0.9992619536549842
                                 mass_smaller_3 radius            0.9986923132156854
random_forest     PARSEC         Base           radius            0.9999331566181023
                                 mass_smaller_3 radius            0.9999651193964072
xgboost           PARSEC         Base           radius            0.9997789304226307
                                 mass_smaller_3 radius            0.9998196387051782

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.008554961717314173
                                 mass_smaller_3 radius             0.005594181561578525
KNN               PARSEC         Base           radius             0.007985505869416846
                                 mass_smaller_3 radius             0.005845529922721153
linear_regression PARSEC         Base           radius              0.04908612232524315
                                 mass_smaller_3 radius               0.0465379923853265
mlp               PARSEC         Base           radius               0.0167702172664392
                                 mass_smaller_3 radius             0.019499953143668845
random_forest     PARSEC         Base           radius             0.004984859197751271
                                 mass_smaller_3 radius            0.0029328828562066485
xgboost           PARSEC         Base           radius             0.009065428036205922
                                 mass_smaller_3 radius             0.006669192529275637

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.002482601676005068
                                 mass_smaller_3 radius            0.0016054257508545566
KNN               PARSEC         Base           radius             0.003650925948323463
                                 mass_smaller_3 radius             0.002675776360426932
linear_regression PARSEC         Base           radius             0.033081384002580365
                                 mass_smaller_3 radius               0.0342477246346664
mlp               PARSEC         Base           radius             0.012107065537423217
                                 mass_smaller_3 radius             0.013588212283423547
random_forest     PARSEC         Base           radius            0.0013960501013639787
                                 mass_smaller_3 radius            0.0008696273244595611
xgboost           PARSEC         Base           radius             0.005656724382967241
                                 mass_smaller_3 radius             0.003941479143004711

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            1.1102230246251565e-15
                                 mass_smaller_3 radius            2.9067053871567605e-05
KNN               PARSEC         Base           radius             0.0006931055649295192
                                 mass_smaller_3 radius            0.00039708399466031885
linear_regression PARSEC         Base           radius               0.02226162593087011
                                 mass_smaller_3 radius              0.027292284148876633
mlp               PARSEC         Base           radius              0.009007943628557114
                                 mass_smaller_3 radius              0.008255732742108113
random_forest     PARSEC         Base           radius             0.0001550106955970354
                                 mass_smaller_3 radius            0.00012278085094008517
xgboost           PARSEC         Base           radius               0.00327438473779601
                                 mass_smaller_3 radius             0.0020163456803985458

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9999015808270715
                                 mass_smaller_3 radius            0.9999365549390407
KNN               PARSEC         Base           radius            0.9999142939860561
                                 mass_smaller_3 radius             0.999930986981458
linear_regression PARSEC         Base           radius             0.996754009800564
                                 mass_smaller_3 radius            0.9955991271410152
mlp               PARSEC         Base           radius            0.9996369828848306
                                 mass_smaller_3 radius            0.9993465833505375
random_forest     PARSEC         Base           radius            0.9999665788188428
                                 mass_smaller_3 radius             0.999982559568496
xgboost           PARSEC         Base           radius            0.9998894630880014
                                 mass_smaller_3 radius            0.9999098155845728

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.3373776625458338
                                 mass_smaller_3 radius            0.16021197089478767
KNN               PARSEC         Base           radius            0.28715046126687094
                                 mass_smaller_3 radius             0.1207677416985975
linear_regression PARSEC         Base           radius             0.3506672434969049
                                 mass_smaller_3 radius             0.3049602043335856
mlp               PARSEC         Base           radius             0.2437543431675493
                                 mass_smaller_3 radius            0.09327647380319826
random_forest     PARSEC         Base           radius             0.2633429653822823
                                 mass_smaller_3 radius            0.07990824443986533
xgboost           PARSEC         Base           radius             0.1760073536087432
                                 mass_smaller_3 radius            0.10583349648732687

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00058 / 90 : 0.00718 / 95 : 0.01609 / 99 : 0.03359
                                 mass_smaller_3 radius              75 : 0.00041 / 90 : 0.00338 / 95 : 0.01053 / 99 : 0.0279
KNN               PARSEC         Base           radius              75 : 0.00479 / 90 : 0.01039 / 95 : 0.01472 / 99 : 0.0293
                                 mass_smaller_3 radius              75 : 0.00296 / 90 : 0.0085 / 95 : 0.01261 / 99 : 0.02402
linear_regression PARSEC         Base           radius               75 : 0.042 / 90 : 0.07847 / 95 : 0.10191 / 99 : 0.18132
                                 mass_smaller_3 radius             75 : 0.04745 / 90 : 0.06697 / 95 : 0.08254 / 99 : 0.16938
mlp               PARSEC         Base           radius             75 : 0.01608 / 90 : 0.02669 / 95 : 0.03443 / 99 : 0.05079
                                 mass_smaller_3 radius             75 : 0.02029 / 90 : 0.03422 / 95 : 0.03988 / 99 : 0.06118
random_forest     PARSEC         Base           radius             75 : 0.00056 / 90 : 0.00364 / 95 : 0.00759 / 99 : 0.01926
                                 mass_smaller_3 radius             75 : 0.00037 / 90 : 0.00179 / 95 : 0.00479 / 99 : 0.01369
xgboost           PARSEC         Base           radius             75 : 0.00752 / 90 : 0.01364 / 95 : 0.01837 / 99 : 0.03161
                                 mass_smaller_3 radius             75 : 0.00475 / 90 : 0.00993 / 95 : 0.01453 / 99 : 0.02591

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 1.0

                                                                                               value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
KNN               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
linear_regression PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
mlp               PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
random_forest     PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394
xgboost           PARSEC         Base           radius            -0.9763360818022064 - 1.1687920203141815
                                 mass_smaller_3 radius            -0.9763360818022064 - 0.7228806106869394

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9996510455556854
                                 mass_smaller_3 radius            0.9997433559877703
KNN               PARSEC         Base           radius             0.999189817501549
                                 mass_smaller_3 radius            0.9989234178730453
linear_regression PARSEC         Base           radius            0.9484107826824842
                                 mass_smaller_3 radius            0.9359057168106971
mlp               PARSEC         Base           radius            0.9981646611985815
                                 mass_smaller_3 radius            0.9966608938106034
random_forest     PARSEC         Base           radius            0.9999197322025316
                                 mass_smaller_3 radius             0.999942082752317
xgboost           PARSEC         Base           radius              0.99924952821124
                                 mass_smaller_3 radius            0.9993147227108912

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.00683673795679465
                                 mass_smaller_3 radius             0.004813472245302639
KNN               PARSEC         Base           radius             0.010435504649753138
                                 mass_smaller_3 radius              0.00987641772869747
linear_regression PARSEC         Base           radius              0.08328587325029292
                                 mass_smaller_3 radius              0.07692690266935816
mlp               PARSEC         Base           radius              0.01679691783716148
                                 mass_smaller_3 radius             0.018382740155483208
random_forest     PARSEC         Base           radius            0.0032788552210763896
                                 mass_smaller_3 radius            0.0022870746186966022
xgboost           PARSEC         Base           radius             0.010025829454064671
                                 mass_smaller_3 radius              0.00786467892100313

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0025103299872091785
                                 mass_smaller_3 radius            0.0017573481231242622
KNN               PARSEC         Base           radius             0.006517645170920483
                                 mass_smaller_3 radius             0.005876040131809627
linear_regression PARSEC         Base           radius              0.06347474231030695
                                 mass_smaller_3 radius              0.05907388999221595
mlp               PARSEC         Base           radius             0.012589885411183529
                                 mass_smaller_3 radius             0.013181100180723018
random_forest     PARSEC         Base           radius            0.0013057244322726821
                                 mass_smaller_3 radius            0.0009144699513593369
xgboost           PARSEC         Base           radius             0.006851980137943696
                                 mass_smaller_3 radius             0.005198325227519067

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            2.7755575615628914e-17
                                 mass_smaller_3 radius            2.7755575615628914e-17
KNN               PARSEC         Base           radius              0.004030783090865381
                                 mass_smaller_3 radius             0.0030877327859323567
linear_regression PARSEC         Base           radius               0.05315497875555691
                                 mass_smaller_3 radius                0.0488720377895618
mlp               PARSEC         Base           radius               0.00968945114626471
                                 mass_smaller_3 radius              0.008761311593608564
random_forest     PARSEC         Base           radius            0.00018112114567073873
                                 mass_smaller_3 radius            0.00013429163094435398
xgboost           PARSEC         Base           radius              0.004714362388504166
                                 mass_smaller_3 radius             0.0034333127182981094

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9998255543922977
                                 mass_smaller_3 radius            0.9998716719772635
KNN               PARSEC         Base           radius            0.9995968900343201
                                 mass_smaller_3 radius            0.9994648580144369
linear_regression PARSEC         Base           radius             0.973870221001157
                                 mass_smaller_3 radius            0.9681394371540123
mlp               PARSEC         Base           radius            0.9991189309824832
                                 mass_smaller_3 radius            0.9983438565505195
random_forest     PARSEC         Base           radius            0.9999599357955143
                                 mass_smaller_3 radius            0.9999710436775603
xgboost           PARSEC         Base           radius            0.9996247501188131
                                 mass_smaller_3 radius            0.9996573327303526

                                                                                MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.11918640771920858
                                 mass_smaller_3 radius             0.08593267655840048
KNN               PARSEC         Base           radius               0.136908653528043
                                 mass_smaller_3 radius              0.1207677416985975
linear_regression PARSEC         Base           radius              0.3506672434969049
                                 mass_smaller_3 radius              0.3049602043335856
mlp               PARSEC         Base           radius              0.1561630360672922
                                 mass_smaller_3 radius             0.08736854702223901
random_forest     PARSEC         Base           radius              0.0707659859859224
                                 mass_smaller_3 radius            0.034953438784615265
xgboost           PARSEC         Base           radius             0.08896295685255406
                                 mass_smaller_3 radius             0.06827712710358969

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00173 / 90 : 0.00758 / 95 : 0.01356 / 99 : 0.03205
                                 mass_smaller_3 radius              75 : 0.00123 / 90 : 0.00532 / 95 : 0.00969 / 99 : 0.0219
KNN               PARSEC         Base           radius             75 : 0.00911 / 90 : 0.01562 / 95 : 0.02098 / 99 : 0.03851
                                 mass_smaller_3 radius             75 : 0.00804 / 90 : 0.01488 / 95 : 0.02065 / 99 : 0.03802
linear_regression PARSEC         Base           radius                75 : 0.08971 / 90 : 0.11906 / 95 : 0.168 / 99 : 0.2684
                                 mass_smaller_3 radius             75 : 0.07656 / 90 : 0.12336 / 95 : 0.16728 / 99 : 0.23774
mlp               PARSEC         Base           radius              75 : 0.01747 / 90 : 0.02666 / 95 : 0.03381 / 99 : 0.0517
                                 mass_smaller_3 radius             75 : 0.01796 / 90 : 0.03325 / 95 : 0.03871 / 99 : 0.05454
random_forest     PARSEC         Base           radius              75 : 0.00108 / 90 : 0.0039 / 95 : 0.00676 / 99 : 0.01445
                                 mass_smaller_3 radius             75 : 0.00075 / 90 : 0.00268 / 95 : 0.00467 / 99 : 0.01047
xgboost           PARSEC         Base           radius             75 : 0.00918 / 90 : 0.01517 / 95 : 0.02011 / 99 : 0.03502
                                 mass_smaller_3 radius               75 : 0.00673 / 90 : 0.01144 / 95 : 0.0161 / 99 : 0.0286

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 2.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
KNN               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
linear_regression PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
mlp               PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
random_forest     PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882
xgboost           PARSEC         Base           radius             0.0199466816788423 - 2.458486763798206
                                 mass_smaller_3 radius            0.0199466816788423 - 1.2289134059946882

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9993088802987002
                                 mass_smaller_3 radius             0.999186317135907
KNN               PARSEC         Base           radius            0.9995060177289445
                                 mass_smaller_3 radius            0.9993918667573749
linear_regression PARSEC         Base           radius            0.9977700166955076
                                 mass_smaller_3 radius            0.9848676500607558
mlp               PARSEC         Base           radius            0.9986910877477772
                                 mass_smaller_3 radius            0.9939856611231387
random_forest     PARSEC         Base           radius            0.9997670556315849
                                 mass_smaller_3 radius            0.9998319561663607
xgboost           PARSEC         Base           radius            0.9994404577145701
                                 mass_smaller_3 radius            0.9987323948124496

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.014231846921850089
                                 mass_smaller_3 radius             0.006964643988089452
KNN               PARSEC         Base           radius             0.012076502958738434
                                 mass_smaller_3 radius             0.006038228885699132
linear_regression PARSEC         Base           radius             0.038903834702896725
                                 mass_smaller_3 radius              0.04248635880309964
mlp               PARSEC         Base           radius             0.019627510651855078
                                 mass_smaller_3 radius             0.019648350972958042
random_forest     PARSEC         Base           radius             0.008291207279458169
                                 mass_smaller_3 radius            0.0031651959073117266
xgboost           PARSEC         Base           radius              0.01284990524417628
                                 mass_smaller_3 radius             0.008693723547433795

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.005530775220687563
                                 mass_smaller_3 radius            0.0030811464517872277
KNN               PARSEC         Base           radius             0.006557152898135641
                                 mass_smaller_3 radius             0.004592917039803602
linear_regression PARSEC         Base           radius             0.030590827136313413
                                 mass_smaller_3 radius              0.03614954928044462
mlp               PARSEC         Base           radius             0.015366807848826314
                                 mass_smaller_3 radius             0.015137915792858614
random_forest     PARSEC         Base           radius              0.00282362516989707
                                 mass_smaller_3 radius            0.0014371210558810485
xgboost           PARSEC         Base           radius             0.009512662463685836
                                 mass_smaller_3 radius             0.006917988282027232

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                               0.0
                                 mass_smaller_3 radius                               0.0
KNN               PARSEC         Base           radius              0.004361558569092205
                                 mass_smaller_3 radius             0.0035874018473111002
linear_regression PARSEC         Base           radius              0.025142574806447715
                                 mass_smaller_3 radius              0.035048729090374514
mlp               PARSEC         Base           radius              0.012451057962700351
                                 mass_smaller_3 radius              0.011578846006440074
random_forest     PARSEC         Base           radius            0.00044907592050269507
                                 mass_smaller_3 radius             0.0002455694836491218
xgboost           PARSEC         Base           radius              0.007496822958309862
                                 mass_smaller_3 radius              0.005892467958579839

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9996583435005846
                                 mass_smaller_3 radius             0.999593629829325
KNN               PARSEC         Base           radius            0.9997680701615442
                                 mass_smaller_3 radius             0.999696946169518
linear_regression PARSEC         Base           radius            0.9991018210196535
                                 mass_smaller_3 radius            0.9929563927643908
mlp               PARSEC         Base           radius            0.9993723124623445
                                 mass_smaller_3 radius            0.9969882969346686
random_forest     PARSEC         Base           radius            0.9998880153089946
                                 mass_smaller_3 radius            0.9999160364095124
xgboost           PARSEC         Base           radius            0.9997269256609371
                                 mass_smaller_3 radius            0.9993660425000692

                                                                                MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.3373776625458338
                                 mass_smaller_3 radius              0.0914021384144007
KNN               PARSEC         Base           radius             0.28715046126687094
                                 mass_smaller_3 radius             0.03184811260315412
linear_regression PARSEC         Base           radius               0.115891857446936
                                 mass_smaller_3 radius              0.0927206479456104
mlp               PARSEC         Base           radius             0.08975244393297599
                                 mass_smaller_3 radius             0.07449609487630049
random_forest     PARSEC         Base           radius              0.2633429653822823
                                 mass_smaller_3 radius             0.03743111377761299
xgboost           PARSEC         Base           radius             0.15352155580429705
                                 mass_smaller_3 radius            0.040720456544565575

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00665 / 90 : 0.01939 / 95 : 0.02552 / 99 : 0.04732
                                 mass_smaller_3 radius               75 : 0.00354 / 90 : 0.0115 / 95 : 0.0156 / 99 : 0.02713
KNN               PARSEC         Base           radius             75 : 0.00805 / 90 : 0.01282 / 95 : 0.01738 / 99 : 0.04106
                                 mass_smaller_3 radius              75 : 0.00637 / 90 : 0.00973 / 95 : 0.01214 / 99 : 0.0181
linear_regression PARSEC         Base           radius             75 : 0.04435 / 90 : 0.06666 / 95 : 0.07915 / 99 : 0.09843
                                 mass_smaller_3 radius             75 : 0.05267 / 90 : 0.06823 / 95 : 0.07548 / 99 : 0.08406
mlp               PARSEC         Base           radius              75 : 0.02194 / 90 : 0.03285 / 95 : 0.0398 / 99 : 0.05137
                                 mass_smaller_3 radius             75 : 0.02136 / 90 : 0.03361 / 95 : 0.03953 / 99 : 0.05522
random_forest     PARSEC         Base           radius             75 : 0.00272 / 90 : 0.00772 / 95 : 0.01204 / 99 : 0.02904
                                 mass_smaller_3 radius             75 : 0.00139 / 90 : 0.00461 / 95 : 0.00715 / 99 : 0.01308
xgboost           PARSEC         Base           radius              75 : 0.01319 / 90 : 0.0197 / 95 : 0.02477 / 99 : 0.03776
                                 mass_smaller_3 radius             75 : 0.00993 / 90 : 0.01424 / 95 : 0.01693 / 99 : 0.02264

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 3.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
KNN               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
linear_regression PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
mlp               PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
random_forest     PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694
xgboost           PARSEC         Base           radius            0.287801729930226 - 2.8372727025023003
                                 mass_smaller_3 radius             0.287801729930226 - 2.363235804483694

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9994904612363711
                                 mass_smaller_3 radius            0.9992237737991333
KNN               PARSEC         Base           radius             0.999784625565223
                                 mass_smaller_3 radius            0.9996424232779713
linear_regression PARSEC         Base           radius            0.9915387683822118
                                 mass_smaller_3 radius            0.9895728506042913
mlp               PARSEC         Base           radius            0.9986278453208044
                                 mass_smaller_3 radius            0.9965685370464973
random_forest     PARSEC         Base           radius            0.9998608333998817
                                 mass_smaller_3 radius            0.9997840970072561
xgboost           PARSEC         Base           radius            0.9995498589485197
                                 mass_smaller_3 radius            0.9991753397329046

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.010605365266839068
                                 mass_smaller_3 radius            0.010221612236998565
KNN               PARSEC         Base           radius            0.006896922823218741
                                 mass_smaller_3 radius            0.006936143539130608
linear_regression PARSEC         Base           radius             0.04356724066953018
                                 mass_smaller_3 radius             0.03811731136696356
mlp               PARSEC         Base           radius             0.01948808370186567
                                 mass_smaller_3 radius              0.0277188418428713
random_forest     PARSEC         Base           radius            0.005554155361236285
                                 mass_smaller_3 radius            0.005394289221614665
xgboost           PARSEC         Base           radius            0.009974108532178276
                                 mass_smaller_3 radius            0.010535463146695411

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.004374327701513734
                                 mass_smaller_3 radius             0.004170037587936136
KNN               PARSEC         Base           radius            0.0043629312172513875
                                 mass_smaller_3 radius              0.00424849435914566
linear_regression PARSEC         Base           radius             0.030995615888437893
                                 mass_smaller_3 radius             0.030628705871080755
mlp               PARSEC         Base           radius             0.015286029270626764
                                 mass_smaller_3 radius              0.02037368195273429
random_forest     PARSEC         Base           radius             0.002267375033252322
                                 mass_smaller_3 radius             0.002151185925290235
xgboost           PARSEC         Base           radius             0.007081097780391801
                                 mass_smaller_3 radius             0.006998000624763989

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             2.220446049250313e-16
                                 mass_smaller_3 radius            1.1102230246251565e-16
KNN               PARSEC         Base           radius              0.002250892214549105
                                 mass_smaller_3 radius              0.001906680560926799
linear_regression PARSEC         Base           radius              0.019344780814333218
                                 mass_smaller_3 radius               0.02706380065000724
mlp               PARSEC         Base           radius               0.01238592486761897
                                 mass_smaller_3 radius                0.0134834279681606
random_forest     PARSEC         Base           radius             0.0002714577975138077
                                 mass_smaller_3 radius            0.00026087134002472645
xgboost           PARSEC         Base           radius              0.005081283262506342
                                 mass_smaller_3 radius             0.0040328208399499355

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9997455275317765
                                 mass_smaller_3 radius            0.9996118475807706
KNN               PARSEC         Base           radius            0.9998923290951487
                                 mass_smaller_3 radius            0.9998214316233864
linear_regression PARSEC         Base           radius            0.9970571881034083
                                 mass_smaller_3 radius            0.9982849239340472
mlp               PARSEC         Base           radius            0.9993653315567101
                                 mass_smaller_3 radius            0.9983655495956483
random_forest     PARSEC         Base           radius            0.9999304541398153
                                 mass_smaller_3 radius             0.999892153662488
xgboost           PARSEC         Base           radius            0.9997753546480828
                                 mass_smaller_3 radius            0.9995876001666243

                                                                               MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.20009427114687028
                                 mass_smaller_3 radius            0.16021197089478767
KNN               PARSEC         Base           radius            0.06743555362299958
                                 mass_smaller_3 radius            0.06897673185942099
linear_regression PARSEC         Base           radius            0.16975441678187275
                                 mass_smaller_3 radius            0.13507473500461264
mlp               PARSEC         Base           radius            0.07866869316395736
                                 mass_smaller_3 radius            0.09327647380319826
random_forest     PARSEC         Base           radius             0.1142642686289066
                                 mass_smaller_3 radius            0.07990824443986533
xgboost           PARSEC         Base           radius            0.10406817392968648
                                 mass_smaller_3 radius            0.10583349648732687

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00313 / 90 : 0.01749 / 95 : 0.02603 / 99 : 0.04039
                                 mass_smaller_3 radius             75 : 0.00188 / 90 : 0.01722 / 95 : 0.02595 / 99 : 0.03791
KNN               PARSEC         Base           radius             75 : 0.00643 / 90 : 0.01145 / 95 : 0.01513 / 99 : 0.02357
                                 mass_smaller_3 radius              75 : 0.00619 / 90 : 0.01142 / 95 : 0.01539 / 99 : 0.0246
linear_regression PARSEC         Base           radius             75 : 0.04228 / 90 : 0.07698 / 95 : 0.09991 / 99 : 0.13118
                                 mass_smaller_3 radius             75 : 0.04392 / 90 : 0.06248 / 95 : 0.07272 / 99 : 0.09733
mlp               PARSEC         Base           radius             75 : 0.02187 / 90 : 0.03281 / 95 : 0.03944 / 99 : 0.05118
                                 mass_smaller_3 radius             75 : 0.03164 / 90 : 0.04736 / 95 : 0.05745 / 99 : 0.08024
random_forest     PARSEC         Base           radius               75 : 0.00178 / 90 : 0.0075 / 95 : 0.01174 / 99 : 0.0229
                                 mass_smaller_3 radius               75 : 0.00137 / 90 : 0.00721 / 95 : 0.0117 / 99 : 0.0232
xgboost           PARSEC         Base           radius              75 : 0.00985 / 90 : 0.0159 / 95 : 0.02011 / 99 : 0.03105
                                 mass_smaller_3 radius              75 : 0.0098 / 90 : 0.01772 / 95 : 0.02303 / 99 : 0.03371

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 4.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
KNN               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
linear_regression PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
mlp               PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
random_forest     PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076
xgboost           PARSEC         Base           radius            0.7818989193511491 - 2.8272399995056454
                                 mass_smaller_3 radius              0.7818989193511491 - 1.61689542640076

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9999406107262824
                                 mass_smaller_3 radius            0.9995559266795759
KNN               PARSEC         Base           radius            0.9999768995098975
                                 mass_smaller_3 radius            0.9997266316533598
linear_regression PARSEC         Base           radius            0.9951095719996579
                                 mass_smaller_3 radius            0.8477314192044365
mlp               PARSEC         Base           radius             0.998980432794861
                                 mass_smaller_3 radius            0.9578594679595471
random_forest     PARSEC         Base           radius            0.9999855628563304
                                 mass_smaller_3 radius            0.9998423191513232
xgboost           PARSEC         Base           radius            0.9998253022554717
                                 mass_smaller_3 radius            0.9986720832493132

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0023172748191803553
                                 mass_smaller_3 radius             0.001536246564018064
KNN               PARSEC         Base           radius            0.0014452873699317566
                                 mass_smaller_3 radius            0.0012052479092144299
linear_regression PARSEC         Base           radius             0.023065644857497684
                                 mass_smaller_3 radius              0.02899528917560975
mlp               PARSEC         Base           radius             0.011434676061494347
                                 mass_smaller_3 radius             0.015751350044846967
random_forest     PARSEC         Base           radius             0.001142507567010268
                                 mass_smaller_3 radius            0.0009153923031587905
xgboost           PARSEC         Base           radius             0.003974805185021588
                                 mass_smaller_3 radius             0.002656391578316406

                                                                                     MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0004145308089903146
                                 mass_smaller_3 radius            0.00028145531288364413
KNN               PARSEC         Base           radius            0.00048301109870547564
                                 mass_smaller_3 radius            0.00037890558760497473
linear_regression PARSEC         Base           radius              0.018915119745092305
                                 mass_smaller_3 radius               0.02357419503812564
mlp               PARSEC         Base           radius              0.008496946293123557
                                 mass_smaller_3 radius              0.010929083801903652
random_forest     PARSEC         Base           radius            0.00027538097882099044
                                 mass_smaller_3 radius             0.0002167139419049085
xgboost           PARSEC         Base           radius             0.0025735369304180585
                                 mass_smaller_3 radius             0.0017508525149562523

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            5.2555755119643166e-05
                                 mass_smaller_3 radius             6.598325960793794e-05
KNN               PARSEC         Base           radius            0.00016722603861696328
                                 mass_smaller_3 radius            0.00016258100649602092
linear_regression PARSEC         Base           radius              0.016702120725859304
                                 mass_smaller_3 radius              0.020356031581365785
mlp               PARSEC         Base           radius              0.006983624468918981
                                 mass_smaller_3 radius              0.006435361571558218
random_forest     PARSEC         Base           radius              7.90396769673185e-05
                                 mass_smaller_3 radius             8.252627108618071e-05
xgboost           PARSEC         Base           radius              0.001669202880062226
                                 mass_smaller_3 radius             0.0011812526351285824

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9999703057649802
                                 mass_smaller_3 radius             0.999778019903856
KNN               PARSEC         Base           radius            0.9999884513498838
                                 mass_smaller_3 radius            0.9998633524518141
linear_regression PARSEC         Base           radius            0.9979019818511545
                                 mass_smaller_3 radius            0.9272024216871227
mlp               PARSEC         Base           radius             0.999513987103144
                                 mass_smaller_3 radius            0.9787037556439331
random_forest     PARSEC         Base           radius            0.9999927818084571
                                 mass_smaller_3 radius             0.999921345709472
xgboost           PARSEC         Base           radius            0.9999126475304364
                                 mass_smaller_3 radius            0.9993360891568229

                                                                                MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.09764087379423292
                                 mass_smaller_3 radius             0.07513268713165133
KNN               PARSEC         Base           radius             0.04019665251667126
                                 mass_smaller_3 radius            0.051572168364900195
linear_regression PARSEC         Base           radius              0.0722175005332415
                                 mass_smaller_3 radius             0.09302018077783347
mlp               PARSEC         Base           radius             0.07545871784276759
                                 mass_smaller_3 radius             0.08846152780966454
random_forest     PARSEC         Base           radius             0.04686962927122429
                                 mass_smaller_3 radius              0.0538866131618958
xgboost           PARSEC         Base           radius            0.050581523468025136
                                 mass_smaller_3 radius            0.040643201474116264

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              75 : 0.00027 / 90 : 0.00042 / 95 : 0.0008 / 99 : 0.00947
                                 mass_smaller_3 radius             75 : 0.00027 / 90 : 0.00041 / 95 : 0.00063 / 99 : 0.00357
KNN               PARSEC         Base           radius             75 : 0.00034 / 90 : 0.00072 / 95 : 0.00169 / 99 : 0.00741
                                 mass_smaller_3 radius             75 : 0.00032 / 90 : 0.00056 / 95 : 0.00096 / 99 : 0.00589
linear_regression PARSEC         Base           radius               75 : 0.028 / 90 : 0.03842 / 95 : 0.04386 / 99 : 0.05087
                                 mass_smaller_3 radius              75 : 0.03438 / 90 : 0.04855 / 95 : 0.0563 / 99 : 0.06808
mlp               PARSEC         Base           radius             75 : 0.01132 / 90 : 0.01622 / 95 : 0.02247 / 99 : 0.03948
                                 mass_smaller_3 radius              75 : 0.01386 / 90 : 0.03106 / 95 : 0.03487 / 99 : 0.0398
random_forest     PARSEC         Base           radius             75 : 0.00023 / 90 : 0.00039 / 95 : 0.00062 / 99 : 0.00506
                                 mass_smaller_3 radius              75 : 0.00022 / 90 : 0.00038 / 95 : 0.0005 / 99 : 0.00242
xgboost           PARSEC         Base           radius               75 : 0.00324 / 90 : 0.00571 / 95 : 0.0081 / 99 : 0.0149
                                 mass_smaller_3 radius              75 : 0.00227 / 90 : 0.00383 / 95 : 0.0052 / 99 : 0.00946

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 5.0

                                                                                             value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
KNN               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
linear_regression PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
mlp               PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
random_forest     PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768
xgboost           PARSEC         Base           radius            0.8787515201730021 - 2.669967369908504
                                 mass_smaller_3 radius             0.8787515201730021 - 1.29928933408768

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9993008112866536
                                 mass_smaller_3 radius            0.9985002596700449
KNN               PARSEC         Base           radius            0.9994091628111624
                                 mass_smaller_3 radius            0.9983294737183708
linear_regression PARSEC         Base           radius            0.9950196502567669
                                 mass_smaller_3 radius            0.9711214679512491
mlp               PARSEC         Base           radius            0.9974148674207028
                                 mass_smaller_3 radius            0.9613792075396019
random_forest     PARSEC         Base           radius            0.9996457109183167
                                 mass_smaller_3 radius            0.9994668477445788
xgboost           PARSEC         Base           radius            0.9992295203371921
                                 mass_smaller_3 radius            0.9968773384630246

                                                                                   RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.012790091588503324
                                 mass_smaller_3 radius            0.0031628663722878545
KNN               PARSEC         Base           radius             0.011790715792866873
                                 mass_smaller_3 radius            0.0034230505460183217
linear_regression PARSEC         Base           radius              0.04660755502373354
                                 mass_smaller_3 radius                0.057267908481538
mlp               PARSEC         Base           radius             0.024693161590720925
                                 mass_smaller_3 radius             0.016291897272706257
random_forest     PARSEC         Base           radius               0.0091472399988179
                                 mass_smaller_3 radius            0.0018909142619881838
xgboost           PARSEC         Base           radius             0.013566469883373242
                                 mass_smaller_3 radius             0.004597502190557579

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.0029726995500074884
                                 mass_smaller_3 radius             0.001044950231789087
KNN               PARSEC         Base           radius              0.00434602907149593
                                 mass_smaller_3 radius             0.001772739615604261
linear_regression PARSEC         Base           radius               0.0327935163416101
                                 mass_smaller_3 radius              0.05557380098473808
mlp               PARSEC         Base           radius             0.015296575096862343
                                 mass_smaller_3 radius             0.011319649735136461
random_forest     PARSEC         Base           radius             0.002223916416064363
                                 mass_smaller_3 radius            0.0006995581402447289
xgboost           PARSEC         Base           radius             0.007980814365370438
                                 mass_smaller_3 radius            0.0036251873247033274

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.0003173507498925865
                                 mass_smaller_3 radius            0.00042557032499268566
KNN               PARSEC         Base           radius             0.0008880980986489817
                                 mass_smaller_3 radius             0.0005690530358022361
linear_regression PARSEC         Base           radius              0.027887800106872085
                                 mass_smaller_3 radius              0.061508216369504654
mlp               PARSEC         Base           radius              0.010592197214744914
                                 mass_smaller_3 radius              0.006157902371664692
random_forest     PARSEC         Base           radius            0.00031720567477755424
                                 mass_smaller_3 radius            0.00031478649437755024
xgboost           PARSEC         Base           radius               0.00532834166484486
                                 mass_smaller_3 radius              0.003057132855861955

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9996505953712973
                                 mass_smaller_3 radius            0.9992499379788913
KNN               PARSEC         Base           radius            0.9997062599547997
                                 mass_smaller_3 radius            0.9991643881247408
linear_regression PARSEC         Base           radius            0.9975096978863107
                                 mass_smaller_3 radius            0.9888384382922044
mlp               PARSEC         Base           radius            0.9987082578110156
                                 mass_smaller_3 radius            0.9825553676873169
random_forest     PARSEC         Base           radius            0.9998244527403095
                                 mass_smaller_3 radius            0.9997333921404862
xgboost           PARSEC         Base           radius            0.9996163947747951
                                 mass_smaller_3 radius             0.998460484525768

                                                                                MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius              0.3229547237977053
                                 mass_smaller_3 radius             0.04389922961135562
KNN               PARSEC         Base           radius             0.19042978845374114
                                 mass_smaller_3 radius             0.01967671744429278
linear_regression PARSEC         Base           radius             0.28767415982826305
                                 mass_smaller_3 radius             0.07816356336038133
mlp               PARSEC         Base           radius              0.2437543431675493
                                 mass_smaller_3 radius            0.049632035033301936
random_forest     PARSEC         Base           radius             0.18906191718489085
                                 mass_smaller_3 radius            0.027707168810690463
xgboost           PARSEC         Base           radius              0.1760073536087432
                                 mass_smaller_3 radius            0.021593211454038475

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00091 / 90 : 0.00525 / 95 : 0.01429 / 99 : 0.05224
                                 mass_smaller_3 radius              75 : 0.00084 / 90 : 0.00149 / 95 : 0.00256 / 99 : 0.0159
KNN               PARSEC         Base           radius             75 : 0.00428 / 90 : 0.00969 / 95 : 0.01548 / 99 : 0.06408
                                 mass_smaller_3 radius             75 : 0.00163 / 90 : 0.00563 / 95 : 0.00877 / 99 : 0.01379
linear_regression PARSEC         Base           radius             75 : 0.04486 / 90 : 0.05235 / 95 : 0.08853 / 99 : 0.18383
                                 mass_smaller_3 radius             75 : 0.06443 / 90 : 0.06709 / 95 : 0.06776 / 99 : 0.06873
mlp               PARSEC         Base           radius             75 : 0.01907 / 90 : 0.03041 / 95 : 0.04039 / 99 : 0.10363
                                 mass_smaller_3 radius             75 : 0.01573 / 90 : 0.03276 / 95 : 0.03661 / 99 : 0.04102
random_forest     PARSEC         Base           radius             75 : 0.00084 / 90 : 0.00398 / 95 : 0.00949 / 99 : 0.04178
                                 mass_smaller_3 radius             75 : 0.00064 / 90 : 0.00111 / 95 : 0.00186 / 99 : 0.01024
xgboost           PARSEC         Base           radius              75 : 0.00979 / 90 : 0.0157 / 95 : 0.02181 / 99 : 0.05548
                                 mass_smaller_3 radius             75 : 0.00514 / 90 : 0.00743 / 95 : 0.00908 / 99 : 0.01209

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Results for the label category with a value of 6.0

                                                                                              value range  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
KNN               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
linear_regression PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
mlp               PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
random_forest     PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316
xgboost           PARSEC         Base           radius            0.9630791606418272 - 2.7777891874348675
                                 mass_smaller_3 radius             0.9405164849325672 - 1.434888120867316

                                                                                 RVE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9982733912722314
                                 mass_smaller_3 radius            0.9839436883371594
KNN               PARSEC         Base           radius            0.9988457609872196
                                 mass_smaller_3 radius            0.9948795989215731
linear_regression PARSEC         Base           radius            0.9938204223034984
                                 mass_smaller_3 radius            0.9758562250537882
mlp               PARSEC         Base           radius             0.996489916749048
                                 mass_smaller_3 radius            0.9545216385511809
random_forest     PARSEC         Base           radius            0.9992773806051242
                                 mass_smaller_3 radius             0.993055464213851
xgboost           PARSEC         Base           radius             0.998657995170862
                                 mass_smaller_3 radius            0.9945621318639318

                                                                                  RMSE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.015943395806649958
                                 mass_smaller_3 radius            0.012532746800063225
KNN               PARSEC         Base           radius             0.01337551466856542
                                 mass_smaller_3 radius            0.009660258116975032
linear_regression PARSEC         Base           radius             0.03748180640923165
                                 mass_smaller_3 radius             0.04744743202643385
mlp               PARSEC         Base           radius            0.024365015134507038
                                 mass_smaller_3 radius            0.021779263675548038
random_forest     PARSEC         Base           radius            0.010481750860972376
                                 mass_smaller_3 radius            0.008752124565757222
xgboost           PARSEC         Base           radius            0.014210503145176438
                                 mass_smaller_3 radius            0.008781990863034276

                                                                                    MAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.006177875770400056
                                 mass_smaller_3 radius             0.005621940722304129
KNN               PARSEC         Base           radius              0.00811523003286422
                                 mass_smaller_3 radius             0.007988083925745145
linear_regression PARSEC         Base           radius             0.024566169900052618
                                 mass_smaller_3 radius              0.04502517989556844
mlp               PARSEC         Base           radius              0.01864196664054924
                                 mass_smaller_3 radius             0.016357402467586043
random_forest     PARSEC         Base           radius             0.004452686895922855
                                 mass_smaller_3 radius            0.0042169779528986985
xgboost           PARSEC         Base           radius             0.010264634604581976
                                 mass_smaller_3 radius             0.006790348523725684

                                                                                   MedAE  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius                               0.0
                                 mass_smaller_3 radius                               0.0
KNN               PARSEC         Base           radius              0.005617249536714719
                                 mass_smaller_3 radius              0.007291738808021586
linear_regression PARSEC         Base           radius               0.01657723664389965
                                 mass_smaller_3 radius              0.046538402888514296
mlp               PARSEC         Base           radius               0.01519621147436423
                                 mass_smaller_3 radius              0.011913584139525257
random_forest     PARSEC         Base           radius             0.0005275781194788998
                                 mass_smaller_3 radius            0.00029191978895282134
xgboost           PARSEC         Base           radius              0.007910371150113282
                                 mass_smaller_3 radius              0.005234726267147494

                                                                                CORR  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius            0.9991377344602529
                                 mass_smaller_3 radius            0.9924837998433284
KNN               PARSEC         Base           radius            0.9994281827782255
                                 mass_smaller_3 radius            0.9975726994243539
linear_regression PARSEC         Base           radius            0.9969471786898386
                                 mass_smaller_3 radius            0.9884732598929342
mlp               PARSEC         Base           radius            0.9982498046347414
                                 mass_smaller_3 radius            0.9794101482288976
random_forest     PARSEC         Base           radius            0.9996389424730997
                                 mass_smaller_3 radius            0.9967895159909602
xgboost           PARSEC         Base           radius            0.9993395471101976
                                 mass_smaller_3 radius            0.9976901847323958

                                                                                MAX_ER  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             0.25638704171264703
                                 mass_smaller_3 radius             0.08495731833646358
KNN               PARSEC         Base           radius              0.1687904484512912
                                 mass_smaller_3 radius             0.02797510507929224
linear_regression PARSEC         Base           radius             0.22111228638643254
                                 mass_smaller_3 radius             0.07657648525669547
mlp               PARSEC         Base           radius              0.1532226811964974
                                 mass_smaller_3 radius             0.06080850937504789
random_forest     PARSEC         Base           radius             0.13645471108258822
                                 mass_smaller_3 radius            0.049872487325862025
xgboost           PARSEC         Base           radius             0.12353177573704421
                                 mass_smaller_3 radius             0.03595027018081032

                                                                                                                  Percentiles  \
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             75 : 0.00656 / 90 : 0.01915 / 95 : 0.03033 / 99 : 0.06953
                                 mass_smaller_3 radius             75 : 0.00604 / 90 : 0.01949 / 95 : 0.02698 / 99 : 0.05645
KNN               PARSEC         Base           radius             75 : 0.01013 / 90 : 0.01569 / 95 : 0.02182 / 99 : 0.05852
                                 mass_smaller_3 radius             75 : 0.01172 / 90 : 0.01542 / 95 : 0.01789 / 99 : 0.02237
linear_regression PARSEC         Base           radius              75 : 0.03082 / 90 : 0.05156 / 95 : 0.0835 / 99 : 0.14989
                                 mass_smaller_3 radius             75 : 0.05662 / 90 : 0.06352 / 95 : 0.06757 / 99 : 0.07262
mlp               PARSEC         Base           radius             75 : 0.02618 / 90 : 0.03718 / 95 : 0.04612 / 99 : 0.07668
                                 mass_smaller_3 radius             75 : 0.02315 / 90 : 0.04082 / 95 : 0.04557 / 99 : 0.05552
random_forest     PARSEC         Base           radius             75 : 0.00441 / 90 : 0.01383 / 95 : 0.02143 / 99 : 0.04544
                                 mass_smaller_3 radius                75 : 0.00503 / 90 : 0.01525 / 95 : 0.021 / 99 : 0.0335
xgboost           PARSEC         Base           radius                75 : 0.01383 / 90 : 0.02107 / 95 : 0.02714 / 99 : 0.05
                                 mass_smaller_3 radius             75 : 0.01007 / 90 : 0.01466 / 95 : 0.01787 / 99 : 0.02303

                                                                                 time
model             physical_model filter         output_parameter
decision_tree     PARSEC         Base           radius             6.6589062213897705
                                 mass_smaller_3 radius              5.519447326660156
KNN               PARSEC         Base           radius              3.132415533065796
                                 mass_smaller_3 radius             2.1986701488494873
linear_regression PARSEC         Base           radius             0.3206288814544678
                                 mass_smaller_3 radius            0.22408533096313477
mlp               PARSEC         Base           radius              197.3649926185608
                                 mass_smaller_3 radius              78.52664422988892
random_forest     PARSEC         Base           radius             100.59411668777466
                                 mass_smaller_3 radius             57.704763412475586
xgboost           PARSEC         Base           radius              6.120966196060181
                                 mass_smaller_3 radius              4.052688121795654

Linear regression : 
- mass_smaller_3 : worse/similar results than Base on every metric.

Decision tree : 
- mass_smaller_3 : better results than Base on every metric.

KNN : 
- mass_smaller_3 : better results than Base on every metric.

Random forest : 
- mass_smaller_3 : better results than Base on every metric.

XGBoost : 
- mass_smaller_3 : better results than Base on every metric.

MLP : 
- mass_smaller_3 : worse results than Base on every metric except MAX_ER.

#### Conclusions on radius

When filtering using mass_smaller_3, the results always improve except for linear regression.

&emsp; => using this filtering for the radius is very beneficial

#### Best models for the radius parameter

The three best performing models in order for the mass parameter are Random forest, Decision tree and KNN.

&emsp; => important to note that the MedAE for random forest and decision tree is very close to 0, actually 0 for decision tree. \
&emsp; &emsp; Same conclusion as with the mass parameter.

### Conclusion on both

Using the mass_smaller_3 filtering is beneficial for the radius but detrimental for the mass. 

Since the mass is more important in the first method, it is used as input for model B, the Base filtering will be used.